### PR TITLE
[stable] Prepare `TargetC` for ARM bit-fields special case

### PR DESCRIPTION
**Pull request by kinke**
Required for 32-bit ARM, and non-Apple 64-bit ARM targets.

The only difference to `Gcc_Clang` is that anonymous and 0-length bit-fields do contribute to the aggregate alignment.

Caught by existing proper C interop tests in `runnable_cxx/testbitfields.d` on such targets. The hardcoded bad tests in `runnable/{bitfieldsposix64.c,dbitfieldsposix64.d}` however now fail after the fix, on such targets again.

See https://github.com/ldc-developers/ldc/pull/4707#issuecomment-2239900730 and following.

### CODE REVIEW

**Comment by ibuclaw** [comment]
My preference would be to add a target hook for this. Looks like the behaviour you want is controlled by this macro in GCC (which doesn't explicitly match for a specific target/compiler combo)

https://gcc.gnu.org/onlinedocs/gccint/Storage-Layout.html#index-TARGET_005fALIGN_005fANON_005fBITFIELD

**Comment by kinke** [comment]
I hope this is the last bit-field special case in a while. If so, we'd only have these 3 `BitFieldStyle`s, no other config options or `Target` hooks to account for bit-field implementation details. If there'd be more to come, then yeah, the enum won't cut it anymore.

**Comment by ibuclaw** [comment]
> I hope this is the last bit-field special case in a while. If so, we'd only have these 3 `BitFieldStyle`s, no other config options or `Target` hooks to account for bit-field implementation details. If there'd be more to come, then yeah, the enum won't cut it anymore.

The docs suggest there are more permutations than just this gcc/clang/arm special case.

**Comment by kinke** [comment]
I hope we won't need much more in the near future. I guess the generic gcc options there also account for the 'Microsoft style' behavior; proper support for all gcc-supported targets would likely entail a rewrite of this frontend code, adding more complexity.

I'd refactored it to a `TargetC.contributesToAggregateAlignment(BitFieldDeclararation)` hook for now.

**Comment by ibuclaw** [comment]
> I hope we won't need much more in the near future. I guess the generic gcc options there also account for the 'Microsoft style' behavior;

Yes, I think it's PCC vs non-PCC bit field layouts.

> proper support for all gcc-supported targets would likely entail a rewrite of this frontend code, adding more complexity.

We're probably not far off how GCC code is, much like the clean room implementation of unwind exceptions follows the same logic flow.

**Comment by kinke** [comment]
Alright, you sound optimistic, good. :) - Anything else to do here?

**Review by dkorpel — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
