### PR TITLE
test: Move runnable tests for complex and imaginary types into runnable/complex.d

### PR DESCRIPTION
**Pull request by ibuclaw**
This is so that `-transition=complex` can be enabled by default, and everything passes cleanly.

### CODE REVIEW

**Comment by Geod24** [comment]
Shouldn't they just live in their own file pending removal ? So we don't inadvertently break them.

**Comment by ibuclaw** [comment]
> Shouldn't they just live in their own file pending removal ? So we don't inadvertently break them.

Maybe.  Ultimately the only thing that will be preserved is the ABI, and that is covered by the runnable_cxx tests.

The backend is still used by dmc, which as far as I know will still need complex type support, so the likelihood of something breaking is pretty unlikely.

**Comment by Geod24** [comment]
> The backend is still used by dmc, which as far as I know will still need complex type support, so the likelihood of something breaking is pretty unlikely.

DMC does not have a CI AFAIK, nor does it compile on other platforms than win32.

**Comment by RazvanN7** [comment]
When `-transition=complex` becomes the default, will we also have a `revert` switch for it? If yes, then we can simply keep the tests and use the revert switch.

**Comment by ibuclaw** [comment]
I don't see any point in having a revert switch until `-preview=complex` becomes the default, as it's just deprecation messages.

**Comment by ibuclaw** [comment]
@Geod24 merged all tests into complex.d, just ran the local branch I have that enabled `-transition=complex` by default, and there's around 862 lines of deprecation messages that will be added to that file if we keep it around until `-preview=complex`. ;-)

**Comment by Geod24** [comment]
> and there's around 862 lines of deprecation messages that will be added to that file 

`REQUIRED_ARGS: -d`

Problem solved.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
