### PR TITLE
Revert "[REG 2.071] Fix Issue 15925 - Import declaration from mixin templates are ignored"

### PR DESCRIPTION
**Pull request by WalterBright**
Reverts dlang/dmd#5724

The behavior is on purpose and as designed.

### CODE REVIEW

**Comment by MartinNowak** [comment]
I'll take care of checking integrating with transition import/checkimports.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
Thanks, @MartinNowak

**Comment by mathias-lang-sociomantic** [comment]
Why was this branch created in upstream ? There's 2 other 'revert' here BTW.

**Pull request merged**
