### PR TITLE
Fix Issue 17462 - Order of base interfaces affects compiler behavior

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by wilzbach** [comment]
@RazvanN7 

```
 ... compilable/fix17686.d          ()
Test failed.  The logged output:
/home/braddr/sandbox/at-client/pull-2994226-FreeBSD_32/dmd/generated/freebsd/release/32/dmd -conf= -m32 -Icompilable   -odgenerated/compilable -ofgenerated/compilable/fix17686_0.o -c compilable/fix17686.d
compilable/fix17686.d(29): Error: class fix17686.DOMImplementation!string.DOMImplementation.Document interface function `INode parentNode() @property` is not implemented
compilable/fix17686.d(29): Error: class fix17686.DOMImplementation!string.DOMImplementation.Document interface function `IDocument ownerDocument() @property` is not implemented
compilable/fix17686.d(31): Error: class fix17686.DOMImplementation!string.DOMImplementation.EntityReference interface function `INode parentNode() @property` is not implemented
compilable/fix17686.d(31): Error: class fix17686.DOMImplementation!string.DOMImplementation.EntityReference interface function `IDocument ownerDocument() @property` is not implemented


==============================
Test failed: expected rc == 0, exited with rc == 1
```

**Comment by RazvanN7** [comment]
@wilzbach I cannot reproduce locally the failing autotester test. It looks like a linking problem, altough the undefined symbol is present and there are no imports.

**Comment by RazvanN7** [comment]
@andralex I made the modifications so that whenever a class inherits another class and implements an interface the methods in the base class are considered to implement methods from the interface

**Comment by JinShil** [comment]
> Still, I don't like the fix. There is this line which looks like a bug to me [1] and I tried to comment it,
but that just makes the codegen scramble some function addresses and I have no idea why. Commenting that line will enable a more elegant fix.

If you can't address this at this time, that's fine.  Just file a detailed bug report so it can be revisited at a later time.

**Pull request closed without merging**
