### PR TITLE
issue 14564 - [REG2.067] dmd -property -unittest combination causes compiler error

### PR DESCRIPTION
**Pull request by aG0aep6G**
Was: #4850. Differences: targeting master now; removed `test/fail_compilation/diag8629.d` entirely; fixed `-property -w`.
## 

fixes issue 14564 - [REG2.067] dmd -property -unittest combination causes
compiler error

https://issues.dlang.org/show_bug.cgi?id=14564

The problem is that phobos isn't compatible with `-property`. And it looks like `-property`'s current behaviour isn't desired anymore.

The plan (also in `mars.c`):
- Step 1 (2.069): Ignore -property and warn about it.
- Step 2: Deprecate -property.
- Step 3: Remove -property. Throw an error when it's set.
- Step 4: Possibly reintroduce -property with different semantics.

To do if this gets agreed upon:
- update http://dlang.org/dmd-windows.html and friends,
- changelog entry.

An alternative way to fix issue 14564 would be to make phobos compatible with the current `-property`.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Ping @WalterBright, want to make sure this doesn't go unnoticed.
Also there is a pending PR to add a [dmd changelog](https://github.com/D-Programming-Language/dmd/pull/4872). This should be mentioned there.

**Comment by aG0aep6G** [comment]
> Can we please not make this a warning but instead go deprecate it outright?

fine with me

**Comment by MartinNowak** [comment]
Let's go on with this, Walter expressed his consent in #4850, and nobody is willing to maintain the current `-property` semantics.

**Comment by aG0aep6G** [comment]
You pulled this with the warning stage intact. Should I make a follow-up PR to skip that and go to deprecation stage directly, as @klickverbot suggested?

**Comment by MartinNowak** [comment]
> You pulled this with the warning stage intact. Should I make a follow-up PR to skip that and go to deprecation stage directly, as @klickverbot suggested?

Please do, I though the above commit did that.

**Comment by aG0aep6G** [comment]
> Please do, I though the above commit did that.

That was just a rebase for DDMD. Follow-up: #4955.

**Comment by aG0aep6G** [comment]
And a PR to remove documentation for `-property` from the website:
https://github.com/D-Programming-Language/dlang.org/pull/1081

**Pull request merged**
