### PR TITLE
Revert "fix Issue 23479 - ImportC recognizes .i and .c files, but not .h files"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/dmd#14636

This change breaks builds with unrelated C headers in the build tree of the same name.  This is also broken with incidental C sources, but headers are far more common to find in the build directories of mixed C/C++/D projects.

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by WalterBright** [comment]
@dkorpel @ibuclaw  #14636 solves a real problem - people would `import stdio;` and it wouldn't find `stdio.h`, and they'd be (rightfully) baffled. The rationale for reverting it needs more explanation. If both `foo.h` and `foo.c` exist in the same directory, why *wouldn't* `foo.h` be the right choice for ImportC? And if `foo.h` is there, and no `foo.c`, why fail to recognize `foo.h`?

**Comment by ibuclaw** [comment]
> @dkorpel @ibuclaw  #14636 solves a real problem - people would `import stdio;` and it wouldn't find `stdio.h`, and they'd be (rightfully) baffled. The rationale for reverting it needs more explanation. If both `foo.h` and `foo.c` exist in the same directory, why *wouldn't* `foo.h` be the right choice for ImportC? And if `foo.h` is there, and no `foo.c`, why fail to recognize `foo.h`?

You're framing it in the wrong context for which issues arise.

This PR fixes a regression in building mixed C++/D language projects - gdc bootstrap builds including. i.e druntime imports `gcc.config`, but the compiler doesn't find/import `gcc/config.d`, rather it imports a C++ header instead, and people are (rightfully) baffled.
If both `foo.d` and `foo.h` exist, why *wouldn't* `foo.d` be the right choice for ImportD? Why does the compiler instead import `foo.h` when this change is applied?

**Comment by WalterBright** [comment]
The fix would be to prefer foo.h over foo.d.

**Comment by WalterBright** [comment]
Line 211 does check for a .d extension first. So I still don't understand the problem with it.

**Comment by ibuclaw** [comment]
There is a link to the regression issue in #14636

https://issues.dlang.org/show_bug.cgi?id=23547

**Comment by ibuclaw** [comment]
> The fix would be to prefer foo.d over foo.h. Not ignore foo.h and say `import foo;` cannot be found.

It doesn't if foo.d is in an included directory.

**Comment by ibuclaw** [comment]
There is a link to the regression issue in #14636

https://issues.dlang.org/show_bug.cgi?id=23547

**Comment by WalterBright** [comment]
All files are looked up by examining each directory in the search path, and in each directory, each file extension is tried. The code behaved exactly as designed and how all other files are looked up when an extension is not provided.

In your case, there was a foo.h in the lookup path before foo.d, so it picked the foo.h.

How do you suggest searching a path for imports work? How should I respond to people who say "ImportC doesn't work" because it cannot find their .h file?

**Comment by WalterBright** [comment]
ping @ibuclaw

**Comment by Geod24** [comment]
> How should I respond to people who say "ImportC doesn't work" because it cannot find their .h file?

How do you respond to people saying "The new DMD release broke my project - again" because of a feature they do not use ?
There's no doubt this change needs to happen - the issue is that it currently breaks some people's code. I don't think @ibuclaw ended there randomly, he either suffered from the effect of this change, or got a bug report from someone that did.

**Comment by ibuclaw** [comment]
> How do you suggest searching a path for imports work? How should I respond to people who say "ImportC doesn't work" because it cannot find their .h file?

How should I respond to people who say "ImportD doesn't work" because it cannot find their .d file?

#14687 would be one compromise that would allow #14636 to be reapplied again without causing regression in issue 23547.

**Comment by WalterBright** [comment]
> How should I respond to people who say "ImportD doesn't work" because it cannot find their .d file?

1. rename the .h file or .d file
2. put the .d or .h file in a package
3. change the order of the search path

**Comment by WalterBright** [comment]
This is clearly controversial. Adding https://github.com/dlang/dmd/pull/14687 and promptly pulling it with no chance to respond is not good.

**Comment by WalterBright** [comment]
@geod24 https://github.com/dlang/dmd/pull/14687 is also going to break someone's project because it is flipping the search order around.

**Comment by ibuclaw** [comment]
> promptly pulling it with no chance to respond is not good.

Yes, promptly pulling things is a bear bug - see also #14681.

**Comment by WalterBright** [comment]
True, but at least it had a day, not an hour.

**Comment by ibuclaw** [comment]
> 1. rename the .h file or .d file

No.  These generated files have been around for a very long time (circa 1997 and 2004), and have never conflicted. The D module system has been working great until it was corrupted with this change.

> 2. put the .d or .h file in a package

Moving config.d to config/package.d does not work, it still prefers ImportC over ImportD.
```
include   ../generated/linux/release/64/../../../../druntime/import/importc.h
cpp -m64 -dD gcc/config.c -include ../generated/linux/release/64/../../../../druntime/import/importc.h config.i
import    gcc.config	(gcc/config.c)
```

>     3. change the order of the search path

The C file is not in the search path, it's being picked up because `-I.` is an implicit search path.

**Comment by Geod24** [comment]
> This is clearly controversial. Adding #14687 and promptly pulling it with no chance to respond is not good.

Apologies, I applied the same rationale to it I would apply to a revert, which is, in hindsight, wrong.
Didn't expect that much controversy, though.

**Comment by WalterBright** [comment]
> 1.

Of course the file names can be changed. BTW, I can't recall any non-trivial project from 20+ years ago of mine that, when compiled with a modern C/C++ compiler, didn't need something changed in it.

> 2.

Importing "baz.foo" is not going to pick "foo.c" out of the default directory.

> 3.

Move the .c file to a directory on the search path.

In any case, every projected I've encountered that had different source files with the same base name has been a source of confusion, and should be avoided.

**Comment by WalterBright** [comment]
@Geod24 I understand. I didn't expect any controversy, either. I put the .c file lookup in a year ago, and there was not a single word said about it, let alone any protest, bug reports, anything.

**Comment by ibuclaw** [comment]
> > 1.
> 
> Of course the file names can be changed. BTW, I can't recall any non-trivial project from 20+ years ago of mine that, when compiled with a modern C/C++ compiler, didn't need something changed in it.
> 
> > 2.
> 
> Importing "baz.foo" is not going to pick "foo.c" out of the default directory.
> 
> > 3.
> 
> Move the .c file to a directory on the search path.
> 
> In any case, every projected I've encountered that had different source files with the same base name has been a source of confusion, and should be avoided.

Ignoring the build-generated, in upstream, breaks thousands of downstream users aspect to renaming/moving aspect, as that is just an aside.

All suggestions contradict

> Or more precisely, it shouldn't matter to the importer how the importee is implemented.

**Comment by WalterBright** [comment]
Sounds like a good use case for `-revert=hfiles`

**Comment by dkorpel** [comment]
> I put the .c file lookup in a year ago, and there was not a single word said about it, let alone any protest, bug reports, anything.

That's plain wrong, this exact issue was pointed out right from the get-go:

https://github.com/dlang/dmd/pull/12507#discussion_r630986639
https://github.com/dlang/dmd/pull/12507#issuecomment-843113110

**Comment by ibuclaw** [comment]
> Sounds like a good use case for `-revert=hfiles`

There shouldn't be a flag to reinstate the correct pre-2.098 import behaviour.

**Comment by WalterBright** [comment]
please continue here: https://github.com/dlang/dmd/pull/14687#issuecomment-1350420496

**Pull request merged**
