### PR TITLE
[DDMD] [cleanup] Move lexer's string table into Identifier and clean up imports

### PR DESCRIPTION
**Pull request by yebblies**
Part 2.

This one removes `Lexer::idPool` and `Lexer::uniqueId` in favor of the equivalent functions in `Identifier`.
With this done nothing needs to import `lexer` to generate `Identifier`s.

Now we can almost isolate `lexer`/`id`/`identifier`/`tokens` + a few from `root` and build them without needing the rest of the compiler.  The remaining offenders are all in `mars.h` and will be addressed in the next pull.

Changes:
- Replace `Lexer::idPool` with `Identifier::idPool` and `Lexer::uniqueId` with `Identifier::generateId`
- Move keywords and `Token::tochars` init into `tokens.c`
- Replace direct access to `stringtable` with `Identifier::lookup` etc
- Remove unnecessary `#include`s of `lexer.h`

### CODE REVIEW

**Comment by yebblies** [comment]
All green.

**Comment by 9rnsr** [comment]
Looks good!

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Comment by yebblies** [comment]
@RazvanN7

**Pull request merged**
