### PR TITLE
[refactor] Create typeid() expressions instead of invoking getTypeInfo directly

### PR DESCRIPTION
**Pull request by yebblies**
Semantic should lower them to the same thing.

### CODE REVIEW

**Comment by 9rnsr** [comment]
For the TypeInfo arrays on D variadic function calls, additional `semantic()` call would be necessary.

**Comment by yebblies** [comment]
Added `semantic` call.

**Comment by ibuclaw** [comment]
:+1: so long as you can get testsuite passing.

**Comment by yebblies** [comment]
Passes now.

**Comment by yebblies** [comment]
All green, anyone?

**Comment by 9rnsr** [comment]
OK, LGTM.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Pull request merged**
