### PR TITLE
Ignore unsafe and impure code in any contract and catch all Exceptions (fixes issue 4995 and regression 10981)

### PR DESCRIPTION
**Pull request by hpohl**
http://d.puremagic.com/issues/show_bug.cgi?id=4995
http://d.puremagic.com/issues/show_bug.cgi?id=10981

### CODE REVIEW

**Comment by andralex** [comment]
this has kinda bitrotten... please rebase?

**Comment by hpohl** [comment]
Don't have the time to rebase all that stuff. Feel free to close. May come back at some point.

**Comment by wilzbach** [comment]
As this is still based on the C++ frontend, it might take a serious effort to revive it.
Though there's some automation - see https://github.com/dlang/dmd/pull/4922#issuecomment-133776696

**Comment by RazvanN7** [comment]
I am planning on adopting this, however, I would like to iron down what is the way forever. After reading the comments, I personally think that the best strategy would be:

1. **Nothrow**: if the invariant is marked as `nothrow` then we must mechanically enforce that it does not throw. If `nothrow` is not present, then all exceptions are converted into errors.

2. **Safe**, **pure**, **nogc** and mutability qualifiers apply as normal and are mechanically checked. Since you slapped them on, then you must want them.

What do you think about this? @andralex @WalterBright @hpohl

**Pull request closed without merging**
