### PR TITLE
support dmd feature branches for CI

### PR DESCRIPTION
**Pull request by MartinNowak**
- fallback to master branch for druntime/phobos when
  an identical named feature branch doesn't exist

@UplinkCoder

### CODE REVIEW

**Review by UplinkCoder — APPROVED** [review]
LGTM

**Comment by WalterBright** [comment]
The travis-ci tests fail with:
```
core.exception.AssertError@std/typecons.d(2757): unittest failure
```

**Comment by MartinNowak** [comment]
> The travis-ci tests fail with:
> 
> core.exception.AssertError@std/typecons.d(2757): unittest failure

First time that I see this w/ gdc, hard to believe that it has anything to do w/ this PR.
Just restarted the [Job #5921.3](https://travis-ci.org/dlang/dmd/jobs/162355940), but maybe some independent phobos change introduced a problem.

**Comment by MartinNowak** [comment]
The problem seems to come from [Issue 11135 - Nullable(T, T nullValue) does not support NaN by Cauterite · Pull Request #3797 · dlang/phobos](https://github.com/dlang/phobos/pull/3797). Not sure why only the gdc built dmd compiler fails, any ideas @jpf91 @ibuclaw?

**Comment by ibuclaw** [comment]
I have none, but you could do an object file comparison to find out what's different between dmd built by itself vs gdc.

You need to turn off that hash table that writes symbols in a random order, if I recall correctly.

**Comment by MartinNowak** [comment]
> I have none, but you could do an object file comparison to find out what's different between dmd built by itself vs gdc.

Yeah, comparing the generated phobos object might work w/ a reduced test case.
BTW, should we use a newer gdc version for CI @ibuclaw? Why is LATEST still on 4.9.3 instead of 5.2.0?
And what are your release schedules? Seems like you don't keep up w/ gcc as well.
Maybe let's discuss this in person at the next D meetup or somewhen else.

**Pull request merged**
