### PR TITLE
convert register pair move to two single register moves

### PR DESCRIPTION
**Pull request by WalterBright**
The code generator handles single register operations a lot better than register pair operations.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=15861

**Comment by WalterBright** [comment]
Thanks for tracking the regression down.

**Comment by CyberShadow** [comment]
Always a pleasure :)

**Pull request merged**
