### PR TITLE
Ignore .vs Visual Studio files

### PR DESCRIPTION
**Pull request by baziotis**

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Comment by baziotis** [comment]
Sorry, I just don't seem to get what I'm doing wrong.

**Comment by jacob-carlborg** [comment]
Pushed to the wrong branch?

**Comment by baziotis** [comment]
Pushed new changes on the same branch because I didn't now that it will also go on the PR. And then Seb told me that each PR should go on separate branch.. So yeah, hopefully not so dumb next time :P Thanks for the patience!

**Comment by jacob-carlborg** [comment]
Yeah, one needs to be able to push new things to a pull request to apply changes according to the review.

**Comment by thewilsonator** [comment]
No problem, thanks for the great work!

**Pull request closed without merging**
