### PR TITLE
use shared phobos library by default on linux

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by WalterBright** [comment]
I'm not sure this is a good idea.

**Comment by Geod24** [comment]
Please don't.
It'll make it impossible (in practice) to have 2 executables depending on a different version of the compiler. There's not a lot of packages currently that are built in D, and with this change, there won't be any.

With this change, if you install a binary that depends on a shared library, you'll need to have the same version of libphobos the program was compiled with. Which in turns forces package maintainers to patch our crazy versioning scheme. You're supposed to be able to start a library compiled with X.YY with a shared library which version is > X.YY. I'm not aware of any released version where that was the case.

**Comment by MartinNowak** [comment]
Fine with me, @Dicebot can you undo this for ArchLinux as well.

**Comment by ibuclaw** [comment]
> Developers shipping binaries may not be sophisticated enough to get the .so installed correctly on their customers' machines.

Developers shipping binaries should always use static.

I don't see why you are telling package maintainers to not ship shared libraries.  @Dicebot might have something different in mind but I see shared libraries as their own package, which D programs depend upon.  Then static libraries are bundle with the development packages along with sources and a compiler.

**Comment by ibuclaw** [comment]
And I'd pretty much call it standard procedure to trigger a rebuild if any source dependencies have changed in a OS distribution.  Eg: new compiler, new vibe.d library, etc...

**Pull request closed without merging**
