### PR TITLE
Extract staticcond.evalStaticCondition and move it to expressionsem

### PR DESCRIPTION
**Pull request by tw1gz**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by tw1gz** [comment]
I'm on Linux, so can't reproduce the failed OSX checks. Locally, `compiler/src/build.d` completes successfully. Are these failures OK?

**Comment by thewilsonator** [comment]
yes, they are expected at the moment

**Comment by dkorpel** [comment]
What's the reason to move it to expressionsem?

**Comment by tw1gz** [comment]
@dkorpel I'm following along with https://github.com/dlang/dmd/blob/master/CONTRIBUTING.md#refactoring-the-dmd-ast

**Comment by dkorpel** [comment]
I don't see any classes in staticcond.d, it just contains a few helper functions. @RazvanN7 was that file added to the list by mistake?

**Comment by dkorpel** [comment]
It's imported only in `TemplateDeclaration.getConstraintEvalError`, is that going to stay?

**Comment by RazvanN7** [comment]
I have no idea just by looking at the code.

**Pull request merged**
