### PR TITLE
dtoh: do not write exact compiler version in silent mode

### PR DESCRIPTION
**Pull request by wilzbach**
The exact compiler version breaks `AUTO_UPDATE` and also will require unnecessary updates to `frontend.h`.

See also: https://github.com/dlang/dmd/pull/11679#discussion_r483178341

### CODE REVIEW

**Review by MoonlightSentinel — APPROVED** [review]

**Comment by UplinkCoder** [comment]
why does this break anything?

**Comment by MoonlightSentinel** [comment]
- The generated `frontend.h` will change with every new release due to this comment.
- `compilable/dtoh_***.d` use `$n$` to avoid this problem but `AUTO_UPDATE` overwrites special sequences

**Comment by wilzbach** [comment]
(+ also when people eventually start to generate headers like we do with `frontend.h` they will run into the same problems).

**Comment by MoonlightSentinel** [comment]
This change should probably be listed in the existing changelog entry.

**Comment by wilzbach** [comment]
> This change should probably be listed in the existing changelog entry.

Nah. This is implementation detail.

**Comment by MoonlightSentinel** [comment]
Fair enough

**Pull request merged**
