### PR TITLE
Issue 13006 - Allow inout return type without inout parameters

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=13006

### CODE REVIEW

**Comment by 9rnsr** [comment]
Rebased on master, and ready for ddmd.

**Comment by ibuclaw** [comment]
One year has passed, I rather like this too, any case to reopen discussion, or move to DIP?

**Comment by 9rnsr** [comment]
A forum discussion without DIP would be difficult to converge. I think creating a new DIP first is better.

**Comment by wilzbach** [comment]
> A forum discussion without DIP would be difficult to converge. I think creating a new DIP first is better.

Yep now we have proof that a [forum discussion](http://forum.dlang.org/thread/nepm2k$311l$1@digitalmars.com) is not converging.

> Then it was reused to mean const wildcard, with the reasoning that inout meant the 'out' const matched the 'in' type.
> This new meaning has no relation the the keyword 'inout'.

I agree, it's very confusing.

@9rnsr - how about proposing the DIP? :)

**Comment by ibuclaw** [comment]
Is a DIP still required for this?

**Comment by JinShil** [comment]
> Is a DIP still required for this?

@WalterBright and @andralex, can we get an official answer to this?

**Comment by andralex** [comment]
Affirmative. A DIP would be required. Thanks!

**Comment by andralex** [comment]
Someone would need to adopt this PR by the way.

**Comment by JinShil** [comment]
We have written record that this feature requires a DIP.  This PR, even if adopted, will not be merged until the DIP is approved.  Therefore, I am closing this until a champion emerges to write the DIP and adopt this PR.

**Pull request closed without merging**
