### PR TITLE
optimize VarDeclaration instance size

### PR DESCRIPTION
**Pull request by ghost**
Compiling dparse as a static library shows a reduction of the maximum resident set size by 2 Mb (from ~940Mb to ~938Mb).
This is because now an instance requires a small block in less (on x86_64 from 305 to 297; i.e from 20 to 19 blocks of 16 Bytes)

### CODE REVIEW

**Review by ibuclaw — COMMENTED** [review]
I suspect that bool might be better for a few of these where the threshold for recursion is 1.

Likewise it looks like the layout needs adjusting for some classes to remove alignment holes that are still present.

**Comment by NilsLankila** [comment]
To put `align(1):` at the beginningof each class would fix the problem.
is there an equivalent in cpp ? I read about `alignas(1)` but it seems that the scope of this attribute iis restrlicted to the following declaration.

**Comment by ibuclaw** [comment]
That doesn't sound like a good idea. X86 may be very forgiving in allowing unaligned loads, but they are the exception not the rule.

**Comment by NilsLankila** [comment]
Anyway, consider this PR as ready.

**Comment by NilsLankila** [comment]
I'll keep foxued on VarDeclaration as the other changes are slightly unrelated or with no impact.

**Comment by ibuclaw** [comment]
Again, I wonder why we can't use bool here.

It's only use:
```
dsym.canassign++;
exp = exp.expressionSemantic(sc);
dsym.canassign--;
```
Could just as easily be:
```
{
  bool canassign = dsym.canassign;
  dsym.canassign = true;
  exp = exp.expressionSemantic(sc);
  dsym.canassign = canassign;
}
```

**Pull request merged**
