### PR TITLE
Refactor: Reduce indent depth in FuncExp.genIdent

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by WalterBright** [comment]
I don't see the point. It's just churn. The stylistic issue is po-tay-toe po-tah-toe.

**Comment by 9rnsr** [comment]
When we converted dmd code to D, it had added one or more level indents. This change reduced indent level.

**Comment by WalterBright** [comment]
That's not what this PR is doing. Anyhow, I oppose refactorings of this sort. Refactorings that are more worthwhile are ones that are along these lines:

1. improve encapsulation
2. add const/purity/nothrow/@safe
3. reduce use of global variables
4. reduce use of allocated memory
5. reduce number of lines of code (not including comments or test cases)
6. reduce cyclomatic complexity
7. take advantage of D features (like using nested functions to improve clarity, using foreach, etc.)

**Comment by ZombineDev** [comment]
@WalterBright I think this is still a valid improvement (although a tiny one) that I would have done myself. I have noticed that @andralex also recommends doing early exits like that in other code reviews.
Often changes like 1) or 5) require other changes before they can be applied.
Are you saying that you generally accept only large improvements and reject small ones?

**Comment by WalterBright** [comment]
> Are you saying that you generally accept only large improvements and reject small ones?

This is a very tiny, and debatable, improvement at the cost of a large diff, which causes its own problems.

**Comment by WalterBright** [comment]
More bluntly, I do not want this to be used as justification for wholesale churning of tens of thousands of lines over a triviality.

**Pull request closed without merging**
