### PR TITLE
Fix Issue 23890 - "Warning: cannot inline function" in core.lifetime

### PR DESCRIPTION
**Pull request by CyberShadow**
I don't think we really need this, do we? CC @radcapricorn

### CODE REVIEW

**Comment by CyberShadow** [comment]
Do tests make sense here? They need `-w` (not `-wi`) to be effective, and this area is implementation-specific.

**Comment by RazvanN7** [comment]
Why wouldn't the compiler be able to inline a simple call expression? Maybe this is an inliner bug?

**Comment by CyberShadow** [comment]
Maybe, but isn't inlining success implementation defined anyway? So as such should not be forced in the language runtime, as it's shared by multiple implementations?

**Comment by RazvanN7** [comment]
It is, but as far as I understand ldc has a modified druntime (cc @kinke ) and gdc (cc @ibuclaw ) might as well but I'm not sure. Either way, I am seeing 83 occurrences of "pragma(inline, true)" in druntime so I don't think that there is any restriction of using it in druntime.

**Comment by CyberShadow** [comment]
> Why wouldn't the compiler be able to inline a simple call expression?

In the error message I also see a mention of `core.lifetime.wipe!(NC).wipe`, maybe that's somehow related as it also has a `pragma(inline, true)`. However, removing that pragma instead of in `move` does not fix the warning.

**Comment by kinke** [comment]
This is surely a DMD inliner bug. Enforcing inlining even for debug builds probably makes sense for such an ugly library implementation (vs. move/forward as language builtins), so if really wanting to suppress the warning for DMD for now, please do so via `version (DigitalMars) { /* cannot inline */ } else pragma(inline, true);` or so.

**Comment by maxhaton** [comment]
> This is surely a DMD inliner bug. Enforcing inlining even for debug builds probably makes sense for such an ugly library implementation (vs. move/forward as language builtins), so if really wanting to suppress the warning for DMD for now, please do so via `version (DigitalMars) { /* cannot inline */ } else pragma(inline, true);` or so.

I'm not sure it does make sense, why is it so important here?

**Comment by maxhaton** [comment]
It also shouldn't really be a warning either way

**Comment by maxhaton** [comment]
The dmd inliner is not very good, but wrt to inlining failures keep in mind that it's contextual e.g. when it fails the complexity of the would-be inlined function may not matter.

**Comment by kinke** [comment]
> I'm not sure it does make sense, why is it so important here?

It's not soo important, but IMO saves us from having to look at/debug-step over pretty embarrassing call stacks, e.g., for https://d.godbolt.org/z/fzoxTxME7. It'd be `fwd -> move -> moveImpl -> trustedMoveImpl -> moveEmplaceImpl`, with this we at least convert the forward to a move directly.

I guess the problem with DMD's inliner is that `arg` is a template alias param.

**Comment by CyberShadow** [comment]
> It also shouldn't really be a warning either way

What should it be, then? `pragma(inline, true)` is essentially an assertion of the optimizer's behavior. The intent is to have the build fail if a certain optimization is unachievable. It's also why I'm not sure it makes sense to use in Druntime - `pragma(inline)`  by itself simply requests inlining and letting that fail silently, which I think is what we want most if not all of the time.

**Comment by maxhaton** [comment]
> > It also shouldn't really be a warning either way
> 
> What should it be, then? `pragma(inline, true)` is essentially an assertion of the optimizer's behavior. The intent is to have the build fail if a certain optimization is unachievable. It's also why I'm not sure it makes sense to use in Druntime - `pragma(inline)` by itself simply requests inlining and letting that fail silently, which I think is what we want most if not all of the time.
> 
> Edit: oh, maybe not - I remembered what I [proposed](https://forum.dlang.org/post/wakrbfctbcxpuclhtmhe@forum.dlang.org) but the implementation today can't do that :(

There is a third category of DMD output other than deprecation: as well as error and warning there is "message".

If you want to tell the user that DMD is useless then fine, but a warning is just way too noisy.

The number of times that you genuinely have to insist upon inlining for correctness reasons is very small in my experience. I can think of exactly one case that I couldn't deal with a function call (any guesses?)

**Comment by CyberShadow** [comment]
> The number of times that you genuinely have to insist upon inlining for correctness reasons is very small in my experience.

I think it's not about the average experience but specialist purposes. E.g. as I understood, for performance sensitive applications, if a build is too slow then it is useless. Catching regressions that cause the compiler to miss an inline is useful there.

**Comment by maxhaton** [comment]
> > The number of times that you genuinely have to insist upon inlining for correctness reasons is very small in my experience.
> 
> I think it's not about the average experience but specialist purposes. E.g. as I understood, for performance sensitive applications, if a build is too slow then it is useless. Catching regressions that cause the compiler to miss an inline is useful there.

Ignoring that they aren't going to be using dmd in this case, this is where you want a proper structured output (LLVM optimization reports or gcc `-fopt-info-all`), doing it with the all or nothing warning style we have seems like a recipe for making people really annoyed.

My usecase was also quite specialist - at one eBPF didn't have function calls!

**Comment by CyberShadow** [comment]
Well, on that topic, warnings probably shouldn't exist at all, and this should probably have been an error; and to recap the above, there should have been a "please try really hard to inline but it's OK if you fail" mode for the `pragma`, and we still should not have been using the warning/error-generating construct in Phobos/Druntime from the start.

What do we do about this specific case, though? 

> if really wanting to suppress the warning for DMD for now, please do so via `version (DigitalMars) { /* cannot inline */ } else pragma(inline, true);` or so.

Done... should I try to reduce and file a separate DMD backend bug?

**Review by WalterBright — APPROVED** [review]

**Comment by RazvanN7** [comment]
@CyberShadow this has been approved by @WalterBright . Please rebase it.

**Comment by CyberShadow** [comment]
I've rebased it. It's still red, not sure if I need to do something? At least the FreeBSD and macOS failures seem completely unrelated.

**Comment by kinke** [comment]
From https://github.com/dlang/dmd/pull/15186/checks?check_run_id=14768971086, apparently some ugly line-number sensitiveness in the touched file:
```
diff myprofilegc.log.linux.64.exp ./generated/linux/debug/64/myprofilegc.log
9c9
<              32	              1	profilegc.main.C core.lifetime._d_newclassT!(C)._d_newclassT ../../src/core/lifetime.d:2755
---
>              32	              1	profilegc.main.C core.lifetime._d_newclassT!(C)._d_newclassT ../../src/core/lifetime.d:2759
make[2]: *** [Makefile:28: generated/linux/debug/64/profilegc.done] Error 1
```

**Comment by CyberShadow** [comment]
Fixed. macOS is still red due to keyring problems.

**Pull request merged**
