### PR TITLE
add -P=preprocessorflag switch

### PR DESCRIPTION
**Pull request by WalterBright**
This is so that the C preprocessor can be controlled from the DMD command line.

All this does at the moment is collect the parameters. Integrating it into the command to the C preprocessor awaits a merge of https://github.com/dlang/dmd/pull/14121 because it would be a nuisance merging the two.

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]
Another switch, another bug!

**Comment by kinke** [comment]
I'd have hoped we could reuse existing `-Xcc` (for C compiler, currently only used for the `cc` linker cmdline on Posix). That'd fit in nicely with `cl.exe` for MSVC targets, and gcc/clang on Posix ones. Some extra defines in the Posix linker cmdline wouldn't hurt IMO.

It should also work for `sppn.exe`, although it's no C compiler - as `-Xcc` currently has no effect on Windows.

**Comment by WalterBright** [comment]
@kinke I don't understand what you're asking for and why. `cl` doesn't even have a `-Xcc` switch:

https://docs.microsoft.com/en-us/cpp/build/reference/x-ignore-standard-include-paths?view=msvc-170

**Comment by kinke** [comment]
https://dlang.org/dmd-linux.html#switch-Xcc

**Comment by WalterBright** [comment]
We have `-L=<linkerflag>` which does the same thing, except for the `linkswitchIsForCC`. I modeled this switch after it. I don't understand what you are proposing. A `-Xcpp` switch?

Can you please explain exactly what switch you are proposing?

**Comment by WalterBright** [comment]
@kinke I'm still open to changing the switch if you want to make a case for it. I just merged it to move on to the next bit, which is passing the arguments to the preprocessors.

**Comment by kinke** [comment]
> Can you please explain exactly what switch you are proposing?

Quoting myself: `I'd have hoped we could reuse existing -Xcc` - so instead of a new switch, I'm arguing in favor of reusing the existing switch for the C compiler (as that's the C preprocessor too, except for `sppn.exe` - which won't be used by LDC or GDC).

E.g., for cross-linking with clang, one would currently use `-Xcc=-target -Xcc=<triple>`. Reusing those flags for the preprocessor too would mean that the user wouldn't have to additionally add `-P=-target -P=<triple>`. And some further `-Xcc=-D…` defines for the preprocessor IMO wouldn't hurt in the `cc` linker cmdline.

**Pull request merged**
