### PR TITLE
Change rvalueRefParam from bool to FeatureState

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by dkorpel** [comment]
Tests fail because frontend.h was not updated correctly

**Comment by MoonlightSentinel** [comment]
> _ No description provided. _

Are there any plans to actually differentiate between `default` and `enabled`/ `disabled`? Also isn't this switch effectively superseeded by `-preview=in`?

**Comment by 12345swordy** [comment]
I thought that the preview switch in replaces the rvalue switch? I had a DIP PR closed because of this.

**Comment by Geod24** [comment]
@12345swordy : We discussed moving forward with `-preview=in`, yes, but it seems there are still some users of this switch out there. I do believe that rvaluerefparam is not compatible with many aspects of D (**cough cough** `@safe` **cough cough**) but the fate of this switch is likely to be decided once `-preview=in` becomes the default (or close to).

**Pull request merged**
