### PR TITLE
Backend's Outbuffer: Use Reset

### PR DESCRIPTION
**Pull request by Geod24**
Simple mechanical fixes, better reviewed commit-by-commit.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by rainers** [comment]
> [backend.outbuf: Use reset instead of setsize(0)]

FYI https://github.com/dlang/dmd/pull/10469

**Comment by WalterBright** [comment]
Please use multiple PRs. Each of the commits should be reviewed on its own merits, not group merits.

For example, the reason `ptr` is used instead of offset is for runtime efficiency reasons. Mixing that up with others makes it hard to separately review it.

**Comment by Geod24** [comment]
> FYI #10469

Right... And I agree with your statement in that PR: `reset` is a much better API, because it is inherently `@safe`, while `setsize` is not. Since `Outbuffer` is used with other data types, a call to `reserve` then `setsize` would expose potentially uninitialized data.

My goal is similar to that of @WalterBright 's as stated here: https://github.com/dlang/dmd/pull/10469#issuecomment-541301118
And the only way `Outbuffer` can be `@safe` is:
- Making its members private;
- Exposing a slice API;
- Not offsetting user-provided pointers (e.g. `write(const void* ptr, size_t len)` can't be `@trusted`);

Now all those 3 things are blocked by one consideration: `Outbuffer` does not only store `ubyte`, it stores other types as well (e.g. https://github.com/dlang/dmd/blob/17d932b73b5b0ddf8efc9710440fe896f9ac7f4b/src/dmd/backend/mscoffobj.d#L80-L81). So things needs to be templated somewhere (for writing it, and reading).

I guess it is up to @WalterBright to decide if he agrees with this direction / rationale.

**Comment by Geod24** [comment]
> Please use multiple PRs. Each of the commits should be reviewed on its own merits, not group merits.

I use single PR / multiple commits to allow people to review commit on their own merits. If a commit is contentious I just take it out of the PR / split it to another PR. It can take hours to have the CI complete, having a PR for each of those small refactoring is a lot of load for no reason (every time a PR is merged, it restart the test for pending PRs in all core repository...).

Reviewing commit-by-commit is absolutely trivial. A reviewer is free to say "LGTM bar commit XXX". I don't understand what the problem is here. But since you asked, I stripped that PR to be `setsize(0)` => `reset`.

**Pull request merged**
