### PR TITLE
[not for merge] [only to use autotester] newCTFE on updated master

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by wilzbach** [comment]
@UplinkCoder I assume you forgot to close this and https://github.com/dlang/dmd/pull/6926 contains your latest work?

**Comment by UplinkCoder** [comment]
@wilzbach please reopen I need this to use the auto-tester.
This is still current

**Comment by MartinNowak** [comment]
As discussed, let's please continue work on UplinkCoder/newCTFE and make a new PR from UplinkCoder/newCTFE -> upstream/master to get auto-tester results.

**Comment by CyberShadow** [comment]
+1, thanks! The Bugzilla spam was a bit annoying :)

**Pull request closed without merging**
