### PR TITLE
dtoh: Re-add rudimentary support for C++98 compatible enums

### PR DESCRIPTION
**Pull request by ibuclaw**
This re-adds the possibility to interface with C++-98.  It was given a passing mention by @UplinkCoder in #11721.

The `compilable/dtoh_enum.d` test has been copied over to `compilable/dtoh_enum_cpp98.d` to explicitly check this.

### CODE REVIEW

**Comment by 12345swordy** [comment]
Any hang ups?

**Comment by ibuclaw** [comment]
> Any hang ups?

As you can see from the [auto-tester](https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=4255196&dataid=30150603&isPull=true), the generated front-end header changes enum style.  So first #11803 should go in, then this.

**Comment by 12345swordy** [comment]
all green here.

**Review by thewilsonator — APPROVED** [review]

**Comment by UplinkCoder** [comment]
Thanks @ibuclaw

**Pull request merged**
