### PR TITLE
[Refactor] Create visitor for resolve method of type AST nodes

### PR DESCRIPTION
**Pull request by RazvanN7**
cc @WalterBright

### CODE REVIEW

**Comment by RazvanN7** [comment]
The jenkins failure is most likely unrelated since this PR does not modify any code logic.

**Review by wilzbach — APPROVED** [review]
LGTM, though `resolve.d` would have been a real option here.

**Review by JinShil — APPROVED** [review]

**Comment by andralex** [comment]
@ibuclaw ping just to make sure we're good here

**Comment by ibuclaw** [comment]
@andralex so you merged it anyway?

**Comment by andralex** [comment]
@ibuclaw yah, under the assumption we can easily undo the merge or make the necessary changes. Optimistic concurrency control :)

**Comment by ibuclaw** [comment]
The resolve function is probably a candidate for making extern(D), I can think of no reason off the top of my head why it needs to be publicly visible (outside of D code).

**Pull request merged**
