### PR TITLE
[stable] Fix another frontend C++ interop regression

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by kinke** [comment]
This seems to uncover a dtoh shortcoming, not accounting for extern(D) functions potentially affecting the vtable layout. Pinging @ibuclaw.

**Review by ibuclaw — APPROVED** [review]
OK

**Comment by ibuclaw** [comment]
> This seems to uncover a dtoh shortcoming, not accounting for extern(D) functions potentially affecting the vtable layout. Pinging @ibuclaw.

A bugzilla issue would be good.

**Comment by thewilsonator** [comment]
`fatal: Remote branch v2.094.0 not found in upstream origin`

Same here, looks like a `stable` problem?

**Comment by kinke** [comment]
> A bugzilla issue would be good.

https://issues.dlang.org/show_bug.cgi?id=21271

**Comment by kinke** [comment]
> Same here, looks like a stable problem?

Apparently a problem for the dlang.org repo in the short period where stable's `VERSION` is already set to the upcoming tag...

**Pull request merged**
