### PR TITLE
add setLength alias to root array

### PR DESCRIPTION
**Pull request by thewilsonator**
The makes the interface more similar between backend.barray and
root.array

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by JinShil** [comment]
What about having a `length` property instead that can be set with the same syntax as dynamic arrays in D.  That way the two interfaces are interchangeable should DMD ever leverage intrinsic D features.

**Comment by thewilsonator** [comment]
because the backend array uses `setLength` and I want to supplant its use with root.array and therefore compatibility is needed.

**Comment by WalterBright** [comment]
> because the backend array uses setLength and I want to supplant its use with root.array and therefore compatibility is needed.

Not ready to do that. There's not really a strong reason to intermingle backend code with front end code, and it makes my life harder keeping DMC++ working with all this shuffling around. It's not like barray or root.array are complex pieces of code, they're trivialities.

**Comment by thewilsonator** [comment]
> Not ready to do that.

With this and #9973 `dmd.backend.barray` will be drop in replaceable by `root.array` (possibly modulo memory allocation strategies).

**Comment by jacob-carlborg** [comment]
> There's not really a strong reason to intermingle backend code with front end code

I don’t see `root` as part of the front end. But you might look at it differently.

**Comment by Basile-z** [comment]
If the plan is to use `setLength` than why not renaming `setDim` to `setLength` and keep `setDIm` as alias ? This PR introduces something that's not used.

**Comment by Geod24** [comment]
Closing as stale and not providing much value.

**Pull request closed without merging**
