### PR TITLE
Revert #6026 - build compiler w/ optimizations to speed up test suite

### PR DESCRIPTION
**Pull request by ibuclaw**
I expect the testsuite to fail - and this is why we should not be doing this.

### CODE REVIEW

**Comment by WalterBright** [comment]
Leaving optimizations on should be fine, but it should not be `-release` because those remove the assert's in the front end.

**Comment by ibuclaw** [comment]
> Leaving optimizations on should be fine, but it should not be -release because those remove the assert's in the front end.

Indeed, this PR won't pass the CI until all assertion failures have been fixed.

**Comment by WalterBright** [comment]
Yes, turning off assert checking was clearly a mistake.

**Comment by wilzbach** [comment]
Closing in favor of #7344

**Pull request closed without merging**
