### PR TITLE
Possible fix for bug #11595 - __traits(allMembers, packageName) behaves oddly

### PR DESCRIPTION
**Pull request by rikkimax**
I'm not 100% on this, mostly for the string stuff.
But I think it is a fix for https://issues.dlang.org/show_bug.cgi?id=11595

### CODE REVIEW

**Comment by MartinNowak** [comment]
So you use fully qualified names for imports, how does that fox the bug where module are missing?

**Comment by rikkimax** [comment]
Basically, given a module name for __traits(allMembers it will only output the first package name for an import. So this adds custom handling for imports. Instead of just doing a toString to get it.

**Comment by MartinNowak** [comment]
The problem exists for any import, not only the ones at module level.
http://dpaste.dzfl.pl/daf3356c378b

**Comment by rikkimax** [comment]
This also fixes bug https://issues.dlang.org/show_bug.cgi?id=14375

**Comment by Geod24** [comment]
> This also fixes bug https://issues.dlang.org/show_bug.cgi?id=14375

That's cool :)
Could you add the test for it ?

N00b question:
Is it legal for `sm->ident` to be empty string at this stage ? From what I see [here](https://github.com/D-Programming-Language/dmd/blob/f5cb574cc46c23b53b8dd76750811ffd0b496838/src/traits.c#L635), no identifier should mean NULL, not "".

**Comment by rikkimax** [comment]
Unfortunately my environment isn't suited to dmd development. So I need to get reset up again before adding tests. But I will someday. Either in this PR or in another.

I currently have plans for a D program that can create a Windows VM with VS ext. automatically. In other words, a nice scratch install of Windows that I can use any time I want. Nicely set up for dmd/druntime/phobos development. Even if it can only be used for 30 days...

@Geod24 I was pretty pleased with myself in that I had fixed two bugs with this PR. But even if sm->indent shouldn't be empty, it is. Yes there probably are better ways to compare if it is empty. But until somebody tells me to change it, I won't.

**Comment by 9rnsr** [comment]
I think any import declarations should not be listed in the result of `__traits(allMembers)`, because they are not true "member" of imported scope.
And listing them would make problem. For exampe:

```d
struct S {
    import object;
    int object;
}
pragma(msg, [__traits(allMembers, S)]);   // ["object", "object"] <-- ?
```

**Comment by Geod24** [comment]
> I think any import declarations should not be listed in the result of `__traits(allMembers)`, because they are not true "member" of imported scope.

Depends on 314 :)
Seriously, I do agree, but we'll need `__traits(imports)` then (should it work on other thing that modules ?)

**Comment by 9rnsr** [comment]
> Depends on 314 :)

Indeed, and I believe that the imported package names should not be "member" due to reject these weird code:
```d
struct S { import std.stdio; }
void main() { S.std.stdio.writeln("woops"); }
```

> __traits(imports)

I think we should stop throwing every new features into __traits.

**Comment by Geod24** [comment]
> I think we should stop throwing every new features into __traits.

Not every new features, only those related to CT reflection. Do you have something in mind ?

**Comment by 9rnsr** [comment]
For CT reflections, we would need to have more better primitives and throw away using double-underscores.
Current string based reflection is handy, but it's not powerful for complex code constructions.

**Comment by Geod24** [comment]
> For CT reflections, we would need to have more better primitives and throw away using double-underscores.
> Current string based reflection is handy, but it's not powerful for complex code constructions.

It's actually not-so handy. I'd rather get a symbol from the compiler than a string, because string are out of context and leads to import hell and loss of safety.

I'd like to be able to do something in this spirit some day:
````
class Test {
   int foo(string par) pure @safe nothrow { /* ... */ }
   // Declare 'int bar(string par) pure @safe nothrow'
   typeof(foo) bar {
      return foo(par);
   }
}
````

**Pull request closed without merging**
