### PR TITLE
Fix #20356 raises recursive expansion limit

### LINKED ISSUE #20356: Missing @nogc compile error in -betterC leads to undefined reference linker error
### Description

````markdown
```
@nogc:

extern(C) void main() {
	foo();
}

void foo() {
	bar([1]);
}

void bar(int[]) {}
```

Compiling with `dmd a.d`, it correctly fails with:
```
a.d(8): Error: array literal in `@nogc` function `a.foo` may cause a GC allocation
```

Compiling with `dmd -betterC a.d`, there is no compile error. Instead there is a linker error:
```
/usr/bin/ld: a.o: in function `main':
a.d:(.text.main[main]+0x5): undefined reference to `_D1a3fooFNiZv'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```

I don't see a good reason not to have a compile error with `-betterC`. The linker error is harder to diagnose.
````

### PR DESCRIPTION
**Pull request by burner**
Raises the limit from 300 to 500 and gives clearer error msg.

### CODE REVIEW

**Comment by burner** [comment]
https://issues.dlang.org/show_bug.cgi?id=20356

**Comment by kinke** [comment]
Replacing a hardcoded constant by another isn't a proper fix IMO. LDC has a `-template-depth` switch.

**Comment by burner** [comment]
true, but I really would like to get this in 89.1 as the 300 limit is currently breaking my dub replacement project.
creating an additional cmd argument to set it should be definitively done for 90.0

**Comment by RazvanN7** [comment]
You should have a commit message that contains the text "Fix Issue 20356" in it (the commit message is not limited to that, you can have additional text in it) so that the bot will link the PR with the issue and close it once the PR gets merged.

Also, I think that a better solution would be to have a global variable in globals.d that is set to 500 and use it throughout the compiler where this number is hardcoded. This will make it easier if we decide to add another compiler switch.

For what's worth I think that adding a compiler switch is the right fix, but @WalterBright  is against adding new switches.

**Comment by RazvanN7** [comment]
There are other uses of the hardcoded 500 that need replacing. Using `rgrep 500 | grep nest` results in:

```
dmd/dtemplate.d:        if (++nest > 500)
dmd/expressionsem.d:                if (++nest > 500)
dmd/dsymbolsem.d:        if (++nest > 500)
dmd/dsymbolsem.d:            if (++nest > 500)
dmd/typesem.d:        if (++nest > 500)
```

The check in typesem is for recursive function types and the one in expressionsem is for recursive evaluation of function calls. I think that we can rename the global to `recursiveLimit` and use it in these situations too.

**Comment by RazvanN7** [comment]
Sorry for the nagging, but you missed 2 occurences in dsymbolsem (I didn't mention them because they are related to mixin templates, so they are not as controversial as the ones in expressionsem and typesem). Also, the name does no longer apply. I suggested renaming `maxTemplateExpansion` to `recursiveLimit` or something more general.

**Comment by burner** [comment]
@RazvanN7 the nagging is welcomed! Thank you.

**Review by RazvanN7 — APPROVED** [review]

**Comment by burner** [comment]
@RazvanN7 thank you

**Comment by RazvanN7** [comment]
You're welcome!

**Comment by PetarKirov** [comment]
> true, but I really would like to get this in 89.1 as the 300

@burner if you want to target the 2.089.1 release you need to change the target branch of your PR to `stable` and also rebase your branch:

```
git checkout expansionLimitRaise_20356
git rebase --onto upstream/stable upstream/master expansionLimitRaise_20356
```

**Review by PetarKirov — APPROVED** [review]
I suggest merging this PR as it is in `stable` and then adding a CLI flag in `master`.

**Pull request merged**
