### PR TITLE
forgot to reset charnum to 0

### PR DESCRIPTION
**Pull request by WalterBright**
Noticed this when reviewing the code.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
and what problems does this cause? can you write a test for it?

**Comment by WalterBright** [comment]
It would take a fair amount of time to figure out how to trigger it, not worth the effort. But it's clearly a bug to set the line and not the column.

**Review by dkorpel — CHANGES_REQUESTED** [review]
- `charnum` starts at 1, not 0
- `charnum` is not incremented, it's computed by `p - line`, so this does nothing

**Comment by dkorpel** [comment]
> But it's clearly a bug to set the line and not the column.

Evidently not. The `line` pointer is already handled by `scan()`, so the `poundLine` function only needs to modify the line number.

**Comment by WalterBright** [comment]
@dkorpel ok

**Pull request closed without merging**
