### PR TITLE
Issue 7903 - Disallow public members in a synchronized class

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Fixes https://issues.dlang.org/show_bug.cgi?id=7903

Recreated from https://github.com/D-Programming-Language/dmd/pull/3067

### CODE REVIEW

**Comment by andralex** [comment]
Alrighty then, seems there's good consensus on the forum. Thanks!

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by MetaLang** [comment]
Should there need to be an accompanying doc pull?

**Comment by AndrejMitrovic** [comment]
> Should there need to be an accompanying doc pull?

Feel free to file an issue and assign me. That's the best way we don't forget about this.

**Comment by MetaLang** [comment]
https://issues.dlang.org/show_bug.cgi?id=15226

**Pull request merged**
