### PR TITLE
Fix issue 20645 - printf deprecation for width + precision

### PR DESCRIPTION
**Pull request by Luhrel**
On top of this fix, the `%lf` format for `printf` is now allowed. Like that, it corresponds to the C99 standard.

### CODE REVIEW

**Review by MoonlightSentinel — APPROVED** [review]

**Comment by rainers** [comment]
I think %lf should be accepted, it is very common, and it is only forbidden in newer C++ standards, not C according to https://stackoverflow.com/questions/4264127/correct-format-specifier-for-double-in-printf

**Review by thewilsonator — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
You need to remove the deprecation warnings from `runnable/dhry`'s `TEST_OUTPUT` section (they were introcued as a workaround in #10877)

**Comment by Geod24** [comment]
Please also change your commit messages to include the issue title. No one remembers issues by their numbers (except perhaps dear 313 / 314), and no including any detail in your PR title makes it inconvenient for people dealing with a large number of deprecations.
As for not putting it in the commit title, it means that when someone is going through the `git` history they're not really able to tell if your commit is related to what they are looking for.

**Comment by Luhrel** [comment]
@Geod24 got it.

**Comment by WalterBright** [comment]
Quoting C99 7.9.16.7:

"l(ell)  Specifies that a following d, i, o, u, x ,or X conversion specifier applies to a
long int or unsigned long int argument; that a following n conversion specifier applies to a pointer to along int argument; that a following c conversion specifier applies to a wint_t argument; that a following s conversion specifier applies to a pointer to a wchar_t argument; or has no effect on a following a, A, e, E, f, F, g, or G conversion specifier."

so @Luhrel is correct. I did get this right in the initial PR. My mistake was not having a unittest for it, hence it broke in the next PR.

**Comment by WalterBright** [comment]
@rainers @MoonlightSentinel my experience with online versions of printf formats is they are WRONG in subtle details. One simply must refer to the actual Standard. The online rewrites are only good for superficial use, they are not definitive, and are sloppy.

The reason is because the Standard is copyrighted, so the online authors feel compelled to rewrite them. Don't trust the result.

**Comment by rainers** [comment]
@WalterBright Did you take a look at the linked answers? The second answer explicitly quotes the standard that lists the allowance of "%lf" as a major change of ISO/IEC 9899:TC3. 7.19.6.1 states that 'l' has no effect on doubles.

**Comment by WalterBright** [comment]
When I need to definitively know what the C99 Standard says, I have a copy and read that. If I read stackoverflow, then I have to go read what C99 says anyway to check it, which is a waste of time trying to figure out which (if any) of its 5 answers are correct.

**Pull request merged**
