### PR TITLE
use ref for OutBuffer rather than *

### PR DESCRIPTION
**Pull request by WalterBright**
`ref` is the safer, more modern style.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
I got the same Azure errors as https://github.com/dlang/dmd/pull/10409

Something gone wrong with Azure?

**Comment by thewilsonator** [comment]
I think so. see also https://github.com/dlang/dmd/pull/10408#issuecomment-531580935

**Comment by WalterBright** [comment]
Any hope of getting Azure fixed? Who should I harangue?

**Comment by thewilsonator** [comment]
https://github.com/dlang/druntime/pull/2799 

see also

https://github.com/dlang/druntime/pull/2800 which should prevent future such events.

But the root cause of the problem seems to be flakey stack stomping code interacting nastily with windows in conjunction with `Fiber`.

**Comment by Geod24** [comment]
Restarted failing checks, let's see how it goes

**Comment by WalterBright** [comment]
ah, thanks!

**Pull request merged**
