### PR TITLE
Fix Issue 14097 - root/async.c: free after use

### PR DESCRIPTION
**Pull request by PetarKirov**
Also add some docs.

### CODE REVIEW

**Comment by ZombineDev** [comment]
Follow up on #4363 (I mistakenly deleted my fork and github didn't allow me update the pull request).

**Comment by ZombineDev** [comment]
@MartinNowak I'm sorry for the long delay. Is there anything else that I have to do?

**Comment by MartinNowak** [comment]
No, thanks for the followup.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
