### PR TITLE
feat(test): Add DWARF_VERIFY flag on DWARF tests

### PR DESCRIPTION
**Pull request by ljmf00**
The other tests are disabled because of inconsistency with DWARF4/5 and `.debug_aranges` section.

### CODE REVIEW

**Comment by ljmf00** [comment]
This still requires some changes on `.debug_line` about `DW_AT_stmt_list` bounds to succeed.

**Comment by ljmf00** [comment]
Why global variables are shared in FreeBSD? CI fails:

```
[RUN] 'llvm-dwarfdump' '--verify' 'test_results/dshell/dwarf/fix21154'
Verifying test_results/dshell/dwarf/fix21154:	file format ELF64-x86-64
Verifying .debug_abbrev...
Verifying .debug_info Unit Header Chain...
error: DIE has DW_AT_type with incompatible tag DW_TAG_shared_type
0x00000097: DW_TAG_variable
              DW_AT_name	("fix21154.i")
              DW_AT_type	(0x00000092 "shared int")
              DW_AT_external	(0x01)
              DW_AT_location	(DW_OP_addr 0x600d90)
Verifying .debug_info references...
Verifying .debug_types Unit Header Chain...
Errors detected.
```

**Comment by ljmf00** [comment]
> Why global variables are shared in FreeBSD? CI fails:
> 
> ```
> [RUN] 'llvm-dwarfdump' '--verify' 'test_results/dshell/dwarf/fix21154'
> Verifying test_results/dshell/dwarf/fix21154:	file format ELF64-x86-64
> Verifying .debug_abbrev...
> Verifying .debug_info Unit Header Chain...
> error: DIE has DW_AT_type with incompatible tag DW_TAG_shared_type
> 0x00000097: DW_TAG_variable
>               DW_AT_name	("fix21154.i")
>               DW_AT_type	(0x00000092 "shared int")
>               DW_AT_external	(0x01)
>               DW_AT_location	(DW_OP_addr 0x600d90)
> Verifying .debug_info references...
> Verifying .debug_types Unit Header Chain...
> Errors detected.
> ```

Fixed. FreeBSD 11 uses an older version of llvm. Updated to LLVM 12.0. I still can't understand why global variables are always shared.

**Comment by RazvanN7** [comment]
> The other tests are disabled because of inconsistency with DWARF4/5 and .debug_aranges section.

Are those going to be re-enabled at some point?

**Comment by ljmf00** [comment]
> > The other tests are disabled because of inconsistency with DWARF4/5 and .debug_aranges section.
> 
> Are those going to be re-enabled at some point?

Yes.

**Review by RazvanN7 — APPROVED** [review]

**Comment by ljmf00** [comment]
> > Why global variables are shared in FreeBSD? CI fails:
> > 
> > ```
> > [RUN] 'llvm-dwarfdump' '--verify' 'test_results/dshell/dwarf/fix21154'
> > Verifying test_results/dshell/dwarf/fix21154:	file format ELF64-x86-64
> > Verifying .debug_abbrev...
> > Verifying .debug_info Unit Header Chain...
> > error: DIE has DW_AT_type with incompatible tag DW_TAG_shared_type
> > 0x00000097: DW_TAG_variable
> >               DW_AT_name	("fix21154.i")
> >               DW_AT_type	(0x00000092 "shared int")
> >               DW_AT_external	(0x01)
> >               DW_AT_location	(DW_OP_addr 0x600d90)
> > Verifying .debug_info references...
> > Verifying .debug_types Unit Header Chain...
> > Errors detected.
> > ```
> 
> Fixed. FreeBSD 11 uses an older version of llvm. Updated to LLVM 12.0. I still can't understand why global variables are always shared.

@RazvanN7 Perhaps this is something that could have some attention, or is it an ABI requirement?

**Comment by RazvanN7** [comment]
I have no clue.

**Comment by ljmf00** [comment]
> I have no clue.

Who can we tag to clarify this? Is there any FreeBSD maintainer? I doubt the global variables are shared otherwise, some code wouldn't work as expected. Can be a DWARF issue, but I can't relate any FreeBSD specific code that does this, so I'm a bit confused.

**Pull request merged**
