### PR TITLE
fix Issue 22084 - [REG 2.097] Segmentation fault passing non-pod struct as variadic argument

### PR DESCRIPTION
**Pull request by ibuclaw**
Use variadic storage class for variadic parameters.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Please target stable

**Comment by ibuclaw** [comment]
> Please target stable

See list of open PRs #12761

**Comment by Geod24** [comment]
Well no need to submit two PR - stable is regularly merged back into master.

**Comment by ibuclaw** [comment]
> Well no need to submit two PR - stable is regularly merged back into master.

Needs to target master as is breaking gdc.

**Comment by Geod24** [comment]
> Needs to target master as is breaking gdc.

Then open a PR that merge stable into master.
It's just going to the `Pull requests` tab, clicking `New pull request`, and then selecting the branch:
Screen Shot 2021-06-27 at 18 48 59

**Comment by thewilsonator** [comment]
superseded by https://github.com/dlang/dmd/pull/12768

**Pull request closed without merging**
