### PR TITLE
Remove 'rvaluerefparam' preview switch

### PR DESCRIPTION
**Pull request by Geod24**
The switch has been in the compiler since one and a half year
(2019-06-14, https://github.com/dlang/dmd/pull/9817) and hasn't
been used, as simple examples just don't work:
- https://issues.dlang.org/show_bug.cgi?id=20704
- https://issues.dlang.org/show_bug.cgi?id=20705
- https://issues.dlang.org/show_bug.cgi?id=20706

### CODE REVIEW

**Comment by PetarKirov** [comment]
Looking at the bug reports, I guess I was lucky since I was using it without problems in a project of mine 😄

**Comment by 12345swordy** [comment]
Hold on, before we remove this, lets get @TurkeyMan involved in this.

**Comment by TurkeyMan** [comment]
I've used it without problem for simple stuff, like, passing vectors/matrices to functions.
I have also run into those issues, and expect they should be fixed. Removing a thing because the implementation wasn't thorough seems weird... is this a decision that's been made?
I don't understand this: "has been superseeded by `-preview=in`", how is that the case?

**Comment by Geod24** [comment]
> I have also run into those issues, and expect they should be fixed. Removing a thing because the implementation wasn't thorough seems weird... is this a decision that's been made?

I should have added, the DIP has been rejected.

**Comment by 12345swordy** [comment]
but this feature was added after the dip was rejected though.

**Comment by Geod24** [comment]
Indeed. So what DIP was https://github.com/dlang/dmd/pull/9817 referring to ?
I assumed it was https://github.com/dlang/DIPs/blob/master/DIPs/rejected/DIP1016.md but the timing doesn't match, and I cannot see any other DIP addressing `ref` on rvalues.

**Comment by 12345swordy** [comment]
I think it was referring to @andralex DIP, but sadly life have catch up with him and couldn't complete it and submit it.

**Comment by TurkeyMan** [comment]
It was meant to be Andrei's DIP, which he presented at keynote at dconf 2019, but I'm not sure the hard DIP materialised.
The issues just seem like bugs to me, they don't appear critical, just cases the weren't handled in the implementation.

**Comment by Geod24** [comment]
> I don't understand this: "has been superseeded by -preview=in", how is that the case?

`-preview=in` as it is implemented fulfill the same needs as rvalue ref, at least according to the rejection of your DIP.

The main argument in rejecting the DIP was that:
> The Language Maintainers insist that any proposal allowing `ref` parameters to accept rvalue references must clearly define how functions which make use of `ref` for side effects will not accept rvalues.

By definition, `in` does not make use of `ref` for side effect.
If people feel strongly about keeping this switch, so be it, but I think having bit-rotten switch reflects badly on the language. I was going through the list of switch we could promote to mainline, and I don't see anyone championing this in the near or intermediate future, which is not the case for the other ones.

**Comment by dkorpel** [comment]
> Indeed. So what DIP was #9817 referring to ?

https://gist.github.com/andralex/e5405a5d773f07f73196c05f8339435a

**Comment by 12345swordy** [comment]
I don't mind the new "In" replacing this switch, as long there is a spec pr and thumbs up approval from @WalterBright  on this.

**Comment by n8sh** [comment]
> The switch has been in the compiler since one and a half year (2019-06-14, #9817) and hasn't been used, as simple examples just don't work

I've been using it for a mixed C++/D project that involved a great deal of translated header files. I've ran into limitations like the linked issues (and put up with them since it's an experimental feature) but working around those cases has been less work than it would be to work around every single time a function expecting an argument to be passed by ref is called with an rvalue.

**Comment by Geod24** [comment]
Thanks for the feedback, it's quite clear now that this is not quite ready for removal. I'll close now, but if other people have experience with it, feel free to share. For reference, one idea I was toying with was to make `in` (with `-preview=in`) always means `ref` when used on a function that is `extern(C++)`.

**Pull request closed without merging**
