### PR TITLE
refactor resolveExp()

### PR DESCRIPTION
**Pull request by WalterBright**
1. improve documentation
2. properly use `out` parameters
3. eliminate unsafe casting
4. improve control flow

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]
Sweet

**Comment by WalterBright** [comment]
fixed typo in comment

**Comment by WalterBright** [comment]
Stymied by bugs in buildkite/dmd:
```
Linking...
--
  | Copying files for dlang-tour...
  | Running ./dlang-tour-test-library
  | lang: en, chapter: dub, section: lubeck failed
  | source/contentprovider.d(330): [unittest] Source code line length exceeds 48 limit in 'Lubeck': import mir.ndslice: magic, repeat, as, slice, byDim;
  | object.Exception@source/contentprovider.d(330): Source code line length exceeds 48 limit in 'Lubeck': import mir.ndslice: magic, repeat, as, slice, byDim;
```
so have to restart entire test suite _again_. Having such a flaky randomly failing test suite is just unacceptable.

**Comment by UplinkCoder** [comment]
What the H?
Why did you self merge this?

**Pull request merged**
