### PR TITLE
Issue 15156 - overload set in eponymous template

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=15156

Trivial bug fix.

### CODE REVIEW

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks!

**Comment by MartinNowak** [comment]
Why wasn't this integrated as AliasDeclaration.isOverloadable? Same bug happened again https://issues.dlang.org/show_bug.cgi?id=16085.

**Comment by 9rnsr** [comment]
Because `isOverloadable` is used in `ScopeDsymbol.search`. As you know, whether an alias declaration is overloadable or not, depends on the aliased thing is overloadable. If we integrate the mechanism into `AliasDeclaration.isOverloadable`, it should invoke semantic analysis to return stable result. I think, a symbol search usually don't run semantic analysys of found symbol.

**Pull request merged**
