### PR TITLE
2nd try at __rvalue(expression)

### PR DESCRIPTION
**Pull request by WalterBright**
as in https://github.com/dlang/dmd/pull/17050

### CODE REVIEW

**Comment by WalterBright** [comment]
Something is wrong with the CI. See https://github.com/dlang/dmd/pull/17496

**Comment by WalterBright** [comment]
Finally, some real progress.

**Comment by WalterBright** [comment]
merged into https://github.com/dlang/dmd/pull/17050

**Comment by thewilsonator** [comment]
I assume this PR can be closed now?

**Pull request closed without merging**
