### PR TITLE
fix Issue 20131 - Bad codegen from inline asm LOCK CMPXCHG; possible …

### PR DESCRIPTION
**Pull request by WalterBright**
…REX prefix missing

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Should this target stable? I know that Manu is doing the atomic stuff on master but this is a major issue.

**Comment by WalterBright** [comment]
Since it hasn't come up in the last 10 years, I don't think it needs rushing. Manu needs it, and he can get it with master.

**Comment by thewilsonator** [comment]
OK.

**Comment by Geod24** [comment]
Test case?

**Comment by WalterBright** [comment]
> Test case?

Already there in the PR. It's the 2nd file.

**Comment by WalterBright** [comment]
Azure pipelines fails with:
```
D:\a\1\phobos>"D:\a\1\s\dm\path\make.exe" -f win64.mak unittest MODEL=32mscoff "DMD=D:\a\1\s\generated\Windows\Release\Win32\dmd.exe" "VCDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\." "CC=D:\a\1\s\dm\path\cl.exe" "MAKE=D:\a\1\s\dm\path\make.exe" 
"D:\a\1\s\generated\Windows\Release\Win32\dmd.exe" -conf= -g -m32mscoff -O -w -dip25 -I../druntime\import -unittest -c  -ofunittest1.obj std\stdio.d  std\string.d  std\format.d  std\file.d

"D:\a\1\s\generated\Windows\Release\Win32\dmd.exe" -conf= -g -m32mscoff -O -w -dip25 -I../druntime\import -unittest -c  -ofunittest2.obj std\range\package.d  std\range\primitives.d  std\range\interfaces.d
std\range\package.d(1396): Error: cannot take address of local `s` in `@safe` function `__unittest_L1392_C12`
std\range\package.d(1670): Error: cannot take address of local `s` in `@safe` function `__unittest_L1666_C12`
std\range\package.d(2043): Error: cannot take address of local `f` in `@safe` function `__unittest_L2039_C12`
std\range\package.d(2043): Error: cannot take address of local `b` in `@safe` function `__unittest_L2039_C12`
std\range\package.d(4275): Error: cannot take address of local `s` in `@safe` function `__unittest_L4271_C12`
```
What's up with that? Doesn't seem to have anything to do with inline asm.

**Comment by wilzbach** [comment]
Unrelated - see https://github.com/dlang/phobos/pull/7143

**Pull request merged**
