### PR TITLE
Fix compatibility with true 64bit integer types in C++

### PR DESCRIPTION
**Pull request by ibuclaw**
Any linker errors that come up need to be resolved in ddmd.

### CODE REVIEW

**Comment by yebblies** [comment]
Ha

**Comment by WalterBright** [comment]
What is the 'true' 64 bit integer type in C++? `long` or `long long`, when they are both 64 bits? And what is the 'true' 32 bit integer type? `int` or `long` when they are both 32 bits? (They mangle differently.)

**Comment by yebblies** [comment]
The closest thing to a `true` 64 bit integer type that I could find was `int64_t`/`uint64_t`.  So I made the mangling match those.

**Comment by WalterBright** [comment]
There is no true 64 bit integer type, and int64_t is just a typedef. There is no mangling for int64_t, the mangling is for the underlying type, and that is not specified.

The mangling as it currently is is as good as it can be done. This PR is not a solution, it just shuffles the problem around.

**Comment by yebblies** [comment]
> There is no true 64 bit integer type, and int64_t is just a typedef. There is no mangling for int64_t, the mangling is for the underlying type, and that is not specified.
>
>The mangling as it currently is is as good as it can be done. This PR is not a solution, it just shuffles the problem around.

I agree, I'm just saying that the current mangling was picked to make int64_t etc match on as many dmd platforms as possible.

**Comment by ibuclaw** [comment]
> There is no mangling for int64_t, the mangling is for the underlying type, and that is not specified.

You may say that, but it is contrary to itanium spec.

		    ::= l   # long
		    ::= m   # unsigned long
		    ::= x   # long long, __int64
		    ::= y   # unsigned long long, __int64

> I agree, I'm just saying that the current mangling was picked to make int64_t etc match on as many dmd platforms as possible

It breaks c++ compatibility with gcc though, eg HOST_WIDE_INT could either be long, longlong, or int64 depending on what host condition passes first.

Ultimately, if D chooses to mangle long/ulong the same as c_long/c_ulong (l/m), then it is impossible to work link with projects that use int64/uint64 (x/y).

**Comment by WalterBright** [comment]
> Ultimately, if D chooses to mangle long/ulong the same as c_long/c_ulong (l/m), then it is impossible to work link with projects that use int64/uint64 (x/y).

There's always going to be something it can't link with, because C++'s `long` can be either 32 or 64 bits depending on the platform, thereby conflicting with either `int` or `long long`. And no, C++ programmers do not avoid using `long`. In fact, just ran into that with OSX32, where `size_t` is typedef'd to `unsigned long`.

**Comment by ibuclaw** [comment]
> There's always going to be something it can't link with, because C++'s long can be either 32 or 64 bits depending on the platform, thereby conflicting with either int or long long.

Still doesn't alter that ``long`` in D maps better to ``__int64``.  Even if ``c_long`` just so happens to be the same size.

**Comment by yebblies** [comment]
> Still doesn't alter that long in D maps better to __int64. Even if c_long just so happens to be the same size.

What would mapping to `__int64` give us over the current design?  Would more code be likely to work?  It doesn't seem so.

**Comment by ibuclaw** [comment]
> What would mapping to __int64 give us over the current design?

1. Correctness
2. Compatibility with gcc (Eg: g++ maps Java ``long`` to ``x``)
3. Being able to interface with ``__int64`` on ``L64`` platforms (blocker for gdc <-> ddmd interface).

**Comment by ibuclaw** [comment]
> Why don't we just make D long map to __int64 and c_long a magic type that is mangled as long?

Incidentally that's what this PR does!

**Comment by WalterBright** [comment]
__int64 is not even a standard C++ type.

The point is, there IS NO SOLUTION to this problem, short of creating more basic types in D. There's only shuffling the errors about. In this case, it fixes Fred's code by breaking Bob's code - neither is "more correct" than the other.

**Comment by ibuclaw** [comment]
> __int64 is not even a standard C++ type

Longlong then.  It is ridiculous that there is no way to interface with longlong on L64 platforms in the current implementation.  And again this blocks any compatibility with gdc/g++.

For the purpose of itanium mangling, 64bit integer types are clearly defined as x or y.

> The point is, there IS NO SOLUTION to this problem, short of creating more basic types in D.

We already have a (partial) solution, it's called __c_long, which allows us to interact with the most commonly used wibbly wobbly type in C/C++.  I'm not asking you to support ILP64 or (please forbid) SILP64.

I maintain the same argument against yebblies when he originally made this change.  There is no notion of 'C long' in D, we should not be mapping 'D long' to it.  You went and did it anyway because you needed a hack to work.  This undoes your hack.

**Comment by yebblies** [comment]
I did consider mapping long to longlong, but it turned out to be less useful than the current setup because int64_t is a long on ILP32 platforms.

**Comment by ibuclaw** [comment]
> because int64_t is a long on ILP32 platforms.

That makes no sense.  It would be a longlong.

**Comment by yebblies** [comment]
Yeah, sorry,I meant on LP64 platforms.

**Comment by rainers** [comment]
PR https://github.com/D-Programming-Language/dmd/pull/5038 showed related problems.

I agree with Iain here. I expect `long long` is 64-bit for all supported platforms so it seems a natural choice for D's `long`. `int64_t` being defined as just `long` on some platforms is nasty, but we could define aliases in core.stdc.config to map the C99 types, e.g. `alias c_int64_t = c_long;`, according to the definitions of stdint.h that comes with the target C compiler.

**Comment by WalterBright** [comment]
> There is no notion of 'C long' in D

`size_t` mangles to 'm' on C++ Linux64. How do you propose to deal with that?

**Comment by ibuclaw** [comment]
> size_t mangles to 'm' on C++ Linux64. How do you propose to deal with that?

Fix the problems preventing ``__c_long`` from being treated seamlessly like a first class integer?

To be honest, the real question that needs to be answered for is this:  D has 4 distinct built-in types of integers (excluding aliases and cent), whereas C/C++ has 5 (excluding typedefs, __int128 and special purpose types).  How do we provide for such a glaring hole?

**Comment by yebblies** [comment]
I'm in favour of adding more integral types to D, that behave identically to the same-size built-ins except for C++ mangling.  C++ interop is important enough to do this right, assuming it can be done in a reasonably clean way.

**Comment by ibuclaw** [comment]
> I'm in favour of adding more integral types to D

Having only fixed-sized types is something that D does right.  Variably sized types should be shunted to the library, and only support them in the compiler only for C++ ABI compatibility (we can expose the size/type through ``__traits`` in user code, and ``Target::`` internally).

**Comment by WalterBright** [comment]
> C/C++ has 5

D: char, wchar, dchar, byte, ubyte, short, ushort, int, uint, long, ulong: I count 11

C++: char, signed char, unsigned char, char16_t, char32_t, wchar_t, short, unsigned short, int, unsigned, long, unsigned long, long long, unsigned long long - I count 15 types. (They all mangle differently.)

The main problem is with long mangling, though all of the above have troubles because of the varying sizes and unpredictable signed-ness of `char`.

This PR doesn't solve the issue at all, and worse, by making size_t mangle differently than it does on Linux, it isn't compatible with a presumably vast amount of C++ code.

**Comment by ibuclaw** [comment]
> D: char, wchar, dchar, byte, ubyte, short, ushort, int, uint, long, ulong: I count 11

I ignored character types and signedness of integers.

> The main problem is with long mangling, though all of the above have troubles because of the varying sizes and unpredictable signed-ness of char.

I don't see the unpredictable signed-ness of char as being *my* problem.  Varying sizes of ``short`` and ``int`` are only problematic from an ABI stance, though this is easily got around by promoting the type for the purpose of passing or returning it.

> This PR doesn't solve the issue at all

It is but one piece of the puzzle.  It seems that ``__c_long`` is never defined on 64bit Linux, someone or I should raise a PR for that in druntime.

**Comment by yebblies** [comment]
I agree that the current situation needs to be improved, although unlike this PR it does at least work for DDMD.  The best idea I have at the moment is to introduce a bunch of magic types that match C++ basic types for mangling, but are otherwise valid D types.

Something like:
```d
version (LP_64)
{
    alias c_long = long;
    alias c_ulong = ulong;
    ...
}
else
{
    alias c_long = int;
    alias c_ulong = uint;
    ...
}

pragma(mangle, "char", c_char) struct cpp_char;
pragma(mangle, "signed char", c_schar) struct cpp_signed_char;
pragma(mangle, "unsigned char", c_uchar) struct cpp_unsigned_char;
pragma(mangle, "signed short", c_short) struct cpp_signed_short;
pragma(mangle, "unsigned short", c_ushort) struct cpp_unsigned_short;
pragma(mangle, "signed int", c_int) struct cpp_signed_int;
pragma(mangle, "unsigned int", c_uint) struct cpp_unsigned_int;
pragma(mangle, "signed long", c_long) struct cpp_signed_long;
pragma(mangle, "unsigned long", c_ulong) struct cpp_unsigned_long;
pragma(mangle, "signed long long", c_llong) struct cpp_signed_long_long;
pragma(mangle, "unsigned long long", c_ullong) struct cpp_unsigned_long_long;
```

Opaque structs are the closest we have to typedefs, so they'd probably do the job.  I think it's probably necessary to add implicit conversions to and from normal integral types.

I don't really like adding this, but D needs C++ interop and C++ interop needs proper type support.

**Comment by ibuclaw** [comment]
> I don't really like adding this, but D needs C++ interop and C++ interop needs proper type support.

Does it really?  I think you are bargaining too much hassle (have you even *looked* at my bug report where a C++11 ABI change breaks the compatibility with ``std::basic_string`` tests? Guess you need an ``-std=c++98`` switch now :-)

Things are much easily binded together through a loose C interface, and probably will end up being the case in the end.  But no ``x`` or ``y`` mangling on LP64 platforms pretty much kills any chance of gdc codebase being compatible at link-time (eg: ``struct longdouble`` -> ``struct real_t`` bindings use it).

**Comment by yebblies** [comment]
I have no idea why you think `x` and `y` are so special.  We lose one set of 64-bit integers either way.

**Comment by ibuclaw** [comment]
I have not the patience to push this upstream (and __c_long still has it's quirks).

**Pull request closed without merging**
