### PR TITLE
fix issue 20675 - dip1000 improper error about copying scope paramete…

### PR DESCRIPTION
**Pull request by aG0aep6G**
…r into allocated memory

@WalterBright, you probably want to have a look.

### CODE REVIEW

**Comment by WalterBright** [comment]
Ya beat me to it :-) and it seems we came up with the same solution. Anyhow, the test case is excessive. It should be appended to `test/compilation/scope.d` and consist of merely:
```
// https://issues.dlang.org/show_bug.cgi?id=20675

struct D
{
    int pos;
    char* p;
}

void test(scope ref D d) @safe
{
    D[] da;
    da ~= D(d.pos, null);
}
```
This will make the incremental test time insignificant compared with making an executable.

**Review by WalterBright — DISMISSED** [review]
see comment

**Comment by aG0aep6G** [comment]
> Anyhow, the test case is excessive. It should be appended to `test/compilation/scope.d`

done

**Comment by aG0aep6G** [comment]
Similar bug and fix: #10935

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
