### PR TITLE
Fix wrong version number 2.069 to 2.070 in stable branch

### PR DESCRIPTION
**Pull request by WebDrake**
This patch conflates patches 6c434bd5d9f73aac1926a24647cce8c727f9a3a0 and fce8f7c630864c38810f9633f53a156747d5c23f from master.

This PR is to make sure that stable also gets the changes, since currently phobos v2.070.0 is generating a libphobos2.so.0.69 due to the VERSION problem.

### CODE REVIEW

**Comment by ibuclaw** [comment]
@MartinNowak - this is OK.

**Comment by MartinNowak** [comment]
So we have to rebuild the release.

**Comment by WebDrake** [comment]
> So we have to rebuild the release.

Wondering if there's something that can be done testing-wise that compares release tag to VERSION to ensure this doesn't happen again.  (That's assuming there is a reason to continue using a VERSION file rather than just taking all versioning info direct from git tags.)

**Comment by ibuclaw** [comment]
``git describe`` could be a possible candidate.

**Comment by WebDrake** [comment]
> `git describe` could be a possible candidate.

Yup.  What I'm wondering is, does the VERSION file actually need to be there in the source tree as-is, or is it only necessary for e.g. tarball delivery of a release?

If the latter, it could be made an auto-generated file directly coming from the `git describe` command.

**Comment by yebblies** [comment]
IIRC it's there so you can build without git

**Comment by WebDrake** [comment]
> IIRC it's there so you can build without git

That's what I assumed.  But I think there are other ways that could be addressed.

The point for me is this: how many scenarios are there for people building without git, other than downloading a tarball of the source (or something similar, like a deb-src package)?

If that's 99% of the building-without-git use-cases, then the VERSION file might as well be turned into something that can be auto-generated when a tarball is created.

**Comment by MartinNowak** [comment]
At least we don't need to rebuild the release, b/c we already overwrite this file during release building.
https://github.com/D-Programming-Language/installer/blob/dabeba4b32e8301be67401bcd871a47dd9f56456/create_dmd_release/build_all.d#L352

**Pull request merged**
