### PR TITLE
Issue 13270 - ddoc can't find parameters of ditto'd function overloads

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=13270

### CODE REVIEW

**Comment by WalterBright** [comment]
I appreciate what you're doing, but realistically, all these refactorings make things really hard to review.

**Comment by 9rnsr** [comment]
So what I should do? All commits are necessary for the last change.

**Comment by 9rnsr** [comment]
@WalterBright OK, I separated some preparation changes to #4642. They're still necessary to fix 13270, but does not change the current behavior.

**Comment by 9rnsr** [comment]
All refactoring changes were merged in master. So this PR contains changes only for the bugfix now.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
