### PR TITLE
[DSSv3] Fix Issue 15828 - DMD should refuse comparing unions

### PR DESCRIPTION
**Pull request by teodutu**
Changes:
- Add check in `dmd/opover.d` to verify if the compared structs are
unions and output an error if the check passes
- Verify the error by `tests/fail_compilation/test15828.d`
- Add `changelog/union-comparison.dd` to explain these changes

### CODE REVIEW

**Review by ibuclaw — CHANGES_REQUESTED** [review]
Needs DIP, needs deprecation, needs approval.

**Comment by ibuclaw** [comment]
Hi @teodutu.  Thanks for your contribution, as this is a language breaking change that affects both industry and community projects, this needs:
1. A DIP
2. Approval from maintainers
3. Follow the proper [deprecation process](https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1013.md).

**Comment by teodutu** [comment]
Thanks for the advice @ibuclaw! I'll take the steps you suggested.

**Comment by thewilsonator** [comment]
Also the error messages need to be improved 
```
std/array.d(1386): Error: incompatible types for array comparison: `U[]` and `U[]`
--
  | std/array.d(1388): Error: incompatible types for array comparison: `U[]` and `U[]`
  | std/array.d(1386): Error: incompatible types for array comparison: `U[]` and `U[]`
  | std/array.d(1388): Error: incompatible types for array comparison: `U[]` and `U[]`
```

**Pull request closed without merging**
