### PR TITLE
investigate issue 21265: Test Suite Heisenbug: FAILED targets: - runn…

### PR DESCRIPTION
**Pull request by rainers**
…able/testptrref_gc.d

### CODE REVIEW

**Comment by rainers** [comment]
@wilzbach Could it be just a matter of updating the host compiler as in https://github.com/dlang/dmd/pull/11531/files ? The reported failures were the same for Win64.

**Comment by wilzbach** [comment]
Likely, but then we would need to officially raise the minimum bootstrapping version, but IMHO doing this once for every ten releases should be fine. Decision isn't up to me though.

**Comment by rainers** [comment]
Alternatively, we could redefine bootstrapping to only build the compiler with the host compiler, then rebuild it with itself and run the tests only on the result of the latter build. This would only require a subset of the host compiler features, e.g. no `-lowmem` as suspected in the random failures.

**Comment by RazvanN7** [comment]
Is there any use for this PR? If not, please close.

**Comment by RazvanN7** [comment]
I see there is no activity here, therefore I will take the liberty of closing this PR. If you still need this you can always reopen.

**Pull request closed without merging**
