### PR TITLE
issue 17083 - convert final switch(bool) to IfElse during the semantic pass

### PR DESCRIPTION
**Pull request by ghost**
I've been warned by UplinkCoder that this is too much for so few. Nevertheless DMD backend is so bad with this pattern that I had to try this.

### CODE REVIEW

**Comment by LemonBoy** [comment]
Since the `switch` is always lowered by the backend into a staircase of `if`/`else` (see `s2ir.d`) I don't see how moving the operation in the frontend would help, it just creates a "drift" of the IR from the original source code for no reason.
If you feel that this idiom (that I find pretty..peculiar) isn't codegen'd as well as a simple if/else then I'd suggest to shift your attention to `s2ir` instead.
Just my 2cents.

**Comment by BBasile** [comment]
> the switch is always lowered by the backend into a staircase of if/else (see s2ir.d)

It is not. I was also surprised to see the disassembly results (see on [bugzilla](https://issues.dlang.org/show_bug.cgi?id=17083)). I know that DMD is not designed for well optimized code but this code is seriously not possible with -O toggled on.

**Comment by LemonBoy** [comment]
I was wrong on the _always_ but it should be relatively easy to do so for this case as done [here](https://github.com/dlang/dmd/blob/master/src/s2ir.d#L520).

**Review by MartinNowak — CHANGES_REQUESTED** [review]
Agree w/ @LemonBoy, switch optimizations belongs into the backend, e.g. [search BCjmptab](https://github.com/dlang/dmd/search?utf8=%E2%9C%93&q=BCjmptab).
In particular considering that [gdc](https://godbolt.org/g/CQxJjt) and [ldc](http://ldc.acomirei.ru/#compilers:!((compiler:ldc,options:'-O',source:'bool+test_final_switch_bool2(bool+a)%0A%7B%0A++++final+switch(!!a)%0A++++%7B%0A++++++++case+false:+return+true%3B%0A++++++++case+true:+return+false%3B%0A++++%7D%0A%7D%0A')),filterAsm:(commentOnly:!t,directives:!t,labels:!t),version:3) generate optimal code.

Besides what's the use case for `final switch (bool)`?

**Comment by WalterBright** [comment]
Optimizations like this belong in the back end, not the front end. They're a lot easier to do in the back end as well, in particular https://github.com/dlang/dmd/blob/master/src/backend/blockopt.c

I'm going to close this. The optimization is still a good idea, please do it in blockopt.c (where similar optimizations reside).

**Pull request closed without merging**
