### PR TITLE
[DDMD] [cleanup] Completely remove toelfdebug.c

### PR DESCRIPTION
**Pull request by yebblies**
It doesn't do anything on non-windows.

### CODE REVIEW

**Comment by WalterBright** [comment]
I know it doesn't do anything on Windows. It's not supposed to. Its purpose is to eliminate the conditional compilation preprocessor use in the front end.

**Comment by yebblies** [comment]
> I know it doesn't do anything on Windows.

It doesn't do anything anywhere.

> Its purpose is to eliminate the conditional compilation preprocessor use in the front end.

`toobj.c` is not in the frontend, it's in the glue layer.  I don't see how keeping this extra file is worth it.

**Comment by yebblies** [comment]
One of the goals I'm going for here is cross-compiling.  Having to rebuild dmd to target a different platform makes that impossible, and so I'd like to remove most of the build-time target decisions from dmd.  Having two source files implement the same functions is a problem for this.

I'm open to other suggestions for achieving the same thing, if you have any.

**Comment by WalterBright** [comment]
By removing conditional compilation from DMD, it does what you are asking for - removing build time target decisions from DMD.

**Comment by WalterBright** [comment]
I have gone to some effort to remove `#if TARGET_????` code from dmd. It's not going back in.

**Comment by yebblies** [comment]
> By removing conditional compilation from DMD, it does what you are asking for - removing build time target decisions from DMD.

Wrong.  You're including different files in the build based on target, which is worse.

**Pull request closed without merging**
