### PR TITLE
fix #20610 aliasing for fields does not work

### LINKED ISSUE #20610: aliasing for fields does not work
```
struct T {
    int k,i = 2;
}

struct S {
    int x;
    T t;
    alias ti = t.i;
}

int main() {
    T t = T(1, 2);
    S s;
    assert(s.ti == 2); // Error: accessing non-static variable `i` requires an instance of `T`
    return 0;
}
```
`s.ti` should be equivalent to `s.t.i`

### PR DESCRIPTION
**Pull request by WalterBright**
Issue: https://github.com/dlang/dmd/issues/20610

@TurkeyMan I think you'll like this!

### CODE REVIEW

**Comment by WalterBright** [comment]
Once again, the tester does not run the test suite first, it tries to build Phobos first.

The tester should run the test suite FIRST, as it is designed to be run FIRST, not LAST.

The test suite is filled with already reduced, standalone tests. This makes it much much easier to fix a problem than trying to debug the massive tangle that is Phobos.

@dkorpel can this be fixed?

**Comment by WalterBright** [comment]
```
std/experimental/allocator/common.d(144): Error: no property `Allocator` for `a` of type
```

**Comment by thewilsonator** [comment]
please use `fix #20610` for PR and commit titles.

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
> please use fix #20610 for PR and commit titles

Done. Can you please fix  the boilerplate message "In preparation for migrating from Bugzilla to GitHub Issues, the issue reference syntax has changed. Please add the word "Bugzilla" to issue references. For example, Fix Bugzilla Issue 12345 or Fix Bugzilla 12345.(Reminder: the edit needs to be done in the Git commit message, not the GitHub pull request.)" added to every PR?

**Comment by thewilsonator** [comment]
https://github.com/dlang/dlang-bot/pull/305#discussion_r1870871793 I suspect that setting that array to empty is the easiest way to do that. N.B that PR was from when the transition to GitHub issues was still ongoing, it is likely to be simpler now that bugzilla is read-only.

**Comment by dkorpel** [comment]
> @dkorpel can this be fixed?

Martin has started work on removing the test suite's Phobos dependency, but it's still WIP: https://github.com/dlang/dmd/pull/16587 

I recommend running the test suite locally, you have more control and get way quicker feedback that way.

**Comment by Bolpat** [comment]
I don’t know if that’s intended, but:
```d
struct T { int x; }

struct S
{
    T t1, t2;

    alias x1 = t1.x;
    alias x2 = t2.x;
    
    void f()
    {
        x1 = x2; // error
        this.x1 = this.x2; // good
    }
}
```

**Comment by Lars-Kristiansen** [comment]
are external aliases supported too ? (example in https://github.com/dlang/dmd/issues/17532)

**Pull request merged**
