### PR TITLE
Eclipse Luna IDE Support

### PR DESCRIPTION
**Pull request by nordlow**
This PR adds an Eclipse Luna (latest stable) project for
- developing (using navigation and Intellisense-completion), 
- building, and 
- debugging

DMD. I did it through the standard
- _File_ -> _Import_ -> _Existing Code as Makefile Project_
- Project local settings for assume .c .h are C++ source instead of C.
- Project local setting that registers `src` as a source directory (tree) to make debugger find sources.
- Add a `Debug` build target that uses class build through `make ENABLE_DEBUG=1`.

See also: 
- http://forum.dlang.org/thread/kvqklkmjnajuhrlthuug@forum.dlang.org?page=1
- https://stackoverflow.com/questions/28286568/make-eclipse-understand-that-c-and-h-is-c

_All you Emacs hackers_: Note that Eclipse includes a quick setting (click at _Window_ => _Preferences_ and search for _Emacs_) for adjusting editing keybindings to Emacs for the most common editing operations including increment search (C-s/r), basic navigation, cut and paste and undo.

### CODE REVIEW

**Comment by nordlow** [comment]
What do you mean by IDE-specific project files? Is this whole PR bad? I noticed that DMD has some xcode settings. Why not add Eclipse aswell then?

**Comment by nordlow** [comment]
Should I close this?

**Comment by MartinNowak** [comment]
I'll also remove the XCode project, putting a sub folder into .gitignore and adding wiki infos is the way to go IMO.

**Comment by jacob-carlborg** [comment]
I you remove the Xcode project you better remove the Visual Studio project as well.

**Comment by MartinNowak** [comment]
As I said here or in the other thread, we need the VS project to build a 64-bit DMD on Windows.

**Comment by WalterBright** [comment]
If it's simple to create one, I don't see much point in adding this.

**Comment by jacob-carlborg** [comment]
The VS compiler cannot be used from a makefile?

**Comment by nordlow** [comment]
For the record I'll try keeping https://github.com/nordlow/dmd/tree/eclipse-ide-support update along the way.

**Pull request closed without merging**
