### PR TITLE
Issue 15394 - [internal] CompileExp and FileExp has same op TOKmixin

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=15394

<del>Add a new token `TOKmixinfile`.</del>

Use `TOKscope` for ScopeExp, then use `TOKimport` for FileExp.

### CODE REVIEW

**Comment by yebblies** [comment]
I always thought `ScopeExp` should use `TOKscope`, then `TOKimport` would be free for this.

**Comment by 9rnsr** [comment]
@yebblies I've thought same thing, but it would be a little big impact for other PRs. Is it better?

**Comment by yebblies** [comment]
I think so, and it looks like only ~30 places need changing so I don't think it should have too much impact on other PRs.  Honestly I don't really understand what `ScopeExp` is used for, so I'm not sure if `TOKscope` is actually more appropriate for it than `TOKimport`.

**Comment by 9rnsr** [comment]
OK, I updated commits to do it. Please wait the auto-tester result.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks!

**Pull request merged**
