### PR TITLE
Issue 13944 - Built-in stringof and mangleof properties are unnecessarily fixed to the type 'string'

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=13944

### CODE REVIEW

**Comment by yebblies** [comment]
Could you please add a few tests that check the wide strings generated are correct?

**Comment by 9rnsr** [comment]
OK, I moved the test suite to `runnable` directory.

**Comment by yebblies** [comment]
Couldn't you have just used static assert?  It doesn't really matter.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Now `S.stringof` may generate three different string literals. The runtime assertion will check that the strings won't share the same memory.

**Comment by 9rnsr** [comment]
Thanks!

**Pull request merged**
