### PR TITLE
Create a filter script for visual studio project filter [WIP]

### PR DESCRIPTION
**Pull request by 12345swordy**
Ditto.

### CODE REVIEW

**Comment by PetarKirov** [comment]
@12345swordy I'm using Linux, so I can't do a proper review, but I opened the [raw file](https://raw.githubusercontent.com/dlang/dmd/053914d0971293b0e2df87b519140297ec9d1b8e/src/vcbuild/dmd.vcxproj.filters) in my browser (the diff is to large to load in GitHub) and I noticed that that there's a ton of repetiion. For example:
* `<ClInclude Include="../dmd/**/*.h">` is repeated 50 times
* `<DCompile Include="../dmd/**/*.d" />` is repeated 150 times
* `<DCompile Include="..\dmd\aggregate.d" />` is repeated 89 times
* `<DCompile Include="..\dmd\aggregate.d">` is repeated 6 times
* etc.

Can you look into eliminating the repetition? From a maintenance point of view using wildcards seems the best approach, though I'm not an expert in this area and I can't say for sure. According to one StackOverflow answer (https://stackoverflow.com/a/2841976) it seems like `vcxproj.filters` could be considered a matter of personal preference where each developer may prefer a different view of the files, so in that case it may be better to gitignore these files. But in any case, since I'm not a VS user anymore, I prefer others to decide.

**Comment by 12345swordy** [comment]
Wild cards are not supported in vc project and is frown upon.
See here: https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-files-and-wildcards?view=msvc-160

**Comment by rainers** [comment]
> * `<ClInclude Include="../dmd/**/*.h">` is repeated 50 times

The filter generation inside VS fails with the wildcard approach in the vcxproj files and generates these nonsense filter files. That's why you cannot really edit the project in Visual Studio. The wildcard approach is a pure win here, though, as it makes the VS project agnostic to most changes and avoids updates by contributors, especially when working on other platforms.

Maybe you can generate a reasonable filter file with https://github.com/rainers/dlangvs/blob/master/vcbuild/genvcxfilters.d (it's used to build the respective files for druntime and phobos).

**Comment by RazvanN7** [comment]
@12345swordy What are your plans with this PR? Currently, this PR does nothing.

**Comment by 12345swordy** [comment]
@RazvanN7 I am planing to create a filter generator based on the code that @rainers posted, so that it will filter the files properly.

**Comment by 12345swordy** [comment]
Just a small fyi. I am using c# for this as the xml library is built into the standard library. The xml in the d standard library has been mark deprecated, and I don't want involve third party libraries regarding xml in the d language.

**Comment by MoonlightSentinel** [comment]
This is just a tool and dub is part of the official d distribution. There are several examples where dub is already used across the core repositories (e.g. the test extractor in druntime/phobos), so I don't see a problem in depending on a xml library.

Requiring a different toolchain is less accessible than dub IMHO.

**Comment by 12345swordy** [comment]
If you have visual studio installed, then it is reasonable to assume that you have C# toolchain installed as well. I am creating this tool, because @rainers here, considered to be burden on the maintainers to keep the project files up to date.

@MoonlightSentinel I am not interested in getting dub to generate the project files by having it to build dmd/phobos/druntime. You guys have the build.d file to achieve that already. Unless you have plans for build.d to generate project files, I am sticking to my strategy here of using C# to generate the project files for dmd/phobos/druntime.

**Comment by 12345swordy** [comment]
I had decided that is simply too much work to generate a filter for visual studio. It be much easier and better for the developers to do it manually then to spent weeks on it.

**Pull request closed without merging**
