### PR TITLE
refactor: make interfaces a proper D array

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by yebblies** [comment]
No longer matches the type in the C++ header?

**Comment by WalterBright** [comment]
Actually, it does, as an [ ] is a length,ptr pair.

**Comment by yebblies** [comment]
I really hope you're joking.  There's no way that having one variable on one side and two on the other is acceptable.  If it's time to start using arrays in places that cross the language boundary then it's time to introduce a struct for them on the C++ side.

**Comment by WalterBright** [comment]
Frankly that just produces more cruft and bloat. The .h and the .d declarations have to be in sync, and this way is easier to check than going off and checking another declaration. Furthermore, the C++ code never references it.
One is always going to have to be careful in lining up D declarations with C++ ones, making aggregate types doesn't necessarily inure one from errors or relieve one of checking such things.

**Comment by yebblies** [comment]
Checking that use of `T[]` is matched with `DArray<T>` is MUCH easier than ensuring the `size_t`/`T*` pair is in the correct place and order etc.  That C++ interfacing is already tricky is no reason to make it worse unnecessarily.

As two example of similar things:
- Passing around `T[]` as a `long` in druntime - it worked until it didn't.
- Passing `char[]` to C variadic functions - it worked until it didn't.

While you and I have this level of D/C++ ABI knowledge, it's unreasonable to expect than anyone looking at this code will understand it.

And for what?  A 6-line
```cpp
template<typename T>
struct DArray
{
    size_t length;
    T *ptr;
};
```
will match both the ABI and the API!

Using matching types is NOT cruft.  Using low-level ABI hacks is asking for trouble.

**Comment by WalterBright** [comment]
> While you and I have this level of D/C++ ABI knowledge, it's unreasonable to expect than anyone looking at this code will understand it.

I'd expect anyone looking at the .h files of the compiler interface to the back end needs to understand that [ ] is a pair. Besides, the only reason it is there is to get the correct size of the ClassDeclaration struct, as the back end code does not need it.

> A 6-line

I'm not a big fan of layers of semantic indirection making it harder to read the code, unless that semantic indirection adds real value. I don't think it does here. And it tempts people to start adding member functions, etc., for what is really just a spacer.

> will match both the ABI and the API!

Not all the ABIs have matched behaviors of structs and pairs of the same size. It's always an uneasy match.

**Comment by WalterBright** [comment]
This is blocking my work, and I need it pulled. So I decided to do it your way.

**Comment by yebblies** [comment]
I can't argue with that.  Thank you.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
