### PR TITLE
fix Issue 19499 - __c_long_double has exact match with double

### PR DESCRIPTION
**Pull request by WalterBright**
This reverts https://github.com/dlang/dmd/pull/8632/ which was an attempt to fix https://issues.dlang.org/show_bug.cgi?id=19201 but dmd source code should be fixed instead of changing the language semantics.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Target stable.

**Comment by ibuclaw** [comment]
This will cause a bootstrap build regression.

Without checking, first point of call for changing dmd would be the sinteger_t aliases.
```
alias sinteger_t = int64_t;
alias uinteger_t = uint64_t;
```
So there wouldn't be any implicit D long <-> C long conversions in the first place.

Can work backwards from there to find less breaking ways to fix dmd source.

**Comment by WalterBright** [comment]
You listed about 4 places in dmd source, why not just insert a cast in those places?

**Comment by ibuclaw** [comment]
Looks like druntime has mitigated this, so no longer reproducible on Linux (https://github.com/dlang/druntime/pull/2302).  But will still fail to build on OSX.

> You listed about 4 places in dmd source, why not just insert a cast in those places?

There are explicit casts in all linked places, the kinds of errors I was seeing:
```
gcc/d/dmd/dcast.d:381:52: error: cannot cast expression ‘cast(long)value’ of type ‘long’ to ‘longdouble’
                 const f = cast(T) cast(sinteger_t) value;
                                                    ^
gcc/d/dmd/dcast.d:459:22: error: template instance ‘dmd.dcast.implicitConvTo.ImplicitConvTo.visit.isLosslesslyConvertibleToFP!(longdouble)’ error instantiating
                 if (!isLosslesslyConvertibleToFP!real_t)
                      ^
```

Casts would mean adding overrides where implicit `long` -> `int64_t` conversion is rejected.
```
static if (!is(int32_t == int))
    void set()(int d) { return this.set(cast(int32_t)d); }
static if (!is(uint32_t == uint))
    void set()(uint d) { return this.set(cast(uint32_t)d); }
static if (!is(int64_t == long))
    void set()(long d) { return this.set(cast(int64_t)d); }
static if (!is(uint64_t == ulong))
    void set()(ulong d) { return this.set(cast(uint64_t)d); }
```

It seems odd however that implicit conversion may work on some, but fail on other host systems depending on what druntime bindings are aliasing today.

**Comment by WalterBright** [comment]
@ibuclaw I don't really understand your comment. What I need is can you fix the dmd code to fix the bootstrap errors you're seeing? Can you submit a PR for that?

**Comment by ibuclaw** [comment]
The bootstrap errors are no longer reproducible since druntime changed aliases of int64_t and uint64_t in https://github.com/dlang/druntime/pull/2302.

**Comment by ibuclaw** [comment]
The bootstrap errors are in places where there's already appropriate casting.
```
f = cast(longdouble) cast(long) value;
```
The errors are local to the longdouble implementation which only has overrides for int64_t/uint64_t, not long/ulong.

What I posted is what adding long and ulong overrides would look like in gdc's longdouble.  Which just looks silly.

**Comment by WalterBright** [comment]
It doesn't matter if it looks silly in the dmd source code. What does matter is adding an "exact" match of `__c_long_double` with `double`, which will cause no end of grief.

**Comment by ibuclaw** [comment]
Well I am not happy that conversely, having `long` and `int64_t` _not_ match will cause the same level of grief.

This isn't just compiling dmd itself, but anyone interfacing with a C++ library that uses `int64_t`/`uint64_t` in their public API.

**Review by ibuclaw — APPROVED** [review]

**Comment by WalterBright** [comment]
> Well I am not happy that conversely, having long and int64_t not match will cause the same level of grief. This isn't just compiling dmd itself, but anyone interfacing with a C++ library that uses int64_t/uint64_t in its public API.

This issue affects C++ as well, because it affects C++ name mangling. Different integer types with the same size can have different mangling. D code should use core.stdc.stdint's definitions of int64_t and uint64_t to match the C++ mangling.

**Comment by ibuclaw** [comment]
Well it's no good if getting the correct C++ mangling means making code that uses it uncompilable.
```
import core.stdc.stdint;

void func(uint64_t r);
void func(int64_t r);

void main()
{
    func(0L);
}
```
It is not ambiguous here as to which overload should be called.

**Pull request merged**
