### PR TITLE
DIP25: don't forget opAssign

### PR DESCRIPTION
**Pull request by WalterBright**
which needs to be annotated with 'return'.

### CODE REVIEW

**Comment by andralex** [comment]
urgh

**Comment by andralex** [comment]
Should the DIP be updated?

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
It needn't be updated for this. Since it's an auto-generated function, it's up to the generator to do it correctly.

**Comment by joakim-noah** [comment]
Looks like this pull broke druntime compilation on linux: wasn't it run through the auto-tester first?

**Comment by WalterBright** [comment]
The druntime pull broke it, not this one.

**Comment by joakim-noah** [comment]
Yes, locally reverting this one didn't fix it, looks like it was the since reverted druntime pull.

**Pull request merged**
