### PR TITLE
Improve FuncExp: Don't check global.errors

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by WalterBright** [comment]
1. This is not just a refactor, there are behavior changes here, like the first two commits.
2. All three of these commits have nothing whatsoever to do with each other, and should be separate PRs.

I am serious about having one issue per PR. This is another kitchen sink one. Please stop doing this. I have explained why at least a dozen times.

**Comment by 9rnsr** [comment]
I put only one commit in this PR. How about this?

**Comment by WalterBright** [comment]
Much better. So now I can say, the point of the checks before successive semantic passes was to not continue if there were errors, as subsequent errors tend to be noise rather than new errors. This PR disables all that without explanation. (This is why this is not a refactor.)

**Comment by 9rnsr** [comment]
The subsequent noisy errors are not shown. When semantic analysis found an already error entity, it won't generate further errors. Instead it would just raise an ErrorExp.
Actually this PR doesn't break any diagnosric tests.

If previous error really needs to block subsequent analysis, it can be checked in semantic2 or semanric3, by using FuncDeclaration.errors. Bui I'm not adding such extra check so it's not necessary today.

**Comment by WalterBright** [comment]
>The subsequent noisy errors are not shown. When semantic analysis found an already error entity, it won't generate further errors. Instead it would just raise an ErrorExp.

This is the theory, but the ErrorExp conversion is incomplete. Secondly, if one is relying on ErrorExp, then there should be an assert that if the error count changes then there **is** an ErrorExp, before assuming that to be the case and removing the code.

> Actually this PR doesn't break any diagnosric tests.

Those tests are hardly comprehensive.

> If previous error really needs to block subsequent analysis,

It does. It's the whole concept behind the 'poisoning' approach to dealing with error recovery, and it has been a big success for D.

> it can be checked in semantic2 or semanric3, by using FuncDeclaration.errors. Bui I'm not adding such extra check so it's not necessary today.

Then this PR is premature. Removing these checks is the last step, not the first.

**Comment by 9rnsr** [comment]
I thought this is row risk because
- `FuncDeclaration.errros` is already sync with the condition `FuncDeclaration.type.ty == Terror`, so it's reliable.
- `FuncDeclaration.semantic3` is still using global.errors to calculate `sematnicErrors`, so it's reliable old way.

**Comment by 9rnsr** [comment]
I'm tired...

**Pull request closed without merging**
