### PR TITLE
Debug Azure V2

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Reverts dlang/dmd#12560 because it's the only PR that looks related.

### CODE REVIEW

**Comment by andralex** [comment]
Is that only on win32? I got greedy and eliminated the special casing of win32 in OutBuffer's destructor.

**Comment by MoonlightSentinel** [comment]
Yes, only the OMF builds. Might be some bug in the DMC runtime?

**Comment by MoonlightSentinel** [comment]
(But this is just a shot in the dark, might be completely unrelated)

**Comment by ibuclaw** [comment]
Looks like the segfault on optlink still occurs after revert.

**Pull request closed without merging**
