### PR TITLE
Add a test for dmd --help output

### PR DESCRIPTION
**Pull request by MoonlightSentinel**

### CODE REVIEW

**Comment by Geod24** [comment]
Oh it's going to be painful to modify this every time a switch is changed...

**Comment by MoonlightSentinel** [comment]
Could change this test to only verify some of those switches and ignore the rest, e.g. `-m32` and `-m64` (assuming that those will never be changed)

**Comment by AndrejMitrovic** [comment]
I think we should probably just turn it into a unittest like Rainer said.

**Comment by MoonlightSentinel** [comment]
Modified it to only check `@<cmdfile>`, `-m64`  and `-main` which will probably never change. Other flags are ignored and hence won't cause trouble for future changes.

> I think we should probably just turn it into a unittest like Rainer said.

This doesn't affect your PR, it just enures that we don't have untested code which could silently break again....

**Review by Geod24 — APPROVED** [review]
Alright, let's give it a try

**Pull request merged**
