### PR TITLE
[TEST] Enable -preview=fieldwise by default

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Just checking the impact on BuildKite

### CODE REVIEW

**Comment by nordlow** [comment]
How will this effect the generated code?
- Faster?
- (Exception) saferr?

**Comment by MoonlightSentinel** [comment]
The code will be more correct, see https://github.com/dlang/dmd/blob/4accb77f1b7b9e48f0227111e68ab70d90c3e30d/changelog/no-cmpsb.dd

**Comment by MoonlightSentinel** [comment]
The current test failure boils down to this example:

```
struct S {}

int foo(S a, S b)
{
    if (a == b)
        return 0;

    return 1;
}
```

The preview apparently makes it possible to const-fold the equality test and hence correctly issues a warning that `return 1;` is unreachable.

**Comment by nordlow** [comment]
Thanks

**Comment by MoonlightSentinel** [comment]
Well, this diagnostic makes it currently impossible for generic code to be compilable with and without this preview (e.g. phobos). The compiler will either report unreachable code with  `-preview=fieldwise` or missing `return...` without...

**Comment by nordlow** [comment]
I believe we should let @andralex and @WalterBright discuss this showstopper.

**Comment by wilzbach** [comment]
FYI: @atilaneves replaced Andrei for official decisions.

**Comment by nordlow** [comment]
> int foo(S a, S b)
> {
>     if (a == b)
>         return 0;
> 
>     return 1;
> }

What is the origin of this constant-folding?

**Comment by MoonlightSentinel** [comment]
[`VariantN` in Phobos does not compile if a member is an empty struct](https://issues.dlang.org/show_bug.cgi?id=21231)

**Comment by nordlow** [comment]
> [`VariantN` in Phobos does not compile if a member is an empty struct](https://issues.dlang.org/show_bug.cgi?id=21231)

Is this the only stopper?

**Comment by MoonlightSentinel** [comment]
> Is this the only stopper?

The only error in phobos, don't know how it affects other projects.

> That sounds like an easy fix using static if on size of member. Shall I?

Sure, if you can implement `static if (<compiling with preview=fieldwise>)` or another workaround.

**Comment by MoonlightSentinel** [comment]
> Structs with no fields of non-zero size (aka Empty Structs) have a size of one byte.

https://dlang.org/spec/struct.html#struct_layout

**Comment by nordlow** [comment]
> > Structs with no fields of non-zero size (aka Empty Structs) have a size of one byte.
> 

What about


```D
int foo(S a, S b)
{
    static if (S.tupleof.length == 0)
        return 0;
    else
        return (a == b) ? 0 : 1;
}
```

**Comment by MoonlightSentinel** [comment]
Already implemented the detection in dlang/phobos#7622.

The problem is to make it also work when `-preview=fieldwise` is disabled.

**Pull request closed without merging**
