### PR TITLE
fix(dsymbolsem): override methods should have semantic logic on attributes

### PR DESCRIPTION
**Pull request by ljmf00**
Fix issue 23138.

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ljmf00** [comment]
Just cross referencing this with https://github.com/dlang/dmd/pull/12934 to remind myself to implement this for new `throw` attribute.

**Review by RazvanN7 — APPROVED** [review]
What about other attributes?

**Comment by ljmf00** [comment]
> What about other attributes?

I can't think of other conflicts here. `@nogc` can't override to some `@gc` attribute, because there is no such attribute, atm. This is applied to `pure` and `nothrow` except when `throw` is a thing. Can you help me find other cases where this might pass and should fail with some other attribute?

**Comment by ljmf00** [comment]
> What about other attributes?

I can't think of other conflicts here. `@nogc` can't override to some `@gc` attribute, because there is no such attribute, atm. This is applied to `pure` and `nothrow` except when `throw` is a thing. Can you help me find other cases where this might pass and should fail with some other attribute?

**Comment by RazvanN7** [comment]
My expectation is that you override a method and you do not specifically add any attributes, then it should be considered that you are trying to lower the restrictions.

For example:

```d
class A
{
     void fun() pure @nogc @safe nothrow {}
}

class B
{
    override void fun() {}
}
```

I think it is surprising that the compiler simply thinks that `fun` is `nothrow pure @nogc @safe` since it is not annotated that way. I understand that it is not allowed to loosen restrictions in overriding methods, but it might be surprising if someone inherits from a library class and does not annotate the method in any way, but the compiler then complains inside the body about violations of attributes that the user did not write. The alternative should be that the user is forced to spell out all the attributes even if it is redundant. It makes for more readable and less surprising code.

To be clear. I think that in my above example, `B.fun` should issue an error reminding the user that the method he is trying to overwrite needs to follow certain restrictions.

**Comment by RazvanN7** [comment]
Ok, sure, my comment should block the addition of this PR. If more people agree with me we can fix this in subsequent PRs.

**Pull request merged**
