### PR TITLE
speed up arrayObjectsMatch

### PR DESCRIPTION
**Pull request by UplinkCoder**
As always I trust the profiler blindly.
It says the pointer dereference in the loop is a problem.

### CODE REVIEW

**Comment by JackStouffer** [comment]
benchmarks and/or profiler output?

**Comment by UplinkCoder** [comment]
sure!

Before :
8124770  2334876680   432570781          53     _Z16arrayObjectMatchP5ArrayIP10RootObjectES3_
With patch applied :
`8127860  2203966227   292311911          35     int ddmd.dtemplate.arrayObjectMatch(ddmd.root.array.Array!(ddmd.root.rootobject.RootObject).Array*, ddmd.root.array.Array!(ddmd.root.rootobjec...`

**Comment by MartinNowak** [comment]
Don't use dmd's profiler for serious work, use a sampling profiler like [perf](https://perf.wiki.kernel.org/index.php/Main_Page) instead, that will actually point you near the problematic instructions.

**Comment by UplinkCoder** [comment]
@MartinNowak 
I already do.
Personally I use codeXL to look at optimized builds of dmd.
However dmds profile-option gives you a good indication of where to look first.
Also due to it's  massive overhead the profiles tend to show very stable numbers.

**Review by MartinNowak — APPROVED** [review]
Here is the perf result for an optimized dmd compiler (build w/ dmd) running the whole dlang test suite.
profile_arrayobjectmatch
This tells me a couple of things.
- arrayObjectMatch takes 0.15% of the total test suite runtime (considerable, but not high, 107th rank)
- the biggest problem (44%) is that the oa1.dim != oa2.dim check is either hard to predict or that the array objects are not cached (running `perf record -e cache-misses` confirmed the latter)
- the second biggest problem (30%) is loading the array content (due to cache misses/memory access)
- dereferencing the arrays only accounts for 2%, so it won't have much of an effect, but let's still help dmd's crippled optimizer

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
A good optimization would be to change dmd's java-style use of arrays as reference type (new Array) to d-style array as value type. Maybe starting at places that use arrayObjectMatch, could be tricky to use move semantics w/ the current Arrays though.

**Comment by UplinkCoder** [comment]
We cannot easily change to value-type arrays because then we cannot manipulate them.
The dmd-testsuite is not a stress-test for templates. 
In template heavy code this function is rank 4

**Comment by MartinNowak** [comment]
> We cannot easily change to value-type arrays because then we cannot manipulate them.

You can still pass them by reference, it's just about storing e.g. dedtypes in the template, instead of going through another indirection.

**Pull request merged**
