### PR TITLE
Resurrect line spaces in expression.d

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by WalterBright** [comment]
Unfortunately, the diffs are so large github won't show them

**Comment by ibuclaw** [comment]
Raise a bug against github. ;-)

**Comment by ibuclaw** [comment]
https://github.com/dlang/dmd/pull/5593.patch

**Comment by ibuclaw** [comment]
I confirm that all additions are only an empty line.  I don't see how it can harm, but I do note that there is a merge conflict. @9rnsr

**Comment by 9rnsr** [comment]
@ibuclaw Thanks for your review, resolved merge conflict.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
