### PR TITLE
Remove dead code in Array and delete copy constructor

### PR DESCRIPTION
**Pull request by gchatelet**
@yebblies @WalterBright

### CODE REVIEW

**Comment by gchatelet** [comment]
ping

**Comment by yebblies** [comment]
Fails?

**Comment by gchatelet** [comment]
Ha thx, trailing whitespace ... Should be fixed now.

**Comment by gchatelet** [comment]
@MartinNowak it seems like [the failing run](https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2046381&isPull=true) in the autotester is a flake. Can you confirm?

**Comment by MartinNowak** [comment]
Yes, test is already deleted.

**Comment by MartinNowak** [comment]
What's the point of removing the C++ functions? Somebody might end up having to readd those.

**Comment by gchatelet** [comment]
IIUC the C++ part is supposed to be read-only because it's just a way to communicate from backend to frontend. I would have removed all writers if I could but it seems to be used by dmd's backend.

**Comment by gchatelet** [comment]
Ping again. The failures are due to timeouts and not related to the removal of these functions.

**Comment by wilzbach** [comment]
Yeah cleanup by removing - great job at finding this! Auto-tester is passing now btw

**Comment by gchatelet** [comment]
A gentle ping :)

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by ibuclaw** [comment]
> What's the point of removing the C++ functions? Somebody might end up having to readd those.

Such as me. *sigh*

**Pull request merged**
