### PR TITLE
dmd.common.int128: Synchronize with druntime core.int128

### PR DESCRIPTION
**Pull request by ibuclaw**
Use latest version, with more streamlined implementations of 128-bit operations.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by maxhaton** [comment]
```
/var/lib/buildkite-agent/builds/ci-agent-17a361ab-1667-4d3c-850f-452a652b2330-2/dlang/dmd/dmd/src/dmd/common/int128.d(800:11)[warn]: Variable C20_0 is never used.
```

**Comment by ljmf00** [comment]
> ```
> /var/lib/buildkite-agent/builds/ci-agent-17a361ab-1667-4d3c-850f-452a652b2330-2/dlang/dmd/dmd/src/dmd/common/int128.d(800:11)[warn]: Variable C20_0 is never used.
> ```

Shouldn't we add those checks on druntime too?

**Comment by ibuclaw** [comment]
That variable was part of the first commit, so unused since the start.

https://github.com/dlang/druntime/pull/3663

**Comment by ljmf00** [comment]
> That variable was part of the first commit, so unused since the start.
> 
> [dlang/druntime#3663](https://github.com/dlang/druntime/pull/3663)

Yes, but @WalterBright deleted that on DMD side and didn't sync with runtime. Anyway, I suggest removing it here and sync with druntime, although we should have this check on druntime too. I'm going to set up a pre-commit hook config for `dscanner` and try to upstream it here later, but for now, shouldn't we copy-paste the current configuration for style checking?

**Comment by thewilsonator** [comment]
`src/dmd/common/int128.d(800:11)[warn]: Variable C20_0 is never used.`

**Comment by ibuclaw** [comment]
Added change in https://github.com/dlang/druntime/pull/3728.  CI should pass now.

**Review by ljmf00 — APPROVED** [review]

**Pull request merged**
