### PR TITLE
Fix Issue 13512 - Allow non-UTF-8 encoding in shebang line 

### PR DESCRIPTION
**Pull request by CyberShadow**
Submitted on behalf of Ketmar Dark, who suffers from a severe GitHub allergy.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
are you sure it only affects the shebang-line ?

**Comment by CyberShadow** [comment]
Yes, expand the diff.

All changes are contained to the ` if (p && p[0] == '#' && p[1] == '!')` block.

**Comment by UplinkCoder** [comment]
that's fine then,

**Review by UplinkCoder — APPROVED** [review]
LGTM

**Review by andralex — APPROVED** [review]

**Pull request merged**
