### PR TITLE
add foreachDsymbol

### PR DESCRIPTION
**Pull request by WalterBright**
The idea is to use a more modern function style that encapsulates the loop for `members[]`, which has always been problematic because it can expand while looping. If this is successful, I'll expand its use.

### CODE REVIEW

**Comment by thewilsonator** [comment]
1) the loops you're replacing are just straight `foreach`, is there a problem with them?

2) I think it'd be much better to have the uses of the delegate closer to the definition, all the branches of the if/else chain are independent.

**Comment by WalterBright** [comment]
1. foreach can't be used because it caches the loop parameters, and there have been several bugs where the array expanded during iteration.

2. This style consistently replaces several lines of tedious code with one.

3. I don't think it can get closer. I'd use a lambda but then there'd be more duplication.

**Comment by thewilsonator** [comment]
1. So this is not just a refactoring?

2. fine

3. `AtttribDeclaration` is moved further down in an independent if/else chain, move it back up.

Otherwise LGTM.

**Comment by WalterBright** [comment]
1. These bugs keep recurring. I don't know any at the moment.

3. The most common case is VarDeclaration, that's why I put it first.

**Comment by thewilsonator** [comment]
OK.

**Pull request merged**
