### PR TITLE
Merge stable into master

### PR DESCRIPTION
**Pull request by PetarKirov**
I would like to get these commits merged sooner then usual, so that more users can easily test them through the nightly builds which AFAIR are only available for the master branch.

More specifically, issue 15661 was a serious one because it affected safe resource management via RAII. For more info see [these](http://forum.dlang.org/thread/bgmzajszxajcuoqtkahq@forum.dlang.org) [two](https://forum.dlang.org/post/nnjfuqeuprcswsjjfmkl@forum.dlang.org) forum threads.

### CODE REVIEW

**Comment by ZombineDev** [comment]
Oops, it's not as simple as I thought. I'll see if I can fix the merge confict.

**Comment by ibuclaw** [comment]
Why are these not in master?

**Comment by 9rnsr** [comment]
@ibuclaw Because they're regression fixes and targeting next minor release.

@ZombineDev I opened #5466.

**Comment by ZombineDev** [comment]
Thanks @9rnsr! I tried to fix the merge conflict, but I saw that you had made many changes to `expandInline` in master, so I think it would be better to leave the merging to you, as you have far better understanding of the code than I have.

**Comment by ibuclaw** [comment]
@9rnsr everything should go in master first.  Or raise two PRs at the same time.  I see no benefit in targeting stable if master has the same problem.

**Comment by ZombineDev** [comment]
@ibuclaw as per [DIP 75](http://wiki.dlang.org/DIP75) bug fixes should first go into stable, and later merged to master. The only thing that DIP75 doesn't make clear is when exactly should fixes be merged back into master (every two weeks, after the PR is merged or sometime else).

**Comment by ZombineDev** [comment]
Also no commits should go from master to stable.

**Pull request closed without merging**
