### PR TITLE
fix building 64-bit dmd for Windows

### PR DESCRIPTION
**Pull request by rainers**
missing down casts size_t -> uint/int

### CODE REVIEW

**Review by PetarKirov — APPROVED** [review]
LGTM. For reference:
```C
DWORD WINAPI GetFullPathName(
  _In_  LPCTSTR lpFileName,
  _In_  DWORD   nBufferLength,
  _Out_ LPTSTR  lpBuffer,
  _Out_ LPTSTR  *lpFilePart
);
```
(https://msdn.microsoft.com/en-us/library/windows/desktop/aa364963(v=vs.85).aspx)

```C
int WideCharToMultiByte(
  _In_      UINT    CodePage,
  _In_      DWORD   dwFlags,
  _In_      LPCWSTR lpWideCharStr,
  _In_      int     cchWideChar,
  _Out_opt_ LPSTR   lpMultiByteStr,
  _In_      int     cbMultiByte,
  _In_opt_  LPCSTR  lpDefaultChar,
  _Out_opt_ LPBOOL  lpUsedDefaultChar
);
```

(https://msdn.microsoft.com/en-us/library/windows/desktop/dd374130(v=vs.85).aspx)

```C
int MultiByteToWideChar(
  _In_      UINT   CodePage,
  _In_      DWORD  dwFlags,
  _In_      LPCSTR lpMultiByteStr,
  _In_      int    cbMultiByte,
  _Out_opt_ LPWSTR lpWideCharStr,
  _In_      int    cchWideChar
);
```

(https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072(v=vs.85).aspx)

**Review by JinShil — APPROVED** [review]

**Comment by ZombineDev** [comment]
@JinShil feel free to add the `auto-merge` label yourself for obvious changes.

**Comment by JinShil** [comment]
> feel free to add the auto-merge label yourself for obvious changes.

I'm still trying to tread lightly.  :worried:

**Comment by ZombineDev** [comment]
> I'm still trying to tread lightly.  :worried:

That's understandable and a good idea in general. I think with time you'll be able to figure out the right balance between being trigger-happy and too cautious.

**Comment by WalterBright** [comment]
```
https://msdn.microsoft.com/en-us/library/windows/desktop/aa364963(v=vs.85).aspx
```
I suggest in the future to put some links next to the API calls. This makes it very convenient for the developer to check the call against the spec. I know Microsoft changes these links all the time, but it's still better than no link.

I've also started including links in the source code to the the relevant sections of the dlang documentation where it makes sense.

**Comment by rainers** [comment]
> I suggest in the future to put some links next to the API calls.

That's way too much noise IMO. Paste the function name into any search engine and the first result guides you to a recent documentation on MSDN. Or just use "Goto definition" to jump to the appropriate declaration.

**Pull request merged**
