### PR TITLE
WIP: fix Issue 20150 - -dip1000 return attribute must be explicit in pure (use deprecation instead of error)

### PR DESCRIPTION
**Pull request by nordlow**
Adjust https://github.com/dlang/dmd/pull/10924 to emit a deprecation instead of error and see how that goes.

After this gets merged the adding of @trusted qualifiers in the changes at

- https://github.com/dlang/phobos/pull/8088

need to be reverted.

### CODE REVIEW

**Comment by thewilsonator** [comment]
This a a serious bug, please target stable.

**Comment by nordlow** [comment]
```
WARNING: fail_compilation/retscope6.d has multiple `TEST_OUTPUT` blocks and can't be auto-updated
```

Ok to split retscope6.d into 7,8,9, etc?

**Comment by thewilsonator** [comment]
yes

**Comment by nordlow** [comment]
> yes

Ok, I'll fix.

**Comment by nordlow** [comment]
What to do about druntime failing?

```
src/core/thread/osthread.d(988): Deprecation: `pure` function `toThread` returns parameter `t`, annotate with `return`
src/core/thread/osthread.d(988): Deprecation: `pure` function `toThread` returns parameter `t`, annotate with `return`
```

**Comment by thewilsonator** [comment]
> Annotate druntime in another PR before we can merge this PR right?

Seems so, yes.

**Comment by nordlow** [comment]
Phobos triggers a pile of diagnostics

```
std/bigint.d(460): Deprecation: `pure` function `opOpAssign` returns parameter `this`, annotate with `return`
std/bigint.d(481): Error: template instance `std.bigint.BigInt.opOpAssign!("*", BigInt)` error instantiating
std/bigint.d(2335):        instantiated from here: `opBinary!("*", BigInt)`
std/bigint.d(460): Deprecation: `pure` function `opOpAssign` returns parameter `this`, annotate with `return`
std/bigint.d(481): Error: template instance `std.bigint.BigInt.opOpAssign!("%", BigInt)` error instantiating
std/bigint.d(2338):        instantiated from here: `opBinary!("%", BigInt)`
std/bigint.d(460): Deprecation: `pure` function `opOpAssign` returns parameter `this`, annotate with `return`
std/bigint.d(481): Error: template instance `std.bigint.BigInt.opOpAssign!("*", BigInt)` error instantiating
std/bigint.d(2335):        instantiated from here: `opBinary!("*", BigInt)`
std/bigint.d(310): Deprecation: `pure` function `opOpAssign` returns parameter `this`, annotate with `return`
std/bigint.d(350): Deprecation: `pure` function `opOpAssign` returns parameter `this`, annotate with `return`
std/bigint.d(2340): Error: template instance `std.bigint.BigInt.opOpAssign!(">>", int)` error instantiating
std/bigint.d(460): Deprecation: `pure` function `opOpAssign` returns parameter `this`, annotate with `return`
std/bigint.d(481): Error: template instance `std.bigint.BigInt.opOpAssign!("%", BigInt)` error instantiating
std/bigint.d(2338):        instantiated from here: `opBinary!("%", BigInt)`
std/bitmanip.d(1622): Deprecation: `pure` function `reverse` returns parameter `this`, annotate with `return`
std/bitmanip.d(1682): Deprecation: `pure` function `sort` returns parameter `this`, annotate with `return`
std/bigint.d(310): Deprecation: `pure` function `opOpAssign` returns parameter `this`, annotate with `return`
std/bigint.d(350): Deprecation: `pure` function `opOpAssign` returns parameter `this`, annotate with `return`
std/bigint.d(2340): Error: template instance `std.bigint.BigInt.opOpAssign!(">>", int)` error instantiating
std/bitmanip.d(1622): Deprecation: `pure` function `reverse` returns parameter `this`, annotate with `return`
std/bitmanip.d(1682): Deprecation: `pure` function `sort` returns parameter `this`, annotate with `return`
std/algorithm/searching.d(1608): Deprecation: `pure` function `trustedMemchr` returns parameter `haystack`, annotate with `return`
std/algorithm/searching.d(1608): Deprecation: `pure` function `trustedMemchr` returns parameter `haystack`, annotate with `return`
std/algorithm/searching.d(1608): Deprecation: `pure` function `trustedMemchr` returns parameter `haystack`, annotate with `return`
std/algorithm/searching.d(1608): Deprecation: `pure` function `trustedMemchr` returns parameter `haystack`, annotate with `return`
std/format/internal/write.d(610): Error: template instance `std.algorithm.searching.find!("a == b", string, const(char))` error instantiating
std/format/write.d(1239):        instantiated from here: `formatValueImpl!(void delegate(const(char)[]) pure nothrow @safe, const(real), char)`
std/complex.d(164):        instantiated from here: `formatValue!(void delegate(const(char)[]) pure nothrow @safe, const(real), char)`
std/complex.d(135):        instantiated from here: `toString!(void delegate(const(char)[]) pure nothrow @safe, char)`
std/complex.d(1231):        instantiated from here: `Complex!real`
std/format/internal/write.d(610): Error: template instance `std.algorithm.searching.find!("a == b", string, const(char))` error instantiating
std/format/write.d(1239):        instantiated from here: `formatValueImpl!(void delegate(const(char)[]) pure nothrow @safe, const(real), char)`
std/complex.d(164):        instantiated from here: `formatValue!(void delegate(const(char)[]) pure nothrow @safe, const(real), char)`
std/complex.d(135):        instantiated from here: `toString!(void delegate(const(char)[]) pure nothrow @safe, char)`
std/complex.d(1231):        instantiated from here: `Complex!real`
std/file.d(3976): Deprecation: `pure` function `name` returns parameter `this`, annotate with `return`
std/file.d(3976): Deprecation: `pure` function `name` returns parameter `this`, annotate with `return`
std/json.d(159): Deprecation: `pure` function `str` returns parameter `this`, annotate with `return`
std/json.d(159): Deprecation: `pure` function `str` returns parameter `this`, annotate with `return`
std/json.d(165): Deprecation: `pure` function `str` returns parameter `v`, annotate with `return`
std/json.d(165): Deprecation: `pure` function `str` returns parameter `v`, annotate with `return`
std/json.d(288): Deprecation: `pure` function `object` returns parameter `v`, annotate with `return`
std/json.d(288): Deprecation: `pure` function `object` returns parameter `v`, annotate with `return`
std/json.d(334): Deprecation: `pure` function `array` returns parameter `v`, annotate with `return`
std/json.d(334): Deprecation: `pure` function `array` returns parameter `v`, annotate with `return`
std/json.d(641): Deprecation: `pure` function `opIndex` returns parameter `k`, annotate with `return`
std/json.d(641): Deprecation: `pure` function `opIndex` returns parameter `k`, annotate with `return`
make: *** [posix.mak:342: generated/linux/release/64/libphobos2.a] Fel 1
```

Shall I qualify as `return` or `return scope`?

**Comment by thewilsonator** [comment]
> To alleviate, shall I qualify as return or return scope

as I understand it `return scope` is a stronger restriction/guarantee than `return`, so use `return scope` where you can and `return` where `return scope` would not be appropriate.

> For the class members I shall only use return, right? And return scope for structs members?

don't know.

**Comment by nordlow** [comment]
> > To alleviate, shall I qualify as return or return scope
> 
> as I understand it `return scope` is a stronger restriction/guarantee than `return`, so use `return scope` where you can and `return` where `return scope` would not be appropriate.
> 
> > For the class members I shall only use return, right? And return scope for structs members?
> 
> don't know.

Won't qualifying as `return scope` increase the risk of other projects using failing to use phobos?

**Comment by thewilsonator** [comment]
As I understand, `return scope` is an onus on the callee not the caller.

**Comment by nordlow** [comment]
> As I understand, `return scope` is an onus on the callee not the caller.

Indeed. So in fact qualifying members as `return scope` instead of `return` should indeed allow more code to call them.

**Comment by dkorpel** [comment]
> Indeed. So in fact qualifying members as `return scope` instead of `return` should indeed allow more code to call them.

While I can't find anything explicitly indicating it, to me it seems like `return scope` is equal to `return`. It's not like just `return` allows you to escape the reference through global variables or non-scope parameters or anything. Can anyone provide an example on how they differ?

**Comment by nordlow** [comment]
> While I can't find anything explicitly indicating it, to me it seems like `return scope` is equal to `return`. It's not like just `return` allows you to escape the reference through global variables or non-scope parameters or anything. Can anyone provide an example on how they differ?

I only this for now https://github.com/dlang/DIPs/blob/master/DIPs/other/DIP1000.md

**Comment by dkorpel** [comment]
When I first saw you suggest to use deprecations, I didn't think it was a good idea, and I agree with aG0aep6G: https://github.com/dlang/dmd/pull/12010#issuecomment-841238791 
However, it seems to do an excellent job at pin-pointing spots in Phobos that need to be updated, unlike applying the bug-fix directly which results in a lot of "this `@safe` unittest can't call function X which is now inferred `@system`  because 8 templates deep some `@safe` inference failed". So thanks for making this PR.

**Comment by nordlow** [comment]
> When I first saw you suggest to use deprecations, I didn't think it was a good idea, and I agree with aG0aep6G: [#12010 (comment)](https://github.com/dlang/dmd/pull/12010#issuecomment-841238791)
> However, it seems to do an excellent job at pin-pointing spots in Phobos that need to be updated, unlike applying the bug-fix directly which results in a lot of "this `@safe` unittest can't call function X which is now inferred `@system` because 8 templates deep some `@safe` inference failed". So thanks for making this PR.

Great. I'm currently sifting through adjusting Phobos. Most of the corrections are trivial; just attribute parameters with `return scope` or `return`. However, some cases I haven't the slightest idea what to do about. I'm gonna either qualify them as @trusted or version(none) them out and add a TODO comment for other reviewers to help me out with. This is gonna be a big one.

**Comment by nordlow** [comment]
Gonna target `master` until all things work and then change to `stable`.

**Comment by RazvanN7** [comment]
> Gonna target master until all things work and then change to stable.

That's not gonna work because your PRs from phobos targeted master, not stable.

**Comment by nordlow** [comment]
> > Gonna target master until all things work and then change to stable.
> 
> That's not gonna work because your PRs from phobos targeted master, not stable.

So I guess I should merge to dmd master first, @RazvanN7 ?

**Comment by RazvanN7** [comment]
Yes.

**Comment by nordlow** [comment]
Rebased and removed WP from title.

Let's see if third-party libraries in Circle CI trigger any deprecations. If they do but they pass is it ok to merge anyway?

**Comment by nordlow** [comment]
Seems Walter has recently updated the PR https://github.com/dlang/dmd/pull/10924 this PR is based upon. I'll notify him. That phobos is ready now.

**Comment by aG0aep6G** [comment]
> Let's see if third-party libraries in Circle CI trigger any deprecations. If they do but they pass is it ok to merge anyway?

In my opinion, this is not ok to merge at all. Just like #10924, this introduces a rejects-valid regression.

**Comment by nordlow** [comment]
Hmm, the dmd tests fail. Need to investigate.

**Comment by nordlow** [comment]
This PR introduces a regression in scope analysis in fail20108.d.

I update the test to make the diff easily highlight.

I could try to adjust the changes escape.d but that's not my territory. Could @WalterBright have a look?

**Comment by aG0aep6G** [comment]
> Ok. Anyway the druntime and phobos have all been updated to allow compilation via this dmd. Should I work on making druntime and phobos build with your #12010 aswell, @aG0aep6G ?

That would be great.

By the way, if you mention someone in an edit, they don't get an email notification. I only noticed this because I had it open in the browser. If you want to reach someone, better post a new comment.

> Moroever, does #12010 completely superceede #10924?

yes

**Comment by nordlow** [comment]
Closing because this has been superceeded by https://github.com/dlang/dmd/pull/12010.

Right, @dkorpel?

**Comment by dkorpel** [comment]
> Right, @dkorpel?

Yes

**Pull request closed without merging**
