### PR TITLE
Automatically convert MODXXX -> MOD

### PR DESCRIPTION
**Pull request by wilzbach**
```bash
replacements=(
"MODconst const_"
"MODimmutable immutable_"
"MODshared shared_"
"MODwild wild"
"MODwildconst wildconst"
"MODmutable mutable"
)
shopt -s globstar
for r in "${replacements[@]}" ; do
    w=($r)
    sed "s/${w[0]}/MODFlags.${w[1]}/g" -i **/*.d
done
```

### CODE REVIEW

**Comment by ZombineDev** [comment]
You also need to update:
https://github.com/dlang/dmd/blob/254c9634f8498c3d7eb38f37de23b14f1c509e36/src/dmd/mtype.h#L116-L125

**Comment by WalterBright** [comment]
Can we slow down on this stuff? All this refactoring means I spend many hours rebasing.

**Comment by ZombineDev** [comment]
@WalterBright On the contrary, I think we should hurry up and finish all of them and be done with this particular nuisance once and for all. As you can see here, most of the work is already done:
https://github.com/dlang/dmd/projects/4#card-6718852

If we complete this task quickly it means that most PRs will have to be rebased only once, and if we spread the work slowly over time it means that many PRs will need to be rebased multiple times.

**Comment by wilzbach** [comment]
> Can we slow down on this stuff? All this refactoring means I spend many hours rebasing

Where do you spend it? Are you referring to https://github.com/dlang/dmd/pull/6907#issuecomment-357601133? I rebased this PR within five minutes after you posting there. Please don't hesitate to ping me if you run into. I'm more than happy to help out with rebasing __any__ PR.

> I presume everyone else, too.

We actively go through the PR queue and rebase or recreate old PRs that have value. Very often, however, it's:

```
git checkout pr/XXXX
git rebase upstream/master
pr_push
```

> If we complete this task quickly it means that most PRs will have to be rebased only once, and if we spread the work slowly over time it means that many PRs will need to be rebased multiple times.

That was exactly my motivation for finishing this up.

**Review by jacob-carlborg — APPROVED** [review]

**Review by JinShil — APPROVED** [review]

**Comment by WalterBright** [comment]
> Where do you spend it?

There were a number of changes, such as code moving from one file to another, layered in with a few other commits that changed things in the changed sections, meaning the rebase needed a lot of manual work. They all failed the autotester, meaning I needed to track down if it was a rebase mistake or something else, all of which takes time as the autotester has a largish turnaround time.

**Comment by wilzbach** [comment]
> meaning the rebase needed a lot of manual work. They all failed the autotester, meaning I needed to track down if it was a rebase mistake or something else

FYI: dlang-bot marks PRs needing a rebase with "needs rebase". Whenever I have time, I browse the first page and see to it that everything is nicely green and rebased. Now that Travis has been replaced by SemaphoreCI we should start seeing green a lot more frequent.

I don't actively look at the older PRs as they can be rebased once they are actively approved, but _please_ let me know if you have old PRs that need rebasing. My rebasing pipeline is pretty optimized ;-)

Also I'm pretty sure that I'm not the only one who would gladly help you with rebasing if that means less vetos on refactorings in the frontend.

> If we complete this task quickly it means that most PRs will have to be rebased only once, and if we spread the work slowly over time it means that many PRs will need to be rebased multiple times.

Yes I'm done with this enum conversion series. Anything else that we should do in this refactoring phase?

**Comment by jacob-carlborg** [comment]
> Anything else that we should do in this refactoring phase?

There's a whole bunch of symbols that I would like to rename for clarity and following the D style guide. But that might be a different phase.

**Comment by jacob-carlborg** [comment]
> They all failed the autotester, meaning I needed to track down if it was a rebase mistake or something else, all of which takes time as the autotester has a largish turnaround time.

@WalterBright I do hope that you do some form of testing before pushing the code to let the autotester run.

**Pull request merged**
