### PR TITLE
[RFC] Allow test output in a separate file

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
This allows tests to specify a file in `TEST_OUTPUT_FILE` which contains the expected output. It's content will be treated identical to a `TEST_OUTPUT` section.

This avoids unecessary bash scripts.

Inspired by #10808

### CODE REVIEW

**Comment by thewilsonator** [comment]
> This avoids unecessary bash scripts.

Hallelujah! I can't wait to see a large red diff.

**Comment by MoonlightSentinel** [comment]
> > This avoids unecessary bash scripts.
> 
> Hallelujah! I can't wait to see a large red diff.

Me too. Combined with #10808 a lot of `grep -v` + `diff` scripts could be removed

**Review by wilzbach — APPROVED** [review]
Nice!

**Comment by MoonlightSentinel** [comment]
Maybe we should also extend the output for failed tests with a diff as manually comparing large files will be rather annoying.

**Comment by wilzbach** [comment]
Yes this would be a nice follow-up, but I would keep this PR as is because we can already merge it (:

**Comment by MoonlightSentinel** [comment]
Agreed, that belongs in another PR

**Review by RazvanN7 — APPROVED** [review]

**Review by RazvanN7 — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
Already merged in #10815 (by accident)

**Pull request closed without merging**
