### PR TITLE
Fix Bugzilla 24872 - Assigning non-copyable value to array has no effect

### PR DESCRIPTION
**Pull request by pbackus**
Credit to @jacob-carlborg for pointing this out on Discord.

### CODE REVIEW

**Comment by schveiguy** [comment]
Please target stable instead. This is a bug fix.

**Comment by pbackus** [comment]
Rebased and targeted to stable.

**Comment by thewilsonator** [comment]
```
std/array.d(307): Error: scope variable `r` may not be returned
```
???

**Comment by pbackus** [comment]
I was able to reproduce this failure locally using Phobos `master` and DMD `stable`, without this PR included. So I guess it's a DIP1000 bug in DMD `stable` that's fixed in `master`.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
If you could find what that is and cherry pick it that would be great.

**Comment by pbackus** [comment]
Bug was fixed by #16724

**Comment by pbackus** [comment]
Cherry-picking results in merge conflicts that I don't know the code well enough to resolve. Maybe @dkorpel can help?

**Comment by dkorpel** [comment]
The bug fix relies on refactoring (especially https://github.com/dlang/dmd/pull/16715) that's currently only in master, so either that refactoring has to be ported to stable as well, or the bug fix should be adapted to be work in the code before refactoring. Or perhaps master can simply be merged into stable since 2.109.1 has been released, or was there a cutoff for 2.110 already? Not sure with the current release situation.

**Pull request merged**
