### PR TITLE
fix Issue 14279 - [REG:git-head]Failed to make dmd because of idgen : HO...

### PR DESCRIPTION
**Pull request by WalterBright**
...ST_DC missing

https://issues.dlang.org/show_bug.cgi?id=14279

### CODE REVIEW

**Comment by yebblies** [comment]
Unfortunately this can't work, because a definition in the makefile will override a definition in the environment.  Digital mars make doesn't recognize the `?=` operator.

**Comment by yebblies** [comment]
Also, HOST_DC=dmd will pick up the dmd that just got built, which is not usually what you want.

**Comment by WalterBright** [comment]
Apparently the autotester is relying on environment variables.

**Comment by yebblies** [comment]
Yep.

**Comment by WalterBright** [comment]
Redid to make it a comment.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
> Unfortunately this can't work, because a definition in the makefile will override a definition in the environment.

Why does it have to be in the environment, and not a `make` parameter?

**Comment by WalterBright** [comment]
I run it using a make parameter rather than an environment variable, so it does work.

**Comment by yebblies** [comment]
> Why does it have to be in the environment, and not a make parameter?

A make parameter will work, but I think we need to support setting it via an environment variable.

**Comment by CyberShadow** [comment]
This isn't very different from the existing settings. People who need to override the setting can use their own build script which invokes the makefile.

I think it's more valuable to not force people to create a HOST_DC variable, and thus provide a sensible default out of the box, than allowing configuring HOST_DC through the environment in win32.mak.

**Comment by yebblies** [comment]
I was initially aiming for that, but Brad set up the autotester to pass it via the environment.
As for a sensible default, `HOST_DC=dmd` will pick up the system dmd on the first build, then pick up the just-built dmd after that.  I'm not sure what default doesn't have this problem.

**Pull request merged**
