### PR TITLE
Move driver and codegen fields from Param to DMDparam

### PR DESCRIPTION
**Pull request by ibuclaw**
None of these are used by the common front-end modules that GDC and LDC share.

### CODE REVIEW

**Comment by kinke** [comment]
I think LDC uses a bunch of these, though it doesn't necessarily have to - dll, lib, link, oneobj, symdebug.

**Comment by kinke** [comment]
Ah, I guess I'll just introduce a `struct LDCparams` or so with LDC's subset. Naming the global `driverParams` instead of `dmdParams` would be better in that case, so that I can simply replace the type.

**Comment by ibuclaw** [comment]
> Ah, I guess I'll just introduce a `struct LDCparams` or so with LDC's subset. Naming the global `driverParams` instead of `dmdParams` would be better in that case, so that I can simply replace the type.

Yeah, that's somewhat the point. For example gdc-specific options are internal to gdc itself. https://github.com/gcc-mirror/gcc/blob/1375e2b62332351a8f9c928421cd1ea8b53c5127/gcc/d/d-lang.cc#L66-L67

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@ibuclaw I rebased and modified this PR so that there is no occurence of dmdParams, but driverParams. Is there anything that needs to be added here?

**Pull request merged**
