### PR TITLE
remove some unsafe casts

### PR DESCRIPTION
**Pull request by WalterBright**
makes the code easier to understand, too

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by ibuclaw — APPROVED** [review]

**Comment by thewilsonator** [comment]
Buildkite:dlang-bot `/usr/bin/ld: error: cannot find -lsqlite3` ????

**Comment by Geod24** [comment]
@RazvanN7 : Looks like you broke Buildkite ;)

**Comment by RazvanN7** [comment]
@Geod24 https://github.com/dlang/ci/pull/445

**Comment by RazvanN7** [comment]
> @RazvanN7 : Looks like you broke Buildkite ;)

Maybe dlang bot should add a stripped version of the buildkite script just to make sure we don't break anything in the future

**Pull request merged**
