### PR TITLE
fix issue 19002 - __FUNCTION__ and __PRETTY_FUNCTION__ cannot be used  as C string literals

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Hmm, dlang-bot has failed to link to the issue.

**Comment by Basile-z** [comment]
I can close it manually if required..

**Comment by jacob-carlborg** [comment]
BTW, I think bug fixes should go into stable instead of master.

**Comment by jacob-carlborg** [comment]
Now you pushed too much.

**Comment by Basile-z** [comment]
It was expected as just changed the base online, i'm fixing this locally...

**Comment by Basile-z** [comment]
Alright, we're good now.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
