### PR TITLE
Fix typo in dmd.expression apparently causing sporadic frontend crashes

### PR DESCRIPTION
**Pull request by kinke**
Seems to fix sporadic segfaults reported in https://issues.dlang.org/show_bug.cgi?id=18864.

### CODE REVIEW

**Review by dnadlinger — APPROVED** [review]

**Comment by kinke** [comment]
That was quick, thanks; I should have targeted stable though. :/ Pinging @MartinNowak.

**Comment by wilzbach** [comment]
Ah we typically only do cherry-picking if it's important, so if you feel like this really should be part of 2.080.1, simply cherry-pick and open a new PR.
OTOH the next release will be in one month.

**Comment by kinke** [comment]
@wilzbach: So a fix for random DMD segfaults isn't important enough to be cherry-picked by one of you guys? What is then? ;)

**Comment by wilzbach** [comment]
Ehm I'm currently traveling and without laptop, otherwise I would have opened the cherry-pick for you.
Well, Martin always complains about this because these cherry-picks can result in ugly merge conflicts, so yep we often don't bother except for really important things :/

**Pull request merged**
