### PR TITLE
add interpretRegion() and try it out

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
I'm at my wits end with this at the moment. It's a classic memory corruption problem - change anything, and the problem shifts. Maybe if I let it be for a while, I'll figure it out.

**Comment by rainers** [comment]
Looking at the latest Windows failures, most (but not all) seem to happen with the -lowmem switch, i.e. when using the GC. stdlib.malloc should not be used in that case,

I think the region allocator could be disabled if the GC is enabled as releasing unused data comes for free without extra copying.

**Comment by WalterBright** [comment]
@rainers I think your reasoning is solid.

**Comment by rainers** [comment]
If I compile d_do_test with this (without `-lowmem` that the CIs use), dmd allocates more than 3 GB and freezes (mostly iterating in `Region.contains()`). It seems it is very slowly copying large arrays from std.regex or std.uni. Master uses a bit more than 2 GB.

Maybe this is still a corruption, but I think the region chunks are way too small. This causes slow linear searches in `contains`. If they are made larger, allocation and freeing take much longer, so I'd suggest not returning them to the system, but reusing them for the next CTFE evaluation.

**Review by rainers — CHANGES_REQUESTED** [review]
Even though tests pass on the auto tester, they seem to take considerably longer. An extreme example is FreeBSD: about 30 minutes instead of 13 minutes for other PRs, see https://auto-tester.puremagic.com/hosts/details.ghtml?hostid=43

**Comment by WalterBright** [comment]
I agree the chunks are too small, and `contains()` is a linear search, also not good. I wanted to get it to work first before making it more efficient.

**Comment by WalterBright** [comment]
> If they are made larger, allocation and freeing take much longer, so I'd suggest not returning them to the system, but reusing them for the next CTFE evaluation.

@rainers done

**Comment by WalterBright** [comment]
The buildkite issues seem to be running out of memory.

**Comment by rainers** [comment]
> @rainers done

Thanks, but the chunk size is still way too small. I tried 4 MB instead, and with that compilation time for d_do_test is good (12 seconds instead of 17 seconds for master), but memory usage is still high (3.4 GB instead of 2 GB). 2 GB of that was allocated from the region. master with -lowmem uses 580 MB and takes about 16 seconds. (All tests with a debug win64 build).

**Comment by WalterBright** [comment]
What do you suggest? I could adopt the 4 MB chunk size, and free chunks when usage gets above, say, half a gig?

`-lowmem` is always going to use less memory. The performance numbers you're showing is a solid win.

**Comment by rainers** [comment]
> What do you suggest? I could adopt the 4 MB chunk size, and free chunks when usage gets above, say, half a gig?

I don't think that would work as the 2 GB of memory is used by just one stack of allocated expressions and its hard to say what can be released. Maybe you could release data before `g.count` goes down to zero by remembering the "starting position" in the region allocator.

I'm wondering why the difference is that big between this PR and master. There are some extra copies here, but the allocated region memory is already as large as all the memory used by master. Does master release the memory allocated during CTFE to some extend?

**Comment by rainers** [comment]
> I'm wondering why the difference is that big between this PR and master.

This happens because `interpretRegion` is allocating from the region prematurely (and UnionExp is 2-3 times larger than the usual Expression). I get better results with:
```
Expression interpretRegion(Expression e, InterState* istate, CtfeGoal goal = ctfeNeedRvalue)
{
    UnionExp ue = void;
    auto result = interpret(&ue, e, istate, goal);
    auto uexp = ue.exp();
    if (result != uexp)
        return result;
    if (mem.isGCEnabled)
        return ue.copy();

    // mimicking UnionExp.copy, but with region allocation
    switch (uexp.op)
    {
        case TOK.cantExpression: return CTFEExp.cantexp;
        case TOK.voidExpression: return CTFEExp.voidexp;
        case TOK.break_:         return CTFEExp.breakexp;
        case TOK.continue_:      return CTFEExp.continueexp;
        case TOK.goto_:          return CTFEExp.gotoexp;
        default:                 break;
    }
    auto p = ctfeGlobals.region.malloc(uexp.size);
    return cast(Expression)memcpy(p, cast(void*)uexp, uexp.size);
}
```
Compiling d_do_test with chunksize 4 MB uses 1.8 GB (360 MB region memory) and takes about 11.5 seconds.

**Comment by WalterBright** [comment]
@rainers updated with your version of `interpretRegion()`.

**Comment by rainers** [comment]
> @rainers updated with your version of `interpretRegion()`.

Thanks. What I don't like about that code is the duplication of the internals of UnionExp.copy and Expression.copy. Should this be avoided, e.g. by passing an allocator function as a template argument?

**Comment by WalterBright** [comment]
The common code is the switch, not the rest of it. That could be encapsulated in a `dontCopy()` function or something like that.

**Comment by rainers** [comment]
> The common code is the switch, not the rest of it. That could be encapsulated in a `dontCopy()` function or something like that.

Ok, let's leave that for another PR.

**Review by rainers — APPROVED** [review]

**Pull request merged**
