### PR TITLE
Integrate ASTBase visitor with the compiler visitor

### PR DESCRIPTION
**Pull request by RazvanN7**
In order to create a transitive visitor for the compiler like the one in the parser library, the existing visitor had to be tweaked a bit.

### CODE REVIEW

**Comment by RazvanN7** [comment]
Does anyone know why the autotester is failing while circleci compiles successfully? Compiling on my machine works perfectly.

**Review by andralex — APPROVED** [review]

**Comment by stefan-koch-sociomantic** [comment]
why did `asttypename.d` get from the build ?
It is a pretty important debugging utility!

**Comment by jacob-carlborg** [comment]
@stefan-koch-sociomantic it was because it caused the auto-tester to fail [1]. It think because it's running an older version of DMD. It also needs to be compatible with GDC.

[1] https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2929293&isPull=true

**Comment by ibuclaw** [comment]
Speaking of compatibility with GDC.  Did no one here think that renaming `class Visitor` would break the C++ API?

You've got to stop doing this.

**Comment by andralex** [comment]
@ibuclaw sorry! The best way to ensure that doesn't happen anymore is to have some unittests to that effect. @RazvanN7 can you please investigate using inheritance of class Visitor instead of aliasing? Thx!

**Comment by stefan-koch-sociomantic** [comment]
The reason asttypename.d caused the build to fail is because of the change in visibility rules; and this indicates problems for everyone wanting to use the generic visitor. When the visibility/import rules get stricter again.

**Comment by ibuclaw** [comment]
@andralex - Perhaps a test (written in C++) that links to and uses the front-end would suffice?

Covering all cases (virtual functions, fields accessors) would be no small thing, particularly if you are "mocking" a compiler.

**Comment by jacob-carlborg** [comment]
@andralex @RazvanN7 what about a tool that generates a C/C++ header file from a D module? If possible, built on the Dub package.

**Comment by ibuclaw** [comment]
Generating the headers is only half the problem.  Notifying downstream of changes is just as important.

**Comment by andralex** [comment]
>Perhaps a test (written in C++) that links to and uses the front-end would suffice?

Good idea, @RazvanN7 what do you think?

**Comment by RazvanN7** [comment]
@ibuclaw 

>You've got to stop doing this.

It's not a simple class rename, but rather a design modification.

>Notifying downstream of changes is just as important.
  
How do you suggest the downtstream notification should be done?

>Good idea, @RazvanN7 what do you think?

@andralex I think that creating such a test requires a big effort for a small gain: in order to be sure that the test is relevant you would have to access all the fields and methods of the compiler. On the other hand, it would be much simpler to create a tool that automatically creates the C++ header. For 90% of the cases the implementation is trivial. Once we have the header generation tool, the integration should not pose any more problems.

Now, specifically for this PR, I suggest we modify the visitor.h file to reflect the changes as I think that the current design of the visitors is suited for the future compiler library. What this PR does is to move the visiting methods for AST nodes that are generated at parse time into a templated visitor (ParseTimeVisitor) and have a generic visitor inherit the ParseTimeVisitor and implement the visiting methods for AST nodes generated at semantic time. The `alias Visitor = GenericVisitor!ASTCodegen` is used in order to not modify the accept methods of all AST nodes.  Now I am no expert in D-C++ linking,
but since the name Visitor aliases a visitor which is instantiated with the code generation AST family shouldn't the Visitor class defined in visitor.h be the same as the aliased one once the ParseTimeVisitor is appropriately added in the header file?

**Comment by wilzbach** [comment]
> On the other hand, it would be much simpler to create a tool that automatically creates the C++ header. For 90% of the cases the implementation is trivial. Once we have the header generation tool, the integration should not pose any more problems.

Yes, I agree - creating the header generation tool is a good way to move forward. This will also be useful for other projects who would like to have a tight C++ integration ;-) 

> Notifying downstream of changes is just as important.

@RazvanN7: for a start, you could either add a changelog entry for bigger changes or CC important people like @ibuclaw 

> @andralex @RazvanN7 what about a tool that generates a C/C++ header file from a D module? If possible, built on the Dub package.

This should help: https://github.com/dlang/dmd/pull/7425

**Comment by ibuclaw** [comment]
> It's not a simple class rename, but rather a design modification.

And where is the C++ interface for it?  As a user of the `Visitor` class for _all_ code generation passes, has this been tested that it doesn't break existing downstream code?

**Comment by RazvanN7** [comment]
Attempted fix : https://github.com/dlang/dmd/pull/7438

**Pull request merged**
