### PR TITLE
dtoh: Support implementing interfaces

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Emit implemented interfaces as public base classes

### CODE REVIEW

**Comment by thewilsonator** [comment]
I like it. Please add a changelog entry.

**Comment by wilzbach** [comment]
> I like it. Please add a changelog entry.

We don't need to over document an currently unusable tool. A bugzilla reference would be nice or _one_ entry about all improvements of dtoh in the upcoming release.

**Comment by thewilsonator** [comment]
Fair enough.

**Comment by MoonlightSentinel** [comment]
See #11815

**Pull request merged**
