### PR TITLE
ddmd -> dmd transition

### PR DESCRIPTION
**Pull request by wilzbach**
Let's see what the missing bits on Windows are.
CC @RazvanN7 

Required steps

- [x] https://github.com/dlang/dmd/pull/6562
- [x] https://github.com/CyberShadow/ae/commit/13bc434ea12c90883f524818510f35970230becb
- [x] https://github.com/dlang/dmd/pull/6585
- [x] https://github.com/dlang/dmd/pull/6586
- [x] https://github.com/dlang/dmd/pull/6593
- [x] https://github.com/dlang/dmd/pull/6620
- [x] https://github.com/dlang/ci/pull/68
- [x] https://github.com/dlang/dlang.org/pull/1903
- [x] https://github.com/braddr/at-client/pull/4
- [x] https://github.com/dlang/druntime/pull/1978
- [x] https://github.com/dlang/phobos/pull/5892
- [x] https://github.com/braddr/at-client/pull/5
- [x] https://github.com/dlang/druntime/pull/1979
- [x] https://github.com/dlang/phobos/pull/5895
- [x] https://github.com/dlang/dlang.org/pull/1971

### CODE REVIEW

**Comment by JinShil** [comment]
If this is to investigate better naming for the compiler-as-a-library API, would it be better to just use the name `d` in an effort to make it compiler-agnostic?

**Comment by wilzbach** [comment]
> If this is to investigate better naming for the compiler-as-a-library API, would it be better to just use the name d in an effort to make it compiler-agnostic?

Yes and no. tl;dr: it's picking up an effort to clean up the folder hierarchy started by @RazvanN7 and @andralex half a year ago (`ddmd` comes back from the old days when it meant "D version of dmd").
See also:

https://github.com/dlang/dmd/pull/6489
https://github.com/dlang/dmd/pull/6562
https://github.com/dlang/dmd/pull/6595

**Comment by JinShil** [comment]
>  (`ddmd` comes back from the old days when it meant "D version of dmd").

Yes, I'm aware of that, but I was questioning the use of `dmd` as a package name as it is specific to only one brand of D compiler.  My suggestion was to use the `d` instead.

**Comment by wilzbach** [comment]
> Yes, I'm aware of that, but I was questioning the use of dmd as a package name as it is specific to only one brand of D compiler. My suggestion was to use the name d instead.

While I appreciate your input, there have been many lengthy discussions about this and a decision has been made to rename to "dmd":

https://github.com/dlang/dmd/pull/6489#issuecomment-279156384
https://github.com/dlang/dmd/pull/6489#issuecomment-281701024
https://github.com/dlang/dmd/pull/6489#issuecomment-281990386

Unfortunately the rename was left in stage 2 and I am just trying to take it to the finish line, which sadly is though enough. Also, there are (and hopefully will be) other D compilers which aren't based on the DMD frontend (e.g. SDC), so taking the `d` namespace would be quite unfriendly (especially if lazy people used `d` to organize their private packages).

@CyberShadow regarding:

```
.generated/stable_dmd-2.072.2/dmd2/linux/bin64/rdmd --compiler=.generated/stable_dmd-2.072.2/dmd2/linux/bin64/dmd -conf=.generated/stable_dmd-2.072.2/dmd2/linux/bin64/dmd.conf modlist.d ../druntime ../phobos ../dmd --ex=gc. --ex=rt. --ex=core.internal. --ex=core.stdc.config --ex=core.sys. --ex=std.algorithm.internal --ex=std.c. --ex=std.concurrencybase --ex=std.internal. --ex=std.regex.internal. --ex=std.windows.iunknown --ex=std.windows.registry --ex=etc.linux.memoryerror --ex=std.experimental.ndslice.internal --ex=std.stdiobase --ex=std.typetuple --ex=tk. --ex=msvc_dmc --ex=msvc_lib --ex=ddmd.libmach --ex=ddmd.libmscoff --ex=ddmd.objc_glue --ex=ddmd.scanmach --ex=ddmd.scanmscoff \
	--dump object --dump std --dump etc --dump core --dump ddmd >.generated/modlist-prerelease.ddoc
core.exception.AssertError@modlist.d(75): ddmd can't be found.
----------------
```

(this is about the menu generation for the dlang.org (Ddoc version))
Q: Would you be okay with making this error soft-failing for the time being?

**Comment by CyberShadow** [comment]
> Q: Would you be okay with making this error soft-failing for the time being?

You're asking the wrong person, DMD docs on dlang.org are mostly pushed by W/A. But I suggest finding a way to do things that doesn't imply that "just break it for now, we'll fix it later", as "later" may be postponed more than expected.

Why not detect the name of the DMD package/directory?

**Comment by ibuclaw** [comment]
I'd still prefer some agnostic name as per comment I made many months ago in linked pr above.

**Comment by andralex** [comment]
>I'd still prefer some agnostic name as per comment I made many months ago in linked pr above.

It's a nice point but gets us into rebranding the front end. I'd say we move forward with this obvious step and defer that.

**Comment by andralex** [comment]
Let's do this already. @MartinNowak ? @WalterBright ?

**Review by MartinNowak — APPROVED** [review]
Anytime

**Comment by ibuclaw** [comment]
Just fix the build.

**Comment by wilzbach** [comment]
Seems like we need to update the auto-tester again: https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=2816476&dataid=19934733&isPull=true  :/

-> https://github.com/braddr/at-client/pull/4

At least CircleCi and Jenkins have been green.

**Comment by andralex** [comment]
rebase?

**Review by andralex — APPROVED** [review]

**Comment by andralex** [comment]
Let's boldly go see regressions we haven't seen before :).

**Comment by wilzbach** [comment]
> rebase?

I really appreciate the enthusiasm, but we have to wait at least for https://github.com/dlang/dlang.org/pull/1903 and https://github.com/braddr/at-client/pull/4.
This turns out to be much more pain than initially thought :/

**Comment by andralex** [comment]
Let's hope gain will follow the pain. Thanks for the hard work! (Also please hop on slack.)

**Comment by andralex** [comment]
ping @braddr - this is waiting for you please pull https://github.com/braddr/at-client/pull/5 thx!

**Comment by wilzbach** [comment]
>> ping @braddr - this is waiting for you please pull braddr/at-client#5 thx!
> I've updated a couple machines with these changes. Assuming they survive without problems I'll finish deploying to the fleet tomorrow or thursday.

Thanks a lot for pulling this @braddr :tada: :birthday: 

@ other: FYI I just rebased this PR and it's looking good so far. There were some changes on dlang.org, so we have to update this again (-> https://github.com/dlang/dlang.org/pull/1971), but apart from that, this PR is ready and waiting for the other auto-tester machines to be updated :)

**Comment by wilzbach** [comment]
Alrighty - this is passing on all auto-tester machines now:

image

According to @braddr 

> Changes are deployed to most machines. The ones left I can't access remotely, so will be at least another day before they're updated.

This means in a __very foreseeable__ future we can finally move on with this.
Any last-minute or final thoughts?

> This branch has conflicts that must be resolved

Don't get confused by this. The current stream of merged PRs into dmd is just too high to be able to constantly rebase this. Note that every merge PR will arise a conflict and as soon as we merge this here, _all_ open PRs will have to be rebased once. This is fairly trivial though as git can handle renames quite well.

**Comment by andralex** [comment]
Can't wait!!

**Comment by wilzbach** [comment]
> Can't wait!!

image

It looks really good. There are just a few hosts which haven't run these changes yet:

- bellevue.puremagic.com (sets `DMD` for Druntime properly to `/home/braddr/sandbox/at-client/master-132655-FreeBSD_32/dmd/generated/freebsd/release/32/dmd`)
- mac-vm-1.local (Last Heard From: 2017-12-13)
- work-vm-1 (Last Heard From: 2017-12-13)

And there seem to be two other other hosts in the list which are solely used to the new FreeBSD OS changes:

- ip-172-31-43-66 (idle, FreeBSD project)
- ip-172-31-46-60 (idle, FreeBSD project)

But let's better wait for @braddr to give his okay.

**Comment by wilzbach** [comment]
>> But let's better wait for @braddr to give his okay.
> All the machines are updated now.

Wohoo :tada: :balloon: :birthday: 

Awesome. Thank you so much!
Everyone ready?

**Review by JinShil — APPROVED** [review]

**Comment by wilzbach** [comment]
I just saw [@klickverbot's comment from January this year](https://github.com/dlang/dmd/pull/6489#issuecomment-275444197):

> The actual file-level reorganisation is something all of us can do given 20 minutes and a sed implementation of choice (well, okay, maybe an extra 10 to fix up the Windows makefiles).

...

**Comment by andralex** [comment]
So should I force merge this?

**Comment by wilzbach** [comment]
> So should I force merge this?

Yes, please. Jenkins is failing due to it running out of space (CC @MartinNowak) and Travis seems to have hit a `runnable/test17868b` which appears to be a spurious failure (after all, it passed a couple of hours ago).

**Comment by andralex** [comment]
alrighty then

**Comment by andralex** [comment]
no mercy

**Comment by RazvanN7** [comment]
Awesome. Thanks!

**Comment by MartinNowak** [comment]
Nice, a bit unfriendly to merge this just on the beta branch day.
https://forum.dlang.org/post/oknjtm$1unb$1@digitalmars.com

**Comment by andralex** [comment]
@MartinNowak sorry, lmk how I can help make things better

**Comment by wilzbach** [comment]
Same here! Did you ran into any issues already?
Sorry Martin. I lost totally track of the branching day.

**Pull request merged**
