### PR TITLE
refactor: replace dt_t* with DtBuilder (part 2)

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by yebblies** [comment]
This one is a bit messy...

**Comment by WalterBright** [comment]
Like a surgery, it'll get messier before it gets better. Doing it all at once is too much to review in one chunk.

**Comment by yebblies** [comment]
Absolutely.  But why can't you finish the refactoring in a branch, before making PRs.  This is how I (and others) have done large refactorings in the past, and it works really well.  Doing it this way makes it really hard to see the net effect.

**Comment by WalterBright** [comment]
I don't see how it is difficult to see the net effect with these. They're all pretty much independent, that's why the four each pass the autotester.

And when I make a mistake in one, as I did, being small PRs makes isolating the bug down enormously easier.

All four are ready to automerge.

**Comment by yebblies** [comment]
As you said,

> Like a surgery, it'll get messier before it gets better.

Which I'm interpreting as meaning the net effect will be good, despite the incremental changes not necessarily making things nicer.

> And when I make a mistake in one, as I did, being small PRs makes isolating the bug down enormously easier.

You can do exactly the same thing with one PR, mark it as a work in progress and only push new commits to it as it passes the tests.  (Or just check every now and then).  It works just as well.

The benefit of this is that as you progress through the code the design tends to change (I'm assuming those private members will become private again at some point).  There is no reason for the intermediate designs to end up in master.

This is how everyone else is doing it:
1. Complete the design in a branch (And use the auto-tester to test that branch)
2. Split the finished work into multiple PRs to make review easier.

This is how I did DDMD and I strongly believe it's how all large work should be done.

**Comment by WalterBright** [comment]
> It works just as well.

And it's impossible to properly review.

> This is how I did DDMD

Pulling that was a leap of faith, as it was too big to review.

**Comment by WalterBright** [comment]
I rag on Kenji to submit things in smaller, more digestible chunks, and you rag on me to produce giant blobs. Sigh.

It's just a fact that incremental changes get reviewed more thoroughly and pulled faster than thousand+ line changes.

**Comment by WalterBright** [comment]
Also, when the large PRs produce a regression, they are a giant pain to debug. With smaller, self-contained one, it's a lot easier to pinpoint where they went wrong. Note that each of these PRs is self-contained and independent, they don't build on each other.

**Comment by yebblies** [comment]
> Pulling that was a leap of faith, as it was too big to review.

Don't you remember the 100s of small PRs that were merged before the switch?  Those came from the WIP branch.  I'm not talking about the final switch PR.

I feel like I'm not getting through here.  I still want you to make lots of small PRs - I just want you to finish the complete change first.

**Comment by WalterBright** [comment]
I don't care to change thousands of lines of code and then have people argue about changing the design. Anyhow, the design is done. It's trivial. These PRs are just voluminous because there is a lot of code to change to switch over to the new design.

**Comment by mathias-lang-sociomantic** [comment]
I fully agree with @yebblies here: It is way easier to start with a finished work which can be tested and reviewed as a whole, and then split it down, than the other way around.

When reviewing, the first thing you want to comment on is the design, then the implementation, then the style, because it affects a decreasing amount of code, hence it provides a decreasing amount of work to do for the contributor and the reviewer.
With large amount of small P.R. like this one, the design is not obvious. It's showing pieces of a puzzle to someone and ask him/her to figure out what the image is.

**Comment by WalterBright** [comment]
> With large amount of small P.R. like this one, the design is not obvious.

The design is obvious - https://github.com/D-Programming-Language/dmd/pull/5587 - which contains the design and usage. These PRs are converting the existing code to use the new design.

**Comment by yebblies** [comment]
If the design was done you wouldn't be making changes to `DtBuilder` in this PR.  It's clearly still changing, and not possible to tell from this PR alone where it will end up.

> And if I get resistance to the change, I'm not throwing away a lot of work, like I would have for #5498 which I was going to do pervasively.

I'll make it easy then.  I'm in agreement with the goal of these changes and want to review and merge them.

The issue is that while small PRs are great for implementation review, they suck for design review.  The design has already changed between PRs, and chances are it will change again.  How can I review a design that isn't finished?

As an active example, see #4569 
1. It was first done as a refactoring of a single visitor, to get review of the goal
2. I then did the rest of the similar refactorings.  Now that it's complete, it can be reviewed for the final design - including net effect on performance and maintainability.
3. Once that's done (if successful) it can be split up (trivially, thanks to git) into smaller independent PRs that can be reviewed for their implementation.

If the goal is beyond question then step 1 is unnecessary.  If the final effect is obvious or unimportant then step 2 is less important.  If implementation review is trivial then step 3 is unnecessary.

You've asked for all of these things from others at one point or another.

I am NOT saying that reviewing the implementation is easier in a giant PR.  I am saying that the final design is unclear from these small PRs and appears to be incomplete.  This makes design review impossible.

> Heck, 3 of these PRs are because there was a mistake in one that I couldn't see in the 1 they used to be in. Splitting it into 3 made it easy to spot the typo. Nobody else spotted the typo, either. Unhelpful also was the mysterious hang in the autotester it caused.

This is why step 3 is useful.  It doesn't remove the value of step 2.

**Comment by WalterBright** [comment]
> If the design was done you wouldn't be making changes to DtBuilder in this PR.

That is necessary only in order to do partial uses of it. Using DtBuilder is viral like `const` is - recall our discussions about casting away `const` when working towards making dmd const-correct.

> How can I review a design that isn't finished?

Nothing is finished in programming. I work on dmd every day. I constantly tear down parts of it and rebuild them. You're setting an impossible bar. A useful, practical standard is "is this progress in the direction we want to go".

In this case, the issue is `dt_t` is a linked list that leaks its implementation all over the place, making it impractical to improve it. It's pervasive technical debt dating back to 1983 or so, and it's not going away in one PR.

(I'm also nearly done switching to it in DMC++.)

**Comment by andralex** [comment]
No reason to keep on bantering about this. Let's move things forward - Walter please switch back to private in the next chunk. Thx.

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
