### PR TITLE
fix Issue 17130 - ambiguous implicit super call

### PR DESCRIPTION
**Pull request by MartinNowak**
- need type of this to resolve base class ctor overloads

### CODE REVIEW

**Comment by ZombineDev** [comment]
Thanks for fixing this so fast!

Strangely vibe.d fails with:

> source/vibe/core/core.d(1183,18): Error: function vibe.core.core.CoreTask.state cannot override final function core.thread.Fiber.state

Which is quite strange, because `Fiber.state` has been marked as `final` for quite some time:
https://github.com/dlang/druntime/blob/druntime-2.052/src/core/thread.d#L3226

I have no idea how vibe.d managed to override it. Sound like another compiler bug.

**Comment by MartinNowak** [comment]
See [Issue 17131 – [Reg 2.074] Fiber.state collides with differently attributed function in derived class](https://issues.dlang.org/show_bug.cgi?id=17131) for the other issue.

**Comment by ZombineDev** [comment]
@MartinNowak I guess you need to force push your branch to re-trigger the project tester since @s-ludwig worked around that bug in vibe.d (https://github.com/rejectedsoftware/vibe.d/commit/74883bcf4cd34774d38ad10d5fccf5e08b9d45cc).

**Comment by MartinNowak** [comment]
Can we please just merge this, it obviously fixes the super overload issue. The functions should have never been overload/rideable which asks for a separate dmd fix.
https://issues.dlang.org/show_bug.cgi?id=17131

**Review by PetarKirov — APPROVED** [review]

**Comment by UplinkCoder** [comment]
@MartinNowak go ahead an merge it yourself.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
