### PR TITLE
Fix Bugzilla 24436: array-of-array-of-NOSCAN falsely marked as NOSCAN.

### PR DESCRIPTION
**Pull request by FeepingCreature**

### CODE REVIEW

**Comment by adamdruppe** [comment]
nice, ez fix with that repro. should have guessed it was scan related!

**Review by thewilsonator — APPROVED** [review]
Rebase onto `stable` though?

**Comment by FeepingCreature** [comment]
Hang on.

I think `setArrayAllocLength` also needs void[]?

**Comment by FeepingCreature** [comment]
Yeah, so done. I don't understand why that function isn't called from `__arrayAlloc` already but it definitely needs the same type.

**Comment by tim-dlang** [comment]
The is a similar problem with three dimensional arrays, where only two dimensions are initialized: https://issues.dlang.org/show_bug.cgi?id=24498

**Pull request merged**
