### PR TITLE
[dmd-cxx] Remove/convert all D sources to C++

### PR DESCRIPTION
**Pull request by ibuclaw**
This mirrors current gdc development, and removes all dependencies  on a dmd bootstrap.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Added CI scripts, lets see if everyone is happy...

**Review by wilzbach — APPROVED** [review]
Travis being green looks great!

**Comment by wilzbach** [comment]
Let's have a look on how we can disable DAutoTest in another PR - or maybe @CyberShadow can directly hard-code it?

**Comment by CyberShadow** [comment]
Disabled

**Comment by ibuclaw** [comment]
@CyberShadow thanks.

**Pull request merged**
