### PR TITLE
druntime: replaces top level version(..) branching by tags

### PR DESCRIPTION
**Pull request by denizzzka**
Squashed version of https://github.com/dlang/dmd/pull/15822

Forum: https://forum.dlang.org/post/ppnylqbaadkqwmulgoam@forum.dlang.org

### CODE REVIEW

**Comment by denizzzka** [comment]
There seems to be something wrong with env variables on Windows host?

**Comment by dkorpel** [comment]
During the Dec 8 DLF monthly meeting, Walter was in favor of putting different OS'es (Windows, Linux, FreeBSD, macOS) in different folders.

**Comment by dkorpel** [comment]
Mike posts summaries in the Announce forum, though it has a bit of delay. The latest one is: [D Language Foundation October 2023 Quarterly Meeting Summary](https://forum.dlang.org/post/jucppgelbdvxvoubxzkr@forum.dlang.org)

**Review by dukc — APPROVED** [review]
Ok @denizzzka, time for the comments you requested at the forums.

I'm somewhat disappointed that this needs a script. On the other hand, a `src/core/sync/event.d` that just read like `version (Posix) public import coreconfig.posix.core.sync;` wouldn't be ideal either since it would require updating the public imports each time platforms are added, while this mechanism is smarter.

It would probably have been better to write the file copying script in D since that's what this repo usually does when the logic is about more than just flag setting. We require a host D compiler with a standard library anyway because we have `compiler/src/build.d`. But asking you to rewrite it before accepting this would probably be more than it's worth so I don't.

But otherwise, I very much like this PR! I think it can also be a big help in the very thing I complained about, as we're getting rid of the `version() else static assert(0, "unsupported")` thing along with version statements in general, meaning stubbing stuff is becoming easier than it was. It will be much easier than before to just copy files from the `config/` directory and replace them with stubs when programming for platform that doesn't yet have DRuntime support.

Also I'm happy to hear Walter is interested in supporting this, or at least somthing along these lines. I recommend merging this.

**Comment by denizzzka** [comment]
> I'm somewhat disappointed that this needs a script.

Seems, there's nothing can do about it: something has to take over `version(..)` functionality. Script or maybe something like `parse_tagged_hier.d` binary is necessary.

But scripts changes will be simplified in a short time because #15894 removes `win*.mak` and `mak/WINDOWS`

> On the other hand, a `src/core/sync/event.d` that just read like `version (Posix) public import coreconfig.posix.core.sync;` wouldn't be ideal either since it would require updating the public imports each time platforms are added, while this mechanism is smarter.
> 
> It would probably have been better to write the file copying script in D since that's what this repo usually does when the logic is about more than just flag setting.

Windows copying script line will be removed in a short time (see before)

Copying which is used by GNU Make is implemented not in this PR and already used for years for `include/` dir creation

> We require a host D compiler with a standard library anyway because we have `compiler/src/build.d`. But asking you to rewrite it before accepting this would probably be more than it's worth so I don't.
> 
> But otherwise, I very much like this PR! I think it can also be a big help in the very thing I complained about, as we're getting rid of the `version() else static assert(0, "unsupported")` thing along with version statements in general, meaning stubbing stuff is becoming easier than it was. It will be much easier than before to just copy files from the `config/` directory and replace them with stubs when programming for platform that doesn't yet have DRuntime support.

I completely agree!

> 
> Also I'm happy to hear Walter is interested in supporting this, or at least somthing along these lines. I recommend merging this.

Thank you for your feedback!

**Comment by ibuclaw** [comment]
> During the Dec 8 DLF monthly meeting, Walter was in favor of putting different OS'es (Windows, Linux, FreeBSD, macOS) in different folders.

To clarify, the idea is generally favourable. The means requires strict approval of both @kinke and @ibuclaw.

One attempt at splitting these bindings into different architectures ~10 years ago sank - that there's too many potential to support didn't help. Making the OS the dividing line for the module system may be more palatable. It will have to be tested.

> But otherwise, I very much like this PR! I think it can also be a big help in the very thing I complained about, as we're getting rid of the `version() else static assert(0, "unsupported")` thing along with version statements in general, meaning stubbing stuff is becoming easier than it was.

I don't know who "we" is and why they want to remove `static assert(false);`. That is not the current consensus as far as I'm aware.

**Comment by dukc** [comment]
> > During the Dec 8 DLF monthly meeting, Walter was in favor of putting different OS'es (Windows, Linux, FreeBSD, macOS) in different folders.
> 
> To clarify, the idea is generally favourable. The means requires strict approval of both @kinke and @ibuclaw.
> 

Of course.

> I don't know who "we" is and why they want to remove `static assert(false);`. That is not the current consensus as far as I'm aware.

With "we" I meant everyone involved. I could have also said "you" as in regular DMD contributors. In either case you're definitely included :-).

As for the "why", it's what this PR does. Since versioning is done by picking the correct D files from `config/` subdirectories, it replaces the `version` statements DRuntime currently uses for that and along with them, the unsupported platform static assertions at their else clauses. I can't know if that's what you want to do, but that's what happens if you do the versioning like it's done here.

**Comment by dukc** [comment]
> Seems, there's nothing can do about it: something has to take over version(..) functionality.

Yes, didn't mean that as criticism. Just that I'd prefer if we could use the module system in the language to do this as well as the script. Since that doesn't seem possible though, at least not without some ugly tricks, the script is justified IMO.

**Comment by RazvanN7** [comment]
> To clarify, the idea is generally favourable. The means requires strict approval of both @kinke and @ibuclaw.

@kinke @ibuclaw where do we stand with this?

**Comment by denizzzka** [comment]
Important notice: this PR implies that `import/` content will be different for each tag set

Because of this, for example, we must provide something like `/usr/include/dmd/druntime/windows/import` if we want to be able to compile binaries for Windows on Linux.

This is same approach as different Linux kernel headers packages coresponding to a different kernel binaries, but derrived from one kernel source tree

(Discussion https://forum.dlang.org/post/vbpsgrypvwmxxwrxusrn@forum.dlang.org)

**Comment by denizzzka** [comment]
> How about splitting up the implementations in something like core.internal.sync.event.{windows,posix} and publicly importing the proper module in core.sync.event?

Will not work for a range of tragets for which `core.internal.sync.event.{target}` isn't implemented in main source tree. For embedded it isn't possible to define all targets, because each set of implementions of any needed primitives is a separate implementation in such D terms. So, it leads to combinatory explosion of implementations matrix.

**Comment by denizzzka** [comment]
> The cross-compilation use cases kill this approach IMO.

(Cross-compilation also was main reason to suggest this PR)

>Then LDC doesn't use the upstream Makefile, but CMake. We don't have an import tree; for the install build target, all *.d[i] files are copied over from druntime and Phobos, except for the rt druntime package IIRC.

This is ~same approach as works current dmd/druntime Makefile. Except that they use predefined list of modules what needed to be copied into `import/`

> I'm also no fan of having to tell the build system which druntime modules to compile for a specific target;

At first sight this isn't looks as big problem: `ldc2.conf` syntax already allows to define separate paths to `imports/` for all supported targets

**Comment by kinke** [comment]
> Will not work for a range of tragets for which `core.internal.sync.event.{target}` isn't implemented in main source tree. For embedded it isn't possible to define all targets, because each set of implementions of any needed primitive is a separate implementation in such D terms. So, it leads to combinatory explosion of implementations matrix.

Adding an extra layer is as simple as adding a `-I` dir containing a custom, non-upstreamed `core/sync/event.d` module for one's favourite platform. For LDC, the `-I` path for the druntime/Phobos imports is a `post-switches` entry, meaning that all explicit `-I` in the compiler cmdline have a higher priority.

**Comment by denizzzka** [comment]
> Adding an extra layer is as simple as adding a -I dir containing a custom, non-upstreamed core/sync/event.d module for one's favourite platform

`-I` is only for imports. In other words, we still end up with the situation where compiler forced to use separate paths to separate sources and imports.

And also we want (as enhancement) to be able replace modules not as individual elements or the entire "platform implementations", but as sets of elements (as groups labelled by same tags).

**Comment by denizzzka** [comment]
@kinke 

> Then LDC doesn't use the upstream Makefile, but CMake. We don't have an import tree; for the install build target, all *.d[i] files are copied over from druntime and Phobos, except for the rt druntime package IIRC. 

This is how tags support can be implemented for CMake:
https://github.com/opendlang/opend/pull/24/files#diff-d55d21ac9c6461b7058d75699e8733f4a93b60d70bd216138b5dae2612715066

**Comment by denizzzka** [comment]
> I'm also no fan of having to tell the build system which druntime modules to compile for a specific target;

Otherwise (as for now) we force compiler to resolve "version branches" twice: first when compiling druntime, and then again when it uses imports for linking of application with druntime.

Obliviously, if for some reason a difference is accidentally introduced between the druntime sources and the sources used by the user, then user risks to get an incorrectly linkinked binary. Such cases are rare now just because we have few supported platforms and we merging not so many changes into druntime sources.

Therefore, as in any case, we should supply both druntime binary and the import/ files corresponding to druntime binary version/commit. So there is no problem in the fact that there will be many imports - for each binary, because it can be built from slightly different druntime sources: it can be considered not as a problem, but as a solution to the problem

**Comment by denizzzka** [comment]
> I'm also no fan of having to tell the build system which druntime modules to compile for a specific target

Otherwise (as for now) we force compiler to resolve "version branches" twice: first when compiling druntime, and then again when it uses imports for linking of application with druntime.

Obliviously, if for some reason a difference is accidentally introduced between the druntime sources and the sources used by the user, then user risks to get an incorrectly linkinked binary.

Therefore, in any case, we should supply both druntime binary and the imports corresponding to it. So there is no problem in the fact that there will be many imports - for each binary: it can be considered not as a problem, but as a solution to the problem

I briefly looked into `libc6-dev` - they use same approach: files in bundle only corresponding to the current platform, not to all platforms what libc6 supports

**Comment by kinke** [comment]
Sorry, there's just no way to convince me that this proposal is in any way better than having a pair of `core.internal.sync.event.{windows,posix_threads}` (with the option to extract common stuff into a `package.d` or whatever, and having the implementations grouped together in a single directory, not spread out out into `config/{windows,posix_threads}/core/sync/event.d`) and controlling the actual imports in `core.sync.event`, with a few `version` statements + public import lines - instead of complicating the druntime build scripts, bundled imports and cross-compilation.

**Comment by denizzzka** [comment]
> Sorry, there's just no way to convince me that this proposal is in any way better than having a pair of core.internal.sync.event.{windows,posix_threads} (with the option to extract common stuff into a package.d or whatever, and having the implementations grouped together in a single directory

It is impossible to place implementations into a single directory because we want to provide "external" implementations too. You mean here a single package?

> not spread out out into config/{windows,posix_threads}/core/sync/event.d) 

(Also, such spread out is good for copy-and-pasted declarations like as in `tgmath.d` or in libc bindings)

> and controlling the actual imports in core.sync.event, with a few version statements + public import lines

(2) It is impossible to provide access to external implementations by `public import` statements directly: we can't use in D code something like:
```d
public import config.${platform_name}.core.sync.event;
```

**Comment by denizzzka** [comment]
> instead of complicating the druntime build scripts, bundled imports and cross-compilation

Just to clarify

I don't think what we actually provide few druntime binaries for each platform that supports all range of theese Libc support: Glibc, Musl, UClibc, etc. And by cross compilation we usually mean as targets only few platforms: Windows, Linux, OSX, *BSD - and each with a one specific configuration of the druntime binary.

And when we say that cross-compilation with the same `import/` is possible we mean only case then we use same `version(..)` set as used. That is, we are usually just lucky (or compiler helps us to set up right versions set) that everything works during cross-compilation

And all we need to support this PR is to specify different output `import/` path per compilation of each druntime binary, so that several directories are created.

Is this correct?

**Comment by ibuclaw** [comment]
> > I'm also no fan of having to tell the build system which druntime modules to compile for a specific target
> 
> Otherwise (as for now) we force compiler to resolve "version branches" twice: first when compiling druntime, and then again when it uses imports for linking of application with druntime.
> 

Versions conditions are cheap.  So performance can't be the reason to avoid expanding them on every compiler invocation.

**Comment by ibuclaw** [comment]
> (2) It is impossible to provide access to external implementations by `public import` statements directly: we can't use in code something like:
> ```d
> public import config.${platform_name}.core.sync.event;
> ```
> In addition, my proposal doesn't requires adding D code, any D "static if" wrappers and so on. A single change in the druntime build script code is better than ~60 D wrappers (one for each module which will be affected). In the result is a lot less manual work and much cleaner code. And finally, in case if it all turns out bad, it will be possible to join *.d sources back automatically

When it comes to adding external implementations, the complexity of both approaches look to be the same.

**Comment by denizzzka** [comment]
@ibuclaw 
> Versions conditions are cheap. So performance can't be the reason to avoid expanding them on every compiler invocation.

I am not worry about performance issues, I talk about possible inconsistency between binary on target machine and versions set used during compilation

> When it comes to adding external implementations, the complexity of both approaches look to be the same.

(I don't agree, but let's assume)

It is known that earlier there were attempts to reform these sources in this way. But nothing came of it. Why? I think reason is that it is unrealizable in the current dialect of the D language.

It is need to somehow combine `version`s, `static if`s and `enum`s. This seems obvious to everyone. But there is still no solution. (And, yes: I tried to solve it too, without success)

**Comment by denizzzka** [comment]
> For cross-linking

:+1: 

> - With your approach however, one would either need a different import tree for each target, or a multi-level import tree (multiple import roots), so even for cross-compiling without linking, the target's imports and the -I ldc2.conf tweak would be needed.

"Multiple import roots" is something like:
```
import/linux-glibc/core/sync/event.d
import/linux-musl/core/sync/event.d
import/linux-uclibc/core/sync/event.d
import/osx-glibc/core/sync/event.d
import/osx-musl/core/sync/event.d
import/windows-mingw/core/sync/event.d
import/windows-msvc/core/sync/event.d
[etc..]
```
?

For common `druntime-dev` bundles we can just perceive this as a single `import/` as for now. Just need to add widely-used platforms (for now actually ~6: windows, linux, bsd*3, osx) imports into `-dev` package and into `ldc2.conf`.

All other cases (when user builds druntime by himself will work as usual without changes)

**Comment by ibuclaw** [comment]
> For common `druntime-dev` bundles we can just perceive this as a single `import/`. Just need to add widely-used platforms (for now actually ~6: windows, linux, bsd*3, osx - each of them with one type of libc) imports into `-dev` bundle and into `ldc2.conf`.

NB. Linux has five different kinds of libc runtimes which support it, and Windows has another four.

**Comment by ibuclaw** [comment]
> It is known that earlier there were attempts to reform these sources in this way. But nothing came of it. Why? I think reason is that it is unrealizable in the current dialect of the D language.
> 

Actually the reason is much more mundane than that. Initially the idea was to split up druntime across a different line in its support matrix. One that would have resulted in an explosion (think around the figure of ~20-30) of modules per package. It seems embarrassing to say so, but it took 10 years for the same people who initially attempted it to say "I would carve it the other way, that other way sounds nuts", forgetting that the "nuts" method was exactly what they tried to do on first attempt.

**Comment by denizzzka** [comment]
@ibuclaw 
>> For common druntime-dev bundles we can just perceive this as a single import/. Just need to add widely-used platforms (for now actually ~6: windows, linux, bsd*3, osx - each of them with one type of libc) imports into -dev bundle and into ldc2.conf.

> NB. Linux has five different kinds of libc runtimes which support it, and Windows has another four.

Yep, but we need to support only one for each platform

This support is necessary only for those users who are now linking cross-platform targets as “just for Linux”. So, they actually isn't choice libc type or another versions, because on their target platforms only one druntime binary is available (provided by ldc2 distributon package, for example) with one predefined version of libc.

Other users (who care about nuances of libc and other "version" abilities) building druntime themselves and, therefore, able to specify `import/` related to their custom druntime binary

**Comment by denizzzka** [comment]
> Initially the idea was to split up druntime across a different line in its support matrix.

> Specifically I'm referring to Arch vs. Platform. It failed because the original dividing line was the architecture.

So I would prefer to not to call this PR "split up" or "dividing" of the code :-)

This proposal does not touches logical structure of the D code. Code will remain same "naturally formed".

**Comment by denizzzka** [comment]
(I have another idea, maybe it will be better. Let's put this PR on pause for now.)

**Comment by denizzzka** [comment]
In case of "multiple import roots" solution: if you are concerned about duplicating of a lot of code it is possible to distinguish platform-specific code into separate directory. But in this case will be need pass two `-I` options into compiler: for `import/` and for specific `platforms/platform_name/`

**Comment by denizzzka** [comment]
We can provide platform-specific directories only fot those 6 platforms mentioned above. (This number will always be small - equal to the number of platforms for which the "official" druntime binary is provided.)

But by default let build scripts remain as it is now (i.e., platform-specific files installed into root of `import/`) - then users who build druntime for themselves also won’t notice anything, it won’t affect them.

Please agree! Otherwise we will never get out of this versions hell. It is obvious that functionality of `version(..)` isn't enough for such complex cases.

**Comment by denizzzka** [comment]
There is another option that solves only problem of external implementations: implement this PR but only with tags like `officially_supported_threading`, `officially_supported_os`, `officially_supported_libc`, etc. In other words, a tags will work but the official resulting code will be same for each target.

In this case cross-linking routine will not changes and "versions hell" will not be resolved. But we will be able to create external implementations of needed functions. (And in this case we still need to move, for example, `Event` unittests into a different module, as in this PR.)

In the future, if the community decides to reorganise all druntime code with a such tag system, this can be easily done

**Comment by denizzzka** [comment]
In a short time I’ll move Event methods into a separate event_impl.d and revert test back to event.d

**Comment by denizzzka** [comment]
> In a short time I’ll move Event methods into a separate event_impl.d and revert tests back to event.d

Done

I think that it is better to maintain this specific event module by this way

Also, as side effect, becomes obvious pointlessness of the handler checks before each `Event` method calling

**Comment by denizzzka** [comment]
@ryuukk 
> This is over engineered..

You mean script or whole idea?

> why a cryptic bash script to split files???

I hesitated to write on D because I was afraid of a potential chicken and egg problem. Bash script works on all our official platforms out of box. And script is a quite simple.

> It should be as simple as this:

> core/sync/event.d
> core/sync/event_posix.d
> core/sync/event_windows.d
> core/sync/event_darwin.d
> grep-able and easy to maintain

...Imagine that there are 80 such lines

**Comment by denizzzka** [comment]
> Anything else is just bad

If you like, this is a necessary evil: Unfortunately, currently druntime isn't same as C rtl/crt. It these C terms druntime is a huge rtl + **libc**. Therefore we are forced to move from current versions to something like (in C terms) different include dirs for a different libc implementations

And without that mechanism it will be impossible to explain to the community why some specific code suddenly needs to be allocated into a separate module (so that it can be replaced in some third code) - the answer always will be: it is convenient as it is for us. Therefore, it is necessary to create a switching mechanism that will also be used by official platforms.

In addition, we already using a similar switching mechanism for core.sys.* (in ldc2 cmake scripts) and (my opinion) we need same approach for core.stdc.* -  just a huge unmaintainable files (as for me, of course) 

Regular users won't notice anything. Only /etc/ldc.conf will give 7 lines like:
```
// Imports for officially supplied druntime binaries:

".+-windows-.+":    { post-switches = [ "-I/tmp/include/d", "-I/tmp/include/d/platforms/windows" ]; };
".+-osx-.+":        { post-switches = [ "-I/tmp/include/d", "-I/tmp/include/d/platforms/osx" ]; };
".+-dragonfly-.+":  { post-switches = [ "-I/tmp/include/d", "-I/tmp/include/d/platforms/dragonfly" ]; };
".+-freebsd-.+":    { post-switches = [ "-I/tmp/include/d", "-I/tmp/include/d/platforms/freebsd" ]; };
".+-linux-.+":      { post-switches = [ "-I/tmp/include/d", "-I/tmp/include/d/platforms/linux" ]; };
".+-netbsd-.+":     { post-switches = [ "-I/tmp/include/d", "-I/tmp/include/d/platforms/netbsd" ]; };
".+-openbsd-.+":    { post-switches = [ "-I/tmp/include/d", "-I/tmp/include/d/platforms/openbsd" ]; };
".+-sunos-.+":      { post-switches = [ "-I/tmp/include/d", "-I/tmp/include/d/platforms/sunos" ]; };
```

Thats all!

**Comment by denizzzka** [comment]
> similar switching mechanism for core.sys.* (in ldc2 cmake scripts)

It will be difficult to change it now. If at the time of core.sys.* creation there was a proposed mechanism then it would be great

**Comment by ibuclaw** [comment]
For the sake of discussing all currently used mechanisms, did you consider breaking up druntime into features rather than versions?

https://github.com/gcc-mirror/gcc/blob/master/libphobos/libdruntime/gcc/config.d.in

This file is generated at configure-time for gdc after having tested what the target system has available.

Obviously `static if` and `version` doesn't mix, but if you use just one consistently it should be fine - assuming that you don't do strange things like the following: https://issues.dlang.org/show_bug.cgi?id=17883

**Comment by denizzzka** [comment]
> For the sake of discussing all currently used mechanisms, did you consider breaking up druntime into features rather than versions?
> 
> https://github.com/gcc-mirror/gcc/blob/master/libphobos/libdruntime/gcc/config.d.in

Actually, I exactly suggest to breaking it down into features (named "tags"). But proposed "features" can be changed also from outside of the official sources.

In the above example, we do not have the abilities to replace atomics with stubs (which is common for single-core CPUs). Yes, maybe this will be solved by the replacement of symbols during the linking, but: there are dozens of such places in druntime, and are all a little different: somewhere it is need to replace class, somewhere need to replace bunch of enums, etc. Also, shove all druntime code into something like:
```d
version (CRuntime_Glibc)
{
    version = Any_Have_Tgmath;
    version = Any_Have_TgMath_Mod;
    version = Any_Have_TgMath_NaN;
}
else version (NetBSD)
{
    version = Any_Have_TgMath;
    version = Any_Have_TgMath_Mod
}
else version (OpenBSD)
{
    version = Any_Have_TgMath;
}
```
?  In my opinion, this which will only complicate possible solution in the future. And it is not a cheap, it's a thousands lines, I think.

Proposed in this PR approach allows us to achieve results "just right now". It will give us time to inventing some way to create static compilation branches based on standard language features. If successful, we will simply delete script, and even the ldc2 configuration file will continue to work (because it introduces only additional `-I` switches which compiller ignores if path is unavailable)

In the future, if a graceful solution will be found (without a scripts, etc), it will be possible to switch to it easily: until such a solution has been found, modules will move to a state more convenient for such hypotetical static branching due to the use of the proposed approach

> This file is generated at configure-time for gdc after having tested what the target system has available.

So we found out that GDC also uses its own mechanism to perform near to the same task

> Obviously `static if` and `version` doesn't mix, but if you use just one consistently it should be fine - assuming that you don't do strange things like the following: https://issues.dlang.org/show_bug.cgi?id=17883

This is exactly what I would like to avoid by this PR

**Comment by denizzzka** [comment]
> > For the sake of discussing all currently used mechanisms, did you consider breaking up druntime into features rather than versions?
> > https://github.com/gcc-mirror/gcc/blob/master/libphobos/libdruntime/gcc/config.d.in
> 
> Actually, I exactly suggest to breaking it down into features (named "tags"). But proposed "features" can be provided also from outside of the official sources (and this is for free)

> > This file is generated at configure-time for gdc after having tested what the target system has available.

> So we found out that GDC also uses its own mechanism to perform near to the same task

Let me make it more clear, that's what I mean (this is my current cmake script for ldc2): https://github.com/opendlang/opend/blob/fda4c0c698137a064b4cbef6255b7f90518f09db/ldc/runtime/CMakeLists.txt#L282
```cmake
# Official targets
set(OfficialPlatforms
    "windows" "osx" "dragonfly" "freebsd"
    "linux" "netbsd" "openbsd" "sunos"
)

# Tags matrix for them
set(TAGS_windows    "windows")
set(TAGS_osx        "posix_threads")
set(TAGS_dragonfly  "posix_threads")
set(TAGS_freebsd    "posix_threads")
set(TAGS_linux      "posix_threads")
set(TAGS_netbsd     "posix_threads")
set(TAGS_openbsd    "posix_threads")
set(TAGS_sunos      "posix_threads")
```

For each line of this matrix "official targets" imports is generated and then can be placed into a bundle with druntime binary. This works ~same as your sample from GDC, but for all targets (so as not to cause discontent ldc users who are used to cross-compile) and this is universal between compilers, applied to the entire druntime and usually does not require heavily changing *.d sources

**Comment by ibuclaw** [comment]
> Let me make it more clear, that's what I mean (this is my current cmake script for ldc2): https://github.com/opendlang/opend/blob/fda4c0c698137a064b4cbef6255b7f90518f09db/ldc/runtime/CMakeLists.txt#L282

[snip]

> For each line of this matrix "official targets" imports is generated and then can be placed into a bundle with druntime binary. "windows" and "posix_threads" is a such "features". This works ~same as your sample from GDC, but for all targets (so as not to cause discontent ldc users who are used to cross-compile) and this format of a tags is universal between all compilers, applied to the entire druntime and usually does not require heavily changing *.d sources

That matrix makes some bold assumptions.  You can't be that assertive about will be available from one version of a platform to the next, or platform-x86 has the same feature as platform-arm.

To pick out one example from my reference.
```
// Whether struct dl_phdr_info has dlpi_tls_modid member.
enum OS_Have_Dlpi_Tls_Modid = @DCFG_DLPI_TLS_MODID@;
```
This is `false` on Solaris 11.4, but `true` from Solaris 11.5 onwards.

FreeBSD and MacOS are two similar moving targets with their APIs.  e.g (1): someone decided it would be a good idea to call `__fork()` in the GC when compiling for OSX, ignoring that this symbol doesn't exist for 10.8 and earlier.  e.g (2): FreeBSD completely rewrote `stat_t` between version 11 and version 12.

**Comment by ibuclaw** [comment]
More likely than not, ImportC will kill off the C run-time bindings as they currently are implemented.

https://github.com/ibuclaw/dmpdecimal/blob/main/dmpdecimal.d#L29-L37

You can even check for symbols that _might_ be missing in the C headers, and selectively expose them.

https://github.com/ibuclaw/dmpdecimal/blob/main/dmpdecimal.d#L122-L127

**Comment by denizzzka** [comment]
> I don't know where atomics came from - if you're referring specifically to the three enums in gcc/config.d, the libatomic library is there to do the right thing for you, so no need to do anything special on the druntime side.

Yes, I saw a reference to atomics library and remembered that I had to cover everything related to atomics with a stub that does nothing im my STM32 druntime binding

> Not really. GDC is doing something _completely_ different to here. The config module is a guide for the _implementation_ of the core run-time library, rather than the public C library bindings.

Ok

By the way in the proposed "tag scheme" I do not distinguish between published by druntime bindings and internal implementations - any module can be switched using this mechanism (just need to add the path to it to the file `TAGGED_COPY` if it should be represented in `import/` dir)

**Comment by denizzzka** [comment]
> That matrix makes some bold assumptions. You can't be that assertive about will be available from one version of a platform to the next, or platform-x86 has the same feature as platform-arm.

I am absolutely sure here: it is from these sources and imports corresponding druntime will be builded and tested for all these platforms

> To pick out one example from my reference.

Discussed matrix intended only to ldc2 with its own unique ldc2.conf

**Comment by denizzzka** [comment]
@ibuclaw 
> More likely than not, ImportC will kill off the C run-time bindings as they currently are implemented in druntime.

Nothing is killed here - everything lives forever in the name of backward compatibility  :-)

Well, that is, I think core.stdc.* files will stay with us for the next ~5 years

**Comment by denizzzka** [comment]
@ibuclaw Okay, let's also see to the patch for the druntime which I want to away by this PR: https://gist.github.com/denizzzka/e8325b75af3cfd1a942a7306f82f33f4

This is current minimal patch to support a third-party targets. 90% of its lines is a like:

(My own main() because before D code starts it is need to [prepare environment](https://github.com/denizzzka/d_c_arm_test/blob/master/d/druntime_freertos_backend/external/rt/dmain.d). Official rt.dmain already contains internal version branching.)
```patch
+version (DruntimeAbstractRt)
+{
+    public import external.rt.dmain : _d_cmain;
+}
+else
```

(Picolibc currently is used - it isn't available in official druntime sources. But remembering what official core.libc.* already contain internal version branching for switching libc.)
```patch
+else version (CRuntime_Abstract)
+{
+    public import external.libc.stddef : wchar_t;
+}
```

(Whole core.sync.* end user API is need to be implemented from scratch. Same, core.sync.* is already contain version branching for all of its methods.)
```patch
+version (DruntimeAbstractRt)
+    public import external.core.mutex;
+else
```
And everything like that

How this can be solved by a another graceful way?

**Comment by denizzzka** [comment]
@kinke 
> Adding an extra layer is as simple as adding a -I dir containing a custom

Yes, I thought well and - you were right! There is really is no exactly need to produce identical files, many `-I` directives is what is need and it’s as easy to implement as copying files.

(But I won't do anything for now - let community make a positive decision about whole approach first)

**Comment by denizzzka** [comment]
Implemented in https://github.com/denizzzka/dfruntime

**Pull request closed without merging**
