### PR TITLE
CircleCI: merge PR branch into master before testing

### PR DESCRIPTION
**Pull request by wilzbach**
(Yet another improvement to our automation infrastructure)

Similar to the already merged PRs at Druntime and Phobos:

https://github.com/dlang/druntime/pull/1723
https://github.com/dlang/phobos/pull/4955

In general it makes a lot of sense to merge to merge with the upstream branch, s.t. changes are always tested as they would be merged (DAutoTest and auto-tester behave in the same way).

I added some minor updates to the script as well, e.g. always using `--depth 1` caused a stupid error at Phobos when done with the tools repo.

### CODE REVIEW

**Comment by WalterWaldron** [comment]
Fix for random failure here: https://github.com/dlang/phobos/pull/4997

**Comment by MartinNowak** [comment]
See https://github.com/wilzbach/dmd/pull/1 for a fixup. Merging that PR into your fork branch will update _this_ PR.

**Comment by MartinNowak** [comment]
Merge conflicts???

**Comment by MartinNowak** [comment]
Works fine locally. Unfortunately don't have the time to ssh into the box right now.

**Comment by MartinNowak** [comment]
Ah, the shallow branch is the problem, git lacks history to do a correct merge.

**Comment by MartinNowak** [comment]
Let's try again, still no need to fetch the other branches.

**Comment by wilzbach** [comment]
> Let's try again, still no need to fetch the other branches.

@MartinNowak it passes now, but I messed up the git history by doing the same change simultaneously and dumbly force pushing. sorry - will be more careful next time :/
I would squash all changes up into one commit if you don't mind?

**Comment by MartinNowak** [comment]
Sure, can you preserve the important parts from the commit messages, also dumped an alternative variant (using GH merge refs) there.

**Comment by wilzbach** [comment]
> Sure, can you preserve the important parts from the commit messages,

-> I reduced the number of commits to 3 & CircleCi is green :)

**Pull request merged**
