### PR TITLE
fix Issue 20903 - seg fault on long signed divide overflow

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This can go directly in the stable branch.

**Comment by WalterBright** [comment]
Blocking https://github.com/dlang/dmd/pull/11236

**Comment by UplinkCoder** [comment]
@WalterBright can you target stable?

**Comment by WalterBright** [comment]
No, because it is not a regression, and I need it for the PR it is blocking.

**Comment by UplinkCoder** [comment]
@WalterBright go ahead and self-merge then.
This is harmless as far as I can see.

**Pull request merged**
