### PR TITLE
Fix issue 14411 - Make implicit switch case fallthrough an error

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
[As per @andralex 's request](https://issues.dlang.org/show_bug.cgi?id=14411#c7).

### CODE REVIEW

**Comment by andralex** [comment]
Alrighty, let's do this!

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by mathias-lang-sociomantic** [comment]
Arg, it was missed in the switch from warning to deprecation ( https://github.com/dlang/dlang.org/pull/1286 ). However it was a warning since 2.054, and documented as gone since 2.068. I highly doubt another cycle will help.

**Comment by MartinNowak** [comment]
Yes, should have get a deprecation first, broke at least one project (Higgs).

**Pull request merged**
