### PR TITLE
fix Issue 15907 - unjustified deprecation with getMember

### PR DESCRIPTION
**Pull request by MartinNowak**
- reverts previous 15907 fix (#6078)
- skip visibility checks for hasMember, getMember, and getOverloads
- inherit scope flags for the new SCOPEflag and noaccesscheck
- keep existing access checks for now

### CODE REVIEW

**Comment by UplinkCoder** [comment]
I like this.
please merge ASAP.

**Comment by MartinNowak** [comment]
A few of the added cases might still need test cases, will add them later today.

**Comment by BBasile** [comment]
> keep existing access checks for now

To be clear you mean that `allMembers` is not modified. 15907 is fixed through the change to `getMember`, leaving room for further improvements to allMembers in the future. Do i got it ?

**Comment by MartinNowak** [comment]
allMember will remain in pre 2.071.0, we're removing visibility checks for getMember and will later also remove access checks

**Comment by WalterBright** [comment]
Thank you, @MartinNowak

**Pull request merged**
