### PR TITLE
Fix Issue 23814 - [Codegen] Calling member function of extern(C++) class with multiple inheritance doesn't preserve the EBX register in some cases

### PR DESCRIPTION
**Pull request by naydef**
I'm not sure how to test this.
Also I  have little idea what I'm doing, so help is appreciated.

### CODE REVIEW

**Comment by naydef** [comment]
Uh, dlang-bot didn't pick up the issue. Will be back soon

**Comment by dkorpel** [comment]
"Fix Issue 23814" needs to be in the commit message, which is currently "Update cod3.d". You can use `git commit --amend` and `git push --force` to update it without opening a new Pull Request.

**Comment by naydef** [comment]
I made new pull request. I modified the code from Github itself (for shame).

**Comment by Geod24** [comment]
@dkorpel : Actually `Fix 23814` works too (and since we want to keep titles short, I'd recommend it)

**Pull request closed without merging**
