### PR TITLE
do not use EX_SOLARIS twice in or expression

### PR DESCRIPTION
**Pull request by BarrOff**
@ibuclaw 

This partially fixes the issue stated here: https://issues.dlang.org/show_bug.cgi?id=22573.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
Fix commit title to say "partial fix"?

**Comment by BarrOff** [comment]
@ibuclaw

Done. But I do not know how to solve the second part. Have no experience with ELF binary file type.

**Comment by ibuclaw** [comment]
> @ibuclaw
> 
> Done. But I do not know how to solve the second part. Have no experience with ELF binary file type.

Did you forget to do a `git push -f`? ;-)

**Comment by ibuclaw** [comment]
Fix applied in #13405. Thanks for your work and testing!

**Pull request closed without merging**
