### PR TITLE
Simplify `Module.read` and its interaction with `FileManager`

### PR DESCRIPTION
**Pull request by Geod24**
```
Since the FileManager will read a file if it exists on the filesystem,
the else clause of Module.read was only ever called if File.read would fail.
As a result, the code can be simplified, and loadSourceBuffer can be renamed
to match its true purpose (printing a decent error message on missing file).
```

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
compilable\issue17167.sh seems to fail everywhere on Azure

**Comment by Geod24** [comment]
Yep, legit failure, looking into it.

**Review by ibuclaw — DISMISSED** [review]
Check headers, modules.h, file.h, etc. For declarations that should be removed.

**Comment by Geod24** [comment]
@ibuclaw : `FileBuffer` is still a member of `class Module` so it can't be removed yet.
`frontend.h` removes it because its decl is no longer used. A future PR will remove it as a member of `Module` (I'm basically trying to get rid of the coupling between module and IO).

**Comment by Geod24** [comment]
Found (and fixed) the bug

**Comment by Geod24** [comment]
To answer @ibuclaw more precisely:
```
% grep -nR -e "struct File$" -e "struct FileBuffer" $(find src -name "*.h")
src/dmd/frontend.h:232:struct FileBuffer;
src/dmd/root/file.h:15:struct FileBuffer
src/dmd/root/file.h:25:struct File
src/dmd/module.h:17:struct FileBuffer;
```

I could remove `root/file.h` if you guys are not using it, but perhaps it's better to wait until it's not used as a member of an AST node ? :)

**Comment by ibuclaw** [comment]
> To answer @ibuclaw more precisely:
> 
> ```
> % grep -nR -e "struct File$" -e "struct FileBuffer" $(find src -name "*.h")
> src/dmd/frontend.h:232:struct FileBuffer;
> src/dmd/root/file.h:15:struct FileBuffer
> src/dmd/root/file.h:25:struct File
> src/dmd/module.h:17:struct FileBuffer;
> ```
> 
> I could remove `root/file.h` if you guys are not using it, but perhaps it's better to wait until it's not used as a member of an AST node ? :)

It could be a `void*` field.  Having a quick scan, the C++ driver still needs to set `srcBuffer->data` when creating a module for code read from stdin.  If there was a C++ helper method such as `Module::setSrcBuffer(char *ptr, size_t length)` then you could internalize `File` and `FileBuffer`, removing file.h outright.

Just making sure that the C++ interface has been checked against for the removals here.

**Pull request merged**
