### PR TITLE
fix issues 20737 and 23014 - TLS variables unusable with -betterC/imp…

### PR DESCRIPTION
**Pull request by rainers**
…ortC for Windows MSVC targets

extracts the relevant parts from https://github.com/dlang/dmd/pull/15081

### CODE REVIEW

**Comment by dkorpel** [comment]
C++ interop tests with g++ looks like a spurious failure

**Review by dkorpel — APPROVED** [review]

**Comment by ibuclaw** [comment]
Bug fixes should target stable.

**Comment by ibuclaw** [comment]
Bug fixes should target stable please.

**Comment by rainers** [comment]
rebased.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
