### PR TITLE
fix issue 14717 - Ddoc macro recursion limit too low

### PR DESCRIPTION
**Pull request by aG0aep6G**
The error message misses file and line information. I'm not familiar with the dmd source, so I have no idea how to go about that. Even without it, a bad error message is better than none.

https://issues.dlang.org/show_bug.cgi?id=14717

### CODE REVIEW

**Comment by aG0aep6G** [comment]
I'm at a loss as for why the auto tester fails. Seems to be related to ddmd?

**Comment by 9rnsr** [comment]
Yes. In Win32, the reported error:

`dmacro.d(86): Error: undefined identifier error, did you mean class Error?`

means that the generated D source `dmacro.d` cannot call the `error()` function because it's not defined. In `dmacro.c`, you've added a new #include to call that function, so you should also fix `magicport.json`.

See http://wiki.dlang.org/Updating_Pull_Requests_for_DDMD

**Comment by aG0aep6G** [comment]
> In dmacro.c, you've added a new #include to call that function, so you should also fix magicport.json.
> 
> See http://wiki.dlang.org/Updating_Pull_Requests_for_DDMD

Thanks. Did that and rebased. Auto tester is happy now.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
LGTM.

**Pull request merged**
