### PR TITLE
[REG2.066.0] Issue 15092 - ICE on duplicated struct declarations in class members

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=15092

Propagate errors in `Dsymbol.addMember()` through `Dsymbol.errors`.

### CODE REVIEW

**Comment by WalterBright** [comment]
There are only a handful of substantive changes for this, and hundreds of white space changes. This is a classic example of something that should be divided into 2 pull requests.

I know you've pointed out that I do it, too, but the ones I've done have been an order of magnitude or two smaller in scope, which is manageable.

**Comment by WalterBright** [comment]
The rest LGTM.

**Comment by 9rnsr** [comment]
When I was investigating the cause of issue 15092, I've read most of `dstruct.d` code to find the best place to fix the bug. I'm tired to repeatedly understand the squashed code. 

I cannot wait the line space insertions in other PR.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
> When I was investigating the cause of issue 15092, I've read most of dstruct.d code to find the best place to fix the bug. I'm tired to repeatedly understand the squashed code.
>
> I cannot wait the line space insertions in other PR.

You need to stop doing this.  Refusing to keep unrelated changes out of pull requests is highly unprofessional.

**Pull request merged**
