### PR TITLE
CodeBuilder: outblkexitcode()

### PR DESCRIPTION
**Pull request by WalterBright**
`outblkexitcode()` is quite a snarl, this straightens it out somewhat.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@WalterBright is `outblkexitcode` conceptually the same as `scope(exit)` ?
If so, could you add a comment stating it ?

**Comment by WalterBright** [comment]
> is outblkexitcode conceptually the same as scope(exit) ?

No, they have nothing to do with each other.

**Comment by UplinkCoder** [comment]
@WalterBright what is it then ?

**Comment by yebblies** [comment]
@UplinkCoder It generates instructions to move between basic blocks.

**Pull request merged**
