### PR TITLE
Refactor dmd.declaration.Declaration.checkDisabled to use early return

### PR DESCRIPTION
**Pull request by RazvanN7**
And reduce nesting level.

cc @thewilsonator you didn't believe me when I said I will refactor this function :P

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
Wrong title, it's `checkDisabled` instead of `checkDeprecated`.

**Comment by RazvanN7** [comment]
Yeah, thanks. Fixed.

**Comment by thewilsonator** [comment]
Oh, I did, but that was to keep the refactor and fix separate, and I forgot about that PR sorry for the long wait on the merge.

**Review by thewilsonator — APPROVED** [review]

**Comment by RazvanN7** [comment]
No worries, I was just kidding.

**Pull request merged**
