### PR TITLE
Remove __INTSIZE

### PR DESCRIPTION
**Pull request by WalterBright**
It's not like it was possible to build a 16 bit dmd executable anyway.

### CODE REVIEW

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Keep them coming!  I guess we don't need to support DOS as a host any more, right?

**Comment by WalterBright** [comment]
I will. There's a lot of old cruft that can go. I do it in chunks so that git bisect will be useful if I break something, also so each change is easily checked.

**Comment by yebblies** [comment]
Yeah.   It may also be useful with this sort of change to check the dmd/dmc binary is identical before and after the change.

**Pull request merged**
