### PR TITLE
Make Loc.toChars pure and nothrow

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Review by thewilsonator — CHANGES_REQUESTED** [review]
`Loc` is a very important struct w.r.t memory consumed by the compiler. 

Since `showColumns` is only used in that method it would be better to make it a default parameter of `toChars()`.

**Comment by jacob-carlborg** [comment]
Walter doesn't like default parameters as far as I know. But I can try to make it a required parameter.

**Comment by thewilsonator** [comment]
As long as its not taking up more memory than is necessary _I_ really don't care. A required parameter is fine, might make the diff a bit bigger. @WalterBright any preferences?

**Comment by jacob-carlborg** [comment]
Using a parameter with a default value in `toChars` now.

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
Hiding the use of a global behind a default value is not a good practice, it's faking a good practice. Either make it explicit or not pure.

**Comment by andralex** [comment]
Been thinking of this for a while, seems like a good step forward.

Before `toChars()`:

* Not pure
* Use of globals entirely opaque (why is it not pure? what global(s) does it need?)
* Impossible to call from a pure context

After `toChars(bool showColumns = global.params.showColumns)`:

* Signature shows what global is involved - very informative!
* Pure caller code can call it by passing a `bool` in
* Better yet, that `bool` can be threaded in from the call chain all the way to the top level, where only one function is impure and passes `global.params.showColumns` down.

This is akin to Haskell's way of carrying monads around, and (less so) Scala's implicits. I think we're in good company.

I'm in favor of this idiom.

**Comment by jacob-carlborg** [comment]
Yes, thank you Andrei. I tried making it a required parameter but that resulted in too many change so I gave up. I was both tiresome to do all those changes and the resulting diff would have been too large.

With this approach it's now possible continue modifying the code base to explicitly pass in the `showColumns` argument one call at the time, instead of hundreds at once.

**Comment by jacob-carlborg** [comment]
Another approach would be to instead of printing the error immediately, collect them a print them later.  Then the printing function could implement what `Loc.toChars` is doing today and take `global.params.showColumns` into consideration as well. Here's an example of where I implemented this:

https://github.com/dlang/dmd/blob/e42f83e1164d53abec74c0447612c2e48dfc05b4/src/dmd/errors.d#L161-L170

Part of https://github.com/dlang/dmd/pull/9480.

**Pull request merged**
