### PR TITLE
Remove support for SemaphoreCI pipelines

### PR DESCRIPTION
**Pull request by ibuclaw**
CirrusCI has replaced the gap that SemaphoreCI filled in our CI pipelines.  As such, SemaphoreCI is no longer a required pipeline to pass on both the master and stable branches.

See https://github.com/dlang/dmd/discussions/13388 for previous discussion on sunseting our use of Semaphore.

All Semaphore CI pipelines are set-up in a way that they do nothing if this script doesn't exist.

image

### CODE REVIEW

**Review by ljmf00 — APPROVED** [review]
LGTM

**Comment by ljmf00** [comment]
Cirrus CI is failing for unrelated reasons.

**Comment by ibuclaw** [comment]
> Cirrus CI is failing for unrelated reasons.

Not if there's some memory-related nuances to macOS 12.x that need to be fixed.
```
****** FAIL debug64 std.experimental.allocator
core.exception.AssertError@std/experimental/allocator/package.d(3738): Assertion failure
```

**Comment by ljmf00** [comment]
> > Cirrus CI is failing for unrelated reasons.
> 
> Not if there's some memory-related nuances to macOS 12.x that need to be fixed on top of all the other things that were found to be broken on the latest macOS.
> 
> ```
> ****** FAIL debug64 std.experimental.allocator
> core.exception.AssertError@std/experimental/allocator/package.d(3738): Assertion failure
> ```

Right, I meant Heisenberg's, but seem to need extra care indeed. I don't see any recent change that might interfere with that other than https://github.com/dlang/dmd/commit/93108bb9ea6216d67fa97bb4842fb59f26f6bfc7 . I can't test this locally to debug it, unfortunately, since I don't have a mac.

**Review by MoonlightSentinel — APPROVED** [review]

**Comment by ibuclaw** [comment]
> > > Cirrus CI is failing for unrelated reasons.
> > 
> > 
> > Not if there's some memory-related nuances to macOS 12.x that need to be fixed on top of all the other things that were found to be broken on the latest macOS.
> > ```
> > ****** FAIL debug64 std.experimental.allocator
> > core.exception.AssertError@std/experimental/allocator/package.d(3738): Assertion failure
> > ```
> 
> Right, I meant Heisenberg's, but seem to need extra care indeed. I don't see any recent change that might interfere with that other than [93108bb](https://github.com/dlang/dmd/commit/93108bb9ea6216d67fa97bb4842fb59f26f6bfc7) . I can't test this locally to debug it, unfortunately, since I don't have a mac.

No, that won't interfere.  That's one of the fixes for OSX 12 because they've decided to abandon the .dtor section.  GCC and Clang do the exact same thing as that PR you've linked.

**Comment by ljmf00** [comment]
> No, that won't interfere. That's one of the fixes for OSX 12 because they've decided to abandon the .dtor section. GCC and Clang do the exact same thing as that PR you've linked.

Yeah, I'm aware, I was just informative since macOS 12 CI was added since that commit. Looking at the history there is other frequent Heisenberg's, not only with macOS 12 but also with Windows pipelines. See examples of those on https://github.com/dlang/dmd/commit/39712e41722fe6f210f1e74a1522f15bc904f742 and https://github.com/dlang/dmd/commit/ad8412530e607ffebec36f2dbdff1a6f2798faf7 . Anyway, I think this can be safely merged but suggest creating a [discussion](https://github.com/dlang/dmd/discussions) about the failures and brainstorming there.

**Pull request merged**
