### PR TITLE
Preview typefunctions

### PR DESCRIPTION
**Pull request by UplinkCoder**
Preview switch for typefunction functionality.

### CODE REVIEW

**Review by WalterBright — CHANGES_REQUESTED** [review]
Fair warning: I'm very predisposed in favor of the far simpler approach in https://github.com/dlang/dmd/pull/12029

That said, what this is missing is:

1. document or DIP describing what type functions are, how to use them, grammar, etc.
2. a description of how the implementation is designed. There's a thousand lines of code with very little in the way of any description. Like what's a Ttype?

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
Besides Walter's comments, this needs a changelog entry, a spec PR and all lines of code that were added need to be covered by tests (currently there are a lot of lines that are not covered).

**Comment by UplinkCoder** [comment]
@WalterBright the performance characteristics and ease of use of https://github.com/dlang/dmd/pull/12029
are not the same as the ones in this PR.
_You have_ merged gotten aliasAssign merged _without_ a DIP.
On the basis that it is purely additive.
I don't see why the same reasoning shouldn't apply to this PR once I've done all the changed to astbase.d to make it pass CI.

This PR is also purely additive as it provides a syntax and semantic extension that was not available previously and is behind a preview flag.

**Comment by UplinkCoder** [comment]
Who put needs tests there?
it has tests.

**Comment by RazvanN7** [comment]
I did because there are a lot of uncovered lines in this PR. Just from the top of my head you still need tests for:
 - nested type functions
 - aliases to type functions
 - overloaded type functions
 - introducing a type function into an overload set

**Comment by UplinkCoder** [comment]
> I did because there are a lot of uncovered lines in this PR. Just from the top of my head you still need tests for:
> 
> * nested type functions
> * aliases to type functions
> * overloaded type functions
> * introducing a type function into an overload set

Ah yes.
Very good points!

I shall add them.

**Comment by nordlow** [comment]
Would be interesting to find relevant test cases that highlight drops in compilation time and memory usage when using type functions compared to traditional template-solutions.

**Comment by maxhaton** [comment]
> Would be interesting to find relevant benchmarks, using common patterns such as `staticMap`, that highlight drops in compilation time and memory usage when using type functions compared to traditional template-solutions including new alias-assign.

@nordlow There should be a blog post soon-ish on what typefunctions are and aren't, some background on why they could be useful, and what their ethos implies for the rest of D

**Comment by UplinkCoder** [comment]
On Hold while more fundamental issues are being addressed.

**Pull request closed without merging**
