### PR TITLE
Fix ClassDeclaration.isBaseOf

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Issue number? Test case?

**Comment by 9il** [comment]
I have got an error kind of `class Module.C base class is forward referenced by C`.
We can't reduce the bug to find a test case. It is x86 specific and maybe windows specific.
In the same time, the fix looks pretty clear, because of the function contains a logical error.

**Comment by MoonlightSentinel** [comment]
Have you tried Dustmite?

Alternatively you could also create an `unittest` in `dclass.d`

**Comment by 9il** [comment]
No, I can't use Dustmite for this. I don't even have an option to compile 32 bit or windows programs.
It is a trivial logic bugfix.

It is a trivial bug fix for the trivial logic error. If it is not enough to merge, just close it.

**Comment by Geod24** [comment]
If you can't even test, how do you know this diff fixes it ?

**Comment by 9il** [comment]
I don't know

**Comment by 9il** [comment]
The point is that function contains a logic error, that is fixed by the MR.

**Comment by thewilsonator** [comment]
If you can't find a test case then please add a changelog entry so that this gets picked up in the release notes, thanks.

**Comment by atilaneves** [comment]
> The point is that function contains a logic error, that is fixed by the MR.

The function might, but as far as anyone knows it might never be called in a way where a bug manifests.

All in all it's probably ok to merge, but we don't want to encourage changes to production code without a corresponding test that would have failed if the change hadn't been made.

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
We cannot know if it is a logical error or not. Maybe the calls to `isBaseOf` are guarded by an explicit `if (this != cd)`. In this situation we would duplicate the check for no apparent reason. Maybe this addition fixes only a symptom of a larger bug. Again we cannot know. We simply cannot merge randomly without a test case on the basis that it seems like a logical thing to do.

In all probability this patch is correct, but if we want to have a mature merging process we simply cannot merge this without a test case that proves that the addition actually fixes anything.

**Comment by MoonlightSentinel** [comment]
> We cannot know if it is a logical error or not. Maybe the calls to `isBaseOf` are guarded by an explicit `if (this != cd)`. In this situation we would duplicate the check for no apparent reason. Maybe this addition fixes only a symptom of a larger bug. Again we cannot know. We simply cannot merge randomly without a test case on the basis that it seems like a logical thing to do.

Especially considering
> It is x86 specific and maybe windows specific.

**Comment by 9il** [comment]
> Maybe this addition fixes only a symptom of a larger bug.

Yes, I think this is true. I hope we can see a more informative error message in the next release after the fix. 

> In all probability this patch is correct, but if we want to have a mature merging process we simply cannot merge this without a test case that proves that the addition actually fixes anything.

**Pull request closed without merging**
