### PR TITLE
Pragma(linkedin)

### PR DESCRIPTION
**Pull request by UplinkCoder**
pragma(linkedin) will cause a symbol to be well linked into the which uses it
    given it is used

### CODE REVIEW

**Comment by adamdruppe** [comment]
is this going to make compiling slower?!

**Comment by dnadlinger** [comment]
If we really want to go this way, `linkedin` is a terrible name, as this is about _avoiding_ linkage. `always_emit`?

**Comment by UplinkCoder** [comment]
@adamdruppe marginally yes.

But only if `linkedin` is used.

@dnadlinger I don't mind changing the name to `emit` something.

**Comment by ibuclaw** [comment]
What is the rationale for this?  Why not just make the symbol a template by adding in an extra `()`?

**Comment by UplinkCoder** [comment]
I lose type checking if I do that.

Am Mo., 15. Juni 2020 um 18:50 Uhr schrieb Iain Buclaw <
notifications@github.com>:

**Comment by ibuclaw** [comment]
And why not extend `pragma(inline)` to mean on-demand and internal linkage?

**Comment by UplinkCoder** [comment]
> And why not extend `pragma(inline)` to mean on-demand and internal linkage?

Less contention on the the issue, that no inline does not actually mean inlining anymore.

**Comment by Geod24** [comment]
No rationale, changelog entry, spec change, or activity for 6 months, and the PR is still very much a WIP.
If you want to pursue this, please re-open a complete PR, with working code and a proper justification, including what other alternatives were considered and discarded. For example, we currently have an issue about `pragma(inline)` emitting symbols.

**Comment by UplinkCoder** [comment]
Ah I did forget about this one.
I am very unhappy with the implementation.

I'll repopen it once I can make it nice.

**Comment by PetarKirov** [comment]
@Geod24 @UplinkCoder I added the `Phantom Zone`, as I think it's appropriate for this PR.

**Comment by Geod24** [comment]
I tend to only add issues to the `Phantom Zone` if they come with a significant discussion / rationale (but I don't mind your feeling differently, obviously).
This was missing both, although this PR was motivated by, IIRC, [a discussion on the forum about inline](https://forum.dlang.org/thread/mailman.3723.1591596899.31109.digitalmars-d@puremagic.com).

**Pull request closed without merging**
