### PR TITLE
Fix ldc regression 3098: don't use Type this pointer as hash for backref, compare types instead.

### LINKED ISSUE #3098: -L--export-dynamic causes missing symbol hashOf with two libraries
Consider the following setup:

Start with a file `lib_a.d` defining some logic on a struct:

```
struct Test(T) {
    T member;

    size_t toHash() const {
        return hashOf(member);
    }
}

enum duppable(T) = is(typeof(T.init.dup));

enum test = duppable!(Test!(void delegate())[]);
```

Link this into library `lib_a.a`: `$ ldc -lib lib_a.d -oflib_a.a`.

Create two more files, `lib_b1.d` and `lib_b2.d`:

lib_b1.d:
```
static this() { }
```

lib_b2.d:
```
import lib_a;

void foo() {
    cast(void) (void delegate()).init;
}
```

Link this into library `lib_b.a`: `$ ldc -lib lib_b1.d lib_b2.d -oflib_b.a`.

Now create a `main.d` file:

```
import lib_b1;
void main() { }
```

And finally, build it into a binary with the libraries and the linker flag `--export-dynamic`: `$ ldc main.d -L-L. -L-l_a -L-l_b -L--export-dynamic -of=test`.

Expected: success

Actual: `./lib_b.a(lib_b1.o):lib_b1.d:function _D5lib_a__T4TestTDFZvZQl6toHashMxFNaNbNiNfZm: Fehler: undefined reference to '_D4core8internal4hash__T6hashOfTDFZvZQnFNaNbNiNeMxDFZvmZm'`

Have "fun"!

### PR DESCRIPTION
**Pull request by FeepingCreature**
Fixes https://github.com/ldc-developers/ldc/issues/3098 (which does not trigger in dmd).

`AssocArray` compares its key as `void*`. This works as long as you never reuse types, or you always reuse subtypes in the same type. But in the LDC bug, `hashOf` is mangled once with backrefs and once without.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
I presume you have tested this with LDC?

**Comment by FeepingCreature** [comment]
Yes, locally.

**Comment by thewilsonator** [comment]
> I'm a bit worried about the O(n^2)

Back-referencing was added because template UFCS chains with ranges produced n^2 symbol length and they usually have a different type per element of the chain. Those are exactly the kinds of symbols where hashing is designed to make it less ridiculous.

**Comment by FeepingCreature** [comment]
I'm using a variation of https://issues.dlang.org/show_bug.cgi?id=15831 to test this. (ping @rainers )

If I go 200 recursions deep, the `backrefType` code begins to be a significant part of the profile. This is obviously dissatisfactory.

**Comment by thewilsonator** [comment]
Ping me when its good to go.

**Comment by FeepingCreature** [comment]
Ergh, I can't compare strings obviously, because the strings may contain backreferences themselves. Bleh.

**Comment by FeepingCreature** [comment]
Okay, nevermind - seems this only worked by coincidence. Will try to come up with a better fix.

**Pull request closed without merging**
