### PR TITLE
Allow `alias this` to use assignment-style syntax

### PR DESCRIPTION
**Pull request by pbackus**
When assignment-style syntax for alias declarations was first implemented in DMD 2.061 [1][2], `alias this = identifier;` was accepted as equivalent to the existing `alias identifier this;`. One release later, in DMD 2.062, it was removed. [3]

The rationale for this change, given in both the changelog [4] and a related spec PR thread [5], was to allow for the possibility that, in the future, the syntax `alias this = super.this;` might be used to merge a derived class's constructor overload set with that of its base class. However, this proposal was never implemented, and seems to have been abandoned in the intervening years.

For the sake of consistency, and since the rationale for its removal no longer applies, this commit reinstates `alias this = identifier;` as valid syntax for an `alias this` declaration.

[1] https://github.com/dlang/dmd/pull/1187
[2] https://dlang.org/changelog/2.061.html
[3] https://github.com/dlang/dmd/pull/1413
[4] https://dlang.org/changelog/2.062.html
[5] https://github.com/dlang/dlang.org/pull/200#issuecomment-11711854

### CODE REVIEW

**Comment by pbackus** [comment]
Spec PR: https://github.com/dlang/dlang.org/pull/3589

**Comment by pbackus** [comment]
CI failure on macOS is [issue 23846][1], currently affecting all DMD PRs.

[1]: https://issues.dlang.org/show_bug.cgi?id=23846

**Review by dkorpel — APPROVED** [review]

**Comment by pbackus** [comment]
Added changelog.

**Comment by PetarKirov** [comment]
Thank you @pbackus for tackling this issue! Reading the old discussions, I get the impression that `alias X this` syntax has been bothering almost everyone (I'm glad it wasn't just me :smile:), so I know many people would be happy to see it be replaced with something better fitting the general design of the language :+1: 

What do you all think think about the two alternatives:
* `alias this : X;` proposed by #1341 / https://github.com/dlang/dlang.org/pull/200
   Reasoning: `alias X = Y;` declarations are consistent with variable declarations in the sense that they allow you replace a (potentially long and complex) expression with a symbol (that hopefully documents the intention). On other hand, `alias X this` not about (re)naming a symbol but establishing a subtyping relationship between a struct and its member, so using a distinct syntax would be fitting as the semantics are distinct from conventional alias declarations. Also it will nicely match the `is(T : U)` expression.
* `opThis`, proposed by @tgehr https://forum.dlang.org/post/ld5c9r$18lt$1@digitalmars.com (also mentioned in https://github.com/dlang/dmd/pull/1341#issuecomment-34845297)

**Comment by pbackus** [comment]
@PetarKirov This is an addition, not a replacement. As far as I know there are no plans to get rid of `alias X this`. And given that `alias X this` isn't going anywhere, consistency demands that we also allow `alias this = X`.

**Comment by PetarKirov** [comment]
> As far as I know there are no plans to get rid of alias X this.

Most likely, that's only because #1413 was merged and we dropped the ball on #1341. If the case was reversed, it's likely that that if the old `alias Old New;` syntax was deprecated (which I thought was, but looking at [here](https://dlang.org/deprecate) it seems it's only forbidden by the [D style CI checks](https://github.com/dlang/phobos/blob/master/.dscanner.ini#L73)), alias this would follow suit. Anyhow, that's a future topic for discussion.

> And given that alias X this isn't going anywhere, consistency demands that we also allow `alias this = X`.

I don't follow. As I mentioned before, "alias this" is about sub typing, so the `alias this : X` syntax would be more consistent with `is(T : X)`. `alias this = x` would imply that each time you're accessing `this.y` inside the aggregate, you're **always** accessing `this.x.y`, which is not exactly the case (e.g. if `y` is defined directly in the aggregate and not inside its `x` member).

**Comment by PetarKirov** [comment]
Btw Dart has a similar feature called inline classes: https://github.com/dart-lang/language/blob/main/accepted/future-releases/inline-classes/feature-specification.md

**Comment by pbackus** [comment]
> Anyhow, that's a future topic for discussion.

Yes. Any redesign or replacement for `alias this` will need a DIP and a long deprecation period, at the very least, all of which is out-of-scope for this PR thread.

> `alias this = x` would imply that each time you're accessing `this.y` inside the aggregate, you're **always** accessing `this.x.y`, which is not exactly the case (e.g. if `y` is defined directly in the aggregate and not inside its `x` member).

This argument applies equally well to both `alias this = x` and `alias x this`.

Again, this PR is not a referendum on `alias this` in general; it is about removing an unnecessary special case from D's syntax.

**Comment by dkorpel** [comment]
Atila approved this in an email

**Review by WalterBright — APPROVED** [review]

**Comment by WalterBright** [comment]
Would like to see a spec PR for this.

**Comment by pbackus** [comment]
@WalterBright Spec PR is https://github.com/dlang/dlang.org/pull/3589, as previously mentioned.

**Comment by WalterBright** [comment]
good

**Comment by WalterBright** [comment]
This needs to be reverted. It has caused too much disruption and angry responses.

**Pull request merged**
