### PR TITLE
[DDMD] Clean up response.c so it can be converted to D

### PR DESCRIPTION
**Pull request by yebblies**
- Remove a level of indentation
- Use root\file instead of reinventing it

### CODE REVIEW

**Comment by Safety0ff** [comment]
Would there be any benefit to manually re-writing responce.c in D so that it is no longer tied to the backendlicense? (I could do this)

**Comment by yebblies** [comment]
Yes, please.  inifile also needs a re-write.  https://github.com/D-Programming-Language/dmd/pull/3421#issuecomment-39661819

This code does some weird backslash escaping stuff that might be hard to duplicate.  I'm not sure it's actually valid on windows though.  It might be possible to re-use escaping code from std.process.

**Comment by yebblies** [comment]
Also, be aware:
- Walter will want a clean-room implementation
- There are no tests for this, at all

**Comment by Safety0ff** [comment]
I was planning to use my [C++ implementation & tests](https://github.com/Safety0ff/response_expand) as a starting point (created for LDC):

> This code does some weird backslash escaping stuff that might be hard to duplicate. I'm not sure it's actually valid on windows though. 

It was easier to write tests and re-discover the rules than read the existing code (IMO.)
IIRC, it deviates from the escaping described [here](https://blogs.msdn.com/b/oldnewthing/archive/2010/09/17/10063629.aspx?Redirected=true).
> - Walter will want a clean-room implementation

If he needs clean-room / chinese wall followed to the letter, then at least my tests can be of use.

**Comment by yebblies** [comment]
Oh you already have an implementation?  That's even better.  Can you re-license it under boost?

>  it deviates from the escaping described here.

It probably pre-dates those rules.  We should probably be following different rules on non-windows anyway.

> If he needs clean-room / chinese wall followed to the letter, then at least my tests might be of use.

I don't think to the letter is necessary, just reasonably believable.

**Comment by Safety0ff** [comment]
> Can you re-license it under boost?

Yes I will.

**Comment by yebblies** [comment]
Thanks!

**Pull request merged**
