### PR TITLE
ImportC: make static functions local

### PR DESCRIPTION
**Pull request by WalterBright**
This is a partial fix for https://issues.dlang.org/show_bug.cgi?id=22428

The code setting this is so complicated and spread out, I'm just doing this bit by bit.

### CODE REVIEW

**Comment by ibuclaw** [comment]
```
==============================
Test 'runnable/test22428.c' failed. The logged output:
/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/generated/osx/release/64/dmd -conf= -m64 -Irunnable  -fPIC  -odtest_results/runnable -oftest_results/runnable/test22428_0  runnable/test22428.c 
test_results/runnable/test22428_0  --DRT-testmode=run-main
==============================
Test 'runnable/test22428.c' failed: caught signal: -10
```

**Comment by WalterBright** [comment]
@ibuclaw I am looking at the fixups on OSX now, as it's the PIC code. I figure I was lucky it worked out of the box on everything else :-)

**Comment by ibuclaw** [comment]
@WalterBright yeah, my first thought was that maybe SCstatic has never been tested on Mach-O (or ELF, for that matter) because we simply don't have the concept of static in the C/C++ sense in D.

**Comment by WalterBright** [comment]
yup

**Comment by WalterBright** [comment]
@ibuclaw seems to be working on the Mac now.

**Comment by dkorpel** [comment]
> This is a partial fix for https://issues.dlang.org/show_bug.cgi?id=22428

Is it partial because it only fixes functions, or are there other limitations to this PR?

**Comment by WalterBright** [comment]
because it only does functions.

**Review by ibuclaw — APPROVED** [review]

**Comment by ljmf00** [comment]
> because it only does functions.

You can still mention the issue in the commit or manually cross-reference it in the Bugzilla issue without closing it.

**Comment by WalterBright** [comment]
semaphoreci has been stuck all day on:
```
4 more jobs in this build are waiting for available capacity…
```

**Comment by ibuclaw** [comment]
> semaphoreci has been stuck all day on:
> 
> ```
> 4 more jobs in this build are waiting for available capacity…
> ```

Something happened on one of the pipelines that made it stuck for over 48 hours.  That build has been cancelled, but there's still at least 3 hours of backlog to do.

**Pull request merged**
