### PR TITLE
CLI: Remove obsolete flag and all its warnings, undocument -wo flag

### PR DESCRIPTION
**Pull request by ibuclaw**
This has two changes that go hand-in-hand.

1. CLI: Remove obsolete flag and all its warnings, undocument -wo flag

Obsolete features have been put on hold until a DIP for "editions" has been drafted and ratified in the language spec.  Rather, these old features will just continue to be accepted without warning for now.

The DMD `-wo` command-line option will continue to be accepted without error, but it now does nothing, and is explicitly undocumented from `--help`.

2. Errors: Remove discrimation of different kinds of warnings

The different kinds of warnings that necessitated the need to differentiate between one command-line controlled option and another (i.e: GDC's diagnostic engine to distinguish between its equivalent `-Wall` and `-Wobsolete` options) will be quietly removed from the compiler.  The rationale being warnings are not part of the language specification.

@WalterBright

### CODE REVIEW

**Comment by thewilsonator** [comment]
Could you please split the revert of #15511 into a separate commit? it will make it much easier to see what is being changed here. Also do you mean a DIP for "editions"?

**Comment by ibuclaw** [comment]
> Also do you mean a DIP for "editions"?

Affect / Effect - what's the difference? :-)

I haven't seen any of this written down, though it did sound to me that everyone was saying the other word at dconf.

WRT this PR, I see it as transactional that reverting both what @WalterBright and I added be done in one. Merging one without the other means that gdc or dmd is in an undesirable state - would two commits suffice?

**Comment by ibuclaw** [comment]
> > Also do you mean a DIP for "editions"?
> 
> Affect / Effect - what's the difference? :-)
> 
> I haven't seen any of this written down, though it did sound to me that everyone was saying the other word at dconf.
> 

Looks like I wasn't [the only one](https://forum.dlang.org/post/uddg70$137g$1@digitalmars.com) who heard the former being spoken by everyone either.

**Comment by thewilsonator** [comment]
>  would two commits suffice?

Yes.

**Comment by RazvanN7** [comment]
cc @WalterBright

**Comment by ibuclaw** [comment]
Split into two commits.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
