### PR TITLE
Issue 14243 - mixin template scope inconsistency?

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14243

Expand template mixin members in statement scope to handle variable destructors.
An additional side effect, CTFE interpreter will be able to run the mixed-in statements.

### CODE REVIEW

**Comment by 9rnsr** [comment]
Based on: #4454.

**Comment by 9rnsr** [comment]
Added test case for [issue 10492](https://issues.dlang.org/show_bug.cgi?id=10492) so the root issue is same.

**Comment by yebblies** [comment]
This is making the DDMD conversion fail because `toStatement` needs to be added to the global list of members.  See [here](http://wiki.dlang.org/Updating_Pull_Requests_for_DDMD#Adding_a_new_global_type.2C_function_etc) for details, let me know if there are any problems.

**Comment by 9rnsr** [comment]
Updated for ddmd build.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
