### PR TITLE
ImportC: smoke test all C Standard .h files

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
When I click on `[View more details on Cirrus CI](https://cirrus-ci.com/task/5902496179159040)` I get a blank page for all the Ubuntu tests.

**Comment by WalterBright** [comment]
All the Cirrus CI test logs are blank pages.

**Comment by WalterBright** [comment]
The Ubuntu tests fail with a complaint about `_Float128` in `mathcalls-helper-functions.h`. This file does not exist on my Ubuntu machine. Can anyone with that file on the Linux box let me know the context of usage of that? I.e. what `#if` guard its use?

**Comment by dkorpel** [comment]
The file looks like this:
```
/* Classify given number.  */
__MATHDECL_ALIAS (int, __fpclassify,, (_Mdouble_ __value), fpclassify)
     __attribute__ ((__const__));

/* Test for negative number.  */
__MATHDECL_ALIAS (int, __signbit,, (_Mdouble_ __value), signbit)
     __attribute__ ((__const__));

/* Return 0 if VALUE is finite or NaN, +1 if it
   is +Infinity, -1 if it is -Infinity.  */
__MATHDECL_ALIAS (int, __isinf,, (_Mdouble_ __value), isinf)
  __attribute__ ((__const__));

/* Return nonzero if VALUE is finite and not NaN.  Used by isfinite macro.  */
__MATHDECL_ALIAS (int, __finite,, (_Mdouble_ __value), finite)
  __attribute__ ((__const__));

/* Return nonzero if VALUE is not a number.  */
__MATHDECL_ALIAS (int, __isnan,, (_Mdouble_ __value), isnan)
  __attribute__ ((__const__));

/* Test equality.  */
__MATHDECL_ALIAS (int, __iseqsig,, (_Mdouble_ __x, _Mdouble_ __y), iseqsig);

/* Test for signaling NaN.  */
__MATHDECL_ALIAS (int, __issignaling,, (_Mdouble_ __value), issignaling)
     __attribute__ ((__const__));
```
With the error on each `__attribute__` line. I need to find the context to make sense of it, it's not a standalone header file (which is probably why it's in the 'bits' folder).

**Comment by ibuclaw** [comment]
Smoke testing was already done here https://github.com/ibuclaw/importC

See this file for all `#define` hacks.
https://github.com/ibuclaw/importC/blob/main/src/keywords.c.in

**Comment by ibuclaw** [comment]
> > This file does not exist on my Ubuntu machine.
> 
> Looks like it comes from the ``libc6-dev`` package
> 
> https://packages.ubuntu.com/kinetic/amd64/libc6-dev/filelist
> 

I don't think that's the problem. ;-)

https://web.archive.org/web/20170522170658/http://packages.ubuntu.com/trusty/amd64/libc6-dev/filelist

**Comment by WalterBright** [comment]
I don't have the Xcode files on my Mac mini:
```
/private/var/folders/hy/gdmd645x1ws410vx266t7py00000gn/T/cirrus-ci-build/generated/osx/release/64/dmd -conf= -m64 -Icompilable  -fPIC  -odtest_results/compilable -oftest_results/compilable/stdcheaders_0.o  -c compilable/stdcheaders.c 
/Applications/Xcode-14.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/stdatomic.h(80): Error: type-specifier is missing
```
so I can't fix this. Anyone care to provide this line that ImportC fails to recognize?

**Comment by WalterBright** [comment]
This has uncovered too many issues for one PR, so I opted to just comment out the offending includes with a note on where they went wrong. It's too bad that each platform standard .h files fails to compile with a C11 compiler in one way or another. All look simple to fix, if only I could change those .h files. Sigh.

Anyhow, the only error hear is buildkite vibe.d failing to compile. Since vibe.d has nothing to do with ImportC, that failure is irrelevant to this PR. How did a failing vibe.d get into Master?

ping @dkorpel @RazvanN7 this s ready to go.

**Comment by WalterBright** [comment]
Confirmation that the buildkite failure is not related to this PR:

https://github.com/D-Programming-Deimos/openssl/pull/99#issuecomment-1436043144

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Buildkite failure has been fixed in the meantime (it was an openSSL configuration issue).

**Pull request merged**
