### PR TITLE
Add opSlice to root.Array so it can be used with foreach

### PR DESCRIPTION
**Pull request by yebblies**
@WalterBright

### CODE REVIEW

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Comment by denis-sh** [comment]
How is `foreach` connected with `opSlice`? Is it some undocumented language feature or what?

**Comment by yebblies** [comment]
Foreach will slice the aggregate if it's not a range, and doesn't support opApply.  The idea is that `myContainer[]` will give you the default range for that container.

**Comment by denis-sh** [comment]
So this is an undocumented language feature. Great. Any issues regarding this fact?

**Comment by 9rnsr** [comment]
https://github.com/9rnsr/dlang.org/commit/2759d7b021779328df3c23cea217f0fa025f9fd9

**Comment by denis-sh** [comment]
> 9rnsr/dlang.org@2759d7b

Thanks a lot, at least there will be docs soon.

**Pull request merged**
