### PR TITLE
fix Issue 15957 - Disabled postblit + template mixin break opAssign w…

### PR DESCRIPTION
**Pull request by WalterBright**
…ith confusing error message

https://issues.dlang.org/show_bug.cgi?id=15957

### CODE REVIEW

**Comment by andralex** [comment]
kewl

**Comment by andralex** [comment]
@CyberShadow guess you can fix this:

fatal error: error closing /tmp/ccR2LOva.s: No space left on device

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
There may be an autogenerated function I missed, but this should cover it.

**Pull request merged**
