### PR TITLE
improve memory layout of AliasDelaration

### PR DESCRIPTION
**Pull request by ghost**
Each instance wasted size_t.sizeof - 1 bytes because of a bool field not much used.
Use a derived class instead.

### CODE REVIEW

**Comment by JohanEngelen** [comment]
Note that this pessimizes member function calls for `AliasDeclaration` variables. E.g.
```d
AliasDeclaration ad = s.isAliasDeclaration();
ad.foo(); // can be devirtualized easily if AliasDeclaration is final.
```
The call to `foo()` is trivially devirtualized without this PR, but after this PR it cannot be devirtualized (without wholeprogram analysis).
Because this is about microoptimization, did you look at the impact of this besides the memory impact?

**Comment by welkam** [comment]
> Each instance wasted size_t.sizeof - 1
DMD allocates everything with 16 byte alignment
https://github.com/dlang/dmd/blob/master/src/dmd/root/rmem.d#L175-L176

**Comment by MoonlightSentinel** [comment]
Not sure about the current implementation. Couldn't `AliasDeclaration.wasTemplateParameter` be replaced by setting `STC.templateparameter` in `Declaration.storage_class`?

**Comment by NilsLankila** [comment]
Yes, good thing that this STC exists.

**Comment by andralex** [comment]
@NilsLankila @MoonlightSentinel is there a follow up plan? Wouldn't want this to fall by the wayside.

**Comment by NilsLankila** [comment]
Sorry. Here are explanations

1. I didn't know that 16 bytes was the size of small block.
2. I forgot about the **inherited members**, so when I've closed the idea was 2 small blocks are 32 bytes so 25 to 24 bytes doesn't change anything. But in reallity if there's a gain, that will be small (yeah b/c of those inherited members...)
3. latter however I wanted to check using `pragma(msg, __traits(getClassInstanceSize,...))` but that didn't print in the output...maybe a due to a problem with build.d

**Comment by MoonlightSentinel** [comment]
`build.d` usually doesn't show the output unless an error occurs to avoid cluttering (allthough you can override this behavoiur is subject to changes, see #11352).

Back to the point, removing the `bool` changes `classInstanceSize` from 209 to 208.

**Pull request closed without merging**
