### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by MartinNowak**
- Fix Issue 22121 - Segmentation fault in in dmd.dsymbol.ScopeDsymbol.addAccessiblePackage (#12864)
- fix Issue 22121: Tweak test to be friendly with gdc testsuite
- fix Issue 22122 - [REG 2.097][ICE] Segmentation fault in in dmd.access.hasPackageAccess
- Fix Issue 22118 - Const union causes false multiple-initialization error in constructor (#12875)
- Revert "Fix Issue 22118 - Const union causes false multiple-initialization error in constructor (#12875)"
- bump VERSION to v2.097.1

### CODE REVIEW

**Review by ibuclaw — DISMISSED** [review]
Hold up, am investigating another potentially critical regression.

**Comment by PetarKirov** [comment]
@ibuclaw what's the status, is there or not another regression? As a matter of process, we should not hold up `stable -> master` PRs, IMO. If there's an issue in stable, we can always merge stable again to master with the fix.

**Comment by ibuclaw** [comment]
#12897. Unfortunately 2.097.1 got released anyway. :-(

**Comment by ibuclaw** [comment]
But there should be some mechanism to halt stable releases for up to a week.

**Pull request merged**
