### PR TITLE
add whetstone benchmark to tests

### PR DESCRIPTION
**Pull request by WalterBright**
The test suite is a bit light on floating point tests. So I dug up the ancient whetstone benchmark. From the 1970's, no less!

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
Ok, I give up. What's happened to `TEST_OUTPUT` ?

**Comment by jacob-carlborg** [comment]
Why print out instead of using `assert`?

**Comment by WalterBright** [comment]
So TEST_OUTPUT has been removed from test/runnable ?

**Comment by Geod24** [comment]
> So TEST_OUTPUT has been removed from test/runnable ?

Was it ever part of it ? AFAICS `TEST_OUTPUT` only tests the output of compilation.
I suppose we could make that work by adding `-run` though ?

**Comment by WalterBright** [comment]
Since it never worked, I'll change it to using asserts.

**Comment by wilzbach** [comment]
TEST_OUTPUT ist only for the compilation and has always been like that. I have heard proposals of adding a similar RUN_OUTPUT or extending TEST_OUTPUT to listen to the run output too though a few times already. I personally prefer the second as it's more intuitive and avoids adding yet another variable to the testing tool.

**Pull request merged**
