### PR TITLE
Remove bitrotten unsupported compiler from make files.

### PR DESCRIPTION
**Pull request by ghost**
Was building a project and for some reason the error messages just weren't printing fully. They were always being cut off. I thought this was strange, not something that anyone will bother to look anyways. So I went to look at it and compiled DMD and it worked fine. Only difference being that I usually compile DMD with 32mscoff. But DMD for some reason still uses DMC to build the release version of DMD. A new release of DMC hasn't been released for **5 years**. The release from back then were also just minor changes, there hasn't been serious support in maintaining the project for far longer. Five years ago Windows 10 didn't exist. Can we please stop using unsupported bitrotten software ?

```D
void main() {

    static foreach(i ; 0 .. 1000) {
        pragma(msg, i);
    }

    static assert(0);
}
```

```
mk@DESKTOP MINGW64 ~/Desktop/fdmc
$ dmd -c main.d
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
2
m@DESKTOP MINGW64 ~/Desktop/fdmc
$
```

### CODE REVIEW

**Comment by WalterBright** [comment]
DMD is almost 100% in D now. Also, I use dmc and haven't noticed any issue with error messages.

**Comment by look-at-me** [comment]
It only happens in MingW64, it's fine in powershell and cmd but the scripts are written in bash..

DMC is part of the problem, optlink is the other part of the issue. Even if it is all written in D, which seems to be a lot more than when I last checked. Not sure where the issue lies, if it's in DMC's stdlib or something Optlink does, just know not using either of them fixes the problem and don't want to look any further into software that isn't supported anymore.

**Comment by JinShil** [comment]
> It only happens in MingW64, it's fine in powershell and cmd but the scripts are written in bash..

Which scripts are you talking about?  There has been an effort to convert these makefiles to a script written in D: https://github.com/dlang/dmd/blob/master/src/build.d  It's still a work in progress, but you can see some of the history here:  https://github.com/dlang/dmd/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+build.d  It would be most welcome to help move that forward, especially for building on Windows without Bash.

**Comment by rainers** [comment]
Reminds me of https://github.com/DigitalMars/dmc/pull/3

**Comment by WalterBright** [comment]
Sounds like it.

**Comment by look-at-me** [comment]
@WalterBright 
If I fix the conflicts will this be merged? I don't feel like wasting time otherwise.
This issue still exists in version 2.086 now, ~6 months later.

**Comment by wilzbach** [comment]
@look-at-me 

1) The DMD codebase now entirely consists of D files. No need for a C compiler anymore.
2) The Digitalmars runtime and the optlink still have a lot of known issues. However, dub already defaults to use MSCOFF for both 32- and 64-bit. I hope DMD will follow soon.
3) We are planning to get rid of these old makefiles. You should already be able to use new src/build.d and test/run.d - if not please report your issues e.g. on slack or Bugzilla.

I hope that helps.

**Comment by look-at-me** [comment]
This PR didn't just change the C compiler, it also compiled using MSCOFF for 32-bit. Which is the root of the issue.

> The Digitalmars runtime and the optlink still have a lot of known issues. However, dub already defaults to use MSCOFF for both 32- and 64-bit. I hope DMD will follow soon.

What exactly is stopping DMD from being built using MSCOFF today? I had it working 6 months ago with this PR.

**Comment by wilzbach** [comment]
> What exactly is stopping DMD from being built using MSCOFF today?

Nothing, the CIs have been testing this for years already.

**Comment by look-at-me** [comment]
Ok so then why isn't -m32mscoff used instead of -m32 for the build that is released?

**Comment by wilzbach** [comment]
For the same reason we don't use LDC to compile the release binaries which would make DMD twice as fast. No one dares to touch the release process. The dragon sits here: https://github.com/dlang/installer

**Comment by look-at-me** [comment]
Well that's always a good sign... Absolute paths with the user name in the path. So where is this machine that does the builds and who is responsible for it?

https://github.com/dlang/installer/blob/master/create_dmd_release/build_all.d#L335

**Comment by look-at-me** [comment]
@wilzbach 
This just changes the default to be 32mscoff now, the only change for the installer process is really just to ensure that the tools are installed, which they should be. There's no way for me to know for sure though cause the image used is hidden behind closed doors.

**Comment by wilzbach** [comment]
> So where is this machine that does the builds

It's a virtualbox image with Martin being the only one who has access to it. He posted instructions on how to replicate the image in a gist, but I don't think anyone has managed to do so.

> and who is responsible for it?

@MartinNowak

> There's no way for me to know for sure though cause the image used for the release build process is hidden behind closed doors

Well, Microsoft doesn't allow to publish virtualbox images, so that's the reason.

Though imho we should just use the Azure pipelines and upload the built binaries (we already build and test a 32 & 64-bit DMD mscoff executable there). LDC is pretty amazing in this regard as their release process is fully automated and they just need to push a git tag (or can use the GitHub UI).

**Comment by jacob-carlborg** [comment]
> Though imho we should just use the Azure pipelines and upload the built binaries (we already build and test a 32 & 64-bit DMD mscoff executable there). LDC is pretty amazing in this regard as their release process is fully automated and they just need to push a git tag (or can use the GitHub UI).

We have multiple repositories making this more complicated.

**Comment by rainers** [comment]
> Ok so then why isn't -m32mscoff used instead of -m32 for the build that is released?

Traditionally, the win32.mak files are for dmc/OMF builds only. When building with the Microsoft toolchain, use win64.mak and MODEL=32mscoff for 32-bit builds.
dmd doesn't have any C files anymore, so it doesn't really make a difference which makefile is used.

**Comment by rainers** [comment]
> Though imho we should just use the Azure pipelines and upload the built binaries

I guess the main obstacle is the signing the binaries and the installer.

**Comment by wilzbach** [comment]
> We have multiple repositories making this more complicated.

LDC has the same problem. We could just do what they do - upload the release binaries at the main repository (DMD).

> I guess the main obstacle is the signing the binaries and the installer.

Yes, this and FreeBSD not being available on normal CI providers (though that changed recently). However, the dlang-bot already has special key for signing binaries. It's a bit more complicated for Windows binaries as IIRC they can't be easily signed on non-Windows though I'm sure we would find a solution for this too or otherwise just manually sign them for every release (this is the status quo after all).

**Comment by jacob-carlborg** [comment]
> LDC has the same problem. We could just do what they do - upload the release binaries at the main repository (DMD).

It’s not what I’m referring to. They have the separate repositories included in the main one as as submodules. They need to create one tag. I’m guessing we need to create one for each repository.

**Comment by wilzbach** [comment]
> They need to create one tag. I’m guessing we need to create one for each repository. Which ideally should be done automatically.

It already is:

https://gist.github.com/MartinNowak/a471fe7ddbfeef205cdf04c93a94c6d0

**Comment by look-at-me** [comment]
You can do the signing and build the installer on Azure pipelines. Not sure about the other OSs though. Then the problem would just be grabbing the installers from the different CIs?

**Comment by wilzbach** [comment]
> You can do the signing and build the installer on Azure pipelines. 

Sure, but that would mean exposing the certificate to Azure/Microsoft. Far from ideal.

> Then the problem would just be grabbing the installers from the different CIs?

This isn't a problem - all of them have this functionality built-in.

**Pull request closed without merging**
