### PR TITLE
Fix issue 17096 - Check the number of arguments given to __trait

### PR DESCRIPTION
**Pull request by LemonBoy**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@LemonBoy may I suggest an alternative approuch ?
make dimError(uint expected) into dimError(uint expcted, uint actual);

**Review by andralex — APPROVED** [review]
LGTM, need @LemonBoy to rebase

**Comment by andralex** [comment]
BTW on some PRs I can fix conflicts by my own on the github website, why is this not available here?

**Comment by stefan-koch-sociomantic** [comment]
@andralex it seems @LemonBoy does no longer have a dmd repo.
I guess his patience has reached the limit.

**Comment by andralex** [comment]
@stefan-koch-sociomantic do you think you can adopt this PR?

**Comment by JinShil** [comment]
> @stefan-koch-sociomantic do you think you can adopt this PR?

@stefan-koch-sociomantic  I'll revive it, unless you really want it.

@andralex I think there are others in the PR queue that  could be revived.  If you find one, and are willing to review it in a timely manner, let me know and I'll revive it.

@LemonBoy Thanks for all the work you did in the DMD repository.  I'm sorry it wasn't considered a priority.  I'll try to keep at least some of it from being lost.

**Comment by andralex** [comment]
@JinShil go for it, thanks! That's a great offer. I'll look into others. cc @WalterBright @MartinNowak

**Comment by JinShil** [comment]
Revived at https://github.com/dlang/dmd/pull/7330  
cc @andralex

**Comment by stefan-koch-sociomantic** [comment]
@JinShil Thanks for taking it.

**Review by andralex — APPROVED** [review]

**Comment by JinShil** [comment]
#7330 was merged, so this can be closed.

**Comment by andralex** [comment]
@JinShil I think it's time to expand your responsibilities. I've invited you as an owner at Team Phobos.

**Pull request closed without merging**
