### PR TITLE
bitfields: add bitoffsetof, bitwidth, isBitfield

### PR DESCRIPTION
**Pull request by WalterBright**
Adds bitfield introspection capabilities as described:

https://github.com/WalterBright/documents/blob/master/bitfields.md

### CODE REVIEW

**Comment by rikkimax** [comment]
Awesome! Thanks for doing this, it'll be a real help.

That covers one of the major issues I outlined in my original post.

**Comment by LightBender** [comment]
@jmdavis This should address the introspection concerns and help you with your work on traits.

**Review by thewilsonator — COMMENTED** [review]
Needs a changelog entry

**Comment by WalterBright** [comment]
As for the "Needs Spec PR" there's a 2+ year old PR for bitfield documentation:

https://github.com/dlang/dlang.org/pull/3190

**Comment by thewilsonator** [comment]
You would still need to add those properties & trait to that PR

**Comment by thewilsonator** [comment]
@RazvanN7 why was this merged without a spec PR for the traits?

**Comment by RazvanN7** [comment]
@thewilsonator Walter has complained about this PR stalling other work. The bitfields DIP hasn't been accepted yet so it might be the case that all of this is reverted anyway. Once the DIP is accepted we can take care of the spec PR, or if it gets rejected then no harm was done.

I agree that the best approach here would have been to also have a spec PR, however, I took Walter's annoyance into account and decided to merge this as is.

**Pull request merged**
