### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Comment by andralex** [comment]
The win32 error is "rm: cannot remove ‘test_results/runnable/test44_2.exe’: Device or resource busy" and the Darwin error is in socket so probably a connectivity issue.

**Comment by andralex** [comment]
OK, tried the close/reopen trick that worked for nobody in the past :)

**Comment by andralex** [comment]
I'll force merge this, autotester failure seems unrelated. cc @braddr

**Comment by andralex** [comment]
oh never mind it's already in!

**Pull request merged**
