### PR TITLE
Move std.zip tests from dmd test suite to Phobos.

### PR DESCRIPTION
**Pull request by jmdavis**
The overload which took an integral value instead of the enum was
deprecated quite a while ago, but the test suite was never updated.

### CODE REVIEW

**Comment by yebblies** [comment]
The test suite should not be testing phobos... can this be moved into phobos unittests instead?

**Comment by jmdavis** [comment]
I have no clue why any of this is in the dmd test suite, but I can certainly look at moving these tests into Phobos.

**Comment by yebblies** [comment]
It's in the dmd test suite for historical reasons, and it would be great if you could move it.

**Comment by jmdavis** [comment]
Okay. I've changed this PR to remove the std.zip tests from the dmd test suite, and I've created a Phobos PR that ports them to std.zip itself:

https://github.com/D-Programming-Language/phobos/pull/3605

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
