### PR TITLE
[REG2.068.0-rc1] Issue 14871 - Linker errors with 2.068.0-rc1

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14871

Place module helpers in COMDAT sections again

This PR overrides the change in #4858.

### CODE REVIEW

**Comment by 9rnsr** [comment]
The breaking change in release candidate version has actually introduced complaint with the frustration.

**Comment by MartinNowak** [comment]
One problem with this approach is that it still has edge cases.
For example when you compile a few objects separately and put them in an archive (that's a makefile build mode, see [here](https://www.gnu.org/software/make/manual/html_node/Archive-Members.html)), the linker will pull a "random" object out of the archive. So it doesn't completely fix [Issue 14828](https://issues.dlang.org/show_bug.cgi?id=14828).
FWIW the only other valid fix is to emit those helpers into __every__ object file that uses them. That way there will never be undefined helper references. It means you'll have to change the multiobj pass to attach additional symbols to a function.

**Comment by 9rnsr** [comment]
Ah... I finally understand the issue that you concern. I didn't consider the situation to construct a library file from by collecting the generated object files by `dmd -c`, so I usually use only dmd.
Indeed the constructed library file will contain comdat module helpers randomly, then linker will pull random object files for them. The unstable behavior would be problematic.

> So it doesn't completely fix Issue 14828.

But the sentence is not still understandable to me. The comdat module helpers essentially won't cause duplicated symbols. Do you mean [issue 14748](https://issues.dlang.org/show_bug.cgi?id=14748) (unintentional binary size bloating)?

**Comment by 9rnsr** [comment]
@MartinNowak Could you please answer my question?

**Comment by 9rnsr** [comment]
@MartinNowak Ping. I'm waiting you in order to close this PR.

**Comment by WalterBright** [comment]
I'll close it.

**Pull request closed without merging**
