### PR TITLE
Fix Issue 17878 - Add __traits(isFuture, ...)

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by andralex** [comment]
cc @WalterBright @leandro-lucarella-sociomantic

**Review by andralex — APPROVED** [review]

**Comment by WalterBright** [comment]
Need spec pull, too.

**Comment by RazvanN7** [comment]
@WalterBright First, we should have get @future into the specs and then the isFuture trait.

**Comment by andralex** [comment]
I'll merge this and the spec pull, let me know if further additions are necessary.

**Comment by leandro-lucarella-sociomantic** [comment]
Please, always state that this is a supposedly hidden, experimental feature, and link to the DIP. It will confuse people if we start adding wrong docs.

**Pull request merged**
