### PR TITLE
optimization: recognize empty trailing statements

### PR DESCRIPTION
**Pull request by WalterBright**
A small one, but anything we can do to eliminate unnecessary try-catches is a win.

### CODE REVIEW

**Comment by Geod24** [comment]
Can you give some code sample in which this would kick in ? Also, any chance you could provide a test for it ?

**Comment by WalterBright** [comment]
The trigger for it is https://github.com/dlang/dmd/pull/8697/files#diff-53d6b4d266fad20ec997b3209808d37dR1283 where fbody is empty. I don't know of any other triggers for it at the moment. As with most optimizations, it's a little hard to write a test case for it.

**Comment by WalterBright** [comment]
Testing optimization transformations is an unresolved problem in the compiler.

**Comment by wilzbach** [comment]
> Testing optimization transformations is an unresolved problem in the compiler.

While it would be amazing to have an IR, there are test for the output assembly already, e.g.

https://github.com/dlang/dmd/blob/master/test/runnable/test_cdvecfill.d

**Comment by wilzbach** [comment]
> While it would be amazing to have an IR,

see also: https://github.com/dlang/dmd/pull/4972

**Comment by wilzbach** [comment]
Though the existing `-vcg-ast` switch might help too, but it currently will always create a separate file and there's no way to force it to output this directly on stdout (which would be nice as then the `TEST_OUTPUT` section could be used directly and no custom `POST_SCRIPT` would be required.)

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
