### PR TITLE
-allinst: Append *all* TemplateInstances to a root module for potential codegen

### PR DESCRIPTION
**Pull request by kinke**
This used to be done for `-unittest`.

### CODE REVIEW

**Comment by kinke** [comment]
Pinging @MoonlightSentinel. While this should be better than the status quo, it's still not enough for https://issues.dlang.org/show_bug.cgi?id=22374, i.e.,
```D
import std;
void main() { assert(0); }
```
still fails with `-allinst -checkaction=context`:
```
ld: error: undefined symbol: _D4core8internal7dassert__T14_d_assert_failTbZQtFNaNbNiNfMxAyaxbZAya
>>> referenced by test/compilable/test22374.d
>>>               test22374.o:(_D3std7variant__T8VariantNVmi32ZQp8toStringMFZAya)
```

Note that it's complaining about a missing `_d_assert_fail!bool` from https://github.com/dlang/phobos/blob/20a88cf6a7b8362d68f5278409717a64e3fb8f17/std/variant.d#L941; not the `_d_assert_fail!int` instantiated from the test module. Changing to `assert(false);` makes it link & run fine - with `-allinst`, otherwise fails to link as to be expected.

**Comment by MoonlightSentinel** [comment]
Thanks. The missing instance (`_d_assert_fail!bool`) is referenced by `immutable(char)[] std.variant.VariantN!(32uL).VariantN.toString()` - which probably originates from this line: 

https://github.com/dlang/phobos/blob/20a88cf6a7b8362d68f5278409717a64e3fb8f17/std/variant.d#L1735

Seems like `-allinst` decided that `VariantN!32` should be emitted but omitted `_d_assert_fail!bool` for unknown reasons - even though it is referenced by a template that needs codegen (not sure if this is intended).

**Comment by kinke** [comment]
Yep exactly. The example links at least with a `return true` (and disabled assertions in that function) here: https://github.com/dlang/dmd/blob/843ae86dc97e3e05f87d03687d1cd3d85d02cc4d/src/dmd/dtemplate.d#L6271

> Seems like -allinst decided that VariantN!32 should be emitted

I guess that's the real question. It doesn't make too much sense that it would be instantiated anywhere in the tiny root module.

**Comment by kinke** [comment]
CI with enforced `-allinst` is basically green, except for [compilable/issue19243.sh](https://github.com/dlang/dmd/blob/master/test/compilable/issue19243.sh) failing on macOS < 12 with some `dyld: initializer function 0x109967b20 not in mapped image for test_results/compilable/issue19243/liborig.dylib`. The 3 tiny files don't have or explicitly instantiate any templates...

So at the very least, this doesn't introduce any linking regressions when running the whole CI testsuite with `-allinst` and more emitted template instances.

**Review by ibuclaw — APPROVED** [review]

**Pull request merged**
