### PR TITLE
Fix Issue 23063 - It is possible to return a noreturn value

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Should this target stable?

**Comment by RazvanN7** [comment]
This currently blocks: https://github.com/dlang/dmd/pull/12898 which targets master.

**Comment by thewilsonator** [comment]
This still has a large number of CI failures.

**Comment by RazvanN7** [comment]
@thewilsonator should be good to go now.

**Comment by RazvanN7** [comment]
All errors seem to be spurious.

**Comment by thewilsonator** [comment]
Restarted failing C++ interop tests. Don't know how to restart the build kite vibe-d/tests failure.

**Comment by CyberShadow** [comment]
The test case in https://issues.dlang.org/show_bug.cgi?id=23364 compiled successfully before this pull request.

**Pull request merged**
