### PR TITLE
Fix issue 22163 - wrong code with static float array and delegate accessing it

### PR DESCRIPTION
**Pull request by dkorpel**
Reposting my analysis from bugzilla:

---
The delegate makes the parameter volatile in dmd/tocsym.d
```D
if (vd.nestedrefs.dim)
{
    /* Symbol is accessed by a nested function. Make sure
     * it is not put in a register, and that the optimizer
     * assumes it is modified across function calls and pointer
     * dereferences.
     */
    //printf("\tnested ref, not register\n");
    type_setcv(&t, t.Tty | mTYvolatile);
}
```

Then in dmd/backend/cod1.d:FuncParamRegs_alloc the float[2] is combined into the xmm0 register:

```D
if (tyaggregate(ty))
{
/* ... */
        else if (tybasic(t.Tty) == TYarray)
        {
            if (I64)
                argtypes(t, targ1, targ2);
        }
```

But in dmd/backend/cod3.d:prolog_loadparams this branch isn't taken:
```D
// This logic is same as FuncParamRegs_alloc function at src/dmd/backend/cod1.d
//
// Find suitable SROA based on the element type
// (Don't put volatile parameters in registers)
if (tyb == TYarray && !(t.Tty & mTYvolatile))
{
    type *targ1;
    argtypes(t, targ1, t2);
    if (targ1)
        t = targ1;
}
```
Which makes it load a `double` from xmm0 instead of a `float`. The comment "This logic is same as FuncParamRegs_alloc function" is no longer true, but I'm not certain what the fix is. I doubt `volatile` should affect the abi, but "Don't put volatile parameters in registers" was written for a reason so I don't want to remove that without consideration.

---

So in this PR I remove the check for `mTYvolatile` to see if something in the test suite breaks. If it passes, still be careful with merging: this could really use a review from someone who knows a thing or two about the backend, volatile and the Posix ABI.

### CODE REVIEW

**Comment by dkorpel** [comment]
Looks like this works on Posix, but the new test fails on Windows.

**Comment by dkorpel** [comment]
There is a separate branch for `config.exe == EX_WIN64` in cod1.d, so I now make cod3.d account for that. Test suit is green now. Still, could use a review from @WalterBright

**Comment by dkorpel** [comment]
@RazvanN7 this is a major bug, can you help move this forward? I think this patch is correct now.

**Review by RazvanN7 — APPROVED** [review]

**Comment by thewilsonator** [comment]
You might want to force merge this, that `macOS 12.x x64, DMD (latest)` looks stuck.

**Pull request merged**
