### PR TITLE
Fix Issue 19856 - [aApplycd2]: foreach (int) doesn't work on BigEndian targets

### PR DESCRIPTION
**Pull request by ibuclaw**
Bugzilla 16976 didn't go far enough in deprecating foreach(int, T; ...).

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Feel free to merge when green.

**Comment by ibuclaw** [comment]
Loosened the deprecation condition to continue allowing static arrays to not trigger, so long as they don't get lowered to `_aApply()`.

**Comment by ibuclaw** [comment]
Added a few more tests to hit 100% coverage.

**Comment by ibuclaw** [comment]
@thewilsonator - should be all green now.

**Pull request merged**
