### PR TITLE
fix compilation broken when using GCC 8.2.1

### PR DESCRIPTION
**Pull request by ghost**
Someone from IRC detected this. Most recent GCC version complains that the two functions has no return. This change is pretty much "meh" since the file will be ported to D but until this is done we still need to be able to compile DMD.

It's likely that the problem was not detected because CI services often use Ubuntu 14.04 LTS which comes with a gcc 4.x. Brad's autotester itself use an older 5.x version.

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]
Yeah this is really meh, but if it makes GCC happy :man_shrugging:

**Comment by thewilsonator** [comment]
Surely the Buildkite BlackEdder/ggplotd is spuirous? Its last commit was 11th Jul, and this PR is NFC.

**Comment by BBasile** [comment]
Ping, it's all green now.

**Review by jacob-carlborg — DISMISSED** [review]
I think this is the wrong solution. The DMD backend is using a custom `assert` defined in `tassert.h`. It should be defined so that the compiler recognized that the function/macro will never return, which then should not require a return statement. Have a look at the implementation for Clang:

https://github.com/dlang/dmd/blob/4a627b883c4185f74d13816d8d84c4b1c8daf38a/src/dmd/backend/tassert.h#L23-L31

**Pull request merged**
