### PR TITLE
Fix changelog entries for v2.091.0

### PR DESCRIPTION
**Pull request by Geod24**
@wilzbach : Is `stable` the right target at the moment ?

### CODE REVIEW

**Comment by PetarKirov** [comment]
@Geod24 yes, target stable for all fixes, especially those that need to be included before the next release (even when a beta release is already out).

**Review by wilzbach — APPROVED** [review]

**Comment by PetarKirov** [comment]
But I think you shouldn't have committed f9c4fa1 as now it will be removed from the changelog of 2.091.0 release. In general, changelogs are only purged on the master branch. For example:
https://github.com/dlang/dmd/pull/10776/commits/b100d09d09135ec6e91097fec8bcb1fa2bfbd429

**Comment by Geod24** [comment]
> But I think you shouldn't have committed f9c4fa1 as now it will be removed from the changelog of 2.091.0 release.

Yes that's the point. Originally it was [this PR](https://github.com/dlang/dmd/pull/10725) targeting master, but I was asked to bring it to stable, [so I did](https://github.com/dlang/dmd/pull/10760).
The changelog entry is part of [v2.090.1](https://dlang.org/changelog/2.090.1.html#d1-operator-deprecation)

**Comment by schveiguy** [comment]
I thought I had fixed that here: https://github.com/dlang/dlang.org/pull/2752

What did I do wrong?

**Comment by schveiguy** [comment]
Oh nevermind. This is for something different.

**Comment by Geod24** [comment]
The perils of copypasta...

**Pull request merged**
