### PR TITLE
[DDMD] Replace use of octal literals in the glue layer

### PR DESCRIPTION
**Pull request by yebblies**
Because D doesn't have these any more.

### CODE REVIEW

**Comment by schuetzm** [comment]
These are hard to read. Could you add a comment with the original octal form?

**Comment by yebblies** [comment]
I can't read the originals either, but sure.  Is there other readable format for these that isn't octal?

**Comment by yebblies** [comment]
Updated.

**Comment by schuetzm** [comment]
`sys/stat.h` has a bunch of constants:
http://man7.org/linux/man-pages/man2/stat.2.html

`0100644` would be `S_IFREG | S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH`. But that's verbose, and I've gotten so used to the octal notation, that it's easier to recognize for me.

Of course, for the comments, the symbolic format printed by `ls -l` is an option: `-rw-r--r--`

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Why do we use different file attributes on OSX?

**Comment by yebblies** [comment]
> Why do we use different file attributes on OSX?

Your guess is as good as mine.

**Pull request merged**
