### PR TITLE
Reduce indentation in TemplateDeclaration constructor

### PR DESCRIPTION
**Pull request by thewilsonator**
cc @Geod24

### CODE REVIEW

**Comment by Geod24** [comment]
Since `isAliasSeq` has a similar problem, can we also address it ?
Also as a commit / PR title, please use something that is not context-dependent.

**Comment by thewilsonator** [comment]
> Since isAliasSeq has a similar problem, can we also address it ?

What problems? IMO its much better than `isAlias` is. What do you have in mind.

> Also as a commit / PR title, please use something that is not context-dependent.

Sure.

**Comment by thewilsonator** [comment]
Done.

**Comment by Geod24** [comment]
> What do you have in mind.

Perhaps `isAliasSeqLike` ? I think it'd be better to have the same pattern for both, but unfortunately `isAliasLike` is too ambiguous.

**Comment by thewilsonator** [comment]
How about this?

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
