### PR TITLE
dmd.expressionsem: Make rewriteOpAssign private to this module

### PR DESCRIPTION
**Pull request by ibuclaw**
It isn't used from anywhere else.

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by ibuclaw** [comment]
I'll just trigger a rebuild for good luck.

**Comment by thewilsonator** [comment]
In future can I suggest to wait until your other auto-merge tagged PRs go through?

**Comment by ibuclaw** [comment]
> In future can I suggest to wait until your other auto-merge tagged PRs go through?

These were all notably sized patches, that were since shrank down to small/trivial patches, they can be collated now into one patch.

**Comment by thewilsonator** [comment]
I meant in terms of competing for CI resources.

**Comment by ibuclaw** [comment]
Yes, less PRs mean less competition. 😉

**Pull request merged**
