### PR TITLE
ImportC: initializers that are arrays of structs

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by ibuclaw — APPROVED** [review]
I hope you are also checking that this file is still compilable by a C compiler (the compilable/cstuff1.c file is not)

**Comment by WalterBright** [comment]
It does if compiled with `-std=c99` which seems a bit weird that isn't the default in 2021. ImportC is supposed to be C11, wouldn't it be strange if the test cases had to be C89? :-)

Also, line 153 fails to compile, because otherwise I can't test the change, due to https://github.com/dlang/dmd/pull/12704 not being pulled.

**Comment by ibuclaw** [comment]
> It does if compiled with `-std=c99` which seems a bit weird that isn't the default in 2021. ImportC is supposed to be C11, wouldn't it be strange if the test cases had to be C89? :-)
> 

You must be using a very old compiler then, as far as I can tell it's been C11 since gcc-5, and C17 since gcc-9. ;-)


> Also, line 153 fails to compile, because otherwise I can't test the change, due to #12704 not being pulled.

Yep, that's bad.

**Comment by PetarKirov** [comment]
> Also, line 153 fails to compile, because otherwise I can't test the change, due to #12704 not being pulled.

@WalterBright I've set #12704 to auto-merge.

**Pull request merged**
