### PR TITLE
Add ddoc support for 'Template Params' section

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
This section is parsed in the same way as the 'Params'
section, but expects the section to be preceeded with
the string 'Template_Params:'.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
See https://github.com/D-Programming-Language/dmd/pull/5071 as well

**Comment by nemanja-boric-sociomantic** [comment]
I'm adding tests, it seems that something is off when I have both `Params` and `Template_Params` in doc (parameter count mismatch).

**Comment by nemanja-boric-sociomantic** [comment]
Updated to check template & function parameters separately. Any advice how to make code less duplicated is appreciated!

**Comment by WalterBright** [comment]
I've just listed template parameters in the `Params:` section. There aren't going to be enough parameters for there to be any confusion about it. Also, keywords with _ in them just don't look good. (sorry!)

**Comment by nemanja-boric-sociomantic** [comment]
> Also, keywords with _ in them just don't look good. (sorry!)

I have no problems renaming it to `Template Params`. Originally @andrej-mitrovic-sociomantic made it `Template Params`, but renamed to `Template_Params` (akin to `See_also`) based on this comment https://github.com/D-Programming-Language/dmd/pull/5071#issuecomment-140166485

> Just a remark about the section name: Currently the specs doesn't mention it explicitly, but no section name includes whitespace (Think of "See_Also"). It wouldn't be a problem if all section name were fixed, but given we can have user-defined section. So I suggest Template_Params.

**Comment by AndrejMitrovic** [comment]
@WalterBright: Back when I last tried it, it wasn't possible to cleanly implement support for whitespace-delimited keywords. I opted for `Template_Params` instead. I guess we could call it `TemplateParams` instead though, I think we'd be ok with that.

**Comment by WalterBright** [comment]
Let's set aside the section name for the moment, and discuss why even have a separate section from `Params:`. As I wrote earlier, when I Ddoc a template function, I just include the template parameters in the `Params:` section.

**Comment by nemanja-boric-sociomantic** [comment]
Fair enough, I will close this not to spend more tester resources! Thanks!

**Pull request closed without merging**
