### PR TITLE
fix 22008 - Add the `.tupleof` property to `enum` declarations

### PR DESCRIPTION
**Pull request by ghost**
The following code

```d
foreach (e; __traits(allMembers, E))
{
    auto v = __traits(getMember, E, e);
}
```

can be more simply written

```d
foreach (v; E.tupleof) {}
```

This saves AST space, copies, time spent in semanticTraits with very few new dmd code.

### CODE REVIEW

**Comment by dkorpel** [comment]
Does this work with `static foreach` as well?

**Comment by TungstenHeart** [comment]
yes, will I'll add that to the test

**Review by Geod24 — CHANGES_REQUESTED** [review]
I don't think that's a good idea. This introduce a special case that seems like a good idea, but special cases are never a good idea. Next thing you know, someone wants it to work with `struct` as well. Or someone opens a bug report because their `static opApply` suddenly isn't called anymore.

**Comment by thewilsonator** [comment]
Yeah, structs have `.tupleof`, maybe add that instead?

**Comment by MoonlightSentinel** [comment]
> Yeah, structs have `.tupleof`, maybe add that instead?

That would also enable other cases where you want to get a list of all members, e.g. `const members = [ E.tupleof ];`

**Comment by TungstenHeart** [comment]
let's go for `.tupleof` then

**Comment by TungstenHeart** [comment]
However the `.tupleof` solution is a breaking change. Should `.tupleof` as a member name be deprecated for one year ? Not great.

**Comment by thewilsonator** [comment]
`.tupleof` is a keyword (or at the very least a reserved member, a la `.sizeof`) though isn't it?

**Comment by Geod24** [comment]
@TungstenHeart : What's the aim of this change though ? I looked at the issue and it say that it "could be", but that's no justification. What's the advantage of adding another way to do the same thing as `__traits(allMember)` ? Does it enable generic code to be neater ? Does it allow things that are currently not possible, or does it have a different semantic ?

While I'm not outright opposed to the `tupleof` (as opposed to the original `foreach` one), I do question whether it makes sense.

**Comment by TungstenHeart** [comment]
You misunderstand the "could". It **is** sematically equivalent but takes a shorter path. From the example given in the changelog entry it's pretty clear that looping the enum members for now requires _absurd_ code to be written.

This _absurd_ code can be hidden using `std.traits.EnumMembers` however. 
But, bonus, the _absurd_ code hidden in`EnumMember` implementation can also be rewritten as 

```d
template EnumMembers(E)
if (is(E == enum))   
{   
    alias EnumMembers = E.tupleof;
}
```

It's doubly verified, all the `EnumMembers` unittests pass using the new `.tupleof`.

**Comment by TungstenHeart** [comment]
> `.tupleof` is a keyword (or at the very least a reserved member, a la `.sizeof`) though isn't it?

technically this is called a "soft keyword", so yeah thanks to that deprecation would not be required.

**Comment by TungstenHeart** [comment]
@andralex, what do you think about that change ? The code for the `EnumMembers` template could be drastically simplified.
The members already exist, almost ready to be used, in the declaration. `EnumMembers` was [added by @SinFu](https://github.com/dlang/phobos/commit/7a003d8cff486b73751e99d58cd4221e38424703) but has grown into something absurd since it basically rebuilds information (using `mixin`, `__traits`, `template`) that is, once again, already available in the compiler without using metaprog (it just requires a TupleDecl).

**Comment by TungstenHeart** [comment]
In a way, `EnumMembers` is a "cargocult" template. The stuff is there ! why mixing strings to reproduce it ?

**Comment by ibuclaw** [comment]
> While I'm not outright opposed to the `tupleof` (as opposed to the original `foreach` one), I do question whether it makes sense.

Indeed.  As enums are part of the user-defined type family, I would agree that adding `.tupleof` would - on the surface - seem to be plugging one found gap to make enums consistent with other user-defined types.

Though the usage difference is actually in stark contrast to each other.
```
struct S { int a, b; }
enum E : int { a, b }

S.tupleof;    // error, need 'this' to access 
svar.tupleof; // returns tuple(svar.a, svar.b)
E.tupleof;    // returns tuple(E.a, E.b)
evar.tupleof; // error, no property for 'int'
```

**Comment by andralex** [comment]
The original code of `EnumTemplate` is [indeed odd](https://github.com/dlang/phobos/blob/v2.097.0/std/traits.d#L4184). 

>In a way, EnumMembers is a "cargocult" template.

I don't think "cargo cult" is fit here. Cargo cult applies to ignorant, simplistic, rudimentary adaptations of complex technology. That said, clearly it's some awkward code.

This PR plays into a trend that @WalterBright also perpetuates and goes like this:

* Some introspection code is possible but difficult.
* Wait, we can hack that easier into the compiler. Let's do it!

At the end of the process we learned nothing. There's no real progress in terms of making the language more expressive, there are no new primitives helping general introspection cases, just yet another finger in yet another hole. This is not how a language should evolve.

The real questions raised by the current implementation are:

* Why in the world the author of the code did not add any comments as to why this or that artifact is needed? This is almost offensive. Hopefully it wasn't me :o).
* What is wrong with `__traits(allMembers, E)`? Should that be fixed instead?
* Should `WithIdentifier` be made a compiler primitive that could help other cases as well?
* Would `EnumSpecificMembers` be simplified/obviated by alias assignment? Looks like a frequent pattern.

**Comment by MoonlightSentinel** [comment]
The underlying problem seems to be that `__traits(allMembers, E)` returns a list of identifiers. That makes it rather awkward to use for code that wants a list of symbols. You can probably build the list by using AliasAssign but that's is cumbersome as well.

Another random idea:
Let `__traits(getMember, ...)` accept a list of identifiers (instead of only one) and return a tuple of all specified members.

```d
alias EnumMembers(E) = __traits(getMember, E, __traits(allMembers, E));
```

**Comment by TungstenHeart** [comment]
>```d  
> alias EnumMembers(E) = __traits(getMember, E, __traits(allMembers, E));   
> ```   

This is not as good as `.tupleof` because that alternative
1. requires to change `__traits(getMember)`, so that it accepts a tuple of string as last argument
2. sounds odd because `getMember` is singular
3. requires to check each individual string given by the last `getMember` argument (that means slower than `tupleof`).

Then if the idea is to only accept `__traits(allMember)` as last `getMember` argument, e.g not any random `AliasSeq` of strings, then it is even worst. Because a special case.

`.tupleof`. is an already existing type property, it will be hard to beat in term of simplicity. Just look at the diff, 3 lines of new DMD code.

**Comment by MoonlightSentinel** [comment]
> 1. requires to change `__traits(getMember)`, so that it accepts a tuple of string as last argument

Which would simply change the error path to build a tuple instead.

> 2. sounds odd because `getMember` is singular

I don't think that it will cause noticeable confusion.

> 3. requires to check each individual string given by the last `getMember` argument (that means slower than `tupleof`).

True, but it will also be useful for many other situations - not just `EnumMembers`. This idea was mostly intended to address Andrea's concerns that `.tupleof` this is too specialised and might indicate insufficient building blocks for introspection.

> Then if the idea is to only accept `__traits(allMember)` as last `getMember` argument, e.g not any random `AliasSeq` of strings, then it is even worst. Because a special case.

Of course not, it should also accept `__traits(getMember, Foo, "bar", baz")`.

> `.tupleof`. is an already existing type property, it will be hard to beat in term of simplicity. Just look at the diff, 3 lines of new DMD code.

Except that it has a different meaning for the other types, as [this answer](https://github.com/dlang/dmd/pull/12650#issuecomment-858518136)  fortunately pointed out .

**Comment by RazvanN7** [comment]
The creator of this PR not longer exists in Github form and this PR is linked to the bugzilla issue. Closing...

**Pull request closed without merging**
