### PR TITLE
remove helper functions for assert and unittest

### PR DESCRIPTION
**Pull request by WalterBright**
This:

1. removes the always-generated assert and unittest helper functions
2. replaces them with direct calls
3. replaces file argument with moduleinfo pointer

This makes using `assert` and `unittest` more pay-as-you-go, which can result in more code generated (though not more code executed). Of course, the extra code doesn't matter for `unittest` asserts.

Undone is the array bounds check, which I'll do if this goes through.

### CODE REVIEW

**Comment by WalterBright** [comment]
This isn't ready yet.

**Comment by MartinNowak** [comment]
> 2. replaces them with direct calls

Direct calls to [_d_unittest*](https://github.com/dlang/druntime/blob/2db828bd4f21807254b770b3ec304f14596a9805/src/core/exception.d#L641) and [_d_assert*](https://github.com/dlang/druntime/blob/2db828bd4f21807254b770b3ec304f14596a9805/src/core/exception.d#L624) you mean.

> 3. replaces file argument with moduleinfo pointer

Why? We have several known issues/drawbacks w/ dragged in ModuleInfos. Are you trying to avoid redundant strings? I think linkers already deduplicate strings.
If you don't trust those, moving the module name to it's own symbol might be an alternative.

**Comment by WalterBright** [comment]
I changed the ModuleInfo pointer to a simple char* for the filename. This eliminates dependency on ModuleInfo, and eliminates problems with accessing the internal functions in shared libraries.

But it is blocked by https://github.com/dlang/druntime/pull/1761

**Comment by andralex** [comment]
This is a welcome simplification.

**Comment by WalterBright** [comment]
@andralex ready to go!

**Comment by MartinNowak** [comment]
What about array bounds checks?

**Comment by UplinkCoder** [comment]
This causes my test-setup to fail :(

**Pull request merged**
