### PR TITLE
replace construct-copy with a construct directly into target

### PR DESCRIPTION
**Pull request by WalterBright**
This is another case of https://issues.dlang.org/show_bug.cgi?id=17457

### CODE REVIEW

**Comment by WalterBright** [comment]
Closely related:
https://github.com/dlang/dmd/pull/6849
https://github.com/dlang/dmd/pull/6847

**Comment by mathias-lang-sociomantic** [comment]
No test ?

**Comment by WalterBright** [comment]
It's implicitly tested by all the use cases already out there. I do have a more specific test case, but it requires all three of the PRs to be pulled first. I still want the PRs to be separate, however, in case one of them breaks something.

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=17632

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=17622

**Pull request merged**
