### PR TITLE
Reject AUTO_UPDATE for TEST_OUTPUT's with special sequences

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Don't overwrite special sequences like `$n$`.

### CODE REVIEW

**Review by ibuclaw — APPROVED** [review]
:+1:

**Review by wilzbach — APPROVED** [review]
Thanks!

**Comment by Geod24** [comment]
Two things:
- Special sequences are likely to get out of sync. However, I don't think `$` ever happens in the output. Can we simply use this ?
- Any chance we could just update the line number of the message, if it matches `\d` ? It's the common case by a large margin.

**Comment by wilzbach** [comment]
> Special sequences are likely to get out of sync. However, I don't think $ ever happens in the output. Can we simply use this ?

How so? The testsuite should still be run and won't pass if these tests aren't manually updated (if required).

**Comment by Geod24** [comment]
> How so? The testsuite should still be run and won't pass if these tests aren't manually updated (if required).

I meant that we should just look for `$` in the output. But now I realize we have `opDollar` so ignore my previous comment...

**Pull request merged**
