### PR TITLE
Print the inference error trace for regular inference errors

### PR DESCRIPTION
**Pull request by Geod24**
EDIT: Previous test was using the release and not master, so triming down to useful commits only.

### CODE REVIEW

**Comment by dkorpel** [comment]
> we already do it for safe inference, but not in the general case, which this does

That's not entirely accurate, most of the safe errors (something like 60 out of 65) are covered. There's a few remaining cases where the enhanced inference error doesn't work:
- a `@system` function pointer/delegate is called
- a function is inferred `@system` not because a specific error, but because a circular inference dependency being resolved conservatively
- a `@system` copy constructor is called
- the address of a local variable is taken without dip1000

It's usually because the error message doesn't fit in the `setUnsafe` / `AttributeViolation` signature, which supports up to 3 `RootObjects` for `%s` specifiers in the message string. The problem with the last case (which this PR addresses) is:
```
const(char)* p = v.isParameter() ? "parameter" : "local";
```
Which is not a RootObject. Possible solutions are: 
- put `p` in an `Identifier` object
- lose the distinction in the error message an just call it "variable"
- What this PR does: falling back on a new "Expression `%s` is not `@safe`" case for the inference error.

I don't think this new fallback case is needed, you can just fit the message into `setUnsafe` and set the `gag` parameter to `true` so you can print the more detailed error when the function returns `true`:

```D
if (setUnsafe(true, orig.loc, "expression %s is not `@safe`", orig))
{
    exp.error("cannot take address of %s `%s` in `@safe` function `%s`", p, v.toChars(), sc.func.toChars());
    return false;
}
```

**Comment by Geod24** [comment]
> That's not entirely accurate, most of the safe errors (something like 60 out of 65) are covered. There's a few remaining cases where the enhanced inference error doesn't work:

Right, that message needed some rewording. I meant to talk about "the most common type of error", which is calling a `@system` function (including inferred system).

> It's usually because the error message doesn't fit [...]

Actually I would like to try another approach in the future: To have the context specify that it expects a `@safe` function, and error if it isn't. In the case of already-analyzed instances, we'd need to re-run semantic to find out why it isn't of a certain attribute.

> and set the `gag` parameter to `true`

AFAIU that's not possible because at this point we do not know what the caller want (`@safe` or not).

**Comment by dkorpel** [comment]
> > and set the `gag` parameter to `true`
> 
> AFAIU that's not possible because at this point we do not know what the caller want (`@safe` or not).

`setUnsafe` currently doesn't look at "what the caller wants". It does look whether the function is explicitly marked `@safe`, in which case it prints the error directly and returns `true`, but you can surpress it with the `gag` parameter and print something yourself in the `true` branch.

**Comment by Geod24** [comment]
@dkorpel : I'm not sure I follow. The problem appears when a `@safe` function calls a templated function, which itself might call other functions, and end up doing something `@system`. In that case, the compiler cannot / should not issue an error when doing semantic analysis of the terminal function (the one doing something `@system`) because, as far as the compiler knows, it is just inferring attributes for the templates. Only the caller will later reckon that this is an error, and print the `Expression` that has been stored.

**Comment by dkorpel** [comment]
> Only the caller will later reckon that this is an error, and print the `Expression` that has been stored.

How does that relate back to 'AFAIU setting the gag parameter to true is not possible'? For reference, I'm suggesting:
```
if (setUnsafe(/*gag*/ true, orig.loc, "deferred error message: %s", exp))
{
    exp.error("direct error message: %s", exp.toChars());
    return false;
}
```
In the case you describe, it will print "deferred error message" with the stored expression.

**Comment by Geod24** [comment]
Trimmed down after a talk with @dkorpel

**Comment by Geod24** [comment]
Rebased

**Review by dkorpel — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
