### PR TITLE
At least GNU make 4.1 on Linux Mint introduces a space in a variable …

### PR DESCRIPTION
**Pull request by andralex**
…definition followed by a space then a comment

### CODE REVIEW

**Comment by wilzbach** [comment]
See this comment for reference & explanation https://github.com/dlang/dmd/pull/6022#issuecomment-238328228

> https://github.com/dlang/dmd/pull/6052 also fixes a typo, could you please pull it and close the other :o). -- Andrei

For obvious reasons I don't have merge rights here, but I am pretty sure that someone else will quickly pull this as well.

**Comment by andralex** [comment]
@wilzbach sent you an invite

**Comment by wilzbach** [comment]
> @wilzbach sent you an invite

thanks a lot, but it seems AutoTester doesn't like me & you need to wait:

image

**Comment by andralex** [comment]
I'll irregularly pull this in the interest of speed, I assume you'd have done the same and do not contest the pull.

**Comment by wilzbach** [comment]
> I'll irregularly pull this in the interest of speed, I assume you'd have done the same and do not contest the pull.

Yep ;-)

> Your tests failed on CircleCI

that's unrelated and we seem to hit the rate-limit of the API again. I think there's a simple fix for it though

```
++ curl -fsSL https://api.github.com/repos/dlang/dmd/pulls/6052
++ jq -r .base.ref
curl: (22) The requested URL returned error: 403
```

**Pull request merged**
