### PR TITLE
use inline assembler rather than hand-assembling test cases

### PR DESCRIPTION
**Pull request by WalterBright**
Hand assembling the code makes little sense when dmd has an inline assembler. Just trying it out for one case.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by wilzbach — CHANGES_REQUESTED** [review]
You'll break the auto-update with this!

**Comment by WalterBright** [comment]
> You'll break the auto-update with this!

How so? It passes the test suite with flying colors. And having had the recent misfortune of having to update all those hand-assembled tests till my eyes bled, a better way was needed.

**Comment by WalterBright** [comment]
@wilzbach please explain.

**Comment by Geod24** [comment]
> How so? It passes the test suite with flying colors. And having had the recent misfortune of having to update all those hand-assembled tests till my eyes bled, a better way was needed.

Well the tests scripts have the ability to do that update for you, instead of doing it manually.
https://github.com/dlang/dmd/blob/00299e3b6ca9dcd5a5dc8bd50280b63d0bdc51f9/test/README.md#automatically-update-the-test_output-segments

**Comment by ZombineDev** [comment]
@WalterBright see: https://github.com/dlang/dmd/pull/7003/commits/0d92c02af25e32e73dfa44089c32988733201987#diff-6ae615a8fd4d30180e88171bfcffb97bR9.

**Comment by WalterBright** [comment]
@ZombineDev that is indeed a clever solution.

**Pull request closed without merging**
