### PR TITLE
Fix: rm: cannot remove ‘test_results/runnable/test17968.exe’: Device or resource busy

### PR DESCRIPTION
**Pull request by wilzbach**
This spurious error seems to occur very often on win32, see e.g. https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=3469860&isPull=true

This is rather dirty fix, but considering that we don't really care about whether this binary is removed immediately as it will either be removed with a `clean` action, by a new CI checkout or simply overwritten locally, but we do care about the auto-tester failing spuriously.

### CODE REVIEW

**Comment by ZombineDev** [comment]
Do we really need to delete the file? I guess it would cleaner to simply remove the `rm` lines if it's not strictly necessary.

**Comment by thewilsonator** [comment]
Usually these kind of things result in an error when running git to check if things are dirty.

**Comment by wilzbach** [comment]
> Usually these kind of things result in an error when running git to check if things are dirty.

Nope as the entire test_results folder is git-ignored.

**Comment by wilzbach** [comment]
> Do we really need to delete the file?

Well, not really, but it works perfectly fine on posix :shrug:

**Review by thewilsonator — APPROVED** [review]

**Comment by wilzbach** [comment]
> If it's not necessary, then I think it's going to confuse less people in the future if we simply delete the line.

Done.

**Comment by thewilsonator** [comment]
Auto-merge toggled on

**Pull request merged**
