### PR TITLE
Add Tint128/Tuns128 to impcvgen.

### PR DESCRIPTION
**Pull request by redstar**
Adds the missing conversion rules for type cent/ucent.

### CODE REVIEW

**Comment by ibuclaw** [comment]
@redstar does this allow backend use if one wishes to implement it?

**Comment by ibuclaw** [comment]
LTGM.

**Comment by yebblies** [comment]
Still needs lots of frontend support I think.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by redstar** [comment]
Yes, it can be used to implement cent/ucent. And yes, it requires frontend support.
See https://github.com/ldc-developers/ldc/pull/891.

**Pull request merged**
