### PR TITLE
make VarArg a ubyte

### PR DESCRIPTION
**Pull request by WalterBright**
Pack things better.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Silly question: why do we have two definitions of the same thing?

Also cc @kinke I seem to remember this kind of thing causing problems.

**Comment by WalterBright** [comment]
Actually it is a very good question. I don't have a good answer.

**Comment by UplinkCoder** [comment]
Wastage shrunk from 30 bits to 6 bits. that's nice.
There are a few things in `FuncDeclaratio`n which could be flags instead.

**Comment by thewilsonator** [comment]
Ah, thats astbase thats why. cc @RazvanN7 you probably know more.

**Comment by kinke** [comment]
I never understood what astbase.d is used for; LDC doesn't include it.

**Comment by thewilsonator** [comment]
DMD as a Library.

**Comment by ibuclaw** [comment]
Yearly reminder that gdc has been using dmd as a library since 2004, and I still have no idea what it is for, even less with @thewilsonator 's explanation. :-)

**Comment by WalterBright** [comment]
@ibuclaw I am having a hard time finding the cause of this error:
```
/media/disk1/braddr/sandbox/at-client/pull-4040183-Linux_32/dmd/generated/linux/release/32/cxxfrontend.o: In function `test_types()':
```
where it is complaining that TypeFunction::create() doesn't match. Is there some other declaration of VarArg that needs changing?

**Comment by WalterBright** [comment]
@ibuclaw never mind.

Who'd have thought such a trivial change would cause trouble?

**Comment by ibuclaw** [comment]
> @ibuclaw I am having a hard time finding the cause of this error:
> 
> ```
> /media/disk1/braddr/sandbox/at-client/pull-4040183-Linux_32/dmd/generated/linux/release/32/cxxfrontend.o: In function `test_types()':
> ```
> 
> where it is complaining that TypeFunction::create() doesn't match. Is there some other declaration of VarArg that needs changing?

D mangles the symbol as:
```
_ZN12TypeFunction6createEP5ArrayIP9ParameterEP4Type6VarArg4LINKm
```

C++ mangles the symbol as:
```
_ZN12TypeFunction6createEP5ArrayIP9ParameterEP4Typeh4LINKm
```

This PR changes the way C++ mangles the symbol from `6VarArg` to `h`.  So the `create` function needs to have its parameter updated to `ubyte` on the D side as well.

**Comment by WalterBright** [comment]
@ibuclaw thanks!

**Comment by ibuclaw** [comment]
@Geod24 just triggered a rerun of the github actions pipeline and there are different success/failures. It could be we are being rate limited due to connection count to llvms servers.

**Review by ibuclaw — APPROVED** [review]

**Comment by Geod24** [comment]
> @Geod24 just triggered a rerun of the github actions pipeline and there are different success/failures. It could be we are being rate limited due to connection count to llvms servers.

Well those downloads are cached. It seems to be a problem on LLVM's side.

**Comment by Geod24** [comment]
> Well those downloads are cached. It seems to be a problem on LLVM's side.

Ah, well, re-triggering a run means the cache is never used... Because [of a Github issue](https://github.com/actions/cache/issues/208#issuecomment-607877125).

**Pull request merged**
