### PR TITLE
fix Issue 23075 - global const string definitions should go in readon…

### PR DESCRIPTION
**Pull request by WalterBright**
…ly segment

### CODE REVIEW

**Comment by ljmf00** [comment]
Are those two bugs interdependent? They don't seem to be. If no, please do separate PRs.

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
Separate PRs for the 2 bugs.

**Comment by WalterBright** [comment]
The fix for 23045 has already been merged. https://github.com/dlang/dmd/pull/14024 I don't know why this PR seems to have acquired parts of it. But it doesn't really matter.

**Comment by ljmf00** [comment]
> The fix for 23045 has already been merged. #14024 I don't know why this PR seems to have acquired parts of it. But it doesn't really matter.

It matters, as merging it into stable will bring a non-regression fix to stable versions that can actually be unstable. Please rebase it against stable and drop the commit.

You can do it interactively with `git rebase -i origin/stable` being `origin` the upstream remote and mark that commit `drop` instead of `pick`.

**Comment by WalterBright** [comment]
This inadvertent merge with another PR seems to have come about when it was rebased to stable.

**Comment by RazvanN7** [comment]
@WalterBright I fixed the rebasing issue. Is there any way we can test this?

**Comment by WalterBright** [comment]
> Is there any way we can test this?

Not in a straightforward way. We don't have any tests for the object file contents, other than does the program run.

**Comment by WalterBright** [comment]
> We should translate the testsuite to FileCheck. Although, you can add a dshell test and filter the objdump result.

I've tried comparing object files before. They turn out to be very brittle. They're a lot of busywork to maintain. Multiply that by the 7 object file formats supported, and it isn't worth it.

**Review by RazvanN7 — APPROVED** [review]

**Comment by ljmf00** [comment]
> > We should translate the testsuite to FileCheck. Although, you can add a dshell test and filter the objdump result.
> 
> I've tried comparing object files before. They turn out to be very brittle. They're a lot of busywork to maintain. Multiply that by the 7 object file formats supported, and it isn't worth it.

It's not brittle. See how `llvm` does object tests: https://github.com/llvm/llvm-project/blob/f44552ab387b9087fb815251064782f8fb60e643/llvm/test/Object/Mips/objdump-micro-mips.test . It uses `FileCheck`.

**Pull request merged**
