### PR TITLE
dtoh: Don't assert when handling complex and imaginary types

### PR DESCRIPTION
**Pull request by ibuclaw**
Written rather hastily, missing tests, needs to be checked for other cases that need special handling.

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
Shouldn't this use [`_Complex`](https://en.cppreference.com/w/c/language/arithmetic_types#Complex_floating_types) instead of `__complex__`? The latter seems to be an [old GNU extension](https://gcc.gnu.org/onlinedocs/gcc/Complex.html).

**Comment by ibuclaw** [comment]
@MoonlightSentinel yes, I only looked quickly at what libstdc++ std::complex was doing for its `__rep()` implementation and lifted what was there.

**Comment by MoonlightSentinel** [comment]
@ibuclaw Added some docs + tests and fixed some remaining issues:
- imaginary types in nested types (e.g. `ifloat*`)
- segfault for templates

**Comment by MoonlightSentinel** [comment]
> dtoh.d:536:18: error: no property 'Treference' for type 'ASTCodegen', did you mean 'Treference'?

An old frontend / GDC bug?

**Comment by ibuclaw** [comment]
> > dtoh.d:536:18: error: no property 'Treference' for type 'ASTCodegen', did you mean 'Treference'?
> 
> An old frontend / GDC bug?

Just put an alias in astcodegen.d

**Comment by MoonlightSentinel** [comment]
Thanks, that worked

**Comment by thewilsonator** [comment]
this is green now, is it good to go?

**Comment by WalterBright** [comment]
> this is green now, is it good to go?

Not when it says "This pull request is still a work in progress".

**Comment by MoonlightSentinel** [comment]
Marked as ready for review (unless @ibuclaw has has some objections)

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
