### PR TITLE
refactor: use union in StringExp

### PR DESCRIPTION
**Pull request by WalterBright**
Using a union makes things a little clearer what is happening.

### CODE REVIEW

**Comment by andralex** [comment]
nice work... wondering when dmd will be all `@safe` :)

**Comment by andralex** [comment]
@MartinNowak what's the matter with travis-ci?

**Comment by andralex** [comment]
core.exception.AssertError@expression.d(4534): Assertion failure

**Comment by WalterBright** [comment]
@klickverbot any ideas on the ldc failure?

**Comment by WalterBright** [comment]
Line 4201 of expression.d is likely the problem. Looks like LDC doesn't statically initialize things correctly if there's a union. Will post a workaround to see.

**Comment by WalterBright** [comment]
It's the advantage of having smaller PRs - going through the line by line changes, the union was the only thing unusual, so looks like I guessed right.

**Comment by WalterBright** [comment]
So how about an automerge?

**Comment by WalterBright** [comment]
I added an LDC issue for it: https://github.com/ldc-developers/ldc/issues/1286

**Comment by WalterBright** [comment]
thanks!

**Comment by andralex** [comment]
@WalterBright @klickverbot nice work you guys

**Pull request merged**
