### PR TITLE
Remove form-feed characters from backend source

### PR DESCRIPTION
**Pull request by yebblies**
I assume these are here to improve printing the code out.  I also assume they haven't been maintained over the years as the code changed.  They sometimes cause problems for some tools that don't handle them correctly.

@WalterBright Can they be removed?  Does anyone actually print out source code any more?

### CODE REVIEW

**Comment by MartinNowak** [comment]
I read that emacs and vi use those for page up/down. What tools have problems with this?

**Comment by yebblies** [comment]
Tools that assume they're working on utf-8.  If they're still being used then we should leave them in, but I'm not sure they are...

**Comment by MartinNowak** [comment]
Never used it, but indeed emacs has functions to navigate those.
Also form-feed is a valid UTF-8 character. Let's see whether @WalterBright still uses them.

**Comment by yebblies** [comment]
That makes more sense than printing.  @WalterBright Please close this if they're something you still use.

> Also form-feed is a valid UTF-8 character.

Hmm it's possible that's not where the error is coming from then.

**Comment by WalterBright** [comment]
They were put in originally when I'd print listings. That hasn't been practical for decades now. I'm surprised, though, that they would cause any tool problems. (If they did, one wonders if such sloppy tools would be useful anyway.)

It's not a problem to remove them, I've removed a bunch myself, but never did it systematically.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!  It's possible my tool problems were caused by something else, I'll investigate.

**Pull request merged**
