### PR TITLE
Issue 481 - Letting compiler determine length for fixed-length arrays

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=481

Add syntax support for partially typed variable declaration.

``` d
void main()
{
    // static array type
    int[$]   a1 = [1,2];    // int[2]
    auto[$]  a2 = [3,4,5];  // int[3]
    const[$] a3 = [6,7,8];  // const(int[3])

    // dynamic array type
    immutable[] a4 = [1,2];    // immutable(int)[]
    shared[]    a5 = [3,4,5];  // shared(int)[]
    // partially specified part is unqualified.

    // pointer type
    auto*  p1 = new int(3);  // int*
    const* p2 = new int(3);  // const(int)*

    // mixing
    auto[][$] x1 = [[1,2,3],[4,5]];  // int[][2]
    shared*[$] x2 = [new int(1), new int(2)];  // shared(int)*[2]
}
```

### CODE REVIEW

**Comment by bearophile** [comment]
This good enhancement could use a little attention by @andralex

**Comment by Hackerpilot** [comment]
For whatever it's worth, I like the ```int[$] arr = [1, 2, 3];``` syntax.

**Comment by andralex** [comment]
Let's pull this in. I approve, and @WalterBright implicitly approves by liking the feature and not finding a better syntax :).

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by bearophile** [comment]
See https://issues.dlang.org/show_bug.cgi?id=14066 (found about one minute after installing the new patch).

**Comment by bearophile** [comment]
Is all this correct? I use a const[$] and I receive an immutable(char[5]). 

    void main() {
        const[$] s1 = "hello";
        pragma(msg, typeof(s1)); // immutable(char[5])
        char[$] s2 = "hello";    // OK?
        s2[0]++;                 // OK?
        pragma(msg, typeof(s2)); // char[5]

        const[$] s3 = "hello"w;
        pragma(msg, typeof(s3)); // immutable(char[5])
        wchar[$] s4 = "hello"w;  // OK?
        s4[0]++;                 // OK?

        pragma(msg, typeof(s4)); // wchar[5]

        const[$] s5 = "hello"d;
        pragma(msg, typeof(s5)); // immutable(char[5])
        dchar[$] s6 = "hello"d;  // OK?
        s6[0]++;                 // OK?
        pragma(msg, typeof(s6)); // dchar[5]

        char[] s7 = "hello";     // Error
    }


	dmd 2.067alpha gives:


	immutable(char[5])
	char[5]
	immutable(wchar[5])
	wchar[5]
	immutable(dchar[5])
	dchar[5]
	test.d(17,17): Error: cannot implicitly convert expression ("hello") of type string to char[]

**Comment by bearophile** [comment]
Is this a good idea?

    void main() {
        int[2][] m = [[1, 2], [3, 4], [5, 6]];
        foreach (auto[2] a; m) {}
        foreach (int[$] a; m) {}
    }

**Comment by 9rnsr** [comment]
```d
void main() {
    const[$] s1 = "hello";
    pragma(msg, typeof(s1)); // immutable(char[5])
```

it's a bug in partial type deduction implementation. The `s1` type should be deduced to `const(char[5])` from the initializer.
I opened: https://issues.dlang.org/show_bug.cgi?id=14069

```d
    char[$] s2 = "hello";    // OK?
    s2[0]++;                 // OK?
    pragma(msg, typeof(s2)); // char[5]
```

That's intended behavior. The s2 type is deduced to `char[5]`, then each string characters will be copied into the static array elements.

**Comment by 9rnsr** [comment]
> Is this a good idea?

Legitimate enhancement. Please file it in bugzilla!

**Comment by bearophile** [comment]
OK, filed: https://issues.dlang.org/show_bug.cgi?id=14070

**Comment by MartinNowak** [comment]
Great to see this in.
Can we get a short note in the changelog please.

**Comment by AndrejMitrovic** [comment]
@9rnsr: Does `static[$] arr = [1, 2, 3]` work? Note that I'm talking about the storage, not the type of the array (I'd prefer if we used the term fixed-length array instead of "static").

**Comment by 9rnsr** [comment]
@AndrejMitrovic It works and properly allowed by the grammar.

**Comment by 9rnsr** [comment]
@MartinNowak I'll do it in the documentation PR: https://github.com/D-Programming-Language/dlang.org/pull/590

**Comment by andralex** [comment]
I hate to say this but I just can't bring myself to agree with this feature - [$] but partial deduction, too.

* Complicates the language without a corresponding increase in power
* Small obscure feature of dubious usefulness that creates a precedent for other small obscure features of increasingly dubious usefulness - https://issues.dlang.org/show_bug.cgi?id=14070 is just the beginning. How about accepting stuff line that in function parameters, etc? It's easy to argue that on grounds of completeness, now that there's a foot in the door.

It is my opinion we should retire this feature before 2.067 is released. I am really sorry for not being more decisive on this and left all this work to be done.

**Comment by WalterBright** [comment]
I agree with @andralex

**Comment by 9rnsr** [comment]
私はこの変更が戻されようとすることには反対しない。
I'm not against to that the change is being reverted due to the 2.067 release.
2.067にこの機能を取り込まないという決定には私は同意できる。
I can agree with the decision that we won't add this new feature in the release.

しかし、私はあなたに怒っている。
However, Andrei, I'm angry to you.

あなたの行動はつまり、このPRをマージするときあなたはこの変更について深く考えていなかったことを示している。
You're wishing to revert this PR. It means that you had not seriously thought about this change when you clicked the merge button.

従って、私は今あなたのD言語に対する真剣さを疑っている。
Therefore now, I'm really doubt that your seriouslness for D.

あなたがDに対して真剣でないなら、私はあなたの主張全てを受け入れることが出来ない。
If you're not serious for D, I should say your all arguments are pointless.

このPRをマージするとき、あなたは何を考えていた？
What did you think when you merging this PR?

**Comment by 9rnsr** [comment]
I reverted this PR in #4373. But @andralex, I'm still waiting your answer.

**Comment by sprinkle131313** [comment]
@andralex 

I'd like to reopen discussion for partial specialization, at the very least. 

> Small obscure feature of dubious usefulness that creates a precedent for other small obscure features of increasingly dubious usefulness - https://issues.dlang.org/show_bug.cgi?id=14070

For the case of "int[$]" this is true, as it would be an entirely new feature and would need to be propagated to places where declarations can occur. For partial specialization, it already exists for function templates. Thus partial specialization already exists in the language, but it only exists in functions. What I'm asking is to extend it to auto declarations for variables and in foreach statements.

```
void func(Auto)(Auto* ptr)
{
}

void func2(Auto)(Auto[string] aa)
{
}

int* p;
func(p);

int[string] aa;
func2(aa);

func(int.init); // err
func2(int.init); // err

```

**Comment by Dgame** [comment]
I don't quite get it, `int.init` is neither a pointer nor an assoc. array. Besides it would be wiser to open an thread in the ng.

**Comment by sprinkle131313** [comment]
@Dgame 

That's the point, init.init would just be an int value, which neither function allows do the partial specialization. 

http://ideone.com/0Ywjlx

What this pull request added was partial specialization to "auto":

```D
auto* ptr = null; // ok
auto* ptr = 0;    // err
```

**Comment by Dgame** [comment]
NG = Newsgroup. Related Thread is: http://forum.dlang.org/post/bewroetnschakoqjzowa@forum.dlang.org

**Comment by sprinkle131313** [comment]
@Dgame yah I posted that and had no way to ping @andralex so I posted here

**Pull request merged**
