### PR TITLE
backend: transition to @safe code part 18

### PR DESCRIPTION
**Pull request by WalterBright**
Rationale is here: #12327

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by WalterBright** [comment]
@Geod24 this is why I resist the idea of just re-running the tests. Today's buildkite failures are completely unrelated, and no error message is given. It just fails. These sort of failures happen constantly with the test suite. Re-running the tests is not the answer, the answer is to fix the tests so when they fail due to environmental problems, they automatically wait a couple minutes and retry.

Probably at least a quarter of my PRs are derailed during testing because of random test suite failures.

**Comment by Geod24** [comment]
> and no error message is given. It just fails.

There is an error message (process killed or agent lost):

Screen Shot 2021-04-05 at 11 25 05

In this case, it's agent lost, which is the most common case for spurious buildkite failure.
If you have an extra server laying around that could be Buildkite server 24/7 we could probably solve this (I had one but I need to reconfigure it).

**Comment by WalterBright** [comment]
Thanks for tracking it down. Do we really need another server, or just have the task automatically restart when such failures occur?

**Comment by Geod24** [comment]
> Do we really need another server, or just have the task automatically restart when such failures occur?

Buildkite does not provide servers to run on, it's simply a means to coordinate things.
Servers are spawned dynamically by the dlang bot (https://github.com/dlang/dlang-bot/blob/master/source/dlangbot/buildkite.d), on Hertzner cloud. I'm not familiar with the full details but I'm pretty sure someone is paying for those servers. It seems that sometimes, those are killed / lost a bit too early.

The easy solution would be to have a server that constantly runs and serves buildkite requests. It wouldn't eliminate spurious failures, but would reduce them.

As for retry, we already have this (it retries once).

**Comment by WalterBright** [comment]
Thanks for the explanation.

> As for retry, we already have this (it retries once).

Maybe retry twice? After sleeping for 5 minutes or so?

**Pull request merged**
