### PR TITLE
accept @pure @nothrow @return attributes

### PR DESCRIPTION
**Pull request by WalterBright**
Not much to it.

### CODE REVIEW

**Comment by Hackerpilot** [comment]
:smile: 
Looks like at least part of my DIP64 is happening.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
@WalterBright take a look at the failures.

**Comment by Orvid** [comment]
The failures I see in the tests are from the DIP 25 PR.

**Comment by WalterBright** [comment]
Here's the code that fails in src/rt/sections_elf_shared.d:
```
ThreadDSO* findThreadDSO(DSO* pdso)
{
    foreach (ref tdata; _loadedDSOs)
        if (tdata._pdso == pdso) return &tdata;
    return null;
}
```
Looks like a case not considered in DIP25, i.e. what to do about ref's in foreach statements.

**Comment by WalterBright** [comment]
Which has nothing to do with this PR.

**Comment by Orvid** [comment]
Instead you wanted [the druntime PR](https://github.com/D-Programming-Language/druntime/pull/1128).

**Comment by jmdavis** [comment]
I would point out that if this doesn't get reverted, then we need to update the error message relating to @ attributes accordingly: https://issues.dlang.org/show_bug.cgi?id=14064 . The message needs to be updated for @nogc regardless, but with this change, three more are missing from the list.

**Pull request merged**
