### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by MartinNowak**
- Revert "fix issue 19590 - `__traits allMembers` should put fully qualified names for imports"
- Fix 21258 - Tuple parameters use the first element of a default tuple value
- Changelog: Output of template usage via `-vtemplates` has been improved
- Fix another little C++ header regression
- bump VERSION to v2.094.0
- Fix another frontend C++ interop regression
- Fix C++ header compilability issue with -Wc++11-narrowing
- Fix Issue 21272 - Overzealous and inconsistent foreach shadowing deprecations for nested functions
- purge changelog

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Review by ibuclaw — APPROVED** [review]

**Comment by thewilsonator** [comment]
This has failures of required windows machines.

**Comment by wilzbach** [comment]
Yup:

```
+ cd /d/a/1/s/src
+ /d/a/1/s/tools/dmd2/windows/bin/make.exe -f win32.mak reldmd-asserts DMD=/d/a/1/s/generated/windows/release/32/dmd
.azure-pipelines/windows.sh: line 82: /d/a/1/s/tools/dmd2/windows/bin/make.exe: No such file or directory
```

Same failure for druntime.

**Comment by kinke** [comment]
> It's because we no longer ship make in the releases.

Tentative fix: #11793 (stable first, then to be included here)

**Comment by wilzbach** [comment]
> (stable first, then to be included here)

Thanks! Added it here.

**Pull request merged**
