### PR TITLE
fix Itanium C++ mangling

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by ibuclaw** [comment]
Just had a quick look and seems fine, apart from the failing tests.

**Comment by WalterBright** [comment]
@ibuclaw it's a work in progress, so expect more changes.

**Comment by WalterBright** [comment]
Removed the clumsy and random string compares. Replaced with elegant symbolic lookups, for a more civilized algorithm.

**Comment by WalterBright** [comment]
I still want to take this further, but this is a good stopping point for this PR.

**Comment by andralex** [comment]
cc @Darredevil

**Review by andralex — APPROVED** [review]
No blocking issue.

**Pull request merged**
