### PR TITLE
dfmt source code

### PR DESCRIPTION
**Pull request by MartinNowak**
- using slightly changed defaults (see .editorconfig)

Let's get back all the time spent formatting code and derive a
prioritized list of dfmt issues that are blocking adoption for dmd.
This PR is meant as a discussion and to keep track of progress.

### CODE REVIEW

**Comment by MartinNowak** [comment]
It's possible to disable dfmt for a particular region btw.
```d
//dfmt off
auto myarray =
[
  12,
  13,
  47,
  8,
  2,
];
//dfmt on
```

**Comment by ZombineDev** [comment]
@MartinNowak I'm all for using automated formating, instead of wasting time by doing this by hand and arguing about it.

**Comment by MartinNowak** [comment]
> @MartinNowak I'm all for using automated formating, instead of wasting time by doing this by hand and arguing about it.

I think we already have a consensus for that, but there are different acceptance criteria.
For example Walter wants aligned comments (http://forum.dlang.org/post/jt4pig$7t2$1@digitalmars.com).

**Comment by yebblies** [comment]
I think aligning comments is one of the few major problems remaining with the dfmt output.  Although, in some places it looks like the dfmt output is an improvement over the arbitrary alignment Kenji recently added.

Formatting of array literals could also use some improvements, and I think the soft line length limit should be increased.

**Comment by AndrejMitrovic** [comment]
This is very stale by now, I don't know if there was a community discussion about going forward with this, but if not I'd suggest opening a discussion in the forums and in the meantime closing this.

**Comment by MartinNowak** [comment]
We already had the discussion, and there are some pending feature requests for dfmt, see https://github.com/dlang/dmd/pull/5217#issuecomment-150273528.

**Comment by MartinNowak** [comment]
Main one being https://github.com/Hackerpilot/dfmt/issues/227, though I don't see why aligned comments are such an important feat that it keeps us from using dfmt.

**Comment by yebblies** [comment]
I'd happily live without aligned declarations/comments.  Some others seem to think they're essential...

**Comment by MartinNowak** [comment]
> I'd happily live without aligned declarations/comments. Some others seem to think they're essential...

Maybe they'd reconsider if it means we can automate formatting right now.

**Comment by yebblies** [comment]
@9rnsr ?

**Comment by MartinNowak** [comment]
We could also have a try at implementing https://github.com/Hackerpilot/dfmt/issues/227#issuecomment-217710164.

**Pull request closed without merging**
