### PR TITLE
Resurrect line spaces in mtype.d

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Seriously? This requires almost any PR changing mtype.d to be rebased, just for minor style fix.
Either we get dfmt up running and automatic formatting or we should just leave the style as is.
I'm not opposed to add a few line spaces when changing the particular code, but PR like this just cost time w/ little benefit.

**Comment by yebblies** [comment]
No, doing it a little bit at a time will take longer and therefore result in more broken pulls. We need to get it done and then STOP screwing around with whitespace.

**Comment by MartinNowak** [comment]
> No, doing it a little bit at a time will take longer and therefore result in more broken pulls. We need to get it done and then STOP screwing around with whitespace.

If you only fix style in code you're changing anyhow, you hardly create additional merge conflicts.

**Comment by yebblies** [comment]
History says otherwise - Kenji has been doing this for months.

**Comment by AndrejMitrovic** [comment]
> I'm not opposed to add a few line spaces when changing the particular code, but PRs like this just cause additional delays for little benefit.

As far as I understand it all @9rnsr is doing is reverting the code style back to what it used to be before the switch to D.

> Either we get dfmt up running and automatic formatting

I think it's a good idea. What's holding us from using dfmt so far? Just a consensus on the style or something more?

**Pull request merged**
