### PR TITLE
minor refactor of inline.d

### PR DESCRIPTION
**Pull request by WalterBright**
Removes some unnecessary artifacts of the D conversion. Added comments. Fixed spelling.

### CODE REVIEW

**Comment by yebblies** [comment]
Should some more of these be private, too?

**Comment by WalterBright** [comment]
Actually, all but two functions can be private. Done.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Beat me to it.

**Comment by WalterBright** [comment]
Thanks, guys!

**Pull request merged**
