### PR TITLE
fix Issue 22500 - ImportC: Lots of errors when compiling tomlc99

### PR DESCRIPTION
**Pull request by WalterBright**
This works for me, so I added a test case for it to ensure it works.

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Hm, it's funny that the bot did not pick up the issue. I wonder if `fix` should be written with a capital letter.

**Comment by Geod24** [comment]
The bot seems offline. If it just didn't pick up the issue, it would still comment.

**Comment by WalterBright** [comment]
Looks like semaphoreci is wedged again.

**Comment by ibuclaw** [comment]
image
@WalterBright try `git commit --amend --no-edit` to force a new commit hash and re-push.

**Pull request merged**
