### PR TITLE
build.d: Save whether dependency was updated

### PR DESCRIPTION
**Pull request by marler8997**
Fixes a race condition caused by https://github.com/dlang/dmd/pull/10639/commits/b3621e8461c4ae066097479efd09500899b17c3b

The problem is line 1420 `return false;`.   The first time something calls `run` it will return whether or not it was updated correctly, but all future calls will return `false`.  This introduces a race condition on whether or not the caller will see that the dependency was updated.  The expected behavior is that the `run` function will always return `true` (meaning the dependency was updated in the current build) if it's command was executed, which signals that all the "dependents" will also need to be rebuilt.

Note that I also removed the return type from `runSynchronized`, which guarantees that it will always return the same `updated` state.  There's no chance that you could have one statement say `return true` or `return false` and return an updated state that doesn't match what it stored in the `updated` field.

### CODE REVIEW

**Review by MoonlightSentinel — APPROVED** [review]

**Review by RazvanN7 — APPROVED** [review]

**Comment by WalterBright** [comment]
@marler8997 something has gone terribly wrong with building dmd. It used to build fairly quickly. Now I change one file, do a "debug" build, and it takes about 5 minutes. Debug builds are supposed to be fast, and they used to be fast. I'm doing a:
```
make -f posix.mak ENABLE_RELEASE= ENABLE_DEBUG=1 -j 4
```

**Comment by WalterBright** [comment]
This is killing my productivity.

**Comment by MoonlightSentinel** [comment]
> @marler8997 something has gone terribly wrong with building dmd. It used to build fairly quickly. Now I change one file, do a "debug" build, and it takes about 5 minutes. Debug builds are supposed to be fast, and they used to be fast. I'm doing a:
> 
> ```
> make -f posix.mak ENABLE_RELEASE= ENABLE_DEBUG=1 -j 4
> ```

@WalterBright Does it also take that much time using the following command?

```
rdmd src/build ENABLE_RELEASE=0 ENABLE_DEBUG=1
```

**Comment by marler8997** [comment]
Looks like the problem is that `build.d` it interpreting `ENABLE_RELEASE=` as true.  (empty value is being interpretes as true).  Putting together a PR to fix...

**Comment by marler8997** [comment]
fix here: https://github.com/dlang/dmd/pull/10663

note that problems like this are going to happen during this transition.  That's why we are making changes gradually so we can isolate and identify issues quickly.  However, I think this issue has likely been around for many months so I'm not sure why this is the first time someone has see/reported it.

**Pull request merged**
