### PR TITLE
Remove C++ linkage from static members

### PR DESCRIPTION
**Pull request by ibuclaw**
Removing members from C++ interface.

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by thewilsonator** [comment]
Semahore timeout.

**Comment by ibuclaw** [comment]
@jacob-carlborg - Do you mind if I roll all these auto-merge PRs into one?

**Comment by thewilsonator** [comment]
That is a good Idea.

**Comment by ibuclaw** [comment]
All have been previously approved, re-added auto-merge.

**Comment by thewilsonator** [comment]
#8774 #8770 and #8769 ?

**Comment by ibuclaw** [comment]
No one hit auto-merge on them, so they didn't show in my filter. :-)

**Review by jacob-carlborg — APPROVED** [review]

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
