### PR TITLE
expression.d: Convert AssignExp.memset from int mask to enum (and use enum class)

### PR DESCRIPTION
**Pull request by ibuclaw**
As I'm currently looking at code generation of AssignExp's, I noticed that these don't have a prefix.

```
if (e->memset & referenceInit)
{
}
// ...
if (e->memset & blockAssign)
{
}
```
Updating the headers to fix that.

@kinke FYI

### CODE REVIEW

**Comment by ibuclaw** [comment]
Oh no...
```
expr.cc:898:16: error: no match for ‘operator&’ (operand types are ‘int’ and ‘MemorySet’)
  898 |  if (e->memset & MemorySet::blockAssign)
      |      ~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~
      |         |                   |
      |         int                 MemorySet
```

**Comment by ibuclaw** [comment]
> Oh no...

Converting `memset` from an `int` to `MemorySet`.  There should never be a case where an assignment is _both_ a reference and block assignment at the same time.

**Review by MoonlightSentinel — APPROVED** [review]
>  There should never be a case where an assignment is both a reference and block assignment at the same time.

Seems reasonable.

**Comment by 12345swordy** [comment]
Time is up.

**Comment by ibuclaw** [comment]
auto-tester is stuck -> rebasing.

**Pull request merged**
