### PR TITLE
Slice struct types as well

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
Tests?

**Comment by WalterBright** [comment]
Looks like the test cases are already in the test suite!

**Comment by WalterBright** [comment]
@wilzbach can something be done about the semaphoreci logs?

1. the scroll bar tab is to small to grab
2. the tab is nearly impossible to move without it skipping large chunks of text
3. I never know which of the two logs per build is the one with the error in it
4. I rarely can find what the error is in those logs in those thousands of lines

I always pray that if there is an error, it isn't only in semaphoreci.

**Comment by jacob-carlborg** [comment]
Most CI systems have a button to download the full build log as plain text. Not sure if Semaphore has that.

**Comment by wilzbach** [comment]
> can something be done about the semaphoreci logs?

Well, we wanted to migrate these jobs to Buildkite, but there was no money for servers.
I think they also over a version 2.0 of SemaphoreCI, but so far no one has shown interest in migrating...

Anyhow, it's very rare that SemaphoreCI catches an error when all the other platforms are green (it can happen though as it tests bootstrapping with GDC/LDC/DMD), but in many cases the failure was unrelated and a restart helps (that's my first action at least).

> I never know which of the two logs per build is the one with the error in it

The one which the red Cross/X is the actual build that failed, the others were just stopped.

**Comment by jacob-carlborg** [comment]
> the others were just stopped

When does that happen?

**Comment by wilzbach** [comment]
> > the others were just stopped
> 
> When does that happen?

Every time a failure happens, because then the other builds gets stopped to save the resources. It's a configurable option, but as we're constantly using up all the free jobs they provide us with, that helps us a bit with conserving them.

Example:

image

The second build (DMD x86_64) failed here and thus all other builds have been stopped.
That's what the "X" tells you.

Disclaimer: I'm not saying that this is a great UI / visualization.

**Pull request merged**
