### PR TITLE
Don't use `foreach` if the loop body modifies the iteration variable

### PR DESCRIPTION
**Pull request by schuetzm**
This fixes a segfault in compiling vibe.d.

### CODE REVIEW

**Comment by ibuclaw** [comment]
:+1:

**Comment by ibuclaw** [comment]
Can we please have a test added to the testsuite?

**Comment by schuetzm** [comment]
I don't know the code that triggers this, haven't tried to reduce it. But I added a comment that should keep people from changing it back to `foreach`.

**Comment by yebblies** [comment]
```d

class E2 : Exception { this() { super(null); } }
class E3 : Exception { this() { super(null); } }

void main()
{
    try
    {
    }
    catch (E3)
    {
    }
    catch (E2)
    {
    }
    catch (Exception)
    {
    }
}
```

**Comment by yebblies** [comment]
A test case is much better than a comment!

**Comment by schuetzm** [comment]
Thanks! Added your testcase.

I also added an enhancement request to deprecate modifying the iteration variable in `foreach`:
https://issues.dlang.org/show_bug.cgi?id=14984

**Comment by yebblies** [comment]
Looks good.  Instead of adding the comment, can you just change it to use foreach_reverse and not modify `i` any more.

**Comment by schuetzm** [comment]
Done.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
BTW, if you want to change the loop variable use `foreach (ref i; 0 .. 10)`.

**Pull request merged**
