### PR TITLE
build.d: Create sc.ini instead of dmd.conf on windows

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
A freshly build `dmd.exe` can now compile without passing the import paths to druntime` and phobos.
I adapted the content from https://github.com/dlang/dmd/blob/34546fac932e267f79d28880e1a9eca22981d5b4/ini/windows/bin/sc.ini

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
What was the problem ?

**Review by wilzbach — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
dmd reads its configuration from ‘sc.ini‘ instead of dmd.conf on windows and hence was missing the appropriate import paths for druntime / phobos

**Comment by wilzbach** [comment]
The build script generated dmd.conf on Windows - not sc.ini

**Comment by Geod24** [comment]
Right, one of those annoying discrepancies that end up crippling up everywhere. I thought we made DMD read `dmd.conf` and fall back to `sc.ini` on Windows years ago, but apparently I dreamed it.

**Pull request merged**
