### PR TITLE
highlight dscope.d error messages

### PR DESCRIPTION
**Pull request by JinShil**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
👌.

**Comment by wilzbach** [comment]
Seems like `fail9665b` needs updates:

```
Test failed: 
expected:
----
fail_compilation/fail9665b.d(32): Error: one path skips field x2
fail_compilation/fail9665b.d(33): Error: one path skips field x3
fail_compilation/fail9665b.d(35): Error: one path skips field x5
fail_compilation/fail9665b.d(36): Error: one path skips field x6
fail_compilation/fail9665b.d(30): Error: field `x1` must be initialized in constructor
fail_compilation/fail9665b.d(30): Error: field `x4` must be initialized in constructor
fail_compilation/fail9665b.d(65): Error: one path skips field x2
fail_compilation/fail9665b.d(66): Error: one path skips field x3
fail_compilation/fail9665b.d(68): Error: one path skips field x5
fail_compilation/fail9665b.d(69): Error: one path skips field x6
fail_compilation/fail9665b.d(63): Error: field `x1` must be initialized in constructor, because it is nested struct
fail_compilation/fail9665b.d(63): Error: field `x4` must be initialized in constructor, because it is nested struct
fail_compilation/fail9665b.d(76): Error: template instance fail9665b.S2!(X) error instantiating
----
actual:
----
fail_compilation/fail9665b.d(32): Error: one path skips field `x2`
fail_compilation/fail9665b.d(33): Error: one path skips field `x3`
fail_compilation/fail9665b.d(35): Error: one path skips field `x5`
fail_compilation/fail9665b.d(36): Error: one path skips field `x6`
fail_compilation/fail9665b.d(30): Error: field `x1` must be initialized in constructor
fail_compilation/fail9665b.d(30): Error: field `x4` must be initialized in constructor
fail_compilation/fail9665b.d(65): Error: one path skips field `x2`
fail_compilation/fail9665b.d(66): Error: one path skips field `x3`
fail_compilation/fail9665b.d(68): Error: one path skips field `x5`
fail_compilation/fail9665b.d(69): Error: one path skips field `x6`
fail_compilation/fail9665b.d(63): Error: field `x1` must be initialized in constructor, because it is nested struct
fail_compilation/fail9665b.d(63): Error: field `x4` must be initialized in constructor, because it is nested struct
fail_compilation/fail9665b.d(76): Error: template instance fail9665b.S2!(X) error instantiating
----
```

I quickly did it myself ;-)

**Review by wilzbach — APPROVED** [review]

**Comment by JinShil** [comment]
> Seems like fail9665b needs updates:  I quickly did it myself ;-)

Thank you, I was leveraging the auto-tester for this one as it takes so long to run the test suite locally for me.  I probably should have marked it WIP.  Sorry.

**Comment by wilzbach** [comment]
>  probably should have marked it WIP. Sorry.

No worries. It just takes the same time for my to point out sth. with a comment compared to actually being more productive and directly fixing it :wink:

**Review by WalterBright — APPROVED** [review]

**Pull request merged**
