### PR TITLE
revert deprecation of scope class

### PR DESCRIPTION
**Pull request by WalterBright**
See https://github.com/dlang/dmd/pull/13767

This is another one where the `scope class` doesn't actually hurt anything.

I suggest with things like this that do not actually hurt anything that we just accept them and keep them doing what they do without complaint. We can perhaps add a switch `-obsolete` which will tell the user about use of such obsolete features.

See also: https://github.com/dlang/dmd/pull/15379 and deprecating class alias this.

### CODE REVIEW

**Comment by WalterBright** [comment]
Or maybe a `-wo` switch, which will emit warnings about obsolete features.

**Comment by rikkimax** [comment]
These features should still be removed at some point. I would like to one day use body for instance.

However, a separate warning that dub turns on by default? Sure, I like that idea.

**Comment by WalterBright** [comment]
You can already use `body` as an identifier, this doesn't turn it off.

**Comment by adamdruppe** [comment]
good.

**Comment by tgehr** [comment]
Nice! TBH I don't really see why this should even be considered obsolete. It's nice to be able to declare a class whose destructor has to be called reliably, the check is very cheap, and the syntax is intuitive.

**Review by dkorpel — APPROVED** [review]

**Pull request merged**
