### PR TITLE
a bit more sensible dt generation

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
@yebblies this one too, please!

**Comment by yebblies** [comment]
Can you fix https://github.com/yebblies/dmd/commit/3aff82e0c63ec71d2670538afc5e40bbc1719b13 ?

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
> Can you fix yebblies@3aff82e ?

What do you mean?

**Comment by yebblies** [comment]
It doesn't work because of D's lack of default ctors/interior pointers.  Since you insist on using these features, it would be nice if you could demonstrate how they can work across the D/C++ boundary.

**Pull request merged**
