### PR TITLE
revert #6816 to due to excessive code breakage

### PR DESCRIPTION
**Pull request by MartinNowak**
- deferring resolution until the next major release
  [Issue 14246 – RAII - proper destruction of partially constructed objects/structs](https://issues.dlang.org/show_bug.cgi?id=14246)

Commenting out dlang.org https://github.com/dlang/dlang.org/pull/1719.

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]
I have already proposed a revert in #6899, but of course adding the tests as fixture is highly appreciated :)
Looking forward to be able to enforce the Project Tester again!

**Review by WalterBright — APPROVED** [review]

**Comment by CyberShadow** [comment]
Jenkins finally looks green again.

Shall we set it as required once more?

**Comment by wilzbach** [comment]
> Jenkins finally looks green again.
> Shall we set it as required once more?

Yes please. Tracking regressions down is a very exhausting job

**Comment by MartinNowak** [comment]
> Shall we set it as required once more?

Already done 3 hours ago ;).

**Comment by MartinNowak** [comment]
This is a good example of how reliant we are on testing external projects.

**Pull request merged**
