### PR TITLE
[Experimental] Enable GC in dmd

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by rainers** [comment]
I don't think it is that easy ;-) There are references from the backend into the front end that need to be known to the GC. I think it's necessary to redirect malloc,calloc,etc. in the backend, too.

I did that once by redefining them in warnings.h (i.e. for VS builds only): https://github.com/rainers/dmd/commit/6584ffb187e84d9f872bb3658eacd3c425c82023. I don't remember how well that worked, though...

**Comment by yebblies** [comment]
I know it doesn't work, but it shouldn't be that hard.  Why would the backend ever hold the only reference to frontend data?

Another option is to disable the GC after semantic is complete, since the bulk of the allocation is already done.

**Comment by rainers** [comment]
> Why would the backend ever hold the only reference to frontend data?

I think it can happen due to transformations in the glue layer. Disabling the GC before that's done might work, though.

**Comment by yebblies** [comment]
I'm not sure how we could drop the memory efficiently without fork+wait, or mmaping ourselves.

**Comment by AndrejMitrovic** [comment]
This seems to be a dead PR. Close or perhaps rebase?

**Comment by JinShil** [comment]
I think the experiment is finished.  Closing.

**Pull request closed without merging**
