### PR TITLE
fix Issue 22175 - assert fail when struct assignment value is desired…

### PR DESCRIPTION
**Pull request by WalterBright**
… and struct size is odd

This replaces https://github.com/dlang/dmd/pull/13255

Description in the comments.

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Comment by dkorpel** [comment]
Shouldn't this target stable?

**Comment by RazvanN7** [comment]
@WalterBright could you please rebase on top of stable so that we can get this in?

**Comment by WalterBright** [comment]
Isn't it already based on stable?

**Comment by RazvanN7** [comment]
Yes, now it is because I rebased it myself, but I don't understand why the tester is failing. It seems that buildkite is checking out the wrong branch for phobos testing.

**Comment by RazvanN7** [comment]
Since the failing testers are not mandatory, I suppose that this kind of failures is seen often enough. Moreover, the PR passed all the tests on master so it should be good to go.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
