### PR TITLE
ranges in phobos increase exe size

### PR DESCRIPTION
**Pull request by WalterBright**
not much to be done about that.

### CODE REVIEW

**Comment by MartinNowak** [comment]
:-(

> not much to be done about that.

Well you don't use datetime at all, so we need to find out how to keep that dead code out of the binary.

**Comment by WalterBright** [comment]
It may have been an accumulation of things that this change just put past the trigger.

**Comment by MartinNowak** [comment]
We had little to no effect of gc-sections with dmd, mostly because it already uses multilibs.
I think the root problem is that the ModuleInfo hard-links imported modules and all classes within a module. The classes vtable the drags all the member functions and lots of other stuff.
I spent some time to make weak external references work, but there were concerns to use that b/c it might break Object.factory.
https://github.com/D-Programming-Language/dmd/pull/4638

**Comment by WalterBright** [comment]
Object.factory in hindsight was a mistake. It should only work with classes marked with `export`. It's probably worthwhile to fix that.

**Comment by MartinNowak** [comment]
Might make an interesting story for the next release, though export still needs a lot of fixes. Also there are more important topics than binary size.

**Comment by mihails-strasuns-sociomantic** [comment]
> on 2.067 the Linux x86_64 executable for that test is only 30% the size of DMD's

Still about the same ratio for 2.068 (with both linked to shared phobos library)

```
-rwxr-xr-x 1 mihails mihails 139K Aug 20 18:34 hello-dmd
-rwxr-xr-x 1 mihails mihails  47K Aug 20 18:33 hello-ldc
```

(for a simple app that uses some template utilities)

```D
void main ()
{
    import std.stdio, std.algorithm;
    writeln([ 1, 2, 3 ].map!(a => 2*a));
}
```

**Pull request merged**
