### PR TITLE
Issue 6620 - argument evaluation order inversed for extern(C)

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=6620

### CODE REVIEW

**Comment by MartinNowak** [comment]
Then isn't the best order for `a() = b() + c() + d();` neither LTR nor RTL, but  `b -> c -> d -> a`?
This is also matches variable declaration, where the initializer can't reference the variable, but otherwise is strictly LTR.

**Comment by ibuclaw** [comment]
I'm just wondering when this x86-specific special case will be removed.

**Comment by 9rnsr** [comment]
I fully updated this PR. Now, array operation keeps existing evaluation order with AST adjustment in `src/arrayop.d`, and it's mostly ready to go forward.

But unfortunately, Phobos unittest is failing in win32, because of a backend regression introduced from 2.069:
https://issues.dlang.org/show_bug.cgi?id=15898

**Comment by 9rnsr** [comment]
Regression 15898 has fixed in stable branch, and the bugfix change has merged into master.
Now, this PR is ready to go.

**Comment by 9rnsr** [comment]
@WalterBright ?

**Comment by ibuclaw** [comment]
As far as I'm aware, array operations are still evaluated in a different order between x86 and every other cpu.  Even if this isn't an ideal patch.

**Comment by ibuclaw** [comment]
As per #4895 - no point pursuing.  The old x86-centric library functions need to die or be made `extern(D)`.

**Pull request closed without merging**
