### PR TITLE
simplify attributesApply()

### PR DESCRIPTION
**Pull request by WalterBright**
by using delegates instead of function pointers.

### CODE REVIEW

**Comment by WalterBright** [comment]
Anyone know what's up with buildkite/dmd ocean?
```
./src/ocean/transition.d(42): Error: basic type expected, not `static`
| ./src/ocean/transition.d(42): Error: found `static` when expecting `)`
| ./src/ocean/transition.d(42): Error: semicolon expected following auto declaration, not `immutable`
| ./src/ocean/transition.d(42): Error: declaration expected, not `)`
| ./src/ocean/meta/types/Qualifiers.d(73): Error: basic type expected, not `static`
| ./src/ocean/meta/types/Qualifiers.d(73): Error: found `static` when expecting `)`
| ./src/ocean/meta/types/Qualifiers.d(73): Error: found `immutable` when expecting `)`
| ./src/ocean/meta/types/Qualifiers.d(73): Error: found `)` when expecting `;`
| ./src/ocean/meta/types/Qualifiers.d(73): Error: found `)` instead of statement
| ./src/ocean/meta/types/Qualifiers.d(169): Error: basic type expected, not `static`
| ./src/ocean/meta/types/Qualifiers.d(169): Error: found `static` when expecting `)`
| ./src/ocean/meta/types/Qualifiers.d(169): Error: found `immutable` when expecting `)`
| ./src/ocean/meta/types/Qualifiers.d(169): Error: no identifier for declarator `U`
| ./src/ocean/meta/types/Qualifiers.d(169): Error: declaration expected, not `)`
| ./src/ocean/meta/types/Qualifiers.d(173): Error: declaration expected, not `else`
| ./src/ocean/meta/types/Qualifiers.d(176): Error: unrecognized declaration
| ./src/ocean/core/Test.d(230): Error: semicolon expected following function declaration
| ./src/ocean/core/Test.d(232): Error: declaration expected, not `if`
```

**Comment by JinShil** [comment]
[Sociomantic Ocean's new 5.0.0 release](https://github.com/sociomantic-tsunami/ocean/releases)

**Comment by WalterBright** [comment]
Looks like it's happening with other PRs, and has nothing to do with this one.

**Review by PetarKirov — APPROVED** [review]
Nicely done!

**Comment by ZombineDev** [comment]
Auto-merge toggled on

**Pull request merged**
