### PR TITLE
refactor cod2.c: using CodeBuilder part 2

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by andralex** [comment]
5 extra lines.... hmmm

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
one tester timed out, push again

**Comment by andralex** [comment]
actually I'll just merge this

**Comment by WalterBright** [comment]
> 5 extra lines.... hmmm

Some of those were from deleting a declaration in an outer scope and moving into inner scope(s). This improves locality and encapsulation, but results in more lines of declarations.

**Pull request merged**
