### PR TITLE
cod4.c: start using CodeBuilder part 1

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by andralex** [comment]
@MartinNowak how do I figure what Jenkins didn't like? https://ci.dawg.eu/job/DPL/713/console is not too indicative.

**Review by andralex — APPROVED** [review]
+70-74

**Comment by mathias-lang-sociomantic** [comment]
> @MartinNowak how do I figure what Jenkins didn't like? https://ci.dawg.eu/job/DPL/713/console is not too indicative.

Your link it to the upstream job (the build of DMD). After this is done, it triggers a bunch of downstream job (one for each tested project). You can see that at the very bottom of the link you provided:

```
make: Leaving directory '/var/lib/jenkins/jobs/DPL/workspace/phobos'
Waiting for the completion of projects
projects #602 completed. Result was FAILURE
Build step 'Trigger/call builds on other projects' marked build as failure
```

Clicking on [the provided link](https://ci.dawg.eu/job/projects/602/) allows you to see which job failed, and get it's own output.

**Comment by andralex** [comment]
@mathias-lang-sociomantic thanks, looks like Jenkins and I have very different UI design sensibilities (need to hover over a link, get a stupid invisible arrow to show, click that, open a submenu, and then choose from it just to get anywhere - all from a page that's very scarcely populated offering vast real estate for things like, well, plain links? who thought that's a good idea?) Anyway I've been hovering everything I could hover and finally got to https://ci.dawg.eu/job/projects/602/console which nicely points to Derelict as the failed build, which in turn points to https://ci.dawg.eu/job/projects/REPO=DerelictOrg%2FDerelictGLFW3/lastFailedBuild/console, which has an odd error:

`
usr/bin/ld: fatal error: ../../../../../../.dub/packages/derelict-util-2.0.6/derelict-util/lib/libDerelictUtil.a: attempt to map 60 bytes at offset 4085484 exceeds size of file; the file may be corrupt
`

Is this it? Is this PR producing a corrupt object file? Thx.

**Comment by mathias-lang-sociomantic** [comment]
> who thought that's a good idea?

Java developpers :)
It's indeed quite convoluted, and you don't want to look at config file. I guess people just get used to it.

The last link you provided points is not the right error, it was for another P.R.:
```
  originally caused by:
   GitHub pull request #6365 of commit e0ac0a804210824e4f9ab5bca935595d21d822e5, no merge conflicts.
```

There is no direct mapping between upstream job number, downstream job number, and P.R., so one has to read the log.

There is an invisible arrow next to each project [on this page](https://ci.dawg.eu/job/projects/602/).
Just go over the name of the failing one, and select "Console output". It brings you to [this page](https://ci.dawg.eu/job/projects/602/REPO=DerelictOrg%2FDerelictGLFW3/console) which has an even weirder error message:

```
collect2: fatal error: ld terminated with signal 7 [Bus error]
```

If you have access, you could try restarting the build to see if it's spurious.

**Comment by andralex** [comment]
>If you have access, you could try restarting the build to see if it's spurious.

Guess not. cc @MartinNowak

**Comment by andralex** [comment]
@WalterBright push again?

**Comment by MartinNowak** [comment]
> @mathias-lang-sociomantic thanks, looks like Jenkins and I have very different UI design sensibilities (need to hover over a link, get a stupid invisible arrow to show, click that, open a submenu, and then choose from it just to get anywhere - all from a page that's very scarcely populated offering vast real estate for things like, well, plain links?

We're working on a better Jenkins pipeline, the current setup is a 1 year old hack, not really build to be readable.

**Pull request merged**
