### PR TITLE
split off main.d from mars.d

### PR DESCRIPTION
**Pull request by WalterBright**
Obviously, the only time dmd will need a `main` is if a standalone console program is being generated. For dmd-as-library, an LSP plugin, or a DLL, no `main` is required. So I thought I'd split off `main` and put it in its own file, `main.d`, along with the code versioned as "not `NoMain`". This should be straightforward.

Knotty problems:

1. main.d winds up importing every other module
2. the not NoMain code calls other functions that are not NoMain (!) but are not called by other not NoMain code not no how not no way

@RazvanN7 I could use your advice on your vision for dmd-as-library, and maybe we can extirpate the naughtiness with this code, so this PR is not for nought.

### CODE REVIEW

**Comment by maxhaton** [comment]
There is already an entrypoint for DMD as a library in frontend.d, have you looked at it?

**Comment by RazvanN7** [comment]
@maxhaton Yes, there is an entry point for dmd as a lib, however, mars.d currently contains (or used to contain) some functions that need to be used for config purposes in dmd as a lib. In the past, we used to just move these functions to other files that are included in dmd-as-a-lib, because mars.d is currently excluded the packaging of the library.

@WalterBright I approve this addition, however, why not go fully in this direction? What I mean is that we can keep all of the functions that `main.d` calls in `mars.d` and `mars.d`  could be included in the dmd-as-a-lib package. You never know what the library might need to use, so if you want to be on the safe side just leave everything up for grabs.

> main.d winds up importing every other module

That's fine. It's the main function after all. dmd-as-a-lib does not include this file. And that's what `mars.d` did anyway.

> the not NoMain code calls other functions that are not NoMain (!) but are not called by other not NoMain code not no how not no way

I cannot parse this sentence, too many negations. But I think the simplest way to move forward is to just keep everything, except for the main function, in `mars.d` and just have `main.d` include it. The purpose of this is to make `mars.d` importable, so why not just go down that path?

**Comment by WalterBright** [comment]
> I cannot parse this sentence, too many negations

That's the point, `NoMain` is confusing. A better version would be `Main`.

I only moved the functions over to `main.d` that were not NoMain functions. There should be a clear separation between code only needed for `main()` and code needed for any build of the compiler.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
> I only moved the functions over to main.d that were not NoMain functions. There should be a clear separation between code only needed for main() and code needed for any build of the compiler.

But dmd as a library might use that code even if the not NoMain code uses it.

**Review by Geod24 — APPROVED** [review]
Great!

**Pull request merged**
