### PR TITLE
fix Issue 20150 - -dip1000 return attribute must be explicit in pure …

### PR DESCRIPTION
**Pull request by WalterBright**
…functions

### CODE REVIEW

**Comment by aG0aep6G** [comment]
With this PR, the following function seems to become impossible.

Without `return` on `r`:

```d
int* f(int* r, int** x) @safe pure
{
    *x = r;
    return r; /* Error: pure function f returns parameter r, annotate with return */
}
```

With `return` on `r`:

```d
int* f(return int* r, int** x) @safe pure
{
    *x = r; /* Error: scope variable r assigned to non-scope *x */
    return r;
}
```

With `scope` on `x`:

```d
int* f(return int* r, scope int** x) @safe pure
{
    *x = r; /* Error: scope variable r assigned to non-scope *x */
    return r;
}
```

The latter two errors make sense to me. The first one, i.e. the one added by this PR, seems nonsensical. Why should `pure` imply `scope` on the parameter?

**Comment by aG0aep6G** [comment]
I think the correct approach would be to check the return type here: <https://github.com/dlang/dmd/blob/master/src/dmd/mtype.d#L4403-L4448>, just like the parameters and `this` are checked.

Problem is: `scope` inference based on the function body is not very good. So things like `dup` currently rely on the incorrectly permissive inference based on `pure`.

A reduced example (should compile, but doesn't):

```d
int* f()(int* p)
{
    static int g;
    g = 0;
    int* p2 = p;
    return new int;
}

int* g() @safe
{
    int x;
    return f(&x); /* Error: reference to local variable `x` assigned to non-scope parameter `p` */
}
```

(Filed as [issue 20674](https://issues.dlang.org/show_bug.cgi?id=20674).)

**Comment by 12345swordy** [comment]
need rebased

**Comment by 12345swordy** [comment]
ping @thewilsonator

**Comment by aG0aep6G** [comment]
> I think the correct approach would be to check the return type here: https://github.com/dlang/dmd/blob/master/src/dmd/mtype.d#L4403-L4448, just like the parameters and `this` are checked.

#12010

**Comment by RazvanN7** [comment]
@WalterBright , what is your response to @aG0aep6G 's comments? It seems like a sensible concern.

**Comment by WalterBright** [comment]
rebased

**Comment by dkorpel** [comment]
I would like to re-iterate aG0aep6G's concern. Here's an even simpler example:

```D
// For pointers with infinite lifetime only
int* identity(int* p) {return p;}
```
This is allowed, both before and after this fix. Just don't call it on a `scope` pointer. Now we make it `pure`:
```D
int* identityP(int* p) pure {return p;}
```
All we do is adding `pure` to a pure function, and now it doesn't compile anymore! 

The compiler forces me to annotate `p` with `return`. In this case that's not a problem, but I have a codebase that's `@safe` `pure` but not `@nogc`: the functions assume the inputs have infinite life-time using GC memory. With this patch applied (or actually Per's deprecation version), dmd gives me ~35 errors asking me to annotate parameters with `return`. I can't do that however, since I put the parameters in associative arrays and array literals and you can't have e.g. a `scope(T)[]`. So my only options are:
- forcibly make the functions impure
- add `@trusted` blocks everywhere
- not use `-dip1000` anymore

The restriction that `pure` functions *must* take `scope` or `return scope` parameters makes no sense.

https://github.com/dlang/dmd/pull/12010 really is the better fix, though unfortunately that requires more update work to druntime and Phobos. My current snag is that `core.lifetime: move` becomes `@system`, probably due to some failed `scope` inference, and it's hard to track down where exactly it goes wrong.

**Comment by nordlow** [comment]
> rebased

Can you rebase again now, @WalterBright 

All the phobos preparations for this PR has been merged on master now. So you need to keep target master on this PR aswell.

If the CircleCI third-party-libraries fail and we don't have the time to correct all the errors nor permission to merge them could make the new error triggerd in PR be a deprecation until those libraries have been fixed.

**Comment by dkorpel** [comment]
Superceded by https://github.com/dlang/dmd/pull/12010

**Pull request closed without merging**
