### PR TITLE
'throw' makes a block BCexit

### PR DESCRIPTION
**Pull request by WalterBright**
As suggested by Nicholas Wilson.

### CODE REVIEW

**Comment by WalterBright** [comment]
Later on, move the BCexit blocks past the end of the function.

**Comment by WalterBright** [comment]
This is a mystery. test/runnable/testaa2.d is segfaulting under 32 bit Linux. But it runs fine on my machine (Ubuntu). Diffing testaa2.o with an without this change yields just what I expect - the generated code is exactly the same, except for:
```
  pop EBX
  pop EBP
  ret
  add [EAX],AL
```
appears after the call to `_d_throwdwarf`, which is just what I expected.

The only thing I can think of is that `_d_throwdwarf` is returning, but the source code to it puts `assert(0)` at all return points. Anyone have any ideas?

**Comment by WalterBright** [comment]
Apparently some dwarf unwinders need the epilog to be present after a throw.

**Comment by WalterBright** [comment]
@MartinNowak what does this error mean?
```
timelimit -t 90  generated/linux/release/64/unittest/test_runner std.xml
0.005s PASS release64 std.xml
posix.mak:379: recipe for target 'unittest/std/xml.run' failed
```

**Review by andralex — APPROVED** [review]
noice

**Pull request merged**
