### PR TITLE
Improve error message for when equality expression requires TypeInfo when using -betterC

### PR DESCRIPTION
**Pull request by ryuukk**
That'll help people who run into this specific issue: https://issues.dlang.org/show_bug.cgi?id=22082

If someone know how to fix it, that would be great! 

It blocks me for this: https://github.com/ldc-developers/ldc/issues/3875

### CODE REVIEW

**Comment by kinke** [comment]
> if someone know how to fix it

The relevant logic is in https://github.com/dlang/dmd/blob/831d407006dcf82c452517f9446ece4d01621fab/src/dmd/expressionsem.d#L11478-L11545

**Comment by ryuukk** [comment]
> > if someone know how to fix it
> 
> The relevant logic is in
> 
> https://github.com/dlang/dmd/blob/831d407006dcf82c452517f9446ece4d01621fab/src/dmd/expressionsem.d#L11478-L11545

LL11503:

Adding: ``if (t.isfloating()) return true;`` seems to solve the issue!


The following test now passes
```D
import core.stdc.stdio;

struct VertexA
{
    float pos;
}

struct VertexB
{
    float[2] pos;
}

extern(C) int main()
{
    float f_a;
    float f_b;
    assert(f_a != f_b);

    f_a = 0;
    assert(f_a != f_b);

    f_b = 0;
    assert(f_a == f_b);


    VertexA a_a;
    VertexA a_b;
    assert(a_a != a_b);

    a_a.pos = 0;
    assert(a_a != a_b);

    a_b.pos = 0;
    assert(a_a == a_b);

    VertexB b_a;
    VertexB b_b;
    assert(b_a != b_b);

    b_a.pos = 0;
    assert(b_a != b_b);

    b_b.pos = 0;   
    assert(b_a == b_b);

    return 0;
}
```

**Comment by ryuukk** [comment]
Added PR that fixes the issue, with a test here: https://github.com/dlang/dmd/pull/13320

**Comment by RazvanN7** [comment]
@ryuukk is it ok to close this? It does not have a test and you seem to be trying to fix the underlying issue.

**Pull request closed without merging**
