### PR TITLE
Print all test failures at the end

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
This won't work because each test is run in a unique `d_do_test` instance.

I think a better solution would be to have no output for successfull tests at all (except maybe `1234/1234 tests finished sucessfully`). But that requires changes in `run.d` or `d_do_test.d` to handle timeouts during test executions s.t. one can detect infinitely running tests.

**Comment by UplinkCoder** [comment]
@MoonlightSentinel I already notcied.

Personally I think that d_run_test.d is a dead end.
And we should write a sane tester from scratch.

**Comment by MoonlightSentinel** [comment]
You could also redirect the immediate output from `d_do_test.d` into the test's logfile and let `run.d` dump them at the end.

**Comment by UplinkCoder** [comment]
> > This won't work because each test is run in a unique d_do_test instance.
> 
> You could also redirect the immediate output from `d_do_test.d` into the test's logfile and let `run.d` dump them at the end.

I had the same idea already.
And this is likely the quickest way to improve the "status-quo". However it's still messy because of all the file-system manipulation.

**Comment by NilsLankila** [comment]
suggestion: if some tests are interupted with CTRL+C then their outputs should not be shown. For example I see a failure then I press CTRL+C to kill all the other test that are running in parallel (because I use -j8). In this case for now i get the output of the tests I interrupt but I dont care about them.

**Comment by Geod24** [comment]
> suggestion: if some tests are interupted with CTRL+C then their outputs should not be shown. For example I see a failure then I press CTRL+C to kill all the other test that are running in parallel (because I use -j8). In this case for now i get the output of the tests I interrupt but I dont care about them.

It's very situational. If a test has an infinite loop, then you want the output.

**Pull request closed without merging**
