### PR TITLE
Refactor a loop with disjoint branches into an 'if' in foreach over array semantic

### PR DESCRIPTION
**Pull request by Geod24**
The foreach had no common branch between the loop, it was either doing one or the other.
Turning it into an 'if' makes the code much more readable.

### CODE REVIEW

**Comment by NilsLankila** [comment]
foreach over user defined opIndex is not handled here (it can take an arbitrary count of param) ?

**Comment by Geod24** [comment]
Expand the diff upwards, this is only for static and dynamic arrays.

**Review by ghost — APPROVED** [review]

**Comment by NilsLankila** [comment]
maybe amend the commit message, it's a bit vague for now. I propose "Refactor foreach over arrays into an 'if'"

**Comment by Geod24** [comment]
Right, hope the new message is better

**Comment by NilsLankila** [comment]
yes. LGTM.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
