### PR TITLE
[DDMD] Stop using bitfields in iasm.c

### PR DESCRIPTION
**Pull request by yebblies**
Instead, just store the three fields separately and combine when needed.  Among other things, this way should be faster.

### CODE REVIEW

**Comment by yebblies** [comment]
Green now, a couple of assignments were missing their masks.

**Comment by 9rnsr** [comment]
LGTM.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Pull request merged**
