### PR TITLE
Revert "fix Issue 14246 - RAII - proper destruction of partially constructed objects/structs"

### PR DESCRIPTION
**Pull request by wilzbach**
This reverts commit 1e755c648e5142719d50dcf984f10ace5b8f8357 (#6816).

I just want to see if Jenkins would be green then or whether there are more hidden errors.

### CODE REVIEW

**Comment by wilzbach** [comment]
image

At least there's an end in sight for the regression goose hunt ;-)

**Comment by UplinkCoder** [comment]
@WalterBright @yebblies 
ping

**Comment by MartinNowak** [comment]
Ah thanks, hadn't seen it, closed in favor of #6913 which adds test cases.
BTW, can we adjust the thresholds for codecov to not complain about `-0.003%` changes?

**Comment by wilzbach** [comment]
> BTW, can we adjust the thresholds for codecov to not complain about -0.003% changes?

Nope, but see this issue for ideas:
https://github.com/dlang/dmd/pull/6879

**Pull request closed without merging**
