### PR TITLE
Visual studio solution should output a executable called "dmd.exe"

### PR DESCRIPTION
**Pull request by Ingrater**
The visual studio solution should behave like the dmd makefile and output a executable called "dmd.exe" instead of a executable called "ddmd.exe"

### CODE REVIEW

**Comment by rainers** [comment]
Although I don't really mind the actual name (I copy the file elsewhere in my build script anyway), why is it necessary to change this? It might break other people build scripts, too.

**Comment by Ingrater** [comment]
I personally think its neccessary because
1) Consitency. The executable name should match the makefile
2) Convenience: When adding the output path of the visual studio to your PATH you should be able to just call dmd instead of remembering to call ddmd and pass DMD=ddmd to each makefile.

**Review by wilzbach — APPROVED** [review]
I don't use Windows (and for that matter VS), but in spite of the recent "rebranding" to `dmd` I think it makes sense to do it here as well!

**Comment by rainers** [comment]
Now that the path of the VS projects has changed, build scripts will be broken anyway. So I'm fine with changing the target name. Some more changes to be considered:
- should changing the target name be implemented by changing the project name instead? This would be even more consistent.
- should we move the folder `vcbuild` out of `ddmd` (back to `src` so it sits alongside with the makefile)?
- we should change the output path to the common `generated` folder (it's currently a `generated` folder inside `vcbuild`).

**Comment by Ingrater** [comment]
> Now that the path of the VS projects has changed, build scripts will be broken anyway. So I'm fine with changing the target name. Some more changes to be considered:

I like all of the 3 proposed changes. I like all changes that make the visualD project behave more like the makefile.

**Comment by rainers** [comment]
I'm waiting for the dust to settle on the makefile changes before making the appropriate PR, e.g. it depends on where the ouptut of optabgen will be written to.

**Comment by rainers** [comment]
> I'm waiting for the dust to settle on the makefile changes before making the appropriate PR, e.g. it depends on where the output of optabgen will be written to.

See https://github.com/dlang/dmd/pull/6610

**Comment by WalterBright** [comment]
@rainers what is the status of this?

**Comment by rainers** [comment]
> @rainers what is the status of this?

Thanks for the remider, it can be closed.

**Pull request closed without merging**
