### PR TITLE
reboot 5750: fix Issue 9766 - align(n) with n compile-time constant

### PR DESCRIPTION
**Pull request by WalterBright**
This is a rebase of https://github.com/dlang/dmd/pull/5750/ since Kenji is away at the moment.

### CODE REVIEW

**Comment by WalterBright** [comment]
Don't pull it yet, I want to make a couple adjustments after I'm sure I didn't screw it up and it passes the autotester.

**Comment by WalterBright** [comment]
Ready to pull.

**Comment by UplinkCoder** [comment]
Looks good to me.

**Comment by rainers** [comment]
LGTM.

**Comment by rainers** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=16563

**Pull request merged**
