### PR TITLE
Issue 15581: Disabling bounds checking in ForEachStatement

### PR DESCRIPTION
**Pull request by gchatelet**

### CODE REVIEW

**Comment by gchatelet** [comment]
@jpf91 if you want to have a look :)

**Comment by jpf91** [comment]
Nice. LGTM, but I'm not a DMD developer ;-)

**Comment by gchatelet** [comment]
@WalterBright @9rnsr can you guys have a look?

**Comment by 9rnsr** [comment]
When the key variable is annotated with `ref`, it can be modified inside foreach body.

```d
int[] arr = [1,2,3];
foreach (ref i, v; arr) { i = 128; }
```

In that case, bounds check should not be disabled.

**Comment by gchatelet** [comment]
@9rnsr so basically if there's aliasing on either the index or the container within the loop we can't remove the bounds checking. Any other reasons why this is not correct ?

**Comment by yebblies** [comment]
The container (in the case of an array) is copied at the start of the loop, so the bounds cannot change.  It's worth noting that we propagate the bounds range to the index variable when it's immutable.  (I think that got in)

**Comment by 9rnsr** [comment]
OK, this is possible improvement. The internally generated index access is always done after the loop condition check. And as @yebblies said, the iterated static/dynamic array boundaries are fixed at the start of foreach loop. So we can throw away the boundary check.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by gchatelet** [comment]
Thx for the review. This will enable a `@safe` **and** performant code for D-Programming-Language/phobos#3916.

**Pull request merged**
