### PR TITLE
Remove -dip1000 influence on immutable conversion

### PR DESCRIPTION
**Pull request by dkorpel**
I probably need to figure out a deprecation path for this somehow, but first let's see what on buildkite breaks

### CODE REVIEW

**Comment by thewilsonator** [comment]
Is this good to go?

**Comment by dkorpel** [comment]
Yes

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
You might want to rebase to see if that fixes build kite.

**Comment by dkorpel** [comment]
It's already rebased on the latest master

**Comment by thewilsonator** [comment]
Hmm, is build kite not picking up https://github.com/libmir/mir-algorithm/commit/88d99b60e783167356e06683b1ce6d1a797ea089 

cc @9il That commit was supposed to fix that error?

Nit sure about the vibe error. Looks unrelated.

**Comment by 9il** [comment]
Oh, working on the fix.

**Comment by 9il** [comment]
Fixed in master / v3.12.47

**Comment by Geod24** [comment]
Vibe error is unrelated and getting fixed.

**Pull request merged**
