### PR TITLE
fix Issue 20781 - Can call @live function without checking dip1021 rules

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
The buildkite and DAutoTest look irrelevant.

**Comment by Geod24** [comment]
I haven't been following `@live` too much, so I was under the impression that it was part of DIP1021, but it's not mentioned anywhere in the DIP, or any other DIPs... So where does it come from ?

**Review by atilaneves — APPROVED** [review]

**Comment by Geod24** [comment]
So my question wasn't answered. What's the point of `-preview=dip1021` when it the checks are actually performed when `@live` is used ?

**Review by MoonlightSentinel — DISMISSED** [review]
Should adress https://github.com/dlang/dmd/pull/11071#issuecomment-621803039

**Comment by WalterBright** [comment]
@Geod24 :

As the comment in the code says, "Test compliance with DIP1021 Argument Ownership and Function Calls", and the code is under the check for DIP1021

**Comment by WalterBright** [comment]
Dip1021 was a step towards @live by not allowing multiple mutable pointers to be passed to a function.

**Comment by WalterBright** [comment]
This makes no sense at all:
```
Test 'runnable/test20855.d' failed. The logged output:
/private/var/folders/hy/gdmd645x1ws410vx266t7py00000gn/T/cirrus-ci-build/generated/osx/release/64/dmd -conf= -m64 -Irunnable  -fPIC  -odtest_results/runnable -oftest_results/runnable/test20855_0  runnable/test20855.d 
test_results/runnable/test20855_0  --DRT-testmode=run-main
core.exception.AssertError@runnable/test20855.d(25): Assertion failure
----------------
??:? _d_assertp [0x10060340c]
??:? _Dmain [0x1005f56d1]
a = 491
```
why does it work on every other platform?

**Comment by WalterBright** [comment]
Weird how that assert failure disappeared after a rebase. It implies the state of the repository is not always in a working state.

**Pull request merged**
