### PR TITLE
Revert "cache file lookup of importc.h"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/dmd#15989

### CODE REVIEW

**Comment by WalterBright** [comment]
Why?

**Comment by ibuclaw** [comment]
> Why?

To add some references to possibly overlooked reviews.

https://github.com/dlang/dmd/pull/15988#discussion_r1440087549
https://github.com/dlang/dmd/pull/15989#issuecomment-1875018399

1. Introduces an import of a back-end module, so compiler fails to build from source.
The missing module and function can be stubbed, but then all ImportC tests fails due to...
2. Introduces a dependency on a header that only exists for dmd.
The error `cannot find "importc.h"` is correct, there is no header file needed to be read in (no need to invoke an external command either).

This cpreprocess interface is becoming increasing the wrong tool for the job.  GDC doesn't depend on a third-party preprocessor, it _is_ the preprocessor.  Before this change, it could get along with faking it by dumping the C files preprocessed in-memory to a temporary file which the D front-end (almost redundantly) reads back into memory again.

I've been trying to think of a way to reconcile that dmd wants to deal with / return a `FileName` for the Module, but it is more natural for gdc to deal with / return a `const(ubyte)[]` buffer when it comes to ImportC. I'd prefer to deal with this starting from a place where things just work, rather than doing something in anger because it's broken.

**Comment by maxhaton** [comment]
> > Why?
> 
> To add some references to possibly overlooked reviews.
> 
> [#15988 (comment)](https://github.com/dlang/dmd/pull/15988#discussion_r1440087549) [#15989 (comment)](https://github.com/dlang/dmd/pull/15989#issuecomment-1875018399)
> 
> 1. Introduces an import of a back-end module, so compiler fails to build from source.
>    The missing module and function can be stubbed, but then all ImportC tests fails due to...
> 2. Introduces a dependency on a header that only exists for dmd.
>    The error `cannot find "importc.h"` is correct, there is no header file needed to be read in (no need to invoke an external command either).
> 
> This cpreprocess interface is becoming increasing the wrong tool for the job. GDC doesn't depend on a third-party preprocessor, it _is_ the preprocessor. Before this change, it could get along with faking it by dumping the C files preprocessed in-memory to a temporary file which the D front-end (almost redundantly) reads back into memory again.
> 
> I've been trying to think of a way to reconcile that dmd wants to deal with / return a `FileName` for the Module, but it is more natural for gdc to deal with / return a `const(ubyte)[]` buffer when it comes to ImportC. I'd prefer to deal with this starting from a place where things just work, rather than doing something in anger because it's broken.

Does LDC not have this header?

**Comment by ibuclaw** [comment]
> > 1. Introduces an import of a back-end module, so compiler fails to build from source.
> 
> Does LDC not have this header?

Module?

Doubt it, dmd.cpreprocess pulls in link and vsoptions.

**Comment by maxhaton** [comment]
https://github.com/ldc-developers/ldc/blob/530d41be11e92901f797ebbbc1dc695df4af06e9/runtime/druntime/src/importc.h#L14

**Comment by ibuclaw** [comment]
> https://github.com/ldc-developers/ldc/blob/530d41be11e92901f797ebbbc1dc695df4af06e9/runtime/druntime/src/importc.h#L14
> 

I guess they don't get a cpp library from clang/llvm then.
```
builtin_define_with_int_value("__IMPORTC__", 1);
```

**Comment by thewilsonator** [comment]
FWIW LDC uses https://github.com/ldc-developers/ldc/blob/master/driver/cpreprocessor.cpp

**Pull request merged**
