### PR TITLE
Expression.copy should use allocmemory

### PR DESCRIPTION
**Pull request by UplinkCoder**
Since it's never freed anyway.
`xmalloc` and `xfree` are only supposed to be used in temporary allocations.
This reduces compile-times for template heavy projects by roughly 5-10% (probably 1-2% in the real world) based on my measurements.
(This 5-10% relating to frontend time only! (compiling with `-o-`))

### CODE REVIEW

**Comment by thewilsonator** [comment]
> 5-10%

Impressive!

**Review by thewilsonator — APPROVED** [review]

**Comment by UplinkCoder** [comment]
Whoops. Somebody does free this it seems?

**Comment by UplinkCoder** [comment]
Interestingly all the buildkite projects pass with this patch I am having a hard time reproducing what's going on

**Comment by MoonlightSentinel** [comment]
Seems like a problem with `-lowmem` because most the older CIs fail to compile `d_do_test` using the generated compiler. 

Additionally, `runnable\xtest46_gc.d` fails on Windows32-OMF` which also uses `-lowmem`.

**Comment by UplinkCoder** [comment]
I suspect that the the compiler at some point depends on the Expression being null ....

**Comment by UplinkCoder** [comment]
@MoonlightSentinel you seem to be correct ... without the `-lowmem` switch it works.
Where have you seen it fail because of that before?

**Comment by MoonlightSentinel** [comment]
Nowwhere, I just recently changed the Makefile to use the host dmd when compiling the test runner (if it supports `-lowmem`). Looking at the CI logs made it pretty obvious that the segmentation fault for `d_do_test` occured whenever the generated dmd was used.

`runnable\xtest46_gc.d` seems to confirm my suspicion.

**Comment by UplinkCoder** [comment]
@MoonlightSentinel could you revert that change please?

**Comment by MoonlightSentinel** [comment]
No,i just changed that the generated dmd is just used as a fallback in case of an ancient host dmd. `d_do_test` is compiled with `-lowmem` since  quite some time because it was likely to end up OOM.

Anyway, that would just be a workaround for a regression introduced by this patch.

**Comment by UplinkCoder** [comment]
I am not so sure that this introduces the regression, I think triggers a bug in lowmem

**Comment by UplinkCoder** [comment]
since xfree is nerver called on the xmallocd expressions, running the GC can actually free things here which may appear unreferenced

**Comment by MoonlightSentinel** [comment]
> I am not so sure that this introduces the regression, I think triggers a bug in lowmem

Maybe not the best choice of words but that's missing the point. This error occurs reliably for high memory compilations on probably low memory systems and needs to be fixed before this can be merged.

**Comment by UplinkCoder** [comment]
@MoonlightSentinel confirmed when running the test with `--DRT-gcopt=disable:1` the crash does not occur

**Comment by rainers** [comment]
`allocmemory` is the lowlevel non-GC version. `_d_allocmemory` should work instead. For bonus points use `_d_newclass` with the proper classinfo which would allow precise collection.

**Comment by UplinkCoder** [comment]
@rainers hmm yes this is one of the place where collection might actually occur.

**Comment by UplinkCoder** [comment]
@rainers thanks for you help!

**Comment by rainers** [comment]
BTW: there is a similar copy in class Type. Maybe these explain some of the leaks when using the frontend with a precise GC.

**Comment by WalterBright** [comment]
Need to add comment why this function is being used.

**Comment by rainers** [comment]
I wonder why this passes on Semaphore: `OVERRIDE_MEMALLOC` is false for GDC, so there is no declaration of `_d_allocmemory` (although there is the default implementation in rt.lifetime).

Maybe it would be better to add a function to `Mem` that also conveys the intent, e.g. `xmalloc_neverfree`. That could be used in a number of places.

**Comment by UplinkCoder** [comment]
> Maybe it would be better to add a function to Mem that also conveys the intent, e.g. 
> xmalloc_neverfree. That could be used in a number of places.

that would have to be used in all the places where `allocmemory` is used.
since that's how it's been used as opossed to xmalloc and xfree which is for things with defined lifetime

**Comment by kinke** [comment]
> Maybe it would be better to add a function to Mem that also conveys the intent, e.g. xmalloc_neverfree.

Absolutely. And stating in the comment that it can't be xrealloc'd either. And that it's used for a speed-up without `-lowmem` (or the frontend as a library), because the tiny individual mallocs are replaced by the paged allocation scheme.

**Comment by kinke** [comment]
> that would have to be used in all the places where allocmemory is used

It's only used in the `Mem` struct itself (at least in the frontend), and those lines seem not to need any adaptations after a quick glance.

**Comment by UplinkCoder** [comment]
@WalterBright I've just added a comment.
Would you like me to reword it, or can it go in.

**Review by rainers — DISMISSED** [review]
I think the comment is too verbose now, something like "memory never freed, so can use the faster bump-pointer-allocation" should be enough.

I'd prefer moving that into Mem with the separate function `xmalloc_neverfree` or similar, though (no comment required here in that case). `allocmemory` and  `_d_allocmemory` should be considered private and even annotated that way (does not have to be in this PR).

**Comment by UplinkCoder** [comment]
The only point of _d_allocmem is to use the faster allocator, why wouldn't
it be enough to give allocmem/_d_allocmem a ddoc comment stating that?

Am Fr., 3. Apr. 2020 um 09:15 Uhr schrieb Rainer Schuetze <
notifications@github.com>:

**Comment by rainers** [comment]
> The only point of _d_allocmem is to use the faster allocator, why wouldn't it be enough to give allocmem/_d_allocmem a ddoc comment stating that?

`_d_allocmemory` is a very special function that in called compiler generated code and is usually implemented in rt.lifetime: https://github.com/dlang/druntime/blob/eb6911eeb4f632d42abe4e28f5030158c9e7af52/src/rt/lifetime.d#L65

In addition it is only conditionally defined in dmd.root.rmem (where it replaces the version from the runtime library).

**Comment by UplinkCoder** [comment]
@rainers I see now.

thanks. Then I agree we should have a function called fastAlloc_nofree or something like that.

**Comment by thewilsonator** [comment]
`ERROR: Error - file '/src/dmd/expression.d' contains tabs at line 698`

**Comment by ibuclaw** [comment]
> In addition it is only conditionally defined in dmd.root.rmem (where it replaces the version from the runtime library).

Indeed, this PR broke the builds for GDC.

**Comment by UplinkCoder** [comment]
Sorry about that @ibuclaw

**Pull request merged**
