### PR TITLE
[REG 2.067] fix Issue 14133 - struct ctor init compiles very slow and produces excessive amounts of code

### PR DESCRIPTION
**Pull request by MartinNowak**
- also use init array for default constructed struct literals
- don't kill struct literal initializer in e2ir.c
  - we now select the appropriate initializer in the frontend
  - this was added in 3f88f15, it's unclear why though

[Issue 14133 – [REG 2.067] struct ctor init compiles very slow and produces excessive amounts of code](https://issues.dlang.org/show_bug.cgi?id=14133)

### CODE REVIEW

**Comment by MartinNowak** [comment]
Don't know why the struct literal initializer code is duplicated and spread across src/expression.c and src/mtype.c. It should be fairly simple to move this into defaultLiteral or so.

**Comment by 9rnsr** [comment]
Maybe this is not correct. If a field of the construced struct is nested struct, it will have null hidden field and. 

At least one of the "excessive codegen" problems is in fillHole() function. Optimizing its codegen will fix your issue case.

**Comment by MartinNowak** [comment]
But we don't assign `sinit` for nested structs. There is always a `&& !t1->needsNested()`.
Of course fixing the codegen would be nice, as the bug still persists for nested structs. I don't think my time permits for that.

**Comment by 9rnsr** [comment]
Ah. I missed that `needsNested()` is used.

But, this PR will break following code.

```d
struct S14133a
{
    bool val;
    size_t[16 * 1024] data;
}

void main()//test14133()
{
    auto a = S14133a(true);
    assert(a.val);
}
```

Setting `sinit` ignores literal arguments completely.

**Comment by 9rnsr** [comment]
A most easy way is replacing the excessive fillHole code with a `OPmemset` IR with zero value.

it's still not efficient, but generated code amount will be reduced.

**Comment by 9rnsr** [comment]
Sorry, I'll go to bed (My clock is 0:40 AM JST). Will come back tomorrow.

**Comment by MartinNowak** [comment]
Sleep well :)

**Comment by MartinNowak** [comment]
In the tests we should compare RIP before and after the ctor and fail if to many instructions were generated.

**Comment by 9rnsr** [comment]
@MartinNowak I opened #4508.

**Comment by MartinNowak** [comment]
> Setting sinit ignores literal arguments completely.

Ah, I missed that struct literals (not calling a ctor) might still have arguments.

**Pull request closed without merging**
