### PR TITLE
Better solution to issue 7951 - Solve the root problem

### PR DESCRIPTION
**Pull request by SSoulaimane**
Array operations require moving the SIMD vector out of the SIMD register.

Previous solution: https://github.com/dlang/dmd/commit/bba8e8faa1ab09f2b87fad00e47f46ae6bb91c22.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by JinShil** [comment]
cc @WalterBright  Kindly requesting your review.

**Review by JinShil — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
@ZombineDev  please note this in https://issues.dlang.org/show_bug.cgi?id=7951

**Review by WalterBright — APPROVED** [review]

**Comment by thewilsonator** [comment]
Should be done automatically by the bot that posts stuff to bugzilla from github.

**Comment by thewilsonator** [comment]
It was.

**Pull request merged**
