### PR TITLE
Proposal: Add application hooks

### PR DESCRIPTION
**Pull request by redstar**
One theme at DConf was the unification of the frontends.
("One frontend to rule them all")
One source of differences in the frontend are compiler-specific
extensions. An easy way to support this is the addition of hooks.
An application may (or may not) use these hooks for additional
processing.

This hook was inspired by a current PR (https://github.com/ldc-developers/ldc/pull/1434).
LDC-specific pragmas could be realized with the same approach.

### CODE REVIEW

**Comment by redstar** [comment]
@WalterBright @yebblies @klickverbot @ibuclaw @JohanEngelen Please destroy!

**Comment by yebblies** [comment]
Can we stick this into `Global` instead?  I'm wary of creating yet another module that's imported by and imports everything.

**Comment by WalterBright** [comment]
> Please destroy!

Ok, you asked for it! Runtime hooking is for runtime plugins. I don't see any prospect of this happening for  backends for dmd. It's compile time.

Compile time plugins are very simple, just add a call to something like "backEndSpecificCodeForFeatureX()" and then implement it in a different module for each back end. The binding happens when the specific import is chosen at compile/link time.

Target specific members can be added to structs using template mixins. That's what template mixins are ideal for.

**Comment by yebblies** [comment]
> Target specific members can be added to structs using template mixins. That's what template mixins are ideal for.

That is far less than ideal.

**Comment by redstar** [comment]
I now isolated the function in a new module. I can also add a `static if (__traits(compile, ...))` to the code - then there would be no penalty for DMD. For a backend like LDC this would be enough. Is this also a solution for a library version of the frontend?

**Comment by WalterBright** [comment]
> That is far less than ideal.

Rationale?

**Comment by yebblies** [comment]
> Rationale?

Never mind, I think I misunderstood what you were saying.

My main concern is that this is a very generic place to put it.  `Target` doesn't seem right, maybe we could promote `Global.compiler` into a similar construct and put it there?

What are we expecting to use this for?  Traits, pragmas, builtins?  Maybe inline asm support?  Can we come up with a meaningful grouping instead of a grab-bag of hooks?

**Comment by ibuclaw** [comment]
> What are we expecting to use this for? Traits, pragmas, builtins?

I can imagine traits and pragmas being the main use-case for this - though it comes 3 years too late for pragmas, as I have long since replaced GNU pragmas with UDAs.

> Maybe inline asm support?

Maybe the parser for inline asm. The other parts are appropriately encapsulated I think.

**Comment by ibuclaw** [comment]
> One theme at DConf was the unification of the frontends.

This is the theme at every Dconf. :-)

**Comment by redstar** [comment]
> What are we expecting to use this for? Traits, pragmas, builtins? Maybe inline asm support?

Traits, pragmas and builtins are the minimal requirement.

> Can we come up with a meaningful grouping instead of a grab-bag of hooks?

I currently try to find a good interface for pragmas. I am open to ideas.

> My main concern is that this is a very generic place to put it. `Target` doesn't seem right, maybe we could promote `Global.compiler` into a similar construct and put it there?

Sounds like a logical place.

**Comment by yebblies** [comment]
Sounds reasonable.  I don't think we need to merge this until the first use is upstreamed.

**Comment by JohanEngelen** [comment]
>  until the first use is upstreamed.

I think this _is_ the first upstreamed use :)

**Comment by yebblies** [comment]
> I think this is the first upstreamed use :)

It doesn't count as compiler code until it allocates a bunch!

**Comment by WalterBright** [comment]
This is a better design than the pointer version.

**Comment by JohanEngelen** [comment]
Ping @yebblies @WalterBright

**Comment by UplinkCoder** [comment]
@redstar you have to add hooks.d to the makefile if you want the tests to pass.

**Comment by JohanEngelen** [comment]
This is now used in LDC: https://github.com/ldc-developers/ldc/pull/1434

**Comment by yebblies** [comment]
Yeah I'll merge this.  Need to update the makefiles first.

**Comment by ibuclaw** [comment]
My response to the bikeshed discussion is to either call it `langhooks.d` or `compiler.d`.  I also prefer static functions in a struct over free functions.

**Comment by wilzbach** [comment]
> Yeah I'll merge this. Need to update the makefiles first.

ping @redstar ;-)

**Comment by JinShil** [comment]
Are people still interested in this?  Should I revive it and update the makefiles?

**Comment by ibuclaw** [comment]
I've still had the idea kicking around to add a `struct Compiler`

**Comment by JinShil** [comment]
Closing due to lack of a clear direction and a champion to take it forward.

**Pull request closed without merging**
