### PR TITLE
rename -transition=safe to -dip1000

### PR DESCRIPTION
**Pull request by WalterBright**
Nothing says "preview" better than "dip????"

### CODE REVIEW

**Comment by UplinkCoder** [comment]
what about `-transition=scope`
Since that says what it is rather then referring to a dip which requires another lookup ?

**Comment by WalterBright** [comment]
Some people strongly argued against `-transition=scope`

**Comment by WalterWaldron** [comment]
The link provides no information, perhaps mentioning https://github.com/dlang/DIPs is more appropriate.

**Comment by andralex** [comment]
cc @MartinNowak

**Pull request merged**
