### PR TITLE
Issue 14906 - dmd dumps core at incorrect enum declaration

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14906

### CODE REVIEW

**Comment by yebblies** [comment]
Please add the test case
```
enum X;
void f14906(X3) {}
```
which should be the same

**Comment by 9rnsr** [comment]
@yebblies Do you mean the `X3` is undefined identifier? or `X[3]`? I'll add one more test case for the latter.

**Comment by 9rnsr** [comment]
Done.

**Comment by yebblies** [comment]
Sorry, I meant `X[3]`.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks!

**Pull request merged**
