### PR TITLE
remove Visitor from toElem()

### PR DESCRIPTION
**Pull request by WalterBright**
This is rather large because I had to move some largish functions, because nested functions cannot be forward referenced.

### CODE REVIEW

**Comment by RazvanN7** [comment]
Is this large reshuffling really worth it? I guess the expectation is that you will obtain a speed-up, however, I think that we should somehow measure this, otherwise, destroying the git history really isn't worth it.

**Comment by WalterBright** [comment]
Yes, because:
1. Cannot add attributes with the Visitor pattern. Like const, nothrow, @safe, etc.
2. The Visitors are confusing. Do they traverse depth first, breadth first, just the top level, stop when found, top level only?
3. I'm always left wondering what happens to the expression nodes I didn't put a case for. Do they get traversed?
4. It's not just me that finds them confusing. I've fixed uses added by others that got it wrong.
5. Having the logic spread across several modules just to traverse is a constant pain to deal with.
6. And yes, it's slower

I agree it's unfortunate I had to move 3 large member functions due to forward referencing, otherwise the diff is quite minimal. If you like, I can move them with a separate PR. The actual changes are very minimal.

As for git history, well, we have all learned to deal with that by now. There have been so many changes over the years, `git blame` rarely points me to where code originated from anyway. I have to move back in time multiple jumps.

**Comment by dkorpel** [comment]
> I agree it's unfortunate I had to move 3 large member functions due to forward referencing, otherwise the diff is quite minimal. If you like, I can move them with a separate PR. The actual changes are very minimal.

That would be helpful, 3600 lines is quite the diff.

**Comment by WalterBright** [comment]
And there it is. Not much different.

**Review by dkorpel — APPROVED** [review]
Thanks for making the diff reviewable! I dislike the visitor pattern too.

**Pull request merged**
