### PR TITLE
cod2.d: add some const and =void

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by Basile-z** [comment]
I'm not a big fan of the `= void`s. In binary code without them this is usually just a `xor reg, reg`, so I'd keep them, although it looks like they can be void init *for now*.

**Comment by WalterBright** [comment]
> I'm not a big fan of the = voids

It's a largish struct, and it's there for performance reasons. It's well tested, as it came from C.

**Comment by Basile-z** [comment]
> It's a largish struct

ok this is more justified then.

**Review by ghost — APPROVED** [review]

**Comment by Basile-z** [comment]
I should have noticed the access to the members, following the decl...

**Review by atilaneves — APPROVED** [review]

**Pull request merged**
