### PR TITLE
Implement visitor for semantic2 functions

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by ZombineDev** [comment]
@RazvanN7 thanks a lot for taking the effort to split your PR into individual commits, much appreciated!

**Comment by RazvanN7** [comment]
@ZombineDev There was no effort at all. Thanks for the tip

**Comment by andralex** [comment]
cc @WalterBright

**Comment by andralex** [comment]
@RazvanN7 please rebase

**Comment by WalterBright** [comment]
Why was this closed?

**Comment by RazvanN7** [comment]
@WalterBright  It was easier to create a new PR with the exact changes as this one than to rebase [1].

[1] https://github.com/dlang/dmd/pull/7122

**Comment by WalterBright** [comment]
makes sense

**Pull request closed without merging**
