### PR TITLE
extend tracking to pointer-like variables

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
How wierd. failob1 generates errors on my machine, and no errors on any of the test machines?

**Comment by WalterBright** [comment]
Uh-oh. Looks like someone broke the `attribute { ... }` syntax. When did that happen?

**Comment by Geod24** [comment]
Isn't your testcase just missing `@safe` ?

**Comment by WalterBright** [comment]
> Isn't your testcase just missing @safe ?

No. @live is orthogonal to @safe. If you plop @live in front of each function, it works, but with the { } syntax, it doesn't work. That seems to have been broken fairly recently in dmd.

**Comment by PetarKirov** [comment]
@WalterBright it seems this PR addresses https://issues.dlang.org/show_bug.cgi?id=17764 (considering that the test case is modified to include `@live` in addition to `@safe`), can you confirm?

**Pull request merged**
