### PR TITLE
drop support for pre pentium pro cpus

### PR DESCRIPTION
**Pull request by benjones**
From what I can tell, target cpu is hardcoded to be pentium pro.  I'm planning to get rid of all the special casing for ancient x86 CPUs in the backend.  I can't imagine anyone is using DMD for those targets and I assume those codepaths aren't exercised currently.

### CODE REVIEW

**Comment by benjones** [comment]
Here's the only place where I could find it being assigned:

```
compiler/src/dmd/backend/backconfig.d
90:    if (!cfg.target_cpu)
91:    {   cfg.target_cpu = TARGET_PentiumPro;
92:        cfg.target_scheduler = cfg.target_cpu;
```

**Comment by rikkimax** [comment]
This should probably wait for https://github.com/dlang/dmd/pull/16422

Once its in, there shouldn't be a way to use these targets.

**Comment by benjones** [comment]
> This should probably wait for #16422
> 
> Once its in, there shouldn't be a way to use these targets.

I'm pretty sure they're already inaccessible.  The cpu_target gets hardcoded to Pentium Pro and isn't assigned to anywhere I can find (grepping for TARGET_Pentium doesn't return any code that assigns that value anywhere)

**Review by dkorpel — APPROVED** [review]

**Review by RazvanN7 — APPROVED** [review]

**Comment by WalterBright** [comment]
Sigh. I wish you'd ask me before deleting code gen support. The pentium pro support is still valid today.

I remember a while back when a change was made that wound up disabling support for putting XMM values in registers. I found out about it about 6 months later when there was a thread about how terribly slow dmd was with XMM code. This got by the autotester because there isn't a straightforward way to test if the compiler made the best optimizations or not, only if the code works.

**Comment by benjones** [comment]
I was hoping you'd review it before it got merged.

I believe my PRs have been removing effectively dead code only. As I
mentioned I believe the target cpu is hard coded to be Pentium pro and the
code I deleted was for CPUs older than that.

**Comment by maxhaton** [comment]
> Sigh. I wish you'd ask me before deleting code gen support. The pentium pro support is still valid today.

Does this not keep the support for the pentium pro? I was under the impression it's for the truly ancient stuff — e.g. isn't there a scheduler for the dual pipeline x86 chips (which are are as dead as dead can be) in there.

> I remember a while back when a change was made that wound up disabling support for putting XMM values in registers. I found out about it about 6 months later when there was a thread about how terribly slow dmd was with XMM code. This got by the autotester because there isn't a straightforward way to test if the compiler made the best optimizations or not, only if the code works.

FYI the way LLVM does this is by having good string matching support (FileCheck) and then being extremely anal about the output (i.e. the typical test is read not run).

**Comment by WalterBright** [comment]
> the way LLVM does this is by having good string matching support (FileCheck) and then being extremely anal about the output (i.e. the typical test is read not run).

I tried that at one point. It consumed a great deal of time with false trips, because the output of the code generator is extremely sensitive to any change in any part of it.

**Pull request merged**
