### PR TITLE
Split interfaces to the glue layer and backend into different files

### PR DESCRIPTION
**Pull request by yebblies**
And add make rules to build a backendless dmd.

In order to generate header files for dmd, I need a working dmd binary with the c++ header generation enabled.  Until the frontend headers are built it's impossible to build the dmd glue layer or backend.

So the steps are:
- Build a frontend-only version of dmd with C++ header support
- Generate the headers
- Build the full version of dmd

This process will let us move to generated headers without changing build dependencies.

### CODE REVIEW

**Comment by yebblies** [comment]
See also #5082

**Comment by ibuclaw** [comment]
I would prefer the idea of ``ddmd.backend`` to be a package containing what you've decided to call ``gluelayer``, then have ``ddmd.backend.dmd`` as the place to keep your backend-proper.

**Comment by yebblies** [comment]
What would that gain?  I don't see the point.

I'm thinking about splitting out the 'driver' code (mars, lib*, scan*, inifile, link etc) from the rest of the frontend, and as you know I'd like to ban glue/backend references from the rest of the frontend.

**Comment by ibuclaw** [comment]
Well, apart from ``gluelayer`` looking aesthetically unpleasing to my eyes... :-)

It could be at least be used as a connector for alternate backends, eg, ``ddmd.backend.gdc`` being where I put references to my functions, types, symbols, and so on...

As for the ban on references, I'm certainly not against the idea of using a common name/alias for backend types so long as they have a consistent naming scheme.
eg:
```
version (DM_Backend)
{
    alias Btype = TYPE;
    alias Bsymbol = Symbol
}
version (GCC_Backend)
{
    alias Btype = tree;
    alias Bsymbol = tree;
}
```
And so on...

**Comment by yebblies** [comment]
> Well, apart from `gluelayer` looking aesthetically unpleasing to my eyes... :-)

This of it as temporary!

The problem with the current system of using `type`/`Symbol`/etc is that's it's not enough.  Some backends need members in more ast classes, some need less...  If we really want to have the frontend as a re-usable library, then we really should be removing the backend references IMO.

**Comment by 9rnsr** [comment]
I can accept this temporary vhange, after the Darwin_64_32 breaking is fixed.

**Comment by yebblies** [comment]
@9rnsr Updated.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Pull request merged**
