### PR TITLE
make D great again

### PR DESCRIPTION
**Pull request by adamdruppe**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Description + changelog/issue# please.

**Comment by adamdruppe** [comment]
https://issues.dlang.org/show_bug.cgi?id=14835
https://issues.dlang.org/show_bug.cgi?id=10532

less directly:

https://issues.dlang.org/show_bug.cgi?id=16201
https://issues.dlang.org/show_bug.cgi?id=20522


It is hard to use D's metaprogramming capabilities without this warning issuing a false positive and forcing you to degrade the code to work around it.

**Comment by thewilsonator** [comment]
So if this fixes any of those, the commit message should say so, you know the drill.

**Comment by rikkimax** [comment]
Alternative: disable it for scopes that use static if and static foreach.

**Comment by 0xEAB** [comment]
This warning sounds great and useful in theory, but:
Practice shows it’s an obstacle most of the time. (Even when we ignore the false positives!)

I can think of maybe one occasion where it actually helped me prevent a buggy program from compiling. On the other hand I could regularly tell tales how it gets in my way.

Unlike with bigger C projects, most D projects are written in a “no warnings” way. This is established well enough that even DUB defaults to emitting the `-w` flag (“Treat warnings as erros”). So, false positive or not, what happens when you run into the “statement not reachable” warning? Yeah, you go and edit your build recipe. Inconvenient :/

—
When it’s not a false positive, it’s still often useless, because code works as intended.

So, let’s say, I’ve hit the warning because I’ve added temporary debugging code to my program. Maybe a quick `assert(false);` to stop execution from going beyond a certain point, a patchy throw statement with a different msg or a return statement to short-circuit things with a different return value. Or whatever… I know what I’m doing here (hopefully), I won’t forget to remove the temp code. But I’ll trigger the warning.
Well, time to interrupt my flow. Gotta add `--wi` for the debugging session. Just to remove it later (or forget to do so).

**Comment by pbackus** [comment]
This isn't just a problem with `static foreach` and `static if`. One of the most annoying instances of this warning I've run into was in code of the form

```d
unittest
{
    assert(cond1);
    assert(cond2);
}
```

If the compiler is able to constant-fold `cond1` to `false`, it will declare the second assertion unreachable. Under default `dub` settings, this halts compilation, which makes it impossible to run the rest of the test suite until that specific assertion i fixed.

**Comment by 0xEAB** [comment]
Another interesting finding is that the warning is not emitted for code like this:
```d
return;
assert(false);
```

You wouldn’t (have to) special case this if the thing weren’t kinda low-value in the first place.

**Comment by ljmf00** [comment]
This is pretty much a linting rule that we are forced to use without just disabling all the warnings. I think this is worth keeping, if we have a way to select which rule to warn us.

**Comment by tgehr** [comment]
Test suite has to be updated.

**Review by dkorpel — APPROVED** [review]
Discussed in the September monthly meeting, remove warning but leave code in for now

**Comment by thewilsonator** [comment]
again, changelog entry or issues fixed please.

**Comment by thewilsonator** [comment]
merge conflict

**Comment by dkorpel** [comment]
> Third commit does more than convert tabs to spaces.

Yeah something went wrong when rebasing on top of https://github.com/dlang/dmd/pull/15623

**Review by thewilsonator — APPROVED** [review]

**Comment by ljmf00** [comment]
Don't forget to merge with squash.

**Pull request merged**
