### PR TITLE
Revert "Move a couple of functions out of dsymbol.d"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/dmd#15789

### CODE REVIEW

**Comment by maxhaton** [comment]
Did it cause a regression?

**Review by thewilsonator — CHANGES_REQUESTED** [review]
No, it did not. https://github.com/dlang/dmd/pull/15789#issuecomment-1807133416

The correct course of action there is to put is some where it does belong, not put it back somewhere it is not desired to be.

**Comment by dkorpel** [comment]
@ibuclaw Why did you merge this without explanation or approval?

**Comment by ibuclaw** [comment]
> @ibuclaw Why did you merge this without explanation or approval?

This has been blocking work for nearly two weeks now - I usually add gdc/blocking labels to such PRs, I thought I did here though now I see it's missing.

Change broke downstream gdc, so likely will break ldc too - typinf is a backend module, not a common frontend.

**Comment by thewilsonator** [comment]
> Firstly, typinf is a backend module, not a common frontend.

Not true: LDC uses it, so I doubt this will break LDC. as I said before if there is a different module you think this is better off residing, please go ahead and move it there, but please stop plating revert ping-pong.

> Secondly there's a cascading undefined references to the StringValue template, likely caused by the change of imports causing D semantic to discard it.

That does sound more problematic, please lead with that next time ;) . `git grep` tells me that `StringValue` is only ever used in `compiler/src/dmd/root/stringtable.d` I'm not sure what the cause of that would be.

**Comment by ibuclaw** [comment]
> That does sound more problematic, please lead with that next time ;) . `git grep` tells me that `StringValue` is only ever used in `compiler/src/dmd/root/stringtable.d` I'm not sure what the cause of that would be.

Old template emission bugs rarely make any sense in larger projects.

It's instantiated with `dmd.mtype.Type`, so it must be indirectly used by at least two modules.

**Pull request merged**
