### PR TITLE
backend.outbuf: Use offset instead of pointer

### PR DESCRIPTION
**Pull request by Geod24**
Split off #10932

### CODE REVIEW

**Comment by atilaneves** [comment]
I've learned the hard way that it's usually better to use an offset instead of a pointer, but why is this needed?

**Comment by WalterBright** [comment]
The reason a pointer is used instead of an offset because due to my extensive profiling years ago, a pointer is faster than a pointer+variable when appending data to a buffer.

**Comment by Geod24** [comment]
> I've learned the hard way that it's usually better to use an offset instead of a pointer, but why is this needed?

My intention was to make `Outbuffer` `@safe`. And to do that, the intention was to use a slice + offset (like the frontend's `OutBuffer`) instead of 3 pointers.

**Comment by WalterBright** [comment]
It doesn't need to be @safe itself, just have an @safe interface. Compiler performance is heavily dependent on Outbuffer, so it is ok for the implementation to be unsafe.

**Comment by Geod24** [comment]
Good point. Since `p` is `private` nowadays, that diff is indeed not required.

**Pull request closed without merging**
