### PR TITLE
Fix styling of if/while statements.

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/dlang/dmd/pull/8667

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by ibuclaw** [comment]
Weren't we introducing enforcement of style through some linter. @wilzbach?

**Comment by wilzbach** [comment]
Only for Phobos and only partially there because people objeced to large-scale reformatting.

**Comment by ZombineDev** [comment]
@wilzbach I thought the same, but the logs are somewhat contradicting: https://buildkite.com/dlang/dmd/builds/1370#645c7c73-470f-474f-8036-649110656dad

**Comment by wilzbach** [comment]
Well we do run dscanner here since a month or so, but only trivial points have been enabled so far and especially no code style checking :/

https://github.com/dlang/dmd/blob/master/src/.dscanner.ini

**Pull request merged**
