### PR TITLE
Bump host compiler for Azure Win64

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Current master seems to trigger an already fixed bug in the host compiler.
(Obviously not an ideal solution, just trying to unblock the CI for now.
We can always revert this later)

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]
It's fine to use newer bootstrap compilers on Azure as long as we still have one CI (Auto-Tester) that tests the same OS with the current bootstrap version (2.079)

**Comment by schveiguy** [comment]
ping @WalterBright this looks like it fixes the issue that you are looking at, no?

**Comment by schveiguy** [comment]
Do we know what the bug is that was fixed? It might be worth releasing a point revision on the old compiler to fix just this bug, and not have to up the major revision of the bootstrap compiler.

**Comment by MoonlightSentinel** [comment]
Not yet. but I can reproduce it locally using an official release binary.

Some observations:
- the segfaults happens for `-release`, not `-O -inline`
- the Azure configuration (`ARGS=-O -inline -g`) passes
- the segfault vanishes when I remove `-lowmem`

**Comment by WalterBright** [comment]
@MoonlightSentinel Thank you very much for finding the solution to this aggravating problem!

As for finding out what caused it, the only way is to do a binary search on the commits. But I suggest it is not a good use of your valuable time. It might be worthwhile to collect what you know about it and file a bugzilla for it.

**Comment by wilzbach** [comment]
> But I suggest it is not a good use of your valuable time.

Yes, it provides almost zero value as the respective GC bug has been fixed and that's why I don't think it should be posted on Bugzilla.

Bugzilla is already a graveyard and I don't see how this wouldn't be immediately closed in two years by the next person who looks at as it's not an active nor actionable issue.

**Pull request merged**
