### PR TITLE
RFC: add isForStatement

### PR DESCRIPTION
**Pull request by UplinkCoder**
I added `isForStatement` since at semantic3 there are an awful lot of ForStatements. 
And I could not figure out the visitor :smile: 

please comment on usefulness.

### CODE REVIEW

**Comment by WalterBright** [comment]
With no use cases, I don't see the point.

**Comment by UplinkCoder** [comment]
It is used in my ctfe-rewrite.
Since the CTFE-Visitor should not be an extern(C++) class.
And therefore cannot inherit from the Visitor.

**Comment by yebblies** [comment]
> Since the CTFE-Visitor should not be an extern(C++) class.

Why shouldn't it?

**Comment by UplinkCoder** [comment]
extern(C++) classes are hard to work with since I am not used to them.

**Comment by yebblies** [comment]
You can stick them in an AA, you just have to cast them to `void*` first...
They're worth getting used to, since most of dmd is designed around them.  You should certainly be using dmd's visitor classes.

**Comment by UplinkCoder** [comment]
Now that I have figured out the visitor this PR is unnecessary

**Pull request closed without merging**
