### PR TITLE
[project] Merge druntime into the dmd repository

### PR DESCRIPTION
**Pull request by ibuclaw**
Merges druntime into dmd using the merge subtree method, then fixes build script paths to work with new merged dmd-druntime repository

See https://github.com/dlang/projects/issues/92

### CODE REVIEW

**Comment by WalterBright** [comment]
Reviewing 300,000 lines of code is not possible.

**Comment by WalterBright** [comment]
What's with the 6 bugzilla references and what do they have to do with this PR?

**Comment by maxhaton** [comment]
> What's with the 6 bugzilla references and what do they have to do with this PR?

Not sure. At least one of them is a druntime issue that was filed against dmd, but the bot has not done anything with them on the issues.dlang.org side so no pollution there.

**Comment by ibuclaw** [comment]
> What's with the 6 bugzilla references and what do they have to do with this PR?

I wouldn't bother questioning the logic of dlang-bot.

**Comment by WalterBright** [comment]
> I wouldn't bother questioning the logic of dlang-bot.

They're all resolved as fixed, too. Perhaps dlang-bot has its supply voltage turned up too high? Maybe we should send @frankpoole to investigate?

**Comment by ibuclaw** [comment]
> > I wouldn't bother questioning the logic of dlang-bot.
> 
> They're all resolved as fixed, too. Perhaps dlang-bot has its supply voltage turned up too high? Maybe we should send @frankpoole to investigate?

Who you're gonna call? [@rayparkerjr](https://www.youtube.com/watch?v=Fe93CLbHjxQ)

**Review by WalterBright — APPROVED** [review]

**Pull request merged**
