### PR TITLE
make testclidflags independent of sc.ini/dmd.conf

### PR DESCRIPTION
**Pull request by rainers**

### CODE REVIEW

**Review by PetarKirov — APPROVED** [review]

**Comment by JinShil** [comment]
This was also done in #7937.  We could just merge that.

**Comment by rainers** [comment]
Ok, closing in favor #7937

**Comment by wilzbach** [comment]
I wonder why this is necessary though. `dmd.conf` is auto generated on Posix ...

**Comment by rainers** [comment]
> I wonder why this is necessary though. dmd.conf is auto generated on Posix ...

That doesn't happen on Windows AFAICT. My build script copies the compiler and the libraries elsewhere anyway so I can use it for other stuff besides testing, too.

**Pull request closed without merging**
