### PR TITLE
Issue 10084 - ICE(toir.c) alias template parameter

### PR DESCRIPTION
**Pull request by 9rnsr**
https://d.puremagic.com/issues/show_bug.cgi?id=10084

### CODE REVIEW

**Comment by 9rnsr** [comment]
Rebased on master, and ready for ddmd.

**Comment by JinShil** [comment]
I tried to revive this in #7383, but it breaks code.  I suggest this be closed.  Any objections?

**Comment by rainers** [comment]
If the ICE is still there, I'd recommend keeping this or the revived PR open, as it likely contains pretty good information where the likely cause is.
I suspect it is just missing a special case triggered by std.meta tests, maybe being evaluated inside a unittest, static if, is() or even the function literal.

**Comment by JinShil** [comment]
> If the ICE is still there, I'd recommend keeping this or the revived PR open, as it likely contains pretty good information where the likely cause is.

Ok, I reopened #7383 as @9rnsr doesn't appear to be active anymore,  I'm closing this as I don't see a reason for both to remain open.

**Pull request closed without merging**
