### PR TITLE
change codecov bot to dlang-bot

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by wilzbach** [comment]
thanks @MartinNowak, but shouldn't it be possible to directly set the bot for all repos in their web interface, e.g. https://codecov.io/account/gh/dlang/yaml ?

https://github.com/codecov/support/wiki/Codecov-Bot
https://github.com/codecov/support/issues/272

Btw we seem so have reached the rate limit for the Github API :/

> ++ jq -r .base.ref
./circleci.sh: line 55: CIRCLE_PR_NUMBER: unbound variable

**Comment by MartinNowak** [comment]
I'm not a team owner, so we can chose the simple path or ask @CyberShadow.
That CircleCI bug comes from using the same base repo I guess, it was dlang/dmd/MartinNowak-patch-1, move to my repo https://github.com/dlang/dmd/pull/6046.

**Comment by wilzbach** [comment]
> I'm not a team owner, so we can chose the simple path or ask @CyberShadow.

Fair enough ;-)

> That CircleCI bug comes from using the same base repo I guess, it was dlang/dmd/MartinNowak-patch-1, 

Ah I was just confused because at [Phobos](https://circleci.com/gh/dlang/phobos/6) I got a 403 :/

**Comment by CyberShadow** [comment]
> I'm not a team owner, so we can chose the simple path or ask @CyberShadow.

I'm fine with pushing more buttons. Which buttons need pushed?

**Comment by MartinNowak** [comment]
Apparently we could configure the account codecov uses to post statuses for all dlang repos here https://codecov.io/account/gh/dlang/yaml instead of configuring each repo.
```yaml
codecov:
  bot: dlang-bot
```

**Pull request closed without merging**
