### PR TITLE
simplify pureMalloc() and friends

### PR DESCRIPTION
**Pull request by WalterBright**
Remove complex and unnecessary wrappers & templates & dealing with errno.

### CODE REVIEW

**Comment by JinShil** [comment]
It appears all of that code is already in druntime:  https://github.com/dlang/druntime/blob/3a74100dc5a1b443b57468d6a5def3875573bf12/src/core/memory.d#L864

Can you just delete this code in DMD, use the druntime code, and then refactor the druntime code in the same manner if need be?

**Comment by WalterBright** [comment]
@JinShil if you can do an equivalent PR for druntime, I'll support it.

**Comment by JinShil** [comment]
> if you can do an equivalent PR for druntime,
I am overwhelmed with other things right now.  For now you can just change DMD to call the druntime implementation.

**Comment by n8sh** [comment]
@JinShil It's not clear that the same simplification would be appropriate when those functions are exposed as part of a library rather than used internally for a single application which could be verified to nowhere depend on `errno` remaining unchanged across calls to `malloc`.

**Comment by JinShil** [comment]
@n8sh I think there are two issues apparent in this code.  1) It is a duplicate of code in druntime 2) it is possibly excessively complex.

If @WalterBright is interested in cleaning up DMD, a simple solution is to delete all of this code in DMD and just call the druntime code; that will solve 1).   2) then becomes a druntime issue.  If the code in druntime cannot be simplified as proposed in this PR, that's fine; it's still no longer a DMD issue.

**Comment by WalterBright** [comment]
There's some debate about whether druntime should support errno changes with this or not. But that's not an issue for the compiler.

**Comment by JinShil** [comment]
> There's some debate about whether druntime should support errno changes with this or not. But that's not an issue for the compiler.

Yes, that is why I suggest calling the druntime functions and leave the debate for a future druntime PR.

**Comment by WalterBright** [comment]
This change should happen regardless of what happens with druntime. The reason is, of course, performance. The druntime replaces one function call with four, and malloc() is critical for speed.

**Comment by jacob-carlborg** [comment]
The reason why it's duplicated is because it was added to druntime after DMD 2.076.0. Which is the oldest version of DMD the compiler needs to be buildable with.

**Review by atilaneves — APPROVED** [review]

**Pull request merged**
