### PR TITLE
fix Issue 18821 - DMD segfault when doing unsafe operation outside of any function

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by JinShil — APPROVED** [review]

**Review by jacob-carlborg — APPROVED** [review]

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@Geod24 From what I know master gets merged into stable every 3 days so it's really not that important to target stable

**Comment by nemanja-boric-sociomantic** [comment]
I think it is important that this bugfix targets stable branch because the bug is introduced in v2.080 (judging solely by commit message) and you do want this to hit 2.080.1, and not 2.081, right?

**Comment by Geod24** [comment]
> master gets merged into stable every 3 days

What? Of course not. If anything, it's the other way around. Otherwise it wouldn't be stable at all.

**Comment by RazvanN7** [comment]
Oh, sorry, I misread a message from Seb and got the wrong idea. You are right @Geod24

**Comment by Geod24** [comment]
That's why that big dlang-bot warning is useless @wilzbach . But I didn't expect reviews to be as useless...

**Comment by wilzbach** [comment]
What can I say that at this point?
It's a really simple rule:

__Regression fixes should ALWAYS ALWAYS go to stable__

And dlang-bot even reminds one about this...
Should we maybe add a CI that always fails for such cases, s.t. a PR can't be merged?
(then again Walter does have admin rights and could override that restriction too)

**Comment by jacob-carlborg** [comment]
It’s all about making it easy to do the correct thing and difficult to do the wrong thing. Not being perfect.

**Comment by nemanja-boric-sociomantic** [comment]
> And dlang-bot even reminds one about this...

To be fair, dlang bot didn't warned this time ;-) (no reference to `stable` branch in its comment).

**Comment by jacob-carlborg** [comment]
> To be fair, dlang bot didn't warn this time ;-) (no reference to stable branch in its comment).

Perhaps because the target branch changed and then changed back?

**Comment by MartinNowak** [comment]
Would be an idea to try addressing this problem with a PR linter/CI.

**Pull request merged**
