### PR TITLE
fix issue 16229: don't use alloca for huge symbols

### PR DESCRIPTION
**Pull request by rainers**
Use malloc/free for these rare cases instead.

### CODE REVIEW

**Comment by ZombineDev** [comment]
LGTM. I wonder if it makes sense to replace alloca with something like:
```
pragma (inline, true) // force stack allocation in the caller's frame
void[] saferAlloca(size_t size)
{
     return size < threshold? alloca(size)[0..size] : malloc(size)[0.. size];
}

pragma (inline, true)
void allocaFree(void[] data)
{
    if (data.lengh >= threshold)
        free(data.ptr);
}
```

**Comment by ZombineDev** [comment]
... or some macos in the same vein for C/C++.

**Comment by rainers** [comment]
> ... or some macos in the same vein for C/C++.

I thought the same, but didn't want to bother recalculating the exact limits for free. It would make more sense to have a generic approach if it is also used elsewhere, too.

**Comment by ZombineDev** [comment]
At first, I thought about [`scopebuffer`](https://github.com/dlang/phobos/blob/master/std/internal/scopebuffer.d), but after looking at it's code, it didn't seem like it could be a drop-in replacement (and it's not easily usable from C++) without modification.

**Pull request merged**
