### PR TITLE
Issue 12378 - Compiler accepts any syntactically-valid code inside double-nested map predicate

### PR DESCRIPTION
**Pull request by 9rnsr**
https://d.puremagic.com/issues/show_bug.cgi?id=12378

### CODE REVIEW

**Comment by CyberShadow** [comment]
This pull request may have introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=14739

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=15092

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=17492

**Comment by ibuclaw** [comment]
I would say this pull request introduced a regression, but it may have already be reported.

**Pull request merged**
