### PR TITLE
C++ -> D

### PR DESCRIPTION
**Pull request by MartinNowak**
- remove all C++ sources that were replaced by D sources
- adjust idgen to generate id.d instead of id.c
- remove magicport
- change dmd target in makefiles to build from D sources

### CODE REVIEW

**Comment by MartinNowak** [comment]
Mmh, git rename detection doesn't seem to work. This means the change will make invalidate every PR and make it hard to track history. Any ideas how to help git to detect the renames?

**Comment by 9rnsr** [comment]
Git does not have true file rename track system. Whether a file rename happens or not, is detected by the concordance rate of contents. And C++ to D conversion modifies almost 100% of source code lines in a file.

**Comment by MartinNowak** [comment]
> And C++ to D conversion modifies almost 100% of source code lines in a file.

I think git's threshold if 50% by default. So maybe if we omit the indentation changes in the first commit, more files can be detected as renames.

**Comment by MartinNowak** [comment]
Let's try to find out, why the objc test fails @yebblies.

**Comment by MartinNowak** [comment]
> The earlier LDC error message you posted indicates an ABI mismatch of some sorts in the compiler, which might or might not be related.

That was for [objc.di](https://github.com/MartinNowak/dmd/blob/24045b919ff3021ba273b9462fe0aed8c6605ec5/src/objc.di#L39) and [objc_stub.d](https://github.com/MartinNowak/dmd/blob/24045b919ff3021ba273b9462fe0aed8c6605ec5/src/objc_stubs.d#L48). This one is just for [objc.d](https://github.com/MartinNowak/dmd/blob/ee26ba903869691526533e9b9b2f8654f395ccac/src/objc.d) and it's also in a different method.

**Comment by WalterBright** [comment]
I suggest abandoning using git rename. Just add these files as new files, and remove the .c ones. The only thing that would make me reluctant to remove the .c ones is if it will affect the diffs of the unmerged PRs. Having the diffs break would make it more difficult to redo them.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Apparently we need to split std.algorithm unittest building, see https://github.com/D-Programming-Language/phobos/pull/3553.

**Comment by yebblies** [comment]
Auto-merge toggled off

**Comment by yebblies** [comment]
Yeah, I forgot about the win64 failure.

> The only thing that would make me reluctant to remove the .c ones is if it will affect the diffs of the unmerged PRs. Having the diffs break would make it more difficult to redo them.

Having git pick them up as renames is not going to help much anyway.  Pull requests can be ported over by rebasing on top of the last commit before this is merged and running the converter to get the D version of the patch.

**Comment by MartinNowak** [comment]
> Pull requests can be ported over by rebasing on top of the last commit before this is merged and running the converter to get the D version of the patch.

Can you please write a more detailed explanation of that in the wiki and/or newsgroup.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Or did you turn off the auto-merge on purpose @yebblies?

**Comment by yebblies** [comment]
Auto-merge toggled off

**Comment by yebblies** [comment]
Sorry, I did just turn it off because of the failure, but I think this still needs a couple of changes to make updating pull requests easier.

**Comment by MartinNowak** [comment]
> Sorry, I did just turn it off because of the failure, but I think this still needs a couple of changes to make updating pull requests easier.

Which ones?

**Comment by MartinNowak** [comment]
I'll be away for a few days, so maybe you want to take over the PR?

**Comment by WalterBright** [comment]
I was thinking of pulling it as soon as it passes, and if @yebblies wants improvements, he can add PRs. I don't want to wait a few days.

**Comment by yebblies** [comment]
This actually has to happen before, and can't be fixed afterwards.

Basically generating this PR needs to be reproducible and scripted.  The process for upgrading pull requests is:

You need two commits 'before' (the last C++ commit of dmd) and 'after' (the first D commit of dmd).

1. Rebase first commit of pull request on top of 'before'
2. Re-do everything from this pull request (run magicport, delete c++ source, update makefiles etc)
3. Diff the new state against the 'after' commit

Then the commit you produced in step 1 becomes your new 'before' and the commit from step 3 becomes the new 'after', and you repeat steps 1-3 for the rest of the commits in the pull request.

So it's important that we have step 2 completely automated, if at all possible.  I assume that means that some of the commits in this pull request need to be moved _before_ the convert step.

Does that make sense @MartinNowak ?

**Comment by yebblies** [comment]
> I was thinking of pulling it as soon as it passes, and if @yebblies wants improvements, he can add PRs. I don't want to wait a few days.

I didn't want to wait for 2 1/2 years, but I also don't want to rush this and screw up automated PR conversion.  Maybe you'd like to test converting one of your PRs to see if it works smoothly?

**Comment by WalterBright** [comment]
I figured I'd just look at the diffs of my PRs, and manually make a new merge when doing a rebase. The test suite changes in the PR don't have to change at all.

It's great if you want to do a script to help - why not make a branch to do that instead of delaying this? Then work can proceed concurrently instead of serially.

**Comment by WalterBright** [comment]
> I didn't want to wait for 2 1/2 years

You deserve enormous credit for making this happen pretty much on your own.

**Comment by MartinNowak** [comment]
Daniel is right with his approach and if it only rescues half of our PRs it's already worth the trouble.

**Comment by WalterBright** [comment]
can it be done on a branch?

**Comment by yebblies** [comment]
> I figured I'd just look at the diffs of my PRs, and manually make a new merge when doing a rebase. The test suite changes in the PR don't have to change at all.

I'm more worried about Kenji's 51 open PRs, with some of them being huge.

Most of these commits can go in before the conversion easily.  @MartinNowak What's the deal with the verstr change?

**Comment by MartinNowak** [comment]
> Most of these commits can go in before the conversion easily. @MartinNowak What's the deal with the verstr change?

We generate a git tag on posix systems.

**Comment by MartinNowak** [comment]
> Most of these commits can go in before the conversion easily.

The makefile changes can remain after the D transition I guess. It's more about the .d generation and .c deletion.

**Comment by yebblies** [comment]
Umm, is this broken on idgen?  Is there some code somewhere in there to make `idgen` generate D code or is it still generating C++?

**Comment by WalterBright** [comment]
I have tried to catch up with the PRs. There is no catching up. More appear as fast as I pull them. There is no magic method of getting caught up to do the switch. We just have to do the switch.

**Comment by yebblies** [comment]
>I have tried to catch up with the PRs. There is no catching up. More appear as fast as I pull them. There is no magic method of getting caught up to do the switch. We just have to do the switch.

We don't need to catch up with the PRs.  We just have to switch master in a clean way so they can be updated with a reasonable amount of effort.

**Comment by WalterBright** [comment]
Why can't this extra script work be done on a branch?

**Comment by MartinNowak** [comment]
> Why can't this extra script work be done on a branch?

It has to be done before mixing the automated part with manual tweaks of the sources.

**Comment by WalterBright** [comment]
> It has to be done before mixing the automated part with manual tweaks of the sources.

I don't see why. The PR's can be merged to the C++ branch, converted by magicport, then the result be submitted as a PR against the D master. Any differences due to manual tweaks can be handled by the usual methods of dealing with that when creating a PR.

**Comment by MartinNowak** [comment]
> The PR's can be merged to the C++ branch, converted by magicport, then the result be submitted as a PR against the D master.

The manual tweaks were done after the automatic conversion. So everyone submitting a PR would have to redo them.

**Comment by MartinNowak** [comment]
Often a little patience is well worth the better result.
I have to go now. So either Daniel finishes this or I'll on monday.

**Comment by yebblies** [comment]
I'll try and get it done tonight.  I really don't see what the rush is.

**Comment by MartinNowak** [comment]
BTW, we have lot's of follow-ups left over from the last review and also a few ready but unreviewed PRs, so it's not like anyone would run out of work if we do the switch a few days later.
https://trello.com/b/XoFjxiqG/active

**Comment by WalterBright** [comment]
Thank you, @yebblies ! Tonight would be great.

> I really don't see what the rush is.

It's been a long time coming. I have a lot of pent up frustration working on the C++ code, and frankly don't want to do it anymore. I am confident that ddmd will lead to a much improved compiler. We don't have ranges, transitive const, purity, unit tests, ddoc, phobos, algorithms, lambdas, etc. in the C++ codebase. I want to do some refactorings that are a lot harder to do in C++. I am tired of the bugs that I am convinced would be much less of a problem in D. Keeping the source code working properly with magicport is a distraction.

We've been putting this off for years. We cannot afford it anymore.

**Comment by MartinNowak** [comment]
> I'll try and get it done tonight. I really don't see what the rush is.

Thanks, here is what I did in the order it should have been done.

1. remove objc.di and just use objc_stubs.d (1st commit, objc_stubs.d is incomplete though)
1. fix ObjcSelector (needs to be an extern(C++) struct, not sure how to teach that to magicport)
1. generate .d files and remove .c files (1st commit) <- please automate
1. update build system
  - update posix.mak and win32.mak (1st and 4th commit)
  - update idgen to produce id.d (1st+5th commit)
  - generate git.ver file to be imported instead of ../VERSION

**Comment by WalterBright** [comment]
> if we do the switch a few days later

Then I guarantee that we'll have 10-20 more unreviewed PRs. I've tried many, many times to cut down on the number of unreviewed/unpulled PRs. There is no getting ahead on it.

**Comment by WalterBright** [comment]
BTW, we had also more or less agreed on 2.069 being the ddmd equivalent of 2.068. Adding in 50 PRs makes it something else entirely.

**Comment by 9rnsr** [comment]
> I'm more worried about Kenji's 51 open PRs, with some of them being huge.

If we really go ddmd, I'll update my many PR by hand.

But, I have one question about the future of ddmd. I posted it in dmd forum.
http://forum.dlang.org/post/tbenhisoqglhqacuxogg@forum.dlang.org

@WalterBright @MartinNowak @yebblies Can you answer my question?

**Comment by WalterBright** [comment]
> If we really go ddmd, I'll update my many PR by hand.

Thank you, I appreciate that.

> If we will continue to use 2.067 to build new ddmd compiler, we have to avoid issue 14815 in dmd source code _forever_? There's no migration path to update host dmd compiler?

Ideally, each ddmd release will be built by the previous official release. The only reason for 2.067 is a temporary thing to accommodate LDC/GDC building ddmd.

**Comment by 9rnsr** [comment]
> Ideally, each ddmd release will be built by the previous official release. The only reason for 2.067 is a temporary thing to accommodate LDC/GDC building ddmd.

Hmm, OK. I think you meant the bootstrap process should succeed in each dmd commits.
So one more question: If a new merged dmd PR breaks the bootstrap process by accident, how that would be detected? For example, after the ddmd started, if I commit a problematic D code that hits issue 14815 into dmd repo, the generated ddmd.exe will be broken silently. Do we already have fail-safe method to avoid such the problem?

**Comment by WalterBright** [comment]
> how that would be detected?

That's what the test suite is for. I know it is inadequate, but it's the only answer.

**Comment by ibuclaw** [comment]
> Do we already have fail-safe method to avoid such the problem?

Has the autotester been updated to do three-stage builds?

The complete failsafe should be:
1.  Host ddmd builds the PR and runs testsuite + unittests (this is already done).
2. PR ddmd builds itself and runs the testsuite + unittests
3. PR ddmd number 2 builds itself and we check md5sums match the previous bootstrap.

I can't think of any other way to prevent silent corruption.

**Comment by WalterBright** [comment]
@ibuclaw is right. (I misunderstood.) I do that with DMC++. It's effective.

**Comment by 9rnsr** [comment]
> That's what the test suite is for. 

Yet not known bugs cannot be detected by the test suite. 

> 14815 can also be avoided by not having static arrays of objects with destructors, 

It's *workaround*. While using 2.067 as the host compiler, all of dmd committers should know that and reject all PRs that will add it.

> I don't think the dmd source code has any of that anyway.

I'm talking about the situations after the ddmd will be actually started.

**Comment by 9rnsr** [comment]
> Has the autotester been updated to do three-stage builds?
> The complete failsafe should be:

@ibuclaw Also to me, the mechanically testable suite is enough. Is the process already in makefile? (I couldn't find it in `win32.mak`) I think we should develop and ready it before ddmd started.

**Comment by 9rnsr** [comment]
IMHO, we core dmd committers should learn additional prior knowledge to start ddmd development. Does someone write text about that? If exists, I'd like to read it.

My most big worry is that, the current dmd is not yet stable enough to me. Small but not less major/critical bugs exist (let's search bugzilla issues). Big language design/behavior issues (e.g. issue 313/314) is not yet fixed. When we'll start to rely on current D(dmd) behavior, we should also consider the yet not fixed bugs and problematic behaviors in current D. I'm afraid that it would become additional maintenance cost for our core dmd developers.

I'm interest with the dmd development by using D.
But I'm yet not sure it will be actual benefit in this time.

**Comment by WalterBright** [comment]
@9rnsr we cannot recommend that other people use D if we are afraid to use it for the compiler.

**Comment by 9rnsr** [comment]
@WalterBright Indeed... OK, I accept the changes toward ddmd. So, my last concern is the mechanical check system suggested by Iain. I'll add a trello card for that.

**Comment by WalterBright** [comment]
Thank you, @9rnsr

**Comment by 9rnsr** [comment]
> I'll add a trello card for that.

Done: https://trello.com/c/4tefvo4i/51-add-three-stage-builds-for-ddmd

**Comment by WalterBright** [comment]
@yebblies ping?

**Comment by yebblies** [comment]
Now to automate the switch step.

**Comment by WalterBright** [comment]
This used to pass all the tests, now no longer. What's the current state of things? Ping @yebblies ping @MartinNowak

**Comment by MartinNowak** [comment]
Daniel did most of my changes and more in separate PRs, so this won't merge any longer.
Apparently he's working on some script to automate the translation now.

**Comment by yebblies** [comment]
I guess it can be done with 1) run conversion, 2) apply diff to makefiles?

Can we cut down on the diff size and just change the rule for dmd.exe, then clean up after the switch?

**Comment by WalterBright** [comment]
Whatever it takes to make this happen. It's been 5 days now :-(

**Comment by yebblies** [comment]
Haven't forgotten, just busy with real world work.

**Comment by WalterBright** [comment]
@yebblies I understand that real world work can interfere. Should @MartinNowak simply rebase this so it works again and move forward with that?

**Comment by yebblies** [comment]
@WalterBright We've already been over why this branch is not enough.

**Comment by WalterBright** [comment]
When do you expect to be able to finish this?

**Comment by MartinNowak** [comment]
@yebblies what's left to do? Can we help somehow?

**Comment by yebblies** [comment]
@MartinNowak Can you see anything missing from this commit?  If not I'll turn it into a pull request.

https://github.com/yebblies/dmd/commit/588ecd7c3fa5ea493abbcf04fde852e41400e84a

**Comment by MartinNowak** [comment]
> @MartinNowak Can you see anything missing from this commit? If not I'll turn it into a pull request.

Yes, it's missing a script/makefile rule that deletes the *.c files and stages the new *.d files instead.
In fact you want something `dify HEAD~4..mybranch` so you can easily rebase your branch onto the new D based master. Let me quickly write something for that.

**Comment by MartinNowak** [comment]
> @MartinNowak Can you see anything missing from this commit? If not I'll turn it into a pull request.

I had some issues with ROOT_OBJS and root.a b/c of the single file compilation. I ended up making a D_ROOT_SRCS list and compiled that directly into the binary, look at my makefiles.

**Comment by MartinNowak** [comment]
You're deleting async.c w/o replacement. Intended?

**Comment by MartinNowak** [comment]
You need to update .gitignore to remove the *.d files

**Comment by yebblies** [comment]
Yes, I've got a script that I used to generate that commit.  I still need to get the auto-update working, which is a little trickier.

> I had some issues with ROOT_OBJS and root.a b/c of the single file compilation. I ended up making a D_ROOT_SRCS list and compiled that directly into the binary, look at my makefiles.

I don't understand, what problems?  Why doesn't this affect the current DDMD build?  Can it be applied to master now before the switch?

> You're deleting async.c w/o replacement. Intended?

Yes.  It's not needed for a working transition and can be dealt with later.

> You need to update .gitignore to remove the *.d files

I don't think that's needed for a working transition.

I'm trying to keep this minimal, with just what's needed so that people can update their PRs.  We can make more changes manually after the switch.  Are there make targets other than the default and 'auto-tester-build' that are absolutely required for manual or automatic testing?

**Comment by MartinNowak** [comment]
> Yes, I've got a script that I used to generate that commit. I still need to get the auto-update working, which is a little trickier.

See https://github.com/D-Programming-Language/dmd/pull/4922

**Pull request closed without merging**
