### PR TITLE
cv8.d: compile for all platforms

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
Blocked by https://github.com/dlang/dmd/pull/11968/

**Comment by PetarKirov** [comment]
The build is failing with:
```
src/dmd/backend/cv8.d(234): 
Error: 
undefined identifier 
MsCoffObj_seg_debugS
src/dmd/backend/cv8.d(276): 
Error: 
undefined identifier 
MsCoffObj_seg_debugS_comdat
```

I guess you need to remove the conditional complication on a few more symbols.

**Comment by WalterBright** [comment]
@PetarKirov I know, that's why it's blocked by #11968

**Comment by Geod24** [comment]
The mir issue should be fixed BTW (it wasn't disabled, but properly fixed)

**Comment by WalterBright** [comment]
good!

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
