### PR TITLE
Fix DDoc warnings and add a CI check to avoid regressions

### PR DESCRIPTION
**Pull request by wilzbach**
Individual commits:
- Remove duplicated id.d from FRONT_SRCS (It's already part of LEXER_SRCS)
- Add new 'style' target to check for Ddoc errors
- Run style target on CircleCi
- Fix DDoc warnings

### CODE REVIEW

**Comment by CyberShadow** [comment]
Shouldn't DAutoTest already (be able to) enforce DDoc warnings?

**Comment by wilzbach** [comment]
> Shouldn't DAutoTest already (be able to) enforce DDoc warnings?

Unfortunately is `-de` effectless on Ddoc warnings.
We do the same thing as part of the `style` target @ Phobos:

https://github.com/dlang/phobos/blob/master/posix.mak#L591

The idea is that this check can be run without needing to clone dlang.org
It's also a chicken-egg problem if we want to avoid even more complex Makefile rules at DAutotest, as we e.g. druntime doesn't have this check at all and here it still will take a bit until it is in `stable` (aka part of a release).

**Comment by CyberShadow** [comment]
`-de` is for deprecations, did you mean `-w`?

**Comment by CyberShadow** [comment]
> It's also a chicken-egg problem if we want to avoid even more complex Makefile rules at DAutotest, as we e.g. druntime doesn't have this check at all and here it still will take a bit until it is in stable (aka part of a release).

Yeah but it's wasted work because the documentation is going to be built anyway...

**Comment by wilzbach** [comment]
> Yeah but it's wasted work because the documentation is going to be built anyway...

Ah I see what you are going for. Fair enough. Done.

**Review by CyberShadow — APPROVED** [review]
Thanks, makefile stuff looks good. Can't judge correctness of the new documentation though.

**Comment by wilzbach** [comment]
> Thanks, makefile stuff looks good.

Ah I realized that `-w` doesn't trigger a halt, which makes it rather pointless :/
I opened a PR to fix it (-> https://github.com/dlang/dmd/pull/7440), but as we still use 2.072.2 for dlang.org, that's not a solution for now.
Thus I added a grep to the Makefile documentation target. There was also an `-of-` which lead to `src/-` being generated. I replaced it with the proper `-o-`

**Comment by CyberShadow** [comment]
> but as we still use 2.072.2 for dlang.org

Huh? DAutoTest builds DMD then uses it to build everything else, no?

**Comment by wilzbach** [comment]
> Huh? DAutoTest builds DMD then uses it to build everything else, no?

Yes and no - `$(STABLE_DMD)` is used to build the documentation.

**Comment by wilzbach** [comment]
> $(STABLE_DMD) is used to build the documentation.

See also: https://github.com/dlang/dlang.org/pull/1926

**Comment by wilzbach** [comment]
Removed the controversial `grep` to check for deprecation errors and added `-w` instead to unblock this PR. As of now `-w` is defunct, but https://github.com/dlang/dmd/pull/7440 will hopefully take care of this soon.

**Review by PetarKirov — APPROVED** [review]

**Comment by wilzbach** [comment]
>  but #7440 will hopefully take care of this soon.

This is in - so we are good to go here (:

> but as we still use 2.072.2 for dlang.org

Okay. I now changed the documentation build to use the currently build DMD. After all, `dlang.org` already passes [`DMD` to the respective Makefile](https://github.com/dlang/dlang.org/blob/master/posix.mak#L265). So it can be easily overridden if needed. Also using an ancient version of Ddoc means that none of the bugs fixed in the Ddoc build will propagate to dlang.org.
DRuntime and Phobos use the latest version of DMD to build the documentation already (see https://github.com/wilzbach/druntime/blob/master/posix.mak#L152 and https://github.com/wilzbach/phobos/blob/udflags/posix.mak#L93).

**Comment by wilzbach** [comment]
BTW as this PR changes the compiler we use to build the docs, this will fix e.g. this recently introduced page:

Online:

image

https://dlang.org/phobos-prerelease/dmd_semantic2.html

----------------

With this PR

image

**Pull request merged**
