### PR TITLE
nest functions inside aecpgenkill()

### PR DESCRIPTION
**Pull request by WalterBright**
Simple cut & paste job, prior to refactoring them.

### CODE REVIEW

**Comment by WalterBright** [comment]
I'd like to get rid of the global dependencies, `this_block` for starters.

**Comment by WalterWaldron** [comment]
Hello! I've posted a 1 line patch for [dmd regression #19550](https://issues.dlang.org/show_bug.cgi?id=19550#c7) which involves ```aecpgenkill```. Could you please have a look at it?

**Comment by WalterBright** [comment]
@WalterWaldron your patch looks good. How about submitting it as a PR so you get the credit?

**Comment by Geod24** [comment]
> I'd like to get rid of the global dependencies, `this_block` for starters.

Why not change those functions to take a parameter like you did in #11078 ?

**Comment by WalterBright** [comment]
> Why not change those functions to take a parameter like you did in #11078 ?

Because I want to do more to them than that. They are only called in one place, and I'd like to integrate them together more.

**Comment by WalterBright** [comment]
Besides, one-time functions should be nested where they are used. It aids encapsulation. It makes for easy parameter passing without specifically passing parameters or aggregating them in a struct. It's what nested functions are for, and why they are a great feature.

**Comment by Geod24** [comment]
@WalterBright : On multiple occasion, I argued for upfront "large" PR with multiple commits, and breaking it down later on. The reason can be seen in this PR: at the moment a reviewer can't really tell what is going to happen, and the code is IMO worse off if considered in isolation. Obviously, within the framework of the changes you envision, it is probably an improvement, but reviewers don't have this context, only the author (you) does.

> Besides, one-time functions should be nested where they are used. It aids encapsulation. It makes for easy parameter passing without specifically passing parameters or aggregating them in a struct. It's what nested functions are for, and why they are a great feature.

I tend to disagree with this. When a function is nested, things immediately become more complicated, as the parameters are implicit and depend on where the function is defined. The scope could or could not capture some of the parameters and/or locally-defined variables. I've seen local functions used successfully much more for cases where `goto Cleanup;` would be used.

I don't want to block progress, as cleaning up the backend is much welcome, but please consider that you as a reviewer would not accept a PR which goes in a direction you can't yet see.

**Review by Geod24 — APPROVED** [review]

**Comment by WalterBright** [comment]
@Geod24 I understand your concern and thank you for your indulgence. Hope you like how it turns out!

**Pull request merged**
