### PR TITLE
Trivial: fix comments, C++ anachronisms

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by yebblies** [comment]
Making the header comment inconsistent with the rest of the files is wrong.  It would be much better to make just this change to all of the files in a single pull request.  I finally got them consistent and I don't want it spoiled.

Also, maybe you want to update the copyright year?

**Comment by WalterBright** [comment]
I'm not a big fan of multi-thousand line PRs, as they are nigh unreviewable, even if trivial. As for consistency, I cut & pasted it from `mtype.d` which is already incorporated.

I fixed the copyright year.

And besides, 1. now that we are in D, we should be converting to Ddoc comments and 2. anybody can submit PRs to do this, but nobody is but me. Progress is progress, even if incomplete. Nothing is hurt or compromised by this. Doing a full Ddoc conversion (including `Params:` sections, etc.) is an overwhelming task, and if it is going to happen it all it is going to happen piecemeal.

**Comment by yebblies** [comment]
> I'm not a big fan of multi-thousand line PRs, as they are nigh unreviewable, even if trivial.

I don't agree with this.  It's effectively a trivial search+replace and should be done in a single PR/commit.  There is no benefit to having the identical changes spread over multiple PRs.

> As for consistency, I cut & pasted it from mtype.d which is already incorporated.

See my comment in #5130.  You were wrong then and you are still wrong now!

> And besides, 1. now that we are in D, we should be converting to Ddoc comments and 2. anybody can submit PRs to do this, but nobody is but me. Progress is progress, even if incomplete.

This kind of thinking is how we ended up with the 'library AA' disaster.  My experience from the DDMD project is that large features and refactorings should ALWAYS be completed in a branch before being pushed to master.

> Nothing is hurt or compromised by this. Doing a full Ddoc conversion (including Params: sections, etc.) is an overwhelming task, and if it is going to happen it all it is going to happen piecemeal.

I'm not suggesting you do the entire Ddoc conversion as one PR, just the entire set of header comment changes.

Adding `Params:` sections for functions is non-trivial and requires non-trivial review, so I can see why you'd want to spread that over multiple PRs.

**Comment by WalterBright** [comment]
> This kind of thinking is how we ended up with the 'library AA' disaster. My experience from the DDMD project is that large features and refactorings should ALWAYS be completed in a branch before being pushed to master.

It's hard to see how changing a header comment leads to disaster. Nor is it a large feature nor is it a refactoring. Giant PRs are indeed a problem, as github/IE slows to a disastrous crawl displaying them, besides just being annoying.

**Comment by andralex** [comment]
yeah, I'm okay with this seeing as it doesn't preclude a massive change later

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
