### PR TITLE
Issue 12647 - Lazy parameter evaluation should be marked as nothrow

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=12647

### CODE REVIEW

**Comment by JakobOvrum** [comment]
What is the status on this? This bug affects `collectException` as well :(

**Comment by Geod24** [comment]
I'm porting Vibe.d to 2.067.This affects us as well.

**Comment by MartinNowak** [comment]
Looks useful, what's the other problem?

**Comment by trikko** [comment]
Here:
https://issues.dlang.org/show_bug.cgi?id=12647

I read it was blocked by two other bugs, now they seem solved.
This bug affect me too.

**Pull request closed without merging**
