### PR TITLE
convert cod4.c to D

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
Does anyone who has an account with buildkite know what the problem is?

**Comment by JinShil** [comment]
```
Running DScanner
../generated/linux/release/64/dscanner-3a859d39c4b59822b1bc0452b3ddcd598ef390a2/dsc --config .dscanner.ini --styleCheck dmd -I.
dmd/backend/cod4.d(2485:5)[warn]: Empty declaration
posix.mak:606: recipe for target 'dscanner' failed
```

```
Running DScanner
../generated/linux/release/64/dscanner-3a859d39c4b59822b1bc0452b3ddcd598ef390a2/dsc --config .dscanner.ini --styleCheck dmd -I.
dmd/backend/cod4.d(2485:5)[warn]: Empty declaration
posix.mak:606: recipe for target 'dscanner' failed
```

```
Running DScanner
../generated/linux/release/64/dscanner-3a859d39c4b59822b1bc0452b3ddcd598ef390a2/dsc --config .dscanner.ini --styleCheck dmd -I.
dmd/backend/cod4.d(2485:5)[warn]: Empty declaration
posix.mak:606: recipe for target 'dscanner' failed
```

See also https://github.com/dlang/dmd/pull/8548 for context, and https://github.com/dlang/dmd/pull/8563/commits/06633f4dbaf4e40cdf9a60b5fa35e871c25ceff9 for potential solution.

**Comment by WalterBright** [comment]
@JinShil thanks, that did the trick!

**Review by JinShil — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
@wilzbach doesn't Walter have a buildkite account?

**Comment by WalterBright** [comment]
I suppose I could sign up, but I tire of the endless accounts I have (several hundred). I'd like it if buildkite could simply produce a log anyone could read, like the other testers. I confess I don't even know what buildkite is or why we need it.

**Comment by jacob-carlborg** [comment]
@WalterBright I think you can login with your GitHub account. Buildkite is intended to replace Jenkins.

**Comment by jacob-carlborg** [comment]
The idea is that it should be public, but Buildkite needs to do that (approve it is an open source project, or something like that). We have asked for that but nothing has happened yet, as far as I know.

**Pull request merged**
