### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by MartinNowak**
- Remove inappropriate array index error on slice copy (#13265)
- d_do_test: Add --DRT-testmode=run-main even without `EXECUTE_ARGS` (#13282)
- Fix 18054 - Use isBool instead of toInteger when const-folding cast(bool) (#13285)
- fix Issue 22398 - importC: Error: unknown, when compiling source with non-constant initializer
- Fix Issue 21073 - Rebindable does not work when class has alias this to inout property (#13291)
- Fix Issue 16579 - ReturnStatement[CallExp(DotVarExp)]: Corrupted runtime on missed manifest constant propagation
- fix Issue 22432 - ImportC: casting result of postfix operator on a parenthesized expression to a typedef.d type is parsed incorrectly
- fix Issue 22422 - ImportC: parse gnu attributes after a function parameter (#13300)
- Fix 22516 - Set TypeError as return type if inference was skipped... (#13313)
- ImportC: make static functions local
- Fix 22514 - Don't raise invalid duplicate case errors when the switch...
- fix Issue 22517 - [REG 2.093][ICE] Bus error at dmd/lexer.d:398
- fix Issue 22428 - importC: static variables/functions emit global symbols
- Fix Issue 22530 - Explicit cast between classes incorrectly goes through 'alias this' inside CTFE (#13332)
- fix Issue 22513 - ImportC: address of member of struct cannot be taken at compile time
- fix Issue 22500 - ImportC: Lots of errors when compiling tomlc99
- fix Issue 22512 - importC: incomplete array type must have initializer (#13345)
- [stable] importC: Backport master fixes to stable (#13344)
- Fix Issue 22529 - wrong deprecation about empty statement (#13347)
- Fix Issue 21414 - Spurious non-constant expression error with immutable constructors (#13358)
- Fix Issue 22385 - CTFE fails to iterate over associative array previously indexed with implicit conversion to enum base type (#13326)
- Fix issue 22549 - float literal should support leading zero
- Fix Issue 20860 - OpDispatch does not work for structs with constructor and destructor
- fix Issue 22560 - ImportC: extra semicolon not allowed outside of functions
- fix Issue 22534 - ImportC: const pointer (not pointer to const) is treated as transitive const (#13378)
- Fix build for Solaris/Illumos Fix Issue 22573 - DMD compiler errors on Illumos/Solaris
- Fix Issue 22570 -  more arguments than fields allowed in struct constructor
- fix Issue 22538, fix Issue 22537 - ImportC: multiple static / non-static declarations of same function
- Issue 22574 - Compiler segfaults on `template test(x* x)` (#13393)
- fix Issue 22584 - importC: Error: undefined reference to 'parameter' when no parameter names in forward declaration
- Fix Issue 20236 - spurious deprecation warnings on function calls within with(X) blocks while X has a deprecated alias this target (#13397)
- fix Issue 22577 - ImportC: decay of function to typedef'd const function pointer causes ICE (#13412)
- bump VERSION to v2.098.1-beta.1

### CODE REVIEW

**Comment by ibuclaw** [comment]
@MartinNowak FYI there are three open regressions caused by a change in this PR, all should be sorted within the next few days though.

- [ ] https://issues.dlang.org/show_bug.cgi?id=22585
- [ ] https://issues.dlang.org/show_bug.cgi?id=22589
- [ ] https://issues.dlang.org/show_bug.cgi?id=22592

FYI @WalterBright

**Comment by MartinNowak** [comment]
Thanks, will wait. Please try to target stable, so I don't have to hunt down the fixes.

**Comment by ibuclaw** [comment]
> Thanks, will wait. Please try to target stable, so I don't have to hunt down the fixes.

All are targeting stable as far as I'm aware. (#13419, #13420 so far, no PR for last issue yet).

**Comment by ibuclaw** [comment]
@MartinNowak all fixes are in, the first issue is just missing a test case.

**Comment by ibuclaw** [comment]
@WalterBright this is failing to build as a result of your TOK refactoring.

@MartinNowak I'll take ownership of fixing up the changes that are broken.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
