### PR TITLE
Win64: overloads in vtable needs to be reversed, too

### PR DESCRIPTION
**Pull request by rainers**
cl behaves like dmc, or is it the other way around?

Should this go to the stable branch instead? Will need a bugzilla report, then.

### CODE REVIEW

**Comment by yebblies** [comment]
The test from https://github.com/D-Programming-Language/dmd/pull/3010 doesn't catch this?  Why not?

**Comment by rainers** [comment]
> The test from #3010 doesn't catch this? Why not?

Probably because it has been versioned out later: https://github.com/D-Programming-Language/dmd/blob/master/test/runnable/cppa.d#L232
I shoud resurrect that one, too. It additionally tests overwriting, while my test adds a test for a second overloaded function in a derived class.

**Comment by rainers** [comment]
> I should resurrect that one, too.

Done.

**Comment by rainers** [comment]
BTW: this PR and https://github.com/D-Programming-Language/dmd/pull/4990 allow the test suite to pass for -m32mscoff. There is one C abi issue left for Win64, though. The test is versioned out in cabi1.d and is still failing.

**Comment by yebblies** [comment]
> Probably because it has been versioned out later

Sigh.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
