### PR TITLE
Fix issue 20609 - Disabled and deprecated functions show up as candidate

### PR DESCRIPTION
**Pull request by Geod24**
```
Do not show disabled functions as candidate or hints.
Only show deprecated functions when inside a deprecated scope.
```

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
Removed test for https://issues.dlang.org/show_bug.cgi?id=19419 because it is now fully covered by this issue.

**Comment by Geod24** [comment]
And the registry is down one more time...

**Review by WalterBright — APPROVED** [review]

**Comment by Geod24** [comment]
This is ready for a merge. The Buildkite failure is because `mir-core` released a new version yesterday and that apparently broke something.
Submitted a fix: https://github.com/libmir/mir-random/pull/124
Will also look into the `dub` bug.

**Comment by Geod24** [comment]
Buildkite fixed (looks like all other agents are down BTW...) and 2 approved reviews, so self auto-merging.

**Pull request merged**
