### PR TITLE
Enable -verrors=context by default

### PR DESCRIPTION
**Pull request by rv32ima**
## Why?
It's been nearly 3 years since this comment (which introduced `-verrors=context`): https://github.com/dlang/dmd/pull/8487#issuecomment-449403672, where @wilzbach said that `-verrors=context` would be *eventually* enabled by default, dependent on community feedback.

I feel that it's been enough time for that community feedback, and leaving it behind a feature flag is doing a disservice to most developers. `dmd`, admittedly, still has a pretty awful user experience, and this is one of many planned fixes to improve that.

### CODE REVIEW

**Comment by maxhaton** [comment]
I think our error messages are massively behind the competition so I'm tempted to say this should be a no-brainer.

**Comment by hatf0** [comment]
Gotta do more work on fixing up the tests, since we're modifying the default compiler output.

**Comment by PetarKirov** [comment]
@hatf0 Check out the AUTO UPDATE option of `run.d`:
https://github.com/dlang/dmd/tree/master/test#automatically-update-the-test_output-segments

**Comment by hatf0** [comment]
Also looks like this exposed an issue with `-verrors=context` -- it segfaults when reading `__stdin.d`.

**Comment by Geod24** [comment]
I would say that's a blocker. First because now the tests that check `-verror=context` don't test it anymore.
Second because we don't want to enabled by default a feature that is broken.

**Comment by hatf0** [comment]
> I would say that's a blocker. First because now the tests that check `-verror=context` don't test it anymore. Second because we don't want to enabled by default a feature that is broken.

Yeah... it looks like this exposed a *lot* of issues with it. I think I'm going to close this and take a stab at refactoring `-verror=context`, because it's *horribly* broken as-is.

The issues are mostly fixed (other then the whole "we don't test for -verrors=context"), but comes at the price of this PR becoming incredibly bloated beyond just "enabling -verrors=context" -- i.e. adding a header for FileCache & requiring that it's initialized by users of the front-end.

**Comment by Geod24** [comment]
Thanks! Getting features to a finished state is ungrateful work, yet highly appreciated.

Personally I don't mind keeping this PR open - For large body of work, I tend to make a giant PR that shows the final product, and break it down into smaller PRs to make it reviewable. But without a clear vision of the final product, it's hard for reviewers to tell whether the design is workable or not. But to each his own.

Feel free to ping (if needed, repeatedly) if your other PRs aren't reviewed timely.

**Comment by maxhaton** [comment]
There is a GSoC thingy open in projects for someone to work just on error
messages. Could be one for next time round.

**Comment by MoonlightSentinel** [comment]
> This will, of course, be eventually fixed once I have my way (and introduce error codes to the compiler), and we can just test for those rather then greping over the output >:)

No, it won't. Tests must verify that the error messages point to the symbols/expressions/... causing the error - even with error codes. (Context: `TEST_OUTPUT` used to be optional which hid some really bad errors in the error messages). Have a look at the special sequences mentioned in the README if some tests need more flexibility.

W.r.t. to the output of `-verrors=context` being unreliable, that really needs to be fixed before enabling `-verror=context`.

**Pull request closed without merging**
