### PR TITLE
fix Issue 11530 - need gdb test suite

### PR DESCRIPTION
**Pull request by MartinNowak**
- add a basic test and 2 regression tests

### CODE REVIEW

**Comment by MartinNowak** [comment]
We could try to integrate that with d_do_test, any opinions?

**Comment by yebblies** [comment]
I would much prefer improvements to d_do_test instead of more shell code, if possible.

**Comment by MartinNowak** [comment]
done

**Comment by MartinNowak** [comment]
> Done, probably won't work on OSX, FreeBSD though, because of older gdb versions.

Yep, changed to only run gdb tests on linux.

**Comment by MartinNowak** [comment]
Anyone?

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
