### PR TITLE
dmd.identifier: Remove C++ linkage from static members

### PR DESCRIPTION
**Pull request by ibuclaw**
Make static variables private to module.

### CODE REVIEW

**Comment by WalterBright** [comment]
What is gained by de-encapsulating a private static member?

**Comment by ibuclaw** [comment]
> What is gained by de-encapsulating a private static member?

I was about to say they are all public, though now I see that `fullPathStringTable` isn't.

Just tested, and Identifier.stringtable is private to the class as well, so I'll move them back in.

**Comment by ibuclaw** [comment]
Fixed up as per discussion https://github.com/dlang/dmd/pull/8770#issuecomment-425675677

**Review by jacob-carlborg — APPROVED** [review]

**Comment by ibuclaw** [comment]
Cherry-picked into #8773.

**Pull request closed without merging**
