### PR TITLE
Revert #4619 - added predefined version D_Warnings

### PR DESCRIPTION
**Pull request by ibuclaw**
This was snuck in and has had some questions that followed.  At the risk of upsetting @andralex  (sorry man) I think this change warrants further discussion over its use.

I'm in the camp sceptic, and judging from #4619, everyone else who chimed in is in the same camp too.

### CODE REVIEW

**Comment by andralex** [comment]
What is this hurting?

**Comment by WalterBright** [comment]
It's not what it's hurting, it's what it adds. I don't see much of any value that it adds.

**Comment by 9rnsr** [comment]
I also think D_Warnings is not good a *feature*. I cannot imagine the situation where someone needs to branch the runtime code by the toggling -w switch.

**Comment by ibuclaw** [comment]
@9rnsr - what about a warning pragma?  I abstained from opinion when asked, but people who I've spoken to seem more positive having that than a version condition.

**Comment by 9rnsr** [comment]
I think `pragma(warning, messageStr)` would be much better so it would be difficult to abuse.

**Comment by ibuclaw** [comment]
So, are we in agreement?

**Comment by 9rnsr** [comment]
I think so.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by BBasile** [comment]
@WalterBright  or @andralex or @klickverbot : don't forget to remove https://github.com/D-Programming-Language/dlang.org/pull/982 which went in pair.

**Comment by 9rnsr** [comment]
@BBasile Thanks for the mention. I reverted the documentation change in: https://github.com/D-Programming-Language/dlang.org/pull/1016

**Pull request merged**
