### PR TITLE
reboot separate out mangleType()

### PR DESCRIPTION
**Pull request by WalterBright**
This fixes complaints about https://github.com/dlang/dmd/pull/14468

Note: reverting without adding a test case means it can happen again.

### CODE REVIEW

**Comment by ibuclaw** [comment]
> This fixes complaints about https://github.com/dlang/dmd/pull/14468
> 
> Note: reverting without adding a test case means it can happen again.

Add a test to cxxfrontend then - for example call mangleExact with a TypeIdentifier. :-)

**Comment by WalterBright** [comment]
@ibuclaw please post the code for the test.

**Comment by WalterBright** [comment]
@ibuclaw > for example call mangleExact with a TypeInstance

That would be a trick as TypeInstance doesn't have a create() function, and couldn't have been created by C++ code. What was the case in your code that triggered the error?

**Comment by ibuclaw** [comment]
> @ibuclaw > for example call mangleExact with a TypeInstance
> 
> That would be a trick as TypeInstance doesn't have a create() function, and couldn't have been created by C++ code. What was the case in your code that triggered the error?

I'd have to bootstrap gdc with the faulty patch applied, as it ICEd at the assert(0). Perhaps some dummy D code with a template function inside, only run first semantic pass on it (not semantic3), search for the symbol, then call mangleToBuffer on the temple decl its `onemember.isFuncDecl().type`.

**Comment by WalterBright** [comment]
In other words it can't be triggered by feeding the compiler a source file? I don't see much point in going this far.

**Comment by WalterBright** [comment]
This appears to be a gdc issue, as dmd can't trigger it. So this PR is ready to merge.

**Comment by ibuclaw** [comment]
> This appears to be a gdc issue, as dmd can't trigger it. So this PR is ready to merge.

It is a front-end issue because you should not be able to ICE it when compiling any code - valid or otherwise.

What I describe is part of the built-in matching code when `isBuiltin` is called from the front-end. DMD abandoned matching signatures for comparing `Type` pointers instead, which is arguably worse off in terms of trading speed for accuracy.  I think a better way to do it would be adding a `core.attribute.intrinsic(string)` UDA, so we just query that instead (and defer type/parameter checking further down the line to catch and reject mismatches).

i.e:
```
import core.attribute;

@intrinsic("cos")
{
    real cos(real x);
    double cos(double x);
    float cos(float x);
}
```
I think LDC does something similar, except with `pragma`.

**Comment by thewilsonator** [comment]
> I think LDC does something similar, except with pragma.

Correct.

**Review by thewilsonator — DISMISSED** [review]
This "refactor" contains at least the following changes that should be split into separate PRs, in order: 

* Moving `class Mangler : Visitor` below the fold.
* Moving `mangleFuncType` out of `Mangler`.
* Moving `mangleParameter` out of `Mangler`
* "De-visit-ifying" the mangler.

Doing this would make it much easier to see what else is not part of the "refactoring" and is actually a functional change.

Also just because this is green, doesn't make it acceptable to merge.

**Comment by WalterBright** [comment]
> It is a front-end issue because you should not be able to ICE it when compiling any code - valid or otherwise.

I can't, which is why I had the assert in their originally, and you can't recall what triggered it. If you can come up with a test to trigger it, I will add it.

**Comment by WalterBright** [comment]
@thewilsonator the git diff display is pretty inadequate. It will be clear what is happening and easy to review if you just set up a couple windows side by side, as I took care to make it that way.

**Comment by ibuclaw** [comment]
> > It is a front-end issue because you should not be able to ICE it when compiling any code - valid or otherwise.
> 
> I can't, which is why I had the assert in their originally, and you can't recall what triggered it. If you can come up with a test to trigger it, I will add it.

Building stage1 druntime triggered it. This is a public function exposed to c++ compilers, and we use it to determine whether a given symbol is built-in or not. You can't just add assert(0) because dmd doesn't use it in the same way.

**Comment by WalterBright** [comment]
dmd passed the entire test suite, including building druntime, with the assert. I do not know how to produce the error you encountered. I cannot guess at it. Please provide a test case, and I will add it.

**Comment by WalterBright** [comment]
@RazvanN7 ping

**Review by RazvanN7 — APPROVED** [review]
Once the test case surfaces we can add after this is merged.

**Comment by RazvanN7** [comment]
@WalterBright I have merged this because you wanted this in, however, @thewilsonator has raised a valid point: you are doing refactoring mixed in with a functional change (de-visit-fying the mangler) and you are historically against such changes.

**Comment by RazvanN7** [comment]
@ibuclaw if you encounter another breakage, it would be great if you could post the code that caused when you revert the introducing PR.

**Comment by ibuclaw** [comment]
> @ibuclaw if you encounter another breakage, it would be great if you could post the code that caused when you revert the introducing PR.

Sounding like a broken record - you only need to compile druntime / stage2 D compiler to hit the ice.

**Comment by WalterBright** [comment]
> you are doing refactoring mixed in with a functional change (de-visit-fying the mangler) and you are historically against such changes.

This version did not change the functionality. See line 388 of the diff.

**Comment by WalterBright** [comment]
> Building stage1 druntime triggered it. This is a public function exposed to c++ compilers, and we use it to determine whether a given symbol is built-in or not.

> you only need to compile druntime / stage2 D compiler to hit the ice

I don't know what stage1 or stage2 compilers or druntimes are, nor do I know what function you're referring to. If you are willing to put together a test case, I'll pull it.

**Pull request merged**
