### PR TITLE
replace char[] with unsigned char[] to make gcc 6.2.0 shut up

### PR DESCRIPTION
**Pull request by UplinkCoder**
As per title.

### CODE REVIEW

**Comment by WalterBright** [comment]
Hmm, what is the message gcc is producing?

**Comment by UplinkCoder** [comment]
These kinds
ackend/cg87.c:716:46: error: narrowing conversion of ‘232’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]

**Comment by UplinkCoder** [comment]
And the error message is correct.
useless but correct.

**Comment by UplinkCoder** [comment]
@WalterBright anything blocking this ?

**Comment by deadalnix** [comment]
@WalterBright The build is broken with newer versions of GCC because of some warning (values > 127 stored in signed chars) and because by default the build threats warning as errors - which is probably a good thing.

That'd be great if this PR could be prioritized.

**Pull request merged**
