### PR TITLE
ci(azure-pipelines): make git core.autocrlf config false

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

Related to #13639 .

### CODE REVIEW

**Review by MoonlightSentinel — CHANGES_REQUESTED** [review]
That's not a proper solution. The test will also fail when working from windows where `autocrlf=true` is the recommend setting - see [Formatting and Whitespace](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration).

The test should rather be adapted to deal with potential CRLF line endings.

**Comment by ljmf00** [comment]
> That's not a proper solution. The test will also fail when working from windows where `autocrlf=true` is the recommend setting - see [Formatting and Whitespace](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration).
> 
> The test should rather be adapted to deal with potential CRLF line endings.

It doesn't make sense to generically enforce `core.autocrlf` on Windows. Platform independent tests will fail. We should change the line ending where is strictly necessary and adopt other mechanisms. Developers might use `git config --global core.autocrlf input` but the test suite should be reproducible without any special config, therefore it should use strictly the exact bytes provided from the git repository or, perhaps the build tool should detect that and patch it, on that specific platform.

You can see, e.g., the LLVM compiler infrastructure requires `core.autocrlf` to be `false`, although, as described by the documentation, ideally, we should specify that enforcement on `.gitattribute` file. This is still in draft, I'm doing this to check which tests are failing, but the intention is to do that, add the affected files to `.gitattribute`. This will remove that enforcement and therefore whoever clones the repository with the default configs doesn't get affected by this behaviour.

**Comment by MoonlightSentinel** [comment]
That's exactly what I proposed though - a test that works with  whatever `core.autocrlf` setting is used by the developer. IIUC your proposal will ignore the local settings and override them automatically.

**Comment by ljmf00** [comment]
> That's exactly what I proposed though - a test that works with whatever `core.autocrlf` setting is used by the developer. IIUC your proposal will ignore the local settings and override them automatically.

Ok, I guess we are partially out of sync, but I guess we have a consensus. I understand your point, and to clarify, this change is temporary, hence the draft. I'm doing this to check what test is failing and act after knowing how the environment is structured. The idea is indeed to remove whatever `core.autocrlf` config the user is using and add the affected files to the `.gitattribute`.

> Note that `d_do_test` already deals with line endings and the failures in the other PR only apply to very niche cases, e.g. checking the bytes of `import(..)`

Ok, I will check `d_do_test`, although, the test in https://github.com/dlang/dmd/pull/13639 should compile with the right entry in the `.gitattribute`. The rationale of this is to seek for other tests that rely on this setting. If the only affected test is the one in #13639, I can rather remove this enforcement.

**Comment by kinke** [comment]
> The idea is indeed to remove whatever core.autocrlf config the user is using and add the affected files to the .gitattribute.

I fully agree with Florian - that should definitely *not* be done, and instead the tests fixed to work with the user's autocrlf setting.

One reason for a user/CI to enforce autocrlf=true is for packaging. If the CI job e.g. generates an artifact containing some README.txt, you'll want crlf line endings.

**Comment by ljmf00** [comment]
> > The idea is indeed to remove whatever core.autocrlf config the user is using and add the affected files to the .gitattribute.
> 
> I fully agree with Florian - that should definitely _not_ be done, and instead the tests fixed to work with the user's autocrlf setting.
> 
> One reason for a user/CI to enforce autocrlf=true is for packaging. If the CI job e.g. generates an artifact containing some README.txt, you'll want crlf line endings.

Right, but we shouldn't enforce it. Anyway, the only affected test is the one I referred, so I'm closing this.

**Pull request closed without merging**
