### PR TITLE
make FuncDeclaration.leastAsSpecialized standalone

### PR DESCRIPTION
**Pull request by WalterBright**
make it standalone

### CODE REVIEW

**Comment by thewilsonator** [comment]
why? I think it reads better the way it currently is.

**Comment by WalterBright** [comment]
The size of the classes is gigantic. They're full of kitchen sink functions that don't really benefit from being class members. My end goal here is to clear those functions out of the class and put them in a "semantic" module as free functions. This also helps us make a "dmd as library", as the data structures will be separated from the code.

I also prefer to make the arguments to a function explicit rather than implicit.

**Review by thewilsonator — DISMISSED** [review]
This function is used by LDC, please update the corresponding header.

**Comment by thewilsonator** [comment]
Noted, git grep tells me that `leastAsSpecialized` is only called from `dtemplate.d` (which I presume you will want to move those references to semantic modules too). Why move these to static functions first and then to elsewhere?

**Comment by WalterBright** [comment]
> Why move these to static functions first and then to elsewhere?

Because then I can move them as a pure cut&paste job. I like making PRs that are trivial to review :-)

**Review by dkorpel — APPROVED** [review]

**Pull request merged**
