### PR TITLE
Fix interface contracts regression recently introuced in #9782

### PR DESCRIPTION
**Pull request by SSoulaimane**
Fix this https://github.com/dlang/dmd/pull/9782#issuecomment-494989175 regression.

### CODE REVIEW

**Comment by kinke** [comment]
Thx for the near-instant quickfix! :) - I feel like this is patching over the cracks though; I don't think the linkage (`extern(C)`) for a function pointer parameter is to be lost anywhere in the process. The testcase works fine in a struct; it's a problem in a class though, although the method is final...

**Comment by SSoulaimane** [comment]
> Thx for the near-instant quickfix! :)

At your service.

> I feel like this is patching over the cracks though; I don't think the linkage (`extern(C)`) for a function pointer parameter is to be lost anywhere in the process. 

This is where it happened https://github.com/dlang/dmd/blob/8e364d300adef422a36ac39b0f09dcfaed78312a/src/dmd/typesem.d#L1167

**Comment by kinke** [comment]
See https://github.com/ldc-developers/ldc/pull/3076#issuecomment-494927344 for my results wrt. `syntaxCopy()` - this testcase compiles fine if the parameter is not syntaxCopied (as LDC did originally), but then another new test case fails (original delegate param to lazy arg for `__ensure`).

**Comment by kinke** [comment]
https://github.com/dlang/dmd/blob/8e364d300adef422a36ac39b0f09dcfaed78312a/src/dmd/typesem.d#L1167 might be the problem. Disabling it makes the testcase work; typesemantic is overriding the `TypeFunction.linkage` based on the scope, but the linkage is a mandatory `TypeFunction` ctor argument, so I guess it should not be touched.

**Comment by SSoulaimane** [comment]
> but then another new test case fails (original delegate param to lazy arg for `__ensure`).

The lazy param failure is something I encountered when I copied LDC's implementation, the problem was similar to this one i.e. the semantic running twice.
That's why I replaced this
https://github.com/ldc-developers/ldc/blob/5e5ce199f493091e6aea39f7f19f609dcf683da2/dmd/func.d#L2448-L2450
with this
https://github.com/dlang/dmd/blob/8fccea7872119c558e6df050e4529c6456a22b68/src/dmd/func.d#L2324

**Comment by SSoulaimane** [comment]
> https://github.com/dlang/dmd/blob/8e364d300adef422a36ac39b0f09dcfaed78312a/src/dmd/typesem.d#L1167
> might be the problem. Disabling it makes the testcase work; typesemantic is overriding the `TypeFunction.linkage` based on the scope, but the linkage is a mandatory `TypeFunction` ctor argument, so I guess it should not be touched (or only if originally `LINK.default_`?).

Yes, you're right.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
