### PR TITLE
Revert "reapply fix Issue 23479 - ImportC recognizes .i and .c files, but not .h files"

### PR DESCRIPTION
**Pull request by WalterBright**
Reverts dlang/dmd#14864

Controversy not resolved.

### CODE REVIEW

**Comment by WalterBright** [comment]
How do I get the failing heisenbug test to restart?

**Review by thewilsonator — DISMISSED** [review]
Controversy of this not resolved, this breaks GDC/GCC.

**Comment by WalterBright** [comment]
@dkorpel ping

**Comment by WalterBright** [comment]
The correct fix for this was https://github.com/dlang/dmd/pull/14636

I understand that @ibuclaw doesn't agree, but my reasons were not addressed.

**Comment by thewilsonator** [comment]
@ibuclaw

**Comment by WalterBright** [comment]
At question was one config.h file that @ibuclaw had. There are many ways to deal with this:

1. rename the config.h
2. rename the config.d
3. adjust the search path to find config.d first

Adjusting the search algorithm to a slow one (file lookups are slow) and converting it to a complicated two level search is not justified by one file.

**Comment by thewilsonator** [comment]
Let me be clear, if this breaks GCC _again_, this will be reverted whether you like it or not.

**Comment by WalterBright** [comment]
@thewilsonator to be clear, the gcc break thing was about #14636 , which was reverted.

**Comment by WalterBright** [comment]
https://github.com/dlang/dmd/pull/14864 did not fix any breakage.

**Comment by ibuclaw** [comment]
> At question was one config.h file that @ibuclaw had. There are many ways to deal with this:
> 
>     1. rename the config.h
> 

And change the hundreds of sources that `#include` it?  Good luck convincing GCC maintainers it's their build scripts that need fixing, not the D compiler.

>     2. rename the config.d
> 

And break downstream projects that import it? Besides this is needless special casing just to work around a broken compiler that doesn't import D modules when you ask it to.

>     3. adjust the search path to find config.d first
> 

Doesn't work because the implicit search path `.` always wins.

>     4. put the priority one explicitly on the command line
> 

And get duplicate definition errors at link-time because the same symbols appear in every compiled object?

> Adjusting the search algorithm to a slow one (file lookups are slow) and converting it to a complicated two level search is not justified by one file. People expect that when a search path is followed, the earlier paths override the later ones.

If you can prove that `5N != 2N+3N` - then this is a valid point, otherwise speed concern just isn't true.  People also expect to import D modules when they use the `import` keyword.

**Comment by ibuclaw** [comment]
>     2. rename the config.d

Should we rename `std.stdio` just because libc has decided to add a header named `std/stdio.h`?

**Comment by WalterBright** [comment]
See https://github.com/dlang/dmd/pull/14864#issuecomment-1428920555

**Comment by schveiguy** [comment]
I already fixed the slowness of stats. That is no longer an issue.

**Pull request merged**
