### PR TITLE
Fix Issues 23331, 23379 - fix casts involving noreturn

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
Stable

**Comment by RazvanN7** [comment]
At some point @ibuclaw said not to target stable. I don't know if that's still a valid constraint or not.

**Comment by Stan4444** [comment]
Take me of your mailing list MOTHER FUCKERS! 🖕🏾 🖕🏾 🖕🏾 🖕🏾 Wed, Sep

**Comment by ibuclaw** [comment]
This PR introduced a regression.
https://issues.dlang.org/show_bug.cgi?id=23587

**Pull request merged**
