### PR TITLE
move .isym from Dsymbol to Declaration

### PR DESCRIPTION
**Pull request by WalterBright**
An alternative to https://github.com/dlang/dmd/pull/13762 which moves a field from the base class to the derived class.

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by thewilsonator** [comment]
cc @ibuclaw @kinke

**Review by kinke — APPROVED** [review]
Looks good.

**Comment by ibuclaw** [comment]
Hmm, this is going to make things confusing for representing modules and imports in debug.  Not that a csym is set for Module or Import nodes anyway, but still, I can't use `dsymbol->isym as a guard anymore.

**Comment by ibuclaw** [comment]
Really, these fields should be kicked out of the AST, forcing each respective code generator to use its own internal hash map to keep track of what symbols have already been generated.

**Comment by ibuclaw** [comment]
Because now we have a situation where gdc no longer builds since this PR.

**Comment by WalterBright** [comment]
I'm fine if you want to do a `version (gdc)` block in the declaration to support what you need.

**Pull request merged**
