### PR TITLE
fix Issue 22912 - importC: syntax error for function call with cast a…

### PR DESCRIPTION
**Pull request by WalterBright**
…nd typedef and parentheses around name

### CODE REVIEW

**Comment by WalterBright** [comment]
What is this:
```
fix end of files.........................................................Failed
```
in pre_commit?

**Comment by RazvanN7** [comment]
It is a style tester that checks for, among others, properly ended files. In this situation the test "fix end of files" fails because of:

```
diff --git a/test/compilable/test22904.c b/test/compilable/test22904.c
index 8e3c567..63[78](https://github.com/dlang/dmd/runs/5656510780?check_suite_focus=true#step:4:78)7b3 100644
--- a/test/compilable/test22904.c
+++ b/test/compilable/test22904.c
@@ -7,4 +7,3 @@ void fn2() { long x = (long) (fn1) (); }
 
 typedef long my_long;
 void fn3() { long x = (my_long) (fn1) (); }
-
```

Which means that you have an extra newline at the end of the file.

**Review by RazvanN7 — APPROVED** [review]

**Comment by PetarKirov** [comment]
@WalterBright I fixed the issue and rebased the PR for you.

**Comment by WalterBright** [comment]
@PetarKirov thank you!

@RazvanN7 perhaps the style checker can have a better error message than `-` ? Like "blank lines at end of file"? :-)

**Comment by PetarKirov** [comment]
@WalterBright these checks are implemented by https://pre-commit.com/, so I guess you could open an issue for that here: https://github.com/pre-commit/pre-commit/issues. In theory we could parse the output of their tool and convert the error messages to a more user friendly format, but I'm not sure if it's worth the effort.

**Comment by WalterBright** [comment]
Oh, sorry, I thought it was something we wrote.

**Comment by WalterBright** [comment]
I tried submitting a bug report, but the form required a version, which is not in the log, and a `.pre-commit-config.yaml`, which I have no idea what that is.

So no bug report for them.

**Comment by WalterBright** [comment]
No way to contact any of the people that run it, either.

Glad we don't operate like these people.

**Comment by PetarKirov** [comment]
> I tried submitting a bug report, but the form required a version

@WalterBright If you look at the logs for the pre-commit CI pipeline (https://github.com/dlang/dmd/runs/5657044263?check_suite_focus=true), specifically the `Run pre-commit/action@v2.0.3` section:

```
Run pre-commit/action@v[2](https://github.com/dlang/dmd/runs/5657044263?check_suite_focus=true#step:4:2).0.[3](https://github.com/dlang/dmd/runs/5657044263?check_suite_focus=true#step:4:3)
  with:
    extra_args: --all-files
  env:
    SKIP: no-commit-to-branch
    pythonLocation: /opt/hostedtoolcache/Python/3.10.2/x6[4](https://github.com/dlang/dmd/runs/5657044263?check_suite_focus=true#step:4:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.2/x64/lib
install pre-commit
  /opt/hostedtoolcache/Python/3.10.2/x64/bin/pip install pre-commit
  Collecting pre-commit
    Downloading pre_commit-2.17.0-py2.py3-none-any.whl (19[5](https://github.com/dlang/dmd/runs/5657044263?check_suite_focus=true#step:4:5) kB)
```

You can see that it's using `pre_commit-2.17.0`.

> and a .pre-commit-config.yaml, which I have no idea what that is.

It's typical for such services to have their configuration stored in the git repo root folder in YAML or JSON format. Often the name is something along the lines of `.<service-name>.yaml`. In this case you can find the file here: https://github.com/dlang/dmd/blob/master/.pre-commit-config.yaml

**Pull request merged**
