### PR TITLE
fix Issue 15898 - [REG2.069] Internal error: backend\cgcod.c 1651

### PR DESCRIPTION
**Pull request by WalterBright**
https://issues.dlang.org/show_bug.cgi?id=15898

### CODE REVIEW

**Comment by 9rnsr** [comment]
Please close this and reopen the fix on stable branch. We should avoid cherry-pick commits from master to stable because it would be problematic for mechanical-generated changelog.

**Comment by 9rnsr** [comment]
I opened #5660 on stable branch.

**Comment by WalterBright** [comment]
How do I pull `stable` down from github?

**Comment by 9rnsr** [comment]
> How do I pull  stable  down from github?

I'd try to explain how to create a new PR on stable branch with my poor English.

In below, I assume that you're using a name 'upstream' to refer the remote repo https://github.com/D-Programming-Language/dmd,
and using a name 'origin' to refer the remote repo https://github.com/WalterBright/dmd that is you own in github.

1. First, fetch the position where the 'stable' branch is on in the https://github.com/D-Programming-Language/dmd repo.
 ```
 $ git fetch upstream stable
 From https://github.com/D-Programming-Language/dmd
  * branch            stable     -> FETCH_HEAD
  * [new branch]      stable     -> upstream/stable
 ```
 -> git creates a "tracking branch" 'upstream/stable' in your local repo to track the 'stable' branch in upstream repo.
 -> If 'upstream/stable' is already there in your local repo, it will be updated to the latest commit in upstream repo.

1. Second, create your working branch on the newest stable.
 ```
 $ git checkout -b bugfix upstream/stable
 ```
 -> Create a new branch 'bugfix' on the tracked 'upstream/stable', then checkout the files in 'bugfix'.
 -> 'bugfix' is on 'upstraem/stable', so your working directory will be updated to the same content within upstream/stable.

1. Third, commit some changes into your local 'bugfix' branch.
 ```
 (modify files)
 $ git commit ...
 ```
 -> It's your work.

1. Fourth, push the new commits and 'bugfix' branch to your own remote 'origin'.
 ```
 $ git push origin bugfix
 ```
 -> Then the 'bugfix' branch will be shown in https://github.com/WalterBright/dmd .

1. Last, open a new pull request to https://github.com/D-Programming-Language/dmd from your own remote https://github.com/WalterBright/dmd with the pushed 'bugfix' branch.
	- Go your 'origin' webpage in github: https://github.com/WalterBright/dmd/

	- Select the `git push`ed branch 'bugfix', then press a button 'New pull request'.

	- Change the combobox 'base: master' to 'base: stable' to change the base branch of new PR.

	- Write in summary and comment, then 'Create pull request'.

----

Once you create a pull request on github, anymore you cannot change its base branch (AFAICS github provides no web interface to do it). That's why we should recreate new PR to *switch* base branch.

**Pull request closed without merging**
