### PR TITLE
Separate Initializer semantic

### PR DESCRIPTION
**Pull request by RazvanN7**
This PR separates the semantic routines from the AST classes of the  Initializer nodes. It is a follow-up to @yebblies 's work #5730

### CODE REVIEW

**Comment by RazvanN7** [comment]
@UplinkCoder any ideas why compiling druntime leads to CTFE errors?

**Comment by UplinkCoder** [comment]
@RazvanN7 Nothing that jumps in the eye.
I suggest to leave the code as is, for now.

**Comment by RazvanN7** [comment]
@UplinkCoder you mean drop the PR? why?

**Comment by UplinkCoder** [comment]
The code is not likely to change.
So there is little benefit it splitting it out.

**Comment by RazvanN7** [comment]
@UplinkCoder 

> Are you sure the constructors are getting called correctly ?
Yep. I just copy-pasted the code and added `i.` in front of (1) all the variables that would normally have been parameters and (2) calls to member functions.

> So there is little benefit it splitting it out.

I disagree. Refactoring the code this way makes the code easier to read and makes packaging the compiler as a library easier

**Comment by wilzbach** [comment]
> I disagree. Refactoring the code this way makes the code easier to read and makes packaging the compiler as a library easier

I can't agree more. Code is read a lot more than its written and __every__ change that helps to improve the readability of the dmd codebase is imho very useful.
@UplinkCoder don't forgot that there are and will be people who want to understand the dmd codebase in the future.

@RazvanN7 Please don't stop cleaning up and refactoring the frontend. You are doing great and important work!

**Comment by RazvanN7** [comment]
I plan on doing Expression next.

**Comment by ibuclaw** [comment]
And C++ headers?

**Comment by RazvanN7** [comment]
@ibuclaw forgot about those... done.

**Pull request merged**
