### PR TITLE
Issue 14603 & 14604 - aliasing opDispatch result

### PR DESCRIPTION
**Pull request by 9rnsr**
[Issue 14603](https://issues.dlang.org/show_bug.cgi?id=14603) - "cannot alias an expression" when opDispatch results in a template
[Issue 14604](https://issues.dlang.org/show_bug.cgi?id=14604) - "cannot resolve forward reference" when opDispatch results in a template

Fixes a root issue:
[Issue 15310](https://issues.dlang.org/show_bug.cgi?id=15310) - [dmd-internal] TemplateDeclaration should be converted to TemplateExp always

### CODE REVIEW

**Comment by 9rnsr** [comment]
Rebased on master, and ready for ddmd.

**Comment by 9rnsr** [comment]
Removed all following cleanup commits. Now this PR contains only a bugfix.

@yebblies This is enough small for review. Can you merge this?

**Comment by apz28** [comment]
problematic return
        if (e1.op == TOKtype)
+            return e2;
         if (e2.op == TOKtype)
             return e2;

**Comment by 9rnsr** [comment]
@apz28 The returns for `TOKtype` in `DotExp.semantic` is intentional.
It means, if a DotExp `Type.member` exists, it will be reduced to a `member`.

```d
        if (e1.op == TOKtype)
+            return e2;
         if (e2.op == TOKtype)
             return e2;
```

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks!

**Pull request merged**
