### PR TITLE
move assert() code past end of function

### PR DESCRIPTION
**Pull request by WalterBright**
Per Nicholas Wilson's suggestion:

http://www.digitalmars.com/d/archives/digitalmars/D/Thoughts_about_D_308441.html#N308716

### CODE REVIEW

**Comment by WalterBright** [comment]
For code:
```
void test(int i) {
    assert(i, "message");
}
```
the following is now generated:
```
_D4test4testFiZv:
                sub     ESP,01Ch
                mov     018h[ESP],EAX
                cmp     dword ptr 018h[ESP],0
                je      L12
                add     ESP,01Ch
                ret
L12:            mov     ECX,offset FLAT:___a6_746573742e64
                mov     EAX,6
                mov     EDX,offset FLAT:___a7_6d657373616765
                mov     dword ptr 010h[ESP],5
                mov     EBX,7
                mov     0Ch[ESP],ECX
                mov     8[ESP],EAX
                mov     4[ESP],EDX
                mov     [ESP],EBX
                call    near ptr __d_assert_msg
```

**Comment by thewilsonator** [comment]
I can't comment on the code, but I will note that this doesn't apply only to asserts, but to all slow path noreturn branches e.g. conditional branches that terminate in a `throw` or calls to functions that are noreturn (e.g. enforce) and asserts.

**Comment by WalterBright** [comment]
I know, but one thing at a time!

**Comment by thewilsonator** [comment]
Fair enough.

**Comment by ibuclaw** [comment]
This caused a regression: https://issues.dlang.org/show_bug.cgi?id=19550

**Comment by thewilsonator** [comment]
I haven't done much much complexity analysis, but that looks `O(pretty bad)` to me.

**Pull request merged**
