### PR TITLE
replace hack with isArrayOp

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by UplinkCoder — APPROVED** [review]
Approved can be merged after the tests pass on atleast one platform.

**Review by dnadlinger — APPROVED** [review]

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
> Was my auto-merge not good enough for you? ;o)

I think @WalterBright isn't familiar with the "auto-merge" labels yet.
@WalterBright since a couple of months the "auto-merge" label has superseded the merging done by the auto-tester. The main reason for this was that the Auto-tester doesn't take the other CIs into account and sometimes blocked because of this. So toggling a PR for auto-merge is as simple as adding the label... (like @klickverbot did)

**Comment by WalterBright** [comment]
Sorry, I didn't know the automerge label was more than just a label.

**Comment by yebblies** [comment]
Does that mean I can use Brad's auto-merge to force a merge when jenkins is broken?

**Comment by JackStouffer** [comment]
@yebblies Yes

**Comment by CyberShadow** [comment]
> Does that mean I can use Brad's auto-merge to force a merge when jenkins is broken?

If it's broken (and you have permissions), just go ahead and unset it as required.

I'd even go as far as hiding it completely, but that's something we should discuss / work on.

**Comment by yebblies** [comment]
> If it's broken (and you have permissions), just go ahead and unset it as required.

How/where do I do that?

**Comment by CyberShadow** [comment]
https://github.com/dlang/dmd/settings/branches

**Comment by yebblies** [comment]
Yeah I don't have permissions for that.

**Comment by CyberShadow** [comment]
OK, I did it.

@MartinNowak One more thing for you to look at once you get back.

**Pull request merged**
