### PR TITLE
fix Issue 18936 - Internal error: dmd/backend/cgxmm.c 684

### PR DESCRIPTION
**Pull request by WalterBright**
This code fails to compile with 2.079, see if the failure still exists in master.

### CODE REVIEW

**Comment by WalterBright** [comment]
Filed as https://issues.dlang.org/show_bug.cgi?id=18936

**Comment by RazvanN7** [comment]
Since this is filed as a bug report and the test is contained in the OP, can we close this? The person that will solve the bug will surely add this test in the fixing PR

**Comment by WalterBright** [comment]
I'm not in a rush to close it, I'd rather wait until there's a fix for it and then decide what to do about it.

**Comment by WalterBright** [comment]
Added the fix.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
