### PR TITLE
Fix issue 18504 - Generate unwind tables for halting functions

### PR DESCRIPTION
**Pull request by LemonBoy**
I think #7333 heuristic is too eager.

### CODE REVIEW

**Review by JinShil — APPROVED** [review]

**Comment by JinShil** [comment]
LGTM, but I'm not really qualified.  @WalterBright or @ibuclaw, please review.

**Comment by WalterBright** [comment]
When creating a PR to fix a bugzilla issue, please post a link to the PR in the issue. This is so that someone browsing bug reports will know if and where a PR for it is.

**Review by WalterBright — APPROVED** [review]

**Comment by ibuclaw** [comment]
Why is this information in the frontend? This is a backend check, and dmd specific.

**Comment by WalterBright** [comment]
All it does is set a flag, which is then used by the glue code and back end.

**Pull request merged**
