### PR TITLE
Merge stable into master

### PR DESCRIPTION
**Pull request by Geod24**
Needed for GDC.
CC @ibuclaw

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
```
/private/var/folders/wh/z5_y2cv53sg24tzvtw_f_y1m0000gn/T/dmd/generated/osx/release/64/dmd -m64 -fPIC -w -I../../src -I../../import -Isrc -defaultlib= -debuglib= -dip1000 -L-lpthread -L-lm -L/private/var/folders/wh/z5_y2cv53sg24tzvtw_f_y1m0000gn/T/druntime/generated/osx/release/64/libdruntime.a -O -release -of./generated/osx/release/64/tester_na customhandler.d -version=NoTests
../../src/core/internal/dassert.d(461): Error: reinterpreting cast from `pure nothrow @safe string(ref const(int) v)*` to `pure nothrow @nogc @safe string(ref const(int))*` is not supported in CTFE
../../src/core/internal/dassert.d(467):        called from here: `assumeFakeAttributes(& miniFormat)`
../../src/core/internal/dassert.d(67):        called from here: `miniFormatFakeAttributes(_param_1)`
src/assert_fail.d(6):        called from here: `_d_assert_fail("==", a, b)`
src/assert_fail.d(6):        called from here: `test(_d_assert_fail("==", a, b), msg, line)`
src/assert_fail.d(22):        called from here: `test(1, 2, "1 != 2", 22LU)`
src/assert_fail.d(449):        called from here: `testIntegers()`
src/assert_fail.d(485):        called from here: `main()`
make[2]: *** [generated/osx/debug/64/assert_fail] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Weird, I don't see any change in this file that would trigger this. Any insight @MoonlightSentinel ?

**Comment by MoonlightSentinel** [comment]
Cirrus did ran the tests using the base branch (`stable`) without actually merging it to master. 
`CIRRUS_PR` is apparently not set for internal pull requests - contrary to [their documentation](https://cirrus-ci.org/guide/writing-tasks/#environment-variables).

**Comment by Geod24** [comment]
Thanks! Guess we should raise an issue to CirrusCI ?

**Comment by MoonlightSentinel** [comment]
After looking at the logs again, I think that the issue is actually caused by the "outdated" script in `stable`. The branch merging PR was not merged to `stable` yet and hence the job was initialized without checking for `CIRRUS_PR`.

E.g. notice `+ '[' -z x ']'` *after* `./ci.sh setup_repos master` in [this run](https://cirrus-ci.com/task/6627886552580096?logs=setup_repos#L5).

(*I blame Beerconf and time zones*)

**Pull request closed without merging**
