### PR TITLE
Fix Issue 17143 - [REG2.072.0] Declaration is already defined on global enum = tuple(...).expand declaration

### PR DESCRIPTION
**Pull request by epi**
Regression was introduced in 53a70e4d66b8bf1b96a51c06eeb2df7fa836f647

### CODE REVIEW

**Comment by epi** [comment]
Sorry, I've pushed again, this time with a test for this issue.

**Comment by MartinNowak** [comment]
Rebased to target stable, fixes should _always_ go into stable.

**Comment by MartinNowak** [comment]
OK, thx. Will you do the rebase or should I?

**Comment by epi** [comment]
I'll do it. It's my first fix to DMD so I didn't know but I'd better learn.

**Comment by MartinNowak** [comment]
You need to change the target branch in GH before pushing the rebased state, for the auto-tester to pick things up in the right order.

**Comment by MartinNowak** [comment]
It's in our contributing, but noone get's this right, we need to figure out how to better communicate this.
https://github.com/dlang/dmd/blob/master/CONTRIBUTING.md#solving-bugs--submitting-pull-requests

**Comment by MartinNowak** [comment]
Sth. along the lines of `git rebase --onto upstream/stable HEAD~1` will do the necessary rebase.

**Comment by epi** [comment]
Should be ok now.

**Comment by MartinNowak** [comment]
Most testers didn't pick up the right target branch, b/c GH was changed after the push (which triggers the builds). Anyhow should roughly test the right thing, and the fix is OK.

**Comment by epi** [comment]
Good, I'll keep in mind to use stable branch next time. Thanks for handling this so quickly.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
BTW, we'll make a point release within the next few days.

**Comment by ZombineDev** [comment]
I restarted the Darwin_64_32 test because it is known to spurious fail in std.regex.internal.tests3.

**Pull request merged**
