### PR TITLE
refactor inliner()

### PR DESCRIPTION
**Pull request by WalterBright**
Looking into improving the capability of the backend inliner.

1. eliminate redundancy
2. reorganize for clarity
3. reorganize for efficiency

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
```
FAILED targets:
- runnable/test22.d
- runnable/testprofile.d
- runnable/inline.d
- runnable/hello-profile.d
- compilable/ice11596.d
```

**Comment by WalterBright** [comment]
The fact that the refactor is not behaving the same way is a good reason a refactor is needed!

**Comment by WalterBright** [comment]
And, I can't repro it locally, so back to incrementally experimenting with the test system.

**Comment by thewilsonator** [comment]
Looks good, the one macOS failure is unrelated.

**Comment by WalterBright** [comment]
Thanks for letting me know about the MacOS failure. Saves me wasting time on it.

**Comment by WalterBright** [comment]
Will continue tomorrow...

**Review by RazvanN7 — APPROVED** [review]

**Comment by WalterBright** [comment]
Never has a short function needed refactoring so badly.

**Comment by braddr** [comment]
Considering the difficulties in getting the refactoring to actually work, approx 30 attempts, I suggest that additional documentation and probably some targeted unit tests are called for.  That other parts of the test suite not geared at inlining testing also happened to catch issues kept the bad versions from slipping through is great, but also means that maintenance is distant parts of the test suite could accidentally result in loss of coverage at some future point.  See also, your own local testing didn't uncover many of the issues.

Also, I suspect this is an area of the backend that's likely to get further touching.  After all, this is a first or second pass at the backend inliner and not an end-game 'really does all the jobs well' inliner.  A bit of extra work now while it's fresh in your mind will pay off the next time you're fiddling with it.

**Comment by PetarKirov** [comment]
I agree. @WalterBright?

**Pull request merged**
