### PR TITLE
Improve compile_output regex

### PR DESCRIPTION
**Pull request by wilzbach**
See also: https://github.com/dlang/dmd/pull/8389#issuecomment-399076936

CC @jacob-carlborg

I can't reproduce your issue on my Linux system, but maybe this fixes it for you?

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
It fixes the problem for me.

**Comment by jacob-carlborg** [comment]
But the split/grouped output is more annoying since that fails to automatically update.

**Comment by wilzbach** [comment]
> But the split/grouped output is more annoying since that fails to automatically update.

Are you referring to the case when a file has multiple `TEST_OUTPUT` sections?
Yeah I haven't found an easy way to hack support for this in :/

However, there's one "easy" solution: just remove the all `TEST_OUTPUT` sections except the first one and rerun the test file with `AUTO_UPDATE=1` twice.

**Comment by jacob-carlborg** [comment]
> Are you referring to the case when a file has multiple TEST_OUTPUT sections?
Yeah I haven't found an easy way to hack support for this in :/

Yes.

> However, there's one "easy" solution: just remove the all TEST_OUTPUT sections except the first one and rerun the test file with AUTO_UPDATE=1 twice.

Already done that. I tried to keep the sections first, but gave up on that.

**Pull request merged**
