### PR TITLE
gloop.d: bunch of minor refactors

### PR DESCRIPTION
**Pull request by WalterBright**
Mostly using `ref` instead of `*`.

### CODE REVIEW

**Comment by Geod24** [comment]
@WalterBright : FYI, Azure has some issues. The testsuite seems to complete, only to timeout after 2 hours... I don't know yet what broke it.

**Comment by WalterBright** [comment]
@Geod24 thanks for looking into it

**Comment by Geod24** [comment]
It's fixed now, can you rebase on master ?

**Comment by WalterBright** [comment]
Ah, you found it? Wunderbar! Rebased.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
