### PR TITLE
Rename CompileStatement to MixinStatement

### PR DESCRIPTION
**Pull request by ntrel**
We already have MixinExp and CompileStatement is not specific enough.

(This was mentioned in @dkorpel's video: https://www.youtube.com/watch?v=hYLvw18obMA)

After this, need to do CompileDeclaration.

### CODE REVIEW

**Comment by RazvanN7** [comment]
`frontend.h` needs to be updated. Note that we also have `CompilerDeclaration`, maybe it's best you do that one too.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Technically, this would break dmdfe-lib. However, given the small adoption, I think we can get away with a changelog entry.

**Comment by dkorpel** [comment]
Or perhaps a `deprecated alias CompileStatement = MixinStatement` (though deprecated aliases currently don't file deprecation warnings IIRC)

**Comment by RazvanN7** [comment]
I was hoping to not add to the technical debt. IIRC it should work, however, there are some situations where indeed it doesn't.

**Pull request merged**
