### PR TITLE
Fix issue 13489:  Boolean semantics of floating point types should handle float

### PR DESCRIPTION
**Pull request by Geod24**
This might be a little controversial, judging from the issue comments.
Cc @don-clugston-sociomantic @david-eckardt-frequenz

### CODE REVIEW

**Comment by WalterBright** [comment]
This is a no from me for reasons enumerated in the bugzilla issue.

**Comment by Geod24** [comment]
> This is a no from me for reasons enumerated in the bugzilla issue.

Would a deprecation be better ?

**Comment by WalterBright** [comment]
> Would a deprecation be better ?

I don't see any way around needing to be cognizant of NaN if you're working with floating point.

**Comment by Geod24** [comment]
> I don't see any way around needing to be cognizant of NaN if you're working with floating point.

That does not answer the question though.
Deprecating implicit conversion from float to bool would make sure users are aware of what they are doing.
I can buy the "compatibility with C[++]" argument, but it doesn't mean it's the right thing to do.

**Comment by don-clugston-sociomantic** [comment]
@WalterBright :
> I don't see any way around needing to be cognizant of NaN if you're working with floating point.

I agree, but one consequence of that is knowing that you should *never* use `if (f)` with a floating-point type. I cannot conceive a situation where that is not a bug.

Even in the case where the code works correctly, it's code with a secret hidden assumption that `f` is not a NaN. And that's a land-mine that could explode years later.
It's particularly nasty for generic code.

Now _maybe_ it could be allowed in the case where f is a (non-NaN) value known at compile-time, since that's always safe. But even then I suspect it is always bad style.

**Pull request closed without merging**
