### PR TITLE
Fix checkaction=context for tuple expressions with side effects

### PR DESCRIPTION
**Pull request by MoonlightSentinel**

### CODE REVIEW

**Comment by WalterBright** [comment]
"Fix" implies a bug. This needs a corresponding bug report.

**Comment by 12345swordy** [comment]
@MoonlightSentinel care to give walter some context?

**Comment by MoonlightSentinel** [comment]
`-checkaction=context` got support for tuples a few days ago (hence no bug report  [yet] for an unreleased feature).

But there's a corner case that doesn work yet, namely tuple expression promoted to temporaries. The current lowering breaks the `equals` generation for tuples because the rewrite looks for `TupleExp` instead of the current `VarExp`.

The handling of tuples in `opover.d` is weird because it's the only case that looks at the actual expression instead of the type.

**Comment by MoonlightSentinel** [comment]
Rebased to `stable` because the fix is minor and completes a feature of the upcoming release (the tuple support).

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
@MoonlightSentinel : Did a dummy rebase to restart the CI.

**Comment by MoonlightSentinel** [comment]
@Geod24 Thanks!

**Pull request merged**
