### PR TITLE
core.time: use crt_constructor instead of static this

### PR DESCRIPTION
**Pull request by WalterBright**
This will avoid problems with betterC code attempting to import core.time and winding up with a reference to ModuleInfo.

### CODE REVIEW

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
This requires a spec change.

**Comment by RazvanN7** [comment]
Spec change: https://github.com/dlang/dlang.org/commit/eebc0b6a26724dc8c2e568b419655a21a1d9a475

**Review by RazvanN7 — APPROVED** [review]

**Comment by ibuclaw** [comment]
https://github.com/dlang/dmd/pull/14679#issuecomment-1344083731

Why would a betterC user want `core.time` of all modules ?

**Comment by ibuclaw** [comment]
Why does the change not match the PR title?

**Comment by ibuclaw** [comment]
Why aren't there any tests?

**Comment by ibuclaw** [comment]
https://issues.dlang.org/show_bug.cgi?id=22031

**Comment by Geod24** [comment]
Yeah this includes a compiler change, it's not a only druntime change, and should have been 2 PRs. @RazvanN7 .

**Pull request merged**
