### PR TITLE
Fix Issue 9290 - Ability to modify immutable struct members in static array assignment

### PR DESCRIPTION
**Pull request by tramker**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
I don't get why this should be disallowed.

**Comment by tramker** [comment]
I guess it's just analogous to a plain struct assignment, which fails too.
```
struct S { immutable int i; }

void main()
{
        S s1,s2;
        s1 = s2;
}
t.d(6): Error: cannot modify struct s1 S with immutable members
```

**Comment by mathias-lang-sociomantic** [comment]
> I don't get why this should be disallowed.

You could take a pointer to the struct member, and then a later blit over this struct would change the value you're pointing to, destroying the promise made by `immutable` (since the stack address should be the same).

**Comment by tramker** [comment]
Rebased.

**Comment by tramker** [comment]
@WalterBright can you please make a decision on this ? Is such change desirable ?

**Comment by JinShil** [comment]
[All tests are passing](https://auto-tester.puremagic.com/pull-history.ghtml?projectid=1&repoid=1&pullid=6435) as of the date of this comment.  However, the PR has sat in the PR queue for so long it's reach the 1000 status update limit set by GitHub, so you won't see the test statuses updated unless a new commit is pushed (at least that's how I understand it)

**Comment by WalterBright** [comment]
BTW, doing a `git rebase` is an easy way to push a new commit.

**Comment by JinShil** [comment]
> BTW, doing a git rebase is an easy way to push a new commit.

Yes, that was done 3 months ago.  This PR stalled because it was waiting on a decision that was explicitly asked for.  Contributors cannot be expected to continually rebase a PR when all precedent shows that it will only be ignored.

**Pull request merged**
