### PR TITLE
fix Issue 21874 - The test suite fails with most recent GDB versions

### PR DESCRIPTION
**Pull request by ibuclaw**
Use explicit source file name in setting up breakpoints.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
thanks

**Review by MoonlightSentinel — APPROVED** [review]

**Comment by thewilsonator** [comment]
please target stable

**Comment by ibuclaw** [comment]
> please target stable

It's not a compiler bug.

**Comment by thewilsonator** [comment]
If this affects stable this needs to be targeted to it, irrespective of whether or not it is a  compiler bug.

**Comment by TungstenHeart** [comment]
next release is a .0 so this does not matter much. Only issue is if someone wants to work on stable, the fix is not there yet.

**Comment by TungstenHeart** [comment]
Actually this fix should go directly in **both** branch.

**Review by Luhrel — APPROVED** [review]

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
I think we are fine with merging this in master as this primarily affects developers.

**Pull request merged**
