### PR TITLE
Deduplicate StringExp.charAt and getCodeUnit functions

### PR DESCRIPTION
**Pull request by dkorpel**
getCodeUnit was added in https://github.com/dlang/dmd/pull/5427 to encapsulate code unit access, but there already was a function for this: `charAt`. Here I keep the newer one, since it's better named and documented.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
Is getCodeUnit part of the C++ interface?

That charAt is still in the headers may suggest one of the downstream compilers is still using it. @kinke

**Comment by dkorpel** [comment]
> Is getCodeUnit part of the C++ interface?

Methods `numberOfCodeUnits`, `writeTo`, `getCodeUnit` and `setCodeUnit` are in frontend.h, but not in expression.h, which I assumed meant the StringExp interface is completely broken, which in turn means it's probably not used by downstream compilers.

**Comment by ibuclaw** [comment]
> > Is getCodeUnit part of the C++ interface?
> 
> Methods `numberOfCodeUnits`, `writeTo`, `getCodeUnit` and `setCodeUnit` are in frontend.h, but not in expression.h, which I assumed meant the StringExp interface is completely broken, which in turn means it's probably not used by downstream compilers.

No, frontend.h is the broken interface. The expression.h header wins if there are any discrepancies.

**Comment by kinke** [comment]
> That charAt is still in the headers may suggest one of the downstream compilers is still using it.

Yep, LDC is using it [along with `numberOfCodeUnits()`].

**Comment by dkorpel** [comment]
> Yep, LDC is using it [along with `numberOfCodeUnits()`].

I kept `charAt` now as a wrapper to `getCodeUnit`

**Comment by ibuclaw** [comment]
> No, frontend.h is the broken interface. The expression.h header wins if there are any discrepancies.

To clarify, if something appears in frontend.h, but not in the hand-maintained headers, then that's a sign that something should rather be marked as `extern(D)` to keep it private to the front-end.

**Comment by kinke** [comment]
> I kept charAt now as a wrapper to getCodeUnit

Ah, please just go ahead and remove it, and just add `getCodeUnit()` to the .h instead.

**Comment by dkorpel** [comment]
> To clarify, if something appears in frontend.h, but not in the hand-maintained headers, then that's a sign that something should rather be marked as `extern(D)` to keep it private to the front-end.

Okay, I thought the missing member functions in the hand-maintained header meant the vtable would be out of sync, but I now see that `StringExp` is a `final` class.

**Review by kinke — APPROVED** [review]

**Review by maxhaton — APPROVED** [review]

**Pull request merged**
