### PR TITLE
test: Add test to ensure static foreach errors about bad input array at the correct location

### PR DESCRIPTION
**Pull request by ibuclaw**
For example:

```
immutable int[257] data = 1;

void test()
{
    static foreach (byte a, int b; data) { }
    static foreach (byte a, int b; data) { }
    static foreach (byte a, int b; data) { }
    static foreach (byte a, int b; data) { }
}
```
Will report a diagnostic about the bad static foreach on the line where `data` is defined.

Haven't got a good test for this, as all the diagnostics that I were able to trigger are themselves compiler bugs.  So apart from a small improvement in stepping through a program in gdb, the benefit won't be seen until the diagnostic bugs are fixed.

### CODE REVIEW

**Review by thewilsonator — COMMENTED** [review]
tests?

**Comment by ibuclaw** [comment]
Draft, because using the starting location of the static foreach loop is a bit of a blunt hammer to the problem, when really it should be using the locations of the original expressions before they were optimized/expanded.

**Comment by ibuclaw** [comment]
> tests?

Read the opening comment.

**Comment by RazvanN7** [comment]
>  the benefit won't be seen until the diagnostic bugs are fixed.

Which bugs are you exactly referring to? We can fix those so that this can advance.

**Comment by ibuclaw** [comment]
https://issues.dlang.org/show_bug.cgi?id=22005
https://issues.dlang.org/show_bug.cgi?id=22006
https://issues.dlang.org/show_bug.cgi?id=22007
Bonus fixes:
https://github.com/dlang/dmd/pull/12660

**Comment by ibuclaw** [comment]
Comparing the diagnostic before/after, it looks like #12660 fixed it.

Before:
```
bug.d(1): Deprecation: foreach: loop index implicitly converted from `size_t` to `byte`
immutable int[257] data = 1;
                          ^
bug.d(1): Deprecation: foreach: loop index implicitly converted from `size_t` to `byte`
immutable int[257] data = 1;
                          ^
bug.d(1): Deprecation: foreach: loop index implicitly converted from `size_t` to `byte`
immutable int[257] data = 1;
                          ^
bug.d(1): Deprecation: foreach: loop index implicitly converted from `size_t` to `byte`
immutable int[257] data = 1;
                          ^
```
After:
```
bug.d(5): Error: index type `byte` cannot cover index range 0..257
    static foreach (byte a, int b; data) { }
                                   ^
bug.d(6): Error: index type `byte` cannot cover index range 0..257
    static foreach (byte a, int b; data) { }
                                   ^
bug.d(7): Error: index type `byte` cannot cover index range 0..257
    static foreach (byte a, int b; data) { }
                                   ^
bug.d(8): Error: index type `byte` cannot cover index range 0..257
    static foreach (byte a, int b; data) { }
                                   ^
```

**Review by RazvanN7 — APPROVED** [review]

**Comment by ibuclaw** [comment]
Nothing is merging due to Azure pipeline failures. :-(

**Pull request merged**
