### PR TITLE
[stable] core.stdc.stdatomic: Treat all non-DMD compilers as 'C-compatible', not just GDC

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
ping @rikkimax

**Review by ibuclaw — APPROVED** [review]

**Comment by kinke** [comment]
Btw I get a segfault with LDC for a trivial
```D
import core.stdc.stdatomic;

struct S
{
    /*align(16)*/ size_t[2] values;
}

int main() {
    shared(S) s = {[1, 2]};
    return atomic_load_impl(&s).values[0] == 1 ? 0 : 1;
}
```

(reduced from newly added unittest), as the local happens not to be 16-bytes aligned automatically.

clang apparently changes the alignment from 8 (`S`) to 16 (`_Atomic S`) automatically in IR: https://cpp.godbolt.org/z/re4b4a879

@ibuclaw: Does GDC do this? If not, should we?

**Comment by kinke** [comment]
That's consistent with `alignof(_Atomic S)` diverging from `alignof(S)`. The `shared` qualifier in D doesn't have an effect on alignment/size, and AFAICT, cannot, as it wouldn't be transitive then anymore (different struct layouts if members inherit `shared`…). So I guess the alignment needs to be taken care of manually, including https://github.com/dlang/dmd/blob/ef9ed979651691708c79568ca625e042d82d4443/druntime/src/core/stdc/stdatomic.d#L493

**Comment by rikkimax** [comment]
I am well past the point of saying we need an atomic storage class.

Shoehorning it into shared is not working.

**Comment by WalterBright** [comment]
@rikkimax adding another basic type to the language is a major undertaking.

**Comment by rikkimax** [comment]
Yes it is, I am not suggesting it lightly.

Atomic memory needs to be treated quite differently and has very specific platform-specific alignment concerns not just limitations on what operations you can perform on it. Even C has added a storage class for this, it isn't just me saying it must be treated differently at the type system level.

**Comment by ibuclaw** [comment]
I've been on and off thinking of adding a mechanism into the compiler to allow downstream vendors to define their own types via the `enum __special : type;` mechanism.  Maybe complex integers and decimal floats could be exposed this way, not sure about float16 or int128 - I keep flipping between maybe it could work and nah actually,

**Comment by ibuclaw** [comment]
> ```d
> import core.stdc.stdatomic;
> 
> struct S
> {
>     /*align(16)*/ size_t[2] values;
> }
> 
> int main() {
>     shared(S) s = {[1, 2]};
>     return atomic_load_impl(&s).values[0] == 1 ? 0 : 1;
> }
> ```

Looks like I get an instantiation error.

```
error: function 'gcc.builtins.__atomic_load(ulong, shared(const(void))*, void*, int)' is not callable using argument types '(ulong, shared(inout(S)*), shared(S)*, MemoryOrder)'
```

From code:
```
T value;
__atomic_load(T.sizeof, cast(shared)src, &value, smodel);
return *cast(typeof(return)*)&value;
```

Seems to me that should be `Unqual!T value;`

**Comment by ibuclaw** [comment]
> > @ibuclaw: Does GDC do this? If not, should we?
> 
> Looks like I get an instantiation error.
> 

Getting past that, looks like the answer is "no", as there is no inline version of `__atomic_load_16` in GCC - it gets passed to the libatomic support library.

To have ABI compatibility with `_Atomic` fields, that is easily supported though #16072.

**Pull request merged**
