### PR TITLE
Replace writeln with puts in fail19103.d for Phobos independence

### PR DESCRIPTION
**Pull request by nordlow**
Unblocks https://github.com/dlang/phobos/pull/8031

### CODE REVIEW

**Comment by thewilsonator** [comment]
This doesn't make any changes...

**Comment by nordlow** [comment]
> This doesn't make any changes...

It disables a unittest that breaks with https://github.com/dlang/phobos/pull/8031

**Comment by thewilsonator** [comment]
the code differential is zero.

**Comment by nordlow** [comment]
> the code differential is zero.

There's the rename test/fail_compilation/fail19103.d → test/fail_compilation/fail19103.d.disabled

**Comment by thewilsonator** [comment]
ahh, touché.

**Comment by Geod24** [comment]
As explained in https://github.com/dlang/phobos/pull/8031#issuecomment-831129842 the test should be changed to not rely on Phobos instead. The bug report that this test apply to is an `accept-invalid` (meaning stuff that wasn't supposed to compile did compile). The stuff that happened to compile was using `writeln`, but it could just as well use any symbol in druntime AFAICS. The test is neither about `writeln`, nor the suggestion around importing modules for well-known symbols.

**Comment by nordlow** [comment]
> As explained in [dlang/phobos#8031 (comment)](https://github.com/dlang/phobos/pull/8031#issuecomment-831129842) the test should be changed to not rely on Phobos instead. The bug report that this test apply to is an `accept-invalid` (meaning stuff that wasn't supposed to compile did compile). The stuff that happened to compile was using `writeln`, but it could just as well use any symbol in druntime AFAICS. The test is neither about `writeln`, nor the suggestion around importing modules for well-known symbols.

I see. Is it ok to pick the symbol `puts` in druntime instead?

**Comment by nordlow** [comment]
Feel free to toggle auto-merge.

**Comment by nordlow** [comment]
What's wrong with https://buildkite.com/dlang/dmd/builds/19578

**Comment by nordlow** [comment]
Build seems to pass now, auto-merge?

**Comment by nordlow** [comment]
Ahh, I guess I need to squash commits, right?

**Comment by nordlow** [comment]
Squashed.

**Review by Geod24 — APPROVED** [review]

**Comment by nordlow** [comment]
Thanks!

**Pull request merged**
