### PR TITLE
[WIP RFC]making __ctfe usable in static if

### PR DESCRIPTION
**Pull request by UplinkCoder**
Hi this change allows __ctfe to be used in static ifs and static asserts. 
Giving the developer a way to ensure (at compile time) that certain code-paths are never or only used at ctfe.
This effectively undos #4084

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Oops I just spotted a big mistake,,,
fixing.

**Comment by wilzbach** [comment]
@UplinkCoder could you please add a test case to prevent regression and ensure it works on all platforms?

**Comment by MetaLang** [comment]
Isn't this a language change that requires a change to the documentation as well? I don't believe that __ctfe currently works correctly in static contexts.

**Comment by UplinkCoder** [comment]
Before I write docs I'd like to know if the community and leadership are okay with this change.

**Comment by UplinkCoder** [comment]
@wilzbach took care of the tests.

**Comment by schveiguy** [comment]
IIRC, @donc thinks `__ctfe` must be runtime variable. I don't pretend to know any details of how it works or is supposed to. Just wanted to make sure Don sees the proposal.

**Comment by UplinkCoder** [comment]
@schveiguy 
A good idea.
I believe there was a reason back in the day which does not apply anymore.

**Comment by UplinkCoder** [comment]
passing the tests depends on https://github.com/dlang/druntime/pull/1638

**Comment by andralex** [comment]
@klickverbot makes sense

**Comment by UplinkCoder** [comment]
@klickverbot 
I will go for another solution then.
The only real utility of __ctfe as a literal is to ensure that ctfeOnly functions don't end up in the binary. 
The same can archived with a flag on the FuncDeclaration.
Closing as this is not the right way

**Pull request closed without merging**
