### PR TITLE
fix Issue 17275 - [REG 2.072.0] AssertError@declaration.d(2121): Asse…

### PR DESCRIPTION
**Pull request by WalterBright**
…rtion failure

### CODE REVIEW

**Review by ibuclaw — APPROVED** [review]
Thanks, lgtm.

**Comment by ibuclaw** [comment]
Argh, this is only half a fix.  It just moves the assert to another location.

Why on earth do we have CI building the compiler in release mode...

**Comment by CyberShadow** [comment]
This pull request may have introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=20684

**Comment by ibuclaw** [comment]
Does it still happen after #6875?

**Comment by CyberShadow** [comment]
It happens with current master, so, yes.

**Pull request merged**
