### PR TITLE
enable assertions in CI tests

### PR DESCRIPTION
**Pull request by MartinNowak**
I guess we'll still need to fix a couple of things and might have to disable class invariants to reduce the overhead.

### CODE REVIEW

**Comment by WalterBright** [comment]
As I recall, back when (Kenji?) tried it it substantially slowed down the compiler. I want to review the best way forward on this first. I think the non-release mode inserts too many checks.

**Comment by MartinNowak** [comment]
> As I recall, back when (Kenji?) tried it it substantially slowed down the compiler. I want to review the best way forward on this first. I think the non-release mode inserts too many checks.

One way forward is `-release=assert,invariant` so that we can enable asserts but not invariants.

**Comment by mathias-lang-sociomantic** [comment]
>so that we can enable asserts but not invariants

Shameless self-plug: https://github.com/dlang/DIPs/blob/master/DIPs/DIP1006.md

**Comment by wilzbach** [comment]
I like the idea of finally moving forward with DIP1006! BTW one minor thing: if we start to use a different compiler build (non-release) than the one we ship on the auto-tester, how do we make sure that the version we ship doesn't get accidentally broken?

**Comment by ibuclaw** [comment]
Guess you can close #6746 then.

**Comment by wilzbach** [comment]
>  for the time being we might be better off with the slow-down.

Yes, we could simply do this on a faster CI (e.g. [SemaphoreCI](https://semaphoreci.com/product) is twice as fast as Travis - I checked this recently. Compare [SemaphoreCi build](https://semaphoreci.com/wilzbach/dmd/branches/master/builds/6), [Travis build](https://travis-ci.org/dlang/dmd/jobs/315475937)).

> I guess we'll still need to fix a couple of things and might have to disable class invariants to reduce the overhead.

FYI: our CircleCi build already runs without `ENABLE_RELEASE` - though
- the flag default is `BUILD=release, but [doesn't set `ENABLE_RELEASE`](https://github.com/dlang/dmd/pull/7473)
-  [I would like to use `ENABLE_DEBUG` on CircleCi too](https://github.com/dlang/dmd/pull/7528)

**Comment by ibuclaw** [comment]
> Yes, we could simply do this on a faster CI (e.g. SemaphoreCI is twice as fast as Travis

I would say more. On a good day, gdc is built with testsuite and unittests ran in 14 minutes flat on semaphore.

Travis barely could do the same in 50 minutes.

**Comment by MartinNowak** [comment]
What I found implementing https://github.com/dlang/dmd/pull/7980, we could hack this already today.
`-release -unittest` disables all run-time checks but assertions. If we versioned out dmd's few unittests, we'd get what we want for CI.

**Comment by ibuclaw** [comment]
> What I found implementing #7980, we could hack this already today.
-release -unittest disables all run-time checks but assertions.

Heh, wouldn't that be a bug? Or maybe not. It does seem surprising though.

**Comment by MoonlightSentinel** [comment]
FWIW CircleCI and Azure already run the test suite with debug builds. Is this still required?

**Comment by Geod24** [comment]
Don't think so. Also we should have it in the release, but that's another topic.

**Pull request closed without merging**
