### PR TITLE
Fix issues 17141, 12711, 17358, 16235 - Avoid preemptive integer promotion for conditional expressions

### PR DESCRIPTION
**Pull request by SSoulaimane**
`typeof(0 ? byte.init : const(byte))` is unnecessarily promoted to `int`, same thing for `byte` with `short`, `char` with `wchar`... etc.

Closes issues [17141](https://issues.dlang.org/show_bug.cgi?id=17141), [12711](https://issues.dlang.org/show_bug.cgi?id=12711), [17358](https://issues.dlang.org/show_bug.cgi?id=17358), [16235](https://issues.dlang.org/show_bug.cgi?id=16235).

Reverts #9889.

### CODE REVIEW

**Comment by SSoulaimane** [comment]
Needs https://github.com/dlang/phobos/pull/7055.

**Comment by jacob-carlborg** [comment]
If this requires a change in Phobos then this sounds like a breaking change.

**Comment by WalterBright** [comment]
Note that the C99 spec for ?: says: 

"If both the second and third operands have arithmetic type, the result type that would be determined by the usual arithmetic conversions, were they applied to those two operands, is the type of the result."
6.5.15.5

The usual arithmetic conversions are described in 6.3.18. The salient part is "the integer promotions are performed on both operands".

**Comment by WalterBright** [comment]
This PR appears to do two separate things:

1. revert #9889 

2. do some other things which cause it to fail in Phobos?

**Comment by WalterBright** [comment]
Added https://github.com/dlang/dmd/pull/9947 which does a simple revert of #9889

**Comment by jmdavis** [comment]
> do some other things which cause it to fail in Phobos?

It makes it so that several arrays or ranges end up having `const` elements when they didn't before, which breaks code in a few places: https://github.com/dlang/phobos/pull/7055

**Comment by RazvanN7** [comment]
I'm going to close this as the author has abandoned it.

**Pull request closed without merging**
