### PR TITLE
fix Issue 16743 - Intrinsic recognition sometimes fails if a software…

### PR DESCRIPTION
**Pull request by WalterBright**
… implementation is available

Needs https://github.com/dlang/druntime/pull/1695 to be fully operational.

### CODE REVIEW

**Review by UplinkCoder — APPROVED** [review]
LGTM

**Comment by wilzbach** [comment]
Is there an easy way to add an automatic test for these intrinsics, so that we can ensure that we don't break them accidentally in the future?

**Comment by UplinkCoder** [comment]
@wilzbach we could do a match on the object-file.
Of course this will only work on x86.

**Comment by WalterBright** [comment]
As with all code gen transformations, they tend to be very hard to test for. I've tried dumping and comparing object files, but these tend to be extremely sensitive to change and so are very hard to maintain.

**Comment by UplinkCoder** [comment]
In General yes.
In specific cases a check for a simple 3 Byte pattern should be enough for this one.

**Comment by tsbockman** [comment]
If inlining breaks intrinsics, ideally the front-end should be modified to refuse to inline them.

Otherwise, we're depending upon everyone who works on intrinsics in the future to know about this unintuitive quirk - which is not a safe assumption, given that even Ilya didn't understand how they work until a day ago...

**Comment by WalterBright** [comment]
> If inlining breaks intrinsics, ideally the front-end should be modified to refuse to inline them.

That's (one reason) why we have `pragma(inline, false)`.  It's expected that the implementer of the library side of things knows how the compiler works and will do it correctly, since he has to change the compiler in parallel. There are few enough of the intrinsics to justify adding even more logic to the compiler.

**Comment by WalterBright** [comment]
> In specific cases a check for a simple 3 Byte pattern

2 bytes. The third is a modregrm byte which can hold any pattern. Not very reliable.
```
0F BC 45 18             bsf     EAX,018h[RBP]
```

**Comment by UplinkCoder** [comment]
> 2 bytes. The third is a modregrm byte which can hold any pattern. Not very reliable.
But better then nothing. 
It can give false positives 
But never false negatives.

**Comment by andralex** [comment]
Hmm, the coverage tool does not work in 32-bit mode. I'll override codecov and merge this. @MartinNowak is this worth to address in general?

**Pull request merged**
