### PR TITLE
Issue 23885 - [CI] disable failing g++ tests

### PR DESCRIPTION
**Pull request by dkorpel**
Disable them while they fail to set up

### CODE REVIEW

**Comment by Geod24** [comment]
Why do they fail ? It completely removes coverage for g++, I don't think that's a good idea.

**Comment by dkorpel** [comment]
> Why do they fail ?

```
Run # Workaround bug in Github actions
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
Error: Process completed with exit code 2.
```

Whatever that means

> It completely removes coverage for g++

It's not like CI checks that instantly fail provide any coverage, they only waste everyone's time

**Comment by dkorpel** [comment]
This PR doesn't close the issue by the way, whoever wants to maintain them can still fix them

**Comment by maxhaton** [comment]
#15184

**Comment by dkorpel** [comment]
Thanks!

**Pull request closed without merging**
