### PR TITLE
Fix issue 19881 - escaping reference to local through return scope with -dip1000 and @safe

### PR DESCRIPTION
**Pull request by lesderid**
If my understanding of the DIP is correct, I believe this should fix https://issues.dlang.org/show_bug.cgi?id=19881.

First contribution to dmd, so any feedback most welcome.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Looks fine to me. cc @WalterBright

**Comment by thewilsonator** [comment]
Also please retarget this to stable.

**Comment by thewilsonator** [comment]
You need to rebase this...

**Comment by lesderid** [comment]
@thewilsonator Yeah, my bad, figured I could do it through GitHub, but seems like that's never a good idea.

**Comment by thewilsonator** [comment]
Heh, yep.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
@WalterBright if you're fine with this just go ahead and merge.

**Review by jacob-carlborg — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
