### PR TITLE
add more isXxxxStatement() functions

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by RazvanN7** [comment]
Shouldn't you add the overriding methods as well?

**Comment by WalterBright** [comment]
They're not virtual.

**Comment by RazvanN7** [comment]
Oh yeah, sorry, I didn't pay attention and thought this was the same pattern as for Dsymbols.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Buildkite failure unrelated.

**Pull request merged**
