### PR TITLE
fix Issue 23418 - double argument is passed on stack, but assumed to …

### PR DESCRIPTION
**Pull request by WalterBright**
…be in XMM0 register

I replaced the "check the generated asm" tests, because the "known good" assembler was wrong. Replaced it with a runtime check.

### CODE REVIEW

**Comment by WalterBright** [comment]
blocking https://github.com/dlang/dmd/pull/14567

**Comment by WalterBright** [comment]
@RazvanN7 @dkorpel ping

**Review by dkorpel — APPROVED** [review]
I'm trying to grasp the issue. So all this time, `double` parameters on 32-bit Linux with `-O` were completely broken, because the caller and callee were not consistent about the ABI? Would the new `runnable/cdcmp.d` test fail on 32-bit Linux with before this fix?

**Comment by ibuclaw** [comment]
Does this affect extern(C/C++) codegen? If so target stable.

**Comment by WalterBright** [comment]
> Would the new runnable/cdcmp.d test fail on 32-bit Linux with before this fix?

Yes. Oops.

@ibuclaw I'd rather not, as this problem is blocking my further work on master with XMM code gen.
> So all this time, double parameters on 32-bit Linux with -O were completely broken, because the caller and callee were not consistent about the ABI?

Ironically, most of the time it worked because the XMM0 parameter was pushed onto the stack, and yet remained in XMM0. 

The bug was possible on memory models that didn't pass floating point values in XMM registers. But for the bug to appear, a set of other conditions have to be met. 

>

**Comment by ibuclaw** [comment]
@WalterBright you can always merge stable into master immediately afterwards.  In fact, I've got it pending on my release tasks, but I'm still waiting for you to reply to your emails w.r.t ftp.digitalmars.com access. :-)

**Comment by WalterBright** [comment]
I thought Jan was doing that?

**Comment by ibuclaw** [comment]
> I thought Jan was doing that?

Seen no response from him just yet.  You are part of the wheel group though, so as a fallback admin, you can `su` up and add me to the group as well.

**Comment by WalterBright** [comment]
Could you email me exactly what to do? Thanks!

**Pull request merged**
