### PR TITLE
provided toString() because strlen must die

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Review by JinShil — APPROVED** [review]
You could replace a `toChars` or two to get full test coverage.

**Comment by Geod24** [comment]
SemaphoreCI was stuck.
I think it'll be better to store the length instead of calling `strlen` on every `toString`, but it's already an improvement.

**Comment by jacob-carlborg** [comment]
Here new public symbols were added without Ddoc 😞.

**Comment by jacob-carlborg** [comment]
How will this affect the C++ headers?

**Comment by JinShil** [comment]
> Here new public symbols were added without Ddoc 😞.

Have you ever tried to convince @WalterBright to do things like this?  It's better if we just merge and add the docs ourselves in a separate PR.

**Comment by jacob-carlborg** [comment]
We managed to get him to do PRs instead of pushing directly.

**Comment by WalterBright** [comment]
> How will this affect the C++ headers?

It won't. They are not callable from C++, and they don't occupy a slot in the vtbl[].

> without Ddoc

If it did something different than every other `toString()` in dmd, then it would need a Ddoc. Actually, if it did something different than every other `toString()`, it should have a different name as well as a Ddoc.

As always, use your best judgement.

**Comment by WalterBright** [comment]
> I think it'll be better to store the length instead of calling strlen on every toString, but it's already an improvement.

It may be. But by adding this function, the need for strlen becomes encapsulated, and is not leaked to the users of the object. A sign of effective encapsulation is being able to change the underlying data structure without needing to change any users of the object.

**Pull request merged**
