### PR TITLE
win32.mak: fix cleanup of ddmd build

### PR DESCRIPTION
**Pull request by rainers**
by moving definitions before the clean target. No other changes in this PR, though some more files should also be removed.

### CODE REVIEW

**Comment by yebblies** [comment]
Thanks.  LGTM.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Anyone wants to work on gmake targets for Windows, btw?

**Comment by braddr** [comment]
And if you do, please make the targets line up with the posix.mak targets rather than the win*.mak targets for the sake of bringing all the platforms in line.

**Comment by yebblies** [comment]
> Anyone wants to work on gmake targets for Windows, btw? We have an OK from Walter for that.

Please, no.  What we need is a D build script.

**Comment by MartinNowak** [comment]
Called dake or what, I don't want to spend my time reprogramming make.
Simple build scripts are rather hard to maintain (we want to replace dm make, because it can't do pattern rules).
But then again, might be worth a try to write a D script.

**Pull request merged**
