### PR TITLE
Fix Issue 18955 - extern(C++) default struct mangling is overridden when interacting with a cppmangle = class template

### PR DESCRIPTION
**Pull request by JinShil**
I'm not all that confident in this fix.  If this isn't the right fix, please help me with some advise.  Thanks.

### CODE REVIEW

**Comment by JinShil** [comment]
There's some strange difference between Appveyor and the auto-tester.  If I adjust the test to make Appveyor pass, then auto-tester fails.  If I adjust the test to make the auto-tester pass, then Appveyor fails.  Can anyone explain the discrepancy?

**Comment by TurkeyMan** [comment]
I think this LGTM, but I didn't do it because I didn't understand the surrounding code enough to have confidence. It kinda looked like the original code was deliberate.

**Comment by JinShil** [comment]
auto-tester Win32_64 expects: 
`?test@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@@std@@@Z`

auto-tester Win32 expects:
`?test@@YAXABV?$basic_string@std@DU?$char_traits@std@D@1@@std@@@Z`

appveyor (Win32 - I think) expects:
`?test@@YAXABV?$basic_string@DU?$char_traits@D@std@@@std@@@Z`

There's no way I can satisfy that.  Any idea why the auto-tester and appveyor expect different results?

**Comment by TurkeyMan** [comment]
Did you get those mangled names from MSVC? It's not like DMC vs MSVC proper is it?

**Comment by JinShil** [comment]
I took them from the error messages generated by the auto-tester and Appveyor.  I don't know which C++ compilers they are employing.

**Comment by rainers** [comment]
autotester's Win32 test is the only server building with dmc.

Looking at cppmanglewin.d, there's a flag `IS_DMC` showing that dmc's mangling is slightly different than VS.  You'll have to version the check with `version(CRuntime_DigitalMars)`.

**Comment by rainers** [comment]
> auto-tester Win32 expects:
> `?test@@YAXABV?$basic_string@std@DU?$char_traits@std@D@1@@std@@@Z`

This string doesn't demangle with [UnDecorateSymbolName](https://docs.microsoft.com/en-us/windows/desktop/api/dbghelp/nf-dbghelp-undecoratesymbolname).

**Comment by JinShil** [comment]
auto-tester and Appveyor are all green now.  Thank you, @rainers.

**Comment by ZombineDev** [comment]
DAutoTest failed, due to a timeout:
```
.generated/stable_dmd-2.081.1/dmd2/linux/bin64/dub build --compiler=.generated/stable_dmd-2.081.1/dmd2/linux/bin64/dmd --root=ddoc && \
	mv ddoc/ddoc_preprocessor .generated/ddoc_preprocessor
Fetching stdx-allocator 2.77.2 (getting selected version)...
Fetching libdparse 0.8.7 (getting selected version)...
Timeout was reached on handle DF7600
posix.mak:920: recipe for target '.generated/ddoc_preprocessor' failed
```

Restarting...

**Comment by ZombineDev** [comment]
@JinShil, can you rebase to restart DAutoTest?

**Comment by ZombineDev** [comment]
@rainers is this PR good to go now?

**Comment by JinShil** [comment]
@TurkeyMan If you could write a test case that link to stdc++, I'll incorporate it into the PR and extend the test to multiple platforms.

**Comment by TurkeyMan** [comment]
@JinShil Writing any tests that link to stdc++ is super hard, since there are a lot of C++ tests that all use different C++ compilers, and different STL's, and most of the machinery to make correct decisions isn't merged yet (see my recent PR's).
What Rainer says is the right thing to do... or the test you have here is fine... hopefully it'll be self-testing with proper C++ link tests pretty soon.

**Comment by thewilsonator** [comment]
@JinShil https://godbolt.org/z/6QZzsf using MSVC 2015

**Comment by TurkeyMan** [comment]
Why isn't this merged? Is something holding it up?

**Comment by ZombineDev** [comment]
@JinShil can you incorporate the tests suggested by @rainers?

**Comment by rainers** [comment]
> @JinShil can you incorporate the tests suggested by @rainers?

Maybe it's simpler to merge this and I make https://github.com/rainers/dmd/commit/194cdc13d3bc183e8382860cfa47fdf66a7154fc another PR? It might expose some non-Windows issues, though.

**Comment by ZombineDev** [comment]
@rainers sounds good, in this case feel free to approve and merge this PR.

**Review by rainers — APPROVED** [review]

**Pull request merged**
