### PR TITLE
more enums to ubyte's

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by kinke** [comment]
Note that we've had mangling problems on Windows before v2.086 (https://github.com/dlang/dmd/pull/9605), so if any of these are used as params in the C++ interface, the min host compiler version might need to be bumped.

**Comment by 12345swordy** [comment]
rebase please

**Comment by WalterBright** [comment]
@MoonlightSentinel Can we **please** do something about these network heisenbugs? Here's yet another one in buildkite/dmd Build:
```
Preparing working directory | 2s
-- | --
  | Running commands | 0s
  | Print environment | 0s
  | Linux ci-agent-be765bef-9cd1-4979-8732-a90a52bd9c0e 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  | git version 2.7.4
  | GNU Make 4.1
  | Built for x86_64-pc-linux-gnu
  | Copyright (C) 1988-2014 Free Software Foundation, Inc.
  | License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
  | This is free software: you are free to change and redistribute it.
  | There is NO WARRANTY, to the extent permitted by law.
  | /bin/bash: line 4: --version: command not found
  | c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
  | Copyright (C) 2015 Free Software Foundation, Inc.
  | This is free software; see the source for copying conditions.  There is NO
  | warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  |  
  | GNU gold (GNU Binutils for Ubuntu 2.26.1) 1.11
  | GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
  | Copyright (C) 2016 Free Software Foundation, Inc.
  | License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
  | This is free software: you are free to change and redistribute it.
  | There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
  | and "show warranty" for details.
  | This GDB was configured as "x86_64-linux-gnu".
  | Type "show configuration" for configuration details.
  | For bug reporting instructions, please see:
  | <http://www.gnu.org/software/gdb/bugs/>.
  | Find the GDB manual and other documentation resources online at:
  | <http://www.gnu.org/software/gdb/documentation/>.
  | For help, type "help".
  | Type "apropos word" to search for commands related to "word".
  | /bin/bash: line 8: dmd: command not found
  | warning: failed to remove build/ldc-developers-ldc/bootstrap
  | 🚨 Error: The command exited with status 1
```

https://issues.dlang.org/show_bug.cgi?id=21313

Each of the CI tests has its own susceptibility to network failures, and the odds of getting a clean run through all of them are low, wasting a lot of developer, resource and clock time.

**Review by thewilsonator — APPROVED** [review]

**Comment by 12345swordy** [comment]
All green here.

**Pull request merged**
