### PR TITLE
Issue 13879 - Default inizialization of function pointers array

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=13879

### CODE REVIEW

**Comment by yebblies** [comment]
Is this going to break it when `e2` _does_ convert to `e1->type`?  Is that handled somewhere else?

**Comment by 9rnsr** [comment]
Today `inferType`works only for `FuncExp`, so no other cases will be broken.

**Comment by yebblies** [comment]
This is why I ask, thanks.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
