### PR TITLE
 DMD now compiles with LDC

### PR DESCRIPTION
**Pull request by welkam**
Made changes to makefile so DEBUG and RELEASE would compile with LDC. Initial goal was to make it so you can compile with clang, gcc and dmd, ldc, gdc but compilation errors prevented gcc addition and incomplete gdc documentation prevented gdc addition.

P.s. this is my first pull request

### CODE REVIEW

**Comment by wilzbach** [comment]
You do realize that DMD is has been buildable forever on every commit and PR succesfully with all three compilers (and passing the testsuite)?
You probably aren't using the DMD-like ldmd or gdmd interface?

**Comment by welkam** [comment]
No im not using DMD-like interfaces. The documentation about building DMD is lacking. Thanks for pointing this out and sorry for any inconvenience I created

**Comment by iain-buclaw-sociomantic** [comment]
> gdc but compilation errors prevented gcc addition and incomplete gdc documentation prevented gdc addition.

You could back this claim up with a bug report, or at least say what you thought was missing.  Sounds like a user mistake though.

**Comment by welkam** [comment]
> > gdc but compilation errors prevented gcc addition and incomplete gdc documentation prevented gdc addition.
> 
> You could back this claim up with a bug report, or at least say what you thought was missing. Sounds like a user mistake though.

when you set HOST_CXX=gcc you get errors about flags like 
error: command line option ‘-std=gnu++98’ is valid for C++/ObjC++ but not for C
error: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C

and compilation errors in dmd/root/newdelete.c
dmd/root/newdelete.c:26:8: error: expected identifier or ‘(’ before string constant
 extern "C"
        ^~~
My assumption was that files that end with .c contains c code.

And for gdc there were not documentation about option for "Show use of deprecated features as errors"

**Comment by iain-buclaw-sociomantic** [comment]
> My assumption was that files that end with .c contains c code.

The front-end is written in C++.

> And for gdc there were not documentation about option for "Show use of deprecated features as errors"

See `gdc --help=d`, but you are going to have to use your intuition there, as warnings map more closely to gcc-style - `-Wdeprecated -Werror`.

**Comment by WalterBright** [comment]
> The front-end is written in C++.

Not for much longer!

**Pull request closed without merging**
