### PR TITLE
jumpless signed divide by 2

### PR DESCRIPTION
**Pull request by WalterBright**
Because jumpless is better.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Seems to break unittests of `mir` and `ocean`.

**Comment by 12345swordy** [comment]
What unit test in question that this PR break @UplinkCoder?

**Comment by UplinkCoder** [comment]
@12345swordy this: https://buildkite.com/dlang/dmd/builds/14374#60eed338-4991-4604-b3a7-a33abd597590
and this: https://buildkite.com/dlang/dmd/builds/14374#076124f8-2161-45d0-ab7d-f6cee445b65d

**Comment by WalterBright** [comment]
Found the problem, and added a test case for it so the test suite will catch it rather than buildkite.

**Pull request merged**
