### PR TITLE
Add support for the in operator in dassert

### PR DESCRIPTION
**Pull request by wilzbach**
Required for https://github.com/dlang/druntime/pull/2463

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
There's no test here or in the druntime PR.

**Comment by wilzbach** [comment]
Yup, the Druntime PR is required

> There's no test here or in the druntime PR.

Yeah I needed to figure out the order on how the PRs can compile/pass the CIs in a proper order.
The tests are now part of the Druntime PR.

**Review by WalterBright — APPROVED** [review]

**Comment by thewilsonator** [comment]
Looks like appveyor timed out?

**Comment by wilzbach** [comment]
> Looks like appveyor timed out?

Yup. Rebased.

**Pull request merged**
