### PR TITLE
install g++-multilib to fix 32-bit tests

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Looks good.
Someone please pull.

**Comment by WalterBright** [comment]
Shouldn't the Travis Cl not fail if this PR works?

**Comment by UplinkCoder** [comment]
It fails because it cannot find 32bit curl

**Comment by MartinNowak** [comment]
Would have made sense to wait. What should we do about the OSX failure? Can we skip a single test for a certain platform?

**Comment by UplinkCoder** [comment]
We could version the test out for 32bit mac... but I am not it is a good thing to do.

**Comment by UplinkCoder** [comment]
also gdc needs the multilib version of gcc-4.9

**Pull request merged**
