### PR TITLE
Issue 8269 - The 'with statement' does not observe temporary object lifetime

### PR DESCRIPTION
**Pull request by yebblies**
Do not create a temporary with a dtor inside an expression.

https://issues.dlang.org/show_bug.cgi?id=8269

### CODE REVIEW

**Comment by MartinNowak** [comment]
That's actually worth mentioning in the changelog @yebblies.

**Comment by MartinNowak** [comment]
Just a few lines @yebblies, it's a really nice feature.

**Comment by yebblies** [comment]
Really?  It's just a bugfix, and only affects using 'with' with an rvalue that has a dtor.

**Comment by MartinNowak** [comment]
```d
with (File("output.log", "w"))
{
    writeln("Content");
}
// File is automatically closed
```

**Comment by MetaLang** [comment]
That is quite a nice pattern. I think Python has something similar.

**Comment by MartinNowak** [comment]
I think that's the reason why there was a 250$ bounty on this.

**Comment by yebblies** [comment]
Ok what do I need to do?

**Comment by MartinNowak** [comment]
The changelog file is here, just add a few words about an old bug being fixed and a small example, e.g. the one from above.
https://github.com/D-Programming-Language/dlang.org/blob/master/changelog.dd
Here is a simple example pull for package level protection.
https://github.com/D-Programming-Language/dlang.org/pull/922

**Pull request merged**
