### PR TITLE
Make hex strings implicitly convert to integer arrays

### PR DESCRIPTION
**Pull request by dkorpel**
Supersedes https://github.com/dlang/dmd/pull/16125, see https://github.com/dlang/dmd/pull/16125#issuecomment-1924480000

### CODE REVIEW

**Comment by ibuclaw** [comment]
Mind the BigEndian target failures https://github.com/dlang/dmd/pull/16094#issuecomment-1969487448

**Comment by dkorpel** [comment]
Thanks, I'll fix the hex string printing routine in another PR

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
Should have this gone in stable instead?

**Comment by dkorpel** [comment]
Since it was supposed to be in 2.108, and it was merged after the cut, yes. https://github.com/dlang/dmd/pull/16293

**Pull request merged**
