### PR TITLE
Issue 15855 - "a[{for" causes dmd to segfault

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by WalterBright** [comment]
The Windows test failure looks like some CR-LF problem in the error message generation.

**Comment by WalterBright** [comment]
I'd also like to see in the test case the following text:
`https://issues.dlang.org/show_bug.cgi?id=15855`
I know we haven't done that before. But I recently enhanced my text editor to recognize and make clickable URLs in the text, and it is awfully convenient.

**Comment by 9rnsr** [comment]
> The Windows test failure looks like some CR-LF problem in the error message generation.

I removed `TEST_OUTPUT` so it's not much important.

**Comment by 9rnsr** [comment]
Thanks!

**Pull request merged**
