### PR TITLE
[REG2.068a] Issue 14609 - Github HEAD: DMD assertion failure for valid code

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14609

### CODE REVIEW

**Comment by yebblies** [comment]
So that old comment is no longer valid?  What changed?

**Comment by 9rnsr** [comment]
In old days, field offsets were calculated by using offset value in Scope object and it had depended on the semantic order of each fields and it was problematic against forward references.
Today, field offsets are calculated by `Dsymbol::setFieldOffset()` and it can correctly process each fields by lexical order. 
Finally `Scope::offset` was removed by refactoring in #3462.

**Comment by yebblies** [comment]
Sounds good to me.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks!

**Pull request merged**
