### PR TITLE
Fix bugzilla issue 24846 - atomicLoad does not work for class arguments with -preview=nosharedaccess

### PR DESCRIPTION
**Pull request by rikkimax**

### CODE REVIEW

**Comment by thewilsonator** [comment]
can this not be fixed in druntime?

**Comment by thewilsonator** [comment]
> *cast(shared(inout(Foo))*)resultValuePtr

IIRC that should then be an unsafe operation, and should therefore be trusted.

**Comment by rikkimax** [comment]
> > _cast(shared(inout(Foo))_)resultValuePtr
> 
> IIRC that should then be an unsafe operation, and should therefore be trusted.

Yes, but I don't see any ``@safe`` checks. This is on for all code.

**Comment by s-ludwig** [comment]
This was my thought, too, that the whole "nosharedaccess" logic should only be active in `@safe` code. There are definitely cases where user code would want to circumvent the checks, possibly in an inline assembly block, or by using an ordinary memory access because outer conditions make it safe to do on a particular hardware architecture. There needs to be a way to circumvent the checks.

Now, to be fair, you can already cast away shared, which is naturally `@system`, and then perform the operation, so we could consider that to be *the* way of circumventing the checks.

**Comment by rikkimax** [comment]
> possibly in an inline assembly block

There is no reason to do this.

By not using core.atomic you are bypassing any optimization opportunity that the compiler can offer you. Doing it yourself is both platform specific and compiler IR specific.

**Comment by rikkimax** [comment]
If we want to turn this on only in ``@safe`` we're going to need to have a different discussion to decide that. As that is a DIP level change.

**Review by thewilsonator — APPROVED** [review]
I don't like this approach, but lets get this fix in

**Pull request merged**
