### PR TITLE
Revert "Remove backend os.d"

### PR DESCRIPTION
**Pull request by WalterBright**
Reverts dlang/dmd#9864

Please stop changing the back end. It thoroughly messes up DMC++.

### CODE REVIEW

**Comment by adamdruppe** [comment]
@WalterBright do you think we can add dmc to the public test somehow? Then other people would realize what is going on here and can save you this trouble.

**Review by ibuclaw — APPROVED** [review]

**Comment by WalterBright** [comment]
It's more than just compiling DMC++. There's a whole test suite for it. As I'm sure you're aware, C++ is a tricky language to compile, and the compiler is fragile because of it. I don't think it makes much sense for D to check in the code for it, as nobody in the D community is interested in it.

I don't mind if people create PRs for the backend. But I do mind if both the people creating PRs and the people approving and pulling them have no expertise with it and even less interest. Each of us has different areas of expertise, and to get a PR merged needs at least one of the involved parties to have expertise with it.

For example, I have no expertise in installation or test framework issues, and defer decisions about them to people who have it. I defer to Jacob regarding issues with the ObjC support. And so on.

**Comment by Herringway** [comment]
A single person only has so much mental bandwidth. You really should lighten your burden.

**Comment by adamdruppe** [comment]
Well, there's gotta just be some way to make it clear to people that these things are ok for dmd, but have side effects on dmc.

I guess you could institute a policy of nobody merges backend stuff without your ok.

**Pull request merged**
