### PR TITLE
can't directly load a TLS variable in IASM

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Why isn't this detected before becoming a linker error?  Shouldn't iasm give an error instead of generating an invalid relocation?

**Comment by 9rnsr** [comment]
@yebblies It would be possible by looking `v->isThreadlocal()` in `asm_merge_symbol()`.

**Comment by braddr** [comment]
This feels like it's papering over a bigger issue.

**Pull request merged**
