### PR TITLE
fix Issue 16625 - undeprecated switch fallthrough error

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Review by UplinkCoder — COMMENTED** [review]
Why is the deprecated again ?
It is so much easier to leave it an error.
(from a compiler-dev point of view)

**Comment by MartinNowak** [comment]
Because it broke code without being deprecated before (it was a warning).
Since you need to deal w/ goto case, you have to implement this anyhow.

**Comment by UplinkCoder** [comment]
fair enough

**Comment by Geod24** [comment]
Sorry for the confusion ! The documentation would also need updating then (it currently state that its an error).

**Comment by MartinNowak** [comment]
> The documentation would also need updating then (it currently state that its an error).

Which documentation are you referring to, can't find anything saying that. Although it's a bit inaccurate, I tend to consider anything deprecated as error deprecations are on by default, and people should use -de once code was upgraded to a newer release. Running with -d should be considered a very bad practice.

**Comment by mathias-lang-sociomantic** [comment]
According to http://dlang.org/spec/statement.html#SwitchStatement :

> A ScopeStatementList must either be empty, or be ended with a ContinueStatement, BreakStatement, ReturnStatement, GotoStatement, ThrowStatement or assert(0) expression unless this is the last case. This is to set apart with C's error-prone implicit fall-through behavior. goto case; could be used for explicit fall-through:
> [Examples that say implicit fall-through is an error]

That was documented this way ages ago. But for all this time it was only a warning.
Also there is no mention of the deprecation in http://dlang.org/deprecate.html .

**Comment by UplinkCoder** [comment]
Keep it an error please.

**Comment by MartinNowak** [comment]
Sounds fine then, deprecation doesn't mean we're allowing it. It's just about not breaking previously working code without deprecation. We can't held people liable for our specs if the compiler doesn't check them.

**Pull request merged**
