### PR TITLE
Revert "Convert TXXXX to Type.Kind"

### PR DESCRIPTION
**Pull request by WalterBright**
Reverts dlang/dmd#7747

This makes things much more verbose. It's harder to read, and all those _ postfixed names are just ugly. It's a good idea gone too far. Please no.

### CODE REVIEW

**Comment by JinShil** [comment]
Comments copied from #7747:

The nested enum avoids a name collision between `class Type` and `enum Type`.  we could have used something like  `TYPE` for the enum, but we were attempting to follow the [style guide](https://dlang.org/dstyle.html).  The verbosity can be handle easily using D's other fantastic features such as 

```D
with(Type.Kind) 
{  
    auto t = uint8; 
}
```
or
```D
alias T = Type.Kind;
auto t = T.uint8;
```

The nested enum was also used for `Prot.Kind` for similar reasons.  I think it's a good pattern to follow when there is a name collision between the enum and another type.

**Comment by andralex** [comment]
Let's get this in and discuss a solution that touches less code. Thanks!

**Review by andralex — APPROVED** [review]

**Comment by andralex** [comment]
@WalterBright you'll need to rebase this

**Comment by JinShil** [comment]
> Let's get this in and discuss a solution that touches less code. Thanks!

Would you support something more incremental.

**Comment by andralex** [comment]
@JinShil yah, see comment in the original PR.

**Comment by WalterBright** [comment]
The jenkins tests appear to be stuck?

**Comment by JinShil** [comment]
> The jenkins tests appear to be stuck?

@WalterBright Jenkins shows that all tests have passed, but it didn't seem to update GitHub.  I don't appear to have rights to manually merge.  @WalterBright, I'd say just go ahead and manually merge if you can.  Otherwise, please try to rebase and force push to wake things up.

**Comment by JinShil** [comment]
I restarted the Jenkins test.

**Comment by WalterBright** [comment]
Thanks for the help

**Pull request merged**
