### PR TITLE
switch backend to Boost License

### PR DESCRIPTION
**Pull request by WalterBright**
Yes, this is for real!

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
You can remove `backendlicense.txt` now ;-)

**Comment by JackStouffer** [comment]
The make files need to be update now that `backendlicense` is no longer there :P

**Review by andralex — APPROVED** [review]
This is a historical moment!

**Review by dnadlinger — APPROVED** [review]
Looks good now.

**Comment by DmitryOlshansky** [comment]
Pardon for the noise, but: Horrray!!!!

If I understand it correctly this basically allows us to include DMD in any Linux distribution with no strings attached, most awesome.

**Comment by gvzq** [comment]
This is great!

**Comment by quickfur** [comment]
Awesome!

**Comment by cogwheel** [comment]
OSSome!

**Comment by ZHANITEST** [comment]
Nice news! :+1:

**Comment by i336** [comment]
YAY! I can learn D now! (Wider [OSS] community support and implementational practicality always dissuaded me - learning new things sometimes takes me a little while, so I only want to focus on stuff that will generally be successful with the least number of caveats.)

**Comment by timotheecour** [comment]
Unexpected and awesome. Great that this wasn't announced 7 days earlier.

**Pull request merged**
