### PR TITLE
Move codegen for initializing _argptr into Target

### PR DESCRIPTION
**Pull request by ibuclaw**
@yebblies - Don't merge yet, I need to think of a name for the hook, too tired right now, will update in the morning.

### CODE REVIEW

**Comment by yebblies** [comment]
I feel like gdc was doing it the right way here.

**Comment by yebblies** [comment]
Needs ddmd update!

**Comment by ibuclaw** [comment]
What do I need to import?  ``init``, ``declaration`` ?

**Comment by ibuclaw** [comment]
I've been too busy to think of a name for ``XXXX`` - any takers?

**Comment by ibuclaw** [comment]
@yebblies - I don't fancy myself learning how to do *that* in dmd's backend codegen speak.

**Comment by ibuclaw** [comment]
I guess I need ``func`` and ``dscope`` too?  Or maybe this PR brings in too many dependencies. ;)

**Comment by yebblies** [comment]
> I don't fancy myself learning how to do that in dmd's backend codegen speak. GDC may be doing it right, but so long at the frontend emits the DeclarationExp that's all I care about for the moment.

I think I know how to do it in the dmd backend/glue layer.

Can you basically do `va_start(_argptr, ...);`?  I'll have to look a bit closer.

> I guess I need func and dscope too? Or maybe this PR brings in too many dependencies. ;)

Yeah, I like that ddmd makes it pretty clear when you're adding new dependencies.

**Comment by ibuclaw** [comment]
> I think I know how to do it in the dmd backend/glue layer.
> Can you basically do va_start(_argptr, ...);? I'll have to look a bit closer.

Nope, ``va_start``, ``va_copy`` and ``va_end`` are compiler provided functions (does not correspond to an extern C library function).

**Comment by ibuclaw** [comment]
> Nope, va_start, va_copy and va_end are compiler provided functions 

Unless of course you mean callilng DMD's versions of ``core.stdc.stdarg.va_start`` from the backend, in which case, yes that would work.

**Comment by yebblies** [comment]
Yeah, I mean inserting a call to the backend intrinsic `va_start`.

**Comment by ibuclaw** [comment]
> Yeah, I mean inserting a call to the backend intrinsic va_start.

Would need 32-bit support by the looks of it.  Shouldn't be difficult as that's the easiest of the two ABI's to implement.

**Comment by yebblies** [comment]
Yeah, 32-bit is delightfully trivial.

**Comment by ibuclaw** [comment]
This needs rebasing

**Comment by ibuclaw** [comment]
https://github.com/dlang/dmd/pull/5779

I'll close this as per above.

**Pull request closed without merging**
