### PR TITLE
DWARF: Add `immutable` type

### PR DESCRIPTION
**Pull request by Luhrel**
Waiting for https://github.com/dlang/dmd/pull/11426 for proper testing

### CODE REVIEW

**Comment by Luhrel** [comment]
Arf, `Unknown TAG value: 4b` on Ubuntu 16.04.

**Comment by ibuclaw** [comment]
Shouldn't you implement this in gdb first?  Otherwise it will be a detriment to user's debugging experience.

**Comment by ibuclaw** [comment]
> Arf, `Unknown TAG value: 4b` on Ubuntu 16.04.

Yeah, the distribution predates dwarfv5, you'll need 20.04 or later to be safe.

**Comment by Luhrel** [comment]
> Shouldn't you implement this in gdb first? Otherwise it will be a detriment to user's debugging experience.

I may do it, but I'll implement DWARFv4 first.

**Comment by ibuclaw** [comment]
> > Shouldn't you implement this in gdb first? Otherwise it will be a detriment to user's debugging experience.
> 
> I may do it, but I'll implement DWARFv4 first.

It looks like the addition is trivial enough, take the `atomic` type as an example template:

https://github.com/bminor/binutils-gdb/blob/6a780b6766378e3dc9610cba7e12d7eaba196f52/gdb/dwarf2/read.c#L22976-L22978
https://github.com/bminor/binutils-gdb/blob/6a780b6766378e3dc9610cba7e12d7eaba196f52/gdb/dwarf2/read.c#L17929-L17945
https://github.com/bminor/binutils-gdb/blob/2c6f2aa66499332b7bb016869fd01267ca1b52ef/gdb/gdbtypes.h#L2359
https://github.com/bminor/binutils-gdb/blob/2c6f2aa66499332b7bb016869fd01267ca1b52ef/gdb/gdbtypes.h#L203-L214
https://github.com/bminor/binutils-gdb/blob/2c6f2aa66499332b7bb016869fd01267ca1b52ef/gdb/gdbtypes.h#L254-L258
https://github.com/bminor/binutils-gdb/blob/9bb305b389f98a1ea271463a0a8ded70317e3f74/gdb/gdbtypes.c#L773-L782

The other part is adding a language specific type-printing for the D language to handle `TYPE_IMMUTABLE` and print `immutable` on the gdb interpreter.  I did write up a mostly complete implementation a few years ago, I may be in a position in a month or two to actually commit to finishing it.

**Review by ljmf00 — CHANGES_REQUESTED** [review]
Thanks! I tested this locally and looks good to me, just a small thing on the test cases

**Review by ljmf00 — APPROVED** [review]
LGTM

**Comment by nordlow** [comment]
For reference see section 5.3 "Type Modifier Entries" in https://dwarfstd.org/doc/DWARF5.pdf.

**Pull request merged**
