### PR TITLE
Issue 13295 - [CTFE] Modifications of const user type disappear

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=13295

Also I add a test case for issue 13297, because the problem is properly fixed by #4227.
[Issue 13297](https://issues.dlang.org/show_bug.cgi?id=13297) - [CTFE] Modifications of user type pointer member passed by ref in function disappear

### CODE REVIEW

**Comment by 9rnsr** [comment]
Added one more test case for:
[Issue 7874](https://issues.dlang.org/show_bug.cgi?id=7874) - [CTFE] internal error: unsupported assignment (x OP= y) = z

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by braddr** [comment]
Pull updated, auto_merge toggled off

**Comment by 9rnsr** [comment]
I just fixed merge conflict in `test/compilable/interpret3.d`, so re-enable auto-merge.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Pull request merged**
