### PR TITLE
End deprecation period for the delete keyword

### PR DESCRIPTION
**Pull request by ibuclaw**
First deprecated in February 2018.  The `delete` keyword - similar to `creal` - is a slow burning deprecation that needs extra care taken before we really do remove it from the language.  Let's see how bad the state of affairs really is at this juncture.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
Runnable tests still need updating.

**Comment by thewilsonator** [comment]
Buildkite is green, save for 
```
src/rt/lifetime.d(1210): Error: The `delete` keyword has been removed.  Use `object.destroy()` (and `core.memory.GC.free()` if applicable) instead.
--
  | src/rt/lifetime.d(1219): Error: The `delete` keyword has been removed.  Use `object.destroy()` (and `core.memory.GC.free()` if applicable) instead.
  | src/rt/lifetime.d(2605): Error: The `delete` keyword has been removed.  Use `object.destroy()` (and `core.memory.GC.free()` if applicable) instead.
  | src/rt/lifetime.d(2610): Error: The `delete` keyword has been removed.  Use `object.destroy()` (and `core.memory.GC.free()` if applicable) instead.
```

**Comment by rainers** [comment]
I was never convinced by the reason given for removal of `delete` as being unsafe, but the rationale given at 
https://dlang.org/deprecate.html#delete is even worse.
Correctly dealing with the reverse of `new` is not trivial. Considering that the latest correction to `__destroy` https://github.com/dlang/druntime/pull/3481 wasn't even in a release yet AFAICT, removal seems a bit early.

**Comment by ibuclaw** [comment]
Superseded by #13666.

**Pull request closed without merging**
