### PR TITLE
Revert "convert LINK and other enums to ubyte"

### PR DESCRIPTION
**Pull request by Geod24**
Reverts dlang/dmd#11851
It broke master, as can be seen in the comment of the PR.

### CODE REVIEW

**Review by ibuclaw — APPROVED** [review]

**Comment by WalterBright** [comment]
> Looks like something broke...

This is not helpful. What broke?

**Comment by Geod24** [comment]
> This is not helpful. What broke?

FreedBSD & Ubuntu bootstrap: https://github.com/dlang/dmd/runs/1237869712 & https://github.com/dlang/dmd/runs/1237869709

**Comment by WalterBright** [comment]
Why did it past the test suite?

**Comment by Geod24** [comment]
It did not. But `dlang-bot` does not see "checks" (it's a new, different API, Github side), hence it merges things it shouldn't
I made those required so it doesn't happen again.

**Comment by WalterBright** [comment]
ok

**Comment by WalterBright** [comment]
One super annoying thing about this is each enum is defined four times.

**Pull request merged**
