### PR TITLE
[stable] Cherry-pick #11500

### PR DESCRIPTION
**Pull request by kinke**
Fixing a serious 2.093 regression (https://issues.dlang.org/show_bug.cgi?id=21092 and my duplicate https://issues.dlang.org/show_bug.cgi?id=21123). This fix should make it into 2.093.1.

### CODE REVIEW

**Review by UplinkCoder — APPROVED** [review]
I agree this should make it

**Comment by Geod24** [comment]
> This fix should make it into 2.093.1.

Then it should target stable

**Comment by kinke** [comment]
Argh, branch fixed.

**Review by Geod24 — APPROVED** [review]
LGTM

**Comment by NilsLankila** [comment]
I suggest to amend + force push to retrigger buildkite.

**Comment by kinke** [comment]
Somebody pls reslap the auto-merge tag on it.

**Pull request merged**
