### PR TITLE
Fix Dub package when cross-compiling

### PR DESCRIPTION
**Pull request by jacob-carlborg**
There are two commits, I recommend reviewing them separately.

### CODE REVIEW

**Comment by WalterBright** [comment]
> There are two commits, I recommend reviewing them separately.

Please do them as 2 PRs, then.

**Comment by jacob-carlborg** [comment]
I don't see the problem of looking at the individual commits.

**Review by thewilsonator — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
> Say what?

Hmm, I didn't know that DAutoTest  was building the Dub package. But for Semaphore I instead get:

```
/bin/sh: 2: : Permission denied
Command failed with exit code 127: 
    "${DUB_EXE}" \
    --arch=${DUB_ARCH} \
    --single "${DUB_PACKAGE_DIR}config.d" \
    -- "${DUB_PACKAGE_DIR}generated/dub" \
    "${DUB_PACKAGE_DIR}VERSION" \
    /etc
```

**Comment by jacob-carlborg** [comment]
> Say what?

Turns out that the `$DUB_EXE` variable was added in the release shipped with DMD 2.084.0 [1] (and the changelog is wrong). DAutoTest is using Dub from DMD 2.083.0. Can we update that?

[1] https://dlang.org/changelog/2.084.0.html#dubEnvVar

**Comment by jacob-carlborg** [comment]
BTW, this blocks: https://github.com/dlang/dmd/pull/8528.

**Comment by thewilsonator** [comment]
> Can we update that?

cc @CyberShadow

**Comment by CyberShadow** [comment]
> Can we update that?

I think it's coming from here:
https://github.com/dlang/dlang.org/blob/master/posix.mak#L183

**Comment by jacob-carlborg** [comment]
@thewilsonator @CyberShadow https://github.com/dlang/dlang.org/pull/2557.

**Comment by CyberShadow** [comment]
Unless it is known for a fact that `DUB_EXE` will not match `$(which dub)`, I suggest using "$${DUB_EXE:-dub}" to allow this change to work with older versions of Dub.

**Comment by jacob-carlborg** [comment]
> Unless it is known for a fact that $DUB_EXE will not match $(which dub)

If `dub` is not in the `PATH` then `which dub` will not work. But `$DUB_EXE` will, it uses `thisExePath`.

**Comment by CyberShadow** [comment]
> If `dub` is not in the `PATH` then `which dub` will not work.

That's fine. If that's your only concern, I recommend that you apply the change I suggested above.

**Comment by jacob-carlborg** [comment]
Any equivalent for Windows?

**Comment by CyberShadow** [comment]
Not in its variable substitution syntax, as far as I know, so only as a separate command. Not updating the Windows command only means that Windows users will have no choice but to update to 2.084, which doesn't seem like a problem.

**Comment by jacob-carlborg** [comment]
I got this error following your advice:

```
/bin/sh: line 2: 29755{DUB_EXE:-dub}: command not found
```

**Comment by CyberShadow** [comment]
And `$${DUB_EXE}` (with two `$$`) works? Is that some special Dub syntax? There should probably be only one `$`, with `:-dub` or without.

**Comment by jacob-carlborg** [comment]
> And $${DUB_EXE} (with two $$) works? Is that some special Dub syntax?

Yes, it's special Dub syntax. Some variables will be substituted before the command is run.

**Comment by CyberShadow** [comment]
I can't find the implementation for parsing that syntax in Dub's source code. It looks like it's just using `spawnShell`, and everything points to that those variables are expanded by the shell, not Dub. Are you sure there are supposed to be two `$`?

**Comment by jacob-carlborg** [comment]
> I can't find the implementation for parsing that syntax in Dub's source code. It looks like it's just using spawnShell, and everything points to that those variables are expanded by the shell, not Dub. 

It must be doing that before calling `spawnShell`.

> Are you sure there are supposed to be two $?

Yes, otherwise I get `Invalid variable: DUB_EXE`. See https://dub.pm/package-format-sdl.html#environment-variables: "To denote a literal dollar sign, use $$. The predefined variables are:".

**Comment by CyberShadow** [comment]
Oh. Looks like it's a Dub bug. Look at this function:

https://github.com/dlang/dub/blob/927c5e6c248f7e2098a303fd475decfd8d8cca0a/source/dub/project.d#L1197-L1211

Instead of looking for `$` (minding escapes), it uses a regular expression to match what it thinks shell variable use looks like. The code looks wrong and overcomplicated, I guess I'll work on a fix.

Never mind my suggestion I guess...

**Comment by CyberShadow** [comment]
> I guess I'll work on a fix.

Here it is: https://github.com/dlang/dub/pull/1641

**Comment by jacob-carlborg** [comment]
@thewilsonator @ZombineDev all tests are passing, finally 😃.

**Comment by thewilsonator** [comment]
Nice I take it it is goo to go?

**Comment by jacob-carlborg** [comment]
> Nice I take it it is goo to go?

Yes. I had to download Dub separately on Semaphore when using LDC 1.11.0. Because the version of Dub shipped with LDC 1.11.0 is too old and doesn't support the `DUB_EXE` environment variable. Using a later version of LDC cause some linker error.

**Comment by thewilsonator** [comment]
Can you report the linker error please?

**Comment by jacob-carlborg** [comment]
Sure.

**Comment by thewilsonator** [comment]
Thanks.

**Comment by jacob-carlborg** [comment]
Has already been reported: https://github.com/ldc-developers/ldc/issues/2954.

**Pull request merged**
