### PR TITLE
statement_toIR(): simplify conversion of label statements to goto

### PR DESCRIPTION
**Pull request by WalterBright**
by not needing another hash table

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
@TurkeyMan @CyberShadow 

The buildkite/dmd error:
```
../../crypto/vibe/crypto/cryptorand.d(173,6): Error: cannot modify `const` expression `p`
```
The code https://github.com/vibe-d/vibe.d/blob/master/crypto/vibe/crypto/cryptorand.d
```
auto p = atomicLoad(*cast(const shared GET_RANDOM*) &hasGetRandom);
if (p == GET_RANDOM.UNINITIALIZED)
{
	p = initHasGetRandom() ? GET_RANDOM.AVAILABLE   <= error on this line
					: GET_RANDOM.NOT_AVAILABLE;
```
Perhaps it has something to do with this? https://github.com/dlang/druntime/pull/2739

**Comment by WalterBright** [comment]
Looks like the buildkite/dmd error is unrelated to this PR.

**Comment by ibuclaw** [comment]
Same as #10322, I'd like a small pause for thought before going ahead.  As I've said in the other, this reverts #4854, and goes against the reasoning for using a hash table in the first place - to remove dmd backend-only fields from common frontend types.

If the reasoning for this is the same as in #10322, then perhaps it would be better to jump straight to something that uses the frontend for data analysis, rather than a halfway solution that has no effect for either gdc/ldc, other than slightly increasing memory usage.

**Comment by CyberShadow** [comment]
> Looks like the buildkite/dmd error is unrelated to this PR.

It was the breaking change in https://github.com/dlang/druntime/pull/2739. @thewilsonator force-merged it.

**Comment by WalterBright** [comment]
> then perhaps it would be better to jump straight to something that uses the frontend for data analysis

Because it took several tries for me to get this correct (making stupid mistakes). Getting it right here, where there is plenty of code to exercise all the cases, is a heluva lot easier than looking for subtle bugs in DFA, which is notoriously hard to debug.

> other than slightly increasing memory usage

It's actually less memory usage, because the hash table with the same number of values (and hence quadruple the storage because of the key, hash, and link) is no longer needed.

**Pull request merged**
