### PR TITLE
Refactor: add isSomeChar to reduce duplication of checking for the 3 char types

### PR DESCRIPTION
**Pull request by benjones**
replace ty == Tchar || ty == Twchar || ty == Tdchar with isSomeChar

### CODE REVIEW

**Comment by ibuclaw** [comment]
Hmm, someone has definitely done this before...

**Comment by ibuclaw** [comment]
See #9777 #9889 #9947.

**Comment by benjones** [comment]
Thanks for finding those, I was sure I had seen something like this before but didn't find them when I looked.  Glad I'm not crazy!

The 2nd 2 pull requests look like they were changing behaviors.  I think this PR is actually doing what Walter's review suggested for your PR: checking the 3 conditions instead of adding a virtual function

**Review by PetarKirov — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]
LGTM. I also had a deja-vu but couldn't find @ibuclaw 's PR.

**Comment by ibuclaw** [comment]
@benjones, right, however ischar should be removed and replaced by isSomeChar, and there's another redundant function in the second PR that can be removed too.

**Pull request merged**
