### PR TITLE
CircleCI: Fix it by using aptitude instead of apt-get

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
Let's see if this works...

### CODE REVIEW

**Comment by MartinNowak** [comment]
Think the problem is apt-get, see [apt - unable to install gcc-multilib after upgrading to 14.04 - Ask Ubuntu](http://askubuntu.com/questions/573863/unable-to-install-gcc-multilib-after-upgrading-to-14-04).

**Comment by mathias-lang-sociomantic** [comment]
@MartinNowak : Thanks for the hint ! Updated, seems to work.

**Comment by WalterBright** [comment]
Hmm, I just pulled a PR from @MartinNowak to fix Circleci. I suppose we should wait and see how that works out?

**Comment by mathias-lang-sociomantic** [comment]
Martin's fix was sadly incomplete, but so is mine. I'll make sure to ping someone if I find a solution :)

**Comment by MartinNowak** [comment]
Think we should simply disable the 32-bit coverage tests until we can resolve the problem.

**Comment by MartinNowak** [comment]
> Think we should simply disable the 32-bit coverage tests until we can resolve the problem.

Did that for now.

**Comment by Geod24** [comment]
> Did that for now.

Yeah, I couldn't find anything that would solve it. Thanks !

**Pull request closed without merging**
