### PR TITLE
add toString to Array, eliminate calls to strlen, add unittest

### PR DESCRIPTION
**Pull request by benjones**
This didn't seem to actually get called running the test suite locally...
The only potential call sites I saw were the overload of toChars in Tuple (2 places)

I added a unittest to cover it.

The calls to the toString of the elements probably leak memory sometimes, but other times probably point to data needed by those objects.  Any thoughts on what could be done to reduce leakage?

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by benjones** [comment]
style failure is due toString being non-const, but since RootObject's is non-const, I don't think there's anything I can do here.

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
> style failure is due toString being non-const, but since RootObject's is non-const, I don't think there's anything I can do here.

If RootObject is non-const, how did it pass up until now?

**Comment by benjones** [comment]
We were calling tochars?

**Comment by thewilsonator** [comment]
As in why was it not triggering on https://github.com/dlang/dmd/blob/master/src/dmd/root/rootobject.d#L61

**Comment by benjones** [comment]
The end of src/.dscanner.ini seems to disable the check for RootObject

**Comment by benjones** [comment]
Most toChars methods can be const-ified easily, but I hit a roadblock at dmd.hdrgen.toCBuffer which is used in a few toChars implementations.  It makes use of visit/accept, so it would require a big rework to make them const, I think.  If I remember right, a few classes cache their string reps, so those would also need to be reworked.

**Comment by jacob-carlborg** [comment]
> As in why was it not triggering on https://github.com/dlang/dmd/blob/master/src/dmd/root/rootobject.d#L61

Yeah.

**Comment by benjones** [comment]
Any thoughts on what I should do about this?

**Comment by thewilsonator** [comment]
add root array to the [filter](https://github.com/dlang/dmd/blob/master/src/.dscanner.ini#L118)

**Comment by thewilsonator** [comment]
Thanks.

**Pull request merged**
