### PR TITLE
VS: choose the default compiler automatically

### PR DESCRIPTION
**Pull request by rainers**
so you don't have to switch it manually from within Visual Studio

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Comment by wilzbach** [comment]
Now if there was an easy way to avoid manually specifying all D files in this solution, you would make my day :)
Is there no support for globbing or folders?

**Comment by rainers** [comment]
> Is there no support for globbing or folders?

MSBuild can do that for VC projects, but not Visual D projects. So it might work if we switch to the D integration with MSBuild.
I never tried that because there have been too many d files in the source directory that should not be part of the build (e.g. idgen or impconvtab). These seem to have been replaced, though.

**Comment by wilzbach** [comment]
> I never tried that because there have been too many d files in the source directory that should not be part of the build (e.g. idgen or impconvtab). These seem to have been replaced, though.

Yep, these files have been replaced with CTFE as part of the work for the DMD as a DUB package.
We also applied a couple of `version(XX) {} else` on top of files, s.t. all we need for DUB is:

https://github.com/dlang/dmd/blob/b1f6aec796286a08395d689b54dacdd01d141f9e/dub.sdl#L62-L64

(the three packages above aren't in any anymore)

It would be really cool to be able to do the same for for Visual Studio ;-)

**Comment by jacob-carlborg** [comment]
Since the Visual Studio project seems to be just an XML file, can't generate it from some other source? We can do something very simple to begin with. Have a template file that contains everything needed for the Visual Studio project except for the source code files. Then have a tool that inserts the source code files into the XML file.

**Comment by wilzbach** [comment]
IIRC that wasn't possible because people would need to run this before opening the project in Visual Studio?

**Comment by jacob-carlborg** [comment]
You could still commit the generated file and then as a test run the tool again and compare the committed file against the new generated file. That way the test would fail if the files are out of sync.

**Comment by jacob-carlborg** [comment]
Seems like Rainer already has a different solution https://github.com/dlang/dmd/pull/7706 by compiling all D files.

**Pull request merged**
