### PR TITLE
optimize memory layout of aggregates

### PR DESCRIPTION
**Pull request by ghost**
On x86_64, StructDeclaration stood on 569 bytes, now 560, which saves allocation of a small block, simply by reordering fields.
Note that this time the gain is always negligible as you dont have thousands of different struct in a project.
My methodology to test (/usr/bin/time -v) doesnt even show anything tangible.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Headers.

**Comment by NilsLankila** [comment]
Headers ok now

**Review by thewilsonator — APPROVED** [review]
Looks good aside the merge conflict

**Comment by NilsLankila** [comment]
conflicts solved

**Comment by ibuclaw** [comment]
This caused a regression.

**Comment by NilsLankila** [comment]
bad headers ?

**Comment by NilsLankila** [comment]
can be caused by the rebase too ?

**Comment by ibuclaw** [comment]
Yes, bad headers.  It could have been avoided if tests can be added whenever public fields get moved around.

https://github.com/dlang/dmd/pull/11394

**Comment by ibuclaw** [comment]
> can be caused by the rebase too ?

Can't say.  But they are clearly in the wrong order when comparing C++ and D definitions.

**Comment by NilsLankila** [comment]
yeah anyway sorry, thanks for the fixup.

**Pull request merged**
