### PR TITLE
DIP25: foreach ref variables

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Can you explain a bit what you're trying to implement? And which DIP or bugzilla issue is this related to?

**Comment by AndrejMitrovic** [comment]
Sorry, didn't see the title! I'll check it out.

**Comment by AndrejMitrovic** [comment]
Just trying to figure out what this changeset enables, since this code used to compile before..

**Comment by WalterBright** [comment]
Also, see the test case I added. This was failing before.

**Comment by AndrejMitrovic** [comment]
> Also, see the test case I added. This was failing before.

No it wasn't: http://dpaste.dzfl.pl/be50238fdf37

**Comment by WalterBright** [comment]
You have to add the `-dip25` flag.

**Comment by andrej-mitrovic-sociomantic** [comment]
Damn, I'm out of the loop on this one. Shouldn't you add this flag at the top of the test file though to properly check?

**Comment by AndrejMitrovic** [comment]
Damn, I'm out of the loop on this one. Shouldn't you add this flag at the top of the test file though to properly check?

**Comment by WalterBright** [comment]
> Shouldn't you add this flag at the top of the test file though to properly check?

It's line 1 of the test file.

**Comment by AndrejMitrovic** [comment]
Ah, okay so it's a fairly recent file as well (`testscope2` wasn't obvious to me). Anyway, done complaining, carry on! :)

**Comment by andralex** [comment]
easy fix eh :)

**Pull request merged**
