### PR TITLE
split OPpair into two separate loads

### PR DESCRIPTION
**Pull request by WalterBright**
Making it two separate operations instead of one works better with the code gen designed for register operands.

### CODE REVIEW

**Comment by WalterBright** [comment]
For an idea of the effect of this, consider the program:
```
void foo() {
    __gshared uint[2]  a1 = [0x1001_1100, 0x0220_0012];
    uint[] a = a1;
    foreach (e; a)
        bar(e);
}
void bar(uint);
```
Before:
```
_D3foo3fooFZv:
                push    EAX
                mov     ECX,offset FLAT:_D3foo3fooFZ2a1G2k
                push    EAX
                mov     EAX,2
                push    EBX
                xor     EBX,EBX
                mov     4[ESP],EAX
                mov     8[ESP],ECX
                cmp     4[ESP],EBX
                je      L30
L1D:            mov     EDX,8[ESP]
                mov     EAX,[EBX*4][EDX]
                call    near ptr _D3foo3barFkZv
                inc     EBX
                cmp     EBX,4[ESP]
                jb      L1D
L30:            pop     EBX
                add     ESP,8
                ret
```
After:
```
_D3foo3fooFZv:
                push    EBX
                xor     EBX,EBX
L3:             mov     EAX,_D3foo3fooFZ2a1G2k[EBX*4]
                call    near ptr _D3foo3barFkZv
                inc     EBX
                cmp     EBX,2
                jb      L3
                pop     EBX
                ret
```

**Comment by CyberShadow** [comment]
This pull request caused a ~30% increase in compilation real time for the "Vibe.d diet templates" test on http://digger.k3.1azy.net/trend/

**Comment by MartinNowak** [comment]
Seems like this introduced a bug.
[Issue 15272 – [2.069-rc2,inline] nothing written to output when -inline is set](https://issues.dlang.org/show_bug.cgi?id=15272)

**Comment by MartinNowak** [comment]
> This pull request caused a ~30% increase in compilation real time for the "Vibe.d diet templates" test on http://digger.k3.1azy.net/trend/

Have you filed that as regression? Is it resolved by now?
Github comments have the tendency to get ignored.

**Comment by CyberShadow** [comment]
> Have you filed that as regression?

From http://forum.dlang.org/post/55F0868F.7070108@dawg.eu I understood that filing such regressions was not a desired course of action.

**Comment by WalterBright** [comment]
> This pull request caused a ~30% increase in compilation real time for the "Vibe.d diet templates" test on http://digger.k3.1azy.net/trend/

1. do you mean dmd time or compiled application time?
2. the link doesn't work

**Comment by CyberShadow** [comment]
> do you mean dmd time or compiled application time?

DMD time.

> the link doesn't work

Try another web browser, some web browsers choke on big JSON blobs with nonsensical errors for some reason.

**Comment by MartinNowak** [comment]
> From http://forum.dlang.org/post/55F0868F.7070108@dawg.eu I understood that filing such regressions was not a desired course of action.

Well 30% slowdown is a huge change, not just a small sideeffect.

**Comment by CyberShadow** [comment]
> Well 30% slowdown is a huge change, not just a small sideeffect.

An even bigger one happened here:
https://github.com/D-Programming-Language/dmd/pull/4924#issuecomment-133939443

**Pull request merged**
