### PR TITLE
Add a Buildkite badge

### PR DESCRIPTION
**Pull request by wilzbach**
https://buildkite.com/dlang/dmd

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by wilzbach** [comment]
While I was at it, I used this opportunity to do more changes:
- use flat style
- use more shield.io badges whenever available
- use logos
- show the name of the CI providers
- add Buildkite
- use the master branch only for AppVeyor
- reorder CIs as the SemaphoreCI badge is bulky

image

As we're free to select the labels, we could also use better names like e.g. "Windows" instead of AppVeyor, "project tester" instead of Buildkite (though I don't  have a good name for CircleCI as it does a few separate things: runs dmd with -cov for CodeCov, checks that no temporary files have been created, runs a small sanity test for `test/run.d`, checks whether building dmd with `build.d` works and last, but not least checks whether the executable work with PIC).

**Comment by wilzbach** [comment]
Oh and I also found that there's an alternative badge `github/tag-date` offered for the SemVer badge. As some of you might have noticed that the latest tag badge doesn't get updated in the README here. This is not due to caching, but to DMD not using SemVer. So we could use the latest tag by date, but then betas would show up too.

Opinions?

**Comment by thewilsonator** [comment]
The _correct_ thing to de here it to actually use SemVer, I've added that to my list-of-things-to-do-at-dconf. In  the mean time

> we could use the latest tag by date, but then betas would show up too.

I think that is a good idea.

**Comment by wilzbach** [comment]
> The correct thing to de here it to actually use SemVer, I've added that to my list-of-things-to-do-at-dconf. In the mean time

It's a long discussion, see e.g.

https://forum.dlang.org/thread/drcekmxvfszpwifbukzk@forum.dlang.org

But in short all key people have more important/pressing things to do and it would require a lot of changes to the infrastructure with minimal benefit.

> I think that is a good idea.

Done.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Auto-merge toggled on

**Pull request merged**
