### PR TITLE
Fix Issue 23258 - ICE on SumType of two arrays of classes

### PR DESCRIPTION
**Pull request by BorisCarvajal**

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Could you please target stable?

**Comment by BorisCarvajal** [comment]
Already targeting there.

**Comment by RazvanN7** [comment]
Ah, sorry, I must be blind.

**Comment by ibuclaw** [comment]
> Could you please target stable?

NO!

**Comment by PetarKirov** [comment]
@ibuclaw why no?

**Pull request merged**
