### PR TITLE
Ddoc enhancements

### PR DESCRIPTION
**Pull request by jacob-carlborg**
This PR is split into two separate commits, where the later ones depend on the former ones. The commit messages describe pretty well what they do and the intention. I've copied them here for convince:
- Ddoc: wrap each symbol in the `DDOC_MEMBER` macro
  
  This allows better control of formatting of the output. For example,
  it allows to output an unordered list instead of a description list.
  
  By default it expands the first argument (`$0`) as is, basically making
  the macro disappear, to keep backwards compatibility.
- Ddoc: add new macros: `DDOC_MEMBER_HEADER` and `DDOC_HEADER_ANCHOR`
  
  The second parameter (`$1`) of the `DDOC_HEADER_ANCHOR` macro expands to
  the fully qualified name of the current symbol without the package and
  module prefix. That is, for a module level symbol it's the name of a
  symbol. For a nested symbol, like a method in a class, it's the symbol
  name prefixed with the class name. The third parameter (`$2`) expands to
  just the name of the current symbol.
  
  The `DDOC_MEMBER_HEADER` wraps `DDOC_HEADER_ANCHOR` to allow a sensible
  output format. The `DDOC_MEMBER_HEADER` is wrapped in the `DDOC_MEMBER`
  macro.
  
  By default these two macros expand to nothing, to keep backwards
  compatibility.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
@andralex ping

**Comment by andralex** [comment]
Nice work, thanks!

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by jacob-carlborg** [comment]
@andralex I need to update the documentation and do a minor tweak for the theme that is used in dlang.org. Where do I find that, and are there any other docs/themes that need to be updated?

**Comment by andralex** [comment]
I guess all of those should be in the https://github.com/dlang/dlang.org repo? The  pertinent ddoc files are *.ddoc. For the site, https://github.com/dlang/dlang.org/blob/master/posix.mak shows how they're used:

```
DDOC=$(addsuffix .ddoc, macros html dlang.org doc ${GENERATED}/${LATEST}) $(NODATETIME)
STD_DDOC=$(addsuffix .ddoc, macros html dlang.org ${GENERATED}/${LATEST} std std_navbar-release ${GENERATED}/modlist-${LATEST}) $(NODATETIME)
```

**Pull request merged**
