### PR TITLE
[RFC] Diff expected and actual output on test failure

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
This simplifies identifying changes between the provided `TEST_OUTPUT` and the actual compiler output.

Inspired by #10813

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
This included #10813 which was not merged yet (I should've put big warning in the description, sorry)

**Comment by wilzbach** [comment]
It's fine. This is great stuff!

**Comment by Geod24** [comment]
Late to the party, but this is an amazing improvement for contributors. I'm ashamed of the amount of time I've lost because I forgot a backtip around symbol name or some other stupid mistake.
Thanks!

**Comment by WalterBright** [comment]
@MoonlightSentinel Thank you so much for this sweet productivity booster!

**Pull request merged**
