### PR TITLE
Automatically convert PROTXXX into a D enum

### PR DESCRIPTION
**Pull request by wilzbach**
I wasn't sure if it should be named `PROTKIND` or just `PROT` -
there were some incosistencies.

```shell
replacements=(
"PROTundefined undefined"
"PROTnone none"
"PROTprivate private_"
"PROTpackage package_"
"PROTprotected protected_"
"PROTpublic public_"
"PROTexport export_"
)

for r in "${replacements[@]}" ; do
    w=($r)
    sed "s/${w[0]}/Protection.${w[1]}/g" -i **/*.d
done
sed "s/PROTKIND/Protection/g" -i **/*.d
```

### CODE REVIEW

**Comment by ibuclaw** [comment]
Could name it PROT I guess.

**Comment by jacob-carlborg** [comment]
Is `PROT` shortening of `Protection`? If that's the case I vote for `Protection`.

**Review by jacob-carlborg — CHANGES_REQUESTED** [review]
I suggest renaming `PROTKIND` to `Protection` or `PROT`.

**Comment by wilzbach** [comment]
> I suggest renaming PROTKIND to Protection or PROT.

Good idea! Done.

**Comment by JinShil** [comment]
I think we should be careful with the naming conventions.  There is also a `struct Prot` which adds some semantics to the protection enum.  I think we should try to find a consistent convention distinguishing the classes/structs that add semantics to the concept represented by the enums.  

FWICT there are other enums (e.g. `BUILTIN`, `SCOPE`, `PASS`, etc...) that are all caps.  The convention is not strictly followed, but given the presence of `struct Prot`, I recommend going with `PROT` for consistency.  I can imagine a desire to rename `struct Prot` to `struct Protection`, so I'm looking for a consistent convention to follow to distinguish the `struct` from the `enum`.

**Comment by jacob-carlborg** [comment]
> I can imagine a desire to rename struct Prot to struct Protection, so I'm looking for a consistent convention to follow to distinguish the struct from the enum.

Perhaps a nested enum:

```d
struct Protection
{
    enum Kind {}
}
```

**Comment by ibuclaw** [comment]
There's StructFlags and ClassFlags, but not sure if that convention is worth repeating.

**Comment by wilzbach** [comment]
> Perhaps a nested enum:

I made a new PR -> https://github.com/dlang/dmd/pull/7674

**Pull request closed without merging**
