### PR TITLE
Fix 24056 - const uninitialized data at module scope is not in TLS

### PR DESCRIPTION
**Pull request by dkorpel**

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
I thought it would make more sense to move const data to TLS. Only `immutable` is documented as shared by the spec as far as I know. @WalterBright what do you think about https://issues.dlang.org/show_bug.cgi?id=24056?

**Comment by dkorpel** [comment]
> I thought it would make more sense to move const data to TLS. 

That would break or subtly change the behavior of existing code.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Please add a changelog entry.

**Comment by dkorpel** [comment]
For a bug fix?

**Comment by RazvanN7** [comment]
For a deprecation.

**Pull request merged**
