### PR TITLE
Move usage fields from Param to DMDparam

### PR DESCRIPTION
**Pull request by ibuclaw**
These are driver-specific, rather than language tuning.

### CODE REVIEW

**Comment by kinke** [comment]
LDC uses three of these - transition, preview, revert - as it supports `-preview=?` etc. too and displays the same help.

**Comment by kinke** [comment]
Nope, I reuse the parser for these options, so that I don't have to adapt it whenever option values are added/removed.

**Comment by RazvanN7** [comment]
I thought that dmdparams refers only to backend specific parameters. The ones that are moved in this PR seem to be frontend related.

**Comment by ibuclaw** [comment]
> I thought that dmdparams refers only to backend specific parameters. The ones that are moved in this PR seem to be frontend related.

They are not required for semantic. They are only for the command line parser (driver) component, to which gdc handles this externally in C++ land (using gcc infrastructure to generate the C++ code to handle it, rather than doing it ourselves, naturally).

**Comment by ljmf00** [comment]
> I thought that dmdparams refers only to backend specific parameters. The ones that are moved in this PR seem to be frontend related.

There is a mix of Params and DMDParams used in backend. See `backend_init()`.

**Comment by RazvanN7** [comment]
@kinke do you suggest we leave transition, preview, revert in param?

**Comment by kinke** [comment]
Well, I agree with Iain that the usage bools shouldn't be part of Params. Moving to `DMDParams` might be a bit of a hassle for LDC, but oh well.

https://github.com/ldc-developers/ldc/blob/490bdcb0dd1c23f9552f116a3e9b68198fd36355/dmd/mars.d#L242
https://github.com/ldc-developers/ldc/blob/490bdcb0dd1c23f9552f116a3e9b68198fd36355/dmd/mars.d#L1630-L1724 (forgot that the `parseCLIOption` parser is duplicated by LDC, as the DMD one is a nested helper function in DMD's `parseCommandLine`…)

**Comment by thewilsonator** [comment]
these flags (and some more) are now in a `Help` struct in `globals.d`. If you still want this, please open a new PR.

**Pull request closed without merging**
