### PR TITLE
Fix issue 14964 - Introduce the isAlias trait

### PR DESCRIPTION
**Pull request by LemonBoy**
Quick'n'dirty implementation, possibly needs more testing to uncover some edge cases.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Not sure if this is warranted.

**Comment by BBasile** [comment]
- naming bikesheding:`isAliasedSymbol` is more appropriate if the traits doesn't verify, for example 
```d
static assert(__traits(isAlias, size_t));
```

- test `foo` in
```d
struct Foo
{
    int a;
    alias b = a;
    alias b this;
}
Foo foo;
```
because currently I have no idea if it'll be considered as an aliased symbol.

**Comment by BBasile** [comment]
Another one to test
```d
template a(alias b)
{
    alias a = b;
}
static int c;
alias d = a!c; // test d
```

**Comment by BBasile** [comment]
Should this case be verified ?

```d
struct Foo
{
    int a;
    alias b = a;
    alias b this;
}
Foo foo;
static assert(__traits(isAlias, foo));
```

For now the assert fails.

**Comment by mathias-lang-sociomantic** [comment]
I don't think it's a good idea. I noted my concerns on the issue.

**Comment by WalterBright** [comment]
The PR is good, but I also have serious concerns about the semantics of this. I suggested for discussion purposes an alternative in https://issues.dlang.org/show_bug.cgi?id=14964

**Pull request closed without merging**
