### PR TITLE
Revert "Initial attempt at stdatomic.h"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/dmd#15816

Module wasn't tested, and dozens and dozens of issues with it that fall into three main camps (based on what I can tell looking at ci logs from phone)

1. `const shared` on the `dest` parameter of `atomic_exchange(_explicit)_impl`
2. Invalid memory models used in many functions (i.e `acq_rel` used in `atomic_store`)
3. Failure memory models stronger than success memory models in all `atomic_compare_exchange` functions.

### CODE REVIEW

**Comment by dkorpel** [comment]
@rikkimax

**Comment by rikkimax** [comment]
I called the PR as initial attempt for a reason.

It needs polishing on a per compiler basis. As far as my work is concerned
I've done my part getting a shell together for a solution.

**Comment by thewilsonator** [comment]
1. is fixed by https://github.com/dlang/dmd/pull/15962

**Comment by thewilsonator** [comment]
2 is fixed by [#15963](https://github.com/dlang/dmd/pull/15963)

Closing per https://github.com/dlang/dmd/pull/15963#issuecomment-1872578760

**Comment by ibuclaw** [comment]
> 2 is fixed by [#15963](https://github.com/dlang/dmd/pull/15963)
> 

No it isn't. That uses more sane alternatives (plus the comment about what gcc does is way off).

**Pull request closed without merging**
