### PR TITLE
fix Issue 22761 - [REG 2.099] importC: Error: redeclaration with diff…

### PR DESCRIPTION
**Pull request by WalterBright**
…erent type

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by ibuclaw — DISMISSED** [review]
There's also a wrong logic in the cparse module, I think you should use it in this fix too.

https://github.com/dlang/dmd/blob/afa04b47eee6fb93e8d265b41edbf9381de78c15/src/dmd/cparse.d#L1849

hasIdentifierList should be set before copying `pl`, so that the original node has it set too.

Rationale, so that you can distinguish between variadic and k&r in this cFuncEquivalence helper.

**Comment by WalterBright** [comment]
@ibuclaw I don't understand why, as the identifiers are irrelevant to determining function type equivalence.

**Comment by WalterBright** [comment]
Also, *all* K+R functions are variadic. Prototyped ones without ... are not variadic, but C11 still regards them as equivalent. I believe the equivalence function is correct.

**Comment by WalterBright** [comment]
Oh, I see what you're talking about. Never mind!

**Comment by ibuclaw** [comment]
The point is, you set it to true in the wrong place, also...
```
long square(int a);  // A

long square(a)  // B
  int a;
{
    return a * a;
}

long square(int a, ...)  // C
{
    return a * a;
}
```
I've not checked, but I'm pretty sure we only want A+B to match, not A+C.

**Pull request merged**
