### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Can this include https://github.com/dlang/dmd/pull/9708 please.

**Comment by RazvanN7** [comment]
Since this includes #9696 , I highly recommend it also includes #9725 as the PRs are related.

**Comment by thewilsonator** [comment]
One more that would be good to have https://github.com/dlang/dmd/pull/9723

**Comment by wilzbach** [comment]
This is merging things back from stable to master. You can do so yourself by running the merge_stable script.

**Pull request merged**
