### PR TITLE
fix Issue 17812 - crash when building JSON info with static foreach

### PR DESCRIPTION
**Pull request by tgehr**
This adds the string representation "__local" for STClocal.

### CODE REVIEW

**Comment by rainers** [comment]
Isn't `__local` something that should be invisible to the user?

Anyway, the reference JSON file needs to be updated with the new declarations.

**Comment by tgehr** [comment]
@rainers: I don't exactly know the purpose of the json/vcg-ast output. (I was not really aware of -X and -vcg-ast, that's why I hadn't tested them.) I have removed __local declarations from the output of both in the respective pull requests.

**Comment by tgehr** [comment]
Any ideas why the auto-tester fails `cpp_abi_tests.d`? (I have not even come close to code dealing with the C++ ABI.)

**Comment by rainers** [comment]
> Any ideas why the auto-tester fails cpp_abi_tests.d?

It looks like it is still failing on the json output. The shell script for comparing with json.out filters out the file names.

**Comment by tgehr** [comment]
@rainers Thanks! The auto-tester is green now.

**Pull request merged**
