### PR TITLE
Issue 14010 - Support mangleof property for opaque enum and struct type

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14010

Based on: #4313

### CODE REVIEW

**Comment by yebblies** [comment]
Structs?  `.stringof`?  Any others?

**Comment by 9rnsr** [comment]
I added code to support struct mangleof.

And, the class `mangleof` was already fixed in [issue 12543](https://issues.dlang.org/show_bug.cgi?id=12543], so I moved test cases in `compilable/fwdref12543.d`.

For other properties:
- `init` and `stringof` may be overridden currently. So we cannot avoid forward reference error.
- For enum and struct, `sizeof` and `alignof` needs the type size - it's different from class case. Then forward reference error is not avoidable.

**Comment by yebblies** [comment]
> `init` and `stringof` may be overridden currently. So we cannot avoid forward reference error.

Urrgh forgot about overriding stringof.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
