### PR TITLE
Fix issue 21255: Mangle aliased overload set passed to template alias parameter.

### PR DESCRIPTION
**Pull request by FeepingCreature**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by UplinkCoder** [comment]
Please add in the commit message what the change actually does

**Review by UplinkCoder — CHANGES_REQUESTED** [review]
Needs a better/longer commit message.

Try to explain the problem you are fixing to someone who only has a passing familiarity with DMD.

**Comment by FeepingCreature** [comment]
Commit changed to work differently.

The problem is that overload declarations are kind of "fake declarations" without many of the properties DMD expects from ordinary declarations. So when we try to mangle them we run into a cryptic "forward declaration" error arising from DMD thinking they're "default" linkage, because that's `LINK.init`, and then it errors with "forward declaration" for no reason I can discern. Anyways, there's already code for mangling an overload set; we just have to avoid crashing until we reach it.

**Comment by UplinkCoder** [comment]
@FeepingCreature yes please put that into the commit message.

**Comment by FeepingCreature** [comment]
(moved explanation to commit message)

**Review by UplinkCoder — APPROVED** [review]
I hope we won't regret this :)

**Comment by FeepingCreature** [comment]
Shouldn't. Afaict, this only triggers if dmd would crash anyways. `OverDeclaration`s are never mangleable, because they never have valid LINKage.

**Comment by UplinkCoder** [comment]
@FeepingCreature I hear you. Yeah it's not that big of a deal as long as changes in the future don't break that unstated invariant.

**Pull request merged**
