### PR TITLE
[RFC] Allow filtering compilation output using a regex

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
This adds `remove_lines_regex` as an option for `TRANSFORM_OUTPUT` to remove lines matching a given regex. This is an opt-in alternative to `remove_lines` because compilation output usually contains a lot of reserved character and hence would require escapes.

Refer to the last commit for an example.

### CODE REVIEW

**Comment by wilzbach** [comment]
Thinking about it, it probably is easier for the user to only have `remove_lines` which is the regex filtering as a regex is a strict super set of word matching. If performance ever becomes a problem the implementation could detect that no regex is required, but basically std.regex does such a detection too.

**Comment by MoonlightSentinel** [comment]
That seems reasonable. My initial concern was that it could bloat `remove_lines` with unecessary escapes but thats probably a hypothetical scenario. I'll merge them for now (and only add a workaround _if_ it  ever becomes a problem)

**Comment by MoonlightSentinel** [comment]
Any idea why Azure fails with an extra newline?
(It does not appear on the autotester or my local windows box)

**Comment by rainers** [comment]
> Any idea why Azure fails with an extra newline?
> (It does not appear on the autotester or my local windows box)

That is likely to be caused by different handling of \r (may related to git auto-crlf ?)

**Comment by MoonlightSentinel** [comment]
> That is likely to be caused by different handling of \r (may be related to git auto-crlf ?)

Thanks, I'll look into that as Azure somehow gets an additional newline between the `version` and `config` section of the debug output.

**Comment by MoonlightSentinel** [comment]
Extended the regex to strip empty lines as a workaround for Azure.

**Comment by MoonlightSentinel** [comment]
This should be good to go once #10842 is in.

**Comment by MoonlightSentinel** [comment]
Can we move forward with this?

**Comment by MoonlightSentinel** [comment]
@Geod24 With #10838 being merged `fail_compilation/fail15616b.d` now issues the following error message:
```
fail_compilation/fail15616b.d(44):        All possible candidates are marked as `deprecated` or `@disable`
```

This does not seem right because all function are neither `deprecated` or `@disable`d.

**Comment by MoonlightSentinel** [comment]
Updatet the expected output to unblock this PR.

**Pull request merged**
