### PR TITLE
iasmdmd.d: move public above fold

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by JinShil — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Can any of the `version(none)` stuff be removed entirely?

**Comment by WalterBright** [comment]
I'd rather not. It's used by DMC++.

**Comment by WalterBright** [comment]
and it may have bearing on "dmd as a library"

**Comment by thewilsonator** [comment]
OK.

**Comment by jacob-carlborg** [comment]
> I'd rather not. It's used by DMC++

Can we have a version identifier like `DMC` to make this more explicit? It's difficult for the rest of us to know if a version identifier like `none` or comments are used by DMC.

**Pull request merged**
