### PR TITLE
Add fancy badges to README

### PR DESCRIPTION
**Pull request by wilzbach**
Imho people love such badges/shields, it the unofficial standard after which you judge a project.

Btw in case someone didn't know [shields.io](http://shields.io/) also offers nice dub badges (current version, license, downloads, ...)

### CODE REVIEW

**Comment by wilzbach** [comment]
In case someone is too lazy to click on the preview:

image

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
@WalterBright wow that was a lot faster than 19 hours ;-) Thanks!
I also added the same set for Druntime and Phobos, in case you have the time to toggle:

https://github.com/dlang/druntime/pull/1631
https://github.com/dlang/phobos/pull/4728

(the failures there are related to our pending CI migration)

**Comment by BBasile** [comment]
issuestats badge is most of the time broken.

**Pull request merged**
