### PR TITLE
Reduce the public API of the lexer

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
```
../generated/linux/release/64/dscanner-b51ee472fe29c05cc33359ab8de52297899131fe/dsc --config .dscanner.ini --styleCheck dmd -I.
--
  | dmd/lexer.d(1361:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(1526:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(1582:23)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(1670:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(1829:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(1871:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(1939:23)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(2008:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(2034:23)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(2322:23)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(2556:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(2664:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
  | dmd/lexer.d(2695:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
```

**Comment by jacob-carlborg** [comment]
Right. Will fix.

**Comment by jacob-carlborg** [comment]
Remove `final` attributes from the private methods.

**Comment by CyberShadow** [comment]
I hate that warning. In D visibility is module-scope, but inheritance is a class issue, as such the two should be orthogonal. IMO there's nothing wrong with being explicit about virtual-ness of a function regardless of the access attribute.

**Pull request merged**
