### PR TITLE
Allow dmd to build on aarch64

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by thewilsonator** [comment]
see also https://github.com/dlang/dmd/pull/12764

**Comment by RazvanN7** [comment]
@UplinkCoder This is currently failing the testsuite.

**Comment by fkorotkov** [comment]
FYI we at Cirrus CI just launched native [Arm64 containers powered by Graviton2 processors](https://cirrus-ci.org/guide/linux/). If interested you can add CI check as well. Don't hesitate to check out with our support if you'll have any issues/questions.

**Comment by UplinkCoder** [comment]
I think this has been addressed in some other PR.

**Pull request closed without merging**
