### PR TITLE
Fix issue 23949 - core.stdc.assert_ for FreeBSD is incorrect

### PR DESCRIPTION
**Pull request by ghost**
See: https://github.com/freebsd/freebsd-src/blob/main/include/assert.h

Also add missing noreturn from previous PR

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by ErnyTech** [comment]
Should it be ported back to stable? this could create unexpected behavior

**Comment by ErnyTech** [comment]
Also Dragonflybsd is broken the same way (https://github.com/DragonFlyBSD/DragonFlyBSD/blob/master/include/assert.h#L85), don't merge until I fix this too

**Comment by ErnyTech** [comment]
This is ready now, waiting for tests

**Comment by RazvanN7** [comment]
@ErnyTech there is no need for the other PR. Just rebase this PR to stable.

**Comment by RazvanN7** [comment]
At some point, the 2 branches will be merged. However, if you want this in the next release, just target stable.

**Comment by ErnyTech** [comment]
Rebased to stable

**Review by RazvanN7 — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
