### PR TITLE
Fix issue 22911: dtoh: make include directives sorted for generated headers

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

This is a step to include a `clang-format` config to check the style conformance of C++ headers.

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by ibuclaw** [comment]
> This is a step to include a clang-format config to check the style conformance of C++ headers.

That seems like a bizarre requirement to me.

**Comment by ljmf00** [comment]
> > This is a step to include a clang-format config to check the style conformance of C++ headers.
> 
> That seems like a bizarre requirement to me.

I think this is a sensible thing to do, although very nitpicking. On a huge number of includes, if they are unsorted, my brain and probably other people's brains struggle a bit finding what is being imported easily. LLVM project and many other big projects I have contributed to also have that enforced by `clang-format` or some sort. Even though this is not D, D style also has that stated:

> Imports should be sorted lexicographically.

We should go forward with a coding style. A clean looking codebase make it more pleasant to contribute/read. I know this is debatable for a generated file, although I don't think it hurts fixing those inconsistencies.

**Comment by ljmf00** [comment]
> Thanks for your pull request, **@ljmf00**!
> 
> ### Bugzilla references
> Auto-close	Bugzilla	Severity	Description
> ✓	[22911](https://issues.dlang.org/show_bug.cgi?id=22911)	enhancement	dtoh: make include directives sorted for generated headers
> ### Testing this PR locally
> If you don't have a [local development environment setup](https://wiki.dlang.org/Starting_as_a_Contributor), you can use [Digger](https://github.com/CyberShadow/Digger) to test this PR:
> 
> ```shell
> dub run digger -- build "master + dmd#13867"
> ```

I created an issue for this, but probably not necessary. I'm going to do other style changes on dtoh generator.

**Comment by RazvanN7** [comment]
@ljmf00 This seems to be failing the testsuite. Maybe a rebase will fix it.

**Comment by ljmf00** [comment]
> @ljmf00 This seems to be failing the testsuite. Maybe a rebase will fix it.

Rebased.

**Comment by ljmf00** [comment]
> @ljmf00 This seems to be failing the testsuite. Maybe a rebase will fix it.

Need to fix the testsuite.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
