### PR TITLE
Enable Dwarf EH for FreeBSD

### PR DESCRIPTION
**Pull request by WalterBright**
Let's see where we are with this.

### CODE REVIEW

**Comment by WalterBright** [comment]
And it "just works"!

**Comment by andralex** [comment]
cool beans

**Comment by ibuclaw** [comment]
@WalterBright it should work on all x86 targets where you use gcc. ;-)

**Comment by WalterBright** [comment]
I doubt it will work on OSX, because the MACH-O object format does fixups and PIC code differently.

**Comment by ibuclaw** [comment]
I thought you switched to Clang on osx?  I was thinking about the other BSDs and Solaris actually.

**Pull request merged**
