### PR TITLE
fix Issue 16703 - Support indexing of SIMD vector types

### PR DESCRIPTION
**Pull request by WalterBright**
The implementation just looks for indexing of a Tvector and converts it to a Tsarray.

### CODE REVIEW

**Comment by yebblies** [comment]
I thought this limitation was by design, to discourage inefficient access - what changed?

**Comment by WalterBright** [comment]
I discussed this with Manu @TurkeyMan , who originally had discouraged this feature. To summarize his opinion, the slowness is a disaster on PPC or MIPS, which are now obsolete. It's not a big deal on x86 or ARM which are in ascendancy. Furthermore, gcc/clang allow it, which cause us problems when porting code.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by TurkeyMan** [comment]
:+1:

Let's pour one out for our old friends PPC and MIPS! :beer:

**Comment by TurkeyMan** [comment]
Out of curiosity, why was it that people were upset to type `v4.array[2]` instead of `v4[2]`?
I did like the explicitness of that former statement which is how it was achieved until now.

**Comment by WalterBright** [comment]
I was just annoying.

**Comment by TurkeyMan** [comment]
I can't think of any other annoying things in D :P

**Comment by WalterBright** [comment]
Neither can I. I think we've got it nailed now!

**Comment by ibuclaw** [comment]
> I can't think of any other annoying things in D :P
Ever find yourself wanting to do this?
```
v3 = v1 < v2;
```
Though I think we could make vector conditions a template along with vector permutations. ;-)

**Comment by WalterBright** [comment]
BTW, bearophile complained about `.array` being bad for generic code, and I think you (Manu) dissed in it in bugzilla somewhere :-)

**Comment by WalterBright** [comment]
Current list of SIMD issues:

https://issues.dlang.org/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&keywords=SIMD&keywords_type=allwords&list_id=211892&query_format=advanced

**Comment by TurkeyMan** [comment]
>Neither can I. I think we've got it nailed now!

**cough**
```
void f(ref const(T) t) {}
T stupid_name_for_temporary = someFunction();
f(stupid_name_for_temporary);
```

> BTW, bearophile complained about .array being bad for generic code, and I think you (Manu) dissed in it in bugzilla somewhere :-)

It's true, `.array` could theoretically be bad for generic code (assuming that a SIMD vector *is* an array, which it's kinda not), but without is bad for portability and performance... I guess we now know who wins this trade-off!


>Ever find yourself wanting to do this?
>```
>v3 = v1 < v2;
>```

Yes! It's even efficient on all arch's I'm familiar with!
It's a weird operator though; looks like a comparison (assume bool reasult?), but the result is actually an unsigned int vec of 0's or -1's...

**Comment by WalterBright** [comment]
> Ever find yourself wanting to do this?

File an Enhancement Request!

**Comment by TurkeyMan** [comment]
Yeah... while I personally like the idea, I don't really actually think it's a good idea ;)
The semantic is too weird.

**Comment by ibuclaw** [comment]
Well, vector condition and vector permutation can certainly be exposed as intrinsics nonetheless.  With or without a special operator support.

**Comment by ibuclaw** [comment]
> Let's pour one out for our old friends PPC and MIPS! :beer:

Speaking of which, I still have that Apple G5 and SGI box in bubble wrap... Should try to revive them someday for proper PPC and MIPS testing. ;-)

**Comment by TurkeyMan** [comment]
> Speaking of which, I still have that Apple G5 and SGI box in bubble wrap... Should try to revive them someday for proper PPC and MIPS testing. ;-)

@jpf91 did some GDC builds for various console toolchains which I tinkered with, they produced good code, but phobos/druntime needed a lot of work. I think for those systems, better-c is more likely what the user wants anyway.
OT: I have often wondered if you guys could add those console toolchains to the GDC build scripts so they're always available?

**Comment by jpf91** [comment]
> @jpf91 did some GDC builds for various console toolchains which I tinkered with, they produced good code, but phobos/druntime needed a lot of work. I think for those systems, better-c is more likely what the user wants anyway.

There are still quite some standard linux MIPS systems (most home routers / access points) so for these a full druntime/phobos build is useful. IIRC LDC already supports linux/MIPS so it shouldn't be too difficult. The main problem when supporting multiple architectures in GDC is that we really should get CI working for these systems, but with GCCs build times this is more complicated than it should be. I've got some long-term plans though to simply setup a home server with enough storage space and then cache the complete GCC build tree between builds ;-)

> I have often wondered if you guys could add those console toolchains to the GDC build scripts so they're always available?

The build scripts are always WIP. I've just rewritten the complete build scripts for standard linux toolchains. At some point I want to integrate the build system with a gitlab CI server + a custom vibe.D based UI. Then we'll have nightlies for all toolchains, the binary releases will be fully tested and the complete build/release process is mostly automated. Long-term plans ;-)

I could build another devkitPro/PPC release though, the old build scripts should still work

**Pull request merged**
