### PR TITLE
test for function should be by default @system even with -dip1000

### PR DESCRIPTION
**Pull request by WalterBright**
Added test case for https://issues.dlang.org/show_bug.cgi?id=19873 to confirm its behavior.

### CODE REVIEW

**Comment by Geod24** [comment]
Commented on the issue. Having different behavior for unattributed functions and `@system` functions is plain confusing and definitely a bug...

**Comment by 12345swordy** [comment]
All green here.

**Comment by MoonlightSentinel** [comment]
Not much use in adding a test case which proves that the bug is not fixed.

**Comment by RazvanN7** [comment]
I'm going to close this as a patch has been proposed for this issue: https://github.com/dlang/dmd/pull/12821

**Pull request closed without merging**
