### PR TITLE
[WIP] Translate _d_array{,set}ctor to templates

### PR DESCRIPTION
**Pull request by Vild**
druntime PR: https://github.com/dlang/druntime/pull/2655

### CODE REVIEW

**Comment by JinShil** [comment]
@Vild Does this just need a rebase?

**Comment by Vild** [comment]
> @Vild Does this just need a rebase?

I found some bugs when compiling with `-O`, so I'm currently looking into them.

**Comment by UplinkCoder** [comment]
Why did this need changes to ctfe?

**Comment by RazvanN7** [comment]
Superseded by: https://github.com/dlang/dmd/pull/13116

**Pull request closed without merging**
