### PR TITLE
Try to fix `runnable/testprofile.d` CI regression on Windows

### PR DESCRIPTION
**Pull request by kinke**
I *think* that test started to rather consistently fail on Windows with https://github.com/dlang/dmd/pull/16120. Looking at it, I noticed a functional change, so trying to revert that.

### CODE REVIEW

**Comment by kinke** [comment]
Nope, it looks like it started later with https://github.com/dlang/dmd/pull/16122: https://dev.azure.com/dlanguage/dmd/_build/results?buildId=41131&view=logs&jobId=6775e4b2-0d76-5db7-9bcd-015c7821c824&j=8af2f344-529d-5953-c6e9-e9e8d82c041d&t=007a24f2-5f9f-5584-8be8-7de5c1d9b6f5 is the oldest failing job on branch master I could find so far

**Comment by kinke** [comment]
Okay, now only reverting #16122, and CI passed. Might have gotten lucky, but I don't think so. ;)

**Comment by RazvanN7** [comment]
cc @dkorpel

**Comment by dkorpel** [comment]
How do I proceed here? The PR was green when it was merged, and the error is:

core.exception.OutOfMemoryError@src\core\internal\gc\impl\conservative\gc.d(512): Memory allocation failed

Which doesn't follow from the change.

**Comment by kinke** [comment]
The issue isn't deterministic, but almost every pipeline since then contained at least one Windows job that failed. The test itself doesn't really allocate anything, so looks like some implicit demangling for profiling broke, somehow on Windows only.

**Pull request merged**
