### PR TITLE
Issue 8262 -  ICE(mtype.c) alias this to alias of an expression tuple

### PR DESCRIPTION
**Pull request by rainers**
https://issues.dlang.org/show_bug.cgi?id=8262

This PR doesn't change anything about what should happen with a tuple being aliased to "this", but merely avoids the crash. The net result seems to be that implicite conversions don't take place.

This is blocking https://github.com/D-Programming-Language/druntime/pull/1057 ATM.

### CODE REVIEW

**Comment by MrMormon** [comment]
> alias this to expression or mixed tuples is not well defined yet

Is this a comment about the D language specification?

**Comment by andralex** [comment]
@rainers status?

**Comment by rainers** [comment]
> @rainers status?

redone now and added test case. This still just follows the example of other code ignoring alias this if `aliasthisof()` returns null instead of crashing.

**Comment by andralex** [comment]
@rainers please mind the test failures thx!

**Review by andralex — APPROVED** [review]

**Pull request merged**
