### PR TITLE
fix Issue 15278 - Compile-time segfault when compiling code with alias this

### PR DESCRIPTION
**Pull request by thewilsonator**
rebases #5256
cc @RazvanN7

### CODE REVIEW

**Comment by thewilsonator** [comment]
Hmm, `runnable/test19251.d(12): Error: alias this is not reachable as `A` already converts to `immutable(A)`.

**Comment by RazvanN7** [comment]
It's not reachable without the alias this

**Comment by BBasile** [comment]
This issue is probably a dup of https://issues.dlang.org/show_bug.cgi?id=14499 and maybe 18260 too.

**Comment by RazvanN7** [comment]
It seems that the issue this PR is trying to fix has been resolved already. Closing...

**Pull request closed without merging**
