### PR TITLE
[dmd-cxx] Backport fixes for issue 18143 and 18719.

### PR DESCRIPTION
**Pull request by ibuclaw**
Last couple of problems found when testing druntime bindings in master.

### CODE REVIEW

**Comment by ibuclaw** [comment]
> std/file.d(213): Error: immutable field 'errno' initialized multiple times
> std/file.d(213): Error: immutable field 'errno' initialized multiple times

Oh yes, I forgot I also fixed phobos as well. :-)

**Comment by RazvanN7** [comment]
Maybe force push ro restart DMD C++?

**Review by RazvanN7 — APPROVED** [review]

**Comment by ibuclaw** [comment]
> Maybe force push to restart DMD C++?

The auto-tester does it automatically.  The Github test runners can be manually re-ran [from the checks page](https://github.com/dlang/dmd/pull/12153/checks?check_run_id=1761459599).

**Comment by RazvanN7** [comment]
Weird. I can re-run all other CirrusCI tests, but it seems I do not have rights for DMD C++ tests.

**Comment by ibuclaw** [comment]
> Weird. I can re-run all other CirrusCI tests, but it seems I do not have rights for DMD C++ tests.

Can you see a "Cancel workflow" button?  In the event of a failed build, that will change into a "Re-run job" button.

**Pull request merged**
