### PR TITLE
Issue 6907 - ice(interpret.d) delete expressions crash interpreter

### PR DESCRIPTION
**Pull request by 9rnsr**
Implement `delete` operation in CTFE.

### CODE REVIEW

**Comment by yebblies** [comment]
I'm not going to merge a pull that is 60% style changes.

**Comment by yebblies** [comment]
Although apart from that it looks good.

**Comment by ibuclaw** [comment]
Yes,  please submit the first commit in a new pr (I'll be happy merge it on the spot)

**Comment by 9rnsr** [comment]
I dropped the first commit.

**Comment by yebblies** [comment]
This doesn't follow the case indentation style of the rest of (d)dmd.

**Comment by 9rnsr** [comment]
@yebblies Which is?

**Comment by yebblies** [comment]
Cases aligned with switch opening brace, case contents indented once.

```d
switch ()
{
case X:
    statement;
}
```

**Comment by 9rnsr** [comment]
Ah, it was *suddenly* changed by ddmd conversion... Fixed indentation style in switch statement.

**Comment by yebblies** [comment]
Yes, I accidentally used my personal style when creating magicport, and nobody noticed until after the switch.  Unless we get approval from Walter to reformat all the code I'd prefer to keep it consistent.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
