### PR TITLE
Fix issue 17169 - New default ddoc theme merges all paragraphs except…

### PR DESCRIPTION
**Pull request by jacob-carlborg**
… the first

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
@Abscissa

**Comment by WalterBright** [comment]
What does this actually emit given the source code in the bug report?

**Comment by jacob-carlborg** [comment]
> What does this actually emit given the source code in the bug report?

It adds `<br><br>` between `P2` and `P3`. For the full output see [1], it's by default minimized in the diff view. This is more in line of how it looked like before the new ddoc theme. Here's a before and after example of the rendered result:

Before:



After:

screen shot 2017-02-14 at 08 29 41

[1] https://github.com/jacob-carlborg/dmd/blob/4d67aee38c9b9d4e2a6037bc73b6fcd9d82d13ea/test/compilable/extra-files/ddoc17169.html

**Comment by jacob-carlborg** [comment]
The failing Travis CI tests are unrelated, I think it fails for all PRs. See https://github.com/dlang/dmd/pull/6539.

**Comment by wilzbach** [comment]
@jacob-carlborg all regression fixes should target stable ;-)

**Comment by jacob-carlborg** [comment]
> all regression fixes should target stable ;-)

I hate this 😃.

**Comment by jacob-carlborg** [comment]
@wilzbach Will I cause any problems if I change the target branch to "stable"?

**Comment by wilzbach** [comment]
> @wilzbach Will I cause any problems if I change the target branch to "stable"?

GitHub will try to rebase your commit to `stable` - in the worst case you need to do it yourself afterwards, but I haven't had any problems yet.

**Comment by jacob-carlborg** [comment]
This doesn't look correct.

**Comment by jacob-carlborg** [comment]
Fixed, no targeting "stable".

**Comment by jacob-carlborg** [comment]
@WalterBright @MartinNowak @andralex ping, this is pretty trivial PR and a regression fix.

**Comment by jacob-carlborg** [comment]
@CyberShadow

**Comment by MartinNowak** [comment]
> GitHub will try to rebase your commit to stable - in the worst case you need to do it yourself afterwards, but I haven't had any problems yet.

No, github does not do the rebase, you have to do it yourself __after__ changing the base commit.
`git rebase --onto upstream/stable upstream/master` should work
It's important to push the rebased commit after changing the base branch in github for the tester to get notified and pick up the new base branch.

**Comment by jacob-carlborg** [comment]
Thanks.

**Pull request merged**
