### PR TITLE
Test hacky version of "always emit templates". Draft PR to trigger CI, please ignore

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Looks like there are some project who require some templates to be dropped.

**Comment by ibuclaw** [comment]
> 

Is this related to https://github.com/ldc-developers/ldc/pull/3422?

**Comment by atilaneves** [comment]
> > 
> 
> Is this related to [ldc-developers/ldc#3422](https://github.com/ldc-developers/ldc/pull/3422)?

I don't know if it's strictly *related* per se, but it's similar, yes. Convergent evolution.

**Comment by atilaneves** [comment]
Closed in favour of https://github.com/dlang/dmd/pull/11996

**Pull request closed without merging**
