### PR TITLE
[DDMD] Add ddmd manually ported source, converter and build system support

### PR DESCRIPTION
**Pull request by yebblies**
Remake of #3410 since I accidentally merged and reverted that one.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Let's keep the discussion in the old pull #3410.

**Comment by WalterBright** [comment]
Closing my eyes and pushing the button!

**Comment by yebblies** [comment]
Fantastic!  Thank you so much everyone.

**Comment by andralex** [comment]
Awesome possum. Congrats @yebblies for pushing this through!

**Pull request merged**
