### PR TITLE
gsroa.d: fix typo bug

### PR DESCRIPTION
**Pull request by WalterBright**
Fix bug introduced by https://github.com/dlang/dmd/pull/9271 yesterday. I haven't found a good way to test that optimizations are being performed.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ZombineDev** [comment]
> I haven't found a good way to test that optimizations are being performed.

Can we write a unittest that constructs some IR and calls `sliceStructs_Gather`?

**Comment by jacob-carlborg** [comment]
> I haven't found a good way to test that optimizations are being performed.

I'm no expert on this part of a compiler. But I'm guessing an optimization just rewrites a data structure into a different form. If that's the case, is it possible to construct the data structure in the unoptimized form, run the optimization and then verify that the data structure has been correctly rewritten?

**Comment by WalterBright** [comment]
Yes, it's possible, it's just freakin' ugly, hence not a good way.

**Comment by WalterBright** [comment]
The semaphoreci error:
```
*** Error in `./frontend': free(): invalid pointer: 0x00007f36ac93d900 ***
```
appears for other PRs, and so presumably has nothing to do with this PR.

**Pull request merged**
