### PR TITLE
Fix issue #15665: Templated scope class with constructor doesn't compile

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
While instantiating a template, FuncDeclaration::semantic3 will call into
TypeFunction::semantic, but the flags SCOPEctor is only set during
CtorDeclaration::semantic.

Not sure that's the right fix though. Suggestions are welcome :)

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
@MartinNowak is it possible to get this into 2.070.1 ?

**Comment by WalterBright** [comment]
Linky: https://issues.dlang.org/show_bug.cgi?id=15665

**Comment by WalterBright** [comment]
Looks good.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
