### PR TITLE
enable Dwarf EH for OSX 32

### PR DESCRIPTION
**Pull request by WalterBright**
This apparently did not get enabled.

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
It needs to be enabled in `target` as well.
You can just cherry-pick https://github.com/mathias-lang-sociomantic/dmd-dlang/commit/c83068fdbedf755b5ca0cb7cb307fcb36128ec05

**Comment by WalterBright** [comment]
@mathias-lang-sociomantic that enable adds C++ EH support. I'll do that in a separate PR.

**Comment by mathias-lang-sociomantic** [comment]
Fair enough.

Could you split it so that fixing the implementation is separate from actually enabling it by default ?
And also link to `D-Programming-Language/dmd#5510` from the fix's commit message.

**Comment by WalterBright** [comment]
> Could you split it so that fixing the implementation is separate from actually enabling it by default ?

I don't understand the point of that.

> And also link to D-Programming-Language/dmd#5510 from the fix's commit message.

To do links in github, use a full URL: https://github.com/D-Programming-Language/dmd/pull/5510

**Comment by WalterBright** [comment]
> Could you split it so that fixing the implementation is separate from actually enabling it by default ?

I don't understand the point of that.

> And also link to D-Programming-Language/dmd#5510 from the fix's commit message.

To do links in github, use a full URL: https://github.com/D-Programming-Language/dmd/pull/5510

**Comment by WalterBright** [comment]
> Could you split it so that fixing the implementation is separate from actually enabling it by default ?

I don't understand the point of that.

> And also link to D-Programming-Language/dmd#5510 from the fix's commit message.

To do links in github, use a full URL: https://github.com/D-Programming-Language/dmd/pull/5510

**Comment by WalterBright** [comment]
> Could you split it so that fixing the implementation is separate from actually enabling it by default ?

I don't understand the point of that.

> And also link to D-Programming-Language/dmd#5510 from the fix's commit message.

To do links in github, use a full URL: https://github.com/D-Programming-Language/dmd/pull/5510

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
Thanks!

(Sorry about the message dups, there was a rip in github's time-space continuum.)

**Comment by mathias-lang-sociomantic** [comment]
> > Could you split it so that fixing the implementation is separate from actually enabling it by default ?

> I don't understand the point of that.

This P.R. addresses multiple topics. It is both fixing the implementation, and enabling it the new behaviour. That's why it should be obvious both for the reviewer and anyone reading the history.

**Pull request merged**
