### PR TITLE
fix Issue 22023 - adding  to escaped argument of a variadic defeats @…

### PR DESCRIPTION
**Pull request by WalterBright**
…safe

### CODE REVIEW

**Comment by WalterBright** [comment]
Fixing this uncovered a related issue:

https://issues.dlang.org/show_bug.cgi?id=22818

**Comment by dkorpel** [comment]
Shouldn't this start as a deprecation?

**Comment by Geod24** [comment]
Aren't typesafe variadic inherently `scope` then ? They don't seem to be marked as such.

**Comment by WalterBright** [comment]
> Aren't typesafe variadic inherently scope then ?

Only arrays and classes. See https://issues.dlang.org/show_bug.cgi?id=22818

**Comment by WalterBright** [comment]
> Shouldn't this start as a deprecation?

Why would fixing a sure-fire crash require a deprecation?

**Comment by dkorpel** [comment]
> Why would fixing a sure-fire crash require a deprecation?

It's not a sure-fire crash, someone might add `return` to a variadic array mistakenly thinking it would apply to the array elements. Or they did return a pointer to the array, but it was not stomped by new stack allocations before use.

Personally I don't mind making this an error directly, I only ask because you [recently mentioned](https://github.com/dlang/dmd/pull/13691#issuecomment-1048281942) that people expect no breakage when not using preview switches.

**Comment by WalterBright** [comment]
@dkorpel you could apply that reasoning to every bug fix. This is why we leaven our rules with good judgement, and do not apply them absolutely.

**Review by dkorpel — APPROVED** [review]

**Comment by RazvanN7** [comment]
This PR has introduced a regression: https://issues.dlang.org/show_bug.cgi?id=23244 .

**Pull request merged**
