### PR TITLE
Remove special newdelete.o target

### PR DESCRIPTION
**Pull request by wilzbach**
I might be wrong, but AFAICT the D-part of dmd uses just `rmem.d`.

- remove linking newdelete.o to the libs (it's not used)
- remove dead code block

`newdelete.c` has been introduced in https://github.com/dlang/dmd/pull/4535 and added as Makefile target in https://github.com/dlang/dmd/pull/4924

### CODE REVIEW

**Comment by WalterBright** [comment]
newdelete.c is still in win32.mak

**Comment by wilzbach** [comment]
> newdelete.c is still in win32.mak

Yeah, I wasn't sure whether this will really pass on the auto-tester. Hence, I only tried `posix.mak`. I removed `newdelete.obj` from the `win32.mak` too, but for some reason CircleCi is still failing :/

**Comment by WalterBright** [comment]
Circleci runs on Linux, so win32.mak changes should be irrelevant to that.

**Comment by wilzbach** [comment]
This isn't going anywhere. Closing for now.

**Pull request closed without merging**
