### PR TITLE
do extra MOVSD instead of 4 MOVSB's

### PR DESCRIPTION
**Pull request by WalterBright**
A small thing, but easy.

### CODE REVIEW

**Comment by Geod24** [comment]
Does this (or could be extended to) fix https://issues.dlang.org/show_bug.cgi?id=21027 as well ?

**Comment by WalterBright** [comment]
@Geod24 that is definitely related and should be fixed as well, but as a separate PR.

**Comment by Geod24** [comment]
Without any test it's pretty hard to see if this work. Looking at the code I'm not convinced it does what you intend it to do. E.g. it does MOVSW before MOVSD in the first part of the diff, and in the second part the `if` is placed after a `REP MOVSD`, so I doubt that this code will ever be triggered.

**Comment by WalterBright** [comment]
> Without any test it's pretty hard to see if this work. Looking at the code I'm not convinced it does what you intend it to do. E.g. it does MOVSW before MOVSD in the first part of the diff, and in the second part the if is placed after a REP MOVSD, so I doubt that this code will ever be triggered.

In my tests it does what it's supposed to. As for the MOVSW, it's actually the same opcode as MOVSD. Calling it MOVSW dates back to the original 16 bit implementation.

Here's what compiling std/digest/sha.d yields:
```
       48 A5                   movsd
       48 A5                   movsd
       A5                        movsd
```

**Pull request merged**
