### PR TITLE
check for out of memory with allocation

### PR DESCRIPTION
**Pull request by WalterBright**
Lots of missing checks.

### CODE REVIEW

**Comment by Geod24** [comment]
Why not call `xmalloc` instead ?

**Comment by WalterBright** [comment]
> Why not call xmalloc instead ?

Because I don't know the original reason why xmalloc wasn't called. I'll leave that for a later effort.

**Comment by rainers** [comment]
How about an (almost) identity function `void* Mem.check(void*p)` instead that could be used to pipe through the result of the allocation? That would avoid adding control statements.

**Comment by Geod24** [comment]
> Because I don't know the original reason why xmalloc wasn't called. I'll leave that for a later effort.

I think that's just adding cruft for something that should be fairly simple.
But if you feel strongly about it, @rainers ' suggestion is a decent backup.

**Comment by WalterBright** [comment]
> I think that's just adding cruft for something that should be fairly simple.

It's not simple. Take a look at root/rmem.d. There are two implementations, one manual, one GC. If the lifetime of the allocation is known, it makes sense to not use the GC one, i.e. mem.xmalloc() should not be used.

**Comment by rainers** [comment]
> If the lifetime of the allocation is known, it makes sense to not use the GC one

You can also use the GC for manually managed memory with the additional benefit of not having to take extra care to add GC ranges in case the memory might contain pointers.
My benchmarks under Windows suggest that the GC is faster than standard C malloc. at the cost of a bit of extra memory but that's irrelevant for these temporary allocations.

**Comment by WalterBright** [comment]
It's hard to believe that GC.malloc/GC.free would be faster than malloc/free. (And Windows isn't the only platform!) But it is a good point that the GC ranges would be tracked.

In any case, this PR is just about fixing the immediate bug.

**Comment by rainers** [comment]
> It's hard to believe that GC.malloc/GC.free would be faster than malloc/free.

I don't see why it should be slower (apart from manpower thrown at the problem). The GC sacrificies some memory to allow fast lookup, that can help freeing quite a bit. A standard allocator will probably not make that compromise.

Unfortunately I had no time left for the last slide of my lightning talk at dconf: it showed that dmd with a disabled GC can be faster than the bump-pointer-allocation version. My speculation is that this is caused by the remaining C malloc/free calls being replaced.

> In any case, this PR is just about fixing the immediate bug.

Pedantically, it's not a bug as accessing null is considered `@safe` but I agree that the error messages are terrible.
BTW: note that `Mem.error` calls onOutOfMemoryError that throws a statically allocated Error. The default handler tries to allocate a stack trace which will probably fail, too (usually that uses the GC which pretty much breaks the current `@nogc` exceptions, though).

**Review by rainers — APPROVED** [review]
Not the best solution IMO, but not worth arguing too much.

**Review by atilaneves — APPROVED** [review]

**Comment by WalterBright** [comment]
> I don't see why it should be slower

Because of the enormous effort thrown by generations of programmers at malloc/free :-)

Note that the Win32 malloc/free is not a cutting edge implementation and shouldn't be considered definitive in the speed department.

> Pedantically, it's not a bug as accessing null is considered @safe but I agree that the error messages are terrible.

A seg fault is always a bug, even if it's not a memory safe issue. Seg faults also just make us look bad. Lastly, calling malloc and not checking the return for null is amateur hour, not professional code. These instances should never have passed code review.

**Pull request merged**
