### PR TITLE
Minor improvements to `foreach` semantic code for arrays

### PR DESCRIPTION
**Pull request by Geod24**
So I was looking into the `foreach` semantic routines and realized they could use some love.
I am working on adding `in` support (for arrays and `opApply`) and it requires a few fixes (e.g. using `isReference` instead of `STC.ref_`). I figured it would also be a good time to improve the code and its coverage.
Here's a couple commit that should be trivial to review.

### CODE REVIEW

**Comment by Geod24** [comment]
Failure is legit. Will fix tomorrow.

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
Spin off: https://github.com/dlang/dmd/pull/13248
Will update this accordingly afterwards.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@Geod24 Any plans on finishing this?

**Comment by Geod24** [comment]
@RazvanN7 : Finished

**Pull request merged**
