### PR TITLE
Fix Issue 20015 - [REG 2.086] Deprecated -preview, -revert, and -transition options not documented

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by Geod24 — CHANGES_REQUESTED** [review]
Test[s]?

**Comment by RazvanN7** [comment]
I didn't add any because, currently, all deprecated features have their documentation purged.

**Comment by MoonlightSentinel** [comment]
See 
- [testhelp.d](https://github.com/dlang/dmd/blob/master/test/compilable/testhelp.d)
- [previewhelp.d](https://github.com/dlang/dmd/blob/master/test/compilable/previewhelp.d)
- [transitionhelp.d](https://github.com/dlang/dmd/blob/master/test/compilable/transitionhelp.d)
- [reverthelp.d](https://github.com/dlang/dmd/blob/master/test/compilable/reverthelp.d)

Shouldn't some of these tests fail with this PR?

**Comment by Geod24** [comment]
> I didn't add any because, currently, all deprecated features have their documentation purged and the fix is obviously correct.

Side note: The main point of test is not to ensure that things work today (although it's still a pretty important side of it), but to ensure that they will work tomorrow. This is especially important for regression, because we have evidence of something that used to work that doesn't anymore.

> Furthermore, I don't see any tests for cli switches in the fail compilation directory.

https://github.com/dlang/dmd/blob/master/test/fail_compilation/reserved_version_switch.d
And obviously what @MoonlightSentinel linked, although those are in the "compilable" directory.

**Comment by RazvanN7** [comment]
@Geod24 At this point there is no deprecated switch with public documentation in dmd. There is a deprecated transition (complex) and a deprecated preview (intpromote) but both have their public documentation disabled. One thing I could do is to enable their documentation and list them as deprecated. If that is not acceptable, then I don't know how I could possibly test this without introducing a mock-up deprecation. What do you think?

**Comment by RazvanN7** [comment]
@Geod24 The `-transiton=complex` is deprecated but it is not listed in the documentation. To be able to test this I marked it as documented and deprecated. Is that ok? I don't really understand what the strategy is here; my expectation was that once a switch is deprecated it is also purged from the documentation to avoid new uses of it (that would require a single Feature field, not 2), but it seems that it is possible to have an undocumented switch which is not deprecated (like `preview=markdown` on the stable branch). This seems weird to me, but I am obviously missing context here.

**Comment by RazvanN7** [comment]
cc @MoonlightSentinel

**Review by Geod24 — APPROVED** [review]
Yes, that test is enough IMO

**Comment by Geod24** [comment]
> This seems weird to me, but I am obviously missing context here.

It's good that the default was enabled but the switch became a no-op (and not deprecated). That's what we did for `-dip25` too. This way, early adopters still get the behavior they expect, without needing to version their code to remove an annoying deprecation at **a specific version**.

**Pull request merged**
