### PR TITLE
issue 15371 - some traits should bypass the protection

### PR DESCRIPTION
**Pull request by ghost**
The argumentation is in the [bug tracker issue](https://issues.dlang.org/show_bug.cgi?id=15371), but in short:

> "__traits(getMember,...)" should always work, whatever is the member protection (as long as the symbol is a valid one).
> 
> The current limitation is problematic because it prevents to write functions related to traits in a separate dedicated modules (e.g mylib.traits)

See also [this issue](https://issues.dlang.org/show_bug.cgi?id=15335), it demonstrates why it could be interesting to give super-powers to traits: because the current limitation already affects phobos.

### CODE REVIEW

**Comment by adamdruppe** [comment]
This could fix my mistake with `getProtection` too which requires a symbol... which you can't get on private members right now.

**Comment by AndrejMitrovic** [comment]
This seems like something that requires approval. Also, would this allow someone to call a private function from another module?

Ping @WalterBright @andralex for thoughts.

**Comment by BBasile** [comment]
Yes this would allow things that are completly illegal, but this is the point. The idea is to allow this with a kind of caution, e.g _use this only if you know what you do because it can break the protection_. 

I'm curious to know if there could be another way to solve the problem exposed in the bugzilla issue (other than mixing a template to get the scope).

**Comment by WalterBright** [comment]
Maybe it would make sense to bypass the protection if one is not in `@safe` code.

**Comment by aubade** [comment]
Isn't ```@safe``` supposed to be about one specific thing (memory corruption)? Expanding it to mean "potentially poor programming practices" seems a very hazard-laden road to take

**Comment by BBasile** [comment]
You can close this PR, bugzilla issue is closed because of #6078

**Comment by JinShil** [comment]
See also comments starting here:  https://github.com/dlang/dmd/pull/7241#issuecomment-358643910

**Comment by RazvanN7** [comment]
Closing this as 2 other PRs have been submitted for this:

https://github.com/dlang/dmd/pull/9325
https://github.com/dlang/dmd/pull/9585

**Pull request closed without merging**
