### PR TITLE
replace test_cdvecfill.d with cdvecfill.sh

### PR DESCRIPTION
**Pull request by WalterBright**
Analogous to https://github.com/dlang/dmd/pull/9668

### CODE REVIEW

**Comment by JinShil** [comment]
I have the same objections to this as I posted in #9668.  There is no reason to use shell scripts when we have D.  We're trying to remove platform dependencies and have made good progress with build.d, run.d, d_do_test.d, etc.  Adding more shell scripts will diminish the progress that we've made.

**Comment by JinShil** [comment]
I think https://github.com/dlang/dmd/pull/9653 is a better solution.  It does not require any external tools and it's written 100% in D.

**Comment by WalterBright** [comment]
> It does not require any external tools

This requires `objdump` and `tail`, which are standard unix utilities. #9653 still requires `objdump`. And it requires dmd to be running on the target system - not a good plan for bootstrapping.

> and it's written 100% in D.

I hate to say it, but the code there is way overly complex. Compare it with how trivial the shell script I wrote is. Note that regular expressions, layers of templates, 200+ lines of code, none of that is needed.

Even worse, when it does fail, it's hard to see what the difference actually is. You get lots of escape codes. With my scheme, diff works like a charm - you see exactly what code is different without all the extraneous litter, and you see all the differences, not just the first.

**Comment by WalterBright** [comment]
Correction, #9653 doesn't require objdump.

**Comment by JinShil** [comment]
> And it requires dmd to be running on the target system - not a good plan for bootstrapping.

Yes, DMD requires a host D compiler because it is written in D.  That's already an intrinsic requirement.  The host D compiler should kick off the test of the target D compiler just as Bash does in this PR.

> I hate to say it, but the code there is way overly complex.

That's only because the code is doing everything in memory instead of compare output files.  If you find it simpler to compare output files, then pull #9653 and submit improvements.

> Even worse, when it does fail, it's hard to see what the difference actually is. You get lots of escape codes. With my scheme, diff works like a charm - you see exactly what code is different without all the extraneous litter, and you see all the differences, not just the first.

Again, that can be remedied by improving the code.  Please improve #9653's implementation rather than submit this competing one.

**Comment by WalterBright** [comment]
> That's only because the code is doing everything in memory instead of compare output files.

No, it's because it is trying to embed the result in the source code of the test. This is not a good approach, and we can see the results in way over-complex code that is also produces nearly unreadable output when errors occur.

**Comment by wilzbach** [comment]
> We can see the results in way over-complex code that is also produces nearly unreadable output when errors occur.

https://github.com/dlang/dmd/pull/9668#issuecomment-485381954

> Note that regular expressions, layers of templates, 200+ lines of code, none of that is needed.

Again, it's a literal translation of Martin's code. It could be made a lot simpler, because currently it explicitly lists all templates and searches for them in the object code. We could just search for these symbols too.

For the record, I don't object to `objdump` at all, I just object to shell scripts (especially because you haven't figured out that they can be reused, see e.g. https://github.com/dlang/dmd/blob/master/test/compilable/extra-files/json-postscript.sh) and using `objdump` without any postprocessor, because that will cause major headaches in the CI infrastructure. The output of `objdump` will change over different versions or vendors, the binary generated by DMD will stay the same.

**Comment by JinShil** [comment]
> This is not a good approach,

Then please pull #9653 and submit a PR to improve it.

**Comment by WalterBright** [comment]
I haven't seen evidence yet that the format of objdump varies. The example you posted was not such, that was different because one was a 32 bit compile and the other 64. Correcting the cdcmp.sh to add -m64 fixed it.

There's good reason to believe objdump does not vary, because I bet a number of tools depend on its output formatting.

**Comment by WalterBright** [comment]
> I just object to shell scripts

I understand, but this shell script has 4 commands in it that do nothing clever. You could translate those 4 commands into D as well, and it also would be vastly simpler than the auto-updater.

**Comment by wilzbach** [comment]
Merging as we have wasted too much time talking about this already. There are so many bigger fish to fry.

**Comment by WalterBright** [comment]
Thank you, @wilzbach

**Comment by wilzbach** [comment]
> objdump without any postprocessor, because that will cause major headaches in the CI infrastructure. The output of objdump will change over different versions or vendors, the binary generated by DMD will stay the same.

I hate to say it, but this was a known objection :/

Anyhow, @Basile-z if the language file settings doesn't work, please let us know. Then, we will have to add our own postprocessor (though it looks like `sed s/^.*section//` could already work).

**Comment by wilzbach** [comment]
Also, @Basile-z could you maybe give `env LC_ALL=C objdump` a try?

**Comment by WalterBright** [comment]
That's exactly what `sed` is for. Stream editing of text files is pretty well developed.

I've many times thought of making a library module that would take an array of bytes and return the disassembled instruction :-)

In the meantime, https://github.com/dlang/dmd/pull/9608 looks ready to go.

**Comment by wilzbach** [comment]
Okay, so I opened https://github.com/dlang/dmd/pull/9704 which converts the cdcmp.sh scrip into a postprocessor (see the PR for details), so it looks like my objdump version _does_ generate a different output.

**Comment by Basile-z** [comment]
I'm running the test suite right now with LC_ALL set to en_US in the two concerned scripts and it seems to work as well.

**Comment by Basile-z** [comment]
Well I don't really care how this is fixed but here's mine #9705.

**Pull request merged**
