### PR TITLE
refactor mscoff.h: #defines to enums

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
could you give the enums TypeNames ?

**Comment by WalterBright** [comment]
I'd rather not because of confusion about whether a new scope is introduced or not. It also won't translate well to D if I do that.

**Comment by UplinkCoder** [comment]
a right. I did not see that they were still .c files.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
