### PR TITLE
Fix Issue 23980 - OpenBSD: Add getthrname(2) and setthrname(2) to unistd.d

### PR DESCRIPTION
**Pull request by ibara**
As it says on the tin.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ibara** [comment]
I'm not sure why the CI failed. Can't imagine it's because of my changes...

**Comment by ibuclaw** [comment]
Triggering rebuild. This was caused by one half of the ci runners being updated to a newer OS.

**Comment by ibara** [comment]
I think it may have failed again :(

**Comment by ibuclaw** [comment]
> I think it may have failed again :(

This time for ssl reasons though. Two steps forward, one step back.

**Comment by ibara** [comment]
Another ping.

**Comment by dkorpel** [comment]
@RazvanN7 Can you merge this? I don't have permission to.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
