### PR TITLE
[dmd-cxx] Apply all backports in GDC to DMD sources

### PR DESCRIPTION
**Pull request by ibuclaw**
All commits were taken from GDC, names of the commits are mostly specific to GDC.  This synchronises entirely GDC's copy of the frontend into this branch, with the notable exception of `ExtAsmStatement` (as documented in #2194)

On the CI side, bumped the library version to v2.071, and enabled building druntime, phobos doesn't build, but IIRC, there are a few cherry pickings from latter releases in GDC in order to be compatible.

Also blindly merged in the 2.071.2 backend release of dmd, so that is at least in sync with druntime.

One thing notably missing are tests from the testsuite.  These are present in gdc, but not here as that would require another long sitting in order to format and apply them.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Turned on the druntime unittests also.

**Comment by ibuclaw** [comment]
@wilzbach - OK to sign off on this?

I promise that future PRs to this branch will be somewhat more reviewable. :-)

**Comment by wilzbach** [comment]
> @wilzbach - OK to sign off on this?

Hehe not really, but considering that you are the only user of the cxx branch, the CI is passing and that no one else looked at this so far, I think the best way forward is to merge this somewhat blindly ;-)

**Comment by ibuclaw** [comment]
Well I aim to keep them to a size like this:
https://github.com/D-Programming-GDC/GDC/pull/537

**Comment by ibuclaw** [comment]
However, 2.072 won't be so small, and I can't comment on backend changes. Which I am doing blindly, and have no intention of keeping them up to date after they have been switched to D.

**Comment by ibuclaw** [comment]
Given the way things are going, I think my last commit here would definitely be before the end of the year anyhow. . Once I have gdc prepped so I can swap the old frontend directly with the new, it shouldn't be long until the jump is made.

**Pull request merged**
