### PR TITLE
rename CompileExp to MixinExp

### PR DESCRIPTION
**Pull request by WalterBright**
I'm tired of the misleading name. Corresponds to `TypeMixin`.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Please add a (deprecated) alias to the old name to avoid breaking other users of DMD (e.g. DMD as a library).

**Review by Geod24 — APPROVED** [review]
Great! Can we rename `wild` next ?

**Comment by Geod24** [comment]
> Please add a (deprecated) alias to the old name to avoid breaking other users of DMD (e.g. DMD as a library).

I'm all for backwards compatibility, but that's not a policy we ever had.

**Comment by WalterBright** [comment]
buildkite:
```
source/contentprovider.d(330): [unittest] Source code line length exceeds 48 limit in 'Lubeck': import mir.ndslice: magic, repeat, as, slice, byDim;
  | object.Exception@source/contentprovider.d(330): Source code line length exceeds 48 limit in 'Lubeck': import mir.ndslice: magic, repeat, as, slice, byDim;
```
Wouldn't it be nice if the test suite would not keep failing for unrelated reasons.

**Pull request merged**
