### PR TITLE
[enh] fix issue 6549 - Implement contracts without implementation

### PR DESCRIPTION
**Pull request by WalterBright**
This is a rebase of https://github.com/D-Programming-Language/dmd/pull/2281

### CODE REVIEW

**Comment by andralex** [comment]
@WalterBright we need this but seems to have stalled... rebase? I agree with the enhancement.

**Comment by WalterBright** [comment]
rebased for ddmd

**Comment by andralex** [comment]
@WalterBright rebase again

**Comment by d-random-contributor** [comment]
Why function declaration without body doesn't require semicolon?

**Comment by andralex** [comment]
@WalterBright ping

**Comment by andralex** [comment]
@WalterBright ping

**Comment by ibuclaw** [comment]
Rebased in #7527

**Pull request closed without merging**
