### PR TITLE
[dmd-cxx] win32.mak: Copy dmd to $(GEN)/$(OS)/$(BUILD)/$(MODEL)

### PR DESCRIPTION
**Pull request by ibuclaw**
So it at least matches posix.mak

### CODE REVIEW

**Comment by ibuclaw** [comment]
Heh, _now_ the windows builds get further than the error in https://github.com/dlang/druntime/pull/2443.

**Comment by rainers** [comment]
The auto-tester doesn't use the expected variables, you could try to correct that by using these variables when invoking make again from the auto-test-build target: `"CC=$(VCBIN_DIR)/cl" AR="$(VCBIN_DIR)/lib"`.

See alo https://github.com/braddr/at-client/pull/10/files

**Comment by ibuclaw** [comment]
@rainers that's a change for druntime and phobos however?

**Comment by rainers** [comment]
> that's a change for druntime and phobos however?

True. Are you running a different build script for the cxx branch on the auto-tester?

**Comment by ibuclaw** [comment]
> True. Are you running a different build script for the cxx branch on the auto-tester?

I don't think so, but then again whatever the auto-tester does is a black box to me.  If that at-client repo contains script for gdc as well, then I guess whatever is there i what's used for dmd-cxx.

**Comment by rainers** [comment]
> std\math.d(4676): Deprecation: package core.stdc is not accessible here
> std\math.d(4676): Deprecation: module core.stdc.fenv is not accessible here, perhaps add 'static import core.stdc.fenv;'

Looks like you hit https://issues.dlang.org/show_bug.cgi?id=15903 or https://issues.dlang.org/show_bug.cgi?id=15900 which might not be backported? You might get further if you remove `-de` from the DFLAGS in phobos makefiles.

**Comment by ibuclaw** [comment]
I'm pretty sure it is backported, and I couldn't reproduce locally (using wine on Linux though).

I would initially guess it is an uninitialized memory bug that slipped through.

**Review by wilzbach — APPROVED** [review]
This at least allows to build druntime

**Pull request merged**
