### PR TITLE
convert cod3.c to D

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
Can anyone with access to buildkite post what it's complaint is?

@rainers what's up with appveyor?

**Comment by joakim-noah** [comment]
You can check Buildkite with the dummy account:

user: dummy@dlang.io
password: dlangrocks

I think it's only a style-checker issue with this PR, other failures are happening for other pulls too.

**Comment by rainers** [comment]
> @rainers what's up with appveyor?

nightlies.dlang.org is down. Thanks to @Geod24 https://github.com/dlang/dmd/pull/8678 has fixed that and its also merged to master.

**Comment by thewilsonator** [comment]
@WalterBright This is now green. Merge it?

**Comment by WalterBright** [comment]
yes, it's ready to go

**Pull request merged**
