### PR TITLE
replace ddmd files in .gitignore with a glob

### PR DESCRIPTION
**Pull request by MartinNowak**
- still possible to manually checking in matching files
  by using `git add -f`
- files already tracked by git show up in the diffs
  even if matching a .gitignore rule

### CODE REVIEW

**Comment by yebblies** [comment]
Why?

**Comment by WalterBright** [comment]
wildcard matches sooner or later cause trouble.

**Comment by MartinNowak** [comment]
Because it's yet another list of files that need to be maintained.
You have an idea how much time we spent telling people to which lists they have to add a new file.

> wildcard matches sooner or later cause trouble.

Sounds a bit like superstition :). As said in the OP, it's so possible to explicitly add *.d files and git won't ignore those. So the only trouble is that you need to `git add -f src/mynewfile.d`, something that's very hard to forget.

**Comment by yebblies** [comment]
The list is only temporary, trivial to maintain (I know this because I've been doing it), and at most a minor annoyance if someone forgets to update it.  Ignoring all D files is asking for trouble, based on my experience doing similar things in other projects.

**Comment by MartinNowak** [comment]
OK

**Pull request closed without merging**
