### PR TITLE
[dmd-cxx] Backport vector array fixes from master

### PR DESCRIPTION
**Pull request by ibuclaw**
Only needs a little more testing on my side to make sure the backport is correct.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
This is good to merge.

**Comment by jpf91** [comment]
@ibuclaw Nows that's interesting, github manages to cross-reference GCC SVN/GIT commits to pull requests if we mention the URL in the commit message? I didn't know that!

**Comment by ibuclaw** [comment]
@jpf91, yes, this has been the case for a number of years now. ;-)

**Comment by jpf91** [comment]
Yes, but it seems the repos also need to be somehow 'connected': For example, there's no link to the official GCC mirror at https://github.com/gcc-mirror/gcc, although it should have exactly the same commit.

**Pull request merged**
