### PR TITLE
fix issue 13975 - ICE: dmd crash if -gc and enum member is immutable int

### PR DESCRIPTION
**Pull request by rainers**
add missing masking of Tty

https://issues.dlang.org/show_bug.cgi?id=13975

### CODE REVIEW

**Comment by WalterBright** [comment]
Looks good, but needs a test for the test suite.

**Comment by Ingrater** [comment]
Looks good here too.

**Comment by rainers** [comment]
Added test case from the bugzilla report.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Pull request merged**
