### PR TITLE
Fix Issue 20687 - Allow member function address as const initializer

### PR DESCRIPTION
**Pull request by BorisCarvajal**
Previous discussion #10948

### CODE REVIEW

**Comment by schveiguy** [comment]
Now that the release is out, can we have a proper review of this? It seems to me like compile time should be able to get compile-time constants, especially when runtime code can get them.

**Comment by zyedidia** [comment]
I'd like to revive this conversation, since I think it should be possible to take addresses of member functions statically. Here are some reasons:

* It can be useful to statically store member function addresses so that they can be called later with a context pointer determined at runtime. The way to do this is to make a delegate, assign the function pointer to `funcptr` and the context pointer to `ptr`, and then call the delegate. This is valid and being able to store the function pointer statically is useful (e.g., for manually creating v-tables).
* It is currently possible to get the function pointer at runtime. It doesn't make any sense that you can get the function pointer (which is a constant) at runtime but not at compile-time.
* It is currently possible to get the function pointer at compile-time in GDC. I think LDC/GDC/DMD should all have the same behavior regarding what is a compilation error and what is not. Given that GDC allows this (plus the reasons above), LDC/DMD should also allow it.

**Comment by BorisCarvajal** [comment]
LDC also needs to remove the `needThis()` check in `gen/llvmhelpers.cpp:DtoConstSymbolAddress()`. ( @kinke )

**Review by kinke — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Comment by zyedidia** [comment]
Pinging @ibuclaw @schveiguy. Thanks!

**Pull request merged**
