### PR TITLE
fix issue 20655 - attribute inference accepts unsafe union access as …

### PR DESCRIPTION
**Pull request by aG0aep6G**
…@safe

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by aG0aep6G** [comment]
This is blocked by [issue 20661](https://issues.dlang.org/show_bug.cgi?id=20661), which is triggered more easily with this PR, but is also present without.

**Comment by schveiguy** [comment]
I just ran into this issue, while building code for my dconf 2020 talk. What is the status of this?

**Comment by aG0aep6G** [comment]
> What is the status of this?

Still blocked by [issue 20661](https://issues.dlang.org/show_bug.cgi?id=20661).

**Comment by RazvanN7** [comment]
I have created: https://github.com/dlang/dmd/pull/12207 . Hope it unblocks this.

**Comment by RazvanN7** [comment]
@aG0aep6G #12207 was merged. Maybe you can have another look at this?

**Comment by aG0aep6G** [comment]
> @aG0aep6G #12207 was merged. Maybe you can have another look at this?

That fix is in stable, but it's not in master yet. I'm targeting master here. Let me know if you want me to switch to stable. Otherwise, we'll have to wait until your fix hits master.

**Comment by RazvanN7** [comment]
Since this PR fixes a regression, procedure dictates that it should target stable.

**Comment by aG0aep6G** [comment]
now targeting stable

**Comment by RazvanN7** [comment]
This PR seems to break phobos.

**Comment by aG0aep6G** [comment]
> This PR seems to break phobos.

A reduced version of what's failing:

```d
enum isAssignable(alias T) = false;

struct Unique
{
    alias ValueType = typeof({ return a; }()); /* Error: circular `typeof` definition */
    static if (isAssignable!ValueType) {}
    int* a;
}
```

I'm not sure that's supposed to work. With `int a;`, the code is rejected with "Error: need `this` for `a` of type `int`". I don't see why it should work with a pointer.

**Comment by RazvanN7** [comment]
Plot twist. This compiles:

```d
enum isAssignable(alias T) = false;

struct Unique
{
    int* a;
    alias ValueType = typeof({ return a; }()); /* Error: circular `typeof` definition */
    static if (isAssignable!ValueType) {}

}

**Comment by aG0aep6G** [comment]
If `typeof({ return a; }())` must work, then I'm afraid this issue is getting too complex for me to fix.

**Comment by RazvanN7** [comment]
Maybe you can file this bug report and I will take a look at it hopefully next week.

**Comment by aG0aep6G** [comment]
> Maybe you can file this as a bug report and I will take a look at it hopefully next week.

Filed: https://issues.dlang.org/show_bug.cgi?id=21680

Note that fixing it doesn't necessarily unblock me here. If we consider issue 21680 a rejects-valid bug (which I think you're leaning towards), then I'm blocked here by my lack of DMD expertise, not by that issue.

**Comment by RazvanN7** [comment]
I'm hoping that fixing that issue will make the phobos compile with this patch. I'll have to investigate further.

**Comment by RazvanN7** [comment]
@aG0aep6G could you please rebase this?

**Comment by aG0aep6G** [comment]
> @aG0aep6G could you please rebase this?

rebased

**Comment by ibuclaw** [comment]
@aG0aep6G still interested in getting this over the finish line?

**Comment by aG0aep6G** [comment]
> @aG0aep6G still interested in getting this over the finish line?

no

**Comment by dkorpel** [comment]
Rebooted here: https://github.com/dlang/dmd/pull/14827

**Pull request closed without merging**
