### PR TITLE
Revert "Move dmd.mtype.Type.covariant to dmd.typesem"

### PR DESCRIPTION
**Pull request by ibuclaw**
This reverts commit aa056db4a6dd748192f937ff4e1484671c0cb4c0.

This broke the bootstrap
```
undefined reference to `covariant(Type*, Type*, unsigned long*, bool)
```

### CODE REVIEW

**Comment by thewilsonator** [comment]
Do you know why this broke bootstrap? 

Fixing that would be much preferable to reverting, as: 
1) this refactoring change is desired, and 
2) clearly CI didn't catch this, so it will be unlikely to catch this again when it, and other changes like it are merged.

cc @RazvanN7

**Comment by adamdruppe** [comment]
I see the same broken azure pipeline here as on my PR, i doubt that's coincidence... broken in master?

**Comment by WalterBright** [comment]
I see the same failure in my PRs, so this PR is not the source of the problem.

**Comment by thewilsonator** [comment]
To be clear, the broken pipeline for 32bit OMF, is indeed unrelated. The apparently broken bootstrap I presume is GDC only.
Also, when are we going to finally kill OMF for good?

**Comment by ibuclaw** [comment]
Indeed, it would be good if people refrained from chipping if they're not talking about this pr specifically.

**Comment by ibuclaw** [comment]
> Do you know why this broke bootstrap? 
> 

Function doesn't exist according to the linker. Could have been caught if a link test was added to cxxfrontend.cc when it got converted over.

**Comment by RazvanN7** [comment]
In what file is the undefined symbol referenced?

**Comment by RazvanN7** [comment]
It may be possible that typesem.o is not passed when compiling the problematic file.

**Comment by ibuclaw** [comment]
> It may be possible that typesem.o is not passed when compiling the problematic file.

There's be a lot more undefined references if that were the case.

**Comment by ibuclaw** [comment]
> In what file is the undefined symbol referenced?

I think you should be able to test it from cxx-frontend.cc with the following addition:
```
void test_mtype(Type *t1, Type *t2)
{
    // Link tests.
    covariant(t1, t2);
}
```

**Comment by RazvanN7** [comment]
Closing this in favor of: https://github.com/dlang/dmd/pull/15990 - which fixes the issue.

**Pull request closed without merging**
