### PR TITLE
Bugzilla 24700 - Don't search for mscoff .dp$B section over and over

### PR DESCRIPTION
**Pull request by dkorpel**
Compile time goes down from 42.5s to 2.8s when compiling this:

```D
static foreach (i; 0 .. 8_000)
    mixin("struct S"~i.stringof~" {float x;}");

__gshared int*[64_000] x;
```

Not closing the issue yet, because it's still doing O(n) section search in general making it slower than needed.

### CODE REVIEW

**Comment by rikkimax** [comment]
Assuming this is a singleton, it perhaps would make sense to have a table of them.

**Comment by dkorpel** [comment]
Please clarify 'this' and 'them'.

**Comment by rikkimax** [comment]
this = ``.dp$B``

them = sections

**Comment by dkorpel** [comment]
Yes, in the issue I mentioned how mscoff should use a hash table for sections just like elf, hence this is not closing the issue yet.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
