### PR TITLE
Fix critical bug causing the uint64_t to be sticky

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by Geod24** [comment]
Test and bugzilla issues ?

**Comment by UplinkCoder** [comment]
I am not going to create a bugzilla issue but I can provide a test.
one sec.

**Comment by Geod24** [comment]
> I am not going to create a bugzilla issue but I can provide a test.

The reason I was asking for a bugzilla issue is so it ends up in the changelog. So that people when they see the release, know that it is solving their problem. Or that someone, 6 months for now, testing with an old release of DMD, realizes that [s]he is affected by this bug and can't use a version lower than X.

Also this should target stable.

**Comment by UplinkCoder** [comment]
No need to target stable the bug is not in stable ...

**Comment by UplinkCoder** [comment]
closing because now it's messed up.

**Comment by Geod24** [comment]
> No need to target stable the bug is not in stable ...

Right, it was introduced by https://github.com/dlang/dmd/pull/10862

**Review by Geod24 — APPROVED** [review]

**Comment by thewilsonator** [comment]
Did this not have bugzilla numbers? The bot post is edited.

**Comment by Geod24** [comment]
No, the regression is only in master.
The bot added a bunch of issue when @UplinkCoder changed the target to `stable` (because then it included commits from `master`), but removed them when the target was switched back.

**Pull request merged**
