### PR TITLE
Fix Issue 19108 - Unknown pragmas not ignored inside body

### PR DESCRIPTION
**Pull request by JinShil**

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Comment by wilzbach** [comment]
@CyberShadow that's a new one:

```
CyberShadow/DAutoTest
Command `'git' '-c' 'core.autocrlf=false' 'fetch' 'origin' '+refs/pull/1021/head:refs/digger/pull/1021'` failed with status 128
```

**Comment by thewilsonator** [comment]
Before this gets merged please see what it does to https://issues.dlang.org/show_bug.cgi?id=19149
where known pragmas are treated as unknown inside a body.

**Comment by ibuclaw** [comment]
Indeed, it's probably better to fix them all in one go.  I have a list of bug reports that are related somewhere...

**Comment by thewilsonator** [comment]
Well it looks to be time to merge the semantic analysis of `PragmaDeclaration` and `PragmaStatement`. I'll do that now.

**Comment by JinShil** [comment]
>  I have a list of bug reports that are related somewhere...

This is the issue list I'm working off of:  https://forum.dlang.org/post/mailman.2739.1532340604.29801.d.gnu@puremagic.com

**Comment by ibuclaw** [comment]
@JinShil ok, yes that is everything. :-)

Fixing the other two issues - giving control to the implementing compiler whether a pragma is recognised, or needs to be a statement - will also close issue 3004.

**Pull request merged**
