### PR TITLE
Fix Issue 22224 - [REG 2.097.0] compiler segfaults with -profile

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
Please follow our guidelines for commit message

**Review by RazvanN7 — APPROVED** [review]
What @Geod24 said.

**Review by ibuclaw — DISMISSED** [review]
What @Geod24 said. :-)

**Comment by UplinkCoder** [comment]
@Geod24 which exactly this is a super trivial bugfix?

**Comment by Geod24** [comment]
https://github.com/dlang/dmd/blob/master/CONTRIBUTING.md#solving-bugs--submitting-pull-requests

> When fixing a Bugzilla issue, use the title: 'Fix issue XXXXX - **Issue title**'. This is recognized by both Bugzilla and our GitHub bot (dlang-bot), and will automatically link the issue and the pull request together (by providing a link to the issue in Github, and automatically closing bugs when pull requests are merged).

Emphasis mine.

**Comment by UplinkCoder** [comment]
@Geod24 there you go please re-add the automerge.

**Comment by UplinkCoder** [comment]
@ibuclaw stuck on FreeBSD?

**Comment by ibuclaw** [comment]
> @ibuclaw stuck on FreeBSD?

Rebase against master, this is pull is too old.

**Comment by Geod24** [comment]
@ibuclaw : It's targeting stable.

**Comment by ibuclaw** [comment]
> @ibuclaw : It's targeting stable.

Then rebase against stable?

**Pull request merged**
