### PR TITLE
add backend/cdef.d

### PR DESCRIPTION
**Pull request by WalterBright**
It's a rote translation of cdef.h. It is not the complete file, but should be enough to get us going.

Blocked by https://github.com/dlang/dmd/pull/6036

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Name the enums please.  :)

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Named enums work differently in C++ and D, it's better not to do that when translating.

**Comment by WalterBright** [comment]
Naming them changes the semantics because it introduces a new scope. Also, the names aren't there on the C++ side, which would make keeping the D and C++ headers in sync more difficult.

**Pull request merged**
