### PR TITLE
use enum instead of immutable for CTFE-only literals

### PR DESCRIPTION
**Pull request by 0-v-0**

### CODE REVIEW

**Comment by dkorpel** [comment]
For array literals, immutable is preferred in general because enums can turn into GC-allocated array literals. There's even a D-scanner warning for this. Is there any reason to prefer enum here?

**Comment by 0-v-0** [comment]
These array literals are only used in CTFE, so using enum can avoid emitting to binary target

**Review by dkorpel — APPROVED** [review]

**Review by Geod24 — DISMISSED** [review]
This is making the code worse, not better. It risks memory allocation, as already mentioned, for what benefit ?

**Comment by 0-v-0** [comment]
To clarify, could you specify whether the memory allocation occurs at runtime or compile time when using enum?

**Comment by Geod24** [comment]
> To clarify, could you specify whether the memory allocation occurs at runtime or compile time when using enum?

Depends on the call site, but usually at runtime.

```D
private enum Literal = [1, 2, 3, 4];
private immutable Constant = [1, 2, 3, 4];

void main()
{
    const int[] foo = Literal; // Works, but allocates
    const int[] bar = Literal; // Allocates again!
    const int[] foobar = Constant; // Does not allocate
    const int[] barfoo = Constant; // Also does not allocate
	assert(foobar is barfoo);
	assert(foo is bar);
}
```

**Comment by dkorpel** [comment]
> for what benefit ?

I tested it, and dmd's executable becomes about 5 Kb smaller by not emitting these arrays into the binary.

```
   text    data     bss     dec     hex filename
8566262  916832   53520 9536614  918466 dmd (before)
8564746  914256   53520 9532522  91746a dmd (after)
```

The arrays are only used to populate `exptab`, `optab1` and `optab2` at compile time, so this doesn't introduce new run-time allocations. As an alternative, the arrays can be defined inside the CTFE function that generates these tables, but I don't think that's required for this PR.

**Comment by dkorpel** [comment]
Since this fails the buildkite style check, can you either disable that warning, or turn the arrays back into static immutable variables, but inside the CTFE function literals that use them?

**Pull request merged**
