### PR TITLE
Fix grammar of changelog a bit for cpp mangle update

### PR DESCRIPTION
**Pull request by schveiguy**

### CODE REVIEW

**Comment by Geod24** [comment]
SemaphoreCI seems stuck here. Removing auto-merge until it comes back online, feel-free to re-apply yourself.

**Review by PetarKirov — APPROVED** [review]

**Comment by schveiguy** [comment]
semaphoreci seems to have skipped this PR. I don't know why. Trying to close and reopen.

**Comment by schveiguy** [comment]
Didn't come back. ping @wilzbach can you just merge this? It's a single word change in documentation.

**Comment by Geod24** [comment]
@schveiguy I think it's because the branch is in the blessed repo. Can you recreate from your fork?

**Comment by Geod24** [comment]
We cannot force merge because Semaphore is set as required.

**Comment by jacob-carlborg** [comment]
> We cannot force merge because Semaphore is set as required.

Would merging using the command line work?

**Comment by wilzbach** [comment]
No, but I just disabled the requirement check for SemaphoreCI.

**Comment by schveiguy** [comment]
> Can you recreate from your fork?

Ugh, this is what github does by default when you are a member and edit via their web interface. I do that for simple doc fixes usually because I don't want to go through the hassle of doing it locally. If I was not a member, it would create it in my own fork.

I suppose it's possible to do it in my own fork (after it's updated from upstream), and then change the PR target? I have no idea, never thought of that process before.

**Comment by schveiguy** [comment]
BTW, thanks @wilzbach.

**Pull request merged**
