### PR TITLE
Remove function prototypes from backend pt2

### PR DESCRIPTION
**Pull request by dkorpel**
Following https://github.com/dlang/dmd/pull/15111
Includes https://github.com/dlang/dmd/pull/15124

### CODE REVIEW

**Comment by dkorpel** [comment]
> Error: out of memory

How much RAM do the Azure pipelines have?

**Review by RazvanN7 — APPROVED** [review]

**Comment by WalterBright** [comment]
This process will go faster if done in smaller chunks. This PR attempts to do too much, resulting in "Some checks were not successful". Smaller chunks makes getting the result to work a LOT easier, resulting in mucho time savings.

**Comment by PetarKirov** [comment]
I agree with @WalterBright. At minimum, these changes should spread over several smaller commits in the same PR.

**Comment by dkorpel** [comment]
I tried to do things incrementally (hence pt1, pt2) and stop at ~100 lines, but this one spiraled a bit out of control because there was a ripple effect: adding an import at one point results in an ambiguous symbol error at another module, which needs to be resolved by replacing a prototype with an import, causing an ambiguous symbol in a third module etc. By the time the errors were resolved, it was -400 lines.

It puzzles me how something as simple as replacing extern functions with imports results in out of memory errors on Azure, and after rebasing (I didn't even change anything :confused: ), time outs on Cirrus . Either they are on the brink of their resource limits, or this PR somehow makes a big difference. Perhaps it's an issue with the backend inliner, such as [Issue 23857](https://issues.dlang.org/show_bug.cgi?id=23857).

**Comment by dkorpel** [comment]
Superseded by https://github.com/dlang/dmd/pull/15146

**Pull request closed without merging**
