### PR TITLE
remove ClassFlags, a dead declaration

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by yebblies** [comment]
It's not dead, it's used in a part of the glue layer that hasn't been translated yet.

**Comment by WalterBright** [comment]
Maybe it should wait for that, then?

**Comment by WalterBright** [comment]
https://www.youtube.com/watch?v=dGFXGwHsD_A

**Comment by andralex** [comment]
waiting

**Comment by AndrejMitrovic** [comment]
_Waiting for Godot._

Is this ready for an auto-merge..? If not please label it blocked.

**Comment by andralex** [comment]
will close for now

**Pull request closed without merging**
