### PR TITLE
fix issue 19112 - Associative array opIn with static array key fails …

### PR DESCRIPTION
**Pull request by aG0aep6G**
…with dynamic array

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Comment by wilzbach** [comment]
(DAutoTest and Jenkins failures are unrelated :/)

**Comment by jacob-carlborg** [comment]
This is a breaking change and should ideally be a deprecation instead.

**Comment by aG0aep6G** [comment]
> This is a breaking change and should ideally be a deprecation instead.

What is it breaking? The code that is now rejected was producing garbage before.

**Comment by wilzbach** [comment]
> This is a breaking change and should ideally be a deprecation instead.

I disagree. Our policy is that we can (and should do) breaking changes for broken code that has never and will never work.

**Review by wilzbach — APPROVED** [review]

**Review by jacob-carlborg — APPROVED** [review]

**Pull request merged**
