### PR TITLE
Add type mangling for cent/ucent.

### PR DESCRIPTION
**Pull request by redstar**
Uses zi/zk as proposed in http://forum.dlang.org/post/jfmvglcbcvnyuzfvvxfr@forum.dlang.org.

May require some discussion...

### CODE REVIEW

**Comment by yebblies** [comment]
Maybe we should migrate to strings?

**Comment by redstar** [comment]
Use of strings would eliminate the ugly `if`. What about the use of zi/zk as @ibuclaw has proposed some time ago?

**Comment by yebblies** [comment]
I have no problem with using zi/sk.  Maybe converting it to a switch would be better than the array.

**Comment by redstar** [comment]
I changed the type to string because the array is used a second time.

**Comment by ibuclaw** [comment]
:+1:

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
