### PR TITLE
Remove no longer needed RTLSYM enum items

### PR DESCRIPTION
**Pull request by JinShil**
The diff looks like hell, but all I did was add explicit values to the enum and remove those marked as `// unused`.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
cc @WalterBright

**Review by RazvanN7 — APPROVED** [review]

**Comment by WalterBright** [comment]
Why?

**Comment by JinShil** [comment]
For those who understand, no explanation is necessaey. For those who don't understand, no explanation is sufficient.

**Comment by wilzbach** [comment]
@WalterBright: why not?

**Pull request closed without merging**
