### PR TITLE
replace Visitor for Statement_toIR() with mixin

### PR DESCRIPTION
**Pull request by WalterBright**
First use of mixin instead of Visitor for Statements.

### CODE REVIEW

**Comment by Geod24** [comment]
What's the benefit ? It's more code and less readable.

**Comment by WalterBright** [comment]
> What's the benefit ? It's more code and less readable.

As I explained when the same thing was done for Initializers, the Visitor class has some drawbacks:

1. double dispatch is slow, as it defeats code prediction
2. double dispatch prevents inlining
3. it's not possible to add attributes to the Visitor code
4. creating the specialized Visitor derived class is clunky with its constructors and fields.
5. inheritance defeats optimization

As for code size, it won't be any larger, as the mixin template size is amortized over every use of it.

The mixin will also ensure that every case is accounted for.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@Geod24 Any objections?

**Comment by RazvanN7** [comment]
@Geod24 for more context: https://github.com/dlang/dmd/pull/14955 . Initially, I had the same reaction as you did.

**Pull request merged**
