### PR TITLE
fix Issue 15257 - __traits(compiles, .) with malformed inline asm sil…

### PR DESCRIPTION
**Pull request by WalterBright**
…ently ends compilation

Previous PRs for this:

https://github.com/dlang/dmd/pull/5244
https://github.com/dlang/dmd/pull/6068

### CODE REVIEW

**Comment by thewilsonator** [comment]
Tests?

**Comment by WalterBright** [comment]
circleci fails with:
```
Makefile:208: recipe for target 'start_all_tests' failed
make: *** [start_all_tests] Hangup
Too long with no output (exceeded 10m0s): context deadline exceeded
```
which is quite useless as it runs a thousand tests in parallel and there's no clue which it is.

**Comment by WalterBright** [comment]
The timeout is happening on the autotester, too. But also with no clue in the log file.

**Comment by WalterBright** [comment]
Found the loop, will fix it tomorrow. The problem is the old method didn't require any error recovery, which I have to add.

**Review by ghost — APPROVED** [review]

**Pull request merged**
