### PR TITLE
fix Issue 15389 - extern(C++) forward referencing problem

### PR DESCRIPTION
**Pull request by WalterBright**
https://issues.dlang.org/show_bug.cgi?id=15389

### CODE REVIEW

**Comment by TurkeyMan** [comment]
Does this fix also address this case?
```
  alias X = NS.X;
  extern (C++, NS) struct X {}
```

**Comment by TurkeyMan** [comment]
Also, is it safe to say this won't make it into 2.70?

**Comment by WalterBright** [comment]
If it doesn't, you can still use HEAD as your compiler.

**Comment by WalterBright** [comment]
> Does this fix also address this case?

Yes.

**Comment by JackStouffer** [comment]
@TurkeyMan you can also use digger to use 2.070 with this PR by doing 

```
$ digger build "2.070 + dmd#5330"
```

**Comment by TurkeyMan** [comment]
I can do that for myself, but I don't love to idea of distributing self-built binaries to my colleagues. If I can't point them to the website and tell them to install the compiler, that really doesn't make a great impression. D needs to make great impressions if I'm gonna win over skeptical minds.
If I miss the imminent release boat, then it's a particularly long wait for the next one :/

@MartinNowak Are you still working on the 2.070 release? Any change this fix will sneak in?

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
> I can do that for myself, but I don't love to idea of distributing self-built binaries to my colleagues. If I can't point them to the website and tell them to install the compiler, that really doesn't make a great impression. D needs to make great impressions if I'm gonna win over skeptical minds.

If you want to try this fix, use our [D Nightlies](https://builds.dawg.eu/).
If you're on anything but Windows, there is also an install script, still need to write a Powershell script.
```d
curl -fsSL https://builds.dawg.eu/install.sh | bash -s dmd-nightly
```
We'll soon be moving all of those to official dlang.org addresses.

**Comment by MartinNowak** [comment]
As this only affects C++ namespaces the risk to break anything is fairly low, so I'll make an exception an pick this over.

**Comment by andralex** [comment]
@MartinNowak see also https://github.com/D-Programming-Language/dmd/pull/5333

**Comment by WalterBright** [comment]
Note that while #5333 was found when researching a namespace problem, I discovered it also affected all scoped names (like struct tag names). #5330, however, is namespace specific.

**Pull request merged**
