### PR TITLE
add type parameter to ArrayLiteralExp constructors

### PR DESCRIPTION
**Pull request by WalterBright**
Most of the time the type parameter is needed, so add it.

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]
Shouldn't the constructor in astbase be updated too?

**Comment by wilzbach** [comment]
(Jenkins failure is unrelated)

**Comment by WalterBright** [comment]
> Shouldn't the constructor in astbase be updated too?

May break using the AST library.

**Comment by wilzbach** [comment]
FWIW DMD as a library is still declares as unstable and AFAICT no one is using it as of now.

**Pull request merged**
