### PR TITLE
fix Issue 23056 - importC: dmd asserts for missing return statement i…

### PR DESCRIPTION
**Pull request by WalterBright**
…n CTFE function

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by WalterBright** [comment]
@ibuclaw I'm not so sure that's a good idea. This is new development, not regressions.

**Comment by thewilsonator** [comment]
ICEs _always_ go to stable, its not that hard.

**Comment by WalterBright** [comment]
Many of our rules are in conflict.

**Comment by ibuclaw** [comment]
It is especially important because we are cutting a new release in a couple weeks. This fix won't be in the 2.100 release because we've already merged master into stable last week, and won't do so again for another 2 months.

And as @thewilsonator says, if you can crash the compiler with some code, that is all the more reason to get it into the upcoming release.

**Pull request merged**
