### PR TITLE
fix Issue 18457 - betterC - struct destructor is always called at fun…

### PR DESCRIPTION
**Pull request by WalterBright**
…ction return

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
> Bug fixes should always target stable...

Isn't that for regressions only?

**Comment by wilzbach** [comment]
Well, this is a regression introduced by betterC. In any case people apparently depend on this fix, so if it's targeted at stable, it will be part of 2.083 which will be released soon (1.11).

**Comment by WalterBright** [comment]
It's not a regression, as it never worked with betterC.

**Comment by kinke** [comment]
Including it in v2.083 final makes a lot of sense though due to the severity of the issue - no point in delaying this to 2.084, i.e., ~2 more months. - Thanks for the fix, Walter.

**Comment by WalterBright** [comment]
It's fine with me if you want to put it in stable.

**Comment by wilzbach** [comment]
Rebased to `stable`. For reference, it's just `git rebase --onto upstream/stable upstream/master`

Stable is regularly merged back into master, but anyone can run [`merge_stable`](https://github.com/wilzbach/git-tools/blob/master/merge_stable) themselves.

**Comment by WalterBright** [comment]
Thank you, @wilzbach ! You're a champ.

**Review by wilzbach — APPROVED** [review]

**Pull request merged**
