### PR TITLE
clean utf code

### PR DESCRIPTION
**Pull request by luismarques**
This pull request cleans the code related to UTF, mainly `utf.d`.

Summary of changes:
- The UTF code only seems to be used by the frontend, so the `extern(c++)` type modifiers and the file `utf.h` were dropped.
- Some functions that, once updated, would only wrap over the existing ones in phobos were deleted and their invocations were changed to call the phobos ones directly
  - `utf_codeLengthChar`
  - `utf_codeLengthWchar`
  - `utf_encodeChar`
  - `utf_encodeWchar`
- The function `isUniAlpha` was changed from a manual binary search to a simple `return c in alphaSet;`. The `alphaSet` is a std.uni.CodepointSet (a trie), built from the existing list of acceptable code points.
  - Warning / TODO: This function says "Use table from C99 Appendix D.", but the list of code points matches neither the C99 Annex D nor the C11 Annex D. Please clarify which code points should be accepted, according to which logic / standard, and if the comment is meant to be interpreted as an aspirational TODO.
- The functions `utf_decodeChar` and `utf_decodeWchar` were not changed to use Phobos decoding code because it doesn't seem to be possible to recover enough information from the UTFException to differentiate between the existing error cases/messages.

### CODE REVIEW

**Comment by yebblies** [comment]
No phobos imports please.

**Comment by luismarques** [comment]
@yebblies I didn't know that using the standard library wasn't allowed in DMD. What's the rationale? So, do I just drop all the changes in this pull request? :(

**Comment by yebblies** [comment]
Right now we are focusing on ensuring ddmd matches c++ dmd in performance and features.  Bringing in phobos is at the very least going to hurt compile times.  This PR doesn't add anything that makes that worthwhile.

There is still plenty of refactoring and cleanup work that could be done in here (eg removing redundant __gshared and static, using D strings) but adding dependencies is a problem.

**Comment by luismarques** [comment]
What's allowed to be thread-local, and what should be __gshared? (In general). I had assumed that nothing thread-local was welcome, due to the use of the -vtls flag.

**Comment by yebblies** [comment]
You assumed correctly, but immutable variables are implicitly shared.  I suspect a lot of constant strings and arrays could be made immutable.

**Comment by luismarques** [comment]
I reverted the actual code changes. Now the pull request only includes clean-ups like making things `immutable`, local, not `extern(C++)` and so on. Also, `utf.h` and references to that file were removed.

**Comment by 9rnsr** [comment]
LGTM.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Pull request merged**
