### PR TITLE
cirrus.yml: Use an alternative mirror for FreeBSD 11

### PR DESCRIPTION
**Pull request by ibuclaw**
Cherry-picked from stable #14076 to fix the FreeBSD 11 pipelines.

### CODE REVIEW

**Comment by ibuclaw** [comment]
FreeBSD 11.4 pipeline passes, that's all that matters -> merging.

**Comment by RazvanN7** [comment]
Thanks @ibuclaw !

**Comment by MartinNowak** [comment]
> Cherry-picked from stable #14076 to fix the FreeBSD 11 pipelines.

Could we please try to reduce cherry-picking a bit. Why not just merge stable?
It really doesn't make sense to spent that much time on resolving merge conflicts from duplicated cherry-pick commits.

<details>
<summary>merge back dmd stable</summary>

```sh
Auto-merging .cirrus.yml
CONFLICT (content): Merge conflict in .cirrus.yml
Auto-merging VERSION
CONFLICT (content): Merge conflict in VERSION
CONFLICT (modify/delete): changelog/mustUse.dd deleted in upstream/stable and modified in HEAD.  Version HEAD of changelog/mustUse.dd left in tree.
Auto-merging src/build.d
Auto-merging src/dmd/backend/cod1.d
Auto-merging src/dmd/cli.d
Auto-merging src/dmd/cparse.d
Auto-merging src/dmd/declaration.d
Auto-merging src/dmd/declaration.h
Auto-merging src/dmd/dinterpret.d
Auto-merging src/dmd/dmangle.d
CONFLICT (content): Merge conflict in src/dmd/dmangle.d
Auto-merging src/dmd/dscope.d
Auto-merging src/dmd/dsymbolsem.d
CONFLICT (content): Merge conflict in src/dmd/dsymbolsem.d
Auto-merging src/dmd/dtoh.d
Auto-merging src/dmd/e2ir.d
Auto-merging src/dmd/escape.d
CONFLICT (content): Merge conflict in src/dmd/escape.d
Auto-merging src/dmd/expressionsem.d
CONFLICT (content): Merge conflict in src/dmd/expressionsem.d
Auto-merging src/dmd/frontend.h
Auto-merging src/dmd/func.d
Auto-merging src/dmd/glue.d
Auto-merging src/dmd/initsem.d
Auto-merging src/dmd/json.d
Auto-merging src/dmd/mars.d
Auto-merging src/dmd/mtype.d
Auto-merging src/dmd/semantic3.d
Auto-merging src/dmd/target.d
Auto-merging src/dmd/tocsym.d
Auto-merging src/dmd/toctype.d
Auto-merging src/dmd/toobj.d
Auto-merging src/dmd/traits.d
Auto-merging src/dmd/typesem.d
Auto-merging src/dmd/utils.d
CONFLICT (content): Merge conflict in src/dmd/utils.d
Auto-merging test/compilable/reverthelp.d
Auto-merging test/fail_compilation/test23037.c
CONFLICT (add/add): Merge conflict in test/fail_compilation/test23037.c
Auto-merging test/fail_compilation/write_error.d
CONFLICT (add/add): Merge conflict in test/fail_compilation/write_error.d
Auto-merging test/runnable/testxmm.d
CONFLICT (content): Merge conflict in test/runnable/testxmm.d
Recorded preimage for '.cirrus.yml'
Recorded preimage for 'VERSION'
Recorded preimage for 'src/dmd/dmangle.d'
Recorded preimage for 'src/dmd/dsymbolsem.d'
Recorded preimage for 'src/dmd/escape.d'
Recorded preimage for 'src/dmd/expressionsem.d'
Recorded preimage for 'src/dmd/utils.d'
Recorded preimage for 'test/fail_compilation/test23037.c'
Recorded preimage for 'test/fail_compilation/write_error.d'
Recorded preimage for 'test/runnable/testxmm.d'
Automatic merge failed; fix conflicts and then commit the result.
```
</details>

**Comment by MartinNowak** [comment]
Same goes for https://github.com/dlang/dmd/pull/14064, even when merging locally, it would be better to avoid fast-forward merges or rebases and rather create a merge commit.

**Comment by MartinNowak** [comment]
@ibuclaw

**Comment by ljmf00** [comment]
> > Cherry-picked from stable #14076 to fix the FreeBSD 11 pipelines.
> 
> Could we please try to reduce cherry-picking a bit. Why not just merge stable? It really doesn't make sense to spent that much time on resolving merge conflicts from duplicated cherry-pick commits.
> merge back dmd stable

I recognize the @ibuclaw workflow, probably from GCC but I also recognize that this is not our current workflow.

We should do `-x` or reference the original commit on the cherry-picked commit in some way to be able to easily seek for context in the original history.

I personally see no reason to use merge commits for patches in general, especially maintaining stable backports. People often missuse `git` and use merge commits to submit a patches and I think we should really stop doing those for individual patches, squashing it is the best option. If it is required to have two commits, people should rebase or if unrelated, should do separate PRs. If you see linux, llvm, gcc and other major projects, they only use merge commits mostly to merge tags and other working tree's, not individual patches.

I also don't think that merging `stable` with `master` is an efficient process/workflow, specially on every change. The reason for it is that merge commits clutter the linearity of the history and easily becomes a spaghetti of merges and the ability to recognize the branched changes on the history is gone. I suppose, the fact that we don't often merge stable with merge on every patch is to not clutter the history, but we should run tests on `master` with those patches too, because `stable` patches might introduce side effects on subsequent changes.

My view is that `stable` should only get cherrypicked patches, and once `stable` needs to be updated with `master`, just rebase the changes and the cherry-picked ones get pruned. Although this doesn't work if someone externally rely on `stable` if it requires a fast-forward pull, but, by nature, `stable` is supposed to be aligned with `master` history when a new minor release, not with two way merges.

At maximum, we should only do one merge, `master` to `stable` and cherry-pick the rest from `master` to `stable`, if `stable` needs to always have a linear history. IIRC, conflicts will only happen if a different merge strategy is used or, obviously, if the affected diff zone is changed on another non-stable patch.

**Pull request merged**
