### PR TITLE
convert filespec.c to D

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
GitHub fails to detect the rename. Perhaps making a separate commit for the rename will help. It's a bit difficult now to review.

**Comment by thewilsonator** [comment]
You typo'd the commit message and title: should be `convert filespec.c to D` not `convert filespec.d to D`.

**Comment by WalterBright** [comment]
@thewilsonator You're right. I shall have myself flagellated with a wet noodle for my incompetence.

**Comment by WalterBright** [comment]
Why should changing the commit message now cause builtkite to fail?

**Comment by thewilsonator** [comment]
Per https://github.com/dlang/druntime/pull/2337#issuecomment-433212312 it is unrelated. Just merge once autotester is green.

**Pull request merged**
