### PR TITLE
[REG2.068a] Issue 14814 - ld: GOT load reloc does not point to a movq instruction

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14814

### CODE REVIEW

**Comment by 9rnsr** [comment]
I'm expecting to fail the test code in OSX...

**Comment by 9rnsr** [comment]
OK, got it.
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=1659627&isPull=true

```
 ... runnable/link14814.d           (-inline -release -g -O -fPIC)
Test failed.  The logged output:
../src/dmd -conf= -m64 -Irunnable   -odgenerated/runnable -c runnable/link14814.d
../src/dmd -conf= -m64 -Irunnable   -odgenerated/runnable -c runnable/imports/link14814a.d
../src/dmd -conf= -m64   -odgenerated/runnable -ofgenerated/runnable/link14814_0 generated/runnable/link14814.o generated/runnable/link14814a.o
ld: GOT load reloc does not point to a movq instruction in '_D7imports10link14814a4fun4FZv' from generated/runnable/link14814a.o for architecture x86_64
collect2: ld returned 1 exit status
--- errorlevel 1
```

I updated to apply my patch. Now I'm expecting all green.

**Comment by 9rnsr** [comment]
All green, ready to merge.

**Comment by MartinNowak** [comment]
Thanks, needs to go into stable though.

**Comment by 9rnsr** [comment]
See #4829.

**Comment by WalterBright** [comment]
Thanks Kenji, Martin and Timothee.

**Pull request closed without merging**
