### PR TITLE
fix Issue 16621 - [REG2.060] DMD hang in semantic3 on alias this

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by JinShil** [comment]
@wilzbach I know we're right on the cusp of a release.  Should this be in stable or master?

**Comment by WalterBright** [comment]
Since it's over a year old, master is fine.

**Comment by wilzbach** [comment]
> __TL;DR__ Safe fixes should __always__ go into stable, all the time.

https://wiki.dlang.org/DIP75#Branching_strategy

**Review by JinShil — APPROVED** [review]
Pending rebase to stable... or not... Walter's call.

**Comment by wilzbach** [comment]
> I know we're right on the cusp of a release.

FYI: 2.078.0 has already been tagged a couple of hours ago (https://github.com/dlang/dmd/releases/tag/v2.078.0).

**Review by PetarKirov — APPROVED** [review]

**Comment by ZombineDev** [comment]
Yes, we should target stable so the changes can land in the 2.078.1 release.

**Comment by wilzbach** [comment]
FYI: We can always trivial merge stable back into master. Here's the simple script I use:

```bash
#!/bin/bash
set -ueo pipefail -o xtrace
DIR=${1:-$(pwd)}
pushd $DIR
git fetch && git fetch upstream
git checkout master
git merge --ff-only upstream/master
git branch -D merge_stable
git checkout -b merge_stable
git merge upstream/stable
# <- Solve merge conflicts (if any occurred)
hub pull-request
git checkout master
popd
```

**Comment by wilzbach** [comment]
> We can always trivial merge stable back into master. 

https://github.com/dlang/dmd/pull/7598

**Pull request merged**
