### PR TITLE
[dwarf] Bump default debug version to DWARF3

### PR DESCRIPTION
**Pull request by ibuclaw**
DMD is actually emitting DWARF3 attributes in debug code today, so might as well update it here for clarity.

List of tags I found in dwarf.c that are not available in DWARF2 specification
- DW_CFA_def_cfa_sf
- DW_CFA_def_cfa_offset_sf
- DW_CFA_offset_extended_sf
- DW_AT_entry_pc
- DW_AT_ranges
- DW_ATE_imaginary_float

### CODE REVIEW

**Comment by ibuclaw** [comment]
Well that is good to know, the one and only branch which was disabled until this change is buggy!

**Comment by yebblies** [comment]
I will defer to your expertise.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by ibuclaw** [comment]
Thanks!

**Pull request merged**
