### PR TITLE
fix Issue 23789 - ImportC: __declspec(align(n))

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by ibuclaw** [comment]
Isn't this just the same as `__attribute__((align(n)))`? Perhaps it would be simpler to add `#define __declspec(N) __attribute__(N)` and avoid duplication of attribute handling in the parser.

**Comment by thewilsonator** [comment]
There are also (at least) `__declspec(dllimport)`/`__declspec(dllexport)`, I don't know if those also have `__attribute__` counterparts. But presumably we will be dealing with only one of `__declspec`/`__attribute__` at a time.

**Comment by dkorpel** [comment]
There's missing test coverage, see the codecov warnings in the diff

**Comment by maxsamukha** [comment]
This doesn't pass:

typedef struct __declspec(align(16)) _M128A {
    int x;
} M128A, *PM128A;

**Comment by WalterBright** [comment]
@thewilsonator you're right, simply changing it to __attribute__ won't work for the other __declspec's we're likely to need to support.

**Comment by WalterBright** [comment]
@maxsamukha it works when I try it. I added your example to the test case to make sure.

**Comment by maxsamukha** [comment]
It still fails here. I'm trying to figure out why.

BTW, `if (n < 1 || n & (n - 1) || ushort.max < n)` - probably should be `n > 8192`, 8192 being the maximum alignment value, according to the spec for __declspec(align).

**Comment by maxsamukha** [comment]
It fails because of https://github.com/dlang/dmd/blob/335470b337a080c80dc7724238b6041c8e4e8723/compiler/src/dmd/cparse.d#L1828. Unlike C11, MS allows __declspec(align) for typedefs.

**Comment by WalterBright** [comment]
@dkorpel fixed coverage shortcomings. It was worthwhile because I actually found a couple problems in doing so.

**Comment by ibuclaw** [comment]
> There are also (at least) `__declspec(dllimport)`/`__declspec(dllexport)`, I don't know if those also have `__attribute__` counterparts. But presumably we will be dealing with only one of `__declspec`/`__attribute__` at a time.

Yes they do have counterparts.

**Comment by ibuclaw** [comment]
> @thewilsonator you're right, simply changing it to __attribute__ won't work for the other __declspec's we're likely to need to support.

Don't be so sure about that. :-)

**Comment by WalterBright** [comment]
@ibuclaw I expect that dealing with the vagaries and underdocumented behaviors of __attribute__ and __declspec will be an ongoing headache. We'll just take it as it comes.

Dealing with the @maxsamukha 's typedef issue will need some refactoring. Hence, this PR is good enough on its own, and I can build on it with another PR.

**Review by dkorpel — APPROVED** [review]

**Comment by ibuclaw** [comment]
> @ibuclaw I expect that dealing with the vagaries and underdocumented behaviors of __attribute__ and __declspec will be an ongoing headache. We'll just take it as it comes.
> 
GCC supports all Microsoft headers (it has to for mingw IIUC), and yet it doesn't support `__declspec` directly, so there has to be a builtin define that is rewriting all declspec's during the translation phase. Sure there are possible problems in that approach - may result in collisions with predefined attributes later on, etc - though there would have been complaints if it really didn't work.

At the very least we could commonize the attribute handling, ie: parse the content inside `__declspec(common content)` and `__attribute__((common content))` in one place.  With this split brain approach, as it stands `__attribute__((align(N)))` doesn't work which ain't good.

**Pull request merged**
