### PR TITLE
Issue 14621, 14624, 14625 - Fix bugs in array operator overloading semantics

### PR DESCRIPTION
**Pull request by 9rnsr**
This is same with #4686, excepting the base branch is 'stable'.

---

[Issue 14621](https://issues.dlang.org/show_bug.cgi?id=14621) - [REG2.066] ICE: Assertion failure: 'global.gaggedErrors || global.errors' on line 752 in file 'statement.c'
[Issue 14624](https://issues.dlang.org/show_bug.cgi?id=14624) - The array operator overloading fallback is not correct
[Issue 14625](https://issues.dlang.org/show_bug.cgi?id=14625) - opIndex() doesn't work on foreach container iteration

Shorten the length of gagged semantic path, and improve `ArrayExp` as the entry point of array operator overloading.

### CODE REVIEW

**Comment by 9rnsr** [comment]
I fixed ddmd build failure in Win32/64.

**Comment by 9rnsr** [comment]
All green.

**Comment by MartinNowak** [comment]
LGTM, I'll have to merge stable into master before pulling, or I'll have to deal with too many conflicts at once.

**Comment by MartinNowak** [comment]
https://github.com/D-Programming-Language/dmd/pull/4979

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks.

**Pull request merged**
