### PR TITLE
Disable non-global template support for other compilers than DMD

### PR DESCRIPTION
**Pull request by SSoulaimane**
Until GDC and LDC catch up.

### CODE REVIEW

**Comment by 12345swordy** [comment]
CC @WalterBright 
Is this an reasonable compromise?

**Review by wilzbach — CHANGES_REQUESTED** [review]
I'm sorry, but I don't see how this would be useful as the error message for the tests will be different for gdc and LDC, so they have to patch things anyhow. Also, LDC has already done this and released a beta.

**Comment by ibuclaw** [comment]
> Also, LDC has already done this and released a beta.

Citation?

**Comment by wilzbach** [comment]
> > Also, LDC has already done this and released a beta.
> 
> Citation?

https://github.com/ldc-developers/ldc/pull/3093#issuecomment-506824208

With this. I was referring to the sentence before (_this_ PR and its disabling of the feature).

**Comment by ibuclaw** [comment]
@wilzbach - Thanks for clarifying.  'This' was rather ambiguous in your context. :-)

**Comment by Geod24** [comment]
The feature has been deprecated in v2.096.0: https://dlang.org/changelog/2.096.0.html#deprecate_dualcontext

**Pull request closed without merging**
