### PR TITLE
fix Issue 14281 - duplicate .debug_info entries for arrays, delegates and aa's

### PR DESCRIPTION
**Pull request by MartinNowak**
- the duplicates exist because DW_AT_sibling pointers
  are unique for each entry and thus the hashing cache
  doesn't work
- as DW_AT_sibling hardly provides a benefit when
  skipping over a few bytes, it's better to remove it
- also shrinks debug info by a few percent

[Issue 14281 – duplicate .debug_info entries for arrays, delegates and aa's](https://issues.dlang.org/show_bug.cgi?id=14281)

### CODE REVIEW

**Comment by MartinNowak** [comment]
[Issue 14281 – duplicate .debug_info entries for arrays, delegates and aa's](https://issues.dlang.org/show_bug.cgi?id=14281)

**Comment by MartinNowak** [comment]
The .debug_info for [dub-registry](https://github.com/D-Programming-Language/dub-registry) shrinked from 13.7MB down to 11.9MB.

**Comment by MartinNowak** [comment]
LLVM omits them as well [[¹]][1] and GCC at least considered it [[²]][2].

[1]: http://llvm.org/devmtg/2013-11/slides/Walker-DWARF.pdf "Page 6 - Comparison LLVM/GCC DWARF"
[2]: https://gcc.gnu.org/ml/gcc-patches/2011-10/msg00992.html "Drop size + performance overhead of DW_AT_sibling"

**Comment by MartinNowak** [comment]
Rebase, and ready to go.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
