### PR TITLE
fix Issue 20460 - [OSX] DMD writes the same address everywhere in DWA…

### PR DESCRIPTION
**Pull request by WalterBright**
…RF debug infos

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
test?

**Comment by thewilsonator** [comment]
also please target stable.

**Comment by WalterBright** [comment]
We don't really have tests for debug output. Anyhow, I'd like to see @Geod24 verify that it works properly in his debugger.

**Comment by thewilsonator** [comment]
We do, there are shell script GDB tests. I know, cos' its a PITA to try to debug them.

**Comment by WalterBright** [comment]
Yes, one can write a script to dwarfdump the output and compare with a known good one. The trouble, though, is the debug info contains code offsets, which make it strongly sensitive to any other changes in the code generation. This leads to lots of aggravation and maintenance. I tried these kinds of tests in the past, and always would up giving up on them.

Another factor to consider is this bug make the gdb symbolic debug info essentially useless for OSX64, which is what the bug report is about. This change is not likely to make that worse :-/

**Comment by Geod24** [comment]
I can write a test for it that doesn't depend on GDB. But tomorrow :)

**Comment by WalterBright** [comment]
@Geod24 can you give it a smoke test tonight and just see if it works for you?

**Comment by ibuclaw** [comment]
> We do, there are shell script GDB tests. I know, cos' its a PITA to try to debug them.

They also all fail with a newer version of gdb.

**Comment by Geod24** [comment]
Unfortunately that doesn't fix the bug. Given how big that issue is, it's actually quite easy to reproduce, but you need two modules at least.

```D
module test20460a;

import test20460b;

void main ()
{
    foo(); // L7
}

int bar ()
{
    throw new Exception("Hello"); // L12
}
```

```D
module test20460b;

import test20460a;

void foo ()
{
    // Some comment so that the call is at L8
    bar();
}
```

Currently, if I try to compile and run this (with upstream DMD):
```shell
% dmd --version
DMD64 D Compiler v2.096.0

Copyright (C) 1999-2021 by The D Language Foundation, All Rights Reserved written by Walter Bright
% dmd -g test20460a.d test20460b.d
% ./test20460a
object.Exception@test20460a.d(12): Hello
----------------
test20460a.d:12 int test20460a.bar() [0x108407227]
test20460a.d:13 void test20460b.foo() [0x108407238]
test20460a.d:7 _Dmain [0x1084071ac]
```

Notice that multiple things are wrong:
- Only `test20460*a*.d` shows up in the trace, but the second frame is in `test20460*b*.d`;
- Except for the first (the one in `main`), line number are wrong;

**Comment by WalterBright** [comment]
Does it fix the specific bug in the bugzilla report?

**Comment by WalterBright** [comment]
I.e. the high and low pc for a function?

**Comment by Geod24** [comment]
It's better. I can't be 100% sure if it's correct without investing some time into reading the specs again, but the ranges make sense.

**Comment by WalterBright** [comment]
All right. Then we'll pull this and do a new bug report for the new case you posted.

**Comment by WalterBright** [comment]
https://issues.dlang.org/show_bug.cgi?id=21864

**Comment by Geod24** [comment]
Thanks!

**Pull request merged**
