### PR TITLE
Add attributes to ctfloat.d

### PR DESCRIPTION
**Pull request by jacob-carlborg**
I think it looks better with the attributes first for the single line functions.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
```
dmd/root/ctfloat.d:79:70: error: pure function 'dmd.root.ctfloat.CTFloat.tan' cannot call impure function 'core.stdc.math.tanl'
         pure static real_t tan(real_t x) { return core.stdc.math.tanl(x); }
                                                                      ^
dmd/root/ctfloat.d:102:74: error: pure function 'dmd.root.ctfloat.CTFloat.round' cannot call impure function 'core.stdc.math.roundl'
         pure static real_t round(real_t x) { return core.stdc.math.roundl(x); }
                                                                          ^
dmd/root/ctfloat.d:103:73: error: pure function 'dmd.root.ctfloat.CTFloat.floor' cannot call impure function 'core.stdc.math.floor'
         pure static real_t floor(real_t x) { return core.stdc.math.floor(x); }
                                                                         ^
dmd/root/ctfloat.d:104:71: error: pure function 'dmd.root.ctfloat.CTFloat.ceil' cannot call impure function 'core.stdc.math.ceil'
         pure static real_t ceil(real_t x) { return core.stdc.math.ceil(x); }
                                                                       ^
dmd/root/ctfloat.d:105:73: error: pure function 'dmd.root.ctfloat.CTFloat.trunc' cannot call impure function 'core.stdc.math.trunc'
         pure static real_t trunc(real_t x) { return core.stdc.math.trunc(x); }
                                                                         ^
dmd/root/ctfloat.d:113:90: error: pure function 'dmd.root.ctfloat.CTFloat.copysign' cannot call impure function 'core.stdc.math.copysignl'
         pure static real_t copysign(real_t x, real_t s) { return core.stdc.math.copysignl(x, s); }
```

Doesn't look so good.

**Comment by jacob-carlborg** [comment]
> Doesn't look so good.

I'm guessing GCC is using an older version of druntime.

**Comment by wilzbach** [comment]
> > Doesn't look so good.
> 
> I'm guessing GCC is using an older version of druntime.

Yup, I think it's ~ 2.076.

**Comment by jacob-carlborg** [comment]
buildkite failure is unrelated?

**Comment by thewilsonator** [comment]
I think so.

**Comment by jacob-carlborg** [comment]
@thewilsonator @wilzbach this is passing now.

**Review by wilzbach — APPROVED** [review]

**Pull request merged**
