### PR TITLE
fix Issue 20981 - Segfault for inlined __simd_sto

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
ping @MoonlightSentinel

**Comment by MoonlightSentinel** [comment]
Nice. Can't really comment on the fix but merging this into #11236 makes it pass the tests locally.

**Comment by UplinkCoder** [comment]
@WalterBright 

So was it the case, that the in-liner enabled a further optimization, which was done wrongly?

**Comment by WalterBright** [comment]
Blocking https://github.com/dlang/dmd/pull/11236

**Comment by 12345swordy** [comment]
Who needs to review this?

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
