### PR TITLE
[DDOC] Fix year in test

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by wilzbach** [comment]
Can't we fix this properly and filter it out or replace it on the fly?

**Comment by thewilsonator** [comment]
I'd love to have a more resilient solution, but I'd more rather have this thing working _now_.

**Comment by thewilsonator** [comment]
Turns out that machine was already there, it just wasn't being used for some reason.

**Comment by thewilsonator** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
This should have targeted stable and then being back-merged properly with `merge_stable`

**Pull request merged**
