### PR TITLE
[refactor] Remove constructors for classes that are defined in D, since they can't be called

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by yebblies** [comment]
All green

**Comment by mathias-lang-sociomantic** [comment]
LGTM

**Comment by WalterBright** [comment]
It's always failed the Windows test. Hmm.

**Comment by yebblies** [comment]
Probably a struct becoming POD with the ctor removed - will investigate.

**Comment by WalterBright** [comment]
Probably easiest to do a binary search commenting them out till the culprit is found.

**Comment by yebblies** [comment]
Works fine without structs, ready to go.

**Comment by yebblies** [comment]
Thanks!

**Pull request merged**
