### PR TITLE
Assume that monitor functions have the nothrow attribute.

### PR DESCRIPTION
**Pull request by FeepingCreature**
Depends on https://github.com/dlang/druntime/pull/2105 and communicates the change to DMD.

### CODE REVIEW

**Comment by FeepingCreature** [comment]
Er, hang on, no. DRuntime depends on *this* change.

**Comment by wilzbach** [comment]
Re this Jenkins failure:

```
../../.dub/packages/libasync-0.8.3/libasync/source/libasync/dns.d(120,3): Warning: statement is not reachable
../../.dub/packages/libasync-0.8.3/libasync/source/libasync/file.d(73,3): Warning: statement is not reachable
dmd failed with exit code 1.
```

Could be something permanent. I restarted.

**Comment by mathias-lang-sociomantic** [comment]
Last time we tried this it blew up in Vibe.d, big time.
I would really like to have @s-ludwig 's word before we merge anything.

**Comment by mathias-lang-sociomantic** [comment]
Also, little to no rationale, and no changelog entry. This is a big change, please treat it as such.
Here's what happen last time it landed (v2.067): https://github.com/vibe-d/vibe.d/pull/972

**Comment by FeepingCreature** [comment]
I didn't realize this would be controversial, or actually that people were using non-nothrow monitors at all.

If this is an issue, the more annoyingly complex solution would be maybe a sub-interface of Monitor that has nothrow? So that the stock monitor could inherit from it, and at least synchronized (this) would no longer violate nothrow.

**Comment by wilzbach** [comment]
> Could be something permanent. I restarted.

Yes, looks like the libasync failure is genuine and introduced by this PR:

image

**Comment by FeepingCreature** [comment]
In that case, I'd probably retract this pr and file a bug for it.

It's kind of ridiculous that D ostensibly has all these nice features like nothrow, but you can't use synchronized(this) with it even though the default monitor evidently does not throw. You end up deciding to use a feature, then a few days later you have to undo the feature because it doesn't work with some other feature and nobody gave any thought to the combination.

**Comment by FeepingCreature** [comment]
Oh, it seems it was filed in 2015...

https://issues.dlang.org/show_bug.cgi?id=11216

**Comment by s-ludwig** [comment]
vibe.d should be fine. After the last attempt, I split up the `TaskMutex` types into one that can throw and another one that is `nothrow`. Only the latter derives from `Mutex` to be able to act as a replacement.

**Comment by FeepingCreature** [comment]
I don't know DMD. Is there any way to ensure that Monitor has nothrow on lock/unlock before setting those attributes on the _d_monitorenter/leave externs we generate?

**Review by WalterBright — APPROVED** [review]

**Comment by s-ludwig** [comment]
The failure appears to be directly in libasync, which is optionally used by vibe.d. All other configurations are fine, though, and the fix should be trivial.

**Comment by FeepingCreature** [comment]
I am increasingly not confident in this pr. The proper solution would really be to find some way to ensure that the monitor lock/unlock functions actually do have nothrow. Is that possible somehow? Otherwise I guess I'll reopen the associated druntime pr.

**Comment by ibuclaw** [comment]
The path of least resistance may be to first deprecate if you are able to detect the wrong use case before we add nothrow.

**Comment by thewilsonator** [comment]
This sound like something that should be solved by proto-object. Closing

**Pull request closed without merging**
