### PR TITLE
Fix Issue 20419 - is(missing == module/package) results in unknown id…

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
…entifier.

is(missing == module) and is(missing == package) raised an error for missing identifiers, violating the [language specification](https://dlang.org/spec/expression.html#is_expression) wich only requires the identifier to be syntactically valid.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
Shouldn't this have gone to stable ?

**Comment by MoonlightSentinel** [comment]
> Shouldn't this have gone to stable ?

Why, isn't stable reserved for regressions?
(IMO this does not qualify as a regression fix because these traits were introduced with this flaw)

**Comment by Geod24** [comment]
It's also used for non-disruptive bugfixes where there is a clear benefit to the bugfix.
IMO this PR is a textbook example of that :)

**Comment by MoonlightSentinel** [comment]
Okay, I'll try to remember that for my future PRs

**Pull request merged**
