### PR TITLE
Revert "deprecate Object.factory"

### PR DESCRIPTION
**Pull request by dkorpel**
This reverts commit 5600cfb42f34e318289102ddeba8b2fdb75deb97.

See https://github.com/dlang/dmd/pull/14681#issuecomment-1345407242 and https://github.com/dlang/dmd/pull/14681#issuecomment-1427048269

### CODE REVIEW

**Comment by Geod24** [comment]
@ibuclaw : Stable or master ?

**Comment by ibuclaw** [comment]
If it's a v2.102 regression, then stable.

**Comment by ibuclaw** [comment]
Idiot question (probably for @WalterBright) - How is `__traits(getModuleClasses [, mod])` a suitable replacement for `Object.factory`?  The later searches all (possibly unknown) modules loaded up at run-time.  The former only searches one (statically known) module at a time.

**Comment by ibuclaw** [comment]
@Geod24 @dkorpel any decision here on whether it's critical enough to revert in the current release?

**Comment by CyberShadow** [comment]
Can we put the class pointers into a separate linker section, which is only pulled in if anything in the program uses `Object.factory`?

**Comment by dkorpel** [comment]
> any decision here on whether it's critical enough to revert in the current release?

I don't know, I just know it was deprecated too quickly.

**Comment by Geod24** [comment]
Agreed.

**Comment by ibuclaw** [comment]
Then, stable? So people aren't stuck with old compiler for the next couple months?

**Pull request merged**
