### PR TITLE
fix Issue 24010 - Destructor called before end of scope for tuples

### PR DESCRIPTION
**Pull request by WalterBright**
I fixed this in 3 separate places, each breaking some unexpected aspect. Finally found the right place to put it. We'll see if it behaves.

### CODE REVIEW

**Comment by WalterBright** [comment]
This one is too potentially disruptive to push to stable.

**Comment by WalterBright** [comment]
Oh, another chicken-and-egg ordering problem. It seems I can't change the order in which VarDeclarations are semantic'd.

**Comment by BorisCarvajal** [comment]
Your solution is the same as mine #15351

**Comment by WalterBright** [comment]
@BorisCarvajal wow! But there are some differences:

1. Mine rewrites the VarExp into a DeclarationExp. Maybe that isn't necessary.
2. Yours allocates an array `a` unnecessarily
3. Mine tests that the destructors occur in the right order
4. Mine inserts the test into runnable/sdtor.d, which makes the test suite run a bit faster than if it was a separate file

Well done!

Other than that, they are surprisingly similar.

**Comment by WalterBright** [comment]
I like your foreachVar use better.

**Comment by BorisCarvajal** [comment]
>     1. Mine rewrites the VarExp into a DeclarationExp. Maybe that isn't necessary.
`toStatement` does that for me too.
>     2. Yours allocates an array `a` unnecessarily
  Yep, I was thinking of changing it but I'm not totally sure if individual inserts are less expensive (`CompoundStatement` could be really big). I'm missing reserving the array size though.
>     3. Mine tests that the destructors occur in the right order
>     4. Mine inserts the test into runnable/sdtor.d, which makes the test suite run a bit faster than if it was a separate file
Yes my tests are just copy paste.

**Comment by RazvanN7** [comment]
So, which one do we keep? @WalterBright , since @BorisCarvajal was the first one to make the PR, would you mind closing this and giving your feedback on #15351 ?

**Comment by WalterBright** [comment]
@BorisCarvajal did it first, and gets dibs!

**Comment by WalterBright** [comment]
I'll close this after #15351 gets merged

**Pull request closed without merging**
