### PR TITLE
use xmalloc instead of malloc

### PR DESCRIPTION
**Pull request by UplinkCoder**
use xmalloc instead of malloc;
This makes it easier to use custom allocation strategies

### CODE REVIEW

**Comment by WalterBright** [comment]
These calls to malloc() have corresponding free()s. Allocating with one scheme and freeing with another will result in memory corruption.

**Comment by yebblies** [comment]
Yes, both of the malloc/free pair should be changed to xmalloc/xfree

**Comment by UplinkCoder** [comment]
Opps well that was embarrassing,

**Comment by UplinkCoder** [comment]
I'll fix it.

**Comment by WalterBright** [comment]
Also, in those cases I deliberately used malloc/free because the lifetime was explicitly known, and xmalloc/xfree is designed to be replaceable with a garbage collector. Replacing the calls with xmalloc/xfree will then make things worse.

**Comment by yebblies** [comment]
Knowing the lifetime isn't enough, they also can't contain pointers to GC memory.  It's easier to get right if we just use xmalloc everywhere.

**Comment by WalterBright** [comment]
> they also can't contain pointers to GC memory

And they don't. These 3 cases are simple and easy to get right.

> It's easier to get right if we just use xmalloc everywhere.

It's also easier and less bug prone to use a garbage collector. But it consumes 3x more memory and is slower to use in DMD.

**Comment by UplinkCoder** [comment]
Maybe another indirection then ?
the main point of not in using malloc is to avoid overhead for  small allocation such as these.

**Comment by UplinkCoder** [comment]
Memory should be grouped by lifetime, maybe we can add allocation primitives for these ?

**Comment by yebblies** [comment]
> And they don't.

Check again.

> It's also easier and less bug prone to use a garbage collector. But it consumes 3x more memory and is slower to use in DMD.

Are you claiming that using xmalloc uses 3x more memory than malloc?  Otherwise it seems you've wandered off point.

**Comment by UplinkCoder** [comment]
most things in the compiler to for all intends and purposes have infinite lifetime. 
Because it's a one-shot process. 
There are two exceptions not-yet-lowerd-constructs  and CTFE.
for thoose we needs to provide an alternative method of allocation. 
Since they are going to leak.

**Comment by WalterBright** [comment]
> the main point of not in using malloc is to avoid overhead for small allocation such as these. malloc is not a tool for speed.

xmalloc currently is a shell around malloc.

**Comment by yebblies** [comment]
> It does if xmalloc() is set to use the GC, which is what it was designed to do.

Unless the GC is enabled, using xmalloc does not incur this cost.  If the GC is enabled, then we will have other things to worry about.  Direct use of malloc can obviously be done in safe and correct ways, but that doesn't mean it will be.  Going through xmalloc gives an easy way to switch the GC on without having to worry.

Actually, we should replace as many of these as we can with `Array` so this becomes a non-issue.

**Comment by WalterBright** [comment]
> Unless the GC is enabled, using xmalloc does not incur this cost.

What I've said twice now. :-) The point is, xmalloc() is there so GC can be swapped in and out easily to see how it works.

> Direct use of malloc can obviously be done in safe and correct ways, but that doesn't mean it will be.

Doesn't mean it won't be, either. Memory consumption is a problem in dmd. The obvious cases where it can be free'd should be taken advantage of.

> Actually, we should replace as many of these as we can with  Array  so this becomes a non-issue.

A couple of them should default to stack arrays, and overflow to malloc. I used this in Warp a lot, and it's very effective.

**Comment by UplinkCoder** [comment]
I think the compiler is not place where GC should be used.
It's will mostly scan stuff it cannot free ever.

**Comment by UplinkCoder** [comment]
interestingly even with the GC turned on, CTFE still leaks memory like there is no tomarrow. 
Even with my super-unsave circuar-buffer it still leaked memory.

**Pull request closed without merging**
