### PR TITLE
add rules to convert the current git tree/index

### PR DESCRIPTION
**Pull request by MartinNowak**
`convert_tree` simply converts the working dir (made for tree-filter)
`convert_index` uses `git rm` and `git add` to prepare a conversion commit.

### CODE REVIEW

**Comment by MartinNowak** [comment]
```sh
# How to convert a PR against CDMD?
# make sure your working dir is clean
git status && git clean -dn
# rebase onto last CDMD state, resolve merge conflicts as usual
git rebase --onto lastCDMD lastCDMD myBranch
# convert all commits using magicport
git filter-branch -f --tree-filter 'make -C src -f posix.mak convert_tree' lastCDMD..myBranch
# cleanup the working tree (still contains .c files)
git reset --hard
# rebase your new DDMD branch onto the first DDMD commit, -X theirs keeps all your changes
git rebase -s recursive -X theirs --onto firstDDMD firstDDMD myBranch
# rebase your branch onto master
git rebase --onto master firstDDMD myBranch
# update your PR
git push -f origin myBranch
```

**Comment by MartinNowak** [comment]
The LastCDMD and FirstDDMD commit are still to be determined.
I'd say we should tag them to make the above simpler.

**Comment by MartinNowak** [comment]
I didn't test the windows rules, hope they work.

**Comment by yebblies** [comment]
https://gist.github.com/yebblies/43555390d29624232ada

Yeah, so you've lost me at filter-branch.  The gitignore changes do not need to be done now.

**Comment by MartinNowak** [comment]
> Yeah, so you've lost me at filter-branch.

foreach (commit)
    checkout sources into tmpdir
    run command
    commit missing/updated/added files (a.k.a. just what we need)

> The gitignore changes do not need to be done now.

It's rather confusing for everyone who will have to rebase their converted code onto this.

**Comment by yebblies** [comment]
> It's rather confusing for everyone who will have to rebase their converted code onto this.

Just turn `git add $(GENSRC) objc.d`
into
`git add -f $(GENSRC) objc.d`

And it will work as expected, so the changes are not necessary.

This pull is missing the makefile updates from https://gist.github.com/yebblies/43555390d29624232ada

**Comment by MartinNowak** [comment]
> This pull is missing the makefile updates from https://gist.github.com/yebblies/43555390d29624232ada

This should be done __after__ the conversion.

> And it will work as expected, so the changes are not necessary.

If I have to make another PR for this trivial piece I'll have to wait another hour and will rather go to bed.

**Comment by yebblies** [comment]
> This should be done after the conversion.

Why?

**Comment by MartinNowak** [comment]
> Why?

Because this is still CDMD and you want to build the C compiler.
The next PR will have the converted sources and updated makefiles.
Then we can tag the merge commit of this PR as {LASTCDMD} and the merge commit of the next PR as {FIRSTDDMD}.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Damn it, you didn't delete root/{async,checkedint}.h, not this will happen in the filter-branch step, and needs to be resolved when rebasing onto upstream/master.

**Comment by MartinNowak** [comment]
I updated the tree-filter script to account for that.

**Pull request merged**
