### PR TITLE
fix 14891: fix profilgc to stdout not working

### PR DESCRIPTION
**Pull request by WebFreak001**
Improves error message for diagnostics and tests stdout functionality

### CODE REVIEW

**Comment by RazvanN7** [comment]
@WebFreak001 Thanks for the PR. Could you please add a commit containing "Fix Issue 17294 [...]" so that the bot picks up the bugzilla issue?

**Comment by WebFreak001** [comment]
oh sorry, the bugzilla interface bamboozled me there. Meant to write [14891](https://issues.dlang.org/show_bug.cgi?id=14891)

**Comment by RazvanN7** [comment]
No worries. Please a commit that contains "Fix Issue 14891" in the commit message so that the bot picks it up. For example: "Fix Issue 14891 - fix profilegc to stdout not working" should be fine.

**Comment by WebFreak001** [comment]
done (the exact issue description has been very dated / already fixed, but the unknown fix introduced a regression which is fixed here)

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
