### PR TITLE
Remove C++ linkage from CTFE functions

### PR DESCRIPTION
**Pull request by ibuclaw**
Sizeable exodus of what is an internal implementation detail.

@Geod24 an example of what I was referring to. :-)

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]
LGTM in principle, although it would be nice of one of the LDC dev could take a look at this.

**Comment by ZombineDev** [comment]
@kinke what do you think?

**Comment by kinke** [comment]
I guess this is fine for us as well; we have a bunch of additional CTFE builtins in `dmd.builtin`, but that seems unaffected.

**Comment by Geod24** [comment]
@ibuclaw: Feel free to self merge once you have fixed the Windows only failure.

**Comment by ibuclaw** [comment]
@kinke - maybe I should have clarified that these are specific to the CTFE engine.  It's implementation details should not concern you.

**Comment by ibuclaw** [comment]
@Geod24 - Win-what?

**Comment by Geod24** [comment]
@ibuclaw Are you done closing and opening the door ?

**Comment by ibuclaw** [comment]
@Geod24 - Win32 machine seems to have lack of available temporary files. :-)

**Comment by Geod24** [comment]
In this case you can just deprecate the test on the autotester.
AFAIK Open/close is only useful for AppVeyor and semaphoreci if you want to re-trigger a test without pushing (and loosing the auto-tester result).

**Comment by ZombineDev** [comment]
Recently I've had to deprecate the test results on the Win32 power machine on a few other PRs for the same reason - failure to create a temp file during the phobos tests, so it's definitely not a problem with this PR.

@braddr could you take a look if this is something that could be fixed on your side?

**Pull request merged**
