### PR TITLE
fix compilation for Win64

### PR DESCRIPTION
**Pull request by rainers**
Trying to build a Win64 executable of ddmd yields:

```
src\root\file.d(198): Error: function core.sys.windows.windows.WriteFile (void* hFile, const(void*) lpBuffer, uint nNumberOfBytesToWrite, uint* lpNumberOfBytesWritten, OVERLAPPED* lpOverlapped) is not callable using argument types (void*, ubyte*, ulong, uint*, typeof(null))
src\cppmangle.d(1622): Error: function ddmd.root.outbuffer.OutBuffer.writeByte (uint b) is not callable using argument types (ulong)
src\cppmangle.d(1718): Error: function ddmd.root.outbuffer.OutBuffer.writeByte (uint b) is not callable using argument types (ulong)
src\link.d(713): Error: undefined identifier 'DWORD'
src\link.d(713): Error: undefined identifier 'GetShortPathName'
src\link.d(713): Error: variable len is shadowing variable ddmd.link.executecmd.len
```

This PR fixes the compilation errors, but there are also link problems due to bad mangling. Not sure how these can be fixed considering a fixed HOST_DC. Send patches to the stable branch?

### CODE REVIEW

**Comment by yebblies** [comment]
> Not sure how these can be fixed considering a fixed HOST_DC.

It's ok to have a later minimum version for win64, since it's not one of our officially supported (ie autotester and releases) configurations.

The other option is to change signatures to work around them, which may or may not be possible depending on how frequent the mis-mangled types are.

**Comment by MartinNowak** [comment]
> It's ok to have a later minimum version for win64, since it's not one of our officially supported (ie autotester and releases) configurations.

It would be quite a nice feat to release a 64-bit dmd.

**Comment by yebblies** [comment]
> It would be quite a nice feat to release a 64-bit dmd.

Sure.  Is that likely to happen anytime soon?

**Comment by MartinNowak** [comment]
> Sure. Is that likely to happen anytime soon?

Version | Date
---------|----------
Beta 2.068.1 | 2015-08-30
Release 2.068.1 | 2015-09-06
Branch+Beta 2.069 | __2015-09-20__
Release 2.069.0 | 2015-10-04

**Comment by yebblies** [comment]
Are you saying the plan is to do win64 binary releases with 2.069?

**Comment by MartinNowak** [comment]
> Are you saying the plan is to do win64 binary releases with 2.069?

Nope, I didn't plan for that, but if it's within reach, why not?

**Comment by rainers** [comment]
> Nope, I didn't plan for that, but if it's within reach, why not?

It was there ready to be built and distributed for a couple of years now.

**Pull request merged**
