### PR TITLE
[dmd-cxx] Remove async read interface

### PR DESCRIPTION
**Pull request by ibuclaw**
Unused by gdc, not present in dmd/master.

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by PetarKirov** [comment]
So much for the bug fixes I made to this code a quite while ago :D

**Comment by Geod24** [comment]
Well, this code hasn't caused any bugs since your bug fix, so I'd count it as a win :D

**Comment by PetarKirov** [comment]
I wanted to completely rewrite it back then, so now that the code is removed, the diff would be smaller :D

**Comment by ibuclaw** [comment]
@PetarKirov - I don't ever recall it being faster than reading files synchronously (infact always slower).  Maybe if I was compiling code off floppy disks...

**Pull request merged**
