### PR TITLE
fixes issue 19342 (duplicate of #8891)

### PR DESCRIPTION
**Pull request by RichardPalme**

### CODE REVIEW

**Comment by RichardPalme** [comment]
I reverted a change introduced two days ago in Merge pull request #8879 from WalterBright/prep-elfobj.c
which is the cause of Issue #19342: https://issues.dlang.org/show_bug.cgi?id=19342

**Comment by stefan-koch-sociomantic** [comment]
@WalterBright @jacob-carlborg LGTM

**Comment by BBasile** [comment]
#8891

**Comment by RichardPalme** [comment]
@BBasile oh I didn't see your exact same pull request. For the record, the problem is not with gcc 8.2.1 specifically but with the recent change to elfobj.c, i.e. every gcc version would give a warning about missing return statements.

**Comment by BBasile** [comment]
Actually we don't target the same branch. Maybe both can be merged since you've written the same fix.

**Review by jacob-carlborg — DISMISSED** [review]
I think this is the wrong solution. The DMD backend is using a custom `assert` defined in `tassert.h`. It should be defined so that the compiler recognized that the function/macro will never return, which then should not require a return statement. Have a look at the implementation for Clang:

https://github.com/dlang/dmd/blob/4a627b883c4185f74d13816d8d84c4b1c8daf38a/src/dmd/backend/tassert.h#L23-L31

**Comment by WalterBright** [comment]
It's being converted to D as soon as the extant PRs for it are approved, so there's no need to worry about making this perfect.

**Review by WalterBright — APPROVED** [review]

**Comment by wilzbach** [comment]
Closing in favor of #8891 as that one does exactly the same, but was submitted earlier.

**Pull request closed without merging**
