### PR TITLE
fix Issues 20596, 20967 - [REG2.086] Error on missed stack allocation for clo…

### PR DESCRIPTION
**Pull request by WalterBright**
…sure for template

Although a regression fix, it is an old issue and is potentially disruptive so it shouldn't go into stable.
I'll add test cases if it passes.

### CODE REVIEW

**Comment by WalterBright** [comment]
buildkite failure looks irrelevant.

**Comment by thewilsonator** [comment]
> it is an old issue 

No its not, its from February.

> potentially disruptive

Its a rejects valid, how is that possibly disruptive?

**Comment by WalterBright** [comment]
> No its not, its from February.

The regression was introduced 2 years ago. The bug report is recent.

> Its a rejects valid, how is that possibly disruptive?

Because it changes whether a closure uses the GC or not. This can silently break code that was tested and ran perfectly fine before. Pre-dip1000 code was a bit unreliable with this.

**Comment by WalterBright** [comment]
This also fixes https://issues.dlang.org/show_bug.cgi?id=20597

**Comment by MoonlightSentinel** [comment]
> This also fixes https://issues.dlang.org/show_bug.cgi?id=20597

Please add that bugzilla id to the commit message

**Comment by WalterBright** [comment]
I don't know how to do that.

**Comment by thewilsonator** [comment]
```
git reset HEAD~1
git add src/dmd/dsymbolsem.d src/dmd/escape.d src/dmd/expressionsem.d test/compilable/test20596.d
git commit -m "Fix issues 20596,20597 ... "
```

**Comment by MoonlightSentinel** [comment]
> ```
> git reset HEAD~1
> git add src/dmd/dsymbolsem.d src/dmd/escape.d src/dmd/expressionsem.d test/compilable/test20596.d
> git commit -m "Fix issues 20596,20597 ... "
> ```

Even simpler:
```
git commit --amend
```

**Comment by WalterBright** [comment]
Thanks! Done.

**Review by atilaneves — APPROVED** [review]

**Comment by JohanEngelen** [comment]
I reopened https://issues.dlang.org/show_bug.cgi?id=20596 because it is not complete fixed.

**Pull request merged**
