### PR TITLE
Move visitors into a package

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]
Walter said he was okay with this at DConf right?

**Comment by thewilsonator** [comment]
I did twist his arm on that, yes.

**Comment by RazvanN7** [comment]
This has broken dmd as a lib when built with dub: https://github.com/Dlang-UPB/D-scanner/pull/145 . Please, don't merge changes like this one so hastily. Now that people are using dmd-as-a-lib this will break their code.

The dub.sdl file needs to be updated to take into account the new change.

**Comment by thewilsonator** [comment]
I thought building DMD with DUB was taste by CI, how did it fail to catch this?

**Comment by RazvanN7** [comment]
The project is tested that it builds, but there aren't tests for each individual file. That's ok for files that are used inside the compiler, but not ok for files that are meant to be used only by library users (such as the parse time transitive visitor). Ideally, we would add tests for all such files/functions that are both built with dub and the makefile.

**Comment by RazvanN7** [comment]
> I'm afraid the latter is a fact of life dealing with DMD

Yeah, this is a bad problem. This might make it difficult for people wanting to use dmdlib.

**Pull request merged**
