### PR TITLE
start killing 16 bit codegen

### PR DESCRIPTION
**Pull request by benjones**
16 bit code is (as far as I can tell) not possible to generate:
From backconfig.d , I didn't see any places where a pointer could be set to 2 bytes long

```d
  if (model == 64)
  {
      util_set64(cfg.exe);
      type_init();
      cod3_set64();
  }
  else
  {
      util_set32(cfg.exe);
      type_init();
      cod3_set32();
  }
```

### CODE REVIEW

**Comment by benjones** [comment]
Build failures are related to this: https://forum.dlang.org/post/jcbcpaugvzsizwmsyffp@forum.dlang.org  The old version had a goto that jumped over a labelled variable declaration but that label is no longer used here

**Review by thewilsonator — APPROVED** [review]
Looks good to me. Mind the CI failures though. Might be easier to do a series of smaller PRs.

**Comment by benjones** [comment]
The existing code was making use of this bug (https://issues.dlang.org/show_bug.cgi?id=24534) and deleting a label that became unused revealed it.  I've been looking into fixing that first, but will come back to working around it if it takes too much longer

**Comment by thewilsonator** [comment]
I would be good to get the most of this PR working and split out what doesn't work into a separate PR. That will allow the progress that can be done to get done and it will hopefully make it more apparent what the actual use of the bug is. 

Note that since DMD relies on the bug, fixing it will likely require a deprecation before an error so that we can still bootstrap properly.

**Comment by benjones** [comment]
@WalterBright is there something along these lines that would be helpful for me to do?  I can't imagine any of these codepaths have been run in ages

**Pull request closed without merging**
