### PR TITLE
Turn deprecation into error for privately imported symbols inside aggregate declarations

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by wilzbach** [comment]
Needs a short changelog entry, s.t. it's easier to for users to find potential problems when upgrading and knowing in which version the change was introduced.

**Comment by RazvanN7** [comment]
Done.

**Comment by thewilsonator** [comment]
It strikes again!
```
Searching for trailing whitespace
Searching for tabs
./changelog/pending.dd:91:	import b;
./changelog/pending.dd:92:	AST.Foobar t;        // triggered a deprecation, but will now trigger an error
./changelog/pending.dd:93:	AST.Foobar.smeth();  // error
./changelog/pending.dd:94:	AST.fun();           // error
```

**Comment by jacob-carlborg** [comment]
I'm skeptical to this until `__traits` can access private symbols.

**Comment by RazvanN7** [comment]
@jacob-carlborg The PR that enables `__traits` to access private symbols should take care this case regardless if it is a deprecation or an error. I don't see that as a blocker for the merge of this PR.

**Comment by jacob-carlborg** [comment]
> jacob-carlborg The PR that enables __traits to access private symbols should take care of this case regardless if it is a deprecation or an error. I don't see that as a blocker for the merge of this PR.

@RazvanN7 because a compilation error will stop the compilation while a deprecation will not.

**Comment by RazvanN7** [comment]
>@RazvanN7 because a compilation error will stop the compilation while a deprecation will not.

And of course, this case should be taken care of in the eventuality of an error.

**Pull request merged**
