### PR TITLE
Dub: add ability to pass version identifiers when initializing frontend

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]
Probably a good idea to introduce a configuration struct for these settings soon.

**Comment by jacob-carlborg** [comment]
> Probably a good idea to introduce a configuration struct for these settings soon.

Yeah, possibly. Let's see where we end up and then decide if it makes sense.

**Comment by thewilsonator** [comment]
Needs a rebase.

**Comment by jacob-carlborg** [comment]
> Needs a rebase.

Done.

**Pull request merged**
