### PR TITLE
[REG2.067a] Issue 14198 - Link failure with Variant

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14198

After this fix, we can remove the workaround in Phobos.

### CODE REVIEW

**Comment by WalterBright** [comment]
The "workaround" stays in Phobos. The original code did memory allocation to implement `to!string(bool)`, which is absurd.

**Comment by 9rnsr** [comment]
The root issue is in `std.array.Appender`. It always allocate memory. `std.format.formatValue` is designed not to allocate memory if possible.

**Comment by WalterBright** [comment]
Thanks for finding & fixing the compiler bug.

**Comment by MartinNowak** [comment]
@9rnsr you think we should get this into 2.067 or will the Phobos workaround suffice?
It changes the internal order of template semantics, so I'm hesitating a little as I don't want to risk a last minute regression.

**Comment by 9rnsr** [comment]
@MartinNowak This fix should go into 2.067. There was not only a link-failure issue, but also was incorrect attribute inference problem. Following code does not compile with 2.067-beta2.

```d
import std.conv;
void main() pure @safe { auto s = to!string(true); }
```

**Comment by CyberShadow** [comment]
This pull request seems to have fixed a compiler crash (and Phobos-introduced regression):
https://issues.dlang.org/show_bug.cgi?id=14552

**Pull request merged**
