### PR TITLE
Merge stable -> master

### PR DESCRIPTION
**Pull request by wilzbach**
Conflicts:
	src/dmd/backend/cgelem.d
	src/dmd/expression.d

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by FeepingCreature** [comment]
While this is up, could you pull in my `~=` deprecated changes as well, please?

**Comment by wilzbach** [comment]
Well, this is time _a lot_ of commits from stable piled up, so I would prefer resolving the test failures here first, before adding more things. We can simply run merge_stable again afterwards and it won't have any conflicts.

@SSoulaimane the testsuite fails on some platforms on your non-global template tests. Is there anything that changed in master in the meantime?

**Comment by SSoulaimane** [comment]
I'll take a look.

**Comment by SSoulaimane** [comment]
It was a reference escape bug. Here is the fix #9966.

**Pull request merged**
