### PR TITLE
make dyncast const - and move DYNCAST out of globals into root

### PR DESCRIPTION
**Pull request by UplinkCoder**
this is a follow-up on #6442,
based on @yebblies comments.

I am not too sure about this structural change.

### CODE REVIEW

**Comment by yebblies** [comment]
Putting a list of dmd class roots in here is weird, but it's still better than actually importing dmd module.

**Comment by ibuclaw** [comment]
This broke C++ builds.  You forgot to put `const` in all headers.

**Comment by UplinkCoder** [comment]
@ibuclaw sorry about that.
How do I check for this kind of breakage ?
So it does not happen in the future ?

**Comment by ibuclaw** [comment]
The only way to know would be to apply the patch to gdc, and see if it can still compile and pass on unittests+testsuites.  As I'm keeping the codebases between gdc and dmd/stable pretty much in sync (not the entire implementation, but just enough to allow common headers + glue), applying patches should be trivial.

**Comment by ibuclaw** [comment]
> LDC consumes the AST from C++ as well, so it would also be affected.

Test both then, the more coverage, the better. :-)

**Comment by WalterBright** [comment]
Another solution is to use `interface`s to connect to the back ends rather than directly access the data structures.

**Comment by WalterBright** [comment]
I had a PR for that which at least tried to remove information not needed by the back end(s) and relied on the virtual inheritance of functions and omitted fields and overriding function declarations. It was roundly criticized and I abandoned it.

What I mean by interfaces is literal - communicate with D objects using the `interface` keyword. This will be far more stable than maintaining adding/subtracting fields which are not conceivably useful to the back end. A more modest approach is to reduce the dependence of the back end(s) on direct access to fields.

This can be done incrementally, it doesn't need to be all-or-nothing.

**Comment by WalterBright** [comment]
The `TypeInfo` object tree is a successful application of this concept.

**Comment by WalterBright** [comment]
Yes, but at least the noise of having to regularly fold in irrelevant fields and unused functions could be eliminated.

**Comment by ibuclaw** [comment]
> Yes, but at least the noise of having to regularly fold in irrelevant fields and unused functions could be eliminated.

They aren't unused functions in gdc so long as I'm maintaining the C++ frontend and keeping it somewhat updated.

**Comment by ibuclaw** [comment]
> Another solution is to use interfaces to connect to the back ends rather than directly access the data structures.

In this event, the interface was broken, not the fields.

**Comment by ibuclaw** [comment]
In any case the fix has been up for a day now in #6665

**Pull request merged**
