### PR TITLE
Fix Issue 23516 - Anonymous enum without base type causes segfault inferring member value

### PR DESCRIPTION
**Pull request by ntrel**

### CODE REVIEW

**Comment by ntrel** [comment]
`ae` test strikes again:
```
Running ae-test-library
std.socket.SocketOSException@std/socket.d(2841): Unable to bind socket: Cannot assign requested address
```

**Comment by RazvanN7** [comment]
Could you please rebase? It might fix it. Also, I have updated the severity of the issue. ICEs are always critical bugs.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Also, please target stable when you rebase.

**Comment by ntrel** [comment]
Rebased to `stable`.

Hmm, now DAutoTest is failing:
```
git clone -b v2.101.0 --depth=1 https://github.com/dlang/druntime .generated/druntime-2.101.0
Cloning into '.generated/druntime-2.101.0'...
warning: Could not find remote branch v2.101.0 to clone.
fatal: Remote branch v2.101.0 not found in upstream origin
posix.mak:580: recipe for target '.generated/druntime-2.101.0' failed
```
@CyberShadow it seems to be using `github.com/dlang/druntime` instead of `dmd/druntime`.

**Pull request merged**
