### PR TITLE
Issue 15332 - ICE in e2ir.c: assert(irs->sthis) in visit(ThisExp), function literal with keyword 'function' calls method

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=15332

### CODE REVIEW

**Comment by SimonN** [comment]
Thanks for fixing 15332 this fast!

**Comment by 9rnsr** [comment]
This PR also fixes a diagnostic issue 15407.

**Comment by WalterBright** [comment]
It would be better to have separate PRs for separate issues. For example, I don't see why ad7f4f7 is not in its own PR. Lumping everything together just makes it much harder to review.

**Comment by ibuclaw** [comment]
Reviewing each separately, it LGTM.

**Comment by ibuclaw** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
@ibuclaw Thanks for all your reviewing!

**Pull request merged**
