### PR TITLE
Disable AppVeyor for dmd-cxx

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Let's try blacklisting instead
https://www.appveyor.com/docs/branches/

**Comment by wilzbach** [comment]
I tried that before, but maybe it didn't take immediate effect:

image

See also: https://github.com/dlang/dmd/pull/7595

**Comment by MartinNowak** [comment]
And while we're at it, let's remove the dummy Jenkinsfile as well.

**Comment by MartinNowak** [comment]
> I tried that before, but maybe it didn't take immediate effect:

It's puzzling me how codecov and appveyor came up with the weird idea to configure in the repo and on their servers. Also why would it test anything if there is no appveyor config? Exactly because of this server-side default config nonsense, requiring us now to override it with a blacklist dummy :o.

**Comment by MartinNowak** [comment]
Not to mention AppVeyors weird login logic, where I have to select your account b/c they haven't thought of orgs beforehand.
screenshot-2018-1-5 login - appveyor

**Comment by jacob-carlborg** [comment]
@MartinNowak @wilzbach it's possible to configure AppVeyor to not build if there's no `appveyor.yml`. It's on the General settings page at further down, called `Skip branches without appveyor.yml`.

screen shot 2018-01-05 at 17 28 11

**Pull request merged**
