### PR TITLE
[REG2.068] Issue 14948 - AA key requirement was broken w/o notice and w/ horrible error message

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14948

### CODE REVIEW

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
This broke: https://issues.dlang.org/show_bug.cgi?id=15906

**Comment by 9rnsr** [comment]
I know that.
https://issues.dlang.org/show_bug.cgi?id=15906#c2

**Comment by WalterBright** [comment]
Is it better to revert and await a better fix for 14948?

**Pull request merged**
