### PR TITLE
Revert "Move DiagnosticReporter to `errors.d`"

### PR DESCRIPTION
**Pull request by WalterBright**
Reverts dlang/dmd#9484

Once this is reverted, https://github.com/dlang/dmd/pull/9350 is next.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Please close, it's fine as is.

**Comment by andralex** [comment]
@jacob-carlborg as a matter of course, if the project lead disagrees with a large refactoring, we need to go with that. Sorry.

**Review by andralex — APPROVED** [review]

**Review by thewilsonator — CHANGES_REQUESTED** [review]
This is not how due process goes.

**Comment by wilzbach** [comment]
Walter: have you ever tried using DMD as a library? We __need__ to be able to collect diagnostics in DMD as a library, just printing them out to stdout doesn't cut it (think e.g. language server), so until there's a clear argument on how one can do this once you'll have undo this work, I strongly urge you to reconsider.

**Review by wilzbach — CHANGES_REQUESTED** [review]
No. Not without a discussion.

**Comment by wilzbach** [comment]
> if the project lead disagrees with a large refactoring, we need to go with that. Sorry.

Sure, but why would anyone still bother contributing?
What do you think will happen to core contributors whose fork gets reverted/closed without any good argument?
Yup, they get fed up and leave. This has happened many many times in the past.

**Comment by thewilsonator** [comment]
You should give a good amount of thought to someone saying that who is giving a dconf presentation on "How to Become a D Contributor"...

**Comment by dkorpel** [comment]
I'm confused. Jacob is doing valuable work to help the sorry state of D static analysis tools, so why is there so much resistance instead of support? It even seems to comply with Walter's values:
"Successfully using `pure` functions is regarded with particular favor." - DMD style
"No I/O In Low Level Functions" (and instead) "Push I/O Up Call Stack" - Avoiding code smells
And it's done in relatively small steps instead of a monster PR. The only objection I see mentioned is:
> It's a great deal of code added that appears to do nothing.

Yes, there is some temporary boilerplate because it's a gradual refactor. And even once it's finished, the line count may be increased. That also happens when changing gotos into nested functions, it doesn't imply worse code.

Is there another diagnostic reporter design we can all agree with, or it the current error handling design considered ideal and not to be tampered with?

**Comment by WalterBright** [comment]
Further rationale given here: https://github.com/dlang/dmd/pull/9350

**Comment by WalterBright** [comment]
> "Successfully using pure functions is regarded with particular favor."

Replacing a call to an impure function with a call to an impure interface doesn't make the caller pure.

> "Push I/O Up Call Stack"

Replacing a call to function to one to an interface is not pushing the call up the stack.

**Comment by WalterBright** [comment]
@wilzbach > there's a clear argument on how one can do this once you'll have undo this work

https://github.com/dlang/dmd/pull/9350#issuecomment-478306655

**Comment by jacob-carlborg** [comment]
> Replacing a call to an impure function with a call to an impure interface doesn't make the caller pure.
Replacing a call to a function with one to an interface is not pushing the call up the stack.

The `DiagnosticReporter` PRs did not do this. It was the other PR that you closed https://github.com/dlang/dmd/pull/9494, that was **in the process** of accomplishing that for the lexer. Here's the complete PR that accomplishes that: https://github.com/dlang/dmd/pull/9480. As you can see, the `error` function of the lexer is now `pure`: https://github.com/dlang/dmd/pull/9480/files#diff-b24a7d8934fc062aaa3f71e4e5f96081R2297.

**Comment by WalterBright** [comment]
> As you can see, the error function of the lexer is now pure

Yes, and that is good.

**Comment by jacob-carlborg** [comment]
>> As you can see, the error function of the lexer is now pure

> Yes, and that is good.

@WalterBright But you don't like it anyway? Because you close the PR https://github.com/dlang/dmd/pull/9494 that is the first of several in the process of making this possible.

**Comment by WalterBright** [comment]
> But you don't like it anyway?

That's right. It's much too heavy, as "first of several in the process of making this possible" indicates.

**Comment by Geod24** [comment]
This branch is 5 months old, and almost 1500 commits behind master. If there's still outstanding issues, please submit a new PR for it.

**Pull request closed without merging**
