### PR TITLE
Fix Issue 14200 - Tuples not being expanded during c++ mangling.

### PR DESCRIPTION
**Pull request by Ingrater**
https://issues.dlang.org/show_bug.cgi?id=14200

### CODE REVIEW

**Comment by yebblies** [comment]
Shouldn't the tuples have been expanded already before it gets to mangling?

**Comment by Ingrater** [comment]
> Shouldn't the tuples have been expanded already before it gets to mangling?
I don't know enough about the dmd internals to answer design questions. Due to the fact that this is a windows only bug I assumed that the issue lies in the mangler and not the calling code. The proposed fix is within a windows only section of the code.

**Comment by yebblies** [comment]
It looks like the itanium mangling uses `Parameter::foreach`, which expands out tuples automatically.  The windows code should probably be doing the same thing, instead of the loop it currently uses.

**Comment by Ingrater** [comment]
I changed the implementation to use Parameter::foreach

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Pull request merged**
