### PR TITLE
[CI] Revert "fix Issue 23875 23880"

### PR DESCRIPTION
**Pull request by dkorpel**
Reverts dlang/dmd#15172

Test if this fixes the Windows_DMD_latest x86-OMF pipeline, since this was the first commit on which the error occurred.

### CODE REVIEW

**Comment by maxhaton** [comment]
Master CI is currently green

**Review by WalterBright — APPROVED** [review]

**Comment by WalterBright** [comment]
@dkorpel I can't merge it if it's a draft.

**Comment by dkorpel** [comment]
Hard to tell if it's green because it reverts a problematic commit or because it's lucky :confused:

**Comment by maxhaton** [comment]
> Lucky 

This means something is completely broken

**Pull request merged**
