### PR TITLE
Issue 14436 - Optimizer fails to remove comparison loop when comparing array against null

### PR DESCRIPTION
**Pull request by yebblies**
Before:

``` asm
__Dmain PROC NEAR
;  COMDEF __Dmain
        push    esi                                     ; 0000 _ 56
ASSUME  fs:NOTHING
        mov     eax, dword ptr fs:[__tls_array]         ; 0001 _ 64: A1, 00000000(segrel)
        mov     eax, dword ptr [eax]                    ; 0007 _ 8B. 00
        push    edi                                     ; 0009 _ 57
        mov     ecx, dword ptr [_D5testx3arrAi+eax]     ; 000A _ 8B. 88, 00000000
        test    ecx, ecx                                ; 0010 _ 85. C9
        jnz     ?_001                                   ; 0012 _ 75, 11
        mov     esi, dword ptr [_D5testx3arrAi+??+eax]  ; 0014 _ 8B. B0, 00000004
        xor     edi, edi                                ; 001A _ 31. FF
        shl     ecx, 2                                  ; 001C _ C1. E1, 02
        xor     eax, eax                                ; 001F _ 33. C0
        repe cmpsb                                      ; 0021 _ F3: A6
        jz      ?_002                                   ; 0023 _ 74, 01
?_001:  nop                                             ; 0025 _ 90
?_002:  pop     edi                                     ; 0026 _ 5F
        xor     eax, eax                                ; 0027 _ 31. C0
        pop     esi                                     ; 0029 _ 5E
        ret                                             ; 002A _ C3
__Dmain ENDP
```

After:

``` asm
__Dmain PROC NEAR
;  COMDEF __Dmain
ASSUME  fs:NOTHING
        mov     eax, dword ptr fs:[__tls_array]         ; 0000 _ 64: A1, 00000000(segrel)
        mov     eax, dword ptr [eax]                    ; 0006 _ 8B. 00
        cmp     dword ptr [_D5testx3arrAi+eax], 0       ; 0008 _ 83. B8, 00000000, 00
        jz      ?_001                                   ; 000F _ 74, 01
        nop                                             ; 0011 _ 90
?_001:  xor     eax, eax                                ; 0012 _ 31. C0
        ret                                             ; 0014 _ C3
__Dmain ENDP
```

I'm sure there's some way the optimizer could be improved to work out that the memcpy length is zero, and pass that along to the OPmemcpy, but that's beyond my current backend knowledge.

https://issues.dlang.org/show_bug.cgi?id=14436

### CODE REVIEW

**Comment by WalterBright** [comment]
Need a test case to tickle it.

**Comment by yebblies** [comment]
Don't really see the point, but ok.

**Comment by yebblies** [comment]
Updated.

**Comment by WalterBright** [comment]
Thank you. The point is coverage testing, and at least ensuring that code generated by that path still works.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
