### PR TITLE
Azure CI: Bump tested MinGW-based libs to v8.0.0

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Cirrus fails. May need manual merge.

**Comment by wilzbach** [comment]
> Cirrus fails. May need manual merge.

Redid the commit to change the sha, s.t. Cirrus CI can be restarted the error was:

```
Error while loading tasks: INVALID_ARGUMENT: Failed to parse tasks: INVALID_ARGUMENT: node conversion failed: map key is not a string!
```

**Comment by thewilsonator** [comment]
Cirrus still fails, same error.

**Comment by kinke** [comment]
Cirrus working again after retriggering, see https://github.com/cirruslabs/cirrus-ci-docs/issues/722#issuecomment-721159015.

**Comment by thewilsonator** [comment]
Semaphore seems like its stuck maybe try force pushing?

**Comment by kinke** [comment]
I guess Semaphore isn't configured for running on arbitrary branches (this direct branch here was an accident)...

**Comment by thewilsonator** [comment]
Yeah looks like you'll have to resubmit the PR from a branch not part of this repo

**Comment by kinke** [comment]
I'd rather have this fixed properly - it seems to work for @ibuclaw's #11921. Semaphore isn't controlled by a YAML file, so someone with according permissions would have to fix it.

**Comment by Geod24** [comment]
I don't know why the build didn't trigger. I fiddled with some button, and looks like its on its way now.

**Pull request merged**
