### PR TITLE
fix Issue 19473 - DMD Segfault on circular struct reference

### PR DESCRIPTION
**Pull request by WalterBright**
Another ancient regression from DMD 2.071

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
Of course, the instructions for rebasing to stable do not work. It still shows 'master'.

**Comment by WalterBright** [comment]
```
mercury~/forks/dmd/test/fail_compilation fix19473> git rebase --onto upstream/stable upstream/master
First, rewinding head to replay your work on top of it...
Applying: fix Issue 19473 - DMD Segfault on circular struct reference
mercury~/forks/dmd/test/fail_compilation fix19473> git push -f origin fix19473
Counting objects: 51, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 852 bytes | 0 bytes/s, done.
Total 8 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
To git@github.com:WalterBright/dmd.git
 + d876f39...ee86365 fix19473 -> fix19473 (forced update)
base --onto upstream/stable upstream/masterx19473>
```

**Comment by wilzbach** [comment]
> Of course, the instructions for rebasing to stable do not work. It still shows 'master'.

Try step 2: https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request

**Comment by WalterBright** [comment]
That shows a nice graphic and master with a pulldown menu, but that does not exist on this page.

**Comment by wilzbach** [comment]
Yes, you need to click on "Edit".

fbc7e2e4-62d9-11e6-8954-44ac9f5317e6

**Comment by WalterBright** [comment]
Thank you!

**Review by ibuclaw — DISMISSED** [review]
Add the new member to headers.

(It won't be used directly, the glue layer only cares that the value == SIZEOKdone, however this PR would mean such a comparison would start failing).

**Pull request merged**
