### PR TITLE
src/posix.mak: Link against libstdc++ explicitly

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by CyberShadow** [comment]
Thanks though I'd have waited for Brad's autotester just in case.

**Comment by yebblies** [comment]
This should not have been necessary...  I don't know why it wasn't automatically added just by using g++ to link.

**Comment by CyberShadow** [comment]
It could be something distro-specific, or it could be some of the hacks I had to do to work around other distro-specific issues (e.g. the libcurl/`--no-as-needed` one).

**Comment by CyberShadow** [comment]
Oh yeah, I had `CC` point to `gcc` not `g++`.

Well, we might as well keep this in case anyone does this too. Is the `CC` variable commonly used for C/C++ compilers interchangeably, or is there another convention for an environment variable name for C++ compilers?

**Comment by rsw0x** [comment]
>or is there another convention for an environment variable name for C++ compilers?

CXX
currently, D's makefiles stomp all over environmental variables anyways.

**Pull request merged**
