### PR TITLE
Add Diagnostic class to represent a single diagnostic message

### PR DESCRIPTION
**Pull request by jacob-carlborg**
The message is constructed on demand to be able to have the constructor pure and formatting the message in an impure way.

Extracted from #9480.

### CODE REVIEW

**Comment by thewilsonator** [comment]
```
dsymbol/src/dsymbol/symbol.d(204): Deprecation: Cannot use `alias this` to partially initialize variable `part` of type `SymbolOwnership`. Use `part.ptr`
```

**Comment by wilzbach** [comment]
No, the error is:

```
dmd/errors.d(77:24)[warn]: Useless final attribute, private functions declared within a class are never virtual
```

**Comment by jacob-carlborg** [comment]
Sounds more reasonable. Will fix

**Comment by jacob-carlborg** [comment]
Fixed.

**Comment by WalterBright** [comment]
I want to put a hold on all this refactoring. I do not agree with the premise of it, and would like to revert https://github.com/dlang/dmd/pull/9350

I do not understand the value in adding hundreds and hundreds of lines of code that do next to nothing. What problem is it solving?

**Comment by jacob-carlborg** [comment]
https://github.com/dlang/dmd/pull/9350#issuecomment-476561666

**Comment by jacob-carlborg** [comment]
https://github.com/dlang/dmd/pull/9480#issue-263842996

**Comment by wilzbach** [comment]
Rebased to upstream/master fix CircleCi.

**Comment by WalterBright** [comment]
Not doing this, for reasons explained elsewhere.

**Comment by jacob-carlborg** [comment]
By collecting all the diagnostics, instead of reporting them directly, and pushing up to the caller it will be possible to make the lexer `pure`. That means it no longer relies global state meaning it increases encapsulation.

**Comment by adamdruppe** [comment]
One thing I would really like long term is for all errors to be jam-packed with useful semantic information, such that they can be formatted in different contexts to best highlight that. (This is what I really mean when I say "xml error messages" on the forum, etc.)

I actually think something like this is the logical first start: error messages represented not as strings, but as objects. It just wraps a string for now, but ultimately if this leads to those input strings all being eliminated (it can still output those strings though, but the input should put the details in more structure), I'd see it as being a good thing.

**Pull request closed without merging**
