### PR TITLE
parseParameters(): use out, do not use default arg

### PR DESCRIPTION
**Pull request by WalterBright**
Modernize.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
wouldn't that qualify as churn?

**Comment by WalterBright** [comment]
No:
1. It's always better to use `out` than the same thing with a pointer.
2. I try to avoid using defaults, don't like hidden arguments. Since these lines change anyway, this is a good time to fix that.

**Comment by thewilsonator** [comment]
1 I agree with, 2 not so much. Thats the entire point of default parameters. Its only called with the arg in one place.

**Comment by WalterBright** [comment]
Abandoned for better idea https://github.com/dlang/dmd/pull/11113

**Pull request closed without merging**
