### PR TITLE
AllocOff should be targ_size_t

### PR DESCRIPTION
**Pull request by WalterBright**
To avoid sign extension bugs

Discussion: https://github.com/D-Programming-Language/dmd/pull/5036

### CODE REVIEW

**Comment by rainers** [comment]
This fixes the issue discussed in #5036.
I still think it's rather unintuitive to store negative offsets in an unsigned variable. What's the reason to do so? It's the same for `spoff`, `Foff`, `CSoff` etc, but not `BPoff` and `EBPtoESP`. Why is `targ_ptrdiff_t` not the better choice for all of these?

**Comment by rainers** [comment]
The failure on FreeBSD is probably unrelated, I've deprecated the test run.

**Comment by WalterBright** [comment]
> I still think it's rather unintuitive to store negative offsets in an unsigned variable.

It's storing an offset to EBP. The CPU adds it, and overflow wraps around, and has no notion of signed-ness in address calculations. Whether the compiler thinks it is signed or not is meaningless. There is no intuitive signed-ness for this, and if one approaches it from that direction one will make mistakes like this PR tries to correct :-)

**Comment by rainers** [comment]
This PR is a workaround for the suboptimal (aka stupid) signed/unsigned rules for arithmetic expressions implemented by C and D. If you think that's intuitive, I'm fine with that. Let's move on...

**Comment by rainers** [comment]
Auto-merge toggled on

**Pull request merged**
