### PR TITLE
simplify toEfilename

### PR DESCRIPTION
**Pull request by WalterBright**
For Win64, the conversion of dynamic array to a ref is done using a stack temporary rather than a temp in the data segment. Should result in slightly smaller code, due to fewer alignment bytes needed.

### CODE REVIEW

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
love dat red

**Comment by andralex** [comment]
Auto-merge toggled off

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
oops sorry @9rnsr I toggled it back and forth :)

**Comment by WalterBright** [comment]
thanks, guyz!

**Pull request merged**
