### PR TITLE
fix remaining problem with multi-statement inlining

### PR DESCRIPTION
**Pull request by WalterBright**
failing runnable/testline.d

### CODE REVIEW

**Comment by WalterBright** [comment]
@rainers you are probably the most knowledgeable person on exceptions for mscoff32. Can you please take a look at this and point me at something I can fix? The failure is most likely due to something being inlined in the runtime library, as testline.d itself is not inlining anything according to my tests.

**Comment by rainers** [comment]
> you are probably the most knowledgeable person on exceptions for mscoff32.

It uses the same exception mechanism as the OMF version, i.e. deh_win32.

As far as I can tell from stepping through a build with the debugger (debug info is pretty broken in optimized builds), the problem is in `onAssertError`: the `emplace` in `staticError` inlines the ctors of `AssertError`, but calls the ctor of `Throwable` with a broken `msg`. This later causes a crash in `Throwable.toString`.

**Comment by WalterBright** [comment]
Which `make` program is used to build the mscoff 32 bit druntime library? win64.mak does not have any build instructions.

**Comment by rainers** [comment]
> Which `make` program is used to build the mscoff 32 bit druntime library?

See https://github.com/dlang/druntime/pull/3853#issuecomment-1163663127

BTW: AFAICT the win*.mak files were left in their dire state mostly to not interrupt your workflow, especially with respect to using VC10.

**Comment by WalterBright** [comment]
Finally, I can repro the problem! Yay!

**Comment by WalterBright** [comment]
The 3 buildkite errors are all of the form:
```
include   src/importc.h
cpp -dD src/core/stdc/errno.c -include src/importc.h errno.i
parse     errno
```
But I have no idea why buildkite fails to build the library while every other test that builds the library succeeds. I do not know what is different about the buildkite builds.

**Comment by WalterBright** [comment]
Hmm, suddenly it starts working! Anyhow, ready to go.

@dkorpel @RazvanN7

**Review by maxhaton — APPROVED** [review]

**Pull request merged**
