### PR TITLE
Make 'private function is not accessible' deprecation an error.

### PR DESCRIPTION
**Pull request by FeepingCreature**
Affects issue 21275, 23947.
Followup to https://github.com/dlang/dmd/pull/15282

### CODE REVIEW

**Review by RazvanN7 — COMMENTED** [review]
Could you please also add a changelog entry?

**Comment by FeepingCreature** [comment]
Changelog added.

**Review by RazvanN7 — APPROVED** [review]

**Comment by FeepingCreature** [comment]
Ah, hm.

Note that the changelog as written is a bit iffy: the deprecation period for 21275 started with 2.094, but my 23947 was merged a few days ago and rolled into the same deprecation message because they shared codepaths.

I don't think 23947 deserves a deprecation of its own. Then again, I'm not sure why 21275 wasn't fixed to begin with.

**Comment by RazvanN7** [comment]
All of these are aspects of the same bug so it makes sense to just turn the deprecation into an error for all.

**Pull request merged**
