### PR TITLE
Fix-ups for the C++ implementation branch of dmd

### PR DESCRIPTION
**Pull request by ibuclaw**
@joakim-noah - By the way, mind if I remove the visual studio files?  As its not being maintained (unlike the makefiles).

### CODE REVIEW

**Comment by wilzbach** [comment]
> if I remove the visual studio files? As its not being maintained (unlike the makefiles).

I doubt that any porters will use visual studio for their build process :scream:

**Comment by wilzbach** [comment]
> De-tabify the frontend sources

Probably a good idea to let one CircleCi run this for now:

```shell
make -C src -f posix.mak checkwhitespace
```

**Review by wilzbach — APPROVED** [review]
@ others: this is https://github.com/D-Programming-GDC/GDC/pull/591 ported to `dmd-cxx`

**Comment by joakim-noah** [comment]
No opinion on the VS files, maybe somebody will update them one day?

**Pull request merged**
