### PR TITLE
Fix Issue 19574 Fix crashing with template declaration used with mangle only namespaces.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
LGTM

**Review by jacob-carlborg — APPROVED** [review]

**Comment by ZombineDev** [comment]
@thewilsonator @jacob-carlborg Bug fixes should always be merged in the stable branch, unless they either fix a bug present only in master, or somehow depend on things not present int the stable branch. Also until bugzilla integration is merged and operational dlang-bot  (https://github.com/dlang/dlang-bot/pull/223) issues need to be closed manually.

**Comment by jacob-carlborg** [comment]
> Bug fixes should always be merged in the stable branch

I thought that applied to regressions. I never seem to be able to remember all this :)

**Comment by ZombineDev** [comment]
> I thought that it applied to regressions. I never seem to be able to remember all this :)

The rule is simple: target stable for bug fixes, whenever possible. In a fictional SemVer world, where each commit bumps the version number, patch version bumps should go to stable.

For regressions from the latest release, there should be extra effort to target stable for bug fixes, even if it would be easier to leave them only in master.

The only other reason to target master for bug fixes (instead of stable) is to prevent breaking changes in stable, if they're not backwards compatible. For example `alias this` bug fixes may likely cause breaking changes, so they should really go to master.

**Pull request merged**
