### PR TITLE
Pass index and length to range error function

### PR DESCRIPTION
**Pull request by adamdruppe**
This lets druntime add it to the error object to give a more useful message by default.

### CODE REVIEW

**Comment by WalterBright** [comment]
All these extra arguments add a lot of hidden bloat to the executable.

**Comment by adamdruppe** [comment]
On Sun, Apr 10, 2016 at 03:44:25AM -0700, Walter Bright wrote:
> All these extra arguments add a lot of hidden bloat to the executable.

http://forum.dlang.org/post/ne59uj$t5i$1@digitalmars.com

There's a few little differences here, like this is on a code path
that is actually potentially executed (it isn't *actually* executed
except when dying, but it is inline with a path so it won't be unloaded)
so it is more relevant, but it is also just a few bytes per instance.
We're talking about a couple push register instructions - at most - to
get the data we are already comparing into the parameter list.

That's worth it to me. And if you don't want it, you can always use
the noboundscheck options.

**Comment by yebblies** [comment]
We could support this through `-boundcheck=verbose`, everyone wins.  I'd be interested to see if it noticeably affects codegen.

**Comment by nordlow** [comment]
@yebblies I fully agree on `-boundscheck=verbose`.

**Comment by wilzbach** [comment]
> We could support this through -boundcheck=verbose, everyone wins. I'd be interested to see if it noticeably affects codegen.

Alternatively we could enable this just for the non-release build?

(As this is still based on the C++ frontend, it might take a bit of effort to revive it.
Though there's some automation - see https://github.com/dlang/dmd/pull/4922#issuecomment-133776696)

**Comment by adamdruppe** [comment]
obsoleted by https://github.com/dlang/dmd/pull/6805

**Pull request closed without merging**
