### PR TITLE
Issue 15278 - Compile-time segfault when compiling code with alias this

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=15278

### CODE REVIEW

**Comment by andralex** [comment]
The test should actually pass. We are looking here at converting a `const List!int` to a `List!int`.

**Comment by 9rnsr** [comment]
alias this does not support `qual1(T)` to `qual2(T)` conversion. it should be done by qualified postblit.

**Comment by andralex** [comment]
@9rnsr thanks! Is that documented?

**Comment by 9rnsr** [comment]
No.

**Comment by andralex** [comment]
@9rnsr thanks. (BTW how is http://wiki.dlang.org/DIP49 related?)

No documentation leaves us more room to do the right thing. Let's leave the bug open; qualified `this(this)` is very complicated (because of the two qualifiers involved) and in fact we're considering removing `this(this)` altogether.

There should be one means for subtyping a user-defined type, and that is alias this.

**Comment by thewilsonator** [comment]
rebased as #9002

**Pull request closed without merging**
