### PR TITLE
[C++ headers] dmd.token: Change TOK and EXP to enum class types.

### PR DESCRIPTION
**Pull request by ibuclaw**
Fixes the C++ interface that got broken during the big refactor (#13406, #13403, #13400, #13395, #13392, #13389, #13376, #13372, #13367, #13360).

:warning: FYI @kinke BIG BREAKING API CHANGE! :warning: 

Steps taken to transition:

1. Replace `TOK[a-z_]` with `TOK::[a-z_]`
2. Fix up the names of `::[a-z0-9_]*` to their new `TOK` names.
3. Replace `TOK::` with `EXP::` where the remainder errors are cropping up.

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Review by kinke — APPROVED** [review]
I haven't verified the enums themselves and assume you've taken care. :)

**Comment by ibuclaw** [comment]
> I haven't verified the enums themselves and assume you've taken care. :)

Copied them ad-verbatim from tokens.d, changed ` = xxx,` to `// xxx`.  Only verification I did later was ensuring that the number of lines inbetween `{...}` was the same for both tokens.d and tokens.h.

**Comment by ibuclaw** [comment]
GDC bootstraps and passes all regression tests on x86_64-linux-gnu.

**Review by WalterBright — APPROVED** [review]

**Comment by WalterBright** [comment]
Sorry about the upheaval to GDC and LDC, but using proper types is better for the long term. All the trouble I had just *finding* all the conflations of expression nodes with token nodes consumed a lot of time. But the result is worth it.

**Pull request merged**
