### PR TITLE
refactor: HEADER_LIST to const

### PR DESCRIPTION
**Pull request by WalterBright**
This affects the DMC++ compiler, not DMD.

### CODE REVIEW

**Comment by WalterBright** [comment]
Also removed INLINE_ASM which is no longer used.

**Comment by WalterBright** [comment]
And a few others removed.

**Comment by yebblies** [comment]
I don't really see the point of `#define` to `const`, but ok.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
The point is to (eventually) remove all use of the preprocessor.

**Pull request merged**
