### PR TITLE
Revert "Fix issue 21648: remove two lines from dsymbolsem.d."

### PR DESCRIPTION
**Pull request by WalterBright**
Reverts dlang/dmd#12212

We're not doing "I don't know what they do but it fixes the bug.
And doesn't break the testsuite, so ¯\_(ツ)_/¯"

### CODE REVIEW

**Comment by FeepingCreature** [comment]
I mean, while I agree and I made the PR to a not small extent to actually get an answer for what the two lines are for, I feel they *should* have to justify themselves in the testsuite, right?

What prompted me to just try removing them was the observation that if tempinst.errors is true, we try jumping to a block that sets tempinst.errors to true. It looked like part of the logic for noticing when a template had failed and should be retried was moved around at some point, causing the case to slip through the cracks. And git blame didn't turn up much for those two lines.

**Comment by WalterBright** [comment]
Our test suite is inadequate and hardly complete. Noting that removal of these two lines seem to work should be noted in the bugzilla report, which will be a solid clue to someone coming along willing to figure out what the right solution is. I.e. what you've discovered is valuable work, but is not enough to base a PR on.

**Comment by FeepingCreature** [comment]
Fair enough. I guess I'd overestimated the testsuite then.

**Comment by atilaneves** [comment]
I think that we should investigate why the lines were there in the first place and add a test to cover them.

**Comment by ibuclaw** [comment]
> To mangle a quote, if you see [a fence in the road](https://www.goodreads.com/quotes/833466-in-the-matter-of-reforming-things-as-distinct-from-deforming), often the fastest way to learn why it was put there is to remove it and see what beast charges out at you.

[Chesterton's fence](https://fs.blog/2020/03/chestertons-fence/) is a better quote to go by.

**Comment by ibuclaw** [comment]
> I think that we should investigate why the lines were there in the first place and add a test to cover them.

"[Fast error propagation in template instantiatino](https://github.com/dlang/dmd/commit/36ff9efbe9f9a47bf4fa1f5e783d2ac99959757a)" (part of #4464).

At first glance, it does not appear to be connected with fixing the regression, but one can just revert the entire commit (rather than these two lines) to confirm that.

**Review by ibuclaw — APPROVED** [review]

**Review by 12345swordy — APPROVED** [review]

**Comment by 12345swordy** [comment]
I can't merge this, someone needs to hit this with an auto merge label.

**Pull request merged**
