### PR TITLE
d_do_test: Improve file & process handling  ....

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
... by applying the following changes:

- Use `std.process` instead of the custom `system`-based implementation (which will be useful to handle timeouts in the future)
- Fold/remove rredundant file operations (which improves readability and avoids uncesserary file system access)

----
Best reviewed per commit, can also split this into multiple PR's if preferred.

### CODE REVIEW

**Comment by wilzbach** [comment]
We need to be a bit careful with this. IIRC there were a lot of random issues on Windows. Maybe wait until we move the Windows builds completely to Azure and then retrigger a few times to check for any issues?

**Comment by MoonlightSentinel** [comment]
Sure, there's no rush to get this merged. Do you recall any specific issues?

**Comment by wilzbach** [comment]
> Sure, there's no rush to get this merged. Do you recall any specific issues?

I couldn't find the issue and looking at git blame I think it was likely something else.

**Review by wilzbach — APPROVED** [review]
Nice simplifications :+1:

**Pull request merged**
