### PR TITLE
Dwarf EH: complete the table generation

### PR DESCRIPTION
**Pull request by WalterBright**
The generated tables appear to be correct now.

### CODE REVIEW

**Comment by WalterBright** [comment]
Next is doing the druntime side of things.

**Comment by ibuclaw** [comment]
> Next is doing the druntime side of things.

Need help with bindings, etc?

**Comment by WalterBright** [comment]
I appreciate the offer, I need __dmd_personality_v0 and _d_throw. I set up the tables to be functionally the same as gdc generates, which should make things easier to develop and debug.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
noice

**Pull request merged**
