### PR TITLE
add VEX generation to cdvecfill()

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
The CyberSahdow/DAutoTest gives the error:
```
dstruct.d(762): Error: constructor ddmd.dstruct.StructDeclaration.this (Loc loc, Identifier id, bool inObject) is not callable using argument types (Loc, Identifier)
```
which makes no sense because line 672 is not a constructor call and the StructDeclaration constructor does not have a 3rd argument.

**Comment by andralex** [comment]
@CyberShadow FYI

**Comment by CyberShadow** [comment]
I pushed the workaround I mentioned so hopefully we won't be seeing any more of these soon.

**Comment by andralex** [comment]
@CyberShadow thx!!

**Pull request merged**
