### PR TITLE
convert varstats.c to dvarstats.d

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
> busy

I run into that on Windows often. If you write an executable, run it, then delete it at high speed, it will often fail because Windows is running a virus scanner on it. Disabling the virus scanner helps, but Windows still is holding on to the file. At some point I just gave up and I run the Windows suite on my old Windows XP which doesn't try to scan the files.

**Comment by WalterBright** [comment]
AppVeyor says:
```
..\dmd\backend\dvarstats.d(60): error : Function type does not match previously declared function with the same mangled name: `?startFunction@VarStatistics@@QAEXXZ` [C:\projects\dmd\src\vcbuild\dmd.vcxproj]
```
I don't understand it. startFunction is declared in varstats.d and defined in dvarstats.d. The types are the same. The error message isn't generated by dmd.

**Comment by jacob-carlborg** [comment]
> I don't understand it. startFunction is declared in varstats.d and defined in dvarstats.d. The types are the same. The error message isn't generated by dmd.

I think that's an error message from LDC. It usually means that the signatures are different which results in a different mangled name.

**Comment by rainers** [comment]
> I don't understand it. startFunction is declared in varstats.d and defined in dvarstats.d. The types are the same. The error message isn't generated by dmd.

The difference between the makefile build and the VS project is that the latter just grabs all *.d files from the src/dmd folder, so it compiles both varstats.d and dvarstats.d instead of merely importing varstats.d. This should also cause duplicate emission of the struct TypeInfo, or the structs might actually be considered different for some reason.
In addition LDC is more picky about duplicate definitions (which is good) than dmd.

A solution is to include the next step of the conversion, i.e. replace varstats.d with dvarstats.d.

**Comment by jacob-carlborg** [comment]
> In addition LDC is more picky about duplicate definitions (which is good) than dmd.

Yes, but it also not implementing this properly [1]. Not sure if it's the same issue.

[1] https://github.com/ldc-developers/ldc/issues/2782

**Comment by wilzbach** [comment]
> The difference between the makefile build and the VS project is that the latter just grabs all *.d files from the src/dmd folder, so it compiles both varstats.d and dvarstats.d instead of merely importing varstats.d.

The DUB build and the `build.d` build do the same.

**Comment by WalterBright** [comment]
> just grabs all *.d files

Will it do that for .di files?

**Comment by rainers** [comment]
> Will it do that for .di files?

It currently does not, but it is just a matter of adding a similar line to this: https://github.com/dlang/dmd/blob/master/src/vcbuild/dmd.vcxproj#L199

**Comment by WalterBright** [comment]
Actually, I don't want it to do it for .di files!

**Comment by WalterBright** [comment]
Looks like it fails as a .di file as well:
```
..\dmd\backend\varstats.di(42): error : Function type does not match previously declared function with the same mangled name: `?writeSymbolTable@VarStatistics@@QAEXPAUsymtab_t@@P6AXPAUSymbol@@@ZP6AXXZP6AXHH@Z3@Z` [C:\projects\dmd\src\vcbuild\dmd.vcxproj]
```

**Comment by WalterBright** [comment]
Not being able to use .di files with LDC is a serious problem.

**Comment by WalterBright** [comment]
Switching to using a free function interface to work around LDC bugs.

**Review by rainers — APPROVED** [review]

**Comment by rainers** [comment]
BTW: merging `<file>.d` and `d<file>.d` should be one of the first steps after translation to get rid of all the duplication.

**Comment by rainers** [comment]
> Not being able to use .di files with LDC is a serious problem.

Standard di file usage should be fine, the problem is with having the declarations in a module with a different module name.

**Comment by WalterBright** [comment]
Thanks for clarifying that.

**Pull request merged**
