### PR TITLE
Fix Issue 16042 - Identifier on template arguments should consider eponymous member lookup

### PR DESCRIPTION
**Pull request by JinShil**
Revival of #5794

Special thanks to @9rnsr

### CODE REVIEW

**Comment by wilzbach** [comment]
> Merge upstream

FWIW it's better for the git history if you use `git rebase` instead of `git merge`. There are a couple of articles in the wiki dealing with this (e.g. https://wiki.dlang.org/Starting_as_a_Contributor#Rebasing) and you can always ping us on Slack if you need help.

**Comment by JinShil** [comment]
I just recreated everything, so the git history should now be clean.

**Comment by JinShil** [comment]
FYI: I will be closing this PR in 14 days if noone shows any interest in it.

**Comment by WalterBright** [comment]
I'm a little nervous about what this may break, but I'll take a chance on it.

**Pull request merged**
