### PR TITLE
link: Send linking errors to stderr, not stdout

### PR DESCRIPTION
**Pull request by CyberShadow**

### CODE REVIEW

**Comment by yebblies** [comment]
Should use `global.stdmsg`?

**Comment by CyberShadow** [comment]
What's `global.stdmsg`? I see it used for `-v` output and being set to `stdout` in `globals.c`.

**Comment by yebblies** [comment]
I thought it was supposed to be where error messages go.  But for some reason it isn't being used by errors.c...

**Comment by ibuclaw** [comment]
stdmsg is used for general messages.  The motivation behind it was that gdc uses stdout to emit assembly code - also at the time there was a lot of randomness around whether stderr or stdout was used in verbose messages.

**Comment by ibuclaw** [comment]
Can't link.c use the error reporting functions?

**Comment by CyberShadow** [comment]
Ugh, is this still open? I guess I'll rebase it

**Comment by CyberShadow** [comment]
Now uses the `error` function per @ibuclaw , though I'm not sure it makes sense to in some places - e.g. it's also used to report signals received for child programs (for `-run`), long after the compiler's job is done.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
