### PR TITLE
scope.h: convert #define to enum

### PR DESCRIPTION
**Pull request by WalterBright**
Puttin' the hate on `#define`.

Should never use macros when a C language construct will work.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
I take it this has no effect on `frontend.h`?

**Comment by WalterBright** [comment]
no

**Comment by Geod24** [comment]
I don't see much purpose in this. It doesn't have a visible impact, nor does it distinctively make the code better. We have rejected PRs that were shuffling things around for much less.

**Comment by WalterBright** [comment]
1. it visibly makes the code look better
2. macros are unhygienic. They should be avoided whenever practical.

The less reliance on the preprocessor, the better.

**Comment by ibuclaw** [comment]
It would be better to look at what the contents of frontend.h is, then update to match.

**Pull request merged**
