### PR TITLE
Fix Issue 19778 - ICE when accessing empty array at compile time

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by RazvanN7** [comment]
I cannot make make this PR on top of stable because the the PR that caused the regression has not made it yet to stable.

**Comment by WalterBright** [comment]
Thanks, @RazvanN7

**Comment by RazvanN7** [comment]
Don't mention it, @WalterBright .

**Comment by JinShil** [comment]
According to a digger bisection, this PR may have introduced a regression: https://issues.dlang.org/show_bug.cgi?id=19822

**Comment by RazvanN7** [comment]
PR: https://github.com/dlang/dmd/pull/9730

**Pull request merged**
