### PR TITLE
refactor statementsem.d: remove a bunch of goto's

### PR DESCRIPTION
**Pull request by WalterBright**
From the old-ways-no-longer-relevant department.

### CODE REVIEW

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
Auto-merge toggled off

**Comment by andralex** [comment]
nice, though a bunch of those lines appear as not covered. I'll pull this because it was the same way before...

**Comment by andralex** [comment]
Actually cc @MartinNowak on how to handle such situations.

**Comment by WalterBright** [comment]
There never was an effort to go through the front end and fix coverage omissions. I think it's beyond the scope of a refactoring PR, though.

**Comment by andralex** [comment]
cool thx

**Pull request merged**
