### PR TITLE
Fix issue 19304 - [Reg 2.081.0] Linker arguments order changed in issue 15574 hinders using --whole-archive linker directive

### PR DESCRIPTION
**Pull request by llucenic**
Proposed change enables again using `--whole-archive` linker directive. Please review that it also does not interfere with the intention of Fix for issue 15574.

### CODE REVIEW

**Comment by llucenic** [comment]
@thewilsonator, how specifically and where exactly should I write the test case, please? I am asking as I did not find any hints on the Wiki. Or did you mean to write a `unittest` directly in the source file `link.d`? Thank you for an answer or guidance.

**Comment by thewilsonator** [comment]
Given that it seems that you need to link stuff you'll probably need to use a shell script test to create some dummy static libs that depend on each other(?), and then pass them all to dmd in the required order and verify that it linked correctly. 

If you can set it up so that the resulting object is an executable, then putting it in runnable seems like the easiest way to verify that it has linked correctly.

I'm really not the person to ask about how to make a shell script test, I tried to do one and failed miserably. Maybe @ZombineDev or @wilzbach can give you some more guidance on the specifics of how the shell script tests work?

**Comment by llucenic** [comment]
I will write the test, no problem. However, is the test required before merging this into stable? Having to have dmd patched seriously complicates my toolchain at the moment. As to write a proper test may take a while, I am asking if it is also possible to attach the test later?

**Comment by thewilsonator** [comment]
It would be nice to have it, but not necessary as long as it is tested eventually (or it will possibly break again).

**Comment by llucenic** [comment]
I understand therefore I will write the test (eventually). The patch I submitted is tested in my environment - it fixes the regression definitively. Unfortunately, however, I do not have a project at hand that would benefit from the PR #8172, so I cannot tell by other means than by static code introspection if this patch does not ruin the then intented improvement. Maybe @rtbo could test it?

**Comment by thewilsonator** [comment]
#8172 did add a test case (` test/compilable/issue15574.sh`) so as everything is all green it should be fine.

**Review by thewilsonator — APPROVED** [review]

**Review by PetarKirov — APPROVED** [review]
I'd also strongly prefer a test case along with this bug fix, but I'm ok with merging this as 1) the change itself looks good to me, 2) we need to address such regressions quickly and 3) @llucenic has promised to add a test case later.

**Comment by wilzbach** [comment]
Take a look at the Shell scripts in the test suite (even #8172 has one).

**Comment by llucenic** [comment]
I know that I should write a script, I was asking about the process of adding it in.

**Comment by wilzbach** [comment]
Oh sorry. Yes please target stable (though if stable has already been merged into master and master contains this fix too, you can target master too if that's easier for you).

**Comment by llucenic** [comment]
Hi, I am updating to let you know I did not forget to prepare the test. I have just lost myself in project duties... Do my best to follow up on this one soon.

**Pull request merged**
