### PR TITLE
Fix issue 20417 - Do not run ctfe for temporaries inside __traits(compiles)

### PR DESCRIPTION
**Pull request by SSoulaimane**
issue [20417](https://github.com/SSoulaimane/dmd/pull/new/f20417).

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]
Nice work! A few explanations for future reviewers:

```d
struct A { ~this(); }
void f(A, int);
A a();
int i();

pragma(msg, __traits(compiles, f(a, i))); // false
```
When `a` is called inside the `traits(compiles)` the compiler automatically inserts a destructor call for the result in the form of `auto __pfx = a()` so that it can then destroy the resulting value. When semantic is performed on `__pfx`  the compiler sees that it's not in a function scope or in typeof and therefore thinks it's at global scope therefore trying to interpret the call. The fix is correct, but there are some remaining problems:

(1) for some reason a temporary is created for the calling of `i` also and that call is also interpreted although it shouldn't.

(2) It seems a waste of time to insert a destructor call in this situation because we are never going to run that code, therefore a superior patch would be to not insert the destructor call at all when we are in `traits(compiles)`.

I guess these problems may be addressed in future PRs, if you don't feet like it @SSoulaimane .

**Comment by SSoulaimane** [comment]
Thanks.

**Comment by SSoulaimane** [comment]
For case (1) neither should be interpreted with this patch since it addresses initializers in a broad way that includes both cases an potentially others.
For suggestion (2) it should be doable but since it's not required I find special casing typeof and __traits(compiles) a bit confusing for code readers/maintainers since the premise of __traits(compiles) is to check whether a code block compiles unchanged.

**Comment by RazvanN7** [comment]
Fair enough.

**Pull request merged**
