### PR TITLE
Resurrect line spaces in statement.d

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by WalterBright** [comment]
These result in a lot of rebasing required for other outstanding PRs, make it hard to do diffs between version before and after, and mess up 'git blame'.

I'm ok with adding line spaces in sections that are being rewritten anyway, but this global reformatting probably causes more difficulty than it is worth.

I'll leave this open for a while if others care to weigh in and offer a compelling reason to pull it.

**Comment by yebblies** [comment]
I'd rather gets these all over and done with.  I don't think this actually hurts git blame since it's all added lines, unlike most other reformattings.

**Comment by AndrejMitrovic** [comment]
I think this goes hand-in-hand with the effort to document DMD. I'm very much in favour of whitespace separation of logical code blocks (like it was before). After all they were chomped up by a tool and not done deliberately IIRC. So, let's get it over with.

**Comment by AndrejMitrovic** [comment]
Auto-merge toggled on

**Pull request merged**
