### PR TITLE
fix Issue 22377: Show location for Windows extern(C++) mangling ICE

### PR DESCRIPTION
**Pull request by tim-dlang**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
Thanks, the same issue also applies to `cppmangle.d`

**Comment by tim-dlang** [comment]
> Thanks, the same issue also applies to `cppmangle.d`

That was already done as part of https://github.com/dlang/dmd/pull/7250.

**Comment by MoonlightSentinel** [comment]
> The mangling implementations also allow different types. For example an extern(C++) function returning a string would compile under Linux, but not Windows

Didn't know that, so please ignore my comment

**Comment by RazvanN7** [comment]
Could you maybe add a `version(windows)` test?

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
