### PR TITLE
use c++/cc as compiler defaults

### PR DESCRIPTION
**Pull request by MartinNowak**
- supports more platforms out of the box, e.g. FBSD and OSX
- use CXX instead of CC for C++ compilers
- still supports old HOST_CC variable
- use HOST_CXX instead of CXX for impcnvgen and optabgen

### CODE REVIEW

**Comment by yebblies** [comment]
@MartinNowak This is why converting the backend to D is useful.

**Comment by ibuclaw** [comment]
@yebblies Where you have ``DMD`` and ``DC`` as two conflicting environment variables? (Depending on the build system/setup).

**Comment by yebblies** [comment]
Yeah, but it's a choice between having the problem with both sets of compilers or having it with just one.

**Comment by MartinNowak** [comment]
> @yebblies Where you have DMD and DC as two conflicting environment variables? (Depending on the build system/setup).

It's kind of a solved problem but the word didn't yet spread.
Use `DMD` when relying on the dmd style command line (dmd/ldmd2/gdmd), use `DC` when directly using the D compilers (dmd/ldc2/gdc).

https://github.com/D-Programming-Language/dub/pull/549
https://github.com/travis-ci/travis-build/blob/aa0918190bfead8c709d981c1ca1bf8e1e6e3cbf/lib/travis/build/script/d.rb#L20

> @MartinNowak This is why converting the backend to D is useful.

That's really not a convincing argument, C++ compilers are omnipresent and depending on them is a minor issue. But spending many many hours to convert an outdated backend without improving anything for D users is a waste of time IMO. If you then compile the backend with the backend itself, it will even slow down the compiler.

**Comment by MartinNowak** [comment]
rebased

**Comment by ibuclaw** [comment]
> It's kind of a solved problem but the word didn't yet spread.

Cool.  FYI - I do have something in mind for the worst of the named gdc switches.  http://bugzilla.gdcproject.org/show_bug.cgi?id=119

**Comment by yebblies** [comment]
> That's really not a convincing argument, C++ compilers are omnipresent and depending on them is a minor issue. But spending many many hours to convert an outdated backend without improving anything for D users is a waste of time IMO.

Still, the build process is simplified when the whole thing is only one language.  As outdated as the backend is, we're stuck with it, and it badly needs cleaning up.  I didn't think Walter would agree to converting it, but he did and it's a great opportunity to strip out the huge amounts of DOS/16-bit support code that D will never use, and add some real codegen tests.

> If you then compile the backend with the backend itself, it will even slow down the compiler.

We have to solve this for the whole of ddmd.

**Comment by MartinNowak** [comment]
> As outdated as the backend is, we're stuck with it

Why?

> and it badly needs cleaning up

We have so many more important problems, and you know how time consuming any backend work is.

**Comment by MartinNowak** [comment]
rebased

**Comment by yebblies** [comment]
> Why?

Walter.

> We have so many more important problems, and you know how time consuming any backend work is.

Yeah but it's fun.

**Comment by MartinNowak** [comment]
merges and passes tests

**Comment by MartinNowak** [comment]
Updated again, this makes dmd and our makefile work by default on FreeBSD.
See https://github.com/D-Programming-Language/dmd/pull/5266.

**Comment by MartinNowak** [comment]
Seems like the gdc archive contains `c++` and `g++` (a copy not a symlink btw), but only `gcc` not `cc`.
So when running the test `cc` will use the system-wide gcc or clang that fails to link against gdc's new `libstdc++`.
Is this a packaging error @ibuclaw? If so we could temporarily workaround it in dmd's travis script, but then the next gcc release incorporating the "frontend" change needs to include a `cc` symlink.

**Comment by MartinNowak** [comment]
It's dmd that's using them, and subsequently fails with gdc on it's path.
We could also remove gdc from PATH for our travis-ci tests.

**Comment by jpf91** [comment]
> Is this a packaging error @ibuclaw, @jpf91?

I'd say it is a packaging error. I'll make sure to fix the build scripts for future releases.

**Comment by MartinNowak** [comment]
I added a workaround for the Travis-CI test. Note that this is only an issue when using dmd with gdc bin&lib PATH overrides. This should be an extremely rare setup in the wild.

**Comment by MartinNowak** [comment]
Anybody (@klickverbot) wants to merge it now?

**Comment by ibuclaw** [comment]
Hmm, I think this broke compiling with gcc 5.x.

**Comment by MartinNowak** [comment]
> Hmm, I think this broke compiling with gcc 5.x.

Why? Same packaging issue as above? Maybe we shouldn't let dmd use gdc's latest gcc for linking.

**Comment by ibuclaw** [comment]
It looks like the CXX_KIND filter is not working.

**Comment by MartinNowak** [comment]
> It looks like the CXX_KIND filter is not working.

Sorry for adding that, but there are very specific clang/gcc warning options.

**Comment by ibuclaw** [comment]
> Sorry for adding that, but there are very specific clang/gcc warning options.

I know.  But it's not doing its job of avoiding the compiler errors I'm receiving now. :-)

**Comment by ibuclaw** [comment]
Adding:
```
$(info CXX_KIND = '$(CXX_KIND)')
$(info Filter result = '$(filter %g++% %gcc% %GCC%,$(CXX_VERSION))')
```
Returns
```
CXX_KIND = ''
Filter result = ''
```

**Comment by MartinNowak** [comment]
I did test it, but apparently changed it later on.
[This](https://www.gnu.org/software/make/manual/html_node/Text-Functions.html#index-patsubst-1) is why it doesn't work.
> Only the first ‘%’ in the pattern and replacement is treated this way; any subsequent ‘%’ is unchanged.

https://github.com/D-Programming-Language/dmd/pull/5347

I wonder why you're test fails b/c some warning flags are missing?

**Comment by ibuclaw** [comment]
@MartinNowak - exactly.  g++-5 and later what with the move away from C++-98 have gotten a bit tighter and error-by-default certain warnings.  -Wno-narrowing is one of them

**Pull request merged**
