### PR TITLE
Stack offsets still not aligned properly in 32 bytes case

### PR DESCRIPTION
**Pull request by SSoulaimane**
supplement to #9143.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
For what values did the original fail?

**Comment by WalterBright** [comment]
It'd be nice to have some tests.

**Comment by jacob-carlborg** [comment]
There was a modification to a test. Not sure if it was enough.

**Comment by thewilsonator** [comment]
Semaphore failure is unrelated, this good to go?

**Comment by SSoulaimane** [comment]
> Semaphore failure is unrelated, this good to go?

If that's the case we're good.

**Pull request merged**
