### PR TITLE
Generate id.d and id.h using "dmd -run idgen.d" instead of compiling

### PR DESCRIPTION
**Pull request by marler8997**
Simple build simplification.  Run idgen.d directly using "dmd -run" instead of compiling and running in 2 seperate steps.

### CODE REVIEW

**Comment by yebblies** [comment]
This is what it used to do, but it was changed.  I don't remember why it was changed, but it needs to be worked out before it is changed back.

https://github.com/marler8997/dmd/commit/aa8a7b3dcf985c8332783961c1dd7bc598ec36c5

**Comment by UplinkCoder** [comment]
Probably such that it does not have to needlessly recompile it.

**Comment by marler8997** [comment]
@UplinkCoder There's a makefile rule for it, it should only be compiled once.  Actually this method will likely result in less recompilation since it seems that the "generated" directory where the idgen binary lives is cleaned for each run of make.  By using the method in this PR there is no intermediate binary that gets cleaned every time so it should only recompile when idgen.d actually changes.

**Comment by wilzbach** [comment]
Related PR: https://github.com/dlang/dmd/pull/6837 (Replace idgen with CTFE implementation)

**Comment by jacob-carlborg** [comment]
Yeah, since https://github.com/dlang/dmd/pull/6837 has been merged, I would say this PR is obsolete.

**Comment by wilzbach** [comment]
> Yeah, since #6837 has been merged, I would say this PR is obsolete.

Agreed, thanks for the work @marler8997, but in this case I think the merged CTFE approach is simpler and more flexible.

**Pull request closed without merging**
