### PR TITLE
Fix Issue 19965 - [DIP1000] Template allows to escape internal pointer

### PR DESCRIPTION
**Pull request by JinShil**
https://issues.dlang.org/show_bug.cgi?id=19965

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by 12345swordy** [comment]
cc @WalterBright

**Comment by JinShil** [comment]
I've narrowed this problem down to `scope` inference.  The problem is `Foo`'s `this` is attributed with `STC.maybescope` because it is a template.  That attribution should be removed with the `notMaybeScope(v)` under the right conditions.  Unfortunately, it's quite fragile.  Calling `notMaybeScope(v)` in `checkReturnEscapeImpl` fixes the [issue 19965](https://issues.dlang.org/show_bug.cgi?id=19965), but causes breakage elsewhere.  I may need some help here.

**Comment by JinShil** [comment]
This seems to work, but I don't know if it's the right solution.  If it's not the right solution, please help me get it right.  @WalterBright, I'm looking at you :smile:  I think you are the only one that understands this scope inference.  You could help remedy that with a little mentoring on this issue. :wink:

**Comment by JinShil** [comment]
For some reason the bugzilla link from @dlang-bot isn't show up, so here it is:  https://issues.dlang.org/show_bug.cgi?id=19965

**Pull request merged**
