### PR TITLE
turn on cent/ucent support

### PR DESCRIPTION
**Pull request by WalterBright**
It's already in much of the front and back end. Let's throw it out the window and see if it flies.

### CODE REVIEW

**Comment by WalterBright** [comment]
Blocked by https://github.com/dlang/dmd/pull/13505

**Comment by 12345swordy** [comment]
ping @WalterBright

**Comment by dkorpel** [comment]
Is this superseded by https://github.com/dlang/dmd/pull/13730 ?

**Comment by ibuclaw** [comment]
I guess so @WalterBright .

**Pull request closed without merging**
