### PR TITLE
(Option 2) in win32.mak, default HOST_DC to dmd

### PR DESCRIPTION
**Pull request by marler8997**

### CODE REVIEW

**Comment by wilzbach** [comment]
> Your tests failed on CircleCI

FYI: this is due to the [recent upgrade of CircleCi to 2.0](https://github.com/dlang/dmd/pull/7461).
Rebasing to `master` will fix the CI errors.

**Comment by andralex** [comment]
This is option 2 to...?

**Comment by wilzbach** [comment]
https://github.com/dlang/dmd/pull/7467

**Comment by JinShil** [comment]
Choosing Option 1: #7467

**Pull request closed without merging**
