### PR TITLE
dtoh: Merge `visitAsRoot` and `includeSymbol`

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Because `includeSymbol` always forwards to `visitAsRoot` which isn't
used by another function. This makes the code easier to follow and
avoid unecessary symbols.

### CODE REVIEW

**Review by ibuclaw — CHANGES_REQUESTED** [review]
Ok after fixing commit title.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@ibuclaw What's wrong with the commit title?

**Comment by ibuclaw** [comment]
> @ibuclaw What's wrong with the commit title?

Doth

**Comment by MoonlightSentinel** [comment]
Fixed

**Review by ibuclaw — APPROVED** [review]
Doch!

**Pull request merged**
