### PR TITLE
Rename onlysafeaccess to onlyunsafeaccess to avoid confusion

### PR DESCRIPTION
**Pull request by wilzbach**
From: https://github.com/dlang/dmd/pull/8035#discussion_r174677577

CC @JinShil

### CODE REVIEW

**Review by JinShil — DISMISSED** [review]

**Comment by WalterBright** [comment]
I have a hard time seeing an improvement. "onlysafeaccess" means that only safe accesses are allowed. "onlyunsafeaccess" means only unsafe accesses are allowed???

**Comment by wilzbach** [comment]
> "onlysafeaccess" means that only safe accesses are allowed. "onlyunsafeaccess" means only unsafe accesses are allowed???

Yes, currently the code uses this check to error in @safe, hence only @system is allowed.

I don't care about the exact naming, another one would be onlysystemaccess, but using onlysafeaccess when the code actually errors with @safe is going to hit people in the future.

**Comment by rainers** [comment]
FWIW: I agree with Walter, `onlysafeaccess` allows only safe access and rejects accesses that need `@system`. What is unclear about that?

**Comment by JinShil** [comment]
> Yes, currently the code uses this check to error in @safe, hence only @System is allowed.

Right.  Look at this code:  `!(sc.flags & SCOPE.onlysafeaccess) || sc.func.setUnsafe())`.  One condition uses the term *unsafe* and the other users *onlysafe*.  It's like it was written by a politician.

**Comment by JinShil** [comment]
Comment above without the typos:  I had to twist my mind a little, but now I see it. I'm withdrawing my approval. @wilzbach, I think we can close this, it's going to be consusing either way depending on how one thinks about it.

**Pull request closed without merging**
