### PR TITLE
#19652 Fix chained alias this.

### PR DESCRIPTION
**Pull request by ghost**
Culprit https://github.com/dlang/dmd/commit/4d4cd923df4401cf4aef4744c5c122adf8aeb631

### CODE REVIEW

**Comment by Basile-z** [comment]
It looks good to merge as is but this is a regression fix so your PR can go in stable although it's not guaranteed that there'll be a 2084.2. Also you don't refer to any issue, the dlang bot should have tell you this. There should be an issue because the bug is delivered in 2084.0.

**Comment by Geod24** [comment]
@look-at-me : Thanks for the quick fix. Could you reword the commit to comply to our style, which, as @Basile-z mentioned, will also trigger dlang bot and the various automation.
It should be: "Fix issue 19652 - alias this chain no longer works" (or any other title you see as meaningful)

Adding a comment to the code, such as "// We need to check for alias this recursively" (over the first check) could also help prevent people doing the same mistake in the future.

**Review by Geod24 — DISMISSED** [review]
Can you also add the following test in runnable:
```D
auto otherTest(inout ref Base block) @nogc { assert(0); }
auto otherTest(inout ref A block) @nogc {}
// ...
otherTest(*thingie);
```

To make sure `A` is picked over `Base` ?

**Review by RazvanN7 — APPROVED** [review]

**Comment by wilzbach** [comment]
> Your PR doesn't reference any Bugzilla issue.

Please follow [this guide](https://github.com/dlang-bots/dlang-bot#automated-references) to reference your Bugzilla issue in your commit message. Thanks!

**Comment by look-at-me** [comment]
> Fix Issue 19652 Fix chained alias this.

My commit message references an issue

https://issues.dlang.org/show_bug.cgi?id=19652

**Comment by wilzbach** [comment]
> My commit message references an issue

Looks like there was just a (temporary?) problem with the dlang-bot. It now detects your issue (:
So in accordance to:

image

I rebased your PR and re-targeted `stable`.

**Pull request merged**
