### PR TITLE
add gitzip target to posix.mak

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by wilzbach** [comment]
FWIW do you know that GH provides this out-of-the box?

e.g. https://github.com/dlang/dmd/archive/master.zip

it works for releases as well:

https://github.com/dlang/dmd/archive/v2.073.1.zip

**Comment by wilzbach** [comment]
@WalterBright what is your motivation for adding this? As mentioned GH already provides convenient links that are automatically updated, but OTOH if this helps to simply your workflow I think no one will mind (especially because `druntime` and `phobos` contain the `gitzip` target already).

**Comment by WalterBright** [comment]
This is already in the druntime and phobos makefiles, and I use it.

**Comment by wilzbach** [comment]
> This is already in the druntime and phobos makefiles, and I use it.

Fair enough.

**Pull request merged**
