### PR TITLE
[Partial] Fix Issue 16523

### PR DESCRIPTION
**Pull request by UplinkCoder**
We have to check if a switch variable is const or immutable otherwise we end of with a missing symbol.

This is only a partial fix.
We also have to make sure that we are not dealing with a temporary symbol.

### CODE REVIEW

**Comment by tramker** [comment]
I believe this show be deprecation as it breaks working code.

**Comment by UplinkCoder** [comment]
@tramker It's explicitly disallowed by the spec. 
Not deprecated.

**Comment by MartinNowak** [comment]
No, using runtime integral case values is a (weird) feature. Deprecating it might be discussable, but breaking isn't OK.
As with many other things, we had this discussion before.
[Issue 6176 – [tdpl] Cannot use string variables in case expressions](https://issues.dlang.org/show_bug.cgi?id=6176)
It's also backed by the specs, see [CaseStatement](http://dlang.org/spec/statement.html#CaseStatement).

**Comment by UplinkCoder** [comment]
@MartinNowak please reopen.
The spec explicitly states that such variables must be const or immutable.

**Comment by MartinNowak** [comment]
> Not deprecated.
> It breaks broken code.

That's the wrong view on the topic, and I don't want to let this argument slip through any more.
What matters, is whether code used to work (at least in some cases) or not. Nobody can be held responsible for checking his code against our specs, it's the compiler's job to enforce the specs, if it didn't, then that's our failure.

The following code works, so it should be a deprecation not an error.
```d
void test(int a, int b)
{
    switch (a)
    {
    case b: return;
    default: assert(0);
    }
}

void main()
{
    test(2, 2);
}
```

Rereading [Issue 6176 – [tdpl] Cannot use string variables in case expressions](https://issues.dlang.org/show_bug.cgi?id=6176) and the discussion around [Updated switch documentation to match TDPL. by Poita · Pull Request #60 · dlang/dlang.org](https://github.com/dlang/dlang.org/pull/60), it seems we have a consensus for removing variable cases (still vaguely remember that the last discussion had the opposite outcome).

**Comment by tramker** [comment]
If you add:
`case a: .. case b: break;`
to Martin's example, you will get a compilation error, so dmd's behavior is clearly inconsistent.

I was trying to fix this before ([here](https://github.com/tramker/dmd/commit/9bbc103fb957f411d41b1346225fc943b229e963)), by disallowing case variable declarations in the switch body, but with pull #5869, I don't see the point. Maybe if it get reverted.

**Comment by UplinkCoder** [comment]
@MartinNowak It's a warning now.

**Comment by MartinNowak** [comment]
Fixed a few things.
- Never use warnings when you mean deprecation (separate switches/control)
- our convention is that deprecations do fix the bug (though arguably 16523 is an ICE and only indirectly fixed)
- As mentioned before (in the first comment!), don't break working code, unless you absolutely have to

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
