### PR TITLE
Issue 11581 - Given T..., new T[0] does not work

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=11581

The two refactoring commits are necessary to avoid "goto skips initialization" issue.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Looks good.  I'm not a fan of ``goto Lagain`` logic in the semantic passes.

**Comment by ibuclaw** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks! I'm also not a fan of goto uses.

**Comment by ibuclaw** [comment]
I don't mind goto, I'm just prejudice against ``Lagain`` ;-)

**Pull request merged**
