### PR TITLE
Make most of `dmd.root.rmem` pure

### PR DESCRIPTION
**Pull request by jacob-carlborg**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
> error: undefined identifier 'pureMalloc'

Fails with GDC 7. How old is GDC? `pureMalloc` was added in DMD 2.074.0. I thought 2.079.0 was the oldest version we need to support. @ibuclaw ?

**Comment by kinke** [comment]
What's the gain of this? It fails with older host compilers, incl. LDC ltsmaster, so I'd have to hack it out again. I don't really get all this purity faking, especially if heap/GC allocations are involved, which clearly modify the global state.

**Comment by ibuclaw** [comment]
2.072? Don't know who agreed setting the minimum version so recent. Next minimum version will be 2.076, and will remain so for the next two years.  DMD is free to set their own internal minimum version however.

**Comment by jacob-carlborg** [comment]
> What's the gain of this?

To identify and eventually remove global state. This will make the compiler more useable as a library. 

> I don't really get all this purity faking, especially if heap/GC allocations are involved, which clearly modify the global state.

Allocating using the GC is pure. If it wouldn’t be possible to do heap allocations in a pure function it would be pretty limiting. I’m no expert on this topic but I assume pure functional languages like Haskell can do heap allocations.

**Comment by jacob-carlborg** [comment]
Copied the `pure*` declarations from druntime.

**Comment by ZombineDev** [comment]
Building with GDC fails at the linking stage:
```
/home/runner/dmd/linker/ld: error: /lib/x86_64-linux-gnu/libc.so.6: symbol 'errno' used as both __thread and non-__thread
/home/runner/dmd/linker/ld: ../generated/linux/release/64/lexer.a(rmem.o): previous definition here
```

**Comment by jacob-carlborg** [comment]
Semaphore passed now.

**Review by PetarKirov — APPROVED** [review]

**Comment by ZombineDev** [comment]
@kinke as mentioned by the spec (https://dlang.org/spec/function.html#pure-functions) pure functions are allowed to allocate memory. `dmd.root.rmem`'s interface should be as if it always uses the GC, whose interface is already `pure`.

**Comment by kinke** [comment]
> as long as all state is created internally or reachable through its arguments. In particular, a pure function may allocate memory by means of e.g. new or malloc without these being special cases

Alrighty then, so malloc/new apparently fall into the 'state is created internally' category, whatever that is supposed to mean (for malloc, internal as in C-runtime-internal, i.e., as internal as it gets from a D perspective %)).

**Pull request merged**
