### PR TITLE
Fix 21951 - Add missing defaultInit literal for `noreturn`

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Otherwise further semantic for `noreturn` variables / overload resultion will segfault.

The default initializer is defined as `assert(false)` for now. This
might need to be revised to satisfy [1] once the backend is adapted to
handle `noreturn` outside of return values (currently either crashes or
hits assertion failures).

[1]:
> Defining a noreturn variable with no initialization expression
> generates an assert(0) only if the variable is accessed, which can be
> useful in generic code where unused noreturn variables may be declared

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
Added CTFE support to check if the chosen initializer works with the current engine.
Also added a custom message to the generated `assert` s.t. the users sees an informative error message instead of a non-existant `assert(0)`

**Comment by UplinkCoder** [comment]
Maybe it would be good to just use `HaltExp` (assert(0) lowers to this)?
it's more in line with the DIP

**Comment by MoonlightSentinel** [comment]
> Maybe it would be good to just use HaltExp (assert(0) lowers to this)?

The DIP explicitly specifies `assert(0)` and it's not always lowered to a `HaltExp` (only with `-release` or `-check=assert=off`).
That ensures a proper stack trace for debug builds.

**Review by RazvanN7 — APPROVED** [review]
Why is this still a draft PR?

**Comment by MoonlightSentinel** [comment]
Realized that I need to add some more tests - which currently fail

**Comment by MoonlightSentinel** [comment]
Added the failing test cases as comments, I'll rather tackle them in another PR because they require more changes to the semantic analysis.

**Comment by thewilsonator** [comment]
This looks like it should probably target sable

**Review by thewilsonator — APPROVED** [review]
otherwise looks good.

**Comment by thewilsonator** [comment]
```
git clone -b v2.097.0 --depth=1 https://github.com/dlang/druntime .generated/druntime-2.097.0
Cloning into '.generated/druntime-2.097.0'...
warning: Could not find remote branch v2.097.0 to clone.
fatal: Remote branch v2.097.0 not found in upstream origin
posix.mak:574: recipe for target '.generated/druntime-2.097.0' failed
```
Ahh, crap! It's pulling the wrong branch again.

**Review by WalterBright — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
> Ahh, crap! It's pulling the wrong branch again.

Not anymore 😄

**Comment by thewilsonator** [comment]
I think this has just missed a merge stable

**Pull request merged**
