### PR TITLE
[DDMD] Switch to D source and delete C++ source

### PR DESCRIPTION
**Pull request by yebblies**
@WalterBright @MartinNowak 

Do we need the switch script in the repo beforehand?  I'm thinking not.

I think this is ready to go when it passes the autotester.

### CODE REVIEW

**Comment by MartinNowak** [comment]
> Do we need the switch script in the repo beforehand? I'm thinking not.

Yes we do, it's important for this to work that people can rebase onto both sides, the C code and the D code. Everything else means you'll have to manually merge your changes.

**Comment by yebblies** [comment]
Don't close this, I'm using it for autotesting.

**Comment by MartinNowak** [comment]
> Don't close this, I'm using it for autotesting.

Sorry, I just don't want that anyone merges this.

**Comment by yebblies** [comment]
> Sorry, I just don't want that anyone merges this.

I understand.  So in your opinion, is it enough to merge #4922 then this?

**Comment by MartinNowak** [comment]
> So in your opinion, is it enough to merge #4922 then this?

Yes should work though I just polished my more complete makefile change.

**Comment by yebblies** [comment]
> Yes should work though I just updated my more complete makefile change.
MartinNowak@6871cb4.
Also you need to update travis.sh now, see MartinNowak@a6a8ba9.

Those can be done after the switch.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
> Auto-merge toggled on

Woo-hoo!

**Comment by MartinNowak** [comment]
> Woo-hoo!

Yes, thanks again @yebblies for making this happen.

But please let's not rush into major rewrites right away. We still have to port some possible 2.068.1 fixes and don't want to loose all PRs. I'd say our main focus for 2.069.0 should lie on making ddmd really fast and ship it with less bugs than the last release.

There is no changelog entry btw ;-).

**Comment by WalterBright** [comment]
I did rush into making an announcement. I've been so wanting to do that!

**Comment by CyberShadow** [comment]
This broke the doc autotester.

Why was this merged despite the autotester failing?

**Comment by MartinNowak** [comment]
> Why was this merged despite the autotester failing?

Because the doc autotester has been somewhat flaky recently, so I guess everybody just started to ignore it.

**Comment by CyberShadow** [comment]
> everybody

You mean the person who clicked the merge button? ;)

The build logs are viewable to anyone, and the failure reason is easy to find.

Should we revert this, then?

**Comment by yebblies** [comment]
> Should we revert this, then?

No.

> The build logs are viewable to anyone, and the failure reason is easy to find.

It looks like it's not finding the C++ lib, does the test suite pass on that machine?

**Comment by CyberShadow** [comment]
That machine does not run the DMD test suite.

**Comment by yebblies** [comment]
I figured, I'm asking can it?  It looks like some host configuration issue.  It should be able to use dmd to link C++ and D together if CC is set to g++.

**Comment by MartinNowak** [comment]
Yes, it doesn't link against `libstdc++`, try to link with `-L--verbose`, `-Wl,--verbose`.

**Comment by CyberShadow** [comment]
LDFLAGS is not referenced anywhere in posix.mak now, maybe that's the reason?

**Comment by CyberShadow** [comment]
This fixes it:
```diff
diff --git a/src/posix.mak b/src/posix.mak
index aac3017..a0d27c7 100644
--- a/src/posix.mak
+++ b/src/posix.mak
@@ -293,10 +293,10 @@ backend.a: $(BACK_OBJS)

 ifdef ENABLE_LTO
 dmd: $(DMD_SRCS) $(ROOT_SRCS) newdelete.o $(GLUE_OBJS) $(BACK_OBJS) verstr.h
-       CC=$(HOST_CC) $(HOST_DMD_RUN) -of$@ $(MODEL_FLAG) -vtls -J. -d $(DFLAGS) $(filter-out verstr.h,$^)
+       CC=$(HOST_CC) $(HOST_DMD_RUN) -of$@ $(MODEL_FLAG) -vtls -J. -d $(DFLAGS) $(filter-out verstr.h,$^) $(addprefix -L,$(LDFLAGS))
 else
 dmd: $(DMD_SRCS) $(ROOT_SRCS) newdelete.o glue.a backend.a verstr.h
-       CC=$(HOST_CC) $(HOST_DMD_RUN) -of$@ $(MODEL_FLAG) -vtls -J. -d $(DFLAGS) $(filter-out verstr.h,$^)
+       CC=$(HOST_CC) $(HOST_DMD_RUN) -of$@ $(MODEL_FLAG) -vtls -J. -d $(DFLAGS) $(filter-out verstr.h,$^) $(addprefix -L,$(LDFLAGS))
 endif

 clean:
```

**Comment by MartinNowak** [comment]
> LDFLAGS is not referenced anywhere in posix.mak now, maybe that's the reason?

Mmh, right dmd doesn't link against `libstdc++`, I wonder why works on other platform.
Shouldn't linking with `g++` automatically add `-lstdc++`?

**Comment by MartinNowak** [comment]
dmd already links against `-lpthread` and `-lm`, so please only add `-lstdc++`

**Comment by CyberShadow** [comment]
I'll just remove all references to LDFLAGS then?

> dmd already links against -lpthread and -lm, so please only add -lstdc++

Where? I don't see anything relevant in `git grep pthread`

**Comment by CyberShadow** [comment]
> Where? I don't see anything relevant in git grep pthread

Oh, you mean `dmd` when invoked does that. OK.

**Comment by CyberShadow** [comment]
https://github.com/D-Programming-Language/dmd/pull/4934

**Comment by CyberShadow** [comment]
This pull request caused a ~80% *reduction* of compilation peak heap usage for an empty program on http://digger.k3.1azy.net/trend/ !

Woah, what happened here? Was the "bump the pointer" allocator replaced with the D GC?

**Comment by CyberShadow** [comment]
It also caused a 17% increase in linker memory usage, why? Are the object files it emits not the same?

**Comment by CyberShadow** [comment]
This pull request broke some tests on http://digger.k3.1azy.net/trend/ because some code DMD emits is not Valgrind-friendly, issue filed: https://issues.dlang.org/show_bug.cgi?id=14952

**Pull request merged**
