### PR TITLE
highlight optimize.d error messages

### PR DESCRIPTION
**Pull request by JinShil**

### CODE REVIEW

**Review by WalterBright — APPROVED** [review]

**Comment by JinShil** [comment]
@atilaneves What's going on with Jenkins failure unit-threaded?  @wilzbach Do you have some insight?

**Review by wilzbach — APPROVED** [review]
Just restarted Jenkins .. let's hope for the best :)

**Comment by atilaneves** [comment]
@JinShil I commited something that broke the test script, it should work now.

**Comment by wilzbach** [comment]
> @JinShil I commited something that broke the test script, it should work now.

@atilaneves: wrong PR?

**Pull request merged**
