### PR TITLE
issue 4650 - write strings/float constants to const section

### PR DESCRIPTION
**Pull request by rainers**
https://issues.dlang.org/show_bug.cgi?id=4650

This implements OMF and COFF versions of the ELF functionionality to write strings and float constants to a separate section in the binary image to allow skipping these during GC scanning.

For OMF, the data is written to a "CONST" section, while for COFF, the ".rdata" section is used similar to C++.
COFF also adds symbols for the beginning of the D generated data and bss sections so that the runtime can restrict scanning to these and exclude data from C linkage.

Long term, this should extend to other const data aswell.

### CODE REVIEW

**Comment by andralex** [comment]
Nice! I don't know about the codebase nearly enough to really review this, but looks like great work.

**Comment by WalterBright** [comment]
We'll see if this breaks the DOS C compiler...

**Comment by WalterBright** [comment]
Looks like it did break DMC++. Sigh.

**Comment by rainers** [comment]
> Looks like it did break DMC++. Sigh.

Sorry to hear that. I guess you can get the old behaviour for the C++ compiler if you use `#if MARS` to revert to DATA in Obj::data_readonly (https://github.com/D-Programming-Language/dmd/pull/4390/files#diff-baf275e112ad2dda18779c8c3c5ed9f9L535).

**Pull request merged**
