### PR TITLE
fix Issue 20461 - [dip1000] Passing stack allocated string to assert …

### PR DESCRIPTION
**Pull request by WalterBright**
…compiles

Added an extra parameter to checkParamArgumentEscape() to make it work.

### CODE REVIEW

**Comment by Geod24** [comment]
Why would be `assert` be defined as escaping its argument ? `assert` can `abort`, `writeln` and crash, etc... Yes it can also throw, but I thought you weren't so in favor of this ?

**Comment by WalterBright** [comment]
Because it does (unfortunately). See explanation here:

Blocked by https://github.com/dlang/druntime/pull/2999

Frankly what happens when assert() gets called is a ridiculous sequence of Rube Goldberg trampolines, but fixing that is beyond the scope of this patch.

**Comment by WalterBright** [comment]
Blocked by https://github.com/dlang/phobos/pull/7426

**Comment by Geod24** [comment]
Fair enough. Personally not too thrilled about it (especially in the `assert(0)` case), as I might been using this pattern now and then. However, it should be a deprecation not to break code (as it already did in druntime and Phobos).

**Comment by WalterBright** [comment]
> However, it should be a deprecation not to break code (as it already did in druntime and Phobos).

The problem is (as pointed out in bugzilla) these are unnoticed critical errors - the message will be garbage. That code does not work, and in good conscience we should not issue deprecations for it, only errors.

**Comment by Geod24** [comment]
Right, I thought it might work with `assert(0)`, but it's only with `checkaction=C`, so objection withdrawn.

**Comment by Geod24** [comment]
Can you rebase ?

**Comment by WalterBright** [comment]
rebased

**Review by Geod24 — APPROVED** [review]

**Comment by 12345swordy** [comment]
@thewilsonator this needs manually merge it seems

**Comment by Geod24** [comment]
In this case the CI just needed to be retriggered, the upstream bug has been fixed.

**Pull request merged**
