### PR TITLE
fix Issue 23710 - [REG master] Reachable code inside an 'if (false)' …

### PR DESCRIPTION
**Pull request by WalterBright**
…block no longer gets codegen

### CODE REVIEW

**Comment by WalterBright** [comment]
Ready to merge.

**Review by dkorpel — APPROVED** [review]

**Review by maxhaton — APPROVED** [review]

**Comment by ibuclaw** [comment]
Note `if (__ctfe)` is still affected.

**Comment by WalterBright** [comment]
> Note if (__ctfe) is still affected.

That's why the later PR prevents a goto into an `if(__ctfe)` block.

**Comment by ibuclaw** [comment]
> > Note if (__ctfe) is still affected.
> 
> That's why the later PR prevents a goto into an `if(__ctfe)` block.

Can discuss in that PR.

**Pull request merged**
