### PR TITLE
add test for Issue 7151 - [CTFE] cannot compare classes with ==

### PR DESCRIPTION
**Pull request by ghost**
https://issues.dlang.org/show_bug.cgi?id=7151

Depends on https://github.com/D-Programming-Language/druntime/pull/916

### CODE REVIEW

**Comment by andralex** [comment]
compilable/test7151.d(4): Error: opEquals cannot be interpreted at compile time, because it has no available source code
compilable/test7151.d(6):        called from here: test()
compilable/test7151.d(6):        while evaluating: static assert(test())

**Comment by andralex** [comment]
@NilsBossung ping?

**Comment by NilsBossung** [comment]
This depends on https://github.com/D-Programming-Language/druntime/pull/916 which is blocked.

**Comment by NilsBossung** [comment]
https://github.com/D-Programming-Language/druntime/pull/916 is in. This should be good to go now.

**Comment by 9rnsr** [comment]
Please add a new test case in compilable/interpret3.d, because too many small test files will slow down speed of running test suite.

**Comment by NilsBossung** [comment]
> Please add a new test case in compilable/interpret3.d, because too many small test files will slow down speed of running test suite.

done

**Comment by NilsBossung** [comment]
and rebased

**Comment by 9rnsr** [comment]
Thanks.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Pull request merged**
