### PR TITLE
Fix issue 21658 Debugger is reading enums with EnumBaseType incorrectly.

### PR DESCRIPTION
**Pull request by 12345swordy**
Fix is suggested by @rainers 
cc @RazvanN7 @WalterBright @Geod24

### CODE REVIEW

**Review by thewilsonator — COMMENTED** [review]
The change seems fine, but the test suite seems more red than usual. Also is it possible to test this change?

**Comment by TungstenHeart** [comment]
The errors point to a line that defines something related to the new bottom type. Maybe try to rebase your branch on the latest ~master commit.

**Comment by rainers** [comment]
It seems the backend isn't ready for this change: it assumes the enum type to be the same as int32 in a number of places, e.g. https://github.com/dlang/dmd/blob/master/src/dmd/backend/var.d#L469 and https://github.com/dlang/dmd/blob/master/src/dmd/backend/elem.d#L2184

**Comment by TungstenHeart** [comment]
Whoops seems that you have forgot a step when rebasing, although it's probably too late now you should have done

```bash
$ git checkout master
$ git pull
$ git checkout EnumFix
$ git rebase -i master
```
Now in the you must change "pick" to "drop" for all the other commits that have slipped in your branch.

**Comment by 12345swordy** [comment]
> 
> 
> Whoops seems that you have forgot a step when rebasing, although it's probably too late now you should have done
> 
> ```shell
> $ git checkout master
> $ git pull
> $ git checkout EnumFix
> $ git rebase -i master
> ```
> 
> Now in the you must change "pick" to "drop" for all the other commits that have slipped in your branch.

Don't worry I have made this mistake before, and someone show me the solution on fixing this.

**Comment by 12345swordy** [comment]
> 
> 
> It seems the backend isn't ready for this change: it assumes the enum type to be the same as int32 in a number of places, e.g. https://github.com/dlang/dmd/blob/master/src/dmd/backend/var.d#L469 and https://github.com/dlang/dmd/blob/master/src/dmd/backend/elem.d#L2184

How many times is that assumption being made?

**Comment by 12345swordy** [comment]
> 
> 
> It seems the backend isn't ready for this change: it assumes the enum type to be the same as int32 in a number of places, e.g. https://github.com/dlang/dmd/blob/master/src/dmd/backend/var.d#L469 and https://github.com/dlang/dmd/blob/master/src/dmd/backend/elem.d#L2184

How should I handle this type of code then? 
```case TYenum:      tym = TYint;   break;```

**Comment by 12345swordy** [comment]
@MoonlightSentinel Any way to restart the test suit? From the looks of it it seems to be hit by a heisenberg.

**Comment by RazvanN7** [comment]
Rebasing + repusing should fix the problem.

**Comment by 12345swordy** [comment]
What exactly is causing the majority of the test suits to crash and burn?

**Comment by MoonlightSentinel** [comment]
> @MoonlightSentinel Any way to restart the test suit? From the looks of it it seems to be hit by a heisenberg.

Some can be restartet manually, but force push works for all.

> What exactly is causing the majority of the test suits to crash and burn?

Apparently your changes because master works as expected

**Comment by RazvanN7** [comment]
It seems that this change causes druntime to fail:

```
core.exception.AssertError@src/test_hash.d(486): Assertion failure
----------------
src/core/exception.d:429 onAssertError [0x8099aac]
src/core/exception.d:585 _d_assertp [0x80944b8]
src/test_hash.d:486 void test_hash.pr2243() [0x808a47b]
src/test_hash.d:19 _Dmain [0x8088d0a]
make[2]: *** [generated/linux/debug/32/test_hash.done] Error 1
```

**Comment by 12345swordy** [comment]
> 
> 
> It seems that this change causes druntime to fail:
> 
> ```
> core.exception.AssertError@src/test_hash.d(486): Assertion failure
> ----------------
> src/core/exception.d:429 onAssertError [0x8099aac]
> src/core/exception.d:585 _d_assertp [0x80944b8]
> src/test_hash.d:486 void test_hash.pr2243() [0x808a47b]
> src/test_hash.d:19 _Dmain [0x8088d0a]
> make[2]: *** [generated/linux/debug/32/test_hash.done] Error 1
> ```

I have run the test manually on my local machine and I got no errors on my end when I compile it with the modifications that I made to it.

**Comment by 12345swordy** [comment]
@RazvanN7 Would it be the best course of action is to create `TYenum64, TYenum16, TYenum8' then?

**Comment by RazvanN7** [comment]
I'm not experienced in the backend, however, I expect that the frontend identifies the basetype of the enum and it passes it to the backend. From this perspective, it seems that the backend should never assume an enum  basetype, disconsidering the one passed by the frontend. I think that a proper fix should make sure that the backend correctly queries the enum basetype identified by the frontend. Why would that require the addition of extra TYenums?

**Comment by 12345swordy** [comment]
> 
> 
> I'm not experienced in the backend, however, I expect that the frontend identifies the basetype of the enum and it passes it to the backend. From this perspective, it seems that the backend should never assume an enum basetype, disconsidering the one passed by the frontend. I think that a proper fix should make sure that the backend correctly queries the enum basetype identified by the frontend. Why would that require the addition of extra TYenums?

The issue with your solution is that is takes a signification rewrite of the Backend and the Frontend in order for this to happen.
@WalterBright Can you please comment on this? I am at a holding pattern as I don't know what solution should I pick.

**Comment by ibuclaw** [comment]
@12345swordy if it only matters for debug generation, why not just fix it there?
@RazvanN7 while I would expect the internal enum type to be comprised of a `scoped` flag, and either a `size` or `basetype` field, unfortunately DMC never supported C++11, so I wouldn't at all be surprised if it only supported plain enum types.

**Comment by 12345swordy** [comment]
@ibuclaw 
According to @rainers here, this is a compiler problem as ldc is effected by this for struct members. Can you check to see if GDC is effected by this as well?

**Comment by ibuclaw** [comment]
> @ibuclaw
> According to @rainers here, this is a compiler problem as ldc is effected by this for struct members. Can you check to see if GDC is effected by this as well?

I don't see why ldc would be _affected_ by this issue.  Nor how gdc would be suffer from the same limitations either.

```
(gdb) pt x
type = enum class test.X {test.X.A, test.X.B, test.X.C}
(gdb) p x
$1 = test.X.A
(gdb) p x.sizeof
$2 = 1
```
That you can't see the subtype is an issue in [gdb](https://github.com/bminor/binutils-gdb/blob/95557f1e09b765e50a3575725c798bd877e40fc0/gdb/c-typeprint.c#L1582-L1596) (I'm not saying that there should be an added check for the D language there, but at present there's no D language support for type printing).

**Comment by 12345swordy** [comment]
> 
> 
> > @ibuclaw
> > According to @rainers here, this is a compiler problem as ldc is effected by this for struct members. Can you check to see if GDC is effected by this as well?
> 
> I don't see why ldc would be _affected_ by this issue. Nor how gdc would be suffer from the same limitations either.
> 
> ```
> (gdb) pt x
> type = enum class test.X {test.X.A, test.X.B, test.X.C}
> (gdb) p x
> $1 = test.X.A
> (gdb) p x.sizeof
> $2 = 1
> ```
> 
> That you can't see the basetype is an issue in [gdb](https://github.com/bminor/binutils-gdb/blob/95557f1e09b765e50a3575725c798bd877e40fc0/gdb/c-typeprint.c#L1582-L1596) (I'm not saying that there should be an added check for the D language there, but at present there's no D language support for type printing).

```enum B : byte {x,y}

struct Y {B A;}
int main()
{
Y y = { A:B.x };
return 0;
}

```
Set your breakpoint at return 0 and print the y and you will see the problem.

**Comment by ibuclaw** [comment]
> Set your breakpoint at return 0 and print the y and you will see the problem.

There is no problem.
```
(gdb) p y
$1 = {A = test.B.x}
```

**Comment by rainers** [comment]
> I think that a proper fix should make sure that the backend correctly queries the enum basetype identified by the frontend.

I agree this would be the better fix. It might allow to extend it to other non-integer base types later, too. I doubt it is an easy fix, though. Please remember the backend is also shared with a C++ compiler.


> this is a compiler problem as ldc is effected by this for struct members.

The cause is likely to be very different between compilers as they don't share this glue code.

**Comment by 12345swordy** [comment]
> 
> 
> > Set your breakpoint at return 0 and print the y and you will see the problem.
> 
> There is no problem.
> 
> ```
> (gdb) p y
> $1 = {A = test.B.x}
> ```

Compile it with ldc and you will see the issue.

**Comment by 12345swordy** [comment]
@WalterBright this is out of my expertise here, the source of the bug is created by poor code gen by the back-end. This is the type of area that is managed by you mostly.

**Pull request closed without merging**
