### PR TITLE
Issue 15799 - Misleading error message against the contract followed by semicolon in interface

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by WalterBright** [comment]
I don't think this fix works. The body is required if it is not an interface function, however, the parser code does not know it is an interface function. And not issuing the message for a non-interface function is a bug, i.e. this fix introduces that bug.

Frankly, I think this issue is a "won't fix".

**Comment by 9rnsr** [comment]
> And not issuing the message for a non-interface function is a bug, i.e. this fix introduces that bug.

In `FuncDeclaration.semantic`, the case is already rejected by the error report: `in and out contracts require function body`. Therefore 15799 is purely a dmd parser bug.

**Comment by AndrejMitrovic** [comment]
> the case is already rejected by the error report: in and out contracts require function body

Wait a minute, you've added this test to `test/compilable/compile1.d`. Therefore you _are_ actually allowing the `in` contract in interface methods, which should be an error.

**Comment by 9rnsr** [comment]
>> the case is already rejected by the error report: in and out contracts require function body
>
> Wait a minute, you've added this test to test/compilable/compile1.d. Therefore you are actually allowing the in contract in interface methods, which should be an error.

I meant, if a function declaration has in/out contracts but doesn't have body block, it's **normally** rejected by the error. See `fail_compilation/fail12901.d`

On the other hands, for the "interface contracts" feature, such the function declaration should be accepted **only** in `interface` members. However, whether a function declaration is placed in interface members or not, is not known while it's parsed (consider mixed-in functions). Therefore D parser should accept such the function declaration always, then the error should occurred from semantic analysis stage.

**Comment by AndrejMitrovic** [comment]
> On the other hands, for the "interface contracts" feature

Ah sorry, I didn't realize this code was actually legal (contracts in interface methods). In that case it LGTM.

**Comment by AndrejMitrovic** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks.

**Comment by MoonlightSentinel** [comment]
This intoduced a regression: https://issues.dlang.org/show_bug.cgi?id=21095

**Comment by AndrejMitrovic** [comment]
It looks like [15799](https://issues.dlang.org/show_bug.cgi?id=15799) was just a diagnostic improvement, so we could revert this PR if it's urgent.

**Pull request merged**
