### PR TITLE
fix Issue 22344 - ImportC: overloading of functions is not allowed

### PR DESCRIPTION
**Pull request by WalterBright**
Fixing a shortcoming I had deferred in the initial implementation.

### CODE REVIEW

**Comment by thewilsonator** [comment]
except with `__attribute__(overloadable)` which causes it to be mangled as `extern(C++)`.

**Comment by WalterBright** [comment]
gag me with a spoon :-/

**Comment by thewilsonator** [comment]
I don't have a spoon that long =P. 

Its a clang/gcc extension. The only time I've ever run into it is the headers for the OpenCL kernel function that overload common math functions. I'd say wait until someone reports a bug for it.

**Comment by WalterBright** [comment]
I agree. I'm not going to implement that one unless there's a pressing need. Frankly, if someone wants to interface to C++ code from C, write the adapter code in C++ which provides such services standard.

**Review by RazvanN7 — APPROVED** [review]

**Review by ibuclaw — APPROVED** [review]

**Comment by ibuclaw** [comment]
https://issues.dlang.org/show_bug.cgi?id=22761

**Pull request merged**
