### PR TITLE
Generate both id.c and id.d from idgen.d, in preperation for switch

### PR DESCRIPTION
**Pull request by yebblies**
@WalterBright Part 2

### CODE REVIEW

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks.

**Comment by ibuclaw** [comment]
Capitalize rather than underscore prefix?  I'm just looking and a whole mix of ``Id::This`` and other ways to get around C++/D reserved keywords.

**Comment by yebblies** [comment]
This is just manually applying what magicport is already doing to D reserved keywords.  I assume we'll be ditching idgen in favor of a CTFE solution in the near future anyway.

**Pull request merged**
