### PR TITLE
Simplify _d_isbaseof by calling _d_isbaseof2

### PR DESCRIPTION
**Pull request by deadalnix**
This removes code duplication.

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by ibuclaw** [comment]
Shouldn't there be a reference to the previous PR that did this?

**Comment by ibuclaw** [comment]
[15117](https://github.com/dlang/dmd/pull/15117)

**Comment by ibuclaw** [comment]
This PR is a duplicate, and it has already been merged.

**Comment by deadalnix** [comment]
I forgot I already submitted this. Sorry.

**Pull request closed without merging**
