### PR TITLE
argprefix: fix evaluation order and missing cleanup bug [bugzilla 14903]

### PR DESCRIPTION
**Pull request by kinke**
DDMD port of https://github.com/D-Programming-Language/dmd/pull/4885.

### CODE REVIEW

**Comment by kinke** [comment]
Am I really the only one deeming this important enough to be included in 2.069?

**Comment by MartinNowak** [comment]
Sorry, we won't merge something risky into stable, and just looking at the diff is pretty hard.
I'm all for fixing this, but don't have enough resources to review this atm. At best you keep track of your work on our trello board (makes it easier for us to plan time for reviews). Just send me a mail so I can add you.

**Comment by kinke** [comment]
So another release will pass by... just let me express that waiting for a pull fixing 2 rather horrible issues (missing dtor calls + totally unintuitive argument evaluation order with potentially nasty side fx) to be merged is pretty annoying. The first pull was for C++ dmd back in August, i.e., 5 months ago; it's been green since then, so it cannot be that wrong - and by no means more wrong than the current implementation ;). If I wasn't part of the community already (to some limited extent), I'd be off for good; if it had been like this with LDC too, I would have never gotten involved. No offense to anyone (especially @MartinNowak), but we should try not to scare off new people with a mindset similar to mine by finding a better prioritization system.

**Comment by andralex** [comment]
@WalterBright @MartinNowak @yebblies now with 2.070 out the door what do you guys think about discussing this?

**Comment by MartinNowak** [comment]
You're absolutely right @kinke, will try to review this within the next few days.
[argprefix: fix evaluation order and missing cleanup bug [bugzilla 14903] on Active | Trello](https://trello.com/c/PWG7w5ey/153-argprefix-fix-evaluation-order-and-missing-cleanup-bug-bugzilla-14903)

> by finding a better prioritization system

We can't currently keep up with github, but if you want to bring up something important, please participate in our [spring planings](http://forum.dlang.org/post/56806778.2040204@dawg.eu) or simply write a mail.

Are you aware of [Issue 14708 – destructor for temporary not called during stack unwinding](https://issues.dlang.org/show_bug.cgi?id=14708) and https://github.com/D-Programming-Language/dmd/pull/5110#issuecomment-142463330.
We don't currently have a proper way to handle exceptions on expression level, only for statements.
The dtors of expressions are added as IR ops (appendDtor or so), lacking any attribute inference.

**Comment by kinke** [comment]
Thanks for the follow-up. :+1: 

I'm at work now so I can't dig into the 2 mentioned issues. But they may very likely be fixed by this. As I said, one thing is the args evaluation order. The other one is a bug wrt. to premature disabling of the temporaries' dtors in case the right-most potentially throwing arg does throw. Disabling is only okay if the callee gets actually called, as it will destruct the args. The previous code disabled all dtors right before evaluating the last potentially throwing arg though, so no dtors were called if it did throw. That's a short summary to give you the required content. ;)

**Comment by MartinNowak** [comment]
> We had to extend LDC for this to work; it keeps a stack of live temporaries to be destructed for the current statement, and takes care of destructing them on a throw.

That would be a good solution, and one that could mostly be implemented in the frontend.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by kinke** [comment]
Thank you very much!

**Pull request merged**
