### PR TITLE
Make backquoted inline code only work on a single line

### PR DESCRIPTION
**Pull request by adamdruppe**
Andrei pointed out linker errors copy/pasted into Phobos doc are written `like this'. That would break things since the backtick was never closed.

This change does what github does in that case: the paired backticks must occur on the same line. If backtick is open when a newline is encountered, the tick is canceled and the text output normally.

### CODE REVIEW

**Comment by andralex** [comment]
awes

**Comment by rainers** [comment]
ddocbackticks.html kills the git experience on Windows for me, because it is considered modified, but nothing works to get it out of the way. A lot of operations are blocked by `error: Your local changes to the following files would be overwritten by merge`.

I suspect that this happens because ddocbackticks.html has CRLF line endings. ddoc10336.html has these aswell and has caused trouble in the past, but currently works.

**Comment by yebblies** [comment]
Do you have autocrlf turned on?  You shouldn't have any problems when it's off.

**Comment by rainers** [comment]
Yes, but that's the default for git on Windows. Unfortunately, Visual Studio also adds CRLF whenever adding lines, so you get mixed line endings when using LF-only files.

**Comment by yebblies** [comment]
It may be the default, but you can turn it off.  And you should, because it's horrible.

And yeah, if you're using visual studio you're going to need to watch out for mixed line endings.

**Comment by rainers** [comment]
I remember having tried turning autocrlf off when ddoc10336.html was causing troubles, but that was also a disaster. I guess I'll have to find/write some VS extension that handles this better...

**Comment by MartinNowak** [comment]
So let's just use LF then, that's also what the editorconfig says (not yet for HTML though).

**Pull request merged**
