### PR TITLE
pure -> immutable fixes

### PR DESCRIPTION
**Pull request by dnadlinger**
https://d.puremagic.com/issues/show_bug.cgi?id=11503
https://d.puremagic.com/issues/show_bug.cgi?id=11909

The actual changes are in 3c0342e and ac4aed5, the rest are just cleanup commits.

### CODE REVIEW

**Comment by CyberShadow** [comment]
This pull request may have introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=17635

**Comment by WalterBright** [comment]
This function is utterly baffling to me, especially how it swaps source and target around, swaps ta and tb around independently, arggh.

The bug in it is it falsely returns `true` for `ta = const(immutable(int)*)` and  `tb = immutable(int)*`. I don't know if it is a detail or the whole algorithm is wrong. @klickverbot can you please help?

**Comment by andralex** [comment]
@klickverbot much appreciated!

**Comment by WalterBright** [comment]
@klickverbot thanks for taking a look. I wrote this: https://github.com/dlang/dmd/pull/7179 and it now passes the test suite and the regression, but I am not terribly happy with it. I'd like a more understandable solution. For one thing it needs better comments.

**Pull request merged**
