### PR TITLE
add `__traits(getCurrentFunction)`

### PR DESCRIPTION
**Pull request by ghost**
- fix issue 8109
- fix issue 9306

This new traits is a shortcut allowing to call the function we are in and this without using `mixin` and `__FUNCTION__` tricks.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Nice, you can argue about the long name, but the trait is a good addition

**Comment by Geod24** [comment]
What's the use case ?

**Comment by NilsLankila** [comment]
I have this that is buged when using  `__FUNCTION__` but that would work with the traits:

```
/**
 * Can be mixed-in as first expression statement of a function body to
 * automatically return if one of the parameter is null. This works for classes,
 * interfaces and pointers.
 *
 * See_Also: voidFunctionProtector.
 *
 * Bugs: Does not work with overloads.
 *
 * Params:
 *      _RETURN_EXP = A string representing the expression to return when the
 *          function gives a return.
 */
enum string functionProtector(string _RETURN_EXP = "") = "
    import std.traits : ParameterIdentifierTuple, Parameters, PointerTarget;

    alias _FUNC_PARAMS_IDENT = ParameterIdentifierTuple!(mixin(__FUNCTION__));
    alias _FUNC_PARAMS_TYPES = Parameters!(mixin(__FUNCTION__));
    alias _RET_TYPE          = typeof(return);

    static foreach (n; 0 .. _FUNC_PARAMS_IDENT.length)
    {
        static if ( is(_FUNC_PARAMS_TYPES[n] == class) ||
                    is(_FUNC_PARAMS_TYPES[n] == interface) ||
                    is(PointerTarget!(_FUNC_PARAMS_TYPES[n])))
        {
            if (mixin(_FUNC_PARAMS_IDENT[n] ~ ` is null`))
            {
                static if (!is(_RET_TYPE == void))
                    return mixin(" ~ _RETURN_EXP ~ ");
                else
                    return;
            }
        }
    }
";
```

**Comment by NilsLankila** [comment]
I'd say that the idiomatic case is when mixin something in a func. Obvioulsy the factorial example is not interesting because you know what to call whan you write but when you mix something, that something has to be generic enough to work, like my `functionProtector` in any function.

**Comment by NilsLankila** [comment]
ping @TurkeyMan, as you requested that feature you may have other use cases to expose to @Geod24.

**Comment by MoonlightSentinel** [comment]
There's another approach to consider: Fixing the `parent` trait to work properly within functions (it currently fails with a forward reference error).

Then you could use `__traits(parent, <local declaration>)` or `__traits(parent, {})` to get the current function.

**Comment by UplinkCoder** [comment]
That technique does not signal intent though.


Am So., 9. Aug. 2020 um 15:29 Uhr schrieb Florian <notifications@github.com

**Comment by TurkeyMan** [comment]
@Geod24 Use case is any `mixin template` where you want to refer to the function it's introduced to.
Typically, some tools that scrape details from the functions parameter list, or various forms of pass-through shim's.,

**Comment by TurkeyMan** [comment]
> Then one could use __traits(parent, <local declaration>) or __traits(parent, {}) to get the current function.

That's also cool. It's not at all obvious though; it would need to be wrapped in some std.meta helper or something to give it a proper name.

**Comment by MoonlightSentinel** [comment]
> That technique does not signal intent though.

Fair enough. We could also consider allowing `__traits(parent)` to get the enclosing symbol.

> What would `parent` give within a `mixin template`? A reference to the mixin template itself, or a reference to the parent of the location the mixin template is mixed in to?

The latter:

```
module mod;

mixin template Foo()
{
    void bar() {}
    pragma(msg, __traits(parent, bar).stringof);
}

mixin Foo!(); // mod

void f()
{
    mixin Foo!(); // f()
}
```

**Comment by TurkeyMan** [comment]
It's lame to declare a dummy symbol, but that would theoretically be fine. You would wrap it in a `core.traits`.

**Comment by MetaLang** [comment]
> It's lame to declare a dummy symbol, but that would theoretically be fine. You would wrap it in a `core.traits`.

No need for a dummy symbol:
`module test;

mixin template Foo()
{
    //The parent of an anonymous lambda is the enclosing module/template/aggregate/function
    pragma(msg, __traits(parent, {}).stringof);
}

mixin Foo!(); //module test

template Bar()
{
    mixin Foo!();
}

alias _ = Bar!(); //Bar!()

struct Test
{
    mixin Foo!(); //Test
}

void f()
{
    mixin Foo!(); //f()
}

void main()
{
	mixin Foo!(); //main()
}`

**Comment by RazvanN7** [comment]
The user has abandoned this PR, however, a link to it is present in the issues that it was trying to fix. Anyone that wants to pick it up feel free to reopen or start a new PR from scratch.

**Pull request closed without merging**
