### PR TITLE
Fix code style corruption introduced by ddmd conversion

### PR DESCRIPTION
**Pull request by 9rnsr**
This is the _last_ PR for my code style frustration. magicport was great tool, but also it was not perfect.

Points:
- Resurrect line spaces. In C-dmd code they had been used for the separator of small code blocks. If it doesn't exist, we need to find the block gaps before understanding the code. It will become huge cost for the code reading repetition.
- Resurrect line wrappings. Too long line is difficult to read.
- Fix indent level in switch statement blocks. The scope statement being immediately below case label had confused magicport conversion. And, current indent level style is not consistent with glue & backend code.
- Place one import declaration per line. This style is diff-friendly when imports will be added/removed.

### CODE REVIEW

**Comment by 9rnsr** [comment]
Most of line space positions are same with the c-source files in `last-cdmd` and `v2.068.2` tags.

**Comment by 9rnsr** [comment]
Ping: @WalterBright @yebblies @MartinNowak

**Comment by 9rnsr** [comment]
@klickverbot dfmt does not fit my purpose.

**Comment by 9rnsr** [comment]
> (this obviously does not concern the added line spaces)

You meant about other changes than line space additions? If so:

1. I'd like to resurrect structural formatting for complex conditions (eg. in if statement). `dfmt` cannot do that.
2. Fixing indent level in switch, and import declaration style fix were just trivial work, and using grep + editor macro was enough for that.

**Comment by 9rnsr** [comment]
Of course refactoring is better than just tweaking code format, but it needs modifying runnable code and introduce some risk.

Anyway, I'd just resurrect code readability that was in c-dmd source code. So dfmt does not fit the purpose. Thanks.

**Comment by MartinNowak** [comment]
Atm there a few things that dfmt doesn't do (for whatever reason people want aligned comments).
https://github.com/D-Programming-Language/dmd/pull/5217

**Comment by MartinNowak** [comment]
Most of this looks good and improves readability, but I think we'll have to discuss the switch/case changes. My editor and I align them by default, dfmt does as well. What do you mean by scope statement in switch case?

**Comment by 9rnsr** [comment]
> My editor and I align them by default, dfmt does as well.

dfmt default setting is not related. From C++ code age, case label is indented inside switch block in dmd source code. Rather I'd like to question about this. Why we've changed style while switching to ddmd? Was there discussion about that? (I don't know about it) If there's not proper decision, I think to keep the historical style is much better than current scrambled indents.


> What do you mean by scope statement in switch case?

In C++, a case label don't make a scope implicitly. So to declare some variables under the case label, following style had been used.

```cpp
case exp1:
{    // <-- scope statement which has same indent with the case label.
    Some variable = declared;
    break;
}
case exp2:
```

(In D, a case label makes scope implicitly, so later we can remove redundant scope statements. But it should go separated refactoring PR.)

**Comment by 9rnsr** [comment]
If there is no other objections, I'll merge this soon.

**Comment by yebblies** [comment]
Here's another objection.

**Comment by 9rnsr** [comment]
@yebblies What is "your objection"? Please tell me.

**Comment by yebblies** [comment]
Many of these changes are just imposing your preferred style on the code, including introducing yet more deviations from what dfmt outputs.  Readability comes from consistency, not from preferring one arbitrary style over another.

> Fix indent level in switch statement blocks. The scope statement being immediately below case label had confused magicport conversion. And, current indent level style is not consistent with glue & backend code.

There is no point in trying to match the glue/backend style.  They don't match the frontend in plenty of other ways.

> dfmt default setting is not related. From C++ code age, case label is indented inside switch block in dmd source code. Rather I'd like to question about this. Why we've changed style while switching to ddmd? Was there discussion about that? (I don't know about it) If there's not proper decision, I think to keep the historical style is much better than current scrambled indents.

There was plenty of time before the ddmd switch to review the generate code style.  Years.

I'm in favor of line break/indentation changes only if they match dfmt's output.  I do support the re-introduction of blank lines, assuming they were deleted by the conversion.

> If there is no other objections, I'll merge this soon.

We have the "don't merge your own pull requests" rule for a reason.  If you can't convince at least one other contributor...

**Comment by 9rnsr** [comment]
I think dfmt is not yet production use ready (see the output in #5217). Yes, the line wrapping method in this PR is arbitrary, but it's definitely better than the current too long one lines.

Note that, dfmt is not yet support to custom indent level in switch statement (`dfmt_align_switch_statements` is not yet supported to `false`).

> There is no point in trying to match the glue/backend style. They don't match the frontend in plenty of other ways.

Fix my word. My change matches to the original C++ code style before ddmd conversion.

> There was plenty of time before the ddmd switch to review the generate code style. Years.

I didn't have any interests for magicport output, because it was not on my work desk. I've just trusted the generated `ddmd.exe` behavior. After the ddmd conversion, the broken source code style makes me unhappiness.

> I do support the re-introduction of blank lines, assuming they were deleted by the conversion.

magicport had deleted many line spaces, which were for the logical code block separators.

If dfmt is enough ready for production use, I can accept it to use dmd source code. But it's not yet. And I cannot wait coming better dfmt.

> If you can't convince at least one other contributor...

I've already answered to the questions of @klickverbot and @MartinNowak . And after that they didn't write any more comments.

**Comment by ibuclaw** [comment]
> I'm in favor of line break/indentation changes only if they match dfmt's output. I do support the re-introduction of blank lines, assuming they were deleted by the conversion.

Can't we just fix dfmt to automatically do what @9rnsr had to do by hand?  Just having a quick glance, a few repeated occurrences I see are:
* Imposing a soft/hard line length.
* Blank line after ``break``
* Blank line after braceless ``if`` or ``else`` body (whichever is the last branch).
* Blank line before comment.

**Comment by 9rnsr** [comment]
@klickverbot All of things you pointed out have less importance than fixing bugs and regression issues. And at least those have historical reasons. You can open a fixup PR or post a dmd bug.

---

At least to me, the C++ code was better to read. The ddmd conversion was broken dmd code at the readability point. This PR recovers equivalent level readability with C++ code. There's no other things.

To @klickverbot @yebblies : How frequently do you read current ddmd code? Once per month? Once per week? I can believe it would be less than per day, because you're not working on daily dmd bugfixes.

Yesterday, I've posted a bugfix #5271. To do finish it, I've read the related functions at least ten times. It was pain that to read squashed code, and to read over 100 columns lines with horizontal scroll of editor view.

So I can reject your arguments. Only when you really read current broken style code frequently and feel it acceptable, you arguments would have weight.

Again, this is my *last* handmade fix for the frustrated code style. If we decide to use  `dfmt` in the future, I'll accept it. But it's not today. And I'd continuously work on dmd to reduce bugs for the next release. Please don't block me.

If no other objections, I'll merge this PR in this weekend (11/21 in JST).

**Comment by 9rnsr** [comment]
OK, I broke down commits again with more fine granularity.

1. Fix broken comments introduced by ddmd conversion
  This is a real fix of corrupted comments introduced by magicport. `dfmt` cannot fix them.

2. Resurrect line spaces
  Add line spaces which were wrongly removed by magicport. `dfmt` cannot do it, so we need to do this by hand.

3. Fix too long one line imports
    This is supplemental change for #4947. The result matches to dfmt result.

4. Fix indent level in switch statements
    Maybe the result would match to the dfmt property `dfmt_align_switch_statements=false`, but it seems not to be implemented yet.

5. Resurrect line wrapping and vertical layout from original C++ code
    The result does not fix *current* dfmt result. However I think, dfmt should recognize vertical code layout, or it just keep handmade formatting when they are not exceeding hard column limit.

At least, I'd like to fix the issues up to No.2 in this PR. If you cannot accept No.3, 4, or 5, I'll remove them from this PR (and will open new PR for them).

Please give me opinion, @klickverbot and @yebblies .

**Comment by yebblies** [comment]
I'm ok with 2 and 3, but you've made up your own new alignment style in 1 and it should be removed.  I see no value in this:
```diff
-if (x) // asdf
+if (x)  // asdf
```

Or at least, significantly less value than conforming to what dfmt is outputting.

**Comment by 9rnsr** [comment]
@klickverbot OK, I'll remove the last two commits from this PR.

**Comment by 9rnsr** [comment]
@yebblies OK, I removed all two or more spaces in preceding line comment.

**Comment by andralex** [comment]
I am against changes of this kind as a matter of principle. They are labor intensive, massive, trivial, blame a lot of irrelevant changes to one person, and do nothing to improve things. They are an illusion of progress through busywork.

The right answer if such changes are deemed necessary is to improve automated tools such as dfmt. 

I'll close this. Please do not reopen, and please let's stay away from this kind of work. Thanks.

**Comment by 9rnsr** [comment]
@andralex Please read discussions. This PR fixes issues which `dfmt` cannot work for.

**Comment by yebblies** [comment]
I mostly agree with Andrei, but I don't think that applies to the changes in this PR any more.

And blame is basically dead at this point, so there's not much point worrying about it.

**Comment by 9rnsr** [comment]
@yebblies: So, OK to merge?

**Comment by WalterBright** [comment]
Some considerations:
1. Do not pull your own PRs. I don't pull mine, and if anyone is entitled to, it should be me.
2. The source as it is has already been released as 2.069. The time for massive reformatting because the code changed anyway in the switch to ddmd has passed.
3. Please respect Andrei's decision to close, despite strongly disagreeing with him. We need to put aside our differences and work together, and that sometimes means accepting things we don't agree with. Many of my PRs have been rejected, too.
4. I dislike single PRs with massive line count changes spread through the project on principle.
5. I am not opposed to doing a bit of reformatting specifically on code that is being fixed anyway. For example, if changing the import list, it would be fine to switch then to one-per-line as part of that PR.

**Comment by 9rnsr** [comment]
> 2. The source as it is has already been released as 2.069. The time for massive reformatting because the code changed anyway in the switch to ddmd has passed.

I was too late? You said that I was to do is the reformatting before any other bugfixes for the 2.069 release?

> 4. I dislike single PRs with massive line count changes spread through the project on principle.

In C++ code, I was continuously fixed brace style in each PRs so it's preferred by Andrei to give own lines for them. And some peoples had dislike the incremental fix. That's the reason I opened this big PR in this time.

> 5. I am not opposed to doing a bit of reformatting specifically on code that is being fixed anyway. For example, if changing the import list, it would be fine to switch then to one-per-line as part of that PR.

OK, I'll separate it to another PR.

**Comment by 9rnsr** [comment]
In really, I don't like to post such the big PR contains no functional changes. However, current squashed code is much harder to read than the previous C++ code. Reading unfolded long conditions is anymore pain.
This reformatting has practical reason to me.

All of line space positions are coming from previous cdmd source code. That's not random.

I'm really question why no other commiters has complaint for the current mechanically generated broken format. Are you really read today's ddmd code?  Please answer to me...

**Comment by 9rnsr** [comment]
Now this PR contains only No.1 & 2 changes listed in [this comment](https://github.com/D-Programming-Language/dmd/pull/5239#issuecomment-156995976).

@WalterBright said I should do it before 2.069 release. So I'll stop any other working for the next release.

**Comment by yebblies** [comment]
> @yebblies: So, OK to merge?

Yes, I'm OK with it, but it obviously can't be merged against Walter's veto.

> In C++ code, I was continuously fixed brace style in each PRs so it's preferred by Andrei to give own lines for them. And some peoples had dislike the incremental fix. That's the reason I opened this big PR in this time.

Yes, doing it this way is much better.

> I'm really question why no other commiters has complaint for the current mechanically generated broken format. Are you really read today's ddmd code? Please answer to me...

I've been reading it for years.  It's certainly not idea, and I do agree with many of the style changes you've proposed.  But I don't think the readability improvement is worth introducing manual formatting that will hopefully be eventually wiped out by auto-formatting.  And at least the current formatting is consistent.

**Comment by CyberShadow** [comment]
The current incomprehensible mess and technical debt that is the DMD source code, and especially the maintainers' attitude against improvements to the situation as seen in this and previous discussions, is why I will likely never actively contribute to DMD. It is just too depressing.

@andralex With all due respect, you almost never contribute to DMD, so you don't have much first-hand experience of the state of the code base.

**Comment by yebblies** [comment]
@WalterBright @andralex I'm not a big fan of big, questionable style changes, but if the alternative is #5303 and #5309 then this is a much better option.

**Comment by ibuclaw** [comment]
I would have to concur, having reviewed recent PRs, and spending ten minutes working out what exactly has changed in them.

**Pull request closed without merging**
