### PR TITLE
Bug 259 Comparing signed to unsigned does not generate an error

### PR DESCRIPTION
**Pull request by lionello**
http://d.puremagic.com/issues/show_bug.cgi?id=259

Consider a comparison a < b, a <= b, a > b, or a >= b, in which a and b are
integral types of different signedness. Without loss of generality, let's
consider a is signed and b is unsigned and the comparison is a < b. Then we
have the following cases:
1. If a.sizeof > b.sizeof, then a < b is lowered into a < cast(typeof(a)) b.
   Then signed comparison proceeds normally. This is a classic value-based
   conversion dating from the C days, and we do it in D as well.
2. If the sizeof common type of a and b is bigger than both sizeof(a) and sizeof(b), both a and b can be safely cast to the bigger [signed] type and the comparison proceeds normally.
3. Otherwise, if a is determined through Value Range Propagation to be greater
   than or equal to zero, then a < b is lowered into cast(U) a < b, where U is the
   unsigned variant of typeof(a). Then unsigned comparison proceeds normally.
4. Otherwise, the comparison is in error. 

Using deprecation() since warnings and errors during template instantiations are suppressed and the final "errors instantiating template" doesn't say why ( http://d.puremagic.com/issues/show_bug.cgi?id=9960 )

### CODE REVIEW

**Comment by andralex** [comment]
This is good work that has fallen into oblivion. @lionello could you please rebase and let's put it back on the docket. Thanks!

**Comment by John-Colvin** [comment]
This would be lovely to have...

**Comment by tsbockman** [comment]
I have created a version of this patch which is updated for DDMD. See it here: https://github.com/tsbockman/dmd/tree/issue_259

It basically seems to work, except that it causes some false positives for unreachable code detection. For example:
```D
module main;

void main(string[] args)
{
    int* a = null;
    int* c = new int;

    for (auto b = a; true; b++)
    {
        if (b > c)
            break;

        return; // DDMD with my patch incorrectly flags this line as unreachable.
    }
}
```
It seems to be limited to `for` loops with pointer arithmetic. So, typical idiomatic D code is unaffected - but it really messes up druntime.

Perhaps @lionello or @John-Colvin could take a look at my work, and point me in the right direction?

I did my translation from C++ into D somewhat blind, without fully understanding the context for the original changes by @lionello, so I really don't know if I messed up somehow, or the bug was already there, or if perhaps it is caused by other changes made to the compiler since June 2014.

**Comment by tsbockman** [comment]
I figured out what was causing the bug above, but in the process I have decided to rework much of the patch, anyway, to address various other problems I found.

**Comment by lionello** [comment]
Superseded by #5229 . Many thanks to @tsbockman for porting. Let's work together to get this in!

**Comment by tsbockman** [comment]
@lionello It might help move things along if you would review my work in #5229.

A simple "LGTM" comment would suffice, if you don't find any problems.

**Comment by lionello** [comment]
@tsbockman I will! But right now it's 1am and I'm off to bed.

**Pull request closed without merging**
