### PR TITLE
[REG2.069] Issue 15962 - Don't strip off asserts to check internal compiler errors

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by yebblies** [comment]
Was added in https://github.com/dlang/dmd/pull/4924

**Comment by AndrejMitrovic** [comment]
Shouldn't the fix then be to change all these asserts to `enforce` (or the equivalent if we're not allowed to import into Phobos)? Removing `-release` from release builds seems to be an odd workaround here.

**Comment by MartinNowak** [comment]
No way we're shipping unoptimized builds.
Please replace asserts with sth. else or use `assert(0; "msg")`.

**Comment by yebblies** [comment]
Wouldn't `-inline -O -boundscheck=off` be basically what cdmd was shipped with?

**Comment by 9rnsr** [comment]
@MartinNowak dmd's `-release` switch doesn't affect code optimization. It just changes code behavior:
- All `invariant` blocks are untested - `global.params.useInvariants`.
- All non-trivial `assert` expressions (== `AssertExp`) are untested - `global.params.useAssert`.
- All `in` and `out` contracts are untested - `global.params.useIn` and `global.params.useOut`.
- All boundary checks under `@system` or `@trusted` code are removed - `global.params.useArrayBounds`.

If "optimization" meant removing array boundary checks, I can add `-boundscheck=safeonly` instead on `-release` in this PR.

@yebblies it's same opinion with mine.

**Comment by 9rnsr** [comment]
I reopen this PR.

**Comment by 9rnsr** [comment]
> If "optimization" meant removing array boundary checks, I can add -boundscheck=safeonly instead on -release in this PR.

Done.

**Comment by MartinNowak** [comment]
Thanks, will benchmark later today.

**Comment by MartinNowak** [comment]
> Thanks, will benchmark later today.

The build is about 5% slower for building an optimized static phobos library, and about 8% slower for building a debug shared phobos library. This is more than most optimizations we've done in the past, so I don't think we want to release this. Any other ideas how to only enable existing asserts?
Maybe doing sth. like `sed 's|assert(|otherFunc(|g'?

**Comment by 9rnsr** [comment]
Does It mean that cdmd was actually slower to evaluate those assertions?
And then is ddmd *incorreectly* faster by ignoring all internal errors?

I don't know how do you think about wrong compilation result in silence, but I think it's critical than compiler perormance.

> Any other ideas how to only enable existing asserts?

There's no commmand line switch to do it. That's by design.

> Maybe doing sth. like `sed 's|assert(|otherFunc(|g'?

Q1: No one can use assert in dmd code? Is it D-ish?
Q2: If built-in `assert` is slower than equivalent user function call, isn't it a dmd backend issue?

**Comment by WalterBright** [comment]
The asserts shouldn't be that costly. I wonder what else is going on here. I suspect it is func.d's `addInvariant()` which adds redundant null checks everywhere, due to the Fear Of Seg Fault since the hardware will check for null anyway.

**Comment by MartinNowak** [comment]
We have a more complex switch for `-noboundscheck` as well, so maybe we should move this forward to sth. along the line of `-release=assert,invariant` to enable only asserts and invariants.

> I suspect it is func.d's addInvariant() which adds redundant null checks everywhere

You should know very well that intuition is a bad guide when it comes to performance.

> due to the Fear Of Seg Fault since the hardware will check for null anyway

Please don't heat up old debates.
People have explained plenty of times that they want stacktraces when a process dies b/c of a rare condition.Also setting up core dumps requires extra efforts (no idea how that works on Windows).

**Comment by MartinNowak** [comment]
Closed due to inactivity and lack of alternative solution. Making release mode a bit more configurable (to only enable asserts) sounds like a feasible choice.

**Pull request closed without merging**
