### PR TITLE
convert cgelem.c to D

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
@wilzbach how/where do I add the `-J$G` switch to `build.d`?

**Comment by WalterBright** [comment]
@rainers how do I add the `elxxx.d` build to VC?

**Comment by wilzbach** [comment]
https://github.com/dlang/dmd/blob/0ed6065c6565e69aa9291887b89daf568db230de/src/build.d#L611

**Comment by WalterBright** [comment]
@wilzbach what is the equivalent to $G ?

**Comment by wilzbach** [comment]
```d
diff --git a/src/build.d b/src/build.d
index bb6bcb558..d7347a67e 100755
--- a/src/build.d
+++ b/src/build.d
@@ -608,7 +608,7 @@ void processEnvironment()
         cxxFlags ~= ["-xc++"];
 
     // TODO: allow adding new flags from the environment
-    string[] dflags = ["-version=MARS", "-w", "-de", env["PIC_FLAG"], env["MODEL_FLAG"]];
+    string[] dflags = ["-version=MARS", "-w", "-de", env["PIC_FLAG"], env["MODEL_FLAG"], "-J"~env["G"]];
 
     flags["BACK_FLAGS"] = ["-I"~env["ROOT"], "-I"~env["TK"], "-I"~env["C"], "-I"~env["G"], "-I"~env["D"], "-DDMDV2=1"];
```

**Comment by WalterBright** [comment]
thanks!

**Review by jacob-carlborg — APPROVED** [review]

**Comment by WalterBright** [comment]
@rainers can you please help out with appveyor? It doesn't seem to be generating elxxx.d, or is not using the -J$G switch. The log file isn't much help.

**Comment by rainers** [comment]
> @rainers can you please help out with appveyor?

Adding the string import path helps:
```
diff --git a/src/vcbuild/dmd.vcxproj b/src/vcbuild/dmd.vcxproj
index ee41956..c066272 100644
--- a/src/vcbuild/dmd.vcxproj
+++ b/src/vcbuild/dmd.vcxproj
@@ -105,7 +105,7 @@
     </Link>
     <DCompile>
       <VersionIdentifiers>MARS</VersionIdentifiers>
-      <StringImportPaths>..\..;..\..\res</StringImportPaths>
+      <StringImportPaths>..\..;..\..\res;$(OutDir)\backend\generated</StringImportPaths>
       <CRuntimeLibrary>MultiThreadedDebug</CRuntimeLibrary>
       <CompilationModel>Package</CompilationModel>
       <ImportPaths>..</ImportPaths>
@@ -129,7 +129,7 @@
     </Link>
     <DCompile>
       <VersionIdentifiers>MARS</VersionIdentifiers>
-      <StringImportPaths>..\..;..\..\res</StringImportPaths>
+      <StringImportPaths>..\..;..\..\res;$(OutDir)\backend\generated</StringImportPaths>
       <CRuntimeLibrary>MultiThreadedDebug</CRuntimeLibrary>
       <CompilationModel>Package</CompilationModel>
       <ImportPaths>..</ImportPaths>
@@ -157,7 +157,7 @@
     </Link>
     <DCompile>
       <VersionIdentifiers>MARS</VersionIdentifiers>
-      <StringImportPaths>..\..;..\..\res</StringImportPaths>
+      <StringImportPaths>..\..;..\..\res;$(OutDir)\backend\generated</StringImportPaths>
       <CompilationModel>Package</CompilationModel>
       <ImportPaths>..</ImportPaths>
       <Optimizer>true</Optimizer>
@@ -186,7 +186,7 @@
     </Link>
     <DCompile>
       <VersionIdentifiers>MARS</VersionIdentifiers>
-      <StringImportPaths>..\..;..\..\res</StringImportPaths>
+      <StringImportPaths>..\..;..\..\res;$(OutDir)\backend\generated</StringImportPaths>
       <CompilationModel>Package</CompilationModel>
       <ImportPaths>..</ImportPaths>
       <Optimizer>true</Optimizer>
```

**Comment by WalterBright** [comment]
@rainers Thanks! Trying it out now...

**Comment by WalterBright** [comment]
@CyberShadow I have no idea what error the log file for DAutoTest is trying to tell me.

**Pull request merged**
