### PR TITLE
prolog_allocoffset to CGstate

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by braddr** [comment]
All the code in pdata.d is disabled code.  That turns prolog_allocoffset into a write only variable.  Why not just remove it instead?

**Comment by WalterBright** [comment]
@braddr I've been sorely tempted to doing some other improvements to these variables concurrently. But my bitter experience in doing refactorings says keep every step small, straightforward, and simple. This is because I make mistakes in refactoring. Doing things in small steps makes it much much easier to find where the mistakes are.

**Comment by braddr** [comment]
I agree with babysteps, but instead of moving, removing is the same size step and is actually forward rather than sideways

**Comment by WalterBright** [comment]
Removing pdata should be a separate issue. Right now I'm just removing globals.

**Pull request merged**
