### PR TITLE
update usages of allocreg to use the newer API

### PR DESCRIPTION
**Pull request by benjones**
Finally some red diffs.

cod3.d line 1852 is the only spot that looks weird.  It looks like it was just assigning a dummy initializer that was overwritten immediately, but worth another set of eyes looking more closely.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
looks good. how many of these be `const reg = allocreg(...);`?

**Comment by benjones** [comment]
> looks good. how many of these be `const reg = allocreg(...);`?

Probably many, but not most.  I'll take a look in a followup PR.  There's a slim chance that some of them don't need to store the return value at all?  Unless we'd get an unused var warning from the compiler?

**Comment by thewilsonator** [comment]
> Probably many, but not most. I'll take a look in a followup PR. 

Sounds good.

> Unless we'd get an unused var warning from the compiler?

that is not a thing unless you mark the function `@mustuse`

**Comment by benjones** [comment]
Lol, dscanner knows: `/buildkite/builds/zaphod-3/dlang/dmd/dmd/compiler/src/dmd/backend/cod4.d(4796:11)[warn]: Variable reg is never used.`

**Pull request merged**
