### PR TITLE
[REG2.068.1] Issue 15150 - Public selective import causes conflict

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=15150

Fix the divergence between `EnumMember` symbol and its representation `VarDeclaration`.

See also my detailed comment in bugzilla: https://issues.dlang.org/show_bug.cgi?id=15150#c1

### CODE REVIEW

**Comment by CyberShadow** [comment]
Thx! This is blocking https://github.com/D-Programming-Language/druntime/pull/1402

**Comment by MartinNowak** [comment]
What's up with the documentation change?
http://dtest.thecybershadow.net/results/700fcb253b69cbff4f313eca0193dea82fdb48c8/9e1e61d6e9d7713f8d64def9c468c0771bb6efff/

**Comment by MartinNowak** [comment]
I did fix this by removing the EnumMember [code](https://github.com/D-Programming-Language/dmd/blob/5e73c30db69347987b617a35ac1c7cbab5ab686a/src/doc.d#L938), but your fix is more conservative.
In any case please merge the test case https://github.com/9rnsr/dmd/pull/4.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
@MartinNowak Oh, I was overlooked the change. To keep compatibility of ddoc generation, I fixed `doc.d` and corresponding test case.

**Comment by 9rnsr** [comment]
@MartinNowak Thanks!

**Comment by CyberShadow** [comment]
@MartinNowak Could you please get this into master, as it's blocking https://github.com/D-Programming-Language/druntime/pull/1402 ?

**Comment by MartinNowak** [comment]
> @MartinNowak Could you please get this into master, as it's blocking D-Programming-Language/druntime#1402 ?

Just make a merge_stable PR, https://github.com/D-Programming-Language/dmd/pull/5167.

**Comment by MoonlightSentinel** [comment]
This introduced a regression: https://issues.dlang.org/show_bug.cgi?id=20520

**Pull request merged**
