### PR TITLE
fix Issue 24181 - reading double parameter from RCX rather than XMM1

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by thewilsonator — COMMENTED** [review]
test case?

**Comment by WalterBright** [comment]
added

**Review by thewilsonator — APPROVED** [review]
Looks good. Finally, this is labeled blocker, do you want to target stable?

**Comment by WalterBright** [comment]
The lisp.c is a demo program, so I'm not sure why it's a blocker. I'll leave it up to you. I'm just happy to get it fixed.

**Pull request merged**
