### PR TITLE
SemaphoreCI transition: only run OSX jobs on Travis

### PR DESCRIPTION
**Pull request by wilzbach**
- Run DMD with `MODEL=32` on Semaphore
- Remove LDC with `MODEL=32`
- Remove now unused multilib packages

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
LGTM 👌.

**Comment by wilzbach** [comment]
FYI: I updated the Semaphore config accordingly:

image

**Comment by ibuclaw** [comment]
@wilzbach - force rebase for retriggering semaphore builds?

**Comment by ibuclaw** [comment]
Also, it's about time that semaphoreci is made mandatory.

**Comment by wilzbach** [comment]
> @wilzbach - force rebase for retriggering semaphore builds?

The build failed. I just restarted it.
FYI: was experimenting with the `x86` DMD build (i.e. DMD 64-bit is used to bootstrapped DMD 32-bit). It seems all that was necessary is this line:

```
> sudo apt-get update && sudo apt-get install -y g++-multilib libcurl3-gnutls:i386
```

It sucks a bit that SemaphoreCI only supports organisations in the paid mode, but maybe @CyberShadow can add the usual candidates from https://github.com/orgs/dlang/teams/team-dmd/members for now?
I still have on my list to let the [dlang-bot recognize a "rebase" or "squash" label](https://github.com/dlang-bots/dlang-bot/pull/109) which would make life a bit easier - maybe I finally get to finish this over the next days.

**Comment by wilzbach** [comment]
> Also, it's about time that semaphoreci is made as a "Required" CI for pulls.

OK let's try this for one week. If something goes wrong we can immediately disable it.

**Comment by JinShil** [comment]
As @WalterBright pointed out in another PR, is it not possible see the stderr and stdout output of the test?

**Comment by wilzbach** [comment]
> As @WalterBright pointed out in another PR, is it not possible see the stderr and stdout output of the test?

1) Click on a job

image

2) Expand the test

image

**Pull request merged**
