### PR TITLE
fix Issue 14975 - DMD refuses to inline even trivial struct constructors

### PR DESCRIPTION
**Pull request by WalterBright**
https://issues.dlang.org/show_bug.cgi?id=14975

### CODE REVIEW

**Comment by DmitryOlshansky** [comment]
LGTM. Seems like a minor leftover had emmense effect on the inliner.

**Comment by yebblies** [comment]
Similar thing here? https://github.com/D-Programming-Language/dmd/pull/5033/files#diff-9450861ae2d65b41bed0152bb8f8e6e4R1765

**Comment by WalterBright** [comment]
> Seems like a minor leftover had emmense effect on the inliner.

Fortunately, now we have a means of testing whether something got inlined or not - `pragma(inline, true)` - which can be used to prevent such regressions in the future. I had not anticipated that when I implemented it.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=15207

**Pull request merged**
