### PR TITLE
Issue 10925 - unittests qualified on the right hand side fail

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=10925

### CODE REVIEW

**Comment by 9rnsr** [comment]
I'll open a documentation fix after the merge.

**Comment by Hackerpilot** [comment]
This looks reasonable; we already allow this for asm blocks.

**Comment by WalterBright** [comment]
I'm not too thrilled with this language change. First off, having the parens sometimes makes it confusing - when does one need them and when not? Second, adding more syntax without new capability and just as long just seems pointless. Third, adding new syntax that is redundant with existing syntax by just shuffling the order of keywords around may cause problems when significant new features are added later. Fourth, then we'll have to decide on what the "preferred" syntax is for style, and bikeshed about it, and write a style document, and add it to dfmt.

**Comment by WalterBright** [comment]
I talked with Andrei about it, and we came to the conclusion that this change would cause problems for future possible enhancements to unittests.

**Pull request closed without merging**
