### PR TITLE
fix bugzilla Issue 23515 - Named Enum of function SIGSEGFAULT 

### PR DESCRIPTION
**Pull request by WalterBright**
The crash was because the ()[] delegate was supposed to be a function pointer.

### CODE REVIEW

**Comment by WalterBright** [comment]
@dkorpel ping

**Comment by thewilsonator** [comment]
segfaults to stable? also please title commit "Fix bugzilla issue 23515: ..." so the bot actually closes the issue.

**Review by dkorpel — APPROVED** [review]
enumsem.d doesn't exist in stable yet, so perhaps the fix can be added to stable in a separate PR?

**Comment by MrcSnm** [comment]
> The crash was because the ()[] delegate was supposed to be a function pointer.

Thanks a lot for the fix :)

**Pull request merged**
