### PR TITLE
Revert "Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/dmd#11874

I was right the first time round, even if it is the most uncomfortable approach so far.

@Geod24 merge please. :-)
@MartinNowak release 2.094.2 please. :-)

### CODE REVIEW

**Comment by Geod24** [comment]
Tested with Ocean ?

**Comment by ibuclaw** [comment]
> Tested with Ocean ?

1. Is Ocean not tested in the pipeline?
2. @kinke 's comment says that the first variant is fine. https://github.com/dlang/dmd/pull/11874#issuecomment-713600187

**Comment by Geod24** [comment]
It is, but only the latest tag. You want to test with v6.x.x to reproduce the error, IIRC.

**Comment by ibuclaw** [comment]
> It is, but only the latest tag. You want to test with v6.x.x to reproduce the error, IIRC.

It's been 24 hours, that's plenty of time to make a reduction of Ocean to include with this PR. ;-)

(I'm running one now).

**Review by andralex — APPROVED** [review]

**Comment by ibuclaw** [comment]
@Geod24 added regression test.

**Review by Geod24 — APPROVED** [review]

**Comment by MartinNowak** [comment]
> @MartinNowak release 2.094.2 please. :-)

Any suggestion for a time-frame @ibuclaw, doesn't seem to fix an urgent regression for D *users* and we can merge this into master for development anytime.
Or does this block some other timelines (e.g. GDC being based on dmd releases)?

**Comment by UplinkCoder** [comment]
It does fix a regression https://issues.dlang.org/show_bug.cgi?id=21336

**Comment by ibuclaw** [comment]
> > @MartinNowak release 2.094.2 please. :-)
> 
> Any suggestion for a time-frame @ibuclaw, doesn't seem to fix an urgent regression for D _users_ and we can merge this into master for development anytime.

It broke [Ocean](https://github.com/ldc-developers/ldc/issues/3590), and it broke industry code.  What more needs to be broken?

> Or does this block some other timelines (e.g. GDC being based on dmd releases)?

GDC is still tied to dmd-cxx branch, and no GCC release until next May. ;-)

**Comment by MartinNowak** [comment]
> It broke Ocean, and it broke industry code. What more needs to be broken?

That's too much detail here for me to parse this in a reasonable time out of all the referenced issues and PRs.
So IIUC this is a regression of dmd being used as a library and Ocean now depends on the D frontend.

Can tag and build a new release in the next few days.

Btw, is dmd frontend now committed to ABI stability?

**Comment by Geod24** [comment]
@MartinNowak : What we saw is that our code started to fail with our `ldc-master` CI pipeline.
We don't test with DMD (dropped support for it a few months ago).

We reported it to the LDC devs (https://github.com/ldc-developers/ldc/issues/3590) and they tracked it to the merge of the latest stable release.
The regression happened because of https://github.com/dlang/dmd/commit/32273e82ec9ba3f4022f03e7e12d5d4a384dc3ba
However, as you can see, it's not part of v2.094.1, so I don't see a need for a new release @ibuclaw .

**Comment by ibuclaw** [comment]
@MartinNowak nevermind the original issue in this PR title, that is fixed and not a problem here. The problem is the second "fix" for it incorrectly suppressed codegen for templates, causing linker errors in community and industry projects.

> However, as you can see, it's not part of v2.094.1, so I don't see a need for a new release @ibuclaw .

It _is_ part of v2.094.1, the next commit is @MartinNowak tagging the release.

**Pull request merged**
