### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by MartinNowak**
Conflicts:
	src/dmd/root/filename.d

### CODE REVIEW

**Comment by ibuclaw** [comment]
> runnable/stdint.d:(.text._Dmain+0x12): undefined reference to `testCppI8Mangle(signed char, unsigned char, signed char, unsigned char, signed char, unsigned char)'

Is there a missing patch?

**Comment by kinke** [comment]
Nope; there's a bidirectional dependency of this on https://github.com/dlang/druntime/pull/2321; druntime's tests are failing because this is missing, and this fails because the druntime fixes are missing. This needed 3 PRs in total in order not to break the `stable` branch...

**Comment by wilzbach** [comment]
> If you don't want to shortly break master,

I wouldn't mind (and as an admin I could merge both PRs directly). Anyone objecting?

**Comment by ZombineDev** [comment]
@wilzbach no objections, please go ahead and merge them both.

**Pull request merged**
