### PR TITLE
Add integer vector comparisons

### PR DESCRIPTION
**Pull request by WalterBright**
i.e. < <= > >= == != for the rest of the integer vector types

### CODE REVIEW

**Comment by WalterBright** [comment]
The failures appear to be server problems.

**Comment by dkorpel** [comment]
Yes, digitalmars.com is down

**Comment by WalterBright** [comment]
all green now

**Comment by ibuclaw** [comment]
Server remained up, domain was down.  All resolved since yesterday.

**Comment by ibuclaw** [comment]
@WalterBright what about comparing structs with vector fields?  i.e:
```
alias int4 = __vector(int[4]);
struct S4 { int i; int4 v; float f; }
bool cmp(S4 a, S4 b)
{
    return a == b;
}
```

The error you get has now shifted from:
```
Error: incompatible types for `(a.v) == (b.v)`: both operands are of type `__vector(int[4])`
```
To...
```
Error: expression `a.v == b.v` of type `__vector(int[4])` does not have a boolean value
```

**Comment by WalterBright** [comment]
@ibuclaw I hadn't thought about that case. Please file an enhancement request for it on bugzilla.

**Comment by WalterBright** [comment]
https://issues.dlang.org/show_bug.cgi?id=23443

**Pull request merged**
