### PR TITLE
[REG2.065] Issue 13321 - Wrong goto skips declaration error

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=13321

Requires Phobos bug fix: https://github.com/D-Programming-Language/phobos/pull/2454

### CODE REVIEW

**Comment by MartinNowak** [comment]
This seems to have introduced a regression.
I was able to bisect a test failure in https://github.com/higgsjs/Higgs down to this commit.
From what I debugged in Higgs this smells like a codegen bug, a string pointer that's passed from D to the JIT code is corrupted.

**Comment by MartinNowak** [comment]
[Issue 13952 – change in struct ctor lowering triggers codegen bug](https://issues.dlang.org/show_bug.cgi?id=13952)

**Comment by MartinNowak** [comment]
Can we revert the problematic commit 91e6e877110d3f24d94f35d4292b9a92e44e078b until the regression get's fixed?

**Comment by MartinNowak** [comment]
@9rnsr, can you please check whether we changed anything about the initialization before calling the ctor. The struct in Higgs had a union that was only partially initialized.

**Comment by 9rnsr** [comment]
@MartinNowak Maybe it's a glue layer issue, or we might need to add more information about that into front-end layer. But, I don't have enough time to find actual issue without repro case. Could you please post it in bugzilla?

**Comment by MartinNowak** [comment]
> @MartinNowak Maybe it's a glue layer issue, or we might need to add more information about that into front-end layer. But, I don't have enough time to find actual issue without repro case. Could you please post it in bugzilla?

I added a comment here https://issues.dlang.org/show_bug.cgi?id=13952#c4 @9rnsr.

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=14556

**Pull request merged**
