### PR TITLE
Compile dmd exe in build.d

### PR DESCRIPTION
**Pull request by marler8997**
Move compiling the main dmd executable into `build.d`.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
```
Failed to download package eventcore from https://code.dlang.org/packages/eventcore/0.8.35.zip
```

You'll need to give it another force push.

**Comment by WalterBright** [comment]
I don't know how build.d works, but it appears to simply grab all the .d files in the directory. This causes it to fail on my machine, as I tend to leave around other .d files, and my editor makes backup files by prepending `.B` to the filename.

**Comment by wilzbach** [comment]
With this PR the CodeCov coverage report dropped to 1.8%:

https://codecov.io/gh/dlang/dmd/tree/6bb95b5bed514070e13ec9a497f47a80e8dfc5c7

**Comment by marler8997** [comment]
After doing some digging, I think the problem could be that we are now passing in absolute paths for the filenames.  I also had to convert to relative names to fix doc generation in #10516

**Comment by marler8997** [comment]
fix here: https://github.com/dlang/dmd/pull/10520

**Comment by CyberShadow** [comment]
@marler8997 This change caused the file size of the `dmd` binary to go up by 1 MB:

https://perf.dlang.io/#size-dmd;size-dmd;1570028973.2662013;1570217574.2034426

**Comment by MoonlightSentinel** [comment]
Guess this difference is caused by ‘build.d‘ including debug symbols unless ‘ENABLE_RELEASE‘ is specified

**Comment by CyberShadow** [comment]
Seems doubtful, the difference between a debug and release build is rarely just 10% of the binary size, usually it's closer to an order of magnitude.

**Comment by rainers** [comment]
Could it be that perf.dlang.io builds the default target, not release? According to this change https://perf.dlang.io/#size-dmd;size-dmd;1525732319.848405;1526707174.5968058 enabling debug information for that added abaout 3 MB.

**Comment by marler8997** [comment]
@CyberShadow thanks for finding this.  I'll try to see what's going on here.

**Comment by marler8997** [comment]
@CyberShadow where is this dmd binary coming from that your TrenD tool is analyzing?

**Comment by marler8997** [comment]
Looks like the reason for the change in size is that `build.d` is compiling a slightly different set of source files than the makefiles are.

`posix.mak` had a couple extra files `dmd/id.d` and `dmd/root/region.d`.

`build.d` had these extra files: `dmd/astbase.d`, `dmd/libmscoff.d`, `dmd/libomf.d`, `dmd/scanmscoff.d`, `dmd/scanomf.d` and `dmd/strictvisitor.d`.

When I removed one of the extra files `dmd/astbase.d` it removed about a megabyte from the dmd binary.

However, I think enabling LTO would solve any issues with include extra source files that aren't being used.  We could also go through the current build to see if dmd is including any source files that aren't being used and remove them.

**Comment by marler8997** [comment]
I've created a PR to remove the new `astbase.d` and `strictvisitor.d` modules from dmd.  It brought the size down by about a megabyte. https://github.com/dlang/dmd/pull/10674

**Pull request merged**
