### PR TITLE
Add changelog entry for #11407

### PR DESCRIPTION
**Pull request by ibuclaw**
To notify any downstream users of dmd simd changes.

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]
Thanks!

**Comment by ibuclaw** [comment]
@Geod24 - sorry, had a typo in the first code block:
```
@@ -4,7 +4,7 @@ Previously, the compiler accepted the following code as being supported by all
 `-mcpu=` types on both OSX 32-bit and all 64-bit targets.
 
 ---
-__vector(long[2]) x;
+__vector(long[4]) x;
 x += 1;
 ---
 
```

**Comment by ibuclaw** [comment]
_Sigh_ it has not rendered it in a desirable format.

http://dtest.dlang.io/artifact/website-10de19b49d1dd5071d77ac1e6271dcebdcaf1d78-3693870e9b20b7b75da8e579cae02c2e/web/changelog/pending.html

**Comment by ibuclaw** [comment]
@Geod24 this is the current look, any suggestions for improvement?

http://dtest.dlang.io/artifact/website-10de19b49d1dd5071d77ac1e6271dcebdcaf1d78-37345714ac305cb20458c4fdabba0c36/web/changelog/pending.html

**Comment by Geod24** [comment]
That looks great! Will you add it to dlang.org as well?

**Comment by ibuclaw** [comment]
I pretty much copied and pasted from the dlang.org site.

https://dlang.org/spec/simd.html#x86_64_vec

Just converted from a binary yes/no.

**Comment by ibuclaw** [comment]
The smallest addition I can think of, add in the following:

```
✝ AVX extension
✝✝ AVX2 extension
```
Then annotate each entry where appropriate.

**Pull request merged**
