### PR TITLE
Fix segfault when printing error message in lib***.d

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
`module_name` isn't always zero-terminated, so pass the length as an
additional parameter.

Found this when building 32bit phobos without an appropriate druntime library.

```
phobos>make -f win32.mak
../dmd/generated/windows/release/32/dmd -lib -ofphobos.lib -Xfphobos.json -conf= -O -release -w -de -preview=dip1000 -transition=complex -I../druntime\import std\stdio.d  std\string.d  std\format.d  std\file.d  std\array.d  std\functional.d  std\path.d  std\outbuffer.d  std\utf.d  std\csv.d  std\math.d  std\complex.d  std\numeric.d  std\bigint.d  std\bitmanip.d  std\typecons.d  std\base64.d  std\ascii.d  std\demangle.d  std\uri.d  std\mmfile.d  std\getopt.d  std\signals.d  std\meta.d  std\typetuple.d  std\traits.d  std\encoding.d  std\xml.d  std\random.d  std\exception.d  std\compiler.d  std\system.d  std\concurrency.d  std\uuid.d  std\variant.d  std\zlib.d  std\socket.d  std\conv.d  std\zip.d  std\stdint.d  std\json.d  std\parallelism.d  std\mathspecial.d  std\process.d  std\package.d  std\algorithm\package.d  std\algorithm\comparison.d  std\algorithm\iteration.d  std\algorithm\mutation.d  std\algorithm\searching.d  std\algorithm\setops.d  std\algorithm\sorting.d  std\algorithm\internal.d  std\container\array.d  std\container\binaryheap.d  std\container\dlist.d  std\container\rbtree.d  std\container\slist.d  std\container\util.d  std\container\package.d  std\datetime\date.d  std\datetime\interval.d  std\datetime\package.d  std\datetime\stopwatch.d  std\datetime\systime.d  std\datetime\timezone.d  std\digest\crc.d  std\digest\sha.d  std\digest\md.d  std\digest\ripemd.d  std\digest\digest.d  std\digest\hmac.d  std\digest\murmurhash.d  std\digest\package.d  std\net\isemail.d  std\net\curl.d  std\range\package.d  std\range\primitives.d  std\range\interfaces.d  std\regex\internal\ir.d  std\regex\package.d  std\regex\internal\parser.d  std\regex\internal\tests.d  std\regex\internal\tests2.d  std\regex\internal\backtracking.d  std\regex\internal\thompson.d  std\regex\internal\kickstart.d  std\regex\internal\generator.d    std\windows\registry.d  std\windows\syserror.d  std\windows\charset.d    std\internal\cstring.d  std\internal\unicode_tables.d  std\internal\unicode_comp.d  std\internal\unicode_decomp.d  std\internal\unicode_grapheme.d  std\internal\unicode_norm.d  std\internal\scopebuffer.d  std\internal\test\dummyrange.d  std\internal\test\range.d  std\internal\digest\sha_SSSE3.d  std\internal\math\biguintcore.d  std\internal\math\biguintnoasm.d  std\internal\math\biguintx86.d  std\internal\math\gammafunction.d  std\internal\math\errorfunction.d  std\internal\windows\advapi32.d  std\experimental\checkedint.d std\experimental\typecons.d  std\uni\package.d    std\experimental\allocator\common.d  std\experimental\allocator\gc_allocator.d  std\experimental\allocator\mallocator.d  std\experimental\allocator\mmap_allocator.d  std\experimental\allocator\showcase.d  std\experimental\allocator\typed.d  std\experimental\allocator\package.d  std\experimental\allocator\building_blocks\affix_allocator.d  std\experimental\allocator\building_blocks\aligned_block_list.d  std\experimental\allocator\building_blocks\allocator_list.d  std\experimental\allocator\building_blocks\ascending_page_allocator.d  std\experimental\allocator\building_blocks\bitmapped_block.d  std\experimental\allocator\building_blocks\bucketizer.d  std\experimental\allocator\building_blocks\fallback_allocator.d  std\experimental\allocator\building_blocks\free_list.d  std\experimental\allocator\building_blocks\free_tree.d  std\experimental\allocator\building_blocks\kernighan_ritchie.d  std\experimental\allocator\building_blocks\null_allocator.d  std\experimental\allocator\building_blocks\quantizer.d  std\experimental\allocator\building_blocks\region.d  std\experimental\allocator\building_blocks\scoped_allocator.d  std\experimental\allocator\building_blocks\segregator.d  std\experimental\allocator\building_blocks\stats_collector.d  std\experimental\allocator\building_blocks\package.d  std\experimental\logger\core.d  std\experimental\logger\filelogger.d  std\experimental\logger\multilogger.d  std\experimental\logger\nulllogger.d  std\experimental\logger\package.d    etc\c\zlib.d  etc\c\curl.d  etc\c\sqlite3.d  etc\c\odbc\sql.d  etc\c\odbc\sqlext.d  etc\c\odbc\sqltypes.d  etc\c\odbc\sqlucode.d  etc\c\zlib\zlib.lib ../druntime/lib/druntime.lib
phobos.lib: Error: ---
ERROR: This is a compiler bug.
Please report it via https://issues.dlang.org/enter_bug.cgi
with, preferably, a reduced, reproducible example and the information below.
DustMite (https://github.com/CyberShadow/DustMite/wiki) can help with the reduction.
---
DMD v2.092.0-125-g3a5f9ffbf
predefs   DigitalMars Windows CRuntime_DigitalMars CppRuntime_DigitalMars LittleEndian D_Version2 all D_InlineAsm D_InlineAsm_X86 X86 Win32 D_ModuleInfo D_Exceptions D_TypeInfo D_HardFloat
binary    dmd\generated\windows\release\32\dmd.exe
version   v2.092.0-125-g3a5f9ffbf
config
DFLAGS    (none)
---

object.Error@(0): Access Violation
----------------
0x00671545 in strlen
0x00671A60 in vsnprintf
0x005A6301 in nothrow void dmd.errors.verrorPrint(ref const(dmd.globals.Loc), dmd.console.Color, const(char)*, const(char)*, char*, const(char)*, const(char)*) at dmd\src\dmd\errors.d(270)
0x005A64D3 in verror at dmd\src\dmd\errors.d(322)
0x004E3CE8 in void dmd.lib.Library.error(const(char)*, ...) at dmd\src\dmd\lib.d(115)
0x00505EA6 in void dmd.libomf.LibOMF.addObject(const(char)[], const(ubyte[])).corrupt(int) at dmd\src\dmd\libomf.d(89)
0x00505D49 in void dmd.libomf.LibOMF.addObject(const(char)[], const(ubyte[])) at dmd\src\dmd\libomf.d(122)
0x00509A02 in int dmd.mars.tryMain(uint, const(char)**, ref dmd.globals.Param) at dmd\src\dmd\mars.d(659)
0x0050A638 in _Dmain at dmd\src\dmd\mars.d(950)
[...]
```

### CODE REVIEW

**Comment by UplinkCoder** [comment]
the length was already passed in?
so it was just a typo?

**Comment by Geod24** [comment]
Oops. Can you also fix https://github.com/dlang/dmd/commit/f8a26fadda0a0f1117598ee3e6046543a4e2b622#diff-13e13bab4b18f823a7f6504c3aad32afR87 ? My bad.

**Comment by MoonlightSentinel** [comment]
Yeah. We should starrt adding `pragma(printf)` to `error` and friends.

**Comment by MoonlightSentinel** [comment]
Also got a test case now

**Comment by kinke** [comment]
Please target stable as this seems to have crept in with v2.092.0 and should be fixed ASAP.

**Comment by MoonlightSentinel** [comment]
Done

**Review by Geod24 — APPROVED** [review]
The single Buildkite error is unrelated (seen in all PRs)

**Pull request merged**
