### PR TITLE
[editions] Make `body` after contract an error

### PR DESCRIPTION
**Pull request by ntrel**
See also: https://github.com/dlang/dmd/pull/16340, https://github.com/dlang/dmd/pull/15612.

### CODE REVIEW

**Comment by ntrel** [comment]
I left `test/compilable/obsolete_body.d` there to check there's no warning for non-edition modules.

**Comment by ntrel** [comment]
`dmd` builds fine, but the unittest is failing for `astbase.d`:
```
src/dmd/parse.d(9592): Error: no property `edition` for `this.mod` of type `dmd.astbase.ASTBase.Module`
src/dmd/astbase.d(1394):        class `Module` defined here
test/unit/parser/test_astbase.d(13): Error: template instance `dmd.parse.Parser!(ASTBase, Lexer)` error instantiating
```
I'm not sure how that should be updated.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
ccing @RazvanN7  for question about ASTBase

**Comment by ntrel** [comment]
I added the edition field to astbase.d and it seems to work.

Some kind of coverage error though:
```
[2024-04-15T10:20:23.037Z] ['info'] Processing /Users/runner/work/dmd/dmd/compiler/src-dmd-astbase.lst...
[2024-04-15T10:20:24.764Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

**Comment by RazvanN7** [comment]
Yes, the field needs to be added to Module just as you did @ntrel . I restarted the coverage failures.

**Review by dkorpel — APPROVED** [review]

**Pull request merged**
