### PR TITLE
Change version string in the backend to D string

### PR DESCRIPTION
**Pull request by jacob-carlborg**
~~Depends on https://github.com/dlang/dmd/pull/9514.~~

### CODE REVIEW

**Comment by Geod24** [comment]
Why does `out_init_config` needs to be `extern (C)` ?
Feels quite weird to have an `extern(C)` function accepting a D array...

**Comment by jacob-carlborg** [comment]
> Why does out_init_config needs to be extern (C) ?

Because it used to be `extern (C++)` but that cannot mangle D arrays. The function is declared here again [1] instead of imported. I'm not sure if it's ok to import instead.

[1] https://github.com/dlang/dmd/blob/18b065bdfa7de2f3382f16bf7debb9316ed5e10d/src/dmd/dmsc.d#L48

**Comment by Geod24** [comment]
@jacob-carlborg : Correct me if I'm wrong, but it is not callable from C / C++ since it uses D arrays. Hence, can't it just be `extern(D)` ?

**Comment by jacob-carlborg** [comment]
I don't want to use `pragma(mangle)` but if it's allowed to import `dmd.backend.backconfig` then I can change it to be `extern(D)`.

**Comment by jacob-carlborg** [comment]
> You've likely already broken something by changing from extern(C++) to extern(C) anyway (where's the header update?)

There are no headers to update. I cannot find either `out_config_init` or `Config` in any header files.

> it would seem that dmd and dmc are at a point where you can drop extern(C++) and/or (C) in most or all backend dmd modules now.

I think so as well. But that would either require to use `pragma(mangle)` or use an import. I don't want use `pragma(mangle)` and I've asked several times if it's ok to use an import. But I haven't got any replies on that.

**Comment by Geod24** [comment]
@jacob-carlborg : Ah right, I missed the point about the double declaration. That "makes sense" then. Import would still be better, but let's wait for an answer...

**Pull request merged**
