### PR TITLE
Don't generate code for compile-time only functions

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Comment by thewilsonator** [comment]
is it possible to test this?

**Comment by UplinkCoder** [comment]
@thewilsonator not on it's own. 
There is a work in progress PR however that want's to use this.
https://github.com/dlang/dmd/pull/11101

**Comment by MoonlightSentinel** [comment]
Maybe add a `dshell`tests that compiles a compile-time only function and dump the symbols of the generated binary using `nm`?

**Comment by UplinkCoder** [comment]
There's no way to mark functions compile-time only in the current language. 
But it's going to come.

**Comment by adamdruppe** [comment]
Interestingly, two of the three mentions of this flag in dmd right now has this comment:

            funcdecl.flags |= FUNCFLAG.compileTimeOnly; // don't emit code for this function

and

    compileTimeOnly  = 0x100,  /// is a compile time only function; no code will be generated for it


Looks like people assumed this was already the behavior!

It appears its only actual use right now is when generating a closure, it won't emit the _d_allocmemory reference in response to someone filing a -betterC bug.

**Comment by MoonlightSentinel** [comment]
I'm not sure that this patch is necessary (unless i got the dmd code/docs wrong). 

Consider this example:
```
int foo(T)()
{
    return cast(int) T.sizeof;
}

enum e = __traits(compiles, foo!int());
```
`foo!int` is marked as `compileTimeOnly` because it's inside of `__traits(compiles, ...)` here:

https://github.com/dlang/dmd/blob/804b9b3f9486294a4a81354fdb28840502047ffa/src/dmd/dsymbolsem.d#L3238-L3239

```
dmd -c ./sample.d && nm sample.o
0000000000000000 t 
0000000000000000 R _D6simple12__ModuleInfoZ
                 U __start_minfo
                 U __stop_minfo
                 U _d_dso_registry
```

`foo!int` isn't emitted into the object file...

**Comment by UplinkCoder** [comment]
@MoonlightSentinel It is needed for type functions.
and `assert(__ctfe)` (when I revive that).

That's because you're using the template in a specutlative context.
The templates instance in not generated for a diffrent reason.

**Comment by MoonlightSentinel** [comment]
> @MoonlightSentinel It is needed for type functions.
> and `assert(__ctfe)` (when I revive that).

Okay. I'm a little concerned that this adds dead code which might (or might not) be used later instead of including it in the PRs relying on this change.

**Comment by thewilsonator** [comment]
@UplinkCoder I think the examples posted by @MoonlightSentinel would suffice for testing this. It would be good to move forward with this. Also rebasing will probably get rid of the buildkite failure.

**Comment by wilzbach** [comment]
Is this still necessary and being worked on it?

**Comment by UplinkCoder** [comment]
It would be nice to have.
The discussion is in a stalemate though I think.

**Pull request closed without merging**
