### PR TITLE
Trivial: fix comments, C++ anachronisms

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by yebblies** [comment]
Same objection here.  The rest of the updates look fine.

**Comment by andralex** [comment]
Will pull this, but I have a different objection - commented-out code for debugging doesn't seem like the best way to go about it, though I understand its practicality. Would be overkill to `version` this stuff in/out?

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
`version(none)` is good for multiline debug printf's, but for one liners it is overkill and annoying.

**Pull request merged**
