### PR TITLE
fix Issue 20441 - Wrong code with -O -fPIC and pointer subtraction

### PR DESCRIPTION
**Pull request by WalterBright**
This is marked as critical in bugzilla.

### CODE REVIEW

**Comment by thewilsonator** [comment]
So, stable?

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
Sigh. Once again, rebasing to stable is blocking on circleci:
```
+ RDMD=/home/circleci/dlang/dmd-2.079.1/linux/bin64/rdmd
./.circleci/run.sh: line 116: MODEL: unbound variable
```

**Comment by WalterBright** [comment]
@thewilsonator can you please find out what is wrong with circleci? Thanks!

**Comment by thewilsonator** [comment]
I'll swap ya making sin and cosine intrinsics for single and double precision.

**Comment by thewilsonator** [comment]
https://github.com/dlang/dmd/pull/10662

**Comment by wilzbach** [comment]
Rebased to upstream/stable for you.

**Comment by WalterBright** [comment]
@wilzbach I thought I had rebased it to stable. I followed the directions above. What did I do wrong?

(and thanks for getting this merged, it was causing Dunnhumby problems)

**Comment by thewilsonator** [comment]
He rebased it on top of #10662 which fixed the CircleCI problems.

**Pull request merged**
