### PR TITLE
convert tocvdebug.c to D

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
Blocked by https://github.com/dlang/dmd/pull/6179

**Comment by WalterBright** [comment]
Blocked by https://github.com/dlang/dmd/pull/6181

**Comment by andralex** [comment]
diff's heroic efforts to figure out minute differences are interesting

**Comment by WalterBright** [comment]
It's interesting to see how close the languages can be.

**Pull request merged**
