### PR TITLE
fix SIGFPE caused by integer division overflow `sinteger_t.min / (-1)` in constant folding

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by WalterBright** [comment]
I'm not sure how integer division produces a floating point exception?

In any case, this needs a test case.

**Comment by MaskRay** [comment]
The `Mod` function already checks for integer division overflow but the `Div` function didn't, I just copied the code. See http://stackoverflow.com/questions/17176221/is-int-min-1-defined-behavior-in-c for details.
```c
        if (n2 == -1 && !type.isunsigned())
        {
            // Check for int.min % -1
            if (n1 == 0xFFFFFFFF80000000UL && type.toBasetype().ty != Tint64)
            {
                e2.error("integer overflow: int.min % -1");
                n2 = 1;
            }
            else if (n1 == 0x8000000000000000L) // long.min % -1
            {
                e2.error("integer overflow: long.min % -1");
                n2 = 1;
            }
        }
```

**Comment by MartinNowak** [comment]
SIGFPE is triggered on divide by zero as well and is used for any arithmetic errors.
[The GNU C Library: Program Error Signals](https://www.gnu.org/software/libc/manual/html_node/Program-Error-Signals.html#index-SIGFPE)

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
