### PR TITLE
add MOVSXb, MOVSXw, MOVZXb, MOVZXw

### PR DESCRIPTION
**Pull request by WalterBright**
Replace hardcoded numbers with mnemonics for these opcodes.

Saves me from constantly checking them.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
buildkite pbackus/sumtype appears to have been recently broken.

**Comment by wilzbach** [comment]
> buildkite pbackus/sumtype appears to have been recently broken.

See https://github.com/dlang/dmd/pull/11650

**Comment by wilzbach** [comment]
> buildkite pbackus/sumtype appears to have been recently broken.

Buildkite "unbreaker": https://github.com/dlang/phobos/pull/7611

**Comment by WalterBright** [comment]
Thanks @wilzbach good work!

**Pull request merged**
