### PR TITLE
Issue 7903 - Public field members should not be allowed in synchronized classes.

### PR DESCRIPTION
**Pull request by ghost**
https://d.puremagic.com/issues/show_bug.cgi?id=7903

### CODE REVIEW

**Comment by andralex** [comment]
We should merge this. @AndrejMitrovic could you please rebase. Thanks!

**Comment by AndrejMitrovic** [comment]
Will do tonight, stay tuned.

**Comment by andralex** [comment]
Thanks!

**Comment by AndrejMitrovic** [comment]
Looks like it's beginning to pass!

**Pull request closed without merging**
