### PR TITLE
dtoh: Emit _d_dynamicArray template which represents slices

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Since slices are a central building block of D, they should also be easily accessible from C++.

CC @ibuclaw 

----
Questions:

- Should `_d_dynamicArray` define addtional functions, e.g. `operator[]`?
- Should `_d_dynamicArray` be hidden behind an `#if !defined(...)` to allow custom definitions?

### CODE REVIEW

**Comment by thewilsonator** [comment]
See also https://github.com/thewilsonator/interop/blob/master/c%2B%2B/dslice.h

@jacob-carlborg which were the PRs we tried to add this in?

**Comment by ibuclaw** [comment]
> See also https://github.com/thewilsonator/interop/blob/master/c%2B%2B/dslice.h
> 
> @jacob-carlborg which were the PRs we tried to add this in?

That would have been my next thought.  I know we use `DArray` and `DString` internally within dmd.  But maybe something like `_d_dynamicArray` would be a bit less generic and stick out more.

**Comment by jacob-carlborg** [comment]
https://github.com/dlang/dmd/pull/8120

**Comment by ibuclaw** [comment]
> #8120

To make it clear, dtoh only deals with fields, not parameters.

**Comment by MoonlightSentinel** [comment]
> That would have been my next thought. I know we use `DArray` and `DString` internally within dmd. But maybe something like `_d_dynamicArray` would be a bit less generic and stick out more.

Fine by me

**Comment by MoonlightSentinel** [comment]
Made a few adjustments:
- use `_d_dynamicArray` instead of `DArray`
- allow custom implementations by defining `CUSTOM_D_ARRAY_TYPE`
- add `operator[]`  with bound checks (up for debate).

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
