### PR TITLE
Rename 'autotester' target to 'auto-tester-build'

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by braddr** [comment]
and the auto-tester-test target?

**Comment by yebblies** [comment]
What would that look like for dmd's makefile?  Are you talking about running the test suite or something else?

**Comment by braddr** [comment]
Oh, right.. I was extrapolating to druntime and phobos which have a unittest target.  dmd doesn't, but should utilize the top level make file standard layout, but that's a different battle.  Though if we're in the middle of such a change, might be worth considering for now too.  Thoughts?

**Comment by WalterBright** [comment]
I'm confused, @braddr and @yebblies 

Should I pull this or not? :-)

**Comment by yebblies** [comment]
> Oh, right.. I was extrapolating to druntime and phobos which have a unittest target. dmd doesn't, but should utilize the top level make file standard layout, but that's a different battle. Though if we're in the middle of such a change, might be worth considering for now too. Thoughts?

IIRC it's fairly complicated to get the test suite running on windows, requiring cygwin and gmake and other stuff.  I'd prefer to leave this to later, and just get the basic dmd target in first.

> I'm confused, @braddr and @yebblies
>
Should I pull this or not? :-)

Can't hurt.

**Comment by braddr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks.

**Pull request merged**
