### PR TITLE
[WIP] Implement DIP 1044

### PR DESCRIPTION
**Pull request by UplinkCoder**
This is supposed to implement the additions needed for enum type inference.
It has been a while since I last touched the codebase so it might be somewhat suboptimal.

### CODE REVIEW

**Comment by nordlow** [comment]
Why the adding of `InferenceExp`?

**Comment by UplinkCoder** [comment]
Well the `$Identifier` is a new syntactic constructs, it names a name.
I opted for inferenceExp since you can see `$` as a top-down inference operator.

**Comment by ichordev** [comment]
I broke it! :fearful:

**Comment by dkorpel** [comment]
DIP 1044 has been rejected: https://forum.dlang.org/thread/fdxkixkcgzrxveayybel@forum.dlang.org

**Pull request closed without merging**
