### PR TITLE
fix Issue 15015 - Win64: interop with C/C++ fails if function return value is a struct of size 8

### PR DESCRIPTION
**Pull request by rainers**
structs of size 8 are returned in register

https://issues.dlang.org/show_bug.cgi?id=15015

### CODE REVIEW

**Comment by rainers** [comment]
Test fails due to https://issues.dlang.org/show_bug.cgi?id=15018. I could make the tests pass by increasing the size of the struct in compilable/ice11596.d, but I guess that's not how we should deal with this.

**Comment by rainers** [comment]
Fix for https://issues.dlang.org/show_bug.cgi?id=15018 is merged, this is now ready, too.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by rainers** [comment]
Thanks. I opened https://github.com/D-Programming-Language/dmd/pull/5260 to take advantage of this to build a 64-bit ddmd.

**Pull request merged**
