### PR TITLE
Rename c => cpp

### PR DESCRIPTION
**Pull request by deadalnix**
As per title.

### CODE REVIEW

**Comment by yebblies** [comment]
Urrgh no.

**Comment by deadalnix** [comment]
Arrrrgh YES !

 - This is recurring request
 - This is a low cost change as git is capable of tracking the move (it won't break all existing PR or history).

**Comment by yebblies** [comment]
- Breaks all existing tools/scripts/ide configs
- I have no faith it won't screw up all the existing PRs

**Comment by deadalnix** [comment]
I'm sorry, but that bonk :
 - The current state is screwing with tools/script/IDE configs and that is exactly why the suggestion come up again and again.
 - Engineering is not a faith based discipline.

**Comment by yebblies** [comment]
So, where's the proof it won't screw up PRs?

**Comment by deadalnix** [comment]
Try it yourself :
git checkout -b pr1
# edit file1 and change something in it
git commit -a -m pr1
git checkout master
git checkout -b pr2
git mv file1 file123
git commit -a -m pr2
git checkout pr1
git rebase pr2

Et voila.

**Comment by yebblies** [comment]
I did, and indeed it works.  I withdraw that argument, although I do remember having problems in the past with something like this.

Still, I think this is a waste of time.

**Comment by John-Colvin** [comment]
Yes please, let's do this. There are tools out there that have real problems with c++ in .c files.

**Comment by justanotheranonymoususer** [comment]
Speaking of file extensions, what about .d? @yebblies, how is **DDMD** doing?

**Comment by yebblies** [comment]
We're one fix away from complete autotester support!

**Comment by WalterBright** [comment]
Note that this change completely disrupts D1 and DMC++, which share the back end with DMD. I oppose it.

**Comment by deadalnix** [comment]
I'm not sure what is the deal with D1, but I didn't renamed backend files to not disrupt DMC++ on purpose.

**Comment by schveiguy** [comment]
Why not write a script that takes the existing code and renames all the files? We can include this script in the distribution so those who have IDEs that whine about .c files can fix their code before developing.

I will note that I support the change, but it doesn't look likely to happen.

**Comment by kuettler** [comment]
You do not earn the full extension if you disable exceptions and rtti. `;)`

No, really, `dmd` has dignity. Those files are more than mere bytes. Those names are proud names. There is history to each and every one. Many a man has touched those files. Show a little respect.

**Comment by justanotheranonymoususer** [comment]
> We're one fix away from complete autotester support!

I guess it's (hack-)fixed now? What's the next step?

**Comment by yebblies** [comment]
> I guess it's (hack-)fixed now? What's the next step?

AFAIK ddmd debug build will work on all platforms once the windows config file issues are fixed, and the host compiles are updated to include the va_copy fix.

The next step then is to get magicport into master, and make it part of the default build.  Then we can switch, once everybody is happy with the build process and performance.

**Comment by jacob-carlborg** [comment]
@WalterBright note that this is deprecated in Clang:

```
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
```

**Comment by justanotheranonymoususer** [comment]
Perhaps it's easier to rename from .c to .C?

**Comment by deadalnix** [comment]
So, this is getting in after the release ?

**Comment by yebblies** [comment]
> So, this is getting in after the release ?

After the 2.999 release.

**Comment by ibuclaw** [comment]
We plan on doing this for D3. :)

**Comment by nordlow** [comment]
For all you Emacs users

```Emacs-Lisp
(add-to-list 'auto-mode-alist
             '("PATH_TO_DMD/src/.*\\.[ch]\\'" . c++-mode))
```

**Comment by MartinNowak** [comment]
> makes life a bit more bearable ;)

Never noticed that it was running as c-mode.

**Comment by lionello** [comment]
With DDMD on the horizon, I think we can safely close this one. No?

**Comment by yebblies** [comment]
Yeah.

**Pull request closed without merging**
