### PR TITLE
[stable] Fix little C++ header regression

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Hmm, semapore sems awol.

**Comment by kinke** [comment]
I think just like last time, when I failed to find the option in GitHub UI to create the tiny branch on my repo instead of here upstream.

**Comment by Geod24** [comment]
I pressed the magic button and it should work now.

**Comment by Geod24** [comment]
But it'd be great if we could avoid using the web UI, as the (unchangeable) default of creating branches in upstream is quite inconvenient.

**Pull request merged**
