### PR TITLE
Pull OutBuffer into dmd.common and use it from both frontend and backend

### PR DESCRIPTION
**Pull request by andralex**
This eliminates the duplication between `OutBuffer` (frontend) and `Outbuffer` (backend), which is exacerbated by the addition of memory-mapped files.

Going forward modules in `dmd.common` can be used across both frontend and backend.

### CODE REVIEW

**Comment by andralex** [comment]
I'll add commits in such a way that the initial commit contains all the drudgery. The others can be reviewed against the first so the differences are easily visible.  [Example](https://github.com/dlang/dmd/pull/12832/commits/968611d05ebcf5600ed9ea85ce092bf3cb8a2bf3).

**Comment by thewilsonator** [comment]
Nice! I would have expected a large section of red in the backend removing the backend's out buffer, although this is WIP so I understand.

**Comment by thewilsonator** [comment]
(resolved merge conflict)

**Comment by UplinkCoder** [comment]
Isn't root already common to dmd and the backend?

**Comment by thewilsonator** [comment]
```
/home/runner/work/dmd/dmd/dmd/src/tests/cxxfrontend.c:20:10: fatal error: root/outbuffer.h: No such file or directory
   20 | #include "root/outbuffer.h"
```

**Comment by andralex** [comment]
> Isn't root already common to dmd and the backend?

Per @WalterBright there's no dependency of the backend on `dmd.root`. I should have verified:

```
$ git grep 'dmd\.root'
aarray.d:21:    import dmd.root.hash;
bcomplex.d:12:public import dmd.root.longdouble : targ_ldouble = longdouble;
bcomplex.d:15:    private import dmd.root.longdouble : fabsl, sqrt; // needed if longdouble is longdouble_soft
cdef.d:259:public import dmd.root.longdouble : targ_ldouble = longdouble;
cg87.d:663:        import dmd.root.longdouble;
elem.d:69:    import dmd.root.longdouble;
evalu8.d:1984:    import dmd.root.longdouble : fabsl; // needed if longdouble is longdouble_soft
fp.d:19:    import dmd.root.longdouble;
$ _
```

@WalterBright please advise.

**Comment by thewilsonator** [comment]
Yeah, I ran into those trying to compile DMD on macOS AArch64 (see https://github.com/dlang/dmd/pull/12764).

**Comment by Geod24** [comment]
Shouldn't the backend's `outbuffer` copy be removed ? Also I expect this will create issues with DMC.
I am more than happy with the direction here though, if it gets accepted by the BDFL.

Although note that `root` was supposed to be `common`. I don't see the point of introducing the new package, but if that's what it takes...

> Per @WalterBright there's no dependency of the backend on `dmd.root`.

Are you referencing [this discussion](https://forum.dlang.org/post/s8ftnv$aoq$1@digitalmars.com) ?

> To be a little clearer, if the files are all merely reshuffled into various packages, then they all violate the rule:
>
> *** Never import a file from an uplevel directory ***
> 
> and understanding is not increased at all. And it isn't even just an uplevel directory, it's up then sideways then down.

This is still a sideway import.

**Comment by andralex** [comment]
> Shouldn't the backend's `outbuffer` copy be removed ?

Yah, I plan to replace its uses incrementally and then eliminate it. That should make testing smooth (lesson learned with the mmfiles...).

> Also I expect this will create issues with DMC.

I'd need to hear more about that.

> I am more than happy with the direction here though, if it gets accepted by the BDFL.
> 
> Although note that `root` was supposed to be `common`. I don't see the point of introducing the new package, but if that's what it takes...

We'll see. It's actually simpler to keep `OutBuffer` in `root` and keep it there. However, `root` is already populated with a bunch of stuff that I assume has no place in the backend, so incrementally building `common` separately may make sense. We'll see.

> > Per @WalterBright there's no dependency of the backend on `dmd.root`.
> 
> Are you referencing [this discussion](https://forum.dlang.org/post/s8ftnv$aoq$1@digitalmars.com) ?
> 
> > To be a little clearer, if the files are all merely reshuffled into various packages, then they all violate the rule:
> > *** Never import a file from an uplevel directory ***
> > and understanding is not increased at all. And it isn't even just an uplevel directory, it's up then sideways then down.
> 
> This is still a sideway import.

The view "Never import a file from an uplevel directory" or "Never import a file from an uplevel directory and then sideways" comes straight from a "high level modules depend on low level modules and low level modules should not depend on high level modules" viewpoint. The sideways part is "low level modules should not depend on other low level modules". 

All of these are fallacious as explained by Robert Martin, so these points will be dismantled in good order.

High level modules and low level modules should depend on abstractions. `OutBuffer` is an abstraction. Both front end and back end can depend on it appropriately. Putting `OutBuffer` here or there is potayto-potahto.

As that book from Harvard on negotiation says: don't argue your point. Don't argue against the other person's point. By everything sacred don't argue against the other person's character. 

Argue the principle. And you will win.

**Comment by WalterBright** [comment]
> I should have verified

I keep removing them and they keep creeping back in.

**Comment by kinke** [comment]
The `dmd.common.outbuffer` module still imports `import dmd.root.{file,rmem,rootobject,string}`, so moving it alone still increases the backend dependencies on `dmd.root`.

**Comment by andralex** [comment]
Reached an impasse with integrating `Out[Bb]uffer` across the backend and the rest of the project. The backend edition of the Outbuffer uses a pointer to buffer as a member, and exposes it as part of the public interface. The backend saves the address of that pointer in `TInfoPair`, which it subsequently puts in a hashtable `AApair`. The double pointers are quite nasty but the whole thing works and is used (according to the doc) by the C++ interface.

This makes it impossible to use `OutBuffer` instead of `Outbuffer` because the former uses a `ubyte[]` instead of a pointer, which makes it impossible (or at least nefarious) to tease out the address of the pointer to data. The cast needed would be something like `(cast(ubyte**) &a) + 1` and could break spectacularly if we ever change the array layout. I think I'll do this as a bridge but I'm hoping to get fresh ideas on how to avoid it. Thanks.

**Comment by dkorpel** [comment]
> The cast needed would be something like `(cast(ubyte**) &a) + 1` and could break spectacularly if we ever change the array layout.

I might be missing something, but isn't this simply `a.ptr` or `&a[0]`?

**Comment by andralex** [comment]
> > The cast needed would be something like `(cast(ubyte**) &a) + 1` and could break spectacularly if we ever change the array layout.
> 
> I might be missing something, but isn't this simply `a.ptr` or `&a[0]`?
> Edit: `&a.ptr` or `&&a[0]`.

Those don't compile.

**Comment by dkorpel** [comment]
> Those don't compile.

That `&a.ptr` doesn't compile surprises me a little, from the error message:

> Error: `cast(int*)a` is not an lvalue and cannot be modified

It does not seem intentional, but a consequence of the lowering. Anyway, it might be best to destructure the `private ubyte[] data` into separate `ptr` and `length` fields then.

**Comment by andralex** [comment]
This has reached its goal and is ready for review. There are a number of items left to do, e.g. some duplication of string and file functions. Will take care of those in good time.

**Comment by thewilsonator** [comment]
Yes please rewrite the commit history to reflect the after the fact view of what has changed. Also if possible split the `root.file->common.file` change into a separate PR or do a commit so that it gets picked up as a file move and rename not an addition and deletion.

**Comment by Geod24** [comment]
> Great, editing the history introduced a bug in mscoff generation. Guess I need to do it all over again. Woe is me.

Just in case this becomes useful for anyone:
If it's purely history re-org, you should be able to `git diff $OLD_COMMIT $NEW_COMMIT` and see nothing.
`$OLD_COMMIT` should stay alive for about 30 days (IIRC) and you can find it in `reflog`.

**Review by Geod24 — COMMENTED** [review]
Thanks, it is much, much easier to review! Made a lot of comments, but they are mostly repetitive. The commit named "Remove dependencies of dmd.common.outbuffer on dmd.root" puzzles me a bit, as it doesn't to be doing this (e.g. I don't see any diff on `outbuffer.d`, only on file-related modules).

**Comment by andralex** [comment]
@Geod24 thanks for reviewing, need to get some shuteye but will act on the good stuff tomorrow.

**Comment by WalterBright** [comment]
> Per @WalterBright there's no dependency of the backend on dmd.root. I should have verified:

I regularly remove them, and they resprout like Himalayan blackberry bushes.

**Review by WalterBright — CHANGES_REQUESTED** [review]
Most important issues:
1. no null checks on malloc calls
2. use of obsolete `A` Windows APIs

**Comment by WalterBright** [comment]
See Phobos for how to convert D strings to Windows W strings.

**Comment by andralex** [comment]
@WalterBright I made the requested changes and also asked a couple of questions - thanks!

**Review by WalterBright — APPROVED** [review]

**Pull request merged**
