### PR TITLE
support integer simd inequality comparison

### PR DESCRIPTION
**Pull request by WalterBright**
!= isn't directly supported by the SIMD instructions, have to do an XOR

### CODE REVIEW

**Comment by WalterBright** [comment]
It appears that the auto-tester is dead in the water.

**Comment by ibuclaw** [comment]
Same as #14545, does non-boolean comparisons even make sense?  Especially as this differs from static array comparison as well.

I'm pretty sure there are some who are already relying on vector == vector => bool in the wild.  I've had at least one person ask me about it when they once compared ldc and gdc.
https://d.godbolt.org/z/7M9Mch3rb

**Comment by WalterBright** [comment]
> does non-boolean comparisons even make sense?

1. SIMD has a suite of instructions (PCMPxx) to do this
2. gcc does it
3. prior to this PR, dmd issued an error for attempting to use == and != for a vector
4. it's used for branchless high speed vector conditional logic, popularized by APL long ago

```
typedef int int4 __attribute__ ((vector_size (16)));
int4 test(int4 x, int4 y) {    return x == y; }
```
```
gcc test2.c -c
obj2asm test2.o
                push    RBP
                mov     RBP,RSP
                movdqa  -010h[RBP],XMM0
                movdqa  -020h[RBP],XMM1
                movdqa  XMM0,-010h[RBP]
                pcmpeqd XMM0,-020h[RBP]   <= vector result!!!
                pop     RBP
                ret
```

**Comment by WalterBright** [comment]
BTW, the old behavior is retained with the `[ ]` operator:
```
x[] == y[]
```

**Comment by WalterBright** [comment]
I did not know that gdc and ldc implemented these operators. Thanks for letting me know. The path forward looks like gdc and ldc recommending that `x == y` be rewritten as `x[] == y[]` and undergoing a deprecation period.

**Comment by ibuclaw** [comment]
> I did not know that gdc and ldc implemented these operators.

I expose vector mask operations via intrinsics.  It's less troublesome. Even have ternary support. :-)

https://d.godbolt.org/z/cE8Kjcvcx

**Comment by ibuclaw** [comment]
> gcc does it

I'm not sure copying gcc is necessary the best thing to do here, especially when it comes from changing the semantic meaning of operators through vendor extensions.

> The path forward looks like gdc and ldc recommending that x == y be rewritten as x[] == y[] and undergoing a deprecation period.

It has just occurred to me that generic code will need to be scrutinized as well.
```
bool foo(T)(T a, T b)
    if (__traits(compiles, a != b))
```
I assume this would be a common signature.

**Comment by WalterBright** [comment]
I agree what you've done is a nice workaround. But some issues with it remain:

1. it's out of step with common practice (like what gcc does)
2. infix operators are better than function calls (after all, the comments in the godbolt code show the infix operator version!)
3. intrinsics don't participate in optimizations
4. intrinsics don't participate in CTFE

I understand there will be transition problems. But it's fairly easy to deprecate the `x == y` syntax for a time, suggesting replacing it with `x[] == y[]`.

**Comment by maxhaton** [comment]
> > I did not know that gdc and ldc implemented these operators.
> 
> I expose vector mask operations via druntime simd intrinsics. It's less troublesome. Even have ternary support. :-)
> 
> https://d.godbolt.org/z/cE8Kjcvcx

why are they called xMask rather than just x? AVX512 has a whole register file (PRF even) just for masks (the k registers) for example

**Comment by ibuclaw** [comment]
> > > I did not know that gdc and ldc implemented these operators.
> > 
> > I expose vector mask operations via druntime simd intrinsics. It's less troublesome. Even have ternary support. :-)
> > 
> > https://d.godbolt.org/z/cE8Kjcvcx
> 
> why are they called xMask rather than just x? AVX512 has a whole register file (PRF even) just for masks (the k registers) for example

Because the result is a vector bit mask, not a boolean.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
