### PR TITLE
Simplify parseStorageClasses

### PR DESCRIPTION
**Pull request by benjones**
eliminate gotos, replace duplicate code with static_foreach, remove mutable local variable.  Potentially speed things up by (hopefully) matching multiple STCs per loop iteration

### CODE REVIEW

**Comment by benjones** [comment]
The gdc build fails because it doesn't have static foreach, and it appears after a quick grep that there are no "static foreach"s in src.  Is there a good workaround and/or is that likely to change in the future?

**Comment by ZombineDev** [comment]
As a workaround you can use:
```D
alias Seq(T...) = T;
foreach(name; Seq!("const_", "immutable_", "shared_"))
{ .. }
```

**Comment by Basile-z** [comment]
In a first time wouldn't the simplification work with non-static loops ? You loose the unrolling but once available for gdc this would be very simple to add the `static` to get the stuff unrolled.

**Comment by ibuclaw** [comment]
> Is there a good workaround

Not a workaround, but tuples are better fit for what you're trying to do.

**Comment by benjones** [comment]
I don't think a "dynamic" foreach will work because I'm passing the values to __traits(getMember)?

**Comment by benjones** [comment]
OK, using @ZombineDev 's tuple hack

**Comment by Basile-z** [comment]
> I don't think a "dynamic" foreach will work because I'm passing the values to __traits(getMember)?

the array used as ForeachAggregate would had to be a CT one... but NVM since the other trick will work ;)

**Comment by WalterBright** [comment]
Compiler speed is highly sensitive to lexing/parsing speed. The use of state variables (such as `match`) replacing control flow tends to be slower. It is worthwhile in the lexer/parser to be less concerned with elegance than with every cycle of speed.

The use of switch is almost always faster than a sequence of if statements, because compilers have specialized strategies for generating code for them according to the various patters of case values.

Also, use the form `if (` rather than `if(` to conform to usual practice in DMD sources.

My last objection is while the revised code uses significantly fewer lines, which is good, it's also significantly harder to understand, as it requires a solid understanding of metaprogramming and introspection, while the original code is trivial.

**Comment by benjones** [comment]
I ran a quick benchmark (are there better ones available somewhere?)
HOST_DMD=generated/osx/release/64/dmd /usr/bin/time ./src/build.d -f -j1  

on master: 6.75s, 6.75s, 6.73s real time
on this PR: 6.76s, 6.71s, 6.71s real time

It would appear that this has negligible impact on speed.

Both versions have basically 1 state variable, stc in the original, matched in mine.

Looking at the codegen, the the switch statement is a bunch of cmp, je pairs, so it doesn't look like the compiler is doing anything clever there.

However, my version is about 1.5x as many instructions, which seems to be due to updateStorageClass not being inlined.  Can I do something to suggest/force inlining?  

Because my if statements are sequential, it's possible that fewer loop iterations would be required overall because we can find multiple classes per iteration if the clauses are ordered well.

WRT to the complexity/difficulty of understanding, I have a few rebuttals comments.  
This is a compiler, so presumably people reading/writing code will have a strong grasp of D and its features/idioms.  If Andrei is going to highlight introspection as one of our greatest strengths, let's use it in our most visible software.  

In terms of readability, I think this version makes it more clear that for each of "static, final, auto, etc", we treat them all the same way.  (having access to static foreach would eliminate a bit more ugliness too).  

I appreciate the review.  If you think there's worthwhile stuff here, let me know and I'll fix the spaces.  New habits are hard :)

**Comment by WalterBright** [comment]
> It would appear that this has negligible impact on speed.

Benchmarking this by timing the execution of dmd itself on an untargeted benchmark is unlikely to give useful results: the timing is too coarse, far to many other variables affecting speed is at play, and the test examples are likely testing something else. I've seen many people led astray by this. (The ambiguous nature of the numbers you posted illustrate.) A far better way is to instrument the target code with a high precision timer, and craft a test case that tickles just what is under test.

> Both versions have basically 1 state variable, stc in the original, matched in mine.

The `match` variable is what I was referring to. The reason `goto` was used was to avoid state variables.

> Looking at the codegen, the the switch statement is a bunch of cmp, je pairs, so it doesn't look like the compiler is doing anything clever there.

That's highly dependent on what compiler is used, and the number/density of the case values.

> Can I do something to suggest/force inlining?

The -inline switch when compiling.

> let's use it in our most visible software.

The most visible software is Phobos. You're right that the dmd source should be an example of doing things right, but that doesn't imply finding ways to use every feature of D. In this example, the metaprogramming doesn't work very cleanly because it is all broken up into various sections that do things a little differently. The switch, on the other hand, is a simple (and complete) list of all the tokens that can appear next. It's more comprehensible with less effort on the part of the reader.

**Comment by benjones** [comment]
> Benchmarking this by timing the execution of dmd itself on an untargeted benchmark is unlikely to give useful results: the timing is too coarse, far to many other variables affecting speed is at play, and the test examples are likely testing something else. I've seen many people led astray by this. (The ambiguous nature of the numbers you posted illustrate.) A far better way is to instrument the target code with a high precision timer, and craft a test case that tickles just what is under test.

This was a response to your comment about compiler speed being sensitive to these things, not about microbenchmarking.  Compiling a reasonably sized project seems like a good way to determine whether or not there's a significant performance impact.  I haven't profiled dmd, but I would assume that it doesn't spend a lot of time parsing storage classes.

> > Both versions have basically 1 state variable, stc in the original, matched in mine.
> 
> The `match` variable is what I was referring to. The reason `goto` was used was to avoid state variables.

Not sure I follow?  Both versions have exactly 1 state variable.  

> The -inline switch when compiling.

I assumed that dmd was built with -inline... is it not?

> The most visible software is Phobos. You're right that the dmd source should be an example of doing things right, but that doesn't imply finding ways to use every feature of D. In this example, the metaprogramming doesn't work very cleanly because it is all broken up into various sections that do things a little differently. The switch, on the other hand, is a simple (and complete) list of all the tokens that can appear next. It's more comprehensible with less effort on the part of the reader.

I would say "D's metaprogramming allowed me to remove duplicated code and express a generic operation in a way that would be impossible in many languages".  It's clear we disagree on whether that improves the code.  I'll close the PR

**Pull request closed without merging**
