### PR TITLE
[DSSv3] Fix issue 21637: Allow trailing comma in the ImportList

### PR DESCRIPTION
**Pull request by dorianverna17**
Modified parse.d as to avoid the error of having a trailing comma, used an auxiliary variable

### CODE REVIEW

**Comment by Geod24** [comment]
Please add a test in `tests/compilable/`. See [the README](https://github.com/dlang/dmd/tree/master/test#types-of-tests) and the linked `compilable` README.
Also make sure the website's spec (https://github.com/dlang/dlang.org/tree/master/spec) match the implementation.

**Review by ibuclaw — CHANGES_REQUESTED** [review]
See review comments

**Review by dkorpel — COMMENTED** [review]
There should be a test for `import std.stdio: ;`

**Comment by CyberShadow** [comment]
@WalterBright was opposed to trailing commas in ArgumentList. In ImportList, most of the advantages of trailing commas in ArgumentList do not apply, as you can always just write more `import` lines, so I think this would be an unlikely addition.

**Comment by RazvanN7** [comment]
@CyberShadow Indeed, Walter opposed it but the PR got in and the revert was closed, so right now trailing commas in ArgumentList is a thing. Should we go for consistency or simply close this?

**Comment by CyberShadow** [comment]
I think it would be good if at least such a change would be accompanied by a compelling rationale.

Actually, looking at the bug report, this PR doesn't even change what the bug report is about. The bug report is about the list of modules, but this PR is about the list of symbols imported from a module.

**Comment by RazvanN7** [comment]
@dorianverna17: @CyberShadow is right, the bug report is about importing modules, not importing symbols from modules.

Importing modules:
```d
import module1, module2,;
```

Importing symbols:
```d
import module1: symbol1, symbol2;
```

Although, thinking about it, I would rather close the issue as WONTFIX.

**Pull request closed without merging**
