### PR TITLE
fix samples/dclient so it compiles

### PR DESCRIPTION
**Pull request by WalterBright**
https://issues.dlang.org/show_bug.cgi?id=17099

### CODE REVIEW

**Comment by WalterBright** [comment]
Though to run dclient successfully one needs admin rights.

**Comment by rainers** [comment]
Compiles, but the code doesn't seem to execute correctly. After unloading the DLL nothing is printed anymore. Seems https://issues.dlang.org/show_bug.cgi?id=1550 is back (the workaround helps).

**Comment by rainers** [comment]
I'll merge this and provide a couple of fixes...

**Comment by rainers** [comment]
> I'll merge this and provide a couple of fixes...

https://github.com/dlang/dmd/pull/6700

**Comment by WalterBright** [comment]
> doesn't seem to execute correctly

In order to run it successfully, you need to run it with admin rights. (This was not true of Windows XP.)

**Comment by WalterBright** [comment]
> Seems https://issues.dlang.org/show_bug.cgi?id=1550 is back (the workaround helps).

Windows DLL support breaks regularly because I cannot figure out how to get the tests for it in the test suite. The latest disaster: https://issues.dlang.org/show_bug.cgi?id=17326

**Comment by rainers** [comment]
> In order to run it successfully, you need to run it with admin rights. (This was not true of Windows XP.)

The bug is also there with admin rights.

**Pull request merged**
