### PR TITLE
build samples when the auto tester runs the win32 test suite

### PR DESCRIPTION
**Pull request by rainers**
also fixes htmlget.d

### CODE REVIEW

**Comment by WalterBright** [comment]
Nice! But it fails on windows with:
```
cd samples
f win32.mak
Error: 'f' not found
```

**Comment by rainers** [comment]
It seems $(MAKE) suddenly expands to nothing. I've amended a different version.

**Comment by rainers** [comment]
It's again the auto tester complicating the build with unnecessary patching of makefiles.

**Comment by braddr** [comment]
Sigh, that's likely something I'll need to help handle.  That's one area that I specifically patch on the auto-testers, I believe.  Sorry for the complications, but if it wasn't needed, I wouldn't be doing it.  More later tonight or tomorrow.

**Comment by rainers** [comment]
> Sorry for the complications, but if it wasn't needed, I wouldn't be doing it.

In this case, can't you just add MAKE="gmake -j3" to the command line instead of patching the file?

Even if command line arguments don't work, adding a special target and configuration/code to the standard repo for the auto-tester would be better than patching. I know some defaults in makefiles are bad, but the current way of handling this prevents improvements, e.g. https://github.com/dlang/phobos/pull/2526

**Pull request merged**
