### PR TITLE
Fix 21018 - Don't emit speculative instances even if -allinst is given

### PR DESCRIPTION
**Pull request by UplinkCoder**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
you need to add a "compile"  test case

**Review by ibuclaw — CHANGES_REQUESTED** [review]
Needs a test.

**Comment by UplinkCoder** [comment]
@ibuclaw you beat me by 10 seconds :)

**Comment by NilsLankila** [comment]
THe first time you forgot to add the file maybe ?

**Comment by UplinkCoder** [comment]
oh wow.
So we do relay on emitting speculative instances?

**Comment by ibuclaw** [comment]
> oh wow.
> So we do relay on emitting speculative instances? 

If the issue is that errors are seeping through, perhaps you should check for any recorded errors against the instance (or find out why there is a lack of and fix that instead).

**Comment by UplinkCoder** [comment]
@ibuclaw I was thinking of approaching it the other way.
And find the places where we leave things speculative which should be un-speculated.

**Comment by RazvanN7** [comment]
Closing due to lack of activity. On the bug report there is a link pointing to this issue if anyone is interested in fixing this.

**Pull request closed without merging**
