### PR TITLE
Fix issue 20223 + 20224: Wrong mangling for const reference of callback

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Review by AndrejMitrovic — APPROVED** [review]

**Comment by Geod24** [comment]
Turns out this also fixes issue 20224, so added a test case.

**Comment by thewilsonator** [comment]
Whats with LDC on build kite? That doesn't look related.

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
> Whats with LDC on build kite? That doesn't look related.

Is it failing on another build ? I restarted the build, however, from a quick look, it does look related. 
I'm not familiar with LDC code, but a quick look pointed to [this file](https://github.com/ldc-developers/ldc/blob/13cc3c4ed2f4e77096313916e55ce460f9dd1ddc/dmd/ldcbindings.d). There might be a change in mangling there, which I'll check tonight.

**Comment by Geod24** [comment]
Alright, found the bug: It seems `const` is not correctly handled by the substitution pool (there are some hacks here and there), will look for a proper fix.

**Comment by Geod24** [comment]
> ../driver/main.cpp:1045: error: undefined reference to 'mars_mainBody(Param&, Array<char const*>&, Array<char const*>&)'
 
So many new test cases, great. Glad we have Buildkite. Removed auto-merge not to clog other PRs.

**Comment by thewilsonator** [comment]
Alright, was just adding some priority. Feel free to add it back when you have a solution to the problem.

**Comment by Geod24** [comment]
Added all the test cases and it's all green now

**Pull request merged**
