### PR TITLE
Cleanup traits.d

### PR DESCRIPTION
**Pull request by 9rnsr**
Use D specific features more.
About -100 lines!

### CODE REVIEW

**Comment by yebblies** [comment]
- `collectUnitTests` is now only called from one place and should not be a function
- Renaming `Expression ex2` to `x` is not an improvement and should be removed
- `isX` function's `static if`s need more structure - eg `s` is only declared inside a static if but is referenced outside.
- This should have been multiple pull requests
- The traits lambda stuff looks much better!

**Comment by 9rnsr** [comment]
- `collectUnitTests` has self-recursion, so need to be left as function.
- Reverted.
- It's better than repeating `auto s = getDsymbol(o); if (!s) goto Lfalse;` check tree times.
- No, this PR has only one purpose - cleanup `traits.d` module. Multiple commits are for the different aspects of "cleanup".
- Thanks.

**Comment by AndrejMitrovic** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
@AndrejMitrovic Thanks!

**Pull request merged**
