### PR TITLE
Issue 15258 - Anonymous const union members don't allow for initialization

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=15258

### CODE REVIEW

**Comment by ibuclaw** [comment]
This looks fine to me.

**Comment by AndrejMitrovic** [comment]
Could you add a `fails-compilation` test-case like this first:

```
class C15258
{
    this(const char* result)
    {
        this.result = result;
    }

    void sneaky() { this.mutable_res = "foo".ptr; }  // oops

    union
    {
        const char** results;
        const char* result;
        char* mutable_res;
    }
}
```

IOW _all_ fields of a union should be const if one of them is.

That is _unless_ we're actually ok with circumventing the type system via the use of unions? I mean sure they're a pretty low-level tool so I could swing both ways on this, but I'm not a fan of breaking the type system.

**Comment by 9rnsr** [comment]
@AndrejMitrovic Note that the proposed test case will never be accepted because `"foo".ptr` is `imutable(char)*` and it's not implicitly convertible to `char*`.

> IOW all fields of a union should be const if one of them is.

It's not related with 15258, and current `std.typecons.Rebindable` implementation will be rejected by the behavior completely, so I cannot agree with all of your idea, but I can say it would be still useful under `@safe` code.

**Comment by AndrejMitrovic** [comment]
Ok, makes sense and I agree.

**Comment by AndrejMitrovic** [comment]
Auto-merge toggled on

**Pull request merged**
