### PR TITLE
fix Issue 22115 - Optimize if (s.a == 3 ? s : null) to if (s.a == 3)

### PR DESCRIPTION
**Pull request by WalterBright**
This should make using isXxx() functions cost-free compared with examining the tag.

### CODE REVIEW

**Comment by dkorpel** [comment]
What's the use for this considering DMD releases are built with LDC now? LDC optimizes your test function fine:
```D
void test2(Exp e)
{
    if (e.isAddExp())
        sss();
}
```

```asm
test2:
        test    rdi, rdi
        je      .LBB3_2
        cmp     dword ptr [rdi + 8], 3
        jne     .LBB3_2
        jmp     void example.sss()@PLT
.LBB3_2:
        ret
```

[godbolt link](https://d.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlJvoCqAZ0wAFAB4gA5AAYppAFZdSrZrVAB9LelIj2yAnjqVMtdAGFUrAK4BbWiABMpU%2BgAyeWpgBydgEaYxE7OAA6oQoRGtJY29sphEYZ0Hl6%2BtgFBnAAcupj6SbQMBMzEBDF2Ds56mAZRRSUEKT7%2BgcG6xaXlcZztDU1pGVxZAJS6qNbEyBxSngQA1ELiAKQAzABCSzIAgiHEzMC2zBCerJ6YpHNUbCLDm1sAbqh46AtCQhDDc0sA7GtzX44NoDFqs/j8ACJ3O6YcQEQK0OYQcxLQEotafZCqN5zbDiEJQ353f7/WZzZigqHbYlzR7PS7WWjID5fX4syFU4lUTxsOaecYECBbdDoXEhT54IRCkV45l86zzH5/YiYAgTBHML4rSFauYrTUAMTmLCEAoIAE8QphUFQIMrVcRaMNhgQEBK5iA5rRrKxWKC2QT2VtobD4YjkajARisUI5lLRe6cXiCRtthDKTs9gcjod1OwLijHHCTY4C7dtrSXkWCI4IPHMGWg4SOSSqIjMAA6CVxmVOonU4lvd63dYBu5SUasaQAVnkDlk8lQ0nBC3Gk0wAJWnHkBGkcidpAA1iAVit2yfzxfLwA2FTSbjyWxcGQyUhzuSkRdSeRCEAvnfz0Y4FgJA0FsEI8HYMgKAgUDwMgkBWHQZBOA0RxeC5Vg4WIH8ID8Xd5D8bliDNaQt1IUDbFMAgAHlaFYEj51ILAc2Adh8KYvBlVqe5MB/RiYRqeVpjI2Y8nY04/D2YjLCwdiCGIPBHykLdRn4RgWDYng%2BDoAhhDESRGKUHpVHUEAtA0HQJJ/SBRlQEICj4gBaai5kcgICCw8xvzyGoChMMwugcThnFcfoWiCRwAE5SASSI6EC%2BJwji2gwvSVpHCqHzajoepOisCouEy/I6g6RozgGdLopNBoEp6arSlSwYMtGIRVymLgJ2nWd2M/RDkDmTh2zQ9sZERXBCBIDcejmSwwIgwIps%2BcFt3w/cEEwZgsCCD5D2PU9LwO88b0nKR71fHrpG/X9SH/PdSCAxAUFQObIPIShYPmoJ0FsdBHFoPBgAQAh6L4CCsJwvDGMI2gSgYsiKKo2j6PY5i1FY6Z33wLjDB4vj3wE5AhNI%2BRRJO98JKks0ZIx7cFKUlTtPoJg2A4LS1L0iR2KUZwTM0bQVDwPxrJ2uyHOkZzXJOM5XPczzvOK4wIFcBKVhCsxGtabhotigoVdCJKCg1oItdyBXClKvXTd8kq%2BnK8KQBN%2BqynyuJVd6Bq7bS43IpatrWc6qQZ3OxjP2%2Bl5/sB4GzTG/AiGIKaLlmuCFpRVWlpWgDRiPE8z0Og7b1O7qQ8u3Rrtu8cA8cIv30/DO91GHjsKiB2gA%3D%3D)

**Comment by WalterBright** [comment]
If it's a common enough pattern that ldc recognizes it, then there's value in implementing it.

**Comment by dkorpel** [comment]
> If it's a common enough pattern that ldc recognizes it, then there's value in implementing it.

I suspect LLVM applies transformations that are far more general than the specific test case of this PR, e.g:
```D
    final int isAddExp() inout { 
        return a == 3 ? a : 0;
    }
```
This also gets optimized to `a == 3` by LDC, while DMD still checks `a != 0` after checking `a == 3`. Since the code in this PR looks for pointers, it won't improve this case. I don't think it's bad to improve the DMD backend in general, but new transformations are risky and this PR looks like a patch catered to a specific pattern seen in DMD's source code, so if this won't speed up DMD releases, I think the optimization should be made more widely applicable.

**Comment by WalterBright** [comment]
@dkorpel doing the general case requires adding a data flow analysis pass, which I can do but is significantly more work (and if you're worried about risk, there's correspondingly more of that).

https://issues.dlang.org/show_bug.cgi?id=22116

Is this pattern only in dmd? I have no idea. But it's just a couple lines of code, why not do it?

**Comment by WalterBright** [comment]
BTW, the whole point of having a test suite is so we can make changes. We can't not make improvements to code generation and worry about breaking things.

**Comment by WalterBright** [comment]
semaphoreci:
```
../_generated/linux/release/32/host_dmd -of../generated/build -g build.d
make: *** [../generated/build] Segmentation fault
```
???

**Comment by MoonlightSentinel** [comment]
> ???

The generated DMD segfaulted while building `build.d`, meaning that this PR introduces a regression.

**Comment by WalterBright** [comment]
Why does it not fail on *any* of the other tests? What's different about semaphoreci?

**Comment by MoonlightSentinel** [comment]
Semaphore uses the current compiler to rebuild itself (including `build.d`). The other CI only build those using the host compiler IIRC.

**Comment by WalterBright** [comment]
It would be nice if when I clicked on "Details" if it would come up with some description of what it is trying to do. The same for the other checks. And each major step in the log files.

**Comment by dkorpel** [comment]
> @dkorpel doing the general case requires adding a data flow analysis pass, which I can do but is significantly more work (and if you're worried about risk, there's correspondingly more of that).

I'm not asking you to, I just guessed that you made this PR because you're worried your recent refactoring of dangerous casts in DMD would introduce a performance regression. If the goal is to improve the backend's general codegen quality instead, I think there's more leverage to be gained from a few powerful transformations than a long list of situational transformations. If you think this is useful on its own, I'm not objecting to adding it. After all, you're the one with experience in the backend. :slightly_smiling_face:

**Comment by MoonlightSentinel** [comment]
Built dmd using the current revision (e3fe38b67bd672b4984e893522fdc06f527fc054) with enabled optimisations. The resulting binary segfaults even for an empty file:
```
gdb --batch -ex r -ex bt --args ../generated/linux/release/64/dmd -c empty.d

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555594870d in _D3dmd9dtemplate19TemplateDeclaration6__ctorMFKxSQBv7globals3LocCQCl10identifier10IdentifierPSQDo4root5array__T5ArrayTCQEnQEm17TemplateParameterZQBiCQFr10expression10ExpressionPSQGuQDgQDe__TQDbTCQHl7dsymbol7DsymbolZQEabbZCQImQIlQIe ()#0  0x000055555594870d in _D3dmd9dtemplate19TemplateDeclaration6__ctorMFKxSQBv7globals3LocCQCl10identifier10IdentifierPSQDo4root5array__T5ArrayTCQEnQEm17TemplateParameterZQBiCQFr10expression10ExpressionPSQGuQDgQDe__TQDbTCQHl7dsymbol7DsymbolZQEabbZCQImQIlQIe ()
#1  0x0000555555a92b80 in _D3dmd5parse__T6ParserTSQw10astcodegen10ASTCodegenZQBk17parseDeclarationsMFbPSQCyQCx__T16PrefixAttributesTQDfZQxPxaZPSQEm4root5array__T5ArrayTCQFl7dsymbol7DsymbolZQBc ()
#2  0x0000555555a7f6d5 in _D3dmd5parse__T6ParserTSQw10astcodegen10ASTCodegenZQBk13parseDeclDefsMFiPCQCu7dsymbol7DsymbolPSQDpQDo__T16PrefixAttributesTQDwZQxZPSQFa4root5array__T5ArrayTQDfZQl ()
#3  0x0000555555a7ed92 in _D3dmd5parse__T6ParserTSQw10astcodegen10ASTCodegenZQBk11parseModuleMFZPSQCs4root5array__T5ArrayTCQDr7dsymbol7DsymbolZQBc ()
#4  0x0000555555902536 in _D3dmd7dmodule6Module__T11parseModuleTSQBl10astcodegen10ASTCodegenZQBrMFZCQCuQCtQCo ()
#5  0x00005555558ffee7 in _D3dmd7dmodule6Module4loadFSQBa7globals3LocACQBr10identifier10IdentifierQBcZCQCxQCwQCr ()
#6  0x00005555558d8c99 in Import::load(Scope*) ()
#7  0x00005555558d8d7a in Import::importAll(Scope*) ()
#8  0x00005555558d9431 in Import::setScope(Scope*) ()
#9  0x00005555559008da in Module::importAll(Scope*) ()
#10 0x00005555558d8dae in Import::importAll(Scope*) ()
#11 0x00005555558d9431 in Import::setScope(Scope*) ()
#12 0x000055555587fedf in _D3dmd6attrib17AttribDeclaration8setScopeMRPSQBr6dscope5ScopeZ__T9__lambda4TCQCx7dsymbol7DsymbolZQBgMFQBaZv ()
#13 0x000055555587fd49 in AttribDeclaration::setScope(Scope*) ()
#14 0x0000555555883aeb in _D3dmd6attrib22ConditionalDeclaration8setScopeMRPSQBw6dscope5ScopeZ__T9__lambda2TCQDc7dsymbol7DsymbolZQBgMFQBaZv ()
#15 0x0000555555883aab in ConditionalDeclaration::setScope(Scope*) ()
#16 0x00005555559008da in Module::importAll(Scope*) ()
#17 0x00005555558d8dae in Import::importAll(Scope*) ()
#18 0x0000555555900918 in Module::importAll(Scope*) ()
#19 0x0000555555867be7 in _D3dmd4mars7tryMainFmPPxaKSQz7globals5ParamZi ()
#20 0x000055555586b242 in D main ()
```

---

Also note that this patch significantly increases the compile times for release builds.
E.g. when building DMD:

Before: 
```
real    1m23.988s
user    1m22.270s
sys     0m2.390s
```

After:
```
real    1m45.436s
user    1m45.757s
sys     0m2.089s
```

**Comment by WalterBright** [comment]
@MoonlightSentinel thanks for the help. I finally found the problem, the code was missing a line that was in my prototype but failed to make it to github for unknown reasons.

**Comment by WalterBright** [comment]
> this patch significantly increases the compile times for release builds

Try it now.

**Comment by ibuclaw** [comment]
> Also note that this patch significantly increases the compile times for release builds.
> E.g. when building DMD:
> 
> Before: 
> ```
> real    1m23.988s
> user    1m22.270s
> sys     0m2.390s
> ```
> 
> After:
> ```
> real    1m45.436s
> user    1m45.757s
> sys     0m2.089s
> ```

Check that you are doing a two or three stage bootstrap on both compilers before timing them. That timing difference could just as easily be (gl)dc optimized release build vs dmd optimized.

**Comment by WalterBright** [comment]
I'm baffled how times could increase. All it does is shorten some generated code. There's something else going on.

**Comment by WalterBright** [comment]
@ibuclaw are you timing dmd's build by dmd? Do you see a change in timings if you just comment out the patch?

**Comment by ibuclaw** [comment]
> @ibuclaw are you timing dmd's build by dmd? Do you see a change in timings if you just comment out the patch?

Did you mean @MoonlightSentinel?

I was just refering to [this change](https://github.com/dlang/installer/pull/466) - also see email thread from last year (Building the dmd distribution with ldc).

**Comment by MoonlightSentinel** [comment]
The test used DMD built with LDC + optimisations. But my test had an error which caused it to compare the current patch against my local DMD (2.096.0) instead of the one built from the parent commit.

The correct test doesn't show  any significant changes introduced by this PR. Sorry for the distraction.

**Comment by WalterBright** [comment]
@MoonlightSentinel good! Then this is ready to go!

**Comment by dkorpel** [comment]
Are there benchmarks to show the speed difference of the generated code?

**Comment by WalterBright** [comment]
No. It'll be small. But I don't know of any CPU where skipping extra jumps and executing less code doesn't make things faster.

**Comment by WalterBright** [comment]
Optimizations are like cigarettes. One will have no observable difference. 50,000 will kill you.

**Review by RazvanN7 — APPROVED** [review]

**Comment by Temtaime** [comment]
And then we'll found some new backend regressions ...
Just build dmd with ldc if it matters

**Pull request merged**
