### PR TITLE
[stable] Pick recent ICE fixes merged in master instead of stable

### PR DESCRIPTION
**Pull request by ghost**
So that they will be part of next point release.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Thanks

**Review by wilzbach — DISMISSED** [review]
Please cherry-pick the merge commits as this will make merging a lot easier for Martin.

**Comment by Basile-z** [comment]
who has to do that ? @thewilsonator I presume ?

**Comment by thewilsonator** [comment]
You can, checkout stable and run 
```
git cherry-pick b4014ac 
git cherry-pick 86710d4
...
```

and then force push to `Basile-z:pull-my-ice-fixes`

**Comment by Basile-z** [comment]
But that's already what I did to make this PR.

**Comment by thewilsonator** [comment]
Hmm, @wilzbach ?

**Comment by Basile-z** [comment]
Actually I did cherry pick but in my branch, I don't see why i would have to cherry pick in stable.

**Comment by thewilsonator** [comment]
As long as your branch is off of stable (which it is) that should work.

**Comment by Basile-z** [comment]
I've created it with stable as parent.

**Comment by thewilsonator** [comment]
Right, I'm not sure what more @wilzbach wants.

**Comment by wilzbach** [comment]
> Right, I'm not sure what more @wilzbach wants.

The same as always. Don't cherry pick specific commits, but the merge commit of them.

**Comment by wilzbach** [comment]
Let me try to explain this again the merge commit is the commit by dlang-bot:

image

or a more familiar picture

image

So the proper thing to do would have been:

```
git cherry-pick -m1 6c8d0bf
git cherry-pick -m1 7448665 
...
```

Have a look at https://github.com/dlang/dmd/pull/9444 for what I was referring to:

image

The reason is that using the actual merge commits, this won't re-create conflicts when using [`merge_stable`](https://github.com/wilzbach/git-tools) or when branching master off into stable for a release.
Also, of course, targeting `stable` and then using [`merge_stable`](https://github.com/wilzbach/git-tools) might be a fast option too.

**Comment by Basile-z** [comment]
reopen, I've just did it.

**Comment by thewilsonator** [comment]
He beat you to it: #9444

**Comment by wilzbach** [comment]
Hmm, but so have I five minutes ago (https://github.com/dlang/dmd/pull/9444).
Anyhow, as these are your fixes, I don't care as long as @thewilsonator keeps a stronger eye on targeting `stable` in the future...

**Comment by thewilsonator** [comment]
Sending bug fixes there or making sure cherry-picks are merge commits?

**Comment by Basile-z** [comment]
@wilzbach, the bot doesn't warn when the issue for the PR has the "ice" tag. It only warns if the importance is reg or critical.

**Comment by wilzbach** [comment]
> Sending bug fixes there or making sure cherry-picks are merge commits?

Both.

**Comment by thewilsonator** [comment]
OK.

**Comment by wilzbach** [comment]
> @wilzbach, the bot doesn't warn when the issue for the PR has the "ice" tag. It only warns if the importance is reg or critical.

Now it will -> https://github.com/dlang/dlang-bot/pull/228

**Comment by Basile-z** [comment]
Thanks, this will be clearer now.

Can you dismiss you change request or approve this one now and label for merge ?

**Comment by Basile-z** [comment]
Thanks.

**Pull request merged**
