### PR TITLE
Implement `pragma(__ctfe)`

### PR DESCRIPTION
**Pull request by thewilsonator**
A pragma declaration to suppress the code generation of functions it is attached to.

### CODE REVIEW

**Comment by RazvanN7** [comment]
Wouldn't simply making the function a template work?

**Comment by thewilsonator** [comment]
No, they are already templates. They are called and instantiated at compile time, but not at run time.

**Comment by rikkimax** [comment]
I stated this on the N.G. thread, but this must tell the .di generator not to elide the function body.

Eliding would require a ton of work to prove it isn't used inside, or exposed outside.

**Comment by RazvanN7** [comment]
> No, they are already templates. They are called and instantiated at compile time, but not at run time.

If the template instances are only used at compile time, I would assume that they will not be codegened.
Last time I looked at the template codegen mechanism it was implemented so that if all instaces are from
speculative contexts then the body does not make it to the object code.

I don't think that this feature is needed. If there are situations where this is useful, then most likely those are compiler bugs.

**Pull request closed without merging**
