### PR TITLE
Fix issue 23148, 21723: Generate invariant id on the basis of location rather than counter.

### PR DESCRIPTION
**Pull request by FeepingCreature**
This makes it more resilient to template order issues.
Thanks Basile B. for the proposal!

Let's see what breaks...

### CODE REVIEW

**Comment by thewilsonator** [comment]
Please include the test case from the bug report, removing the use of the standard library.

**Comment by SixthDot** [comment]
I think that the goal is to see what would break, e.g it's a draft.

**Comment by FeepingCreature** [comment]
Will add the testcase, soon as I figure out what's going on with the failures.

**Comment by FeepingCreature** [comment]
Should be good now, tests pass locally.

Note: There is nothing from the standard library in the bug report. It's reduced from std.sumtype, that's why it looks like that, but it's freestanding.

**Comment by FeepingCreature** [comment]
Since this also fixes 21723, I'll add a testcase for that too.

**Review by thewilsonator — APPROVED** [review]

**Review by maxhaton — APPROVED** [review]

**Comment by dkorpel** [comment]
Are locations unique though? I thought this wasn't done because in `static foreach` you can have multiple definitions with the same location.

**Comment by FeepingCreature** [comment]
Ah shit, I noticed templates but I forgot about `static foreach`. Hm.

**Comment by FeepingCreature** [comment]
Hm, I'm actually having a hard time constructing a test case of a `static foreach` with two struct or class definitions with *different names*, but the same mangling and the same type location.

**Comment by FeepingCreature** [comment]
Oh wait, looking at Identifier.d, it has *another* counter that's site specific. So we're good.

**Comment by FeepingCreature** [comment]
Ah, but that global counter causes *another* undefined-reference bug that I'll probably have to dustmite.

The fun never stops with global variables!

**Pull request merged**
