### PR TITLE
Experiment with running Code Coverage on AppVeyor

### PR DESCRIPTION
**Pull request by wilzbach**
This will probably increase the build time heavily, but let's see first
how much more Windows would cover.

### CODE REVIEW

**Comment by RazvanN7** [comment]
What's the status on this?

**Comment by wilzbach** [comment]
I haven't had time to look into why the coverage files don't get generated and as I don't have a Windows machine it's not at the top of my priority list. Sorry.

**Comment by wilzbach** [comment]
> Even if it's not, would it be problematic to close this and reopen once you work on it?

I don't mind per se, but once this is closed it will probably be forgotten and sink in the abyss.

> At this point, this PR is just eating autotester time.

That's not true. The auto-tester uses a priority list based on the latest push date of a PR which means old PRs are never ever tested ;-)

**Comment by wilzbach** [comment]
BTW for reference, the status of this PR is the following, `-cov` gets injected correctly into DMD

```
dmd  -of..\generated\windows\release\64\dmd.exe -vtls -J..\generated\windows\release\64 -J../res -L/STACK:8388608 -O -release -inline -cov
```

But for some reason:

```
2018-01-23 01:19:31 [Fatal] No Report detected.
   at Codecov.Coverage.Tool.Coverage.LoadReportFile() in C:\Users\Administrator\github\codecov-exe\Source\Codecov\Coverage\Tool\Coverage.cs:line 29
```

**Comment by Geod24** [comment]
Where does Codecov expect the coverage reports ?

**Comment by wilzbach** [comment]
The good news. The coverage files are generated and detected by CodeCov:

image

The bad news:
-------------------

1) Built time increased from to ~28-32min to ~40 min

2) CodeCov doesn't seem to merge the reports yet

image

**Comment by wilzbach** [comment]
This looks a lot better now:

image

https://codecov.io/gh/dlang/dmd/compare/504767e31b2be62f324daf4b973e89ee1dd53a16...c0c4dd17b27a617f7d0a8ee536d7f191837148e8

The runtime of the last build was 44 minutes. So we are looking at ~15 minutes increase in build time of the AppVeyor machine (the maximum build time is 60 minutes).
What do you think: is it worth it?

**Comment by Geod24** [comment]
> What do you think: is it worth it?

Yes. Will merge in 72h unless someone object.

**Comment by rainers** [comment]
AppVeyor only covers COFF so far, shouldn't there also be some coverage for OMF?

The phobos unittests are also not run, not sure if they take part in coverage elsewhere.

**Comment by rainers** [comment]
>  I don't see `'/delexe/la'` anywhere.

It's also shown for the regular build: https://ci.appveyor.com/project/greenify/dmd/builds/20315804#L307 These are options for optlink that mslink ignores.

I think this is failing because some files (ROOT_SRCS) are compiled both into lexer.lib and dmd.exe. This happens to work for the normal build, but coverage creates other dependencies so the linker drags in both versions.

**Comment by Geod24** [comment]
> Looks like this didn't happen.

Indeed. Want to rebase & ping me ?

**Comment by wilzbach** [comment]
Well, we don't use AppVeyor anymore :man_shrugging:

**Pull request closed without merging**
