### PR TITLE
Add AVR to reserved versions

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/ldc-developers/ldc/pull/3420

### CODE REVIEW

**Comment by Geod24** [comment]
Add it at the end to avoid the massive diff

**Comment by ErnyTech** [comment]
@Geod24 done

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Thanks. Could you also add AVR to the spec list o predefined versions.

**Comment by ErnyTech** [comment]
The tests fail due to an error not relevant to this PR

**Comment by ibuclaw** [comment]
Needs spec change?

**Pull request merged**
