### PR TITLE
[markdown] Merge remote-tracking branch 'upstream/master' into HEAD

### PR DESCRIPTION
**Pull request by wilzbach**
Try to merge upstream/master into markdown, s.t. maybe the build failures of https://github.com/dlang/dmd/pull/8209 are gone.

### CODE REVIEW

**Comment by wilzbach** [comment]
```
Warning: Ddoc: Stray ')'. This may cause incorrect Ddoc output. Use $(RPAREN) instead for unpaired right parentheses.
Warning: Ddoc: Stray '('. This may cause incorrect Ddoc output. Use $(LPAREN) instead for unpaired left parentheses.
Warning: Ddoc: Stray ')'. This may cause incorrect Ddoc output. Use $(RPAREN) instead for unpaired right parentheses.
Warning: Ddoc: Stray '('. This may cause incorrect Ddoc output. Use $(LPAREN) instead for unpaired left parentheses.
```

Looks like (1) the location isn't working and (2) https://github.com/dlang/phobos/pull/6541 is required.

**Comment by wilzbach** [comment]
Hmm DAutoTest is still failing with "Stray ')'. This may cause incorrect Ddoc output", but now I can no longer reproduce this locally :/

**Comment by wilzbach** [comment]
> I wonder if it's a quirk of how DAutoTest chooses the version of Phobos to test with.

I think it's using `master`. I tried another repush, but without success.

> Would it help to update markdown-master to the tip of master, if it isn't already there?

This PR already tries to merge master into `markdown`.

CC @CyberShadow any other ideas what could have gone wrong here?

**Comment by dgileadi** [comment]
@wilzbach I'm not convinced this is merging `master` into `markdown`—at the top of this page it says:

> **wilzbach** wants to merge 387 commits into `dlang:markdown` from `wilzbach:markdown-master`

I checked your `markdown-master` branch and it says:

> This branch is 5 commits ahead, 285 commits behind dlang:master.

That's what made me suggest updating the `markdown-master` branch to the latest.

**Comment by wilzbach** [comment]
Hmm I think this was just due to master being pretty active and this PR becoming older.
Anyhow, I just resetted the branch and did a fresh merge from current upstream/master:

https://github.com/dlang/dmd/compare/master...wilzbach:markdown-master

Not sure I can help much more, but maybe @CyberShadow knows why DAutoTest is so persistently not checking out the latest Phobos master branch...

**Comment by dgileadi** [comment]
This can be closed; I'm abandoning the `markdown` feature branch in favor of PRs directly against `master`. See the comments in this PR and the description in #8870.

**Pull request closed without merging**
