### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by 9rnsr**
Conflicts:
    src/dclass.d
    test/runnable/template9.d

### CODE REVIEW

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Someone knows about the OPTLINK error `Error 45: Too Much DEBUG Data for Old CodeView format` on Win64 dmd build?

**Comment by rainers** [comment]
> Someone knows about the OPTLINK error Error 45: Too Much DEBUG Data for Old CodeView format on Win64 dmd build?

dmd is still built as a 32-bit application using dmc and the OMF object file format. This is then used to build 64-libraries and tests.
IIRC this error has been fixed in optlink, but the version on the build server is 8.00.15 while dmd 2.067 is released with 8.00.17.

**Comment by MartinNowak** [comment]
> IIRC this error has been fixed in optlink, but the version on the build server is 8.00.15 while dmd 2.067 is released with 8.00.17.

I sent Brad a mail, asking him to update optlink.

**Comment by 9rnsr** [comment]
> IIRC this error has been fixed in optlink, but the version on the build server is 8.00.15 while dmd 2.067 is released with 8.00.17.

I feel it's correct. Also in my local environment, I use 8.00.17 and same error doesn't happen.

**Comment by MartinNowak** [comment]
Can we build the dmd_frontend.exe without debug info for now?

**Pull request merged**
