### PR TITLE
fix Issue 23357 - ImportC: compatible types with definitions leads to…

### PR DESCRIPTION
**Pull request by WalterBright**
… redeclaration error when used from D

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Comment by adamdruppe** [comment]
Fails to actually fix the issue.

This is the problem with playing whack-a-mole on the initial reduced test case instead of actually reading the comments and understanding the underlying bug.

**Comment by adamdruppe** [comment]
More specifically:

1) fails to address functions being redefined. the general issue behind the bug is that the D namespace is separated and the C namespace isn't.

2) allows incompatible structs to be redefined:

```
// b.c
typedef struct A {
        unsigned char c;
} A;
```

```
// b2.c
typedef struct A {
        int a;
} A;

void test(A a) { }
```

```
// d.d
import b2;
import b;

void main() {
        b.A a;
        b2.test(a);
}
```

A is defined there in an incompatible way but it pretends they're the same. The C standard rule - as quoted in the original bug report already closed - says they must be compatible to allow redefinition.

**Comment by WalterBright** [comment]
@adamdruppe I do read your comments and do understand the issues. I understand the solution isn't complete, but it does fix the bug. I am doing this incrementally, finding the right places to make the adjustments, making sure I am moving in the right direction before committing much more code to it. There are several approaches to solving this issue, I want to gain confidence that I'm picking the right one.

On a pragmatic note, the code you showed will compile in C, but of course it will crash at run time as C is unable to detect the problem. This makes it not a critical problem when importing existing C .h files. The bug this PR fixes is, however, a blocking bug for using existing correct C .h files, so I prioritize fixing this over a more comprehensive solution.

**Comment by adamdruppe** [comment]
C allows different struct definitions in different translation units, but not in the same unit. It'd take some antics to make that happen in C, but with ImportC, it'd happen easily. With a normal C build, the struct definitions would either be in a .h file alongside (or at least #included by the file with) the public function prototype, in which case it is subject to the same-translation-unit rules, or it would be private/static in a .c file and thus not be an interop problem anyway, as neither the struct nor the function would be accessible from the outside (without separate declaration antics at least; obviously you can do it).

With ImportC, what would be separate translation units in C just become separate modules in D, but they are imported together, meaning there's a different interop paradigm. (oh btw `static` functions in C are still public in ImportC so that separate translation unit analogy has several holes in it)

In the same translation unit, compatible redefinitions are permitted as of the newer C standard (in the older standard, it would be an error though), and incompatible ones are always an error. While importC's modules are currently roughly analogous to C11's translation unit rules, they're still different - we import two things at once as a matter of course - and we'd do well to think about it holistically. Doing it piecemeal without any overarching vision is leading to more complicated code and is very likely to spawn more bugs (as soon as you close that issue, I - or someone else as these issues aren't hard to find, especially if you understand the underlying issue - will just open another one with a slightly different test case).

My suggestion for a more comprehensive solution is to put all the importC symbols in a special namespace - a compiler-provided pseudo module, which is selectively put publicly imported into the module the end-user imports. Then you allow compatible redefinitions in there like the new C rule so if it is included across different modules, it will allow it, but still detect errors of incompatible things, except in separate compilation, but that's an acceptable compromise. Doing this should allow C compatibility under existing D module rules and thus not need special cases scattered throughout the code, passing all these tests at the same time.

**Comment by WalterBright** [comment]
Yes, we both understand how C works. My point is that the current way D works when importing C modules will work if the same thing in C will work. This is the top priority for ImportC.

Of lesser priority is diagnosing errors which C is unable to do.

> My suggestion for a more comprehensive solution is to put all the importC symbols in a special namespace - a compiler-provided pseudo module, which is selectively put publicly imported into the module the end-user imports.

That is a good idea, and I went down that path for a while. It turned out to be unworkable, at least with how D internally does things. After a lot of thinking about it, I came up with a workable solution.

1. Instead of eagerly looking for name collisions, look for them lazily the same way D does for unqualified name lookup. If the colliding names are in two different C modules, then silently pick the first one (so always the same one is selected). (Not implemented yet: if the names are incompatible, diagnose an error.)
2. The type system totally depends on the type ids being distinct. This collides with the module system, as C structs in one module will mangle to a different type than the same name in a different C module. The solution was for C structs to not include the module in the type id. Now global C types will always mangle to the same type regardless of what module they come from.
3. The next problem is two C struct definitions mangle to the same type. This PR resolves that by picking the first one. A unimplemented improvement is to check that the two definitions are the same. (Note that C does not allow a struct to have two definitions in the same translation unit, but does allow them in different TUs.)

So far, it appears that this solution is workable. It makes sense to try these out before committing lots of code to them, only to discover it fundamentally does not work.

**Comment by drpriver** [comment]
This solution currently doesn't work as it leads to duplicate symbols for the `.init` of the struct.

```C
// Dummy function definitions to make the example compile.
// freer.i
typedef struct Foo3 *FooRef3;
struct Foo3 {
    int x;
};
void free_foo3(FooRef3 foo){}
```

```C
// maker.i
typedef struct Foo3 *FooRef3;
struct Foo3 {
    int x;
};
FooRef3 make_foo3(void){return 0;}

```

```D
import maker;
import freer;

void main(){
     FooRef3 f = make_foo3();
     free_foo3(f);
}
```
```sh
# Separate compilation makes
# the issue obvious.
$ dmd maker.i -c
$ dmd freer.i -c
$ dmd do_foo.d -c
$ dmd do_foo.o freer.o maker.o 
duplicate symbol '__D3__C4Foo36__initZ' in:
    freer.o
    maker.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
$ nm freer.o
0000000000000010 B __D3__C4Foo36__initZ
0000000000000000 S _free_foo3
$ nm maker.o
0000000000000010 B __D3__C4Foo36__initZ
0000000000000000 S _make_foo3
$ echo "__D3__C4Foo36__initZ" | ddemangle
__C.Foo3.__init
```

**Comment by WalterBright** [comment]
@drpriver I cannot reproduce the issue on Linux. The __initZ symbols are not generated. Perhaps you are not using master?

**Comment by drpriver** [comment]
> @drpriver I cannot reproduce the issue on Linux. The __initZ symbols are not generated. Perhaps you are not using master?

Happening for me on x64 macOS with Monterey 12.6 I tested it on my linux box and confirm the __initZ are not being generated there.

**Comment by WalterBright** [comment]
I verified that it does produce the __initZ symbols on OSX. But that appears to be an orthogonal issue to this PR, i.e. a separate bug report.

**Comment by drpriver** [comment]
> I verified that it does produce the __initZ symbols on OSX. But that appears to be an orthogonal issue to this PR, i.e. a separate bug report.

This PR (or perhaps the previous one) makes them mangle to the same now when they didn’t before, but I’m fine with it as a different bug.

**Comment by WalterBright** [comment]
The cause of the problem is a workaround for a linker problem:

https://github.com/dlang/dmd/blob/master/compiler/src/dmd/toobj.d#L524

**Comment by WalterBright** [comment]
Yeah, I'd rather work on that as a separate issue. Please file it and take the credit!

**Pull request merged**
