### PR TITLE
fix Issue 22138 - foreach cannot declare the loop variables as scope

### PR DESCRIPTION
**Pull request by WalterBright**
This came up in the quarterly meeting, but I couldn't find a bugzilla for it, so I created one.

### CODE REVIEW

**Review by dkorpel — COMMENTED** [review]
This should have a test case for `opApply` to make sure that works, because that's the issue @Geod24 actually had IIRC. Putting `scope` on the element of an array isn't very useful since you can't have an array of scope pointers.

**Comment by Geod24** [comment]
I'll review today (KST) and will look for test cases.

**Comment by maxhaton** [comment]
> I'll review today (KST) and will look for test cases. It also will need a grammar PR, will it not ?

It will, as far as I can see - no `StorageClass` in the grammar currently

**Comment by maxhaton** [comment]
> This should have a test case for `opApply` to make sure that works, because that's the issue @Geod24 actually had IIRC. Putting `scope` on the element of an array isn't very useful since you can't have an array of scope pointers.

I'm not sure if this PR actually makes any difference to opApply or not. I'm not familiar with the exact issue being discussed but my experimentation (with fb9a0aa82e5217d4689d08a3330ae22a096114e8) so far yielded: 
Prior to this PR:
```d
struct Wow
{
    @safe int opApply(int delegate (scope int* ptr) @safe dg)
    {
        int local  = 456;
        dg(&local);
        return 0;
    }
}
int* global;
void main()
{
	Wow tmp;

    foreach(int* ptr; tmp)
    {
        //escape ptr
        global = ptr;
    }
}
```
results in the error message
```
<source>(15): Error: function `example.Wow.opApply(int delegate(scope int* ptr) @safe dg)` is not callable using argument types `(int delegate(int* ptr) nothrow @nogc @safe)`
<source>(15):        cannot pass argument `__foreachbody1` of type `int delegate(int* ptr) nothrow @nogc @safe` to parameter `int delegate(scope int* ptr) @safe dg`
```
i.e. `ptr` is escaped and therefore cannot be inferred to be scope. Not a great error message but whatever.

With this PR, we can write the following (say hello to `scope`)
```d
struct Wow
{
    @safe int opApply(int delegate (scope int* ptr) @safe dg)
    {
        int local  = 456;
        dg(&local);
        return 0;
    }
}
int* global;
void main()
{
   Wow tmp;

    foreach(scope int* ptr; tmp)
    {
        global = ptr;
    }
}
```
This yields the same error message. 

I don't know whether that is the problem you mentioned, but if not then it should be considered one since the compiler should obviously issue an error now that it is guaranteeing `scope`-ness rather than inferring it.

**Comment by Geod24** [comment]
So, there are a few things I expect:
```D
void main()
{
    int[] array;
    foreach(scope ptr; array) {}
}
```

This is the most basic usage, and should compile. With HEAD, it doesn't parse, but the current PR makes it compile. Good.

Now, `scope` on `int` is useless. Things should work with `scope` being actually useful:
```D
void main() @safe
{
    int value;
    int*[1] array = [ &value ];
    foreach(scope ptr; array) {} // Line 5
}
```

(Need to compile with `-dip1000`).
This does not compile with this PR:
```
foreach.d(5): Error: cannot take address of `scope` local `array` in `@safe` function `main`
```

Likewise, I would expect the `scope` storage class to be inferred, so, once the previous snippet is made to compile, the following should, too:
```D
void main() @safe
{
    int value;
    int*[1] array = [ &value ];
    foreach(ptr; array) {} // `scope` should be inferred here
}
```
But that inference can be left to a later PR.

Currently, there exists an `accept-invalid` with `-dip1000`:
```D
int* global;

void main () @safe
{
    int value;
    int*[1] array = [ &value ];
    bar(array);
    assert(global !is null);
}

void bar(scope int*[] array) @safe
{
    foreach(ptr; array) // `scope` should be inferred here
    {
        global = ptr; // BUG HERE
    }
}
```

Adding `scope` explicitly now works, so we can start to tackle this issue. Since the issue is already existing, I don't think it needs to be fixed by this PR either, but should definitely be tackled before `-dip1000` becomes the default.

So now, let's give a shot to `opApply`:
```D
int* global;

struct Foo {
    int opApply (scope int delegate (scope int* ptr) @safe dg) @safe
    {
        return 0;
    }
}

void main () @safe
{
    Foo f;
    foreach (x; f) { global = x; }
}
```

Compiled with `-dip1000`:
```
foreach.d(13): Error: function `foreach.Foo.opApply(scope int delegate(scope int* ptr) @safe dg)` is not callable using argument types `(int delegate(int* x) nothrow @nogc @safe)`
foreach.d(13):        cannot pass argument `__foreachbody2` of type `int delegate(int* x) nothrow @nogc @safe` to parameter `scope int delegate(scope int* ptr) @safe dg`
```

Alright, no inference, so if we use:
```D
    // Add an explicit type to avoid inference :
    foreach (scope int* x; f) { global = x; }
```

We get the same error message. If we remove the escaping, the code compile though. So I think we can merge this PR as-is.

**Comment by WalterBright** [comment]
Spec PR https://github.com/dlang/dlang.org/pull/3074

**Comment by Geod24** [comment]
Thanks! Regarding bugs, I've reported https://issues.dlang.org/show_bug.cgi?id=22145.
The other ones will be hard to reduce as long as issues like https://issues.dlang.org/show_bug.cgi?id=20505 still exist.

**Comment by dkorpel** [comment]
> The other ones will be hard to reduce as long as issues like https://issues.dlang.org/show_bug.cgi?id=20505 still exist.

That should have been fixed a long time ago. @WalterBright please rebase your https://github.com/dlang/dmd/pull/10951

**Pull request merged**
