### PR TITLE
Fix Issue 20190 - Deprecation not triggered on templates

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by RazvanN7** [comment]
I tried rebasing on top of stable, but I'm receiving merge conflicts.

**Comment by Geod24** [comment]
Here's my test case:
```D
deprecated template Const20190_1 (T)
{
    alias Const20190_1 = const(T);
}
void func20190(Const20190_1!(char)[]) {}

template Const20190_2 (T)
{
    deprecated alias Const20190_2 = const(T);
}
Const20190_2!(char)[] var20190;

deprecated("Hello") template Const20190_3 (T)
{
    deprecated(`World`) alias Const20190_3 = const(T);
}
struct Struct20290 { Const20190_3!(char)[] data; }

template Const20190_4 (T)
{
    alias Const20190_4 = Const20190_2!(T);
}
class Class20290 { Const20190_4!(char)[] data; }

void Function20190 (T) () {}
alias Alias20190 = Function20190!int;
```

**Comment by RazvanN7** [comment]
@Geod24 My patch currently yields:
```
test.d(5): Deprecation: alias test.Const20190_1!char.Const20190_1 is deprecated
test.d(11): Deprecation: alias test.Const20190_2!char.Const20190_2 is deprecated
test.d(17): Deprecation: alias test.Const20190_3!char.Const20190_3 is deprecated - World
```

It seems that:

```d
template Const20190_4 (T)
{
    alias Const20190_4 = Const20190_2!(T);
}
class Class20290 { Const20190_4!(char)[] data; }
``` 
Does not yield a deprecation. If I comment line `Const20190_2!(char)[] var20190;`, then the deprecation is issued.

**Comment by Geod24** [comment]
I have an (incomplete) patch for it locally. I don't think you can get away without adding a `deprecated` attribute in `TemplateDeclaration`. Test cases I hadn't added but could be worthwhile:
- Deprecated template, non-deprecated eponymous function;
- Deprecated template, non-deprecated non-eponymous function, multiple members;
- Other deprecated template with aliases and not eponymous / onemember

**Comment by thewilsonator** [comment]
@RazvanN7 whats the status of this?

**Comment by RazvanN7** [comment]
This PR fixes the reported bug, however there is one case that @Geod24 pointed out that my patch does not fix. I'm not entirely sure why, @Geod24 have you made any progress with your patch?

**Pull request closed without merging**
