### PR TITLE
fix intrinsic bug

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by thewilsonator** [comment]
OK so it seems that for 
```typeof(e.Ecount) == ubyte
e.Ecount =1 
e.Ecomsub =225 
```
```
typeof(e.Ecount) == ushort
e.Ecount =1 
e.Ecomsub =65535 
```
I'm not sure where that is coming from  though, I've no idea what typical values are for them.

**Comment by thewilsonator** [comment]
The only place I can see that would cause that is https://github.com/dlang/dmd/blob/18652b5f029d471c9de9dee09b42723f8fd50eba/src/dmd/backend/cgcod.d#L1871

@WalterBright should that be a pre-decrement instead of post-decrement?

**Comment by thewilsonator** [comment]
Hmm, no that triggers a different assertion.

**Comment by ibuclaw** [comment]
It would appear that dmd takes a dump when it encounters an intrinsic with the wrong parameter types, so intrinsic_op needs to have stricter matching so that it ignores non-real math functions.

**Comment by thewilsonator** [comment]
Or alternately it needs to be taught how to deal with intrinsics that work in single and double precision. Which shouldn't be too hard, `sqrt` already works in all three FP types.

**Comment by thewilsonator** [comment]
Which I plan to palm off to Walter https://github.com/dlang/dmd/pull/10661#issuecomment-565394494

**Pull request closed without merging**
