### PR TITLE
Revert "accept @pure @nothrow @return attributes"

### PR DESCRIPTION
**Pull request by 9rnsr**
Reverts D-Programming-Language/dmd#4341

### CODE REVIEW

**Comment by andralex** [comment]
Please let's wait for a closure of the forum discussion. Thanks!

**Comment by WalterBright** [comment]
Because I don't want to wind up reverting the revert.

**Comment by 9rnsr** [comment]
> Because I don't want to wind up reverting the revert.

It's not an issue. After the syntactic sugar is actually approved by the community, we can add it again.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
I understand and approve; just as a matter of procedure let's have in the future a different person than the pull creator merge it. Thanks!

**Pull request merged**
