### PR TITLE
test: Add RUNNABLE_PHOBOS_TEST and COMPILABLE_MATH_TEST

### PR DESCRIPTION
**Pull request by ibuclaw**
This highlights the remaining tests that still have phobos dependencies in a way that is easily greppable.

These tests should should arguably either be reduced further without the phobos dependency, or be moved to the phobos testsuite.

FYI @MoonlightSentinel 

If there are other tests that import phobos, either I haven't picked them up yet (it's been a while since I last ran the testsuite with druntime only), or the tests aren't used by gdc (i.e: contains dmd asm, dmd coverage, gdb test, shell test, etc.)

### CODE REVIEW

**Review by RazvanN7 — COMMENTED** [review]
I see that `RUNNABLE_MATH_TEST`s import `std.math`, however, `compilable/test5227.d`, `runnable/arrayop.d`, `runnable/builtin.d` and maybe others import only `std.math` (and maybe some druntime module), yet are tagged as `RUNNABLE_PHOBOS_TEST`. What is the difference between the 2?

**Comment by ibuclaw** [comment]
> I see that `RUNNABLE_MATH_TEST`s import `std.math`, however, `compilable/test5227.d`, `runnable/arrayop.d`, `runnable/builtin.d` and maybe others import only `std.math` (and maybe some druntime module), yet are tagged as `RUNNABLE_PHOBOS_TEST`. What is the difference between the 2?

You mean `COMPILABLE_MATH_TEST`?

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@ibuclaw Is this ready?

**Comment by dkorpel** [comment]
I've updated the line number of the deprecation in compilable/compile1.d, it should pass now.

**Comment by dkorpel** [comment]
Ping @ibuclaw

**Pull request merged**
