### PR TITLE
Automatically convert RECXXXX -> AliasThisRec

### PR DESCRIPTION
**Pull request by wilzbach**
```
replacements=(
"RECno no"
"RECyes yes"
"RECfwdref fwdref"
"RECtypeMask typeMask"
"RECtracing tracing"
"RECtracingDT tracingDT"
)
shopt -s globstar
for r in "${replacements[@]}" ; do
    w=($r)
    sed "s/${w[0]}/AliasThisRec.${w[1]}/g" -i **/*.d
done
```

### CODE REVIEW

**Comment by ZombineDev** [comment]
You also need to update this: https://github.com/dlang/dmd/blob/254c9634f8498c3d7eb38f37de23b14f1c509e36/src/dmd/mtype.h#L716-L725

**Comment by wilzbach** [comment]
> You also need to update this:

I didn't because C++ 03 (the version GDC uses) doesn't support scoped enums at the root level. However, I now used the namespace trick. CC @ibuclaw

**Review by jacob-carlborg — APPROVED** [review]

**Review by ibuclaw — DISMISSED** [review]
Why do you need to change the headers at all here?

**Comment by wilzbach** [comment]
> Why do you need to change the headers at all here?

I don't. That's why I left them alone initially, but there was https://github.com/dlang/dmd/pull/7728#issuecomment-357923118

**Review by PetarKirov — APPROVED** [review]

**Pull request merged**
