### PR TITLE
fix Issue 22797 - [REG master] Internal Compiler Error: cannot mixin static assert ''

### PR DESCRIPTION
**Pull request by ibuclaw**

### CODE REVIEW

**Review by MoonlightSentinel — APPROVED** [review]
You beat me to it

**Comment by ibuclaw** [comment]
> You beat me to it

Also bootstrapped and regression tested on x86_64-linux-gnu{-m64,-m32,-mx32} and ppc64le-redhat-linux

**Comment by WalterBright** [comment]
Thanks for fixing it. I don't know how it passed the test suite to begin with.

**Comment by MoonlightSentinel** [comment]
https://github.com/dlang/dmd/pull/13694#discussion_r810647881 

The old condition was equivalent to:

```d
s.kind().ptr is "static assert".ptr
```

This works for dmd because the string literals are deduplicated when compiling `statement.d` and `statementsem.d` in the same compiler invocation.

**Pull request merged**
