### PR TITLE
fix Issue 13147 - Wrong codegen for thisptr in naked extern (C++) met…

### PR DESCRIPTION
**Pull request by WalterBright**
…hods

https://issues.dlang.org/show_bug.cgi?id=13147

### CODE REVIEW

**Comment by yebblies** [comment]
Don't `addPreInvariant` and `addPostInvariant` already check for naked?

**Comment by WalterBright** [comment]
Yes, they do, but `naked` hasn't been set yet. It's set by the call to `semantic()` for the function body.

**Comment by WalterBright** [comment]
refactored for ddmd

**Comment by andralex** [comment]
sup with the travis failure

**Comment by AndrejMitrovic** [comment]
Closing in favor of https://github.com/dlang/dmd/pull/5729 as this has gotten stale.

**Pull request closed without merging**
