### PR TITLE
infer 'scope' for 'this' parameter

### PR DESCRIPTION
**Pull request by WalterBright**
I had forgotten to do that. It's needed to compile Phobos.

### CODE REVIEW

**Comment by WalterBright** [comment]
Blocking https://github.com/dlang/phobos/pull/5044

**Comment by UplinkCoder** [comment]
What does it do, force a this pointer to always be scope ?

**Comment by WalterBright** [comment]
No, it infers `scope` if it is used as if it were scope.

**Comment by UplinkCoder** [comment]
so this is treated as if it were always annotated scope ?

**Comment by UplinkCoder** [comment]
Rationale please.

**Review by UplinkCoder — APPROVED** [review]
It does not look like it would break anything.

**Comment by UplinkCoder** [comment]
@WalterBright go ahead and merge :)

**Pull request merged**
