### PR TITLE
Move druntime changelogs to top-level

### PR DESCRIPTION
**Pull request by ibuclaw**

### CODE REVIEW

**Comment by Geod24** [comment]
But they are separate sections, aren't they ?

**Comment by ibuclaw** [comment]
> But they are separate sections, aren't they ?

Hmm.

**Comment by ibuclaw** [comment]
@Geod24 doing the inverse then, as having the top-level changelog would just be confusing.

**Comment by Geod24** [comment]
I think it'd be better to have them at the top. I would rather have a way to distinguish them, e.g. have `pre-commit` enforce that all changelog entry start with either `dmd.` or `druntime.` in their file name ?

**Comment by ibuclaw** [comment]
> I think it'd be better to have them at the top. I would rather have a way to distinguish them, e.g. have `pre-commit` enforce that all changelog entry start with either `dmd.` or `druntime.` in their file name ?

If we're going down that route, then [changed.d](https://github.com/dlang/tools/blob/master/changed.d#L279-L290) will need to be updated to reflect the new scheme.

**Comment by RazvanN7** [comment]
I also think that having the changelog directory at the top would be better. Also, the point of the changelog is to give a high-level overview of what changed. I don't think that it is relevant, from a changelog reader perspective, whether the change was made in dmd or druntime, considering that there might be changes that affect both.

For interested parties, you can search the PR and see exactly what was modified. So, I would rather have a common changelog entry directory.

**Comment by RazvanN7** [comment]
@ibuclaw what is your stance on this?

**Comment by RazvanN7** [comment]
@ibuclaw any progress on this?

**Comment by ibuclaw** [comment]
Just moved druntime changelogs to top-level then.

Also require tools to be updated. https://github.com/dlang/tools/pull/452

Without either of these PRs in, we can't move forward with cutting a release.

**Review by RazvanN7 — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
