### PR TITLE
issue 17027 - add TZCNT and LZCNT to inline assembler

### PR DESCRIPTION
**Pull request by ghost**
This is useful for efficient bitsets operations (max and min member in set).

If you accept these kind of PRs I may also add others BMI1 and BMI2 opcodes.

### CODE REVIEW

**Comment by WalterBright** [comment]
Thanks. But there's a problem with the way the test is set up - it checks to see that the instruction produces the right results. The trouble with that is:

1. it's quite a chunk of code to do that. Doing that for more instructions implies an enormous test suite.
2. testing it requires running on a CPU with those instructions, which is often not the case.

Instead, make it work like most of the rest of the tests, where it just tests that the correct instruction bytes are emitted. It's simple, fast, correct, compact, and works on every test machine.

I.e. it tests what the assembler is supposed to do - output the correct instruction bytes - not what the CPU does with it.

**Comment by BBasile** [comment]
Ok, rewritten to verify opcode correctness.

**Comment by nordlow** [comment]
Will these be available as builtins aswell, like for POPCNT?

**Comment by BBasile** [comment]
@nordlow , good Q, I don't know. Actually I didn't even know that these intrinsics exist. It would be certainly be better since iasm can't be inlined. tzcnt seems reasonable but lzcnt is more modern and requires relatively recent processors. You can ask to those who made core.bitop.

**Pull request merged**
