### PR TITLE
Build build.d with symbols

### PR DESCRIPTION
**Pull request by CyberShadow**
Helps debug build issues when build.d crashes.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by MoonlightSentinel — APPROVED** [review]
Did you encounter a specific issue?

**Comment by CyberShadow** [comment]
Yes, but it manifests only under Wine and Windows versions before 7. The bug is in Phobos, I plan to submit a fix to Wine and Phobos later.

**Review by wilzbach — APPROVED** [review]

**Comment by Geod24** [comment]
@CyberShadow : Sorry to hijack, but as I was going over the druntime issues yesterday, I saw [this one](https://issues.dlang.org/show_bug.cgi?id=5562).
From your message, it looks like we could make it WONTFIX since we can compile using `build.d` instead ?

**Comment by CyberShadow** [comment]
Yes, I don't see why you wouldn't want to just run the entire build under Wine. Not sure how build.d relates to this, since you could do this before and after build.d (the above Wine bug notwithstanding). With the Wine bug patched locally, I can get Digger to build D for Windows under Wine (though currently -m64 is a bit broken, which is what I'm working on now).

There's a longer standing problem with -m32 under Wine - OPTLINK seems to have some kind of synchronization bug that's exposed only under Wine, which causes it to hang. The Microsoft linker doesn't have this problem though.

**Comment by rainers** [comment]
> There's a longer standing problem with -m32 under Wine - OPTLINK seems to have some kind of synchronization bug that's exposed only under Wine, which causes it to hang.

IIRC the exe header of optlink is patched to disable running on multiple cores (see https://github.com/DigitalMars/optlink/pull/2#issuecomment-13684595). Maybe wine doesn't respect that flag?

**Comment by CyberShadow** [comment]
Windows and LInux both use preemptive multithreading. AFAIU, other than for some very fine details like memory ordering, restring a task to one thread doesn't shield it from multithreading bugs, as the OS could still preempt and schedule threads arbitrarily, even going as far as simulating a multi-threaded system by running one instruction from each thread in turn. So, it seems more likely that the bug is exposed to the different scheduling characteristics of the Linux task scheduler as opposed to the Windows one.

**Comment by CyberShadow** [comment]
> The bug is in Phobos, I plan to submit a fix to Wine and Phobos later.

- Wine fix: https://source.winehq.org/patches/data/176789 and https://source.winehq.org/patches/data/176790
- Phobos fix: https://github.com/dlang/phobos/pull/7357

**Pull request merged**
