### PR TITLE
change Parentheses singular to Parenthesis

### PR DESCRIPTION
**Pull request by WalterBright**
Sorry, I just can't stand the misspelling any more.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
please update the headers and frontend.d, too.

**Comment by thewilsonator** [comment]
please also update tokens.h

**Comment by WalterBright** [comment]
token.h does not have Parentheses in it.

**Comment by thewilsonator** [comment]
Semaphore fails with 
```
lexer.d(14,9): Error: no property `leftParentheses` for type `TOK`. Did you mean `TOK.leftParenthesis` ?
```
I think that is the dub test in `test/dub_package/lexer.d`

**Review by ibuclaw — APPROVED** [review]
One parenthesis, two parentheses, merge.

**Pull request merged**
