### PR TITLE
fix Issue 16193 - opApply() doesn't heap allocate closure

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Should it go in the release notes ? Sounds like an important change for people caring about memory allocations.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
> How is this related to @safety?

See https://issues.dlang.org/show_bug.cgi?id=16193

**Comment by WalterBright** [comment]
@klickverbot all the `-transition=safe` changes are bug fixes for @safety, but likely will require some changes to user code. In this case, having the closures unexpectedly now being allocated can cause hidden, unwelcome memory consumption and slowdowns without warning. It can also break existing code that is annotated with @nogc.

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
It fits in with https://github.com/dlang/dlang.org/pull/1473

**Comment by andralex** [comment]
@klickverbot this lgtm please let me know if I'm missing something

**Comment by andralex** [comment]
Auto-merge toggled off

**Comment by andralex** [comment]
@WalterBright please clarify with @klickverbot

**Comment by WalterBright** [comment]
> There is my previous comment and an explicit question – which hasn't been answered yet.

Then I do not understand your question. Can you please rephrase?

> This is a bug fix for a memory corruption issue that is entirely unrelated to @safe.

Memory corruption issues have everything to do with @safe, which is supposed to add checks to ensure corruption does not happen.

> Accidentally not creating a heap closure where it is required isn't supposed to be possible in @system code either, nor is it related to the various new meanings of scope.

Yes it is, because `scope` was mostly ignored before. Paying attention to it is likely to break user code, hence the whole point of `-transition=safe`.

> This is now enabled by a compiler flag that is documented as "implement enhanced @safe checking", which doesn't make any sense whatsoever.

The changelog.dd entry enumerates just what that flag does.

As I remarked upthread, we cannot just throw this in because it silently **breaks existing code** that was correct before (even though the compiler could not verify it correct). I've never seen a case where opApply() leaked a delegate, but the compiler can't verify it. Annotating it with `scope` is not mentioned in the spec, and has not been consistently done in Phobos. It is unreasonable to expect user code to have done these annotations.

**Comment by WalterBright** [comment]
> the flag -transition=2.072

All this work on safety, including dip1000, is intended for 2.072.

**Comment by WalterBright** [comment]
In my efforts to make `scope` actually work, I've found it is rarely specified (in Phobos, anyway), so rarely that I've had to make it inferred for templates and literals. The inference helps a great deal, but inference for regular functions is impractical at the moment. Furthermore, existing uses of `scope` were not checked by the compiler. Suddenly turning all this on will be a wrenching change, hence the need for the switch.

I've been making PRs for Phobos/Druntime along the way so they'll work with or without the switch.

**Comment by Geod24** [comment]
> In my efforts to make scope actually work, I've found it is rarely specified (in Phobos, anyway), so rarely that I've had to make it inferred for templates and literals. The inference helps a great deal, but inference for regular functions is impractical at the moment. Furthermore, existing uses of scope were not checked by the compiler. Suddenly turning all this on will be a wrenching change, hence the need for the switch.
> 
> I've been making PRs for Phobos/Druntime along the way so they'll work with or without the switch.

A slightly bit OT, but Vibe.d relies on `scope delegate` quite a lot and might be an interessant testing ground.

**Pull request merged**
