### PR TITLE
Deprecate alias this for classes v2

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by RazvanN7** [comment]
cc @Geod24

**Comment by RazvanN7** [comment]
cc @WalterBright

**Comment by benjones** [comment]
Wow, the only buildkite failures are phobos!

**Review by thewilsonator — COMMENTED** [review]
Changelog entry

**Comment by pbackus** [comment]
Should this include interfaces too?

**Comment by RazvanN7** [comment]
I had no idea you could use alias this in interfaces. Yes, definitely, interfaces should be included too.

**Comment by RazvanN7** [comment]
@thewilsonator added changelog entry
@pbackus included interfaces

**Comment by RazvanN7** [comment]
The GDC tester fails with:

```
src/dmd/dtoh.d:294:12: error: declaration expected, not 'foreach'
  294 |     static foreach(member; __traits(allMembers, Context))
      |            ^
src/dmd/dtoh.d:294:28: error: declaration expected, not '__traits'
  294 |     static foreach(member; __traits(allMembers, Context))
      |                            ^
src/dmd/dtoh.d:3037:1: error: unrecognized declaration
 3037 | }
      | ^
```

when trying to build the compiler. @ibuclaw does gdc not recognize static foreach?

**Comment by adamdruppe** [comment]
gdc added static foreach i think in version 10. Version 9 and below do not have it.

You can make a helper function concat the strings and return them in one go for a use like this to be compatible with more ocmpailers.

**Comment by RazvanN7** [comment]
> gdc added static foreach i think in version 10. Version 9 and below do not have it.

Yeah, I just consulted the changelog: https://gcc.gnu.org/gcc-10/changes.html (ctrl-f "static foreach").

Is anything preventing us from upgrading the tester to gdc10?

**Comment by ibuclaw** [comment]
> > gdc added static foreach i think in version 10. Version 9 and below do not have it.
> 
> Yeah, I just consulted the changelog: https://gcc.gnu.org/gcc-10/changes.html (ctrl-f "static foreach").
> 
> Is anything preventing us from upgrading the tester to gdc10?

Yes, me. Don't break gdc's bootstrap, else I'll revert.

**Review by WalterBright — APPROVED** [review]

**Comment by RazvanN7** [comment]
Spec PR: https://github.com/dlang/dlang.org/pull/3498

**Comment by ibuclaw** [comment]
There's more deprecated messages when running the testsuite:
```
testsuite/libphobos.hash/test_hash.d:293: warning: alias this for classes/interfaces is deprecated
testsuite/libphobos.hash/test_hash.d:300: warning: alias this for classes/interfaces is deprecated 
```
These excess warnings breaks the testsuite.

**Pull request merged**
