### PR TITLE
fix Issue 23768 - ImportC: ICE on nested C initializer

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
Took me a while to figure this out, as I thought it had something to do with anonymous unions. But nope, once I realized what the real problem was, the fix was simple.

**Review by thewilsonator — APPROVED** [review]

**Review by dkorpel — APPROVED** [review]
Rebased to stable

**Comment by dkorpel** [comment]
Thanks for fixing this by the way!

**Comment by dkorpel** [comment]
This introduced a regression: https://issues.dlang.org/show_bug.cgi?id=24026

**Pull request merged**
