### PR TITLE
Issue 15172 - ICE(interpret.c ctfeCompile) Assertion `!fd->semantic3Errors' failed. 

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=15172

See explanation comments in `fail_compilation/ice15172.d`.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Yep, looks good.

**Comment by 9rnsr** [comment]
Ready.

**Comment by ibuclaw** [comment]
Having a second look, I see that assert has been removed.  Is this really necessary?

Probably unrelated, but there's another CTFE ICE that I want to make a start on, and what I determined is that the semantic passes don't do enough to propagate ErrorExps to the top.

**Comment by 9rnsr** [comment]
> Having a second look, I see that assert has been removed. Is this really necessary?

Necessary. As I commented on `ctfeInterpret`, CTFE can cross over functions during interpretation. But, `CallExp.semantic` don't validate the body of called function. For example:

```d
int foo(int n) { return n == 0 ? 1 : bar(n-1); }
int bar(int n) { return n == 0 ? 1 : foo(n-1); }
```

If the `bar` call in `foo` needs to validate the `bar` body, it will also need to validate `foo` body at the `foo` call in `bar`, then the whole code will become uncompilable. But, of course it's allowed, because "function signature analysis" and "function body analysis" are properly separated in D semantic analysis. The former is done in `FuncDeclaration.semantic`, and the latter is done in `FuncDeclaration.semantic3`.

From the fact, a CTFE may reach a CallExp which calls a function contains invalid function body. With that case, as you noticed, a success of semantic analysis is not enough to guarantee that the CTFE interpretation never reach to invalid expression.

So the removed the assertion so it was relying on incorrect assumption.

**Comment by ibuclaw** [comment]
:+1:

**Comment by ibuclaw** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
@ibuclaw Thanks!

**Pull request merged**
