### PR TITLE
Make C++ warnings errors (i.e. -Werror) in posix.mak

### PR DESCRIPTION
**Pull request by JinShil**
Attempt at shepherding #7358 across the finish line.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Aren't there any complains about the C++ files in the backend are using the `.c` extension?

**Comment by ibuclaw** [comment]
> Aren't there any complains about the C++ files in the backend are using the .c extension?

That's what the testsuite will tell us.

**Comment by ibuclaw** [comment]
@JinShil - Forgetting some patches?

https://github.com/dlang/dmd/pull/7358/files#diff-9b5e2f2ac206ebe201f44f8e316514bcR4247

**Comment by JinShil** [comment]
> @JinShil - Forgetting some patches?

Thanks!

**Review by ibuclaw — APPROVED** [review]
ok, but ping @WalterBright on backend stuff.

**Comment by MartinNowak** [comment]
This has broken the release builds with an older clang on OSX.

**Comment by MartinNowak** [comment]
See https://github.com/dlang/dmd/pull/7430

**Comment by JinShil** [comment]
> This has broken the release builds with an older clang on OSX.

Why wasn't it caught by the auto-tester?

**Comment by MartinNowak** [comment]
Because that is running a newer clang version, apparently the compiler was fixed to not be so picky.

**Comment by jacob-carlborg** [comment]
> Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.2.0
Thread model: posix

I suggest that the compiler is updated. Clang 5 and LLVM 3.4 is pretty old. Latest version of Xcode is 9.2.

**Comment by jacob-carlborg** [comment]
> This has broken the release builds with an older clang on OSX.

The same compiler that is running the tests should be building the releases. Ideally on the same computer.

**Comment by wilzbach** [comment]
> I suggest that the compiler is updated. Clang 5 and LLVM 3.4 is pretty old. Latest version of Xcode is 9.2.

Good luck!
We are working since February to upgrade the auto-tester, s.t. we can finally transition from ddmd -> dmd (see e.g. https://github.com/dlang/dmd/pull/7135 or https://github.com/dlang/dmd/pull/6562).

**Comment by jacob-carlborg** [comment]
How is "ddmd -> dmd" related to upgrading Clang?

**Comment by wilzbach** [comment]
> How is "ddmd -> dmd" related to upgrading Clang?

It's just an example on how difficult it is to upgrade things on auto-tester.

**Comment by jacob-carlborg** [comment]
Ok. Is Brad the only one with access?

**Comment by braddr** [comment]
I'm the only one with access to most of the machines.  They're typically behind firewalls and on networks I don't have liberty to give direct access to.

The Feb to Now transition time for ddmd -> dmd can't be reasonably placed on me like that.  *Maybe* a month of the total time can, but the rest, sorry, no.  The rest was largely waiting for the build system and branches to be in sync enough that the changes to the build system wouldn't break every build.  I won't pull change just because they've been submitted.  They kinda have to work too.

As to the osx versions, there's three of them in the fleet, each with a different version.  I'd be happy to upgrade the oldest ones if we're deprecating support for those altogether.  The versions in place:

Darwin 13.4.0, Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Darwin 15.6.0, Apple LLVM version 8.0.0 (clang-800.0.42.1)
Darwin 16.7.0, Apple LLVM version 9.0.0 (clang-900.0.39.2)

The difficulty is that we've got a large set of platforms, several branches, and lots of project in flight and aligning them all correctly doesn't happen as fast as anyone would like.

Another great example is upgrading the freebsd supported platform from 8.x to 10 and/or 11.  I'd love to, except that the code base doesn't pass testing on them.  I even setup the auto-tester to build and test master against those platforms.  No one touched that project beyond a tiny bit of initial interest.

**Comment by jacob-carlborg** [comment]
> I'm the only one with access to most of the machines. They're typically behind firewalls and on networks I don't have liberty to give direct access to.

Fair enough. Then it's also understandable why it might take longer, if only one person is responsible.

> Another great example is upgrading the freebsd supported platform from 8.x to 10 and/or 11. I'd love to, except that the code base doesn't pass testing on them. I even setup the auto-tester to build and test master against those platforms. No one touched that project beyond a tiny bit of initial interest.

I see. I would hope that upgrading just the compiler is simpler than upgrading the whole operating system.

**Pull request merged**
