### PR TITLE
does master pass the test suite?

### PR DESCRIPTION
**Pull request by WalterBright**
This is to see if the random bugs when running the test suite are in the test suite rather than in the code base. Here's the current list of bugs in the test suite:

https://issues.dlang.org/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&keywords=TestSuite%2C%20&keywords_type=allwords&list_id=232615&query_format=advanced

I've had to re-create this several times now. Do not pull it.

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
Again, not a bug in the test suite but current master ... seems like the optimizer segfaults with -lowmem or triggers some GC related bug.

**Comment by WalterBright** [comment]
How did master wind up getting pulled if it fails every time to pass the test suite?

**Comment by MoonlightSentinel** [comment]
Insufficient tests which do not reliably trigger the Heisenbug. That bad but not a bug in the test suite.

Sometimes caused by merging PRs based upon trust ...

**Comment by WalterBright** [comment]
It's also the damned run.d failing, so none of the tests can be run.

It could also be a druntime issue, or a phobos issue.

**Comment by WalterBright** [comment]
Seriously, folks, the test harness should NOT BE BUILT WITH THE COMPILER UNDER TEST. Sorry I'm shouting again, but nobody seems to feel this is of any importance.

**Comment by Geod24** [comment]
> Seriously, folks, the test harness should NOT BE BUILT WITH THE COMPILER UNDER TEST. Sorry I'm shouting again, but nobody seems to feel this is of any importance.

I don't think anyone is arguing it should. @wilzbach raised a PR for it: https://github.com/dlang/dmd/pull/11519

**Comment by WalterBright** [comment]
Working again!

**Pull request closed without merging**
