### PR TITLE
Fix Issue 21742 - dot template expressions don't have the void type like any template

### PR DESCRIPTION
**Pull request by BorisCarvajal**
Note: There is a line of code on phobos depending on this bug.

### CODE REVIEW

**Comment by thewilsonator** [comment]
You will need to force push to restart the CI now the phobos PR is merged

**Comment by MoonlightSentinel** [comment]
Templates should exhibit consistent behaviour, but shouldn't it be the other way round?
Uninstantiated type templates don't denote a type, e.g. this fails as expected. 

```d
struct S() {}
static assert(is(S));
```

**Comment by BorisCarvajal** [comment]
I'm not sure, it would be better like you said.
Honestly I've been familiar with seeing non-instantiated templates as `void` and never had considered aggregated templates, another inconsistency in the language and also the spec is completely void on this matter.

**Comment by RazvanN7** [comment]
I also think that the real problem is that the top-level function has a type. Templates, by definition, do not have a type.

**Comment by BorisCarvajal** [comment]
> I also think that the real problem is that the top-level function has a type.

Functions are not needed for the issue:

```
template T(X) {}
struct S { template T(X) {} }

pragma(msg, typeof(T).stringof); // void
pragma(msg, typeof(T!int).stringof); // void
pragma(msg, typeof(S.T).stringof); // void
pragma(msg, typeof(S.T!int).stringof); // void
pragma(msg, typeof(S.init.T).stringof); // Bug, it should be void as well. "Error: expression S().T(X) has no type".
pragma(msg, typeof(S.init.T!int).stringof); // void
```

> Templates, by definition, do not have a type.

Sure, and that's why they are currently of type `void`.

**Comment by MoonlightSentinel** [comment]
> Sure, and that's why they are currently of type `void`.

But `void` is a type which is distinct from no type.
Even worse:

```d
struct S() {}

pragma(msg, typeof(S).stringof);    // void
pragma(msg, typeof(S!()).stringof); // Correctly fails because S!() is already a type, not an expression
```

**Comment by BorisCarvajal** [comment]
That's a particular case because `struct/class` are types themselves.

**Comment by RazvanN7** [comment]
I guess this patch is correct, then. I find it weird that template declaration have a type that is void. I would have expected that template declarations should have no type.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@WalterBright @Geod24 @thewilsonator to double check.

**Comment by RazvanN7** [comment]
This patch seems to consistently fail buildkite with:

```

optional 1.2.0: building configuration "optional-test-unittest"...
--
  | tests/oc.d(132,17): Error: cannot resolve type for oc(a).aTemplateFunctionArity1!""
  | tests/oc.d(133,17): Error: cannot resolve type for oc(b).aTemplateFunctionArity1!""
  | tests/oc.d(230,5): Error: static assert:  `__traits(compiles, oc(c).opDispatch(Args...)(auto ref Args args)())` is false
  | dmd failed with exit code 1.

```

**Comment by BorisCarvajal** [comment]
@RazvanN7 I know, `optional` lib fails because is using the same line of code that phobos used.

**Comment by RazvanN7** [comment]
So we should fix aliak/optional first. Care to make a PR?

**Comment by RazvanN7** [comment]
Awesome! Thanks @BorisCarvajal for the quick fixes!

**Pull request merged**
