### PR TITLE
[stable] [from master] Issue 19181: when an UFCS or opDispatch call has syntactically invalid arguments, always error.

### PR DESCRIPTION
**Pull request by FeepingCreature**
Cherry-pick from master. Sorry, I didn't understand how stable worked when I made the original PR and I don't particularly want to wait two months.

### CODE REVIEW

**Comment by FeepingCreature** [comment]
ping

**Comment by jacob-carlborg** [comment]
If I understand correctly we should not cherry pick.

**Comment by FeepingCreature** [comment]
Yeah explanations in slack suggest that adding the same commit in both branches will lead to merge issues later on.

**Comment by MartinNowak** [comment]
If you need to cherry-pick, please prefer to pick the merge commit (c2317ad3b7401dc9fe26a28cca66846a892d5d34), so we can find the original PR from the commit message.

**Pull request merged**
