### PR TITLE
remove ability to create static Symbol

### PR DESCRIPTION
**Pull request by WalterBright**
Now that removed all the static Symbol instances.

Eventually, Symbol should become an OOP class.

### CODE REVIEW

**Comment by yebblies** [comment]
I don't understand, what's going on here?

**Comment by WalterBright** [comment]
`Symbol` uses a very hackish C-like method of doing inheritance. For example, if it's a function, it allocates an extra struct and points to that. A much better way is to make `Symbol` a class and use inheritance.

Classes are reference types, so static instances are verboten. There's still a problem in that space is allocated at the end to hold the name, but that needs to go away and then `Symbol` can become a proper OOP class.

**Comment by yebblies** [comment]
Oh I see, this is the last member of Symbol.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
