### PR TITLE
free closname after use

### PR DESCRIPTION
**Pull request by WalterBright**
dmd's memory use is too high

### CODE REVIEW

**Comment by yebblies** [comment]
Yeah but this really isn't why...

**Comment by WalterBright** [comment]
> Yeah but this really isn't why...

Queue my comment about barnacles on a ship.

**Comment by yebblies** [comment]
Shouldn't we take care of the hole in the hull first?

**Comment by WalterBright** [comment]
> Shouldn't we take care of the hole in the hull first?

What is the point of deferring this PR? It's already done, it works.

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
