### PR TITLE
Merge stable into master

### PR DESCRIPTION
**Pull request by mihails-strasuns**
1) reverts https://github.com/dlang/dmd/pull/6172 because after moving it from flag hidden error to deprecation I have noticed some false positives in the test suite. FYI @WalterBright - this may need more work when re-implemented in master
2) provides merge commit for stable -> master which removes all traces of `-transition=safe` flag

After this PR is merges, following bugzilla issues need to be reopened:

- https://issues.dlang.org/show_bug.cgi?id=16589
- https://issues.dlang.org/show_bug.cgi?id=16193

@MartinNowak would be nice to merge this soon-ish to minimize propagation of `-transition=safe` related conflicts.

### CODE REVIEW

**Comment by MartinNowak** [comment]
I don't quite understand the thing about the reversion? Is it just a commit in your merge-stable?
Merging back stable should do nothing but merging and resolving merge conflicts.
If you want to revert sth. on master, I'd expect it to be a normal PR, if there are problems w/ a feature on stable, it should be reverted there. Reverting a whole feature during the merge b/c it now causes failures on master seems wrong.
I'd usually disable the test (and open a bug ticket) or fix the feature, sort of an extended/semantic merge conflict resolution.

**Comment by WalterBright** [comment]
Doesn't reverting this leave things in quite a mess? I no longer have idea what the state of the source code is in, between this, master, and the scope feature branch.

I had put these things behind `-transition=safe` in order to not break things while we work out all the details. Changing it to deprecated naturally broke things - is the solution really to just remove it all? Maybe the solution is to leave it as `-transition=safe`?

Renaming `global.params.safe` to `global.params.vsafe` has also fouled things up, as all those branches have now diverged.

>  I have noticed some false positives in the test suite.

Please be specific.

**Comment by WalterBright** [comment]
> Nope, vsafe existed only for a very short period of time in stable and was removed as soon as only change it was used for got reverted. Right now there is neither safe or vsafe in stable.

`vsafe` is there in master:
https://github.com/dlang/dmd/blob/master/src/globals.d#L115

But is `safe` in the feature branch:
https://github.com/dlang/dmd/blob/scope/src/globals.d#L115

**Comment by quickfur** [comment]
We really ought to have people target bugfix PRs to *both* master and stable (i.e., for the same bugfix submit 2 PRs, one for stable, one for master). This should be a requirement for merging. Otherwise once the branches diverge it's a lot of churn trying to resync the code and not break anything else.

**Comment by schveiguy** [comment]
@quickfur That's a recipe for disaster. If you fix the same thing in both branches, everything will be merge conflicts.

**Comment by WalterBright** [comment]
This PR is problematic because it lumps merging fixes in with merging reversions in an all-or-nothing manner.

**Comment by WalterBright** [comment]
>After this PR is merges, following bugzilla issues need to be reopened:
>https://issues.dlang.org/show_bug.cgi?id=16193

The reversion for that is https://github.com/dlang/dmd/pull/6251, and I only agreed to it for **stable**, not for **master**.

>After this PR is merges, following bugzilla issues need to be reopened:
>https://issues.dlang.org/show_bug.cgi?id=16589

I'm not seeing a rationale for this other than "reason for reverting
is that trying to remove flag protection has shown it results in some false
triggers in dmd test suite" which gives essentially no information. There's no clarification in https://issues.dlang.org/show_bug.cgi?id=16589 nor https://github.com/dlang/dmd/pull/6172 that it is reverting. Note that it did pass all tests when merged, so I have no idea what "some false triggers" are.

**Comment by schveiguy** [comment]
> The reversion for that is #6251, and I only agreed to it for stable, not for master.

This is problematic. Stable should only get fixes that should be pushed upstream. I don't like the idea that stable cannot be merged at-will into master. This will poison all future merges because you'd have to cherry pick this one thing out.

Perhaps we need a version branch to which such temporary reversions could be merged?

ping @MartinNowak, we need some guidance on this.

For the meantime, we likely have to merge the reversion to master, then revert the reversion!

**Comment by MartinNowak** [comment]
You guys are starring at the wrong PR. The reversion has already been split off to a separate PR https://github.com/dlang/dmd/pull/6290, and I can hardly provide even more information than there https://github.com/dlang/dmd/pull/6290#issuecomment-264706485 and in the bug report [Issue 16949 – [Reg 2.073] confusing @safe error message for fields with unsafe destructors](https://issues.dlang.org/show_bug.cgi?id=16949#c2).

**Comment by schveiguy** [comment]
@MartinNowak I'm concerned about a possibility of merging a PR into stable that should not be merged into Master (e.g. #6251). How does that affect future merges? How would one know not to remove it from a merge? Or am I not understanding something?

**Comment by MartinNowak** [comment]
> @MartinNowak I'm concerned about a possibility of merging a PR into stable that should not be merged into Master (e.g. #6251). How does that affect future merges? How would one know not to remove it from a merge? Or am I not understanding something?

That's not planned at all!
There is a lot of confusion around _this_ particular PR.

**Comment by MartinNowak** [comment]
Let's just merge back stable and do the rest of the adjustments on master, no need to conflate so many discussions into a single merge commit.
https://github.com/dlang/dmd/pull/6335

**Pull request closed without merging**
