### PR TITLE
Revert PR: "Windows: Allow enforced ANSI colors for redirected stderr"

### PR DESCRIPTION
**Pull request by RazvanN7**
Reverts: https://github.com/dlang/dmd/pull/12541

cc @WalterBright @kinke @CyberShadow

### CODE REVIEW

**Comment by thewilsonator** [comment]
Why?

**Comment by thewilsonator** [comment]
https://github.com/dlang/dmd/pull/12541#issuecomment-845448899 also this has been cherry picked LDC already https://github.com/ldc-developers/ldc/commit/aeeb90b241736bfe3706cf56b2955c40bb3d8ba8

**Comment by RazvanN7** [comment]
After this is reverted, I'm going to resubmit the patch in separate PRs.

**Comment by thewilsonator** [comment]
That is frankly a ridiculous waste of time.

**Comment by RazvanN7** [comment]
@thewilsonator Honestly, it takes a few seconds to put in a few git commands. If that is what it takes to extinguish the fire, that's not really a big deal.

**Comment by thewilsonator** [comment]
I don't care for what you do for DMD here, I do care for for the nuisance this causes LDC.

**Review by Geod24 — CHANGES_REQUESTED** [review]
There's no reason to revert perfectly working code. The complaint was about the number of commits in a single PR, reverting doesn't solve that.

**Review by wilzbach — CHANGES_REQUESTED** [review]
What a waste of time. This is exactly why people stopped contributing to D.

**Comment by WalterBright** [comment]
> The complaint was about the number of commits in a single PR, reverting doesn't solve that.

The complaint was about mixing a bug fix into a large refactoring.

**Comment by WalterBright** [comment]
> What a waste of time.

I know things are a bit heated, so let's try to reach some sort of consensus. Do you have recommendations for changes to the contributing guidelines?

**Comment by WalterBright** [comment]
> I do care for for the nuisance this causes LDC.

It shouldn't have any effect on LDC. The end result will be exactly the same.

**Comment by WalterBright** [comment]
> I don't care for what you do for DMD here

Please, everyone, do not lay into @RazvanN7 about this. Direct your ire towards me.

**Comment by WalterBright** [comment]
All this PR is doing is fixing the commit history so that the original PR is divided into two:

1. refactoring
2. bug fix

Not one character of @kinke's code will be changed. Nor am I asking anything of @kinke, @Geod24, @wilzbach or @thewilsonator I don't see how it wastes any of your time.

**Comment by thewilsonator** [comment]
> All this PR is doing is fixing the commit history so that the original PR is divided into two:

Incorrect, this converts the commit history from 4 commits into 12 commits that do the same thing assuming that you make no changes. 

Also, there was no merge commit on #12541 and its commits were separate, as rebase & merge is the default, which is why I merged that PR as it was. If you want to revert a single commit of that PR use `git revert hash-of-commit`.

To put it another way, the commit history is _exactly_ the same as if #12541 had been split in to 4 and rebased & merged back-to-back.

> I don't see how it wastes any of your time.

I had assumed you wanted changes which would have caused merge conflicts for LDC, however...

> Not one character of @kinke's code will be changed

... If this is your intention, then this PR achieves less than nothing and should be closed.
If you don't understand why, then please read the documentation on `git revert`. 
If it still doesn't make sense, please do ask!

**Comment by RazvanN7** [comment]
I, personally, don't have a strong opinion on whether this should be merged or not. It's probably better if we let this slide and close this PR, however, the bigger picture here is that bug fixes should not be mixed with refactorings. @WalterBright does have a point here and the way I see it we either enforce this policy or we just drop it. Having something in the middle like: "we generally do not mix refactorings with bug fixes, but there are occasions when we accept it because ...." is the worst of both worlds and causes endless discussions such as this one. Therefore, I don't really care on how this ends up as long as we decide on somethings and go with it in the future.

Note: why is everyone so fixated on this being a waste of time? It's literally just 2-3 git commands that I will take care of and @kinke 's code will still end up it master untouched. @WalterBright 's concerns are met, the code is still in master; everyone is happy. If anything is a waste of time, it's this discussion going forward without ironing out what the procedure should be in the future.

**Comment by WalterBright** [comment]
> this PR achieves less than nothing

It splits it into 1 bug fix and 1 refactoring. I've explained why this is important at least a dozen times. If you want to argue its importance, that's ok as I'm interested in your feedback, but please don't just ignore everything I wrote.

**Comment by WalterBright** [comment]
> there was no merge commit

As I wrote in that PR, I clicked on each of those commits and they were all the whole change. I am not asking for the moon. Just having the 3 or 4 line bug fix be a separate PR, for reasons explained a dozen times. As @RazvanN7 wrote, we either have contribution guidelines or we're cowboying things. After that long thread in the n.g. about people not understanding the dmd code, I would have thought you'd agree!

https://digitalmars.com/d/archives/digitalmars/D/How_can_we_make_it_easier_to_experiment_with_the_compiler_350443.html

**Comment by thewilsonator** [comment]
>  but please don't just ignore everything I wrote.

I would ask the same:

>> All this PR is doing is fixing the commit history [...]

> To put it another way, the commit history is exactly the same as if #12541 had been split in to 4 and rebased & merged back-to-back.

I perceive a logical inconsistency with what you're asking for here. Either you care about the commit history, in which case why is there an argument in the fist place, or you care about something else that I'm not getting.

**Comment by thewilsonator** [comment]
> As I wrote in that PR, I clicked on each of those commits and they were all the whole change. 

I don't know what you're doing, but for multi commit PRs e.g. like #12541 e.g. https://github.com/dlang/dmd/pull/12541/commits/99cbeb9e057f35c9b018f85913b574a7b592804e and https://github.com/dlang/dmd/pull/12541/commits/13d543f892a31945999d567faff7d0b03336ef0d show _very_ different things.

**Comment by WalterBright** [comment]
None of them isolate the bug fix which is: https://github.com/dlang/dmd/pull/12541#issuecomment-851673941

**Comment by thewilsonator** [comment]
> After that long thread in the n.g. about people not understanding the dmd code, I would have thought you'd agree!

I do, but there is a difference between the codebase and the differential revisions of its history.
In particular, I have absolutely no problem with multi commit PRs that mix refactors and bug fixes. I agree its a bad idea to do refactoring and bug fixing in the same commit of reasonable size (i.e. unless its like a one or a small handful of line change with the bug fix and refactor in the same commit).

**Comment by WalterBright** [comment]
> or you care about something else that I'm not getting.

I care about: THE BUG FIX BEING IN A SEPARATE PR. As it says in the contributor guidelines. I am baffled by my inability to explain this.

> I have absolutely no problem with multi commit PRs that mix refactors and bug fixes.

I do, for reasons explained a dozen times. It's in the contributor guidelines. (I did a PR that emphasized this, as nobody seemed to notice it.) Just like I expect functions to have a function Ddoc comment. We won't get anywhere if each of us has a very different idea of what the minimum standard for a PR should be. Heck, I don't agree with everything in it, but I still follow it.

**Comment by WalterBright** [comment]
> there is a difference between the codebase and the differential revisions of its history.

The history is very important when one needs to fix a regression, or discover *why* a piece of code is the way it is. It's part of the whole reason for using Github. Having readable histories is crucial. Burying bug fixes in large refactorings is technical debt.

I am not making this up. I have experience with what happens when I try to figure out what went wrong when git bisect points the finger at a PR. It costs me hours of time trying to untangle things. I am done with that. I am not asking for unreasonable things here - I'm asking for experience-driven standards on what works and what causes problems.

**Comment by Geod24** [comment]
With 3 against and 1 in favor, and no visible benefit, I'm going to close this so we all do not waste more time on this.

**Pull request closed without merging**
