### PR TITLE
STC should be ulong

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by Geod24** [comment]
Then https://github.com/dlang/dmd/blob/ba0178454db39803762a24b22e2fbf68f63d54e9/src/dmd/declaration.h#L32-L89 needs to be updated too

**Comment by WalterBright** [comment]
It's already a uinteger_t.

**Comment by UplinkCoder** [comment]
LGTM

**Review by thewilsonator — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]

**Comment by Geod24** [comment]
Auto-merge toggled on

**Pull request merged**
