### PR TITLE
fix bugzilla Issue 24836 - struct return by hidden struct arg does no…

### PR DESCRIPTION
**Pull request by WalterBright**
…t need copy to become an rvalue

### CODE REVIEW

**Comment by WalterBright** [comment]
Oh why oh why are the phobos unittests run before the test suite? The build process builds the compiler, then tries to compile d_do_test, which relies on:
```
import std.algorithm;
import std.array;
import std.conv;
import std.datetime.stopwatch;
import std.datetime.systime;
import std.exception;
import std.file;
import std.format;
import std.meta : AliasSeq;
import std.process;
import std.random;
import std.range : chain;
import std.regex;
import std.path;
import std.stdio;
import std.string;
import core.sys.posix.sys.wait;
```
which tries to run the unittests while building it, and so everything must work perfectly in phobos and d_do_test for it to even get to the test suite. The comments in it say it is supposed to be called by the Makefile - what Makefile?

**Comment by WalterBright** [comment]
Why is it missing the simplest:

1. how to build it
2. how to run it

?

**Comment by WalterBright** [comment]
I found another way to debug it. d_do_test still needs much in the way of documentation.

**Comment by WalterBright** [comment]
Testing optimizations is rarely very practical.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
