### PR TITLE
 Prevents the import of object module when -dnostdlib has been passed

### PR DESCRIPTION
**Pull request by ghost**
Depends on https://github.com/dlang/dmd/pull/10180

### CODE REVIEW

**Comment by marler8997** [comment]
Most of `object.d` is templated now, so if you don't use anything from `object.d` then it's really not doing anything.  What's the reasoning for adding a command-line option to disable `object.d`?

**Comment by JinShil** [comment]
The problem is that the compiler automatically imports `object.d`.  If it can't find it in the import path, DMD emits a compiler error.  For the use case that this PR addresses, the user doesn't need `object.d`, but the user is forced to create an empty one just to keep the compiler from complaining.

**Comment by marler8997** [comment]
I wonder if it would be better to allow the source to specify this in some way?  Maybe through a pragma?  `pragma(noObjectModule)`?

**Comment by marler8997** [comment]
I've created an alternative solution here: https://github.com/dlang/dmd/pull/10188

**Review by Geod24 — CHANGES_REQUESTED** [review]
Having a standard module with definitions such as `alias size_t = (void*).sizeof;` or `string` is not inherently incompatible with a `-dnostdlib`. So IMO they should not be conflated.

**Comment by marler8997** [comment]
> Having a standard module with definitions such as alias size_t = (void*).sizeof; or string is not inherently incompatible with a -dnostdlib. So IMO they should not be conflated.

I think most things in `object.d` really don't do any harm which was the point that @andralex brought up.  Most things in `object.d` are already pay for what you use.  It's not all there yet but I think it can be at some point.  The only use case I've heard for removing the `object.d` import is when you don't need/want it and you don't want to create an empty one.

**Comment by WalterBright** [comment]
The need for such a feature is so specialized that the programmer doing it shouldn't have any difficulty creating a dummy object.d with nothing in it to import.

I don't think this feature pulls its weight.

**Pull request closed without merging**
