### PR TITLE
Fix Issue 16284 - [REG2.067] CTFE internal error: bad compare

### PR DESCRIPTION
**Pull request by JinShil**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@JinShil please provide a description.
My intuition: this fix seems to allow more then intended.

**Comment by WalterBright** [comment]
What this solution does is decide that void initialized fields (which is done for unions) should compare equal to other void initialized fields. This makes me uneasy. I'd rather they compared unequal. Or even issue an error.

In any case, this behavior should be documented in the spec.

**Comment by JinShil** [comment]
What appears to happen is whenever a single field of a union is assigned to, the CTFE interpreter sets all other fields to `void` as a way of invalidating them, or so I assume.  

See https://dlang.org/changelog/2.065.0.html#ctfe-overlapped-field
See https://github.com/dlang/dmd/blob/03e806abaae49fe84de8fc0bdbe2ead80f58d038/src/ddmd/dinterpret.d#L3959-L3960

If that's by design, then any aggregate containing a union and an assigned-to field will never compare to equality.  I need some clarification on how this should behave in order to continue.

**Comment by JinShil** [comment]
According to GitHub's blame feature @9rnsr was the author that introduced the `dinterpret.stompOverlappedFields()` feature for `union`s.  @UplinkCoder are you the resident expert on this.  If so, what are your thoughts?

**Comment by stefan-koch-sociomantic** [comment]
changing the old interpreter to not relay on the void expr,
is going to be tricky;
newCTFE will not relay on the void expression in order to check the current valid fields.

**Comment by JinShil** [comment]
We need a design for this.  Closing until we have one.

**Comment by WalterBright** [comment]
I changed my mind, this is the right fix.

**Comment by WalterBright** [comment]
Eek! Too many diffs. Will reboot.

**Comment by thewilsonator** [comment]
I accident rebased again master instead of stable.

**Comment by thewilsonator** [comment]
Its 15 lines.

**Pull request closed without merging**
