### PR TITLE
make the Statement is*** functions pure, nothrow, etc.

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by PetarKirov — APPROVED** [review]

**Review by jacob-carlborg — COMMENTED** [review]
Please avoid aligning the code. We’re not writing code in spreadsheets.

**Comment by WalterBright** [comment]
When the code forms a pattern, it should be aligned. Alignment makes it easy to see where it is the same, and where it is different. It's far easier to read than the original.

**Comment by jacob-carlborg** [comment]
> When the code forms a pattern, it should be aligned. Alignment makes it easy to see where it is the same, and where it is different. It's far easier to read than the original.

I requires extra work to align the code and doesn't increase the readability. Adding new lines would often require realigning all lines causing unnecessary big diffs making it difficult to see which line was added.

I know you won't change but I try 😄.

**Comment by thewilsonator** [comment]
My internet connection seems to be crap, and I cannot load any if the CI pages, so I can't tell if those failures are unrelated. If they are please merge.

**Comment by jacob-carlborg** [comment]
CircleCI failed to download `install.sh` with a timeout. `d-language-server/dls` fails, not sure why.

**Comment by thewilsonator** [comment]
`dls` had been randomly segfaulting for a while now.

**Pull request merged**
