### PR TITLE
Fix isLvalue error message

### PR DESCRIPTION
**Pull request by ntrel**
Requiring an lvalue is not the same as requiring modification.
Fix Issue 23791 - Rvalue default argument for ref parameter gives misleading error.

 Merge 2 tests & add test for a type used as a default argument.

### CODE REVIEW

**Comment by RazvanN7** [comment]
As a general rule of thumb, I think we should avoid putting compiler slang in error messages. Lvalue/rvalue might be confusing terms for some parts of our audience.

I think that for the vast majority of cases outputting "cannot modify variable $variable" is fine. However, in the case of rvalues we just need to

**Comment by PetarKirov** [comment]
> As a general rule of thumb, I think we should avoid putting compiler slang in error messages.

If a supplemental error message links to the specification where the term is defined, I don't see a problem with that. Note that there is a difference between a compiler-internal term like visitor, IR, etc. and term defined in the language specification like POD or in this case lvalue/rvalue.

**Comment by ntrel** [comment]
I learned lvalue/rvalue when learning C. If there are better concise terms I'd like to know. (In any case they were already used in messages).

> I think that for the vast majority of cases outputting "cannot modify variable $variable" is fine

It's confusing when you're not trying to modify anything, as well as wrong. Compilers should use precise language IMO.

> in the case of rvalues we just need to special case the message to "cannot modify literal $literal".

Literals are just a subset of rvalues.

**Comment by ntrel** [comment]
Superceded by https://github.com/dlang/dmd/pull/15793.

**Pull request closed without merging**
