### PR TITLE
Remove Travis testing

### PR DESCRIPTION
**Pull request by wilzbach**
- Travis got super slow and unreliable over the last weeks
- Even reduced to [only one OSX job](https://github.com/dlang/dmd/pull/7653) it still takes hours for a PR to build
- We often run into failures as the job reaches the maximal 50 minutes build limit
- Travis was only intended to test bootstrapping with the latest DMD + GDC + LDC (SemaphoreCI does this [now pretty reliable](https://github.com/dlang/dmd/pull/7617#issuecomment-357567565).
- If https://github.com/dlang-bots/dlang-bot/pull/69 gets merged, we would need to wait for hours or even days until a PR gets merged (even if all other CI pass)

Or in Martin's word:

> What's the worth of a CI that doesn't report back in 1 day.

See also:
- https://github.com/dlang-bots/dlang-bot/pull/69#issuecomment-357854277
- https://github.com/dlang/dmd/pull/7617#issuecomment-357567938
- https://travis-ci.org/dlang/dmd/builds
- http://forum.dlang.org/post/ronypzvsafxpqlpnxlsf@forum.dlang.org (Heads-up for pending auto-merge change)
- http://forum.dlang.org/post/zbxaviowooiaenaawmgs@forum.dlang.org (Re: Bump the minimal version required to compile DMD to 2.076.1)

CC @MartinNowak

### CODE REVIEW

**Comment by JinShil** [comment]
So does this mean we have to forego the OSX tests?

**Comment by wilzbach** [comment]
> So does this mean we have to forego the OSX tests?

To be clear: OSX is still fully tested for 64_32 and 64_64 on auto-tester.
Travis/Semaphore only tests bootstrapping with the latest release - in Martin's words:

> so let me repeat what was decided when we made the frontend switch from C++ to D.
> - Other platforms are bootstrapped by cross-compilation.
> - DMD must be compilable with the latest stable/major release of dmd, ldc, and gdc.
>   To enforce this policy the Travis-CI test was set up.

http://forum.dlang.org/post/zbxaviowooiaenaawmgs@forum.dlang.org

**Comment by JinShil** [comment]
> Travis/Semaphore only tests bootstrapping with the latest release

Ok, so we are giving up the OSX bootstrap tests, right?

**Comment by wilzbach** [comment]
> Ok, so we are giving up the OSX bootstrap tests, right?

Yep.

**Comment by jacob-carlborg** [comment]
What about macOS on CircleCI?

**Comment by wilzbach** [comment]
> What about macOS on CircleCI?

We only get 500 minutes for free / month:

> > What if I am building open-source?
> We also offer the Seed plan for macOS open-source projects:

> 2x macOS concurrency
> Recommended for teams building 1-5 builds/day
> 500 max minutes/month*
...
> Overages are as follows:
> Seed & Startup: .08/minute

**Comment by jacob-carlborg** [comment]
> We only get 500 minutes for free / month:

Right, forgot that part.

**Comment by MartinNowak** [comment]
There was an outage of OSX on Travis-Ci hence their huge backlog.
https://www.traviscistatus.com/incidents/6xb4kjczh4k6
Looks like they've upped their capacity just today.
image

As we were just digging into the purpose of that OSX test, we figured it became obsolete now that glibc/gcc is no longer used on OSX.
https://github.com/dlang-bots/dlang-bot/pull/69#issuecomment-358071363
Here was the original cause that lead to the addition of the clang based OSX tester.
https://github.com/dlang/druntime/pull/1542

> So does this mean we have to forego the OSX tests?

Not at all, the auto-tester was and will remain our central CI infrastructure. Other things were only added to supplement it, or temporarily to bridge missing parts.

**Review by MartinNowak — APPROVED** [review]

**Pull request merged**
