### PR TITLE
extend #5024 for SCshadowreg

### PR DESCRIPTION
**Pull request by WalterBright**
https://github.com/D-Programming-Language/dmd/pull/5024

### CODE REVIEW

**Comment by WalterBright** [comment]
std.net.curl fails again. What a surprise, but it has nothing to with this PR.

**Comment by yebblies** [comment]
If only there was a way to make the autotester re-run on that platform...

**Comment by WalterBright** [comment]
It's passing now.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
Hmm. This always fails on Win64, and shadowreg is only for Win64. Looks like there's some problem with it. I'm going to abandon this for now.

**Pull request closed without merging**
