### PR TITLE
Fix Issue 22356 - Can't mixin the return type of a function

### PR DESCRIPTION
**Pull request by BorisCarvajal**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
I predict unintended consequences.

**Comment by BorisCarvajal** [comment]
> I predict unintended consequences.

You are a very pessimistic person. :stuck_out_tongue:

**Comment by 12345swordy** [comment]
Doesn't this require a spec change?

**Comment by BorisCarvajal** [comment]
> Doesn't this require a spec change?

No.
See the bug report pls and look at the examples, they already work at statement level.

```
According to the language spec, any BasicType can be used as a function return type [1],
and a MixinType can be used anywhere a BasicType is allowed [2], so the program should compile.

[1] https://dlang.org/spec/function.html#FuncDeclaration
[2] https://dlang.org/spec/type.html#BasicType
```

**Comment by thewilsonator** [comment]
Please rebase to fix the CI issues

**Pull request merged**
