### PR TITLE
Fix Issue 22014 - Wrong MSVC++ mangling of wchar_t

### PR DESCRIPTION
**Pull request by RazvanN7**
cc @TurkeyMan as you introduced this in the first place.

### CODE REVIEW

**Comment by thewilsonator** [comment]
The issue is wrong and confuses D's ` wchar` (which is C++'s `char16_t`) with `wchar_t` which is neither of those. 
This PR and that issue should be closed as working as intended.

**Comment by thewilsonator** [comment]
Hmm, I thought we had a `wchar_t` akin to `c_long` and friends: see https://github.com/dlang/druntime/pull/2349 https://github.com/dlang/dmd/pull/8958

**Review by thewilsonator — CHANGES_REQUESTED** [review]
see comments

**Comment by ibuclaw** [comment]
Agreed, wchar_t is 16-bit on Windows, not 32-bit.

**Comment by ibuclaw** [comment]
The fix should instead go in druntime, the `core.stdc.stddef` module is not right for C++ compatibility.
```
version (Windows)
{
    ///
    alias wchar wchar_t;
}
else version (Posix)
{
    ///
    alias dchar wchar_t;
}
```
That should instead be something like.
```
version (Windows)
    private enum __c_wchar_t : wchar;
else version (Posix)
    private enum __c_wchar_t : dchar;
///
alias wchar_t = __c_wchar_t;
```

**Comment by ljmf00** [comment]
> Agreed, wchar_t is 16-bit on Windows, not 32-bit, and we already have `__c_wchar_t` which does the correct mangling.

Just for context, `__c_wchar_t` is hardcoded as a special TY in the compiler? Is it detected as `TYwchar`? This may affect DWARF generation, since we are using that TY for both types.

**Comment by maxhaton** [comment]
> > Agreed, wchar_t is 16-bit on Windows, not 32-bit, and we already have `__c_wchar_t` which does the correct mangling.
> 
> Just for context, `__c_wchar_t` is hardcoded as a special TY in the compiler? Is it detected as `TYwchar`? This may affect DWARF generation, since we are using that TY for both types.



> 

https://github.com/dlang/dmd/blob/6908173c62b40a4f3f179d4bd57f38ee2f5f400e/src/dmd/cppmangle.d#L1885

**Comment by maxhaton** [comment]
not sure what the backend actually gets in that case, worth investigating.

**Comment by ljmf00** [comment]
> > > Agreed, wchar_t is 16-bit on Windows, not 32-bit, and we already have `__c_wchar_t` which does the correct mangling.
> > 
> > 
> > Just for context, `__c_wchar_t` is hardcoded as a special TY in the compiler? Is it detected as `TYwchar`? This may affect DWARF generation, since we are using that TY for both types.
> 
> > 
> 
> https://github.com/dlang/dmd/blob/6908173c62b40a4f3f179d4bd57f38ee2f5f400e/src/dmd/cppmangle.d#L1885

I'm going to make a patch on the DWARF generator to fix the wrong behavior and discuss it there. I'm talking about the TY enum. If we have `__c_wchar_t` as a special type, we should distinguish it from `TYwchar`, because on DMC, the backend interprets `TYwchar` as `wchar_t` (from C), but on DMD, the backend interprets `TYwchar` as `wchar`. If we don't have any special TY for that, we need to hardcode the string on the backend. I didn't know about this case but the DWARF generator reports a different typedef for that type and the debugger can't understand it as `wchar_t`.

**Pull request closed without merging**
