### PR TITLE
Fix Issue 17080 - Can assign member-function-ptr to free-function-ptr

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**

### CODE REVIEW

**Comment by LemonBoy** [comment]
A test-case is needed along with a proper commit message.
It seems that D1 had the same problem [1], heh.

[1] https://issues.dlang.org/show_bug.cgi?id=2557

**Comment by mathias-baumann-sociomantic** [comment]
Yeah, this was more a way to run the test suite for me currently.. But the fix seems to be more difficult than I anticipated

**Comment by JinShil** [comment]
@mathias-baumann-sociomantic Does this PR have a future?

**Comment by mathias-baumann-sociomantic** [comment]
Unlikely currently.

**Comment by JinShil** [comment]
> Unlikely currently.

Closing then.  Feel free to re-open if you ever wish to revisit it.  Though, I may beat you to it.

**Pull request closed without merging**
