### PR TITLE
Revert "detect noreturn statements"

### PR DESCRIPTION
**Pull request by Geod24**
This reverts commit 0fc1fc0539659d03acb9f39d01415778391bfcda.
This commit broke ocean on Buildkite, because it started emitting
'Statement is not reachable' after `abort`, which wasn't detected before.
This is a good thing and the project will be fixed, but let's not
halt all development on core projects in the meantime.

### CODE REVIEW

**Comment by Geod24** [comment]
For reference, this is the statement that is now triggering the warning:
https://github.com/sociomantic-tsunami/ocean/blob/81050e06f3197e637ab6090b027c158fa28691a2/src/ocean/net/http/HttpStack.d#L66

I'll replace the `abort` with `assert(0)`, but making a new release takes a bit of time (and other projects have dependencies on Ocean).

**Comment by RazvanN7** [comment]
It's weird that buildkite passed all tests on the offending PR.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
The circleCi failure is spurios. We can merge this by hand when all tests pass.

**Comment by RazvanN7** [comment]
@MoonlightSentinel I thought that this should have been fixed.

**Comment by MoonlightSentinel** [comment]
Thought so too, but apparently it just made it less likely to fail (tested it several times without encountering this error).

Sadly there still no response from CodeCov on this issue (which affects several repos)

**Comment by RazvanN7** [comment]
cc @WalterBright

**Comment by Geod24** [comment]
Fix submitted: https://github.com/sociomantic-tsunami/ocean/pull/840
Will merge when green, and get started on a release.

**Pull request merged**
