### PR TITLE
Revert "mtype: Add TypeAggregate and refactor repetitive code for structs and classes"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/dmd#13734

### CODE REVIEW

**Comment by RazvanN7** [comment]
Is reverting this entirely necessary? IIUC the problem is that some .h files need to be updated. Can't we do that instead of reverting this?

**Comment by ibuclaw** [comment]
So you want me to trawl through a large non-trivial diff to work out what interfaces have changed? No thanks, the other PR should have not passed review.

**Comment by RazvanN7** [comment]
No, my expectation is that you can give us a moment so that @ljmf00 or myself cand fix it.

**Comment by RazvanN7** [comment]
Anyway, I will merge this and we can resubmit this once the headers are updated so that you are not blocked anymore.

**Review by RazvanN7 — APPROVED** [review]

**Comment by ljmf00** [comment]
Can you describe your problems with this change in the GCC tree? I see usefulness of having a TypeAggregate node, although I don't know a better way of casting the generic AggregateDeclaration without breaking the C++ interfaces. I think we should move forward with the idea, anyway, but please present me an alternative solution. See the PR related to the reverted change for a proposed alternative.

**Comment by ibuclaw** [comment]
@ljmf00 the C++ interface should be updated in lock-step, that's all.  The C++ front-end tests should really be more extensive so it can catch more frequently when someone is unintentionally messing with the vtable, or changing field offsets.  Maybe a mini back-end would be enough, but that's an extra amount of work that probably no one would have time for.

**Pull request merged**
