### PR TITLE
convert a for loop in AggregateDeclaration.determineFields to a foreach loop

### PR DESCRIPTION
**Pull request by Herringway**

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
See https://github.com/dlang/dmd/pull/8955#discussion_r233616764

**Review by thewilsonator — APPROVED** [review]

**Comment by Herringway** [comment]
Hrm. I suppose this isn't much different than those past attempts. I'll close this then.

**Comment by ZombineDev** [comment]
@Herringway see if you can use `foreachDsymbol`, or something along those lines:
https://github.com/dlang/dmd/commit/53523fa52363f0c02829538269a8a06f1ab06b67

**Comment by Herringway** [comment]
It's possible, but I don't know if it can be done without making this code uglier.

**Pull request closed without merging**
