### PR TITLE
toir.setClosureVarOffset: Use early return

### PR DESCRIPTION
**Pull request by Geod24**

### CODE REVIEW

**Comment by atilaneves** [comment]
I like this but don't know what @WalterBright thinks.

**Review by MoonlightSentinel — APPROVED** [review]

**Comment by Geod24** [comment]
> I like this but don't know what @WalterBright thinks.

There's plenty of precedent for this refactoring. IIRC it was a common feedback by Andrei, following a Code Complete advice.

See for example:
- https://github.com/dlang/dmd/pull/10893
- https://github.com/dlang/dmd/pull/8572
- https://github.com/dlang/dmd/pull/10399
- https://github.com/dlang/dmd/pull/10344

Those are all mine because searching for "early return" was easier, but I've definitely seen it in other people's code.

**Comment by atilaneves** [comment]
> > I like this but don't know what @WalterBright thinks.
> 
> There's plenty of precedent for this refactoring. IIRC it was a common feedback by Andrei, following a Code Complete advice.
> 
> See for example:
> 
>     * #10893
> 
>     * #8572
> 
>     * #10399
> 
>     * #10344
> 
> 
> Those are all mine because searching for "early return" was easier, but I've definitely seen it in other people's code.

Awesome. Like I said, I'm fully in favour.

**Comment by WalterBright** [comment]
I'm all right with new code, etc., being done in this style. I'm less all right with churning the existing code base with massive diffs over a minor stylistic issue.

**Comment by Geod24** [comment]
I'm not going over the code to apply this pattern, I have other changes to make to this function but since you wanted small / separate PR I submitted this separately.

**Pull request merged**
