### PR TITLE
Revert "Fix issue 17793 - ICE using simd.double4 as array"

### PR DESCRIPTION
**Pull request by wilzbach**
Reverts dlang/dmd#9832

This was failing on our bootstrapping CI and was still merged :angry:

see e.g. https://semaphoreci.com/dlang/dmd-2/branches/stable/builds/230

image

tl;dr: we can no longer compile DMD master with GDC 8. The CI was testing this.
The error:

```
dmd.o:access.d:function PrintASTVisitor::printIndent(int): error: undefined reference to '_D4core4stdc5stdio4putcFNbNiNeiPOS4core4stdc5stdio8_IO_FILEZi'
dmd.o:access.d:function PrintASTVisitor::visit(StructLiteralExp*) [clone .localalias.1878]: error: undefined reference to '_D4core4stdc5stdio4putcFNbNiNeiPOS4core4stdc5stdio8_IO_FILEZi'
dmd.o:access.d:function PrintASTVisitor::visit(Expression*) [clone .localalias.169]: error: undefined reference to '_D4core4stdc5stdio4putcFNbNiNeiPOS4core4stdc5stdio8_IO_FILEZi'
dmd.o:access.d:function PrintASTVisitor::visit(UnaExp*) [clone .localalias.1873]: error: undefined reference to '_D4core4stdc5stdio4putcFNbNiNeiPOS4core4stdc5stdio8_IO_FILEZi'
../generated/linux/release/64/backend.a(dwarfdbginf.o):dwarfdbginf.d:function dwarf_initfile(char const*): error: undefined reference to '_D4core4stdc5errno5errnoFNbNdNiNeZi'
../generated/linux/release/64/backend.a(dwarfdbginf.o):dwarfdbginf.d:function dwarf_initfile(char const*): error: undefined reference to '_D4core4stdc5errno5errnoFNbNdNiNeiZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNefZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNefZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNeeZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNefZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNefZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNedZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNedZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNeeZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNeeZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function boolres(elem*): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNedZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function evalu8(elem*, unsigned int): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNeeZi'
../generated/linux/release/64/backend.a(evalu8.o):evalu8.d:function evalu8(elem*, unsigned int): error: undefined reference to '_D4core4stdc4math5isnanFNbNiNedZi'
../generated/linux/release/64/lexer.a(globals.o):globals.d:function _D3dmd7globals3Loc6toHashMxFNaNbNeZm: error: undefined reference to '_D4core8internal4hash9bytesHashFNaNbNiPxvmmZm'
../generated/linux/release/64/lexer.a(globals.o):globals.d:function _D3dmd7globals3Loc6toHashMxFNaNbNeZm: error: undefined reference to '_D4core8internal4hash9bytesHashFNaNbNiPxvmmZm'
../generated/linux/release/64/lexer.a(globals.o):globals.d:function _D6object14__T6hashOfTxkZ6hashOfFNaNbNfKxkmZm: error: undefined reference to '_D4core8internal4hash9bytesHashFNaNbNiPxvmmZm'
../generated/linux/release/64/lexer.a(globals.o):globals.d:function _D6object15__T6hashOfTAxaZ6hashOfFNaNbNiAxamZm: error: undefined reference to '_D4core8internal4hash9bytesHashFNaNbNiPxvmmZm'
../generated/linux/release/64/lexer.a(ctfloat.o):ctfloat.d:function CTFloat::parse(char const*, bool*): error: undefined reference to '_D4core4stdc5errno5errnoFNbNdNiNeiZi'
../generated/linux/release/64/lexer.a(ctfloat.o):ctfloat.d:function CTFloat::parse(char const*, bool*): error: undefined reference to '_D4core4stdc5errno5errnoFNbNdNiNeZi'
../generated/linux/release/64/lexer.a(file.o):file.d:function File::read(): error: undefined reference to '_D4core4stdc5errno5errnoFNbNdNiNeZi'
../generated/linux/release/64/lexer.a(file.o):file.d:function File::read(): error: undefined reference to '_D4core4stdc5errno5errnoFNbNdNiNeZi'
../generated/linux/release/64/lexer.a(filename.o):filename.d:function FileName::ensurePathExists(char const*) [clone .localalias.2]: error: undefined reference to '_D4core4stdc5errno5errnoFNbNdNiNeiZi'
../generated/linux/release/64/lexer.a(port.o):port.d:function Port::isFloat32LiteralOutOfRange(char const*): error: undefined reference to '_D4core4stdc5errno5errnoFNbNdNiNeiZi'
collect2: error: ld returned 1 exit status
```

Hence, I suggest a revert, s.t. we can have time to figure this out.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Hmm, semaphore does't seem to load for me.

**Comment by SSoulaimane** [comment]
Still fails though.

**Comment by thewilsonator** [comment]
YEah I don't think this was the PR that caused that.

**Comment by ibuclaw** [comment]
My guess would be there's been a change in the semaphore CI environment.  Hazarding a guess, using gdc-8 to link against a gdc-9 compiled library?

**Comment by ibuclaw** [comment]
gdc-9 was pushed to the ppa 22 hours ago.  https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

@wilzbach - Upgrade the compiler!!!!

**Comment by wilzbach** [comment]
Sorry for the false alert. It looked very suspicious on the CI history.

**Pull request closed without merging**
