### PR TITLE
use ldc-0.16.0-beta2 for testing ddmd

### PR DESCRIPTION
**Pull request by MartinNowak**
- based on 2.067.1 frontend

### CODE REVIEW

**Comment by MartinNowak** [comment]
Didn't we have that problem with ldc-15.2 already? You should really build your releases in a virtualized environment.

**Comment by redstar** [comment]
Well, I am building the release in a VirtualBox environment. I thought I had ultimately fixed the problem (its simply adding `--static-libstdc++` to the flags) but apparently that's not the case.

**Comment by MartinNowak** [comment]
Trying again w/ alpha4.

**Comment by MartinNowak** [comment]
Now compiles ddmd but triggers an assertion https://github.com/D-Programming-Language/dmd/blob/b6e5152c188e4eee567712a095386b8ee8eec05a/src/expression.d#L4417.

**Comment by MartinNowak** [comment]
retry with beta1

**Comment by MartinNowak** [comment]
retry with beta2

**Comment by yebblies** [comment]
Looking good!

**Comment by redstar** [comment]
Nice!

**Pull request merged**
