### PR TITLE
ci(pre-commit): add stable branch to ci triggers

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by ljmf00** [comment]
Shouldn't we cherry-pick this to `stable` too?

**Comment by PetarKirov** [comment]
> Shouldn't we cherry-pick this to stable too?

@ljmf00 Yes, but I think we would also need to cherry-pick all the related fixes (e.g. `test22886.c`, `fail22825a.d`, etc.).

**Comment by ljmf00** [comment]
> > Shouldn't we cherry-pick this to stable too?
> 
> @ljmf00 Yes, but I think we would also need to cherry-pick all the related fixes (e.g. `test22886.c`, `fail22825a.d`, etc.).

Well, right. That would be hard, but doable.

**Comment by PetarKirov** [comment]
@ljmf00 Alternatively, we can simply wait for the next master -> stable merge (before the first 2.100 beta is released).

**Comment by RazvanN7** [comment]
If I understand correctly this PR attempts to add the pre-commit check for the stable branch, however, stable is behind master with regards to some fixes. I suggest we leave stable as is and wait for the master->stable merge, until then we can fix all of the potential config bugs for pre-commit. The alternative would be to always duplicate fixes in both master and stable.

**Comment by ljmf00** [comment]
Yup, we can merge this and then when it's time for `master -> stable` this will enter naturally.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
