### PR TITLE
[cleanup] Unify checkSomething function interfaces.

### PR DESCRIPTION
**Pull request by 9rnsr**
When an error occurs in `bool checkSomething()` function, not they consistently return `true` for error propagation.

### CODE REVIEW

**Comment by 9rnsr** [comment]
A small error propagation change in `BinAssignExp::semantic()` fixes [issue 13320](https://issues.dlang.org/show_bug.cgi?id=13320).

**Comment by WalterBright** [comment]
But if there's already an error, why add checks for more errors?

**Comment by 9rnsr** [comment]
TOKtype cannot appear in array elements. It's definitely an error, but error message is not yet shown. In here, checkValue is used just for reusing error text.

**Comment by WalterBright** [comment]
ok, please add comment to that effect.

**Comment by 9rnsr** [comment]
done

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
