### PR TITLE
test autotester

### PR DESCRIPTION
**Pull request by WalterBright**
The autotester seems to be always failing in cppa.d line 252 in multiple PRs. Let's see if it happens in a no-change change.

### CODE REVIEW

**Comment by yebblies** [comment]
It's only failing on one of the tester machines, `D-Autotester.local`.

**Comment by WalterBright** [comment]
I guess what does that mean? (I cannot repro it on my OSX machine.)

**Comment by yebblies** [comment]
It most likely means the trigger is in the environment of that machine.  My guess would be that it has a different host C++ compiler than the other OSX testers, maybe it was upgraded recently. @braddr ?

**Comment by WalterBright** [comment]
I tried both clang++ and g++ on my OSX machine. Both worked.

**Comment by WalterBright** [comment]
This one is passing on OSX. Vot de hek is happenink.

**Comment by yebblies** [comment]
> It's only failing on one of the tester machines, `D-Autotester.local`.

**Comment by braddr** [comment]
I haven't change anything on the failing box in ages.  It is a vm on Steven Schveighoffer's box, so he might have changed something, but I doubt it.  He's very good about letting me know when something is going to change and hasn't said anything.

The test that's failing, on the other hand, looks similar to what happened when I upgraded my air to osx 10.11 for 32 bit builds.  The air is currently forced to only do 64 bit builds to avoid the problem.  Checking Steve's box, it's still running the same older compiler versions, so that's not it.

The failures all started right after the phobos pull for the BigInt changes (https://github.com/D-Programming-Language/phobos/pull/3995).  I have no idea how that could possibly have caused the problem, unless it tickled something particularly oddly.

**Comment by WalterBright** [comment]
We should ping Steven, what's his github handle?

**Comment by schveiguy** [comment]
Sorry guys, Skiing in NH at the moment, so I'm not at home where the system is.

I attempted sshing into it, but that doesn't work. Not sure what the issue is.

I won't be back until Tuesday, Maybe you can disable it from the auto test fleet until then.

It's a VM with only one core. In the past, the fact that it had one core distinguished it from other testers on another issue.

**Comment by schveiguy** [comment]
BTW, I haven't changed anything.

**Comment by braddr** [comment]
see also: https://github.com/D-Programming-Language/phobos/pull/4028

**Comment by braddr** [comment]
Ok, so, reverting the pull that happened immediately before the host started failing doesn't seem to help: https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=1972531&isPull=true

I guess the next best test is to actually build at the cln before that submit, just to be very sure.  But if neither I nor Steve changed something...

**Comment by yebblies** [comment]
Did any dmd pulls get merged between last time it passed and the first time it failed?  I would start with anything there that touched the glue layer or backend.

**Comment by braddr** [comment]
I can't login to the host either (I could earlier) right now.  It's obviously still up and running tests.  I've changed the tester configs to only assign it darwin_64_64 builds, which will help.  That does bring us down to a single tester for darwin_64_32, which is less than ideal.  However, that will have to do until Steve gets home in a few days or someone figures out why osx 10.11 and darwin_64_32 builds fail and I can restore the air to performing those builds.

**Comment by braddr** [comment]
The closest dmd pull to the point of failure is #5475 but the timeline doesn't line up.. it's several hours before with successful builds in between that merge and the start of the failures.

What _does_ show as interesting is that there's a 3 hour gap in the tests from the host.  Before that gap, all the builds are succeeding.  After the reboot all 32 bit builds fail.

2016-02-25 09:43:16 finished fine, successfully
2016-02-25 10:04:33 never finished
2016-02-25 13:53:59 finished fine, failed

Never finishing is almost certainly a reboot of the vm.  If it had been aborted (either with a manual deprecation or by a pull being merged) there would be an end time and a different result code.

What happened during that window of time, I don't know.

**Comment by schveiguy** [comment]
FYI, we did have a power outage this past week, can't remember when. But when I started the Mac back up, I started the VM, and didn't give it a second thought. it's possible there was an issue created there, but not sure at all.

**Comment by braddr** [comment]
Steve started vmware and re-booted the vm.  I've re-enabled the 32 bit builds.  We'll see what happens.

**Comment by braddr** [comment]
a build failed still.  disabled again.

**Comment by schveiguy** [comment]
No idea what is going on. I did install updates recently, but it was passing after that.

**Comment by schveiguy** [comment]
Checked on some notifications I had, and yes, that 3 hour gap was when we had the power failure.

So the mac and the vm were shut down ungracefully. I have no idea how that could have messed up the install. Does the issue have to do with disk failures? Maybe the disk was corrupted?

**Comment by braddr** [comment]
Looks like the /opt/local/bin/cc symlink disappeared, causing the system clang cc compiler to be used when invoking cc.  The rest of the links (gcc, g++, and c++) all pointed to gcc 4.2.  Not sure what caused cc to disappear, but presumably it did during the outage.  Re-adding the link and both 32 and 64 builds work.

**Comment by braddr** [comment]
that would be the bugzilla issue I just filed (might well be a dup) https://issues.dlang.org/show_bug.cgi?id=15736

**Comment by yebblies** [comment]
That sounds about right.  Is gcc on OSX dead enough that we can just support clang instead?

**Comment by schveiguy** [comment]
@braddr glad you could figure it out. It sounds strange that the power outage caused the problem. I'm wondering if some update I ran earlier was held off until a restart occurred, and then the forced restart revealed the issue.

**Comment by schveiguy** [comment]
It would be great to fix the OSX ABI compatibility. I know at least for myself, whenever I'm testing phobos/druntime, I simply build dmd with clang, because I don't want to have to have another compiler installed just for that.

**Comment by schveiguy** [comment]
> I tried both clang++ and g++ on my OSX machine. Both worked.

This doesn't jive with @braddr's explanation, @WalterBright ?

**Comment by braddr** [comment]
If I were a betting man, and I am, I'll bet that @WalterBright was only testing 64 bit and the problem is 32 bit specific.

**Pull request closed without merging**
