### PR TITLE
expressionsem:visit(IsExp e) goto -> local function

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Those gotos weren't bad gotos.
D doesn't allow bad gotos in the first place.

**Comment by thewilsonator** [comment]
No, but functions are better than gotos.

**Comment by UplinkCoder** [comment]
Better? because they introduce more symbols?
potentially take more optimizer time?

**Comment by thewilsonator** [comment]
Because its easier to comprehend.

**Review by Geod24 — APPROVED** [review]
LVGTM

**Pull request merged**
