### PR TITLE
Issue 14989 - Overload merge sometimes doesn't work

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14989

I found this bud during fixing [issue 13203](https://issues.dlang.org/show_bug.cgi?id=13203) (#4816).

### CODE REVIEW

**Comment by 9rnsr** [comment]
The code refactoring on `AliasDeclaration` is necessary to fix other overloading bugs, e.g.:
https://issues.dlang.org/show_bug.cgi?id=15225

**Comment by ibuclaw** [comment]
Auto-merge toggled on

**Comment by ibuclaw** [comment]
I ack'd this in #2130

**Comment by 9rnsr** [comment]
Thanks a lot!

**Pull request merged**
