### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by MartinNowak**
- Fix Issue 15909 - Duplicate case error reports characters as numbers
- Fix Issue 21282 - mixin of AliasSeq "cannot alias an expression" (#11814)
- Fix Issue 21283 - [C++] Wrong mangling for ref of parameter pack
- bump VERSION to v2.094.1-beta.1

### CODE REVIEW

**Comment by Geod24** [comment]
What's up with the `Azure pipelines (Windows_LDC_MinGW win32-ldc)` failure ? We're seeing it on other PRs as well, aren't we ?
CC @wilzbach @MoonlightSentinel

**Comment by thewilsonator** [comment]
We are.

**Comment by thewilsonator** [comment]
@BorisCarvajal there is a merge conflict in one of your PRs here. Please advise how it should be resolved.

**Comment by BorisCarvajal** [comment]
It seems there's a new `errorRet()` instead of `t = Type.terror;`, here:
```
    ds.error("cannot alias an expression `%s`", e.toChars());
    t = Type.terror;
```

**Pull request merged**
