### PR TITLE
Add c++ ABI tests

### PR DESCRIPTION
**Pull request by gchatelet**
@yebblies Here is a first simple version of C++ abi tests.
It fails for real numbers on Linux.

### CODE REVIEW

**Comment by gchatelet** [comment]
So `real` type compiled with `-O` seems to produce an invalid value for when passing the value `0`
See [failing test](https://travis-ci.org/D-Programming-Language/dmd/jobs/77049614#L1852).

**Comment by gchatelet** [comment]
@klickverbot I see, so for `real` values I should check only for the first 80 bits ?

**Comment by gchatelet** [comment]
`is` or `==` doesn't work with `NaN` since `NaN==NaN` is always false.
I think a better strategy is to use `==` expect when value is `NaN`.

**Comment by ibuclaw** [comment]
``is`` will use memcmp at the correct precision for you (so you don't need to have logic in your own tests for that).

**Comment by jmdavis** [comment]
> @gchatelet: I'm pretty sure nan is nan.

Except that there are different variants of NaN, so two NaNs may not be the same via `is`. e.g. https://github.com/D-Programming-Language/phobos/blob/master/std/bitmanip.d#L2288

**Comment by yebblies** [comment]
Checking float equality with `is` is the correct thing to do, but be wary of https://issues.dlang.org/show_bug.cgi?id=3632

We really do want to be checking that the floats match bit for bit.

**Comment by gchatelet** [comment]
So as @jmdavis pointed out two `NaN`s might not have the same representation. Especially since the value is copied in C++ `passthrough` functions. The C++ code might choose a different representation for NaN.

Options are:
1. For robustness and also valid semantic I'll use `std.math.isIdentical` for floating point and `is` otherwise.
2. Do not use value `NaN` or `0` for floating points since they can have different binary representations.
3. Special case floating points on `T.mant_dig` as in [std.math](https://github.com/D-Programming-Language/phobos/blob/6681862b4e3a77004e8d6ec1f62cf6587e20f6d4/std/math.d#L249)

I went for 1. right now. What do you think ?

**Comment by gchatelet** [comment]
BTW the [Windows tests are failing](https://auto-tester.puremagic.com/pull-history.ghtml?projectid=1&repoid=1&pullid=4952), I suspect a name mangling issue.

**Comment by yebblies** [comment]
Phobos should not be used in the dmd test suite.

**Comment by gchatelet** [comment]
Please take another look. There is now no more dependencies on phobos.
Parameters are now passed: by value, by pointer and by reference.

**Comment by yebblies** [comment]
Looks good.  Please squash the commits together.

**Comment by gchatelet** [comment]
Done. Thx for the review.

**Comment by gchatelet** [comment]
thx @klickverbot . What do you mean by funny pointer ? Having the star next to the type instead of next to the variable ? I don't mind providing a fix if you want.

**Comment by yebblies** [comment]
> Having the star next to the type instead of next to the variable ?

Yes, that's correct C++ style but incorrect D style, since the association is different.

**Comment by gchatelet** [comment]
Hmm why do you think this is linked to this PR, it looks like it's linked to druntime, not dmd tests.
```
make[2]: Entering directory `/home/travis/build/D-Programming-Language/druntime/test/profile'
Testing profile
make[2]: execvp: ./obj/linux/64/profile: Permission denied
make[2]: *** [obj/linux/64/profile.done] Error 127
```

**Pull request merged**
