### PR TITLE
Fix Issue 20296 - Segfault when using variadic D functions with exter…

### PR DESCRIPTION
**Pull request by BorisCarvajal**
…n(C++) linkage

### CODE REVIEW

**Review by ibuclaw — DISMISSED** [review]
Needs a runnable_cxx test for good measure.

**Comment by MoonlightSentinel** [comment]
Also should target stable because it's a regression from 2.084

**Comment by BorisCarvajal** [comment]
> Also should target stable because it's a regression from 2.084

Already there.

**Comment by BorisCarvajal** [comment]
> Needs a runnable_cxx test for good measure.

@ibuclaw , I need this first #11583

**Comment by schveiguy** [comment]
The buildkite failure is temporary. If you want to merge this, please do so manually as long as only the no-autodecode test is the only one failing.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
