### PR TITLE
Move more things into internal backend.d header

### PR DESCRIPTION
**Pull request by marler8997**
`backend.d` is a new module meant to hold declarations that are private to the backend.  This change moves a good chunk of declarations from the public `code.d` module to the private `backend.d` module.

This is alot of turmoil so I understand if maintainers don't want to integrate this, but I thought I should follow through with the changes that were started and make them available should they be desired.

I also didn't fully move everything from `code.d` that could have been moved.  I just started from the bottom and moved a good chunk.  If the changes are accepted I can finish the rest in a follow-up PR.

### CODE REVIEW

**Comment by RazvanN7** [comment]
I, personally, don't see the point of this change. What do you mean by "priavate to the backend"? Can't you just make them package instead? I don't think moving them to another file accomplishes anything.

**Comment by marler8997** [comment]
The purpose is to make these declarations only available to the backend itself. Would the `package` identifier solve this as well?

**Comment by marler8997** [comment]
Since @WalterBright has to maintain this code both here and with DMC++, I'd like to get his opinion on what to do here.  These are the 3 options I see

1. Do nothing.  Leave the declarations in `code.d`.  This means that other components like the frontend will have access to all the symbols even though they aren't used.  As someone unfamilair with the backend this made it much more difficult to understand as I was never sure whether symbols were really only being used by the backend.  Having all the symbols open to any external component means so many more ways to modify/call them.

2. Continue with this PR. Move declarations that are only mean to be used by the backend to a private "d header file".  This splits up the public/private declarations so that developers can easily identify which parts of the backend are apart of the public API and which are strictly internal.  The disadvantage is that it's moving a big chunk of code from one file to another.

3. Use the `package` modifier to limit which symbols these "d header files" expose.  With this option I'd suggest using a global `package:` modifier in `code.d` and then using the "public" modifier on symbols that need to be exported.  This way you can easily search for which symbols are used externally and the majority of the symbols are going to be private anyway.

I think option 2 is the cleanest as it mean you can see the entire public interface in a single file.  Option 3 is fine too.  I think it's better to do something here rather than nothing as this makes the backend alot easier to understand (at least for me).  But I'll leave it up to @WalterBright whether the ROI is there.

**Comment by wilzbach** [comment]
4. Finally switch to LDC as official backend and stop wasting so many efforts into maintaining Walter's personal backend.

**Comment by marler8997** [comment]
Cleaning up old PRs that aren't going anywhere.

**Pull request closed without merging**
