### PR TITLE
make new safety checks warnings when using default feature setting

### PR DESCRIPTION
**Pull request by WalterBright**
Consider this error:
```
../.dub/packages/vibe-core/1.22.6/vibe-core/source/vibe/core/log.d(426,19): Deprecation: scope variable `text` assigned to non-scope parameter `__param_0` calling `write`
```
which occurs when compiling buildkite/dlang-tour/core. It's been failing for quite a while now, and doesn't get fixed. There are pages of variations of this error. A simple repro of the error:
```
@safe:
void foo(int* p);
void bar(scope int* abc) {    foo(abc); }
```
so yes, it is an error according to dip1000. But this message is occurring by default. What we did is break everyone's code that was working, and working when in good faith they added `scope` and it remained working, but now it fails to compile. The fact that this is long time broken in dlang-tour/core shows why we need to fix this.

This PR changes it to a warning, but only if `-wo` is used.

### CODE REVIEW

**Comment by WalterBright** [comment]
And this does reduce the volume of the deprecation messages in `dlang-tour/core`. https://github.com/dlang/dmd/pull/15391 will reduce it even further.

**Comment by maxhaton** [comment]
Is it not still a deprecation? Why is the code broken

Consider that dub has warnings-as-errors enabled by default, so why is anyone going to turn `-wo` on?

**Comment by WalterBright** [comment]
It's not still a deprecation, as it does not have an expiry date. The point is the code isn't broken, it's just that it doesn't pass the stricter safety checks.

People who care about robustness will turn on `-wo`.

**Comment by maxhaton** [comment]
> What we did is break everyone's code

**Review by dkorpel — APPROVED** [review]

**Comment by dkorpel** [comment]
> Where's the changelog?

-wo doesn't have a changelog yet

> Anyone using this new obsolete warning with dub for example will have their build broken unless they allow warnings.

Then they shouldn't use both `-wo` and `-w`. I was in favor of temporarily disabling dip1000 deprecations entirely, but Walter insisted they had to be under `-wo`. `-wo` is a bit of a mess right now, but hopefully it's all moot when we have editions figured out.

**Pull request merged**
