### PR TITLE
resurrect hex string literals

### PR DESCRIPTION
**Pull request by WalterBright**
3 people have now asked for its resurrection.

This is the PR being reverted: https://github.com/dlang/dmd/pull/13773

### CODE REVIEW

**Comment by rikkimax** [comment]
Since one of your original goals was to simplify the lexer, perhaps it wouldn't be a horrible idea to make it ``0x`` instead of the leading ``x``.

The code breakage has already happened, so we do have an opportunity here.

**Comment by ichordev** [comment]
> Since one of your original goals was to simplify the lexer, perhaps it wouldn't be a horrible idea to make it `0x` instead of the leading `x`.
> 
> The code breakage has already happened, so we do have an opportunity here.

A great idea, I second this.

**Comment by tgehr** [comment]
Another reason why this was deprecated is that the type of the hex string literal was `immutable(char)[]`, while it would make more sense for it to be `immutable(ubyte)[]`.

**Comment by ichordev** [comment]
> Another reason why this was deprecated is that the type of the hex string literal was `immutable(char)[]`, while it would make more sense for it to be `immutable(ubyte)[]`.

Yeesh, they should've just changed its type. Perhaps changing the type to `immutable(ubyte)[]` or `immutable(void)[]` should be considered? Though I'm not sure exactly how `void` differs from `ubyte`.

**Comment by ibuclaw** [comment]
> Though I'm not sure exactly how `void` differs from `ubyte`.

`void` arrays are scanned for pointers in the GC, `ubyte` arrays are not.

**Comment by WalterBright** [comment]
I appreciate the suggestions for improvements, but this PR is about continuing to support legacy code, and the suggestions would make it not work with legacy code.

**Comment by rikkimax** [comment]
Bin2d is the only legacy code I know of that uses it, which I wrote. It
casts to ubyte array. So that change is safe to do.

I never updated it because there wasn't anything good to update it to.

**Comment by ichordev** [comment]
> Bin2d is the only legacy code I know of that uses it, which I wrote. It casts to ubyte array. So that change is safe to do. I never updated it because there wasn't anything good to update it to.

`immutable(ubyte)[] x = cast(immutable(char)[])[‘a’]` works, so I reckon hex strings should at least *implicitly convert* to ubyte array.

**Comment by dkorpel** [comment]
> I appreciate the suggestions for improvements, but this PR is about continuing to support legacy code, and the suggestions would make it not work with legacy code.

The rationale is:

> 3 people have now asked for its resurrection.

They want it to be resurrected as a proper feature to be used in new code, not simply stick around under `-wo` to avoid updating old code. Perhaps the syntax can stay the same, but when we went through the hassle of deprecating the old hex string literals, we should at least take the opportunity to type it as `ubyte[]`. It could still implicitly convert to `char[]`.

**Comment by WalterBright** [comment]
I understand that making the result a ubyte[] is probably a better choice than char[]. But the purpose of this PR is to compile legacy code. It's not difficult to create one's own hexstring, or any sort of string, for that matter, with CTFE:
```
ubyte[] hexToUbytes(string s)
{
    ubyte[] result;
    uint n = 0;
    ubyte v = 0;

  Loop:
    foreach (i, cc; s)
    {
        char c = cc;
        switch (c)
        {
            case ' ':
            case '\t':
            case '\v':
            case '\f':
            case '\r':
            case '\n':
                continue;                       // skip white space

            case 0:
            case 0x1A:
                assert(0, "unterminated string constant");
                assert(0);

            case '0': .. case '9':
                c -= '0';
                break;

            case 'A': .. case 'F':
                c -= 'A' - 10;
                break;

            default:
                break Loop;
        }
        if (n & 1)
        {
            v = cast(ubyte)((v << 4) | c);
            result ~= v;
            v = 0;
        }
        else
            v = c;
        ++n;
    }
    assert(!(r & 1), "odd string constant");
    return result;
}

ubyte[] ub = hexToUbytes("ABCD01");
```

**Comment by rikkimax** [comment]
Out of interest Walter, have you measured that function?

I assume no, or you wouldn't be proposing that function.

So I'll do it.

Let's start, the workload is a 1mb string, the contents don't matter but I'll pick all zero's.

At runtime it takes a whopping ``2 ms, 547 μs, and 2 hnsecs``. Looks good. Now lets do it at CTFE.

Capture

18s 122ms 997us

Almost the entire compilation time!

The problem is not the grammar, it's the _tradeoffs_. There just isn't something comparable.

**Comment by ichordev** [comment]
> Let's start, the workload is a 1mb string, the contents don't matter but I'll pick all zero's.
> 
> At runtime it takes a whopping `2 ms, 547 μs, and 2 hnsecs`. Looks good. Now lets do it at CTFE.
> 
> Capture
> 
> 18s 122ms 997us
> 
> Almost the entire compilation time!
> 
> The problem is not the grammar, it's the _tradeoffs_. There just isn't something comparable.

CTFE is never gonna be faster at compile time than a well-implemented language feature. Otherwise, we’d just move every other type of literal from the core language to a CTFE-able function.
If everyone makes their own boilerplate CTFE-able functions for such things, then the performance (and code-correctness) will likely go completely untested, as has already been demonstrated here.

**Comment by rikkimax** [comment]
Yes. But we are not talking about small gains here.

That work load is on the low end as well, think images and shared libraries.

This has enough gains I consider this a hard requirement for new languages
to include, easy to implement and there just isn't anything comparable to
it.

It's not like we are talking about octal integers, they don't use tables
and will be fast to CTFE.

**Comment by dkorpel** [comment]
> But the purpose of this PR is to compile legacy code.

I responded to that with: https://github.com/dlang/dmd/pull/15393#issuecomment-1630535072

**Comment by WalterBright** [comment]
@rikkimax yes it's slow. It could be sped up by a couple orders of magnitude by having it fill, say, a 1K buffer and append those to `result`. Or using a buffer that doubles in size each time it fills up. But that's not really the point, which is it can be done with CTFE.

I use the same technique here https://github.com/dlang/dmd/blob/master/compiler/src/dmd/backend/disasm86.d#L3613 to create my own DSL for the unit tests.

Or, the char hexstring can simply be implicitly converted to a ubyte hexstring, as already mentioned.

**Comment by rikkimax** [comment]
No, you cannot optimize it. You could be using a static array and it would
still be too slow.

It's the CTFE engine, it's known to be doing something pretty wrong with
arrays which makes it dead slow.

I have a CRC module, lots of them but same problem there. Same reason for
std.regex. It's all about the arrays you can't use them at CTFE if you want
fast compilations.

**Review by dkorpel — APPROVED** [review]
Discussed at DConf, implicit conversion to `ubyte[]` can be done in separate PR

**Pull request merged**
