### PR TITLE
fix Issue 17275 - [REG 2.072.0] AssertError@declaration.d(2121): Asse…

### PR DESCRIPTION
**Pull request by WalterBright**
…rtion failure

Replaces https://github.com/dlang/dmd/pull/6845

fix Issue 17275, 17289, 17337, 17338, 17339, 17344, 17489

### CODE REVIEW

**Comment by WalterBright** [comment]
Also fixes 17289, 17337, 17338, 17339, 17344.

**Comment by ibuclaw** [comment]
> Also fixes 17289, 17337, 17338, 17339, 17344.

I am suspicious about this claim. :-)

**Review by ibuclaw — APPROVED** [review]
Tested using gdc, and confirmed this is fixed.

**Comment by wilzbach** [comment]
> Also fixes 17289, 17337, 17338, 17339, 17344.

You can make the Dlang-Bot aware of this, simply enumerate them and use a comma as a separator:

fix Issue 17275 -> fix Issue 17275, 17289, 17337, 17338, 17339, 17344

[Proof that the bot will accept this with Regex101](https://regex101.com/r/aI0Rp6/6).

**Review by wilzbach — APPROVED** [review]
This also fixes [17489](https://issues.dlang.org/show_bug.cgi?id=17489), i.e. the ICE that we are observing on the Jenkins tester. I guess that's the reason why Jenkins is so green here :)

**Comment by ibuclaw** [comment]
> fix Issue 17275 -> fix Issue 17275, 17289, 17337, 17338, 17339, 17344

Did you even read the issues? Totally unrelated, and already marked as resolved.

https://issues.dlang.org/show_bug.cgi?id=17344

**Pull request merged**
