### PR TITLE
[stable] Fix C++ header regressions

### PR DESCRIPTION
**Pull request by kinke**
Introduced by #11821.

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]
Looks like `frontend.h` is not infallible.

**Comment by kinke** [comment]
Yeah well, it needs due diligence before merging. ;)

**Comment by ibuclaw** [comment]
> Looks like `frontend.h` is not infallible.

This is why there's `tests/cxxfrontend.c`

**Comment by kinke** [comment]
Sorry but I never found that to be of much use; I'd rather focus on dtoh than coming up with a testcase for each regression encountered when upgrading LDC's frontend.

**Pull request merged**
