### PR TITLE
chore(druntime/posix): annotate posix_memalign as pure and scope

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

As per the documentation of `pure_memalign`, it doesn't produce any side effects like writing to `errno` variable on error, therefore, it should be marked as `pure`. Required to make `AlignedMallocator` `pure`. See https://github.com/dlang/phobos/pull/8576.

Reference to documentation: https://man7.org/linux/man-pages/man3/posix_memalign.3.html

### CODE REVIEW

**Review by thewilsonator — CHANGES_REQUESTED** [review]
Shouldn't this have a fakePure wrapper like `malloc` instead?
 (also the `void**` argument should be `scope`)

**Comment by ljmf00** [comment]
> Shouldn't this have a fakePure wrapper like `malloc` instead?

No, as `malloc` DOES write to `errno`. There is a `fakePure` wrapper to circumvent the type system to be later used on `pureMalloc` function that saves and restore errno to make it a pure behaviour. 

> (also the `void**` argument should be `scope`)

I think we can also annotate that. There's nothing describing it does escape that pointer.

**Comment by thewilsonator** [comment]
So, `posix_memalign` does not write to `errno`?

**Comment by ljmf00** [comment]
> So, `posix_memalign` does not write to `errno`?

Yes, the error code is not written to the errno, but instead to its return value.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
