### PR TITLE
Add OS versions for iOS, TVOS, and WatchOS

### PR DESCRIPTION
**Pull request by smolt**
Just starting the process to make iOS official.  Here we reserve OS `version(iOS)` which will trickle into LDC eventually.  ~~Also reserve `version(Darwin)` for OSX and iOS common code because iOS is based on OS X.  Most of the system and libc calls are identical for iOS/OSX and this will prevent either copying code or having to manually `version(OSX) version = Darwin; version(iOS) version = Darwin` in many files.~~

~~Note - this does not touch legacy version darwin which can still follow its deprecation lifecycle.~~

~~The LDC discussion is ldc-developers/ldc#1081 is where this is coming from.  The choice of `version(Darwin)` for common code comes from Mono and LLVM's Triple class.~~

~~If this is accepted, the next step is to change many occurrences of `version(OSX)` in the runtime to `version(Darwin)`.  That doesn't seem so bad, but then there are all the packages with osx in the name like `core.sys.osx`.  Ideally they would all be `core.sys.darwin`.  But that is for later.~~

### CODE REVIEW

**Comment by joakim-noah** [comment]
Where do `iOS` and `OSX` differ?  Are you planning on adding `iOS`-specific APIs to druntime/phobos?

**Comment by smolt** [comment]
@joakim-noah - at the system level, iOS and OSX differ in very few places.  `struct direct` is an example and there are a few others like this.  There are also Mach differences due to CPU architecture, but those are versioned on the CPU.

**Comment by WalterBright** [comment]
> Most of the system and libc calls are identical for iOS/OSX and this will prevent either copying code or having to manually  version(OSX) version = Darwin; version(iOS) version = Darwin  in many files.

We've been over this general issue before. There isn't a problem copying interface code. There is a problem making a change for one operating system variant thereby breaking another variant. Someone modifying iOS interfaces should not be assuming it will or will not work on OSX, and having the iOS and OSX modules different will ensure this.

There should not be a version(Darwin).

**Comment by WalterBright** [comment]
Alternatively, one can do things like:
```
version (OSX) import darwin;
...
version (iOS) import darwin;
```
where the Darwin code will be clearly segregated. No version(Darwin) is necessary.

**Comment by joakim-noah** [comment]
>Someone modifying iOS interfaces should not be assuming it will or will not work on OSX, and having the iOS and OSX modules different will ensure this.

They will not assume it: I think Dan's offering to check and set it up right, after which they'll almost never be changed.

More broadly, I don't think you have to worry about code breaking, as it's possible to make the change without breaking anything on OS X.  I changed linux similarly recently, splitting up linux kernel APIs from APIs from the two popular C runtimes on linux, Glibc and Bionic.  It shipped in 2.068 for linux and nobody has complained about problems with linux/glibc, as it should be transparent to the user.

Similarly, `Darwin` would just be an internal change for druntime/phobos, to make organizing the code easier, but likely wouldn't affect much externally, as most users would likely only use `OSX` and `iOS`.  But it would provide an easier way to organize code and avoid redundancy for those who need it, both in druntime/phobos and for those few external users who dig that deep.

Of course, if OS X and iOS are substantially similar, it does raise the question if it's worth the trouble, ie if it's better to just define `OSX` for both and use `iOS` to specialize, or one of the other hacks mentioned.  If he's willing to go to the trouble of patching druntime to use `Darwin` everywhere necessary, I think it's worth it to reorganize using `Darwin`, if only because it'll look a lot better, though that's subjective.  If we ever ported to Watch OS or TV OS, the resulting duplication wouldn't look good.

A bigger issue is that it needs to be made clear what APIs `Darwin` refers to, ie is there a clear separation of those APIs somewhere we can point to?  On linux, `linux` refers to kernel APIs, `CRuntime_Glibc` refer to glibc APIs, and the unmerged in dmd but used in druntime/phobos `Android` refers to the remaining differences, like the system shell path or the fact Android has no /root directory.

`Darwin` would have to make similarly clear what APIs it refers to, that `OSX` and `iOS` don't refer to.

**Comment by WalterBright** [comment]
Regardless, there are on the table at least three ways to deal with the Darwin issue that do not require a predefined compiler version. I'd like to keep the number of predefined versions to the bare minimum possible.

For why, run:
```
gcc -dM -E - < /dev/null
```
and see the blizzard of predefined names, and who knows which ones to use, which ones are obsolete, why, etc.

**Comment by joakim-noah** [comment]
Yes, I've seen that list before, I believe when trying to figure out what predefined name to use on OpenSolaris years ago.  I agree with the general principle of keeping the list of predefined versions short and avoiding that mess.  But surely we can add versions and do it right?

The determinant should be how much the platforms actually differ.

@smolt, presumably you haven't patched all of your druntime yet to use `Darwin`.  If you simply defined `OSX` on iOS so far, how many places did you have to specialize for iOS in druntime/phobos?  If it's not many, maybe you could just leave that hack in for now and propose `Darwin` again later when there's a real need for it?

**Comment by WalterBright** [comment]
> But surely we can add versions and do it right?

In my not-so-humble-opinion, the fact that `Darwin` can be derived from other existing predefined versions means it is redundant and should not be added.

**Comment by smolt** [comment]
@WalterBright - I understand the concern about changes in shared code breaking iOS or OSX.  It is a possibility.  Changes to core OS APIs should be somewhat safe because they are built from [xnu](https://github.com/opensource-apple/xnu).  If that is not a good case for sharing these APIs, then I can make copies.

I agree, the C preprocessor has a lot of predefined macros, is a bad model to follow, and can be hard to interpret.  Portably identifying [POSIX] (http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#HowtodetectPOSIXandUNIX) is complicated.  [Darwin](http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#OSXiOSandDarwin) is a little better.

@joakim-noah - I haven't yet changed any code to use version Darwin in my fork.  I am still setting both iOS and OSX when target Triple ends in ios (e.g. x86_64-apple-ios) to make sharing and merging the `version(OSX)` code easy.  I specialized for iOS in 3 of 170 `version(OSX)` code blocks.

However, I was persuaded by @jacob-carlborg, Swift, and Mono that OSX and iOS should be mutually exclusive to avoid surprise:

```D
// always does desktop stuff when OSX set with iOS
version (OSX) { /* do Mac desktop stuff */}
else version (iOS) { /*do mobile stuff */}
```

Planning ahead, if no version Darwin, how best to deal with these sample druntime cases?
- core/thread.d has 16 `version(OSX)` code blocks.  All contain the code I want for iOS.  Copy each or define a `version = Darwin` at beginning of module based on OSX or iOS and use instead of `version(OSX)`?
- core.sys.osx modules - copy entire directory tree and rename core.sys.ios?  With version(iOS) inside?

**Comment by smolt** [comment]
A thought experiment.  I download open source darwin, get it running, then decided to port dmd to it.  Then I would need version (?) :blush:  Sorry, couldn't resist.

**Comment by joakim-noah** [comment]
>Copy each or define a version = Darwin at beginning of module based on OSX or iOS and use instead of version(OSX)?

I believe defining `version = Darwin` in each file is what Walter's suggesting.  It's a hack, but it'll do for now.  I count 86 files in druntime/phobos which version on `OSX`, should be fairly easy to cut-and-paste and search-and-replace.

>core.sys.osx modules - copy entire directory tree and rename core.sys.ios? With version(iOS) inside?

That's a little easier to address.  Assuming there are actually differences between OS X and iOS there, you could create three directories, core.sys.darwin, core.sys.osx, and core.sys.ios, and use the same version logic above for core.sys.darwin, while only importing the files actually necessary from any of those directories into other modules.

I agree that it's not ideal, but it will allow end users to version on `OSX` and `iOS` and if we ever decide to add Darwin as a predefined version someday, all we have to do is delete that `version(OSX) version = Darwin; version(IOS) version = Darwin` block at the top of those 86 files and we're good.

As for running Darwin itself, good luck with that, as there hasn't been a viable distro from that source in a decade, with OpenDarwin shutting down and PureDarwin not going anywhere.  The "get it running" part will take you a while, but you probably knew that.

**Comment by jacob-carlborg** [comment]
> I believe defining version = Darwin in each file is what Walter's suggesting. It's a hack, but it'll do for now. I count 86 files in druntime/phobos which version on OSX, should be fairly easy to cut-and-paste and search-and-replace.

I we want to define `version = Darwin` in 86 files, isn't that a sign that it should be a predefined version identifier?

**Comment by WalterBright** [comment]
> I we want to define  version = Darwin  in 86 files, isn't that a sign that it should be a predefined version identifier?

As I mentioned earlier, Darwin is redundant, and we're not going to have predefined redundant versions. I know that was done for Posix, but I believe that was a mistake.

**Comment by smolt** [comment]
> As for running Darwin itself, good luck with that, as there hasn't been a viable distro from that source in a decade, with OpenDarwin shutting down and PureDarwin not going anywhere.

@joakim-noah - That's I it was a thought experiment!

**Comment by joakim-noah** [comment]
Seems uncontroversial at this point, LGTM.

@WalterBright, would you prefer that version block added to all 86 files or use of `static if` instead, ie use the version to set Darwin in a config module and then import and use that config in 86 files?

**Comment by WalterBright** [comment]
Setting a value in an import and then referring to that with `static if` in the importers as a substitute for `version` is pure eevil. There are several much better ways:

1. segregate all the Darwin declarations into a `darwin` module and them import it in the OSX and iOS modules.

2. Have two separate imports, OSX and iOS, and have them duplicate the common definitions. It's really not a problem to duplicate definitions.

3. Use the: `version(OSX) version = Darwin; version(iOS) version = Darwin; ` in each file.

**Comment by jacob-carlborg** [comment]
I would for the first alternative. As long as it's not a single module with all declarations.

**Comment by joakim-noah** [comment]
1. While that would work, it subverts the whole point of the current layout, where declarations are in the module named for the equivalent C header file.  Sure, you could still import them that way, but you'd always have to check the darwin modules to see if they're declared.

2. I think some duplication is fine, but copying all of them when most are really from Darwin doesn't make much sense to me.

3. I guess this is the only option left.  It doesn't look great, but there's no other alternative.

I suggest using 3. for modules with a lot of version blocks, with 2. for modules with only one or two small version blocks.

**Comment by WalterBright** [comment]
> Sure, you could still import them that way, but you'd always have to check the darwin modules to see if they're declared.

The users will never import the Darwin modules. The OSX and iOS modules publicly import the Darwin ones. The users only see OSX and iOS modules.

**Comment by joakim-noah** [comment]
>The users will never import the Darwin modules. The OSX and iOS modules publicly import the Darwin ones. The users only see OSX and iOS modules.

Maybe you're talking about `core.sys.osx/ios`, but I'm talking about the remaining 70-80 modules, [like `core.sys.posix.pthread`](https://github.com/D-Programming-Language/druntime/blob/master/src/core/sys/posix/pthread.d#L135).  If you were suggesting adding an `iOS` version block to that module and then having it and the `OSX` version block import a common Darwin module from elsewhere, that contains the actual C declarations, as you seemed to be saying in option 1. above, my point is that those looking for those declarations would then end up having to check the Darwin module all the time, not `core.sys.posix.pthread`.

This would be weird, as most C declarations would be found in `core.sys.posix` modules, but Darwin's declarations alone would be centralized elsewhere.  Perhaps this is an argument for pushing forward the druntime platform re-org and you'd prefer it that way, just saying I don't think 1. will be natural for users hunting for those C declarations, at least if they're used to the way druntime is organized now.

**Comment by WalterBright** [comment]
> This only pushes the problem to user code, when people writing cross-platform code now need to do  version (OSX) import xyz.osx; else version (iOS) import xyz.ios . That can't be a good idea.

Why not? I seems perfectly reasonable to me if one is writing code for both OSX and iOS. It makes it very clear to the reader which systems the code is supporting.

**Comment by WalterBright** [comment]
I don't find it a burden at all to enumerate what systems a piece of code has been targeted and tested for. Even if it is perceived a terrible burden to put that in each user module, the user can still write a module named `supportedoses.d` and inside that, just once, enumerate iOS and OSX, then import `supportedoses`.

The win, of course, is that the predefined versions are not overlapping, and so there is no ambiguity on what to test against.

**Comment by WalterBright** [comment]
Other people have similar ideas and techniques: https://www.reddit.com/r/programming/comments/3qo79b/living_in_the_ifdef_hell/

**Comment by yebblies** [comment]
> @WalterBright, would you prefer that version block added to all 86 files or use of static if instead, ie use the version to set Darwin in a config module and then import and use that config in 86 files?

This is what DDMD does, `version` is too crippled to be of general use.  It only works well in simple situations with specific module layouts, unlike pretty much everything else in D.  It's too easy to end up with a copy-paste disaster.

The best workaround we have is to add a new predefined version identifier.

**Comment by WalterBright** [comment]
I would have agreed with you guys 10 years ago, but not any more. I've seen too much #ifdef hell, in my own code and in just about everyone else's code that has been around a while. Run that `gcc` command I posted upthread, and gaze on the fires of hell :-)

**Comment by yebblies** [comment]
I mostly agree with you Walter, but I think you're taking it way too far.  We should be wary of creating these catastrophic messes but the cost in code duplication is too high with the current policy.

**Comment by WalterBright** [comment]
I question the assumption of a high cost to code duplication. They're just lists of declarations. Secondly, I question the efficacy of "we should be wary" because multiple times druntime has gotten screwed up by attempts to merge allegedly common declarations, and one attempt to use `static if` as a substitute, and I was left with having to fix it.

**Comment by TurkeyMan** [comment]
I couldn't agree with @klickverbot more. I have anecdotes contrary to the link Walter presented; I spent years on codebases where we defined explicit platform separation (as Walter appears to advocate).  
In games - which I still think is one of the best targets for D - we have many, many platforms. I have worked on an engine codebase which supported; Windows, OSX, linux, Android, iOS, PS2, XBox, Gamecube, PS3, X360, Wii, PS4, XBOne, WiiU, PSP, PS Vita, Nintendo DS, Nintendo 3DS, NaCl, Web (Emscripten), and some other minor targets. That's like, more than 20 operating systems. They almost all have a distinct operating system and API, but as you can imagine, many (quite a few) of the platforms do have overlapping subsets.  
We concluded that understanding the subsets was too complex for the average programmer, and as a result we stuck with a rule that they shall each exist beneath their own little platform-specific code tree.  
The long-term result of this decision was a disaster. Fixes to one platform would often be repeated some time later for another because they were unnaturally separated, which usually involved the same time spent discovering and isolating the same problem, just on a 'different' (read: not actually different) platform, often by a different person who didn't have the prior experience. 10 years later, if I could go back and refactor the common parts into properly common modules, I definitely would, but by that time duplication of code had appeared around the place, some of them were defined or implemented slightly differently, other code was built above, and refactoring in a way to isolate the common subsets became almost impossible. We needed to do it from the start. That decision was one of the biggest mistakes I've made in my career, shared by a company of around 200 engineers, and we would never repeat it again.  
In subsequent game-engine projects, I have proactively identified and merged the common subsets shared among platforms, and it has yet to cause me a single moment's grief.  
I feel Walter's position is well meaning (we felt the same way, and committed to that principle), but misguided. Perhaps he hasn't worked across 20 platforms, and knows well where it leads? Or if this is to be taken as subjective, on a case-by-case, then how is it possible to get everyone on the same page, or to agree on matters of subjectivity? For my money, well defined subsets should be defined, and acknowledged.

**Comment by TurkeyMan** [comment]
FWIW, I take Walter's proposed 'ifdef hell' as a different thing than I think he presents it.
I see ifdef hell as the conditions that emerge precisely when platform subsets _aren't_ well defined, and instead tend to express in higher level code, at which level, platform differences appear significant.  
I think the proper approach to combat 'ifdef hell' is to make sure the lower level modules are properly separated into modules where multiple platforms in conflict doesn't occur.

**Comment by WalterBright** [comment]
We're talking about lists of declarations here. Nobody is suggesting, for example, make a separate gc implementation for every platform.

**Comment by TurkeyMan** [comment]
Is this principle strictly limited to lists of prototypes? Sorry, that wasn't clear.
I wasn't suggesting that either. The problem here seems to be about where you draw the lines, and the discussion seemed more general.
In the case of declaring OS prototypes, that's one thing, but that's not a general case. And even in this case, if someone comes along and adds a missing function who's working on iOS, it should probably be readily available on OSX too, otherwise someone will probably just come along and to it again later.

Anyway, I'm not addressing this specific case here, I'm just talking on principle. Your argument sounded massive warning alarms from past experience, so I thought I'd comment.

**Comment by joakim-noah** [comment]
Thanks for the input, Manu, that's interesting, especially since almost nobody else targets so many wildly different platforms.  This discussion only concerns druntime and phobos and is largely aesthetic, as we can still use `version(Darwin)`, only with the aforementioned `version = Darwin` block at the top of each file.  User code can always use any non-predefined versions and organize their platform-specific code any way they want, nothing here affects that.

As for what code it affects in druntime/phobos, it's almost all C declarations, as Walter says, but a little platform-specific code in the druntime implementation also, threading for example.  That's so little that I don't think it really matters.

**Comment by TurkeyMan** [comment]
> Also, there is the question of how to figure out where to draw the line, which Walter has not made any effort to answer so far.

Right, and that's what I was trying to comment on.

**Comment by WalterBright** [comment]
The dmd source code itself is a good example of how to do it. Most of the #if's had been removed over time. For a module that started out well, but gradually backslided see std/stdio.d

> how to figure out where to draw the line, which Walter has not made any effort to answer so far.

Use good judgment, not blind rule following.

**Comment by WalterBright** [comment]
Each system has its own separate section in port.c, and there are no common code sections (except for the writelongLE(), etc. functions which don't belong there.)

> Now it is your turn to clarify or prove me wrong.

I believe that if you try what I suggest in good faith, how to use exercise judgment with it will become clear. A Dicta Boelcke is not necessary. DRY is not a goal that trumps all others, it is only one of many means to the goal.

**Comment by yebblies** [comment]
> Each system has its own separate section in port.c, and there are no common code sections (except for the writelongLE(), etc. functions which don't belong there.)

port.c doesn't exist any more.

**Comment by WalterBright** [comment]
> port.c doesn't exist any more.

I know. port.d is not an example of my preferred way of doing things. For example, there are 9 instances of `version(CRuntime_Microsoft)`. And code like:
```
static real strtold(const(char)* p, char** endp)
{
    version (CRuntime_DigitalMars)
    {
        auto save = __locale_decpoint;
        __locale_decpoint = ".";
    }

    version (CRuntime_Microsoft)
        auto r = .strtold_dm(p, endp).r;
    else
        auto r = .strtold(p, endp);
    version (CRuntime_DigitalMars) __locale_decpoint = save;
    return r;
}
```
is a style we should be avoiding, especially in its use of `else`. (New systems should hit a `static assert(0)`, not use `else` defaults.) I see am having a really hard time convincing anyone of this.

**Comment by joakim-noah** [comment]
No, it makes sense to me, [I even had a PR merged to replace as many catch-all elses as possible with more specific conditions in druntime](https://github.com/D-Programming-Language/druntime/pull/1069), though I didn't add `static assert` everywhere, as it was inconsistently used in druntime and I didn't want to add to the PR.  As @jmdavis said in the forum, your position is radical but consistent.

I haven't understood David's line of reasoning regarding version blocks in user code since he started it.  My understanding is that such versioning would only be required for truly platform-specific code under Walter's scheme, which would require importing `core.sys.ios` or `core.sys.osx` for those mobile- or desktop-specific APIs.

Everything from Darwin would stay in the druntime modules where it is now, either duplicated in iOS and OSX version blocks, or merged in a single Darwin version block, with the aforementioned `version = Darwin` definition for OSX and iOS at the top of each file.  That is completely transparent to the user, it is basically no different from adding a predefined version `Darwin` from the user's standpoint.  The only difference is that Walter's scheme would allow the user to also set the the version `Darwin` the way they want, and I don't know the version precedence rule if they somehow set it differently from a version set locally in a druntime file, but I doubt that'd be a problem.

As for David's argument regarding how we know when a predefined version is needed, that's more understandable, but I agree with Walter that it's a matter of judgement, and that his limited allowance of OS's and maybe a C runtime or two, while disallowing all redundant versions like `Darwin`, is workable.

**Comment by joakim-noah** [comment]
>I'm afraid your understanding is wrong, although I agree it would be much more sensible.

I don't think your understanding is what he meant, but he would have to clear it up himself.

>version declarations are local to each module, by the way.

Right, what I was referring to is if the user had a build script that passed `-version=Darwin` to the compiler, could that cause a conflict with the version definition in the imported druntime files?  Now that I think about it further, all it will do is make sure `Darwin` is defined, there is no conflict or precedence issues, as I had in my earlier incorrect mental model of comparing it to C's `#define` and `#undef`.

Rather, the only possibility for errors is if some user building for linux or some non-Darwin system happens to add a `-version=Darwin` to their compile to activate some subset of their code that they versioned with the name `Darwin` for some unknown reason, ;) and all of a sudden, they get a bunch of C declaration conflicts.  That's not a real concern and is easily fixed by the user.

**Comment by joakim-noah** [comment]
@WalterBright, I believe we're just waiting on you to clear up what you mean for David, so we can merge this and Dan can move on to adding the necessary iOS support to druntime/phobos.

I'll rework my Android PR #3643 and Bionic support in druntime/phobos based on whatever is decided here.

**Comment by smolt** [comment]
Don't merge yet before I add watchOS and tvOS versions too.  Support for these iPhoneOS variants  has been upstreamed to LLVM now and might as well get them all at once.

**Comment by smolt** [comment]
Ready...

**Comment by WalterBright** [comment]
I am curious how `watchOS` is envisioned to be used. Clearly, the compiler isn't going to be hosted on the watch, so how is the `watchOS` version to be set?

**Comment by smolt** [comment]
These are the target OS, not necessarily the host OS.  For all of these LDC is cross compiling to these targets.

**Comment by WalterBright** [comment]
I understand that. But is it intended that a special `watchOS`-only compiler be built?

**Comment by smolt** [comment]
In particular `-mtriple=thumbv7-apple-watchos` for watchOS and `-mtriple=thumbv7-apple-ios` for iOS.

> On an unrelated note, shouldn't the version names be in PascalCase?

I was not sure on that.  Swift uses those stylized names for its `#if os(tvOS)` construct, and since that is the path folks prefer for iOS instead of IOS, I followed suit.  I myself do not care.

**Comment by smolt** [comment]
I'll wait a day and see if anybody has an opinion on names, then revise as needed.  For reference, here are sample namings:

SDK Name |Swift OS Name| OS Name (LLVM triple)
---------|-------------|---------------------
MacOSX   | OSX	       | macosx               
iPhoneOS | iOS	       | ios    		     
AppleTVOS| tvOS	       | tvos   		     
WatchOS  | watchOS     | watchos

**Comment by smolt** [comment]
Let's try `WatchOS` and `TVOS` and see what happens.  This is how Mono named them.

**Comment by joakim-noah** [comment]
I thought it was better when all three were lower-case, but don't really care what's chosen.

**Comment by smolt** [comment]
I thought there would be discussion over TVOS versus TvOS!  :smirk_cat:

**Comment by smolt** [comment]
Trying to un-stall this PR by proposing a druntime structure.   See D-Programming-Language/druntime#1448

**Comment by joakim-noah** [comment]
At this point, this PR is very small.  I see no reason not to merge it.  @WalterBright?

**Comment by joakim-noah** [comment]
@WalterBright, [Dan has got the druntime/phobos tests running on an Apple Watch by using these PRs with ldc](http://forum.dlang.org/thread/m2bn9b74o4.fsf@comcast.net), can you merge or provide any remaining feedback?

**Comment by smolt** [comment]
ping

**Comment by joakim-noah** [comment]
Calling in air support from @andralex, Walter has gone AWOL on this PR for more than 4 months now.

**Comment by andralex** [comment]
"What's the worst that could happen?"

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by smolt** [comment]
Nice - I'll groom the related druntime PR next, bring it up to date!

**Pull request merged**
