### PR TITLE
fix Issue 21526 - x87 not rounding to precision on assignment on some…

### PR DESCRIPTION
**Pull request by WalterBright**
… platforms

The comment in the code explains it. Maybe @9il can provide the test values?

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Review by ibuclaw — APPROVED** [review]
Does this also fix https://issues.dlang.org/show_bug.cgi?id=21376?

**Comment by WalterBright** [comment]
> Does this also fix https://issues.dlang.org/show_bug.cgi?id=21376?

No.

**Comment by WalterBright** [comment]
Can someone with the Azure setup let me know what code is being generated for the f21526 function in mars1.d?

**Comment by MoonlightSentinel** [comment]
> Can someone with the Azure setup let me know what code is being generated for the f21526 function in mars1.d?

```asm
Disassembly of section .text:

00000000 <__D5mars16f21256FddZd>:
   0:	c8 08 00 00          	enter  $0x8,$0x0
   4:	dd 45 10             	fldl   0x10(%ebp)
   7:	dc 45 08             	faddl  0x8(%ebp)
   a:	dd 5d f8             	fstpl  -0x8(%ebp)
   d:	dd 45 f8             	fldl   -0x8(%ebp)
  10:	c9                   	leave  
  11:	c2 10 00             	ret    $0x10

```

[mars1.txt](https://github.com/dlang/dmd/files/5781326/mars1.txt)

**Comment by WalterBright** [comment]
Thank you, @MoonlightSentinel 
And that's what the generated code should be (see the store and reload).

**Comment by WalterBright** [comment]
With some more investigation, I was able to duplicate the problem. Unfortunately, I cannot get the x87 to always produce the same value as XMM. But this change still gets it to do a write/read, which improves things.

**Pull request merged**
