### PR TITLE
[TEST] Dont mangle extern(C|system|windows) names in aggregates

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
The behaviour is an inconsistent and odd special case which can cause silent corruption (because a function mangled as D symbols adheres to the C ABI).

As discussed in #8429, just checking the impact on BuildKite.

### CODE REVIEW

**Comment by PetarKirov** [comment]
@MoonlightSentinel A private static member function with `extern (C)` calling convention is a common design pattern where the goal is not to private bindings for something defined in C, but to define a function in D that will passed as a function pointer to a C function (say a `qsort` callback). When a function is passed as function pointer it doesn't matter whether it has name mangling or not. However the reason for defining such function as a `class` or `struct` member (and not as a regular free function) is to have namespacing, encapsulation and I'd argue that the the D name mangling helps in this regard.
The benefit of the name mangling in this situation is that it allows the user to use a short and generic name (like say `sortCmp`) and the name mangling will prevent clashes with other function with same name (in say other structs and classes).

**Comment by ibuclaw** [comment]
> The behaviour is an inconsistent and odd special case which can cause silent corruption (because a function mangled as D symbols adheres to the C ABI).
> 

Not sure you should really be conflating the two.  Mangling and ABI are two different things.

For example, by your logic we have
 https://github.com/dlang/druntime/blob/17fb8437d4444e212a1a7c79792052abfcda007a/src/core/internal/entrypoint.d#L25

Which may not be ABI compatible with `extern(D) int main(char[][] args)`

**Comment by adamdruppe** [comment]
I'm pretty sure this is a massive break of a useful functionality....  gonna keep an eye on it

**Comment by WalterBright** [comment]
Changing the mangling could cause a lot of hidden breakage to existing code, and the rationale for it seems murky. Sometimes the rationale for the existing situation is underdocumented, and we find out the hard way if we change it.

**Comment by Geod24** [comment]
It breaks tons of useful use cases, such as:
```D
unittest
{
    extern(C) int someCallBackForSort () {}
    // ...
}

unittest
{
    extern(C) int someCallBackForSort () {}
    // ...
}
```

Suddenly this silently breaks. That's a big no from me.

**Comment by MoonlightSentinel** [comment]
The main idea was to get rid of yet another special case in the language ("`extern(X)` implies X mangling + ABI - except when used in this special context"). But i can see the reasoning that the flexibility for callbacks outweighs the inconsistency, hence closing it for now.

**Pull request closed without merging**
