### PR TITLE
Fix issue 21154 - DWARF: shared types are not represented

### PR DESCRIPTION
**Pull request by Luhrel**

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
Tests?

**Comment by Luhrel** [comment]
> Tests?

Unfortunately, there's no way to test this, because DMD doesn't emit the `debug_pubtypes` section.

**Comment by wilzbach** [comment]
> Unfortunately, there's no way to test this, because DMD doesn't emit the debug_pubtypes section.

Why bother adding it then?

**Comment by wilzbach** [comment]
> Unfortunately, there's no way to test this, because DMD doesn't emit the debug_pubtypes section.

Not even with a GDB or shell test?

**Comment by ibuclaw** [comment]
> > Unfortunately, there's no way to test this, because DMD doesn't emit the debug_pubtypes section.
> 
> Not even with a GDB or shell test?

GDB ignores the tag, someone will have to implement support there as well...

... however, granted that this tag is intended for UPC, are we certain that it has the same meaning as D shared?

**Comment by Luhrel** [comment]
> ... however, granted that this tag is intended for UPC, are we certain that it has the same meaning as D shared?

Yes and no. DWARF tags are abstracts, so it'll depend of its implementation in the debuggers.

**Review by ghost — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
