### PR TITLE
don't need to allocate memory in hasIdentityOpAssign()

### PR DESCRIPTION
**Pull request by WalterBright**
use stack variables instead

### CODE REVIEW

**Comment by andralex** [comment]
this may get dangerous...

**Comment by yebblies** [comment]
FWIW there was a bunch of this in the C++ version of DMD, so it's nothing new.

**Comment by 9rnsr** [comment]
From my knowledge, this is dangerous change.

With template opAssign or opEquals, `auto ref` parameters would store the function arguments into `TypeFunction.fargs`. Then later, the second instantiation of those template function would refer the arguments to see the match of ref-ness, then it will destroy everything so the argument expressions are already dead.

I can remember that a crash or other incorrect result generation issue had occurred before, though I cannot find it from git blame. I was studied that we should not allocate any AST objects on stack. That's always the source of segfault issue.

**Comment by WalterBright** [comment]
We already store some AST objects on the stack in CTFE. And yes, it is dangerous. But memory consumption is very excessive in the compiler, and a significant cost. We just have to be careful.

**Comment by 9rnsr** [comment]
Do you mean the use of `UnionExp`? It's completely different. It's content never be referred from other ASTs, but in this case, references to the stack allocated expressions are actually saved into template instance cache.
I know that not-few places use heap allocation for short term use. But they're necessary to avoid compiler segfault. (and the jump to ddmd has reduced its pain by GC?) Taking precedence of memory footprint reduction than segfault occurrence is merely foolish.

**Pull request merged**
