### PR TITLE
[REG2.071] Issue 15984 - Interface contracts retrieve garbage instead…

### PR DESCRIPTION
**Pull request by thewilsonator**
… of parameters

Rebase of #5765

### CODE REVIEW

**Comment by WalterBright** [comment]
@rainers writes in https://github.com/dlang/dmd/pull/5765

"FYI: when porting the original fix to LDC, I chose to just pass the adjusted this pointer to the interface contracts. No magic required to change the actual pointer in ThisExp.
With this, your test case runs further than when built with DMD 2.071, but still asserts in C.f3.i."

I'm not sure what he means. Does he have a better fix? @rainers please clarify!

**Comment by rainers** [comment]
> I'm not sure what he means. Does he have a better fix? @rainers please clarify!

I guess this referes to this commit: https://github.com/ldc-developers/ldc/commit/628a560574ffcc5e5902f7c5513e6ae9bd2c4844. This was 2 and a half year ago, so the following might not be accurate and also outdated:

IIRC dmd passes the object pointer to the interface contract, passes the offset as a parameter and goes to great length to correct both in the contract function when calling interface functions or accessing parameters. LDC instead passes the adjusted interface pointer as `this` so the contract just stays a regular unmodified function.

**Comment by WalterBright** [comment]
Does the ldc commit fix bug 15984 for LDC?

**Comment by FeepingCreature** [comment]
This PR does not seem to actually fix the issue.

```
import core.stdc.stdio;
interface I {
    void foo(Object obj)
    in { printf("%p\n", obj); obj.toString; }
}
class C : I { override void foo(Object obj) in { } do { } }
void main()
{
    auto c = new C;
    c.foo(new Object);
}
```

**Pull request closed without merging**
