### PR TITLE
change codecov bot to dlang-bot

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by wilzbach** [comment]
LGTM, let's hope this will fix our access problems :)

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by wilzbach** [comment]
I am not sure whether it was this PR kicking on (or @CyberShadow pushed some buttons), but it seems that we finally got the CodeCov status checks working :tada: 

image

thanks  @MartinNowak  :)

**Comment by MartinNowak** [comment]
Obviously still had to OAuth dlang-bot for codecov.

**Pull request merged**
