### PR TITLE
Move TypeInfo's DT generation into todt.c

### PR DESCRIPTION
**Pull request by yebblies**
This makes converting typeinf.c to D easier.

### CODE REVIEW

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Comment by ibuclaw** [comment]
I only have a need to move these guys to the frontend.

https://github.com/D-Programming-GDC/GDC/blob/master/gcc/d/d-typinf.cc

**Comment by yebblies** [comment]
That seems pretty close.

**Comment by ibuclaw** [comment]
Almost spot on, if you consider the refactorings between 2066 and 2068.

**Comment by yebblies** [comment]
There is a pretty strong correlation between 'functions that call dmd backend methods' and 'functions that gdc deletes'.

**Pull request merged**
