### PR TITLE
New ctfe

### PR DESCRIPTION
**Pull request by UplinkCoder**
updating
this added floating point support among other things.

### CODE REVIEW

**Comment by thewilsonator** [comment]
This seems to have a very large amount of unrelated history, is it possible to split this PR in two and rebase your changes on top of the commits that are already in master, and have those in a separate PR? That would make reviewing much easier.

**Comment by UplinkCoder** [comment]
@thewilsonator this PR does not target master.
it is meant to bring the newCTFE branch up to date.
rebasing the 200 something commits on newCTFE is too much effort.

**Comment by MartinNowak** [comment]
> @thewilsonator this PR does not target master.
> it is meant to bring the newCTFE branch up to date.
> rebasing the 200 something commits on newCTFE is too much effort.

Where did you merge master (and why :))?

**Comment by MartinNowak** [comment]
I rebased this PR and removed the merge master commit, thus changed the HEAD from b6eb2c84ebd863abfed3196b3f36ba7613c4f104 -> 62370823e33e08fc66e2c7767d297aac3ef0e962.

**Pull request merged**
