### PR TITLE
Fix Issue 5380 - alias this is not considered with superclass lookup

### PR DESCRIPTION
**Pull request by RazvanN7**
implicitConvTo did no check the baseclasses for an alias this. I added the missing bits.

### CODE REVIEW

**Comment by ZombineDev** [comment]
When there's a change in behavior, deprecating the old behavior is the way to go. The annoying part is that we'll need to support both behaviors during the transition period.

**Comment by CyberShadow** [comment]
Here is the failing code:

https://github.com/CyberShadow/ae/blob/d5b62cba28ab7eb8e3ba248de21458218a4436d4/sys/d/cache.d#L185
https://github.com/CyberShadow/ae/blob/d5b62cba28ab7eb8e3ba248de21458218a4436d4/sys/d/cache.d#L209

Here's a short test case:
```d
class X
{
	int i;
}

class C
{
	X x;
	alias x this;
}

class D : C
{
	// alias x this;

	void test()
	{
		i = 5;
	}
}
```

* Current behavior: the code compiles only if the commented line is enabled (workaround for issue 5973).
* Behavior with this PR: the code fails to compile when the commented line is enabled or not.

As far as I can see, currently this PR will introduce a regression, and in this case, does not fix anything. But, I haven't tested with #8822.

**Comment by RazvanN7** [comment]
@CyberShadow #8822 fixes this issue. It seems that both PRs need to be merged in order to delete the workaround alias thises

**Comment by thewilsonator** [comment]
Oh, looks like you did.

**Comment by thewilsonator** [comment]
Ah, I remember why I wanted you to rebase: so that #8822 is included to see if it fixes `ae`.

**Comment by thewilsonator** [comment]
(Rebased, lets see what `ae` thinks)

**Comment by thewilsonator** [comment]
`ae` is still red.

**Comment by CyberShadow** [comment]
Should this go through a deprecation, then?

If not, I can fix ae to detect 5973 and only enable the workaround then. I think that will allow it to compile with this change.

**Comment by thewilsonator** [comment]
It probably should go through a deprecation, but if you can fix it another way that would also work.

**Comment by CyberShadow** [comment]
Well, the two are orthogonal. We generally want all breaking language changes to go through a deprecation, but sometimes we can decide that implementing the deprecation is too hard and the amount of code the change affects is too small to bother.

**Comment by WalterBright** [comment]
What the existing implementation is look back up through the base classes, if that fails, look at the alias this for the current class.

The PR looks back through the base classes, if that fails, go back through the base classes *again*, looking at any alias this in that base class.

An alternative scheme is to merge the two, i.e. look back through the base classes simultaneously with checking the alias this in those base classes.

A third scheme is to use both methods, and yield an error if both succeed and produce different results. I.e. this is the good old multiple inheritance lookup problem. I suspect method 3 is the safest one to go with.

I'm not sure which is obviously better. But I am sure that the new search behavior needs to be documented. It isn't.

**Review by WalterBright — CHANGES_REQUESTED** [review]
1. Search method is not documented.

2. Not sure search method is correct.

**Comment by 12345swordy** [comment]
> A third scheme is to use both methods, and yield an error if both succeed and produce different results. I.e. this is the good old multiple inheritance lookup problem. I suspect method 3 is the safest one to go with.

There is a name for that particular problem, it called the "Diamond Problem"

**Pull request closed without merging**
