### PR TITLE
build.d Merge backend and backendObjs

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
The seperation of compilation and linking of the backend is a remainder of
DMDs beeing written in C++. Joining both targets results in fewer lines of
code and HOST_DC invocations.

Please let me know if there is another reason to keep both steps separated.

### CODE REVIEW

**Comment by marler8997** [comment]
Actually I think it's this way to support LLVM object files.  When using LDC with link-time optimization I think it needs to be compiled this way.

@Jonmight have more info on this.

**Comment by wilzbach** [comment]
> Actually I think it's this way to support LLVM object files.

Hmm, I don't see how this would be a problem. I think it's mainly historic to support the mixed C++/D build.

> When using LDC with link-time optimization I think it needs to be compiled this way.

Sadly LDC isn't used to compile the DMD binaries anyhow.

**Review by wilzbach — APPROVED** [review]

**Comment by kinke** [comment]
> Actually I think it's this way to support LLVM object files. When using LDC with link-time optimization I think it needs to be compiled this way.

Nope.

**Comment by marler8997** [comment]
In this commit: https://github.com/dlang/dmd/commit/66b0ede5a90325b74f84f34ecacbb41d529d5930

I removed the `ifdef ENABLE_LTO` case in `posix.mak`.  Someone had added support to compile DMD with link-time optimization.  I chatted with @JohanEngelen about it and he said that when you enable link-time optimization with LDC, it generates LLVM object files instead of the normal ELF object files.  The difference between the ENABLE_LTO case and the non LTO case was that the LTO case used the backend object files whereas the non LTO case used `backend.a`.  I combined both cases by using a combined `backend.o` instead of a `backend.a` as it would be compatible with both LDC with LTO and any other compiler.

Since then, `build.d` has switched to using `backend.a` instead of `backend.o`.  I'm not sure whether or not this breaks LDC with LTO or not, but if it does then we should probably switch back to using `backend.o`...?

**Comment by kinke** [comment]
LLD or the LTO gold plugin don't care about whether they get a bitcode object file directly or a static library containing bitcode objects. And as long as using LDC for archiving the static library via `-lib`, there are no issues when producing a static library including bitcode objects.

The change in this PR is a more subtle one; it compiles and archives the backend modules in a single `-lib` command-line, which implies that each module is compiled as a separate object file, whereas master currently compiles all backend modules to a single object file. This means that LTO is more useful with this change, as cross-module optimizations across the backend objects aren't performed anymore (whereas they currently are when compiling them all into a single object file/translation unit). When compiling with LDC, the previous behavior can be easily restored by adding `-singleobj` to the cmdline; not sure if that's possible with DMD and GDC too. So this PR might lead to a somewhat worse performance without LTO.

**Comment by kinke** [comment]
So for best general performance, I'd get rid of the static library for the backend and use the single backend object file directly instead.

**Comment by kinke** [comment]
After a quick glance, this also applies to the static `lexer` lib, which also compiles to separate object files via `-lib`. The DMD executable (frontend, glue, ...) is fine, as `-of` implies a single object file as well.

**Comment by MoonlightSentinel** [comment]
> LLD or the LTO gold plugin don't care about whether they get a bitcode object file directly or a static library containing bitcode objects. And as long as using LDC for archiving the static library via `-lib`, there are no issues when producing a static library including bitcode objects.
> 
> The change in this PR is a more subtle one; it compiles and archives the backend modules in a single `-lib` command-line, which implies that each module is compiled as a separate object file, whereas master currently compiles all backend modules to a single object file (and then pointlessly archives that single object into a static lib). This means that LTO is more useful with this change, as cross-module optimizations across the backend objects aren't performed anymore (whereas they currently are when compiling them all into a single object file/translation unit). When compiling with LDC, the previous behavior can be easily restored by adding `-singleobj` to the cmdline (=> generating a single object file and putting it into a static lib); not sure if that's possible with DMD and GDC too. So this PR might lead to a somewhat worse performance without LTO.

I didnt know this, thanks for pointing that out.

Omitting the archive seems to be the better solution for compiling DMD if the archive is not used for other purposes(?)

**Comment by kinke** [comment]
Yes, but also for other purposes, as a static lib containing a *single* object doesn't make a lot of sense. See #10605.

**Comment by MoonlightSentinel** [comment]
Thanks for the insight @kinke.
Closing in favour of #10605

**Pull request closed without merging**
