### PR TITLE
[new AA] aaLiteral compiler support

### PR DESCRIPTION
**Pull request by IgorStepanov**
This is a dmd part of the new AA implementation. 
This PR depends on D-Programming-Language/druntime#1046 and uses new aaLiteral version (with arrays of keys and arguments)

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@IgorStepanov would you close this ?

**Comment by andralex** [comment]
@IgorStepanov around?

**Comment by ibuclaw** [comment]
This should be implemented in the library, not the compiler.

I vote close.

**Comment by ibuclaw** [comment]
Closing.

**Pull request closed without merging**
