### PR TITLE
Issue 15235 - inline asm: silent ICE (segfault) in asm_add_exp(

### PR DESCRIPTION
**Pull request by Cauterite**
https://issues.dlang.org/show_bug.cgi?id=15235

### CODE REVIEW

**Comment by Cauterite** [comment]
still not finished, just opened the pull so I can do bisection

**Comment by WalterBright** [comment]
dmd doesn't use EH for reporting errors; I don't really want to start now. I understand that the existing scheme just quits on errors, and this makes it annoying to write the test suite file. A better scheme would be to fix iasm.d so it recovers from errors and continues, like the rest of dmd does, rather than use EH.

**Comment by WalterBright** [comment]
P.S. Thanks for tracking down the root cause of this set fault.

**Comment by Cauterite** [comment]
Alright then, should I modify this pull so that it doesn't rely on pull/5244 ?

**Comment by CyberShadow** [comment]
@MartinNowak dlang-bot's comment above looks bugged (same issue number repeated twice) but I can't reproduce this bug locally.

**Comment by Cauterite** [comment]
@CyberShadow I can reproduce it very reliably: http://dpaste.dzfl.pl/78292955e3c5

**Comment by CyberShadow** [comment]
@Cauterite Sorry, I'm talking about @MartinNowak's dlang-bot, particularly the comment it posted above (the same Bugzilla number repeated twice), this has nothing with your bug or the issues it fixes :)

**Comment by Cauterite** [comment]
@CyberShadow Oops, never mind then.

**Comment by Cauterite** [comment]
this will be fixed by the patch for issue 15257

**Pull request closed without merging**
