### PR TITLE
Rework rewrites of OPmemset to be more general

### PR DESCRIPTION
**Pull request by WalterBright**
…ails for types of size > 1

### CODE REVIEW

**Review by ibuclaw — COMMENTED** [review]
A test case would be nice.

**Comment by WalterBright** [comment]
If this didn't work it should break everything. Besides, this is a WIP. There's a lot more to come.

**Comment by WalterBright** [comment]
```
core.exception.AssertError@/home/runner/work/dmd/dmd/dmd/compiler/test/tools/dshell_prebuilt/dshell_prebuilt.d(204): last command failed
----------------
??:? _d_assert_msg [0x7fc3c8f8e3ac]
??:? [0x55cf5cadaedb]
??:? [0x55cf5cadb0e1]
??:? [0x55cf5cb38ee6]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll().__lambda2() [0x7fc3c8fcb31e]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x7fc3c8fcb1cd]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7fc3c8fcb2a6]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x7fc3c8fcb1cd]
??:? _d_run_main2 [0x7fc3c8fcb136]
??:? _d_run_main [0x7fc3c8fcaf1f]
??:? [0x55cf5cb38f87]
??:? __libc_start_main [0x7fc3c88ef0[82](https://github.com/dlang/dmd/actions/runs/3810503059/jobs/6482619242#step:18:83)]
??:? [0x55cf5cad9c3d]
Error: last command exited with code -11
==============================
>>> TARGET FAILED: dshell/dll_cxx.d
FAILED targets:
- dshell/dll_cxx.d
Error: Process completed with exit code 1.
```

@RazvanN7 Can we please fix the test suite so that the tests designed to find compiler bugs run *first* rather than *last*?

**Comment by WalterBright** [comment]
Since this chunk of code stands alone fine, it should be pulled and then I will proceed with fixing 19946.

**Comment by dkorpel** [comment]
Please remove 'fix issue 19946' from the commit message and give it an appropriate title, so it's clear what this actually does

**Comment by WalterBright** [comment]
ok

**Comment by RazvanN7** [comment]
@WalterBright Currently, the tester needs to build some tools to be able to run the testsuite. Most of those tools are build with the host D compiler (not the generated, most recent one), however, the dshell test requires that the most recent compiler version is used, because it tests shell stuff like if an environment variable is propagated correctly to an executable. However, this should not be a problem, because, typically, the dshell test is usually run among the last tests.

**Pull request merged**
