### PR TITLE
Drop identical template instances from sibling list

### PR DESCRIPTION
**Pull request by UplinkCoder**
This PR cannot be merged as is.
I am putting it out here for discussion.

@WalterBright I'd like your opinion.
Or anyone else's who knows the template system.

### CODE REVIEW

**Comment by joakim-brannstrom** [comment]
Ohh interesting, I'll test it out when it starts passing the test suite.
If I understand correctly this may reduce the number of symbols in the object file? I dislike the link times I am having so....

**Comment by UplinkCoder** [comment]
@joakim-brannstrom 
it should.
I doubt it's significant though since `needsCodegen` should answer no to most of those.
It passes the test-suite already.

**Comment by joakim-brannstrom** [comment]
> I doubt it's significant though since `needsCodegen` should answer no to most of those.
> It passes the test-suite already.

Do you think it would help in this case? https://forum.dlang.org/post/mkfxhykosaxwgclibgng@forum.dlang.org

**Comment by UplinkCoder** [comment]
I don't think so.
type functions would help though.

**Comment by UplinkCoder** [comment]
This ain't gonna work.

**Pull request closed without merging**
