### PR TITLE
Revert "fix Issue 23548 - [REG 2.098] C sources files have precedent over D modules in imports"

### PR DESCRIPTION
**Pull request by WalterBright**
Reverts dlang/dmd#14687

Reverted until consensus can be reached on what the behavior should be.

ping @ibuclaw @Geod24 @thewilsonator

### CODE REVIEW

**Comment by adamdruppe** [comment]
ImportC should never have hijacked D syntax in the first place. We ought to define something separate.

**Comment by Geod24** [comment]
@WalterBright : Release is not happening tomorrow, so can we have the conversation here about what the behavior should be?

I think things I've been pulled a bit fast, so we can either pull this fast as well (which is just adding to the confusion), or have a conversation, with the shared understanding that no release is going to happen without:
a) A solution that we agree on, OR;
b) This PR being pulled in the absence of a solution;

If you disagree with that approach, we can just pull this as-is.

**Comment by WalterBright** [comment]
@Geod24 thanks for the sensible approach. I'm ok with (a).

**Comment by WalterBright** [comment]
Or more precisely, it *shouldn't matter* to the importer how the importee is implemented.

**Comment by ibuclaw** [comment]
Merging, because let's keep current broken behaviour in point release for now.

**Pull request merged**
