### PR TITLE
Fix Issue 24112 - binary expressions with noreturn vars produce incon…

### PR DESCRIPTION
**Pull request by ntrel**
…sistent results

Testing like `fail_compilation/noreturn.d`.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by RazvanN7** [comment]
It seems that this issue is a 2.099 regression. Before that the compiler used to issue "Error: incompatible types for `(foo) + (1)`: `noreturn` and `int`" for such code, however, this seems to have been wrong also. The bottom type DIP does not specifically say whether `int` + `noreturn` should be a compiler error or a runtime assert, however, from this excerpt from the DIP:

"(2) All built-in operators that have "overloads" act as if they have specialized versions for noreturn.

E.g., the expression assert(0) + assert(0) would otherwise cause an ambiguity error: is it int, long, float or double addition? With this rule, it holds that is(typeof(assert(0) + assert(0)) == noreturn). Another example: In [1, 2, 3] ~ assert(0), is it concatenating an int or an int[]? Since noreturn is the subtype of everything, it would technically be ambiguous. In practice, it does not matter---the resulting expression has type int[] and compiles to:

auto __tmp = [1, 2, 3];
assert(0);
"
 
I would deduce that `auto t = foo + 1` where `foo` is of type noreturn would be lowered to:

```
assert(0);
auto t = 1;
```

making this PR correct.

@dkorpel can you double check this please?

**Review by RazvanN7 — APPROVED** [review]

**Comment by SixthDot** [comment]
please revert, this breaks the CI, esp. fail_compilation/noreturn_expr.d

**Comment by RazvanN7** [comment]
hmm but it was passing all of the tests.

**Comment by SixthDot** [comment]
> hmm but it was passing all of the tests.

Yes but for some reasons tests were not re-reun since last week. And you've fixed the other noreturn bug within that week.

**Pull request merged**
