### PR TITLE
make DsymbolPrettyPrintVisitor a function local class

### PR DESCRIPTION
**Pull request by WalterBright**
Which guarantees it is accessible only through the front door.

Review with whitespace changes off.

### CODE REVIEW

**Review by thewilsonator — COMMENTED** [review]
I agree with the change from `*` -> `ref`, I don't really agree with the nesting of the visitor inside the function, it adds four spaces of indentation for not much gain.

**Comment by dkorpel** [comment]
I agree with Nicholas, large nested declarations are hard to read.

**Comment by thewilsonator** [comment]
Put it this way, I've done more than a few refactoring doing the exact opposite of this and had I stumbled across code that looked like this PR would submit a PR to put it back the way is was.

**Comment by WalterBright** [comment]
More generally, it just isn't evident what the class is doing without some careful study of it. By encapsulating it into a function, it's purpose becomes much more clear.

**Review by ghost — APPROVED** [review]
long nested declarations are a problem when nested in "already-long" declarations. That is not the case here. Essentially the diff is like +15 -15.

**Pull request closed without merging**
