### PR TITLE
fix Issue 14708 - destructor for temporary not called during stack un…

### PR DESCRIPTION
**Pull request by WalterBright**
…winding

This is working for me, so to be sure this PR adds the test case for it.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
Looks like it ain't working on Win64.

**Comment by WalterBright** [comment]
So, why does the autotester dmd build of Win64 work, but the Azure dmd builds fail? The object files generated by each build of dmd should be identical. Can someone email one of the failing Azure dmd builds, so I can compare its output?

**Comment by WalterBright** [comment]
Here's what the various builds are: https://issues.dlang.org/show_bug.cgi?id=21133

**Comment by wilzbach** [comment]
> So, why does the autotester dmd build of Win64 work, but the Azure dmd builds fail? The object files generated by each build of dmd should be identical. 

Because we stopped testing on auto-tester and stubbed the output for the windows machines until we get a full replication of all other builds.

 > Can someone email one of the failing Azure dmd builds, so I can compare its output?

Did it pass locally on your machine?

**Comment by rmanthorpe** [comment]
This introduces an asymmetry between constructor and destructor calls. Now temporaries have their destructors called but they are never constructed to begin with. At the very least this need test cases demonstrating construct/destructor symmetry with elaborate constructors and copy constructors.

**Comment by UplinkCoder** [comment]
When has the compiler changed happened that made this work?

**Comment by WalterBright** [comment]
> Did it pass locally on your machine?

No. But at least now I know that Win64 is the only platform where it fails. Kenji's assessment of the cause is likely correct. I have my work cut out for me on this one.

**Comment by WalterBright** [comment]
Why should everything else pass but `buildkite/dmd dlang/phobos` fail with:
```
../dmd/generated/linux/release/64/dmd  -conf= -I../druntime/import  -w -de -preview=dip1000 -preview=dtorfields -m64 -fPIC -transition=complex -O -release -unittest -version=StdUnittest -c -ofgenerated/linux/release/64/unittest/std/traits.o std/traits.d
--
  | posix.mak:379: recipe for target 'generated/linux/release/64/unittest/std/traits.o' failed
  | make[1]: *** [generated/linux/release/64/unittest/std/traits.o] Segmentation fault (core dumped)
```
which is a **linux** build yet this change is specific to win64?

**Comment by UplinkCoder** [comment]
@WalterBright because the issue is already in ~master.
manually merging stuff and not listening to CI can let that happen.

**Pull request merged**
