### PR TITLE
fix Issue 19609 - [ICE] dmd/expression.d(2790): Segmentation fault

### PR DESCRIPTION
**Pull request by ibuclaw**
Not entirely sure that allowing anything CTFE-able as a deprecation message is wise, but still better than a segfault.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Does the spec need an update?

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
According to 8.3.3, no, this is not spec violating.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
OK, lgtm.

**Comment by ibuclaw** [comment]
You are however limited to only literals in the deprecated message for modules (no symbol resolving is possible as the module hasn't been scanned yet).

People can rejoice that they can finally do `deprecated ("break this up" ~ "into multiple lines") module foo;`, but otherwise the odd tests are there just for coverage (they each have a toStringExp override).

**Comment by ibuclaw** [comment]
Infact I should put a manifest constant test in just for good measure.

**Pull request merged**
