### PR TITLE
remove dead condition when foreach variables are checked

### PR DESCRIPTION
**Pull request by ghost**
No `foreach` variable (`dim < 1`) cannot happen during the semantic pass , this is a parse-time error, example

```d
int[] a;
foreach( /*dim is 0*/ ;a){}
```

does not go further than the parser pass.

### CODE REVIEW

**Comment by 12345swordy** [comment]
That condition looks like a fall back in case the parser fails to catch it.

cc @WalterBright

**Comment by MoonlightSentinel** [comment]
Then it probably should be an `assert` instead.

**Review by 12345swordy — CHANGES_REQUESTED** [review]
Rewrite the old condition as an assert

**Comment by NilsLankila** [comment]
> Then it probably should be an assert instead.

> Rewrite the old condition as an assert

As a little challenge, try to prove that the case can happen.

**Comment by 12345swordy** [comment]
> 
> 
> > Then it probably should be an assert instead.
> 
> > Rewrite the old condition as an assert
> 
> As a little challenge, try to prove that the case can happen.

It can easily happen by a pull request. It has happen before and it can happen again.

**Comment by MoonlightSentinel** [comment]
That misses the point, assertions are there to enforce preconditions like the one you make here:

> this is a parse-time error, [...] it does not go further than the parser pass.

Verifying this assumption prevents future regressions.

**Comment by NilsLankila** [comment]
I have modified the parser and added tests that show that this dead condition is well dead (let's call this a *death certificate*).

> It can easily happen by a pull request. It has happen before and it can happen again.

From now the test suite would break. Also "easily" makes no sense and you dont provide any example of what you state.

> Verifying this assumption prevents future regressions.

done. It turns out that the parser actually **always created a parameter** (the D parser do this all the time, if something fails, it emitts an error but continue parsing)... 
but as said previously as there was a parsing error, the semantic was never run.

**Comment by 12345swordy** [comment]
> From now the test suite would break. 

Test suite does not always capture regression bugs caused by PR.

**Review by Geod24 — CHANGES_REQUESTED** [review]
I think the original code makes more sense. It clearly handles error case while the new version relies on prior knowledge. If it bothers you that the condition is dead, feel free to add a comment.

**Pull request closed without merging**
