### PR TITLE
Delete hack to always do codegen for templates if -debug is used

### PR DESCRIPTION
**Pull request by atilaneves**
This PR deletes code that special cases -debug/-unittest when considering whether or not to do codegen for templates in non-root modules. It also deletes a dmd test that's no longer necessary due to Phobos having been updated in the meanwhile (there used to be a debug block in std.range that caused linker errors due to template instantiation with -debug).

Relevant issues and PR:

https://issues.dlang.org/show_bug.cgi?id=12661
https://issues.dlang.org/show_bug.cgi?id=15230
https://github.com/dlang/dmd/pull/4944

### CODE REVIEW

**Comment by atilaneves** [comment]
Blocked by https://github.com/dlang/phobos/pull/7439

**Review by thewilsonator — APPROVED** [review]

**Comment by UplinkCoder** [comment]
This caused a ICE to appear in our code.

**Comment by UplinkCoder** [comment]
also why are you deleting this tests ... they should still pass after this PR?

**Comment by wilzbach** [comment]
> This caused a ICE to appear in our code.

Is it possible to isolate the code to a reduced example?

**Comment by UplinkCoder** [comment]
> Is it possible to isolate the code to a reduced example?
possible. yes.

My comment is less about a particular example, and more about doing invasive things in poor understood systems ...
I can reduce it for completeness sake.

**Comment by atilaneves** [comment]
> also why are you deleting this tests ... they should still pass after this PR?

They weren't very good tests and not relevant anymore. They were testing that there were no linker failures with Phobos code that doesn't even exist anymore.

**Comment by WalterBright** [comment]
This has caused a regression https://issues.dlang.org/show_bug.cgi?id=15985

**Comment by ibuclaw** [comment]
> This has caused a regression https://issues.dlang.org/show_bug.cgi?id=15985

Issue was created in 2016, this PR was created in 2020.  Unless I've forgotten how time works, no it didn't. :-)

**Pull request merged**
