### PR TITLE
Issue 13116: should reject returning `this` from a ref class member function

### PR DESCRIPTION
**Pull request by quickfur**
Fixes: https://issues.dlang.org/show_bug.cgi?id=13116
Basically, for class members, `this` is a local reference to the class instance, so returning it by ref amounts to returning a reference to a local variable (due to classes being reference types).
For structs, returning `this` by ref returns the address of the original struct, so there is no problem.
There is an unresolved issue with this fix, though: the following valid case is now rejected:

```
class C {
    void func() {
        ref C helper() {
            return this; // should be OK
        }
        auto tmp = helper(); // reference hasn't escaped, shouldn't be rejected
    }
}
```

Not sure how to fix this. Any pointers from dmd experts? ;-)

### CODE REVIEW

**Comment by MartinNowak** [comment]
This caused a regression.
https://issues.dlang.org/show_bug.cgi?id=14262

**Comment by MartinNowak** [comment]
Please properly deprecate before breaking code.

**Comment by 9rnsr** [comment]
> but please properly deprecate before breaking code.

Why we need to prolong life of the broken code?

**Comment by MartinNowak** [comment]
> Why we need to prolong life of the broken code?

One of the main problem with breaking changes is that people can't fix code in libraries they use.
So while some library `A` might force them to update to 2.067 another library `B` and `C` might not yet be compatible. We'll have to get a lot better on this as D applications grow their stack.

Also this fixes a surprising/problematic behavior, but there are a lot of cases where this code currently  works, so it should have been a deprecation not an error.

**Comment by 9rnsr** [comment]
I don't understand. Are you saying that we cannot fix compiler bug anymore so it will break user code?

**Comment by yebblies** [comment]
I agree with Kenji, this looks like a bug fix and shouldn't require deprecation.

**Comment by MartinNowak** [comment]
I'm saying you should try your best to not break code, without giving people a fair chance to fix their code and wait for updated dependencies.

```d
void foo(T)(ref T t)
{
    t.x += 1;
}

class Klazz
{
    void breaks()
    {
        foo(this);
    }

    int x;
}
```

**Comment by yebblies** [comment]
Yes, it breaks code.  It's a bug fix.  Sometimes they break code, but we do them anyway.

**Comment by MartinNowak** [comment]
> Sometimes they break code, but we do them anyway.

Don't unless it's really necessary. And if it is then clearly communicate to people why you broke their code and how they can fix it.

If you're working on a huge application, what are you supposed to do with such a message when updating the compiler?
```sh
../libxyz/source/libxyz/internal/blabla.d(1725): Error: template libxyz.internal.blabla.foo cannot deduce function from argument types !()(Klazz), candidates are:
../libxyz/source/libxyz/internal/blabla.d(1716):        libxyz.internal.blabla.foo(T)(ref T t)
```

**Comment by mihails-strasuns-sociomantic** [comment]
> Sometimes they break code, but we do them anyway.

And this really really sucks, making any compiler upgrade a big commitment for any non-trivial code base with many dependencies. As I have mentioned in bugzilla, please at least make sure error messages communicate the problem clearly and don't make user stare into the error log with "wtf?" feeling.

Also there are different kinds of big fixes (based on 2.067-b3 trial experience):

1) One that highlights actual hidden bug in your application (like running destructors/invariants in union fields). When I see one like that I immediately rush fixing it in live code base and feel very grateful to compiler for saving me from some debug nightmare.

2) Cleanup of messy bits (redundant attributes) and closing _theoretical_ type system hole (this PR). What makes such bug fixes very annoying is that they tend to break code that both compiled before and worked correctly. It is "good to fix but please not now" kind of issue.

This is also why I have commented on http://wiki.dlang.org/DIP75 that distinguishing between features and bug fixes for versioning is not very useful in practice.

**Pull request merged**
