### PR TITLE
Fix Issue 22427 - betterC: casting an array causes linker error in string comparison

### PR DESCRIPTION
**Pull request by RazvanN7**
```d
extern(C)
int main(){
    if("a" == "a")
        return 1;
    char[] p;
    auto a = cast(int[])p;
    return 0;
}
```

It seems that the cast is lowered to __ArrayCast which in turn ends up instantiating __equals with the same template parameters, but in a [speculative context](https://github.com/dlang/dmd/blob/master/druntime/src/core/memory.d#L1129). Somehow, the template emission strategy decides that the instance does not require codegen (from what I can tell, the compiler decides that it's better to put the instance in the imported module - core.memory in this case), hence the linker errors.

I think that this strategy should be disabled in the case of betterC as it currently is with -allinst.

Targeting master as this might be controversial.

### CODE REVIEW

**Comment by RazvanN7** [comment]
cc @kinke . I'm not sure this is correct, but it seems to me that `TemplateInstance.needsCodegen` doesn't take into account speculative contexts such as `static if`s. It looks like `TemplateInstance.minst` should be null, but in the case of the static if in core.memory, `minst` is set to the module.

**Comment by kinke** [comment]
Such linker errors are absolutely to be expected with `-betterC`, we have talked numerous times about this - if the compiler can prove that an instantiation is guaranteed in imported & analyzed druntime/Phobos modules, it's eliding codegen without `-allinst`, NO ugly special cases for `-betterC` yet (where druntime & Phobos aren't linked), just the regular, default template culling algorithm. A slight change in druntime can easily cause such regressions. As can different compiler options for druntime/Phobos and user code...

So implying (or defaulting to) `-allinst` with `-betterC` makes sense to me, to work around these cases. The extra codegen cost heavily depends on the compilation granularity - from basically negligible (e.g., compiling a whole dub project at once) to potentially heavy when compiling each module separately.

`global.params.allInst` is used in at least one other location, so I think this should be taken care of by the driver (`dmd/mars.d` or so) instead of the current 'hacky' localized `-betterC` special case.

**Review by dkorpel — APPROVED** [review]

**Comment by dkorpel** [comment]
Is this intentionally targeting master?

**Comment by dkorpel** [comment]
I guess the controversial part is that -betterC is supposed to be 'light', but -allinst is 'heavy'.

**Pull request merged**
