### PR TITLE
[dmd-cxx] Backport testsuite makefile changes from master

### PR DESCRIPTION
**Pull request by ibuclaw**
And move disabling of D2 testsuite to auto-tester-test recipe (should make Windows CI green)

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Comment by wilzbach** [comment]
It still fails on OSX when building Phobos though:

```
ld: warning: could not create compact unwind for _D4core7runtime19defaultTraceHandlerFPvZ16DefaultTraceInfo7opApplyMxFMDFKmKxAaZiZi: offset of saved registers too far to encode
Undefined symbols for architecture x86_64:
  "___tls_get_addr", referenced from:
      _D3std6getopt21__T12handleOptionTPbZ12handleOptionFNfAyaPbKAAyaKS3std6getopt13configurationbZb in checkwhitespace.o
      _D3std6getopt21__T12handleOptionTPbZ12handleOptionFAyaPbKAAyaKS3std6getopt13configurationbZ14__foreachbody6MFNfKmKwZi in checkwhitespace.o
      _D3std6getopt16__T10getoptImplZ10getoptImplFNfKAAyaKS3std6getopt13configurationKS3std6getopt12GetoptResultKC3std6getopt15GetOptExceptionHAyaAvHAyaAvZv in checkwhitespace.o
      _D3std10functional114__T7memoizeS95_D3std5regex18__T9regexImplTAyaZ9regexImplFNfAyaAxaZS3std5regex8internal2ir12__T5RegexTaZ5RegexVii8Z7memoizeFAyaAxaZS3std5regex8internal2ir12__T5RegexTaZ5Regex in checkwhitespace.o
      _D3std6getopt8optMatchFNfAyaAyaKAyaS3std6getopt13configurationZb in libphobos2.a(getopt_89f_340.o)
      ___dmd_begin_catch in libphobos2.a(dwarfeh_68f_6b9.o)
      __d_arrayappendcTX in libphobos2.a(lifetime_6dd_6c8.o)
      ...
ld: symbol(s) not found for architecture x86_64
```

**Comment by ibuclaw** [comment]
I think some backend change is required for that.

**Comment by jacob-carlborg** [comment]
`___tls_get_addr` is defined in druntime. Has the mangling changed?

**Comment by ibuclaw** [comment]
#7620 comes to mind.

**Comment by ibuclaw** [comment]
The problem with `___tls_get_addr` is the absence of any mangling.  I've tried to remove this special case before.

**Pull request merged**
