### PR TITLE
Revert "Merge pull request #11381 from andralex/pool"

### PR DESCRIPTION
**Pull request by andralex**
This reverts commit 30dc1a406541aa4d1dcfe8989d1b33a51ae331a9, reversing
changes made to 74b6dade8044b10d625588ff685512f04182533f.

For reference here are the commands I ran:

```bash
git checkout -b nopool
git revert --strategy resolve 30dc1a406541aa4d1dcfe8989d1b33a51ae331a9 -m 1
```

Then I fixed one conflict, which seems to have been why the automatic revert didn't work.

### CODE REVIEW

**Comment by andralex** [comment]
Reference: https://github.com/dlang/dmd/pull/11381 which seems to be more trouble than it's worth.

**Comment by John-Colvin** [comment]
I think this should target `stable`,  no?

**Comment by andralex** [comment]
https://github.com/dlang/dmd/pull/11898 targets stable, thanks

**Comment by UplinkCoder** [comment]
@andralex you can close this one.
stable gets merged into master after releases.

**Comment by wilzbach** [comment]
> stable gets merged into master after releases.

Everyone can run the `merge_stable` script at any time (and thus merge stable back to master).

**Pull request closed without merging**
