### PR TITLE
add getMember support for strings representing the FQN of an import

### PR DESCRIPTION
**Pull request by ghost**
This is a follow up of https://github.com/dlang/dmd/pull/11627 and based on the complains on https://forum.dlang.org/post/emvjkiaquulxswddfyeu@forum.dlang.org.

Note that I'm afraid that that it's not possible not to scan the string.

### CODE REVIEW

**Comment by schveiguy** [comment]
This needs an issue/changelog. In any case, I'm not sure this is the right path. But I also don't ever use `__traits(allMembers)` to look at imports. So I don't know what people expect when they are specifically looking for it.

To me, this fixes the bug that I can use `__traits(allMembers, modname)` and `__traits(getMember, modname, m)` to look for certain things in the module, and it still compiles. So if this is what people want, then I guess it works for me.

People might expect `__traits(getMember, modname, "Struct.Member")` to work as well, but I'm not too worried about it.

**Comment by NilsLankila** [comment]
> People might expect __traits(getMember, modname, "Struct.Member") to work as well, but I'm not too worried about it.

That works already as that is covered by phobos "hasStaticMember" for example. That's the reason why the code added never return `False()` or `null`.

**Comment by NilsLankila** [comment]
> This needs an issue/changelog

Not really. The issue was 19590. What 's done here should have be done with the other PR.

**Comment by thewilsonator** [comment]
The reason for an issue/changelog entry is so that it ends up in the release notes.

**Comment by UplinkCoder** [comment]
This way of going about it seems like the design was a bit off in the first place.

**Comment by NilsLankila** [comment]
The problem is that sub modules as something imported, e.g `std.stdio` are a single thing but this single thing is represented with several identifiers in a kind of shell. If you bypass the shell then you give access to imports of other modules, creating symbol leaks:

```d
module a;
import std.stdio;
```

```d
module b;
import std.meta;
```

without the fix for 19590 in this case when doing introspection on `a` you'd get `std` and `std` would leak `meta` while not imported frrom `a`.

**Comment by NilsLankila** [comment]
I dont know if i explain well the problem (because that interfers with a identical situation I've encountered in the implementation of another programming language).

Let's say that `__traits(allmembers, someModule)` would still return "std" if it contains `import std.stdio`. 
Then `__traits(getMember, someModule, "std")` resolves to a module/package. 
At this point you loose completly the track of the import as a __whole__ (what i called a _shell_ in my previous explanations)

**Comment by schveiguy** [comment]
I'm pushing to revert the original change. This should wait until after the release I think. See #11739

**Comment by UplinkCoder** [comment]
@NilsLankila I don't think allMembers should include imports at all.

**Comment by schveiguy** [comment]
Author is a ghost now.

**Pull request closed without merging**
