### PR TITLE
Fix bugs when building with g++-7

### PR DESCRIPTION
**Pull request by ibuclaw**
First is a bug caught by `-Waggressive-loops` - it's pretty obvious that it's an out of bounds error.

Second, ~there seems to be a segfault when doing `esave = *e`, I have no idea why.  Seems like a g++ regression.  Using memcpy and things just work...~ building using g++7, I get the same bug as 6215, aligning memory to 16-bytes fixes the problem - particularly for copying `elem` which uses `movqda`. instruction.

### CODE REVIEW

**Comment by ibuclaw** [comment]
The instruction where it segfaults is:
```
movdqa 0x40(%rbx),%xmm0
```
Something is very fishy about `movdqa`.

**Comment by ibuclaw** [comment]
Ahh... you can't movdqa to/from unaligned memory addresses.  My guess is that it requires that the memory is aligned to 16 (both structs have an 8 byte alignment).  I'm now getting segfaults in other places.

I wonder if the misalignment is coming from gcc or dmd...

**Comment by ibuclaw** [comment]
I'm getting the same as https://issues.dlang.org/show_bug.cgi?id=6215

**Comment by ibuclaw** [comment]
@WalterBright - ready for review.  This should allow using gdc-7 in travisci.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
