### PR TITLE
remove the SC Enum aliases

### PR DESCRIPTION
**Pull request by benjones**
Follow up to #14399
I removed the first ~5 of the enum aliases here and the diff was big enough that I figured I'd spread it across a couple of PRs.  I also replaced entire switch/case blocks using the ones I removed, and other easily visible nearby uses of SCxxx enums.

### CODE REVIEW

**Comment by benjones** [comment]
@dlang-bot ??

**Comment by benjones** [comment]
@dkorpel looks like the bot didn't assign reviewers, but since this is followup to your PR, you're probably the right person to look.

**Review by thewilsonator — APPROVED** [review]
Looks good. You might want to do all of them at once and add the resulting commit to the git blame ignore revs list.

**Comment by benjones** [comment]
> Looks good. You might want to do all of them at once and add the resulting commit to the git blame ignore revs list.

I removed the rest of the aliases in a second commit.   I can squash them if you want.  It doesn't look like there's a blame ignore revs file yet, should I add one to the root of the repo?

**Comment by thewilsonator** [comment]
> I can squash them if you want. 

Yes please.

> should I add one to the root of the repo?

Yes.

**Review by RazvanN7 — APPROVED** [review]

**Comment by benjones** [comment]
@thewilsonator Done

**Comment by benjones** [comment]
@RazvanN7 bump

**Pull request merged**
