### PR TITLE
Fix Issue 19548 - [REG 2.080] Missing reference to _D6object__T14__switch_errorZQrFNaNbNiNfAyamZv

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by thewilsonator** [comment]
I thought we can't use phobos in the test suite?

**Comment by wilzbach** [comment]
Argh, the test was in `compilable` and thus didn't test this as no linking was done. Please ignore.

**Comment by wilzbach** [comment]
> I thought we can't use phobos in the test suite?

```
 ag "import std" |wc
    300    1086   16325
```

**Comment by thewilsonator** [comment]
I stand corrected.

**Pull request closed without merging**
