### PR TITLE
Issue 14016 - Nested inherited class doesn't know the type of its outer object

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14016

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Well, the assert is triggered in the test-suite. :)

**Comment by 9rnsr** [comment]
Oh... if the nested class is declared in a function, cdp will be NULL. I removed the assert for the case.

**Comment by AndrejMitrovic** [comment]
Hmm, I'm getting this in the autotester after logging in and trying to toggle auto-merge:

```
Sorry, it looks like you don't have permission to this project at github.
```

@braddr any ideas?

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Pull request merged**
