### PR TITLE
Fix Issue 18623 - Documented unittest should not allow private symbol access

### PR DESCRIPTION
**Pull request by RazvanN7**
Just as a discussion starter.

### CODE REVIEW

**Comment by dkorpel** [comment]
This could use a spec PR, changelog entry, and end date for the deprecation. But before that, it should get a yay or nay from @WalterBright and/or @atilaneves .

**Comment by MoonlightSentinel** [comment]
Access to private symbols is just one of the problems that can manifest in examples generated from unittests. E.g. missing imports is another big issue that is currently detected using the `test_extractor`.

**Review by Geod24 — CHANGES_REQUESTED** [review]
Strong no from me, for the following reasons:

1) Implementation
This only considers `public` symbols: What about `protected`, which is public under certain conditions ? And `package` ?

2) Concept
If someone wants to document private symbols, why prevent it ? In the example, the documented unittest is attached to a private symbol, isn't it ? This is the kind of check that belongs to a linter, not the compiler.

**Comment by RazvanN7** [comment]
Thanks @Geod24 for the assessment. I am certain that there are some cases where a private symbol is used in a documented unittest that is not attached to the actual declaration. In those situations, this sort of diagnostic would be useful, however, I agree that a third party tool should be the judge of that (such as our test extractor that use in phobos).

**Comment by ntrel** [comment]
> Access to private symbols is just one of the problems that can manifest in examples generated from unittests. E.g. missing imports is another big issue that is currently detected using the `test_extractor`.

Missing imports is something a user of a library can fix themselves. Accidental use of a private symbol is not necessarily fixable by that user.

**Comment by ntrel** [comment]
> 2. Concept
>    If someone wants to document private symbols, why prevent it ? In the example, the documented unittest is attached to a private symbol, isn't it ? 

If you want to support that unusual case, require `private unittest` to enable using private symbols in the test. (The documented unittest could even be inferred as private if the symbol it's documenting is private).

**Comment by ntrel** [comment]
> I agree that a third party tool should be the judge of that (such as our test extractor that use in phobos).

I doubt that many projects will set up a CI test just for this. Instead private symbol use will have to be manually detected and reported.

**Pull request closed without merging**
