### PR TITLE
[stable] cirrus: Switch to big-sur image, use catalina for bootstrap only

### PR DESCRIPTION
**Pull request by ibuclaw**
Requires:

* [x] dlang/druntime#3612.

### CODE REVIEW

**Comment by PetarKirov** [comment]
I restarted CircleCI. Let's see how it goes.

**Comment by PetarKirov** [comment]
It's green now.

@ibuclaw not sure what to do about this:

image

Perhaps you can ignore it and merge manually?

**Comment by ibuclaw** [comment]
Yes, it can be ignored, I'll fix the repo after this.

**Comment by ibuclaw** [comment]
Or do we want to keep both for transition? All PRs will need rebasing, (but that's a good thing for testing).

**Comment by PetarKirov** [comment]
> Or do we want to keep both for transition? 

I'm not against keeping both, though if we had to make a choice, I'd say that adding `monterey-xcode-13.1` would be slightly more important.

**Comment by ibuclaw** [comment]
Monterey has its own issues that need a bug report for:
```
==============================
Test 'runnable/test17868b.d' failed: 
expected:
----
init
init
main
fini
fini
----
actual:
----
init
init
main
----
diff:
----
 init
 init
 main
-fini
-fini
----
```

**Comment by PetarKirov** [comment]
> Monterey has its own issues that need a bug report for [..]

Thanks for testing, in that case, let's this PR focused on just adding macOS 11 (BigSur).

**Comment by PetarKirov** [comment]
@ibuclaw So finally, shall we keep Catalina (I'm fine either way)?

**Comment by PetarKirov** [comment]
As discussed with Iain on Slack, we will use macOS 10.15 for bootstrap builds and 11.x for building with latest dmd and for coverage.

**Pull request merged**
