### PR TITLE
Fix the circle CI failures

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by thewilsonator** [comment]
WTF this is green on master as of 71df3f6e4593d6af3e464397c1693cb0a588dc38 
rebasing onto a221c08

**Comment by thewilsonator** [comment]
I suspect #11823 is to blame

**Comment by thewilsonator** [comment]
Weird, when rebased on a037caa5785e27db1f547849d0b992b7a86e6282 it results in a different error

**Comment by thewilsonator** [comment]
rebasing after #11823 , green?!?!???!!?

**Comment by RazvanN7** [comment]
So it's not #11823 ?

**Comment by thewilsonator** [comment]
I have no idea math this point. It was the first red pr on https://github.com/dlang/dmd/commits/master that exhibited the same error.

**Comment by jacob-carlborg** [comment]
This might be a reason: https://github.com/dlang/dmd/blob/93852961332e44d6e581ef9dc4e2395d74f67a6a/test/unit/lexer/location_offset.d#L7
`deinitializeFrontend` is never called.

**Comment by thewilsonator** [comment]
That seems like a reasonable explanation. Much better Than I've been able to come up with.

**Comment by jacob-carlborg** [comment]
For just using the lexer, initializing the fronted shouldn't be necessary. It's not done  in the other lexer test: https://github.com/dlang/dmd/blob/master/test/unit/lexer/diagnostic_reporter.d.

**Comment by thewilsonator** [comment]
OK.

**Comment by thewilsonator** [comment]
Done.

**Comment by jacob-carlborg** [comment]
Looks good. All tests are passing. 

Did it fail every time before? Can we trust it's good now?

**Comment by thewilsonator** [comment]
> Did it fail every time before?

No it was intermittent

> Can we trust it's good now?

Well the reversion of #11916 passengers first time and so did this.

**Pull request merged**
