### PR TITLE
Fix issue 22027, 20149 - inout doesn't imply return

### PR DESCRIPTION
**Pull request by dkorpel**
Since https://github.com/dlang/dmd/pull/10390 got abandoned, here's another try. Needs a changelog and spec PR, but first let's see if this breaks Phobos and whether this gets accepted.

### CODE REVIEW

**Comment by WalterBright** [comment]
I'm not so sure about this. Removing the implicit `return` may break existing code. The programmer will have to go in and manually add it.

**Comment by dkorpel** [comment]
> I'm not so sure about this. Removing the implicit `return` may break existing code.

It dawned on me that since dip25 is enabled by default now, this is a breaking change, making it less appealing. It might be easier to fix the bug and leave the enhancement be after all.

**Comment by WalterBright** [comment]
@dkorpel are you going to merge the changes from https://github.com/dlang/dmd/pull/13658 into this?

**Comment by dkorpel** [comment]
> @dkorpel are you going to merge the changes from #13658 into this?

My current goal is to fix return-ref / return-scope ambiguity / inference to fix the buildkite failure:
```
source/mir/rc/ptr.d(279,31): Error: returning `createRCWithContext(context._get_value().s, move(context))` escapes a reference to parameter `context`
source/mir/rc/ptr.d(279,31):        perhaps annotate the parameter with `return`<!--EndFragment-->
```

And the druntime stdcpp/string test on FreeBSD (which I haven't reproduced locally yet):
```
../../src/core/stdcpp/string.d(171): Error: scope variable `s` assigned to non-scope parameter `this` calling core.stdcpp.string.basic_string!(char, char_traits!char, allocator!char).basic_string.as_array
../../src/core/stdcpp/string.d(176): Error: scope variable `rhs` assigned to non-scope parameter `this` calling core.stdcpp.string.basic_string!(char, char_traits!char, allocator!char).basic_string.as_array
src/string_test.d(5): Error: template instance `core.stdcpp.string.basic_string!(char, char_traits!char, allocator!char)` error instantiating
../../src/core/stdcpp/string.d(171): Error: scope variable `s` assigned to non-scope parameter `this` calling core.stdcpp.string.basic_string!(wchar, char_traits!wchar, allocator!wchar).basic_string.as_array
../../src/core/stdcpp/string.d(176): Error: scope variable `rhs` assigned to non-scope parameter `this` calling core.stdcpp.string.basic_string!(wchar, char_traits!wchar, allocator!wchar).basic_string.as_array
src/string_test.d(6): Error: template instance `core.stdcpp.string.basic_string!(wchar, char_traits!wchar, allocator!wchar)` error instantiating
```

If that's green, I'll consider this ready for review. Is there anything from #13658 you want see in this PR?

**Comment by WalterBright** [comment]
https://github.com/dlang/dmd/pull/13658 is all green now.

**Comment by dkorpel** [comment]
This is finally unblocked by https://github.com/dlang/dmd/pull/13693 
@RazvanN7

**Review by RazvanN7 — APPROVED** [review]
Thanks!

**Pull request merged**
