### PR TITLE
Add tests for sprintf and fprintf in fail_compilation/chkformat.d

### PR DESCRIPTION
**Pull request by Luhrel**
~~Blocked by https://github.com/dlang/druntime/pull/2972~~

### CODE REVIEW

**Review by WalterBright — APPROVED** [review]

**Comment by Luhrel** [comment]
Can now be merged.

**Comment by thewilsonator** [comment]
```
dhry.d(629): Deprecation: format specifier `"%7.1lf"` is invalid
dhry.d(631): Deprecation: format specifier `"%10.1lf"` is invalid
dhry.d(632): Deprecation: format specifier `"%10.3lf"` is invalid
dhry.d(637): Deprecation: width argument `& Reg_Define` for format specification `"%*s"` must be `int`, not `char*`
dhry.d(637): Deprecation: more format specifiers than 1 arguments
Error: unknown, please file report on issues.dlang.org
dhry.d(638): Deprecation: format specifier `"%7.1lf"` is invalid
dhry.d(639): Deprecation: format specifier `"%10.1lf"` is invalid
dhry.d(640): Deprecation: format specifier `"%10.3lf"` is invalid
```

**Comment by MoonlightSentinel** [comment]
That's already present in master, see https://issues.dlang.org/show_bug.cgi?id=20645

**Comment by Luhrel** [comment]
> ```
> dhry.d(629): Deprecation: format specifier `"%7.1lf"` is invalid
> dhry.d(631): Deprecation: format specifier `"%10.1lf"` is invalid
> dhry.d(632): Deprecation: format specifier `"%10.3lf"` is invalid
> dhry.d(637): Deprecation: width argument `& Reg_Define` for format specification `"%*s"` must be `int`, not `char*`
> dhry.d(637): Deprecation: more format specifiers than 1 arguments
> Error: unknown, please file report on issues.dlang.org
> dhry.d(638): Deprecation: format specifier `"%7.1lf"` is invalid
> dhry.d(639): Deprecation: format specifier `"%10.1lf"` is invalid
> dhry.d(640): Deprecation: format specifier `"%10.3lf"` is invalid
> ```

Somehow, I don't get any error on my system:
```
$ test/run.d runnable/dhry.d
unit_test_runner is already up-to-date
d_do_test is already up-to-date
sanitize_json is already up-to-date
dshell_prebuilt is already up-to-date
 ... runnable/dhry.d                -release -O -g -inline  -fPIC ()
```

Which command did you run ?

**Comment by Luhrel** [comment]
Can someone re-run the auto-tester and buildkite ?
It should be ready to merge.

**Comment by MoonlightSentinel** [comment]
Please give this a force push to  trigger the auto-tester

**Comment by thewilsonator** [comment]
@MoonlightSentinel You can restart individual auto-tees by clicking on the Run ID column,  and then clicking on `deprecate` on the Deleted row. Alternatively when all of the tests are delete (on the main screen) just add `auto-merge` and it will prioritise that PR.

**Comment by MoonlightSentinel** [comment]
Thanks @thewilsonator but I don't seem to have the permission to restart single jobs (there is no `deprecate` button for me).

**Comment by thewilsonator** [comment]
You nee to log in, see the top left corner.

**Comment by MoonlightSentinel** [comment]
Nevermind, I was already logged in but only looked at already deleted runs.

**Comment by thewilsonator** [comment]
```
std\math.d(246): Deprecation: argument `cast(double)x` for format specification `"%.*Lg"` must be `real`, not `double`
std\math.d(247): Deprecation: argument `cast(double)y` for format specification `"%.*Lg"` must be `real`, not `double`
```

**Comment by WalterBright** [comment]
> Allow double type for Lg format specifier

**PLEASE** follow the SPECIFICATION, do not make up rules. C99 7.19.6.1.7 says "L Speciﬁes  that  a  following  a, A,  e,  E,  f,  F,  g,  or  G conversion  speciﬁer applies to a long double argument."

Not a double. A long double, i.e. `real`.

Please also defer to the actual Standard, not some web site that rewrote it (to avoid copyright infringement concerns) and got it wrong.

Refactorings must not change behavior, either.

**Comment by Luhrel** [comment]
> > Allow double type for Lg format specifier
> 
> **PLEASE** follow the SPECIFICATION, do not make up rules. C99 7.19.6.1.7 says "L Speciﬁes that a following a, A, e, E, f, F, g, or G conversion speciﬁer applies to a long double argument."
> 
> Not a double. A long double, i.e. `real`.
> 
> Please also defer to the actual Standard, not some web site that rewrote it (to avoid copyright infringement concerns) and got it wrong.
> 
> Refactorings must not change behavior, either.

In your changelog, you said:

> For printf, it takes a generous, rather than strict, view of compatiblity.

**Comment by WalterBright** [comment]
Unfortunately, there is no way a 10 byte real is binary compatible with an 8 byte double.

Besides, and I cannot over-emphasize this, **refactorings MUST NOT INCLUDE BUG FIXES OR BEHAVIOR CHANGES**.

**Comment by MoonlightSentinel** [comment]
Is this still useful given `pragma(printf)`?

**Comment by Luhrel** [comment]
> Is this still useful given `pragma(printf)`?

As Walter did all the work, this PR is very trivial now.

I close it. Feel free to reopen it if you really want to.

**Pull request closed without merging**
