### PR TITLE
remove unused addPredefinedGlobalIdent and addGlobalIdent overloads

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by thewilsonator** [comment]
That should say `remove unused addPredefinedGlobalIdent and addGlobalIdent overloads`, the functions are still very much used.

**Review by thewilsonator — DISMISSED** [review]

**Comment by thewilsonator** [comment]
```
/home/circleci/dmd/src/dmd/mars.d(1182): Error: dmd.cond.VersionCondition.addPredefinedGlobalIdent called with argument types (string) matches both:
/home/circleci/dmd/src/dmd/cond.d(715):     dmd.cond.VersionCondition.addPredefinedGlobalIdent(const(char)* ident)
and:
/home/circleci/dmd/src/dmd/cond.d(721):     dmd.cond.VersionCondition.addPredefinedGlobalIdent(const(char)[] ident)
```

Ah, thats why we had them.

**Comment by thewilsonator** [comment]
Hmm, not sure we can do a whole lot about that.

**Comment by WalterBright** [comment]
I just removed them. They're deprecated anyway. @kinke ? @ibuclaw ?

**Comment by WalterBright** [comment]
It is anyway.

**Review by Geod24 — CHANGES_REQUESTED** [review]
They are used. The `char*` is only called from LDC (/ GDC?) which is why it can be marked as `deprecated` - So D code does not use it, but C++ still can.

As long as we are not able to pass slices to an `extern(C++)` functions, we'll have to keep them.

**Comment by ibuclaw** [comment]
Why was this marked deprecated in the first place?

**Comment by Geod24** [comment]
> Why was this marked deprecated in the first place?

Prevent people from using it by mistake from D code.

**Pull request closed without merging**
