### PR TITLE
Remove arrow from TOK enum

### PR DESCRIPTION
**Pull request by AsterMiha**
Unused token type

### CODE REVIEW

**Comment by WalterBright** [comment]
`->` is one of the most common tokens in C and C++ that is not present in D. People converting code from C/C++ to D need to replace all the `->` with `.`, and even so, may accidentally use `->` in their code. Recognizing it as a token in D makes for a more sensible error message than one for `-` followed by `>`.

**Comment by Geod24** [comment]
@AsterMiha : There are a few other places where this is done. E.g. we recognize C-style casts, and used to recognize C-style array declarations. And indeed, this turned out to be quite useful, just like the spellchecker or other suggestions.
If it threw you off, I'm sure it will do so for other would-be contributors. Hence, perhaps adding a comment to explain why it's here would be a better way to address your discovery ?

**Comment by dkorpel** [comment]
@WalterBright @Geod24 The PR isn't lying when saying it's unused. As Razvan pointed out:

> Actually, at the site where that error is printed the condition utilizes 2 distinct tokens [1]: minus and greater than. Therefore I think we can get rid of Tok.arrow
>
> [1] https://github.com/dlang/dmd/blob/master/src/dmd/parse.d#L7737

https://forum.dlang.org/post/dckvecinyykeaawmpexm@forum.dlang.org

**Comment by Geod24** [comment]
Good catch. When submitting such a PR, it would be great to include this information, as reviewers might not be privy to the context.

E.g. something like:
```
`TOK.arrow` seems to be intended to allow better error messages to be displayed when porting C(++) code to D,
as `a->b` is a common construct in those languages.
However, the parser doesn't actually uses it: the parser check uses `TOK.min` followed by `TOK.greaterThan`.
See https://github.com/dlang/dmd/blob/23ff71eb4ecfc16e04efcb73989505d4f7692c55/src/dmd/parse.d#L7737
```

Both in the commit message and the description of the PR ought to give enough context for anyone to validate that the change is correct. This is not only important for reviewers, but for the poor developer that will be tracking a bug in the parser at 3am 5 years from now and want to quickly skip commits that are not relevant to him/her (which is harder to do without context/rationale).

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
