### PR TITLE
Give root/string.d complete coverage

### PR DESCRIPTION
**Pull request by dkorpel**
[Per request](https://forum.dlang.org/thread/qiab48$j46$1@digitalmars.com)

Also adds attributes to it.

### CODE REVIEW

**Comment by Geod24** [comment]
Could you rebase

**Comment by dkorpel** [comment]
> Could you rebase ?

Rebase what, and why? I'm relatively new to rebasing so I'm trying to understand.

**Comment by Geod24** [comment]
Rebase this PR, means including the new commits from master into this PR.
Assuming you are on the right branch:
```console
git fetch upstream # If "upstream" is the remote pointing to dlang/dmd, check "git remote -v"
git rebase upstream/master
```
Also, I highly recommend you to spend the time to read [this](https://git-scm.com/book/en/v2), it's an invaluable help to use `git`.

**Comment by dkorpel** [comment]
Thanks, I'll give it a read.
I rebased as you described and force pushed. I still wonder though, how did it help? There were no merge conflicts. How can I tell myself I need to rebase?

**Comment by Geod24** [comment]
> There were no merge conflicts. How can I tell myself I need to rebase?

Rebasing is just a simple / easy way to get the tests to re-trigger.
When the CI tests your PRs, it uses a Github-generated merge commit, which is the merge of your PR into master (because your PR might be based on an old commit). Rebasing your PR will just change that commit, and retrigger the whole testsuite as a result.
There are other way to do so, e.g. `git commit --amend --reset-author` will change your commit without changing its content, and some can be restarted manually, but all things considered, rebasing is just the simplest way to do so.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
