### PR TITLE
don't need to copy the result of copyLiteral()

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by jacob-carlborg — APPROVED** [review]

**Comment by thewilsonator** [comment]
Looks like curl timed out building the docs?

**Comment by thewilsonator** [comment]
Removing automerge, this is blocked by #9177

**Comment by thewilsonator** [comment]
Please rebase.

**Comment by thewilsonator** [comment]
You've changed line endings or something.

**Comment by WalterBright** [comment]
The originals are CR-LF ended, and my stuff forces everything to CR. Sigh.

**Pull request merged**
