### PR TITLE
fix issue 19510 - random and spurious error about a missing NOLOGO.d file

### PR DESCRIPTION
**Pull request by ghost**
There was a missing strlen on a static array that caused random things. One of them is that replaceName failed and the linker name was set to dmd filename, causing dmd to be called with the linker arguments.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]
Can you do a test for this?

**Comment by BBasile** [comment]
I'll try to fix the issue in a first place.

**Comment by BBasile** [comment]
I don't know how to test this (because of the random nature of the bug) but I'm super confident about what was the problem and that the fix is good.

**Review by Geod24 — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Please squash the commits.

**Comment by BBasile** [comment]
ready for merge.

**Comment by andre2007** [comment]
Thank you for solving this nasty bug

**Comment by BBasile** [comment]
your're welcome @andre2007, it was a typical "C" bug.

**Pull request merged**
