### PR TITLE
change -stdc++ switch to -extern-std

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
@ibuclaw > To answer with a question. What part of the D compiler supports the C++ 98 dialect? Can we use dmd to compile C++ code directly?

Adding another c++ does not address your question.

@thewilsonator > What part of -std= says c++ to you?

The part where it says `-std=c++98`

> c++98 is for consistency in the keys accepted by the correspond argument to the c++ compiler. I want this switch to read foreign-language-compatibilty=foo-version-42, -std= does not do that.

`-std=` does that just fine, that's what the `c++` in `c++98` does.

> This horse is dead

Why do you need two `c++` strings?

**Comment by 12345swordy** [comment]
Ok, this is getting ridiculous and downright comical here.

**Comment by TurkeyMan** [comment]
> The part where it says -std=c++98

See, my reading is that you're asking the compiler to compile c++98 code, and the D compiler doesn't build C++ at all! This is contrary to the behaviour of other compilers where they do exactly what you expect; they interpret the given source file as the language specified.

And then there's the issue; what if we want to support `-std=d2020`? We've already taken the argument for a weird and surprising use case.

**Comment by TurkeyMan** [comment]
We're not making a statement about the language here, the language is completely unaffected by this option. `-std` specifies a language dialect, that's what it means to people.
What we're specifying is micro-level control of a very niche feature (backend conformance to a particular C++ ABI). `-std` does not suggest anything like that to me.

**Comment by TurkeyMan** [comment]
@WalterBright Surely you have all the evidence you need that people are surprised and mystified by the application of the `-std` option as you suggest... think of something else that you like. The evidence that people don't find your argument intuitive is overwhelming.

**Comment by thewilsonator** [comment]
>> What part of -std= says c++ to you?
> The part where it says -std=c++98

I don't know what your thought processes are doing at this point, but I've frankly lost interest.
 
You have 3 days to come up with a name that captures the sentiment `foreign-language-compatibilty=foo-version-42`.

**Comment by TurkeyMan** [comment]
@WalterBright added insight: https://github.com/dlang/dmd/pull/9214#issuecomment-452088899

If we're gonna change it, `-cppstd` to match the `__traits` is looking reasonable.

**Comment by WalterBright** [comment]
> my reading is that you're asking the compiler to compile c++98 code

How does `-stdc++=c++98` differ?

> I don't understand this claim; what if we want to support -std=d2020

How is that a problem in any way? (Note that gcc and c++ do this with `std=c99` and `std=c++98` switches.)

> -std does not suggest anything like that to me.

Why does `-stdc++` suggest that to you?

> Surely you have all the evidence you need that people are surprised and mystified by the application of the -std option

Surprised and mystified? That's not my suggestion at all. My observation is having `c++` twice is adds no value and hence looks daft. The rationales defending `-stdc++=c++98` have not yet explained why `c++` is needed twice.

**Comment by WalterBright** [comment]
> I don't know what your thought processes are doing at this point

It's straightforward. There is no need for `c++` to be there twice, and gcc/g++ uses the same switch syntax I propose, so there's clearly not a problem with it.

**Comment by WalterBright** [comment]
Hmm, how do I get this branch into my local repo so I can fix it? `git pull origin revert-9203-revert-9199-std-switch` did not work.

**Comment by wilzbach** [comment]
> Hmm, how do I get this branch into my local repo so I can fix it? 

```
git fetch upstream
git checkout revert-9203-revert-9199-std-switch
```

**Comment by TurkeyMan** [comment]
> How does -stdc++=c++98 differ?

I actually hate that too. It doesn't read well to me either, but at least it's clear that it's not the accepted flag to specify the compilers language dialect.

> > I don't understand this claim; what if we want to support -std=d2020

> How is that a problem in any way? (Note that gcc and c++ do this with std=c99 and std=c++98 switches.)

because if you want to use `-std` to specify `-std=d2020`, where do you ask for the `extern(C++)` abi conformance?

> Why does -stdc++ suggest that to you?

`-cppstd` reads "choose the c++ standard" to me. i don't like `-stdc++` either, that kinda says "choose the standard c++", which kinda reads like nonsense, but I just can't care enough to force a change, just as long as it's NOT `-std`.

gcc/g++ uses `-std` to specify the language dialect that the compiler will conform. that is absolutely *NOT* what is going on here. and it's also something we may want in the future, and should reserve.

you have overwhelming evidence that every person who has weighed in finds your perspective confusing... are you really saying all of our intuitions on this matter are wrong? even if so, and your intuition is superior, what we demonstrate is that the masses have feeble minds that can't see it the same way as you here.

**Comment by wilzbach** [comment]
And if you haven't defined `upstream` yet:

```
git remote add upstream git@github.com:dlang/dmd.git
```

**Comment by TurkeyMan** [comment]
> It's straightforward. There is no need for c++ to be there twice, and gcc/g++ uses the same switch syntax I propose, so there's clearly not a problem with it.

`-std` chooses the frontend language, and DMD **does not compile C++ code of any version**. this has nothing to do with choosing a language dialect for the compiler, which is specifying the `extern(C++)` ABI conformance, which is a niche side matter, and needs an option that makes that clear.

**Comment by TurkeyMan** [comment]
I'm going to presume that everybody here would support a change to `-cppstd` such that it matches the traits; would you support that?

**Comment by WalterBright** [comment]
> because if you want to use -std to specify -std=d2020, where do you ask for the extern(C++) abi conformance?

`-std=d2020`, `-std=c++98`, `-std=python3` do not conflict with each other, and can happily coexist on the same command line at the same time and will have the obvious meaning.

`-std=c++98` and `-std=c++14` obviously conflict, and by convention the last one rules.

> that kinda says "choose the standard c++", 

As does `-stdc++=c++98` so that's an irrelevant point.

> gcc/g++ uses -std to specify the language dialect that the compiler will conform. that is absolutely NOT what is going on here.

What about `-stdc++=c++98` is any different? That is the crux of our disagreement - WHY is it different?

**Comment by WalterBright** [comment]
> a change to -cppstd

It has the same problem with specifying C++ twice in the same switch. It also says `std` which you object to for implying D will compile standard C++.

**Comment by WalterBright** [comment]
@wilzbach Thank you, I did that, and checked it out. Made changes:
```
git checkout revert-9203-revert-9199-std-switch
git rebase master
... fix cpp11.d test case ...
git commit --amend -a
git push -f origin revert-9203-revert-9199-std-switch
```
and the revision does not show up here???

**Comment by TurkeyMan** [comment]
> > that kinda says "choose the standard c++",

> As does -stdc++=c++98 so that's an irrelevant point.

Umm... it's like you didn't read my comment, or took the opposite meaning from what was intended.
I read a strong difference between "choose the c++ standard" and "choose the standard c++". The forer is what I want to do, the latter doesn't really make sense. It reads like it doesn't even take an argument.

> What about ~`-stdc++=c++98`~ `-cppstd=c++98` is any different? That is the crux of our disagreement - WHY is it different?

Because it's supplying the C++ standard used by the niche `extern(C++)` subset, and it's NOT asking for a language that the frontend should presume the code it's about to compile is written in. `-std` says something about the language we're compiling, and this option has NO AFFECT on the source language at all.

Consider GDC/LDC. I think the only reasonable output for the invocation:
`gdc -std=c++11 blah.d`  would be the same error that's already emit when you supply a mismatching language dialect to `-std`:
```
> g++ -std=c99 test.cpp
error: command line option ‘-std=c99’ is valid for C/ObjC but not for C++

> gcc -std=c++11 test.c
error: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
```
I expect:
```
> gdc -std=c++11 test.d
error: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for D
```

**Comment by TurkeyMan** [comment]
```
> gdc -std=d2020 -cppstd=c++11 test.d
```
I think this is intuitive to anyone that looks at it.
If you wanna go super-explicit:
```
> gdc -std=d2020 -extern-cpp-std=c++11 test.d
```
But I feel that's going too far.

**Comment by wilzbach** [comment]
> @wilzbach Thank you, I did that, and checked it out. Made changes:
>
> and the revision does not show up here???

Did you try pushing to `upstream`?

```
git push -f upstream revert-9203-revert-9199-std-switch
```

**Comment by WalterBright** [comment]
> I read a strong difference between "choose the c++ standard" and "choose the standard c++"

The switch reads: "**choose the standard C++ 98**" vs "**choose the standard C++ C++ 98**". Nobody ever says or writes the latter.

**Comment by TurkeyMan** [comment]
Okay, you're referring to `-stdc++` again, which I don't care for; let me again rephrase your criticism:

> The switch reads: "choose the standard C++ 98" vs "choose the C++ standard = 'C++ 98'".

The first suggests you're asking the compiler to do something it literally doesn't do, and the second reads perfectly to me!

**Comment by WalterBright** [comment]
> The first suggests you're asking the compiler to do something it literally doesn't do, and the second reads perfectly to me!

I'm baffled that you think it implies anything different.

**Comment by TurkeyMan** [comment]
> I'm baffled that you think it implies anything different.

`-std` chooses the source language. I'm baffled that you can't seem to accept that basic reality.

Telling the compiler to build the source as C++ code is not an instruction I expect to give the D compiler, and if I saw it written, I would be confused.
The existing error messages for mismatching `-std` specification are very clear, and make perfect sense, and there's no reason we should deviate from the established expectation.

**Comment by TurkeyMan** [comment]
> No, it chooses what standard to conform to. There are lots of standards a compiler for language X may wish to conform to, and having a -std=xxxx can be used for all of them, and there's no particular implication those mean source language.

Have you ignored all my posts?

I'll paste a third time:
```
> g++ -std=c99 test.cpp
error: command line option ‘-std=c99’ is valid for C/ObjC but not for C++

> gcc -std=c++11 test.c
error: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
```
Your argument is demonstrably false.

> Furthermore, -cppstd or -stdc++ therefore doesn't imply changing the source language is quite a stretch.

I don't think I understand this comment?
This option *doesn't* imply changing the source language. This option has no affect on the source language, and that's the point.

> I don't believe you would be any more or less confused by a -cppstd switch.

Okay, so `-extern-cpp-std`? Are we behind that? I'm in.

> As an aside, sometimes people buy Digital Mars C++ because they want to get into programming. They contact me for help, and they clearly do not know what a directory is, what a file is, or what the command prompt is. I just refund their money. You can't help someone learn algebra if they don't understand arithmetic.

I don't know what to take from that anecdote.

Look, I'm done here, I can't make my case stronger. `-std` has a well-established meaning (including error conditions), and it's something very different than what our feature here does; therefore, it seems objective that it's the wrong way to express this feature.

You have 2 choices; use your BDFL powers to change it as you like, and you will piss everyone off, and cause GDC/LDC to do something different anyway (it's not like there's much uniformity between DMD and the other compilers command lines anyway), or choose something that everyone can agree on.

**Comment by TurkeyMan** [comment]
Rather than wasting all of our time, help me with real problems:
https://github.com/dlang/druntime/pull/2446

Our build farm is terribly out of date.
That OSX machine doesn't build, which seems like a simple problem.
On a larger scale, I can't test anything that relies on C++14 or C++17, because all the C++ compilers are out of date.
I'm wasting probably *weeks* of my life randomly pushing to CI and hoping things work, when I'm really just fighting against misconfiguration (or, old configuration).

**Comment by WalterBright** [comment]
> Your argument is demonstrably false.

For g++, sure. I would expect g++ to not compile C code.

> This option doesn't imply changing the source language.

Why not? What about `-cppstd=c++98` does not imply changing the source language?

> I don't know what to take from that anecdote.

There's a certain level of knowledge expected of a programmer, and one is that a D compiler compiles D code, and if he is actually confused, he can always check the man page.

> I can't make my case stronger.

I know. I think it's painfully weak - somehow adding "c++" to the string "std" means it's not about implementing the C++ Standard?

> You have 2 choices

I choose (3), convincing you that `-std=c++98` does the job in a short, simple, unambiguous, straightforward way. Adding in another `c++` adds no value and looks like we don't know what we're doing.

**Comment by thewilsonator** [comment]
> `-std=foo42`

Bzzzzzzt.

> Okay, so `-extern-cpp-std`? Are we behind that? I'm in.

I quite like that and, tbh if it shuts this debate up, I'd be fine with just `-extern-std=c++11`. @WalterBright ?

**Comment by WalterBright** [comment]
> Please help me with my other problems...

@braddr and @wilzbach can help you with the build farm C++ compiler(s).

**Comment by WalterBright** [comment]
> just -extern-std=c++11. @WalterBright ?

Not my fave, but it does remove my major objection, so I can go with that.

**Comment by Pulgovisk** [comment]
> 
> 
> > I don't know what your thought processes are doing at this point
> 
> It's straightforward. There is no need for `c++` to be there twice, and gcc/g++ uses the same switch syntax I propose, so there's clearly not a problem with it.

Why not `-cppstd=14`, `-cppstd=17`, `-cppstd=gnu11`?
If we need this for some other external ABI, we can just add another command line swich, like `-cstd=11`

**Comment by wilzbach** [comment]
> > Please help me with my other problems...
> 
> @braddr and @wilzbach can help you with the build farm C++ compiler(s).

We haven't been able to reach @braddr via GitHub for several months and I don't have any access to the auto-tester. In fact, I proposed to replace it fully with Buildkite, but that was rejected as the DLF would then need to spend some $$$ on servers.

That being said the error that I can see:

```
Test runnable/cpp11.d failed.  The logged output:
/home/braddr/sandbox/at-client/pull-3474924-FreeBSD_64_64/dmd/generated/freebsd/release/64/dmd -conf= -m64 -Irunnable -stdc++=c++11  -fPIC -L-lstdc++ -L--no-demangle  -odgenerated/runnable -ofgenerated/runnable/cpp11_0  runnable/cpp11.d generated/runnable/cpp11.cpp.o 
Error: unrecognized switch '-stdc++=c++11'
       run 'dmd -man' to open browser on manual


==============================
Test runnable/cpp11.d failed: expected rc == 0, exited with rc == 1
```

Comes from a new test which has been added in the meantime and uses the `-stdc++` flag.
You need to rebase with `upstream/master` to see this file locally. I just did this for you.

**Review by thewilsonator — CHANGES_REQUESTED** [review]
`-extern-std=c++NN`

**Comment by jacob-carlborg** [comment]
> We haven't been able to reach @braddr via GitHub for several months and I don't have any access to the auto-tester.

He did reply on the forums [1] recently.

> In fact, I proposed to replace it fully with Buildkite, but that was rejected as the DLF would then need to spend some $$$ on servers.

Why can't we repurpose the existing auto-tester machines? I don't think Brad owns all of them. I know that Steven owns at least one of them.

[1] https://forum.dlang.org/post/mailman.6319.1546927753.29801.digitalmars-d@puremagic.com

**Comment by WalterBright** [comment]
Please move the discussion about the build machines elsewhere, it is OT for this PR. It's already on the n.g., where it is on topic.

**Comment by WalterBright** [comment]
@wilzbach ok that worked, thanks! though I have no idea why `upstream` should be used instead of `origin`, and it asked me to approve my fingerprint again.

**Comment by thewilsonator** [comment]
Please give this PR a title and commit description that reflects what it does ;) (i.e. nothing to do with reversion).

**Comment by jacob-carlborg** [comment]
> @wilzbach ok that worked, thanks! though I have no idea why upstream should be used instead of origin

The convention is to have `upstream` point to `http://github.com/dlang/dmd` and `origin` to your fork.

**Comment by TurkeyMan** [comment]
... you know, I'm still not particularly happy with this.
`-extern-cpp-std` is preferable. The option name has poor relationship to the thing it affects.
Why did you feel `-extern-std` was better? It could be anything now...

**Comment by thewilsonator** [comment]
None of us are, but I'm sick of dealing with this circus of PRs wasting time/CI. Blame Walter.

**Review by andralex — APPROVED** [review]
Let's get this in and spend time on productive endeavors. Thanks!

**Comment by thewilsonator** [comment]
Now one of the documentation is out of sync.

**Comment by WalterBright** [comment]
> Now some of the documentation is out of sync.

I don't know which documentation you're referring to, but PR fixes are welcome!

**Comment by thewilsonator** [comment]
Some of @wilzbach's recent ones, don't have time to look at the moment.

**Comment by wilzbach** [comment]
They haven't been merged yet. I'll rebase them tomorrow.

**Comment by thewilsonator** [comment]
Ahh, thanks.

**Pull request merged**
