### PR TITLE
Issue 12929 - Empty union followed by field causes ICE due to offset of 0.

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=12929

@WalterBright If I'm not mistaken, empty anonymous struct/union does not have to have 1 byte size in C11.

### CODE REVIEW

**Comment by ibuclaw** [comment]
> Why? With this code:

ISO C99 doesn’t support unnamed structs/unions

**Comment by ibuclaw** [comment]
> The idea is that the equivalent C++ declaration to a D declaration should be ABI compatible.

However C and C++ disagree on what the ABI should be!

**Comment by ibuclaw** [comment]
Ping on this.  Looking again at the pr, I think we should stick to C++ compatibility over C.

The only argument for being compatible with C is if `extern "C"` produces a different layout.  It should be trivial to support different layouts based on extern linkage.

However, this is such an oddball corner case, I doubt it really matters if we aren't compatible with C here.  (I'm sure that I would have come across a bug report in g++/gcc if it was really an issue for them)

**Comment by JinShil** [comment]
The test cases for this issue pass.  See https://run.dlang.io/is/gnrWgZ

**Comment by JinShil** [comment]
Closing this as the original issue has been resolved.  An issue has been created at https://issues.dlang.org/show_bug.cgi?id=18008 to document the C/C++ compatibility concerns.

**Pull request closed without merging**
