### PR TITLE
parse: refactor logic to check STC conflicts

### PR DESCRIPTION
**Pull request by ljmf00**
This patch removes duplicate code to check for STC conflicts for some STC
groups.

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Review by Geod24 — CHANGES_REQUESTED** [review]
Honestly, while it does reduce the code size, I don't see how it makes the code simpler to follow, so IMO not an improvement. However, improving those error messages (see what's done above for `in` / `scope` / `const` would be welcome.

**Comment by ljmf00** [comment]
> Honestly, while it does reduce the code size, I don't see how it makes the code simpler to follow, so IMO not an improvement.

This can reduce even more the code size for upcoming attributes like `throw`/`nothrow`, and possibly in the future attributes like `pure`/`impure` or `@nogc`/`@gc`, deduplicating 6 times the same code. This change was motivated by the implementation of DIP 1029.

Also making this logic clearer can indeed improve readability. If the inner function name is not self-explanatory enough we can consider adding a comment explaining the sequence.

> However, improving those error messages (see what's done above for `in` / `scope` / `const` would be welcome.

Improving the error message can also be generic enough and more concise with the same code for STC groups. Something like:
```
attribute `%s` is conflicting with attribute `%s`
```

This can be achieved by intersecting the original STC group with the added one and using `AST.stcToString`. I can add that error message improvement in another PR and prove the point of this refactoring.

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
> Something like: [...]

Stating the conflict is a start, but telling the user what to do is pretty useful. That's why I think this refactoring is going to be undone if someone wants to actually improve the message, e.g. by using `errorSupplemental` to inform the user of what the attributes mean.

**Comment by RazvanN7** [comment]
@Geod24 Wouldn't adding an error supplemental in `checkConflictStcGroup` stating something along the lines of "`%s` and `%s` cannot be applied simultaneously, delete one or the other"? Or would you like to have an error message that explains both of the attributes? If so, I guess that a function can be created that explains the problem for each faulty combination of attributes.

**Comment by RazvanN7** [comment]
ping @Geod24

**Comment by RazvanN7** [comment]
@Geod24 I will add the `72h - no objection merge` .

**Comment by Geod24** [comment]
@RazvanN7 : Error message should ideally tell you how to fix the error (if they can). That's what I went with for `in`.
I guess in this case there's no obvious way to signal to the user what to do. I still believe the code is not better, but if it helps with future changes, let's go ahead.

**Pull request merged**
