### PR TITLE
Fix Issue 17646 - dmd segfaults on missing [tuple] foreach body in import

### PR DESCRIPTION
**Pull request by UplinkCoder**
see  #6992

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@wilzbach can you set the auto-merge on this ?

**Comment by UplinkCoder** [comment]
@andralex merge please :)

**Comment by braddr** [comment]
Lacks a unit test, so not ready for a merge.  Also, not sure that this fix is correct.  It should have almost certainly failed earlier than getting down to this block of code.  Isn't it papering over an ice on invalid by just turning it into accepts invalid?

**Comment by UplinkCoder** [comment]
It does not accept it.
Since in this situation we will generate an error regardless.

**Comment by ZombineDev** [comment]
@UplinkCoder in any case, each bug fix needs a test case to prevent regressions in the future. In this case we need an entry in `test/fail_compilation`.

**Comment by wilzbach** [comment]
> @wilzbach can you set the auto-merge on this ?

Thanks a lot for pointing out the leak of a test @braddr @ZombineDev - in addition I am sadly not very familiar with the DMD codebase, so I wouldn't merge this.
Besides at least at Phobos we try to keep non-trivial PRs open for at least a day 😉

**Comment by yebblies** [comment]
@UplinkCoder Why can't you test this with the test case from the bug report?  This patch appears to be fine but unless there's a very good reason it should come with a test case, since this path is obviously not covered by the existing tests.

**Comment by MartinNowak** [comment]
5 ppl. and noone adding the test from Bugzilla?

**Review by MartinNowak — APPROVED** [review]

**Pull request merged**
