### PR TITLE
Don't compile runnable/testptrref_gc.d with -lowmem

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Maybe this will resolve the missing import.
The file is present as it sometimes fail on a subsequent run

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Comment by rainers** [comment]
Compiling with -lowmem is the point of the test, it is otherwise covered by testptrref.d.

@MoonlightSentinel Win64 had the same/similar issue, solved (?) by raising the host compiler version (https://github.com/dlang/dmd/pull/11531). Can we do it for OSX, too?

**Comment by rainers** [comment]
BTW: LDC is seeing similar issues, even without -lowmem, but also on CirrusCI/Mac: https://github.com/ldc-developers/ldc/issues/3370

**Comment by MoonlightSentinel** [comment]
> Compiling with -lowmem is the point of the test, it is otherwise covered by testptrref.d.

I know, this was just a shot in the dark because of the earlier problems related to `-lowmem`. IIRC there was a run failing after running multiple permutations.

**Comment by MoonlightSentinel** [comment]
Similar failures occurred without `-lowmem`.

**Pull request closed without merging**
