### PR TITLE
add driverParams to parseCommandLine()

### PR DESCRIPTION
**Pull request by WalterBright**
globals bad

### CODE REVIEW

**Review by thewilsonator — COMMENTED** [review]
Looks fine to be , just ccing @ibuclaw and @kinke to make sure this isn't too annoying for LDC/GDC.

**Comment by WalterBright** [comment]
I don't know what Iain and Martin need, but I do know that using globals like that impairs using DMD as an LSP library.

**Review by thewilsonator — APPROVED** [review]
I was thinking I was in a different part of the code base. This code is versioned out in LDC and I presume GDC.

**Comment by ibuclaw** [comment]
> I don't know what Iain and Martin need, but I do know that using globals like that impairs using DMD as an LSP library.

No library is going to use the main or mars modules.

**Pull request merged**
