### PR TITLE
14831 - Each function local symbols should have unique mangled name

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14831

Current ABI specification does not explain anything about the mangling scheme for function local symbol, but if we need to update the spec page, it would be:

```
QualifiedName:
    SymbolName
    SymbolName QualifiedName
    SymbolName AnonScopeName QualifiedName    // new

AnonScopeName:    // new
    Number __S Name
```

### CODE REVIEW

**Comment by yebblies** [comment]
`num` is a very generic name, should it be called `scopeNum` or something more descriptive?

Will static variables etc inside extern(C/C++) functions work after this change?

**Comment by 9rnsr** [comment]
> num is a very generic name, should it be called scopeNum or something more descriptive?

Renamed to `localNum`.

**Comment by 9rnsr** [comment]
> Will static variables etc inside extern(C/C++) functions work after this change?

It was not in my head entirely. Current dmd implementation seems not considered well about the linkages of function local symbols. For example, `DeclarationExp::semantic` will ignore the prefix `extern(linkage)` attribute excepting for variables. We should fix such the bugs first.

Therefore I removed the last commit. Then, I'll left it as [issue 3031](https://issues.dlang.org/show_bug.cgi?id=3031).

**Comment by 9rnsr** [comment]
Rebased on master, and ready for ddmd.

**Comment by yebblies** [comment]
What's with the renaming commit?

**Comment by 9rnsr** [comment]
It's for the errors in Travis CI build.

https://travis-ci.org/D-Programming-Language/dmd/jobs/77910680

```
mtype.d(4364): Error: declaration ddmd.mtype.TypeArray.dotExp.fd is already defined in another scope in dotExp
statement.d(2764): Error: declaration ddmd.statement.ForeachStatement.semantic.fdapply is already defined in another scope in semantic
```

**Comment by yebblies** [comment]
So those are new errors detected by this PR?  I thought these errors caused link failure if unchecked, why weren't they failing before?

**Comment by 9rnsr** [comment]
Yes, it's new errors.

This PR does not emit unique numbers for static local variables, so they will have un-numbered mangled names.
On the other hand, this PR is reusing `localsymtab` to detect same name local symbols. But it can store only one previous symbol per entry.
If a function contains two or more static local variable, the logic cannot detect those duplication.

To keep rejection of duplicated static local variables, a static variable is *conservatively* forced to be unique from any other function local symbols.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Auto-merge toggled off

**Comment by yebblies** [comment]
I just took another look and eg `reverseName` does not appear to be declared in more than one place.  Why is it being renamed?  Did I miss a declaration?

**Comment by 9rnsr** [comment]
Read my previous comment.

**Comment by yebblies** [comment]
So, a static variable cannot have the same name as a non-static variable in the same function?  I don't think this is acceptable.

**Comment by andralex** [comment]
I'll close this - if @9rnsr or anyone else wants to work on it please reopen.

**Pull request closed without merging**
