### PR TITLE
fix issue 14811 : allow to exclude current directory from search path in dmd

### PR DESCRIPTION
**Pull request by timotheecour**
dmd implicitly adds current directory to search path, causing trouble when user has both foo/fun1.d and fun1.d and cwd=foo. This fixes this by adding a flag -exclude_cwd_from_imports.

Reduced use case:
see https://github.com/timotheecour/dsnippet/tree/master/bug_14811

make
..//main.d(3): Error: module foo.fun1 from file fun1.d conflicts with another module fun1 from file ..//foo/fun1.d

With my modification (adds a flag -exclude_cwd_from_imports):
make with_flag
# works

See also https://issues.dlang.org/show_bug.cgi?id=14811

### CODE REVIEW

**Comment by schuetzm** [comment]
Service: https://issues.dlang.org/show_bug.cgi?id=14811

Can you explain why this is useful/needed?

Also, please use a more descriptive commit message than "_".

**Comment by timotheecour** [comment]
Done

**Comment by schuetzm** [comment]
@timotheecour It seems you haven't pushed your changes... Depending on how you did the changes, you probably need to use `git push -f`.

**Comment by timotheecour** [comment]
amended commit message; I am seeing the changes now

**Comment by ibuclaw** [comment]
@timotheecour - in sore need of rebasing here.  Solution doesn't really seem very appropriate though.

**Comment by JinShil** [comment]
I think I would prefer that the current working directory was not hard coded in the compiler, but rather included by default as `-I.` in the dmd.conf file.

**Comment by JinShil** [comment]
@timotheecour Should we close this?

**Comment by JinShil** [comment]
This PR is awfully old and doesn't seem to have much support.  Furthermore, queries to the author have gone unanswered, so I'm assuming this PR is abandoned. 

I'm closing this for now;  it can always be reopened or resubmitted.

**Comment by ibuclaw** [comment]
Couple of notes.
1. Seems like the intent was to implement the equivalent of the (deprecated) `gcc -I-`.
2. I think you could get around this issue using the existing `-mv` switch, the bug in question is toeing the line between what should be considered compilable or intentional fail anyway.

**Pull request closed without merging**
