### PR TITLE
iasmdmd: use string switch on asm_reg_lookup

### PR DESCRIPTION
**Pull request by ljmf00**
This patch use a string switch instead of manual for look on a static immutable
array. String switches can benefit from jump table optimization, especially for
quite big arrays.

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by thewilsonator** [comment]
Looks like cirrus still builds with old GDC that doesn't have `static foreach`

**Comment by ljmf00** [comment]
> Looks like cirrus still builds with old GDC that doesn't have `static foreach`

Should this be updated or is it part of a bootstrap step?

**Comment by ibuclaw** [comment]
9.4 is the baseline for bootstrapping, so no static foreach in the compiler just yet.

**Comment by ljmf00** [comment]
> 9.4 is the baseline for bootstrapping, so no static foreach in the compiler just yet.

Ok, this can be done with a mixin tho.

**Comment by WalterBright** [comment]
I'm sorry, but this change makes the code far harder to read and understand.

I doubt this is worth speeding up, as it's pretty rare to even use the inline assembler, let alone use it for more than a handful of instructions.

But if one did desire to speed it up, the best way would be to use a simple hash table. Or use Id's like are used everywhere else in DMD.

**Comment by ljmf00** [comment]
> I'm sorry, but this change makes the code far harder to read and understand.
> 
> I doubt this is worth speeding up, as it's pretty rare to even use the inline assembler, let alone use it for more than a handful of instructions.
> 
> But if one did desire to speed it up, the best way would be to use a simple hash table. Or use Id's like are used everywhere else in DMD.

I totally understand your point. This ended up being utterly complex to implement due to bootstrapping restrictions, as `static foreach` is not available. I'm going to close this.

**Pull request closed without merging**
