### PR TITLE
clone.d for -> foreach

### PR DESCRIPTION
**Pull request by John-Colvin**
Having done this I now feel like it wasn't really worth the bother, especially because of the scary potential problems where the iterable is being modified...

but maybe others disagree, so here's some `foreach`s.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
@John-Colvin You're right to be disturbed by this. It'll have to be reverted.

**Comment by WalterBright** [comment]
Ack I was too quick. This one's ok. How do I cancel a PR?

**Comment by thewilsonator** [comment]
>  cancel

More descriptions please. Also you opened a PR to revert the other one no this one.

**Comment by WalterBright** [comment]
I pushed the Revert button, and it opened a screen with a PR. There's no button to stop it.

**Comment by WalterBright** [comment]
Only the create PR button.

**Comment by thewilsonator** [comment]
If that's the screen I think it is then its the diff compare screen, just close the browser tab.

**Comment by WalterBright** [comment]
Ah, ok. Thanks!

**Pull request merged**
