### PR TITLE
Preserve the `__debug_line` section on macOS in the final executable

### PR DESCRIPTION
**Pull request by jacob-carlborg**
The linker on macOS will remove any debug info, i.e. every section with the `S_ATTR_DEBUG` flag, this includes everything in the `__DWARF` section. By using the `S_REGULAR` flag the linker will not remove this section. This allows to get the filenames and line numbers for backtraces from the executable.

Normally the linker removes all the debug info but adds a reference to the object files. The debugger can then read the object files to get filename and line number information. It's also possible to use an additional tool that generates a separate `.dSYM` file. This file can then later be deployed with the application if debug info is needed when the application is deployed.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
I've not included a changelog entry here because it's not a user facing change.

**Review by WalterBright — APPROVED** [review]

**Comment by WalterBright** [comment]
Please add your opening comment in as a comment in the code.

**Comment by jacob-carlborg** [comment]
> Please add your opening comment in as a comment in the code.

It's already in the commit message, do you want it in the code as well?

**Comment by jacob-carlborg** [comment]
Is the failing DAutoTest related to this change? Nothing else fails.

**Comment by wilzbach** [comment]
Yeah the error is

```
Test the D Language specification
../dmd/generated/linux/release/64/dmd -run tools/dspec_tester.d --compiler=../dmd/generated/linux/release/64/dmd
---
void main() {
import std.stdio;
        struct S { int x; float y; }

        int foo(S s) { return s.x; }

        foo( S(1, 2) ); // set field x to 1, field y to 2
        
}
---
/usr/bin/ld: error in __stdin.o(.eh_frame); no .eh_frame_hdr table will be created.
/usr/bin/ld: __stdin.o: invalid string offset 1096055152 >= 528 for section `.strtab'
/usr/bin/ld: unknown operator '(' in complex symbol
/usr/bin/ld: final link failed: Invalid operation
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```

But it's unrelated to this PR.

**Comment by wilzbach** [comment]
> Is the failing DAutoTest related to this change? Nothing else fails.

-> https://github.com/dlang/dlang.org/pull/2345

**Comment by jacob-carlborg** [comment]
Everything is green.

**Comment by jacob-carlborg** [comment]
Ping, this is pretty trivial.

**Comment by jacob-carlborg** [comment]
@wilzbach @JinShil ping

**Review by JinShil — APPROVED** [review]

**Comment by WalterBright** [comment]
Suggestion to revert this:

https://www.digitalmars.com/d/archives/digitalmars/D/Not_Working_on_the_Mac_369782.html#N369787

**Comment by jacob-carlborg** [comment]
@WalterBright 

There are a couple of options:

* You can choose to revert this. Then filenames and line numbers will not be available in stack traces of exceptions (unless LDC has upstreamed its changes in druntime. The changes require an external tool, shipped with Xcode, which might not be available when an application is deployed)
* Try to fix the alignment (don't know if that's possible)
* Revert this change but duplicate the debug info in a custom section. I don't know if the linker will strip custom sections with the `S_ATTR_DEBUG` attribute

**Comment by WalterBright** [comment]
@jacob-carlborg  I'd prefer to fix the problem rather than revert this. Except nobody seems to know what to do about it.

**Comment by WalterBright** [comment]
Can you try fixing the alignment and see if it works?

**Comment by jacob-carlborg** [comment]
> Can you try fixing the alignment and see if it works?

Unfortunately that's out of my league. It would be more suitable for someone that actually knows the compiler.

**Pull request merged**
