### PR TITLE
Revert "remove optabgen.d"

### PR DESCRIPTION
**Pull request by Geod24**
Reverts dlang/dmd#10221

Let's see what SemaphoreCI says.
(I wish Github opened revert branches in forks...)

### CODE REVIEW

**Comment by marler8997** [comment]
What's the reason for the revert?

**Comment by rainers** [comment]
> What's the reason for the revert?

master failing to build on semaphoreci: https://semaphoreci.com/dlang/dmd-2/branches/master

**Comment by Geod24** [comment]
The PR broke SemaphoreCI. Master is currently red: https://semaphoreci.com/dlang/dmd-2
But reverting this PR fixes it.
CC @thewilsonator

**Comment by marler8997** [comment]
Shoot, now I'm going to have to rebase #10217 after already rebasing it from #10221.  Then if this gets fixed and re-merged, then I"ll have to rebase/rework again.  Is it possible to try to fix the failure before reverting?

**Comment by Geod24** [comment]
You can just use `git reflog` (and Github might still show the commits).
In any case, having the reverter fix the bug is a bad trend: it shift the burden of work to the person that finds the bug, not the one that creates the bug.

**Comment by marler8997** [comment]
> You can just use git reflog (and Github might still show the commits).

Sure but I've made changes since the rebase so my original commit is no longer valid.  It's not a big deal, I'm just letting you know that this is causing extra work.

> In any case, having the reverter fix the bug is a bad trend: it shift the burden of work to the person that finds the bug, not the one that creates the bug.

I'm not worried about trends.  You have every right to revert the commit, but that doesn't mean we can't try to fix it first either.  You don't have a responsibility to fix it of course, I was just asking if it could be easily done.  If not then by all means go ahead with the revert.

**Comment by marler8997** [comment]
Ping @WalterBright, do you want a chance to come up with a quick fix before the change is reverted?  Or should we go ahead with the revert now and fix this later?

**Comment by marler8997** [comment]
Interesting, semaphore is currently with my PR, which has been rebased with the "remove optabgen": https://semaphoreci.com/dlang/dmd-2/branches/pull-request-10212/builds/22

**Comment by marler8997** [comment]
Well I couldn't figure out the cause in the few minutes I spent, so don't hold back on my account.  I'm off to bed.

**Comment by rainers** [comment]
I don't see why removing an usused generator can produce different binaries, but I suspect we hit some threshold producing different code due to something like
https://github.com/dlang/dmd/blob/08c385ce0f18e2d2059f05bee74e3b595f281067/src/dmd/backend/go.d#L351
in the optimizer.

**Comment by rainers** [comment]
Maybe https://github.com/dlang/dmd/pull/10240 helps.

**Comment by rainers** [comment]
> Maybe #10240 helps.

it didn't but #10242 seems to.

**Comment by Geod24** [comment]
Thanks @rainers !

**Pull request closed without merging**
