### PR TITLE
Add Xcode project

### PR DESCRIPTION
**Pull request by jacob-carlborg**
I thought that since we have a Visual Studio project we could have a Xcode project as well. The project contains an extra target, dummy, to support code complete and similar features. Apparently Xcode doesn't support those features for external build systems, aka make. Any new files that are added should be added to the dummy target. One also needs to explicitly set the language for new files since DMD uses .c file extension instead of .cpp.

### CODE REVIEW

**Comment by MartinNowak** [comment]
We need the VS project to build a 64-bit version of dmd under windows.
This doesn't hold true for OSX, and by now the build likely doesn't work any longer, this would be better off in gitignore.

**Comment by MartinNowak** [comment]
Also we're getting getting copycat.
https://github.com/D-Programming-Language/dmd/pull/4379

**Comment by jacob-carlborg** [comment]
The Xcode project uses make with the regular makefile to build the DMD. It doesn't get out of date.

**Comment by MartinNowak** [comment]
> The Xcode project uses make with the regular makefile to build DMD. It doesn't get out of date.

It contains a list with all source files that noone updates. Why not move that to the wiki or just keep it for you?

**Comment by jacob-carlborg** [comment]
The list is not for building and it's not changed often anyway. I will keep it regardless of what you decide. Not sure what there is to put on the wiki. Is it possible to attached files?

**Pull request merged**
