### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by MartinNowak**
- bump VERSION to v2.095.1

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Comment by PetarKirov** [comment]
@jacob-carlborg can you check the DWT CI failure?

**Comment by PetarKirov** [comment]
I think the issue is either that the CI is not using https://github.com/dlang/ci/pull/441, or that it is using it and that causes the problem.

**Comment by Geod24** [comment]
I think we might need to re-trigger the full pipeline to get it to pick up the change, which I just did.

**Comment by jacob-carlborg** [comment]
Has the issue been resolved? I don't have time to look at this right now. If it's not resolved, please feel free to disable DWT.

**Comment by Geod24** [comment]
Yes, it's green now.

**Comment by RazvanN7** [comment]
Auto-merge and all green but issue is still open.

**Pull request merged**
