### PR TITLE
added predefined version D_Warnings

### PR DESCRIPTION
**Pull request by ghost**
when some code is compiled  using dmd and the switches `-w` or  `-wi`, some user-defined warnings can be emitted in a `version(D_Warnings)` block.

It allows to follow the compiler logic, let's say in a static library, for example if something is known to be a bit buggy under certain rare circumstances but is not likely to really happend.

example:

``` D
void foo(A)(A a)
{
    version(D_Warnings) static if (A.sizeof > size_t.sizeof)
        pragma(msg, "this is not usable as an AA key");
}
```

### CODE REVIEW

**Comment by ibuclaw** [comment]
I'm not sure on value of this.

Also, you first need to add ``D_Warnings`` to the predefined versions list to disallow declaring ``version = D_Warnings`` in user code.

**Comment by andralex** [comment]
We need programmatic access to all appropriate flags, so I'm in favor of this.

**Comment by CyberShadow** [comment]
> We need programmatic access to all appropriate flags, so I'm in favor of this.

Even `-O`?

Generally, if a program behaves differently with and without `-O`, it's considered a compiler bug. I'd be inclined to say the same with `-w`.

I think a `pragma(warning, "message...")` would be a better approach.

**Comment by denis-sh** [comment]
Yes, `pragma(warning, "message...")` looks much better.

**Comment by ibuclaw** [comment]
> We need programmatic access to all appropriate flags, so I'm in favor of this.

I seriously doubt that.

**Comment by ibuclaw** [comment]
By the way, what happened to:
1. Toggle on Autotester
2. Adding a file in the testsuite for the change.
3. Bug report!

**Comment by yebblies** [comment]
I agree that `pragma(warning)` would be useful.

**Comment by Geod24** [comment]
Sorry to jump in that late, but as library contributor, I've always wanted `pragma(warning)` and `pragma(deprecated)`.

I can see tons of reasons to misuse a `version` bloc. This might even go unnoticed for some times if the author is using a build tool which enables warnings by default, as `dub` does.
However, `pragma`s are much harder to get wrong...

**Pull request merged**
