### PR TITLE
Use standard names for COFF structs and members

### PR DESCRIPTION
**Pull request by yebblies**
Needed before scanmscoff can be ported to D.

@WalterBright

### CODE REVIEW

**Comment by yebblies** [comment]
All green.

**Comment by yebblies** [comment]
@9rnsr ? =)

**Comment by 9rnsr** [comment]
I found following official information about the "standard names" of each structures and their fields.

- IMAGE_FILE_HEADER
    https://msdn.microsoft.com/en-us//library/windows/desktop/ms680313(v=vs.85).aspx
- IMAGE_SECTION_HEADER
    https://msdn.microsoft.com/en-us/library/windows/desktop/ms680341(v=vs.85).aspx

But I couldn't find more for others...

**Comment by yebblies** [comment]
The big spec is here: http://download.microsoft.com/download/e/b/a/eba1050f-a31d-436b-9281-92cdfeae4b45/pecoff.doc
but not everything is in there, so I just used similar names.

**Comment by 9rnsr** [comment]
OK, make sense.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Comment by WalterBright** [comment]
I was using the original COFF names. Apparently Phobos is the only library undergoing grand renamings.

**Comment by yebblies** [comment]
@WalterBright Reference?  Because Microsoft's documentation seems to think these are the names.

**Comment by WalterBright** [comment]
The book is, I believe, "Understanding and Using COFF", 1988. I used to have 2 copies, and cannot find either of them :-( In any case, using names like f_nscns is not my style of naming things.

**Comment by WalterBright** [comment]
I did find a scan of the old COFF format in my old papers. Yup, those are the names in it.

(ELF is a modernized COFF)

**Comment by yebblies** [comment]
Are those for the ms coff format or the original coff?  Anyway, these names are easier to understand, if a little verbose, and are what ms' current documentation uses.

**Pull request merged**
