### PR TITLE
Fix Issue 10084 - ICE(toir.c) alias template parameter

### PR DESCRIPTION
**Pull request by JinShil**
Revival of #2780

Special thanks to @9rnsr

### CODE REVIEW

**Comment by JinShil** [comment]
So that's why noone reviewed the original...it works for the test case, but breaks other code.  Closing for now.

**Comment by JinShil** [comment]
Reopening per [this comment](https://github.com/dlang/dmd/pull/2780#issuecomment-349751335)

**Comment by andralex** [comment]
@JinShil status?

**Comment by JinShil** [comment]
@andralex This PR fixes the issue it's intended to fix, but causes other code breakage.  Unfortunately, it is beyond my current ability to fix, hence the "Needs Help" tag.  This PR needs someone to take a look at the failures and provide advice, or it needs a new champion.

I already closed it once, but [@rainers suggested we keep it open](https://github.com/dlang/dmd/pull/2780#issuecomment-349751335).  I don't like leaving PRs like this open, so I'm going to put a time limit in place.  Either this PR receives the help it needs in 14 days or I'm going to close it.

**Comment by JinShil** [comment]
This code in this PR is brittle and has gotten too far away from first principles.  It's beyond my current ability to fix and not in my current interest.  I closing this to delegate it back to Bugzilla to find a new champion or to revisit later.

**Pull request closed without merging**
