### PR TITLE
add EX_posix declaration

### PR DESCRIPTION
**Pull request by WalterBright**
Seems like a reasonable thing to do. Will expand its use later.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
Shouldn't it be `EX_POSIX`, to match existing style, and also because it's an acronym and spelt POSIX everywhere (like HTTP).

**Comment by WalterBright** [comment]
I thought about it, but chose lower case to match the other EX bit collections.

**Comment by WalterBright** [comment]
```
++ jq -r .base.ref
parse error: Unfinished JSON term
+ BRANCH=
```
another  irrelevant semaphoreci failure.

**Comment by Geod24** [comment]
It's quite confusing: We have an enum, and bit set that are `enum`. The enum has uppercase name, the bit set do not.
Why not just merge everything in the enum and respect the D style guide ?

**Pull request merged**
