### PR TITLE
fix Issue 17489 - ICE in ddmd/argtypes.d

### PR DESCRIPTION
**Pull request by MartinNowak**
More info on the ICE https://github.com/dlang/dmd/pull/6894#issuecomment-308176723.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Mmh, changing anything in struct resolution can easily introduce new regressions, might not be worth the risk, given that the ICE code fails to parse correctly.
Any other ideas how to resolve this problem?

**Comment by wilzbach** [comment]
> Mmh, changing anything in struct resolution can easily introduce new regressions, might not be worth the risk, given that the ICE code fails to parse correctly.

In particular if the test suite already segfaults:

```
../src/dmd -conf= -m32 -Ifail_compilation -verrors=0   -odgenerated/fail_compilation -ofgenerated/fail_compilation/ice8100_0.o -c fail_compilation/ice8100.d
fail_compilation/ice8100.d(10): Error: no property 'Q' for type 'ice8100.Bar!bool'
fail_compilation/ice8100.d(11): Error: template instance ice8100.Foo!(Bar!bool) error instantiating
fail_compilation/ice8100.d(12):        instantiated from here: Bar!bool
Segmentation fault (core dumped)
```

**Comment by WalterBright** [comment]
Is the failing call to `toArgTypes()` coming from `finalizeSize()` ?

**Comment by MartinNowak** [comment]
> Is the failing call to toArgTypes() coming from finalizeSize() ?

See https://github.com/dlang/dmd/pull/6894#issuecomment-308176723 for an explanation @WalterBright.

**Comment by WalterBright** [comment]
> The root of the problem is that immutable() m_nodes; is a parse error which bumps global.errors and returns a Type.terror already during parseType. This error is later not detected by StructDeclaration::semantic for Path when it runs semantic for all of it's members, b/c it only compares global.errors at the begin and end of StructDeclaration::semantic. Since the error type isn't propagated from the field m_nodes to the struct Path, we make it all the way to finalizeSize of DirectoryChange, where the assertion is triggered when setting the offset for field path. Doesn't happen when the module is part of the compilation, since we eagerly abort on any parse errors.

It strongly looks to me like detecting the error in `toArgTypes()` is the wrong place. The fix should be fixing "the error type isn't propagated from the field m_nodes to the struct Path".

I.e. the error scheme used in dmd is a `poisoning` one, where errors propagate such that any declaration that depends on something that errored is itself marked as erroneous. The same holds for types, statements, and expressions.

**Comment by WalterBright** [comment]
My take on where this fix should be https://github.com/dlang/dmd/pull/6914

**Comment by WalterBright** [comment]
Superseded by https://github.com/dlang/dmd/pull/6914

**Pull request closed without merging**
