### PR TITLE
use strtold_dm when building against VC runtime

### PR DESCRIPTION
**Pull request by rainers**
Replacement necessary due to missing real support in VC.

BTW: Im trying to build ddmd against the MS runtime using a VC project for the backend and a Visual D project for the frontend. I guess that's the only way to get sensible debugging experience on Windows.
I can compile dmd this way now, but the resulting executable does not yet produce code good enough to pass the test suite.

### CODE REVIEW

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by ibuclaw** [comment]
All those uses of real should be replaced with longdouble.  I can see this being a problem for me too.

**Comment by rainers** [comment]
> All those uses of real should be replaced with longdouble. I can see this being a problem for me too.

Here's another problem with longdouble vs real: https://github.com/D-Programming-Language/dmd/pull/5008

**Comment by ibuclaw** [comment]
> Here's another problem with longdouble vs real: #5008

I wouldn't know because I roll my own longdouble :-)

**Pull request merged**
