### PR TITLE
refactor: make functions private where possible in ctfeexpr.d

### PR DESCRIPTION
**Pull request by RazvanN7**
...and delete modifyStructField function since it wasn't used anywhere.

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]
LGTM

**Review by mathias-lang-sociomantic — CHANGES_REQUESTED** [review]
You also need to edit `ctfe.h`

**Comment by RazvanN7** [comment]
@mathias-lang-sociomantic Done. thanks!

**Comment by mathias-lang-sociomantic** [comment]
Ditto squash :(

**Comment by RazvanN7** [comment]
Done

**Review by mathias-lang-sociomantic — APPROVED** [review]

**Pull request merged**
