### PR TITLE
more use of region in dinterpret.d

### PR DESCRIPTION
**Pull request by WalterBright**
Doing it piecemeal so any bugs will be easier to find.

### CODE REVIEW

**Comment by JinShil** [comment]
@WalterBright If you're actively working on a PR, please submit it as a draft pull request.  It will still be tested by the CIs, but we can ignore it in our review queue until it's ready.

**Comment by WalterBright** [comment]
If it's got red Xs, you can ignore it.

**Review by thewilsonator — APPROVED** [review]

**Comment by CyberShadow** [comment]
-5 MB peak heap size when compiling dietbench:
https://perf.dlang.io/#program-dietbench-compile-massif;;1566954007;1567152989

**Comment by Geod24** [comment]
@CyberShadow : How hard would it be to get those stats (or a subset of them) on PRs ?

**Comment by CyberShadow** [comment]
I would like to do that too. I think @maxhaton's SAOC proposal also mentions a CI of some sort.

**Pull request merged**
