### PR TITLE
build.d: rename Dependency to BuildRule

### PR DESCRIPTION
**Pull request by marler8997**
Looking through @MoonlightSentinel 's parallel commit made me realize that the name `Dependency` is confusing enough to warrant a rename.  The word "dependency" usually refers to an object that has a relationship to another object, however, here we are using it to name an object without implying a relationship to any other object.

My comment here shows how this can result in confusing documentation (https://github.com/dlang/dmd/pull/10611#discussion_r353274816)

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
This has a merge conflict.

**Comment by marler8997** [comment]
rebased

**Comment by thewilsonator** [comment]
Hmm, this needs to be rebased again.

**Comment by marler8997** [comment]
rebased again :)

**Pull request merged**
