### PR TITLE
renumber STC values

### PR DESCRIPTION
**Pull request by WalterBright**
Since `printf` does not have a format for `1 << n`, but can print in hex, the values are changed to hex for comparison. Grouped some related ones together for more efficient bit masking. Add some more comments. Switched to Ddoc comments.

### CODE REVIEW

**Comment by WalterBright** [comment]
Adds `toChars(ScopeRef sr)` which is used when debugging code.

**Comment by WalterBright** [comment]
@RazvanN7 Test suite heisenbugs are the only problems here.

**Comment by Geod24** [comment]
I don't think that's an Heisenbug. It's definitely unrelated, but not random:
> /home/runner/dlang/ldc-1.27.0/bin/ldc2: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/runner/dlang/ldc-1.27.0/bin/ldc2)

LDC v1.27.0 was released yesterday. CC @kinke .

**Comment by WalterBright** [comment]
@Geod24 then pull away, me hearties!

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
