### PR TITLE
add changelog entry for @live

### PR DESCRIPTION
**Pull request by WalterBright**
and convert it from ob.md to ob.d

### CODE REVIEW

**Comment by Geod24** [comment]
Thanks! Diff looks nice, going to check the result on DAutoTester

**Review by wilzbach — CHANGES_REQUESTED** [review]
There's no need to convert it back. Markdown is supported even with the .dd extension.

**Comment by Geod24** [comment]
For ref, implemented in https://github.com/dlang/dmd/pull/10586

**Comment by WalterBright** [comment]
What's the point to editing it back to markdown?

**Comment by Geod24** [comment]
Merged because the results look good, and the work to convert it was already done. We should fix the markdown handling so that we don't run into situation where files in `changelog` get ignored tho.

**Comment by rainers** [comment]
It looks broken to me. The sub items in this text are using the same enumeration as the other changelog entries.
IMO the text is rather long for the changelog, I would expect a link to a place where it might also evolve over time, e.g. a PR to the spec.

**Pull request merged**
