### PR TITLE
Issue 3731 - Can implicitly cast an immutable reference to a derived class

### PR DESCRIPTION
**Pull request by yebblies**
Ensure the modifier conversion is valid before allowing an implicit conversion to a base class.

http://d.puremagic.com/issues/show_bug.cgi?id=3731

### CODE REVIEW

**Comment by quickfur** [comment]
This PR may have caused a new problem: https://issues.dlang.org/show_bug.cgi?id=15638

**Comment by yebblies** [comment]
> This PR may have caused a new problem: https://issues.dlang.org/show_bug.cgi?id=15638

?

**Comment by quickfur** [comment]
Yeah, just confirmed with git that this PR causes https://issues.dlang.org/show_bug.cgi?id=15638 .

**Comment by quickfur** [comment]
Originally deleted my comment 'cos I hadn't manage to substantiate it yet, and I just saw how old this was. :-P

**Comment by yebblies** [comment]
FYI this code is most likely correct, and the bug is in the common-type deduction code.  Ie `typeMerge` or `CondExp.semantic` or wherever the seven copies of that code currently live.

**Comment by quickfur** [comment]
Probably this PR just exposed a latent bug in the common-type code, I guess?

**Comment by yebblies** [comment]
IIRC at the time this was merged the common-type code wasn't capable of finding the common type of two arrays of objects at all.

**Comment by quickfur** [comment]
Hmm. Looking at `src/dcast.d:typeMerge`, it does seem to have proper merging of two `const` types into `const`... does `CondExp` actually have copy-pasta code for the conversion?!

**Comment by quickfur** [comment]
Probably will have to step through the code to figure this out... gotta run now, will get back to this later.

**Comment by quickfur** [comment]
Ah, found the point of failure. In `src/dcast.d` at label `Lcc:`, there's a `while(1)` loop that, in the case of classes, walks up the base classes and uses `implicitConvTo` to try to match a common base class. In the case of `const` classes, `implicitConvTo` fails because even though the correct common base class was checked at one point, a `const` derived class cannot implicitly convert to a non-const base class, so it fails to recognize the common base class.

**Comment by quickfur** [comment]
Fixed: https://github.com/D-Programming-Language/dmd/pull/5450

**Pull request merged**
