### PR TITLE
Add namespace handling to cpphdrgen

### PR DESCRIPTION
**Pull request by UplinkCoder**
The test is also included.

The formatting of this feature will be fixed as soon as 
https://github.com/dlang/dmd/pull/10973
can be merged.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@thewilsonator I factored this one out of my bigger dtoh PR.
@TurkeyMan I know you'll like this.

**Review by Geod24 — APPROVED** [review]

**Comment by UplinkCoder** [comment]
buildkite failure is most likely unrelated: 
`std/socket.d(2841): [unittest] Unable to bind socket: Cannot assign requested address`
@CyberShadow can be do something about that. As in not have tests that require a network?

**Comment by CyberShadow** [comment]
Here is the top-level line:
```d
	auto serverPort = server.bind("localhost", 0);
```
It assigns binds to a random port on the loopback interface, which should always be present. The test does not require a network.

As far as I can see, the error could mean two things:
1) The system ran out of ports (possibly due to a port leak in some other program running)
2) The system is misconfigured (e.g. no `localhost` entry in `/etc/hosts`)
3) The system is configured with some security framework which is so strict it does not allow doing standard things such as the above.

However, BuildKite says the problem was that the test timed out, so I'm not sure it is any of the above.

Why is it failing on this pull request all of a sudden?

**Comment by Geod24** [comment]
Seems like the problem was spurious so I just re-triggered the test.

**Pull request merged**
