### PR TITLE
fix Issue 22655 - Disassembler assertion on rdtsc

### PR DESCRIPTION
**Pull request by WalterBright**
This bug is also in obj2asm, so putting it in dmd is paying off in squeezing out these bugs.

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]
LGTM.

Is there any plan to add tests for the disassembler ?

**Comment by WalterBright** [comment]
I added a unit test for this.

**Review by maxhaton — APPROVED** [review]

**Comment by WalterBright** [comment]
How can buildkite be running for 7 and a half hours without finishing?

**Comment by maxhaton** [comment]
Thanks for the fix @WalterBright

**Pull request merged**
