### PR TITLE
dtoh: Emit template aliases as templated using declaration

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Instead of simply skipping the declaration

### CODE REVIEW

**Comment by thewilsonator** [comment]
Please restrict this to C++11 or greater

**Review by thewilsonator — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
Not sure about the WIn64 segfault but it looks like an unrelated (ABI?) bug.

**Comment by MoonlightSentinel** [comment]
Versioned the `dshell` tests for non-Win64

**Comment by thewilsonator** [comment]
This good to go?

**Comment by MoonlightSentinel** [comment]
Yes

**Pull request merged**
