### PR TITLE
fix: Issue 15464 - Template parameter-dependent attributes

### PR DESCRIPTION
**Pull request by Kozzi11**

### CODE REVIEW

**Comment by andralex** [comment]
Related discussion went mostly in the associated issue: https://issues.dlang.org/show_bug.cgi?id=15464

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by JackStouffer** [comment]
@Kozzi11 this deserves a changelog entry, seeing as it's a language change. Could you please add it?

**Comment by Kozzi11** [comment]
@JackStouffer  Yes, I have it on my todo list for tommorow with doc improvments too

**Pull request merged**
