### PR TITLE
lexer: remove some C++ conversion artifacts

### PR DESCRIPTION
**Pull request by WalterBright**
Reboot of https://github.com/D-Programming-Language/dmd/pull/5137

### CODE REVIEW

**Comment by ibuclaw** [comment]
:+1:  once you sort out the build errors.
```
s2ir.c:17:26: fatal error: lexer.h: No such file or directory
```

**Comment by yebblies** [comment]
Can any of this be made private?

**Comment by WalterBright** [comment]
It's got enough diffs for one PR.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
