### PR TITLE
fix Issue 20565 - Local template declarations in different scopes produce…

### PR DESCRIPTION
**Pull request by WalterBright**
… uncaught name collisions

This attempts to solve the problem by adding a sequence number to the mangled name of the colliding symbol.

It uses elements from https://github.com/dlang/dmd/pull/4836

### CODE REVIEW

**Comment by WalterBright** [comment]
Not completely happy with this, so marking as WIP.

**Comment by Geod24** [comment]
@WalterBright : FYI something is broken with `downloads.dlang.org` which means the compiler cannot be installed across multiple CIs. This *might* have to do with the lack of TLS on `downloads.dlang.org`, although I'm not 100% positive. I sent you an email about it a couple days ago, as it's a rather urgent issue regardless.

**Comment by WalterBright** [comment]
@geod24 did you contact Martin Nowak?

**Comment by Geod24** [comment]
> @Geod24 did you contact Martin Nowak?

Good point, I just emailed @MartinNowak .

**Review by RazvanN7 — DISMISSED** [review]
This looks good, however, what happens with nested `extern(C++)` functions?

```d
void main()
{
    {
    	extern(C++) void fun() {}   
    }
    
    {
    	extern(C++) void fun() {}   
    }
}
```

Would this work? Or does the patch only apply to D linkage functions?
Either way, a test should be added for this test case.

**Comment by WalterBright** [comment]
@RazvanN7 made the change.

**Comment by RazvanN7** [comment]
Does this fix Issue 20565? If so, please add a commit saying "Fix Issue 20565 ..."

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Thanks! Auto-merge toggled on.

**Comment by MartinNowak** [comment]
> FYI something is broken with `downloads.dlang.org` which means the compiler cannot be installed across multiple CIs. This _might_ have to do with the lack of TLS on `downloads.dlang.org`, although I'm not 100% positive. I sent you an email about it a couple days ago, as it's a rather urgent issue regardless.

@Geod24 http://downloads.dlang.org is directly hosted on S3, hence there is (was) no simple TLS functionality and we rely on signatures instead.
If you absolutely need, you could use the direct AWS-S3 sub-domain, https://downloads.dlang.org.s3-website-us-west-2.amazonaws.com/.
Seems like the tests ran through, so it doesn't seem like this was the major problem.

**Comment by Geod24** [comment]
> @Geod24 http://downloads.dlang.org is directly hosted on S3, hence there is (was) no simple TLS functionality and we rely on signatures instead.

It actually had  to do with the certificate on dlang.org. Let's Encrypt changed their intermediary and we were not serving it, so validation failed until Jan fixed it (I also worked around it in Github CI). See [the discussion](https://github.com/dlang/dmd/discussions/12123).

> If you absolutely need, you could use the direct AWS-S3 sub-domain, https://downloads.dlang.org.s3-website-us-west-2.amazonaws.com/.

Doesn't work. Bradd also provided me a link which only showed the top level, but the rest gave a 404.

> Seems like the tests ran through, so it doesn't seem like this was the major problem.

`install.sh` and `d-keyring.gpg` were behind a broken TLS certificate for 36 hours, but it eventually got fixed.

**Pull request merged**
