### PR TITLE
[REG2.069] Issue 15781 - Template type deduction failure with same-type variables with different constness

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks, but the auto-merge is currently blocked by the red of Phobos unittest in stable branch.
See also: https://github.com/D-Programming-Language/phobos/pull/4092

**Comment by ZombineDev** [comment]
Will this work with `immutable`, i.e.:
``` 
static assert(is(typeof(foo(ms, is)) == const S));
```
?

**Comment by 9rnsr** [comment]
@ZombineDev Yes, `MODmerge(MODmutable, MODimmutable)` returns `MODconst`.

**Pull request merged**
