### PR TITLE
fix Issue 20893 - [REG 2.087] 32-bit arithmetic goes wrong

### PR DESCRIPTION
**Pull request by WalterBright**
Fix refactoring mistake in https://github.com/dlang/dmd/pull/9722

It's an ugly problem, and should be a priority.

### CODE REVIEW

**Comment by thewilsonator** [comment]
Err, stable...

**Comment by WalterBright** [comment]
> Err, stable...

I follow the directions here exactly. Result is the mess you see :-(
```
mercury~/forks/dmd fix20893> git rebase --onto upstream/stable upstream/master
First, rewinding head to replay your work on top of it...
Applying: fix Issue 20893 - [REG 2.087] 32-bit arithmetic goes wrong
```
Then I do:
https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/

Result: Mess.

So I try:
```
git push -f origin stable
```
which does not help.

I figure I'm missing some obvious, but omitted, step?

**Comment by MoonlightSentinel** [comment]
> ```
> git push -f origin stable
> ```

Pushing stable should be unnecessary, your PR uses the `fix20893` branch, Did you push that branch as well?

**Comment by WalterBright** [comment]
> Pushing stable should be unnecessary, your PR uses the fix20893 branch, Did you push that branch as well?

I followed the directions presented here exactly. It did not say to do anything else like push that branch.

**Comment by Geod24** [comment]
Are your remote up to date ? (`git remote update -p`, I run it so often I have an alias for this).
And as @MoonlightSentinel pointed, pushing to your stable won't help. The syntax is: `git push [-f] $NAME_OF_REMOTE $LOCAL_REF[:$REMOTE_BRANCH]`.

Let me fix that for you.

**Comment by WalterBright** [comment]
This stuff desperately needs to be added to the directions. The directions should be complete.

**Comment by WalterBright** [comment]
Another question:

is `origin` my fork, or is `upstream` my fork?

**Comment by Geod24** [comment]
Here you go. For reference, when `git rebase` is uncooperative, you can also do:
```console
$ git checkout upstream/stable
$ git branch -D fix20893 # Make sure you know the commit before, or `man git-reflog`
$ git checkout -b fix20893 # Gives you a fresh branch off `stable`
$ git cherry-pick 72f110d # The original commit ID
```

In my experience this is easier for people that struggle with `rebase`. But really, [read this](https://git-scm.com/book/en/v2/Git-Branching-Rebasing).

**Comment by thewilsonator** [comment]
run `git remote -v` it will list all the local names for external repository.

**Comment by Geod24** [comment]
@WalterBright : `git branch -v` will tell you which is which. I suspect `origin` is your fork, `upstream` is `dlang/dmd`, as it is the convention (but again, there's nothing preventing you from using different names if you wanted to).

**Comment by WalterBright** [comment]
I don't want to use different names, I want to use the usual conventions as long as I haven't mastered git.

`git branch -v` does not tell me what `origin` and `upstream` are, though `git remote -v` does. Also, why do your instructions not include `git fetch`?

Now, when I do `git remote -v` I get:
```
git remote -v
origin  git@github.com:WalterBright/dmd.git (fetch)
origin  git@github.com:WalterBright/dmd.git (push)
upstream        git@github.com:D-Programming-Language/dmd (fetch)
upstream        git@github.com:D-Programming-Language/dmd (push)
```
Notice the first is `dmd.git` and the second is just `dmd`. Why?

**Comment by WalterBright** [comment]
When would I do `git remote update` vs `git fetch upstream stable`?

**Comment by WalterBright** [comment]
Anyhow, thanks for the info and fixing this PR. Please fix the "rebase to stable" directions.

**Comment by Geod24** [comment]
> `git branch -v` does not tell me what origin and upstream are, though `git remote -v` does.

My bad, I don't know why I wrote `branch` here... It should have been `remote` as you realized.

> Also, why do your instructions not include `git fetch`?

`git fetch` just fetches either `origin` or the upstream of the current branch. `git fetch -a` will fetch all remotes. `git remote update` is pretty much the same as `git fetch -a`. `git remote update -p` (`--prune`) will also remove references to remote branches that have been removed.

> Notice the first is `dmd.git` and the second is just `dmd`. Why?

I'm not sure, but I guess Github changed their remote endpoints at some point. You can do `git remote set-url upstream git@github.com:dlang/dmd.git` to change it to the "latest" address.

**Comment by WalterBright** [comment]
@Geod24 thanks!

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
