### PR TITLE
Move verbose/printing flags out of global.params

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by ibuclaw** [comment]
So, where is this going?

**Comment by thewilsonator** [comment]
Trying to strip down the number or non-semantic flags in `global.params` by grouping them in preparations for a refactor of the semantic flags (really flags that we would like packages to be able to control) in turn in preparations for the introduction of editions. 

I have no idea what editions will look like but if they are to be configurable per package (which is really the main point of editions) then those flags will need to be separated out from the rest of the flags.

**Comment by rikkimax** [comment]
Looks like these for the most part could be surmised by calling them logging.

Otherwise, it sounds like a good idea to split the parameters up in preparation for needing to differentiate the others by-file or package.

**Comment by RazvanN7** [comment]
I am weary of merging this because I don't really understand what we gain by it.

We don't really know what editions are going to look like so I would wait until we have a clear path ahead.

**Comment by thewilsonator** [comment]
>  I don't really understand what we gain by it.

This PR, less disparate (global) variables in Params, same as #15603 #14048 #12617 

w.r.t editions this was so I can get most of the semantic/codegen/instrumentation flags on one screen (c.f. #14348) and think about which flags make sense as being part of an edition/configuration (e.g. `betterC`/`dip1000`) vs flags that should be set only globally (e.g. `tracegc`, either you want to trace calls to the GC (everywhere) or you don't) and those that could arguable be either but is not immediately obvious.

After this I want to finally make `[multi]obj`/`lib[name]` et al `Output`s (c.f. #14048)

> We don't really know what editions are going to look like so I would wait until we have a clear path ahead.

I only mention editions here because Iain asked what this was for. This refactoring is completely independent of editions, although it will make it easier to think about what flags make sense as an edition.

**Comment by thewilsonator** [comment]
ping

**Comment by thewilsonator** [comment]
(this also fixes https://github.com/dlang/dmd/pull/15600#discussion_r1338162655 )

**Comment by thewilsonator** [comment]
This is green and good to go.

**Review by dkorpel — APPROVED** [review]

**Comment by ibuclaw** [comment]
Just what we need, more pointless breaking the (already broken) C++ interface for gdc/ldc compilers.

**Comment by thewilsonator** [comment]
Broken how? Changed, yes, broken I certainly hope not.

**Pull request merged**
