### PR TITLE
TypeFunction.callMatch: Extract code to match typesafe variadic argument

### PR DESCRIPTION
**Pull request by Geod24**
That one wasn't fun but it should make the code much clearer.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Geod24** [comment]
Buildkite did find a bug.

**Comment by nordlow** [comment]
Thank you for performing these modularizations.

**Comment by maxhaton** [comment]
I was tempted to try and get all the matching state & logic into one struct at one point.

Will chip in with my own refactorings I think

**Comment by Geod24** [comment]
Removed one minor commit that turned out to just not be covered by the test-suite.
https://github.com/dlang/dmd/pull/14421 adds a check for it, so in the future there can be no regression.
Would like 14421 pulled before this, even if there's no dependence, as 14421 includes line number informations which will be invalid after this is pulled.

**Pull request merged**
