### PR TITLE
Make core.demangle compile with -preview=nosharedacccess

### PR DESCRIPTION
**Pull request by atilaneves**

### CODE REVIEW

**Comment by thewilsonator** [comment]
```
object.Error@src\rt\minfo.d(364): Cyclic dependency between module constructors/destructors of core.sys.windows.stacktrace and core.runtime

core.sys.windows.stacktrace* ->

core.demangle ->

core.atomic ->

core.thread ->

core.thread.osthread ->

core.sys.windows.dll ->

core.runtime* ->

core.sys.windows.stacktrace*
```

not sure what the correct course of action is here.

**Comment by atilaneves** [comment]
The MacOS thing seems completely spurious.

**Review by dkorpel — APPROVED** [review]

**Comment by atilaneves** [comment]
@dkorpel Do we merge despite the failures then?

**Comment by dkorpel** [comment]
Yes, the failure is [Issue 23846](https://issues.dlang.org/show_bug.cgi?id=23846)

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
