### PR TITLE
refactor intrinsic_op

### PR DESCRIPTION
**Pull request by thewilsonator**
rebase of #8002

### CODE REVIEW

**Comment by thewilsonator** [comment]
WTF is with circle? The code explicitly checks to disable 64bit bswap.

**Comment by thewilsonator** [comment]
`std.math:3789` fails `assert(ilogb(nextUp(-double.min_normal)) == -1023);`
`std.bitmanip` fails in 
```d
static foreach (T; AliasSeq!(byte, short, int, long))
    assert(bitsSet(T.min).equal([8 * T.sizeof - 1]));
```

**Comment by thewilsonator** [comment]
Hmm, `ilogb` uses `bsr`, `bitsSet` uses `bsf`, maybe they are the same failure as circle.

**Comment by thewilsonator** [comment]
Aaaaand back to the fail on 32bit.

**Comment by rainers** [comment]
> deleting this so the druntime PR on branch with same name works, will come back to this soon.

IIRC this only happens if the branch is from the dlang repository, not your fork. Unfortunately, when starting a patch from the web interface it defaults to use dlang.

**Comment by thewilsonator** [comment]
And its mode more complicated by the fact that my druntime fork is from LDC.

**Pull request closed without merging**
