### PR TITLE
DWARF v5 data representation

### PR DESCRIPTION
**Pull request by Luhrel**
I moved `dwarf2.d` into `dwarf.d` because they were every time both imported.

This PR doesn't include any features and is very trivial, but we may need these declarations in the future.

Data representation according to http://dwarfstd.org/doc/DWARF5.pdf, chapter 7.5.

### CODE REVIEW

**Comment by Geod24** [comment]
I suppose you also plan to implement support in druntime ?
https://github.com/dlang/druntime/blob/addfbeb5e2ba91a5bf51858adda5e2b3835bd42f/src/rt/backtrace/dwarf.d#L622

**Comment by ibuclaw** [comment]
I very much doubt there will ever be a need to emit non-contiguous ranges in dwarf.

**Comment by Luhrel** [comment]
> I suppose you also plan to implement support in druntime ?
> https://github.com/dlang/druntime/blob/addfbeb5e2ba91a5bf51858adda5e2b3835bd42f/src/rt/backtrace/dwarf.d#L622

There is a lot of changes and enhancement in DWARF v5, so... maybe, if I have time.

**Comment by Luhrel** [comment]
Moved to new PR https://github.com/dlang/dmd/pull/11426

**Pull request closed without merging**
