### PR TITLE
fix 17259 -  ICE with multiple mixin templates containing conflicting…

### PR DESCRIPTION
**Pull request by ghost**
… ctor declarations

This only fixes the ICE, not the fact that resolution should work, as explained in https://issues.dlang.org/show_bug.cgi?id=19729

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Please target stable.

**Comment by Basile-z** [comment]
BTW, all my latest commits where ICE fixes, none targeted stable. Would you pick them for the upcoming point release ?

**Comment by thewilsonator** [comment]
Yes. Generally all bug fixes that are unlikely to introduce regressions should target stable.

**Comment by Basile-z** [comment]
The bot needs an update. This ICE fix is not more critical than another one. It should rather suggest to rebase when the keyword ICE is present in the issue, which was the case in the other issues I mentioned.

**Comment by thewilsonator** [comment]
ICEs are not good, but all the bot does is grab data from the [importance](https://issues.dlang.org/page.cgi?id=fields.html#importance) field.

**Comment by Basile-z** [comment]
What I meant is that someone can open an ICE with importance normal, someone else an ICE with importance critical but when the fix is opened, the bot only propose to rebase on stable the second one, which is not logical, since both are ICE...you see ?

**Comment by thewilsonator** [comment]
Ah, I do now.

**Comment by thewilsonator** [comment]
Preferably without pulling the rest of master ;)

**Comment by thewilsonator** [comment]
Thanks!

**Comment by Basile-z** [comment]
Yes, fixed that by interactive rebase. The instructions of the bot don't work most of the time.

**Pull request merged**
