### PR TITLE
Remove opDollar from internal array because it's not used at all and doesn't work either

### PR DESCRIPTION
**Pull request by ghost**
…

### CODE REVIEW

**Review by jacob-carlborg — CHANGES_REQUESTED** [review]
Remove the code instead of commenting it out.

**Comment by BBasile** [comment]
@jacob-carlborg ok done.

**Comment by BBasile** [comment]
The problem of this alias is that it gives the illusion that `stuff[$-N]` works, which is not the case.

**Review by jacob-carlborg — APPROVED** [review]

**Comment by n8sh** [comment]
For my edification can you explain why`alias opDollar = dim` doesn't work as expected?

**Comment by BBasile** [comment]
Yes, if course @n8sh, a simple usage shows this pretty well : 

dollar_not_working

**Pull request closed without merging**
