### PR TITLE
Fix issue 3827 - Deprecate implicit string concatenation

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
```
Implicit string concatenation is an old feature that can now be replaced by explicit concatenation.
It was also a source of bug, even for experienced D programmer, and the deprecation has been agreed
on in 2010: http://forum.dlang.org/post/ibi742$gi2$1@digitalmars.com
```

Removed in:
- druntime: dlang/druntime#1660
- phobos: dlang/phobos#4821

And the spec P.R.: dlang/dlang.org#1487

Ping @WalterBright @andralex for re-approval.

### CODE REVIEW

**Review by UplinkCoder — APPROVED** [review]

**Comment by BBasile** [comment]
One more https://github.com/dlang/phobos/blob/master/std/getopt.d#L1661

**Comment by mathias-lang-sociomantic** [comment]
> One more https://github.com/dlang/phobos/blob/master/std/getopt.d#L1661

Hum ? I see a concatenation on that line([permalink for ref](https://github.com/dlang/phobos/blob/5813facba9c07b80d352e89aad0bd29d87ff8fb4/std/getopt.d#L1661)).

**Comment by BBasile** [comment]
Local phobos was not up to date. Sorry.

**Comment by schveiguy** [comment]
Nice!

**Pull request merged**
