### PR TITLE
fix regression introduced by #9691

### PR DESCRIPTION
**Pull request by WalterBright**
https://github.com/dlang/dmd/pull/9691#issuecomment-486836792

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Geod24** [comment]
Can the class itself be made `static` ?

**Comment by WalterBright** [comment]
It should be replaced with a switch. But that's a job for another day.

**Comment by thewilsonator** [comment]
Er, tests?

**Comment by Geod24** [comment]
I assume that's what's Azure is doing now. I tested it locally and it was working.

**Comment by jacob-carlborg** [comment]
I think Semaphore is testing with LDC as the host compiler.

**Comment by thewilsonator** [comment]
Oh, this is an internal compiler regression. Never mind.

**Comment by jacob-carlborg** [comment]
I see that Semaphore failed for the PR that introduced the regression, but clicking on the link to the Semaphore build results in a 404 😢.

**Comment by jacob-carlborg** [comment]
I managed to find the build log for the master branch, see: https://github.com/dlang/dmd/pull/9691#issuecomment-486987018.

**Pull request merged**
