### PR TITLE
[DDMD] [refactor] Split out TOK and Token into tokens.h and tokens.c

### PR DESCRIPTION
**Pull request by yebblies**
There are three reasons that source files `include "lexer.h"`:
1. To actually use the lexer (~3 places)
2. To get access to `TOK` (almost every single file)
3. To call `Lexer::idPool` / `Lexer::uniqueId` (about a dozen)

In the C++ version this isn't a big deal (it's just a header), but in the D version it means importing the whole of the lexer when only a few files actually need it.

This pull splits out the `TOK`/`Token` stuff into another file.  The next pull depends on this one and does something similar for the string table.  With both done I've been able to remove most imports of `lexer` in DDMD.

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
Auto-merge toggled on

**Comment by AndrejMitrovic** [comment]
This is good. Whenever I had to look up a token I'd be lost trying to find "tokens.h" when it didn't exist.

**Comment by yebblies** [comment]
Thanks!

**Comment by yebblies** [comment]
@RazvanN7

**Pull request merged**
