### PR TITLE
Fix issue 9960 Show deprecation errors during template instantiation in verbose mode

### PR DESCRIPTION
**Pull request by lionello**
http://d.puremagic.com/issues/show_bug.cgi?id=9960

This fix allows you to fix issues in templates. Without the fix, specifying "-de" on the command line will silently drop templates from being instantiated, resulting in either the application of a different template, or a fatal template instantiation error.

### CODE REVIEW

**Comment by andralex** [comment]
@lionello @9rnsr  should we close this?

**Comment by lionello** [comment]
I don't disagree with @9rnsr that this is a hack, but it's useful nonetheless.

There's currently no alternative, no way to debug template instantiation errors. This patch gives you the option to show instantiation errors by turning verbose on. Yes, it will print duplicates. But, it's verbose after all :)

I'll rebase this tonight.

**Comment by lionello** [comment]
I'm not happy with the fact that I need two baselines, one for *nix and one for Windows, because of the path separators in the output. The test runner replaces separators in the output, but I can't use the test runner since it captures both stdout and stderr and I only care about stderr.

**Comment by yebblies** [comment]
So, improve the test runner so it can capture stderr by itself?

**Comment by lionello** [comment]
@yebblies Yeah, I was looking into that, but I'd have to add an in-test var, something like `CAPTURE_OUTPUT: stderr`or some such. What do you think?

**Comment by yebblies** [comment]
Yeah.

**Comment by lionello** [comment]
Not sure what it takes to convince you that this is worth taking. Using `deprecated` in templates can result in code silently changing behavior when built with `-dw` versus `-de`. This patch allows you to see these differences by making any template instantiation errors explicit by adding `-v`.

The test case shows this behavior. It will compile successfully, without errors/warnings, no matter whether it's being built with `-de` or `-dw`, but the return code from the process differs.

**Comment by ibuclaw** [comment]
You can see the speculative errors when compiling with `dmd -de -verrors=spec`.

I don't think this is relevant anymore.

**Pull request closed without merging**
