### PR TITLE
use StmtState in ob.d for graph generation

### PR DESCRIPTION
**Pull request by WalterBright**
This is the payoff for splitting StmtState off into its own module. By making it a template, the same logic can be used in ob.d to generate the graph as is used in s2ir.d to generate the intermediate code blocks.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Does stmtstate import any backend or other codegen modules?

**Comment by Geod24** [comment]
> Does stmtstate import any backend or other codegen modules?

[Not anymore](https://github.com/dlang/dmd/pull/10992/files#diff-a3429db9a77faecc66278dca44b212d7L17)

**Comment by ibuclaw** [comment]
Github should really have a button to sort by diff size. :-)

There are no complaints from me then.

**Review by ibuclaw — APPROVED** [review]

**Comment by WalterBright** [comment]
> Not anymore

I was indeed thinking of @ibuclaw  when eliminating back end dependencies from it!

**Pull request merged**
