### PR TITLE
fix Issue 23207 - dmd hangs compiling druntime/src/core/stdc/errno.c

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
buildkite/druntime fails with:
```
  | generated/linux/release/64/unittest/test_runner rt.util.utility
  | generated/linux/release/64/unittest/test_runner rt.util.typeinfo
  | 0.000s PASS release64 rt.util.typeinfo
  | generated/linux/release/64/unittest/test_runner etc.linux.memoryerror
  | 0.000s PASS release64 etc.linux.memoryerror
  | make[1]: Leaving directory '/var/lib/buildkite-agent/builds/ci-agent-ef646f10-7c39-4f37-9ee1-a729da92d3e4-8/dlang/dmd/druntime'
  | 🚨 Error: The command exited with status 2
```
i.e. a completely useless error message.

The autotester error is not reproducible.

I get really tired of bugs I cannot fix because of these sorts of problems.

**Comment by ibuclaw** [comment]
> buildkite/druntime fails with:

Parallel builds, errors are always in a different place other than the end of the logs.

**Comment by ibuclaw** [comment]
There's likely some cross printing going on between make threads, but it's a linker error - try ensuring you're rebased on current mainline first,.
```
generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D8runbench8runTestsFSQu6ConfigZv: error: undefined reference to '_D3std4file8DirEntry4nameMxFNaNbNdNjNfZAya'generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D8runbench8runTestsFSQu6ConfigZv: error: undefined reference to '_D3std4file8DirEntry4nameMxFNaNbNdNjNfZAya'generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D8runbench8runTestsFSQu6ConfigZv: error: undefined reference to '_D3std4file8DirEntry4nameMxFNaNbNdNjNfZAya'generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D8runbench8runTestsFSQu6ConfigZv: error: undefined reference to '_D3std4file8DirEntry4nameMxFNaNbNdNjNfZAya'generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D3std5range__T11SortedRangeTAkVAyaa6_61203c3d2062VEQByQBx18SortedRangeOptionsi0ZQCo__T10lowerBoundVEQDvQDu12SearchPolicyi3TyiZQBoMFNaNbNiNfyiZSQFmQFl__TQFiTQEyVQEza6_61203c3d2062VQEzi0ZQGp: error: undefined reference to '_D3std5range__T11SortedRangeTAkVAyaa6_61203c3d2062VEQByQBx18SortedRangeOptionsi0ZQCo7opSliceMFNaNbNiNjNfmmZSQEcQEb__TQDyTQDoVQDpa6_61203c3d2062VQDpi0ZQFf'collect2: error: ld returned 1 exit statusError: linker exited with status 1generated/linux/release/64/unittest/test_runner core.sys.posix.dlfcngenerated/linux/release/64/unittest/test_runner core.sys.posix.fcntlposix.mak:459: recipe for target 'generated/linux/release/64/benchmark' failedmake: *** [generated/linux/release/64/benchmark] Error 1make: *** Waiting for unfinished jobs....
```

**Comment by WalterBright** [comment]
> Parallel builds, errors are always in a different place other than the end of the logs.

When the log is thousands of lines, and often the "errors" in it are not errors at all, it might as well not be there. I gave up scrolling through it.

A major point of a test suite is to do more than pass/fail - it should **help** in finding the error.

**Comment by WalterBright** [comment]
I thought the test suite would always try to merge the PR into master first. It doesn't do that?

**Comment by ibuclaw** [comment]
> I thought the test suite would always try to merge the PR into master first. It doesn't do that?

I know as much that's true for the autotester. Can't say about the others.

**Comment by WalterBright** [comment]
No wonder the test suite is constantly failing in incomprehensible ways.

**Comment by WalterBright** [comment]
Rebasing seems to have fixed it, along with some guesswork about the auto-tester failure. Thanks, @ibuclaw !

**Comment by WalterBright** [comment]
Blocking https://github.com/dlang/druntime/pull/3857

**Review by dkorpel — APPROVED** [review]

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
