### PR TITLE
refactor _isZeroInit()

### PR DESCRIPTION
**Pull request by WalterBright**
The function is seriously confused and overly complex. Replaced with simpler and straightforward code.

### CODE REVIEW

**Comment by WalterBright** [comment]
This function was added by https://github.com/dlang/dmd/pull/8583

**Review by ibuclaw — APPROVED** [review]
Seems reasonable.

**Comment by ibuclaw** [comment]
Although it looks like this subtly changes codegen to cause one of the unittests to fail.

**Comment by WalterBright** [comment]
Yah, missed a case.

**Pull request merged**
