### PR TITLE
remove unused code

### PR DESCRIPTION
**Pull request by UplinkCoder**
This code did nothing.
Since we are going to have a real ctfe compiler soon I thought it appropriate to remove this.

### CODE REVIEW

**Comment by yebblies** [comment]
It doesn't do nothing, it checks that there are no `ErrorExp`s in the AST.  Until it's replaced we still want this.

**Comment by UplinkCoder** [comment]
okay how about just removeing the funcDeclaration.ctfeCode, then ?

**Comment by UplinkCoder** [comment]
I see.
imo that should be done in regular sematic3

**Comment by yebblies** [comment]
It could be turned into a bool or something.  The issue with semantic3 is that it doesn't always get run, and usually when this picks up errors the global.errors is set correctly, it just wasn't propagated up to the top level (meaning that the next semantic pass won't be run).

Having it as a separate (and debug only) pass right before codegen would be nice, but having it run before interpreting is good too.  It's a very basic AST verify pass.

**Comment by UplinkCoder** [comment]
then let's rename it.

**Comment by UplinkCoder** [comment]
@yebblies btw. how is your backend work progressing ?
Because I think that ctfe and the real backend could maybe share code.

**Pull request closed without merging**
