### PR TITLE
fix Issue 519 - Invariant not called from autogenerated class/struct ctor/dtor

### PR DESCRIPTION
**Pull request by WalterBright**
fix https://issues.dlang.org/show_bug.cgi?id=519

Will follow up with change to spec.

### CODE REVIEW

**Comment by andralex** [comment]
@WalterBright we should pull this. Rebase?

**Comment by WalterBright** [comment]
rebased for ddmd

**Comment by andralex** [comment]
@WalterBright @MartinNowak status?

**Comment by andralex** [comment]
>Why would you need to check the invariant before destroying structs/classes that don't have a destructor? No code could ever use that value again.

Walter is right - object should be valid for destruction

**Comment by andralex** [comment]
@WalterBright need rebase

**Comment by andralex** [comment]
legit errors in autotester

**Comment by andralex** [comment]
ping @WalterBright

**Comment by ibuclaw** [comment]
Rebased patch in #7536.

**Pull request closed without merging**
