### PR TITLE
Add more info to assert to track down mir-algo failure

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by thewilsonator** [comment]
Results from  `const(long[1]) == long[0]`

**Comment by 9il** [comment]
Is it possible to track file and line?

**Comment by thewilsonator** [comment]
Fastest way to track it would be to git bisect mir using DMD master and then derive a test from that. Bisecting DMD will probably be a whole lot slower.

**Comment by thewilsonator** [comment]
`this.___structure_field_1 == []` is the failing expression.

**Comment by 9il** [comment]
> `this.___structure_field_1 == []` is the failing expression.

thanks! btw, this looks is also DMD regression.

**Comment by thewilsonator** [comment]
Oh its definitely DMD's fault. Crashing DMD is always DMD's fault. Have you tested mir-algo 3.0.0 with LDC?

**Comment by 9il** [comment]
> Oh its definitely DMD's fault. Crashing DMD is always DMD's fault. Have you tested mir-algo 3.0.0 with LDC?

Yes, LDC works well. Check travis for v3.0 (v3.1 has other issues for now)

**Comment by thewilsonator** [comment]
Thanks. does `___structure_field_1` look like anything in mir? It almost looks compiler generated except that it has 3 leading _'s instead of two.

**Comment by 9il** [comment]
> Thanks. does `___structure_field_1` look like anything in mir? It almost looks compiler generated except that it has 3 leading _'s instead of two.

Yes, `_structure` is a tuple of one or two fields in mir_slice structure. Filed 0 is lengths, Field 1 is strides.

**Comment by thewilsonator** [comment]
https://github.com/libmir/mir-algorithm/blob/3a72519bb3bea3518a81657294b17b619607f3da/source/mir/ndslice/topology.d#L322 would seem to be it.

**Comment by 9il** [comment]
> Ah, so it is both compiler generated _and_ in mir ;), well that narrows the search space a lot (that was not meant to be sarcastic).

Could you please check with mir-algorithm master or v3.1.2 ? Should be fixed thought

> Given this is a codegen bug it and given `___structure_field_1` is a static array presumably DMD is trying to generate runtime code for a copmiletime condition check?

Probably both, compile time and runtime checks

**Comment by thewilsonator** [comment]
culprit was 
```d
auto slice = iota(2, 3).universal.assumeContiguous;
assert(slice._strides == []); // <<<
```

will do a bug report soon.

**Pull request closed without merging**
