### PR TITLE
merge several tests into fail_scope.d

### PR DESCRIPTION
**Pull request by WalterBright**
Merges a bunch of related tiddlywink tests into one file, making further regression testing easier and speeding up the autotester slightly.

### CODE REVIEW

**Comment by WalterBright** [comment]
This is a no-brainer. What's the issue?

**Comment by MartinNowak** [comment]
> This is a no-brainer. What's the issue?

Time and focus, as usual.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
thanks!

**Pull request merged**
