### PR TITLE
CI: Try to improve parallelization of tests with auto-tester on Windows

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
Argh, that line is patched by the auto-tester: https://github.com/braddr/at-client/blob/master/src/diff-dmd-win64.diff

**Comment by rainers** [comment]
The autotester uses parallel builds for the tests, see for example https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=3764028&dataid=26743929&isPull=true. It is running `gmake -j4` and the non-order of the tests in the log suggests that it works.

**Comment by kinke** [comment]
Yeah I've seen that, but I'm worried that the parallelization only goes as far as 'run runnable/compilable/fail_compilation/... groups in parallel', which would be *very* bad, as runnable takes x times as long as the others. `start_all_tests` is the best we have so far (build the tools in parallel, then run all tests (flat, no groups) in parallel, starting with runnable (for which the order has already been tweaked, longest-running ones first)).

**Comment by rainers** [comment]
Not sure about the tools, but from the logs I assume the tests build in parallel as expected, as the files are processed unsorted within each group, too. Locally I use the run.d tool these days, though.

**Comment by kinke** [comment]
The Windows runtimes are still suspiciously high, but I have no idea about the used hardware. - As the auto-tester repo doesn't seem to feature any CI itself, I'll just close this.

**Pull request closed without merging**
