### PR TITLE
Revert "Fix Issue 20687 - Allow member function address as const initializer"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/dmd#10946

I think this needs some more thought, @WalterBright ?

The main concerns being:
1. You can't use the address for any reasonable purposes, so why allow it?
```
struct S { 
    int foo;
    int bar() { return foo; }
}
static fun = &D.bar;

int main() {
    return fun();  // segfault
}
```

2. Allowing virtual functions to statically have their address taken seems odd.
```
class C { 
    int bar();
}
static fun = &C.bar;
```

### CODE REVIEW

**Comment by Geod24** [comment]
Yep. Taking the `fptr` explicitly might be okay (because the user asks for it), but allowing to get it by just taking the address is IMO a bad idea.

**Review by Geod24 — APPROVED** [review]

**Comment by rainers** [comment]
> static fun = &D.bar;

While the feature seems dubious, it is currently allowed at runtime, so why make a difference for compile time?

> return fun();  // segfault

funcptr has a bad type, it should somehow declare its different ABI abd disallow being called directly.

> 1. Allowing virtual functions to statically have their address taken seems odd.

You can call these with `(new D).C.bar`, so I'm not too surprised.

**Comment by ibuclaw** [comment]
> While the feature seems dubious, it is currently allowed at runtime, so why make a difference for compile time?

Well, then perhaps the inverse of this PR should be done then?  Instead of a rejects-valid bug, perhaps the runtime part should be considered accepts-invalid.

**Comment by ibuclaw** [comment]
> You can call these with (new D).C.bar, so I'm not too surprised.

You mean `(new C).C.bar`?  Otherwise you get need 'this' errors.

**Comment by rainers** [comment]
> You mean `(new C).C.bar`?

I meant D to be a derived class of C, but the delegate still calls the C implementation of bar.

**Comment by Geod24** [comment]
CC @BorisCarvajal too

**Comment by schveiguy** [comment]
> While the feature seems dubious, it is currently allowed at runtime, so why make a difference for compile time?

This was going to be my point.

There are 2 ways to "solve" this:

1. Disallow taking the function pointer at all times (very disruptive, disallows quite a few usages).
2. Change the type of the function pointer so calling without a context pointer is disallowed.

**Comment by schveiguy** [comment]
> 1. Allowing virtual functions to statically have their address taken seems odd.

As an example use case, you can check if a specific instance of a base class has overridden a method:

```D
class C
{
   int foo() { return 1; }
}

checkC(C c)
{
   if(&c.foo.funcptr == &C.foo) { ... }
}
```

I remember doing this for something, but I can't remember exactly when/where.

The truth is, a this-call function pointer is still a constant, and there are use cases for having it. It's allowed at runtime, it should be allowed at compile time as well, or at least usable as a constant since it is a constant.

**Comment by BorisCarvajal** [comment]
Just want to add or repeat:

- You can already do it.
- It can be useful/usable if you take care of pairing it with the correct context pointer or doing address introspection with class methods as @schveiguy code.
- I assume all this code won't work on `@safe` code.
- The compiler should error on the naive usage like the OP example. Here as it was said, exposing the this argument seems to be the solution.

**Comment by ibuclaw** [comment]
> I meant D to be a derived class of C, but the delegate still calls the C implementation of bar.

OK, though I still don't think that is compilable.

**Comment by ibuclaw** [comment]
> I remember doing this for something, but I can't remember exactly when/where.

I've proposed this as a way to optimize calls using speculative devirtualization. The C++/LTO maintainers claim there's on average a 6% speed up IIRC with MI heavy codebases.
```
// c.foo(args) is lowered as... 
if (c.foo.funcptr == &C.foo)
{
  // C.foo typically inlined here
  C.foo(c, args);
}
else
  c.foo(args);
```

**Comment by rainers** [comment]
> OK, though I still don't think that is compilable.

It is, I've tested this on run.dlang.io (unfortunately generating a link no longer works):
```
class C {
    int foo = 4;
    int bar() { return foo; }
}

class D : C {
    override int bar() { return 7; }
}

int main() {
    auto fun = &((new D).C.bar);
    assert(fun() == 4);
    return fun();
}
```

**Comment by rainers** [comment]
> 2\. Change the type of the function pointer so calling without a context pointer is disallowed.

This is also my favorite, but it might also be a breaking change if the type is introspected.

**Comment by ibuclaw** [comment]
Ah, that is a delegate though
```
auto fun = &((new D).C.bar);
```
I can't see why this would be a function pointer, it needs a context pointer, even if it is set to null.
```
auto fun = &C.bar;
```
Infact, a delegate with a null context would be better as at least then you'd trigger the `assert(this !is null)` contract in non-release mode if you try to call it.

**Comment by schveiguy** [comment]
> I can't see why this would be a function pointer, it needs a context pointer, even if it is set to null.

It should be whatever `(&instance.bar).funcptr` type is. Which is currently a straight function pointer.

If we don't have that mechanism (getting function pointer of a non-static member function), then editing `funcptr` of a delegate would be impossible.

C++ has a "thiscall" type of pointer, right? We would need something like that if we wanted it to be robust.

**Comment by schveiguy** [comment]
OK, so C++ has notion of member function pointers. e.g. `int (C::*)()`. We would need something like that.

**Comment by Geod24** [comment]
> We would need something like that.

That is a huge language change for a single use case.

@BorisCarvajal : I'm going to merge this, but if you feel like continuing the conversation, feel free to re-open a PR.
I'm only merging this because your original PR wasn't reviewed and just blindly merged, and we don't want to end up in a situation where the change makes it in a release due to a lack of agreement.

**Comment by ibuclaw** [comment]
Agreed, master should have been the branch to target, not stable.

**Comment by ibuclaw** [comment]
@schveiguy probably a technical detail too far, but the language implementation offloads the inserting of the member pointer parameter to the glue layer, so delegates would be the goto type if we don't want to uproot on the entire system.

**Comment by schveiguy** [comment]
@BorisCarvajal please reopen a PR, this is still a bug that needs solving. Please target master instead.

@Geod24 sure there are consequences to introducing a completely new type to the language, but we don't have to do that to fix this inconsistency. And the new type has more uses than just this (I imagine with such a function pointer you could call via passing an appropriate type without having to construct a delegate).

@ibuclaw sure, but again, we can fix the inconsistency without creating a whole new type.

Just to refocus everyone, the issue at hand here is that a constant determined at compile-time (a function address) is accessible only at runtime. Given the fact that you can get it at runtime even without an instance, there is no excuse to disallow this at compile time. This is compounded by the fact that you can get the address of a static or non-member function at compile time without issue at compile or runtime.

**Comment by Geod24** [comment]
Actually, can't you already do this ?

```D
import core.stdc.stdlib;
static immutable staticPtr = SymToPtr!malloc;
auto SymToPtr (alias Sym) () { return &Sym; }
pragma(msg, typeof(staticPtr));
```

**Comment by schveiguy** [comment]
@Geod24 malloc isn’t a member function. I’m not sure what that code sample is showing.

**Comment by MoonlightSentinel** [comment]
Just out of curiousity:

```
extern(C) int printf(const scope char*, ...);

typeof(Sym)* SymToPtr (alias Sym) () { return &Sym; }

void* malloc(size_t bytes) { return null; }
enum mallocPtr = cast(void*) SymToPtr!malloc;
pragma(msg, mallocPtr);

struct Str
{
    int i;
    void inc() { i++; }
}

enum strIncPtr = SymToPtr!(Str.inc);
pragma(msg, strIncPtr);

interface Int
{
    void inc();
}

/* Pragma succeeds but causes linker error
enum intIncPtr = SymToPtr!(Int.inc);
pragma(msg, intIncPtr);
*/

class Cla : Int
{
    int i;
    override void inc() { i++; }
}

enum claIncPtr = SymToPtr!(Cla.inc);
pragma(msg, claIncPtr);

void main()
{
    printf("mallocPtr = %p\n", mallocPtr);
    printf("sIncPtr   = %p\n", strIncPtr);
//  printf("iInPtr    = %p\n", intIncPtr);
    printf("cInPtr    = %p\n", claIncPtr);
}
```

**Comment by schveiguy** [comment]
@MoonlightSentinel enum works. Static initializers do not.

**Comment by MoonlightSentinel** [comment]
Right, my mistake.

**Comment by schveiguy** [comment]
> Right, my mistake.

I might have given that you with my statement above (that they work only at runtime), I forgot that enums work.

**Pull request merged**
