### PR TITLE
is master broken?

### PR DESCRIPTION
**Pull request by WalterBright**
Do a dummy change, see if it passes.

### CODE REVIEW

**Comment by WalterBright** [comment]
I guess not. Don't pull this.

**Comment by Geod24** [comment]
@WalterBright : The issue with LDC is being worked on by @kinke : https://github.com/dlang/ci/pull/422

**Comment by Geod24** [comment]
Should be fixed.

**Comment by WalterBright** [comment]
Once again looking to see if bugs are in test suite.

**Pull request closed without merging**
