### PR TITLE
Issue 13874 - Invalid FunctionTypeOf segfault the compiler

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=13874

### CODE REVIEW

**Comment by 9rnsr** [comment]
In `TypeEnum::getProperty`, the call `toBasetype()->getProperty(loc, ident, flag);` had caused infinite recursion when the enum is opaque.

**Comment by yebblies** [comment]
Does this prevent `.mangleof` from working on a struct forward declaration?

**Comment by yebblies** [comment]
I mean an enum forward declaration, not struct.

**Comment by 9rnsr** [comment]
Unfortunately following code reports "enum E is forward referenced" error.

```d
enum E;
pragma(msg, E.mangleof);
```

Fixing it is easy, but it should go another PR.

**Comment by yebblies** [comment]
That's fine.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Improving mangleof for opaque enum: #4314

**Comment by Geod24** [comment]
Thanks for fixing it so fast @9rnsr !

**Pull request merged**
