### PR TITLE
add const to mtype.d functions

### PR DESCRIPTION
**Pull request by WalterBright**
trivial

### CODE REVIEW

**Comment by yebblies** [comment]
Header file?

**Comment by WalterBright** [comment]
If there were any issues, it wouldn't link. It links. :-)

**Comment by yebblies** [comment]
It links because all of these methods are virtual.  The C++ header still needs updating.

**Comment by yebblies** [comment]
> So far, the DDMD frontend migration has been pretty painless for us

The real fun starts _after_ 2.069.

> (@yebblies: Your auto-generation thingamajig certainly is a good step towards avoiding such issues. Not sure whether it is something to go into the compiler, though. I'd expect it to be an external tool.)

An external tool has one critical downside - it won't automatically be available on the autotester.

It also only solves one of the problems.  Walter has already removed a bunch of the C++ interface, and we won't know if it's too much until you guys get to that merge.  Are there any more LDC patches that are ready to upstream?

**Comment by MartinNowak** [comment]
Ping @WalterBright

**Comment by WalterBright** [comment]
added const to mtype.h

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
