### PR TITLE
add isDstyleVariadic()

### PR DESCRIPTION
**Pull request by WalterBright**
Repeating the same code over and over is not the best style.

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Comment by thewilsonator** [comment]
Looks good. Assigning a bool to a size_t is a bit weird and I've no Idea what `if (i - j < nparams)` is supposed to mean. Also it looks like `visit(NewExp)` and `visit(CallExp)` share lots in common and should be deduplicated.

**Comment by Geod24** [comment]
> I've no Idea what `if (i - j < nparams)` is supposed to mean.

It's a "clever" trick: `bool` in non-boolean context is always `1` so it's either `i` or `i - 1`.
But it's probably too clever.

**Comment by thewilsonator** [comment]
Hmm ```dmd: /var/lib/buildkite-agent/builds/ci-agent-b0c8ed6f-ad59-4449-ab08-57c407425724-1/dlang/dmd/dmd/src/dmd/backend/cod4.d:3764: Assertion `array overflow' failed.```

**Comment by WalterBright** [comment]
> It's a "clever" trick: bool in non-boolean context is always 1 so it's either i or i - 1.
But it's probably too clever.

There's nothing remotely clever about it.

**Comment by WalterBright** [comment]
> Hmm

That is indeed a bizarre failure considering what this PR consists of.

**Comment by thewilsonator** [comment]
No but it is not obvious what the _intention_ is. I presume that it is special casing handling of `_argptr`, but I don't know which way around that casing is.

**Comment by WalterBright** [comment]
Trying to track the problem down with a binary search.

**Comment by WalterBright** [comment]
This PR now has only comments and buildkite still fails.

**Comment by rainers** [comment]
Your PR is 15 commits behind master, maybe buildkite doesn't merge it, but builds the branch as is? I'd try rebasing...

**Comment by WalterBright** [comment]
@rainers good idea, trying it now.

**Comment by WalterBright** [comment]
@rainers looks like you nailed the problem. Thanks! You saved me a lot of time.

**Comment by WalterBright** [comment]
The buildkite errors are network failuers.

**Pull request merged**
