### PR TITLE
dmd.mars: Combine DMD driver options with DMD language options for command-line processing

### PR DESCRIPTION
**Pull request by ibuclaw**
This begins a migration path for many dmd driver/codegen flags to be moved from `global.params` to `dmdParams.`

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]

**Comment by WalterBright** [comment]
I'm a little confused. Does this mean that all parameters are DMD parameters? Does gdc and ldc not use mars.d at all?

**Comment by thewilsonator** [comment]
The only thing in dmd's `mars.d` that LDC calls is `int mars_mainBody(Param &params, Strings &files, Strings &libmodules);`, it defines some of its own argument parsing utilities for revert/transition/preview options.

**Comment by WalterBright** [comment]
I can't find `mars_mainBody()` in mars.d

**Comment by ibuclaw** [comment]
> I'm a little confused. Does this mean that all parameters are DMD parameters? Does gdc and ldc not use mars.d at all?

GDC does not use mars.d at all.  The main function and option handling is all done on the GCC side, the D front-end is merely hooked in as if it were a "library" (during option parsing it is asked: do you recognize this option? yes/no/unhandled)

Because of this, GDC only deals with matters of language, rather than matters of output format, so there are options that control fields in `global.params` and `target` that are of no concern for GDC (`-c`, `-g`, `-m32`, `-m64`, `-mcpu`, `-run`, `-target`, `-os`, `-fPIC`, `-L`, `-Xcc`, ...), nor indeed are they even set.

Because `params` is passed around by reference, this would also mean passing around `dmdParams` (and maybe `target`) by reference as extra parameters too.  This is a bit messy, so I'd rather just put them behind a common object and pass them around together.

**Comment by thewilsonator** [comment]
This is well out of date. If you still want this please open a new PR based on `master`

**Pull request closed without merging**
