### PR TITLE
fix Issue 14587 - generated 64 bit code for switch jump tables is wrong

### PR DESCRIPTION
**Pull request by WalterBright**
https://issues.dlang.org/show_bug.cgi?id=14587

This is a critical bug fix.

### CODE REVIEW

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by schveiguy** [comment]
I think this should have gone into branch stable, since it's a regression. I think we need to update the D wiki on how to properly do this. @MartinNowak, what is the proper way to do this, and how do you know whether something goes into stable or not?

**Comment by MartinNowak** [comment]
> how do you know whether something goes into stable or not?

It goes into stable if it makes the compiler more stable :), i.e. regression fixes and bugfixes with low risk.

**Comment by tramker** [comment]
I think the question is, should it go to stable at this stage, when 2.067.1 is out and 2.068 is next ? Will there be 2.067.2 ? I assume at some point master is going to be merged to stable.

**Comment by MartinNowak** [comment]
> I think the question is, should it go to stable at this stage, when 2.067.1 is out and 2.068 is next ? Will there be 2.067.2 ? I assume at some point master is going to be merged to stable.

Always stable, simpler and leaves us more options, e.g. releasing 2.067.2, even though that isn't planned.

**Comment by schveiguy** [comment]
I'll try my hand at updating the wiki.

**Pull request merged**
