### PR TITLE
handle byte, short, and int cases for bug 19946

### PR DESCRIPTION
**Pull request by WalterBright**
This is some basic code to implement short and int fixes for https://issues.dlang.org/show_bug.cgi?id=16098

### CODE REVIEW

**Comment by WalterBright** [comment]
Hmm, it appears to fail for everything *but* the test cases! I'll look at tomorrow.

**Comment by WalterBright** [comment]
Well well, looks like it's working now!

**Comment by dkorpel** [comment]
If you rebase on the latest master, macOS tests should be fixed

**Comment by dkorpel** [comment]
*after https://github.com/dlang/dmd/pull/14775 has been merged

**Comment by PetarKirov** [comment]
@WalterBright I've rebased your MR on master, so now Cirrus CI (macOS) should be working again.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
