### PR TITLE
Revert "start adding support for storage classes for ..."

### PR DESCRIPTION
**Pull request by CyberShadow**
Reverts dlang/dmd#11125

I think that PR broke the dlang.org build, so this should unbreak master.

See https://forum.dlang.org/post/npfvnbltyptukmznzeum@forum.dlang.org

Explanation: https://github.com/dlang/dmd/pull/11125#issuecomment-626901284

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]

**Review by MoonlightSentinel — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
Even simpler: #11132

**Comment by Geod24** [comment]
Merged to unbreak the build.
#11132 was red on SemaphoreCI, and despite re-triggering the build, it was still red, so going with this. There's no reason to leave the build broken any longer, especially since one has to click this to break it in the first place:

Screen Shot 2020-05-12 at 9 28 41

Because DAutoTester is mandatory (and rarely flaky).

**Comment by WalterBright** [comment]
SemaphoreCI, etc., have cried wolf so many times and have such inscrutable logs, you'll have to forgive me.

**Comment by WalterBright** [comment]
@Geod24 why did you merge this rather than #11132 ?

**Comment by CyberShadow** [comment]
@WalterBright He answered that question here: https://github.com/dlang/dmd/pull/11131#issuecomment-627037764

**Comment by Geod24** [comment]
@WalterBright : I explained it here: https://github.com/dlang/dmd/pull/11131#issuecomment-627037764
I wanted to go with #11132 but the build was consistently red.

> SemaphoreCI, etc., have cried wolf so many times and have such inscrutable logs, you'll have to forgive me.

Yet everyone else deal with this. Note that it's extremely rare that those CI are consistently broken, so if you had re-triggered the CI a few times you'd have seen that it was consistently failing.

Now I remember that you didn't have access to re-triggering some CI. I invited you to Buildkite (you need to use SSO to login), so you'll have the ability to re-trigger build. I checked SemaphoreCI and you're marked as "Invited", so I'd check your emails. It seems I don't have the right to invite people to SemaphoreCI, so I couldn't re-invite you (CC @wilzbach). Let me know if you can't retrigger other CIs.

**Comment by WalterBright** [comment]
> Yet everyone else deal with this.

It's a significant impediment to everyone. Can the logs be better?

Re invitation emails - I don't recall getting them. Perhaps lost in my spam filter? Please resend? I don't know what SSO is.

**Comment by Geod24** [comment]
> It's a significant impediment to everyone. Can the logs be better?

I'm all for it, but someone has to work on it. So far @MoonlightSentinel has been doing a great job. Maybe we could have a topic to brainstorm ideas ?

> Re invitation emails - I don't recall getting them. Perhaps lost in my spam filter? Please resend? I don't know what SSO is.

I sent the buildkite one a couple minutes before I posted that message, so you should have it somewhere (sent it to the address I have - your company email).
Regarding [SSO](https://en.wikipedia.org/wiki/Single_sign-on), it means you need to login with one of the accepted provider - e.g. Github. If for some reason you can't register after you get the email, let me know.

**Comment by WalterBright** [comment]
Ok, I got the invite (it was in my spam filter) and accepted it. Thanks.

**Comment by WalterBright** [comment]
My ideas would be:

1. have a description of what the test actually is. Cannot tell this from the log file.
2. Have the log file say what the step is going to be rather than just doing something
3. Have the error be the last thing in the log file, not buried pages upscreen
4. Put the log file in a bigger window
5. Have a scroll tab in that log file window that is bigger than microscopic
6. Stop displaying "error"s that are not substantive - maybe call them "warnings"?

**Comment by MartinNowak** [comment]
>> I'm all for it, but someone has to work on it. So far @MoonlightSentinel has been doing a great job.
> Maybe we could have a topic to brainstorm ideas ?

Colouring logs is often useful to better structure logs.

> Yet everyone else deal with this. Note that it's extremely rare that those CI are consistently broken, so if you had re-triggered the CI a few times you'd have seen that it was consistently failing.

What helps quite well is to automatically retry CI *once* to recover from intermittent failures.

> Buildkite

Buildkite is a bit special because we test D packages, hence it has 3 sources of errors (PR bugs, intermittent failures, broken packages) instead of just the former 2.

Here packages could be updated via a daily/weekly cron job instead of automatically taking the latest stable package versions. This shift responsibility for the ecosystem's health a bit more to the package maintainers.

**Comment by WalterBright** [comment]
P.S. I agree @MoonlightSentinel has been doing a great job!

**Comment by MoonlightSentinel** [comment]
> My ideas would be:
> 
> 1. have a description of what the test actually is. Cannot tell this from the log file.
> 2. Have the log file say what the step is going to be rather than just doing something

CircleCI/Azure/... could split the "Build+Test" step into smaller steps with more descriptive names (as done for the auto-tester).

DAutoTest is more difficult because it is limited to a single log file, Maybe `echo` a separator + short description before each step?.

> 3. Have the error be the last thing in the log file, not buried pages upscreen

(See #11141 if you referring to the random semaphore failure due to missmatched binaries)

That's mostly caused by `make` and especially horrible in druntimes test suite (which could be improved using intermediate log files for each step)

> 4. Put the log file in a bigger window
> 5. Have a scroll tab in that log file window that is bigger than microscopic

100% agreed (especially unbearable on mobile devices), but i don't think there is anything we can do about that.

> 6. Stop displaying "error"s that are not substantive - maybe call them "warnings"?

Could you provide some examples?

**Comment by wilzbach** [comment]
> CircleCI/Azure/... could split the "Build+Test" step into smaller steps with more descriptive names (as done for the auto-tester).

Unfortunately this is not a good idea. The way these CI works is that they take the yaml/config from the PR branch and we need to manually merge master afterwards into the git checkout. Hence, whenever you add/modify/remove a task, you run into a ton of "unrelated failures". We tried this before and lots of people had problems as this then requires the branch to be up to date with latest master.

What could be done is to use dlang-bot to for example update/post the last 30 or so lines of the failing CI in its comment and maybe even detect a few common patterns.

**Pull request merged**
