### PR TITLE
Use posix compliant preprocessor directive for linux

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by Geod24** [comment]
Please don't self merge. Especially on a PR without a single line of description, not a bugzilla issue.

**Comment by thewilsonator** [comment]
Title is self descriptive.

**Comment by thewilsonator** [comment]
For reference I'm trying to figure out why https://github.com/dlang/dmd/pull/8342 fails with linker error on that conditionally defined function

**Comment by thewilsonator** [comment]
This is also NFC on a test, of any PRs acceptable to self merge this would be one.

**Comment by Geod24** [comment]
> Title is self descriptive.

No it's not. Reviewers don't have any context (like #8342).
Just providing the link to the specs which says `__linux__` would have been enough in this case.

**Comment by thewilsonator** [comment]
> Just providing the link to the specs which says __linux__ would have been enough in this case.

I expect that combination of the title with the diff that would be blindingly obvious without the need to do that. It is not like this is a complex PR dealing with an obscure spec.

**Comment by wilzbach** [comment]
# Never ever self-merge please!!!

**Comment by WalterBright** [comment]
Not in this case, but sometimes there are obscure reasons things are done in a certain way (I've nixed several PRs on that basis). Self-merging after minutes doesn't give anyone a chance to notice it.

**Pull request merged**
