### PR TITLE
Highlight Error Messages: cond, escape

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by JinShil** [comment]
LGTM

**Review by JinShil — APPROVED** [review]

**Review by PetarKirov — APPROVED** [review]
LGTM too.

**Comment by WalterBright** [comment]
There are about 1500 `error()` prints in dmd. This fixes about 15 of them. Taking days/weeks to get these pulled means it will take several years to fix them all.

Fixing them in parallel is problematic because so many of the test files emit multiple messages, so there'd be endless rebasing work.

**Comment by CyberShadow** [comment]
@WalterBright If you find yourself wasting too much time on these, I could try to take over & automate things.

**Comment by WalterBright** [comment]
The main time sink is getting it through the test suite. I do use grep to try to get them done, but there's always nitpicky things and typos to get it through. I suspect it would take more time to automate than to just do it manually.

Some judgement calls need to be done, too, because of variations in how the error messages present code.

**Comment by ibuclaw** [comment]
Why not just convert an entire file at once, then tick it off the list.

**Comment by WalterBright** [comment]
That's pretty much what I've been doing.

**Comment by ibuclaw** [comment]
> That's pretty much what I've been doing.

So then it should total up to about 38 pull requests.  I suppose an upper bound of 38 weeks and conservative lower bound of 38 days seems more likely. :-)

**Pull request merged**
