### PR TITLE
Issue 12888 - Include template constraints in JSON output

### PR DESCRIPTION
**Pull request by Hackerpilot**
https://issues.dlang.org/show_bug.cgi?id=12888

### CODE REVIEW

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Oh wait @9rnsr had a concern. @Hackerpilot ?

**Comment by andralex** [comment]
Auto-merge toggled off

**Comment by Hackerpilot** [comment]
Updated.

**Comment by 9rnsr** [comment]
I was waiting the reply about 8 months.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Pull request merged**
