### PR TITLE
treat the null type as a pointer type

### PR DESCRIPTION
**Pull request by WalterBright**
We'll see if this is the solution to https://github.com/dlang/phobos/pull/6871

### CODE REVIEW

**Comment by thewilsonator** [comment]
It wasn't before?

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
buildkite/dmd:
```
\ No newline at end of file
```
Since that's not a file that's part of the dmd repository, I have no clue what's going on with buildkite.

**Comment by thewilsonator** [comment]
The problem is the diff above it. For some reason this changes the output of dls? cc @LaurentTreguier

**Comment by LaurentTreguier** [comment]
This could be entirely unrelated to this PR. I released a new DLS version just this morning, and this PR happened to be the first using it in its Buildkite build.
All tests seemed to pass on my machine and on Travis, including [with dmd v2.085.0-beta.1](https://travis-ci.org/d-language-server/dls/jobs/496977681), so I think whatever is triggering this has likely come after that.

**Comment by LaurentTreguier** [comment]
Wait, I know exactly why this fails: the newest tests are about finding references to symbols. The failing ones are trying to find references to `writeln` from `std.stdio`, but on the Buildkite machine, DLS doesn't find any DMD installation and thus doesn't consider `writeln` to be a valid symbol.
I'll remove the test and push a new version, and see later how to make it work regardless of having a D installation on the testing machine.

**Comment by wilzbach** [comment]
> having a D installation on the testing machine.

Well, it's a D installation - just a bit different to the ones from the official packages. The `dmd` honey is still in the `$PATH` etc.

**Comment by LaurentTreguier** [comment]
Yes, but it doesn't use dmd to detect them on Posix. Maybe I should do that actually. Right now, it looks for config files in `/etc` as well as some predetermined locations instead. And if no config file is found and phobos isn't in a standard location, it's not going to be found.
The new version is up and has those tests disabled for now. Sorry for the trouble !

**Comment by wilzbach** [comment]
> Right now, it looks for config files in /etc as well as some predetermined locations instead. And if no config file is found and phobos isn't in a standard location, it's not going to be found.

Have a look at `dmd.frontend`. You can use this detection to find config files for DMD and LDC. It's intended to be used by libraries.

**Comment by LaurentTreguier** [comment]
I'll have a look. Thanks !

**Comment by WalterBright** [comment]
It's passing buildkite now, so turning automerge back on. Thank you, @LaurentTreguier for the quick action!

**Pull request merged**
