### PR TITLE
convert s2ir.c to s2ir.d

### PR DESCRIPTION
**Pull request by WalterBright**
Try again.

### CODE REVIEW

**Comment by WalterBright** [comment]
Looks like I fixed the problem with OSX32, but the ldc build still faults.

**Comment by WalterBright** [comment]
Anyone care to provide a stack trace of the ldc failure? I'd appreciate it.

**Comment by MartinNowak** [comment]
Well, this was a nice test for the github hooks of the project tester ;), https://ci.dawg.eu/job/dmd_trigger/.
Here is what Travis-CI does and you can do on a normal linux box.

### download, unpack, and activate (ENV) the latest ldc release
https://travis-ci.org/dlang/dmd/jobs/169502344#L493
```sh
source $(curl -fsSL https://dlang.org/install.sh | bash -s ldc --activate)
```
### build dmd with ldc
https://travis-ci.org/dlang/dmd/jobs/169502344#L552
```sh
make -j2 -C src -f posix.mak MODEL=32 HOST_DMD=ldmd2 ENABLE_RELEASE=1 all
```
### build druntime w/ that newly build dmd
https://travis-ci.org/dlang/dmd/jobs/169502344#L692
```sh
make -j2 -C ../druntime -f posix.mak MODEL=32
```
boom!
```
(gdb) bt
#0  0x0820985e in setScopeIndex(Blockx*, block*, int) ()
#1  0x0820d43d in S2irVisitor::visit(TryCatchStatement*) ()
#2  0x081df237 in TryCatchStatement::accept(Visitor*) ()
#3  0x0820b30a in S2irVisitor::visit(CompoundStatement*) ()
#4  0x081dcd77 in CompoundStatement::accept(Visitor*) ()
#5  0x0820b30a in S2irVisitor::visit(CompoundStatement*) ()
#6  0x081dcd77 in CompoundStatement::accept(Visitor*) ()
#7  0x0820ae22 in Statement_toIR(Statement*, IRState*) ()
#8  0x0820290d in FuncDeclaration_toObjFile(FuncDeclaration*, bool) ()
#9  0x0814c21a in FuncDeclaration::accept(Visitor*) ()
#10 0x0821e5c6 in toObjFile(Dsymbol*, bool)::ToObjFile::visit(ClassDeclaration*) ()
#11 0x080abf3a in ClassDeclaration::accept(Visitor*) ()
#12 0x0821d405 in toObjFile(Dsymbol*, bool) ()
#13 0x08184962 in genObjFile(Module*, bool) ()
#14 0x0818262e in ddmd.mars.tryMain(uint, const(char)**) ()
#15 0x08185807 in D main ()
```
Unfortunately ldc doesn't manage to build w/ debug symbols, $eax is 0 in the debugger. Looks like sth. w/ the [sizeCheck](https://github.com/WalterBright/dmd/blob/ae9ef94bb27ebebb82fe5f73cc2b073079b687fa/src/s2ir.d#L97) is broken.

```
(gdb) disassemble _Z13setScopeIndexP6BlockxP5blocki
Dump of assembler code for function _Z13setScopeIndexP6BlockxP5blocki:
   0x0825eac0 <+0>:	push   %ebx
   0x0825eac1 <+1>:	sub    $0x28,%esp
   0x0825eac4 <+4>:	mov    0x38(%esp),%eax
   0x0825eac8 <+8>:	mov    0x34(%esp),%ecx
   0x0825eacc <+12>:	mov    0x30(%esp),%edx
   0x0825ead0 <+16>:	mov    %edx,0x24(%esp)
   0x0825ead4 <+20>:	mov    %ecx,0x20(%esp)
   0x0825ead8 <+24>:	mov    %eax,0x1c(%esp)
   0x0825eadc <+28>:	call   0x82a32ea <_ZN6Config9sizeCheckEv>
   0x0825eae1 <+33>:	mov    $0x50,%ecx
   0x0825eae6 <+38>:	cmp    %eax,%ecx
   0x0825eae8 <+40>:	je     0x825eb21 <_Z13setScopeIndexP6BlockxP5blocki+97>
   0x0825eaea <+42>:	call   0x82a32ea <_ZN6Config9sizeCheckEv>
   0x0825eaef <+47>:	lea    0x832c0de,%ecx
   0x0825eaf5 <+53>:	mov    $0x50,%edx
   0x0825eafa <+58>:	mov    %ecx,(%esp)
   0x0825eafd <+61>:	movl   $0x50,0x4(%esp)
   0x0825eb05 <+69>:	mov    %eax,0x8(%esp)
   0x0825eb09 <+73>:	mov    %edx,0x18(%esp)
   0x0825eb0d <+77>:	call   0x8049d00 <printf@plt>
   0x0825eb12 <+82>:	xor    %ecx,%ecx
   0x0825eb14 <+84>:	mov    %cl,%bl
   0x0825eb16 <+86>:	test   $0x1,%bl
   0x0825eb19 <+89>:	mov    %eax,0x14(%esp)
   0x0825eb1d <+93>:	jne    0x825eb2b <_Z13setScopeIndexP6BlockxP5blocki+107>
   0x0825eb1f <+95>:	jmp    0x825eb2d <_Z13setScopeIndexP6BlockxP5blocki+109>
   0x0825eb21 <+97>:	xor    %eax,%eax
=> 0x0825eb23 <+99>:	cmpl   $0x1,0x4c(%eax)
   0x0825eb27 <+103>:	je     0x825eb48 <_Z13setScopeIndexP6BlockxP5blocki+136>
   0x0825eb29 <+105>:	jmp    0x825eb6c <_Z13setScopeIndexP6BlockxP5blocki+172>
   0x0825eb2b <+107>:	jmp    0x825eb21 <_Z13setScopeIndexP6BlockxP5blocki+97>
   0x0825eb2d <+109>:	mov    %esp,%eax
   0x0825eb2f <+111>:	movl   $0x61,0x8(%eax)
   0x0825eb36 <+118>:	movl   $0x832c0eb,0x4(%eax)
   0x0825eb3d <+125>:	movl   $0x6,(%eax)
   0x0825eb43 <+131>:	call   0x830ad30 <_d_assert>
   0x0825eb48 <+136>:	mov    0x24(%esp),%eax
   0x0825eb4c <+140>:	mov    0x1c(%esp),%ecx
   0x0825eb50 <+144>:	mov    %eax,(%esp)
   0x0825eb53 <+147>:	mov    %ecx,0x4(%esp)
   0x0825eb57 <+151>:	call   0x8283b6c <_Z23nteh_setScopeTableIndexP6Blockxi>
   0x0825eb5c <+156>:	mov    0x20(%esp),%ecx
   0x0825eb60 <+160>:	mov    %ecx,(%esp)
   0x0825eb63 <+163>:	mov    %eax,0x4(%esp)
   0x0825eb67 <+167>:	call   0x8295456 <_Z15block_appendexpP5blockP4elem>
   0x0825eb6c <+172>:	add    $0x28,%esp
   0x0825eb6f <+175>:	pop    %ebx
   0x0825eb70 <+176>:	ret    
End of assembler dump.
```

**Comment by MartinNowak** [comment]
For some reason `&config` is null (crashes in config.ehmethod).
There are absolute R_386_32 relocations in the text segment, looks a bit weird, but not necessarily wrong.
```d
Relocation section '.rel.text._Z13setScopeIndexP6BlockxP5blocki' at offset 0xcb0 contains 18 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
0000001e  00003602 R_386_PC32        00000000   _ZN6Config9sizeCheckEv
00000024  00000201 R_386_32          00000000   .L.str
0000002f  00003f01 R_386_32          00000000   config
0000004b  00004502 R_386_PC32        00000000   printf
00000051  00000301 R_386_32          00000020   .L.str.1
00000057  00003f01 R_386_32          00000000   config
00000067  00004502 R_386_PC32        00000000   printf
0000006d  00000401 R_386_32          00000000   .L.str.2
00000079  00004502 R_386_PC32        00000000   printf
00000082  00003602 R_386_PC32        00000000   _ZN6Config9sizeCheckEv
00000090  00003602 R_386_PC32        00000000   _ZN6Config9sizeCheckEv
00000096  00000501 R_386_32          00000006   .L.str.3
000000b3  00004502 R_386_PC32        00000000   printf
000000c8  00003f01 R_386_32          00000000   config
000000df  00000601 R_386_32          00000013   .L.str.4
000000ea  00003a02 R_386_PC32        00000000   _d_assert
000000fe  00003202 R_386_PC32        00000000   _Z23nteh_setScopeTable
0000010e  00003102 R_386_PC32        00000000   _Z15block_appendexpP5b
```

**Comment by MartinNowak** [comment]
Apparently the linker is converting the relocation to null.
s2ir.o
```
?_001:  cmp     dword ptr [config+4CH], 1               ; 0061 _ 83. 3D, 0000004C(d), 01
```
linked executable (both w/ ld.gold and ld.bfd)
```
?_48890:xor     eax, eax                                ; 0825E931 _ 31. C0
        cmp     dword ptr [eax+4CH], 1                  ; 0825E933 _ 83. 78, 4C, 01
```
Maybe it's an ldc bug to emit absolute relocations in text segments @JohanEngelen, @klickverbot?

**Comment by WalterBright** [comment]
By enabling/disabling code, I have tracked it down last night to:
```
void setScopeIndex(Blockx *blx, block *b, int scope_index)
{
    if (config.ehmethod == EHmethod.EH_WIN32)
        block_appendexp(b, nteh_setScopeTableIndex(blx, scope_index));
}
```
which causes the crash when the D version is compiled, but works when the old C++ version is used. This confirms the stack trace Martin posted. I did put an assert for sizeCheck() in there, and the sizes match. Oddly, with the sizeCheck check in, the 32 bit test succeeds while the 64 bit one still fails.

**Comment by WalterBright** [comment]
```
   0x0825eb21 <+97>:    xor    %eax,%eax
=> 0x0825eb23 <+99>:    cmpl   $0x1,0x4c(%eax)
```
That certainly will crash.

**Comment by WalterBright** [comment]
> we'll still have to find a way to work around this,

How about this?

> Compiling all the modules to individual object files (at once w/ @-c) and linking those (using ldmd2) does not reproduce the crash.

I.e. change the makefile.

**Comment by WalterBright** [comment]
> is certainly an option, but we'll (for now) lose LTO and thus ~10% performance. Still preferable to not building at all, of course.

As you say, it's a workaround until the problem with LDC is solved. It enables me to continue working, as this is a bit of a blocker for me. After LDC is fixed, the makefile change can be reverted. Can you please do it? And thanks for your (and Martin's) help with this. It was driving me batty last night! People are often too quick to blame the compiler, which is why I was reluctant to suggest there was something wrong with LDC.

**Comment by WalterBright** [comment]
Looks like https://github.com/dlang/dmd/pull/6210 has the same ldc problem.

**Comment by MartinNowak** [comment]
> Looks like #6210 has the same ldc problem.

The essence of which seems to be having a definition and a reference (to an undefined symbol) in different modules. Simplest solution might be to do the definition in C++ (e.g. ldc_workaround.c).

**Comment by WalterBright** [comment]
Prevents this from working, too:
  https://github.com/dlang/dmd/pull/6211

**Comment by WalterBright** [comment]
> The essence of which seems to be having a definition and a reference (to an undefined symbol) in different modules. Simplest solution might be to do the definition in C++ (e.g. ldc_workaround.c).

Not sure just what you mean. Do you want to do a PR for it?

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
