### PR TITLE
Fix issue 18946:  assert message can throw hijacking the assert failure

### PR DESCRIPTION
**Pull request by thewilsonator**
I presume the protocol is to deprecate this first.

### CODE REVIEW

**Comment by Geod24** [comment]
When submitting a PR, please provide a title which allow us to see what it's about from the notification.

**Comment by Geod24** [comment]
I am not sure the linked issue is valid. In the end, your exception happens last, and that's what gets reported. If the function was to `assert`, that would also be reported, wouldn't it ?

**Comment by thewilsonator** [comment]
Instead of throwingFunc replace that with a call to format or the like, which one might reasonably expect to catch from some higher call chain call...

**Comment by Geod24** [comment]
@thewilsonator : Exactly. But forcing people to put `nothrow` on their string-formatting functions is quite excessive IMO.

**Comment by thewilsonator** [comment]
Hmm, perhaps this is not the correct way to fix this. It would be better to wrap the message evaluation in a try catch.

**Comment by Geod24** [comment]
Yeah, that would be much better

**Comment by Geod24** [comment]
If you don't mind, I'm going to close this for the time being since this approach won't work.
This way it won't get scheduled into the CI queue.
Feel free to reopen when you implement the different approach.

**Pull request closed without merging**
