### PR TITLE
DIP xxxx - implicit conversion operators

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by JinShil** [comment]
Oh!!! Please pursue this.  It's near the top of my list.  If I can assist in any way, let me know.

**Comment by JinShil** [comment]
Why not `opImplicitCast`.  That seems to be the preference.  See https://forum.dlang.org/search?q=opImplicitCast&scope=forum

**Comment by Basile-z** [comment]
Yes I continue but I didn't mean to open here. I wanted to [open here](https://github.com/Basile-z/dmd/pull/2) but were not careful enough. The PR is actually more advanced than the DIP...

**Comment by WalterBright** [comment]
People regularly complain about implicit conversions of integer types. C++ has implicit conversions for classes, and I can't find a reference to it at the moment, but was regarded as a mistake because people would rapidly lose track of what overloads were being called when implicit conversions were thrown into the mix.

Implicit conversions often look sensible and cool in the small, but when the complexity increases, it becomes unmanageable. The troubles only appear after it's in use a couple years, and then it's too late.

This is why D does not have implicit conversion operator overloads. Keep in mind that many languages eschew implicit conversions entirely.

You can work on a DIP for it if you like, but it'll get a strong negative reaction from me.

**Comment by JinShil** [comment]
Part of the motivation here is an attempt to implement `alias this` in the library.  If it were done in the library we would get multiple `alias this` without any additional changes to the language.  Multiple `alias this` (a.k.a. DIP66) was approved and [an implementation was attempted](https://github.com/dlang/dmd/pulls?utf8=%E2%9C%93&q=is%3Apr+DIP66) multiple times, but it was never approved because it introduced too much complexity into the compiler.

As far as I can tell, some kind of implicit cast/conversion feature is the only thing preventing us from implementing the essentials of `alias this` in the library.  `alias this` as a language feature introduces [quite a bit of complexity](https://github.com/dlang/dmd/search?q=%22aliasthis%22&unscoped_q=%22aliasthis%22) (and [problems](https://issues.dlang.org/buglist.cgi?quicksearch=%22alias%20this%22&list_id=226855)) in the compiler.  I believe that if we delegated this implementation to the library we'd have a much more scalable feature and a much simpler compiler, and that would cover the cost of `opImplicitCast`.

@WalterBright, if `opImplicitCast` is not the right answer, can you suggest something else that would allow us to utilize D's metaprogramming features to implement something akin to `alias this` and multiple `alias this` in the library to achieve composition as elegantly and conveniently as `alias this`?

Furthermore, if you believe `opImiplicitCast` is not the right answer, you can't be too happy about `alias this` either, because it essentially does the same thing.  `opImplicitCast` would essentially provide the same ability that `alias this` provides today, but without all of the complexity and bugs in the language.

**Comment by WalterBright** [comment]
`alias this` has been a constant problem, because it has an inadequate and incomplete design. I don't think it should be used for anything other than a single instance in structs (which would make it single inheritance, which is a tractable problem). Otherwise, yes, it is multiple inheritance, and a significant problem. Extending it with multiple alias this just makes the problem worse.

If you want multiple inheritance:

1. use multiple interfaces with classes
2. use aggregation with structs

Your code will work in predictable and sensible ways and will be understandable.

**Comment by WalterBright** [comment]
implicitCast does not cover what alias this does, such as presenting an lvalue.

**Comment by JinShil** [comment]
> If you want multiple inheritance:

I don't want multiple inheritance (and I think you're using that term imprecisely);  I want convenient struct composition.

> use aggregation with structs

Yes, that is what I want, but with D's current features, the possibilities are too limiting.  This very contrived example illustrates the problem.

```D
struct IStream
{
    string read() { return ""; }   
}

struct OStream
{
    void write(string s) { };   
}

struct IOStream
{
    IStream i;
    OStream o;
    
    // Generating the following functions can be automated with D's awesome
    // metaprogramming facilities, so no problem here.
    string read() { return i.read(); }
    void write(string s) { o.write(s); }
}

extern string source(ref IStream i);
extern void sink(ref OStream o);

void main()
{
    IOStream io;

    // This is the problem...
    source(io);    // Can't do this, and I may not be the author of `source`
    sink(io);      // Can't do this, and I may not be the author of `sink`
}
```

I have another use case as well, but, at the moment, I'm have the problem above in mind.

**Comment by Geod24** [comment]
> implicitCast does not cover what alias this does, such as presenting an lvalue.

Returning by `ref` should cover this

**Comment by WalterBright** [comment]
> I have the problem above in mind.

Those tiny examples always look good. But it doesn't scale. It's terrifyingly easy to create impenetrable code with implicit casting overloads. Phobos is filled with what I consider abusive use of overloads - let's not open the door to making it an order of magnitude worse.

D's operator overloading is significantly restricted compared with C++'s. This is very deliberate.

Some features are just not worth it. This is where I play the experience card. Clever code is not going to look clever to you 20 years from now. I don't expect you to believe me. Just remember I said that :-)

> Returning by ref should cover this

It kinda terrifies me that someone would write code like this.

**Comment by 12345swordy** [comment]
> Those tiny examples always look good. But it doesn't scale. It's terrifyingly easy to create impenetrable code with implicit casting overloads. Phobos is filled with what I consider abusive use of overloads - let's not open the door to making it an order of magnitude worse.
> 
> D's operator overloading is significantly restricted compared with C++'s. This is very deliberate.
> 
> Some features are just not worth it. This is where I play the experience card. Clever code is not going to look clever to you 20 years from now. I don't expect you to believe me. Just remember I said that :-)


We can implement implicit conversions without the majority of nonsense of that is c++.

**Comment by WalterBright** [comment]
> We can implement implicit conversions without the majority of nonsense of that is c++.

Even better, we can learn from C++'s experience and not repeat the same mistakes.

**Comment by aliak00** [comment]
@WalterBright Experience is just an argument of contextual convenience. C++ decided to implement implicit conversions as default behavior with copy constructors. It's like, "lets create an iron that's on by default" - of course your house will burn.

One use case I have, where it is exactly what is desired is where you want to wrap dispatching -  effectively a form of lowering applied on UDTs. You want the "lowerer" to be a private implementation details, and you want the result to be usable as the UDT.

It's the basis behind many language features, except doable in user code - aka libraries.

@JinShil That use case is mitigated and *arguably* made better for everyone with explicitness:

```
IOStream stream
source(stream.input);
sink(stream.output);
```

What do you have against the above? Is it just convenience?

`alias this`, it is currently used for two things:
1. I want `A` to be replaceable with `B` (inheritance property, a "pull-from-type" feature) 
1. I want `B` to forward to `A` (compositions property, a "push-to-type" feature)

That's why it sucks. It both wants to take over from a type and give it away to a type.

For the first one, you want protocols/structures, for the second one, you want something like multiple alias this (but without the implicit conversions).

If we can make opDispatch easier to use, then we don't need the second use-case of alias this either.

**Comment by look-at-me** [comment]
> D's operator overloading is significantly restricted compared with C++'s. This is very deliberate.

No it isn't, they function almost identically. If D's was "significantly restricted" no one would use it, but it's not because it's effectively how C++ implements operator overloading. Unless you are referring to user-defined implicit conversion which has a similar syntax but is *not* operator overloading.

**Comment by 12345swordy** [comment]
Oh bloody hell! I didn't expect Basile-z to delete their account!
cc @JinShil 

I am taking this dip over asap, as soon I find some spare time on my hands.

**Pull request closed without merging**
