### PR TITLE
remove XCode project

### PR DESCRIPTION
**Pull request by MartinNowak**
- somewhat unmaintained
- added to .gitignore instead

### CODE REVIEW

**Comment by MartinNowak** [comment]
see #4379

**Comment by jacob-carlborg** [comment]
There reason why it's not maintained is there's no critical need for it. It's not needed for building, and during these two years it's been available I haven't felt the need to updating it. There's a few stray files, probably a few new ones as well that's not included but I think I only ever needed one of the new files and I've worked with a lot of different parts of the compiler when implementing D/Objective-C.

**Comment by MartinNowak** [comment]
I added it to gitignore so you can keep you're project files, but why should we maintain editor specific project files in the upstream repo?

**Comment by jacob-carlborg** [comment]
I'm going to stop arguing this since it's a waste of time. There's no point in adding it to .gitignore, I can do that myself.

**Pull request merged**
