### PR TITLE
fix(nogc): associative array indexing may only cause GC allocation on assignment

### PR DESCRIPTION
**Pull request by ljmf00**
Fix issue 13060.

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

Spec PR: https://github.com/dlang/dlang.org/pull/3444

### CODE REVIEW

**Comment by dkorpel** [comment]
Needs spec update for [Operations That Involve the Garbage Collector](https://dlang.org/spec/garbage.html#op_involving_gc)

**Comment by thewilsonator** [comment]
```
 FAILED targets:
- compilable\nogc.d
- compilable\vgc2.d
- fail_compilation\nogc2.d
```

**Comment by ljmf00** [comment]
> Needs spec update for [Operations That Involve the Garbage Collector](https://dlang.org/spec/garbage.html#op_involving_gc)

Well, the spec is wrong in two ways. Lookups doesn't use GC, as `key in aa` is a lookup.

**Review by thewilsonator — APPROVED** [review]

**Comment by RazvanN7** [comment]
> Well, the spec is wrong in two ways. Lookups doesn't use GC, as key in aa is a lookup.

How is this an argument to not update the spec?

**Comment by ljmf00** [comment]
> > Well, the spec is wrong in two ways. Lookups doesn't use GC, as key in aa is a lookup.
> 
> How is this an argument to not update the spec?

It isn't. In contrast, is a reason to do so :) I updated the spec, see the PR description.

**Review by RazvanN7 — CHANGES_REQUESTED** [review]

**Comment by RazvanN7** [comment]
> It isn't. In contrast, is a reason to do so :) I updated the spec, see the PR description.

Ah, sorry, I missed that. I thought you are arguing that "the spec is wrong in multiple ways so why bother?".

**Review by RazvanN7 — APPROVED** [review]

**Comment by ljmf00** [comment]
> > It isn't. In contrast, is a reason to do so :) I updated the spec, see the PR description.
> 
> Ah, sorry, I missed that. I thought you are arguing that "the spec is wrong in multiple ways so why bother?".

Yeah, I also forgot to cross reference it, sorry :)

**Pull request merged**
