### PR TITLE
fix Issue 16699 - [REG 2.070] stack corruption with scope(exit)

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by aG0aep6G** [comment]
Does this fix [issue 16102](https://issues.dlang.org/show_bug.cgi?id=16102) too?

**Comment by quickfur** [comment]
@WalterBright Awesome! Thanks for the prompt response!

**Comment by MartinNowak** [comment]
Once again!
Bugfixes should always target stable, please rebase and change the target branch.

**Review by MartinNowak — APPROVED** [review]

**Comment by MartinNowak** [comment]
thx

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
Thank you, @MartinNowak and @Dicebot

**Comment by quickfur** [comment]
Just wondering, when this fix will be backported (forward-ported?) to master?

**Pull request merged**
