### PR TITLE
refactor dmacro.d: use arrays instead of pointers

### PR DESCRIPTION
**Pull request by WalterBright**
Start with the interfaces to the functions.

### CODE REVIEW

**Comment by atilaneves** [comment]
LGTM.

**Comment by CyberShadow** [comment]
This got the documentation tester stuck due to an infinite loop in DMD.

http://dtest.dlang.io/results/3001436b6df8cd9744f62c6c0fa2907fe4169432/24bf9b16700727ef017681340e164a8e380749c5/build.log

**Comment by rainers** [comment]
> This got the documentation tester stuck due to an infinite loop in DMD.

Seems like a temporary hick-up unrelated to this PR.

**Review by rainers — APPROVED** [review]

**Comment by WalterBright** [comment]
I like it when problems fix themselves :-)

**Pull request merged**
