### PR TITLE
Fix Issue 19277 - storage class used in alias statement has no effect

### PR DESCRIPTION
**Pull request by thewilsonator**
This may well need a round of deprecation first.

### CODE REVIEW

**Comment by thewilsonator** [comment]
cc @TurkeyMan

**Comment by jacob-carlborg** [comment]
> This may well need a round of deprecation first.

Yes, since it compiles today.

**Review by jacob-carlborg — DISMISSED** [review]
Need to go through the deprecation process.

**Comment by Geod24** [comment]
Yep, deprecation. Also can you add:
```d
alias Dg = scope void delegate();
```

**Comment by thewilsonator** [comment]
Switched to deprecation. What is the standard comment text for marking a deprecation?

> alias Dg = scope void delegate();

added.

**Comment by jacob-carlborg** [comment]
> What is the standard comment text for marking a deprecation?

The existing comments don't seem very standardized. But here's one example:

```d
// @@@DEPRECATED_2.091@@@
// Made an error in 2.087.
// Should be removed in 2.091
```

You can search for `@@@` for more examples.

**Comment by thewilsonator** [comment]
> The existing comments don't seem very standardized

Colour me surprised. Is the length of the deprecation standard?

**Comment by jacob-carlborg** [comment]
> Colour me surprised. Is the length of the deprecation standard?

I think so. There's [1], but I think it's best to ping @wilzbach.

[1] https://github.com/dlang/DIPs/blob/master/DIPs/DIP1013.md

**Comment by JinShil** [comment]
> Is the length of the deprecation standard?

**Comment by JinShil** [comment]
I know @WalterBright  and @andralex want the spect to be so good that a principled vengeful ex could implement the language from it.  So, there should probably be a spec update to accompany this PR, though, I hate doing that kind of work too.

**Comment by thewilsonator** [comment]
Hmm, 
[`alias FuncType = @safe pure nothrow immutable(LocalTime) function();`](https://github.com/dlang/phobos/blob/master/std/datetime/timezone.d#L535)

It seems that `@safe` has no effect, but pure and nothrow _do_:

Given:
```
void main() @safe pure nothrow
{
   FuncType f;
   f();
}
``` 

with the definition
```
struct LocalTime {}
alias FuncType = immutable(LocalTime) function() @safe pure nothrow ;
```

no error is given

however with 

```
struct LocalTime {}
alias FuncType = @safe pure nothrow immutable(LocalTime) function() ;
```
onlineapp.d(7): Error: `@safe` function `D main` cannot call `@system` function pointer `f`.

Any guesses as to why?

**Comment by BorisCarvajal** [comment]
What about `ref` before function/delegate pointers?
We need this now:
```
alias FPrefRet = ref int function(long);  // or using the old alias syntax
FPrefRet fp;
```
because we can't do it directly with neither of:
```
ref int function(long) fp;
int function(long) ref fp;
```
BTW I think the `RetType function|delegate(Params) Attribs VarName;` syntax should be deprecated too in favor of a more unified syntax similar to function literals and the upcoming #9667.
Something like `function StorageClass RetType(Params) Attribs VarName;` so you can use:
```
function ref int(long) fp;    // or
function int(long) ref fp;    // 'ref' is really confusing, is it a stc or an attribute?
```
Sorry, this is another subject but I just remembered thinking about it.

**Review by MoonlightSentinel — DISMISSED** [review]
Invalid deprecation for `ref` returns, e.g.

```
alias F = ref int function();
```

**Comment by MoonlightSentinel** [comment]
Rebased and fixed the handling of function/delegate types. Ready for another review.

**Comment by thewilsonator** [comment]
Thanks, has this fixed the oddities in https://github.com/dlang/dmd/pull/10018#issuecomment-500654296

**Comment by MoonlightSentinel** [comment]
No, but that’s for another pr. Those attributes not applying is a bug, so dmd should not raise an error.

**Comment by thewilsonator** [comment]
Fair enough

**Pull request merged**
