### PR TITLE
fix Issue 15618 - [REG-master] Class member layout has been changed, …

### PR DESCRIPTION
**Pull request by WalterBright**
…ABI needs to be updated?

https://issues.dlang.org/show_bug.cgi?id=15618

### CODE REVIEW

**Comment by WalterBright** [comment]
@yebblies this one too, please!

**Comment by yebblies** [comment]
Can you add a test for putting such a class in the data segment and checking that using it succeeds?  We've had a couple of tricky issues where the ctfe class todt code wasn't kept in sync.

**Comment by WalterBright** [comment]
That's beyond the scope of this, which is just to fix the regression. Such a test would not have exposed this regression, because laying out the fields then filling them in was consistent in the compiler - it was just inconsistent with previous versions.

In any case, I need this pulled because I am rewriting all that code, and one of the things I'm thinking about addressing is the parallel but separate algorithms to lay out fields then fill them in.

What I'm trying to do is duplicate how C++ lays out classes and interfaces. There are already a bunch of test cases to check this for the simple cases, and new cases which fail for the complex ones, which I am trying to address.

**Comment by WalterBright** [comment]
In fact, I have a PR waiting for this that will merge the two membersToDt() functions, which will keep them at least in sync.

**Comment by yebblies** [comment]
Ok, are you planning to clean up the code duplication that you've just introduced in this PR?

**Comment by yebblies** [comment]
I'll merge assuming that you are.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
