### PR TITLE
Fix Issue 22278 - [Conditional Compilation] there should be in and out flags

### PR DESCRIPTION
**Pull request by iK4tsu**
If this is to be accepted, how can I test it?

### CODE REVIEW

**Comment by ljmf00** [comment]
> If this is to be accepted, how can I test it?

You can add a runnable test case into `test/runnable` folder. See the other tests to setup custom compiler flags.

This also needs a changelog entry and spec PR.

**Comment by Geod24** [comment]
For tests:
https://github.com/dlang/dmd/blob/master/test/fail_compilation/reserved_version.d
https://github.com/dlang/dmd/blob/master/test/fail_compilation/reserved_version_switch.d

**Comment by Geod24** [comment]
> You can add a runnable test case into `test/runnable` folder. See the other tests to setup custom compiler flags.

Actually, it's better to avoid `runnable` if your test can go in compilable, as `runnable` tests are the slowest (compilable do not need to link).

**Comment by ljmf00** [comment]
> > You can add a runnable test case into `test/runnable` folder. See the other tests to setup custom compiler flags.
> 
> Actually, it's better to avoid `runnable` if your test can go in compilable, as `runnable` tests are the slowest (compilable do not need to link).

It is needed to properly check if `in` and `out` checks are present and actually runnable when the right flags are applied. See https://github.com/dlang/dmd/blob/0517fc93ceb9e74e979bbbc9de64eb64d610094c/test/runnable/xtest47.d this test as an example.

Most of the flags are not being tested at all tho, like `D_NoBoundsChecks`, only on the tests you described.

**Comment by RazvanN7** [comment]
I don't understand the problem that is being solved here. Could you please provide a code sample highlighting the issue? By the looks of this PR it seems that a predefined version identifier that does nothing is added.

**Comment by iK4tsu** [comment]
I gave an explanation for this in the submitted issue:
> Currently, there is no way within the language to check if contracts are being compiled or not. The only way is to use `version(assert)`, which accomplishes that in a way. The problem is if the user runs unit tests in release mode. The assertions are compiled but contracts are not, leading to the failure of all `assertThrown` checks.

> There are ways to still compile without failures. DMD has the `check` flag that can override the build mode. To run unit tests in release with `in` contracts on, one can pass `-check=in=on` to the compiler. But this still isn't favorable because the flag isn't shared across compilers. LDC for example has `--enable-preconditions=1`.

> Having a language version can standardize this and make it easier when working with this.

> I propose implementing the version flags: D_PreConditions and D_PostConditions for `in` and `out` contracts respectively.

**Comment by iK4tsu** [comment]
TL:DR: if someone has unit tests relying on the outcome of contract failures it may not work if they are not compiled. An example is when unit testing in release mode the thrown assertions.

**Comment by thewilsonator** [comment]
this needs a spec PR

**Comment by Geod24** [comment]
> TL:DR: if someone has unit tests relying on the outcome of contract failures it may not work if they are not compiled. An example is when unit testing in release mode the thrown assertions.

Such unittests would be invalid, as testing for `assert` is invalid.

**Comment by iK4tsu** [comment]
So I need to do a separate PR updating this: https://github.com/dlang/dlang.org/blob/master/spec/version.dd?

**Comment by iK4tsu** [comment]
> > TL:DR: if someone has unit tests relying on the outcome of contract failures it may not work if they are not compiled. An example is when unit testing in release mode the thrown assertions.
> 
> Such unittests would be invalid, as testing for `assert` is invalid.

Why is that?

**Comment by RazvanN7** [comment]
cc @atilaneves @WalterBright

**Review by RazvanN7 — CHANGES_REQUESTED** [review]
This, currently, does not test anything, except that the predefined versions are not used in user code.

**Comment by iK4tsu** [comment]
> This, currently, does not test anything, except that the predefined versions are not used in user code.

How do I do add these tests? The runnable tests talked above?

**Comment by RazvanN7** [comment]
> How do I do add these tests? The runnable tests talked above?

Yes, you can add runnable tests and specify the command line arguments by using the `REQUIRED_ARGS` macro. Take a look at [this](https://github.com/dlang/dmd/blob/master/test/runnable/overload.d#L2)

**Comment by atilaneves** [comment]
> cc @atilaneves @WalterBright

I also fail to see what problem this fixes.

**Comment by ljmf00** [comment]
> > cc @atilaneves @WalterBright
> 
> I also fail to see what problem this fixes.

The same way `D_PIC`, `D_PIE`, `D_NoBoundsChecks`,... and so on, exists? There should be a better way to do this (discover which compiler argument is passed on the compiler), I agree, but that is how is being done right now. This is for `invariant` but you need to do this type of janky things to check whether the contracts are enabled or not. https://github.com/dlang/phobos/blob/12b78bdebfe5ba55f3717f5ae1a5c81be8bac337/std/sumtype.d#L1275-L1290 

There is also situations where this is basically impossible to do nicely, for example, when you are not using asserts.

**Comment by atilaneves** [comment]
> > > cc @atilaneves @WalterBright
> > 
> > 
> > I also fail to see what problem this fixes.
> 
> The same way `D_PIC`, `D_PIE`, `D_NoBoundsChecks`,... and so on, exists? 

I don't think that the existence of other versions has any bearing on adding another one.

> This is for `invariant` 

What does this mean?

> but you need to do this type of janky things to check whether the contracts are enabled or not. 
> https://github.com/dlang/phobos/blob/12b78bdebfe5ba55f3717f5ae1a5c81be8bac33/std/sumtype.d#L1275-L1290

What's the problem with that test?

> There is also situations where this is basically impossible to do nicely, for example, when you are not using asserts.

I don't know what this means. Could you explain, please?

I still don't know what problem this is trying to solve. The way to test in contracts is to break them on purpose in a test and make sure they throw.

**Comment by ljmf00** [comment]
> > > > cc @atilaneves @WalterBright
> > > 
> > > 
> > > I also fail to see what problem this fixes.
> > 
> > 
> > The same way `D_PIC`, `D_PIE`, `D_NoBoundsChecks`,... and so on, exists?
> 
> I don't think that the existence of other versions has any bearing on adding another one.

There is no way to check if `-check=in` or `-check=out` is on or off. That is what this PR tries to add.

> > This is for `invariant`
> 
> What does this mean?
> 
> > but you need to do this type of janky things to check whether the contracts are enabled or not.
> > [dlang/phobos@`12b78bdebfe5ba55f3717f5ae1a5c81be8bac33`/std/sumtype.d#L1275-L1290](https://github.com/dlang/phobos/blob/12b78bdebfe5ba55f3717f5ae1a5c81be8bac33/std/sumtype.d#L1275-L1290)
> 
> What's the problem with that test?

It is really clear that this is a workaround. No one should do this unless they know what they are doing, because this is something implementation-defined and catching throwables that are `Error` or `Error` derivates are just wrong, including catching `AssertError`. This is far from ideal and a better way to check this should be available, avoiding this `try`/`catch` thing.

This situation doesn't perfectly fit here, because this PR is not about `invariant`s but about `in` and `out` contracts. @iK4tsu may expand this to `invariant` or someone should make another PR. Although, it can describe a real-world example of why this is needed.

> > There is also situations where this is basically impossible to do nicely, for example, when you are not using asserts.
> 
> I don't know what this means. Could you explain, please?
> 
> I still don't know what problem this is trying to solve. The way to test in contracts is to break them on purpose in a test and make sure they throw.

That is testing only one part of the branch and not including coverage for everything. Furthermore, that is also considering the `in` contract is used with `assert`. You can create a `in` contract without any `assert`:

```d
import std;

int foo(int* foo)
in {
    if(*foo < 0) *foo = -1;
}
do
{
    return *foo;
}

void main () {
    int a = -2;
	foo(&a).writeln;
    a = 0;
    foo(&a).writeln;
}
```

If you run this with and without checks, the output is different. You can't check this without a janky `static assert` + `__trait(compiles)`.

**Review by atilaneves — APPROVED** [review]

**Comment by atilaneves** [comment]
> > > but you need to do this type of janky things to check whether the contracts are enabled or not.
> > > [dlang/phobos@`12b78bdebfe5ba55f3717f5ae1a5c81be8bac33`/std/sumtype.d#L1275-L1290](https://github.com/dlang/phobos/blob/12b78bdebfe5ba55f3717f5ae1a5c81be8bac33/std/sumtype.d#L1275-L1290)
> > 
> > 
> > What's the problem with that test?
> 
> It is really clear that this is a workaround. No one should do this unless they know what they are doing, because this is something implementation-defined and catching throwables that are `Error` or `Error` derivates are just wrong, including catching `AssertError`. This is far from ideal and a better way to check this should be available, avoiding this `try`/`catch` thing.

Ah. I didn't understand what that code was doing the first time I read it, and now I see what you mean.

**Comment by iK4tsu** [comment]
> @iK4tsu may expand this to invariant or someone should make another PR
Yes, do think `invariant` should have the same feature, that's why I exemplified with `sumtype` above. I did not implement a version for `invariant` in this PR because I feel that they are different enough to separate on their own issues. I'm a bit tight on time at the moment, but I can implement it as soon as I can if there isn't a fix yet.

Thank you for explaining in more detail what this fixes. I thought the runnable test was explicit enough since it does a similar thing. Should I change it to something more explicit?

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
