### PR TITLE
Revert "Merge pull request #13029 from dteod/master"

### PR DESCRIPTION
**Pull request by RazvanN7**
This reverts commit d396a9e89c9e2a7ae687616231ba392c9ba7859d, reversing
changes made to 46bfe386636e846dee719d58b723523f4732c640.

cc @WalterBright @dteod

### CODE REVIEW

**Comment by dteod** [comment]
May I suggest to cherry pick the offended commit instead of wasting one month of work?

**Comment by dteod** [comment]
> This reverts commit [d396a9e](https://github.com/dlang/dmd/commit/d396a9e89c9e2a7ae687616231ba392c9ba7859d), reversing
> changes made to [46bfe38](https://github.com/dlang/dmd/commit/46bfe386636e846dee719d58b723523f4732c640).
> 
> cc @WalterBright @dteod



> This reverts commit [d396a9e](https://github.com/dlang/dmd/commit/d396a9e89c9e2a7ae687616231ba392c9ba7859d), reversing
> changes made to [46bfe38](https://github.com/dlang/dmd/commit/46bfe386636e846dee719d58b723523f4732c640).
> 
> cc @WalterBright @dteod

The two commits are not intimately related. Looks to me there is no regression introduced by d396a9e, could you explain a bit more?

**Comment by RazvanN7** [comment]
I don't know what commit you are referring to. As far as I understand, the PR modifies the limit via a CLI parameter. If we drop the addition of a CLI parameter, what else could be kept from the PR?

**Comment by Geod24** [comment]
@WalterBright 's reasoning is here: https://github.com/dlang/dmd/pull/13029#issuecomment-928843419
To me, it sounds like a good tool to bypass cases where the limit is hit but the recursion would end.
Sure, it's not really something we'd use every day, but what makes 500 a good limit ? Wouldn't 300 be better ? What about 700 or 1000 ? There's no one-size-fits-all and having a switch for it doesn't seem like a bad idea.

If the concern is the growing number of switches, we could expose it through another way, such as `--internal-[${whatever}]` (e.g. the way `--DRT` works).

**Comment by dteod** [comment]
> I don't know what commit you are referring to. As far as I understand, #13106 modifies the limit via a CLI parameter. If we drop the addition of a CLI parameter, what else could be kept from the PR?

Sorry, I misunderstood. I didn't see the last comment in the PR.

**Review by WalterBright — APPROVED** [review]

**Comment by WalterBright** [comment]
> If the concern is the growing number of switches, we could expose it through another way, such as --internal-[${whatever}] (e.g. the way --DRT works).

Hiding it doesn't help. See also https://github.com/dlang/dmd/pull/13029#issuecomment-929997597 where I expounded a bit more, but please reply here.

**Comment by WalterBright** [comment]
> doesn't seem like a bad idea

A switch needs to have a compelling argument _for_ it. Lack of a compelling argument _against_ it is not necessary, i.e. the default decision should never be "let's add a switch".

The best user experience in using the compiler should be:
```
dmd program
```
All switches are bugs.

**Pull request merged**
