### PR TITLE
Fix C++ mangling for substitution of pointers with mismatching qualifier.

### PR DESCRIPTION
**Pull request by skl131313**
https://run.dlang.io/gist/9821400cfd8ae64eba7f964994096aa3
https://godbolt.org/g/81fNBg

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Is the mangling on Windows already correct?

**Comment by skl131313** [comment]
Windows uses Microsoft's specific mangling, it doesn't have this issue as far as I am aware. Its a completely different format anyways.

**Comment by WalterBright** [comment]
Need to create a bug report in bugzilla explaining what the problem is this PR addresses.

**Comment by skl131313** [comment]
I'd rather not deal with that rat's nest, you can close this pull request if you won't accept it without one.

**Comment by WalterBright** [comment]
> rat's nest

I'm curious what the barrier there is for you posting on bugzilla?

**Comment by WalterBright** [comment]
A search on bugzilla of 'skl131313' turns up nothing:
https://issues.dlang.org/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&email1=skl131313&emailreporter1=1&emailtype1=substring&list_id=221733&query_format=advanced

**Review by jacob-carlborg — CHANGES_REQUESTED** [review]
A bugzilla issue or changelog entry is required, otherwise this won’t show up in the changelog.

**Comment by skl131313** [comment]
@WalterBright I don't use the same username for an email and I definitely wouldn't give my email to be publicly viewed on something like bugzilla.

**Comment by Geod24** [comment]
@skl131313 : Thanks for taking the time to find and fix this!
Unfortunately the comparison code has changed significantly since you've made your PR, so I've submitted a reworked version (#8919 ) using your test cases as a base.

**Pull request closed without merging**
