### PR TITLE
Makefile: use same logic for OS and MODEL for test as druntime/phobos/dmd

### PR DESCRIPTION
**Pull request by lionello**
On OSX, make would default to `MODEL=64` for dmd/phobos/druntime, but would use `MODEL=32` (and therefor require 32-bit phobos/druntime) when making the tests. This is counterintuitive as simply running `make` would not make the 32-bit libraries but would require them for the tests.

### CODE REVIEW

**Comment by andralex** [comment]
mmkay...

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
pls take a look at the autotester

**Comment by lionello** [comment]
Not sure why this is failing in win32 and win64. It doesn't even affect win32 and win64 builds.

**Comment by lionello** [comment]
Nevermind, found it.

**Pull request merged**
