### PR TITLE
Add tests for the druntime fix for destroy on large aggregates (issue 21097)

### PR DESCRIPTION
**Pull request by JohanEngelen**
This requires druntime fix: https://github.com/dlang/druntime/pull/3467

### CODE REVIEW

**Review by MoonlightSentinel — CHANGES_REQUESTED** [review]
Druntime tests do not belong into dmd. You should rather add this test in the `test` directory of druntime.

**Comment by RazvanN7** [comment]
@JohanEngelen as @MoonlightSentinel pointed out, this test should be placed in the test directory of druntime. Feel free to close.

**Comment by JohanEngelen** [comment]
@MoonlightSentinel  Ah I didn't know that druntime had its own test dir. Do you have suggestions in which subfolder to add this test?

**Comment by MoonlightSentinel** [comment]
Not really, I don't think there is an appropriate folder ATM. But you can also create a new one.

**Pull request closed without merging**
