### PR TITLE
fix Bugzilla Issue 24749 throw block moved to end of function

### PR DESCRIPTION
**Pull request by WalterBright**
A branch optimization thing.

Doesn't need a test case, there are likely many of these.

### CODE REVIEW

**Comment by WalterBright** [comment]
Strange. I get the same errors in master.

**Comment by WalterBright** [comment]
Disabled the change, let's see what happens with the tests.

**Comment by thewilsonator** [comment]
Please remove the `WIP` label when you are done.

**Comment by WalterBright** [comment]
Roger that.

**Comment by WalterBright** [comment]
Found & fixed the problem.

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
