### PR TITLE
[backend] Improve 64 bit constant code generation

### PR DESCRIPTION
**Pull request by WalterWaldron**
As the commit messages say:
- Fix an erroneous pinhole optimization
- Remove redundant REX prefix for 64 bit register clear
- Improved codegen for moving 64 bit constants to registers

I originally implemented these improvements in the pinhole optimization but it is now done at the source.
I can still include the additions to the pinhole optimization if they are wanted.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Do you have a test case for the fix?

**Comment by WalterWaldron** [comment]
Please, do not merge for now.
I've decided to change my approach: I'll use simpler code in ```movregconst``` and restore my pinhole optimization code.
This enables the improvements for inline assembly code as well.

**Comment by MartinNowak** [comment]
Just make sure to add a comment when updating the pull, so we'll get a notification.

**Comment by WalterWaldron** [comment]
Updated!

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Thanks

**Pull request merged**
