### PR TITLE
C++ small struct test

### PR DESCRIPTION
**Pull request by TurkeyMan**
This unittest shouldn't fail, but there seems to be an ABI issue with small struct's, which needs to be fixed.

https://issues.dlang.org/show_bug.cgi?id=19563

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by TurkeyMan** [comment]
Don't jump to conclusions; I expect this to fail CI, and hopefully motivate someone to fix it ;)

**Comment by WalterBright** [comment]
I don't understand. If there's a bug that needs fixing, and this PR is not fixing, shouldn't it be in bugzilla instead?

**Comment by TurkeyMan** [comment]
The bugzilla issue has been sitting there for months... which means I've been twiddling my thumbs for months.
I figured a working unit test would be more helpful.

**Comment by TurkeyMan** [comment]
I was also interested to see the matrix of targets where this fails.

**Comment by WalterBright** [comment]
I see you added the bugzilla reference after I posted that, thank you. The Bugzilla should also be in the PR title, something like "Test case for Issue 19563 extern(C++) Incorrect ABI passing small struct"

**Comment by look-at-me** [comment]
https://github.com/dlang/dmd/pull/9295

**Pull request closed without merging**
