### PR TITLE
refactor: make functions private where possible in dinterpret.d

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by mathias-lang-sociomantic — CHANGES_REQUESTED** [review]
Same comment about checking the .h files

**Comment by RazvanN7** [comment]
@mathias-lang-sociomantic There were only a few functions which were declared in ctfe.h. How we're good now.

**Review by mathias-lang-sociomantic — APPROVED** [review]

**Comment by mathias-lang-sociomantic** [comment]
Can you squash ? Otherwise looks good.

**Comment by RazvanN7** [comment]
There's the auto-merge-squash label which does it automatically.

**Comment by mathias-lang-sociomantic** [comment]
No that label was removed because it was absued :(

**Comment by RazvanN7** [comment]
@mathias-lang-sociomantic I squashed the commits.

**Comment by RazvanN7** [comment]
Again that annoying failure....

**Pull request merged**
