### PR TITLE
treewide: fix end of file and ensure conformancy with POSIX 3.206

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

This patch removes all trailing newlines and ensures that every file conforms with POSIX 3.206. The intention behind this change is to add a CI check for this in an upcoming PR.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Looks like you need to update generated files too. Eg: https://github.com/dlang/dmd/blob/master/test/runnable/extra-files/runnable-a20.lst

**Comment by ljmf00** [comment]
> Looks like you need to update generated files too. Eg: [https://github.com/dlang/dmd/blob/master/test/runnable/extra-files/runnable-a20.lst](https://github.com/dlang/dmd/blob/master/test/runnable/extra-files/runnable-a20.lst?rgh-link-date=2022-02-10T20%3A03%3A40Z)

Yup. I will try to do it on different PRs to facilitate review. Same about `test/compilable/makedeps_file.d` and `makedeps` related tests.

**Comment by dkorpel** [comment]
Can you rebase this?

**Comment by ljmf00** [comment]
@dkorpel Done. I'll add `pre-commit` hook on a subsequent PR, to avoid mixing changes.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
