### PR TITLE
Fix 23497: Revert #14116 as it introduced a regression

### PR DESCRIPTION
**Pull request by deadalnix**
This is achieved by reverting 4e7c4925772fe6e098d3a0736f25cb4fae4bce0b, which introduced the regression, and adding a new test case that ensure this specific regression doesn't happen again going forward.

### CODE REVIEW

**Comment by deadalnix** [comment]
I'm somewhat disappointed this is taking so long. Now we won't be able to pivot to a nightly on monday to get things going.

When something introduces a regression, one would expect the following to happen:
1. The person who introduced the regression and/or someone familiar with that part of the codebase fixes it promptly. Promptly here means a few hours at most.
2. Short of 1. being an option (people have personal life, cannot be available 24/7, may be confused as to how things should be fixed, and a million other reasons) then the offending code needs to be reverted, and said people must be made aware that this has been done so they can fix it.

The work is not lost: it is in source control, it can be recommitted with the appropriate tweak to fix the problem.

**Comment by thewilsonator** [comment]
Could you refresh the CI by force pushing this branch, IIRC the DAutotest issue should be fixed now.

**Comment by Geod24** [comment]
It doesn't help that the title doesn't say anything about the change itself. Could you edit the commit title to clearly state that this is a revert, then I will merge.

**Comment by dkorpel** [comment]
> I'm somewhat disappointed this is taking so long. Now we won't be able to pivot to a nightly on monday to get things going.

I'm sorry, I saw the issue when you first posted it but forgot to follow up on it. When you pinged me on Discord two days ago I said I didn't have time this weekend, and asked if you were in a hurry to get a fixed nightly. Your response "I typically am not, but this is blocking everything, so if this is what i have to do, then this is what i have to do." did not read like you wanted a nightly by Monday, so I thought I was good.

In any case, here's my fix: https://github.com/dlang/dmd/pull/14686

**Pull request closed without merging**
