### PR TITLE
Revert "fix Issue 23727 - ImportC support imaginary real numbers"

### PR DESCRIPTION
**Pull request by adamdruppe**
Reverts dlang/dmd#14902

### CODE REVIEW

**Comment by RazvanN7** [comment]
cc @WalterBright

**Comment by Herringway** [comment]
Seems pretty simple to me. New code shouldn't depend on deprecated code. ImportC is going to have to handle this on its own when the deprecation moves on. That work should be done now, instead of passing it on to someone else.

It seems kinda disrespectful to push that work to someone who is actively working to remove the feature.

**Comment by WalterBright** [comment]
A better resolution: https://github.com/dlang/dmd/pull/14971

**Comment by RazvanN7** [comment]
@adamdruppe #14971 has been merged and #14977 is on the way. Do you still think we should revert #14902 ?

**Comment by RazvanN7** [comment]
Closing this as we the alternative has already been partly implemented.

**Pull request closed without merging**
