### PR TITLE
remove root.aav dependency from expression.d

### PR DESCRIPTION
**Pull request by WalterBright**
for better encapsulation

### CODE REVIEW

**Comment by yebblies** [comment]
`generateId` takes a `size_t`, how about returning that from `len` instead of casting?

**Comment by WalterBright** [comment]
1. frankly it's silly to use a size_t for this - there's no way anyone is going to have 4 billion identifiers. In general we should be more circumspect in using size_t.
2. 32 bit quantities are faster than 64 bit ones, even on 64 bit machines
3. it's all encapsulated in the dsymbol.d code, where I intend to replace aav with native AAs anyway

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
@andralex So you're pro useless casts?

**Comment by quickfur** [comment]
Pity we can't(?) use Phobos in dmd code; else I'd recommend using `to!int` instead of a cast and be able to sleep well at night.

**Comment by yebblies** [comment]
The cast isn't unsafe (passing the 4bn limit is unlikely), it's just pointless.  Using `to!int` would be just as pointless.

**Pull request merged**
