### PR TITLE
Fix 23073 - scope inference from pure doesn't consider self-assignment

### PR DESCRIPTION
**Pull request by dkorpel**

### CODE REVIEW

**Review by WalterBright — CHANGES_REQUESTED** [review]
You've identified exactly where the problem lies. Upon examining that code, there's more wrong with it than 23073. So I rewrote the implementation, which is https://github.com/dlang/dmd/pull/14374

Please incorporate that into your PR here.

**Comment by dkorpel** [comment]
> Please incorporate that into your PR here.

I can also just close this one, it seems all your PR is missing is tests.

**Comment by WalterBright** [comment]
You deserve the credit for it.

**Comment by RazvanN7** [comment]
@WalterBright is this good to go?

**Review by WalterBright — APPROVED** [review]

**Pull request merged**
