### PR TITLE
Add a `lowering` field for AssignExp to store potential lowerings

### PR DESCRIPTION
**Pull request by RazvanN7**
This PR does the  following:

- ~add a field, `lowering` to `AssignExp` to store the potential lowerings that are done in the frontend.~
- ~use `lowering` to lower array length expressions.~
- add a new AST node `LoweredAssignExp` that inherits from AssignExp and adds a `lowering` field.
- use the new AST node to handle lowerings to array length expressions.
- delete the code in dinterpret that recreates the initial assign expression.
- update `inline.d` to inline the call to the lowering, not the AssignExp since that avoids extra copies.
- update `hdrgen.d` so that if the switch `-vcg-ast` is used we will print the call to the hook not the initial AssignExp. For code that does not use `-vcg-ast` the AssignExp is printed.
- update C++ headers
- fix Issue 23773

cc @WalterBright as this is in line with your work of not generating the hook if in ctfe blocks
cc @teodutu - this needs to be done for all previously implemented templated hooks.

### CODE REVIEW

**Comment by SixthDot** [comment]
Is that the only solution to fix [23773](https://issues.dlang.org/show_bug.cgi?id=23773) ?
I'm concerned by the memory overhead caused by this approach.

**Comment by RazvanN7** [comment]
Fixing 23773 is just a collateral gain of implementing this.

**Comment by SixthDot** [comment]
> its peanuts compared to the memory used by template instances.

expressions, including one of their most common form, Assignment ones, are also copied with template instances, i.e function bodies.

**Comment by ibuclaw** [comment]
The unlowering is memory expensive too.

So that not every AssignExp gets a redundant lowering field, you could make a new derived node `ArrayLengthSetExp : AssignExp`.

**Comment by maxhaton** [comment]
A general solution to link to where an expression was lowered *from* is also needed for error messages (I have worked on this in the past).

**Comment by RazvanN7** [comment]
> So that not every AssignExp gets a redundant lowering field, you could make a new derived node ArrayLengthSetExp : AssignExp.

Yes, that might work, however, that will pollute the codebase with all kinds of different AST nodes, provided we will use this strategy for other lowerings as well. Anyway, compared to the importC ugliness that was added in the semantic phases I guess it's worth a shot.

**Comment by RazvanN7** [comment]
> A general solution to link to where an expression was lowered from is also needed for error messages (I have worked on this in the past).

This should be solved by the approach in this PR.

**Comment by SixthDot** [comment]
> Well, we have to agree on some path going forward

Yes, exactly. Do we waste the effect of the accumulation of the micro efforts made 2 or 3 years ago or not ? People have worked to save 10 megs here, 20 megs theres, etc. and now let's waste 80 megs because of a bug that basically nobody gives a crack about ?

**Comment by SixthDot** [comment]
that will affect the size of all BinaryAssign nodes btw, which are not disallowed as condition.

```d
void main(string[] args)
{
    int a;
    if (a+= 1){} // ok
    if (a= 1){}  // ng
}  
```

To be clear, that PR is going nowhere, trying to fix nothing.

**Comment by RazvanN7** [comment]
@SixthDot As I've explained earlier. The fix for 23773 is just a side effect of adding the lowering field. We plan on doing variations of this approach for all of the hooks.

**Comment by ibuclaw** [comment]
> @SixthDot As I've explained earlier: the fix for 23773 is just a side effect of adding the lowering field. We plan on doing variations of this approach for all of the hooks.

And hopefully a few more things too.  For example, I've just seen someone post this error message.
```
a.d(9): Error: cannot implicitly convert expression `foo(((int[7] __arrayliteral_on_stack2 = [0, 1, 2, 3, 4, 5, 6];) , cast(int[])__arrayliteral_on_stack2))` of type `int[]` to `immutable(int[])`
```

**Comment by RazvanN7** [comment]
@ibuclaw I have implemented the new AST node. cc @SixthDot

**Comment by ibuclaw** [comment]
I think ArraySetLengthExp would be better so that it isn't some black box the backends can't optimize for.

**Comment by RazvanN7** [comment]
@ibuclaw There are multiple lowerings that can be performed from an AssignExp. I was hoping that we could use this class for all and not add a new class for each.

**Comment by SixthDot** [comment]
I'm not blocking anything BTW, I wanted to encourage to think more about alternative solution.

**Comment by RazvanN7** [comment]
> I think ArraySetLengthExp would be better so that it isn't some black box the backends can't optimize for.

The backends can still check the original rhs and lhs expressions for optimizations. However, if you consider that the AST node should be specialized, I can do that but that will result in having an AST node for each AssignExp lowering.

**Review by dkorpel — APPROVED** [review]

**Comment by RazvanN7** [comment]
I have added the "72h no objection -> merge" label.

**Pull request merged**
