### PR TITLE
[REG2.066] Issue 13886 - global.gaggedErrors ICE

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=13886

### CODE REVIEW

**Comment by yebblies** [comment]
No output check?

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Ignore me.

**Comment by 9rnsr** [comment]
Thanks!

**Comment by sinkuu** [comment]
An ICE (on invalid code) seems come to the surface with this PR:
https://issues.dlang.org/show_bug.cgi?id=14146

**Pull request merged**
