### PR TITLE
Beautiful Readme

### PR DESCRIPTION
**Pull request by bistcuite**
I made changes to make readme file beautiful.

### CODE REVIEW

**Comment by dkorpel** [comment]
I think it looks good!

I'm not a fan of adding another file to the root of the repository, can you pull the logo from e.g. https://github.com/dlang/dlang.org/blob/master/images/dlogo.png?

**Comment by bistcuite** [comment]
html heading converted to markdown heading, and `hr` tag converted to `---` markdown command

**Review by rv32ima — COMMENTED** [review]
Like @dkorpel said, let's try avoid adding blobs to the repository where unnecessary.

**Review by rv32ima — CHANGES_REQUESTED** [review]
Please change `src="dlogo.png"` to `src="//dlang.org/images/dlogo.png"` or `src="https://dlang.org/images/dlogo.png"`, or even to where it's stored on GitHub (`https://github.com/dlang/dlang.org/blob/master/images/dlogo.png`)

**Review by WalterBright — APPROVED** [review]

**Pull request merged**
