### PR TITLE
Revert "Issue 9731: implement $(DDOC_PARAGRAPH)"

### PR DESCRIPTION
**Pull request by andralex**
Reverts D-Programming-Language/dmd#4338 because it breaks the pdf build. Enumerated lists should allow code blocks in items.

### CODE REVIEW

**Comment by CyberShadow** [comment]
The problem occurs in `property.dd`, line 123. Currently, the example is inside an `OL` but not inside a `LI`. This is not valid HTML:

http://www.w3.org/TR/html5/grouping-content.html#the-ol-element

> Content model:
>     Zero or more li and script-supporting elements.

**Comment by andralex** [comment]
@CyberShadow cool beans... could you please tend to that?

**Comment by CyberShadow** [comment]
> This is not valid HTML:

This patch is still broken!

Consider:

```
$(FOO
   $(BAR
      $(BAZ
---
...
---
      )
   )
)
```

You may expect that `BAZ` opens before the code block and is closed immediately after.

In reality, this patch closes the `BAZ` tag when the code block starts, and opens a `DDOC_PARAGRAPH` after the code block, which is closed by the `)` which was supposed to close `BAZ`.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by quickfur** [comment]
Oops. I guess I'm gonna hafta start keeping track of parentheses nesting when inserting paragraph macros... Seriously, `highlightText()` is an unmaintainable spaghetti of boolean flags, typical signs of ad hoc structure conflict resolutions... where are range-based algorithms when I need them?!

**Comment by yebblies** [comment]
@quickfur Time to refactor it?

**Comment by quickfur** [comment]
That's what I'm thinking. I was hoping to get the paragraph macro implementation in first, but I suppose it's unavoidable now.

**Comment by quickfur** [comment]
Question: given the following source text:
````
/**
 * This is the first line $(MYMACRO blah
 *
 * blah blah). Is this the second paragraph or what?
 */
````
where should the paragraph macro be inserted?

**Pull request merged**
