### PR TITLE
Heisenbugs in test suite

### PR DESCRIPTION
**Pull request by WalterBright**
I have a number of open PRs that exhibit weird errors in buildkite and semaphoreci. This is to find out where the heisenbugs in the test suite are.

### CODE REVIEW

**Comment by Geod24** [comment]
The Buildkite error is consistent, and triggered by (presumably) a missing import.
The SemaphoreCI is indeed flakey, and I don't quite know what triggers it. I think it runs out of memory (despite having added 4G of RAM...).

**Comment by WalterBright** [comment]
My PRs are all stalled by these test suite bugs.

**Comment by Geod24** [comment]
Regarding Buildkite, we usually try to fix the bug if possible, if not, an easy way out is to temporarily disable it *and ping the maintainers*. I just submitted a PR for this: https://github.com/dlang/ci/pull/418

Regarding the SemaphoreCI, re-triggering help. I am trying to find the cause of the error but I don't mind some help.

**Comment by MoonlightSentinel** [comment]
Maybe run the tests on semaphore sequentially / less parallel jobs and check if it still get's terminated?

**Comment by Geod24** [comment]
I altered a few settings in SemaphoreCI (cancellation policy) to try to make it more user-friendly. I'll see if we can reduce the parallelism. And yeah, Buildkite should be back to normal. Another example why ignoring the CI is bad.

@WalterBright : One thing that blocks us from upgrading SemaphoreCI is PIC support on 32 bits machines. I tried to update the setup but hit a wall: https://issues.dlang.org/show_bug.cgi?id=18798

**Comment by wilzbach** [comment]
@Geod24: as SemaphoreCI is solely to check whether we can still bootstrap with the latest LDC, GDC or DMD we could consider just skipping the 32-bit DMD test if this blocks the upgrade/transition. Better to not test an obscure, unused build than having an unfixable CI setup ;-)

**Comment by ibuclaw** [comment]
I have found that the 32bit compiler segfaults unless built with `HOST_DMD=gdmd`. So one path to upgrade would be to use either gdc or ldc as the host compiler in the 32bit CI.

**Comment by ibuclaw** [comment]
SemaphoreCI is a file locking issue with the gdb tests @MoonlightSentinel was able to reproduce locally.

**Comment by Geod24** [comment]
Closing then, as the heisenbugs have been identified.

**Pull request closed without merging**
