### PR TITLE
Add recent regression test case to CTFE test suite

### PR DESCRIPTION
**Pull request by thewilsonator**
~~Currently finding out which PR Fixed this.~~ It broke somewhere between 2.084.1 to 2.085.0-beta1 and was fixed by #9547 .

### CODE REVIEW

**Review by PetarKirov — APPROVED** [review]
LGTM. The Circle CI failure looks unrelated.

**Comment by wilzbach** [comment]
You need to rebase against upstream master for the CircleCI failures to go away.

**Comment by ZombineDev** [comment]
> You need to rebase against upstream master for the CircleCI failures to go away.

git-tools FTW!

**Comment by thewilsonator** [comment]
> You need to rebase against upstream master for the CircleCI failures to go away.

I know, but I've got an ambiguous reference to `dlang/master` somehow, I'll probably https://www.xkcd.com/1597/ it sometime soon.

**Comment by ZombineDev** [comment]
@thewilsonator

```bash
git clone git@github.com:dlang/dmd
cd dmd
git remote rename origin upstream
git remote add me git@github.com:thewilsonator/dmd
```

To create a local branch:
```bash
git checkout -b my-branch
...
git commit -m 'Message'
git push me my-branch
```

To rebase a local branch to master:
```bash
git checkout master
git pull --ff-only upstream master
git checkout my-branch
git rebase master
git push -f me my-branch
```

To checkout any PR locally:

```bash
# 1. Get git-tools if you don't have them yet:
cd $HOME # Choose a dir to clone git-tools there
git clone https://github.com/wilzbach/git-tools

# 2. Go to the repo for which you want to checkout a PR locally, say dmd
cd $DMD

# 3. Use git-tools to checkout a PR, say #9686
$HOME/git-tools/pr_checkout dlang/dmd/pull/9686

# 4. Rebase to master
git rebase master

# 5. Push the PR branch
$HOME/git-tools/pr_push
```

**Pull request merged**
