### PR TITLE
[WIP] Deprecate alias this for classes

### PR DESCRIPTION
**Pull request by RazvanN7**
Sloppy, fast implementation, just to see the size of the breakage.

### CODE REVIEW

**Review by thewilsonator — COMMENTED** [review]
Nice, needs a changelog.

**Comment by 12345swordy** [comment]
Even though I support this, this needs a dip as this is not a minor change, but a major one.

**Comment by Geod24** [comment]
This would break legit use cases. One example for us:
https://github.com/bosagora/agora/blob/f93cb3006f0501a770c9d01c8227da9b8a427bde/source/agora/common/ManagedDatabase.d#L60

Where the aliased type is a getter function, which returns a pointer to a `struct`.

**Comment by rikkimax** [comment]
> This would break legit use cases. One example for us: https://github.com/bosagora/agora/blob/f93cb3006f0501a770c9d01c8227da9b8a427bde/source/agora/common/ManagedDatabase.d#L60

That absolutely smells of it should be done with scope or reference counting (assuming eliding of calls are possible), not with alias this.

**Comment by RazvanN7** [comment]
I think that there might be legitimate use cases out there and unfortunately I don't know what alternative to propose.

**Comment by 12345swordy** [comment]
> I think that there might be legitimate use cases out there and unfortunately I don't know what alternative to propose.

Hence this needs a DIP, to exploring the alternatives if exist and If they don't exist then the DIP must explain how are they going to be replaced.

**Comment by adamdruppe** [comment]
alias this has a pretty easy definition - it is a last-resort after other look ups - we just need to write it down and make sure the impl is up to spec.

**Comment by 12345swordy** [comment]
> alias this has a pretty easy definition - it is a last-resort after other look ups - we just need to write it down and make sure the impl is up to spec.

I am going to quote this here:
 "In the discussion that ensued, the bigger problem with alias this is that fixing any issues with it will likely cause significant breakage. Andrei suggested that what we really need to do is go back to the drawing board with a DIP for a new feature that replaces and fixes the issues with alias this. We left it at that for now."
 https://forum.dlang.org/post/tesktfsmdglmzbhzypsx@forum.dlang.org

**Comment by RazvanN7** [comment]
cc @Geod24

**Comment by adamdruppe** [comment]
just fix it instead

**Pull request closed without merging**
