### PR TITLE
fix issue 19708 - Can't use __traits(getAttributes, ...)[...] as a type

### PR DESCRIPTION
**Pull request by ghost**
The first part of the fix is simply to extract `Type`s from `TypeExprs` when a `TypeTrait` returning a `TypeTuple` contained some .

The second part is more delicate. ~~A flag used by the `TypeTrait`s was not set correctly because the `TypeTrait` was not directly aliased but wrapper in a `TypeNext`. To fix te problem the type next is replaced by its content after aliasing it.~~ It's fixed by refactoring a bit the feature using a new SCOPE member.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Basile-z** [comment]
Don't auto-merge for now because I may try something with `Scope.flags` to replace `TypeTraits.inAliasDeclaration`.

**Comment by Basile-z** [comment]
Yeah it really looks like using the scope flags fixes a flaw in the original design. There nothing really special anymore in `aliasSemantic` now. :tada:

**Comment by MoonlightSentinel** [comment]
@Basile-z Thank you for picking this up. 

Once this fix is released the workaround should be removed from the spec ( https://dlang.org/spec/attribute.html#uda)

**Comment by thewilsonator** [comment]
So, it this good to go?

**Comment by Basile-z** [comment]
> Once this fix is released the workaround should be removed from the spec

Yes I see that point 4 still uses a Tuple.

> So, it this good to go?

Yes.

**Pull request merged**
