### PR TITLE
[dtoh] append _ to C keywords in addition to C++ keywords

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by thewilsonator** [comment]
This is good to go, failures are unrelated.

**Comment by thewilsonator** [comment]
I'll put together a changelog entry for all of these at the end.

**Review by dkorpel — APPROVED** [review]

**Comment by ibuclaw** [comment]
Why?

**Comment by thewilsonator** [comment]
```
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1805:5: error: expected identifier
    _Alignas = 205u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1806:5: error: expected identifier
    _Alignof = 206u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1807:5: error: expected identifier
    _Atomic = 207u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1810:5: error: expected identifier
    _Generic = 210u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1811:5: error: expected identifier
    _Imaginary = 211u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1812:5: error: expected identifier
    _Noreturn = 212u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1813:5: error: expected identifier
    _Static_assert = 213u,
    ^
/Users/nicholaswilson/d/ldc/ldc/./dmd/frontend.h:1814:5: error: expected identifier
    _Thread_local = 214u,
```

Because they cause errors.

**Pull request merged**
