### PR TITLE
Organize the lexer as a library

### PR DESCRIPTION
**Pull request by RazvanN7**
This is the first step on the way to organizing the compiler as a library. I moved all the lexer files into a new directory called lexer and created a library named lexer.a. I also modified the makefile so that the targets use the generated library instead of the actual source files. The files should be organized better and I think some renamings and code movements are needed to avoid constructions like : import ddmd.lexer.lexer.Lexer;

This is just the posix implementation; still need to update win32.mak

### CODE REVIEW

**Comment by rikkimax** [comment]
A problem with using dmd-fe as a library is with Token/Identifier. The stringtable inside of Identifier gets modified as dmd executes with it initially being set with certain built in tokens. These built in tokens are provided by a module constructor in Token.

This may need to be addressed in a future PR.

**Comment by RazvanN7** [comment]
@rikkimax why is that a problem? It is the user's problem how the stringtable gets modified once he uses the library (the user will have all the necessary tools to modify the stringtable)

**Comment by rikkimax** [comment]
This is why: https://github.com/RazvanN7/dmd/blob/Liblexer/src/ddmd/lexer/tokens.d#L837

```D
static this()
    {
        Identifier.initTable();
        foreach (kw; keywords)
        {
            //printf("keyword[%d] = '%s'\n",kw, tochars[kw].ptr);
            Identifier.idPool(tochars[kw].ptr, tochars[kw].length, cast(uint)kw);
```

As a user of the library I cannot reset this between runs. During a normal execution dmd-fe will populate said stringtable automatically. So after one run that stringtable will contain identifiers that either a) no longer exists (segfault) or b) produce erroneous builds.

I have tried to use dmd-fe as a library in the past, this is a show stopper.

**Comment by yebblies** [comment]
As the large number of files changed should tell you, it's wrong to move identifier/globals/etc into the lexer package as they are not part of the lexer.

Building the lexer without the rest of the compiler is already possible, see https://github.com/yebblies/ddmd
The problem is a lexer is not that interesting (others with better APIs exist), and allowing even a parser is much more complicated.

Shuffling the directories around give more the illusion of progress than actual progress.  A more interesting step would be adding a dub description that can build the lexer and start working on API improvements such as the one @rikkimax is talking about.

Beyond this the next step IMO is splitting out the semantic routines from the AST object definitions, so that when the parser imports the object definitions it doesn't end up pulling in the entire compiler source.  I started on that with statementsem.d (with Walter's sign-off) but it's very tedious and I don't have the time and/or energy for it these days.

**Comment by RazvanN7** [comment]
@yebblies Maybe we can unite our efforts to split the semantic routines from the AST object definitions?

**Comment by yebblies** [comment]
Yeah, that would be nice.  Although I don't generally have a lot of effort to spare these days.

It's probably worth your time to have a read through the comments in #5730

That was as close to ideal as I could get it, with very few files changed and the number of imports reduced, showing that it broke part of the cycle.  The other semantic groups are generally more complex, and include more than just the 'semantic' function.

The easiest would probably be `Initializer::semantic`.  It may also need `toExpression` to be included, and maybe `inferType`.  Once a new module layout is decided, the actual work is mostly just copy+paste and adding `i.` in front of thousands of member variables.

Does that sounds like something you'd be interested in?  If you have the free time for it I can help with the review and merging.

The worst part is that these PRs bitrot almost instantly.  I was considering making automated tooling for it but the source is much less uniform than it was when I finished the D conversion.

**Comment by RazvanN7** [comment]
@andralex @WalterBright  Having the lexer sources in the same directory as the rest of the files makes it impossible to differentiate the lexer imports from anything else. For example: if you want to import the file entity.d you have to write import ddmd.entity instead of ddmd.lexer.entity (which would be ideal).

**Review by andralex — APPROVED** [review]
thx

**Comment by yebblies** [comment]
I feel compelled to point out that while this PR does quite literally "Organize the lexer as a library" it does so in the sense of an 'object library' and not in the sense of making it possible to use the lexer independently from the rest of the compiler frontend.

The existing split of the compiler build into multiple `.a`/`.lib` files was added by me during the D conversion because it allowed me to test that I could link the frontend without the dmd backend present.  The actual test part of this is located [here](https://github.com/RazvanN7/dmd/blob/9f11dc6965be556abbb8840bfa107f03f0a6a394/src/posix.mak#L362) and builds a compiler binary that is incapable of codegen, but can pass the rest of the dmd test suite.  This test ensures that the compiler frontend does not accidentally start depending on any more glue layer or backend symbols - they will cause link errors.

A similar test could be constructed for the lexer - build and link together just the minimal set of modules with a minimal `main` that lexes stdin or something.  This is simple enough to include in the autotester build and will ensure that at no (link-error-inducing) dependencies are accidentally added to the lexer.

**Comment by andralex** [comment]
@yebblies btw do you think it makes logi(sti)cal sense to separate the lexer and parser library? @RazvanN7 made the point there'd be preciously few applications that would need the lexer but not the parser, and those could import the (small) parser library and only use the lexer. Thoughts?

**Comment by yebblies** [comment]
Yes, i think the only requirement should be that you can import/link the lexer without the parser. I expect the whole frontend would live in one repository and be distributed together. The only reason i made a dub package with just the lexer was that was the only part i could extract at the time.

**Pull request merged**
