### PR TITLE
[stable] Move fix for issue 22974 from glue layer to frontend

### PR DESCRIPTION
**Pull request by kinke**
See #13950.

### CODE REVIEW

**Review by maxhaton — APPROVED** [review]

**Comment by kinke** [comment]
Oh wait, I missed that the `|| vd.mangleOverride` was added in the meantime.

**Comment by maxhaton** [comment]
> Oh wait, I missed that the `|| vd.mangleOverride` was added in the meantime.

ok. Does that mean this isn't sufficiently covered by tests? If so could you add one (that would've caught this omission, if I follow correctly)

**Comment by kinke** [comment]
Looks like the test added in https://github.com/dlang/dmd/pull/14008 should cover it just fine. So I guess the `if (d.mangleOverride) return null;` is superfluous at the moment (for VarDecls).

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
This good to go? (Also cc @ibuclaw)

**Review by ibuclaw — APPROVED** [review]
Yeah, seems reasonable to me.

**Pull request merged**
