### PR TITLE
Refactor: remove unnecessary statement scope

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by 9rnsr** [comment]
You can see the diff view ignoring indent changes.
https://github.com/D-Programming-Language/dmd/pull/5174/files?w=1

**Comment by schuetzm** [comment]
Was the removal of the `else` intentional?

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
@schuetzm Yes. the then branch finishes by 
return statement, so the else if is just unnecessary.

**Comment by 9rnsr** [comment]
The phobos failure is definitely unrelated.

**Pull request merged**
