### PR TITLE
cirrusci.sh: Run brew style --fix before installing gnupg

### PR DESCRIPTION
**Pull request by ibuclaw**
CirrusCI OSX is failing again, seeing if this resolves it.

https://cirrus-ci.com/task/5219352065605632?logs=install_prerequisites#L95

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
nope, no dice. This fix will need to be replicated to stable too.

**Comment by ibuclaw** [comment]
> nope, no dice. This fix will need to be replicated to stable too.

I initially ran `style --fix` on the entire Formula directory, but killed the pipeline after 5 minutes.  Just doing individual files at the moment, though I'll stop in a minute because the list is just getting ridiculous.

**Comment by ibuclaw** [comment]
Running it on the folder and it just bombs out and dies.

**Comment by thewilsonator** [comment]
`/usr/local/Homebrew/Library/Homebrew/brew.sh: line 102: /usr/local/Homebrew/Library/Homebrew/shims/scm/git: No such file or directory`
is likely because it is located at [`shims/shared/git`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/shims/shared/git) not `shims/scm/git`

**Comment by thewilsonator** [comment]
Look like `brew`'s offending PR is https://github.com/Homebrew/brew/pull/12170

**Comment by ibuclaw** [comment]
@thewilsonator why did you merge this?

**Pull request merged**
