### PR TITLE
Issue 15186 - Emit better diagnostic for C++ member lookup operators

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Fixes https://issues.dlang.org/show_bug.cgi?id=15186

### CODE REVIEW

**Comment by AndrejMitrovic** [comment]
That's a very bizarre segfault..

```
make[1]: *** [unittest/std/concurrency.run] Segmentation fault (core dumped)
```

Can't reproduce it locally, although I have to build with `MODEL=64` and not 32-bit like the autotester (32-bit builds fail for me).

I'll try to force a re-test.

**Comment by andralex** [comment]
@AndrejMitrovic I think I've seen that before. Are you running inside a VM?

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Nice - thanks!

**Comment by AndrejMitrovic** [comment]
> @AndrejMitrovic I think I've seen that before. Are you running inside a VM?

The 32-bit build fail? Yeah.

P.S. I've had problems with my account and I'm no longer on the [team list](https://github.com/orgs/D-Programming-Language/people). Any way you could add me back so I could start merging some pulls? Yeah, I'm back in the game. :)

**Comment by yebblies** [comment]
> Yeah, I'm back in the game. :)

Welcome back!

**Pull request merged**
