### PR TITLE
Unify path delimiters in win32.mak

### PR DESCRIPTION
**Pull request by e10s**
Currently `'/'` and `'\'` are mixedly used but this PR replaces the former with the latter to avoid possible confusion.

### CODE REVIEW

**Comment by WalterBright** [comment]
It's been like this for 17 years now, and there are no reports of confusion. The trouble with mass changes like this is they make things harder to track with `git blame`. I need a better reason to approve this.

**Comment by e10s** [comment]
Okay, I've been hacking broken win64 build system and found this inconsistency. E.g., `$G/strtold.obj` on win32 against win64's `$D\strtold.obj` and `$G\longdouble.obj` against `$D\longdouble.obj`. In addition, the MAKE program distinguishes `'/'` and `'\'`. Because these confused me, I thought they should be unified for coming hacks.

Overkill? Should be a just follow-up of the recent PR #6562?

**Comment by RazvanN7** [comment]
I agree with this PR not because the inconsistent use of \ and / is confusing, but rather annoying. 
CC @WalterBright

**Comment by ibuclaw** [comment]
I agree with Walter here too, sorry.  Closing as this has stalled.

**Pull request closed without merging**
