### PR TITLE
chore(ctfeexpr): use switch case instead of an if statement

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Looks like you missed something.

**Comment by ljmf00** [comment]
> Looks like you missed something.

Sorry, my vim converted it to lowercase, somehow. Fixed.

**Comment by thewilsonator** [comment]
Please repush, it seems azure has timed out.

**Comment by ibuclaw** [comment]
(Note: smart optimizers will generate a jump table for this, but apparently ldc and gdc aren't one of them).

**Comment by ljmf00** [comment]
> (Note: smart optimizers will generate a jump table for the if condition, but apparently ldc and dmd aren't one of them).

Yes, but in this case its also ugly to have a 120+ chars line of ors.

**Review by RazvanN7 — APPROVED** [review]

**Comment by maxhaton** [comment]
> (Note: smart optimizers will generate a jump table for the if condition, but apparently ldc and dmd aren't one of them).

gcc does not generate a jump table here, ldc does.

**Pull request merged**
