### PR TITLE
Remove RootObject.print method

### PR DESCRIPTION
**Pull request by Geod24**
Following a comment on a previous PR:

"Mixing I/O into a class is usually a failure of encapsulation."
> [Walter Bright](https://github.com/dlang/dmd/pull/8670#discussion_r215821235)

This removes a bunch of versioned/commented out code as well as the `print` method.
I could have left the uncompiled code in, but I might as well clean it up.
Some places (when it precedes an `assert(0)`), `printf` is used instead.

### CODE REVIEW

**Review by jacob-carlborg — APPROVED** [review]

**Comment by Geod24** [comment]
Gotta love spurious CI failures...

**Comment by Geod24** [comment]
@thewilsonator : In this case, it's because it's in a `debug` block.
I aimed not to remove any functionality. Since DMD is compiled with `-release` for distribution, this code is never included in user-facing binary.

**Comment by thewilsonator** [comment]
Fair enough.

**Review by WalterBright — APPROVED** [review]

**Comment by Geod24** [comment]
```
c++ -Wno-deprecated -Wno-narrowing -Wstrict-aliasing -Werror -fno-exceptions -fno-rtti -D__pascal= -DMARS=1 -DTARGET_LINUX=1 -DDM_TARGET_CPU_X86=1 -m64 -fPIC -std=gnu++98 -Idmd/tk dmd/backend/optabgen.c -o ../generated/linux/release/64/optabgen
  (CC)  ROOT_OBJS  dmd/root/newdelete.c
Testing for -no-pie...
c++ -c -o../generated/linux/release/64/newdelete.o -Wno-deprecated -Wno-narrowing -Wstrict-aliasing -Werror -fno-exceptions -fno-rtti -D__pascal= -DMARS=1 -DTARGET_LINUX=1 -DDM_TARGET_CPU_X86=1 -m64 -fPIC -std=gnu++98 -Idmd/root -MMD -MF ../generated/linux/release/64/newdelete.deps dmd/root/newdelete.c
CC="c++" /home/dtest/DAutoTest/work/dl/dmd-2.079.0/dmd2/linux/bin64/dmd -lib -of../generated/linux/release/64/lexer.a -m64 -J../generated/linux/release/64 -L-lstdc++  -version=MARS -fPIC -J../generated/linux/release/64 -w -de -g dmd/console.d dmd/entity.d dmd/errors.d dmd/globals.d dmd/id.d dmd/identifier.d dmd/lexer.d dmd/tokens.d dmd/utf.d dmd/root/array.d dmd/root/ctfloat.d dmd/root/file.d dmd/root/filename.d dmd/root/outbuffer.d dmd/root/port.d dmd/root/rmem.d dmd/root/rootobject.d dmd/root/stringtable.d dmd/root/hash.d
echo "$DEFAULT_DMD_CONF" > ../generated/linux/release/64/dmd.conf
Testing for -no-pie...
/usr/bin/ld: cannot open output file ../generated/linux/release/64/optabgen: No such file or directory
collect2: error: ld returned 1 exit status
posix.mak:534: recipe for target '../generated/linux/release/64/optabgen' failed
make: *** [../generated/linux/release/64/optabgen] Error 1
make: *** Waiting for unfinished jobs....
```

[That's a weird one](http://dtest.dlang.io/results/17bf1546c12b5663d9759fbfcb1175f2984d59d3/66a218436b9b5a4c1ac01507bb4cb64d9035215a/build.log)

**Comment by Geod24** [comment]
Rebased on master to retrigger the doc tester

**Pull request merged**
