### PR TITLE
Fix win32.mak to match posix hierarchy

### PR DESCRIPTION
**Pull request by RazvanN7**
Currently BUILD is hardcoded to release. Since the windows make tool is pretty dumb, it should suffice for now

### CODE REVIEW

**Comment by RazvanN7** [comment]
ping @braddr @andralex @wilzbach

**Review by andralex — APPROVED** [review]

**Comment by andralex** [comment]
Cool, now please follow up with updates to the testing scripts.

**Comment by mathias-lang-sociomantic** [comment]
Will that pose any problem for Digger ? @CyberShadow ?

**Comment by CyberShadow** [comment]
> Will that pose any problem for Digger ?

Not as long as it creates a `src\dmd.exe` as before.

**Comment by RazvanN7** [comment]
@CyberShadow We should update digger to use the executable in generated/ because subject of the follow up PR is going to be to delete the executable in src

**Comment by CyberShadow** [comment]
No problem, ping me when you make that PR

**Comment by wilzbach** [comment]
> Since the windows make tool is pretty dumb

Yeah about that ... how feasible would it be to replace DigitalMars make with GNUMake on Windows? It would at least save us the huge pain of maintaining different files for the same thing...
AFAICT is DigitalMars​ make part of the Windows release? Could it be swapped or are there licensing problems with bundling GNUMake?
I don't use Windows, but it seems that they offer prebuilt releases:

http://gnuwin32.sourceforge.net/packages.html

In the worst case we could use the Windows Makefiles & DigitalMars make to bootstrap GNUMake ...

**Comment by CyberShadow** [comment]
> Yeah about that ... how feasible would it be to replace DigitalMars make with GNUMake on Windows? It would at least save us the huge pain of maintaining different files for the same thing...

I looked into that a while ago, for dlang.org. Essentially it would put us halfway there - GNU make is only half useful without the other GNU utilities, such as `cp`, `rm` etc. Without those, we would likely still need to maintain separate makefiles, or use lots of careful macros to use each platform's native OS/filesystem commands.

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=17522

**Comment by wilzbach** [comment]
> GNU make is only half useful without the other GNU utilities, such as cp, rm etc. Without those, we would likely still need to maintain separate makefiles, or use lots of careful macros to use each platform's native OS/filesystem commands.

Hmm couldn't we download the coreutils on windows too?
Heck, as we only need a specific subsets, we might even be able to implement them in D, e.g.

### rm

```
void main(string[] args)
{
    import std.file, std.getopt;
    bool recursive;
    auto config = getopt(args, "-r", recursive);
    foreach (arg; arg[1 .. $])
    {
        if (recursive) arg.rmdirRecurse;
        else arg.remove;
    }
}
```

**Comment by CyberShadow** [comment]
> Hmm couldn't we download the coreutils on windows too?

Requiring a (any) POSIX toolchain on Windows (Cygwin, GnuWin32, MinGW, msys2, etc.) is one possibility of going forward and away from win32/64.mak.

> Heck, as we only need a specific subsets, we might even be able to implement them in D

Yes. One idea is to implement them directly in DigitalMars Make.

**Pull request merged**
