### PR TITLE
refactor: restore whitespace in func.d

### PR DESCRIPTION
**Pull request by WalterBright**
Restoring to what it was before ddmd.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Pointless wast of time IMO.

**Comment by yebblies** [comment]
It also means this code no longer matches dfmt output.

**Comment by MartinNowak** [comment]
Did you use dfmt during conversion? That would be a good move IMO.

**Comment by yebblies** [comment]
I used dfmt on the manually ported code, and spent a lot of time making magicport's output match dfmt and [filing bugs](https://github.com/Hackerpilot/dfmt/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Ayebblies).

I hope one day we'll have a make rule and autotester check for formatting.

**Comment by MartinNowak** [comment]
Doing this now (after 2.068.1 is merged back into master) would be better than later as we lost a huge part of our but history anyhow.

**Pull request merged**
