### PR TITLE
Debug azure

### PR DESCRIPTION
**Pull request by MoonlightSentinel**

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
Seems like it's a problem with the makefile:

```
src\core\sys\windows\odbcinst.d(158): Deprecation: function `core.sys.windows.odbcinst.SQLInstallTranslatorW` is deprecated - Use SQLInstallTranslatorExW instead
src\core\sys\windows\odbcinst.d(158): Deprecation: function `core.sys.windows.odbcinst.SQLInstallTranslatorW` is deprecated - Use SQLInstallTranslatorExW instead
src\core\internal\dassert.d(143): Deprecation: argument `cast(__c_long_double)v` for format specification `"%Lg"` must be `real`, not `double`
src\core\internal\dassert.d(157): Deprecation: argument `cast(idouble)v` for format specification `"%Lg"` must be `real`, not `idouble`
src\core\internal\dassert.d(147): Deprecation: argument `cast(__c_long_double)cast(real)v` for format specification `"%Lg"` must be `real`, not `double`
src\core\internal\dassert.d(147): Deprecation: argument `cast(__c_long_double)cast(ireal)v` for format specification `"%Lg"` must be `real`, not `double`

unittest
Error: 'unittest' not found

D:\a\1\druntime>dir
 Volume in drive D is Temporary Storage
 Volume Serial Number is E684-5A0E

 Directory of D:\a\1\druntime

10/10/2020  09:33 PM    <DIR>          .
10/10/2020  09:33 PM    <DIR>          ..
10/10/2020  09:29 PM    <DIR>          .circleci
10/10/2020  09:29 PM             1,312 .codecov.yml
10/10/2020  09:29 PM               156 .editorconfig
10/10/2020  09:29 PM    <DIR>          .github
10/10/2020  09:29 PM               136 .gitignore
10/10/2020  09:29 PM             2,493 appveyor.yml
10/10/2020  09:29 PM             2,973 azure-pipelines.yml
10/10/2020  09:29 PM    <DIR>          benchmark
10/10/2020  09:29 PM    <DIR>          changelog
10/10/2020  09:29 PM             2,574 CODEOWNERS
10/10/2020  09:29 PM             3,944 CONTRIBUTING.md
10/10/2020  09:29 PM    <DIR>          def
10/10/2020  09:32 PM        15,139,525 druntime.json
10/10/2020  09:29 PM               207 dub.sdl
10/10/2020  09:32 PM             2,619 errno_c_32mscoff.obj
10/10/2020  09:32 PM    <DIR>          generated
10/10/2020  09:32 PM    <DIR>          import
10/10/2020  09:29 PM                51 Jenkinsfile
10/10/2020  09:32 PM    <DIR>          lib
10/10/2020  09:29 PM             1,361 LICENSE.txt
10/10/2020  09:29 PM    <DIR>          mak
10/10/2020  09:29 PM            15,657 posix.mak
10/10/2020  09:29 PM                18 project.ddoc
10/10/2020  09:29 PM             2,784 README.md
10/10/2020  09:29 PM               492 setmscver.bat
10/10/2020  09:29 PM    <DIR>          src
10/10/2020  09:29 PM    <DIR>          test
10/10/2020  09:33 PM         1,478,144 unittest.exe  // <===
10/10/2020  09:33 PM             1,294 unittest.lib
10/10/2020  09:33 PM         6,151,130 unittest.obj
10/10/2020  09:29 PM             4,559 win32.mak
10/10/2020  09:29 PM             5,244 win64.mak
              21 File(s)     22,816,673 bytes
              13 Dir(s)  12,176,785,408 bytes free

D:\a\1\druntime>exit /B 3 
##[error]Cmd.exe exited with code '3'.
```

**Comment by rainers** [comment]
> Seems like it's a problem with the makefile:

As mentioned in https://github.com/dlang/dmd/pull/11833#issuecomment-706298828 the "not found" message is a misinterpretation of the exit code by Digital Mars make at https://github.com/DigitalMars/Tools/blob/master/make.c#L1705: A crash in the exceutable `unittest` produces a negative result code which then makes the DMC runtime search for other locations of the program: https://github.com/DigitalMars/dmc/blob/master/src/core/SPAWN.C#L332 .

**Comment by rainers** [comment]
> https://github.com/DigitalMars/dmc/blob/master/src/core/SPAWN.C#L332 .

This line suggests that using `.\unittest` to execute it should correctly report the exception code.

**Comment by Geod24** [comment]
> This line suggests that using `.\unittest` to execute it should correctly report the exception code.

Thanks for the confirmation. Then https://github.com/dlang/druntime/pull/3231 should solve this.

**Comment by WalterBright** [comment]
@rainers > A crash in the exceutable unittest produces a negative result code which then makes the DMC runtime search for other locations of the program: https://github.com/DigitalMars/dmc/blob/master/src/core/SPAWN.C#L332 .

Nice work! I'm not sure what the correct fix for spawn.c is, or should I fix make.c? Let me know and I'll get it fixed.

**Comment by rainers** [comment]
> Nice work! I'm not sure what the correct fix for spawn.c is, or should I fix make.c? Let me know and I'll get it fixed.

A simple workaround should be to just check for `status != -1` instead of `>= 0` at https://github.com/DigitalMars/dmc/blob/master/src/core/SPAWN.C#L332 and https://github.com/DigitalMars/dmc/blob/master/src/core/SPAWN.C#L370.

That doesn't support process exit code -1, but allowing that would be a larger refactoring (and maybe doesn't make much sense when implementing the C lib).

**Comment by WalterBright** [comment]
Thanks!

**Comment by WalterBright** [comment]
https://github.com/DigitalMars/dmc/commit/9478d25a677f70dbe4fc0ed317cc5a5e5050ef8b

**Comment by WalterBright** [comment]
Thanks everyone for helping out finding what turned out to be an ancient bug in dmc's runtime library.

**Pull request closed without merging**
