### PR TITLE
Fix issue - simd 32 bytes function argument silced down to 16 bytes when copied to the stack

### PR DESCRIPTION
**Pull request by SSoulaimane**

### CODE REVIEW

**Comment by SSoulaimane** [comment]
The test case may still fail until #9143 is merged.

**Comment by jacob-carlborg** [comment]
Please squash the commits.

**Review by WalterBright — APPROVED** [review]

**Comment by thewilsonator** [comment]
This fails on semaphore.

**Comment by SSoulaimane** [comment]
It's good now.

**Pull request merged**
