### PR TITLE
dwarfdbginf: DWARF array tags should not be ambiguous

### PR DESCRIPTION
**Pull request by ljmf00**
Fixes Issue 22352.

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

Please read the issue report for more context.

### CODE REVIEW

**Comment by ljmf00** [comment]
semaphoreci seems to be failing for unrelated reasons.

**Review by thewilsonator — APPROVED** [review]
LGTM, cc @maxhaton

**Comment by maxhaton** [comment]
This seems fine to me. I was just looking at what LDC, GDC, and C++ compilers do in this situation (specifically I was wondering whether the mangled name was emitted as well as the muggle-readable name).

**Comment by ljmf00** [comment]
> This seems fine to me. I was just looking at what LDC, GDC, and C++ compilers do in this situation (specifically I was wondering whether the mangled name was emitted as well as the muggle-readable name).

Yes, LDC does this way too. It may improve consistency across compilers and remove ambiguous name tags, since I can currently create a struct named `_Array_struct`. This will not be much of an issue if we move to DWARF5 tags (array tag type).

**Comment by thewilsonator** [comment]
please rebase to restart CI

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
