### PR TITLE
[DDMD] Add objc.d to GENSRC

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by yebblies** [comment]
@WalterBright @MartinNowak

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Auto-merge toggled off

**Comment by 9rnsr** [comment]
From `posix.mak`, ObjectC support is enabled only in OSX 64 (`D_OBJC := 1`). IMHO, this change is not necessary so Windows platform doesn't support it.

**Comment by yebblies** [comment]
Ah, that makes sense.

**Pull request closed without merging**
