### PR TITLE
It's now 2015

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by ibuclaw** [comment]
And in 2/3 of a year, it'll be 2016. :)

**Comment by ibuclaw** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Maybe use `__DATE__ + 7` or so?

**Comment by MartinNowak** [comment]
Do we really need to print a copyright preamble at all?

**Comment by WalterBright** [comment]
> Maybe use  __DATE__ + 7  or so?

Won't produce the right result when compiling older versions.

> Do we really need to print a copyright preamble at all?

Many people still assume that no copyright notice equals public domain.

**Pull request merged**
