### PR TITLE
Fix Issue 23874 - -profile=gc segfaults / ICE regression

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WebFreak001** [comment]
seems like this wasn't the root cause causing the segfault in msgpack-d. Are you sure there isn't some more fundamental code that should be changed instead to fix all these profilegc segfaults?

Currently reducing the test case again to try to figure out what's happening

**Comment by RazvanN7** [comment]
There is a possibility that something else is at stake, but from the bug reports (yours and others) this seems to be the problem.

**Comment by WebFreak001** [comment]
found in reduction, but unrelated since it also happens without profile-gc: https://issues.dlang.org/show_bug.cgi?id=23876

**Comment by WebFreak001** [comment]
ah nvm the actual issue is gone, I was just reducing on `master` and not on `stable`.

**Comment by WebFreak001** [comment]
this issue still is in effect:

```d
string myToString()
{
    return "";
}

immutable x = myToString ~ "";
```

**Pull request merged**
