### PR TITLE
fix Issue 22913 - importC: array index expression parsed as cast

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by RazvanN7** [comment]
This should target stable.

**Comment by WalterBright** [comment]
I don't think so, because the cause of the regression is not in stable.

**Comment by ljmf00** [comment]
> I don't think so, because the cause of the regression is not in stable.

So, is it really a regression in the user perspective? I had the idea that regression is only applied to tagged versions.

**Comment by WalterBright** [comment]
That's right.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
