### PR TITLE
[trivial] extern function defs never used

### PR DESCRIPTION
**Pull request by Cauterite**

### CODE REVIEW

**Comment by etcimon** [comment]
lgtm

**Comment by Geod24** [comment]
Please remove the merge commit though.

**Comment by Cauterite** [comment]
@Geod24 that was a lot harder than you made it sound

**Comment by JackStouffer** [comment]
`git fetch origin && git rebase origin/master`

**Comment by Cauterite** [comment]
i'll try to remember that for next time

**Comment by AndrejMitrovic** [comment]
Auto-merge toggled on

**Pull request merged**
