### PR TITLE
move `fill` from `aggregate.d` to `expressionsem.d`

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Comment by ibuclaw** [comment]
A good deal of these are likely to be reverted if merged.

**Comment by thewilsonator** [comment]
well yeah, I have to fix the C++ interface first.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@ibuclaw why? apart from having the C++ interface synced is there anything else that concerns you?

**Comment by ibuclaw** [comment]
> @ibuclaw why? apart from having the C++ interface synced is there anything else that concerns you?

The majority of these are removing functions from the public ABI without considering why they are there in the first place.

That this one was caught by CI is incidental. GDC can't link against current DMD mainline at the moment, so assume that's the same for LDC too.

**Pull request merged**
