### PR TITLE
Fix issue 19329 pragms(lib) and pragma(linkerDirective) can emit dupl…

### PR DESCRIPTION
**Pull request by thewilsonator**
…icate entries to the object

Not sure how to write a test for this

### CODE REVIEW

**Comment by thewilsonator** [comment]
this should be good to go mod tests, cc @TurkeyMan

**Comment by MoonlightSentinel** [comment]
> Not sure how to write a test for this

Maybe create a `dshell` test that builds a library and requests it multiple times using `pragma(...)`?

**Comment by RazvanN7** [comment]
ping @thewilsonator

**Comment by MoonlightSentinel** [comment]
You could also try to override the linker to check the arguments (as done for `dshell/test6952.d`):

E.g.
```d
enum LIB = "uniqueLibraryName1234";

version (AS_TEST)
{
    // Insert actual test here
    pragma(lib, LIB);
   //  ...
}
else:

import std.algorithm;
import std.stdio;
import dshell;

int main(const string[] args)
{
    // Cannot easily override the linker on windows
    if (OS == "windows")
        return DISABLED;

    // Invoked as CC?
    if (args.length > 1)
    {
        const num = args.count!(a => a.canFind(LIB));

        if (num == 1)
            return 0;

        writeln();
        writeln(num ? "Passed `LIB` multiple times!" : "Didn't pass `LIB` at all!");
        writeln(args);
        writeln();
        return 1;
    }

    // Recompile this file as the test defined above
    string cmd = "$DMD -m$MODEL -version=AS_TEST -od=$OUTPUT_BASE " ~ __FILE_FULL_PATH__;
    string[string] env = [
        "DFLAGS": "",
        "CC": args[0],
    ];
    return tryRun(parseCommand(cmd), stdout, stderr, env);
}
```

**Comment by RazvanN7** [comment]
ping @thewilsonator

**Comment by RazvanN7** [comment]
@thewilsonator please add the test suggested by @MoonlightSentinel  so that we can get this in.

**Comment by RazvanN7** [comment]
@ping @thewilsonator

**Comment by thewilsonator** [comment]
https://github.com/dlang/dmd/pull/16849

**Pull request closed without merging**
