### PR TITLE
Reverse parameter order of xopCmp to match extern(C) ABI

### PR DESCRIPTION
**Pull request by ibuclaw**
Required to support dlang/druntime#2025  (and tests will fail until it is pulled also).

### CODE REVIEW

**Comment by ibuclaw** [comment]
Hmm that's interesting, all tests pass.

I'll have to dig up the original patch which reversed these arguments.  Because *something* should have broke.

**Comment by ibuclaw** [comment]
IIRC it was the sort property, which may mean that some test was removed that validates this particular call works.

**Comment by ibuclaw** [comment]
Yep, test was removed (test 5854) in #6827.

**Comment by ibuclaw** [comment]
Re-added test which validates the call to compiler-generated  `__xopCmp()`.

**Comment by jpf91** [comment]
> IIRC it was the sort property, which may mean that some test was removed that validates this particular call works.

The sort property has been removed: https://dlang.org/blog/2017/07/24/new-d-compiler-release-dmd-2-075-0/

**Comment by kinke** [comment]
So this is a rebase of https://github.com/dlang/dmd/pull/5232.

**Comment by ibuclaw** [comment]
@kinke - right, I missed that.  I wrote this independently, but will have a look at yours.

**Comment by kinke** [comment]
It appears to be exactly the same minus a few comments of mine and plus your test. ;)

IIRC, this approach doesn't work for LDC on 32-bit x86. A method `extern(D) int opCmp([ref T this,] ref T rhs)` and a static function `extern(C) int opCmp(ref T this, ref T rhs)` aren't equivalent ABI-wise - the method's `this` would be passed in EAX, while the static function expects both pointers to be passed on the stack. See https://github.com/dlang/dmd/pull/5232#issuecomment-177538912.

The real problem is that a function pointer is used to invoke either an `extern(D)` method or a static function. That's why my last suggestion was using a static function in any case for the TypeInfo's function pointer, even if `opCmp([ref] const T rhs)` does take its argument by reference (=> trampoline).

**Comment by ibuclaw** [comment]
> IIRC, this approach doesn't work for LDC on 32-bit x86. 

Right, but you would have the same problem calling a nested function from a delegate, then using that same delegate to call a method also.

As I said in the other PR, I've chosen to ignore supporting `thiscall` for the moment until a satisfactory solution comes up.

**Comment by kinke** [comment]
As this isn't about `thiscall` but rather about the D ABI on Win32, DMD should be affected by this too and so shouldn't work with the druntime patch.

**Comment by ibuclaw** [comment]
There is no special Windows ABI, unless you mean the non-standard optlink calling convention that DMD unfavourably implements, which would be better off being dropped altogether.

You shouldn't support that in LDC either.

**Comment by kinke** [comment]
Don't know if it's Optlink specific, but it's D's official ABI for Win32 (https://dlang.org/spec/abi.html#function_calling_conventions) and as such also implemented by LDC (for all 32-bit x86 platforms, most likely because that's what inline assembly in druntime/Phobos expects...).

Anyway, I just wanted to emphasize that the revived changes most likely still don't work for DMD on Win32 as long as that ABI isn't ditched, and that something like the enforced static function would be required in the meantime.

**Comment by ibuclaw** [comment]
> Don't know if it's Optlink specific,

The similarities are too uncanny for it to be a coincidence.

https://www.ibm.com/support/knowledgecenter/SSQ2R2_9.5.0/com.ibm.etools.cbl.win.doc/topics/rpsubw30.htm

https://dlang.org/spec/abi.html#function_calling_conventions

**Comment by wilzbach** [comment]
(rebased)

**Comment by wilzbach** [comment]
(rebased)

**Comment by WalterBright** [comment]
> The similarities are too uncanny for it to be a coincidence.

I've never heard of IBM's "optlink" convention, and it has nothing to do with our Optlink linker. A linker does not define a calling convention anyway.

The win32 calling convention goes back to Microsoft's C++ compiler on win32. I tried to be compatible with it.

**Comment by WalterBright** [comment]
> Hmm that's interesting, all tests pass.

Probably because the test cases do not have side effects in the arguments, so reversing the order of non-existent side effects will have no effect.

**Comment by Geod24** [comment]
@ibuclaw : Do you want to pursue this now that GDC is up to date with master ?

**Comment by Geod24** [comment]
Ping @ibuclaw

**Comment by ibuclaw** [comment]
> Ping @ibuclaw 

Well I still need to patch dmd to reverse the arguments. I assume ldc is the same too.

**Comment by ibuclaw** [comment]
Superseded by #13590

**Pull request closed without merging**
