### PR TITLE
update Copyright to 2016

### PR DESCRIPTION
**Pull request by Passw**
ag "1999-2015" -l | xargs -i -t sed -i 's/1999-2015/1999-2016/g' {}

### CODE REVIEW

**Comment by notna123** [comment]
still 2015 ?!?

C:\Users\notna>dmd
DMD32 D Compiler v2.071.1
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright
.
.
.

**Comment by JackStouffer** [comment]
This commit probably hasn't been in a release yet

**Comment by notna123** [comment]
well, obviously... whom and how to ping? Martin? If so, by mail or news/forum? can/will you do taht, please?!

1. imho it's another little example for improvement opportunities in our release process
2. as we face this "issue" every year since years ;) it's time to automate the recent year in the copyright, would you agree?

**Comment by notna123** [comment]
wasn't there a ::trivial:: flag used or recommended for such thing?
if available, how and who would be willing to flag this commit?

**Comment by Geod24** [comment]
> This commit probably hasn't been in a release yet

Correct. There is no one to ping / mail, it will be part of the next minor release automatically (so 2.072.0, not 2.071.2 if it is ever released).

**Comment by JackStouffer** [comment]
@notna123 the only thing fast tracked for releases are regression fixes. Every commit that brought out of the commit history and put into `stable` makes the merge process later on harder.

**Comment by notna123** [comment]
ok, understood, thanks.
still for my gusto it shows we have improvement opportunities. this is just a little thing, but still the impression stays (to outsiders) that even trivial things are not "fixed" for months in dlang... it's July ;)

Thanks for your feedback!!!

**Pull request merged**
