### PR TITLE
[DDMD] [cleanup] Stop using tassert in the glue layer

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by WalterBright** [comment]
Please stop calling changes `[cleanup]` as if they were dirty. They're not. In this particular case, there is a reason they exist in the C++ source - it makes for smaller executables. This reason may not exist for D, but it doesn't make the code 'dirty'.

`[Refactor]` seems more appropriate for this sort of change.

**Comment by yebblies** [comment]
IMO it is dirty, because it leaks the internals of tassert into every file that uses it.  It's not an attack on you, and I do understand the reason this is in the code.

**Comment by WalterBright** [comment]
This adds significant bloat to the executable without benefit.

> it leaks the internals of tassert into every file that uses it.

It's C++, it's the only way to make what tassert does work, tassert is trivial, and I've been using tassert.h this way for 30 years with no problems whatsoever.

**Comment by yebblies** [comment]
> This adds significant bloat to the executable without benefit.

Wrong.  It adds a 0.36% size increase when compiled with dmc.
With gcc it adds 0.057%.  Calling that significant bloat is a lie.

The benefit is that the glue layer files that import tassert can now be converted to D.

**Comment by andralex** [comment]
>Calling that significant bloat is a lie.

Daniel, this is inappropriate and I won't tolerate it. Please keep it professional. Thanks.

**Comment by yebblies** [comment]
Apologies, I'm getting very frustrated.  In my opinion, 0.36% is _not_ significant bloat, and this change is _not_ without benefit.  I would appreciate if you could explain why you view it as significant and why you don't consider allowing automated conversion a benefit.

I can understand not wanting to accept changes that are just churn with no benefit, but if there was no benefit then I wouldn't be doing this.  I'm working on automatic conversion for DDMD, and as I understand it this is something we both want.

**Comment by WalterBright** [comment]
Thank you.

0.36% is significant to me. Bloat, weight, bankruptcy, performance problems, all happen by allowing creeping smaller bits through. Keeping things lean and fast is a constant vigilance sort of thing, or you wake up one day and discover you're bankrupt. dmd is meant to be lean and fast, and 0.36% is definitely on the radar.

Anyhow, helping ddmd translation out is a good reason. Redo for the glue layer code only which is dealt with by the ddmd translator, and I'll pull it.

(Note that dmd does this optimization in its D code generation!)

**Comment by yebblies** [comment]
> 0.36% is significant to me. Bloat, weight, bankruptcy, performance problems, all happen by allowing creeping smaller bits through. Keeping things lean and fast is a constant vigilance sort of thing, or you wake up one day and discover you're bankrupt. dmd is meant to be lean and fast, and 0.36% is definitely on the radar.

IMO this is a sort of slipperly slope argument, and while it is not completely without merit, it is not sufficient justification.  DMD's allocation patterns make this amount negligible, and the strings will only need to be loaded in the event of an assertion failure, which is as far as you can get from the fast path.  I think your stance puts too much importance on executable size at a cost to ease of understanding the code.

> Anyhow, helping ddmd translation out is a good reason. Redo for the glue layer code only which is dealt with by the ddmd translator, and I'll pull it.

Ok, but I'm not sure how to do this cleanly without dropping use of `tassert` from the glue layer completely.  Is that acceptable?

> (Note that dmd does this optimization in its D code generation!)

I was a little surprised that dmc doesn't appear to do string pooling.

**Comment by WalterBright** [comment]
> Ok, but I'm not sure how to do this cleanly without dropping use of  tassert  from the glue layer completely. Is that acceptable?

Yes. Just use `<assert.h>`.

**Comment by yebblies** [comment]
Updated.

**Comment by yebblies** [comment]
> Yes. Just use `<assert.h>`.

`assert.h` isn't actually used when building with dmc.  Just removing the tassert include makes it pick up whichever is used in `mars.h`.

**Comment by yebblies** [comment]
All green.

**Comment by WalterBright** [comment]
thanks!

**Comment by yebblies** [comment]
Thanks.

**Pull request merged**
