### PR TITLE
optimize _d_interface_cast() and _d_dynamic_cast()

### PR DESCRIPTION
**Pull request by WalterBright**
It could still be better.

### CODE REVIEW

**Comment by WalterBright** [comment]
This is a draft, don't pull it yet!

**Comment by WalterBright** [comment]
Can we please fix or remove this time-wasting test:
```
core.exception.OutOfMemoryError@src\core\internal\gc\impl\conservative\gc.d(512): Memory allocation failed
----------------
0x00007FF6D9771AF7 in rt.deh._d_createTrace at D:\a\1\s\druntime\src\rt\deh.d(47)
0x00007FF6D977227A in rt.deh_win64_posix._d_throwc at D:\a\1\s\druntime\src\rt\deh_win64_posix.d(254)
0x00007FF6D94A66A1 in core.exception.onOutOfMemoryError at D:\a\1\s\druntime\src\core\exception.d(704)
0x00007FF6D96EA9F0 in core.internal.gc.impl.conservative.gc.ConservativeGC.mallocNoSync at D:\a\1\s\druntime\src\core\internal\gc\impl\conservative\gc.d(512)
0x00007FF6D96FB319 in core.internal.gc.impl.conservative.gc.ConservativeGC.runLocked!(mallocNoSync, mallocTime, numMallocs, ulong, uint, ulong, const(object.TypeInfo)).runLocked at D:\a\1\s\druntime\src\core\internal\gc\impl\conservative\gc.d(316)
0x00007FF6D96EA7EA in core.internal.gc.impl.conservative.gc.ConservativeGC.malloc at D:\a\1\s\druntime\src\core\internal\gc\impl\conservative\gc.d(484)
0x00007FF6D96E965D in core.internal.gc.proxy.gc_malloc at D:\a\1\s\druntime\src\core\internal\gc\proxy.d(30)
0x00007FF6D96F84C2 in core.internal.gc.impl.conservative.gc.__unittest_L4985_C18 at D:\a\1\s\druntime\src\core\internal\gc\impl\conservative\gc.d(4999)
0x00007FF6D96FFCAB in void core.internal.gc.impl.conservative.gc.__modtest()
0x00007FF6D94230FB in test_runner.doTest at D:\a\1\s\druntime\src\test_runner.d(73)
0x00007FF6D9422F0F in test_runner.testModules at D:\a\1\s\druntime\src\test_runner.d(44)
0x00007FF6D9422CDE in test_runner.tester at D:\a\1\s\druntime\src\test_runner.d(25)
0x00007FF6D94E07CB in core.runtime.runModuleUnitTests at D:\a\1\s\druntime\src\core\runtime.d(596)
0x00007FF6D9773F54 in rt.dmain2._d_run_main2.runAll at D:\a\1\s\druntime\src\rt\dmain2.d(488)
0x00007FF6D9773E9E in rt.dmain2._d_run_main2.tryExec at D:\a\1\s\druntime\src\rt\dmain2.d(462)
0x00007FF6D9773CC0 in rt.dmain2._d_run_main2 at D:\a\1\s\druntime\src\rt\dmain2.d(521)
0x00007FF6D97731D8 in rt.dmain2._d_run_main at D:\a\1\s\druntime\src\rt\dmain2.d(321)
0x00007FF6D94233B2 in test_runner._d_cmain!().main at D:\a\1\s\druntime\src\core\internal\entrypoint.d(29)
0x00007FF6D97BF794 in __scrt_common_main_seh at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288)
0x00007FFDD55E7AC4 in BaseThreadInitThunk
0x00007FFDD5B9A4E1 in RtlUserThreadStart
```

**Comment by WalterBright** [comment]
This is a step towards resolving https://issues.dlang.org/show_bug.cgi?id=24335

**Review by thewilsonator — APPROVED** [review]
Apart from the confusing/plain wrong documentation, this looks good.

**Comment by thewilsonator** [comment]
Please fix the documentation in a follow up PR

**Comment by WalterBright** [comment]
Yes, I'll be improving it. Thank you.

**Pull request merged**
