### PR TITLE
convert for() for modules[] into foreach()

### PR DESCRIPTION
**Pull request by WalterBright**
A trivial refactor. This one is ok because `modules` is local and someone else isn't going to be adding to it while in the loops.

### CODE REVIEW

**Review by ibuclaw — APPROVED** [review]

**Comment by ibuclaw** [comment]
Hmm. Looks like there are some linker errors in the Jenkins testsuite.

**Comment by ZombineDev** [comment]
Yeah, I tried restarting Jenkins twice to see if the failures were spurious, but the link errors were reproduced consistently.

**Comment by ibuclaw** [comment]
@ZombineDev and master is fine?

**Comment by ZombineDev** [comment]
It looks this PR is not at fault as [there are](https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/activity) other PRs having problems and most of the errors look IO related. [This](https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fdmd/detail/PR-7170/2/pipeline/210) build points to a disk space problem. @MartinNowak can you take a look?

**Comment by wilzbach** [comment]
Used the `git commit --amend --no-edit` trick to restart all CIs. Hopefully this time they like this PR more :)

**Pull request merged**
