### PR TITLE
fix gdc (2.066.x) compilation

### PR DESCRIPTION
**Pull request by MartinNowak**
- disable extern __gshared array declarations

### CODE REVIEW

**Comment by MartinNowak** [comment]
Not sure what commit fixed this (between 2.066.1 and 2.067.0) or if some workaround exists.
For now we don't need the declarations, so it's better to fix compilation with gdc.

**Comment by WalterBright** [comment]
This is going to put a serious monkey wrench into converting the glue code to D. @ibuclaw can you investigate, please?

**Comment by MartinNowak** [comment]
> This is going to put a serious monkey wrench into converting the glue code to D. @ibuclaw can you investigate, please?

It's a dmd front-end bug, we already know that, the same error happens w/ dmd-2.066.1.

**Comment by WalterBright** [comment]
What are the prospects for upgrading gdc?

**Comment by WalterBright** [comment]
The workaround I made here works:

https://github.com/dlang/dmd/pull/6033

**Comment by MartinNowak** [comment]
I could swear I tried replacing TYMAX, but probably only one of them.

**Comment by MartinNowak** [comment]
Found an even nicer workaround.

**Comment by ibuclaw** [comment]
Ok, that is bizarre to me.  I could have sworn that compiler binaries were built against 2.067.

**Comment by ibuclaw** [comment]
@jpf91 - gcc-4.9.4 was released last week.  This could be an excuse to build new binaries. :-)

**Comment by jpf91** [comment]
>  gcc-4.9.4 was released last week. This could be an excuse to build new binaries. :-)

Sure. I'd like to have a fix for http://bugzilla.gdcproject.org/show_bug.cgi?id=231 first though, it's a serious regression.

**Comment by MartinNowak** [comment]
When adhering to GCC's release cycle, you should stick to one DMD front-end version (only point release updates) per Major GDC release IMO.
Since even 5.2 started with 2.066.1 I'd only expect gdc-6.x to have a newer front-end.
This implies being more up to date with the merging though, e.g. so that gdc-7 can get the latest front-end once it's released.

**Comment by jpf91** [comment]
> When adhering to GCC's release cycle

We don't really do that right now though. GCC updates are just an excuse to release updated binaries. As long as GDC is not integrated into GCC I'll just backport all changes to older GDC versions and we'll ideally have one release per frontend version.

However, 2.067 was updated quickly to 2.068 so the 2.067 GDC code was never stable (IIRC GDC issue 231 is present in all 2.067 commits, so no 2.067 GDC version can build GTKd). Once 231 is fixed we can do a 2.068 release.

**Comment by ibuclaw** [comment]
Yes, I've being saying something to that effect for the last 3 years now.  Until we are accepted though... :-)

**Comment by MartinNowak** [comment]
> Yes, I've being saying something to that effect for the last 3 years now. Until we are accepted into gcc though... :-)

Well it could become an acceptance criteria that you run a completely different release process, so might be better to adopt in advance.

**Pull request merged**
