### PR TITLE
Fix Issue 21282 - mixin of AliasSeq "cannot alias an expression"

### PR DESCRIPTION
**Pull request by BorisCarvajal**

### CODE REVIEW

**Comment by WalterBright** [comment]
@BorisCarvajal looks like your fix is better.

**Comment by WalterBright** [comment]
Oops, closed the wrong one!

**Comment by BorisCarvajal** [comment]
You closed that one, xD

**Comment by thewilsonator** [comment]
Hmm can you repost? Cirrus seems to have died.

**Comment by UplinkCoder** [comment]
@WalterBright it would have been good, to give tricky internal changes, like this one more eyes to look at.

**Comment by CyberShadow** [comment]
I noticed that this change allowed more things, possibly more than intended or should be allowed:

```d
struct S
{
	int a, b;
	alias args = typeof(this).tupleof;
}

void main()
{
	S s;
	int i = s.args[0];
}
```

Generally, getting values through an alias to a field in the type and some implicit context was not possible.

**Pull request merged**
