### PR TITLE
Sort switch list in help text

### PR DESCRIPTION
**Pull request by CyberShadow**
Q: How many programmers does it take to sort a list?

### CODE REVIEW

**Comment by WalterBright** [comment]
So far, it has taken 3 :-)

**Comment by zachthemystic** [comment]
3 programmers and a mystic, perhaps. --version precedes -vgc and -vtls, no?

**Comment by CyberShadow** [comment]
~~No because -vgc and -vtls follow the existing pattern where the actual switch is -v, and gc and tls are "extensions" to it. If we were to ignore this pattern, then we'd also put~~

You know what, I don't care enough about this to get into a bikeshedding argument.

**Comment by zachthemystic** [comment]
Okay!

**Pull request merged**
