### PR TITLE
[trivial] fix loc of TypeMixin

### PR DESCRIPTION
**Pull request by BorisCarvajal**
I made a change a month ago but I committed it with the lines swapped.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by wilzbach — DISMISSED** [review]
Shouldn't there be a test for this?

**Comment by BorisCarvajal** [comment]
This was an oversight in #10629, when I put together all the changes in the last branch I pasted the line in wrong position getting the loc of the left parentheses instead of the token itself.
But it really doesn't matter, this loc was only used to fix this marginal case (and the only difference you can see with this patch is in the mixin generated file):
```
int[] v = new int[mixin // mixin expansion happens here
        (    // not here
         ...)];
```

**Comment by wilzbach** [comment]
> and the only difference you can see with this patch is in the mixin generated file

Then why not add this to the test suite?

**Comment by Geod24** [comment]
👍 with @wilzbach .
Adding it to the test-suite ensure this cannot regress. Someone refactoring the lexer 5 years from now will have no idea if they introduce this regression.
And as you mentioned, it's trivial to test it.

**Comment by thewilsonator** [comment]
Lets just fix this.

**Pull request merged**
