### PR TITLE
run tests w/ 32-bit binaries

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Any idea how to reduce test load? 14 runners at 30 minutes each is quite some load we're putting on a free service.

**Comment by WalterBright** [comment]
The load can be reduced substantially by merging many of the files in test/runnable into one file, or even making them imports of another file.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
See https://github.com/dlang/dmd/pull/5908

**Comment by MartinNowak** [comment]
Doesn't look like this actually passes Travis-CI.

**Comment by MartinNowak** [comment]
The annoying cpp_a test is failing on OSX 32-bit, apparently with a dwarfeh error.
https://travis-ci.org/dlang/dmd/jobs/142414609#L2997

**Pull request merged**
