### PR TITLE
Add a changelog for DIP25-by-default (PR10805)

### PR DESCRIPTION
**Pull request by Geod24**
This was forgotten in the original PR (#10805 )

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by jondegenhardt — COMMENTED** [review]
Since changelog entries are read by a wide variety of readers, it might be helpful to include a brief description and perhaps a link to the DIP. Reading the DIP, there's a line or two in the abstract that appears to sum thing up briefly. Pulling lines from the DIP text, perhaps something like:

> With DIP 25, "Sealed references" enabled, it is impossible in safe code to have `ref` refer to a destroyed object.

I'm not an expert in this DIP, and the changelog should be accurate, but if something like the above is accurate and fair summary of the DIP then it would seem useful to add it.

**Comment by thewilsonator** [comment]
Good idea.

**Comment by Geod24** [comment]
@jondegenhardt : Thanks, much appreciated. Indeed we should do a much better job with our changelog. I can't tell how many times I've been through them looking for when a feature was introduced and why.

I have expanded the description quite a bit, and included a code example with the fix.

The deprecation message is also quite good IMO, so I hope that this, combined will be informative enough (people don't always read changelog, so unfortunately good compiler message >>> good changelog entry).

**Review by jondegenhardt — APPROVED** [review]
Very nice, thanks for making this change.

**Pull request merged**
