### PR TITLE
ctfeCast(): push allocations up the stack

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
```
Test fail_compilation/fail105.d failed: expected rc == 1, but exited with rc == 0
```

**Comment by thewilsonator** [comment]
Please rebase.

**Comment by WalterBright** [comment]
Oh, great. I did this with the github editor, which is clearly using CR line endings, while the original is CR-LF.

CR-LF endings should be purged with fire from the repository.

**Comment by jacob-carlborg** [comment]
> Oh, great. I did this with the github editor, which is clearly using CR line endings

"CR line endings", you're not referring old line endings that was used on Classic Mac OS (before OS X)?

**Pull request merged**
