### PR TITLE
Convert fp.c to fp.d

### PR DESCRIPTION
**Pull request by JinShil**
I don't really know what I'm doing here, but it seems to work.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
cc @WalterBright

**Review by PetarKirov — APPROVED** [review]
Only 2 more to go ;)

**Comment by wilzbach** [comment]
Hehe once all the C++ relicts are gone, building DMD could be as easy as `dmd -i ..` . Of course, building the backend separately is still preferred for faster builds and one needs to generate the VERSION file etc. and run optabgen, but this is still pretty cool!

**Comment by jacob-carlborg** [comment]
Yeah. `strtold.c` is pretty annoying for anyone using DMD as a library. The frontend depends on it for formatting floating point numbers when using the Microsoft C runtime.

**Comment by JinShil** [comment]
> Yeah. strtold.c is pretty annoying for anyone using DMD as a library.

Yeah, strtold.c worries me the most.  Hey @rainers, I saw you ported longdouble.c to D.  What would it take to persuade you to do strtold.c too?  Would "pretty please" suffice?

**Comment by MartinNowak** [comment]
Looks like this has broken the nightly build on FreeBSD. Any idea? Maybe libm is missing during linking but the previous C++ version managed to not link the functions?

**Comment by jacob-carlborg** [comment]
> Looks like this has broken the nightly build on FreeBSD. Any idea?

Broken how? Doesn't build? Doesn't link? Doesn't run?

**Comment by MartinNowak** [comment]
Sorry forgot the link https://buildkite.com/dlang/build-release/builds/217#e9c51485-15a5-4b83-8b37-ed04dc988750/6-15211.

**Comment by MartinNowak** [comment]
> Maybe libm is missing during linking

Though dmd seems to add that https://github.com/dlang/dmd/blob/95189b63de6644106fc564b747943a0999fd5f27/src/dmd/link.d#L683.

**Comment by jacob-carlborg** [comment]
Would be nice to have the verbose output of the DMD command to see the linker command it's using.

**Comment by MartinNowak** [comment]
`cc ../generated/freebsd/release/32/dmd.o -o ../generated/freebsd/release/32/dmd -m32 -Xlinker --export-dynamic ../generated/freebsd/release/32/backend.a ../generated/freebsd/release/32/lexer.a -L/usr/home/vagrant/old-dmd/dmd2/freebsd/bin32/../lib32 -Xlinker -Bstatic -lphobos2 -Xlinker -Bdynamic -lpthread -lm`
Might be related to the age of the FreeBSD libc version (8.4) though feclearexcept should be available all the way back. Or maybe the D header is wrong.
Unfortunately blocks the 2.086.0-beta.1 for now and I can't definitely say when I'll have time to look into this.

**Comment by MartinNowak** [comment]
Would temporarily reverting this be a viable option so that we gain some time to sort this out?

**Comment by MartinNowak** [comment]
@JinShil @wilzbach @jacob-carlborg

**Comment by JinShil** [comment]
> Would temporarily reverting this be a viable option so that we gain some time to sort this out?

Probably not.  There would be too many other changes that would also need to be reverted.  I'm thinking...

**Comment by JinShil** [comment]
Is there anyone that actually uses FreeBSD that we can call on?  @jmdavis?

**Comment by JinShil** [comment]
I think we can work around the issue with code like this:

```D
static if (TARGET_FREEBSD)
{
    int statusFE() { return 0; }
    int  testFE() { return 1; }
    void clearFE() { }
}
else
{
    int statusFE()
    {
        return 0;
    }

    int testFE()
    {
        return fetestexcept(FE_ALL_EXCEPT);
    }

    void clearFE()
    {
        feclearexcept(FE_ALL_EXCEPT);
    }
}
```

**Comment by jacob-carlborg** [comment]
> Might be related to the age of the FreeBSD libc version (8.4) though feclearexcept should be available all the way back. Or maybe the D header is wrong.

"These functions first appeared in FreeBSD 5.3." [1]

[1] https://www.freebsd.org/cgi/man.cgi?query=feclearexcept&sektion=3

**Comment by jmdavis** [comment]
Well, taking a quick look at `/usr/include/fenv.h`, both of those functions are marked with `inline` (as is pretty much everything in that header file). `/usr/include/c++/v1/cfenv` and `/usr/include/c++/v1/tr1/cfenv` then provide prototypes for those functions so that they're in `std::`, but my guess is that because they're `inline`, no actual functions are generated to link against. The code just always gets inlined. And when I do a dump on libc's .so file, those functions aren't there. The same goes with dumping libc.a. So, that would imply that we would actually have to copy the implementations of these functions in order to use them. :|

**Comment by MartinNowak** [comment]
Here is what we need https://github.com/freebsd/freebsd/commit/a38603b0b57960e07b576fdc7c8ed64d919770d0 available since FBSD-10.0.
Some more details on C99's extern/inline semantics [Storage classes of inline functions - C99](https://en.wikipedia.org/wiki/Inline_function#C99).
I'll try to update the images to FBSD-10 then.

**Comment by MartinNowak** [comment]
Images updated (https://github.com/dlang/installer/commit/65f9dca56dc0be3a3e916d2bb78eb9941f3d3ccd) builds upcoming soon.

**Comment by jacob-carlborg** [comment]
> Images updated (dlang/installer@65f9dca) builds upcoming soon.

Not that I understand how `build_all.d` works but only comments were changed.

BTW, this issue wasn't triggered by the CI environments because they're already running FreeBSD 11?

**Comment by MartinNowak** [comment]
> Not that I understand how `build_all.d` works but only comments were changed.

It's the documentation on where to get/how to build the vagrant boxes for release building.

**Comment by MartinNowak** [comment]
Of course I also updated the images of the nightly builders to use the new vagrant boxes.
https://buildkite.com/dlang/build-release/builds/229

**Pull request merged**
