### PR TITLE
Optional monitors

### PR DESCRIPTION
**Pull request by yglukhov**
This PR introduces optional monitors feature.
The whole idea is that Object doesn't contain __monitor field anymore.
TypeInfo_Class will hold a monitor offset, if a class has one (by marking class declaration with @monitor attribute), or 0.
Monitor lookup is done with a hash map, if monitorOffset is 0.
The hash map is protected by a primitive RW spin lock.
Monitor finalization will only lookup for monitors, if a monitor was allocated at least once for the type of object being finalized.

druntime counterpart: https://github.com/D-Programming-Language/druntime/pull/789
discussion: http://forum.dlang.org/thread/xpliectmvwrwthamquke@forum.dlang.org

### CODE REVIEW

**Comment by andralex** [comment]
I'm in favor of this. The current backward-compatible approach is the way to go, though I agree with @MartinNowak in the long run we may envision complete deprecation.

Please rebase and let's push this through. Thanks!

**Comment by DmitryOlshansky** [comment]
Half a year later w/o merging this patch the idea still looks sexy to me.
@MartinNowak any plans to move on this in any of 2 competing plans?

**Comment by andralex** [comment]
Well what's going on?

**Comment by andralex** [comment]
"All checks have failed"

**Comment by MartinNowak** [comment]
> Half a year later w/o merging this patch the idea still looks sexy to me.
> @MartinNowak any plans to move on this in any of 2 competing plans?

Yes, I'm still opposed to adding a global hash and the [outlined plan](https://github.com/D-Programming-Language/dmd/pull/3547#issuecomment-57909912) still makes sense.
Furthermore having monitor support on all classes creates ownership/attribute issue for the monitor (https://github.com/MartinNowak/phobos/commit/8cf0ec29ad65ac2a13bd6917b4ff3da0fdea5ab0#diff-4e008aedb3026d4a84f58323e53bf017R4883).
I don't have the capacity to pull this story, but starting by adding an `@(Object.Monitor)` UDA and recognizing that in the compiler should be fairly trivial (e.g. look at the objective-c changes).

**Comment by ibuclaw** [comment]
> recognize monitor UDA and deprecate synchronizing on classes without it

Let's proceed with stage 1 for when 2.071 opens then?

Do we have available documentation / rationale on the deprecated features page?  Or a DIP?

**Comment by MartinNowak** [comment]
> Do we have available documentation / rationale on the deprecated features page? Or a DIP?

Sure, a small entry on http://dlang.org/deprecate.html would be nice, a DIP is overkill though.

**Pull request closed without merging**
