### PR TITLE
d_do_test: Use flock instead of File.lock on SemaphoreCI

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
`File.lock` (which uses `fcntl`) doesn't work properly on recent Ubuntu,
so use `flock()` as a fallback.

### CODE REVIEW

**Comment by wilzbach** [comment]
Hmm, is there a bug report about this?

If we can't use Phobos, I don't think we should version it, but only use flock as a lot of people use "newish" Ubuntu and thus might run into such weird problems.

**Comment by Geod24** [comment]
DMD x86 failed anyway, are you sure that's the issue ?

**Comment by MoonlightSentinel** [comment]
That's weird, it fixed the bug locally (tested on Ubuntu 18.04.4 through WSL2).

**Comment by MoonlightSentinel** [comment]
> If we can't use Phobos, I don't think we should version it, but only use flock as a lot of people use "newish" Ubuntu and thus might run into such weird problems.

`flock` doesn't work with certain file systems (e.g. NFS IIRC) so using  it by default would also cause problems for other users.

Anyway, I'll close this for now because it's probably not a proper fix.

**Comment by ibuclaw** [comment]
Isn't the problem rather gdb15729.sh ?  It seems to be always present in the last few lines of the failed CI run.

**Pull request closed without merging**
