### PR TITLE
Fix 16701 - Remove Restriction of "package.d" Source File Module Forc…

### PR DESCRIPTION
**Pull request by dkorpel**
…ed to All Lowercase

### CODE REVIEW

**Comment by adamdruppe** [comment]
So this would fix that one issue, but the larger issue with package.d is that the compiler forces a filename at all. It should work like the rest of the language, where the filename can match the module name, or it can be told to it.

This change would actually make it even more inconsistent with the rest of the language, by still requiring a filename, but, for once, not being case sensitive.

(that said i do see the practical benefit of being case insensitive if you wanna force the name, but i still maintain that oyu shouldn't be forcing the name at all)

**Comment by dkorpel** [comment]
> It should work like the rest of the language, where the filename can match the module name, or it can be told to it.
> (...) you shouldn't be forcing the name at all

I don't follow, what names are being forced to what exactly? A package module must be called "package.d" because it is special, I wouldn't want it to be called something else.

**Comment by adamdruppe** [comment]
There is zero justification for it to be special (and in fact, it goes directly counter to the stated justification for the feature in the first place, to maintain compatibility with old code!). THAT is the inconsistency with the rest of the language, and the root cause of most these bugs.

**Comment by dkorpel** [comment]
> There is zero justification for it to be special (and in fact, it goes directly counter to the stated justification for the feature in the first place, to maintain compatibility with old code!).

What is the compiler supposed to do with `import some_folder;` then, if not locate a "package.d" inside it?

**Comment by dkorpel** [comment]
> to be consisted with everything else

What "everything else"? The only other special file I know of is `object.d`, which is also checked with `FileName.equals`. File extensions are also checked with `FileName.equals`. "package.d" being checked with `strcmp` is the inconsistency.

**Comment by dkorpel** [comment]
> with every other `package.d`, everything in the std and druntime, filename seems to follow the lower, snake case, even in libraries around, everything is lower case

This PR doesn't change those files, nor does it change the style convention.

**Comment by dkorpel** [comment]
> If that change goes in, we'll need to also update DCD to handle this
> 
> https://github.com/dlang-community/DCD/blob/2bfd3d004ff7eda2428353d2ab44f389dfd5b8e0/src/dcd/server/autocomplete/complete.d#L476-L485

I don't see any case-sensitive filename checks in the linked code

**Comment by dkorpel** [comment]
> It doesn't change that but it introduce that possibility now

The compiler isn't there to enforce a style guide. It would be especially weird if it enforces a casing style on "package.d" and nothing else.

**Comment by dkorpel** [comment]
> it builds the path with `package.d|di` that are expected to be lower case

I don't see code that expects it to be lower case. `exists()` is not case-sensitive on Windows.

**Comment by adamdruppe** [comment]
> It would be especially weird if it enforces a casing style on "package.d" and nothing else.

When it is looking up modules normally, it assumes the file name matches the module name (unless you give it a list of files, in which case it ignores the name and just checks the module definition - which it doesn't allow for package.d lol).

But when it uses the module name to guess the filename, that is case sensitive because module names are case sensitive in D. The underlying filesystem might return a case-insensitive answer though, which can cause trouble, so the style guide recommends always using all lowercase module names. But on linux, for example, the lookup is case sensitive in D and in the filesystem.

**Comment by dkorpel** [comment]
> What about other filesystems?

This only affects Windows, which has a case insensitive file system. On Linux it's still case sensitive. I don't know what 'other' filesystems you're talking about.

> It introduce unnecessary complexity

I'm not a fan of the fact that Windows has a case-insensitive file system and its associated complexity, but DMD releases on Windows and adheres to its choice in most cases. The only exceptions I know of being this PR and https://github.com/dlang/dmd/pull/14261 . You could have a stance of enforcing casing even on Windows, but why only "package.d" and not everything else?

> one improvement would be to get rid of the need of package.d as adam suggested

I agree, but that's for a later PR. This is a trivial fix.

**Comment by Geod24** [comment]
> So this would fix that one issue, but the larger issue with package.d is that the compiler forces a filename at all. It should work like the rest of the language, where the filename can match the module name, or it can be told to it.

Actually the filename really *should* the module name. Anything else breaks too easily.
Regarding `package.d[i]` itself, it would be consistent with the way we treat extensions. I don't really like removing this restriction personally, as I don't think it does any harm, but I don't have a strong opinion one way or the other.

@dkorpel : I don't see any test, and I don't see any change to the lookup code though, so I'm not sure it "fully" work ?

**Comment by RazvanN7** [comment]
@dkorpel can you add a test for this?

**Comment by dkorpel** [comment]
Done. auto-tester failure looks unrelated:
> core.exception.AssertError@std/experimental/logger/core.d(1908): unittest failure

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
