### PR TITLE
Remove unused imports.

### PR DESCRIPTION
**Pull request by veelo**
This completes `dimport.d` in https://github.com/orgs/dlang/projects/41.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by veelo** [comment]
@RazvanN7 You can mark `dimport.d` as complete in https://github.com/orgs/dlang/projects/41. I guess I got lucky with my first pick, I don't expect all files to be this easy ;-)

**Comment by RazvanN7** [comment]
@veelo Thanks for your contribution! Unfortunately,  there's still some work that this module requires. We also need to get rid of the scope import since scopes are used only during semantic analysis. Also, note that this will also require some modifications once we get to extracting semantic information from the `module.d` file. I suspect functions such as `resolve` and `load` will need to be moved from `module.d` to other semantic files and that will in turn require modifications to `dimport.d`. So, at the very least we need to get rid of `import dmd.scope` before considering the item completed.

**Comment by veelo** [comment]
Alright, I'll see if I can manage. Should this be mentioned in [CONTRIBUTING.md#refactoring-the-dmd-ast](https://github.com/dlang/dmd/blob/master/CONTRIBUTING.md#refactoring-the-dmd-ast), @RazvanN7?

**Comment by RazvanN7** [comment]
@veelo I don't think that's necessary since the contributing guide is not going to cover all of the potential scenarios. It's just a way to help contributors kickstart their contributions and I will be managing and helping along the way.

**Comment by RazvanN7** [comment]
@thewilsonator Yes, we can just put the import inside the `version(none)` block if that's the case.

**Comment by ibuclaw** [comment]
Knock wood this won't cause more undefined references in old buggy compilers that I still need to support. :-)

(#16138)

**Comment by veelo** [comment]
> @thewilsonator Yes, we can just put the import inside the `version(none)` block if that's the case.

I suspect your are talking past eachother :-) @thewilsonator is talking about https://github.com/veelo/dmd/blob/fa8f603dceba739c65d79bf0386c7ce09347e2a2/compiler/src/dmd/dimport.d#L74, which is a "scoped import", and @RazvanN7 is talking about https://github.com/veelo/dmd/blob/fa8f603dceba739c65d79bf0386c7ce09347e2a2/compiler/src/dmd/dimport.d#L17, which is the "scope import". Correct?

**Comment by RazvanN7** [comment]
Indeed, you are right!

**Pull request merged**
