### PR TITLE
fix Issue 23014 for Win32 and Win64

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
@rainers I am going slightly batty with this. For 32 bit MSCOFF Windows, -m32, dmd generates the same code as cl. But it seg faults. Can you see what I'm doing wrong here?

**Comment by WalterBright** [comment]
The frustrating thing is, I compile the test case locally, and link with VS link, and it works fine.

**Comment by WalterBright** [comment]
Here's where we stand with this:

1. Azure pipelines (Windows_DMD_latest x86-OMF) successful, the errors are from some other problem plaguing all PRs
2. Azure pipelines (Windows_VisualD_LDC x86-mscoff_MinGW) fails because it is not linking in LIBCMT.LIB. That library is required for the MultiThreadedC code. I don't know who is in charge of MinGW, maybe @ibuclaw ?
3. All other win32omf and win64 models fail with a seg fault. They all work on my machine, and I am dead in the water on this.

**Comment by rainers** [comment]
As mentioned in the comments to https://issues.dlang.org/show_bug.cgi?id=20737: "The TLS directory is not generated into the executable. It's not linked in because there is no reference to _tls_index in the object file as dmd assumes _tls_index==0 when directly building an executable.

If you compile with -c and link separately, the TLS directory exists and the program runs without problems."

So a simple workaround: when not linking with druntime (which has a reference to `_tls_index`), do not assume that `_tls_index==0`. The Microsoft Compiler also doesn't do this optimization.

**Comment by WalterBright** [comment]
@rainers trying your suggestion...

**Comment by WalterBright** [comment]
That's not working, either, though now mars1.d is asserting.

**Comment by rainers** [comment]
> That's not working, either, though now mars1.d is asserting.

I suspect that either mars1.d assumes something about TLS that's changed now, or the change uncovered a different issue. I don't see any assert on the reported line, though.

Indeed, building mars1.d with dmd 2.103 and via `-c -O -inline -m64` trips the assert, too.

**Comment by WalterBright** [comment]
I see:
```
core.exception.AssertError@runnable\mars1.d(1986): Assertion failure
```
and the line in mars1.d is:
```
    assert(byteswap(xx) == 0x34F2);
```
compiled as:
```
D:\a\1\s\generated\windows\release\64\dmd.exe -conf= -m64 -Irunnable -mcpu=native -O -inline -odD:\a\1\s\compiler\test\test_results\runnable -ofD:\a\1\s\compiler\test\test_results\runnable\mars1_3.exe  runnable\mars1.d 


D:\a\1\s\compiler\test\test_results\runnable\mars1_3.exe  --DRT-testmode=run-main
```

**Comment by WalterBright** [comment]
Well, that's certainly bad code! Got it fixed now.

@RazvanN7 @ibuclaw could you please look into the failing Ming test? It needs to link in LIBCMT.LIB.

**Comment by rainers** [comment]
> could you please look into the failing Ming test? It needs to link in LIBCMT.LIB.

LIBCMT is not a distributable library, it must not be added unconditionally. The MinGW builds use the redistributable shared runtime and links with one of the lib*/mingw/msvcrt*.libs.

**Comment by WalterBright** [comment]
@rainers then I don't know what to do. The VC builds need LIBCMT.LIB to reslove the _tls_??? names.  There's no compiler switch for MinGW.

**Comment by rainers** [comment]
> The VC builds need LIBCMT.LIB to reslove the _tls_??? names. There's no compiler switch for MinGW.

The appropriate C runtime is included by the lines right above where you added libcmt (I think this line just has to be removed). It can be selected by `-mscrtlib`. See it's help for information on mingw handling.

**Comment by WalterBright** [comment]
@rainers The Ming version:
```
D:\a\1\s\druntime>"D:\a\1\s\dm\path\make.exe" -f win64.mak MODEL=32mscoff "DMD=D:\a\1\s\generated\Windows\RelWithAsserts\Win32\dmd.exe" "VCDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\." "CC=C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx86\x86\cl.exe" "MAKE=D:\a\1\s\dm\path\make.exe" unittest test_mingw   || exit /B 5 
"D:\a\1\s\generated\Windows\RelWithAsserts\Win32\dmd.exe" -m32mscoff -conf= -O -release -preview=dip1000 -preview=fieldwise -w -version=_MSC_VER_ -Isrc -Iimport -version=druntime_unittest -version=CoreUnittest -unittest -checkaction=context -ofunittest.exe -main src\object.d   src\core\atomic.d  src\core\attribute.d  src\core\bitop.d  src\core\builtins.d  src\core\checkedint.d  src\core\cpuid.d  src\core\demangle.d  src\core\exception.d  src\core\factory.d  src\core\int128.d  src\core\lifetime.d  src\core\math.d  src\core\memory.d  src\core\runtime.d  src\core\simd.d  src\core\time.d  src\core\vararg.d  src\core\volatile.d   src\core\gc\config.d  src\core\gc\gcinterface.d  src\core\gc\registry.d   src\core\internal\abort.d  src\core\internal\atomic.d  src\core\internal\attributes.d  src\core\internal\convert.d  src\core\internal\dassert.d  src\core\internal\destruction.d  src\core\internal\entrypoint.d  src\core\internal\execinfo.d  src\core\internal\hash.d  src\core\internal\moving.d  src\core\internal\parseoptions.d  src\core\internal\postblit.d  src\core\internal\qsort.d  src\core\internal\spinlock.d  src\core\internal\string.d  src\core\internal\switch_.d  src\core\internal\traits.d  src\core\internal\utf.d  src\core\internal\lifetime.d   src\core\internal\array\appending.d  src\core\internal\array\arrayassign.d  src\core\internal\array\comparison.d  src\core\internal\array\construction.d  src\core\internal\array\equality.d  src\core\internal\array\casting.d  src\core\internal\array\capacity.d  src\core\internal\array\concatenation.d  src\core\internal\array\duplication.d  src\core\internal\array\operations.d  src\core\internal\array\utils.d   src\core\internal\backtrace\dwarf.d  src\core\internal\backtrace\elf.d  src\core\internal\backtrace\handler.d  src\core\internal\backtrace\libunwind.d  src\core\internal\backtrace\macho.d  src\core\internal\backtrace\unwind.d   src\core\internal\container\array.d  src\core\internal\container\common.d  src\core\internal\container\hashtab.d  src\core\internal\container\treap.d   src\core\internal\elf\dl.d  src\core\internal\elf\io.d   src\core\internal\gc\bits.d  src\core\internal\gc\os.d  src\core\internal\gc\pooltable.d  src\core\internal\gc\proxy.d  src\core\internal\gc\impl\conservative\gc.d  src\core\internal\gc\impl\manual\gc.d  src\core\internal\gc\impl\proto\gc.d   src\core\internal\util\array.d  src\core\internal\util\math.d   src\core\internal\vararg\aarch64.d  src\core\internal\vararg\sysv_x64.d   src\core\stdc\assert_.d  src\core\stdc\complex.d  src\core\stdc\config.d  src\core\stdc\ctype.d  src\core\stdc\errno.d  src\core\stdc\fenv.d  src\core\stdc\float_.d  src\core\stdc\inttypes.d  src\core\stdc\limits.d  src\core\stdc\locale.d  src\core\stdc\math.d  src\core\stdc\signal.d  src\core\stdc\stdarg.d  src\core\stdc\stddef.d  src\core\stdc\stdint.d  src\core\stdc\stdio.d  src\core\stdc\stdlib.d  src\core\stdc\string.d  src\core\stdc\tgmath.d  src\core\stdc\time.d  src\core\stdc\wchar_.d  src\core\stdc\wctype.d   src\core\stdcpp\allocator.d  src\core\stdcpp\array.d  src\core\stdcpp\exception.d  src\core\stdcpp\memory.d  src\core\stdcpp\new_.d  src\core\stdcpp\string.d  src\core\stdcpp\string_view.d  src\core\stdcpp\typeinfo.d  src\core\stdcpp\type_traits.d  src\core\stdcpp\utility.d  src\core\stdcpp\vector.d  src\core\stdcpp\xutility.d   src\core\sync\barrier.d  src\core\sync\condition.d  src\core\sync\config.d  src\core\sync\exception.d  src\core\sync\event.d  src\core\sync\mutex.d  src\core\sync\rwmutex.d  src\core\sync\semaphore.d   src\core\sys\bionic\err.d  src\core\sys\bionic\fcntl.d  src\core\sys\bionic\stdlib.d  src\core\sys\bionic\string.d  src\core\sys\bionic\unistd.d   src\core\sys\darwin\crt_externs.d  src\core\sys\darwin\dlfcn.d  src\core\sys\darwin\err.d  src\core\sys\darwin\execinfo.d  src\core\sys\darwin\fcntl.d  src\core\sys\darwin\ifaddrs.d  src\core\sys\darwin\pthread.d  src\core\sys\darwin\stdlib.d  src\core\sys\darwin\string.d   src\core\sys\darwin\mach\dyld.d  src\core\sys\darwin\mach\getsect.d  src\core\sys\darwin\mach\kern_return.d  src\core\sys\darwin\mach\loader.d  src\core\sys\darwin\mach\nlist.d  src\core\sys\darwin\mach\port.d  src\core\sys\darwin\mach\semaphore.d  src\core\sys\darwin\mach\stab.d  src\core\sys\darwin\mach\thread_act.d   src\core\sys\darwin\netinet\in_.d   src\core\sys\darwin\sys\cdefs.d  src\core\sys\darwin\sys\event.d  src\core\sys\darwin\sys\mman.d  src\core\sys\darwin\sys\sysctl.d   src\core\sys\freebsd\dlfcn.d  src\core\sys\freebsd\err.d  src\core\sys\freebsd\execinfo.d  src\core\sys\freebsd\netinet\in_.d  src\core\sys\freebsd\pthread_np.d  src\core\sys\freebsd\stdlib.d  src\core\sys\freebsd\string.d  src\core\sys\freebsd\time.d  src\core\sys\freebsd\unistd.d   src\core\sys\freebsd\sys\_bitset.d  src\core\sys\freebsd\sys\_cpuset.d  src\core\sys\freebsd\sys\cdefs.d  src\core\sys\freebsd\sys\elf_common.d  src\core\sys\freebsd\sys\elf.d  src\core\sys\freebsd\sys\elf32.d  src\core\sys\freebsd\sys\elf64.d  src\core\sys\freebsd\sys\event.d  src\core\sys\freebsd\sys\link_elf.d  src\core\sys\freebsd\sys\mman.d  src\core\sys\freebsd\sys\mount.d  src\core\sys\freebsd\sys\sysctl.d   src\core\sys\dragonflybsd\dlfcn.d  src\core\sys\dragonflybsd\err.d  src\core\sys\dragonflybsd\execinfo.d  src\core\sys\dragonflybsd\netinet\in_.d  src\core\sys\dragonflybsd\pthread_np.d  src\core\sys\dragonflybsd\stdlib.d  src\core\sys\dragonflybsd\string.d  src\core\sys\dragonflybsd\time.d   src\core\sys\dragonflybsd\sys\_bitset.d  src\core\sys\dragonflybsd\sys\_cpuset.d  src\core\sys\dragonflybsd\sys\cdefs.d  src\core\sys\dragonflybsd\sys\elf.d  src\core\sys\dragonflybsd\sys\elf32.d  src\core\sys\dragonflybsd\sys\elf64.d  src\core\sys\dragonflybsd\sys\elf_common.d  src\core\sys\dragonflybsd\sys\event.d  src\core\sys\dragonflybsd\sys\link_elf.d  src\core\sys\dragonflybsd\sys\mman.d  src\core\sys\dragonflybsd\sys\socket.d  src\core\sys\dragonflybsd\sys\sysctl.d   src\core\sys\elf\package.d   src\core\sys\linux\config.d  src\core\sys\linux\dlfcn.d  src\core\sys\linux\elf.d  src\core\sys\linux\epoll.d  src\core\sys\linux\err.d  src\core\sys\linux\errno.d  src\core\sys\linux\execinfo.d  src\core\sys\linux\fcntl.d  src\core\sys\linux\fs.d  src\core\sys\linux\ifaddrs.d  src\core\sys\linux\io_uring.d  src\core\sys\linux\link.d  src\core\sys\linux\perf_event.d  src\core\sys\linux\sched.d  src\core\sys\linux\stdio.d  src\core\sys\linux\string.d  src\core\sys\linux\termios.d  src\core\sys\linux\time.d  src\core\sys\linux\timerfd.d  src\core\sys\linux\tipc.d  src\core\sys\linux\unistd.d   src\core\sys\linux\netinet\in_.d  src\core\sys\linux\netinet\tcp.d   src\core\sys\linux\sys\auxv.d  src\core\sys\linux\sys\eventfd.d  src\core\sys\linux\sys\file.d  src\core\sys\linux\sys\inotify.d  src\core\sys\linux\sys\mman.d  src\core\sys\linux\sys\signalfd.d  src\core\sys\linux\sys\socket.d  src\core\sys\linux\sys\sysinfo.d  src\core\sys\linux\sys\xattr.d  src\core\sys\linux\sys\time.d  src\core\sys\linux\sys\prctl.d   src\core\sys\netbsd\dlfcn.d  src\core\sys\netbsd\err.d  src\core\sys\netbsd\execinfo.d  src\core\sys\netbsd\stdlib.d  src\core\sys\netbsd\string.d  src\core\sys\netbsd\time.d   src\core\sys\netbsd\sys\elf.d  src\core\sys\netbsd\sys\elf32.d  src\core\sys\netbsd\sys\elf64.d  src\core\sys\netbsd\sys\elf_common.d  src\core\sys\netbsd\sys\event.d  src\core\sys\netbsd\sys\featuretest.d  src\core\sys\netbsd\sys\link_elf.d  src\core\sys\netbsd\sys\mman.d  src\core\sys\netbsd\sys\sysctl.d   src\core\sys\openbsd\dlfcn.d  src\core\sys\openbsd\err.d  src\core\sys\openbsd\execinfo.d  src\core\sys\openbsd\pthread_np.d  src\core\sys\openbsd\pwd.d  src\core\sys\openbsd\stdlib.d  src\core\sys\openbsd\string.d  src\core\sys\openbsd\time.d  src\core\sys\openbsd\unistd.d   src\core\sys\openbsd\sys\cdefs.d  src\core\sys\openbsd\sys\elf.d  src\core\sys\openbsd\sys\elf32.d  src\core\sys\openbsd\sys\elf64.d  src\core\sys\openbsd\sys\elf_common.d  src\core\sys\openbsd\sys\link_elf.d  src\core\sys\openbsd\sys\mman.d  src\core\sys\openbsd\sys\sysctl.d   src\core\sys\posix\arpa\inet.d  src\core\sys\posix\aio.d  src\core\sys\posix\config.d  src\core\sys\posix\dirent.d  src\core\sys\posix\dlfcn.d  src\core\sys\posix\fcntl.d  src\core\sys\posix\grp.d  src\core\sys\posix\iconv.d  src\core\sys\posix\inttypes.d  src\core\sys\posix\libgen.d  src\core\sys\posix\locale.d  src\core\sys\posix\mqueue.d  src\core\sys\posix\netdb.d  src\core\sys\posix\poll.d  src\core\sys\posix\pthread.d  src\core\sys\posix\pwd.d  src\core\sys\posix\sched.d  src\core\sys\posix\semaphore.d  src\core\sys\posix\setjmp.d  src\core\sys\posix\signal.d  src\core\sys\posix\spawn.d  src\core\sys\posix\stdio.d  src\core\sys\posix\stdlib.d  src\core\sys\posix\string.d  src\core\sys\posix\strings.d  src\core\sys\posix\syslog.d  src\core\sys\posix\termios.d  src\core\sys\posix\time.d  src\core\sys\posix\ucontext.d  src\core\sys\posix\unistd.d  src\core\sys\posix\utime.d   src\core\sys\posix\net\if_.d   src\core\sys\posix\netinet\in_.d  src\core\sys\posix\netinet\tcp.d   src\core\sys\posix\stdc\time.d   src\core\sys\posix\sys\filio.d  src\core\sys\posix\sys\ioccom.d  src\core\sys\posix\sys\ioctl.d  src\core\sys\posix\sys\ipc.d  src\core\sys\posix\sys\mman.d  src\core\sys\posix\sys\msg.d  src\core\sys\posix\sys\resource.d  src\core\sys\posix\sys\select.d  src\core\sys\posix\sys\shm.d  src\core\sys\posix\sys\socket.d  src\core\sys\posix\sys\stat.d  src\core\sys\posix\sys\statvfs.d  src\core\sys\posix\sys\time.d  src\core\sys\posix\sys\ttycom.d  src\core\sys\posix\sys\types.d  src\core\sys\posix\sys\uio.d  src\core\sys\posix\sys\un.d  src\core\sys\posix\sys\utsname.d  src\core\sys\posix\sys\wait.d   src\core\sys\solaris\dlfcn.d  src\core\sys\solaris\elf.d  src\core\sys\solaris\err.d  src\core\sys\solaris\execinfo.d  src\core\sys\solaris\libelf.d  src\core\sys\solaris\link.d  src\core\sys\solaris\stdlib.d  src\core\sys\solaris\time.d  src\core\sys\solaris\sys\elf.d  src\core\sys\solaris\sys\elf_386.d  src\core\sys\solaris\sys\elf_amd64.d  src\core\sys\solaris\sys\elf_notes.d  src\core\sys\solaris\sys\elf_SPARC.d  src\core\sys\solaris\sys\elftypes.d  src\core\sys\solaris\sys\link.d  src\core\sys\solaris\sys\priocntl.d  src\core\sys\solaris\sys\procset.d  src\core\sys\solaris\sys\types.d   src\core\sys\windows\accctrl.d  src\core\sys\windows\aclapi.d  src\core\sys\windows\aclui.d  src\core\sys\windows\basetsd.d  src\core\sys\windows\basetyps.d  src\core\sys\windows\cderr.d  src\core\sys\windows\cguid.d  src\core\sys\windows\com.d  src\core\sys\windows\comcat.d  src\core\sys\windows\commctrl.d  src\core\sys\windows\commdlg.d  src\core\sys\windows\core.d  src\core\sys\windows\cpl.d  src\core\sys\windows\cplext.d  src\core\sys\windows\custcntl.d  src\core\sys\windows\dbghelp.d  src\core\sys\windows\dbghelp_types.d  src\core\sys\windows\dbt.d  src\core\sys\windows\dde.d  src\core\sys\windows\ddeml.d  src\core\sys\windows\dhcpcsdk.d  src\core\sys\windows\dlgs.d  src\core\sys\windows\dll.d  src\core\sys\windows\docobj.d  src\core\sys\windows\errorrep.d  src\core\sys\windows\exdisp.d  src\core\sys\windows\exdispid.d  src\core\sys\windows\httpext.d  src\core\sys\windows\idispids.d  src\core\sys\windows\imagehlp.d  src\core\sys\windows\imm.d  src\core\sys\windows\intshcut.d  src\core\sys\windows\ipexport.d  src\core\sys\windows\iphlpapi.d  src\core\sys\windows\ipifcons.d  src\core\sys\windows\iprtrmib.d  src\core\sys\windows\iptypes.d  src\core\sys\windows\isguids.d  src\core\sys\windows\lm.d  src\core\sys\windows\lmaccess.d  src\core\sys\windows\lmalert.d  src\core\sys\windows\lmapibuf.d  src\core\sys\windows\lmat.d  src\core\sys\windows\lmaudit.d  src\core\sys\windows\lmbrowsr.d  src\core\sys\windows\lmchdev.d  src\core\sys\windows\lmconfig.d  src\core\sys\windows\lmcons.d  src\core\sys\windows\lmerr.d  src\core\sys\windows\lmerrlog.d  src\core\sys\windows\lmmsg.d  src\core\sys\windows\lmremutl.d  src\core\sys\windows\lmrepl.d  src\core\sys\windows\lmserver.d  src\core\sys\windows\lmshare.d  src\core\sys\windows\lmsname.d  src\core\sys\windows\lmstats.d  src\core\sys\windows\lmsvc.d  src\core\sys\windows\lmuse.d  src\core\sys\windows\lmuseflg.d  src\core\sys\windows\lmwksta.d  src\core\sys\windows\lzexpand.d  src\core\sys\windows\mapi.d  src\core\sys\windows\mciavi.d  src\core\sys\windows\mcx.d  src\core\sys\windows\mgmtapi.d  src\core\sys\windows\mmsystem.d  src\core\sys\windows\msacm.d  src\core\sys\windows\mshtml.d  src\core\sys\windows\mswsock.d  src\core\sys\windows\nb30.d  src\core\sys\windows\nddeapi.d  src\core\sys\windows\nspapi.d  src\core\sys\windows\ntdef.d  src\core\sys\windows\ntdll.d  src\core\sys\windows\ntldap.d  src\core\sys\windows\ntsecapi.d  src\core\sys\windows\ntsecpkg.d  src\core\sys\windows\oaidl.d  src\core\sys\windows\objbase.d  src\core\sys\windows\objfwd.d  src\core\sys\windows\objidl.d  src\core\sys\windows\objsafe.d  src\core\sys\windows\ocidl.d  src\core\sys\windows\odbcinst.d  src\core\sys\windows\ole.d  src\core\sys\windows\ole2.d  src\core\sys\windows\ole2ver.d  src\core\sys\windows\oleacc.d  src\core\sys\windows\oleauto.d  src\core\sys\windows\olectl.d  src\core\sys\windows\olectlid.d  src\core\sys\windows\oledlg.d  src\core\sys\windows\oleidl.d  src\core\sys\windows\pbt.d  src\core\sys\windows\powrprof.d  src\core\sys\windows\prsht.d  src\core\sys\windows\psapi.d  src\core\sys\windows\rapi.d  src\core\sys\windows\ras.d  src\core\sys\windows\rasdlg.d  src\core\sys\windows\raserror.d  src\core\sys\windows\rassapi.d  src\core\sys\windows\reason.d  src\core\sys\windows\regstr.d  src\core\sys\windows\richedit.d  src\core\sys\windows\richole.d  src\core\sys\windows\rpc.d  src\core\sys\windows\rpcdce.d  src\core\sys\windows\rpcdce2.d  src\core\sys\windows\rpcdcep.d  src\core\sys\windows\rpcndr.d  src\core\sys\windows\rpcnsi.d  src\core\sys\windows\rpcnsip.d  src\core\sys\windows\rpcnterr.d  src\core\sys\windows\schannel.d  src\core\sys\windows\sdkddkver.d  src\core\sys\windows\secext.d  src\core\sys\windows\security.d  src\core\sys\windows\servprov.d  src\core\sys\windows\setupapi.d  src\core\sys\windows\shellapi.d  src\core\sys\windows\shldisp.d  src\core\sys\windows\shlguid.d  src\core\sys\windows\shlobj.d  src\core\sys\windows\shlwapi.d  src\core\sys\windows\snmp.d  src\core\sys\windows\sql.d  src\core\sys\windows\sqlext.d  src\core\sys\windows\sqltypes.d  src\core\sys\windows\sqlucode.d  src\core\sys\windows\sspi.d  src\core\sys\windows\stacktrace.d  src\core\sys\windows\stat.d  src\core\sys\windows\stdc\malloc.d  src\core\sys\windows\stdc\time.d  src\core\sys\windows\subauth.d  src\core\sys\windows\threadaux.d  src\core\sys\windows\tlhelp32.d  src\core\sys\windows\tmschema.d  src\core\sys\windows\unknwn.d  src\core\sys\windows\uuid.d  src\core\sys\windows\vfw.d  src\core\sys\windows\w32api.d  src\core\sys\windows\winbase.d  src\core\sys\windows\winber.d  src\core\sys\windows\wincon.d  src\core\sys\windows\wincrypt.d  src\core\sys\windows\windef.d  src\core\sys\windows\windows.d  src\core\sys\windows\winerror.d  src\core\sys\windows\wingdi.d  src\core\sys\windows\winhttp.d  src\core\sys\windows\wininet.d  src\core\sys\windows\winioctl.d  src\core\sys\windows\winldap.d  src\core\sys\windows\winnetwk.d  src\core\sys\windows\winnls.d  src\core\sys\windows\winnt.d  src\core\sys\windows\winperf.d  src\core\sys\windows\winreg.d  src\core\sys\windows\winsock2.d  src\core\sys\windows\winspool.d  src\core\sys\windows\winsvc.d  src\core\sys\windows\winuser.d  src\core\sys\windows\winver.d  src\core\sys\windows\wtsapi32.d  src\core\sys\windows\wtypes.d   src\core\thread\fiber.d  src\core\thread\types.d  src\core\thread\threadgroup.d  src\core\thread\threadbase.d  src\core\thread\osthread.d  src\core\thread\context.d  src\core\thread\package.d   src\rt\aApply.d  src\rt\aApplyR.d  src\rt\aaA.d  src\rt\adi.d  src\rt\alloca.d  src\rt\arraycat.d  src\rt\cast_.d  src\rt\cmath2.d  src\rt\config.d  src\rt\cover.d  src\rt\critical_.d  src\rt\deh.d  src\rt\deh_win32.d  src\rt\deh_win64_posix.d  src\rt\dmain2.d  src\rt\dwarfeh.d  src\rt\ehalloc.d  src\rt\invariant.d  src\rt\lifetime.d  src\rt\llmath.d  src\rt\memory.d  src\rt\memset.d  src\rt\minfo.d  src\rt\monitor_.d  src\rt\msvc.d  src\rt\msvc_math.d  src\rt\profilegc.d  src\rt\sections.d  src\rt\sections_android.d  src\rt\sections_darwin_64.d  src\rt\sections_elf_shared.d  src\rt\sections_osx_x86.d  src\rt\sections_osx_x86_64.d  src\rt\sections_solaris.d  src\rt\sections_win32.d  src\rt\sections_win64.d  src\rt\tlsgc.d  src\rt\trace.d  src\rt\tracegc.d   src\rt\util\typeinfo.d  src\rt\util\utility.d   src\etc\linux\memoryerror.d lib\druntime32mscoff.lib -debuglib=lib\druntime32mscoff.lib -defaultlib=lib\druntime32mscoff.lib user32.lib
lld-link: error: could not open 'LIBCMT.lib': no such file or directory

```

**Comment by rainers** [comment]
> could not open 'LIBCMT.lib': no such file or directory

You are still adding it to the link explicitly. You should not do that. The automatically selected `driverParams.mscrtlib` already contains the proper library, `msvcrt120` in the case of mingw.

**Comment by WalterBright** [comment]
The reason I put in LIBCRT.lib directly is without it, I get __tls_index/array undefined errors for the non-Ming platforms.

**Comment by rainers** [comment]
> The reason I put in LIBCRT.lib directly is without it, I get __tls_index/array undefined errors for the non-Ming platforms.

The test suite runs without that linker directive. Even your test case works with dmd 2.103 if I build it with `-c`. 
Maybe it was an issue for one of your intermediate versions or it is caused by the unrelated changes to ".tls$AAB".

**Comment by WalterBright** [comment]
Abandoned in favor of https://github.com/dlang/dmd/pull/15170

**Pull request closed without merging**
