### PR TITLE
Add -dnostdlib to simplify the use of DLang without stdlib

### PR DESCRIPTION
**Pull request by ghost**
This PR was created to provide an easier alternative to accept than https://github.com/dlang/dmd/pull/7825 and https://github.com/dlang/dmd/pull/9814

This PR has been divided into 5 parts to make it easier to analyze each change and not to accept all the changes

With this initial PR you begin to define the new flag: "-dnostdlib" which will allow developers to use the DLang compiler without any dependency on various runtime (both DRuntime and Libc) without having to use boring methods like generating object files and linking them manually (this is done for example here https://github.com/JinShil/utiliD/blob/91b9048cac92e8341816cd2bc78fdc066f5ad5cc/test/HelloWorld/run.d#L17)

With this PR, unlike previous attempts, no code/script currently in use will be broken, just a new flag will be added for users interested in using DLang without any standard library.

The "-dnostdlib" flag should do the following:

- Disable the generation of the entry point C main https://github.com/dlang/dmd/blob/22113af36e4324ad1a78beb3af623336cac49b4e/src/dmd/compiler.d#L74
- Prevent implicit linking with default libraries hardcoded in dmd/link.d https://github.com/dlang/dmd/blob/22113af36e4324ad1a78beb3af623336cac49b4e/src/dmd/link.d#L672
- Prevent the use of the library specified in -defaultlib
- Add to the linker flags "-nostdlib -nodefaultlibs -nostartfiles" to prevent the linking of standard C libraries
- Do not implicitly import the object module https://github.com/dlang/dmd/blob/22113af36e4324ad1a78beb3af623336cac49b4e/src/dmd/dmodule.d#L1134

After this PR it will be possible to compile with DMD a source code like this just adding -dnostdlib (so with a way like C compilers):
```d
private extern(C) void __d_sys_exit(long arg1)
{
    asm
    {
        mov RAX, 60;
        mov RDI, arg1;
        syscall;
    }
}

private long __d_sys_write(long arg1, in void* arg2, long arg3)
{
    long result;

    asm
    {
        mov RAX, 1;
        mov RDI, arg1;
        mov RSI, arg2;
        mov RDX, arg3;
        syscall;
    }

    return result;
}

void write(string text)
{
    __d_sys_write(2, text.ptr, text.length);
}

private extern(C) void _start()
{
    main();
    __d_sys_exit(0);
}

void main()
{
    write("Hello, World!\n");
}
```

### CODE REVIEW

**Comment by ErnyTech** [comment]
Link to other PR:
https://github.com/dlang/dmd/pull/10181
https://github.com/dlang/dmd/pull/10182
https://github.com/dlang/dmd/pull/10183
https://github.com/dlang/dmd/pull/10184

**Comment by thewilsonator** [comment]
cc @JinShil @marler8997

**Comment by Geod24** [comment]
How does it compare to `-betterC` ?

**Comment by ErnyTech** [comment]
-betterC links the libc and import object.d, while -dnostdlib was born to be used without any stdlib (druntime, phobos and libc)

**Comment by WalterBright** [comment]
I don't understand. Just don't call your main function `main()`, as it is `main()` that triggers the other stuff.

**Comment by marler8997** [comment]
Already have a PR for this: https://github.com/dlang/dmd/pull/9831

It turns out we don't need an new option, using `-defaultlib=` will suffice.  The only thing holding it back is that there's still some linking errors in either druntime/phobos.

**Comment by JinShil** [comment]
> It turns out we don't need an new option, using `-defaultlib=` will suffice.

If you examine the other PRs (#10181, #10182, #10183, #10184), you will see that there is more to it than just linking the default platform libraries.  This PR will introduce a compiler switch that will also disable implicitly importing `object.d` and generation of the startup code (`__entrypoint`, C `main`, etc.)

> I don't understand. Just don't call your main function main(), as it is main() that triggers the other stuff.

That's only true for the startup code (`__entrypoint`, C `main`, etc.).  As mentioned above the goal with the new compiler switch proposed in this PR is to do more (preventing linking of default platform libs, and implicitly importing `object.d`).

---
I've given this PR some thought, but the approach proposed here is not my preference.

I'm interested in making D more pay-as-you-go, but the spirit of the `pay-as-you-go` mantra is that everything is turned OFF by default and you only turn ON what you need.  The approach taken with this PR is to turn things OFF.  That's not a deal-breaker, but it's a warning flag that something's not right.

I have an alternate proposal which I believe will be more generally useful for all, more in the spirit of "pay-as-you-go", and will reduce much hard-coded complexity in the compiler.  I propose utilizing `dmd.conf` as the place where default compiler behavior is encoded. That includes import directories, implicitly imported modules, library search directorys, and default linked libraries.  That way all the hard-coded logic in [link.d](https://github.com/dlang/dmd/blob/master/src/dmd/link.d) and [elsewhere](https://github.com/dlang/dmd/blob/5e15e986b298e9251dd37b3323fe9d7bb84ae3a2/src/dmd/dmodule.d#L670-L676) can be delegated to the compiler distribution.  It can be fully customized for a given platform ([as is already done](https://github.com/dlang/installer/tree/master/create_dmd_release/extras)) without having to make any changes to the compiler, complicating the compiler with a lot of platform detection logic, or `version`ing the compiler.

Those who are using D for bare-metal, new platforms, or other pioneering use cases that don't wish to utilize the compiler's defaults can simply invoke the compiler with `dmd -conf=` or create a new `dmd.conf` file with their default configuration suitable to their target platform or use case.

I believe that will be more scalable, will reduce complexitiy in the compiler, and will be more generally useful for all.

**Comment by marler8997** [comment]
@JinShil I already started work on your proposal but we are waiting on @WalterBright to respond https://github.com/dlang/dmd/pull/9936#issuecomment-498097368

[WIP] [NeedsAcceptOrRejectFromWalter] Move standard library config to dmd.conf 
   https://github.com/dlang/dmd/pull/9944

[WIP] [NeedsAcceptOrRejectFromWalter] Remove hardcoded phobos info from the compiler 
   https://github.com/dlang/dmd/pull/9936

**Pull request closed without merging**
