### PR TITLE
[stable] druntime: Fix InvalidMemoryOperation error on Windows when throwing exceptions from finalizers

### PR DESCRIPTION
**Pull request by kinke**
A v2.102 regression, which newly enabled `StackTrace` constructions from within GC finalizers. The construction is `@nogc`, but apparently depends on the `typeid(StackTrace)` monitor having been allocated already, i.e., a previous `StackTrace` construction.

So pre-allocate a dedicated `Mutex` in the module constructor to make the `StackTrace` construction really `@nogc`. `druntime/test/allocations/src/alloc_from_assert.d` then passes on Windows again (not tested by DMD, but by LDC).

While at it, also prevent `InvalidMemoryOperation` errors when trying to print exceptions within finalizers - by not resolving anything (=> empty printed trace), as resolving currently heavily depends on the GC.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by RazvanN7** [comment]
Can you add a `version(Windows)` test case?

**Comment by kinke** [comment]
I could add an ugly `druntime/test/allocations/win64.mak` and include at least that one `alloc_from_assert.d` test on Windows. But really, all these ugly redundant DigitalMars makefiles for the druntime integration tests should finally be gotten rid of - LDC is using the generic `Makefile`s on Windows too (+ GNU make), so the LDC mods to these files should eventually be upstreamed.

**Comment by kinke** [comment]
Trying that in https://github.com/dlang/dmd/pull/14903, which is supposed to fail.

**Comment by kinke** [comment]
Okay, failed as expected. I've now added that commit here, should obviously pass now.

**Review by RazvanN7 — APPROVED** [review]

**Comment by schveiguy** [comment]
Thanks, @kinke Yeah, I did the minimum to get it working on Windows, I don't use windows, so I thought this was enough. So many sneaky GC uses!

**Review by schveiguy — APPROVED** [review]

**Comment by kinke** [comment]
Yeah, that `synchronized` was very sneaky indeed. :) - Thx @schveiguy for your work on this - a
```D
    ~this () { assert(this.magic == 42); }
```
previously hung with LDC v1.31 on Linux, and now it prints the full proper stacktrace. :)

**Review by schveiguy — CHANGES_REQUESTED** [review]
Just realized, needs a bug report or changelog.

**Review by schveiguy — APPROVED** [review]

**Pull request merged**
