### PR TITLE
refactor expression.h: remove fields unused by backend

### PR DESCRIPTION
**Pull request by WalterBright**
Back end .h files should be on a need-to-know basis.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Does this work ?
won't the class layout be seen diffrently _

**Comment by UplinkCoder** [comment]
Ah I get it. you removed all the members.

**Comment by rainers** [comment]
I don't think this is a good idea. It makes it harder for other compiler backends (or other tools when using the front end as a library in the future). 

For example, LDC uses code like `((IdentifierExp *)exp)->ident`, too. There are other types being used in static_casts. I didn't find any of the ones changed here, though.

IIRC the plan was to autogenerate the C++ header files in the long run.

**Comment by yebblies** [comment]
Ehhh this doesn't seem like a good idea.

**Comment by jpf91** [comment]
ping @ibuclaw

**Comment by kinke** [comment]
I generally dislike .d and .h going out of sync. I find it absolutely natural that the C++ header corresponds to the D implementation. Hiding members this way for C++ bindings (and ending up with different type sizes etc.) seems a particularly bad idea to me.

**Comment by kinke** [comment]
I generally dislike .d and .h going out of sync. I find it absolutely natural that the C++ header corresponds to the D implementation. Hiding members this way for C++ bindings (and ending up with different type sizes etc.) seems a particularly bad idea to me.

**Comment by WalterBright** [comment]
It's a common and reasonable approach to encapsulation when using virtual functions (I've even used it with D in object.d). Reducing the coupling from the front end to the back end is a worthwhile goal, and will decrease the brittleness of the .d/.h interface, not increase it.

As for the other compilers, isn't that what the Travis CI test does?

**Comment by ibuclaw** [comment]
> As for the other compilers, isn't that what the Travis CI test does?

The TravisCI tests only check that other compilers can build dmd.  If we did use any of these fields, we wouldn't know until we next sync up our sources with yours.

**Comment by ibuclaw** [comment]
I have nothing to add to what concerns have already been said.  However I will echo the importance of improving the quality of the interface for the back, I just think there are better ways to spend our time doing that.

**Comment by wilzbach** [comment]
> The TravisCI tests only check that other compilers can build dmd. If we did use any of these fields, we wouldn't know until we next sync up our sources with yours.

That sounds like a good challenge for more automation! Is the increased build time the only thing that is blocking you from doing this or are you still too much out of sync? @klickverbot @JohanEngelen afaik is LDC now in sync with DMD?

**Comment by JohanEngelen** [comment]
@wilzbach LDC is pretty much in sync with the `stable` branch.
If you want to automate things, the usual steps are:
1. checkout dmd commit of last sync
2. copy LDC's `ddmd` dir over dmd's `src` and commit it
3. merge dmd commit hash up to where you want to sync
4. copy files in `src` and `src/root` back to LDC's `ddmd` dir.
5. done!
Merge conflicts aside, dmd's `src` dir contains a bunch of backend-specific files and other things that we don't use. Those should be ignored of course (moving the backend-specific files into `backend` would be nice for us). If files were added/removed, you need to determine whether they should be added/removed for LDC too.

**Comment by ibuclaw** [comment]
> Is the increased build time the only thing that is blocking you from doing this or are you still too much out of sync?

I wrote a lengthy rant in the mailing list some time ago.  In short travisci is a terrible platform because.
- Kills build after 40 minutes (not enough time for single thread builds)
- Kills build after excessing 4GB memory (so can't speed up using `-j`)
- Kills build after 10 minutes silence in console (so must increase verbosity)
- Only keeps the first thousand lines of console output.

I think I got build suceeding only once. But that required using some memory-saving linker switches, and by using parallel mutex locks to prevent two linkers running at once.  But travisci has hardware that ranges from ok to terrible, so builds got killed more than they succeeded.

**Comment by kinke** [comment]
> Kills build after 40 minutes (not enough time for single thread builds)

I can't confirm that. The Linux multilib job for LDC used to take slightly more than an hour, and that wasn't an issue. The OSX release job used to take almost 50 mins and also worked; I think the jobs got killed after 50 mins on OSX.

> Kills build after excessing 4GB memory (so can't speed up using -j)

We use `-j3` when building LDC, druntime & Phobos; `-j2` for the Phobos unit tests, and have no issue with insufficient memory (on both Linux and OSX; the OSX VM is supposed to feature 3GB only).

> Kills build after 10 minutes silence in console (so must increase verbosity)

True, but again no issue for LDC. What step would take that long?

> Only keeps the first thousand lines of console output.

I recall some limitation, which could be worked around by displaying the raw log, which was always complete. A recent LDC job features almost 15k lines though, which are fully available: https://travis-ci.org/ldc-developers/ldc/jobs/151737315

Note that Travis provides different build environments with different features (memory, CPU cores, boot time etc.): https://docs.travis-ci.com/user/ci-environment. We use the container-based one for Linux.

**Comment by ibuclaw** [comment]
> We use -j3 when building LDC, druntime & Phobos; -j2 for the Phobos unit tests, and have no issue with insufficient memory (on both Linux and OSX; the OSX VM is supposed to feature 3GB only).

The frontend itself is small, but whereas you link against a prebuilt compiler library, I have an entire compiler to build from source. ;-)

https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error

And it lists other problems I ran into also.

> What step would take that long?

The D2 testsuite.  Which is silent except for failures.

**Comment by WalterBright** [comment]
Closed for lack of interest.

**Comment by ibuclaw** [comment]
Also I am currently doing the opposite and adding fields and methods that you leave out of the headers (#6643)

**Comment by WalterBright** [comment]
dmd no longer has any need for those .h files, so I leave decisions on how to deal with them up to you and the ldc team. I recommend, however, finding ways to reduce dependency on them.

**Comment by ibuclaw** [comment]
Well my plan is to align up the C++ codebase to the stable branch just enough so I can begin testing bootstrapping the D frontend on gdc without having to maintain a separate copy.

Reducing dependence would entail another top-down rewrite.   But not impossible, just wouldn't hold my breath for it to happen.  :-)

**Pull request closed without merging**
