### PR TITLE
Issue 9608 - Implement a set of traits for template parameter introspection.

### PR DESCRIPTION
**Pull request by ghost**
https://issues.dlang.org/show_bug.cgi?id=9608

Spec pull will be made if it's accepted.

Together with the [isTemplate](https://github.com/D-Programming-Language/dmd/pull/3380) trait this should form a good set of introspection traits.

@andralex: Are these traits complete enough for your needs?

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
I'm really interested in this. What's the status?

**Comment by AndrejMitrovic** [comment]
Needs a rebase, I'll add it to my todo for the upcoming days.

**Comment by andralex** [comment]
Thanks, @AndrejMitrovic (modulo test failures :)). I'd want us to collect more experience in this area before committing to a set of primitives. How about this: we merge these and use them in std.traits but leave them undocumented for the time being. Would this work? cc @WalterBright @9rnsr @yebblies @MartinNowak

**Comment by Hackerpilot** [comment]
Reminder: http://dlang.org/traits.html will need to be updated if this is merged.

**Comment by jacob-carlborg** [comment]
Ping, what's the status of this?

**Pull request closed without merging**
