### PR TITLE
Fix 21957 - Don't crash when aligning noreturn members 

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
`alignmember` assumes that every type with default alignment has a size
greater than zero - which obviously does not apply for `noreturn`.

A `noreturn` field with default alignment does not affect the layout of
the aggregate because `noreturn.sizeof = noreturn.alignof = 0`. Hence
skip the `alignmember` call unless a custom alignment was requested.

---

Targeting stable because this is a minor change to prevent an ICE

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by UplinkCoder** [comment]
@Geod24 because noreturn is botiom.
It leads to less special casing in the type-checker.

**Comment by MoonlightSentinel** [comment]
As stated in the [DIP, Interaction with other language features](https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1034.md#interaction-with-other-language-features):

> Defining a variable with type noreturn with an initialization expression will simply generate that expression as soon as it becomes live. Defining a noreturn variable with no initialization expression generates an assert(0) only if the variable is accessed, which can be useful in generic code where unused noreturn variables may be declared. Generating the assert(0) as soon as the variable is live in these cases could prematurely end the program.

TL, DR: Don't require special cases for `noreturn` in templated code as long as the variable is never used

**Review by RazvanN7 — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
This PR introduced a regression: https://issues.dlang.org/show_bug.cgi?id=22858

**Comment by ibuclaw** [comment]
This PR introduced a new ICE (not _quite_ a regression, just moved the ICE from alignmember to CTFE).
https://issues.dlang.org/show_bug.cgi?id=23439

**Pull request merged**
