### PR TITLE
Fix Issue 18365 - allow return storage class to be set in prefix style

### PR DESCRIPTION
**Pull request by wilzbach**
As an alternative to https://github.com/dlang/dmd/pull/7836.

### CODE REVIEW

**Comment by wilzbach** [comment]
Note that the D spec is out of date anyhow:

https://dlang.org/spec/grammar.html#declarations

`return` is not a storage class

https://dlang.org/spec/grammar.html#attributes

but a valid attribute.

**Comment by rainers** [comment]
Doesn't this produce ambiguities for nested functions or doesn't allow it there?

**Comment by wilzbach** [comment]
I'm not sure - imho `return` is highly under-documented.
I assume it will just ignore the storage class or error:

```
struct Foo
{
    char function(char a) return value2()
    {
    	static char foo(char a)
    	{
            return a;
    	}
    	return &foo;
    }
}
```

will error with:

```
compilable/test18365.d(8): Error: const/immutable/shared/inout/return attributes are only valid for non-static member functions
```

BTW I'm not saying this is the best way to move forward, but when trying to generate header files for Phobos I hit the problem that `return` is the only attribute that is only allowed postfix, but emitted in prefix by the header generation.

**Comment by RazvanN7** [comment]
Since https://github.com/dlang/dmd/pull/7836 was merged. Can you close this one please?

**Pull request closed without merging**
