### PR TITLE
Use a pragma to identify intrinsic functions

### PR DESCRIPTION
**Pull request by yebblies**
This is much less work than matching the mangled names, and much less brittle.

@WalterBright 

We'll need to come up with either a common pragma or an API for compiler-specific pragmas.
@ibuclaw @klickverbot @redstar

### CODE REVIEW

**Comment by yebblies** [comment]
Requires: https://github.com/D-Programming-Language/druntime/pull/1366/files

**Comment by ibuclaw** [comment]
Why map to DigitalMars_intrinsic?

**Comment by yebblies** [comment]
Huh?

**Comment by ibuclaw** [comment]
Why pragma(DigitalMars_intrinsic) when all but two or three are specific to dmd?  Or is this the API you are referring to?

**Comment by yebblies** [comment]
Yeah, I don't know how we want to hook it, so I went with compiler-specific.  Is everyone fine with `pragma(intrinsic, "name")` and leaving the meaning until the backend?  Should the functions in core.math etc have pragmas or should they forward to core.dmd.intrinsics?

**Comment by yebblies** [comment]
New tactic: pragmas now do not need to be adjacent to the function.  I've also integrated the interpreter builtins.

**Comment by ibuclaw** [comment]
> I've also integrated the interpreter builtins.

I was thinking about that this morning before I checked back here again.

**Comment by ibuclaw** [comment]
>  it also needs to be able to handle calls to template functions.

+1 for GDC too (``va_copy``, ``va_arg``, ``va_end``)

**Comment by dkorpel** [comment]
builtin.d has since been overhauled, mangled names are no longer used.

**Pull request closed without merging**
