### PR TITLE
fix Issue 15519 - Circular imports leads to fwd ref error with aliase…

### PR DESCRIPTION
**Pull request by WalterBright**
…d imports

https://issues.dlang.org/show_bug.cgi?id=15519

Chicken or egg? Hopefully this resolves some frustrating errors with circular imports.

Corrected anachronistic use of `->` in debugging printf's.

### CODE REVIEW

**Comment by WalterBright** [comment]
Requires https://github.com/D-Programming-Language/dmd/pull/5330 in order to work.

**Comment by WalterBright** [comment]
The travis builds aren't re-running.

**Comment by andralex** [comment]
let's see if this breaks the world...

**Comment by yebblies** [comment]
@andralex Why aren't you using the autotester's auto-merge?

**Pull request merged**
