### PR TITLE
fix issue 19493 - compiler crash when trying to format invalid contracts

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Review by WalterBright — CHANGES_REQUESTED** [review]
Please look at other test case files in fail_compilation, particularly about how `TEST_OUTPUT` is done.

Secondly, both of the test cases can be merged into one file.

**Comment by BBasile** [comment]
https://github.com/dlang/dmd/blob/5ceddec744443e13999a8c7421a7785a7aad71f3/test/tools/d_do_test.d#L411

**Comment by BBasile** [comment]
@WalterBright, misunderstanding confirmed ? Is this PR finally ok considering my explanations ?

**Comment by thewilsonator** [comment]
Adding 72h ->merge

**Comment by WalterBright** [comment]
Since it crashes trying to format the error message, I don't see how checking that the message output is well-formed is a problem. Nor do I see why putting both in the same file would defeat the tests.

**Comment by thewilsonator** [comment]
> I don't see how checking that the message output is well-formed is a problem

It doesn't need to be. The dmd test suite has a serious problem of being overly prescriptive of what the compiler must produce, rather than caring about the bit that actually matter. This is the basis for why we have no codegen (other than "it works") or IR tests.

This issue at hand is that the compiler segfaults, not that the errors are sensible (they aren't, but neither is the input). This tests for that, no more, no less.

> Nor do I see why putting both in the same file would defeat the tests.

There are no synchronisation tokens in the tests, if `typeof function function in typeof function function out` still crashes the compiler it should be a test of its own.

**Comment by BBasile** [comment]
I (just) get why they should be merged and found after verification that a semicolon between the two sequence of tokens will do the trick (parsing typeof restart then).

**Comment by BBasile** [comment]
No the semicolon reveals another case of crash finally. The parser thinks that the colon is an empty expression statement and set it for the in contract. Later an assertion fails since the expression token is expected to be of type TOK.assert_.

**Comment by BBasile** [comment]
I'd like more to fix the parser but since i had the feeling that the D constructs are parsed in a peculiar way on purpose (see the NG announce about fuzzed) i'll stop here. Sorry for the time lost at reviewing.

**Pull request closed without merging**
