### PR TITLE
Issue 14549 - isVirtualMethod does not work well with Github DMD

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14549

This PR also changes [issue 7815](https://issues.dlang.org/show_bug.cgi?id=7815) case invalid. see the explanation in test code (or commit log).

### CODE REVIEW

**Comment by WalterBright** [comment]
Can we please stop with the endless refactoring? It makes changes difficult to review, forces rebasing of uncommitted pulls, and makes it hard to compare different versions of the source code.

**Comment by 9rnsr** [comment]
Sorry for my incremental changes, it's supplemental of #3400. 

A compile bug fix is equivalent with dmd code cleaning to me. 
I believe that if compiler code is not enough consistency, it would appear as a bug. Today's code cleaning is same with the preparation of future bug fix.
Therefore if we don't want to kill dmd, we cannot stop the endless refactoring.

Furthermore, it's becoming more difficult to spent my time for dmd than before. So I'd like to make dmd source code as clean as I believe for future dmd committers.

**Comment by CyberShadow** [comment]
> Can we please stop with the endless refactoring? It makes changes difficult to review, forces rebasing of uncommitted pulls, and makes it hard to compare different versions of the source code.

On the other hand, do you want to remain the only compiler contributor should Kenji leave, because the code is a giant impenetrable mess of cryptic undocumented identifiers?

Every time I tried to contribute to DMD, I burned out very quickly because of how needlessly complicated the code is. I think refactoring to make the code more readable and comprehensible is very worthwhile.

**Comment by andralex** [comment]
A few considerations from one not actively involved with the compiler codebase:

1. Refactorings add burden on the reviewers. Since @WalterBright, @9rnsr. @yebblies and a couple others most often end up reviewing each other's code, it's reasonable to give them leeway in working out what is reasonable for everyone.

2. Refactorings should be non-controversial in value added (as opposed to e.g. adaptation across styles of coding). (I'm not sure whether this is the case with this or other refactorings.)

3. The entire reasoning along "This refactoring comes from a contributor we can't afford to lose, therefore must be accepted" is fallacious.

4. @klickverbot's remark is moot because the fix is not under discussion.

5. Refactorings make it difficult to pinpoint regressions because lockstep changes to compiler, runtime, and stdlib make it difficult to use the ilk of git bisect or dustmite. This is a tooling issue that ideally would be resolved.

The way I see it if a coworker's refactorings add too much work for me thus preventing me from working more on other things, it's entirely reasonable for me to ask him/her to be more selective about such, and it's equally reasonable for them to mind the request. I shouldn't refrain from mentioning such in fear that they'd leave the team or company.

**Comment by CyberShadow** [comment]
> Refactorings make it difficult to pinpoint regressions because lockstep changes to compiler, runtime, and stdlib make it difficult to use the ilk of git bisect or dustmite. This is a tooling issue that ideally would be resolved.

Huh?

**Comment by WalterBright** [comment]
Although the refactorings are in separate commits, which is good, they are still packaged together with critical bug fixes. Non-trivial refactorings should be in separate PRs and judged on their own merits. This would resolve @klickverbot 's issue.

**Comment by yebblies** [comment]
It makes life easier for the reviewers if refactorings are put in different pull requests to functional changes, but apart from that I don't mind refactoring that produces even a small improvement to consistency or maintainability.  It isn't always possible, and it isn't always worth the trouble to split them out.

The main thing that putting refactorings in separate commits doesn't solve is that they pollutes the 'Files Changed' diff, which is the most convenient tool for PR review.

> [it] forces rebasing of uncommitted pulls

As Kenji is by far the one most affected by refactoring breaking pull requests, if he feels it's worthwhile then it probably is.

> Refactorings make it difficult to pinpoint regressions because lockstep changes to compiler, runtime, and stdlib make it difficult to use the ilk of git bisect or dustmite. This is a tooling issue that ideally would be resolved.

@andralex That has nothing to do with internal dmd refactorings, it only with happens ABI changes.  And there _is_ tooling that resolves it.

**Comment by tramker** [comment]
>Regression fixes also should not include refactorings, because updating 2.067 should just have fixes.

Yes, please keep REG fixes as simple as possible. Ideally refactor *after* the fix, not before.

**Comment by 9rnsr** [comment]
I removed commits for code cleanup in order to concentrate on bug fix.

**Comment by CyberShadow** [comment]
> Refactorings add burden on the reviewers.

> It makes life easier for the reviewers if refactorings are put in different pull requests to functional changes,

> Yes, please keep REG fixes as simple as possible. Ideally refactor after the fix, not before.

I would like to point out that, from a utilitarian perspective (counting total effort expended), it is often much easier for reviewers to simply look at individual commits' diffs, than it is for contributors to split their changes into separate refactoring and non-refactoring pull requests, because some fixes are easier after refactoring.

**Comment by CyberShadow** [comment]
> The main thing that putting refactorings in separate commits doesn't solve is that they pollutes the 'Files Changed' diff, which is the most convenient tool for PR review.

If I write a userscript that makes it easier to view each commit's individual diff, will people use it?

**Comment by yebblies** [comment]
> If I write a userscript that makes it easier to view each commit's individual diff, will people use it?

Viewing each commit's diff is easy, it's excluding a single refactoring commit from the total diff that's needed.

**Comment by CyberShadow** [comment]
> Viewing each commit's diff is easy, it's excluding a single refactoring commit from the total diff that's needed.

That doesn't make sense to me, if each commit is a logical self-contained change then looking at the patch one commit at a time should be simpler (plus commit messages help). But if that is what you really want, GitHub allows viewing the diff of any commit range, so a userscript that allows selecting two commits to diff, MediaWiki-style, is also possible.

**Comment by yebblies** [comment]
> That doesn't make sense to me, if each commit is a logical self-contained change then looking at the patch one commit at a time should be simpler (plus commit messages help). But if that is what you really want, GitHub allows viewing the diff of any commit range, so a userscript that allows selecting two commits to diff, MediaWiki-style, is also possible.

Commit 1: Do half of the things
Commit 2: Refactor
Commit 3: Do the other half

What I want to see is the total set of changes, without the fluff.  Viewing each commit separately means I need to keep the track of everything in my head.

**Comment by CyberShadow** [comment]
> Commit 1: Do half of the things
> Commit 2: Refactor
> Commit 3: Do the other half

Yes, I realize that's the problem with my suggestion. No need to rub it in my face, I'm just trying to make the situation better. Now, how often does this happen in practice? Maybe we can agree to simply not do this, instead of forbidding mixing refactoring with non-refactoring changes altogether?

**Comment by andralex** [comment]
>I removed commits for code cleanup in order to concentrate on bug fix.

@9rnsr: thanks!!

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
I agree, thanks Kenji! You da man.

**Comment by WalterBright** [comment]
Causes a regression: https://issues.dlang.org/show_bug.cgi?id=14883

**Comment by 9rnsr** [comment]
@WalterBright I [commented in bugzilla ticket](https://issues.dlang.org/show_bug.cgi?id=14883#c2) how the behavior difference is happened. To me, the 2.068 behavior is more natural. I'd like to hear your opinion.

**Pull request merged**
