### PR TITLE
test ddmd with latest gdc/ldc and dmd-2.067.1 host compilers

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by ibuclaw** [comment]
I've noticed that host_dc doesn't work so well unless you pass the absolute or relative path to the compiler. I blame the fact that one of the build rules has a dependency on it.

**Comment by MartinNowak** [comment]
> I've noticed that host_dc doesn't work so well unless you pass the absolute or relative path to the compiler. I blame the fact that one of the build rules has a dependency on it.

It's a mess, don't wanna know who is responsible for it.

**Comment by yebblies** [comment]
> It's a mess, don't wanna know who is responsible for it.

Andrei, IIRC.

**Comment by MartinNowak** [comment]
requires https://github.com/D-Programming-Language/druntime/pull/1355

**Comment by MartinNowak** [comment]
Works for now.

**Comment by MartinNowak** [comment]
Done

**Comment by MartinNowak** [comment]
> Likely ran into the Travis memory limit just now, but this is unrelated.

I reduced it to 2 threads, no need to use so much resources.

**Comment by ibuclaw** [comment]
Nice ice from gdc!  However it *is* fixed by https://github.com/D-Programming-GDC/GDC/pull/131 incase anyone asks.

**Comment by jpf91** [comment]
@ibuclaw I could upload an updated GDC binary package. Do you prefer 5.2.0 or 4.9.3?

**Comment by ibuclaw** [comment]
@jpf91 We could do with a 5.2 release. :)

**Comment by jpf91** [comment]
@ibuclaw ftp://ftp.gdcproject.org/binaries/x86_64-linux-gnu/x86_64-linux-gnu_2.066.1_gcc5.2.0_5b7a4a93c7_20150823.tar.xz

I had to remove the toolchain vendor name 'gdcproject'. This caused some trouble for tools only checking for x86_64-unknown-* (instead of x86_64-gdcproject-*). AFAICS travis ci should still work fine as they use the 'gdc' command, which hasn't changed. The top level directory name has also changed but travis strips the top level name so that should work as well.

**Comment by jpf91** [comment]
@ibuclaw Other compilers will take some more time. There seems to be a GCC regression which prevents me from compiling an arm native compiler so I'll have to debug this first.

I've tested the `x86_64-linux-gnu_2.066.1_gcc5.2.0_5b7a4a93c7_20150823.tar.xz` compiler and it compiles a (mostly) working ddmd. it compiles druntime&phobos just fine. ddmd segfaults for one failure test. A quick gdb backtrace looks not gdc related, maybe I've used some outdated dmd code. So I think if you update the travis symlink and LATEST_GDC we could start testing with gdc.

**Comment by ibuclaw** [comment]
@jpf91 - I'm just running it through now, but then I got hit by: https://issues.dlang.org/show_bug.cgi?id=14956

**Comment by ibuclaw** [comment]
> A quick gdb backtrace looks not gdc related, maybe I've used some outdated dmd code.

It looks like a bug to me?  The parameter has a default parameter, but it is being set to ``null`` instead.

**Comment by ibuclaw** [comment]
Ahh, it a ``va_list`` bug.  Damn D2 for passing static arrays by value and not taking C ABI into consideration! :smiling_imp:

**Comment by ibuclaw** [comment]
Having "yet another stab" at passing 64bit va_list's as a pointer. https://github.com/ibuclaw/GDC/commit/41f4d90dce7383cebd1e74e414df8a5e455a266c

**Pull request merged**
