### PR TITLE
merge scope/DIP1000 preview

### PR DESCRIPTION
**Pull request by MartinNowak**
This is intended as feature preview (hidden behind a switch). The implementation might still have a few bugs, but we want to test the design with a slightly broader audience.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Can we please keep using a feature branch for all the changes and fixes until 2.074? Delete all the scope branches in the dlang repo now, but we can easily recreated them

**Comment by WalterBright** [comment]
why? Now it's just conventional bug reports and fixes for dip1000 issues.

**Comment by nordlow** [comment]
What switch is it hidden behind? `-transition=safe`?

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=17445

**Comment by WalterBright** [comment]
> This pull request introduced a regression:

An example of why I don't like feature branches - somewhere in 1500 lines of changes is the problem.

**Comment by CyberShadow** [comment]
It's usually not a problem to bisect inside the branch, it's just that Digger is not set up to do it by default.

**Comment by CyberShadow** [comment]
Bisected it down to the scope PR and commit -> https://github.com/dlang/dmd/pull/5972#issuecomment-312485464

**Pull request merged**
