### PR TITLE
Add new default ddoc theme

### PR DESCRIPTION
**Pull request by jacob-carlborg**
This adds a new default ddoc theme that generates a result with a design that can be used as is without manual styling. It outputs modern HTML 5, CSS 3 and passes the W3 HTML validator. This makes the out of the box experience a lot more pleasant.

The two first commits are from #6170.

Depends on https://github.com/dlang/dmd/pull/6170.

### CODE REVIEW

**Comment by ZombineDev** [comment]
Nice work, @jacob-carlborg!  Can you post a before and after screenshots for comparison?

**Comment by jacob-carlborg** [comment]
Sure.

**Comment by jacob-carlborg** [comment]
new_theme

old_theme

**Comment by jacob-carlborg** [comment]
@andralex ping

**Comment by andralex** [comment]
Very nice. Thanks!

**Comment by jacob-carlborg** [comment]
That was quick, thanks 😃.

**Comment by CyberShadow** [comment]
This introduced some regressions in dlang.org (look at the doc autotester diffs for details). Because we auto-deploy website changes, the regressions have already propagated to the live website: http://dlang.org/phobos-prerelease/std_datetime.html#Month

Also, this made a massive impact on DDoc tests: test files that were previously under 100 lines are now over 1000 lines long. Perhaps there should be a way to opt-out of the new stylesheet, or the tests should be built with a simple .ddoc file that mimics the old default style.

Unless @jacob-carlborg can provide a timely dlang.org switch, I suggest that this is immediately reverted. @andralex

**Comment by andralex** [comment]
If we preserve the existing ecosystem 100% by definition we cannot make progress. I'm okay with reverting the PR for now until we sort out the problems, but I'd rather put up with the larger test files rather than use a smaller mockup. What are the issues caused by the longer test files?

cc @jacob-carlborg

**Comment by CyberShadow** [comment]
> If we preserve the existing ecosystem 100% by definition we cannot make progress.

Yes, but breaking the live site could've been avoided by checking the CI systems in place to prevent exactly this. (Unfortunately there is no automated way that I know of to test if something "looks broken", so DDoc-related changes should be evaluated by at least a cursory examination of the diffs, available only two clicks away.)

> I'm okay with reverting the PR for now until we sort out the problems

What I'm trying to say is that I think it would be better if the problems were noticed and sorted out before merging. :)

> What are the issues caused by the longer test files?

That part was more of an observation in case it's a concern to someone, however one issue is that DDoc regressions (which the test files are supposed to identify) will be more difficult to identify when the diffs are so big, they are difficult to make sense of.

**Comment by jacob-carlborg** [comment]
> This introduced some regressions in dlang.org

@CyberShadow working on it. It should be easy to fix, it's one or two new macros that needs proper configuration.

> Also, this made a massive impact on DDoc tests: test files that were previously under 100 lines are now over 1000 lines long

I suggested having DMD output a separate CSS file, but Andrei wanted a simper solution.

**Comment by MartinNowak** [comment]
> Unfortunately there is no automated way that I know of to test if something "looks broken", so DDoc-related changes should be evaluated by at least a cursory examination of the diffs, available only two clicks away.

You can render and visually diff, but that's rather expensive and requires acknowledgment for every pixel.
https://github.com/rejectedsoftware/ddox/pull/107

**Pull request merged**
