### PR TITLE
C++: Set default  -extern-std value to C++-11

### PR DESCRIPTION
**Pull request by ibuclaw**
So the style of the current generated frontend header is now matched by `-extern-std=`.  This would be a prerequesite for #11802.

### CODE REVIEW

**Comment by thewilsonator** [comment]
This probably warrants a changelog entry.

**Comment by ibuclaw** [comment]
> This probably warrants a changelog entry.

True.

**Comment by 12345swordy** [comment]
All green here.

**Comment by MoonlightSentinel** [comment]
Why change the default instead of passing `-extern-std` in `build.d`?

**Comment by kinke** [comment]
Non-ancient C++ compilers all default to at least C++11 (AFAIK, g++ 6+, and MSVC cl.exe doesn't even have an option and simply uses the last supported version), so bumping the default makes perfect sense IMO.

**Comment by ibuclaw** [comment]
- Added changelog entry.
- Updated `--help` to report c++11 as the new default.

**Review by MoonlightSentinel — APPROVED** [review]
> Non-ancient C++ compilers all default to at least C++11 (AFAIK, g++ 6+, and MSVC cl.exe doesn't even have an option and simply uses the last supported version), so bumping the default makes perfect sense IMO.

Seems reasonable

**Comment by ibuclaw** [comment]
> Why change the default instead of passing `-extern-std` in `build.d` when running `cxx-headers`?

As per [g++ docs](https://gcc.gnu.org/projects/cxx-status.html) 
- `-std=c++98` was default up until g++5
- `-std=c++14` has been default since g++6
- `-std=c++17` will be the default from g++11

I pick `-extern-std=c++11` here as:
- It maintains the broadest support.
- It aligns with [gcc bootstrap](https://github.com/gcc-mirror/gcc/commit/5329b59a2e13dabbe2038af0fe2e3cf5fc7f98ed#diff-67e997bcfdac55191033d57a16d1408a) requirements.
- We don't actually support being able to extern to any new features in C++-14 or later.

**Review by wilzbach — APPROVED** [review]

**Pull request merged**
