### PR TITLE
fix Issue 18573 - cast(void) leads to floating point return value not…

### PR DESCRIPTION
**Pull request by WalterBright**
… being popped from FPU stack

### CODE REVIEW

**Review by thewilsonator — DISMISSED** [review]
Test!

**Comment by WalterBright** [comment]
I know, I'll get to it.

**Comment by WalterBright** [comment]
Another who-knows-what's-wrong-with-semaphoreci problem.

**Comment by wilzbach** [comment]
Well, the error is right here:

```
+ diff _generated/linux/release/32/host_dmd generated/linux/release/32/dmd
Binary files _generated/linux/release/32/host_dmd and generated/linux/release/32/dmd differ
+ nm --print-size _generated/linux/release/32/host_dmd
+ nm --print-size generated/linux/release/32/dmd
```

i.e. the DMD binary built differs when twice.

https://github.com/dlang/dmd/blob/eb1298a55778b5530adb684e2a1483e41bf0c0ff/ci.sh#L131


Before you ask, no it's _not_ the difference between the host DMD used to built DMD, but DMD itself.
In other words:

1) HOST_DMD -build-> DMD -rebuild-> DMD
2) HOST_DMD -build-> DMD -rebuild-> DMD -rebuild-1> DMD

1) and 2) produce different binaries.

**Comment by WalterBright** [comment]
The last line in a failed build log should be what the error was. There is no reasonable way I can tell from that log what the diff is diffing, certainly not "2\. HOST_DMD -build-> DMD -rebuild-> DMD -rebuild-1> DMD" as those logs are nearly impossible to read (tiny font, microscopic scroll bar tab, I have a big screen but the gigantic log is presented through a tiny window). In fact, what you wrote above would be a GREAT error message to append to the log at the end when it gets those errors. Not simply stopping. It should also contain the string "Error".

Also, I've noticed many logs that contain a thousand line of executable diffs, yet the tests "passed". So I've learned to ignore those diffs.

Lastly, I've had a lot of trouble diffing executables, as they get spurious differences. Sometimes going an extra generation and diffing the last two clears it up. Sometimes it's just heisen-differences, as the toolchain output depends on things like internal pointer values. (Can happen if it hashes a data structure using malloc pointer values, or because of address shuffling.) In other words, it produces too many false negatives to be particularly useful.

**Comment by WalterBright** [comment]
And now it's passing semaphoreci!

The randomness in its results can also be due to the linker being multithreaded, and the output changing based on the changing order of execution.

In any case, the problem with this sort of test is when it fails, there's nothing I can do to try and backtrack this sort of problem that only appears on a remote system. It's best to just make this an informational message.

**Pull request merged**
