### PR TITLE
Use project relative path for including root headers

### PR DESCRIPTION
**Pull request by ibuclaw**
This saves on having to have `-I $(srcdir)/d/dmd/root` in the gdc makefiles.

### CODE REVIEW

**Review by Geod24 — APPROVED** [review]

**Review by JinShil — APPROVED** [review]

**Comment by ZombineDev** [comment]
@kinke @JohanEngelen are you also ok with this change?

**Comment by ibuclaw** [comment]
> What’s the advantage of this change?

I still had a flattened directory structure for dmd, which resulted in root header changes not getting picked up in periodic merges.

However moving all root headers from dmd -> dmd/root means that I now need to add more than 30 lines of `CFLAGS-d-lang.o += $(srcdir)/d/dmd/root` to the makefile in so that they can be looked up correctly.

This patch seems the most reasonable alternative to adding boilerplate on my side.

**Comment by ibuclaw** [comment]
@Geod24 started this when he added dcompat.h  ;-)

**Comment by kinke** [comment]
> are you also ok with this change?

Yep, fine by me.

**Review by WalterBright — APPROVED** [review]

**Comment by ibuclaw** [comment]
Rebased as #8615 in conflict.

**Review by JinShil — APPROVED** [review]

**Pull request merged**
