### PR TITLE
fix Issue 7044 - Missing a way to control the order of arguments pass…

### PR DESCRIPTION
**Pull request by WalterBright**
…ed to the linker makes impossible to link some programs

https://issues.dlang.org/show_bug.cgi?id=7044

Adds the `-confsection=name` switch.

### CODE REVIEW

**Comment by MartinNowak** [comment]
See https://issues.dlang.org/show_bug.cgi?id=7044#c51 for a discussion of the shortcomings of this solution.

**Comment by WalterBright** [comment]
rebased for ddmd

**Comment by andralex** [comment]
@WalterBright @MartinNowak ping?

**Comment by andralex** [comment]
@WalterBright @MartinNowak ping :)

**Comment by JinShil** [comment]
I don't care for this solution for much the same reason @MartinNowak mentioned in the bug report and because I think better solutions exist.

I don't think `-defaultLib` and `-debugLib` should exist and be given special treatment by the compiler.  Rather I think the problem should be generalized and phobos/druntime should be treated just like any other library.  If we want to link libraries by default, then those libraries should be added to default `DFLAGS` in dmd.conf.  

Then to address linker order, we simply use the order specified on the command line appended or prepended to `DFLAGS`.  If we want to make it even more flexible, we can append an order the the `-L` flag, so `-L2=xxx -L0=yyy -L2=www -L1=zzz` would create linker flags in the order of `yyy zzz xxx www`.  `-L` with no order number will always go last (or first if you prefer).

To mitigate breakage, we can always place `-defaultLib` and `-debugLib` at `-L2` (or some other middle of the road order), so users can easily place libraries before or after at their discretion without overriding the default `DFLAGS`.

If users need to override the defaults in dmd.conf, they can always do `-conf=` and build the command line from scratch.

**Comment by WalterBright** [comment]
Should be completely re-evaluated.

**Pull request closed without merging**
