### PR TITLE
Fix path validation in import expression (issue #21227)

### PR DESCRIPTION
**Pull request by andrey-zherikov**
https://issues.dlang.org/show_bug.cgi?id=21227

Changes:

- Extracted `isDirSeparator` function to make code clearer.
- Fix `safePath` check:
    - Do not allow character that are reserved according to [documentation](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) on Windows.
    - Do not allow reference to parent directory in any place in the path.

Rationale:
- Consistently support both backslash '\\' and forward slash '/' as directory separator on Windows.
- Make path check in import expression consistent across Windows and POSIX (besides Windows-specific things like UNC paths, disk drive letter in path).

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Please make the commit message say "Fix issue 21227: import(".\\file") doesn't work on Windows" so that the bot picks it up (see the 'x' in the auto-close field). 

Also if you could please split the extracting of isDirSeparator into a function into a separate commit that would make reviewing much easier.

**Comment by thewilsonator** [comment]
cc @MoonlightSentinel

**Comment by andrey-zherikov** [comment]
> Please make the commit message say "Fix issue 21227: import(".\file") doesn't work on Windows" so that the bot picks it up (see the 'x' in the auto-close field).
> 
> Also if you could please split the extracting of isDirSeparator into a function into a separate commit that would make reviewing much easier.

Done

**Comment by thewilsonator** [comment]
Thanks.

**Comment by wilzbach** [comment]
Shouldn't this have had actual E2E tests as well?

**Comment by andrey-zherikov** [comment]
> Shouldn't this have had actual E2E tests as well?

Could you point me to such tests? I'll try to add them.

**Comment by wilzbach** [comment]
Checkout the `test` top-level directory. I hope the README describes it, but let me know if you have further questions.
You want a `compilable` test.

**Pull request merged**
