### PR TITLE
appveyor: build Win32 dmd executable with LDC

### PR DESCRIPTION
**Pull request by rainers**
Unfortunately https://github.com/dlang/dmd/pull/7339 wasn't good enough for Win32.

### CODE REVIEW

**Comment by WalterBright** [comment]
`longdouble.c` should be rewritten in betterC

**Review by WalterBright — APPROVED** [review]

**Comment by rainers** [comment]
There is one failing test:
```
Test fail_compilation\ice1358.d failed.  The logged output:
..\generated\Windows\Release\Win32\dmd.exe -conf= -m32mscoff -Ifail_compilation -verrors=0   -L/OPT:NOICF  -odtest_m32mscoff\fail_compilation -oftest_m32mscoff\fail_compilation\ice1358_0.obj  -c fail_compilation\ice1358.d  -map nul.map
fail_compilation\ice1358.d(29): Error: invalid UTF character \U00d30762
==============================
Test fail_compilation\ice1358.d failed: 
expected:
----
fail_compilation\ice1358.d(29): Error: invalid UTF character \U80000000
----
actual:
----
fail_compilation\ice1358.d(29): Error: invalid UTF character \U00d30762
```
It is caused by a wrong value being passed through Lexer.error to .verror. Seems to be an issue with va_args. @kinke I suspect you have seen this with LDC before?

**Comment by kinke** [comment]
Hmm nope. That test passes for LDC (CI-compiled using 64-bit LDC v1.6) on both Win32 and Win64 and I don't recall seeing it fail.

**Comment by rainers** [comment]
@kinke Just wait until you update to latest dmd sources (before the latest commit in this PR): the problem is that passing variadic arguments through an interface function doesn't work with LDC because the interface thunk **calls** the class member function instead of just **jump** to it avoiding a copy of the arguments on the stack.

**Comment by kinke** [comment]
Oh I just fixed that for LDC: https://github.com/ldc-developers/ldc/pull/2630

**Comment by WalterBright** [comment]
> but it involves quite some changes so I think it should be better made in a separate PR.

Ehhhkselllehnt!

**Pull request merged**
