### PR TITLE
make -vcg-ast print all instantiated template

### PR DESCRIPTION
**Pull request by UplinkCoder**
This PR enables -vcg-ast to print the instancied versions of templates and mixin templates in fullDump mode (vcg-ast)

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@andralex I think you'll like this.

**Comment by WalterBright** [comment]
No test case(s). Note that the new code is all marked red in the coverage tests.

**Comment by UplinkCoder** [comment]
@WalterBright It's not something you can write tests for.
You could but that would mean you'd have maintain them on every semantic or ast change.

**Comment by WalterBright** [comment]
You don't actually have to test the output. But it needs to be exercised.

**Comment by UplinkCoder** [comment]
@WalterBright should be covered now

**Comment by UplinkCoder** [comment]
I have no idea why this fails on  travis with gdc.
But this is primarily a developer-tool anyhow, and not for daily use.

**Comment by ibuclaw** [comment]
Thou shalt not break gdc. :-)

**Comment by ibuclaw** [comment]
There's probably nothing in this PR that breaks it, but as you've never added tests for `-vcg-ast` before, there may be something funny going on elsewhere that has never been caught.

**Comment by ibuclaw** [comment]
Hmm, I seem to get a segfault in evalu8.c when testing locally, and I have no idea why, must be a g++-7 regression.  @WalterBright - looks like there's some wrong-code in evalu8 also.

**Comment by ibuclaw** [comment]
Seems like it's a reference counting bug that is causing a double free.  First the data in `new Outbuffer` is freed by the dtor in `File`, then it is freed again by the dtor in OutBuffer.

**Review by ibuclaw — CHANGES_REQUESTED** [review]
You must add `cgFile._ref = 1;` immediately after `cgFile.setbuffer()`.

https://github.com/dlang/dmd/blob/3698d759cbcb6ef72668db6fe01966ce3e133cd2/src/ddmd/mars.d#L1607-L1608

**Comment by UplinkCoder** [comment]
@ibuclaw done. Thanks for the heads-up, I would not have found this one.

**Comment by UplinkCoder** [comment]
@WalterBright, @andralex  ready for merge.

**Review by ibuclaw — APPROVED** [review]

**Pull request merged**
