### PR TITLE
callfunc: make side effects of 'this' happen consistently before args

### PR DESCRIPTION
**Pull request by WalterBright**
Added a bit of `const` and `private` too.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@WalterBright could we please fix this in the frontend. 
the order-of-evalutation issues affect ctfe as well.

**Comment by yebblies** [comment]
This has a severe lack of test cases...

**Comment by WalterBright** [comment]
It has 100% test coverage now.

**Review by andralex — APPROVED** [review]
noice

**Pull request merged**
