### PR TITLE
[cleanup] Finish moving glue functions out of classes

### PR DESCRIPTION
**Pull request by yebblies**
Net -216 lines.

### CODE REVIEW

**Comment by yebblies** [comment]
Green now, I missed renaming one of the local variables that conflicted.

With this, gluestub is looking very light!

We have some functions to trigger typeinfo/helper/init/etc generation:
```
toInitializer
toModuleAssert
toModuleUnittest
toModuleArray
getInternalTypeInfo
getTypeInfo
```
Backend/object emission:
```
backend_init
backend_term
obj_start
obj_end
obj_write_deferred
genObjFile
genhelpers
```
Library stuff (this should probably be in frontend/driver code)
```
LibMSCoff_factory
LibOMF_factory
LibElf_factory
LibMach_factory
```
Inline asm: `asmSemantic` (should probably be in the frontend)
And one function that should probably be in Target: `retStyle`

**Comment by yebblies** [comment]
Cool.  Is there an easy way to see a diff with LDC's current frontend patches?

**Comment by ibuclaw** [comment]
I'll need to update my PR diff.  However it will not be representative of the current situation - just what the difference *should* be after I get round to the many, many visitor conversions.

@yebblies - Apart from what you can see when you search for ``IN_GCC`` in dmd, there is ``ExtAsmStatement`` class, and LDC has it's own ``AsmBlockStatement`` too.  IIRC, I seem to recall the general consensus being to add these to statement.h so they get included in the ddmd shared source (but version'd out).

**Comment by yebblies** [comment]
I was thinking we add parser support for `ExtAsmStatement`/`AsmBlockStatement`, if they don't parse already, then stub them out in semantic for dmd.

Visitors have solved the problem of adding methods fairly well, but we still have the problem of storing backend-dependent state.  I'm thinking of `Type::ctype`, `Dsymbol::csym` and similar.  What do you think about just moving them into hash tables?

**Comment by ibuclaw** [comment]
It would have to be a void* if it goes in shared code.  Otherwise, we could have a ``class Backend`` that I mentioned in another PR.  ie:
```
class Dsymbol : public xxx
{
...
  Backend btype;
}
```
And in dmd-specific headers:
```
class DMDBackend : public Backend
{
...
}
```

Would that go down well?

**Comment by yebblies** [comment]
My concern is that that doesn't scale well.  We'd need a different type for every ast class that needs to store data, and while it makes sense to group all the variable the backend needs together, I'm hoping there will be (many) other consumers in the future.

**Comment by ibuclaw** [comment]
@yebblies - I only suggest as GDC uses the same type across the board for all kinds of symbols - decls, types, etc... so it makes most logical sense for us. :)
How can you achieve it in dmd? You could use a union maybe...

**Comment by andralex** [comment]
noice

**Comment by yebblies** [comment]
Sooo anyone want to merge this or should I start splitting it up?

**Comment by 9rnsr** [comment]
Looks good to me.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Auto-merge toggled off

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Pull request merged**
