### PR TITLE
dinterpret.d: try to get that .origin hack to work

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
Is there any way to get a stack trace from any of these test runs?

**Comment by thewilsonator** [comment]
Throw an exception?

**Comment by WalterBright** [comment]
They're seg faulting.

**Comment by thewilsonator** [comment]
Oh it is not the assert you added, never mind.

**Comment by WalterBright** [comment]
I think I might have found it.

**Comment by WalterBright** [comment]
At least it doesn't seg fault now.

**Pull request merged**
