### PR TITLE
fix issue 18093: [Reg 2.071] MSCOFF: dmd crashes when overriding a C+…

### PR DESCRIPTION
**Pull request by rainers**
…+ method in a mixin template

Latest dmd no longer builds against VC...

### CODE REVIEW

**Comment by rainers** [comment]
Should this be based on stable instead? IIRC stable is supposed to be branched off master anyway and the regression seems pretty old...

**Comment by wilzbach** [comment]
> IIRC stable is supposed to be branched off master anyway

The branch-off should happen in the next few days. We can always rebase if this doesn't make it in before the branch-off.

**Review by PetarKirov — APPROVED** [review]

**Comment by WalterBright** [comment]
It seems odd that, despite having a test case, zero lines of the patch are executed?

**Comment by rainers** [comment]
> It seems odd that, despite having a test case, zero lines of the patch are executed?

The changed code is executed under Windows only, coverage is posix only.

**Comment by JinShil** [comment]
> The changed code is executed under Windows only

There doesn't appear to be anything Windows-specific in the code.  Could you elaborate on why this code in only executed in Windows?

**Comment by rainers** [comment]
The function `overrideInterface` is only called from https://github.com/dlang/dmd/blob/master/src/dmd/dsymbolsem.d#L4512 under condition global.params.mscoff, and from the VisualCPPMangler.

**Review by JinShil — APPROVED** [review]

**Comment by rainers** [comment]
@MartinNowak AFAICT the next release has been branched off master in the meantime. It would be good to cherry-pick this for stable, too. Otherwise there is no released compiler that can build the win64 version of dmd.

**Comment by wilzbach** [comment]
> @MartinNowak AFAICT the next release has been branched off master in the meantime. It would be good to cherry-pick this for stable, too. Otherwise there is no released compiler that can build the win64 version of dmd.

Yes and cherry-picking is pretty easy: `git cherry-pick <commt-hash>` ;-)
No need to bother Martin for this:

See: https://github.com/dlang/dmd/pull/7481

**Pull request merged**
