### PR TITLE
Group together public and private parts of VisualCPPMangler

### PR DESCRIPTION
**Pull request by ibuclaw**
Just changing:

```
class
{
  private:
    ...
  public:
    ...
  private:
    ...
}
```

To:

```
class
{
  private:
    ...
  public:
    ...
}
```

Though the diff doesn't seem to understand how to represent the change correctly. ;-)

### CODE REVIEW

**Comment by yebblies** [comment]
Why?

**Comment by ibuclaw** [comment]
I was adding some other method and got confused.

**Comment by yebblies** [comment]
Ok, but is it really worth the churn?  Maybe it would be better to just remove the `private` tags, it's not like protection is really used in dmd anyway.

**Comment by ibuclaw** [comment]
*Shrug* maybe.  It would also be nice if common methods between the two shared the same names.  Instead what we have is ``mangle_function`` vs. ``mangleFunction``.  Cause that helps me when I want to updates in two places... :)

**Comment by yebblies** [comment]
I've always wanted to merge these, or at least give them a common base class.  I'd be more supportive of renaming the functions than moving them around.

**Comment by WalterBright** [comment]
I'll have to agree with @yebblies . This is 784 lines of churn, and actually is quite impossible to review to see if it really is just moving things around.

**Comment by WalterBright** [comment]
I'm going to close this. I'm very concerned with the length of and steadily growing size of the regression list. Large refactors will just make everything worse.

**Comment by andralex** [comment]
I'm with @yebblies et al...

**Pull request closed without merging**
