### PR TITLE
hdrgen: ob: add support for '@live' string pretty print

### PR DESCRIPTION
**Pull request by ljmf00**
Added equivalent string representation of '@live' for stcToString() and
DtorDeclaration visitor.

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by Geod24** [comment]
Needs tests

**Comment by ljmf00** [comment]
> Needs tests

Sure. I'll add more tests because this feature is not tested for any attribute. I'll add it for other attributes, as well.

**Comment by ljmf00** [comment]
@Geod24 Added `@live` to the existing tests for other attributes.

**Comment by ljmf00** [comment]
Uhhhgg, tests are failing when using `-inline`?

**Comment by ljmf00** [comment]
> Uhhhgg, tests are failing when using `-inline`? Why tho?

Nevermind, I thought it was using the same header file. Didn't read the log carefully. Should be good now.

**Pull request merged**
