### PR TITLE
[RFC]cache vptr - surprisngly effective

### PR DESCRIPTION
**Pull request by UplinkCoder**
According to the profile this is effective.
At least on my machine and on the cases I ran it on.

### CODE REVIEW

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
Rather a sign of dmd's bad optimizer.

**Comment by UplinkCoder** [comment]
@MartinNowak dmds optimizer is relatively hard to improve. (Without having looked to closely at it)

**Comment by UplinkCoder** [comment]
@klickverbot At the end of the day dmd compiles with dmd by default.
and dmd ~master does not compile cleanly without -version=MARS

**Comment by UplinkCoder** [comment]
Oh

**Comment by UplinkCoder** [comment]
Thanks for the info

**Pull request merged**
