### PR TITLE
Mangle extern(C++) ctor as C++ ctor.

### PR DESCRIPTION
**Pull request by redstar**
Additionally, it disallows a extern(C++) ctor to have a body.
It should be safe to call a C++ ctor from C++ and D as long as
the initialization rules from C++ are used. Disallowing an ctor
body ensures this.

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
So this is only for interfacing with foreign C++ code, not for C++ to interface with D code ?
I'm pretty sure we'll get soon enough a request of to do the later.

Anyway, a bit of self-promotion: https://forum.dlang.org/post/576C770B.4060408@sociomantic.com ;)

**Comment by WalterBright** [comment]
> Additionally, it disallows a extern(C++) ctor to have a body.

I agree with @mathias-lang-sociomantic and this restriction should not be added. Compatibility goes both ways.

**Comment by redstar** [comment]
My ultimate goal is to add interfacing for both ways. I added the restriction only to make it possible to split the development into two steps. I still try to figure out where to change the initialization of a class/struct.

@mathias-lang-sociomantic I already work on a PR for the language chance.

**Comment by redstar** [comment]
I removed the restriction. But without changing the initialization, this is a bit dangerous.

@mathias-lang-sociomantic I didn't noticed that @JohanEngelen already created a PR for the spec change!

**Comment by mathias-lang-sociomantic** [comment]
> @mathias-lang-sociomantic I didn't noticed that @JohanEngelen already created a PR for the spec change!

You mean https://github.com/dlang/dlang.org/pull/1397 ? That's only for `extern(C++, {class,struct{)`. Or did I miss one ?

**Pull request closed without merging**
