### PR TITLE
[easy review] Reenable development utility astTypeName

### PR DESCRIPTION
**Pull request by UplinkCoder**
Getting this merged will allow me to continue work on newCTFE on ~master.
@Geod24  @RazvanN7

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Test failures on build-kite are due to some projects taking too much resources.

**Comment by BorisCarvajal** [comment]
I fixed that file a few days ago #10833. It has no conflicts, though.

**Comment by UplinkCoder** [comment]
Interesting I thought nobody besides me used it 😂

**Comment by BorisCarvajal** [comment]
It's really handy for debug printing. I even changed it to get the base classes names too.

**Review by wilzbach — DISMISSED** [review]
How about only including it in the debug build?

**Comment by UplinkCoder** [comment]
@wilzbach it hardly takes up any space, and is a very good taste to make sure external visitors don't break.

**Pull request merged**
