### PR TITLE
Fix issue 16449 - Add support for the RDTSCP opcode in IASM.

### PR DESCRIPTION
**Pull request by LemonBoy**

### CODE REVIEW

**Comment by BBasile** [comment]
Can you rebase your PR and change the commit message to 
`Fix  issue 16449 - Add support for the RDTSCP opcode in IASM.` please ?
The sharp is not recognized by the dlang bot and it won't be able to auto-close the issue.

**Comment by LemonBoy** [comment]
I've updated both the PR and ameded the titles

**Comment by andralex** [comment]
thx

**Comment by andralex** [comment]
Auto-merge toggled on

**Pull request merged**
