### PR TITLE
remove getLabel() and labelToBlock() as dead code

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by WalterBright** [comment]
Ah, I thought https://github.com/dlang/dmd/pull/10322 had been pulled.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
```
dmd/s2ir.d(459): Error: undefined identifier `getLabel`
dmd/s2ir.d(519): Error: undefined identifier `getLabel`
dmd/s2ir.d(459): Error: undefined identifier `getLabel`
dmd/s2ir.d(560): Error: undefined identifier `getLabel`
dmd/s2ir.d(519): Error: undefined identifier `getLabel`
dmd/s2ir.d(560): Error: undefined identifier `getLabel`
```

or not.

**Comment by WalterBright** [comment]
Blocked by #10322

**Comment by thewilsonator** [comment]
There was a network failure on the doc tester. Please push and re-add auto-merge

**Comment by thewilsonator** [comment]
The failures are still there.

**Comment by WalterBright** [comment]
Yah, looks like all unrelated networking problems.

**Pull request merged**
