### PR TITLE
optimize instance size of SymbolExp and VarExp

### PR DESCRIPTION
**Pull request by ghost**
From 64 and 65 to 57 and 58, so the positive effect is for VarExp, a small block is saved.

### CODE REVIEW

**Comment by nordlow** [comment]
There's are many more of these reordering on descending `alignof` for all the AST-nodes possible to save more words.

Some compile-time analysis on the '.tupleof' of all these AST-nodes could deduce the optimal packing reordering.

**Comment by NilsLankila** [comment]
Is there anything to discuss here ?

**Comment by nordlow** [comment]
> Is there anything to discuss here ?

Not from my side, thanks.

**Comment by NilsLankila** [comment]
@thewilsonator or @Geod24, can you merge this one ?

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
