### PR TITLE
Fix Issue 2195 - Variable shadowing in foreach is not detected and reported

### PR DESCRIPTION
**Pull request by RazvanN7**
Blocked by: https://github.com/dlang/druntime/pull/2791

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by RazvanN7** [comment]
Is there a reported issue on this? I would expect that this does not happen if the variable is not passed by ref (`foreach (ref var; range)`).

**Comment by nordlow** [comment]
I've seen it in the spec somwhere but it has never been implemented. I can't find anything at https://dlang.org/spec/statement.html right now.

Right, @WalterBright @andralex?

**Comment by CyberShadow** [comment]
Bug, it probably should not trigger across nested function boundaries:
https://issues.dlang.org/show_bug.cgi?id=21272

**Comment by RazvanN7** [comment]
Fix: https://github.com/dlang/dmd/pull/11790

**Pull request merged**
