### PR TITLE
[REG2.067a] Issue 14304 - ICE with static immutable variable CTFE

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14304

### CODE REVIEW

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by schuetzm** [comment]
I think `ownedByCtfe` should be an enum instead of using magic values.

**Comment by 9rnsr** [comment]
@schuetzm Yes, it would be better. I'll refactor code later.

**Comment by MartinNowak** [comment]
Yes it should be, but we're a little in a hurry, so I skipped the nitpicking.

**Pull request merged**
