### PR TITLE
add mscoffobj to SCPP build

### PR DESCRIPTION
**Pull request by WalterBright**
This doesn't affect dmd, it just harmonizes the object file generation with DMC++ to make the diverse builds less diverse.

### CODE REVIEW

**Comment by WalterBright** [comment]
The buildkite error looks irrelevant.

**Review by Geod24 — APPROVED** [review]
Nice simplification.

**Comment by Geod24** [comment]
@WalterBright : Side question, regarding the backend. What's the reason for not using `dmd.root` modules there ? Is it documented anywhere ?

**Comment by WalterBright** [comment]
> Side question, regarding the backend. What's the reason for not using dmd.root modules there ?

The original reason is root was in D and the backend was in C++. Now it's more of a "how much time do I want to spend on that".

**Pull request merged**
