### PR TITLE
fix bugzilla Issue 24315 - dmd/cpreprocess.d:87: warning: use of tmpn…

### PR DESCRIPTION
**Pull request by WalterBright**
…am is dangerous use mkstemp

This fixes it for Posix versions. Windows needs a separate implementation.

The fix is to capture the stdout of the preprocessor, rather than write it to and retrieve from a temporary file.

### CODE REVIEW

**Comment by RazvanN7** [comment]
Regressions should target stable.

**Comment by thewilsonator** [comment]
Is it a regression though? its a DMD internal potential safety issue.

**Comment by RazvanN7** [comment]
Technically, it's a regression since before using tmpnam the problem didn't exist.

**Comment by dkorpel** [comment]
But the offending code was committed to master on Jan 2, it's not in the stable branch yet

**Comment by RazvanN7** [comment]
Oh, ok.

**Pull request merged**
