### PR TITLE
[No Pull] Trace symbol time

### PR DESCRIPTION
**Pull request by UplinkCoder**
This is just to use the tester.

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Why does this thing automatically request freaking reviews.

**Comment by UplinkCoder** [comment]
you know why this fail, right ?
Because during the compilation of phobos there are more then 64M calls to semantic.

**Comment by UplinkCoder** [comment]
@quickfur you might be interested in this :)

**Comment by quickfur** [comment]
Thanks! I'll git pull this to my local repo and see if I can find out what's going on with my low-memory system.

**Comment by UplinkCoder** [comment]
@quickfur you'll have to modify root/rdmd.d and add a static varaible to sum up the allocated mem, put that into the symbol-trace-record, and you should be able to reconstruct the allocation patterns from there.

**Comment by UplinkCoder** [comment]
What is going on here ?
I never closed this.

**Comment by quickfur** [comment]
Are you sure somebody didn't hijack your github account?  I've never had this happen to me.

**Pull request closed without merging**
