### PR TITLE
[REG] fix Issue 16027 - Wrong result of double multiplication

### PR DESCRIPTION
**Pull request by WalterBright**
https://issues.dlang.org/show_bug.cgi?id=16027

### CODE REVIEW

**Comment by WalterBright** [comment]
This is a serious regression (silent bad code), and pulling this should be a priority.

**Comment by CyberShadow** [comment]
Shouldn't regression fixes target stable?

**Comment by Duncan--** [comment]
How on earth did something this basic get through regression testing?
Have the inadequate tests been identified - I see no mention of that?

**Comment by yebblies** [comment]
> How on earth did something this basic get through regression testing?
Have the inadequate tests been identified - I see no mention of that?

This PR contains a new test...

**Comment by TooHuman** [comment]
Thanks for getting this fix out so fast, I thought it was my code that was wrong when I discovered it. Will this be pushed straight to an updated stable branch or will it be delayed?

**Comment by AndrejMitrovic** [comment]
> How on earth did something this basic get through regression testing?

I think the majority of tests that we have are testing the front-end. The backend existed before DMD or its test-suite was created.

**Comment by WalterBright** [comment]
It wasn't detected by the back end test suite, either.

**Comment by MartinNowak** [comment]
> Shouldn't regression fixes target stable?

Yes they should, then I wouldn't need someone [in the beta thread](http://forum.dlang.org/post/pgztvdpckhfuqpukgood@forum.dlang.org) tell me about this PR.
Also highly favoured is to put important PRs on Trello https://trello.com/b/XoFjxiqG/active.

**Comment by MartinNowak** [comment]
Please rebase against stable and open a new PR.

**Comment by WalterBright** [comment]
Sigh. Here we go again. I have a 'stable' branch on my fork. I update it with the official stable. I commit the fixes. I do 'git push origin stable' and nothing appears on my github fork under 'stable'.

**Pull request closed without merging**
