### PR TITLE
Fix issue 22804: multiple object files without linking produces broken files

### PR DESCRIPTION
**Pull request by ljmf00**
CC @rainers .

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ljmf00** [comment]
Fixed line endings and used spaces instead of tabs for consistency.

**Comment by thewilsonator** [comment]
@ljmf00 please merge when green.

**Review by RazvanN7 — APPROVED** [review]

**Comment by ljmf00** [comment]
Now, I merge stable to master?

**Comment by thewilsonator** [comment]
Merging stable into master can be done at any time by anyone. 
As to whether it is necessary in this case: does the absence of this block other PRs to master? If yes or in doubt merge.
Otherwise its probably not necessary, but still harmless.

**Pull request merged**
