### PR TITLE
Sync up names of member variables that conflict with D keywords

### PR DESCRIPTION
**Pull request by yebblies**
The D versions were renamed automatically by magicport, but the C++ side was never updated.

### CODE REVIEW

**Comment by 9rnsr** [comment]
I dislike this. The names prefixed with underbar are just the result of automatic conversion and aren't follow existing dmd source code naming scheme. Changing C++ code will increase inconsistency.

**Comment by yebblies** [comment]
> Changing C++ code will increase inconsistency.

Do you mean changing the D code?  This PR _is_ changing the C++ code.

**Comment by 9rnsr** [comment]
I mean changing both.

**Comment by yebblies** [comment]
I agree, but I don't have the willpower to go through a naming debate right now.  If you have names in mind you'd be happy to merge then let me know and I'll update it.  Otherwise this is preventing compiling the glue layer with https://github.com/D-Programming-Language/dmd/pull/5082 's generated headers.

**Comment by WalterBright** [comment]
We can always change the names later. This is just getting things to work.

**Comment by yebblies** [comment]
Thanks Walter!  @9rnsr Let me know if you have preferred names, I'll be happy to change them.

**Pull request merged**
