### PR TITLE
Fix ASTNull

### PR DESCRIPTION
**Pull request by davispuh**
15b6ac7d40eee622bdb752fa05ccff046eb1b96f addded

`Parser!ASTNull(null, null, false)`

which crashes

````
object.Error@(0): Access Violation
----------------
0x005E0673 in ddmd.lexer.Lexer ddmd.lexer.Lexer.__ctor(const(char)*, const(char)*, uint, uint, bool,bool) at dmd\src\ddmd\lexer.d(189)
0x004E6ADF in ddmd.parse.Parser!(ddmd.astnull.ASTNull).Parser ddmd.parse.Parser(ddmd.astnull.ASTNull).Parser.__ctor(ddmd.astnull.ASTNull.Module, const(char)[], bool) at dmd\src\ddmd\parse.d(275)
0x004D4A07 in void ddmd.parse.__unittestL8426_10() at dmd\src\ddmd\parse.d(8429)
0x004F84AC in void ddmd.parse.__modtest()
0x005F105D in scope int core.runtime.runModuleUnitTests().__foreachbody1(scopeobject.ModuleInfo*)
0x005EE80B in scope int object.ModuleInfo.opApply(scope intdelegate(object.ModuleInfo*)).__lambda2(immutable(object.ModuleInfo*))
````

### CODE REVIEW

**Comment by UplinkCoder** [comment]
@davispuh change commit message please.

**Comment by UplinkCoder** [comment]
@MartinNowak can you fix the commit message by doing a rebase -i into `check for source !is null berfore parsing` ?

**Comment by jacob-carlborg** [comment]
Just as https://github.com/dlang/dmd/commit/15b6ac7d40eee622bdb752fa05ccff046eb1b96f, this was merged a bit too soon. Unit tests, that is `unittest` blocks inside the DMD source code, are not run as part of the regular test suite.

@MartinNowak @davispuh @RazvanN7

**Comment by wilzbach** [comment]
> Unit tests, that is unittest blocks inside the DMD source code, are not run as part of the regular test suite.

-> https://github.com/dlang/dmd/pull/6767

**Comment by jacob-carlborg** [comment]
> -> #6767

That's great 👍.

**Pull request merged**
