### PR TITLE
[Test] travis CI test build

### PR DESCRIPTION
**Pull request by jpf91**
Do NOT merge!

### CODE REVIEW

**Comment by wilzbach** [comment]
@jpf91 may I ask what you are trying to achieve? Maybe I can help ;-)

**Comment by jpf91** [comment]
Testing new GDC binaries ;-) Unfortunately there are  two problems: One is a regression in GDC and the other is travis-CIs binutils package being too old. I've got no clue how to solve the second problem...

http://forum.dlang.org/post/o2ep38$1n71$2@digitalmars.com

**Comment by wilzbach** [comment]
> I've got no clue how to solve the second problem...

Hmm - how about using GCC5? E.g. something like:

```
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
```

**Comment by jpf91** [comment]
Interesting. These toolchains provide the newest GCC versions but no new binutils so they should be affected by the same issue. I'll have to test this later, thanks.

**Comment by jpf91** [comment]
Turns out I just have to use an old binutils version when compiling the GCC binaries. Otherwise GCC enables code which only works with newer binutils versions.

**Pull request closed without merging**
