### PR TITLE
use ENTER instruction only for 16-bit codegen

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
See http://forum.dlang.org/post/ytaicvubtxfdgctchngb@forum.dlang.org

**Comment by WalterBright** [comment]
This is not true for 16 bit code generation, which is still supported by the code generator. In addition, ENTER is shorter, and so is appropriate when being optimized for space, also supported by the code generator. It can't be removed wholesale.

I'm not sure which CPU made ENTER slower, but the code generator supports quite a number of CPU specific optimizations from the 8088 (!) to the present.

**Comment by WalterBright** [comment]
If ENTER appears in speed optimized code, then fix that and reopen this.

**Comment by adamdruppe** [comment]
D doesn't support 16 bit code anyway... can you at least like #ifdef it if this code is shared with dmc? (BTW I still kinda like dmc's 16 bit support, but dmd doesn't need it)

**Comment by BBasile** [comment]
> If ENTER appears in speed optimized code, then fix that and reopen this.


It does, just checked again. Something like `enter &= globals.release;` at the right places would do the trick to generate the full prologue when `-release` is defined.

**Comment by Temtaime** [comment]
16 bit in 2015? Are you joking?

**Comment by Safety0ff** [comment]
IIRC valgrind doesn't support ENTER/LEAVE, and its use was supposed to be removed (atleast on IA-32 & amd64)
https://issues.dlang.org/show_bug.cgi?id=11788

**Comment by WalterBright** [comment]
> D doesn't support 16 bit code anyway...

But dmc does, and the code generator is shared, and the dmc test suite does a lot of code gen checking that the dmd suite does not.

> can you at least like #ifdef it if this code is shared with dmc?

I've been trying to remove all the #ifdef's because I'd eventually like to convert the source code to D. Besides, I cannot identify any detriment to having a test for I16 here and there.

**Comment by WalterBright** [comment]
> valgrind doesn't support ENTER/LEAVE

One wonders why valgrind doesn't support the complete instruction set.

**Comment by WalterBright** [comment]
> 16 bit in 2015?

dmc is the only compiler supporting DOS that is still maintained. There are users of it I support.

**Comment by MartinNowak** [comment]
Updated to only use ENTER for 16-bit codegen.

**Comment by WalterBright** [comment]
There's no reason to not use ENTER/LEAVE for 32/64 bit code when optimizing for space on Windows. Valgrind doesn't run on Windows, so Valgrind's bugs are irrelevant.

**Pull request closed without merging**
