### PR TITLE
Fix issue 20835 - Enum member attributes being evaluated in wrong scope.

### PR DESCRIPTION
**Pull request by BorisCarvajal**

### CODE REVIEW

**Comment by UplinkCoder** [comment]
Nice catch!

**Comment by JonathanILevi** [comment]
Does this also fix #19344? which was marked as a duplicate?
Should the code from #19344 also be added as a unit test?

**Comment by BorisCarvajal** [comment]
Yes, I'll add it.

**Review by thewilsonator — APPROVED** [review]

**Review by Geod24 — APPROVED** [review]
Thanks!

**Comment by Geod24** [comment]
@BorisCarvajal : Check your emails, you should have an invite for Buildkite and SemaphoreCI, so you can re-trigger the CIs in case of failure.

**Comment by BorisCarvajal** [comment]
@Geod24 cool, thanks.

**Pull request merged**
