### PR TITLE
Remove more ancient stuff from optimizer

### PR DESCRIPTION
**Pull request by WalterBright**
All localized changes.

### CODE REVIEW

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
Thanks, @yebblies , for the quick action on these!

**Comment by WalterBright** [comment]
You guyz still there? :-)

**Comment by yebblies** [comment]
Yeah, we're trying to get LDC to build DDMD.  Currently links successfully but DDMD segfaults.

**Comment by WalterBright** [comment]
dazz

**Comment by ibuclaw** [comment]
Congrats.  I should try running the testsuite on my GDC built DDMD. ;-)

**Comment by yebblies** [comment]
Yes, please do!

LDC-built DDMD is currently showing performance on par with g++ built dmd, even with the code to hook D's `new` disabled.

**Comment by ibuclaw** [comment]
> LDC-built DDMD is currently showing performance on par with g++ built dmd

Cool.  I've built ddmd using my 2.067 PR https://github.com/D-Programming-GDC/GDC/pull/99 (which incidentally has nothing from 2.067 merged in apart from C++ mangling) using dflags ``-O2 -frelease``. And I can confirm that everything builds and passes both unittests + testsuite

**Comment by ibuclaw** [comment]
Just need the PR in phobos to be merged in.

**Pull request merged**
