### PR TITLE
[DDMD] Convert idgen to D

### PR DESCRIPTION
**Pull request by yebblies**
Host D compilers are now available on most platforms, let's see how this goes...

Previous pull: #2783

### CODE REVIEW

**Comment by yebblies** [comment]
Update: Host D compilers are now available on all of the autotesters, and the config file issue has been fixed for all posix platforms.

That just leaves a similar config fix for windows blocking this pull request.  Getting close!

**Comment by yebblies** [comment]
This is now ready to go.  I understand that this will break many people's setups, but that is inevitable and I would rather find critical problems out now when it is still easy to revert.

Note that this change does not require a _recent_ host compiler, just a working one.  DMD/GDC/LDC should all be fine.  Even SDC might work.

@WalterBright @andralex

**Comment by ibuclaw** [comment]
For porting to new architectures, the worst case is to pre-generate the id.c/id.h

This PR is low risk at best.

**Comment by redstar** [comment]
Yeah, I also agree.

**Comment by MartinNowak** [comment]
Can we try to establish something convention for D env variables.
I used the following for Travis-CI.

- `DC` = native compiler binary (either `dmd`, `ldc2` or `gdc`)
- `DMD` = dmd style wrapper (either `dmd`, `ldmd2` or `gdmd`)

So I'd be in favor of using `HOST_DMD` here, otherwise LGTM.

**Comment by yebblies** [comment]
If you can get the autotester changed to provide `HOST_DMD` I'll update the makefile(s), but I don't want to block this on autotester changes again.

**Comment by Orvid** [comment]
Are there any plans to re-write idgen to use d-style code rather than just a direct port?

**Comment by MartinNowak** [comment]
The goal is to first make the transition to D keeping the code C++ish so we can apply patches to both DMD and ddmd. Then change to something more D-ish later.
It's really important that we can compile the compiler with the last 1 or 2 releases, so using newest D features remains verboten.

**Comment by yebblies** [comment]
Thanks!

> Are there any plans to re-write idgen to use d-style code rather than just a direct port?

There doesn't seem to be much point at the moment.  Would it work better?  For now phobos is banned inside ddmd.

Later, it will be possible to use ctfe and get rid of idgen entirely, but only once D versions of all the required classes are available.

**Comment by jacob-carlborg** [comment]
> There doesn't seem to be much point at the moment. Would it work better?

I think it will be easier to read the source code. But that also depends on how the current translation looks like. For example, I think `foreach(e; msgtable)` is much more easy to read than `for (i = 0; i < sizeof(msgtable) / sizeof(msgtable[0]); i++)`.

**Comment by yebblies** [comment]
This file doesn't have a lot of complexity left to remove.  And apart from adding entries, it doesn't get edited a lot.

**Comment by jacob-carlborg** [comment]
Oh, I thought the original question was about the code base in general, not this specific file.

**Comment by yebblies** [comment]
Ah ok.  The main compiler code will certainly be updated to a better D style, but only after development on the C++ version stops.  I'm expecting a lot of clean up using foreach, strings and lambdas/opApply.

**Comment by jacob-carlborg** [comment]
That was what I thought. I got me worried there for a second :smiley:

**Comment by CyberShadow** [comment]
Posted a question on the forum: http://forum.dlang.org/post/berkxxqbqoxzitsulufd@forum.dlang.org

**Comment by WalterBright** [comment]
I've translated code from one language to another many times. One rule surfaces:

  Do not refactor until the translation is complete and all the tests pass.

**Comment by MartinNowak** [comment]
We need to figure out what to do about dmd.conf for the HOST_DMD compiler.
It's often necessary to put a dmd.conf file into dmd's src folder.
Implicitly picking up a dmd.conf from the current working directory is a terrible behavior for a tool.

**Comment by yebblies** [comment]
With https://github.com/D-Programming-Language/dmd/pull/4460 it's possible to just set `HOST_DC=path/to/dmd -conf=path/to/conf`.  It should work already on posix.

**Comment by yebblies** [comment]
> I think it will be easier to read the source code. But that also depends on how the current translation looks like. For example, I think foreach(e; msgtable) is much more easy to read than for (i = 0; i < sizeof(msgtable) / sizeof(msgtable[0]); i++).

> I've translated code from one language to another many times. One rule surfaces:
>
Do not refactor until the translation is complete and all the tests pass.

I've added support in magicport to automatically convert for into foreach - the rules are different with automated translation and a lot more refactoring is possible, because translation takes seconds to complete and can easily be done again and again, and there is never a point where the tests stop passing on the original code.

**Pull request merged**
