### PR TITLE
Fix error propagation: TraitsExp should return ErrorExp if any errors happen

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by yebblies** [comment]
Test case?

**Comment by 9rnsr** [comment]
@yebblies That's for the diagnostic issue found in #4846.

https://github.com/D-Programming-Language/dmd/pull/4846#discussion-diff-35853116

For the test, I tweaked `fail_compilation/ice14844.d`.

**Comment by yebblies** [comment]
Ok.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Pull request merged**
