### PR TITLE
Resurrect line spaces in dtemplate.d

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by WalterBright** [comment]
> 382 additions, 0 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

Hmmm....

**Comment by ibuclaw** [comment]
And it's not even April yet.

https://patch-diff.githubusercontent.com/raw/D-Programming-Language/dmd/pull/5594.diff

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
What is githubusercontent.com? Going directly to that doesn't work.

**Pull request merged**
