### PR TITLE
enable release optimizations when the existing RELEASE=1 flag is passed

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Needed by the release build script.

**Comment by WalterBright** [comment]
It'd be nice to put into the makefile some documentation on what the parameters to the makefile are.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
It seems that the Travis-CI build with `SELF_COMPILE=2` is broken by this change.

**Comment by MartinNowak** [comment]
My bad, I mixed up the PRs. This was already fixed in #5022.

**Pull request merged**
