### PR TITLE
Split needspkgmod.d by TEST_OUTPUT

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
This file actually represents two tests in one:
- wrong usage `-i`
- linkage failure because  a module is not compiled.

Side note:
This PR and #10836 contain the last missing `TEST_OUTPUT` sections for `fail_compilation`!

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by MoonlightSentinel** [comment]
Blocked by #10836

**Comment by MoonlightSentinel** [comment]
Included #10836 to implement the current solution. It's the best approach i could think of given the plethora of linker error message formats out there ...

**Review by thewilsonator — APPROVED** [review]

**Comment by kinke** [comment]
@MoonlightSentinel: Sorry, I don't know how to best contact you. First of all, thx for working on this stuff. The current `$n$`, `$p:...$` etc. are useful, but still not flexible enough to cover all issues for LDC. What I would really need would be an option to embed one or multiple regexes directly inside TEST_OUTPUT. E.g., for needpkgmod.d here, the error msg produced by LDC includes the name/path of the C compiler, which can be pretty much anything.

It'd be great if you could help out. Similar to LLVM's [FileCheck](https://llvm.org/docs/CommandGuide/FileCheck.html) (used for LDC-specific testing), I'd propose to be able to embed regexes in double-curly-braces, e.g.:
```
TEST_OUTPUT:
----
Error: {{.+}} failed with status: $n$
----
```

**Comment by MoonlightSentinel** [comment]
> @MoonlightSentinel: Sorry, I don't know how to best contact you.

I'm usually available via Slack.

> What I would really need would be an option to embed one or multiple regexes directly inside TEST_OUTPUT. [...].

Thought about that as well but didn't implement it back then. Guess I'll give it another try soon.

> I'd propose to be able to embed regexes in double-curly-braces, e.g.:

That syntax is used already IIRC, I would prefer the established `$...$`.

**Comment by kinke** [comment]
> That syntax is used already IIRC, I would prefer the established $...$.

Fine by me. I've worked around this for now via https://github.com/ldc-developers/dmd-testsuite/commit/d83968862bb9221f096d722384be10f7feea6218, so it's not pressing.

**Pull request merged**
