### PR TITLE
fix issue 12001 -  __traits(isSame) does not work with the basic types

### PR DESCRIPTION
**Pull request by ghost**
Very surprisingly not already fixed. As rationale, I quote the reporter:
> ...It really should be true ... to be useful in generic code.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Basile-z** [comment]
Sorry I didn't see the failure after running locally the test, So not ready yet.

**Comment by thewilsonator** [comment]
OK ping me when it is.

**Comment by Basile-z** [comment]
Ping @thewilsonator this is working now. It was a `getType()` vs `isType()` problem, the former always falls back to something, which i should know...

**Comment by thewilsonator** [comment]
Done.

**Pull request merged**
