### PR TITLE
Fix issue 18888 - extern(C++) template arg/alias arg mangling issue

### PR DESCRIPTION
**Pull request by TurkeyMan**
There was a problem where the name of the alias was being used instead of the name that the alias aliases...

### CODE REVIEW

**Comment by JinShil** [comment]
I don't think the changelog entry is necessary because this is fixing a bug.  The dlang-bot will automatically add a link to fixed bugs in the changelog automatically, if they are properly linked to the pull request.  I don't know of any algorithm for determining when a changelog entry is necessary but I'll say, IMO, it's only necessary for deprecations, enhancements, changes to the public API, and changes to language implementation that enable new idioms (just about everything except bug fixes, now that I read that sentence myself).

**Comment by JinShil** [comment]
Sorry for closing.  Pressed the wrong button.

**Comment by TurkeyMan** [comment]
Ohhhh no!!!! You just restarted the CI!! I've been waiting ##**_hours_**## for that to finish! >_<

**Comment by TurkeyMan** [comment]
You guys are so fickle! Last time I was rejected for not change-log entry... and it was also a bugfix.

**Comment by jacob-carlborg** [comment]
> You guys are so fickle! Last time I was rejected for not change-log entry... and it was also a bugfix.

There are many people involved with different mindsets and different ideas. 

Sometimes a bug is fixed by introducing a new feature, which in my opinion should have an explicit changelog. I think adding support for classes to `__traits(getLinkage)` deserves a changelog because new functionality was added.

**Comment by TurkeyMan** [comment]
I agree... I now have 5 PR's that all conflict with eachother, and none of them merge because CI takes HOURS to build.
The workflow here is really... un-fun.

**Review by jacob-carlborg — APPROVED** [review]

**Review by dnadlinger — APPROVED** [review]

**Comment by TurkeyMan** [comment]
I'll do that before risk of a release.
I'm not done here yet... we'll see how many more of these I get in.

**Comment by TurkeyMan** [comment]
Oh good, our old mates `bellevue`, `win-farm-1`, and `win-farm-2` are onto it!
They take an hour each! ;)

**Comment by wilzbach** [comment]
>  CI situation drives me off the deep-end

It's expected that auto-tester __never__ completes until the PR has auto-merge added to it as it will constantly restart the builds and deprecate all builds whenever something got merged at DMD, druntime or phobos.
So I really hope you didn't invest your time in waiting for them.
Just run the testsuite locally once (about 10s) and if you haven't done serious changes you should be good. Luckily most spurious failures have been removed, otherwise report them in #ci on Slack.

**Pull request merged**
