### PR TITLE
backend: transition to @safe code part 14

### PR DESCRIPTION
**Pull request by WalterBright**
Rationale is here: #12327

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by WalterBright** [comment]
C++ interop tests / Run (macOS-10.15, clang-9.0.0) fails pathetically with a message that says simply "this check failed" and puts a big X on the screen. I doubt it has anything to do with this PR.

**Comment by Geod24** [comment]
There's a simple solution to this:
Screen Shot 2021-04-04 at 23 50 52

**Review by Geod24 — APPROVED** [review]

**Comment by WalterBright** [comment]
> There's a simple solution to this:

Even better, fix the heisenbugs in the test suite!

**Comment by Geod24** [comment]
> Even better, fix the heisenbugs in the test suite!

Not everything that fails spuriously is a heisenbug. Or rather, not everything that fails spuriously can be fixed.
We depend on:
- Github API for pretty much everything;
- CirrusCI community edition (Google Cloud);
- The auto-tester and all its machines that, AFAIK, are not all co-hosted, and those that are live at an individual's house;
- Azure cloud (for Azure pipelines and probably some Github stuff);
- Agents which are spawned and shut down by a home-grown bot on demand (Buildkite);
- SemaphoreCI;
- CodeCov;
- `dlang.org`;
- AWS S3;
- CircleCI;
- Cybershadow's auto-tester;

In other words, we depend on all of the top 3 cloud providers, a lot of homegrown stuff managed by different people, and 5 different CI providers, and the Github API is a single point of failure. Not to mention that every single project we test in Buildkite could break without the author of the project knowing. And our CI is spread among multiple repositories, which all somehow manage to collaborate together.

So when a network request spuriously fail, or a VM fails to start, or is throttled, I don't think twice about it and I retry the check. If it starts to happen more frequently, I first check we have proper retries in place, then report the issue to the service provider if it persists.

**Comment by WalterBright** [comment]
Whenever the test suite fails, and the recommended solution is for the submitter to restart the tests, I suggest a better solution is to have the test suite restart the test automatically. In order to avoid gumming the system up, insert a wait before the restart.

**Pull request merged**
