### PR TITLE
make TypeTraits semantic more clear and prevent invalid type swaps

### PR DESCRIPTION
**Pull request by ghost**
The switch over the traits expression gives a better control over what's accepted and how the matching type or symbol is extracted.
Previously using `getType()` as a default fallback could lead to an invalid type swap from the expression type to the type represented by the `TypeTraits`.

This commits also restore the `getDsymbolWithoutExpCtx()` function as it was before the implementation of `TypeTraits`.

### CODE REVIEW

**Comment by Basile-z** [comment]
To the attention of @thewilsonator, there's no emergency for this one. It's better to wait in case one TOK would miss from the switch. So maybe put a WIP label in the meantime.

**Comment by thewilsonator** [comment]
Thanks! Tests?

(Also My time will be a bit limited over the next couple of days, apologies for any delays.)

**Comment by Basile-z** [comment]
There's no tests because this PR replace the current code with a more lower level approach.
However the coverage results indicate that there's one or two superfluous cases.

**Comment by Basile-z** [comment]
BTW you're not member anymore, I simply see "contributor" on the header of your answers ?

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
