### PR TITLE
Downgrade ICE's in cppmangle to errors

### PR DESCRIPTION
**Pull request by ibuclaw**
- Stores the function/variable location in the visitor so we are able to get correct line error reporting.
- Downgrades the ICE's to errors because there is _no_ protection whatsoever from, eg:

```
extern(C++):
int myCxxvar;
int myCxxfunc(int[4]);
int myCxxfunc2(shared int);
```

ICE and abort in these cases most certainly the wrong way to go about it.
- Noticed that functions may have `mangleExact` called more than once in the glue layer.  Once when generating the function symbol, and then multiplied by the total number of times the function is called.   Caching it prevents errors from being duplicated, tripleted, ad infinitum.  I suspect there is a speed gain (and a win for memory usage) too.

### CODE REVIEW

**Comment by ibuclaw** [comment]
May require:
- Adding fail tests in the testsuite
- Also updating the VisualCPPMangler

**Comment by ibuclaw** [comment]
I haven't tried ways of triggering the ICE's in the template mangling code.  They can be sorted out in another PR if I'm getting problems with them.

**Comment by yebblies** [comment]
I think these _should_ be ICEs.  The errors should be detected in `FuncDeclaration::semantic` etc

**Comment by ibuclaw** [comment]
Updated VisualCPPMangler.

> The errors should be detected in FuncDeclaration::semantic etc

That might lead to code duplication?  And for the moment, I'll be stubbing out any errors you give to static arrays, just to give me more time transitioning over ``va_list`` in a way that seems satisfactory.

**Comment by WalterBright** [comment]
ICEs are appropriate when those cases should never happen - if they do, it is a compiler bug. Changing these to errors implies that they are not compiler bugs, but user bugs. The inability to craft a test case for them confirms that it should not be possible to trigger them.

**Comment by yebblies** [comment]
It's not impossible to craft a test case for them, just use the banned types as an parameter for an extern(C++) function.  I'm saying the error should be detected during semantic on the function type, not during mangling.

**Comment by WalterBright** [comment]
Right, it should be detected earlier, not here.

**Pull request closed without merging**
