### PR TITLE
Issue 2354 - conditional compilation rejects else if the declaration is a single pragma

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=2354

Accept the semicolon followed by `Pragma`, although a semicolon followed by `Attribute` is disallowed in `parseBlock()`.

### CODE REVIEW

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks!

**Comment by WalterBright** [comment]
The D grammar needs to be reviewed for this change.

**Comment by 9rnsr** [comment]
I think this change does not need grammar update. As I commented in code,  DeclarationBlock already accepts a single semicolon. The token should be consumed as the part of `AttributeSpecifier`.

**Pull request merged**
