### PR TITLE
Issue 481 - Letting compiler determine length for fixed-length arrays

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=481

Sadly, the feature was removed from 2.067 release, but I still think the feature is useful. So I revive PR.

This commit also contains fixed for those issues:
- Issue 14066 - [ICE](init.c line 410) with wrongly used array definition syntax
- Issue 14069 - Partial type deduction should prefer the specified type qualifier
- Issue 14076 - Partial type deduction doesn't work with lambdas

### CODE REVIEW

**Comment by andralex** [comment]
I am definitely thinking [$] should not be in D. We need to achieve most of what it does with libraries.

The partial deduction part needs a DIP - it's too large to be introduced by means of a pull request. That said I must confess I'm unlikely to approve such a DIP - I've thought about partial deduction a lot over the past weeks and also inspected a lot of C++ code with an eye for its use. I don't think it enables us to do anything we currently cannot do.

I'm really sorry about good work going to waste. What I can promise is I'll do my best to prevent that from happening in the future.

**Comment by ibuclaw** [comment]
@andralex - This feature request was rejected, right?

**Comment by wilzbach** [comment]
> We need to achieve most of what it does with libraries.

FWIW we can't do this nicely with libraries at the moment: https://github.com/dlang/phobos/pull/4936

**Comment by andralex** [comment]
@ibuclaw affirmative. This should need a DIP, and the DIP is only successful if it demonstrates superiority compared to library-based approaches on important use cases.

**Comment by JinShil** [comment]
I suggest this be closed, delegating it back to the Bugzilla issue until either a library implementation or DIP emerges.  Any objections?

**Comment by wilzbach** [comment]
No the Phobos PR is still open too, so that one allows tracking this too.

**Pull request closed without merging**
