### PR TITLE
Revert "Merge pull request #3761 from quickfur/issue13116"

### PR DESCRIPTION
**Pull request by MartinNowak**
This reverts commit 24e8347f1fa4ccbb1cc6a27c40eedef1324e6c13, reversing
changes made to 5418b7120396f066ed1be941ad3f0c25c8ae0fe0.

### CODE REVIEW

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Auto-merge toggled off

**Comment by 9rnsr** [comment]
Don't introduce wrong-code bug again. Please read the summary in #3761.

**Comment by 9rnsr** [comment]
I opened a changelog documentation PR https://github.com/D-Programming-Language/dlang.org/pull/923 for the issue 13116 change.

**Comment by MartinNowak** [comment]
I'll turn this into a deprecation.

**Comment by MartinNowak** [comment]
Done, can we please merge this soon?

**Comment by mihails-strasuns-sociomantic** [comment]
Thanks, this also makes error/deprecation message for ref argument much more helpful.

**Comment by WalterBright** [comment]
This broke https://issues.dlang.org/show_bug.cgi?id=14284

**Pull request merged**
