### PR TITLE
fix Issue 15897 - private base class method not seen through derived class

### PR DESCRIPTION
**Pull request by MartinNowak**
- properly deprecate private symbol visibility through derived classes

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Looks like you need an update `checkimports2a`. The fix itself LGTM.

**Comment by MartinNowak** [comment]
> Looks like you need an update checkimports2a. The fix itself LGTM.

I rather wait for https://github.com/dlang/dmd/pull/5651/files#diff-00b32f1ed7ba16d50e1e619c297ff277L1315 to remove the nonsense message.

**Comment by MartinNowak** [comment]
Rebased

**Comment by MartinNowak** [comment]
Fixed

**Comment by AndrejMitrovic** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
This change will break existing valid code, without legitimate design decision.

If someone (@WalterBright and @andralex ?) get approved the [new design](https://issues.dlang.org/show_bug.cgi?id=15897#c12), it should be documented in changelog and language spec. I'll repopen the original bugzilla issue.

**Comment by AndrejMitrovic** [comment]
Hmm.. the change seemed logical to me at first. Think it needs to go through a DIP? We could revert until we agree on something.

**Comment by 9rnsr** [comment]
I also think the concept talked by @MartinNowak is logical. But I think a logical behavior is not always useful. 
I opened #5736 to revert this change on stable branch.

**Comment by MartinNowak** [comment]
This just turns an error into deprecation. We could discuss the change though. https://github.com/dlang/dmd/pull/5736#issuecomment-217639942

**Pull request merged**
