### PR TITLE
Fix the concat assign case of Issue 20321 in a frontend solution

### PR DESCRIPTION
**Pull request by SSoulaimane**
See discussion on #10510.

Do more lowering in the front-end that reduces the need to create temporaries in the glue layer.
This PR only does the concatenation assignment for arrays, but more cases could be potentially solved in the same way. 
When the glue layer decides to copy or move it doesn't call the copy constructor or the postblit since only the semantic phase knows how elaborate copy semantics works.

### CODE REVIEW

**Comment by SSoulaimane** [comment]
buildkite failures are fixed by this DUB PR https://github.com/dlang/dub/pull/1796.

**Comment by PetarKirov** [comment]
@SSoulaimane although I agree with the change to dub, it looks worrying that this PR causes change in behavior. Do you know what now causes DMD to "print some stuff in between calls of pragma(msg)"?

**Comment by SSoulaimane** [comment]
> Do you know what now causes DMD to "print some stuff in between calls of pragma(msg)"?

Yes, the first commit of this pull request moves druntime calls which are issued for array element concatenation from the glue layer to the front-end,  so now every time there is element concatenation it instantiates a template https://github.com/dlang/druntime/blob/cd1a3e06b912a801877a3104c5e57498970822ed/src/core/internal/array/appending.d#L16-L19. the template which imports the module `core.internal.array.utils`, subsequently DMD prints `import    core.internal.array.utils ...` in between the `pragma(msg)` calls, because one of the pragmas invokes a ctfe function which does array concatenation.

**Comment by PetarKirov** [comment]
The part that actually confuses me is this one:
> DMD prints import core.internal.array.utils ... in between the pragma(msg)

**Comment by SSoulaimane** [comment]
Yes, https://github.com/dlang/dub/blob/f87302dd206b0e5871b39704e694b2194e294aa5/source/dub/compilers/dmd.d#L130.

**Comment by RazvanN7** [comment]
This has been superseded by: https://github.com/dlang/dmd/pull/13495

**Pull request closed without merging**
