### PR TITLE
Issue 15680 - TypeInfo broken for typeof(null)

### PR DESCRIPTION
**Pull request by 9rnsr**
`builtinTypeInfo()` needs to return true for mutable `TypeNull`.

### CODE REVIEW

**Comment by 9rnsr** [comment]
Requires druntime fix: https://github.com/D-Programming-Language/druntime/pull/1498

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
But you'll need to rebase it :-)

**Comment by 9rnsr** [comment]
Rebased, thanks!

**Pull request merged**
