### PR TITLE
Replace hilariously out of date backend architecture document

### PR DESCRIPTION
**Pull request by thewilsonator**
Also on that subject why do we have two AA implementations, another leaking allocator, that leaks from malloc instead of the GC?

### CODE REVIEW

**Comment by thewilsonator** [comment]
@WalterBright can we:
* `rm backend/aarray.d` and replace its uses with `root/aav.d`?
* `rm backend/outbuf.d` and replace it with `root/outbuffer`?
* `rm backend/ph2.d` and leak from just the GC?
* `mv complex.d root/complex.d && rm backend/bcomplex.d`?

**Review by jacob-carlborg — CHANGES_REQUESTED** [review]
This looks pretty awful when it’s rendered: https://github.com/thewilsonator/dmd/blob/d38197fe1734cd03961bcb322b9fd926eafccebb/src/dmd/backend/backend.md

**Comment by jacob-carlborg** [comment]
I don’t think Walter want the backend to use the `root` package. Although I thought the reason for having the `root` package was for the frontend and backend to share code.

**Comment by thewilsonator** [comment]
Ow, yeah that it a horrible rendering (looks much nicer in plain text, lol). Fixed.

**Comment by thewilsonator** [comment]
Yes, a list looks much better.

**Comment by jacob-carlborg** [comment]
Perhaps make the filenames bold as well.

**Comment by thewilsonator** [comment]
Im about to go to sleep, don't let me stop you doing that ;)

**Review by jacob-carlborg — APPROVED** [review]

**Pull request merged**
