### PR TITLE
[DDMD] [refactor] Move toObjFile into a visitor

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by yebblies** [comment]
@ibuclaw One of the remaining glue visitors.

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by yebblies** [comment]
Thanks!

**Comment by ibuclaw** [comment]
Cool beans

**Comment by yebblies** [comment]
@ibuclaw @klickverbot See also #4291

**Pull request merged**
