### PR TITLE
fix Issue 21513 - [Reg 2.094.1] Slice assignment segmentation fault

### PR DESCRIPTION
**Pull request by WalterBright**
Don't `JE` over the register save code.

### CODE REVIEW

**Comment by Geod24** [comment]
Stable please

**Comment by WalterBright** [comment]
> Stable please

And this is the result of following the posted directions exactly.

**Comment by WalterBright** [comment]
I wish the directions given were complete, and the person who writes them would actually try them.

**Comment by WalterBright** [comment]
Here's what I did at my end:
```
mercury~/forks/dmd fix21513> git rebase --onto upstream/stable upstream/stable
First, rewinding head to replay your work on top of it...
^C
mercury~/forks/dmd (detached from 7233643)> git rebase --onto upstream/stable upstream/master
First, rewinding head to replay your work on top of it...
Fast-forwarded HEAD to upstream/stable.
mercury~/forks/dmd (detached from 7233643)> git push -f origin fix21513
Everything up-to-date
mercury~/forks/dmd (detached from 7233643)>
```

**Comment by RazvanN7** [comment]
You probably have to pull before you can rebase, just to make sure you have the latest stable.

I never had any problems with the suggested command.

**Comment by Geod24** [comment]
> Here's what I did at my end:
> [...]

You typed the wrong command, pressed `Ctrl + C` in the middle of it, leaving you in a detached state.
Those instructions are an help for users that need a bit of guidance, not a `git` introduction class.
And for what it's worth, they are correct. You just didn't push your branch. I'll do it for you.

**Comment by WalterBright** [comment]
> And for what it's worth, they are correct. You just didn't push your branch.

I did push my branch. That's what the original PR was - my pushed branch.

> that need a bit of guidance

I don't see much point in providing instructions that literally do not work. More advanced users won't be bothered by more thorough instructions. The benefit to you and @RazvanN7 is I won't be wasting your time with this problem, either.

**Comment by WalterBright** [comment]
> I'll do it for you.

Thank you.

**Comment by Geod24** [comment]
> I did push my branch. That's what the original PR was - my pushed branch.

What I meant is, as a result of not properly following the instructions, your branch wasn't pushed, hence why you were seeing a gazillions commits.

> I don't see much point in providing instructions that literally do not work.

Once again, it works, when followed. Your log above shows that you typed:
> mercury~/forks/dmd fix21513> git rebase --onto upstream/stable upstream/stable

While the bot's instruction is:
> git rebase --onto upstream/stable upstream/master

If you entered the correct command, the one given to you by the bot, things would have worked.

**Pull request merged**
