### PR TITLE
fix Issue 20466 - Optimizer clobbering msw register when testing it f…

### PR DESCRIPTION
**Pull request by WalterBright**
…or 0

Blocking https://github.com/dlang/dmd/pull/10679

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Should this target stable.

**Comment by WalterBright** [comment]
If it passes :-)

**Comment by WalterBright** [comment]
Refactored #10679 so this won't block it.

**Comment by WalterBright** [comment]
Note: this is an ugly little goto I added. It should be refactored. But it is better to separate the fix from the refactor, which is why I did it this way. It's good that D supports `goto` to enable this sort of thing.

**Comment by thewilsonator** [comment]
Indeed, can you come up with a slightly more descriptive name than `L1`? Otherwise looks great.

**Comment by WalterBright** [comment]
The comment associated with it is clear enough. Rebased to stable.

**Comment by WalterBright** [comment]
The buildkite errors:
```
dmd/complex.d(57): Deprecation: `opMul` is deprecated.  Use `opBinary(string op)(...) if (op == "*")` instead.
--
  | dmd/complex.d(57): Deprecation: `opMul_r` is deprecated.  Use `opBinaryRight(string op)(...) if (op == "*")` instead.
  | dmd/complex.d(62): Deprecation: `opMul` is deprecated.  Use `opBinary(string op)(...) if (op == "*")` instead.
  | dmd/complex.d(62): Deprecation: `opMul_r` is deprecated.  Use `opBinaryRight(string op)(...) if (op == "*")` instead.
  | dmd/complex.d(67): Deprecation: `opDiv` is deprecated.  Use `opBinary(string op)(...) if (op == "/")` instead.
```
are not relevant to this PR.

**Pull request merged**
