### PR TITLE
Workaround for issue 21654 - CodeCov build already finished

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Try adding the Azure/Cirrus jobs to the job count and expected CI's.

Upstream issue: https://github.com/codecov/codecov-bash/issues/411

### CODE REVIEW

**Comment by RazvanN7** [comment]
So upstream fails because we are sending more than 1 request? Then why are Azure and Cirrus added to the list of jobs?

**Comment by MoonlightSentinel** [comment]
> So upstream fails because we are sending more than 1 request?

CodeCov apparently thinks that all builds were submitted and fails when it receives a delayed report. Not sure why it suddenly started failing...

>Then why are Azure and Cirrus added to the list of jobs?

To sync the list of CI providers with the actual pipelines

**Comment by RazvanN7** [comment]
So the issue was that codecov was expecting only one report from circleCI whereas we were sending 3. The first one was taken into account and when the second one came the issued an error?

**Comment by MoonlightSentinel** [comment]
The CI currently creates five coverage reports (1 CircleCI + 1 Azure + 3 Cirrus).
But the upload failed for CircleCI, even though it was already listed as an expected CI.

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
