### PR TITLE
fix Issue 20149 - [DIP1000] Local data escapes inout method if not de…

### PR DESCRIPTION
**Pull request by WalterBright**
…corated with return

This is a reboot of https://github.com/dlang/dmd/pull/10390

@JinShil had the right diagnosis, but the fix was in the wrong place. The type shouldn't be altered after it finishes its semantic() routine, so the fix got moved there.

### CODE REVIEW

**Comment by WalterBright** [comment]
All the errors are:
```
std/net/curl.d(2491): Error: scope variable `__dop5353` assigned to non-scope parameter `this` calling std.regex.Captures!(const(char)[]).Captures.opIndex!().opIndex
```
The code in std.regex is:
```
    inout(R) opIndex()(size_t i) inout
    {
        assert(_f + i < _b,text("requested submatch number ", i," is out of range"));
        return getMatch(_f + i);
    }
```

**Comment by WalterBright** [comment]
I'm beginning to think that inferring `return` is a mistake, as `inout` is transitive, and `return` is not.

**Comment by dkorpel** [comment]
> I'm beginning to think that inferring `return` is a mistake, as `inout` is transitive, and `return` is not.

Exactly: https://issues.dlang.org/show_bug.cgi?id=22027

**Comment by WalterBright** [comment]
I see your PR https://github.com/dlang/dmd/pull/12689. It looks good, but I would break the legacy code only if `-preview=dip1000` and `@safe` are in play. If you're willing to proceed with that, I can close this PR.

**Comment by dkorpel** [comment]
> I see your PR #12689. It looks good, but I would break the legacy code only if `-preview=dip1000` and `@safe` are in play. 

Maybe, dip25 is now the default but only in deprecation form, so in theory this should not produce new errors in legacy code, only new deprecations. In any case, that's worth considering after the more immediate problem that blocks both your and my PR: druntime and Phobos still need to compile with `-preview=dip1000`, and they rely on the `inout` bug.

I've started fixing the problematic `inout` cases (https://github.com/dlang/phobos/pull/8319, https://github.com/dlang/druntime/pull/3629, https://github.com/dlang/phobos/pull/8320), but there's still more to do (e.g. https://github.com/dlang/phobos/pull/8383), and I recall a buildkite project using dip1000 being blocked by the inability to express `ref-return scope` member functions (https://issues.dlang.org/show_bug.cgi?id=22541#c7).

**Comment by WalterBright** [comment]
The ref-return-scope problem has been fixed in the compiler.

**Comment by dkorpel** [comment]
> The ref-return-scope problem has been fixed in the compiler.

Only partially, `return scope` will not become `return ref + scope` anymore, but `scope return` can still become `ref + return scope`, see my issue comment: https://issues.dlang.org/show_bug.cgi?id=22541#c7

```D
struct S 
{
    int i;
    int* ptr;
    
    int* wannabeReturnRef() scope return
    {
        return &i;
    }
}
```
```
Error: returning `&this.i` escapes a reference to parameter `this`
       perhaps remove `scope` parameter annotation so `return` applies to `ref`
```

**Comment by WalterBright** [comment]
@dkorpel https://github.com/dlang/dmd/pull/13677

**Comment by WalterBright** [comment]
@dkorpel that's taken care of now.

**Comment by WalterBright** [comment]
Curiously, the FreeBSD tests fail with:
```
./generated/freebsd/debug/32/test19433 --DRT-dont-eat-me
/usr/home/braddr/sandbox/at-client/pull-5125964-FreeBSD_32/dmd/generated/freebsd/release/32/dmd -m32 -fPIC -w -I../../src -I../../import -Isrc -defaultlib= -debuglib= -preview=dip1000 -L-lpthread -L-lm -L/usr/home/braddr/sandbox/at-client/pull-5125964-FreeBSD_32/druntime/generated/freebsd/debug/32/libdruntime.so -g -debug -ofgenerated/freebsd/debug/32/dynamiccast.so src/dynamiccast.d -version=DLL -fPIC -shared 
../../src/core/stdcpp/string.d(171): Error: scope variable `s` assigned to non-scope parameter `this` calling core.stdcpp.string.basic_string!(char, char_traits!char, allocator!char).basic_string.as_array
```
but the `as_array` is in a `version (Cpp_Runtime_Microsoft)` section.

**Comment by WalterBright** [comment]
This is a mystery. Why would it only happen on FreeBSD? And the `this` is `scope`.

**Comment by WalterBright** [comment]
Let's try disabling this change and see if the failure persists.

**Comment by WalterBright** [comment]
Ah, I was finally able to duplicate the FreeBSD problem. Thanks to the new `-os=freebsd` switch! Yay!

**Comment by WalterBright** [comment]
With `-os=freebsd` and `pragma(msg, "xyzzy")` I was able to quickly figure out which branch in the tangle of `version` declarations was being compiled, and discovered I had been looking at the wrong one.

**Comment by WalterBright** [comment]
@RazvanN7

**Review by dkorpel — DISMISSED** [review]
The test case from the bugzilla issue should be added to the test suite

**Comment by WalterBright** [comment]
I added a minimal test case that tests the problem. Nothing further is needed.

**Comment by WalterBright** [comment]
A good test suite contains tests that are rifle-targeted to what they are testing. The reasons are simple:

1. if the test suite breaks, the example is *already minimized*. This makes for much faster identification of where in the compiler the breakage occurred.
2. having a test suite of a random assortment of filler code does nothing to improve reliability of the compiler
3. having a test suite of a bunch of filler code makes the test suite slower
4. the purpose is to debug the compiler, *not* Phobos. This is because you can't bootstrap a compiler if you can't debug it without a fully functioning Phobos.

Now, if you have something *specific* that is not covered by the tests in this PR, we can talk about it. The example in the bugzilla is way, way too much filler code. The example code also includes `std.stdio`, which adds massive (hidden) bloat. The compiler test suite is supposed to run *without* need of Phobos.

**Comment by ibuclaw** [comment]
> the test case from bugzilla is unsuitable for the test suite

Can you run dustmite on the code then? Shouldn't take any longer than half an hour to get the minimum test you're looking for.

**Comment by WalterBright** [comment]
@ibuclaw here's the minimum test:

https://github.com/dlang/dmd/pull/13658/files#diff-1a3be1f0ca528aa4ab2a3fcf2a3f9a9448ef8ee2604ef25701822e8fd38a8994

**Review by dkorpel — CHANGES_REQUESTED** [review]
I'll be more specific. Add [your reduced test case from the bugzilla issue](https://issues.dlang.org/show_bug.cgi?id=20149#c25) to the test suite.
```D
  @safe:

  struct S {
  //inout(char)* slice() inout return /* gives correct error */
    inout(char)* slice() inout          /* no error */
    {
        return &buf;
    }

    char buf;
  }

  char* fun() {
    S sb;
    return sb.slice();
  }
```

I agree we should get rid of the filler, but it's important to verify that the changes in code you make actually result in the desired behavior. The desired behavior is that the compiler gives an error when you escape a stack pointer from an `inout` method in `@safe` code. Your minimal test case doesn't verify that, hence you could revert the code changes and the new test suite will still pass. It's important that future regressions to this issue are prevented by tests.

**Comment by WalterBright** [comment]
@dkorpel there's simply no need for it. You'll note that several other tests in the test suite changed, too.

**Comment by dkorpel** [comment]
> You'll note that several other tests in the test suite changed, too.

Ah, you're referring to `fail_compilation\fail17927.d:15`, which I didn't see because it's not part of the diff. 
https://github.com/dlang/dmd/pull/13658/files#diff-d016b03d1e635444aacd3760c45280b9769abaf5c7ba141908f7d1e4b54be325R15
The comment "no error because `ref inout` implies `return`" is outdated now, but that's a minor thing. Sorry to be a nuisance, I'm only being critical because I care about dmd's quality.

Since this is an incremental improvement, are you going to file new bugzilla issues for the remaining problems or do you want me to do it?

**Review by dkorpel — APPROVED** [review]

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
