### PR TITLE
Fix Issues 22149 & 22150 - TypeInfo names aren't unique, leading to botched equality semantics

### PR DESCRIPTION
**Pull request by kinke**
Making the `TypeInfo_Struct` names truly unique and more compact at the same time. Requires https://github.com/dlang/druntime/pull/3527.

### CODE REVIEW

**Comment by kinke** [comment]
This is a follow-up on https://github.com/dlang/dmd/pull/11450, tackling `TypeInfo_Struct` only for now (no `TypeInfo_Class`), as only this requires synchronization with druntime. Making TypeInfo names of classes and interfaces truly unique is a trivial 2-lines change: https://github.com/dlang/dmd/pull/11450/commits/4a484c0b4081f1e7d1e9545aa26caf9d8244d194

**Comment by PetarKirov** [comment]
@kinke I'm lacking the context of #11450. What problem prompted the work that you did there? Can you also provide some before and after numbers for this PR?

**Comment by kinke** [comment]
`TypeInfo_Class` handled too now; more context in general in the druntime PR. The Cirrus CI hack (to test the correct dmd and druntime branches) obviously needs to be removed before merging.

**Review by WalterBright — APPROVED** [review]

**Comment by kinke** [comment]
Thx for the review, Walter. I found a proper solution for Cirrus CI (details [here](https://github.com/dlang/druntime/pull/3527#issuecomment-887918082)), working analogously to Azure Pipelines, and pushed one more according commit - the previous hack doesn't need to be removed anymore.

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
Waiting for the druntime PR to get in and then I will merge this one also.

**Pull request merged**
