### PR TITLE
first method-call support

### PR DESCRIPTION
**Pull request by UplinkCoder**
Method calls are now supported.
They mostly reuse the infrastructure of normal pointer support.

fails travis because of 
`fail_compilation/ctfe10995.d`
Basically I because cannot preserve the VoidValue attribute through a function call.
Doing this will require inter-procedural dataflow-ananlysis.
So it'll be a while until this is ready.

### CODE REVIEW

**Comment by MartinNowak** [comment]
Also seems to fail to compile druntime atm.

**Comment by UplinkCoder** [comment]
Ah yes Thanks @MartinNowak I did not notice that.
I must have lost some code while stashing and stash apply

**Comment by UplinkCoder** [comment]
@MartinNowak Thanks for telling me, I did not notice :)
this must have been introduced by the heapRef stuff.
I'll look into it

**Comment by UplinkCoder** [comment]
@MartinNowak druntime build is fixed

**Pull request merged**
