### PR TITLE
Remove some (over)due deprecation -> errors

### PR DESCRIPTION
**Pull request by thewilsonator**
(presumable still need to update tests and remove `-de`?) and add a changelog entry.

### CODE REVIEW

**Comment by thewilsonator** [comment]
```
>>> TARGET FAILED: `unit` tests
```

that's `cxxfrontend.cc` right?

**Review by RazvanN7 — APPROVED** [review]

**Comment by RazvanN7** [comment]
@thewilsonator no,  there is a folder `compiler/test/unit` where there are various standalone tests for the compiler library and other things.

**Comment by thewilsonator** [comment]
Well that is a particularly unhelpful error message then. It doesn't even say which test failed. I'll come back to this tomorrow.

Also cc @jacob-carlborg  `dstep` has some deprecations (now errors) triggered by this.

**Comment by jacob-carlborg** [comment]
I thought the policy was that there shouldn't be any more breaking changes. Those would need to go in an edition.

**Comment by RazvanN7** [comment]
@jacob-carlborg I'm not sure how that applies to deprecations that should have been errors for some time now.

**Comment by thewilsonator** [comment]
I am going to partition this into separate PRs for the different deprecations.

**Comment by thewilsonator** [comment]
Split into different PRs

**Pull request closed without merging**
