### PR TITLE
Fix Issue 23332 - core.sync.condition notify methods should be @nogc

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by RazvanN7** [comment]
Looks like this is breaking the interface Condition. Classes that derive from `Condition` must have @nogc methods, which seems to be an arbitrary limitation. One thing we could do is maybe create `NogcCondition`, however, this does not scale well.

@atilaneves any other ideas?

**Comment by gdamore** [comment]
I cannot think of any useful way to subclass this that works without just using the class.

We could just add a new _nothrow version of the methods.

**Comment by schveiguy** [comment]
Regardless of the breaking change, you should change to throwing static errors instead of using abort. Using abort is really harsh for something like this.

**Comment by schveiguy** [comment]
And regarding the breaking change, just add new methods, that won't break existing code.

**Comment by RazvanN7** [comment]
> Regardless of the breaking change, you should change to throwing static errors instead of using abort. Using abort is really harsh for something like this.

What do you mean by harsh? Do you think someone could try to catch that error?

> And regarding the breaking change, just add new methods, that won't break existing code.

But that's not going to scale. What if we want to make them @safe at some point? We create another overload? If we create another overload, should we deprecate the old one?

**Comment by schveiguy** [comment]
> What do you mean by harsh?

abort does not print a stack trace.

> What if we want to make them `@safe` at some point?

Why not now? I can't see what's unsafe about it.

**Comment by atilaneves** [comment]
Yeah, I don't think there's a good reason to not add `@safe`.

**Comment by RazvanN7** [comment]
@atilaneves @schveiguy I have replaced the usage of  `abort` with throwing a static error. I have marked constructors and destructors as `@nogc` as those cannot be overriden. I did not add nothrow/@safe overloads for wait and notify because these functions forward to a templated version for which the attributes are inferred. I think that users can simply use the template.

**Comment by RazvanN7** [comment]
cc @dkorpel

**Review by dkorpel — APPROVED** [review]
Why not use `assert(0)`?

**Comment by RazvanN7** [comment]
> Why not use assert(0)?

Because `assert(0)` gets lowered to a HLT instruction (you lose the informative message) and I want the failure to be informative.

**Pull request merged**
