### PR TITLE
Split C++ runnable tests into a separate directory ...

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
... s.t. they can be executed if an appropriate compiler is present and omitted if not.

CC @Geod24

### CODE REVIEW

**Comment by Geod24** [comment]
Thanks for taking care of this ! I guess this needs a rebase on master now ?

**Comment by thewilsonator** [comment]
Why? Its green.

**Comment by Geod24** [comment]
> Why? Its green.

Probably because it's a draft PR ? For one, if you look at the diff, at least 2 lines in the `test/Makefile` conflict with #10878

**Comment by ibuclaw** [comment]
Out of curiosity, what's preventing us from having a test directory named cxx and adding TEST_MODE as a testsuite directive (which can be set to run, compile or fail), allowing all c++ tests to reside in the same directory.

**Comment by Geod24** [comment]
Nothing, but why would we do that ? `compilable` are not platform dependent, and so far we don't have a `fail_compilable` test that is platform dependent. Only runnable has been a problem so far.

**Comment by ibuclaw** [comment]
So these don't need to be in a separate directory to fix the issue then?

**Comment by Geod24** [comment]
As far as I can see, no. I originally thought about moving all C++ tests in their own directory as you suggested, but I think it would be a bad precedent: then what about a `deprecation` directory ? An `alias this` directory ? Etc...

`cxx_runnable` are just "special" runnable directory. If we end up adding more tests (e.g. tests for ABI compatibility), we could consider segmenting things differently, e.g. having subfolders in `runnable`, or grouping them by common features (e.g. tests that target exclusively GCC vs tests that target clang).

What do you think ?

**Comment by ibuclaw** [comment]
I think having a target test directory sounds reasonable, e.g: target/freebsd would just be the logical opposite for having instead DISABLED: linux32 linux64 osx win32 win64 etc...

C and C++ are in a way a kind of target that we support.

**Comment by MoonlightSentinel** [comment]
Not opposed to adding more directories but maybe we should also consider a tagging system as well. That could be a more flexible way to filter the existing tests depending on the environment.
E.g:
```
// TAGS: FOO;BAR
<the test>
```
```
run.d --include-only=FOO
run.d --exclude-all=BAR
```

ATM CI scripts usually "disable" tests by deleting the files before running the test suite...

**Comment by ibuclaw** [comment]
> ATM CI scripts usually "disable" tests by deleting the files before running the test suite...

Really? I assumed that DISABLED was already some sort of tagging/filtering.

**Comment by Geod24** [comment]
Was surprised too:
https://github.com/dlang/dmd/pull/10934/files#diff-f72b89e1df48055b95440fb7d9d8ab90L69

**Review by Geod24 — APPROVED** [review]
LGTM. Can you rebase ? Also the fix to the windows CI could be its own commit if you'd like.

**Comment by ibuclaw** [comment]
By way of comparison, the dejagnu testsuite has a `target` selector. Such a filter argument could be a specific target, or a capability (implemented by a function). eg:
```
{ target *-*-linux } # any Linux target
{ target s390*-*-* } # any SystemZ target
{ target hw } # target is native (not cross-compiled)
{ target d_runtime } # druntime/phobos libraries were built
{ target libcurl_available } # curl library installed
{ target linux_pre_2639 } # Linux kernel is older than 2.6.39
```

**Comment by MoonlightSentinel** [comment]
Rebased and split into two commits (add `runnable_cxx`, move existing tests + required changes for Azure).

> Really? I assumed that DISABLED was already some sort of tagging/filtering.

Azure probably had the same problem that @Geod24 is facing now - they could be executed on Windows but missed an appropriate compiler.

**Pull request merged**
