### PR TITLE
End deprecation period for the 'delete' keyword

### PR DESCRIPTION
**Pull request by ibuclaw**
This keyword has been deprecated since 2.079, time to make it an error.

A `@@@DEPRECATED@@@` notice has been put up in the parse to remind ourselves in the future to remove it entirely from the language in 10 releases time (or thereabouts).

### CODE REVIEW

**Comment by ibuclaw** [comment]
> I would be supporting this if the decade bug regarding ~this() for classes has been fix already, but it hasn't so I am not sure that we should removing it without fixing it.

Issue link?

**Comment by 12345swordy** [comment]
> > I would be supporting this if the decade bug regarding ~this() for classes has been fix already, but it hasn't so I am not sure that we should removing it without fixing it.
> 
> Issue link?

https://issues.dlang.org/show_bug.cgi?id=15246

**Comment by ibuclaw** [comment]
> https://issues.dlang.org/show_bug.cgi?id=15246

That is questionable, has nothing to do with `delete`, and is fixed by use of explicit `destroy()` or `__delete()`.  Any surprising behavior that occurs from finalizing that is done implicitly from the GC during rt_term() is a library problem.

**Comment by ibuclaw** [comment]
Blocked by dlang/druntime#3746

**Comment by 12345swordy** [comment]
> > https://issues.dlang.org/show_bug.cgi?id=15246
> 
> That is questionable, has nothing to do with `delete`, and is fixed by use of explicit `destroy()` or `__delete()`. Any surprising behavior that occurs from finalizing that is done implicitly from the GC during rt_term() is a library problem.
What do you mean by  "Explicit destory()" here? You can't call destroy in attribute context for classes here. That is a problem here caused by the bug that I have link for you. Libraries can't fix that without fixing the bug first.

**Comment by ibuclaw** [comment]
> What do you mean by "Explicit destory()" here? You can't call destroy in attribute context for classes here. That is a problem here caused by the bug that I have link for you. Libraries can't fix that without fixing the bug first.

You can't call delete nor destroy in a `@safe` context, and destructors are not chained (unlike contracts), but called from the library.  It's a library issue.  And again, `delete` is nowhere to be seen because it has nothing to do with it.

**Comment by 12345swordy** [comment]
> > What do you mean by "Explicit destory()" here? You can't call destroy in attribute context for classes here. That is a problem here caused by the bug that I have link for you. Libraries can't fix that without fixing the bug first.
> 
> You can't call delete nor destroy in a `@safe`/`pure` context, and destructors are not chained (unlike contracts), but called from the library. It's a library issue. And again, `delete` is nowhere to be seen in 15246 and the removal of the keyword has nothing to do with it.

An  issue which is caused by the language issue described in the bug report, like I said before. I have tried to provide solutions to the library in the discord sever, only to met with negative responses. Please if you think it fixable, then fix it. It driving me insane ever since I used D.

**Comment by ibuclaw** [comment]
No longer blocked, and green. :+1:

**Review by thewilsonator — APPROVED** [review]

**Comment by BrainKicker** [comment]
What is the problem to just change 'delete' keyword to a library call at the compile time?
Removing 'delete' keyword breaks the codestyle.

**Comment by ibuclaw** [comment]
> What is the problem to just change 'delete' keyword to a library call at the compile time? Removing 'delete' keyword breaks the codestyle.

What do you think `delete` does? (Hint, it doesn't do that).

Having a `delete` keyword doesn't fit the paradigm where allocations are new'd but never freed (until perhaps some indeterminate time in the future when the GC pool that was referenced by the `new` pointer/reference is completely empty). There are allocators to manage determinism, and the delete keyword will be dropped in 2.109 anyway, so you can just turn it into a property function (`obj.delete`) after that release.

**Comment by BrainKicker** [comment]
What if I want to rewrite a program from C++ to D without using GC? So I want to manually free up memory.

Deleting the keyword 'delete' forces me to write ugly constructions like

__delete(...);

or

destroy(...);
GC.free(...);

(Actually, I'm new to D and may not understand something. As I understand, these two are alternatives to the 'delete' keyword.)

**Comment by ibuclaw** [comment]
> What if I want to rewrite a program from C++ to D without using GC? So I want to manually free up memory.

Then you wouldn't be using `new` in the first place. 

> Deleting the keyword 'delete' forces me to write ugly constructions like
> 
> __delete(...);

Just a wrap around `destroy()` + `GC.free`.

> GC.free(...);
> 

Which doesn't actually free up memory, it marks the pointer as available for re-use in the GC.

> (Actually, I'm new to D and may not understand something. As I understand, these two are alternatives to the 'delete' keyword.)

If you're allocating on the GC, just let the pointer go out of scope, and when the GC next runs (after a few more `new` allocations) it'll detect that there are no references to the pointer in scope, and run clean-ups all by itself.

**Comment by BrainKicker** [comment]
> Then you wouldn't be using `new` in the first place.

Why? It seems to work well with GC disabled. It just doesn't trigger garbage collection, but allocates memory just fine.  
What should I use instead?

> Just a wrap around `destroy()` + `GC.free`.

But `destroy` makes pointer null, so I can't use it as an argument for `GC.free` anymore. Isn't that right?

> Which doesn't actually free up memory, it marks the pointer as available for re-use in the GC.

So what's the difference? Isn't it calling destructor?

Sorry for so many questions.

It seems like not using GC in D is inconvenient. It doesn't seem right.  
I'm not against GC, but I think both ways of dynamic memory management should be convenient to use.

**Comment by ibuclaw** [comment]
> > Then you wouldn't be using `new` in the first place.
> 
> Why? It seems to work well with GC disabled. It just doesn't trigger garbage collection, but allocates memory just fine. What should I use instead?

It works even better with the GC enabled, because then it'll just pick-up and reuse the allocated memory that's gone out of scope.

C++ memory management has determinism when dealing with heap allocations (the memory need not be freed in the background, for instance the `malloc` implementation could still choose to have per-thread memory arena's, but that sits outside of language-specific semantics).  When porting, to D, if you want to keep that, then you should be [using allocators](https://dlang.org/phobos/std_experimental_allocator.html) instead of `new` (yes, they will be moved out of experimental soon).

 
> > Just a wrap around `destroy()` + `GC.free`.
> 
> But `destroy` makes pointer null, so I can't use it as an argument for `GC.free` anymore. Isn't that right?
> 

For plain pointers yes, classes, no.  Which is why `__delete` exists, to give consistent behaviour for all kinds of pointer/array types.

> > Which doesn't actually free up memory, it marks the pointer as available for re-use in the GC.
> 
> So what's the difference? Isn't it calling destructor?
> 

It does not, at least not immediately. Destructors/finalizers will eventually get ran, but not until the program gets shut down or the freed memory is reused for a new allocation.

> Sorry for so many questions.
> 
> It seems like not using GC in D is inconvenient. It doesn't seem right. I'm not against GC, but I think both ways of dynamic memory management should be convenient to use.

Dynamic memory management of the kind found in the many, many C++ libraries that reinvent the wheel on this, can just be swapped out with [std allocators](https://dlang.org/phobos/std_experimental_allocator.html).

D's style is just to keep on new'ing and never think about freeing every again, because the GC will take care of the rest.  That way you half the number of problems you need to think about, giving more time to focus on the application logic itself, without memory management getting in the way, its tentacles consuming parameter slots in all your interfaces.

**Comment by BrainKicker** [comment]
OK, I'll look into it.

It's just that so far I don't understand why not leave the usual constructions for allocating and deleting memory, just making the garbage collection optional.

**Comment by ibuclaw** [comment]
> OK, I'll look into it.
> 
> It's just that so far I don't understand why not leave the usual constructions for allocating and deleting memory, just making the garbage collection optional.

That you are referring to it as deleting memory would be the obvious reason to me.

The [language forum](https://forum.dlang.org/group/learn) [or discord](https://discord.gg/bMZk9Q4) would be the best platform to ask though, so you don't just hear my opinionated thoughts on the matter.

**Pull request merged**
