### PR TITLE
Add support for static if, debug, and version blocks within inline asm

### PR DESCRIPTION
**Pull request by Orvid**
This is a fairly simply change to the parser to allow `static if`, `debug`, and `version` blocks within inline asm statements. Allowing these within inline asm statements allows for significantly cleaner templated inline asm. Feel free to discuss whether this is actually a good thing or not. A test suite is included.

### CODE REVIEW

**Comment by andralex** [comment]
@yebblies so are you opposed to this enhancement? @Orvid @WalterBright @yebblies let's move toward a conclusion. Thanks!

**Comment by yebblies** [comment]
Yes, I'm against this.  I don't think it's worth the complexity, and seems to encourage writing monolithic spaghetti-asm blocks.  Inline asm is a low level tool.

**Comment by ibuclaw** [comment]
Looking at the tests - I must agree with @yebblies - it looks almost horrific.

**Comment by WalterBright** [comment]
Yes, I'm going to agree with the naysayers. It doesn't enable things that cannot already be done, and arguably its use makes for unattractive code.

**Comment by Orvid** [comment]
I'll eventually get around to putting together a good use-case to argue for this, but, for now at least, I don't have the time to do so. It's primary intended purpose is to reduce the visual disconnect that results when doing a set of ASM instructions where only a small part of it is dependent on a compile-time option. It's intended to allow putting more sanity into locations where inline-asm is templated to allow easier maintenance of accelerated code bases. [this](https://github.com/D-Programming-Language/dmd/pull/3469/files#diff-e5d8b1514aec296088b1d3fd5a50ffb9R80) from the unittests is the best example of this in the PR, although I do probably have a better example lying around somewhere.

**Comment by ibuclaw** [comment]
@Orvid nothing that can't be done with template mixins. :)

**Pull request closed without merging**
