### PR TITLE
Treat `import("file")` as hex string

### PR DESCRIPTION
**Pull request by dkorpel**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by dkorpel** [comment]
I need to update the tests to account for Windows line endings

**Comment by Herringway** [comment]
@dkorpel I hope you are aware that this changes the endianness of all >8-bit integer types for string imports, with a file such as `80 00` now being interpreted as `[-32768]` instead of `[128]` when casted to `short[]` on little endian systems. This is a huge breaking change...

**Comment by dkorpel** [comment]
Thanks for bringing that up. I think I was aware, but in my experience:
- Import expressions aren't a very commonly used feautre to begin with
- When they're used, they usually import a string (like the ddoc default theme in dmd) or binary file types (like a png), not a plain binary integer array
- They're also often used to initialize global variables, where casting an import expression to a `short[]` was formerly not supported
- When casting a string/ubyte[] variable initialized by an import expression to a short[] at runtime, the result is the same
- When casting to wstring first (`cast(short[]) cast(wstring) import(__FILE__)`) the result is the same.

Only when you directly `cast(short[])` an `import(__FILE__)` in a runtime expression would you notice the difference. so I thought this wouldn't be disruptive. When I discussed [Issue 24363](https://issues.dlang.org/show_bug.cgi?id=24363) with Walter, he suggested straight up changing the behavior, so I figured we weren't being that strict with no-breakage in this area.

**Comment by Herringway** [comment]
> Only when you directly `cast(short[])` an `import(__FILE__)` in a runtime expression would you notice the difference. so I thought this wouldn't be disruptive. When I discussed [Issue 24363](https://issues.dlang.org/show_bug.cgi?id=24363) with Walter, he suggested straight up changing the behavior, so I figured we weren't being that strict with no-breakage in this area.

Unfortunately, I was doing exactly that in some 16-bit signed PCM tests. I only noticed yesterday when I enabled (and subsequently disabled) automated testing with dmd-beta.

**Comment by dkorpel** [comment]
Sorry for that, do you have a suggestion for a corrective action?

**Comment by Herringway** [comment]
> Sorry for that, do you have a suggestion for a corrective action?

That's a good question... This same problem would come up when using an older compiler on a big endian machine, but those are pretty rare. It would have been somewhat easier with some sort of warning or transition period, I suppose.

**Comment by dkorpel** [comment]
@Herringway So what I can do is give the hexstring a 'c' postfix, to force its element size to be 1. That would keep your run-time target-endian dependent `cast(short[])` the same as before, but disallow converting `import()` to `wstring` or `short[]` at compile time.

Or just make a separate category of StringExp for import expressions entirely. That's a bit more complexity, bit it can allow ubyte[] and wstring conversion but not short[] and int[].

Either way, I'll try to revert the breakage before 2.110 releases.

**Pull request merged**
