### PR TITLE
fix bugzilla Issue 24819 - Optimizer changes result of float calculat…

### PR DESCRIPTION
**Pull request by WalterBright**
…ions on 32-bit

Thanks to @dkorpel for zeroing in on the problem.

### CODE REVIEW

**Review by thewilsonator — COMMENTED** [review]
Shouldn't the test case have `-O` as an argument?

Also this is a "major" issue, did you want to target stable for it?

**Comment by thewilsonator** [comment]
> I thought it was good to test every combination.

Isn't that what permute args is for?

> so I'll let him make that call.

Fair

**Review by RazvanN7 — APPROVED** [review]

**Comment by dkorpel** [comment]
> Isn't that what permute args is for?

The default permute set is (-inline -release -g -O), so -O doesn't need to be added manually.

**Review by dkorpel — APPROVED** [review]
Thanks! Did you find out why the sqrt instruction disappears with the `x ^ signbit` optimization? I hope there's no other latent bugs with integer optimizations on floating point math.

**Comment by thewilsonator** [comment]
> The default permute set is (-inline -release -g -O), so -O doesn't need to be added manually.

Yes but there is no `//PERMUTE_ARGS` directive(or however it is spelled) in the test file.

**Comment by veelo** [comment]
Many thanks for working on this, guys! I know we are probably the last bunch that need x87 to work correctly.

**Comment by dkorpel** [comment]
> Yes but there is no `//PERMUTE_ARGS` directive(or however it is spelled) in the test file.

With default I mean that even without any `PERMUTE_ARGS`, it's testing both -O and unoptimized amongst other things.

**Comment by WalterBright** [comment]
> did you find out ...

No, I just went with the elem tree was malformed.

**Comment by WalterBright** [comment]
That optimization was a relic of the old no-x87 CPUs.

**Comment by veelo** [comment]
This fix is important to us. Does it help if I make a PR to the stable branch with a cherry pick of this commit, or does that only add to your workload, @ibuclaw? Is master going to be merged into stable before the next beta release?

It would be good to have an approximate ETA of the next release. If that is months from now, we would have to decide between two unpopular options: 1. to use the nightly build, putting us on master, or 2. build our own compiler, possibly missing out on PGO. In both cases we mess up our system for reproducible builds (which relies on official version tags and the release archive).

**Comment by thewilsonator** [comment]
> Is master going to be merged into stable before the next beta release?

No. If you want them in the next release, please cherrypick this and https://github.com/dlang/dmd/pull/16780 onto `stable`
I don't think exact duplicate commits cause merge conflicts, but if you want to, you could always rebase master on top of stable after you are done.

**Pull request merged**
