### PR TITLE
refactor: add parseCommandLine()

### PR DESCRIPTION
**Pull request by WalterBright**
This just pulls the code that loops over `arguments[]` into `parseCommandLine()`. You can't really tell that from the github diff, as github gets thoroughly confused.

This makes the inputs and outputs for parsing the command line clear, and removes the global variable references from it. All instances of `global.params` in `parseCommandLine()` are replaced with just `params`. It's much better encapsulated.

More can be done, but this is a good first approximation.

### CODE REVIEW

**Comment by JinShil** [comment]
Since you're going through the work of refactoring this entire file, is it possible to start using D's string facilities instead of C's `char *` , `strcmp`, and friends?

**Comment by WalterBright** [comment]
Yes, but my main concern is better encapsulation, rather than a tangle of dependencies.

**Comment by JinShil** [comment]
If you main concern is a dependency on Phobos, I understand.  But what about just druntime where `string` is defined.  You can always add a string utilities module to DMD to avoid the dependency on Phobos.

**Comment by WalterBright** [comment]
By encapsulation I mean having clear inputs and outputs. Dependency on Phobos is a separate issue.

**Review by MartinNowak — APPROVED** [review]
LGTM

**Pull request merged**
