### PR TITLE
Fix 23867 and 23869

### PR DESCRIPTION
**Pull request by bachmeil**
https://issues.dlang.org/show_bug.cgi?id=23867

https://issues.dlang.org/show_bug.cgi?id=23869

### CODE REVIEW

**Comment by maxhaton** [comment]
Tests + more detailed commit message please

**Comment by bachmeil** [comment]
> Tests + more detailed commit message please

I'm not sure what more could be added to the commit message. The entirety of the commit is adding 

```
#define __builtin_isnan(x) isnan(x)
#define __builtin_isfinite(x) finite(x)
```

in order to avoid unsupported GNU extensions. Not sure how to test something like this either. The gcc preprocessor inserts code that DMD can't compile. This prevents that from happening. This PR doesn't affect DMD.

**Comment by maxhaton** [comment]
There are quite a lot of .c tests in test/

**Comment by bachmeil** [comment]
This is a simple fix. Feel free to close it but I'm not spending my time on something like that. Tests would be pointless.

**Comment by thewilsonator** [comment]
> I'm not sure what more could be added to the commit message.

Please [title the commit messages "Fix issue XXX: ..."](https://github.com/dlang/dlang-bot#automated-references) so the bot picks them up and they end up in the generated changelog.

Apart from that, this looks fine to me.

**Review by PetarKirov — APPROVED** [review]
LGTM. I did a manual rebase to adjust the commit message.

**Pull request merged**
