### PR TITLE
fix Issue 12822 - Delegate .ptr assignment considered @safe

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by ZombineDev** [comment]
What about `.funcptr`? Is modifying it considered `@safe`? If not, can you add it to the test?

**Comment by WalterBright** [comment]
Does `.funcptr` now, too.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by ZombineDev** [comment]
@WalterBright thanks

**Comment by denis-sh** [comment]
Line numbers in comment in `test12822.d` are incorrect. As there is no `TEST_OUTPUT` token compiler output isn't tested for this issue.
Creating pull #5865...

**Pull request merged**
