### PR TITLE
Fix Issue 20151 - particular directory layout causes DMD to crash

### PR DESCRIPTION
**Pull request by BorisCarvajal**
Similar to issue 17991 but the foreach runs more than 1 time.
Moved the workaround to where it should be;

### CODE REVIEW

**Comment by thewilsonator** [comment]
Tests?

**Comment by BorisCarvajal** [comment]
I forgot to say the code is covered by the test case that comes from issue 17991.

**Comment by Geod24** [comment]
> I forgot to say the code is covered by the test case that comes from issue 17991.

No it's not, otherwise the testsuite wouldn't have been passing.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
We have some network issues going on you'll need to force push to restart the doc tester at some point.

**Pull request merged**
