### PR TITLE
Give D2-style operator overload priority over D1-style, reinstate the latter's deprecation

### PR DESCRIPTION
**Pull request by Geod24**
It was merged accidentally, see https://github.com/dlang/dmd/pull/10716#issuecomment-574562709

### CODE REVIEW

**Comment by Geod24** [comment]
@don-clugston-sociomantic : Can you review ? Hope this will suit you. The only downside I can see is that the following is not supported:
```D
class DontDoThat {
   int opAdd(int) {}
   int opBinary(string op)(int) if (op == "-") { return 0; }
}

void main ()
{
     scope o = new DontDoThat();
    // This will now error out because the compiler does not consider `opAdd`,
    // as it sees an `opBinary`... I don't think that's a big deal but you tell us.
     o + 42;
}
```

**Comment by don-clugston-sociomantic** [comment]
That looks great! From there, we can mark the D1 names as deprecated in our own code, so that we can flush out existing uses. Nice solution.

**Comment by don-clugston-sociomantic** [comment]
> The only downside I can see is that the following is not supported:
> 
> ```d
> class DontDoThat {
>    int opAdd(int) {}
>    int opBinary(string op)(int) if (op == "-") { return 0; }
> }
> 
> void main ()
> {
>      scope o = new DontDoThat();
>     // This will now error out because the compiler does not consider `opAdd`,
>     // as it sees an `opBinary`... I don't think that's a big deal but you tell us.
>      o + 42;
> }
> ```

I think that's good behaviour actually. Any code affected by that deserves to be broken.

**Review by don-clugston-sociomantic — APPROVED** [review]
LGTM. This is a good solution.

**Comment by schveiguy** [comment]
Nice! Note that I found even an alias works, and should be exactly equivalent to the original (no inlining necessary):

```D
class C
{
    int *opIn_r(int x) { return null; }
    alias opBinaryRight(string s : "in") = opIn_r;
}
```

This should not error now, I would think (it did not error if the virtual call was not named `opIn_r`).

**Comment by don-clugston-sociomantic** [comment]
Can we get this merged into stable, please?

**Comment by Geod24** [comment]
https://github.com/dlang/dmd/pull/10760

**Pull request merged**
