### PR TITLE
Remove old support code for struct __c_long/ulong/long_double

### PR DESCRIPTION
**Pull request by ibuclaw**
Library support is long gone.  And that the compiler still special cases it (and checks in the testsuite) is surprising.  I got caught out by the cppa test failing on i686.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Also mind the D language server failure on build kite. Not sure if its related.

**Comment by Geod24** [comment]
Fails on Win32

**Comment by ibuclaw** [comment]
> Fails on Win32

Indeed, I removed too much.

**Comment by ibuclaw** [comment]
Auto-tester seems like a spurious problem.

Buildkite has been failing since this merge to master.
https://buildkite.com/dlang/dmd/builds/2583#1a9e1552-a482-46ce-991c-45aeac951fad

**Comment by thewilsonator** [comment]
Yeah there have been several cases of build machines running for hours without timing out as well. OTOH, mir algorithm passes now.

**Pull request merged**
