### PR TITLE
fix Issue 22541 - DIP1000: Resolve ambiguity of ref-return-scope para…

### PR DESCRIPTION
**Pull request by WalterBright**
…meters

This is a work in progress. I want to see what breaks :-)

### CODE REVIEW

**Comment by WalterBright** [comment]
That didn't take long: https://github.com/dlang/druntime/pull/3634

**Comment by WalterBright** [comment]
Interestingly, that's the only error compiling druntime & phobos.

**Comment by RazvanN7** [comment]
Is this still a work in progress?

**Comment by WalterBright** [comment]
It seems to be working quite well. I added a changelog file, and removed the WIP.

**Comment by dkorpel** [comment]
The new code in dsymbolsem.d is not covered by tests. Also this doesn't add explicit `return ref`, so this shouldn't close issue 22541

**Comment by RazvanN7** [comment]
ping @WalterBright

**Comment by WalterBright** [comment]
> this doesn't add explicit return ref

I know, it doesn't seem to be necessary, though.

**Comment by dkorpel** [comment]
> > this doesn't add explicit return ref
> 
> I know, it doesn't seem to be necessary, though.

What if I want to return `&this` from a `scope` struct? 
```D
struct S {
    int x;
    int* y;
    int* get() scope return {return &this.x;} // language spec says this is still `return scope`
}
```
Also:
https://issues.dlang.org/show_bug.cgi?id=22528
https://issues.dlang.org/show_bug.cgi?id=20881

**Review by dkorpel — APPROVED** [review]
From the changelog it seems you want to follow my alternative proposal (https://issues.dlang.org/show_bug.cgi?id=22541#c2)

I think this is a step in the right direction, though I don't think it fixes the issue entirely since there are still cases where separate scope + return gets interpreted as return scope.

**Review by RazvanN7 — APPROVED** [review]

**Comment by dkorpel** [comment]
The bot is not auto-merging.

**Comment by RazvanN7** [comment]
@dkorpel It's still building the documentation. Once that's done it should work.

**Comment by dkorpel** [comment]
It was green 3 days ago, and green when I posted that, but of course right after I called the bot out it quickly turned yellow again for a moment :eyes:

**Pull request merged**
