### PR TITLE
fix Issue 22897 - importC: segfault calling forward-declared static f…

### PR DESCRIPTION
**Pull request by WalterBright**
…unction through pointer

I have not been able to duplicate the problem on Linux. So here's the test case, to ensure it works on all platforms.

### CODE REVIEW

**Comment by WalterBright** [comment]
Hmm. It seems to fail everywhere *but* on my Ubuntu Linux box.

**Comment by WalterBright** [comment]
I see now. It fails with `-fPIC` switch.

**Comment by maxhaton** [comment]
> I see now. It fails with `-fPIC` switch.

So is there an assertion missing from the backend somewhere? Bad IR?

**Comment by WalterBright** [comment]
? See the fix I added.

Took me 3 hours to find the problem. Looked in all the wrong places :-/

**Comment by maxhaton** [comment]
> ? See the fix I added.
> 
> Took me 3 hours to find the problem. Looked in all the wrong places :-/

I can see the fix, (my point is) if there was a segfault that means something slipped through the cracks.

**Review by maxhaton — APPROVED** [review]

**Pull request merged**
