### PR TITLE
fix Issue 15900 - public imports not accessible using FQN

### PR DESCRIPTION
**Pull request by MartinNowak**
- public imports in imported modules were not accessbile using their
  FQN, this was an oversight when adding the package tree masking to fix
  Bugzilla 313 (see #5426)
- fixed by recursively checking imported scopes for accessible packages
- Uses the same reduced visibility distinction (only private vs. rest) as the
  unqualified symbol search, b/c extending importedScopes to track rich
  visibility (e.g. package(a.b)) was out of scope for a regression fix.
  This should be implemented when combining the search/import w/
  the symbol visibility mechanism.
- also fixes Issue 16316 - FQN of imports in mixin template not accessible
  by searching the importedScopes for accessible packages

### CODE REVIEW

**Comment by MartinNowak** [comment]
Need to fix Travis-CI testing of stable branch (it's checking out druntime/phobos) master atm., please ignore the failures, but only this time ;).

**Comment by MartinNowak** [comment]
Finally fixed all the testing issues with stable, both for Travis-CI and the auto-tester.

**Comment by wilzbach** [comment]
> Finally fixed all the testing issues with stable, both for Travis-CI and the auto-tester.

FYI The windows machines still seem to fail :/

**Comment by WalterBright** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
> FYI The windows machines still seem to fail :/

Got fixed [here](https://github.com/dlang/dmd/pull/5967/commits/0a20f1d407281f61da5b6386fdbe762bab410200#diff-e4bd40e09a773ea58f6c688feba63465R1116), had to handle public import cycles.

**Pull request merged**
