### PR TITLE
druntime: refactor PAGESIZE to use core.memory.pageSize

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

### CODE REVIEW

**Comment by ibuclaw** [comment]
Thanks, makes sense.

I remember seeing something like this before, maybe from @geod24?

**Comment by ljmf00** [comment]
> Thanks, makes sense.
> 
> I remember seeing something like this before, maybe from @Geod24?

This was added by @jacob-carlborg a while ago.

**Comment by ljmf00** [comment]
There's also a fixed sized `PAGESIZE` on `core.lifetime`. Is it supposed?

**Review by RazvanN7 — APPROVED** [review]
Mind the failing test.

**Comment by ibuclaw** [comment]
> This was added by @jacob-carlborg a while ago.

I've found the last attempt at doing this. https://github.com/dlang/druntime/pull/3074

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
