### PR TITLE
Remove runnable test which test phobos modules

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
Those modules are already tested as part of the phobos test suite.

Removed files:

- runnable/teststdio.d   -> std.stdio
- runnable/testformat.d   -> std.(format|stdio)
- runnable/testsignals.d -> std.signals
- runnable/testsocket.d  -> std.socket
- runnable/test60.d  	-> std.algorithm

### CODE REVIEW

**Comment by ibuclaw** [comment]
Also remove tests from slowRunnableTests.

**Comment by MoonlightSentinel** [comment]
> Also remove tests from slowRunnableTests.

Done

**Review by ibuclaw — APPROVED** [review]
I don't disagree in principle, but do make sure that phobos really does cover them with its own tests. :-)

Saying that, it would be a surprise if it didn't already.

**Comment by MoonlightSentinel** [comment]
That should be the case (some tests were simply copied to phobos).

The only notable difference is that there are no tests using `writefln` with FPNs but that method simply forwards to `formattedWrite` anyway (which has sufficient tests AFAICT)

**Review by Geod24 — APPROVED** [review]
LGTM

**Pull request merged**
