### PR TITLE
fix Issue 20520 - Runtime segfault when taking typeid of a class inst…

### PR DESCRIPTION
**Pull request by WalterBright**
…anciated within an enum

Can't reproduce the error, but so I add the test case.

### CODE REVIEW

**Comment by WalterBright** [comment]
I was wrong. The bug persists.

**Comment by WalterBright** [comment]
I'm having second thoughts about this fix. It looks wrong.

**Comment by WalterBright** [comment]
Apparently there is code in the the test suite that expects this to work:
```
void test()
{
    class C { this(int i) { this.i = i; } int i; }
    enum EC : C
    {
        a = new C(42),
        b = null,
        c = new C(1),
        d = new C(33),
    }
    static assert(EC.init.i == (new C(42)).i);
    static assert(!__traits(compiles, EC.min));
    static assert(!__traits(compiles, EC.max));

    EC ec = EC.d;
    assert(ec.i == 33);
    ec = EC.b;
    assert(ec is null);
}
```
aargh

**Comment by RazvanN7** [comment]
I'm having trouble understanding what is happening in the above case. Are the instances of `C(42)`, `C(1)`, `C(33)` created at runtime or are they created at compile time and are being saved somewhere in the .rodata segment?

**Comment by ibuclaw** [comment]
This should target stable.

**Comment by WalterBright** [comment]
This problem was the result of https://github.com/dlang/dmd/pull/5161 which moved EnumMember to be derived from VarDeclaration. This has caused various problems, such as an inconsistency in how enums are handled. Unfortunately, code has come to rely on these inconsistencies, so all I did was fix the particular problem identified in the bug report.

@ibuclaw this is a 7 year old problem, it doesn't really need to go in stable.

**Comment by WalterBright** [comment]
Why is this not getting merged?

**Comment by thewilsonator** [comment]
> Why is this not getting merged?

> This should target stable.

**Review by dkorpel — APPROVED** [review]

**Pull request merged**
