### PR TITLE
reduce indenting in dsymbolsem.d

### PR DESCRIPTION
**Pull request by thewilsonator**
best reviewed with whitespace off.

### CODE REVIEW

**Comment by WalterBright** [comment]
I'm not enamored with these mass reformattings. For one thing, they necessitate rebasing other PRs, and they make following the git history difficult, for a trivial benefit.

**Comment by RazvanN7** [comment]
@WalterBright Early returns are not a trivial benefit. They make the code much more readable. On the other hand there is 0 cost if `git blame -L` is used to find out the commits that modified a range of lines of code.

**Comment by MoonlightSentinel** [comment]
See the man page for `git blame`:

```
-w
           Ignore whitespace when comparing the parent’s version and the child’s to find where the lines came from.
```

Also implictly supported by some editors, e.g. the superb GitLens plugin for VSCode.

**Comment by RazvanN7** [comment]
@thewilsonator this seems to fail the CI testsuite.

**Comment by RazvanN7** [comment]
@thewilsonator any progress on this?

**Comment by RazvanN7** [comment]
@thewilsonator Adding `72h no response -> close`

**Comment by thewilsonator** [comment]
I think this should be good/green now. Need to squash, but otherwise alright.

**Comment by RazvanN7** [comment]
Tests are still failing.

**Comment by thewilsonator** [comment]
Hmm, I might break this PR into pieces.

**Comment by ljmf00** [comment]
Since all references are merged, shouldn't this be closed @thewilsonator ?

**Pull request closed without merging**
