### PR TITLE
Compare identifers in traits.d only by their toString thereby enabling use of switch statements

### PR DESCRIPTION
**Pull request by nordlow**
Motivation: There are currently about 50 traits and some traits definitions are very simple so the simple ones far down in `semanticTraits` are gonna be sped up.

Note that the `Identifier.value` (typically mapping to the token `__traits`) and `Identifier.isAnonymous` are useless for comparison and should be excluded from the comparison of identifiers in traits.

It might be possible to delay indentation of the added `switch` to reduce the diff.

### CODE REVIEW

**Review by thewilsonator — CHANGES_REQUESTED** [review]
Please provide benchmarks for this. I doubt this will be faster, comparing a bunch of pointers is going to be faster than string comparisons.

**Comment by nordlow** [comment]
> Please provide benchmarks for this. I doubt this will be faster, comparing a bunch of pointers is going to be faster than string comparisons.

Which pointer comparison are you referring to? AFAICT, the comparisons currently uses `Identifier.opEquals`.

**Comment by nordlow** [comment]
> Please provide benchmarks for this. I doubt this will be faster, comparing a bunch of pointers is going to be faster than string comparisons.

How do you suggest those benchmarks should be performed?

**Comment by nordlow** [comment]
Closing in favor of https://github.com/dlang/dmd/pull/16795.

**Pull request closed without merging**
