### PR TITLE
update version file 2.073.0

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
Auto-merge toggled off

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
With automerge on, it blocks testing of other PRs because it is given high priority. Turning automerge off until it starts passing.

**Comment by WalterBright** [comment]
Auto-merge toggled off

**Comment by MartinNowak** [comment]
Replaced `q"__VERSION__` w/ `q"__VENDOR__` in the test.

**Comment by MartinNowak** [comment]
> Bad idea; the error message will be different on LDC.

I know but all the other special tokens are times&dates @klickverbot.

**Comment by Geod24** [comment]
I have a feeling [we had this discussion before](https://github.com/dlang/dmd/pull/5379).
What about `__FILE__` / `__FUNCTION__` ? If none is suitable we should really just remove that test...

**Comment by MartinNowak** [comment]
We can't use file/line b/c they're apparently translated at a different stage and aren't expanded in heredoc strings or so. I'll just remove the test.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Pull request merged**
