### PR TITLE
fix Issue 16037 - assigning delegate to a scope variable shouldn't al…

### PR DESCRIPTION
**Pull request by WalterBright**
…locate closure

Improves the reach of @nogc code.

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
Why is it a DIP1000-only fix ?

**Comment by WalterBright** [comment]
So it doesn't break existing code.

**Comment by mathias-lang-sociomantic** [comment]
Do you have an example of code that would break with this fix ? It looks like a fix to a reject-valid, which should have a limited, if any, impact.

**Comment by WalterBright** [comment]
The thing is, the old behavior was still correct, because it generated a closure. It only failed when the function was marked `@nogc`.

So I was not willing to gratuitously break the old behavior. Recall that a lot of the "don't break working code" is because Sociomantic has strongly advocated that.

I recommend switching to -dip1000 as soon as you can. It has already found some expensive bugs in existing code bases.

**Comment by mathias-lang-sociomantic** [comment]
> The thing is, the old behavior was still correct, because it generated a closure. It only failed when the function was marked `@nogc`.

That is actually correct, and the point I was missing. So objection withdrawn on my side.

**Review by JinShil — APPROVED** [review]

**Pull request merged**
