### PR TITLE
Add __traits(classInstanceAlignment)

### PR DESCRIPTION
**Pull request by kinke**

### CODE REVIEW

**Comment by kinke** [comment]
Argh, `align(N) class C {}` seems unsupported.

**Comment by ljmf00** [comment]
Thanks for implementing this!

> Argh, `align(N) class C {}` seems unsupported.

What do you mean?

**Comment by kinke** [comment]
> What do you mean?

See 2nd commit title - unlike `StructDeclaration`, a `ClassDeclaration` has no `alignment` field (set to the scope's current alignment one during semantic).

**Comment by ljmf00** [comment]
> > What do you mean?
> 
> See 2nd commit title - unlike `StructDeclaration`, a `ClassDeclaration` has no `alignment` field (set to the scope's current alignment during semantic).

Oh, it prints the default alignment, maybe. Well, this needs to be fixed. Perhaps, `.alignof` would return the right alignment after that or the actual alignment of the reference?

**Comment by kinke** [comment]
We cannot change `C.alignof`, that's always going to remain the class-ref alignment.

> Well, this needs to be fixed.

Yeah I guess so, but not of high priority IMO. We should probably simple move the `alignment` field to the `AggregateDeclaration` base and set it during ClassDecl sema too. And maybe give `AggregateDeclaration` some `getActualAlignment()` method, which returns this explicit 'outer' one, or the natural alignment (`alignsize`).

**Comment by ljmf00** [comment]
> We cannot change `C.alignof`, that's always going to remain the class-ref alignment.

Yes, of course, I meant we should be careful if that is the case.

> Yeah I guess so, but not of high priority IMO. We should probably simply move the `alignment` field to the `AggregateDeclaration` base and set it during ClassDecl sema too. And maybe give `AggregateDeclaration` some `getActualAlignment()` method, which returns this explicit 'outer' one, or the natural alignment (`alignsize`).

Right.

**Review by ljmf00 — APPROVED** [review]

**Comment by ljmf00** [comment]
It is trivial to me that this should go through.

It facilitates https://github.com/dlang/druntime/pull/3802 and is somewhat related to https://issues.dlang.org/show_bug.cgi?id=16508 . @kinke I think you should at least reference the issue without closing it, until `align(N) class C {}` is supported.

**Comment by kinke** [comment]
Filed https://issues.dlang.org/show_bug.cgi?id=23081 wrt. ignored `align(N)` for ClassDecls.

> I think you should at least reference the issue

Yeah, thx for looking it up, I forgot it's specifically about class *members*.

**Review by RazvanN7 — APPROVED** [review]
This makes sense to me. However, ccing @WalterBright and @atilaneves as this is adding a new trait.

**Comment by atilaneves** [comment]
I'm ok with it if @WalterBright is.

**Comment by kinke** [comment]
Ping @WalterBright, it's been a week.

**Comment by WalterBright** [comment]
It's ok with me.

**Pull request merged**
