### PR TITLE
fix issue 19755 - Compiler crash

### PR DESCRIPTION
**Pull request by ghost**
Just an easy to fix unsafe access

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by Basile-z** [comment]
@thewilsonator, sorry I had to force push, auto-merge label needed again.

**Comment by thewilsonator** [comment]
Done.

**Comment by UplinkCoder** [comment]
There seems to be another bug here.
`Thunk self` should NOT be rewritten to `Thunk!int self`

**Comment by UplinkCoder** [comment]
ping @thewilsonator

**Comment by thewilsonator** [comment]
Hmm, yeah. That should error on use of uninstantiated template.

**Comment by Basile-z** [comment]
You mean that it's a hdrgen bug or a semantic one ?

**Comment by UplinkCoder** [comment]
not sure; I assume it's sema.

**Pull request merged**
