### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by ibuclaw**
- Fix 24281 - Segfault with missing field after named argument
- bump VERSION to v2.106.1-rc.1

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
Where's the merge commit?

**Comment by dkorpel** [comment]
What do you mean?

**Comment by ibuclaw** [comment]
There's now two divergent histories between master and stable. This has caused problems in the past.

**Comment by ibuclaw** [comment]
I noticed this when searching for the release tag on the master branch. There is no tag.

**Comment by ibuclaw** [comment]
> There's now two divergent histories between master and stable. This has caused problems in the past.

And the release build is indeed broken.
```
+ git -C dmd merge upstream/stable --no-ff
Auto-merging VERSION
CONFLICT (content): Merge conflict in VERSION
```

**Pull request merged**
