### PR TITLE
Make the auto-tester check for whitespace issues

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by WalterBright** [comment]
Ought to do a 'git blame' for each of those and harangue the submitter to use `tolf` and `detab` as part of their checkin script.

**Comment by yebblies** [comment]
We sure could, but the point of this is that the autotester will catch any new instances in the future.

**Comment by WalterBright** [comment]
Um, check the fail log. It shouldn't check makefiles for tabs.

**Comment by yebblies** [comment]
Yep, just updated it.  win32 doesn't include the makefiles in the SRC list so I missed it locally.

**Comment by yebblies** [comment]
All green now.

**Comment by yebblies** [comment]
Thanks!

**Pull request merged**
