### PR TITLE
refactor: split off StatementRewriteWalker to statementrww.d

### PR DESCRIPTION
**Pull request by WalterBright**
It really doesn't belong in func.d. It needing only two imports is strongly indicative of that.

### CODE REVIEW

**Comment by ibuclaw** [comment]
Maybe statement should be made a package, rather than having many abbreviated files called statementxyz.d

**Comment by UplinkCoder** [comment]
stmt_rewriter.d would be a nice name as well.

**Comment by WalterBright** [comment]
Reorganizing the code into packages is a dog for another day.

**Comment by yebblies** [comment]
I agree, but could you please use a less opaque name? `statementrewrite` would be better.

**Comment by WalterBright** [comment]
Long file names are annoying. Most of the dmd filenames are already abbreviations.

**Comment by UplinkCoder** [comment]
Well yes.
But stmtrewriter will tell me more then statementrrw.
when in doubt abriviate the common part,
such that developers only have to keep one abbreviation in mind rather then many.

**Comment by yebblies** [comment]
I have nothing against abbreviated names, I just think `rrw` is not a good choice, since it is basically opaque.

How about `srewrite.d`, like `sapply.d`?  I'm sure there's something better than `rrw` we can agree on.

**Comment by andralex** [comment]
@WalterBright please mind the reviews and rebase. The name is unlikely to cause grief if long.

**Comment by andralex** [comment]
@WalterBright much appreciated

**Comment by ibuclaw** [comment]
How is that name an improvement?

**Pull request merged**
