### PR TITLE
fix Issue 19447 - [REG2.066] fixed size slice assignment in ctfe lose…

### PR DESCRIPTION
**Pull request by WalterBright**
…s connection with array

The difficulty was that the interpreter failed to recognize a slice of a static array as being an lvalue.

### CODE REVIEW

**Comment by WalterBright** [comment]
It's a fairly serious bug, as it silently generates the wrong answer.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
Please target stable. cc @UplinkCoder

**Comment by WalterBright** [comment]
I don't think there's much point to targeting stable. This broke in version 2.066, and we're at 2.083 now.

**Comment by UplinkCoder** [comment]
I'd remark that there is a bit of code duplication,
other than that, LGTM.

**Comment by UplinkCoder** [comment]
Please add another test.
To ensure this fails:
```
void g19447(ref int[2] a)
{
    int[2] b=2;
    a=b;
    //a[]=b;            // works
    //a[] = b[];                // works
    assert(a[0]==2);
}```

**Comment by WalterBright** [comment]
@UplinkCoder why should that fail?

**Comment by jacob-carlborg** [comment]
Why is there an extra commit "Merge branch 'stable' into fix19447" ?

**Comment by UplinkCoder** [comment]
the code I posted changes an array at global scope;
And then ctfe would modify an exsiting ast node.

**Comment by WalterBright** [comment]
I'm putting this back into master, as it relies on some of the refactoring work I've done earlier.

**Comment by ibuclaw** [comment]
> It does mean LDC get the fixes sooner.

Which also means GDC gets the fix later. :-)

**Comment by ZombineDev** [comment]
@ibuclaw not necessarily much later, as you can merge `stable` to `master` at any time.

**Comment by RazvanN7** [comment]
This PR has introduced a regression: https://issues.dlang.org/show_bug.cgi?id=20133

**Pull request merged**
