### PR TITLE
Attempt to fix issue 23868

### PR DESCRIPTION
**Pull request by JohanEngelen**
https://issues.dlang.org/show_bug.cgi?id=23868

Not sure if this is correct.

### CODE REVIEW

**Comment by maxhaton** [comment]
@WalterBright

**Comment by JohanEngelen** [comment]
This probably needs some extra work to make it exception-safe (what if exception is thrown in the dtor)

**Review by RazvanN7 — APPROVED** [review]
I also don't think the copy was needed.

Please update the failing test.

**Comment by RazvanN7** [comment]
> This probably needs some extra work to make it exception-safe (what if exception is thrown in the dtor)

This case wasn't treated previously either. Since we are not constructing anything I don't see why we would need to do anything extra.

**Comment by JohanEngelen** [comment]
> > This probably needs some extra work to make it exception-safe (what if exception is thrown in the dtor)
> 
> This case wasn't treated previously either. Since we are not constructing anything I don't see why we would need to do anything extra.

The state is different after exception is thrown in dtor:
Before:  `this` object contains new assigned object
After: `this` object contains old value (on which the dtor failed). The assign object value is lost.

**Comment by JohanEngelen** [comment]
Testcase whose behavior changes with this change (i.e. I think the PR is wrong currently) :
```d
import std.stdio;
import std.exception;

struct S {
    int i;

    ~this() {
        writeln("~S(", i, ")");
        if (i == 1)
            throw new Exception("thorw");
    }
}

void main() {
    S s;
    s.i = 1;

    try {
        s = S(2);
    } catch (Throwable) {}

    writeln(s.i);
}
```

Without the change:
```
~S(1)
2
~S(2)
```
With this PR:
```
~S(1)
1
~S(1)
object.Exception@../dtor_throw.d(11): thorw
----------------
??:? void dtor_throw.S.__dtor() [0x100fd3689]
??:? _Dmain [0x100fd35ce]
```

**Comment by 12345swordy** [comment]
The deconstructor should be nogc and nothrow by default here.

**Comment by JohanEngelen** [comment]
> The deconstructor should be nogc and nothrow by default here.

Why?  Is that a language requirement? (do you have a reference?)

**Comment by WalterBright** [comment]
Please see https://issues.dlang.org/show_bug.cgi?id=23868 which explains that this solution is not correct, and offers suggestions on how to avoid the issue.

**Review by WalterBright — CHANGES_REQUESTED** [review]
Solution is not correct, see bugzilla for commentary.

**Pull request closed without merging**
