### PR TITLE
[D1] Minor improvements to the makefile

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, it seems like travis C compilers don't like the C++03 standard.

**Comment by leandro-lucarella-sociomantic** [comment]
And it seems pretty complicated to install newer compiler versions in travis: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

So I might consider some conditional adding of that flag.

**Comment by mihails-strasuns-sociomantic** [comment]
Try picking https://github.com/dlang/dmd/commit/c8162374dbce86454d9a02b377bc405267069b80 instead

**Comment by leandro-lucarella-sociomantic** [comment]
It seems like too much trouble. This is only to shut up some warnings? I wonder if it's even worth it.

**Comment by leandro-lucarella-sociomantic** [comment]
Using an older standard (98) seems to work fine. If this is only about warnings on a zombie branch that's being fed some brain only once in a while, I think we can move on... :)

**Pull request merged**
