### PR TITLE
switch to expressionSemantic() from semantic()

### PR DESCRIPTION
**Pull request by WalterBright**
I hadn't realized there were so many calls. Anyhow, this makes things much more greppable.

### CODE REVIEW

**Comment by WalterBright** [comment]
While a lot of lines, it is just a name change. Trivial.

**Review by JinShil — APPROVED** [review]
Nit:  I don't really like the name, as "expressionSemantic" being a member of type "Expression" seems redundant.  It would really only make sense if you were trying to disambiguate it from other "...Semantic" members.

That being said, I don't see any problem with this PR.

**Comment by ibuclaw** [comment]
> I don't really like the name, as "expressionSemantic" being a member of type "Expression" seems redundant

They are all free functions now. If the invocation still looks like a member function call, that's because of ufcs.

**Comment by JinShil** [comment]
> They are all free functions now.

Still, can't D disambiguate based on the parameter types (`semantic(Express e)` vs `semantic(DSymbol s)`)?

**Comment by ibuclaw** [comment]
It can, the reasoning was mentioned in #7209 (and a few other PRs that renamed other semantic functions).

**Comment by WalterBright** [comment]
Please pull this one so I can do the next one.

**Pull request merged**
