### PR TITLE
workaround azure failures

### PR DESCRIPTION
**Pull request by rainers**
I suspect that there is some new exception validation enabled on the build servers that we yet don't understand.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by wilzbach** [comment]
@rainers see: https://github.com/dlang/druntime/pull/2822#issuecomment-539872764

**Comment by rainers** [comment]
Arrgh, the horrors of quoting when mixing bash and cmd. I won't be able to do anything on this before tonight.

**Comment by WalterBright** [comment]
> I won't be able to do anything on this before tonight.

No worries. I'm just glad this is getting fixed! Thank you!

**Comment by rainers** [comment]
druntime is back to green.

**Pull request closed without merging**
