### PR TITLE
[Draft] Disable case range limit

### PR DESCRIPTION
**Pull request by pbackus**
It's unclear what the purpose of this limit is, and disabling it doesn't seem to break anything, so let's see how it does in CI.

### CODE REVIEW

**Comment by dkorpel** [comment]
I think it's to prevent people from using `switch` to e.g. check for integer ranges, since that could slow down compilation a lot and increase memory consumption given that the current implementation just duplicates case statements. E.g. this innocuous looking code would make the compiler crash:
```D
switch (x) {
    case 1000..999_999: return "grand";
    case 1000_000 .. 999_999_999: return "million";
    case 1000_000_000..int.max: return "billion";
    default: return false;
}
```

**Comment by pbackus** [comment]
Makes sense. I guess the correct fix would be to detect switch statements with large ranges and rewrite them as `if`-`else` chains.

**Comment by UplinkCoder** [comment]
could be done ... not that hard. 
But a programmer should be warned if they are generating such code.

**Comment by UplinkCoder** [comment]
no one writes a 255+ case switch by hand.

**Comment by WalterBright** [comment]
@dkorpel is right. Disabling this check is going to cause grief for anyone who intentionally or not writes a very large case range.

**Pull request closed without merging**
