### PR TITLE
Turn deprecation into error for privately imported symbols

### PR DESCRIPTION
**Pull request by RazvanN7**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
To we really want to do this before all `__traits` has been loosened, https://github.com/dlang/dmd/pull/9325?

**Comment by RazvanN7** [comment]
> To we really want to do this before all `__traits` has been loosened, #9325?

Looking at the code in #9325 , it seems that it should that be affected by this PR.

**Comment by jacob-carlborg** [comment]
Perhaps it's time due to notify the owners of the projects that fail to build in buildkit, or start making PRs to those projects.

**Comment by wilzbach** [comment]
Needs a short changelog entry, s.t. it's easier to for users to find potential problems when upgrading and knowing in which version the change was introduced.

**Comment by RazvanN7** [comment]
So... I've made PRs to fix all the failing projects (or dependencies of failing projects); now we have to wait for the authors to merge and push new tags

**Comment by wilzbach** [comment]
> we have to wait for the authors to merge and push new tags

FYI: if they don't respond within a reasonable time frame (typically three days or so), we can remove these projects from buildkite. We have done this before for semi-dead projects.

**Comment by wilzbach** [comment]
Ocean just released a new version yesterday with @Razvan's fix, so this is only missing a changelog entry to be good to go.

**Comment by rainers** [comment]
There are a couple of more places where a similar deprecation is emitted. grep for `is not visible from module`.

**Comment by RazvanN7** [comment]
Changelog entry added.

**Comment by jacob-carlborg** [comment]
> There are a couple of more places where a similar deprecation is emitted. grep for is not visible from module.

Yeah, I got 8 hits.

**Comment by RazvanN7** [comment]
>There are a couple of more places where a similar deprecation is emitted. grep for is not visible from module.

Those can be treated in subsequent PRs as they deprecate in slightly different situations.

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
>>There are a couple of more places where a similar deprecation is emitted. grep for is not visible from module.
>Those can be treated in subsequent PRs as they deprecate in slightly different situations.

OK, lets not keep this waiting.

**Pull request merged**
