### PR TITLE
Fix issue 20369 - shadowed variable in foreach loop always considered "foreach variable"

### PR DESCRIPTION
**Pull request by eoan-ermine**

### CODE REVIEW

**Review by dkorpel — APPROVED** [review]

**Review by RazvanN7 — COMMENTED** [review]
I think it would be better if the error/deprecation message also outputs the line number of the variable that is shadowed.

**Comment by ssvb** [comment]
Would it be better to squash two commits into a single one? In order to avoid having a commit in the git history, which fails tests.

**Comment by dkorpel** [comment]
There's a 'Squash and merge' button and 'auto-merge-squash' label, so it's not needed to squash manually.

**Comment by maxhaton** [comment]
Having to squash often means poor commit-iquette - changing something and forgetting to update the tests should be done with an amend rather than another commit. 

Keeping (valid) history around is actually pretty worthwhile so squashing can come back to bite you.

**Comment by eoan-ermine** [comment]
> I think it would be better if the error/deprecation message also outputs the line number of the variable that is shadowed.

Like now?

**Comment by eoan-ermine** [comment]
> > Like now?
> 
> @eoan-ermine Using `errorSupplemental` - you can find many examples in `compiler/src/dmd/expressionsem.d`.

Thanks! Got it! Hope it's fine now!

**Comment by thewilsonator** [comment]
looks like you need to update the output of a few more tests
```
FAILED targets:
- fail_compilation/diag11425.d
- fail_compilation/fail110.d
- fail_compilation/fail93.d
```

**Comment by PetarKirov** [comment]
> looks like you need to update the output of a few more tests

@eoan-ermine you can do that automatically with the following command:

```
AUTO_UPDATE=1 ./run.d fail
```

**Review by PetarKirov — APPROVED** [review]

**Pull request merged**
