### PR TITLE
DIP1034 add TypeNoreturn to astbase.d and mtype.d

### PR DESCRIPTION
**Pull request by WalterBright**
First step to implement https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1034.md

Adds the TypeNoreturn type.

None of this code can be accessed yet, so no test cases.

### CODE REVIEW

**Comment by Geod24** [comment]
Can we get a complete implementation this time ? Dead code can't be reviewed.

**Comment by WalterBright** [comment]
The PR will be so large I guarantee nobody will review it.

**Comment by WalterBright** [comment]
This PR is reviewable if one is familiar with the internals of DMD.

**Comment by Geod24** [comment]
> The PR will be so large I guarantee nobody will review it.

You can do it commit-by-commit, like you are doing currently.

Having a fully-fledged out PR allows other people to assess if the design is sound, while individual commits allow us to assess if code changes make sense. Sending out minor PRs without clear direction for the reviewer means that we can review neither the implementation (because it does nothing) nor the design.

**Comment by WalterBright** [comment]
The design is pretty obvious, it follows the same pattern as the other types. This PR is simply filling in the boilerplate that every distinct type has. This PR is quite easy to review.

**Review by Geod24 — APPROVED** [review]

**Pull request merged**
