### PR TITLE
DDMD: Fix duplicate definition linker errors in gdc

### PR DESCRIPTION
**Pull request by ibuclaw**
As per discussion, dmd does some fancy section trick to evade this.  But it just won't fly in gdc.

@klickverbot - would this bug you?

### CODE REVIEW

**Comment by yebblies** [comment]
You should probably make up a new version for these and set it from the command line, eg `version=OverrideAllocationFunctions`.  Host compiler conditions really don't belong in here.

**Comment by MartinNowak** [comment]
It also doesn't work with LDC b/c only dmd creates multilibs.

**Comment by MartinNowak** [comment]
We should make a GC proxy to override the allocations. Simply disabling them for GDC/LDC is a major slowdown.

**Comment by yebblies** [comment]
> We should make a GC proxy to override the allocations. Simply disabling them for GDC/LDC is a major slowdown.

That's outside my expertise.  How complicated is it?

**Comment by MartinNowak** [comment]
Let's deactivate the stuff for now.

**Pull request merged**
