### PR TITLE
dtoh: Remove isBuildingCompiler and related code

### PR DESCRIPTION
**Pull request by ibuclaw**
As frontend.h is being built without it, I assume then that the goal is to make dtoh usable without the need for "insider knowledge" specific to the dmd internals.

### CODE REVIEW

**Review by MoonlightSentinel — APPROVED** [review]
`isBuildingCompiler` always felt wrong.

**Comment by ibuclaw** [comment]
> `isBuildingCompiler` always felt wrong.

AssocArray can be generated by marking `dmd.root.aav.AssocArray` as extern(C++), and `DArray` can be generated by adding a dcompat.d module that roughly corresponds to dcompat.h.  But as dynamic arrays are pretty integral, I guess it is better to have it inline in dtoh.

```diff
--- a/src/dmd/frontend.h
+++ b/src/dmd/frontend.h
@@ -7042,6 +7042,14 @@ typedef void* Value;
 
 typedef KeyValueTemplate<void*, void*> KeyValue;
 
+template <typename K, typename V>
+struct AssocArray
+{
+    // Ignoring var aa alignment 0
+public:
+    AA* aa;
+};
+
 typedef _d_real longdouble;
 
 extern void browse(const char* url);
@@ -7613,7 +7621,6 @@ template <typename T>
 struct Array
 {
     // Ignoring var length alignment 0
-public:
     size_t length;
     // Ignoring var data alignment 0
     DArray< T > data;
diff --git a/src/dmd/root/aav.d b/src/dmd/root/aav.d
index 15abd7bba..2f4f7af8f 100644
--- a/src/dmd/root/aav.d
+++ b/src/dmd/root/aav.d
@@ -268,7 +268,7 @@ unittest
     assert(v == cast(void*)3);
 }
 
-struct AssocArray(K,V)
+extern (C++) struct AssocArray(K,V)
 {
     private AA* aa;
 
```
There's a bug in the `public`/`private` implementation too @MoonlightSentinel.

**Comment by MoonlightSentinel** [comment]
> But as dynamic arrays are pretty integral, I guess it is better to have it inline in dtoh.

Sounds reasonable

> There's a bug in the public/private implementation too @MoonlightSentinel.

That's caused by the current handling of template declarations which doesn't `visit` the template members (fixed in #11848 )

**Comment by ibuclaw** [comment]
Ok to merge?

**Comment by MoonlightSentinel** [comment]
Yes

**Pull request merged**
