### PR TITLE
Fix problematic tests for GDC's testsuite

### PR DESCRIPTION
**Pull request by ibuclaw**
These lines are problematic gdc testsuite (we inject dejagnu options to replace d_do_test ones).

```
--- a/test/compilable/iasm_labeloperand.d
+++ b/test/compilable/iasm_labeloperand.d
@@ -1,4 +1,4 @@
-<U+FEFF>
+
```

### CODE REVIEW

**Comment by ibuclaw** [comment]
> But GDC itself can handle BOMs, right?

Yes, just not when it's in the middle of the file.

**Comment by ibuclaw** [comment]
I'm finding a few more, so sending them through too.

**Comment by MartinNowak** [comment]
Auto-merge toggled on

**Comment by ibuclaw** [comment]
Thanks

**Pull request merged**
