### PR TITLE
Revert "Fix Issue 22118 - Const union causes false multiple-initialization error in constructor"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/dmd#12875

1. This was merged into stable after 22 minutes.
2. Change is non-trivial.
3. Change subverts the AST, which has been found to cause [more problems](https://github.com/dlang/dmd/pull/12783) than [it resolves](https://github.com/dlang/dmd/pull/9467).
4. We are less than a week away from a point release being cut.

### CODE REVIEW

**Review by RazvanN7 — APPROVED** [review]
OK, should resubmit for master?

**Comment by WalterBright** [comment]
If you're going to resubmit it, please see my comments on the original.

**Comment by ibuclaw** [comment]
> OK, should resubmit for master?

1. Why can't fieldInit be set correctly in modifyFieldVar?
2. See Walter's coments.
3. 72h no objection label.

**Review by kinke — APPROVED** [review]

**Comment by ibuclaw** [comment]
```
+ for proj in druntime phobos
+ '[' '!' -d ../phobos ']'
+ '[' revert-12875-Issue_22118 '!=' master ']'
+ '[' revert-12875-Issue_22118 '!=' stable ']'
+ git ls-remote --exit-code --heads https://github.com/dlang/phobos.git revert-12875-Issue_22118
+ clone https://github.com/dlang/phobos.git ../phobos master
```
CI scripts are broken, again.

**Comment by Geod24** [comment]
Don't create a revert branch upstream.

**Pull request closed without merging**
