### PR TITLE
[D1] Add ddoc support for 'Template Params' section

### PR DESCRIPTION
**Pull request by andrej-mitrovic-sociomantic**
Untested yet as I have to figure out how to fix my libraries on this Ubuntu clone.

Perhaps the autotester will lend me a hand though. :) Let's see what it says..

### CODE REVIEW

**Comment by andrej-mitrovic-sociomantic** [comment]
@mihails-strasuns-sociomantic: So this seems to build, but I can't currently test it because I'm missing GCC and my system's a little bit broken right now. :)

Could you try to build this locally and run `dmd -D test.d` with a `Template Params:` section and see if this works? I'd appreciate it!

**Comment by mihails-strasuns-sociomantic** [comment]
```D
/**
    Template Params:
        T = anything
 */
void foo (T) (T t) { }
```

produces this HTML:

```HTML
<html><head>
        <META http-equiv="content-type" content="text/html; charset=utf-8">
        <title>sample</title>
        </head><body>
        <h1>sample</h1>
        <!-- Generated by Ddoc from sample.d -->
<br><br>
<dl><dt><big><a name="foo"></a>void <u>foo</u>(T)(T <i>t</i>);
</big></dt>
<dd>Template Params:
        T = anything<br><br>

</dd>
</dl>

        <hr><small>Page generated by <a href="http://www.digitalmars.com/d/1.0/ddoc.html">Ddoc</a>. </small>
        </body></html>
```

**Comment by WalterBright** [comment]
The autotester doesn't test the D1 branch.

**Comment by WalterBright** [comment]
I don't know that Travis does.

**Comment by mihails-strasuns-sociomantic** [comment]
Travis job only checks that branch builds, no tests.

**Comment by andrej-mitrovic-sociomantic** [comment]
I don't see any tests in the D1 branch anywho.

So it looks like the feature works. :) 

Review & merge?

**Comment by Geod24** [comment]
Just a remark about the section name: Currently the specs doesn't mention it *explicitly*, but no section name includes whitespace (Think of "See_Also"). It wouldn't be a problem if all section name were fixed, but given we can have user-defined section. So I suggest `Template_Params`.

**Comment by andrej-mitrovic-sociomantic** [comment]
> Just a remark about the section name

Ah.. I've always hated `See_Also`. But seeing that it's a convention I'll fix it up. 

Btw @Geod24 this is the first time I've realized that you're Mathias, because Thunderbird said so. I remember your nickname from way back. :)

**Comment by andrej-mitrovic-sociomantic** [comment]
I've updated to use the detected section name as `Template_Params`.

**Comment by andrej-mitrovic-sociomantic** [comment]
@mihails-strasuns-sociomantic: Whenever you're ready to give a LGTM. :)

**Comment by mihails-strasuns-sociomantic** [comment]
Checked again + compared vs output of plain `Params`. LGTM.

**Comment by andrej-mitrovic-sociomantic** [comment]
Wait I'll change this back to `Template Params`. I don't think it makes sense to shoot ourselves in the foot by forcing us to change all of our code to use `Template_Params`.

**Comment by andrej-mitrovic-sociomantic** [comment]
Ok so I think the best way forward is to actually support both styles in the D1 branch. It allows our existing code to generate docs, while allowing an easier transition to `Template_Params`. So I'll change the PR to allow this.

**Comment by andrej-mitrovic-sociomantic** [comment]
Updated. @mihails-strasuns-sociomantic: I've also tested this locally and it seems to work. I've added some checks for lowercase matches as well, as I see plenty of mixed-style in our code (if there is a case-insensitive version of `icmp` I would use that)

**Comment by Geod24** [comment]
> Ok so I think the best way forward is to actually support both styles in the D1 branch. It allows our existing code to generate docs, while allowing an easier transition to Template_Params. So I'll change the PR to allow this.

:+1: 
Works for me. Though on the long run we should switch to `Template_Params`. There is a lot of work involved and this change is probably one of the lightest and can be performed by a simple `sed`. Things like reordering sections are probably the most painful.

> (if there is a case-insensitive version of icmp I would use that)

`icmp` is case insensitive comparison.

**Comment by andrej-mitrovic-sociomantic** [comment]
> icmp is case insensitive comparison

Ah, I've been fooled. Let me remove those extra icmp checks then.

**Comment by andrej-mitrovic-sociomantic** [comment]
So it looks like the compiler does not support whitespace-delimited keywords, the styling output of the HTML confirms this. We'll have to go with supporting only `Template_Params`.

**Comment by WalterBright** [comment]
Do you want me to pull this?

**Comment by andrej-mitrovic-sociomantic** [comment]
There are some errors but this looks unrelated to this PR:

```
backend/code.c:23:14: error: ‘code_list’ was declared ‘extern’ and later ‘static’ [-fpermissive]
backend/code.h:85:14: error: previous declaration of ‘code_list’ [-fpermissive]
```

Anyone have any idea what this is about?

**Comment by mihails-strasuns-sociomantic** [comment]
Different set of default `CFLAGS` in travis job?

**Comment by mihails-strasuns-sociomantic** [comment]
(builds locally for me with gcc 4.8.4)

**Comment by andrej-mitrovic-sociomantic** [comment]
Ok let's go forward with this! :)

**Comment by mihails-strasuns-sociomantic** [comment]
Ah I see the problem. Your branch builds but current `dmd-1.x` HEAD doesn't build because of backend changes @WalterBright has merged from D2 upstream. Thus merged Travis build doesn't build too.

**Comment by WalterBright** [comment]
I pushed a fix for the build error.

**Comment by andrej-mitrovic-sociomantic** [comment]
Well, it looks like there are more bugs upstream? :)

**Comment by mihails-strasuns-sociomantic** [comment]
Branch HEAD has been fixed, please rebase

**Comment by andrej-mitrovic-sociomantic** [comment]
Rebased.

**Pull request merged**
