### PR TITLE
Allow pragma(inline, knownAtCTFE);

### PR DESCRIPTION
**Pull request by thewilsonator**

### CODE REVIEW

**Review by PetarKirov — COMMENTED** [review]
Please, add a test, otherwise looks good to me.

**Comment by Geod24** [comment]
Test, specs change, release note entry. But feature 👍

**Comment by 12345swordy** [comment]
A brief description of what this PR would do would be nice.

**Comment by thewilsonator** [comment]
Any ideas how to resolve the forward reference issues?

**Comment by BorisCarvajal** [comment]
> Any ideas how to resolve the forward reference issues?

I took a look at that issue, `pragma` logic is run very early before its inner symbols get processed.
I've made an attempt to fix it by getting the code to run in the function semantic phase, I'm currently finishing the last details and it seems to work fine.

**Comment by BorisCarvajal** [comment]
new version #11967

**Pull request closed without merging**
