### PR TITLE
remove dead code: addLibrary()

### PR DESCRIPTION
**Pull request by WalterBright**
trivial

### CODE REVIEW

**Comment by MartinNowak** [comment]
This apparently broke our nightlies. It was merged despite the Travis-CI build failure. Can we somehow fix the auto-merge to take this into account?
https://travis-ci.org/dlang/dmd/jobs/145424319#L588

**Comment by MartinNowak** [comment]
It was actually #5939 to break the build.

**Comment by ZombineDev** [comment]
Thanks, @WalterBright!

**Comment by WalterBright** [comment]
> It was merged despite the Travis-CI build failure. Can we somehow fix the auto-merge to take this into account @braddr?

Those failures tend to be heisenbugs unrelated to the PR. I'm reluctant to do this until it gets more reliable.

There also appears to be no way to kick the Travis-CI to get it to re-run the tests.

**Comment by MartinNowak** [comment]
> Those failures tend to be heisenbugs unrelated to the PR. I'm reluctant to do this until it gets more reliable.

Just submitted one PR yesterday to fix some download issues.
https://github.com/travis-ci/travis-build/pull/799

> There also appears to be no way to kick the Travis-CI to get it to re-run the tests.

Yes there is, you need to login w/ your github account, b/c only repo owner can restart tests.

**Pull request merged**
