### PR TITLE
[REG2.068.1-b1] Issue 14985 - Link failure for const TypeInfo of speculative instantiated struct

### PR DESCRIPTION
**Pull request by 9rnsr**
https://issues.dlang.org/show_bug.cgi?id=14985

Fixup for #4944.

### CODE REVIEW

**Comment by 9rnsr** [comment]
All green.

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
Thanks!

**Comment by CyberShadow** [comment]
This pull request introduced a regression:
https://issues.dlang.org/show_bug.cgi?id=17155

**Pull request merged**
