### PR TITLE
Fix Bugzilla issue 24111 - [ImportC] fatal error C1034: stdio.h: no include path set

### PR DESCRIPTION
**Pull request by shoo**
I have attempted a fix for this problem: https://issues.dlang.org/show_bug.cgi?id=24111
https://github.com/dlang/dmd/pull/15780 is the predecessor's approach to this problem.
My implementation is based on how it is used in LDC ( https://github.com/ldc-developers/ldc/blob/8399e47ceb4dfbbcf1ca0b7cf934c04a864387b7/driver/tool.cpp#L297-L312 )
Also, I refer to a part of std.process to pass environment variables to CreateProcess. ( https://github.com/dlang/phobos/blob/dcbfbd43ac321e81af60afd795bd0f3c3f47cfa0/std/process.d#L412-L440 , https://github.com/dlang/phobos/blob/dcbfbd43ac321e81af60afd795bd0f3c3f47cfa0/std/process.d#L1450-L1482 )

I have very little experience with dmd code, so my coding style may be incorrect or inefficiently implemented. Please point out any problems.

### CODE REVIEW

**Comment by rikkimax** [comment]
This seems quite a bit more complex than is required.

I suggest setting the environment variable into the process state instead and then resetting it to the old value afterward.
This is what LDC appears to be doing.

**Comment by shoo** [comment]
> This seems quite a bit more complex than is required.
> 
> I suggest setting the environment variable into the process state instead and then resetting it to the old value afterward. This is what LDC appears to be doing.

Fix it.
The process of checking for duplication with existing paths was also removed as it was not very useful.

**Comment by rikkimax** [comment]
Okay, that looks a lot cleaner.

The failures for OSX are currently known and are unrelated to you.
@ibuclaw has a plan for it.

**Comment by thewilsonator** [comment]
are you able to add a test case for this issue?

**Comment by shoo** [comment]
> are you able to add a test case for this issue?

I would like to be able to add a test case similar to or minimized from the [dub test case](
https://github.com/dlang/dub/tree/1acfe7b4fa378ac76ded73a30edb9a4df1147204/test/use-c-sources) and run it on Windows with the INCLUDE environment variable forced to be empty.

```bat
@REM In the Windows *.bat file:
cd .\test\use-c-sources\
set INCLUDE=
dub build
```

However, I could not understand how to properly add the test case.
Can you tell me a good way to do this?

**Comment by thewilsonator** [comment]
run `dub build -v` and extract the compiler command and use that in place of `dub build`, as for how to do windows batch file tests, not sure. We definitely have`.sh` shell tests for posix systems.

**Comment by shoo** [comment]
@thewilsonator How about this?

**Comment by shoo** [comment]
Can anyone review this PR?

**Review by thewilsonator — APPROVED** [review]

**Pull request merged**
