### PR TITLE
Rename 'safe' global arg to 'vsafe'

### PR DESCRIPTION
**Pull request by mihails-strasuns**
Trivial tweak to prevent reviewer confusion like in https://github.com/dlang/dmd/pull/6183#discussion_r82521760

### CODE REVIEW

**Comment by WalterBright** [comment]
-transition=safe does not work without -dip25. I don't understand this reversion, anyway, because nobody uses -dip25.

**Comment by WalterBright** [comment]
-transition=safe does not enable new semantics for -dip25, it enables a superset of them. It does not change -dip25.

**Comment by MartinNowak** [comment]
@Dicebot point is that the meaning of the `-transition` switch should only be additional messages that highlight semantic changes. Instead `-transition=safe` now enables new semantics (-dip25).

**Comment by WalterBright** [comment]
I don't see the value in the rename. Why is vsafe less confusing?

Regardless of the name of the switch, it still needs to enable dip25 internally. It is not designed to work without dip25.

**Comment by MartinNowak** [comment]
It's less confusing b/c it's not related to somehow turning on/off `@safe`.

**Comment by WalterBright** [comment]
> 1) DIP25 is becoming the default in next release so this is irrelevant

But it's not the default **now** and so now there's an unknown state where -transition=safe is thrown and -dip25 is not. This state was not designed for, there are no test cases for it, and should not exist.

**Comment by WalterBright** [comment]
I don't particularly mind the vsafe change, and I would have pulled this but for the -dip25 change. It's another reason why independent changes should be in separate PRs.

**Pull request merged**
