### PR TITLE
Attempt to prevent a race condition with dmd test runner when same file but different extension is used

### PR DESCRIPTION
**Pull request by rikkimax**
My working theory is that when you have tests with the same base name but different extensions, it is possible for the concurrent test runner to result in a test trying to clobber another.

This is an attempt to fix that by simply adding the file extension.

A failed write of object file was discovered by @benjones, thanks to my UAX31 ranges PR.

I've also undone a previous PR he did on my suggestion although he only did one of the files that needed the adjustment.

It may take a few weeks to confirm that this works (beyond CI passing).

### CODE REVIEW

**Comment by rikkimax** [comment]
I suspect someone is going to have opinions about what this PR is doing (adding ``d``/``c`` directory for outputs).

Which makes it a little ugly. But short of verifying a base name is the only one (ignoring extension), I suspect this is the better solution to the problem.

**Comment by benjones** [comment]
How about just adding /c to importC tests and leaving the d ones alone?

**Comment by rikkimax** [comment]
``-c`` or ``-o-`` maybe, depending upon the order of evaluation of the flags.

However that only fixes these tests, what happens when someone else tries to do this another time?

**Comment by dkorpel** [comment]
The issue of race conditions with ImportC tests and D tests has come up before, so a structural solution is indeed in place.

> But short of verifying a base name is the only one (ignoring extension), I suspect this is the better solution to the problem.

I don't see a problem with simply disallowing multiple tests with the same name, but this solution is fine as well.

**Review by dkorpel — APPROVED** [review]

**Pull request merged**
