### PR TITLE
fix Issue 12092 - Wrong TLS access in PIC code (X86_32)

### PR DESCRIPTION
**Pull request by MartinNowak**
- fix code sequence to access TLS variables in 32-bit PIC code
- currently uses text relocations

[Issue 12092 – Wrong TLS access in PIC code (X86_32)](https://issues.dlang.org/show_bug.cgi?id=12092)

### CODE REVIEW

**Comment by 9rnsr** [comment]
Maybe this PR introduces the Linux 32bit link failure in `test/runnable/s2ir.d`.
https://auto-tester.puremagic.com/?projectid=1

(Strangely, the failure does not appear in [pull request testers](https://auto-tester.puremagic.com/pulls.ghtml?projectid=1))

**Comment by yebblies** [comment]
> (Strangely, the failure does not appear in pull request testers)

That could be because the pull testers don't run the full set of compiler switch permutations.  I think this would be the first time running the full permutations actually caught a bug that the fast mode missed.

**Comment by MartinNowak** [comment]
> Maybe this PR introduces the Linux 32bit link failure in test/runnable/s2ir.d.

Yeah, will look at it.

**Comment by 9rnsr** [comment]
> Yeah, will look at it.

Thank you.

**Comment by MartinNowak** [comment]
#4253

**Pull request merged**
