### PR TITLE
Activate -dip1008 by default

### PR DESCRIPTION
**Pull request by RazvanN7**
Adoption of https://github.com/dlang/dmd/pull/8508

### CODE REVIEW

**Comment by rainers** [comment]
druntime needs to be fixed first, see https://github.com/dlang/dmd/pull/8508#issuecomment-538310708

**Comment by RazvanN7** [comment]
>druntime needs to be fixed first, see #8508 (comment)

Yes, I discovered that the default trace handler allocates with the GC a new trace handler (in druntime). I'm working on a fix.

**Comment by RazvanN7** [comment]
Current issues with this PR:

1. As @rainers mentioned, dip1008 still allocates with the GC the traceHandler [1]. The class should probably be manually allocated, however this means that we should then track its usage so we can deallocate it.

2. A lot of catched exceptions escape their catch block in phobos [2]. For this situation I found a trick: instead of `if (firstException) throw firstException;` we have:

```d
if (firstException)
{
    try
    {
        throw new Exception("dummy exception");
    }
    catch(Throwable e)
    {
        e = firstException;
        throw e;
    }
}
```
For some reason e is allowed to escape the catch scope. The DIP says: "In catch blocks, e is regarded as scope so that it cannot escape the catch block. As a special case, if e is thrown in a catch block then it can escape.  This works because, as mentioned before, _d_throwc() or _d_throwdwarf() will increment the reference count." . I get that the reference count is incremented, but still, this all just looks like a hack.

3. 
```d
Exception collectException(void delegate() dg)
{
    try
        dg();
    catch (Exception e)
        return e.;
    return null;
}
```
`e` is scope, so it cannot outlive the catch block. The only thing you could do here is clone `e` but then you're in the same situation as in point 1 (manually manage the exception).

I don't completely understand the druntime internals of dip1008, but it seems like a major limitation that the catched exceptions have to be `scope` in the catch block and the relaxation that you can further throw the catched exceptions seems somewhat arbitrary.

[1] https://github.com/dlang/druntime/blob/master/src/core/runtime.d#L727
[2] https://github.com/dlang/phobos/blob/master/std/parallelism.d#L3712

**Comment by rainers** [comment]
Thanks @RazvanN7 for the analysis.

> 1. dip1008 still allocates with the GC the traceHandler [1]

To avoid confusion: rhe traceHandler allocates a stack dump.

I don't like all the special cases that come with DIP1008 to begin with. Wouldn't it be better to just allocate from the GC, but pass a flag to never start a collection when in `@nogc` code? Calling `addRange`/`removeRange` in addition to C malloc/free is less efficient anyway (and happens unconditionally because `Throwable` contains strings and a `next` pointer).

That would cause the exception not to be deallocated immediately with the catch clause, but that's also not guaranteed with DIP1008, e.g. when the exception is chained to a GC allocated exception.

**Comment by WalterBright** [comment]
We had a meeting with Don Clugston a while back (or was it email?) who is the implementer of the exception chaining thing. He agreed he'd be happy if we got rid of it (something I'd advocated for a while now), which would greatly simplify this problem.

I suggest doing that, and then revisiting this.

**Comment by rainers** [comment]
I think if we consider removing exception chaining, treating errors as exceptions should be open for discussion, too: they behave differently anyway (no guarantee that unwinding code is executed), so providing a hookable error handler should work just as well and makes the distinction cleaner, It would also simplify the exception handling.

**Comment by WalterBright** [comment]
> if we consider removing exception chaining, treating errors as exceptions should be open for discussion, too

Sure, but it's an orthogonal topic.

Frankly, I don't see a purpose in Error anymore. Program bugs should just use assert().

**Comment by Geod24** [comment]
@WalterBright : Is it something that can be offloaded to the community ? I'm sure something like "Deprecate exception chaining" is clear enough to be advertise as something that can be worked on by volunteers, especially if you already agreed to it.

**Comment by WalterBright** [comment]
@Geod24 yes

**Comment by MoonlightSentinel** [comment]
> @WalterBright : Is it something that can be offloaded to the community ? I'm sure something like "Deprecate exception chaining" is clear enough to be advertise as something that can be worked on by volunteers, especially if you already agreed to it.

A DIP seems like a good start (as it should be required for this change anyway). But i don' t think that this would be good change as it breaks code with little benefit.

Anyway, chaining GC and non-GC exceptions is not the real problem here (given i understood the preceeding comments correctly) but

1. `TraceHandler` still allocates from the GC
2. `Exception`s cannot escape their `catch` block

**Comment by rikkimax** [comment]
> A DIP seems like a good start (as it should be required for this change anyway), but i don' t think that this would be good change as it breaks code with little benefit.

Chaining is not mentioned in the spec see [errors](https://dlang.org/spec/errors.html) and [exception safety](https://dlang.org/articles/exception-safe.html).
As such, it does not need a DIP as far as I understand it, its purely an implementation thing, not a language one.

Based upon what I've read in the past, its an awfully complex concept in implementation that does not serve any real benefit so I'm all for its removal as well.

**Comment by MoonlightSentinel** [comment]
> Chaining is not mentioned in the spec see [errors](https://dlang.org/spec/errors.html) and [exception safety](https://dlang.org/articles/exception-safe.html).
> As such, it does not need a DIP as far as I understand it, its purely an implementation thing, not a language one.

It's mentioned regarding [suppressed exceptions](https://dlang.org/spec/statement.html#try-statement).

**Comment by MoonlightSentinel** [comment]
DIP 1008 forbids exception to  escape their `catch`-Block because it is implemented by inserting an additional `finally`-block which calls `_d_delThrowable`[a]. The proposal states that an exception becomes a reference counted object, so why not implement completely and rewrite references to a throwable into smart pointers instead?

[a].
https://github.com/dlang/dmd/blob/7ae57e4e5ae91cfbdd8b56af068c4335b3a5fca2/src/dmd/statementsem.d#L4332-L4347

Feel free to `destroy()`

**Comment by schveiguy** [comment]
> 1. As @rainers mentioned, dip1008 still allocates with the GC the traceHandler [1]. The class should probably be manually allocated, however this means that we should then track its usage so we can deallocate it.

Just want to mention that this is now fixed in the soon-to-be-released version of the compiler (2.102.0)

https://dlang.org/changelog/2.102.0.html#druntime.nogc-traceinfo

**Pull request closed without merging**
