### PR TITLE
add ty.d

### PR DESCRIPTION
**Pull request by WalterBright**
I.e. translate ty.h to ty.d.

### CODE REVIEW

**Comment by WalterBright** [comment]
rebased

**Comment by MartinNowak** [comment]
This broke gdc, see [Job #5185.3 - dlang/dmd - Travis CI](https://travis-ci.org/dlang/dmd/jobs/150394016#L655).

**Comment by ibuclaw** [comment]
@MartinNowak does this happen with dmd 2.068?

It looks like a old frontend bug to me.

**Comment by MartinNowak** [comment]
> @MartinNowak does this happen with dmd 2.068?
> 
> It looks like a old frontend bug to me.

Yes, apparently a 2.066.1 bug. Why is gdc's LATEST still on 4.9.3 btw?

**Comment by ibuclaw** [comment]
I asked because I think it's using 2.067 frontend with backports from 2.068 tree.

Current master is supporting 2.068, and it is occasionally backported to older branched gcc releases to keep them updated.

**Comment by ibuclaw** [comment]
Does TravisCI build environment support gcc5 yet?  Last time I looked they were only supporting Ubuntu 14.04.

**Comment by wilzbach** [comment]
> Does TravisCI build environment support gcc5 yet? Last time I looked they were only supporting Ubuntu 14.04.

https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
https://github.com/ericniebler/meta/pull/25/files

If I read this right, sth. like below should work:

```
    addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-5
             - gcc-5
```

**Comment by ibuclaw** [comment]
So that is a "no" then.

**Comment by ibuclaw** [comment]
Unless they have 16.04 build environment ready to use, then we still need gdc-4.9

**Comment by MartinNowak** [comment]
> So that is a "no" then.

That's a yes, you simply have to install the packages for those tests.

**Comment by ibuclaw** [comment]
It's the old version of binutils could be problematic.  G++ is only needed if you plan on using gdc for the D2 testsuite run.

**Pull request merged**
