### PR TITLE
astenums: refactor old enums to CapitalCase

### PR DESCRIPTION
**Pull request by ljmf00**
Signed-off-by: Luís Ferreira <contact@lsferreira.net>

---

Discussion starter for renaming these enums to CapitalCase.

### CODE REVIEW

**Comment by ibuclaw** [comment]
I'm not so sure we should be doing grand renaming of things.  It makes history tracking via git blame harder.

**Comment by ljmf00** [comment]
On Sun, 2022-03-13 at 14:43 -0700, Iain Buclaw wrote:
> I'm not so sure we should be doing grand renaming of things. It makes
> history tracking via git blame harder.

I understand the drawbacks of that and I'm fine with this not going
forward, although I still believe the side effects are not a big issue
and this would improve positivily the overall consitency.

We could agree on just a few enums (probably the least used ones). The
heavily used ones can sure cause some fuzziness on `git blame`, so we
can keep those out?

-- 
Sincerely,
Luís Ferreira @ lsferreira.net

**Comment by pbackus** [comment]
This PR mixes together formatting changes (all caps to camel case) and name changes (e.g., "match" to "match level", "pure" to "pure kind"). If, as the commit message suggest, the intent is only to fix the formatting, then the name changes should be left out of this PR.

**Comment by ljmf00** [comment]
> This PR mixes together formatting changes (all caps to camel case)
> and name changes (e.g., "match" to "match level", "pure" to "pure
> kind"). If, as the commit message suggest, the intent is only to fix
> the formatting, then the name changes should be left out of this PR.

I can rename it. Just a suggestion of names.

**Review by RazvanN7 — COMMENTED** [review]
I don't think we should be doing this. As @ibuclaw said, screwing up the history for the sake of consistency in the name of these enums does not worth it. Moreover, you would have to do many more renamings, just look at `Sizeok`, `Baseok`, `MODFlags`, `STC`, `TY`.

**Comment by maxhaton** [comment]
In that case dmd has no style convention.

**Comment by ljmf00** [comment]
> I don't think we should be doing this. As @ibuclaw said, screwing up the history for the sake of consistency in the name of these enums does not worth it. Moreover, you would have to do many more renamings, just look at `Sizeok`, `Baseok`, `MODFlags`, `STC`, `TY`.

There is some that can be seen as abbreviations but yeah, I understand that.

**Comment by ljmf00** [comment]
> In that case dmd has no style convention.

Unfortunately, yes. I'll try to follow the D style.

**Comment by ljmf00** [comment]
Btw, about the history thing. LLVM project introduces NFC prefix to mitigate that. As a thumb rule, NFC stands for Non Functional Change, including formatting, simple refactoring,... You can then distinguish easily from the history those.

**Pull request closed without merging**
