### PR TITLE
Fix Issue 22311 - Slice .length DWARF type

### PR DESCRIPTION
**Pull request by maxhaton**

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by UplinkCoder** [comment]
doesn't dwarf have a tag for ptrsize?

**Comment by ibuclaw** [comment]
> doesn't dwarf have a tag for ptrsize? 

It'll be a typedef tag.

**Review by WalterBright — APPROVED** [review]

**Comment by WalterBright** [comment]
The Azure problems appear unrelated.

**Comment by maxhaton** [comment]
> The Azure problems appear unrelated.

CodeCov are changing their uploader, and are in the process of deprecating the old one (they got burned by some fairly major security problems with their old system). We need to shuffle some CI code around (migrate to their new uploader) then we can continue as normal.

**Pull request merged**
