### PR TITLE
https://issues.dlang.org/show_bug.cgi?id=15465

### PR DESCRIPTION
**Pull request by adamdruppe**

### CODE REVIEW

**Comment by andralex** [comment]
Hm, no tests but I'll take this on karma. Thanks!

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by andralex** [comment]
The autotester is seeing hard tabs, please fix when you wake up.

**Comment by adamdruppe** [comment]
I pushed the tab change hopefully I got it all this time as I really am out of time.

I'd appreciate it if someone else would add a quick test. Since the Ddoc thing is optional and ignored if there no existing tests should fail but a new one should probably be added.

Be aware that while "Ddoc" is stripped off... any following "\n" characters are NOT. With how picky these testers are about whitespace, don't blindly delete the Ddoc line and expect exactly the same results - the \n might make a difference in some test too, so generate a new html file and actually eyeball it.

**Pull request merged**
