### PR TITLE
add backend/cgcv.di

### PR DESCRIPTION
**Pull request by WalterBright**
This is a more-or-less rote translation of `backend/cgcv.h`

### CODE REVIEW

**Comment by WalterBright** [comment]
Also add backend/dt.di, which is split off from `backend.d`. Had to rename `ddmd.backend` to `ddmd.backenddecls` to avoid module name conflict with package. Eventuall, `backend.d` will be removed as its parts are split into various `.di` files.

**Comment by yebblies** [comment]
Why not just make them `.d` files?  Otherwise you've just broken all my scripts that search for `*.d`.

And if backend is now a package, make `backend.d` into `backend/package.d` and then you won't need to change the imports.

**Comment by WalterBright** [comment]
> Why not just make them .d files? Otherwise you've just broken all my scripts that search for *.d.

Because they are interface files, not implementation files!

> And if backend is now a package, make backend.d into backend/package.d and then you won't need to change the imports.

I considered that, and then decided that backend.d should be just eliminated anyway, so why have some intermediate state for it on the road to the dustbin?

I'm not even sure if `backend` is the right name for the package anyway. I have to figure out the right structure so that DMC++ fits in with it, too. But that's all unimportant right now. I just want to move forward on getting all the glue code translated to D, while I twiddle my thumbs because nobody is pulling the work on fixing the safety problems D has.

**Comment by wilzbach** [comment]
>  while I twiddle my thumbs because nobody is pulling the work on fixing the safety problems D has.

Maybe because #5860 still has the "Needs work" label?
Afaict all PRs to Phobos have been merged.

**Comment by yebblies** [comment]
> Because they are interface files, not implementation files!

I've never had anything but problems from hand-maintained di files.  I feel like the header/source split mentality is not helpful in modern D code, and should be avoided.  Do we have clear rules on what can go into a di file?  Do they need to be linked in?

Anyway, I'll merge this if you change them to .d files.

**Comment by WalterBright** [comment]
ok

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by MartinNowak** [comment]
> Do they need to be linked in?

No, they're not linked or compiled.

**Comment by rainers** [comment]
> No, they're not linked or compiled.

In this case they have to be passed on the command line due to the bad folder structure in dmd that doesn't match package names. Is this going to change? It's vital for using the frontend as a library.

**Pull request merged**
