### PR TITLE
Cleanup dcast.d

### PR DESCRIPTION
**Pull request by 9rnsr**

### CODE REVIEW

**Comment by 9rnsr** [comment]
This front-end cleanup is necessary for:

https://trello.com/c/ihKhGeiu/115-reg2-031-forward-reference-to-inferred-return-type-of-function-call-when-using-auto-return-type

**Comment by yebblies** [comment]
What are you (re-)aligning the comments to?  I don't see the point of this when the comments aren't on consecutive lines.  Some of these changes (like moving that function) seem to have very little benefit.

**Comment by 9rnsr** [comment]
@yebblies As I commented in commit log, the `castTo` visitors for `AddrExp`, `SymOffExp` and `DelegateExp` are strongly related (they are handling ambiguous function addresses). So placing them in near positions is good.

**Comment by WalterBright** [comment]
This is ok with me, except for the repositioning of AddrExp.castTo. That one is just churn. I understand that you wish to move it nearer where it is used, but if we continue down that route the whole source code base will be upended, and my usual nightmare of making it impossible to compare code from one release to the next will be realized.

When doing refactorings, please please keep in mind the affect on diffs.

**Comment by 9rnsr** [comment]
Diff? It's not a matter today. When we release a dmd version, we'll forget its previous versions. The maintained release versions and development versions are managed in two distinct breanches (`master` and `stable`). If we need to trace some changes, we can use git blame. There's no serious issue.

Ultimately I believe program source code should have no meaningless matters. In this case, `implicitConvTo` and `castTo` do very similar things. Therefore so, their visitors' methods should be declared with identical order, if there's no other special thing.  From the view, the inconsistent positioning of `CastTo.visit(AddrExp e)` is just not good.

Why we keep code format style? Because consistent style will help to focus on the code logic. Why I recommend to reorder `AddrExp.castTo`? Because increasing similarity will highlight the logic difference between `implicitConvTo` and `castTo`.

Indeed, it's a little artistic sense. However, I think and believe that making code more meaningfulness will increase code readability and maintainability.

**Comment by 9rnsr** [comment]
Removed line space changes and repositioning.

**Comment by 9rnsr** [comment]
Ping to @yebblies and @WalterBright .

**Comment by yebblies** [comment]
Auto-merge toggled on

**Comment by 9rnsr** [comment]
@yebblies Thanks!

**Pull request merged**
