### PR TITLE
Add src-symlink ddmd

### PR DESCRIPTION
**Pull request by nordlow**
Enables DCD (D Completion Daemon) and alikes to find module files from imports.

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
I'd much rather seen the file moved. And Walter agreed to it.

**Comment by nordlow** [comment]
Should I fix?

**Comment by WalterBright** [comment]
I don't understand the issue here?

**Comment by nordlow** [comment]
The imports in the DMD source (`such as ddmd.access`) does not match the directory structure (`src/access.o`). This confuses completion programs such as DCD. Solution is to either create a symlink `ddmd` pointing to `src` or move `src` to `ddmd`.

**Comment by WalterBright** [comment]
> It also makes compiling DMD in any other way than all modules at once impossible.

I know. It hearkens back to when @yebblies had it in a separate location to do the conversion. I've been meaning to change it to match the actual file layout.

**Comment by nordlow** [comment]
Thanks.

**Comment by CyberShadow** [comment]
Please, let's remove the symlink. Symlinks are not supported by Git on Windows on any way, so it'll just be a plain file there. This will create yet another platform-specific difference in building DMD. It also broke everything that uses Digger, right now notably website auto-deploy, because it can't deal with symlinks, and I'd rather not spend time working on symlink support for such a weak proposal.

**Comment by MartinNowak** [comment]
Mmh, renaming src->ddmd is not a solution either, b/c it will break about any build script.
Not being able to build separate components of dmd separately is quite a problem though.
Any other suggestions?

**Comment by mathias-lang-sociomantic** [comment]
The suggestion was `src/ddmd/file.d` (e.g. nest them inside `ddmd` directory).

**Comment by CyberShadow** [comment]
> Any other suggestions?

Well...

- Create the ddmd symlink from the makefile / build script using ln / mklink
- Rename src to ddmd, but leave a stub src/posix.mak and src/win32.mak that forwards arguments to the ddmd/ one
- Move source files one directory level lower (src/ddmd/*.d)

**Comment by MartinNowak** [comment]
src/ddmd sounds best, let me check whether git can preserve existing PRs.

**Comment by MartinNowak** [comment]
Yes, merging PRs against moved sources would work, still going to cause some headaches.
In any case we should preserve `make -f posix.mak` and `make -C src -f posix.mak`, and the output target `src/ddmd`, b/c many build scripts rely on that.

**Comment by CyberShadow** [comment]
> It also broke everything that uses Digger, right now notably website auto-deploy, because it can't deal with symlinks, and I'd rather not spend time working on symlink support for such a weak proposal.

Never mind that part, I decided to fix it anyway. I still think we should avoid introducing more platform-specific stuff into the build process, though.

**Comment by WalterBright** [comment]
Don't move the sources. Just remove all the `ddmd.` prefixes from the import declarations.

**Comment by CyberShadow** [comment]
> Don't move the sources. Just remove all the ddmd. prefixes from the import declarations.

I think that would make it more difficult to use parts of DMD as a library.

**Pull request merged**
