### PR TITLE
[enh] Issue 10848 - Compiler should always try to inlining a direct lambda call

### PR DESCRIPTION
**Pull request by 9rnsr**
http://d.puremagic.com/issues/show_bug.cgi?id=10848

I'd like to propose an additional spec for the direct lambda call inlining.

### CODE REVIEW

**Comment by andralex** [comment]
This has been languishing for a while. Does it have a future?

**Comment by WalterBright** [comment]
There are cases where one does not want inlining:

1. it makes using a debugger harder
2. it won't have a separate entry in the performance profiler
3. outlining such code in the 'slow' data path means it doesn't take registers away from the fast path

So it is not an unequivocal "should always inline these".

**Comment by JinShil** [comment]
It looks like there are too many objections to this PR.  It doesn't look like it has a future.  I'm suggesting it be closed.  Any objections?

**Comment by WalterBright** [comment]
The idea has much merit. This implementation, however, has problems. It inlines the function during semantic analysis, whereas other inlining is done after all semantic analysis is complete. This has lead to some hacky code being added to change how side effects are computed.

These sorts of things often lead to further trouble.

A better solution (as suggested by Manu in the bug report) would be to simply mark lambdas as "always inline if possible" and then let the normal inlining code work on it. (Although implementing such a flag would require more changes to the compiler, at least they would not be risky changes.)

So, I agree with @JinShil and am closing this.

**Comment by ibuclaw** [comment]
I only had objections to one of the commits. The others might be of use, but will need to have another close look at them later.

**Pull request closed without merging**
