### PR TITLE
fix Issue 17512 - [REG 2.073] [DIP1000] Error on bad interplay of 'au…

### PR DESCRIPTION
**Pull request by WalterBright**
…to ref' and 'return' attribute deduction

### CODE REVIEW

**Comment by wilzbach** [comment]
(rebased to stable)

**Review by wilzbach — APPROVED** [review]
LGTM though it feels like this is a bit of a  workaround against the fact that `return` is added somewhere in DMD before.

**Comment by wilzbach** [comment]
DAutoTest needs https://github.com/dlang/dlang.org/pull/2270

**Comment by WalterBright** [comment]
oh gawd, not again

**Comment by WalterBright** [comment]
Abandoning this mess.

**Comment by wilzbach** [comment]
> oh gawd, not again

Did you force-push

**Comment by WalterBright** [comment]
I redid it as https://github.com/dlang/dmd/pull/8006

**Comment by wilzbach** [comment]
> Abandoning this mess.

Just fixed it for you. Just do a `git pull` if other people made changes to your PR.
In this case it was just `git rebase --onto upstream/stable upstream/master`

**Comment by WalterBright** [comment]
Thanks! In that case, I'll turn on automerge before any more changes bork it again.

**Comment by wilzbach** [comment]
> before any more changes bork it again.

For the future, if someone else force-pushed onto your branch, you need to reset your local branch to it before adding changes as otherwise the previous work will be overwritten.
In short: there's e.g. `git pull -f` to reset you branch to the remote state.

**Comment by WalterBright** [comment]
The failing win64 test looks spurious, I deprecated the test, but it won't rerun it.

**Comment by rainers** [comment]
> The failing win64 test looks spurious, I deprecated the test, but it won't rerun it.

Looks like @braddr is in the middle of updating the build servers. It is trying to compile with VC2010.

**Pull request merged**
