### PR TITLE
fix Issue 16080 - [REG2.071.0] Internal error: backend\cgobj.c 3406 w…

### PR DESCRIPTION
**Pull request by WalterBright**
…hen building static library

### CODE REVIEW

**Comment by WalterBright** [comment]
This is a serious bug since it can cause corrupt binaries on Win32.

**Comment by andralex** [comment]
thx!

**Comment by andralex** [comment]
Auto-merge toggled on

**Comment by s-ludwig** [comment]
Shouldn't this (also) go to stable?

**Comment by MartinNowak** [comment]
Come, the rule is as simple as that.
__Bugfixes always go into stable__

**Comment by MartinNowak** [comment]
Thx for the fix!

**Comment by WalterBright** [comment]
sorry, I forgot

**Pull request merged**
