### PR TITLE
fix issue 19402 - bitshift with long shift amount results in int instead of long

### PR DESCRIPTION
**Pull request by ghost**
The type of result of the ShiftExpressions didn't follow the specs.
This change requires https://github.com/dlang/phobos/pull/6863 and possibly fixes in the user projects.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Can we somehow deprecate the existing behavior?

**Comment by Basile-z** [comment]
I've managed to add a deprecation message, which was not a piece of cake due to the hidden cast, and with the phobos PR this PR is virtually green so you can review now.

**Comment by WalterBright** [comment]
The compiler is behaving correctly, the spec is wrong. See my comment on bugzilla. I'll go fix the spec. Fortunately, since the compiler is already correct, we don't have to do any deprecations or break any existing code :-)

**Comment by Basile-z** [comment]
Yes I have seen. Well...

**Pull request closed without merging**
