### PR TITLE
Fix issue 22999 - no switch fallthrough error with multi-valued case

### PR DESCRIPTION
**Pull request by dkorpel**
Revert the incorrect fix of https://github.com/dlang/dmd/pull/1673 and fix `hasCode()` instead to account for `CaseStatement` and `DefaultStatement`.

### CODE REVIEW

**Comment by dkorpel** [comment]
Maybe this should target master since it broke Phobos (https://github.com/dlang/phobos/pull/8429).

**Comment by RazvanN7** [comment]
yes, let's target master please. The regression is old anyway.

**Comment by dkorpel** [comment]
D-YAML broke too, I'm thinking of making it a deprecation.

**Comment by RazvanN7** [comment]
@dkorpel This still needs a changelog entry

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
