### PR TITLE
dsymbol.d: convert to D delegates

### PR DESCRIPTION
**Pull request by WalterBright**

### CODE REVIEW

**Comment by yebblies** [comment]
Please use `opApply` instead.

**Comment by WalterBright** [comment]
one thing at a time. BTW, opApply was a mistake. I'd like to (eventually) move it to a template with an alias parameter. Don't pull this yet, anyway, until I remove the WIP.

I like to do these sorts of things a bit at a time, rather than the grand mal seizure method, because it's easier to track down breakage.

**Comment by yebblies** [comment]
Mistake or not, opApply is here to stay, and works in 2.067.

I'm certainly not going to pull this as is, at the very least one of these _foreach methods should call the other.

**Comment by WalterBright** [comment]
It is a WIP. Once it passes, I'll remove the C++ version and the WIP in the subject.

**Comment by yebblies** [comment]
If you remove the C++ version it will be unusable from the glue layer.

**Comment by WalterBright** [comment]
This one isn't used by the glue layer.

**Comment by yebblies** [comment]
Have you checked GDC and LDC?  We are going to need an official policy on what exactly is exposed over the C++ interface.

**Comment by WalterBright** [comment]
> Have you checked GDC and LDC?

No.

**Comment by luismarques** [comment]
@WalterBright how do you check for any performance regressions in these refactorings? I was looking into contributing one change, but I'm unsure about the performance consequences.

**Comment by WalterBright** [comment]
Updated: converted the next use of _foreach to using D style.

**Comment by WalterBright** [comment]
@klickverbot This is purely a refactoring to use D nested functions rather than the ugly C++ fake nested functions. @luismarques it should produce essentially identical code.

**Comment by WalterBright** [comment]
Updated to include use of `ScopeDsymbol._foreach` from `traits.d`.

**Comment by WalterBright** [comment]
Updated to remove C++ version.

**Comment by luismarques** [comment]
@WalterBright OK, but if you were making some refactoring where it could impact performance (perhaps unexpectedly), how would you go about detecting that? I mean, you do advocate using a profiler all the time, I'm just asking what is your routine with regards to dmd :o)

**Comment by yebblies** [comment]
C++ headers will probably need updating.

**Comment by WalterBright** [comment]
> C++ headers will probably need updating.

I couldn't find `_foreach` in any .h files.

**Comment by yebblies** [comment]
https://github.com/D-Programming-Language/dmd/blob/master/src/dsymbol.h#L309

**Comment by WalterBright** [comment]
That's `foreach`, not `_foreach`. Note leading _. Calling it from C++ will never work :-)

**Comment by yebblies** [comment]
Yeah, the leading underscore was added by magicport.

**Comment by yebblies** [comment]
That delegate should be scope, right?

**Comment by WalterBright** [comment]
> That delegate should be scope, right?

One step at a time. All the functions need to be reviewed for adding all the various attributes.

**Comment by yebblies** [comment]
So... does it cause a (leaked) GC allocation?  Was that intentional?

**Comment by WalterBright** [comment]
yah, you're right. But I can't fix it till Friday. (storm took out my internet)

**Comment by WalterBright** [comment]
Fixed, btw. My internet is back (Comcast rigged up a temporary patch).

**Comment by WalterBright** [comment]
Why is this not being pulled?

**Comment by 9rnsr** [comment]
The commit message still contains "WIP"... but it seems ready to go.

**Comment by 9rnsr** [comment]
Auto-merge toggled on

**Comment by WalterBright** [comment]
Thanks!

**Pull request merged**
